### ISSUE TITLE
Custom fields + attributes of goods in the archive product card

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#10]
Good afternoon, you often need the functionality to output arbitrary fields and attributes of goods in the product card of the store archive, it would be great if you could do this in the Jet Woo Builder plugin when building the product archive card. As far as I know, not a single plugin addition to the Elementor is able to.

/*Оригинал на русском*/
Добрый день, часто нужен функционал вывода произвольных полей и атрибутов товара в карточке товара архива магазина, было бы здорово если вы смогли это сделать в плагине Jet Woo Builder при построении карточки товара архива. Насколько я знаю, еще ни один плагин дополнение к Elementor этого не умеет.

**Comment by SashkoWooTeam** [comment]
Set Elementor Default in render method option (http://prntscr.com/njsvo4) and use dynamic widgets from Jet Engine for display custom data in archive product template.
