### ISSUE TITLE
Woocommerce and Woocommerce My Account Page User Data

### ISSUE THREAD

**Issue by jazir5** [Crocoblock/suggestions#1002]
Hi, i’m trying to build a custom My Account page with Woocommerce and cannot find a single Elementor addon which will let me dynamically and easily populate widgets with Woocommerce data associated with the user. This includes both Dynamic Content for Elementor and JetEngine.

What i want to do is be able to query/dynamically pull in any woocommerce field on any widget type. I’ll list a few use case scenarios which as far as i can tell right now, are impossible to implement with the current limitations on Elementor Dynamic Content that your plugin could solve.

Scenario 1. Importing Woocommerce Product photos into the new Elementor Pro Gallery widget.
https://imgur.com/a/igEJcFE

I cannot dynamically populate the Gallery Widget with the Featured Image of a product. I get the tag to pull in the product gallery(meaning the non-featured product images), but that’s it. This makes it effectively worthless for displaying product images. This is a big issue as every other Woocommerce Gallery widget is gimped in some way, they all have major functionality/design shortfalls and are pretty glitchy. Being able to do everything with Product Images from the stock Gallery widget would definitely be the ideal solution, but i can’t figure out how to populate it with the featured image as that isn’t an option.

I would also like a separate dynamic tag to specifically pull in each product variation’s image gallery, as each variation will also have a separate gallery which needs a separate dynamic query.

Scenario 2. Creating the Woocommerce My Account page and dynamically updating User Data via the Front-end based on user submitted Data(most likely in concert with JetEngine
I cannot dynamically query Woocommerce Data with JetEngine as it does not seem like it can update those user fields. I want to have Dynamic tags for all of the Woocommerce endpoints such as Payment Info, Addresses saved, Order Info, Order Status. Any fields that need to be updated by the user would hook into the JetEngine form widget which has the functionality to update user account data from the frontend when submitted. I want to use JetEngine to completely customize the My Account page, which is simply undoable at the moment as it seemingly cannot modify woocommerce fields

The end result that i would like would look like this mockup: https://imgur.com/a/HEMsX1n

As you can see, the data is queried dynamically and populated by the user’s account data, and sectioned off in their own boxes so that it appears all at once in the dashboard. Each section here would be editable via a JetEngine frontend form.

Scenario 3. Dynamic Product ID in any field
JetProductGallery is a pretty decent Gallery widget which is utterly kneecapped as it has a field to manually enter product ID and does not allow it to be queried dynamically as far as i can tell. A Dynamic tag which automatically populates the field via the current product ID of the product being viewed would solve the issue.

Scenario 4. Woocommerce Account Summary quick stats

I want to create a quick stats dashboard account summary tab for users that displays when they click "My Account" like so: https://imgur.com/a/LJuguFf. Being able to easily pull in any data regarding a user accounts woocommerce data would make this significantly easier.

Scenario 5. Updating User Woocommerce data from the Front-end via a form

There is currently no easy plug and play way for a user to update their information from the front-end. All Elementor woocommerce addons fall short in functionality, and i've downloaded every single addon pack available for Elementor that contains Woocommerce integration. They all have very obvious gaps in what visual features they can control. Widgets specifically designed for Woocommerce don't seem to get the attention and polish other Elementor widgets do. 

So to that effect, being able to use the Elementor default Form Widget linked to Dynamic tags that auto-populate Woocommerce user info into each relevant field (For instance, a form for shipping address would be prepopulated with the previous shipping address entered by the user. Ex: https://imgur.com/a/9jEdrKg). This way i can style the form exactly as desired without the limitations of the poorly coded woocommerce specific Address widgets. One limitation of them is that you cant have an empty form display by default, it will just show text with an add new button if no address currently exists, which looks janky.

I want to be able to allow users to update their Woocommerce based data via the front-end using normal Elementor widgets which sync back via dynamic tags. This is currently doable via JetEngine and it's front-end form submission feature, but you do not have an easily accessible and labeled set of meta_keys for woocommerce, nor are the form fields editable within elementor itself, they have to be assigned from the backend.

**Comment by HermesMacedo** [comment]
Nice, any news Crocoblock? I need same

**Comment by jazir5** [comment]
Another request that JetEngine is uniquely positioned to solve.

Scenario 6:

I want to a create a tab in the Account page for user privacy settings. I simply cannot find any solution which allows me to create a user privacy panel which dynamically populates options per user account, which the user can manage in the front-end, preferably via toggles or checkboxes. 

I want them to be able to easily unsubscribe/opt-out from the newsletter, be able to decide whether to enable/disable cookies, opt-out of Analytics tracking, be able to launch an export of their user data on button click. 

It should be simple to create a preference panel for users, but there seemingly is not available solution for this.

**Comment by UraraReika** [comment]
In closest release of JetWooBuilder you will be able to create default pages, such as My Account, Cart, Checkout and Thank you page and this solve some of your needs. But for complete all the scenarios we need more time.

**Comment by UraraReika** [comment]
Hello @jazir5!

> Scenario 1. Importing WooCommerce Product photos into the new Elementor Pro Gallery widget.

This scenario not about our product at all, and such kind of dynamic tag is very specific, not everyone need it. Most people stay satisfied used standard widgets for displaying product gallery. In your case to use product gallery with featured image you can add your custom dynamic tag in your child theme.

> Scenario 2. Creating the Woocommerce My Account page and dynamically updating User Data via the Front-end based on user submitted Data(most likely in concert with JetEngine)

Most likely all data that you want to change stored as metadata, in this case you can easily get it and change in with the help of Jet Engine Forms functionality.

> Scenario 3. Dynamic Product ID in any field

Field product id created to use widgets whatever you want to use it. But if you ignore this field and leave it empty than widget grab the current product ID if you mean dynamic tag functionality it will be added in next releases.

>Scenario 4. Woocommerce Account Summary quick stats

You already can achieve some kind of this look and functionality and next release of JetWooBuilder makes it even better.

>Scenario 5. Updating User Woocommerce data from the Front-end via a form

As i said answering on scenario 2 if field store their data in metabox you can control it with JetEngine. But first you should get all correct in the backend. Although few future updates will give you opportunity to style WooCommerce endpoints templates and separate parts of it including forms.

Scenario 6 is very complex, something you can make right now with the help of option, other things can be make with the help of webhooks but in this case you should write a bunch of code lines.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
