### ISSUE TITLE
JetAppointments - Providers availability (working hours)

### ISSUE THREAD

**Issue by noob-webmaster** [Crocoblock/suggestions#1005]
Hi! 
In Jet Appointment think about set Providers working hours. The plugin assumes all Providers works for whole time.
Anyway, great job, keep it up ! :)

**Comment by dtyllack** [comment]
Yes please! It is absolutely necessary that individual working hours can be set for the individual Service Providers. Not every Business is a restaurant with fixed working hours, like in your YouTube video.
For example: I am trying to set up a page where people can book appointments with different freelancers. There is no way on earth they could all always work during the same hours.
Hope this gets implemented soon! Thank you

**Comment by dissipatio** [comment]
Yes, please! It will be great to have the working hours and availability by week day or calendar. Thank you!

P.S. I like very much jetAppointment, great job!

**Comment by bennybersier** [comment]
I agree with this and was about to create a suggestion. 
not all services and providers are available on all days in many cases. So it would be great to have such an option in the future.
Thank you

**Comment by planetapyme** [comment]
I totally agree, we need this implementation as soon as possible. Thanks Crocoblock!

**Comment by MakhonkoDenis** [comment]
Hi guys,
This feature appeared in version 1.2.2
