### ISSUE TITLE
JetProductGallery with additional images for variations

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#1006]
The JetProductGallery plugin does not have integration with additional images for variations, the main ones being https://wordpress.org/plugins/woo-variation-gallery/ and https://woocommerce.com/products/woocommerce-additional-variation-images/

**Comment by UraraReika** [comment]
Hi @marcofrasson! We have analyzed your request and are in a hurry to inform you that the widgets of our plugin do not have the standard markup used by the plugins you provided to implement such functionality.

To make it compatible with plugins of this type, we need to make a huge amount of work with restructuring, which will take a lot of time.

At the moment, our team has higher priorities over other tasks, but in the future we will definitely return to this issue.
