### ISSUE TITLE
Dynamic Field widget not working(fetching value) from custom field created by Jetengine Meta Boxes for User Profile in Elementor author archive template

### ISSUE THREAD

**Issue by realstephenzhao** [Crocoblock/suggestions#1008]
**Describe the bug**
Dynamic Field widget not fetching value from custom fields created by Jetengine Meta Boxes in wordpress user profile.

**To Reproduce**
1. Go to 'Jetengine', select "Meta Boxes"
2. Add new Meta Box for 'User'
3. Go to "Users", Click "All Users" then edit or click "Your Profile"
4. Type some dummy data, update
5. Edit author archive template using Elementor
6. Add Dynamic Field or Dynamic Link widget, not working, no data returns.

**Expected behavior**
Should return data, but it didn't.

**Screenshots**
See:

![](https://i.imgur.com/3VwYOsL.png)

![](https://i.imgur.com/oh2ket0.png)

![](https://i.imgur.com/CGjsSNv.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox Developer Edition
 - Version 75.0 b1

**Comment by kaskad88** [comment]
Fix for the next version.
Thanks for your report!

**Comment by giacozama** [comment]
I still get the same error with the same conditions. plugins are all up to date. the default values appear on the front end only by "updating" the user from wordpress' admin backoffice

**Comment by kaskad88** [comment]
@giacozama  I tried to reproduce your issue and looks like all works fine
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
