### ISSUE TITLE
Jet Engine add type field Number

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1009]
Hello, consider adding the "Number" field type to arbitrary Jet Engine fields - https://prnt.sc/rgn8l4
Thanks!

Здравствуйте, рассмотрите возможность добавления типа поля "Number" в произвольных полях Jet Engine - https://prnt.sc/rgn8l4
Спасибо!

**Comment by realstephenzhao** [comment]
I vote for **Conditional Logic** to meta fields like ACF.

**Comment by HobbyAlchemist** [comment]
+1 Conditional Logic

**Comment by MBarns** [comment]
I vote for Conditional Logic to meta fields as well!! This is the last missing puzzle piece for us in using Jet engine. Once we have that we can implement everything we want. Much appreciated if added to its functionality!

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0
