### ISSUE TITLE
Jetengine datetime picker(custom field) not working in Firefox browser

### ISSUE THREAD

**Issue by realstephenzhao** [Crocoblock/suggestions#1010]
**Describe the bug**
Datetime picker created by Jetengine Meta Boxes not working in Firefox browser

**To Reproduce**
1. Using Firefox to login your wordpress admin dashboard
2.  Create a datetime custom field in Jetengine Meta Boxes for any Post Type
3. Add new post under this Post Type
4. Scroll down to datetime picker you created above
5. Not working at all no matter how you hover or click, only a blank line there

**Expected behavior**
This datetime picker should be campatible to Firefox

**Screenshots**
Only blank line appeared, so I don't upload screenshots here.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition  75.0 b3
 - Version: Lastest

**Additional context**
It can work in Chrome Browser though.

**Comment by Floydtm** [comment]
@realstephenzhao, hi! http://prntscr.com/rh9fi4 Firefox browser does not support this
