### ISSUE TITLE
Dynamic Background Bug

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1011]
Hello, this bug has been contacting support for quite some time, and they gave me CSS code as a solution that helped me, but I would like to solve this problem without using custom code.
The essence of the problem, if you use a dynamic background from arbitrary fields of the Jet Engine, then the "Do not repeat" option does not work https://prnt.sc/rgnkc6
And the background still repeats - https://prnt.sc/rgnlj5

I contacted Elementor in support, they checked everything and said that you need to contact you.

Here is the code I was given in your support

.elementor-3521 .elementor-element.elementor-element-659c85a4> .elementor-background-overlay {
        background-repeat: no-repeat! important;
}

Здравствуйте, этот баг уже довольно давно, обращался в поддержку и в качестве решения дали CSS код который помог мне, но хотелось бы решить эту проблему без использования кастомного кода.

Суть проблемы, если использовать динамический фон из произвольных полей Jet Engine, то опция "Не повторять" не срабатывает https://prnt.sc/rgnkc6 
И фон всё равно повторяется - https://prnt.sc/rgnlj5

Обращался в поддержку Elementor, они всё проверили и сказали что нужно обратиться именно к вам.

Вот код который мне давали в вашей поддержке

.elementor-3521 .elementor-element.elementor-element-659c85a4 > .elementor-background-overlay {
        background-repeat: no-repeat!important;
}

**Comment by kaskad88** [comment]
Здравствуйте, @stasonua0, обновитесь до последней версии JeEngine и сделайте Regenerate CSS ( Elementor->Tools->General ), если проблема останется обратитесь ещё раз в нашу службу поддержки указав, что я Вас направил и прикрепите ссылки к этому ишью. Спасибо.
