### ISSUE TITLE
OSM Open Street Map Widget

### ISSUE THREAD

**Issue by pedrostein** [Crocoblock/suggestions#1012]
It's really getting harder and harder to find something that could be missing in crocoblocks :-) 

But I just noticed, that Open Street Map isn't supported (yet) 

**Add an example of where this feature is already implemented. **
https://elementpack.pro/demo/element/open-street-map/
https://youtu.be/DCQ5g7yleyk

I think this would also nicely complement Jet Engine, Jet Booking, Jet Appointment and Jet Elements
Specially as Jet Engine Custom Fields could be used to provide the needed location values. to provide dynamic maps.

**Comment by Floydtm** [comment]
@pedrostein, hi! Soon we will release an update for jetengine in which there will be something similar http://prntscr.com/rh9c4w stay tuned

**Comment by pedrostein** [comment]
@Floydtm - this sounds good:-)
The screenshot looks great - but will it also support Open Street Map?

**Comment by Pierrezoomkite** [comment]
UP, i would like to create a directory listing with crocoblock but google API is expensive. Can you add this possibility in next update ? Thanks !
