### ISSUE TITLE
More than four columns available in posts grid

### ISSUE THREAD

**Issue by lingvemulo** [Crocoblock/suggestions#1014]
Hi - I like the plugin but ultimately am having to request a refund as I didn't know I'd be limited to four columns in the post grid. The option to have more (up to 8 at least) would be great.

**Comment by kaskad88** [comment]
Hi, @lingvemulo. Please indicate the exact name of the widget and from which it is a plugin

**Comment by lingvemulo** [comment]
Hi - sorry, it's Jetblog for Elementor.

**Comment by lingvemulo** [comment]
Sorry, didn't mean to close.

**Comment by kaskad88** [comment]
Added for the next version

**Comment by lingvemulo** [comment]
Great!!! I won't ask for a refund then. :-)
