### ISSUE TITLE
JetSmartFilter Supports ACF checkbox custom field

### ISSUE THREAD

**Issue by 1101blueli** [Crocoblock/suggestions#1016]
Hello, is it possible for the SmartFilter to support the ACF meta custom filed?

thanks

**Comment by realstephenzhao** [comment]
It supports ACF, but not fulled supported as far as I know.

**Comment by Floydtm** [comment]
@1101blueli,hi! Please specify what exactly does not work for you

**Comment by 1101blueli** [comment]
Hello, I have a ACF checkbox field for my product Trade Option (Face to face, Store Pickup, Mail or courier)
and  have a template with a product grid by JetEngine Listing Grid widget, with SmartFilter
But The Filter not working with the ACF checkbox field that I created for the product.

You may take a look at my testing site.
https://bird.blueli-testing.club/

![Screenshot 2020-03-18 at 5 35 15 PM](https://user-images.githubusercontent.com/55223003/76946417-f820a800-693e-11ea-85f8-f9e6dae695bc.png)
![Screenshot 2020-03-15 at 1 45 05 PM-1](https://user-images.githubusercontent.com/55223003/76946429-fbb42f00-693e-11ea-875f-bc8b6862174e.png)
![Screenshot 2020-03-15 at 1 44 49 PM-1](https://user-images.githubusercontent.com/55223003/76946432-fc4cc580-693e-11ea-83eb-e470c285a0c4.png)

**Comment by Floydtm** [comment]
@1101blueli, I understood you. Unfortunately, such a case will not work. While there are difficulties with the operation of the filter and ACF plugin. You can do it another way. Do it through taxonomy. You can also do it all with the jetengine plugin. If you don’t have one then do it with the help of taxonomies using free plugins Pods, CPT UI and others. http://prntscr.com/rj4vnh http://prntscr.com/rj4vxw http://prntscr.com/rj4w6m
