### ISSUE TITLE
Add to Jet Fields Dynamic Colors Elementor

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1018]
Hello, I ask you to consider adding to the new Elementor function the output of colors from arbitrary fields of the Jet Engine and options pages - https://prnt.sc/rib8pd

Здравствуйте, прошу рассмотреть возможность добавить в новую функцию Elementor выводить цвета из произвольных полей Jet Engine и страницы опций - https://prnt.sc/rib8pd

**Comment by kaskad88** [comment]
Added for the next version ( 2.3.0 ).
Thanks for your report!
