### ISSUE TITLE
customized product badges

### ISSUE THREAD

**Issue by RoyPi** [Crocoblock/suggestions#1019]
Hey,
I think it is very important to give the option of placing custom badges when setting up a products online store using jet product grid, even when there is no promotion on the same product. 
For example, if I want to write: The best price. Because the price of the product is the best but it is not on sale.
A company that gives you the option to do this is YITH WooCommerce Badge Management.
I tried to use this plugin but it fails to display the badge on the jet product grid.

TIA

**Comment by UraraReika** [comment]
Hi @RoyPi !

From the core of plugin there is no possibility to put custom badges on the global product widgets. But we provide filters in our function which processes product thumbnail and with the help of it you can add whatever you want badge not only from YITH WooCommerce Badge Management.

Here is the code you need to put in your child theme: 
```
add_filter( 'jet-woo-builder/template-functions/product-thumbnail', '__your_prefix_add_yith_badge', 10, 1 );

function __your_prefix_add_yith_badge( $html ) {
	global $post;

	$product_id = $post->ID;
	$product    = wc_get_product( $product_id );

	if ( $product ) {
		$bm_meta     = yit_get_prop( $product, '_yith_wcbm_product_meta', true );
		$id_badge    = ( isset( $bm_meta['id_badge'] ) ) ? $bm_meta['id_badge'] : '';
		$badges_html = yith_wcbm_get_badge( $id_badge, $product_id );

		if ( ! empty( $badges_html ) ) {
			$html .= $badges_html;
		}
	}

	return $html;
}
```
