### ISSUE TITLE
JetSmartFilter indexer auto reindex?

### ISSUE THREAD

**Issue by 1101blueli** [Crocoblock/suggestions#1021]
Hello,
I am building a multi vendor site, and planning to use JetSmartFilter indexer for the filter. Because the vendors do not have access to the admin dashboard. So when they have a product created. There will have to be someone to click the index filter button. 
I am wondering can it to have any options for the indexer atomically renew like every 2hours or something?

thanks

**Comment by Floydtm** [comment]
@1101blueli, hi. There is no such functionality in the plugin settings. I think you should study this [plugin](https://wordpress.org/plugins/wp-crontrol/) or similar.

**Comment by marcofrasson** [comment]
I also need the index to be automatic, but I didn't understand how to use WP Cron for this. What are the guidelines for creating a Cron for this?

**Comment by mcj777** [comment]
+1

**Comment by marcofrasson** [comment]
Any update for this?

**Comment by createque** [comment]
Yeah, I just found this issue too.
So, after each data submit you must press INDEXER button in backend to all filter working properelly.
It's very impractical or even paralysis of correct data display on websites, especially when it comes to the advert page and other data entered by users via frontend forms...
Huge problem. Very Very huge problem...
Any update for this please?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks. install this [plugin](https://wordpress.org/plugins/wp-crontrol/) and add PHP Cron Event https://prnt.sc/t2t214
