### ISSUE TITLE
Product variations on the catalog page

### ISSUE THREAD

**Issue by Olxa** [Crocoblock/suggestions#1022]
Hello.
Could you add a selection of product options on the catalog page?
This is necessary in some cases, for example, on a website for food delivery and the like.
If you use third-party plugins for these purposes, then you will not be able to use WooBuilder
![пицца](https://user-images.githubusercontent.com/24510457/77154085-0c35e800-6aac-11ea-9aaa-266e3346cb17.jpg)

![вариации](https://user-images.githubusercontent.com/24510457/77153913-c4af5c00-6aab-11ea-8e45-c4f7eda85001.jpg)

**Comment by mcj777** [comment]
+1
I support! A very necessary option when working with variable goods!
-------
Поддерживаю! Очень нужная опция при работе с вариативными товарами!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. Link this issue with #361
