### ISSUE TITLE
Adding custom tabs to the product page

### ISSUE THREAD

**Issue by Olxa** [Crocoblock/suggestions#1025]
Hello.
You can provide the ability to add your own tabs on a single product page (for example, delivery information).

I wanted to try to do this through templates (create a template containing default information and add my information), but when creating a template there is no access to the widgets of a single product

![дефолтный таб](https://user-images.githubusercontent.com/24510457/77190417-42925800-6aea-11ea-90b0-1511e397f141.jpg)
![собственные табы](https://user-images.githubusercontent.com/24510457/77190422-445c1b80-6aea-11ea-920f-128a4b14c5b6.jpg)

__________________________________________________________________________________________________________
Здравствуйте.
Можете предусмотреть возможность добавлять собственные табы на одиночной странице продукта (к примеру информацию о доставке)?
Хотела попробовать сделать это через шаблоны (создать шаблон содержащий дефолтную информацию: описание, характеристики и добавить свою информацию о доставке), но при создании шаблона нет доступа к виджетам одиночного продукта (т.е. создать отдельно шаблон содержащий характеристики продукта не представляется возможным)

**Comment by UraraReika** [comment]
Hello sorry for the long delay.

You can create separate section in single product template and save this section then use it wherever you want.

Thank you for understanding !
