### ISSUE TITLE
Format Date Jet Engine Forms

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1034]
Hello, at the moment when receiving emails to Jet Forms, the date in this format is https://prnt.sc/rlvpoh

Very often this format does not suit customers. Please consider adding the functionality to change the date format

Здравствуйте, на данный момент при получении писем на Email с Jet Forms дата в таком формате - https://prnt.sc/rlvpoh

Очень часто этот формат не устраивает заказчиков. Прошу рассмотреть возможность добавления функционала изменения формата дат

**Comment by MjHead** [comment]
Hi! You can use format_date filter for %date% field macros in notification settings. For example - %date|format_date%. This filter uses default date format set in WP settings.

------

Вы можете использовать фильтр format_date для макроса поля с датой в настройках письма. Например - %date|format_date%. Этот фильтр отформатирует дату в тот вид, который задан в настройках ВП
