### ISSUE TITLE
Process/steps from ThePlusAddons

### ISSUE THREAD

**Issue by itismebrian** [Crocoblock/suggestions#1039]
Hello!

I think a widget like https://elementor.theplusaddons.com/widgets/process-steps/ needs to be added to the CrocoBlock project. That would be super nice to have :)

Now I need to use ThePlusAddons for that widget, I would love to see this come at CrocoBlocks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. Now you can use [this](https://crocoblock.com/widgets/horizontal-timeline/) and [this](https://crocoblock.com/widgets/vertical-timeline/)
