### ISSUE TITLE
JetEngine Repeater - Have the ability to use Save templates

### ISSUE THREAD

**Issue by andrewkirkcaldy** [Crocoblock/suggestions#1042]
The repeater widget is very useful but it can be sometimes challenging create more complex styling with this widget.

It would be great if you could develop the ability to use saved templates with the repeater widget. I recently watched a video on competitor plugin call Dynamic Content for Elementor and they appear to utilise the save templates.

Would be great to build into a future release.

thansk

**Comment by MjHead** [comment]
From 2.3.0 you can build items for repeater the same way as Listings Items and showcase repeaterfields with Listing Grid widget
