### ISSUE TITLE
[Feature Request] JetSmartFilters: Checkbox Sort Filter 

### ISSUE THREAD

**Issue by jazir5** [Crocoblock/suggestions#1043]
I would like to create a sort filter in the form of checkboxes, specifically for the JetWooProducts Grid widget. I want users to be able to apply more than one sort at once and in the form of checkboxes, not a select box dropdown.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. If we get more similar requests then we will return to this
