### ISSUE TITLE
[Feature Request] Jet Engine Repeater Tabs

### ISSUE THREAD

**Issue by itaides** [Crocoblock/suggestions#1044]
Hi all, The Repeater options is great but it would be even better if we can use it in tabs . 
what i want:
1. ability to use repeater fileds with jet tabs - like timeline or other stuff . 
2. ability to choose different colors for each tabs 

thanks.

**Comment by kaskad88** [comment]
Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )
