### ISSUE TITLE
[Feature Request]JetElements: select multiple post types when querying post widget

### ISSUE THREAD

**Issue by liammaurer** [Crocoblock/suggestions#1047]
**Please, describe the feature request, making it clear to understand.**

When choosing a post type to display on JetElements there is no way to select more than one post type. This makes it very difficult to see ALL custom post types.

Feel free to add any videos, links, screenshots to illustrate the requested feature.

<img width="262" alt="Screen Shot 2020-03-29 at 4 30 30 pm" src="https://user-images.githubusercontent.com/25132161/77842925-3b023b80-71db-11ea-9be8-384eef3f407c.png">

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. Now you can use jetengine listing grid there is such an option http://prntscr.com/rpeyqx
