### ISSUE TITLE
Checkbox Position shifted in Jetengine Form Builder

### ISSUE THREAD

**Issue by satomiao** [Crocoblock/suggestions#1048]
**Describe the bug**

1. The position of the checkbox option shifted when there are many options. 

The normal position: https://tinyurl.com/rjkry7p
Shifted: https://tinyurl.com/r74e54y

However, by adding a "width" value to .jet-form-col__end will show the correct position
https://tinyurl.com/u4wp88j

2, The page break sometimes not working.

I have 2 page-break field in the form.
https://tinyurl.com/wmb4jv7

but in the second page of the form, there is no "Previous" button showed, even the Previous button option is checked and enabled. I can't get to the earliest page.
https://tinyurl.com/w7g82dg

You may try it here:
https://wordpress-144543-1218858.cloudwaysapps.com/form-builder/

**Comment by kaskad88** [comment]
Hi @satomiao.
1 issue - fix for the next version
2 issue - I tried to reproduce your issue based on the information you provided but without success.
Please contact our support at support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
