### ISSUE TITLE
Color picker is not working -BUG . 

### ISSUE THREAD

**Issue by itaides** [Crocoblock/suggestions#1055]
hi, i am trying to use the  dynamic color picker  with jet in taxonomy , its not working.
***With the ACF plugin it is working .**
 please fix that, thanks .

**Comment by kaskad88** [comment]
Hi @itaides . Please provide more details to reproduce the issue

**Comment by itaides** [comment]
ok , create a new meta box>choose for taxonomy and choose and taxonomy you want>then create meta filed > choose color picker and publish .
go to the edit of taxonomy >choose the color you want.
**now for the fun part:**
go to theme builder > edit or create a archive - try to use the headline widget for example > choose dynamic color and its not working with jet field (color picker), its working with acf filed (color picker) .

**Comment by kaskad88** [comment]
@itaides. I checked this issue. There really is a problem, but only on the editor page. On the frontend, jet dynamic color works correctly.

**Comment by kaskad88** [comment]
I checked this issue. There really is a problem, but only on the editor page. On the frontend, dynamic color works correctly with a jet field (color picker)

**Comment by itaides** [comment]
@kaskad88 true. in frontend works great . 
thanks mate.
