### ISSUE TITLE
JetEngine > Listing Grid > Post Query > Meta Query > Date : Add "Now" as possible value

### ISSUE THREAD

**Issue by jonathangerbaud** [Crocoblock/suggestions#1058]
In the listing grid, I want to be able to filter posts based on some date meta field. This is actually possible, which is great but is missing a little feature.

Let's say that the meta field is named "expiration_date".

In my case, I need to be able to display only posts for which the expiration date is greater than today.

When I select the "Greater than" operator, I do not have access to a magic variable that would take the current date time as value. (I tried to put "NOW", NOW()", "now", "now()", "TODAY" but nothing worked).

**Comment by realstephenzhao** [comment]
It works in my situation.
"now" is datetime type, "today" is date type.

![](https://i.imgur.com/uDTaEwP.png)

**Comment by jonathangerbaud** [comment]
Thank you for your answer.

I managed to make it work but only if I set "Save as timestamp" to true in the metabox options.

Also, my prior setup was using ACF fields, not JetEngine fields. And I couldn't make it work with a Date ACF field. I tried a whole bunch of combinations but nothing is working.

**Comment by realstephenzhao** [comment]
> 
> 
> Thank you for your answer.
> 
> I managed to make it work but only if I set "Save as timestamp" to true in the metabox options.
> 
> Also, my prior setup was using ACF fields, not JetEngine fields. And I couldn't make it work with a Date ACF field. I tried a whole bunch of combinations but nothing is working.

ACF is not fully supported by crocoblock plugins as far as I know, and ACF hasn't introduced such feature of storing datetime field value as timestamp yet.
See the answer -> [Date Time Picker should optionally save timestamp | ACF Support](https://support.advancedcustomfields.com/forums/topic/date-time-picker-should-optionally-save-timestamp/)

**Comment by SivaArkwell** [comment]
I am still having an issue with this. I have my system set up virtually the exact same way but it is not filtering based on my custom meta date.

Do I just type in "now" or "today" into the Value box or do I need to manually set up these variables of "now" or "today" beforehand?

I do also have the option of using Elementor's "Current Date Time" but that does not seem to work either.

**Comment by segunolamidegitup** [comment]
The temporal solution would be creating a shortcode that can fetch IDs of the required listing. These IDs will then be placed in the dynamic data field in jet engine post query IDs
