### ISSUE TITLE
JetCompareWishlist : "cx_include_module_url" is missing from loader.php

### ISSUE THREAD

**Issue by benjaminhaeberli** [Crocoblock/suggestions#1066]
**Describe the bug**
We use Bedrock (from Roots) as boilerplate for our Wordpress websites and we can't use *JetCompareWishlist* because the URL generated in ``loader.php`` is not correct. I contacted your technical suppord and they sent me the ``jet-fix-framework-url`` to avoid this error. It did not work and I found that in the ``loader.php`` of *JetCompareWishlist*, the ``cx_include_module_url`` filter is missing (only for this plugins, the others are OK).

**To Reproduce**
1. Activate _JetCompareWishlist_ without any other Jet plugin
2. Use [Bedrock](https://roots.io/bedrock/)

**Expected behavior**
I think you need to add the ``cx_include_module_url`` filter in the ``loader.php`` as the other plugins 👍 

```php
if (file_exists($path)) {
    $dir = pathinfo($path, PATHINFO_DIRNAME);

    $url = str_replace(
    '\\',
    '/',
    str_replace(untrailingslashit(ABSPATH), esc_url(site_url()), $dir)
);

    $this->included_modules[ $slug ] = array(
    'path' => trailingslashit($dir),
    'url'  => apply_filters('cx_include_module_url', trailingslashit($url), $path),
);

    require_once $path;
}
```

**Screenshots**
Wordpress back-office (plugin settings)
![GitHub Logo](https://i.imgur.com/UaZGoo3.png)

**Additional context**
This issue seems to be related with the #831 and #833

**Comment by kaskad88** [comment]
JetCompareWishlist v1.1.1 has been released.
Feel free to update!
