### ISSUE TITLE
Jetmenu: Make menuitems clickable to open submenu's

### ISSUE THREAD

**Issue by adorbit** [Crocoblock/suggestions#1067]
Hi,

I have a feature request for JetMenu, especially the mobile menu. To open a submenu you have to click on the '**>**' icon. It would be nice if the submenu (optionally) is opened if you click on the parent menuitem. See the screenshot for an explanation.

Thanks!

![IMG_6B60B42A1272-1](https://user-images.githubusercontent.com/63058871/78261982-394cb680-7500-11ea-9a80-86c487bad89a.jpg)

**Comment by shinTM** [comment]
done v 2.0.2 06.04.20 https://prnt.sc/rtukrc
