### ISSUE TITLE
Добавьте, пожалуйста, адаптивность таблицам

### ISSUE THREAD

**Issue by madmeur** [Crocoblock/suggestions#1069]
Адаптивность в таблицах никуда не годится, это совсем вообще не адаптивность.
В самых обычных Элементоровских таблицах предусмотрены мобильные заголовки, посмотрите как они работают. 

Очень хотелось бы, чтобы ваш функционал был дополнен подобным решением, потому что в противном случае, виджет таблиц не годен к использованию, а он необходим, как воздух. 

Пожалуйста, сделайте адаптив для ваших таблиц.

**Comment by stasonua0** [comment]
Про какие самые обычные Элементорские таблицы речь?

**Comment by Floydtm** [comment]
Please, note, that the feature requests can be accepted and processed only if they’re written in English.
