### ISSUE TITLE
JetPopup close trigger not stoping video(jupiter)

### ISSUE THREAD

**Issue by ZemezLab** [Crocoblock/suggestions#1070]
YouTube videos continue to play when the popups is closed which shouldn't do so.

You can see the issue (https://prnt.sc/rs3pl1) here: https://jupiterx.artbees.net/dance-coach/ 

Thanks

**Comment by antoinelbch** [comment]
Just came across this issue. The solution that worked was setting "Loading content with Ajax" and "Force Loading" to "Yes".

This seems to unload the videoplayer when the popup closes.
![jetpopup-video-force-loading-unloads-videoplayer](https://github.com/Crocoblock/suggestions/assets/1252145/ee69bff6-e908-4033-9eac-bef56cf6977f)

**Comment by FelixMendoza** [comment]
This really helped a lot. Thank you!
