### ISSUE TITLE
Make Jetengine options page meta fields name's translatable with WPML in admin.

### ISSUE THREAD

**Issue by poehaldur** [Crocoblock/suggestions#1072]
I have an options page in admin, that would need to have titles translated. Unfortunately only meta fields content can be translated but not the meta fields names.

![download](https://user-images.githubusercontent.com/32192439/78367903-77fb7300-75cb-11ea-9a24-7ebd5721af8c.png)

**Comment by kaskad88** [comment]
Added in JetEngine v.2.4.11. Look for JetEngine admin labels in WPML->String Manager->Jet Engine Admin Labels domain
