### ISSUE TITLE
[Feature Request] JetSmart Filters : View results as you typing in search 

### ISSUE THREAD

**Issue by dionisis17** [Crocoblock/suggestions#1076]
I would like very much to see the feature of the [doofinder.com](https://www.doofinder.com) in Jetsmart Filters and Jet Search. I have many e-shops and listing sites that I want to add this awesome type of search. It's in this [template ](https://luxury.wealty.co/)too. As you type in search the results below are filtered.
Please keep it in mind! 
![search](https://user-images.githubusercontent.com/53856507/78417605-63a38e80-763c-11ea-9606-6b1aec1f2177.gif)

**Comment by Floydtm** [comment]
@dionisis17, hi! now you can implement this with smartfilters http://prntscr.com/ruqz06
[search on typing.zip](https://github.com/Crocoblock/suggestions/files/4444682/search.on.typing.zip)

**Comment by dionisis17** [comment]
Thank you so much! I really appreciate it. You are really great !
