### ISSUE TITLE
Filter JetBlog Widgets by JetEngine Relations

### ISSUE THREAD

**Issue by johnbolandwp** [Crocoblock/suggestions#1077]
Hi.  

I love JetBlog Smart Post Tiles.  I love JetEngine's ability to define relations.  I can't make Post Listings for the Listing Grid that look as good as a Smart Post Tile, but I use JetEngine's relations feature extensively because I like making highly dynamic websites.   I'd rather not have to make a shitty looking post template for posts just so I can use that feature.  
[
Advanced Post Queries for Elementor](https://wordpress.org/plugins/advanced-post-queries/) has this exact feature for ACF relationship fields and works perfectly with Elementor Pro posts widget.  

Dynamic OOO has a feature like this, except their posts widget isn't as pretty as JetBlog.  

**The Feature**:  Query Posts by Relation.  
There's 3 straightforward ways I could see doing this:

- Ideally, it would be nice to just have an option to select a relations option like dynamic ooo or dynamic relations options like advanced post queries for elementor that worked with both JetEngine and ACF relationship fields.  

- Next best option would be to have the ability to use macros in the comma separated ids list.  

- Next best option would be to be able to dynamically generate the post ids in a JetEngine Field or a default WordPress custom field - as I attempted in the second photo.

- The next best option would to be able to use a JetBlog Skin within the JetEngine Listing Grid, so we could use macros there.

- The next best option would be to make some really solid templates for creating your own custom listings.  You guys should probably do this anyway.  

I'm guessing this can be done with a custom query, but I can't figure out how to do it. 

In general, I think the post relations is a super useful feature that I would like to see elevated.  It allows for a much more sophisticated cms design.     

![Advanced Post Queries](https://user-images.githubusercontent.com/61186283/78573898-dfddd380-77ee-11ea-9b2e-462ac5360a54.png)
                                                                                                                                                                                             
![Dynamic OOO Post Relations](https://user-images.githubusercontent.com/61186283/78419653-6044de80-760d-11ea-80d7-85eda02e14eb.png)

![JetBlog Query Screenshot](https://user-images.githubusercontent.com/61186283/78419332-579ed900-760a-11ea-8a7e-930a69cda658.png)

![JetBlog Dynamic Id Query](https://user-images.githubusercontent.com/61186283/78419486-d5171900-760b-11ea-9fc5-a54c1c5e4dcf.png)

**Comment by kaskad88** [comment]
For the next version added an ability to use dynamic tags in the `Include posts by IDs`controls 
<img width="292" alt="Снимок экрана 2020-04-24 в 13 24 23" src="https://user-images.githubusercontent.com/14362877/80205308-0eeba600-8633-11ea-8bbd-1ea7aa996c93.png">
