### ISSUE TITLE
Module Path and Url error with roots/bedrock .

### ISSUE THREAD

**Issue by trickymast3r** [Crocoblock/suggestions#1078]
**Describe the bug**
This bug about getting module path and url 

**To Reproduce**
1. Go to Admin -> Jet -> Plugin Setting page

**Expected behavior**
I was fix with this on Kava theme
Replace
`					$url = str_replace(
						'\\',
						'/',
						str_replace( untrailingslashit( ABSPATH ), esc_url( site_url() ), $dir )
					);`
With
`					$url = str_replace(
						'\\',
						'/',
						str_replace(untrailingslashit(WP_CONTENT_DIR), esc_url(WP_CONTENT_URL), $dir)
					);`

**Screenshots**
![image](https://user-images.githubusercontent.com/5774210/78451543-5fb15400-76b0-11ea-8584-bc0a9b307670.png)

**Comment by kaskad88** [comment]
Hello. To solve this problem, try installing this plugin [jet-fix-framework-url.zip](https://github.com/Crocoblock/suggestions/files/4436159/jet-fix-framework-url.zip). If the problem persists, please contact our support team at https://crocoblock.com/help-center/ for instructions on how to solve this problem (and mention that I was directed by you and refer to this problem).
