### ISSUE TITLE
JetWooBuilder error sale badge on product bundles

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#1079]
The sale badge on the product's single page for bundle products using Yith does not show the percentage discount using %percentage_sale% (https://yithemes.com/themes/plugins/yith-woocommerce-product-bundles/)

See product bundle image: https://pasteboard.co/J2joX9k.png
Now correct in a simple product: https://pasteboard.co/J2jpc5E.png

**Comment by UraraReika** [comment]
Hello @marcofrasson !

If you install this plugin https://yithemes.com/themes/plugins/yith-woocommerce-product-bundles/. Than go to product, make proper settings https://prnt.sc/vg3byc and put macros `%percentage_sale%` in the widget https://prnt.sc/vg3cuf. Result -  https://prnt.sc/vg3d8x.
