### ISSUE TITLE
JetEngine not being compatible with Phlox Pro

### ISSUE THREAD

**Issue by ahmadabuaysheh** [Crocoblock/suggestions#1081]
**Describe the bug**
JetEngine plugin isn't fully compatible with Phlox Pro theme

**To Reproduce**
1. Install Phlox Pro Theme
2. Activate basic plugins and Elementor
3. Add a custom post type with any number of fields
4. Add support to Featured image.
5. Create a new post of the new custom post type, the featured image won't be there. 
6. Change the theme to twenty twenty theme, the featured image section will appear.

**Expected behavior**
The featured image to be there

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 

**Smartphone (please complete the following information):**
 - Version: 75 Developer Edition

**Comment by Floydtm** [comment]
@ahmadabuaysheh, hi! Contact the theme developer. Or use one of the themes: kava, astra, ocean wp, hello, generate press
