### ISSUE TITLE
Add conditional logic to fields on a JetEngine form.

### ISSUE THREAD

**Issue by OverSysDev** [Crocoblock/suggestions#1082]
It is very important to be able to add conditional logic to fields on a JetEngine form.

Basically the function of showing or hiding other fields of the form according to an "x" condition

I am migrating from UltimateMember to JetEngine Forms and I encounter this issue.

It would be very interesting if they included these requirements in a next version of the product.

**Comment by Floydtm** [comment]
I merge this with #923
