### ISSUE TITLE
Jet Smart Filters doesn't load Hierarchy filters correctly

### ISSUE THREAD

**Issue by sonld89** [Crocoblock/suggestions#1086]
**Describe the bug**
On the website, model and body are being loaded base on parent make value. If you have a look at https://www.shevron.com.au/shop/?jet-smart-filters=epro-archive-products/default&_tax_query_pa_make=29701&_tax_query_pa_model=29711&_tax_query_pa_body=29581. You will see model and body type dropdown aren't being loaded correctly. Could you please fix it?

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know.

**Comment by etic86** [comment]
I have the same problem, on this web site:
https://test.climaproyectos.com.mx/tipos/comercial/
The performance improved by working on WPO of the website, but it still causes problems between the 3rd or 4th hereditary filter.
![error](https://github.com/user-attachments/assets/377f65a8-1d2a-41c8-b629-91bb4f43777e)

When reloading the page, I think ajax is working again and loading the pending elements correctly. 

I don't know if it is a site performance problem or if it is too nested.

**Comment by etic86** [comment]
![image](https://github.com/user-attachments/assets/5b9f400d-c665-4bab-8b51-17b5c6cec98d)

**Comment by promahdihasan** [comment]
> ![image](https://private-user-images.githubusercontent.com/61601604/389064851-5b9f400d-c665-4bab-8b51-17b5c6cec98d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzU4NTYsIm5iZiI6MTczNTM3NTU1NiwicGF0aCI6Ii82MTYwMTYwNC8zODkwNjQ4NTEtNWI5ZjQwMGQtYzY2NS00YmFiLThiNTEtMTdiNWM2Y2VjOThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA4NDU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGIwOTY3N2RlMWExZWZkZGEyNTQ5ODA0NWU2MGYyZmQ4YmVjYTg5MDNiZTA0NTY3MjNhZTA0NzAxOWU0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zWFzy4OhuNhxpKrZ4r_wEF2VGrx5JpS3aZmknD-ywms)



It is the same bug I am facing now in 2024

**Comment by Crocoblock** [comment]
Hi @etic86 @promahdihasan 
We've tried reproducing your issue, and everything works fine on our side. Please, contact [our support team](https://crocoblock.com/help-center) regarding this case and create a ticket including access details for your site where the issue occurred to ensure we can help you.
