### ISSUE TITLE
Dynamic Field Excerpt Custom Length not working

### ISSUE THREAD

**Issue by oweibor** [Crocoblock/suggestions#1089]
**Describe the bug**
The Custom Length of Dynamic Field Excerpt not working

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Listing
2. Add Custom Meta Field
3. Add **Dynamic Field**
4. Select **Post/Term/User Data**
5. Then Select the Object Field as **Excerpts**
6. Reduce the text length of the excerpts by Setting Custom Length to 13 as opposed to the default WordPress excerpt length of 55.

![edit](https://user-images.githubusercontent.com/3755176/78662438-4b47a400-78c8-11ea-9b92-9f778a275d20.png)

**Expected behaviour**
I expected the post excerpt length to be truncated down as shown in the listings column B and C. But instead, it displayed the full excerpt. 

![screencapture-localhost-jetproperties-sample-page-2020-04-07-11_11_27](https://user-images.githubusercontent.com/3755176/78662741-de80d980-78c8-11ea-81fa-0fcec44868f2.png)

**NB**: Column B and C are the static text displayed when those custom posts have no excerpts, however, my major concern is with column A, which has an excerpt but is not honouring the character length instructions. Kindly assist

**Desktop and Website Information:**
 - **OS**: Windows 10
 - **Local Server**: xampp
 - **Browser**: chrome
 - **Wordpress Version**: 5.4 
 - **Wordpress Theme**: Oceanwp v1.8.2
 - **JetEngine Version**: 2.2.6

@MjHead @SargasTM @shinTM @kaskad88

**Comment by Floydtm** [comment]
@oweibor, hi! this option works if you automatically generate a short description from the content of the post. while a short description should not be filled in the post http://prntscr.com/ruo8nv

**Comment by oweibor** [comment]
> @oweibor, hi! this option works if you automatically generate a short description from the content of the post. while a short description should not be filled in the post http://prntscr.com/ruo8nv

Thank you, this was helpful
