### ISSUE TITLE
Smart Post List cannot offset posts

### ISSUE THREAD

**Issue by tf5bassist** [Crocoblock/suggestions#1093]
When using the Smart Posts List, you cannot specify an offset.  This means that if, for example, the top of the page is using the Smart Post Tiles widget for 5 posts and then the Smart Posts List is immediately below it, the first five posts in the List will be repeats of the Tiles widget.

All post listing widgets MUST have an offset control that works.

**Comment by kaskad88** [comment]
I merged this issue with #744, which is on the same subject so we could deal with it more efficiently.
