### ISSUE TITLE
Shorter/Custom URL for “page reload” jet smart filter widgets

### ISSUE THREAD

**Issue by maxdegraaf0803** [Crocoblock/suggestions#1096]
I missed a feature in the jet smart filter widgets. I want to redirect people straight to a pre filtered shop page. This is possible but you get a really long URL like:  “ (domain name)/?jet-smart-filters=epro-product/default&_tax_query_product_cat=42”

I would like to see a feature in which its possible to get a shorter or custom URL. Something like the things that are filtered like: (domain name)/shop/hoodie+black+M

**Comment by Floydtm** [comment]
I merged this issue with #243 , which is on the same subject so we could deal with it more efficiently.
