### ISSUE TITLE
Required Metabox Variable

### ISSUE THREAD

**Issue by mandarpatil09** [Crocoblock/suggestions#1097]
I had come across with an Issue with Metabox, This may be a Feature request or might i had missed any setting.
I want to use a Dynamic repeater with Accordion on the website. which can be able to achieve with ACF repeater and Unlimited Elements addon but if crocoblock repeater is there then there is no use of ACF for me. 
Unlimited Elements Addon works as an Accordion with adding a custom Variable in HTML code it will dynamically display the current page details. ACF variable is showing as {{current.post.cf.customtitle}}.
Tried with the same with replacing the meta box field key but it is not working.

**Comment by Floydtm** [comment]
@mandarpatil09, hi! jetengine 2.3 has the ability to create a grid listing for a repeater. You can also use this [widget](https://crocoblock.com/widgets/classic-accordion/) to display templates. http://prntscr.com/rwmf1l
