### ISSUE TITLE
Jet Parallax inside Columns

### ISSUE THREAD

**Issue by thiagomendes78** [CrocoBlock/suggestions#11]
Please enable Jet Parallax inside Columns instead in Sections only.

**Comment by CrocoBlock** [comment]
Dear customer, 

Right at the moment, the parallax effect is also available for the widgets. 
Please, check this effect on live demo: https://jettricks.zemez.io/parallax-element/ 

Perhaps it's what is needed. If not, please, specify in more details what effect should be achieved. If possible, please, add a screenshot or al ink to the site where a similar effect is used. It will help our team understand the request better.

Best regards from CrocoBlock team
