### ISSUE TITLE
Logo shrink on scroll with JetBlocks

### ISSUE THREAD

**Issue by frostbytemarketing** [Crocoblock/suggestions#1100]
I would love it if in the Logo section of JetBlocks, when the user scrolls the website, there would be an option for the logo to shrink. I would LOVE it if the percent of shrinkage could be controlled differently on desktop, tablet and mobile. Right now I have CSS controlling this on a number of my websites but I am moving to use JetBlocks in my setup as my employees do not know how to code.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
