### ISSUE TITLE
The Team Members Widget on Elementor doesn't allow Social Media Links to open in a new window / tab

### ISSUE THREAD

**Issue by milesbulloch** [Crocoblock/suggestions#1101]
**Describe the bug**
The Team Members Widget on Elementor doesn't allow Social Media Links to open in a new window / tab

**To Reproduce**
1. Create new team member
2. Add social media links
3. No option for links to open in a new tab

**Expected behavior**
There should be a check box which allows links to open in a new tab.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - 80.0.3987.163 (Official Build) (64-bit)

**Comment by kaskad88** [comment]
Add for the next version.
Thanks for your report!
