### ISSUE TITLE
Add preview images to media meta field for not yet supported file types (JetEngine)

### ISSUE THREAD

**Issue by oceandiveloper** [Crocoblock/suggestions#1102]
Currently in the post editor the media meta field does not show preview images for all common file types, e.g. SVG, PDF. 

<img width="773" alt="Screen Shot 2020-04-11 at 07 54 58" src="https://user-images.githubusercontent.com/43462095/79030838-abdb2780-7bcd-11ea-8115-c2f3bbbf9802.png">

Also you can only see the title of the uploaded file only on hover. 

<img width="577" alt="Screen Shot 2020-04-11 at 08 23 35" src="https://user-images.githubusercontent.com/43462095/79030896-e80e8800-7bcd-11ea-8482-58b86aaa6633.png">

This means there is basically no indication what file you have chosen without hovering over the preview image box. This is very bad UX design that annoys me and also my clients on a daily basis. 

Can you please add preview images (which are visible in the media library)? 
For PDFs it would also be nice to see the title of the file.

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0

**Comment by oceandiveloper** [comment]
thank you :-) this makes me very happy
