### ISSUE TITLE
Social Widget: Hide empty social networks

### ISSUE THREAD

**Issue by erzorro** [Crocoblock/suggestions#1104]
Hello,

   I am using the social widget in a Team template using a custom post type. Not all the persons in the team have the same social networks. It would be great if a social network would not be showed if the link is empty.

   Is there a way to hide social networks or any other item if it is empty in the database?

**Comment by kaskad88** [comment]
Hello, @erzorro. Could you attach the screen or describe in more detail, because I tried to reproduce your steps and everything seems to work fine if the empty link then the social network is hidden

**Comment by kaskad88** [comment]
If the problem persists, please contact our support team at https://crocoblock.com/help-center/ for instructions on how to solve this problem (and mention that you were directed by me and provide a link to this problem).
