### ISSUE TITLE
Error when editing Post with Built-in JetEngine

### ISSUE THREAD

**Issue by HermesMacedo** [Crocoblock/suggestions#1105]
1-Enable Built-in JetEngine.

2-I click on edit Post.

3- Add Meta Field - Gallery and save.

4- when editing the post, editing with elementor is displayed.

The error is: I disabled the option to edit post with elementor in elementor settings.

Until then I had not added a post type with JetEngine.

This error only works when I edit the default WP post.

**Comment by HermesMacedo** [comment]
the error is: If I disable elementor for post, in elementor settings, it should not appear in post.

But it's showing up after I used the Built-in JetEngine.

I didn't create any post type, I edited the WP core post directly.

**Comment by Floydtm** [comment]
@HermesMacedo, hi! I checked your case and could not reproduce the bug. Contact our support team, describe your request, provide the data to enter your site. Our team will help solve your request.
