### ISSUE TITLE
JetEngine: Dynamic Field cannot be made clickable even when selecting Make Clickable

### ISSUE THREAD

**Issue by tf5bassist** [Crocoblock/suggestions#1106]
Reproduction steps:
- Build a Listing
- Drag in Dynamic Field widget
- Set widget Source to Post/Term/User Data
- Set Field to Title
- Notice the preview post title does appear as expected
- Turn on Filter Field Output
- Select Make Clickable from dropdown
- Notice that the Dynamic Field output is not clickable

Screen recording of example via OneDrive link:
https://1drv.ms/v/s!At3BYw_MFTvp2XF5c-6umYVg-ma_?e=TNUXNW

**Comment by kaskad88** [comment]
Hello @tf5bassist. The `Make Clickable` callback is not for your case. For your case, use the Dynamic Link widget with the following settings 
<img width="300" alt="Снимок экрана 2020-04-24 в 18 04 46" src="https://user-images.githubusercontent.com/14362877/80227739-bfb76c80-8656-11ea-833b-d52f8622b9e2.png">

**Comment by tf5bassist** [comment]
Hi @kaskad88, thanks for the clarification.  Is there a reason why this doesn't work as expected?  And is it possible to update the documentation for Dynamic Field to indicate that Make Clickable doesn't actually make something clickable?

Thanks again, I've reproduced the widget with the suggested replacement.

**Comment by kaskad88** [comment]
Hi @tf5bassist. This callback is used for сonvert plaintext URI to HTML links. https://developer.wordpress.org/reference/functions/make_clickable
