### ISSUE TITLE
[Feature] Dynamically change the text color based on the background color

### ISSUE THREAD

**Issue by digitpulse** [Crocoblock/suggestions#1109]
**Before adding a new feature request, please, make sure you’ve checked:**

[x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Please, describe the feature request, making it clear to understand.**

Hi,

I have an Elementor header drived with OceanWP and some Jetplugins widget (ex "Nav Menu", Ath Links, etc.) and when the sticky header comes over white backgrounds or images that has a white shape on, the text or icons are not visible.

It would be great if Crocoblock can provide such a feature : an option in the advanced settings of the widget that dynamically change the text or widget color in a black color when passing over white background and so on.

**Add an example of where this feature is already implemented. **

Example: https://www.carineroitfeld.com/en

**Comment by Floydtm** [comment]
@digitpulse, hi! At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
