### ISSUE TITLE
Feature request : JetBlocks : BreadCrumb widget doesn't include CPT inside

### ISSUE THREAD

**Issue by fhfournier** [CrocoBlock/suggestions#111]
Hi,

This is a feature request! I want to get more option in your breadcrumb widget.
Like YoastSEO, you should include option in elementor widget "Do you want to include CPT archive in it"
I only test with post CPT not the other but you should consider to add this option :-)

Something like that

Home > CPT > TAXO > Post title

![image](https://user-images.githubusercontent.com/3278753/54493968-d87a1e00-48ab-11e9-9337-b75110d80d73.png)

**Comment by kaskad88** [comment]
Hi @fhfournier

Thanks for the feedback.

CPT archive title is displayed in breadcrumbs only if it has the archive page. http://prntscr.com/n01b2r

**Comment by fhfournier** [comment]
Hi @kaskad88 

No, take a look

http://stage.tumeniaises.com/connerie/bonne-fete-mon-gros-gamer/ (no work)

Its should be

Home  >  Post CPT >  Fail >  Bonne fête mon gros gamer

Like http://stage.tumeniaises.com/conneries/cat/fail/ (work)

Home  >  Post CPT >  Fail

**Comment by fhfournier** [comment]
its a stage env. just tell me how you want to connect if you want to see in back-end
