### ISSUE TITLE
JetSmartFilters remember Results Page when going back

### ISSUE THREAD

**Issue by Neilnjk** [Crocoblock/suggestions#1113]
I was wondering if it's able for JetSmartFilters to remember the filters you have set, after you go to a product page that you found by setting specific filters and want to go back again but with the same adjusted filters.

For example:
You have found 3 different red scarfs by setting the JetSmartFilters to "filter:red" and "filter:scarfs"  you click on the first one, but you don't like it and you want to see the second one so the filters are still set to the latest search results. 

The problem now at my website is that the filters reset when I want to go back and I have to select "filter: red" and "filter:carfs" again.

Right now this is not available.

**Comment by Floydtm** [comment]
@Neilnjk, hi! Now it is available. You need to change apply type http://prntscr.com/s0zcqf to mixed
