### ISSUE TITLE
product variants on WooCommerce archive page 

### ISSUE THREAD

**Issue by michalczajka** [Crocoblock/suggestions#1114]
I would love to see something like this on WooCommerce archive page.

https://getwooplugins.com/plugins/woocommerce-variation-swatches/

**Comment by ibridges** [comment]
I second that...

**Comment by UraraReika** [comment]
https://crocoblock.com/troubleshooting/articles/how-to-add-attractive-variation-swatches-to-woocommerce-archive-page/

**Comment by sara-kariv** [comment]
> https://crocoblock.com/troubleshooting/articles/how-to-add-attractive-variation-swatches-to-woocommerce-archive-page/

the 2 codes on this article breaks my website

**Comment by fabi20x** [comment]
same here!
