### ISSUE TITLE
Dynamically load post Content into the JetElements Unfold Widget not working

### ISSUE THREAD

**Issue by oweibor** [Crocoblock/suggestions#1115]
The JetElements Unfold widget cannot dynamically display The Content of a post.  there is no option for the post content in the dynamic fields list, also when I click the excerpts option, nothing is displayed. Without having to create a special template for the content of the post, is there a more direct way to display the content using the unfold widget?

![unfold](https://user-images.githubusercontent.com/3755176/79301667-0f24cc80-7ee2-11ea-878f-cee027c9783d.png)

@shinTM @Floydtm

**Comment by kaskad88** [comment]
The post content cannot be displayed using dynamic tags functionality. For these purposes, you need to use the widgets Dynamic field ( JetEngine ) or Post content ( Elementor Pro )
