### ISSUE TITLE
Animated Text Widget in Safari

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#1116]
I have discovered a bug in Safari with the Animated Text Widget. It works fine in Chrome.
As you can see when scrolling back to the top - it reloads the animation on top of the existing animation when attempting to scroll up.
The error is only on SAFARI: Desktop & iPad.
When stroking up with two fingers on the macbook pro, it produces the original error I attached as an mp4 above.  Same when swiping up on iPad.

See video for more details
[animated_text_bug.zip](https://github.com/Crocoblock/suggestions/files/4481009/animated_text_bug.zip)

*ticket# 8697

**Comment by kaskad88** [comment]
Fix for the next version
