### ISSUE TITLE
[Feature Request] Dynamic accordion tabs based on number of repeater fields

### ISSUE THREAD

**Issue by ewancluckie** [Crocoblock/suggestions#1119]
Would really appreciate the ability to have a dynamic number of accordion fields or tabs generate based on the number of repeater fields with data.

This functionality was developed here by a third party: [https://github.com/ShariqKhan2012/Elementor-Repeater-Accordions] but unfortunately looks like it is no longer updated by the developer and has since broken.

Official support of this functionality would be an ideal solution.

Use case example:

Tour pages - Tours have varying durations from single day to 12+ days. Would like to style day-to-day itinerary in an accordion format using data from repeater fields in JetEngine for a 'Tours' custom post type.

Repeater Field 1 - Day Number (Day #) i.e. Day 1
Repeater Field 2 - Day Description (Long Itinerary Description text field)

A 3-day tour would dynamically show 3 tabs with the day number as the tab title and the body content being the description for each day, a 5-day tour would dynamically show 5 tabs and so on...

**Comment by stasonua0** [comment]
I’ve been writing about this for a long time, and not only me, but so far the guys don’t want to implement this very very important function

**Comment by ewancluckie** [comment]
> I’ve been writing about this for a long time, and not only me, but so far the guys don’t want to implement this very very important function

Well a lot of the dev work has been done in the discontinued plugin I linked to in the request, so hopefully that would be a solid base they can build from - which is already based on JetEngine and Elementor.

**Comment by Floydtm** [comment]
@ewancluckie, hi! To implement your request, use a listing for the repeater. and display this listing using the listing grid widget http://prntscr.com/s4offj http://prntscr.com/s4og0v https://www.youtube.com/watch?v=jG_WLJKWz_4&t=98s
@stasonua0, we just do not have enough time for everything.

**Comment by stasonua0** [comment]
> @ewancluckie, hi! To implement your request, use a listing for the repeater. and display this listing using the listing grid widget http://prntscr.com/s4offj http://prntscr.com/s4og0v https://www.youtube.com/watch?v=jG_WLJKWz_4&t=98s
> @stasonua0, we just do not have enough time for everything.

You are the best. So quickly introduce innovations that I do not have time to learn everything. Thank!

Please clarify what the closing of this ticket means?

**Comment by Floydtm** [comment]
@stasonua0, at the moment we cannot implement a issue with a dynamic accordion. as an option, I suggested using a listing grid to display a repeater. as soon as we collect more requests for a dynamic accordion we will return to this.

**Comment by ewancluckie** [comment]
> @ewancluckie, hi! To implement your request, use a listing for the repeater. and display this listing using the listing grid widget http://prntscr.com/s4offj http://prntscr.com/s4og0v https://www.youtube.com/watch?v=jG_WLJKWz_4&t=98s
> 
> @stasonua0, we just do not have enough time for everything.

This method only allows you to show the repeater in a static listing right? That’s all I’m able to make work. 

None of the accordion widgets seem to let you access the post meta content.

**Comment by stasonua0** [comment]
The function is very much in demand. Think about increasing the priority for implementing this functionality. - https://prnt.sc/s6qmub

**Comment by fafchook** [comment]
+1

**Comment by kaskad88** [comment]
Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )

**Comment by stasonua0** [comment]
> Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )

Hooray! We waited for this!

**Comment by About2git** [comment]
Yeah, this is nice, but seems not to work with Terms Metadata. So in Term as Archive Templates Repeater Fields are still not possible with this addon :-(

**Comment by pierrehansen** [comment]
What I'm still missing is the ability to change the order of repeater fields in those widgets (repeater widget, accoridon widget etc.)
I want to use it for clients who make calendar entries. I want the last repeater entry to show first which doesn' seem to be possible which is odd.

**Comment by remygfx** [comment]
It still doesn't work, only the title field of the accordion can collect the repeater field data, the content area of each tab/accordion region data access is missing, can still only reference normal metafields

**Comment by antoinelbch** [comment]
> It still doesn't work, only the title field of the accordion can collect the repeater field data, the content area of each tab/accordion region data access is missing, can still only reference normal metafields

+1

**Comment by yanivalm** [comment]
Help please :)

I'm trying to create tabs from repeater fields and show an image inside each tab also from the same repeater.
The problem is that i cant pull the image into the tab by using the "editor" option.
That is the code i used: <img src="%media1|img_url_by_id(medium)%"> But all i get is: "img src" it doesn't pull the image itself.

Also tried using a template but it pulls all the images from all the repeater fields which is not what i want.

Any idea how to solve it?

![image](https://user-images.githubusercontent.com/33746031/148283278-7d436697-d6a6-46ff-b940-902df083663d.png)

**Comment by jofori** [comment]
Even though the Topic is closed I desperately need the ability of a Dynamic accordion especially now their a New relationshp Workflow :-)

**Comment by stasonua0** [comment]
> Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )

**Comment by stasonua0** [comment]
Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )

**Comment by stasonua0** [comment]
> Even though the Topic is closed I desperately need the ability of a Dynamic accordion especially now their a New relationshp Workflow :-)

Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )
