### ISSUE TITLE
Feature request : JetElements : Posts widget doesn't include thumbnail size for box background & Taxo & link

### ISSUE THREAD

**Issue by fhfournier** [CrocoBlock/suggestions#112]
Hi,

There is a little option who is missing in your "posts" widget.

When selecting the option Show Featured Image As "Box background". There is no option for selecting Thumbnail size like "Simple image"

Also, this can be very nice if you could add "link for box background" or "title only".

If i select "Simple image" i can click on the image and title. If i choose "Box background" i could only click on title.

And last thing, its could be also nice if you could add a option for taxo. If i want to insert at the top left the category of the post.

![image](https://user-images.githubusercontent.com/3278753/54495886-d077a980-48be-11e9-9855-aa53ea0db64a.png)
![image](https://user-images.githubusercontent.com/3278753/54495889-d53c5d80-48be-11e9-95fb-45882bb5b741.png)

**Comment by fhfournier** [comment]
So happy to see @kaskad88 is on this feature :+1:

**Comment by kaskad88** [comment]
`Featured Image Size` control for `Box Background` added in JetElements 1.15.11
`Terms Links` added in JetElements 1.15.13. ( Please wait for the release )

Other suggestions are now impossible to do.

Thanks for suggestions

**Comment by fhfournier** [comment]
Thanks!
