### ISSUE TITLE
Control Tabs with hotspot CSS ID

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#1121]
Is it possible to bridge a link between the JetTricks hotspot widget that once clicked allows this than to open tabs from the JetTab widget by an ID selector?

**Comment by kaskad88** [comment]
Hello @iamdanbarrett. This can be done if the widgets are on different pages

**Comment by iamdanbarrett** [comment]
Hello @kaskad88 it would be great to be able to do it from the same page. So the hotspots on a map to open tab content boxes

**Comment by iamdanbarrett** [comment]
Is there any updates on this at all?

**Comment by kaskad88** [comment]
Fixed for the next version. Thanks for your report!

**Comment by iamdanbarrett** [comment]
That's fantastic, I am excited to see this added :D
