### ISSUE TITLE
JetEngine: duplicating Repeater meta field issue

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#1123]
In the act of creating a CPT -> Repeater fields.
1. Create a new CPT.
2. Create a Meta Field of type 'repeater' and name it repeater1(or whatever name you pick).
3. Create 3-4 fields within this repeater of any type.
4. Use the 'Copy' feature to duplicate the 'repeater' field to another Meta Field and name it repeater2(or whatever name you pick different than the 1st).
Attempt to update the embedded field types by either deleting and re-adding the fields required for this 2nd repeater, and it changes the 1st one as well.

**Comment by kaskad88** [comment]
Fix for the next version.
Thanks for your report!
