### ISSUE TITLE
 Smart Filters - very need a multi-choose field !!!

### ISSUE THREAD

**Issue by justdudeone** [Crocoblock/suggestions#1125]
Hi,

Seems that your very powerful Smart Filters still does not have a very important multi-choose dropdown filter type-style! It's a very-very important for a shops to chose many variants instaed of one! For example Gucci+Zara, Nike+Reebok, etc.

PS Where your Smart Filters are stored at WP database? At Posts table or it's own?

![image](https://user-images.githubusercontent.com/43311177/79632674-8b7d1100-8169-11ea-9552-9e4f5b7ff69a.png)

**Comment by rocketeer76** [comment]
Yes. Its called fselect and I was asking for this vey important feature in the below issue.

https://github.com/Crocoblock/suggestions/issues/811

**Comment by justdudeone** [comment]
Seems that developers are more care about quantity, but not quality. JET create enormous number of plugins&addons. But almost all of them or copy-analog of ElementorPro (ThemeCore, WooBuilder, PopUp, StyleManager), or have better alternatives from other developers (mega menu better at PlusAddons, filters+options+swatches better at XforWooC, search better at AJAX Search Pro, Compare&Whishlist and Reviews and most of Elements are too simple, even Engine have powerful competitors as ACF-Pro/Pods/Toolset/MetaBox). this crap happen because JET trying to make too much functions-widgets - they just overload by they own greed.

Some addons developers understand that most developers needs not quantity, but max quality-functionality and clients free to buy many different most powerful addons - so they chose the better strategy - not to waste time to copy existed ElementorPro functionality, but only add they own original and very powerful widgets - in result their addons better and have less competition.

Hope at least for a most popular and the most promising JET plugins as MegaMenu + SmartFilters + Engine + Blog = developers will listen to the clients wishes-requests.... or even those plugins with great potential will be wasted into the laggards. :\

**Comment by rocketeer76** [comment]
FacetWP seems a better option at this time. Sad that Crocoblock didn't implement this. Maybe it's too difficult?!

https://facetwp.com/documentation/facets/facet-types/fselect/

**Comment by justdudeone** [comment]
Hi, can you tell ETA?

**Comment by anderoav** [comment]
Any news?

**Comment by kochhase** [comment]
yes any news??

**Comment by rocketeer76** [comment]
No. Seems to be forgotten.

**Comment by jamsheehan** [comment]
@MjHead any chance this can be implemented in an upcoming sprint?

**Comment by nreljed** [comment]
#3885

**Comment by MjHead** [comment]
Done (as additional options for the Checkboxes filter)
