### ISSUE TITLE
WooBuilder - Rating widget - add custom field metakey

### ISSUE THREAD

**Issue by justdudeone** [Crocoblock/suggestions#1126]
Hi,

Your rating widget are very lack of possibility to set any custom post/product field.
https://docs.elementor.com/article/556-dynamic-tags

(ElementorPro similar rating widget have such possibility to set some custom fields, but fields list are too short, so it also lack of a "Post Custom Field" with possibility to enter any metakey.)

Also for a SmartFilter RatingFilter add possibility to filter base on custom metakey.

It's very simple, please, add possibility to get rating value from "Post Custom Field" by metakey!

**Comment by justdudeone** [comment]
Hi, can you tell ETA?

**Comment by UraraReika** [comment]
Hi, @justdudeone! Rating widgets from JetWooBuilder namely these two https://prnt.sc/ssbi41 are sharpened for Woocommerce and it is incorporated in the structure, it is not a blank that can be modified. So the functionality you are writing about will not be embedded in these widgets. This is purely for Woocommerce and for the rating that people leave in the comments. You can use the ElementorPro widget if you are comfortable with its functionality. As for JetSmart Filters, you can filter by the rating displayed in our widgets using this key https://prnt.sc/ssbjis.
