### ISSUE TITLE
[Profile builder] Custom password recovery page/widget

### ISSUE THREAD

**Issue by Kestrel-glitch** [Crocoblock/suggestions#1127]
There is currently a problem with elementor, the woocommerce part it reaches is fine but incomplete, crocoblock fixes many of its problems with jetwoobuilder and Jetengine but in my opinion there is a problem with login and **password recovery system** . This system when you approach the page to recover password redirects you to the default page of wordpress to reset the password, this **generates branding problems for most e-commerce.**

There is a plugin that solves this called "profile builder" but I think the functionality of being able to **_customize the password reset_** page is important that it comes with some plugin from the crocoblock suite. (maybe jetblocks?) _(that at least works as it is on your own website crocoblock.com_)

**Comment by Dhaump** [comment]
It would be great if the password recovery template could be modified ... I totally agree

**Comment by jimhuds** [comment]
This would be great. Currently the reset password form on my site is stretched out across the screen.

**Comment by Zegklitz** [comment]
+1

**Comment by unitedonline** [comment]
Any news on this please?
JetBlocks is not the solution because it depends on Elementor.
This functionality must be independent, so developers can use other page builders also (example - Bricks builder).

**Comment by MjHead** [comment]
This functionality will be added into JetFormBuilder with next update of User Login addon - https://jetformbuilder.com/addons/user-login/
