### ISSUE TITLE
Bug report : JetBlocks : BreadCrumb widget doesn't include full path when primary subcategory

### ISSUE THREAD

**Issue by fhfournier** [CrocoBlock/suggestions#113]
Hi,

There is some problem when having post with category and subcategory.

![image](https://user-images.githubusercontent.com/3278753/54500099-9246ae00-48ef-11e9-99ec-85408a1784cc.png)

If "full path" is set, its should display parent category if primary category is a child

![image](https://user-images.githubusercontent.com/3278753/54500125-ca4df100-48ef-11e9-94cc-a65f104a1e9b.png)

Yoast Widget work perfect but jet doesn't include the subcat (primary)

![image](https://user-images.githubusercontent.com/3278753/54500116-b3a79a00-48ef-11e9-9b30-2b5bc21bca0f.png)

Please don't make me choose Yoast for this widget :P lol

**Comment by kaskad88** [comment]
Hi @fhfournier 

Thanks for the feedback.

In the next release, an ability to set additional settings for CPT in the breadcrumbs will be available  http://prntscr.com/n01dpg. And categories and subcategories will be displayed in the breadcrumbs http://prntscr.com/n01ce5.
