### ISSUE TITLE
JetSmartFilters - Very important filter bug - not all Terms displayed!!! 

### ISSUE THREAD

**Issue by justdudeone** [Crocoblock/suggestions#1132]
Hi,

At your Jet SmartFilters there are filter style named "Visual", which must represent filter taxonomy variants as Color or Images. It something similar to swatches. But it have some very important problems!!!

1a) Why option Terms list display only one Term from about 50 ??? (Maybe it displaying only Terms already used at Products - but for a filter tune at dashboard it's wrong!)
1b) The same problem for all filter types at "Exclude/Include" field - it also displaying only 1 Term from about 50!
2) Even if all Terms will be displayed - it's absolutely uncomfotable to add each Term one-by-one by clicking "Add Option" and by chosing each time needed term. Will be much better and faster if full list of Terms will be displayed immediatly atomatically on Taxonomy chosing!
3) Term name field size are really redicolous. Better make those "options tiles" as horizontal lines! So Term name will have much more space!
4) In addition to color&image will be great to have an Icon option to set icons for Taxonomy based on existed fonts (with support of custom generated fonts as fontello.com, icomoon.io, etc too).

![image](https://user-images.githubusercontent.com/43311177/79682476-4caf8f80-822b-11ea-9bf9-3e2e685bddc3.png)

Without those problems resolving it just impossible to work with Visual filter!!!

Please, resolve them ASAP!!!

**Comment by justdudeone** [comment]
Hi, can you tell ETA?

**Comment by Floydtm** [comment]
@justdudeone, hi! Please update the plugin to the latest version https://prnt.sc/sjmf84
