### ISSUE TITLE
[Feature request ¦ jet engine]  frountend delete button link

### ISSUE THREAD

**Issue by P258tiwari** [Crocoblock/suggestions#1134]
Hi crocoblock,
Thanks for creating beautiful plugins, 

Jet Engine has missing delete link feature.. 

I am using jet engine to create listing project website. In jet engine I am not find any way to create a delete button on front end just like edit button link. 

I need your help to overcome this issue 
Thanks 😊🤗

**Comment by Floydtm** [comment]
@P258tiwari, hi! It will be available in future updates

**Comment by P258tiwari** [comment]
Thanks for reply;
I am waiting for this feature.

**Comment by XavaDigital** [comment]
Any progress on this?

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/jetengine-dynamic-link-widget-overview/
