### ISSUE TITLE
jetappointment issue

### ISSUE THREAD

**Issue by KreatifDesign** [Crocoblock/suggestions#1137]
It would be great to have a feature where you can create a booking that allows you to choose a specific date at a specific time slot to allow for booking. So I could say make 2 Slots 4pm and 8pm on Monday, then 3 slots on a Wednesday. This will allow a booking system where smaller businesses can just set random days and times and only make those available. It is a reverse of what is currently available as you would have to eliminate all the non working days that could take ages to set up

**Comment by MakhonkoDenis** [comment]
Hi,
The ability to add working days for providers or services appeared in version 1.2.0
And so the provider can set up his week, after that select only those days on which he plans to work. https://prnt.sc/1349ft8
