### ISSUE TITLE
Feature Request for Pagination Element.

### ISSUE THREAD

**Issue by exploredesign** [Crocoblock/suggestions#1140]
I would like to have the ability to add basic content / ads to specific Elementor column based on the Jet Smart filters pagination page that is being viewed. To make it a bit clearer I have a site with custom posts. It uses Elementor and JetEngine and of course Jet Filters. I have some space below the filter checkboxes that I would like to put advertising.

Can you please let me know if this featured could be added anytime soon
Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
