### ISSUE TITLE
Meta box fields are showing escaped characters

### ISSUE THREAD

**Issue by fonderco** [Crocoblock/suggestions#1143]
**Describe the bug**
When putting a single or double quote into a textarea, upon saving the char gets escaped.  I.E. slash single quote (\') or slash double quote (\").  Then when the user updated the post again, it get escaped again.  For example \\"  Then \\\"  Then \\\\"

**To Reproduce**
1. Create meta box with textarea
2. Enter single or double quote into textarea
3. Save post
4. Keep clicking Update to see the escape slashes grow in number

**Expected behavior**
We should never show the escape character to the end user.

**Current work around**
I used the save_post hook and stripslashes_deep function to fix it.  The stripslashes_deep function should be used in the core code.

**Comment by kaskad88** [comment]
Fix for the next version.
Thanks for your report!
