### ISSUE TITLE
Jet Menu Mobile CSS not caching and breaking when using ajax

### ISSUE THREAD

**Issue by enoteware** [Crocoblock/suggestions#1144]
FYI: Ticket posted on support forum, but was suggested to post here: #9105 Jet Menu - Ajax loading breaks CSS for listing grids, https://support.crocoblock.com/support/tickets/9105

Hello,

I've got the mega menu's setup and are working well.  However, if ajax loader is enabled the css of the listing grids used in the jet menu don't load certain css properties and look broken.  I've been able to disable ajax loader on desktop, but cant seem to find a way to do it on mobile. I'd prefer to leave ajax on to speed page loads, but not sure how to avoid css breaks.

Here is a video of the issue.
https://lc.notewaredigital.com/wp-content/uploads/2020/04/mobile_menu_issue.mp4

TY,
Elliot

**Comment by shinTM** [comment]
added compatibility with jetEngine v2.3.6

**Comment by enoteware** [comment]
Thank you! Glad to see it working.
