### ISSUE TITLE
Ability to have dedicated Single Product Page Template for each product category

### ISSUE THREAD

**Issue by hamidmoghaddasi** [Crocoblock/suggestions#1145]
Hi.
It would be wonderful to be able to have dedicated Single Product Page for each product category. I currently use Elementor Single Product Templates and each one is conditioned for one product category. Since I want to use some of JetWooBuilder widgets (It seems I can't access them with Elementor Single Templates) in my Singles, I would really appretiate to see this option in your plugin. Something like "Custom Taxonomy Template" you already have for product archive pages.

**Comment by rtpHarry** [comment]
This is something that I need for my current project.

It is possible to go into WooCommerce > Products > Product and edit the template for a single product:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/1038062/182337181-10aa0127-187a-4c43-b5ce-25b796b5e3e4.png">

I have three different types of shop running in the one site though, and need to add templates per category, rather than requiring the admin to set a custom template on every product.

I've been doing some digging, and it seems like there is a filter for this: `jet-woo-builder/custom-single-template`

It's in:

`wp-content/plugins/jet-woo-builder/includes/integrations/base/class-jet-woo-builder-integration-woocommerce.php`

```PHP
/**
 * Get custom single template
 *
 * @return string
 */
public function get_custom_single_template() {

	if ( null !== $this->current_template ) {
		return $this->current_template;
	}

	$enabled          = jet_woo_builder_shop_settings()->get( 'custom_single_page' );
	$product_template = get_post_meta( get_the_ID(), '_jet_woo_template', true );

	if ( ! empty( $product_template ) ) {
		return apply_filters( 'jet-woo-builder/custom-single-template', $product_template );
	}

	$custom_template = false;

	if ( 'yes' === $enabled && 'default' !== jet_woo_builder_shop_settings()->get( 'single_template' ) ) {
		$custom_template = jet_woo_builder_shop_settings()->get( 'single_template' );
	}

	$this->current_template = apply_filters(
		'jet-woo-builder/custom-single-template',
		$custom_template
	);

	return $this->current_template;

}
```

Just need to a bit of custom coding...

**Comment by rtpHarry** [comment]
I took another look at this, and this snippet is the basic code that would assign a custom category to a product.

```PHP
function runthings_custom_woo_product_template( $template ) {
	global $product;
	$id = $product->get_id();

	if($id === 10030) { // temporarily locked to "bell tent" (a product id)
		$terms = get_the_terms( $id, 'product_cat' );

		foreach ($terms as $term) {
			if($term->term_id == 407) { // temporarily locked to "stay" (a product category id)
				$template = 12737; // temporarily locked to "stay product" template (a jet woo builder template id)
			}
		}
	}

	return $template;
}
add_filter( 'jet-woo-builder/custom-single-template', 'runthings_custom_woo_product_template');
```

It's just a starting point, as I want this to be customisable for the shop manager.

I'm thinking that it will need a custom drop down adding to the taxonomy category page, using this:

https://stackoverflow.com/questions/33907177/add-custom-taxonomy-metadata-field-to-wordpress

And then check each assigned category to see if it has a template override.

I'm also thinking that there could be an optional priority field for when a product is in two categories.

**Comment by rtpHarry** [comment]
OK I spent a few hours this evening and built this out into a plugin.

It adds in new template settings to the Category taxonomy of WooCommerce Products to let you apply a custom template per-category.

You can use the priority setting if your products are assigned to multiple categories and you want to control which template is used.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/1038062/182479967-499603cd-efaf-41ed-80d1-891ad9a31c7d.png">

The plugin is available here:

https://github.com/rtpHarry/jet-woo-builder-category-custom-product-template

**Comment by UraraReika** [comment]
In the latest release of the JetThemeCore plugin new WooCommerce related condition appears. There is although integration with JetWooBuilder so you can easily use it widgets in JetThemeCore templates.
