### ISSUE TITLE
Product Grid and Product List at the same time

### ISSUE THREAD

**Issue by woofworkshop** [Crocoblock/suggestions#1146]
Please consider using Product Grid and Product List at the same time. Here are implementation examples:

1.	https://www.dns-shop.ru/catalog/17a892f816404e77/noutbuki/?mode=simple
https://prnt.sc/s4dn1k
https://prnt.sc/s4dn8b
2.	https://www.proficosmetics.ru/catalog/dlya-tela/kremy-dlya-tela/#v1=y
https://prnt.sc/s4dnh7
https://prnt.sc/s4dnrs
3.	https://preview.themeforest.net/item/woodmart-woocommerce-wordpress-theme/full_screen_preview/20264492?_ga=2.187762991.602043059.1579566593-223919026.1573677344
https://prnt.sc/s4do2g
https://prnt.sc/s4do8y

Those. when the user himself can choose the display method, tile or list. In addition to visual convenience, such a scheme implements a powerful SEO tool. Namely: since the tile and the list will be simultaneously uploaded to the page, the product headers will be duplicated, and this will increase the density of keywords on the page. In addition, a description can be added to the lists, which will also positively affect the number of keywords.

**Comment by petranca** [comment]
It should be possible to switch from grid to list and vice versa. The user should be able to decide if he wants to view the list or the grid. This is standard in almost every shop today. 

For example, in the grid view you can display only picture and price and in the list view you can display additional information like the description.

I miss this feature too!

**Comment by UraraReika** [comment]
I merged this issue with #565, which is on the same subject so we could deal with it more efficiently.
