### ISSUE TITLE
LOAD MORE button

### ISSUE THREAD

**Issue by woofworkshop** [Crocoblock/suggestions#1148]
Please add the LOAD MORE button to the PANGINATION tool. When you click on it, the products from the next page are added to already visible products through AJAX. Moreover, the classic pangination should work synchronously, highlighting the page number.
https://prnt.sc/s4e36g

**Comment by stasonua0** [comment]
For now, a compatible plugin with Jet Woo Builder can be used - WooCommerce Load More Products by BeRocket

**Comment by UraraReika** [comment]
https://github.com/Crocoblock/suggestions/issues/4668
