### ISSUE TITLE
The gap in the Dynamic term is not taken into account

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1149]
Hello, I noticed that in the Dynamic Term widget the spacebar is still not taken into account - https://prnt.sc/s4imvh, in other Jet Engine widgets you fixed it

Здравствуйте, заметил что в виджете Dynamic Term всё еще не учитывается нажатие пробела - https://prnt.sc/s4imvh, в других виджетах Jet Engine вы это исправили

**Comment by kaskad88** [comment]
Fix for the next version
