### ISSUE TITLE
Jet Engine Map Listing support for OpenStreetMaps and Yandex.Maps

### ISSUE THREAD

**Issue by dbelyaeff** [Crocoblock/suggestions#1151]
**Please, describe the feature request, making it clear to understand.**

It would be great if JetEngine new Maps feature won't be strictly connected only with Google Maps.

Please, give end user a choice to choose from — add OpenStreetMaps and Yandex.Maps.

**Comment by pedrostein** [comment]
+1 this would be a unique feature not available in comparable products and make jetengine even more  appealing to new customers

**Comment by dzined** [comment]
+1 mapbox integration would also be neat

**Comment by derrickmg** [comment]
+1
I would buy Crocoblocks if it had this feature.
I am currently searching for a directory map listing plugin. 
Google maps are now paid and it would be great to be able to use open street maps (ie: topographical) + I don't want to use google on my site.

**Comment by p4velj** [comment]
Hi

Yes, I am also inclined to integrate **MapBox** or at least **OpenStreet**.

Integrating only GoogleMap (paid) takes you potentially unnecessarily;)

Regards p4vel

**Comment by stephscode** [comment]
+1 
I agree please consider Mapbox too.

**Comment by rocster01** [comment]
100% agree - whilst Google Maps / API do give you a certain amount of monthly credit, it is prohibitively expensive if you go beyond the limit.

On a site that may get a decent amount of traffic, the risk is that if you have the map feature active, you are stung with a hefty monthly charge from Google.

Having trialled it on a site I'm building, I quickly burned through a lot of the credit from Google, and decided to switch to using static screenshot maps, as I didn't want to run the risk of a big bill from Google.

There are plenty of either open source or alternative map API providers that are a fraction of the cost of google. 

I 100% believe that this feature alone will be a deciding factor whether people adopt Jetengine as a tool-of-choice, or go with another platform that offers openstreetmap (or similar) integration out-of-the-box

**Comment by dfgnoebrg** [comment]
+1 here. We need Open Street Map Support **as soon as possible** due to the pricing policy of Google Maps..
other wise we have to look for another solution.
please make this happen. 

Thx!

**Comment by serg-pervushin** [comment]
+1 for Yandex.Map

**Comment by travelgu** [comment]
+1 for Open Street Map

**Comment by petranca** [comment]
+1 for open street map minimum like https://elementpack.pro/demo/element/open-street-map/

**Comment by mindingear** [comment]
+1 for Open Street Map

**Comment by dfgnoebrg** [comment]
@victoriabormotova || @Floydtm 

Hi! any news/plans to implement this feature?

Thx : )

**Comment by dasigna** [comment]
+1 for openstreetmap integration!

nasty google maps have the already mentioned downsides - another one is the data protection thing.
we need a cookie-free solution. so far they are very rare and if present quite limiting.

elementor wont get it done - so chime in guys. 

openstreetmap with styling integration might be even better :)

**Comment by ludekcerny** [comment]
+1 for OpenStreetMap ❤

**Comment by Dennisvb** [comment]
OpenStreetMap integration would be great!

**Comment by dbfischer** [comment]
+1 for OpenStreetMap ... please.

**Comment by binaire01** [comment]
+1 for OpenStreetMap and MapBox

**Comment by AlaplayaW** [comment]
+1 for OpenStreetMap and MapBox.
Is there some news about it? Is it a planned feature?

**Comment by greyzusht** [comment]
+1 Please add OpenStreetMap for map listing. thanks

**Comment by Jackal-un** [comment]
+1 for OpenStreetMap and MapBox.

**Comment by Pierrezoomkite** [comment]
+1 for OpenStreetMap :)

**Comment by Rugby-Clubs** [comment]
I'd love it too !

**Comment by MiDoronin** [comment]
+1 for Yandex.Map

**Comment by CptSlow2000** [comment]
+1 Also for JetElements Advanced Map. I just wanted to use it but only as a design feature. And for that purpose I think OSM is a much easier and better choice than Stonks Google.

**Comment by brupao** [comment]
+1

**Comment by Mrakhil299** [comment]
Is it available open street map like snap chat on crocoblock . I want a feature where all user of my website profile can be visiable live location like travel app on map. Is it possible to create

**Comment by imaxenio** [comment]
+1 for Leaflet OpenStreetMap and MapBox.

**Comment by devyncocreative** [comment]
+1 for OpenStreet Map

**Comment by ssoronid** [comment]
+1

**Comment by trofimartya** [comment]
+1

**Comment by MjHead** [comment]
Added with 3.0.0 update (without Yandex. You understand why)
