### ISSUE TITLE
Mega Menu not working in IE11 and causing javascript errors

### ISSUE THREAD

**Issue by joelnewcomer** [Crocoblock/suggestions#1152]
Hi! In IE11 the mega menu is not working at all and is throwing javascript errors:

Invalid character
jet-menu-public-script.js (688,8)

Syntax error
ecspro.js (137,49)

Object doesn't support property or method 'JetMenuPlugin'
jet-menu-widgets-scripts.js (42,5)

Thank you!
![QqmCPG2QaKbk3PZb7M4offy-LTzmK0Qjmw](https://user-images.githubusercontent.com/171541/80101162-0b76f280-853f-11ea-91fc-352d7bda2f30.JPG)

**Comment by CF-NGrid** [comment]
Having same problem here. Any temporary workarounds suggested?

**Comment by CF-NGrid** [comment]
For our purposes, we were able to replace the backticks with straight quotes '' in the code on lines detected by the debugging in IE11. We removed the lines calling the mobile menu (we are using a different menu for mobile):

jet-menu-public-script.js

`jet-mobile-menu__item`,
`jet-menu-item-${ this.itemDataObject.itemId }`,
`jet-mobile-menu__item--sub-trigger-${ this.menuOptions.subTrigger || 'item' }`

Our modified file - testing clear on IE11.
[jet-menu-public-script.zip](https://github.com/Crocoblock/suggestions/files/4531096/jet-menu-public-script.zip)



`jet-mobile-menu__item`,
`jet-menu-item-${ this.itemDataObject.itemId }`,
`jet-mobile-menu__item--sub-trigger-${ this.menuOptions.subTrigger || 'item' }`

Also, we are not using the mobile menu, so we removed those two lines from above.

**Comment by joelnewcomer** [comment]
@CF-NGrid Thank you for sharing that! That fixed the issue for me!

**Comment by shinTM** [comment]
https://developers.elementor.com/elementor-dropping-support-ie/
