### ISSUE TITLE
Jet engine - Last Viewed Posts 

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1154]
Hello, consider introducing functionality in Jet Engine to display recently viewed records by a specific user based on his browser cookie. So please consider that this functionality works when the page caching plugin is enabled.

An example implementation without plugins - https://wp-kama.ru/question/plagin-prosmotrennyih-zapisey
Plugins that can do this:
1. Posts Viewed Recently
2. Recently Viewed Products
3. DD Last Viewed

/*Оригинал*/
Здравствуйте, рассмотрите возможность внедрения в Jet Engine функционала по выводу недавно просмотренных записей конкретным пользователем на основании его cookie браузера. Так просьба учесть чтобы этот функционал работал при включенном плагине кеширования страниц.

Пример реализация без плагинов - https://wp-kama.ru/question/plagin-prosmotrennyih-zapisey
Плагины которые это умеют: 
1. Posts Viewed Recently
2. Recently Viewed Products
3. DD Last Viewed

**Comment by stasonua0** [comment]
Changed the title and content, please re-pay your attention to this request.

**Comment by mcj777** [comment]
I support! The right thing!

-------

Поддерживаю! Нужная штука!

**Comment by panpsonis** [comment]
Is this included in the 2.6.0-beta1? Not sure how to set it up.
