### ISSUE TITLE
WordPress crash if Elementor not present

### ISSUE THREAD

**Issue by cristiansimion** [Crocoblock/suggestions#1155]
**Describe the bug**
The bug happens when you either deactivate Elementor and puts WordPress into a 500 internal error or if you install and activate JetEngine without Elementor being present.

**To Reproduce**
Steps to reproduce
1. Install WordPress ( no Elementor, blank slate of WP install )
2. Install JetEngine
3. Activate JetEngine

**Expected behavior**
A notification that Elementor is not enabled or at least not to crash the site.

**Suggestions**
Check if Elementor is present and if not, don't continue to load the plugin, but allow it to stay active. Add a notice to the WP notices that it requires Elementor.

**Comment by kaskad88** [comment]
Fix for the next version
