### ISSUE TITLE
Product Categories list display without photo

### ISSUE THREAD

**Issue by stochris** [Crocoblock/suggestions#1156]
In JetWooBuilder, similar to the Products List, the Products Categories List should also have checkbox that allows me to hide the images, so I only see the texts :) Also, if that could be added to the Product Categories Grid, that would be awesome

https://prnt.sc/s4hd7e

**Comment by UraraReika** [comment]
Hi, @stochris!
This issue can be solved by rewriting Categories Grid preset template in your child theme, like this https://prnt.sc/t4xdu1 and you `ll get such result https://prnt.sc/t4xecy. Then you need style it whatewer you want.

To rich this result you need: 
1 - Rewrite preset template in your child theme 
child-theme\jet-woo-builder\jet-woo-categories\global\presets\__your_prefix_preset.php
2 - Add following code to your child theme 

```
add_filter( 'jet-woo-builder/shortcodes/jet-woo-categories/atts', '__your_prefix_product_categories_custom_preset', 10, 1 );

function __your_prefix_product_categories_custom_preset( $preset ) {
	$preset['presets']['options']['__your_prefix_preset'] = esc_html__( 'Your prefix preset', 'jet-woo-builder' );

	return $preset;
}
```

Where this key https://prnt.sc/t4xgph equel your preset template file name.
