### ISSUE TITLE
Dynamic pin in Jet Engine Maps

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1162]
Hello, consider introducing very important functionality in Jet Engine Maps.

Add dynamic pin - https://prnt.sc/s5f6fo

Purpose: To be able to set an individual icon or image for each object, while being able to make a default icon, in case a custom icon is not set for a specific post.

/*Оригинал*/
Здравствуйте, рассмотрите возможность внедрить очень важный функционал в Jet Engine Maps.

Добавить динамический pin - https://prnt.sc/s5f6fo

Цель: Иметь возможность задавать каждому объекту индивидуальную иконку или изображение, при этом иметь возможность сделать иконку по умолчанию, на случай если не задана кастомная иконка для конкретного поста.

**Comment by MjHead** [comment]
Added in version 2.3.4

**Comment by stasonua0** [comment]
Thanks for the promptness, everything worked as it should!
