### ISSUE TITLE
Output data from the password.

### ISSUE THREAD

**Issue by GOHA81177** [Crocoblock/suggestions#1164]
Using metaboxs, I output the registered data.
In the metaboxes themselves, I set the parameter to display these same data, so that each block displays the data that the user entered during registration.

Unfortunately, there are no parameters for output of the password.
in other words, can I now make the password line display the password itself ?
![Пароль](https://user-images.githubusercontent.com/47380983/80254542-0ec7c680-8684-11ea-988b-429aaced2d83.png)

**Comment by Floydtm** [comment]
@GOHA81177, hi! We cannot embed this in a plugin, it is not safe.
