### ISSUE TITLE
Editing woocommerce pages ( JetWooBuilder)

### ISSUE THREAD

**Issue by GOHA81177** [Crocoblock/suggestions#1165]
Just about painful !
Jet plug-in products are simply gorgeous... and of all this beauty I can not mention the lagging plugin JetWooBuilder which by and large does not bring anything new!

The question is
When can I use the JetWooBuilder plugin to edit woocommerce pages such as checkout, thank you pages, shopping cart pages, delivery options, etc.?

And will there be this feature at all ?

You of course know best. But this opportunity will greatly wipe the nose of your competitors !

**Comment by stasonua0** [comment]
I propose to combine with https://github.com/Crocoblock/suggestions/issues/498
