### ISSUE TITLE
Create a dynamic table with relative subproducts, using Crocoblock

### ISSUE THREAD

**Issue by Mallfox** [Crocoblock/suggestions#1168]
We have to convert-redesign a site (not based on woocommerce), to a wp-woocommerce one.
It has in the **product details page** a **table with (dynamic data)** with all the relative subproducts,
Example Screeenshot: [https://prnt.sc/s6ay8k]
(When we say subproducts we mean the same product with different weight, length and so on, namely **attributes** of the product) displayed in a list with the possibility to have **Add to Cart** in each of them.
The **Table** from Crocoblock seems to not having that deep approach about product attributes to achieve this result and certainly has not the capability to have the **Price** and the **Add to Cart** button. 
Table row with: the **product's thumbnail**, **subproduct's SKU**, the **product's attributes in columns**, the **price** and the **add to cart button** (not existing in the screenshot).

**Comment by MjHead** [comment]
This feature will be added as separate module with JetEngine 2.9.0. More details here - https://github.com/Crocoblock/suggestions/issues/3803
