### ISSUE TITLE
Merge Jet Woo Templates with Theme Builder

### ISSUE THREAD

**Issue by 3rinyes** [Crocoblock/suggestions#1174]
![Schermafbeelding 2020-04-27 om 22 28 40](https://user-images.githubusercontent.com/64439075/80417811-aae90c00-88d6-11ea-838c-539560b28754.jpg)
**Please, describe the feature request, making it clear to understand.**

JetWooTemplates are now situated underneath the WooCommerce tab in the WordPress toolbar. That was so confusing for me at first: why couldn't I see all the available JetWoo widgets in my single page template? I would love to have these JetWoo templates merged with the Theme Builder. And the JetWoo widgets in the standard widget list.

**Comment by johnbolandwp** [comment]
Agree.

**Comment by maljassem** [comment]
I support this also

**Comment by DmitryBychenko** [comment]
Right, group all Croco templates like E does. Everything in one place more or less.

**Comment by ElvinPeter** [comment]
And also take advantage of Elementors Conditions

**Comment by UraraReika** [comment]
As for now, we moved JetWooTemplates to JetPlugins admin dashboard menu page https://prnt.sc/t5ift3. But in the future updates we will fully merge this pages.
