### ISSUE TITLE
Can not translate buttons "Choose Media" and "ADD CUSTOM VALUE" with loco translate and another plugins

### ISSUE THREAD

**Issue by dislokacia** [Crocoblock/suggestions#1177]
**Describe the bug**
Want to translate buttons "Choose Media" and "ADD CUSTOM VALUE" with loco translate

**To Reproduce**
1. Create custom field media
2. Go to posts admin panel and try to translate these buttons

**Expected behavior**
Hope it will be possible!

**Screenshots**
[screenshot-2](https://user-images.githubusercontent.com/44621240/80473975-9006ae00-894f-11ea-9f71-5594d37661a0.jpg)

Forward to Dmitriy Bartoshchak

**Comment by kaskad88** [comment]
Added for the next version. 
Thanks for your report!
