### ISSUE TITLE
JetAppointment days off: from - till date

### ISSUE THREAD

**Issue by SarahvanGorp** [Crocoblock/suggestions#1179]
The appointment plugin haves the option days off. For each date you have to create a day off.
It would be fantastic if there is also the option for holidays with a from until date. 

With this solution you dont have to create single days for a holiday. For example a holiday of 14 days we don`t have to create with 14 single days. It would be much easier.

**Comment by creativemacmac** [comment]
bulk day off would be really helpful - think of the events that occur once a year - for example a concert or festival - a bit cumbersome to deselect all days of the year except one :)

**Comment by MakhonkoDenis** [comment]
Hi,
This feature appeared in version 1.2.2 https://prnt.sc/vy99zg
