### ISSUE TITLE
In jet menu (mobile),  top-level item's link (with sub items) don't work

### ISSUE THREAD

**Issue by dudurom** [Crocoblock/suggestions#1180]
**Describe the bug**
In jet menu (mobile),  top-level item's links don't work. it always goes to sub-item.

**short video explainer**
https://www.loom.com/share/2d046a1f398f4c99a0fc2d4db8261ab7

**To Reproduce**
1. create a mobile menu with sub-items
2. make the top-level items (which have sub-items) with link.
3. go the front end, try to navigate to top-level link. u will see that it always goes to sub-items and top-level link (that have sub items) can't be linkable.

**Expected behavior**
when clicking on arrow, i would expect to go to sub item.
when clicking on the text of the item, i would want to go to the link

**screenshot**
![image](https://user-images.githubusercontent.com/59249697/80496865-6a3ed080-8972-11ea-9e13-c594f4937e43.png)

**Desktop (please complete the following information):**
doesnt work on any system

**Smartphone (please complete the following information):**
doesnt work on any device

**Comment by Floydtm** [comment]
@dudurom, hi! check this [option](http://prntscr.com/s7td82). You need to select sub menu icon
