### ISSUE TITLE
JetEngine - form appointment_date 

### ISSUE THREAD

**Issue by SarahvanGorp** [Crocoblock/suggestions#1182]
With a form it is posibble to send it with a email.
There is already something solved wit the appointment date. Before it only showed the date, but now it also shows the slot time. But I realy want to show the slot end time also. 

For example, a bookings date now shows up as 28-04-2020 19.00 (date, begin time),  but I want to see it as 28-04-2020 19.00 - 23.00 (date, begin time - end time)

Is that possible?

**Comment by MakhonkoDenis** [comment]
In version 1.3.0, macros have been added.

Appointment Macros:
- %service_title% - Name of the appointment service.
- %provider_title% - Name of the appointment provider.
- %service_link% - Link of the appointment service.
- %provider_link% - Link of the appointment provider.
- %appointment_start% - Displays the date and time the appointment started. You can set the format for the date. Read more https://wordpress.org/support/article/formatting-date-and-time/ about the time format. For example: %appointment_start|format_date(F j, Y g:i)%
- %appointment_end% - Displays the date and time the appointment end. Also accepts date format.
