### ISSUE TITLE
JetSearch -- capability to search Product Attributes & Tags

### ISSUE THREAD

**Issue by jeff1osu** [Crocoblock/suggestions#1183]
I worked with Alex on your support team.  He confirmed there is no capability to search in Woocommerce Product Attributes and Tags via JetSearch.  This is critical as that is what I am using in JetSmartFilters so my users can find the right products.

**Comment by Floydtm** [comment]
I think Alex’s decision was wrong. AjaxSearch can do this. If you still have questions, please contact our support

**Comment by jeff1osu** [comment]
Floyd is this what you are referring to:

| 
Hello again, Jeff.
Take my sincere apologies, I didn't get the specialist correctly, it's not possible to search by product attributes or tags, using the "Search in custom fields" field, but you can do it like this = https://prnt.sc/s80pxs
That is, you should specify the Products in the Source field and then choose what you need in the Terms field.
Also, you must create those tags and attributes beforehand.
 |

Or do you mean it is possible via "Search in Custom Fields"?
    On Wednesday, April 29, 2020, 09:28:02 AM CDT, Floyd <notifications@github.com> wrote:  
 
 


Closed #1183.

**Comment by Floydtm** [comment]
Describe your request in more detail. In the first message you did not say anything about custom fields

**Comment by jeff1osu** [comment]
Sure -- I run woocommerce and am using Elementor.  I want the Ajax search to search across my Product Categories, which it does.  But I have setup several Product Attributes and Tags that I am using in JetSmartFilters so my users can find exactly what they are looking for.  The Ajax search does not search Attributes and Tags.  Originally, Alex thought I could specify the Attributes and Tags in the "Search in Custom Fields" and be able to search them...that works great for "_price" but I couldn't get it to work for me.  He then suggested trying to use the Terms = Products and using the "Include" field.  I added a bunch of individual attributes and one tag that I know I had setup on some products but the Search still didn't return results.
Thanks for your help!
    On Thursday, April 30, 2020, 01:33:36 AM CDT, Floyd <notifications@github.com> wrote:  
 
 


Describe your request in more detail. In the first message you did not say anything about custom fields

**Comment by Floydtm** [comment]
I understand you now. at the moment the plugin is not able to do this. we plan to do this in future updates

**Comment by jeff1osu** [comment]
Thank you Floyd.
    On Friday, May 1, 2020, 02:43:09 AM CDT, Floyd <notifications@github.com> wrote:  
 
 


I understand you now. at the moment the plugin is not able to do this. we plan to do this in future updates

**Comment by sakalcik** [comment]
Hi i am also iteresting in this functionality. Searc by tags, attributes

**Comment by TheAdminKing** [comment]
Yes I want this functionality. I mean when there is a spot that say Search In Custom Fields, but when you set it up to search in _sku or _price or _description it will not show any results if you type a sku a price or a random word in a description, then what does this field actually do only search custom fields in custom posts?

**Comment by x3mp** [comment]
Why is this closed? It's not added? Its not possible to search through Product Attributes and tags.
This is a serious lack of attention on the developers part!

**Comment by x3mp** [comment]
@Floydtm this is still not possible, why is this closed?

**Comment by MjHead** [comment]
Option `Search in taxonomy terms` added with 3.0.0 update

**Comment by Cornhul1** [comment]
i am trying to enable search for attribute but its setup as a custom attribute. any idea how i can get this to work?

**Comment by Crocoblock** [comment]
@Cornhul1 For now the Taxonomy select returns only taxonomies where `show_in_nav_menus` is true so that you can set option `show_in_nav_menus` on true https://i.imgur.com/zPgX5KN.png
Also, I'll create a separate issue for this
