### ISSUE TITLE
search for product tags (JetSearch)

### ISSUE THREAD

**Issue by blueberry11** [Crocoblock/suggestions#119]
In our case, one of our products is called "E-1", it is tagged with "e-1" and "e1". Since we sometimes get calls from clients which we help navigate the website to purchase, it would be great if we could simply say: "Please type e1 into the search bar", rather than "Please type e hyphen one into the search bar".

**Comment by MjHead** [comment]
Option `Search in taxonomy terms` added with 3.0.0 update
