### ISSUE TITLE
jetEngine: Allow Dynamic Field to show Post ID

### ISSUE THREAD

**Issue by gpolitog** [Crocoblock/suggestions#1191]
The Dynamic Field is able to show User ID, but not Post ID.  See attached image.

Between other use cases, this opens the possibility to construct dynamic shortcodes using the post ID.  That's the actual current use case I need it for.

![postID](https://user-images.githubusercontent.com/29667516/80721583-03313100-8ac4-11ea-9622-095f7558f475.jpg)

Regards.

**Comment by kaskad88** [comment]
Added for the next version
