### ISSUE TITLE
Wishlist variation support

### ISSUE THREAD

**Issue by petranca** [Crocoblock/suggestions#1192]
Variations are not supported. From my point of view a very important feature, because the usability suffers a lot and is a must in "every" professional webshop. That means, if the user adds a product variation to the wish list, the variation is not taken into account, but only the "global" product. When the user goes to the wishlist, he sees the "global" product, but he has to set again the whole variation selection, if he remembers it at all. However, the wishlist should avoid that the user has to remember it.

**Comment by Floydtm** [comment]
I understand that you need this functionality. I discussed this issue with the developers and should refuse you this question. We cannot implement it now, because it still depends on the woocommerce plugin

**Comment by petranca** [comment]
It is really very disappointing
