### ISSUE TITLE
Bug. Dynamic Field Text Align 

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1194]
Hello, if you select "Multiline" - https://prnt.sc/s8tm5t, then the headers in one line are not centered
If you select "To line" - https://prnt.sc/s8tmoo, then the headers in two or more lines - https://prnt.sc/s8tn2k become off-center

The request to make universal centering of the text, regardless of how many lines are in it.

/*Оригинал*/
Здравствуйте, если выбрать "Многострочный" - https://prnt.sc/s8tm5t, то заголовки в одну строку не по центру
Если выбрать "В строку" - https://prnt.sc/s8tmoo, тогда не по центру становятся заголовки которые в две и более строк - https://prnt.sc/s8tn2k

Просьба сделать универсальное центрирование текста, независимо сколько в нём строк.

**Comment by Floydtm** [comment]
@stasonua0 try to configure like this http://prntscr.com/s92sd6 http://prntscr.com/s92sly

**Comment by stasonua0** [comment]
Thanks, it worked.

пт, 1 мая 2020 г. в 10:52, Floyd <notifications@github.com>:
