### ISSUE TITLE
Pop up Windows during registration

### ISSUE THREAD

**Issue by GOHA81177** [Crocoblock/suggestions#1197]
In the plugin JetEngine made a registration form
How do I make a pop-up window appear after registration with a notification that you have "successfully registered" and also when the user logs out of their account ?

Can you implement this in future updates ?

**Comment by shinTM** [comment]
These are all custom solutions, but it is possible to open some popup using js script:
$( window ).trigger( {
	type: 'jet-popup-open-trigger',
	popupData: {
              popupId: <popup_id>
        }
} );
