### ISSUE TITLE
Search by other filter values

### ISSUE THREAD

**Issue by GOHA81177** [Crocoblock/suggestions#1198]
Can you consider searching by values of another filter?

The point is that I output the search filter and put the filter just below it... for example, Checkboxes...
and when I set a query in the search filter, The checkboxes filter starts displaying only the values that you set in the search query.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
