### ISSUE TITLE
JetEngine - Use Post Category as a Filter for Meta Boxes

### ISSUE THREAD

**Issue by Perchpole** [Crocoblock/suggestions#12]
Currently, when assigning meta boxes, it is only possible to use "Post Type" as a selector. The system would be far more powerul and flexible if were also possible to use "Post Category".

Posts are split into different categories for good reasons and each may require different meta boxes.

Note: ACF allows any combination of over 20 options.

Screenshot: http://prntscr.com/mnp2j4

**Comment by MjHead** [comment]
Hi @Perchpole Thanks for suggestion. You are not first who asking this :) And we'll definitely rewrite meta boxes management UI and on this stage we'll add a lot more options to control meta box appearance. But we need a bit more time to do this. Currently couple more features on the line for JetEngine, when we'll implement all of them, we'll start to work on new admin UI. I'll let you know here when some exact ETA will be available.

**Comment by absym** [comment]
Hi, nice feature, hope it will be possible to also assign a Meta boxe to a specific category of Woocommerce products ? The product management form can be very long with a lot of unused/unwanted fields depending on which kind of product you are working.  Any idea of when it will be available ?

**Comment by norbertfogarasi** [comment]
Any update on this?

**Comment by Perchpole** [comment]
I got tired of waiting so switched to another solution.

**Comment by norbertfogarasi** [comment]
You mean, another plugin?

**Comment by Perchpole** [comment]
A combination of CPT UI and Advanced Custom Fields. They work very well together.

**Comment by norbertfogarasi** [comment]
Yes, I used that combination. The only downside of ACF is that it doesn't have repeater fields. So if I need repeaters and custom meta boxes for categories I need to choose between them.

**Comment by Perchpole** [comment]
It does have repeater fields!

Also, use this: https://wordpress.org/plugins/acf-extended/

**Comment by kbcelik** [comment]
Hello. Any update on this? @MjHead

**Comment by dcambria** [comment]
Hi, need this feature too. 👍

**Comment by simonvanoordt** [comment]
+1

**Comment by Bookit24** [comment]
+1

**Comment by tole011** [comment]
This is so basic functionality. I'm a new user of JetEngine and can't believe that it's not there. Free combo of ACF and CPT UI (which I used so far) is becoming increasingly appealing to me.

**Comment by getunrealtoday** [comment]
+2 !!!!
I was very surprised to find that it is not possible to limit display of the meta box by product category or product type (simple / variable / bookable etc.) Holding off on ACF for now, but need this functionality soon please!

**Comment by tole011** [comment]
We are waiting for 2y and there is no meaningful answer from Croco... At least put a disclaimer in the comparison table that you can't provide such basic functionality. To be honest, I wouldn't spend money on your product if I knew about this, It's available in all similar products. This is not a way to treat your customers.

**Comment by Zegklitz** [comment]
+1

**Comment by pajtai** [comment]
This would be awesome 👍

**Comment by jarahner** [comment]
+1

**Comment by slaakk** [comment]
+1

I'll pull the trigger on the refund; JetEngine is great but this kind of functionality is basic.

**Comment by koolkarma** [comment]
Agree that it's needed!

**Comment by HazmeUnaPaginaCL** [comment]
+1... C'mon guys :D - Its gonna be 3 years since the request

**Comment by lifeact** [comment]
As a programmer, I understand that this change affects a lot of work, including with smart  filters. But three years is a lot

**Comment by MjHead** [comment]
https://github.com/Crocoblock/suggestions/issues/4234

**Comment by LuisCarrizo** [comment]
4 years!! unbelievable
