### ISSUE TITLE
Jet Engine Gallery field not visible in image gallery

### ISSUE THREAD

**Issue by luxpatrick** [CrocoBlock/suggestions#120]
<img width="950" alt="Screenshot 2019-03-20 at 11 02 27 PM" src="https://user-images.githubusercontent.com/48523191/54722256-65e79780-4b64-11e9-8d68-83175c574f2e.png">
**Describe the bug**
The custom field with an image gallery created with JetEngine cannot be called in elementors image gallery widget, a similar field created by pods or ACF is. 

**To Reproduce**
Should be clear. 

**Expected behavior**
Image gallery from JetEngine should appear in the widget dynamic content list. 

**Additional context**
the less plugins I have running the better, therefore I would like to see JetEngine as substitute for other CPT plugins.

**Comment by Floydtm** [comment]
Added in JetEngine 1.4.2
