### ISSUE TITLE
jetThemeCore prevents creating/editing Elementor Saved Templates

### ISSUE THREAD

**Issue by gpolitog** [Crocoblock/suggestions#1201]
While jetThemeCore is active, when trying to create/edit (Free) Elementor Saved Templates, error "content not found" occurs.  See image

![noContent](https://user-images.githubusercontent.com/29667516/80826123-46b09b80-8ba7-11ea-9289-b341d3cba817.jpg)

When jetThemeCore is disabled, no error occurs.
I already tried the different settings of jetThemeCore.  Se image

![themeCore](https://user-images.githubusercontent.com/29667516/80826236-84adbf80-8ba7-11ea-893a-aa25c81f7fbe.jpg)

I tried Elementor (free) 2.9.7 and 2.9.8.
I tried jetThemeCore 1.1.22 and 1.1.23.

In a production site, it is not an option to disable jetThemeCore in order to be able to edit an Elementor Saved Template.

Regards.

**Comment by Floydtm** [comment]
I checked your request and could not reproduce this bug. Please contact our [support](https://crocoblock.com/help-center/) team, provide access to your site and we will try to solve your problem
