### ISSUE TITLE
JetEngine: If Elementor gets deactivated, whole site crashs

### ISSUE THREAD

**Issue by secondsky** [Crocoblock/suggestions#1203]
**Describe the bug**
Deactivating Elementor Plugin (as long as JetEngine is still active) leads to a fatal error = site crash

**To Reproduce**
Deactivating Elementor leads to this error:
`An error of type E_ERROR was caused in line 29 of the file /var/www/vhosts/xxx.com/staging.xxx.com/core/modules/jet-engine/includes/core/dynamic-functions.php. Error message: Uncaught Error: Class 'Elementor\Controls_Manager' not found in /var/www/vhosts/xxx.com/staging.xxx.com/core/modules/jet-engine/includes/core/dynamic-functions.php:29 Stack trace: #0 /var/www/vhosts/xxx.com/staging.xxx.com/core/modules/jet-engine/jet-engine.php(224): Jet_Engine_Dynamic_Functions->__construct() #1 /var/www/vhosts/xxx.com/staging.xxx.com/wp-includes/class-wp-hook.php(287): Jet_Engine->init() #2 /var/www/vhosts/xxx.com/staging.xxx.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #3 /var/www/vhosts/xxx.com/staging.xxx.com/wp-includes/plugin.php(478): WP_Hook->do_action() #4 /var/www/vhosts/xxx.com/staging.xxx.com/wp-settings.php(540): do_action() #5 /var/www/vhosts/xxx.com/staging.xxx.com/wp-config.php(110): require_once('/var/www/vhosts...') #6 /var/www/vhosts/xxx.com/staging.xxx.com/wp-load.php(37): requir`

**Additional context**
WordPress version 5.4.1
Current theme: Hello Elementor Child (version 1.0.1)
Current plugin: JetEngine (version 2.3.3)
PHP version 7.4.5

**Comment by kaskad88** [comment]
Fix for the next version (2.3.4)
Thanks for your report!
