### ISSUE TITLE
💡 jetEngine: Add a "Listing Grid" heading to the block.

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1208]
When you're building highly dynamic layouts using Listing Grid and have multiple on the same page with a filtering system, it **would be essential** to have a heading attached to the listing grid. That way if you filter things and the query is empty, the heading can be hidden as well.

Currently, you can only add a custom heading above the listing grid as an external element, but there's no way to make that heading hide if the listing grid is empty.

This is a use case we're facing and the only way around it is to add an AJAX listener that tracks each listing grid query, and if empty, it picks the previous Elementor element and hides it. But it's a bit of an overkill when there could be easier ways to do it:

1) By having a before (or even after) template just like the Hamburger Menu;
2) By adding a property to all Elementor elements where their visibility depends on the Listing Grid's query, via ID or Class.
3) By having a simple heading field that is part of the element.

This would help A LOT of use cases on things we're working on, and I'm sure would benefit others as well.

[Internal Reference](https://support.crocoblock.com/support/tickets/9778)

**Comment by SatoshiNerd** [comment]
Please crocoblock this would be sooooooa amazing

**Comment by kaskad88** [comment]
For this case, you can use the `Query Has Items` dynamic visibility condition https://tppr.me/wuL4M and listing created with Query Builder
