### ISSUE TITLE
💡 jetEngine: Custom User Meta Fields

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1209]
jetEngine is a great way to structure meta data, but what it's missing is an efficient way to do custom user meta. Given the whole Fields API system that's already in place and the ability to show meta in blocks, it would make sense to be able to manage custom user meta fields using jetEngine as well.

[Internal Ticket](https://support.crocoblock.com/support/tickets/9782)

**Comment by Floydtm** [comment]
hi! Could you describe the request in more detail? if you can attach screenshots or video

**Comment by altechzilla** [comment]
Hey @Floydtm - Nevermind - it's actually already there under Meta Boxes but didn't notice it. My bad!
