### ISSUE TITLE
💡 jetEngine: Element-Level Access Control

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1210]
When building a membership platform or even an e-com site, there's plenty of cases where things should only be visible to a certain role, or based on a specific user meta.

There's already a system in place where you can dynamically show listing grids based on user meta, so it would be great to have something where you can make any block dynamic based on:
- User Role
- Logged In / Out
- User Meta Value

Here are a few use cases:
- Making certain header blocks hidden or visible when the user is logged in/out
- Making a block say "You must be logged in to view this"
- Displaying a block only to a sub-segment of users

[Internal Ticket With Examples](https://support.crocoblock.com/support/tickets/9781)

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0
