### ISSUE TITLE
🐞 jetStyleManager: When you save a skin, it doesn't save and show in the Apply Skin panel.

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1215]
When you save a skin, it doesn't save and show in the Apply Skin panel.

**Comment by altechzilla** [comment]
Seems to work for tabs, but not for listing grids.

**Comment by Floydtm** [comment]
@altechzilla 
this solution only works with the jetelements plugin

**Comment by altechzilla** [comment]
Then it shouldn't show on a listing grid when you right click or on other unsupported elements @Floydtm .
