### ISSUE TITLE
Fixed meta box for JetReview

### ISSUE THREAD

**Issue by luxpatrick** [Crocoblock/suggestions#122]
**Please, describe the feature request, making it clear to understand.**
Adding possibility to make a fixed meta box. 
In your documentation http://documentation.zemez.io/wordpress/index.php?project=jetreviews&lang=en§ion=jetreviews-start#jetreviews-dashboard

point 3. following I have to define the review fields every time I add an review to a post. I want to have a fixed meta box where I just fill out: Customer, Rating and a Customers conlusion (text). 

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already.:

no alternatives. I'm planning it to use it in a presentation of some customer projects where I want to add a customers review.

**Comment by shinTM** [comment]
Please use the new reviews widget available since v2.0.0
