### ISSUE TITLE
JetEngine: compatibility with RankMath SEO Plugin

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#1228]
RankMath SEO Plugin doesn't see what I write on JetEngine's custom fields. Thus I opened a ticket about it on RankMath support and they said you need to add their API on your system. Could you please integrate it? Following link has more detail:
https://support.rankmath.com/ticket/rank-math-wont-read-custom-fields-by-jet-engine/?view=all

**from ticket# 9933

**Comment by realstephenzhao** [comment]
I vote for this suggestion as I also use Rank Math SEO plugin.

**Comment by 3rinyes** [comment]
+1

**Comment by curtis-harley** [comment]
+1

**Comment by ideasebuild** [comment]
+1

**Comment by darkpheonic** [comment]
+1

**Comment by poziomapl** [comment]
+1

**Comment by bennybersier** [comment]
+1

**Comment by TheBigBanik** [comment]
4 months after the first request, nothing has been fixed concerning the compatibility with SEO plugins. Neither Rank Math or Yoast can support Jet Engine metqa fields and today I have also share the Rank Math Api to crocoblock. Let's hope that you will take this under serious concideration as we do to build SEO friendly websites.

**Comment by Sayeed1440** [comment]
@TheBigBanik , he is totally right.

It's a much needed update.

**Comment by Sayeed1440** [comment]
Hi Guys, Any Updates.

This is really important for us. Please understand.

**Comment by WardenCommander** [comment]
+1

**Comment by joseehilton147** [comment]
+1 important

ACF already have that,,, this is a must for SEO

**Comment by stasonua0** [comment]
Please increase the priority to complete this task, customers are very much asking to solve this problem, but do not redo all of them under ACF fields

**Comment by greggdev** [comment]
Super important! Please update for Rank Math or any SEO plugin compatibility

**Comment by futureyoon** [comment]
+1

**Comment by pravinlpatel** [comment]
+1

**Comment by greggdev** [comment]
Spoke with Crocoblock technical support in a very detail converstaion, and they said its NOT GOING TO HAPPEN.  They are not supporting any SEO plugins whatsoever!  I just dumped this product.  If you look at how they store and retrieved their meta data, its not fully compliant with Wordpress standards and function calls, ACF, PODS, Toolset and and custom post type generator will work better. Yes you don't get the Elementor integration but Elementor is pure bloatware anyway.

**Comment by TheBigBanik** [comment]
I had the same conversation yesterday and they said "Unfortunately, we do not guarantee the compatibility with 3-rd party plugins, the Rank Math could cause some issues still". Although Rank Math has an API for the compatibility which I have shared to the Crocoblock team 4 months ago. My solution is to use the ACF fields for content that matters in SEO and the Jet Plugins to build single pages, woocommerce archives etc. The nice thing here is that we can use the Jet plugins with elementor to load ACF fields, so we can mix them together.

**Comment by acornavi** [comment]
Any updates? This is a very important feature.

**Comment by acornavi** [comment]
> 
> 
> I had the same conversation yesterday and they said "Unfortunately, we do not guarantee the compatibility with 3-rd party plugins, the Rank Math could cause some issues still". Although Rank Math has an API for compatibility which I have shared with the Crocoblock team 4 months ago. My solution is to use the ACF fields for content that matters in SEO and the Jet Plugins to build single pages, Woocommerce archives, etc. The nice thing here is that we can use the Jet plugins with elementor to load ACF fields, so we can mix them together.

I also get this bad answer about compatibility. It is not very wise to create a plugin which is producing "invisible" data and invisible posts for search engines. I don't understand this logic. This is not even a feature, it is a must.

**Comment by travelgu** [comment]
+1 

Cant have a site with SEO and RankMath is the best

**Comment by EquilibriumTechx** [comment]
+1 needed feature

**Comment by ayhanmalkoc** [comment]
+1

**Comment by kaskad88** [comment]
Added in JetEngine v2.7.6

**Comment by TheBigBanik** [comment]
After a while I found out that to make this work we have to go to the Jet Engine main settings, SEO tab and select the meta fields we need to be parsed by Rank Math or Yoast. It is working fine. 5 stars to Crocoblock.

**Comment by stefanvandenende** [comment]
Where can I find the Jet Engine main settings, the SEO tab?

**Comment by kaskad88** [comment]
@stefanvandenende https://prnt.sc/135nwlf

**Comment by Rauljauregi** [comment]
Hi there,

Is it possible to to select on Rank Math a Taxonomy Term´s custom field ? I mean that I achieved to select a Custom Post Type´s custom field, but I cannot with a term´s field... I cannot even activate on the SEO tab on Jet Engine settings. 

Does anyone know something about this?
