### ISSUE TITLE
--- jet engine on hebrew wp dashboard broken layout ---

### ISSUE THREAD

**Issue by yaron86** [Crocoblock/suggestions#1235]
everytime i install jet engine i get this broken layout on Hebrew WP Dashboard (screenshot attached), it's unpleasant to work like that,

can you guys fix these issues and make it look stable?
it will be easier to understand the layout and the experience will be enhanced

screenshot:  
https://i.postimg.cc/Y04Zy4zs/96098680-10158658681459752-7214173635567681536-o.jpg

**Comment by pintolog** [comment]
I have this problem also
![image](https://user-images.githubusercontent.com/7497319/81047912-095c4e80-8ec4-11ea-817f-b2ebe084acc9.png)

**Comment by pintolog** [comment]
Also the popup that declares the post type is hidden in Hebrew interface
![image](https://user-images.githubusercontent.com/7497319/81049088-30b41b00-8ec6-11ea-835c-fe19f31b9d53.png)

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0
