### ISSUE TITLE
Delete :)

### ISSUE THREAD

**Issue by pintolog** [Crocoblock/suggestions#1236]
Hi,
When i'm working on a site that is Hebrew based language (RTL) the fields in the **Edit Post Types** dashboard are close to each other and the dashboard looks broken & uncomfortable to work with, I have attached a screen shot here.

Please fix this spacing problem so we will be happy to work on our sites,
Thanks.

![image](https://user-images.githubusercontent.com/7497319/81047564-57bd1d80-8ec3-11ea-899f-1d6c7dd984a4.png)

**Comment by kaskad88** [comment]
I merged this issue with #1235 , which is on the same subject so we could deal with it more efficiently.

**Comment by pintolog** [comment]
I just saw that there is one mor so you can delete this one :D
