### ISSUE TITLE
JetEngine - Allow Dynamic Field to show Post URL so that we can Filter field output

### ISSUE THREAD

**Issue by realstephenzhao** [Crocoblock/suggestions#1238]
I would like to create a dynamic QR code on my post page, but it can't be achieved by Dynamic Field currently because it doesn't allow Post URL / Permalink as source.

There is no Filter field output option in Dynamic Link widget, so I think the only way is to add Post URL as source to Dynamic Field widget.

**Comment by mboxhero** [comment]
This would be a time saver for me. I could just put it in the footer.
For now, I  created an option page and put in the url's manually to get me by for pages and metabox's in posts to pull the data from. Manual, but works for now.

**Comment by kaskad88** [comment]
Added in the next release ( 2.11.3 ). From v2.11.3 the `Post ID` will be convert to `Post URL` in the QR Code callback https://prnt.sc/26qjc5v
