### ISSUE TITLE
Sliders with two column

### ISSUE THREAD

**Issue by jojobali** [CrocoBlock/suggestions#124]
Hi, at the moment elementor has basic slider with color or image background and text/description. Is there any possibilities to add additional slider functions so in each slide we can have an image in left column for example and title/description/button on the right column.

**Comment by kaskad88** [comment]
In the next version (1.15.14) will be added the ability to use Elementor templates in the Slider Widget. This new functionality will help you in creating two columns in the slide.

**Comment by jojobali** [comment]
Wow... perfect
