### ISSUE TITLE
Timeline Widget - Adjacent images option

### ISSUE THREAD

**Issue by sonjachisnall** [Crocoblock/suggestions#1240]
When using the **vertical timeline** with **centre alignment**, the text sections alternate on the left and right. This is great but when images are added they go right above or below the text leaving a lot of empty vertical space on the opposite side and this lengthens the page altogether. 

If you could create an option for the images to be adjacent to/opposite side of the text when the vertical timeline is centre aligned this would be a huge help and solve mine and my clients needs.

I tried using the left and right vertical alignment but the text becomes too long for readibility as it spans two column widths. If you could also enable a padding option for the text and images apart from the timeline line then we could reduce the appearance of the text as super lengthy. 

But the adjacent images first please.

**Comment by Floydtm** [comment]
Could you describe your request in more detail. provide a screenshot or video. Thanks you!

**Comment by sonjachisnall** [comment]
![screenshot](https://user-images.githubusercontent.com/33021524/84586994-aae5a100-ae6f-11ea-847b-5db316dc42d5.jpeg)

Here's an annotation of how I imagine it'd be with the images opposite the text on the other side of the timeline.

**Comment by kaskad88** [comment]
Added in 2.3.1
