### ISSUE TITLE
Widget Portfolio Font Awesome 5

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1241]
Hello, consider choosing icons from the FA5 set or custom icons uploaded by the user in the Jet Elemenets> Portfolio plugin - https://prnt.sc/sceqhh

/*Оригинал*/
Здравствуйте, рассмотрите возможность выбора иконок из набора FA5 или кастомных иконок загруженных пользователем в плагине Jet Elemenets > Portfolio - https://prnt.sc/sceqhh

**Comment by kaskad88** [comment]
Added in 2.3.1
