### ISSUE TITLE
Show Smartfilters only on specific taxonomy or category

### ISSUE THREAD

**Issue by purepixels** [Crocoblock/suggestions#1245]
The possibility to show a Smartfilter only on a pecific taxonomy or category.

The functionality is called: Display conditions.

For example when you visit a product category page (woocommerce), you see the ability to filter on product tags.

Live example: https://www.mavalanederland.nl/product-categorie/gezichtsverzorging/

Tag filter is only visible on this category.
I managed to do this with a 3rd party plugin. It would be easier to do this with SmartFilters itself.

**Comment by Floydtm** [comment]
You can use Dynamic Visibility module for Sections/Columns/Widgets https://github.com/Crocoblock/suggestions/issues/1338
