### ISSUE TITLE
Filter content in Dynamic repeater.

### ISSUE THREAD

**Issue by diecreativo** [Crocoblock/suggestions#1246]
Hello, my suggestion is for JetEngine for repeater fields.

I have seen the need to create a series of fact sheets, which JetEngine and Dynamic repeater works perfectly.

The problem arises when I need to generate a filter.

It would be nice to be able to add a function that you can type into Before items markup, which allows you to create a filter tab and thus be able to filter the Dynamic repeater items.

Or see how JetSmart Filters can work with Dynamic Repeater.

**Comment by anderoav** [comment]
Any updates on this?

**Comment by fernando-partridge** [comment]
+1 On this. Very surprised (and frustrated) that this isn't possible already. 
I am using the repeater function to add Report attachments with custom fields to a page. Once there are more than a handful, a sort filter option on the front end becomes absolutely necessary.

**Comment by Willitbang** [comment]
+1

**Comment by Sayeed1440** [comment]
+1

**Comment by ivanyu8** [comment]
+1

**Comment by scotianu** [comment]
Any update?

**Comment by scotianu** [comment]
I belive no

**Comment by BaronVonDerpsalot** [comment]
+1 please! 
I want to be able to create an options page with repeaters and only display entries based on their contents.

**Comment by GaribayMarketing** [comment]
Any update?

**Comment by Duuble-U** [comment]
I need it often ! It would be very cool :-)

**Comment by lamlai** [comment]
+1

**Comment by leorcdias** [comment]
I want this too!

**Comment by AnkitLawctopus** [comment]
Everyone wants this. why isn't it done yet?

**Comment by aureliolk** [comment]
Any Update ?

**Comment by b6web** [comment]
Any update?

**Comment by fbeach73** [comment]
long overdue on this imo...

**Comment by jorgesan07** [comment]
+1

**Comment by unbrandeduser** [comment]
+1

**Comment by dudynets** [comment]
+1

**Comment by MjHead** [comment]
This can be accomplished by Repeater Query + Listing - https://tppr.me/jdlfe

**Comment by valneimota** [comment]
+1

**Comment by eraqueldamas** [comment]
+1

**Comment by alexilal** [comment]
+1
