### ISSUE TITLE
💡 jetEngine: Essentials --- Listing grid should have a lazy load option

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1247]
When on a page with a ton of listing grids (on a content-rich site/platform), it takes a lot of time to run queries. 

The listing grid element should have the option to lazy load once it gets into view (with an option for offset so that it starts loading right before the element enters the view).

Also, when using a slider, there should also be an option to lazy load items when sliding (Slick JS already has that I think).

**Comment by altechzilla** [comment]
Thanks for considering this @Floydtm - can't wait to have it up! I think that by having listing grids be loadable via AJAX we'll see massive performance improvements. Even more if there's also lazy loading while sliding.

**Comment by Gidsa** [comment]
I'd also love to see a lazy load function for the Listing Grid widget. My site has loads of posts and the 'load more' function is just too cumbersome to implement each time.

I would also be great to have the option to 'select number of posts to display before lazy load begins'.

**Comment by petranca** [comment]
It would be great if "Load more" and "Lazy load" would also work with the archive enabled.

**Comment by futureyoon** [comment]
I see those tasks regarding infinite scroll were merged into this..

and all of tasks status is closed. so I would like to confirm if 'infinite scroll' in jetblog has been implmented?

or it's 2 different issues? 

What i need is jetblog infinite scroll 
Anyone can confirm this?
