### ISSUE TITLE
WooBuilder - impossible to use because ProductLoop does not have settings!

### ISSUE THREAD

**Issue by justdudeone** [Crocoblock/suggestions#1250]
Although some might see this as a new features request - if you will read - you will understand that this is a VERY IMPORTANT BUG (subquality work).

Your WooBuilder gives possibility to create for a WooCommerce Shop Products Grid a custom product card style. (BTW it's name at WooBuilder are also must be changed because create a misunderstanding - it's NOT an archive). This custom product card style for a WooC Shop Product Grid creating can be used at Elementor ONLY via your WooBuilder ProductLoop widget, your widgets ProductGrid/List does not use it! But ProductLoop widget does not have no one settings for a grid/list styling-tune - margin / padding / individual number of items per product category / absent of a ProductLoop Grid/List view switching, etc.

Without those options users need to have a deep CSS knowledge to tune WooC Shop ProductLoop from a WP frontend customizer with direct coding - this completely destroys the "fully Elementor"  concept of your plugin! Most of your clients just don't know manual CSS coding at all!

So you need to:
1) Rename function on a screenshot to a "Shop Product Grid custom product card style" or just "Shop Product Card style" etc to avoid a mess with an absolutely different Archive PAGES at WP/WooC/Elementor.
![JET_WooBuilder_SetArchiveTemplate](https://user-images.githubusercontent.com/43311177/81379710-4453c180-9112-11ea-8d4b-0ab945748117.png)
2) Add grid settings and styling options etc to a ProductLoop widget, you can simply copy them from ProductGrid widget.
3) Add one more template to #1 for a WooC Shop Product LIST VIEW and at ProductLoop widget add to frontend a views switching possibility with button.

**Comment by Floydtm** [comment]
@justdudeone, hi!
1. We are not plaguing to do this.
2. The product loop widget does not have any settings because it only outputs products. All settings with regards to columns and indents you need to do in the archive template https://prnt.sc/skdgq4 or in the customizer settings https://prnt.sc/skdha5
3. I think we will do it soon.

**Comment by justdudeone** [comment]
1. TT.
2. TT do you try to use it even one time with custom themes??? your allegedly custom products loop inherit many themes settings for ul/li margin, padding, etc and your crococoblock does not have possibility to edit them.

Overall "under your command" you again make the same useless-crooked shit as your Cherry Framework which no one does not need.

GLHF stay with your crap and stubbornness.
