### ISSUE TITLE
Ability to use lat/lon coordinates for marker positions in Jet Engine Map Listing

### ISSUE THREAD

**Issue by dzined** [Crocoblock/suggestions#1251]
Would be nice in jet engine maps, if we could provide lat/lon coordinates instead of an address for the markers that would be amazing and an address isn't always suitable

And perhaps further down the road other integration like what3words

**Comment by kaskad88** [comment]
This feature is already available https://gyazo.com/5eaa3d3c828070b89842d76ea1915882
