### ISSUE TITLE
Feature Suggestion: Sorting option for Listing Grid Widget

### ISSUE THREAD

**Issue by pedrostein** [Crocoblock/suggestions#1254]
Hi crocoblock Team 

It would be great if there would be a possibility to have an option for sorting the listing grid queries.  

This would be useful for example when using relationships to sort by a field value like for example "Title" or a custom field available in that listing grid

**Comment by realstephenzhao** [comment]
Isn't there an Sorting Filter from JetSmartFilters already?

**Comment by pedrostein** [comment]
@realstephenzhao thanks for pointing out the option to use Smart Filters. 

But what if you just want to have a default sorting without using frontend controls like in this example: 
Workshop with a list of participants which is sorted alphabetically by Last name where you have a CPT for Workshops and a CPT for participants. 

In this case it would be even good to have two sorting levels where primary sorting is by last name and secondary sorting is by first name so the result would look like this: 

Miller Anna
Miller Bethany
Miller Claire  
Morton Felicia
Morton Jim
Morton Tony

**Comment by Floydtm** [comment]
@pedrostein, hi! Describe your request in more detail with screenshots or videos. How do you select the list of participants? if I understand you correctly, do you need to sort the list itself inside the item?

**Comment by pedrostein** [comment]
Hi @Floydtm 
thanks for your reply 

here is an example with screenshot and you can see the related posts are not sorted by Title and are sorted by post date. 
![Parent with Children in Listing Grid](https://user-images.githubusercontent.com/1089812/82333923-9c7aa580-99e7-11ea-8bfa-970499f643d7.JPG)

So it might be great if in the Listing Grid widget would be an option to choose how to sort the content of the Listing Grid, like for example Sort by Title, custom field value, custom date etc 

![Listing Grid Widget](https://user-images.githubusercontent.com/1089812/82334727-a94bc900-99e8-11ea-9a3b-ca8cbcaaa5e0.JPG)

Also this might be a nice option when using dynamc fields with related lists
![Dynamic Fields Related Post List Callback ](https://user-images.githubusercontent.com/1089812/82333940-a00e2c80-99e7-11ea-8145-04bc4746b95e.JPG)

**Comment by Floydtm** [comment]
@pedrostein, hi! You probably didn’t notice these settings in the list grid https://prnt.sc/spaapo as regards the dynamic field. we need time to study this issue. Thanks you!

**Comment by pedrostein** [comment]
Hi @Floydtm thanks for the helpful hint which solves the sorting in the Listing Grid. 

Even sorting with multiple levels like in the example above (Sort by name and then by the first name) works nicely. 

Maybe it could be helpful for new crocoblock users if this awesome feature is described in the tutorials a bit more in detail. 

As for the Dynamic Field, it would be nice to have these sort options too if possible, but as a workaround using a listing grid is a possibility too, even if its not so straight forward from the UX perspective.

**Comment by joy-hancock** [comment]
I just stumbled across this thread because I was having the same sorting issues.  Thanks so much for the helpful hint as well.  I agree that the tutorials could have a lot more detail about how this feature works.
