### ISSUE TITLE
Add a style tab in WooCommerce Sale Products  Widget

### ISSUE THREAD

**Issue by paolajolley** [Crocoblock/suggestions#1257]
I was told to ask for a request here since my ticket was not able to be resolved.  Add a style tab in WooCommerce Sale Products  Widget or in any widget it takes WooCommerce Style as refrerence.  Now With the possibility of add styles in the theme builder as part of the hello theme. will be nice if the widgets follow that instead of WooCommerce.  Many thanks in advance.

<img width="311" alt="Screen Shot 2020-05-07 at 11 09 08 AM" src="https://user-images.githubusercontent.com/65026272/81442933-7c72f880-9142-11ea-97ea-ffb1afcc91cf.png">

**Comment by Floydtm** [comment]
@paolajolley, hi! This widget simply processes the shortcode and displays the products, its appearance depends on the theme styles. If you want to change its appearance then use the jetwoobuilder plugin https://prnt.sc/sjg84o
