### ISSUE TITLE
💡 jetElements: Add Support for (Dynamic) Images on the Drop Bar Trigger

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1258]
It would be extremely useful if you could add the ability to have an image on a drop bar element. That way you could use it to create a profile picture drop down with links. For an easy reference, you can check out GitHub's profile picture top right. It's such a common pattern that I think it should be an essential addition to the block.

**Comment by kaskad88** [comment]
Added in 2.3.1
