### ISSUE TITLE
Feature Suggestion: JetWoobuilder Custom Button Text "Select Options"

### ISSUE THREAD

**Issue by NeoAcla** [Crocoblock/suggestions#1260]
Hi crocos!

I think since we are in customizing every bit in all areas of WP and even woocommerce.
I am thinking if we can add a feature for the variable products which has a "Select Options" button to be customizable whatever you want to name the button.

Key features:
You can rename the button by, single product or by category product or even by taxonomies which will only take effect.

Usage:
This is a better understanding when you have a button like this to your variable products.
My scenario is from what I am currently working right now, i have a variable product that it needs to choose a location first before they can add to cart.
So it would be nice if instead a client will see a button Select Options, we can rename it to Choose Locations. And this custom button will only affect the selected category or item.

I hope you get it what I mean. and finger cross that it will be doable and added to a new features soon.

Thanks
Neo

**Comment by Floydtm** [comment]
@NeoAcla, hi! I understand you, but at the moment we can’t implement this in the plugin. This function relates more to the woocommerce plugin itself. I think you can do it yourself. You need to contact woocommercee support
