### ISSUE TITLE
Z-Index for the Hotspots Tooltip

### ISSUE THREAD

**Issue by NeoAcla** [Crocoblock/suggestions#1261]
Hi

First of, i was in contact with the support last week regarding this issue, and she did try to help me solve the issue but unfortunately with all the codes that she recommended it didn't solve my issue.

I think this is just a minor issue with the Hotspots Tooltip but still its better to improve.
Below attached image on what my issue is.
If you check closely the image, the circled in reds are the hotspots, and the rectangle apple green color is the tooltip.
When i hover the B1 hotspot it will show up the tooltip, the problem is that the tooltip is under the hotspots, the z-index ordering should be the tooltip is on top of all hotspots when hovered or opened.

![padel tooltip](https://user-images.githubusercontent.com/19571084/81491564-eb666380-92a0-11ea-9060-cb3fe961ffc7.png)

I hope you understand what i am explaining.

For the meantime as much as possible I am trying to reduce using additional plugins out from crocoblocks, while this issue is still not resolve i am using other plugins widget for Hotspots Tooltips.

I just hope this will resolve immediately so i can use your Hotspots Tooltip widget.

Thanks again

**Comment by kaskad88** [comment]
Fix for the next version.
Thanks for your report!
