### ISSUE TITLE
💡JetEngine / JetWooBuilder -- Listing Design -- Toggle Button

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#1262]
Add a 'toggle between' button on the WooCommerce product archive allowing users to switch between a regular grid layout and list layout.

Example setup: Create the listing as they would usually be created - add the new 'Toggle between' widget and select which listing templates you wish to flip between.

**Comment by UraraReika** [comment]
JetWooBuilder 1.7.0 release!
