### ISSUE TITLE
Possibility to make relationship to the same post type

### ISSUE THREAD

**Issue by mahroch** [Crocoblock/suggestions#1263]
I have multiple uses of relationship to the same post type and cannot figure out why it is not possible. 

This is the example of use:

I have a gardening web with PT Vegetables (it means onion, carrot, strawberries, tomato, ...) and I want to make a field to show 'good' neighbors. It means, in garden eg. carrot is good neighbor of onion and tomatoes but not strawberries. And of course, I want to make relationship to point parent and child to the same PT Vegetables. If eg. carrot is good neighbor to onion, then of course onion is good neighbor of carrot. And that is not possible (parent and child cannot be the same PT), neither any workaround.

Other examples are obvious - players in team they form a good group, books they are related to other books etc.

I believe that it shouldn§t be a big problem to enable it.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin. But you can use a post type meta field. This way you can link the posts you need https://prnt.sc/sixrio
