### ISSUE TITLE
Feature request: Jetwoo checkout page sections widgets

### ISSUE THREAD

**Issue by poehaldur** [Crocoblock/suggestions#1267]
I know that checkout page is one single form but would it be possible to build widgets that would help changing the form layout without touching any code?

Like for example you would have widgets:
- Billing Details
- Shipping Details
- Additional Information
- Coupon
- Login reminder
- Order review
- Payment section
- etc

That way you could truly customize the checkout experience.

**Comment by NeoAcla** [comment]
I agree on these

**Comment by HermesMacedo** [comment]
I agree on these
