### ISSUE TITLE
Add to some JET ELEMENTS widgets Dynamic Data

### ISSUE THREAD

**Issue by Rocketzzz** [CrocoBlock/suggestions#127]
Is it possible to add dynamic data in all these widgets? Very need...

![222](https://user-images.githubusercontent.com/48887369/54882177-6c2d8a80-4e68-11e9-894c-1d3cc3450cab.png)

**Comment by aksamitnaya** [comment]
Unfortunately, currently Elementor doesn't allow to manage Number Controls dynamic data. Our team will follow up on Elementor updates, and will add this option as soon as we have an opportunity to do that.
