### ISSUE TITLE
 Wordpress detects an error in class-jet-elements-db-upgrader.php

### ISSUE THREAD

**Issue by SoCarbone** [Crocoblock/suggestions#1271]
Hello,

the plugin works correctly and no display problem has been detected on the site but Wordpress detects an error of type E_ERROR in the file class-jet-elements-db-upgrader.php.

Here is the message received by email:
Uncaught Error: Class 'CX_DB_Updater' not found in /www/wp-content/plugins/jet-elements/includes/class-jet-elements-db-upgrader.php:48

Here is the current configuration of the site:
WordPress version 5.3.3
Theme : Jupiter X child (version )
Plugin : JetElements For Elementor (version 2.2.14)
PHP version 7.0.26

I remain available if you need more information.

Regards,
Alexis

**Comment by kaskad88** [comment]
We tried to reproduce your issue based on the information you provided, but without success.

Please contact our support at support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
