### ISSUE TITLE
jetEngine metabox for WC product variations

### ISSUE THREAD

**Issue by petranca** [Crocoblock/suggestions#1273]
I know it's a complicated matter, but it would be a great feature and a USP for jetEngine if you could add metaboxes to product variation.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by danielemuscia** [comment]
Guys pls work on it because this is a killer feature and it is really what it is missing on the woocommerce side for now

**Comment by jrlopezd** [comment]
Guys this function is super interesting, I hope you can implement it as soon as possible

**Comment by lolomarchal** [comment]
Hey. I, my clients and my partners need this functionality. But I see that since May 2020 there is no one to provide us with a solution.

**Comment by su69ar** [comment]
There's no follow up yet till now :(
