### ISSUE TITLE
JetSmartFilters - In Stock/Out of Stock toggle or button

### ISSUE THREAD

**Issue by TheOriginalBeef** [Crocoblock/suggestions#1274]
My Woocommerce Store has numerous products we stock, of which not everything is in stock at every given time. Stock is dwindling during this lockdown period - at the moment, site users are having to scroll through a lot of "out of stock" products (which I can only imagine is off-putting). I believe an Availability Filter would assist with this.

I know it is possible to toggle out of stock products not to show on the store page, but I would rather not do this - we have a feature whereby customers can be notified when an item is back in stock and it does assist in closing sales that would have otherwise been lost.

**Comment by Floydtm** [comment]
@TheOriginalBeef, hi! You can implement your request right now. You need to create a filter like this https://prnt.sc/sist5p and display it on the page with the products https://prnt.sc/sisyna https://prnt.sc/sisyyl
