### ISSUE TITLE
JetSmartFilters - Shortcodes and Js overlays not working.

### ISSUE THREAD

**Issue by bradkins** [Crocoblock/suggestions#1276]
**Describe the bug**
If a smart filter or load more button is applied to a listing, shortcodes will no longer work. One of the shortcodes for example is a Stripe Simple Pay shortcode that initiates a Js overlay popup purchase form. When a filter is applied, the pop-up forces to open another page instead of an overlay. 

**To Reproduce**
1. Place JetFilter on a JetListing 
2. Filter the listing
3. Try a shortcode

**Expected behavior**
The shortcode will not display, or if it does display it doesn't function properly. 

 - OS: iOS Mojave
 - Browser: chrome, safari

**Comment by Floydtm** [comment]
@bradkins, hi! To solve this case, you better contact the support service, provide access to your site and we will try to solve it
