### ISSUE TITLE
Jet smart Hierarchical filter to navigate to a category Archive page

### ISSUE THREAD

**Issue by LovelyCupOfTea** [Crocoblock/suggestions#1278]
JetSmartFilters;

The ability to use Jet smart filters Hierarchical filter on a pop up or embedded in a page, to drilldown to a category. 

The apply button would then load the woocommerce archive page for that category. 

Example: decalgirl.com, see category drilldown on top banner

Hierarchical filter on home page to navigate directly to a product archive. 

I cannot currently see an effective alternative product, JetSmartFilters is great due to well implemented mobile support with the filters already in place, just need the button to navigate to the filtered category page. 

already discussed with Veiki who has advised it is not currently possible.

**Comment by LovelyCupOfTea** [comment]
Any Chance of an update on this please? If it is easy to implement it would be highly useful.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
