### ISSUE TITLE
Responsiveness option for Dynamic Field Image Gallery Slider

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#128]
Need add responsiveness option (https://prnt.sc/n2jyda)

I just create a dynamic Filed - gallery image slider.
I choose slides to show = 4. Work fine.
BUT, on tablette and phone, it's 4 too, can't change that (https://prnt.sc/n2jqmn). I need to can change the number (2 tablette and 1 mobile)

**Comment by MjHead** [comment]
Added in JetEngine 1.4,0
