### ISSUE TITLE
  сделать новый шаблон для портала

### ISSUE THREAD

**Issue by kinorki** [Crocoblock/suggestions#1282]
Добрый день
Я поискал в готовых шаблонах но не нашел, не могли бы вы сделать новый шаблон для большого портала
Свадебного допустим, да и если там будет опция для регистрации клиентов будет отлично. 
Очень понравился ваш сервис большое спасибо

**Comment by kinorki** [comment]
[https://marry.ua/](url)

Это я покопался нашел пример

**Comment by Floydtm** [comment]
@kinorki We will consider your issue. I close it because it is not related to the development of plugins. Thanks you!
