### ISSUE TITLE
💡 jetEngine - Add a "Edit Meta Box" cog in the admin area.

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1283]
Adding a cog with a link to the meta box would dramatically save time when building up meta boxes. ACF does that and it's a great feature.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/8274669/81816462-e0b70300-951a-11ea-8f1c-d7a563398c84.png">

**Comment by altechzilla** [comment]
Right there by the caret to the top right.

**Comment by MjHead** [comment]
Added with v.2.3.6
