### ISSUE TITLE
💡 jetEngine: The ability to pick icons using the Elementor Icon Picker.

### ISSUE THREAD

**Issue by oalexdoda** [Crocoblock/suggestions#1284]
When using custom icon packs, such as Font Awesome 5 Pro - Light, it would be extremely useful if all icon pickers (throughout the plugins, including jetMenu, jetEngine, etc.) would support the Elementor icon system.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/8274669/81816738-4905e480-951b-11ea-9890-c315bd1fc438.png">

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/8274669/81816781-56bb6a00-951b-11ea-9145-e199a3a7d342.png">

Elementor Custom Icons:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/8274669/81816826-65098600-951b-11ea-83f4-dc2b4599f0b4.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/8274669/81816935-866a7200-951b-11ea-8a83-adeb0238d917.png">

**Comment by pixelmultiplo** [comment]
+1

**Comment by WEBLOTI** [comment]
Exactly, it would be very useful!

**Comment by kellyrenee814** [comment]
Yes, please add this. Elementor has the icons I need and Jet Engine does not (ACF does).

**Comment by Dennisvb** [comment]
This would be very usefull

**Comment by simonst** [comment]
any plans to include this?

**Comment by tusamni** [comment]
+1 this would be great to have.

**Comment by tony-keller** [comment]
@Crocoblock can we have this sorted ? I followed elementor guidelines and still find this issue. 
See : https://elementor.com/help/speed-up-a-slow-site/

**Comment by bursacmilan** [comment]
+1 This would be very useful

**Comment by simonst** [comment]
+1 I would appreciate this as well

**Comment by Duuble-U** [comment]
Yes very useful improvement.

**Comment by unitedonline** [comment]
Hi,
was this issue ever sorted out by the development team?
It has been over 3 years from what I can see.
It would be great if they implement it.

**Comment by eobotrd01** [comment]
Hello guys, any news about the implementation of the Elementor icons in the jet engine? Wow, more than 3 years and crocoblock doesn't help the community :( I'm not even able to use the jet engine's own iconpicker some icons like: fa-glass doesn't appear in front end when I use embed icon from iconpicker. Please does anyone know how to solve it that?

**Comment by fostira** [comment]
+++1 Would be really great if we could get more or better set of icons in the icon picker field. The current one is outdated and not useful for a wide range of customers.

**Comment by DogG0d** [comment]
+1

**Comment by Pigitale** [comment]
I would love this

**Comment by jspassov** [comment]
+++2

**Comment by NicholasMancini6** [comment]
+++1, It's been 3 years, please.

**Comment by NicholasMancini6** [comment]
Just had a quick chat via Messenger with support, reported this issue but they still have no solution at the moment. I am trying to use custom icons for the icon picker but had no success. Do you guys use/know any workarounds to replace those icons with custom ones?

**Comment by Duuble-U** [comment]
> Just had a quick chat via Messenger with support, reported this issue but they still have no solution at the moment. I am trying to use custom icons for the icon picker but had no success. Do you guys use/know any workarounds to replace those icons with custom ones?

I finded a workaround. Not perfect but 🤷🏻‍♂️ : 

1. I made a text field.
2. In the text field I put the code of the icon. « fa-user »
3. In description of the field a link to the list of icon.
4. In the template, add a dynamic field where you add html code arround %s, in the customised output : `<i class="fa-solid %s"></i>`

**Comment by NicholasMancini6** [comment]
I did almost the same thing, but I'd like to have a dropdown menù for the client to choose from... just to make it User Friendly. 
I'll try to do something else and then post it here if I find something better!

**Comment by fonderco** [comment]
Any update to this?  Having an iconpicker without being able to load in custom icons isn't helpful.

**Comment by vcpaige** [comment]
+1 This would be great. Not being able to pick a custom svg icon that I've uploaded to the media library has been an issue during many website builds.

**Comment by Crocoblock** [comment]
was released in 3.4.0
