### ISSUE TITLE
After updating Elementor and Elementor PRo to the latest versions, the JetProductGallery plugin is causing JS conflict

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#1287]
After updating Elementor and Elementor PRo to the latest versions, the JetProductGallery plugin is causing JS conflict when editing any page. I need to disable it to edit with Elementor.

**Comment by Floydtm** [comment]
@marcofrasson, hi! We could not reproduce the bug on our site. Please contact our support team and we will try to solve your problem.
