### ISSUE TITLE
JetSmartFilters 1.8.0 - CSS Reset Toggle Not Working

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#1290]
The bug is that using Astra theme when switching on the CSS toggle to reset to whichever the browser being used the style of the select field remains.

**Comment by Floydtm** [comment]
@iamdanbarrett, hi! Could you describe the bug in more detail. provide screenshots or video if possible

**Comment by iamdanbarrett** [comment]
hi sure see this video here: https://www.loom.com/share/a4d80d8451324810b21547bccf8291fe

**Comment by iamdanbarrett** [comment]
Jus to assist in the investigation a little further... https://www.loom.com/share/1c89a0908c2b4e6b979f73d9df6920e9

**Comment by Floydtm** [comment]
@iamdanbarrett, try to instal this version of the plugin. Let me know if this helped.
[jet-smart-filters-master.zip](https://github.com/Crocoblock/suggestions/files/4629734/jet-smart-filters-master.zip)

**Comment by iamdanbarrett** [comment]
@Floydtm No it is still the same

**Comment by Floydtm** [comment]
@iamdanbarrett, we are working on it. in the near future we will release an update

**Comment by iamdanbarrett** [comment]
The near future? It has broken all the fields on my website...
