### ISSUE TITLE
Sort by filter

### ISSUE THREAD

**Issue by TheBigBanik** [Crocoblock/suggestions#1291]
Hi, since the jet engine and woobuilder create a totally custom archive pages, there is no way to sort by price or anything else like in the most woocommerce themes. Maybe you should add the sort by option in the smart filters so we can create a new filter with the options for sorting in a drop-down. Not only for woocommerce but for posts too so we can sort posts by date, name or other meta field.

**Comment by iamdanbarrett** [comment]
You can do, you use the sort widget and set the parameters you want.
<img width="301" alt="Screenshot 2020-05-14 at 15 42 06" src="https://user-images.githubusercontent.com/3041238/81948389-95275680-95f9-11ea-87d5-e8d0fb965a13.png">

**Comment by TheBigBanik** [comment]
Perfect, thank you so much for your help.

ANGRY PARROT CREATIVE STUDIO
Νικηφόρος Μπάφας
Art director
www.angryparrot.gr
___________________
2651066987-6972923992

**Comment by iamdanbarrett** [comment]
You are welcome :)
