### ISSUE TITLE
JetAppointments Add support for guest booking, new user & login

### ISSUE THREAD

**Issue by Juanto77** [Crocoblock/suggestions#1293]
As it sits JetBooking requires you to be logged in before you can interact with the calendar which is a huge hindrance for me. It would be very beneficial to allow users to schedule through JetAppointments even if they aren't logged in so we can capture the user data and automatically create an account for them.

**Comment by Juanto77** [comment]
I may have fixed it the original issue I had. I use litespeed webserver which comes with a cache plugin, the calendar wouldn't load for non-cached users because the Rest API was being cached. I'm not sure if anyone has had this issue before but this was my resolution to it.

**Comment by iamdanbarrett** [comment]
@Juanto77 I also use LiteSpeed as my server choice - would it be possible to let me know what exclusions you made incase I need this for the future?

**Comment by Juanto77** [comment]
@iamdanbarrett Sure thing!

In your WP dashboard:

1) Turn off Rest API Cache Under
 Cache > Cache > Rest API

2) Add all of the URLs where the appointment blocks will exist to 
Cache > Excludes > Do not Cache URLs 

3) Add the same URLs as above to
Page Optimization > Tuning Settings > URL Excludes

If you have any more questions please feel free to let me know.
