### ISSUE TITLE
JetBlog - Smart Posts List - Allow toggling built in pagination and "To Top" for custom queries.

### ISSUE THREAD

**Issue by Hotcooler** [Crocoblock/suggestions#1294]
Before 2.2.5 built in pagination used to work if you set it prior to toggling on custom query and I used that a lot, now it does not.

Please allow these two toggles to work on custom queries out of the box, it's a simple fix that does not break anything I imagine, especially since it'll be an option.

To make the toggles work (and their respective effects) one needs to remove
`'is_archive_template!' => 'yes',`
condition from the 'show_arrows', 'arrow_type' and 'scroll_top' controls.

Said controls are located in jet-blog/includes/addons/jet-blog-smart-listing.php on lines 1205, 1222, 1238 respectively.

Also if at all possible, please look at all of the custom query able widgets and allow some of the options to be toggled while using custom queries, since a lot of the time control related things like pagination, "To top" e.t.c. located in the same query and controls section get disabled for no reason.

**Comment by kaskad88** [comment]
Fix for next version
