### ISSUE TITLE
Form duplications and PDF invoice to customer

### ISSUE THREAD

**Issue by cwebmaster** [Crocoblock/suggestions#1295]
We are stack with setting the booking, we need to be able to Make the Price changing depending on the number of days, there is no room in the world have one price and double price per person, also we need to service prices, parking, food, etc..

- Please we need to be able to duplicate the forms
- PDF Invoice to customer

**Comment by UraraReika** [comment]
All this requests related to JetFormBuilder. You can set Meta fields for customising service prices, parking, food, etc and then use calculated  field to get correct price with the help of simple formulas.  You can [contact](https://support.crocoblock.com/support/home/ ) our support team, so they can help you.

Form duplication functionality already exists - https://tppr.me/3FbcM in JetFormBuilder plugin.

For the PDF invoice to customer you can use new JetFormBuilder Pro version addon - https://jetformbuilder.com/addons/pdf-attachment/

Thank you!
