### ISSUE TITLE
Map Listing - Map inside an Elementor Archive Template doesn't load listing 

### ISSUE THREAD

**Issue by dibeja** [Crocoblock/suggestions#1299]
Hi, when using the map listing widget inside an Elementor Archive template it doesn't load the proper listing style.

You can check this here:
http://elementor.metaordini.it/portalecommercialisti/map/ (here in the Modify with Elementor top menu i can see the template of the correct listing is loaded)

INSIDE AN ARCHIVE TEMPLATE: http://elementor.metaordini.it/portalecommercialisti/servizi/dichiarazione-dei-redditi/ (here the listing is loaded without styling and in the Modify with Elementor top menu the listing template is not loaded)

**Comment by MichaelDarko** [comment]
Can confirm this bug exists. 

Map listing popup inside archive template doesn't load styling. 

It loads the styling fine in Elementor editor, but on a frontend the styling is not there.

So right now the map listing widget can't practically be used in an archive template - the place where you need it the most.

Please, fix this quickly.

**Comment by kaskad88** [comment]
Fixed in 2.3.6
Feel free to update!
