### ISSUE TITLE
JetWooLicense (software / product license management engine)

### ISSUE THREAD

**Issue by marcber** [CrocoBlock/suggestions#13]
Hi,
It would be a great addition to your line up to make a new plugin to allow WooCommerce enabled web sites to manage licenses for certain types or products that someone can sell on their web sites.

Things like :

- Generating new license / use admin provided license and deliver to Buyer by Email, once payment confirmed
- Provide an API to allow client side (software / plugins sold, etc) to interrogate the license DB on the WWW
- Handle various types of licenses such as one-time and annual (with renew mechanisms)
- ...

An example of all this is https://woosoftwarelicense.com/

Thanks

**Comment by CrocoBlock** [comment]
Thank you for sharing your vision and for your suggestions. 

Unfortunately, our team has now prioritized the Elementor-based tasks, and we evolve our products in the context of Elementor functionality. 

However, when the tasks related to Elementor functionality and its specifics will be complete, our team will return to this suggestion and look into it. 

Best regards from Crocoblock team
