### ISSUE TITLE
Infinite AJAX Scroll

### ISSUE THREAD

**Issue by JLAcostaEC** [Crocoblock/suggestions#1300]
Greetings to the whole team, the suggestion is that the Smart Filter or WooBuilder also has the possibility of infinite scrolling.

I give the following example: If we have a Product/Post Archive with for example an 'Elementor Archive' or a 'JetWooBuilder Product Grid' with about 6 rows, when we get to the last row on the screen, this generates the AJAX request to bring more products / post including smart filters (Filter Checkbox List or Range, Sort Filter, etc). This way if we have a filter activated and the Archive needs more than 6 rows, then the content will be loaded at that point.

It would be a functionality that in my opinion would end up giving the AJAX look to any page that has the plugins that you offer.

I will leave a GIF using the ThemeIsle NEVE Theme as it has this Infinite Scroll functionality that I can better illustrate with.

![InfiniteScrollNEVE](https://user-images.githubusercontent.com/61467132/82069059-cdce3b00-96a0-11ea-89f8-74f62771bc4e.gif)

Excellent work, Greetings to the entire team.

**Comment by UraraReika** [comment]
In the latest release of the JetSmartFilter plugin new load more functionality appears. It works with all available providers. Please feel free to try it.
