### ISSUE TITLE
How to make JetSmartFilters work with Posts(& CPTs) pagination on Archive Posts?

### ISSUE THREAD

**Issue by realstephenzhao** [Crocoblock/suggestions#1301]
Actually JetSmartFilters can work on the first page of Archive Posts created by Jetengine Listing Grid(use as Achive) or Elementor Pro Archive Posts, but it will lose all applied filter settings when we navigate to the next or previous page(slug like `.../cpts/page/2`) even use Posts Pagination widget from JetElements(or JetBlog).

I know it can work with Ajax Pagination widget from JetSmartFilters, but it also bring non SEO-friendly page url unlike FacetWP plugin. See this https://github.com/Crocoblock/suggestions/issues/243

While I still prefer using pagination slug like `.../cpts/page/2` to my default Posts(blog) and Deals(CPT). Is it possile to get it work with some filters like Sorting widget and checkbox filter from JetSmartFilters?

**Comment by Floydtm** [comment]
Use pagination from filters with other providers
