### ISSUE TITLE
Hierarchical doesn't work with additional providers

### ISSUE THREAD

**Issue by TheBigBanik** [Crocoblock/suggestions#1302]
I have created 2 taxonomies, CAR BRAND and CAR MODEL. I use listing grid and map listing to show both in the same page. Now, if I create 2 sepaate select filters for each taxonomy and use "this filter for" JetEngine Maps and Additional provider Jet engine, then on selecting the values both map and listing grid changes the right posts. But, if I create 1 filter with hierarchical setting with 2 levels for each taxonomies (which is the right solution for filtering cars), any change of value affects only the map or the listing grid, not both of them. I believe when in hierarchical the changes are retrieved only form the field "This filter for" without taking anything from additional providers.

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know.
