### ISSUE TITLE
💡 jetElements: Line Style for Vertical Charts & Previous Month Performance

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1309]
It would be great if there was a way to offset values by month so that you can see performance vs. previous month. For example on an earnings dashboard.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/8274669/82193056-60aae780-98e4-11ea-92d8-f190f1d0822c.png">

**Comment by kaskad88** [comment]
Added in JetElements v2.5.0
