### ISSUE TITLE
Problem with Jet Woo Template - Single Product Template with variations plugins

### ISSUE THREAD

**Issue by NeoAcla** [Crocoblock/suggestions#1310]
Hi,

It seems that there is a problem with the Single Product Template created in Jet Woo Template when using a third party variation plugins.

The issue is, when the variation plugins are active, and you select an option from the variation then click the add to cart, seems that the one that you selected is being deselected again after hitting the add to cart button does it gives warning.
![image](https://user-images.githubusercontent.com/19571084/82198850-f6a73800-990d-11ea-9882-ab44ea023d92.png)

But if i disable the variation plugins its working fine.

In order for me to check properly, i created a Elementor Single Product Template and make it as a default.
Enabling the variation plugins
Tested by selecting a variation options and clicking add to cart button, the result is working properly.
But if i disable to the elementor template and use the jet woo template as a default, adding to cart does not work.

Does this mean i should contact the developer of the variation plugins?
But all the variation plugins that i tried and tested are giving the same results.

I tested 2 variation plugins, Variation Swatches for WooCommerce and WPC Variations Radio Buttons for WooCommerce
Both of them doesn't work well if used in Jet Woo Template,

Here is a sample single product lin with jet woo single product template enabled.
https://corkpadeldubai.ae/product/custom-image/
Try to choose any from the location code and hit add to cart button.

**Comment by NeoAcla** [comment]
Anyone from the dev to check this issue?
I posted this 2 days ago now.

I sent this as well to support ticket, until now still being in process and no one assigned yet.

**Comment by Mulli** [comment]
There should be real support for **product variations** - could not find any.
Am I missing something?

**Comment by NeoAcla** [comment]
The support team already fix the issue thru support ticket.
I think they will include this fix on the next release update.

Issue is solved
