### ISSUE TITLE
add "primary catagory" as option to choose from when query products in "product grid" widget

### ISSUE THREAD

**Issue by dudurom** [Crocoblock/suggestions#1313]
In "product grid" widget, i have the ability to choose between these options in "query pruducts by":
all, featured, sale, tag, catagory, specific ID's, recently viewd, related, up sells, cross sells.
![image](https://user-images.githubusercontent.com/59249697/82222845-8529b280-992a-11ea-84c3-ac60d01e6118.png)

now, "related" is querying products with the same category (or maybe also tags I don't know).
but, if a product is assigned with many catagories, there will be products there in the widget that i dont want.

because i have "yoast", i can determine which category will be primary.

i would like to see another option in "query pruducts by" like this: **related main category**.

here is explainer video:

https://www.loom.com/share/41edff8f837a4ef1b36d6a44ee0cfc68

**Comment by UraraReika** [comment]
Hi @dudurom!

This is the functionality of a third-party plugin. And there is more than one plugin giving such functionality. Therefore, your request will not be added to our plugin, but you can use the filter to write custom code to meet your needs. For example:
`add_filter( 'jet-woo-builder/shortcodes/jet-woo-products/final-query-args', '__your_prefix_product_grid_main_category_relation', 10, 1 );

function __your_prefix_product_grid_main_category_relation( $args ) {

	$primary_term_product_id = yoast_get_primary_term_id('product_cat');
	$productTerm             = get_term( $primary_term_product_id );

	if ( strval( $productTerm->term_id ) === '' ) {
		return $args;
	}

	$args['tax_query'][] = array(
		'taxonomy' => 'product_cat',
		'field'    => 'term_id',
		'terms'    => array( strval( $productTerm->term_id ) ),
		'operator' => 'IN',
	);

	return $args;

}`
