### ISSUE TITLE
JetMenu - The Hamburger Menu Button Should Show Instantly - Not a loading animation

### ISSUE THREAD

**Issue by quinnfive** [Crocoblock/suggestions#1314]
Regarding the hamburger menu button.

Right now when you load the page it loads this ajax loading animation. 

The problem is that button takes 1-2 seconds to load, and if it's at the top of the page, the user is going to notice that on every single page they visit on the website and that's just not good enough. It's a critical issue that the page appears to load as quickly as possible. 

I understand that probably the reason why you've made it this way is the content of the menu takes time to load and you can't have the button be able to be clicked on until the menu content is loaded.

**However, here is my suggestion to make the user experience much better :** 

Show the menu button instantly... IF the menu content has not loaded yet, AND the user clicks the button, THEN show the 'loading' gif.

**Here is a video highlighting the problem**

https://www.youtube.com/watch?v=Wl8QcxVxVi0

So simply loading a button instantly and then having that button show an ajax loading animation, similar to the way the sub menu buttons in the video above do, IF the menu content has not yet loaded and the user clicks on the menu button. Do not have it like it currently is, where the menu button is hidden and in it's place is an ajax loading animation every time the user loads a page of a website. It's off putting and not neccessary and makes the site appear to load slower, even though all sites have things loading in the background after the first colorful paint, they just don't advertise it with swirling loading animations. 

Look, I love this plugin, I think it is by far THE BEST mega menu plugin for Elementor hands down. If we can just fix this one critical issue then it's going to be perfect.

**Comment by iamdanbarrett** [comment]
I agree with this, I had to pull out the JetMenu entirely from a client's website as it kept getting 'Stuck' and really wasn't working as it should.

**Comment by oliverf72** [comment]
Good idea, on my page the loader is loading and loading and I am searching for the reason.. instantly would be much better.

**Comment by Floydtm** [comment]
will be fixed in plugin version 2.0.5

**Comment by quinnfive** [comment]
Thanks Floyd!!

Where can I go to check what the current version of Jet Menu is? 

How can I be notified or keep track of future changes to the Jet Menu version number?

**Comment by AdrianPaulV** [comment]
I am having the same issue. Sometimes it's fast, sometimes it gets stuck on loading. I just opened my website, the hamburger menu got stuck on loading. I had to refresh the website. Once inside the menu, I clicked on Shop and same thing, stuck on loading, had to refresh again. This is terrible, why is it happening? I have the latest version.

**Comment by MrJoshFisher** [comment]
Having an issue where some shortcodes aren't loading on the mobile sub menus but are working fine on Desktop (Jet Menu V 2.0.9 With Elementor Pro)

**Comment by atomikweb** [comment]
I have the same problem, but it is strange, the menu works correctly while I have the wordpress admin logged in but if I close the wordpress session the plugin stops working and the menu stays loading

**Comment by coryhubbell** [comment]
+1 for what is going on here?

**Comment by lvmunster** [comment]
+1 should be taken care off ASAP. Having the same issue. Also jetmenu in general is slow, is the last thing on entire website to load

**Comment by JoshPNG** [comment]
Has anyone found any fixes for this? On Mobile sometimes the hamburger menu will just randomly refuse to show, and also I have an elementor after header template which will often also just completely randomly refuse to show, how am I supposed to fix this? Lol

**Comment by ghost** [comment]
I have the same problem. The menu sometimes dont show up y load 1 or 2 second after the page load full

**Comment by tony-keller** [comment]
+1 we face this issue too. Always keeps loading with no results, have to reload and hope..
@Crocoblock can we have a working update ?

**Comment by akramg478** [comment]
Is there any update on this ? Thanks
Or should I load that json from my own static file to put things faster ... any word on this will be helpful ?

**Comment by Smalyleinchen** [comment]
Have the same problem. Sometimes the menu opens instantly and sometimes it loads endless until i reload the page.

**Comment by coryhubbell** [comment]
I gave up on them along time ago. My best advice is to use something else. Terrible menu system with so many ongoing bugs

**Comment by tehben** [comment]
Same issue. Very slow loading times (4-7s).

**Comment by simonst** [comment]
same here, since the latest update JetBlocks 1.3.4 I am getting an Animation which is closing the menu. which makes page load very slow.

**Comment by magdakubis** [comment]
Same issue. Constantly keeps loading on mobile. Seems to work fine on desktop.

**Comment by magdakubis** [comment]
> 

What did you replace it with? If I leave the mega menu on desktop (where it seems to work fine) but remove it on mobile - do you think that will speed up the mobile loading time?

**Comment by tehben** [comment]
Issue/suggestion is closed. Maybe we should post another one…

**Comment by coryhubbell** [comment]
It will never get fixed properly. We abandonded Jet because of this type of behavior. They dont care.

**Comment by branditechture** [comment]
@magdakubis I found the issue. 
Crocoblock JetMenu uses the WP-JSON REST API to fetch menu content. If you use an optimization plugin that has a feature to disable Rest-API Access for non-admins, then you would likely run into this problem. 

Here's what to do;
1. Disable the feature restricting access to REST API
2. Clear your cache.

Viola.
