### ISSUE TITLE
Ability to export and import option pages

### ISSUE THREAD

**Issue by josecristobal** [Crocoblock/suggestions#1315]
I use Jet Engine to create an options page in which I create the necessary fields for the client to fill in. This helps me to get all the customer information in an orderly manner.

Every time I make a website I have to build the options page again, when most of the fields are the same in all the projects.

How can I export one of these options pages and then import it into the next project?

Thank you very much.

**Comment by kaskad88** [comment]
Added in JetEngine 2.4.5
