### ISSUE TITLE
💡JetSmartFilters - Sort Posts by Category

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#1317]
Is it possible to add a new Smart filter tab option that picks up the categories and can sort/filter the posts within the JetListings widget? See the image from a competitive plugin vendor:

![posts-filtarable-tabs](https://user-images.githubusercontent.com/3041238/82324537-bc06d380-99d1-11ea-920e-1b3bf09fa6a4.png)

**Comment by Floydtm** [comment]
@iamdanbarrett, hi! I think you can implement right now. Create a filter with these settings https://prnt.sc/sngi6w accept the necessary styles for the filter https://prnt.sc/sngiwd https://prnt.sc/sngj4c and it will work https://prnt.sc/sngjn4 https://prnt.sc/sngjwt
