### ISSUE TITLE
Using GPS coordinates in Advanced Map widget

### ISSUE THREAD

**Issue by smcrmo** [Crocoblock/suggestions#1318]
This is a feature request for the Advanced Map widget. I have a website offering vacation rentals in rural Costa Rica. There is not an address system here recognized by Google Maps, just latitude-longitude coordinates. 

I'd like to place a location map on each rental listing page, but since the Advanced Map widget doesn't resolve GPS coordinates, I can't use it to perform this function.

**Comment by scottybo** [comment]
Any news on this one?

**Comment by smcrmo** [comment]
Unfortunately, no, I haven’t seen the addition of the GPS feature requested.

**Comment by scottybo** [comment]
Turns out it accepts longitude and latitude

**Comment by smcrmo** [comment]
Awesome, I haven’t checked in months. Thx for the update!

**Comment by kaskad88** [comment]
Available from version 2.3.1
