### ISSUE TITLE
JetBlog Problem after update to Version 2.2.5 (no Filter,pagination etc.)

### ISSUE THREAD

**Issue by JidWictut** [Crocoblock/suggestions#1324]
Hello,
i use jetblog version 2.2.4 and have updated to version 2.2.5. The filter under Query & Controls no longer works. It is no longer displayed on the page when I also use Custom Query. In version 2.2.4, however, the filter is displayed and the other settings with the custom query switched off are also adopted. After the update, this is no longer the case. Only the custom query is displayed without filters etc. I use the Smart Post List widget.
**Version 2.2.4:** 
under Query & controls I activate "show filter by terms". then I activate "use custom query". the filter above the pictures is **still visible.**
**Version 2.2.5:**
under Query & controls I activate "show filter by terms". then I activate "use custom query". the filter above the pictures is **no longer visible.**

Every setting is lost when I switch to custom query (filter,pagination etc.). This was not the case before!!!!!

I only use custom query because I want to sort the posts alphabetically (ASC) and unfortunately there is no other way. Why?

This is the answer from support: 

> Well, with the last plugin update to 2.2.5 the logic of all connection was changed and fixed. Now it is not available to display filters if Use custom query enabled. We can only offer you to return the 2.2.4 version of the plugin, so you can use it. 

That's a pity. Then i cannot use the changes and improvements of new versions of your plugin.

![Difference between Version 2 2 4-2 2 5](https://user-images.githubusercontent.com/65712457/82552459-70376400-9b62-11ea-8d46-e464bb45b639.jpg)

**Comment by kaskad88** [comment]
Fixed to the next version

**Comment by JidWictut** [comment]
Hello,
I have noticed that the bug in version 2.2.8 should be fixed. **I have updated the plugin and you can see the result on the pictures!!!!!!!!** 
With Custom Query there is now a filter again but it can't be edited. No matter which custom query I enter the filter always shows all possible categories etc. So the filter is not usable with cutsom query.

Without Custom Query
![Version 2 2 8 without Custom Query](https://user-images.githubusercontent.com/65712457/83651279-9d036680-a5b9-11ea-87e9-dba5ad1ca6e4.JPG)

With Custom Query enabled
![Version 2 2 8](https://user-images.githubusercontent.com/65712457/83651285-9e349380-a5b9-11ea-8ed0-447ba616f4b9.JPG)
