### ISSUE TITLE
Change the date format on the Smart filters from m/d/Y to d/m/y

### ISSUE THREAD

**Issue by Rob1337Rob** [Crocoblock/suggestions#1325]
I Requested a little help on the Crocoblock Help and they asked me to request on hear as it is curtly not possible 

So my entire site work with UK Date format that is d/m/Y but the Smart Filler is not as Smart it will only show dates as m/d/y 

This seems as if it would not matter but actually can be extremely confusing for British users. 

I would love this to be added as a Feature or at least pointing in the right direction to possibly manually change it myself

**Comment by Rob1337Rob** [comment]
Is this something that is being looked at as I would like to use this system again but can't use it with the Date formats as they curtly are

**Comment by inb4cookies** [comment]
Id really love this feature as well, since using a different type of date formats is a kind of a no go.

**Comment by peterforensys** [comment]
![filter](https://user-images.githubusercontent.com/69253541/89429341-b8b3f600-d73d-11ea-8a07-8c081c85340a.PNG)
This is important for us too. In Hungary the Y.m.d. format should be used. I hope Crocoblock will take this into consideration soon!

**Comment by Floydtm** [comment]
Available in version 2.0.1

**Comment by vinnyCalixto** [comment]
Floyd where I found that? I need help changing the date format on my site!!  from Y-m-d to d/m/Y...thank you

**Comment by Floydtm** [comment]
https://prnt.sc/1yst9gj

**Comment by vinnyCalixto** [comment]
> https://prnt.sc/1yst9gj

I can't see the image!

**Comment by Floydtm** [comment]
In the filter settings you can change the date format
![Screenshot_1](https://user-images.githubusercontent.com/14220177/140972210-ac8ee858-93aa-470b-b7dd-460c5d834fb4.png)

**Comment by mbaierl** [comment]
Can this also work for the date period filter? No helping link there...
