### ISSUE TITLE
Add Lottie element to jet elements 

### ISSUE THREAD

**Issue by azimdotnet** [Crocoblock/suggestions#1327]
Please add Lottie element in jet elements as lottie elements are very favorite widgets now a days. 
Examples:

https://theplusaddons.com/elementor/widgets/lottiefiles-animations-elementor/

https://premiumaddons.com/elementor-lottie-animations-section-addon/

**Comment by Srg-Nrg** [comment]
This functionality will be available in the next version of Elementor Pro. This functionality is now available in beta.

**Comment by kaskad88** [comment]
Added in JetElements 2.3.0
