### ISSUE TITLE
JetEngine: Maps Listing on Elementor Archive page

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#1328]
On Archive template the styling of the item isn't displayed correctly: https://prnt.sc/slpuz4
while on a page it's displayed well

**ticket#10747

**Comment by MichaelDarko** [comment]
This has already been reported here: #1299

I can't finish a project for my client because of this. Hopefully they fix it very soon. The Crocoblock subscription is not cheap and bugs like this should not be acceptable. How can something like this get through testing?

**Comment by kaskad88** [comment]
Fixed in 2.3.6
Feel free to update!
