### ISSUE TITLE
adding number field in the metabox field type

### ISSUE THREAD

**Issue by yaron86** [Crocoblock/suggestions#1330]
i came across something i needed to do but i can't.

there is an elementor widget called "starts" (i want rate hotels), it has dynamic feature and it's a number field (and it has support for decimal numbers like 3.5).
but when i add metabox field in jet engine, in the field type there is no number field. 
please add number field, it is very needed.

![99117574_10158728965194752_7079760280397283328_n](https://user-images.githubusercontent.com/3582979/82736107-bbeb3880-9d2f-11ea-926f-972c463c9b1e.jpg)

![99370456_10158728974489752_3961822037357363200_n](https://user-images.githubusercontent.com/3582979/82736111-c6a5cd80-9d2f-11ea-9f0b-975a9123f4b2.jpg)

**Comment by pintolog** [comment]
I have the same problem, will be happy to get it fixed also

**Comment by kaskad88** [comment]
I merged this issue with #1009
