### ISSUE TITLE
 🐞 jetEngine: Nesting a listing grid in a listing item causes the parent one to use the child one's preview width.

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1332]
Child Listing Item:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/8274669/82745537-1bb80280-9d75-11ea-8dfe-d306be489bf9.png">

Parent Listing Item:

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/8274669/82745544-2f636900-9d75-11ea-869f-a4456d7d1a5c.png">

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
