### ISSUE TITLE
Calendar doesn't show all listings items

### ISSUE THREAD

**Issue by LeonaTech** [Crocoblock/suggestions#1334]
**All event's doesn't showed on Calendar**
We have events listing via Listing Grid and Calendar.
Al work fine, but some events doesn't show in calendar.
For examle: We have event 30 june. It showed in Liging grid: https://prnt.sc/sngisq but doesn't showed in Calendar: https://prnt.sc/sngk2r

**To Reproduce**
1. Go to https://qagroup.com.ua/all-events/
2. Click on calendar to next month (June (Червень)
3. Scroll down to 30th day of month

**Event's from the past month doesn't showed this month**
We have past event in 29th April: https://prnt.sc/sngmrq
But after clicking to next month (May) - this event doesn't showed https://prnt.sc/sngo11

**To Reproduce**
1. Go to https://qagroup.com.ua/all-events/
2. Click on calendar arrow to past month (April (Квітень)
3. Click on calendar arrow to todays month (May (Травень)
4. See error on 29th April

**Comment by kaskad88** [comment]
Added to the Jet Engine 2.5.3 release
