### ISSUE TITLE
💡 jetElements: Tabs Dynamic Data Support

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1350]
It would be great if Tabs had a dynamic data feature like the timeline element does. Then you could select a posts field, repeater field or relationship on-page, and show have two content fields:

- Tab Control Item
- Tab Content

...where you could use repeater keys to render the content.

**Comment by kaskad88** [comment]
Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )
