### ISSUE TITLE
Ajax search product tag

### ISSUE THREAD

**Issue by petranca** [Crocoblock/suggestions#1352]
It is not possible to find products by the keyword (tag). It would be good if you could get a list of all products with this keyword when entering the keyword.

**Comment by noxdiurna** [comment]
I would be really happy to have this feature being a part of your future updates! The current search engine is rather awkward and weird as I have very high expectation on the capacity of JetEngine and JetSearch.

**Comment by MjHead** [comment]
Option `Search in taxonomy terms` added with 3.0.0 update
