### ISSUE TITLE
jet engine calendar mobile dynamic color bug

### ISSUE THREAD

**Issue by yaron86** [Crocoblock/suggestions#1353]
hello, i dragged the calendar widget, and under style > mobile > mobile trigger color, i chose dynamic color and choose jet engine > custom filed > and chose my **Meta Field** event color (which i used a select field type and put the hex color on the Option value) but the color does not appears on the trigger color background...

can this issue be fixed? 
![image](https://user-images.githubusercontent.com/3582979/83121939-9f5a5200-a0db-11ea-851d-7eb211f958be.png)

**Comment by pintolog** [comment]
I would be happy to know about a solution for this also, as i came a cross this request from my client

**Comment by kaskad88** [comment]
Unfortunately, this is not possible. The mobile trigger is not part of the post object and cannot be dynamically styled via post meta. Moreover, the mobile trigger can show multiple posts.
