### ISSUE TITLE
Jet Woo Product Gallery

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#1355]
I don't know which of the latest versions, but there is a blank div added on every page in the footer. It would be interesting to remove it and let the plugin load assets only on the product page.

Look http://prnt.sc/sppo61

**Comment by UraraReika** [comment]
Jet Woo Product Gallery can be used everywhere in your site despite it made for Woocommerce. Each widget from the plugin you can use wherever you want, not just at the single product page, in this case you need to put product ID in this field https://prnt.sc/t64y5e, also widgets can used in quick view popups, which can be triggered in the big amount of pages.
