### ISSUE TITLE
Ability to use google map control options in MapListing widget

### ISSUE THREAD

**Issue by navnak** [Crocoblock/suggestions#1361]
In the **Advanced Map widget** you’ve got the ability to control the Googlemap control options, like turn on or off zoom or fullscreen options. 

In the **Map Listing widget** there is no such option. Is there a possibility to build this option in this widget also?

**Comment by albertogg023** [comment]
Hi, did you have a response on how to change that map options?

**Comment by navnak** [comment]
No, not yet. Only that it was a good idea.

**Comment by kaskad88** [comment]
Added for the next version. Thanks.
