### ISSUE TITLE
Active Filter hide item name option toggle on/off

### ISSUE THREAD

**Issue by NeoAcla** [Crocoblock/suggestions#1363]
Hello guys,

Can I suggest, if we can add options in the content to toggle on/off to hide the filter name.
The documentation and sample preview should be the same materials, the documentation is poor.
Expectation and reality. 

Below screenshot for reference.

![hide filter name](https://user-images.githubusercontent.com/19571084/83345001-25b2a600-a31f-11ea-9cea-cbd858edff6e.jpg)

What confusing me is that, the sample from the website the filter name is not visible. And i cannot find the settings to toggle off from my Active Filter.

![hide filter name sample](https://user-images.githubusercontent.com/19571084/83345172-251b0f00-a321-11ea-8182-75a28a4f65ef.jpg)

Thank you and regards,
Neo

**Comment by Floydtm** [comment]
You just need to leave these fields blank https://prnt.sc/srhjxv in active tag filter https://prnt.sc/srhmqk

**Comment by NeoAcla** [comment]
Thanks for showing that to me. Issue solved

Just a follow up question.
What's the difference of the other widget (Active Filter) because this is the widget that the support specialist suggests to me. The only thing that I saw from my side is that just I know that Active Tag widget has the options that I am requesting. Why does the Active Filter doesn't have that option?

**Comment by Floydtm** [comment]
The only difference between Active Filters and Active Tags widgets is that you can remove, for example, only one filter option instead of removing all of them. https://prnt.sc/ss7d5m You can also check out this [tutorial](https://crocoblock.com/knowledge-base/articles/jetsmartfilters-active-tags-widget-overview/).
