### ISSUE TITLE
jet mega menu rtl issue on wp-admin

### ISSUE THREAD

**Issue by yaron86** [Crocoblock/suggestions#1364]
hello
i am using wp on hebrew language, which the interface it rtl.
as you can see in the wp admin - jet plugins > jetMenu Settings, things are not position correctly, please see the screenshot:

![image](https://user-images.githubusercontent.com/3582979/83347877-c362a100-a330-11ea-89d5-6f8f8f1e8dff.png)

**Comment by shinTM** [comment]
done v2.0.7
