### ISSUE TITLE
Jet engine rtl issue on wp-admin

### ISSUE THREAD

**Issue by yaron86** [Crocoblock/suggestions#1365]
when i click on jet engine on the wp-admin, it looks likt this:
![image](https://user-images.githubusercontent.com/3582979/83355818-76032580-a36a-11ea-9d12-8c14d9b5839e.png)
there is no padding between the text and the checkbox

and on the skin manager it looks like this:
![image](https://user-images.githubusercontent.com/3582979/83355877-cf6b5480-a36a-11ea-96db-8dcc06d8f012.png)

**Comment by kaskad88** [comment]
Merged with #1235
