### ISSUE TITLE
Hide the mobile menu after clicking on the item? (jetmenu)

### ISSUE THREAD

**Issue by GOHA81177** [Crocoblock/suggestions#1367]
Please make it possible that when you click on the mobile menu items... the menu itself was hidden after clicking on its items

**Comment by serg-pervushin** [comment]
Join us! I have a single-page site with anchors and moving around the page on my mobile became a problem, because it is impossible to hide the menu after clicking on an item in the menu.

**Comment by shinTM** [comment]
https://prnt.sc/v98gq2
