### ISSUE TITLE
Megamenu order of category product 

### ISSUE THREAD

**Issue by fermin1107** [Crocoblock/suggestions#1369]
I need to order the categories and sub by the order of category product 
![Untitled-1](https://user-images.githubusercontent.com/54163848/83444115-44996100-a421-11ea-97f7-d95b3ebacfd2.jpg)
of the menu, not only Name, ID.
Please see what the solution is.
Thank you

**Comment by Floydtm** [comment]
@fermin1107, hi! We cannot do this. You show the woo category list widget in the screenshot. But we do not have such a widget

**Comment by Floydtm** [comment]
@fermin1107, in the products grid widget there is such an option https://prnt.sc/t0jwcq but it is not available if you use the use current query option. When the use current query option is enabled, the options from the customizer are activated on the widget https://prnt.sc/t0jynn Here you can add the desired option for sorting products yourself
