### ISSUE TITLE
JetSmart Filters - Add RESET button to clear all active filters with one click 

### ISSUE THREAD

**Issue by joedivine** [Crocoblock/suggestions#137]
To add a reset button to clear all active filters and reset the results with AJAX for JetSmart filters.

Also a JS function that could be triggered onclick would also work for developers. 

This functionality can be seen on all the other filter plugins available. 

Thanks

**Comment by Nodws** [comment]
https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-use-remove-filters-widget/
