### ISSUE TITLE
JetSmart Filters: autocomplete, search selecting tags, height for column.

### ISSUE THREAD

**Issue by dionisis17** [Crocoblock/suggestions#1372]
Hello, I would like so much to use in Jetsmart filters some useful features that customers always telling me to add. 
1. the autocomplete feature (with the ability of adding tags) like this [site ](https://www.xe.gr/property/en/)or like [fSelect from facetwp](https://facetwp.com/documentation/facets/facet-types/fselect/).
2. add filters in a tab with toggle with the ability of choosing column height. This is **very important** cause many times I have a long height column with many check boxes and is not beautiful and convenient at all.

I am an elementor pro user and I have a subscription in Crocoblock

![fselect](https://user-images.githubusercontent.com/53856507/83482504-16f7fa80-a4a9-11ea-868e-d27b04d6f227.jpg)
![autocomplete and tags search2](https://user-images.githubusercontent.com/53856507/83482522-21b28f80-a4a9-11ea-8f7c-5cc6f5ba07c2.jpg)
![autocomplete and tags search](https://user-images.githubusercontent.com/53856507/83482529-25461680-a4a9-11ea-82f8-f141627a4c76.jpg)

**Comment by dantedanieltesta** [comment]
its a good feature to create for us!!!! I need this

**Comment by dionisis17** [comment]
> 
> 
> its a good feature to create for us!!!! I need this

I agree and its very important cause when you have 30-40 select boxes or radio you cant show them all. The height is a must fix for me.
