### ISSUE TITLE
JetSmart Filters: Filters not working properly in subcategories.

### ISSUE THREAD

**Issue by noob-webmaster** [Crocoblock/suggestions#1373]
Issue: I created a custom template for WooCommerce products archive. Added JetSmart Filters. Problem is that JetSmart Filters are only working if category has child with product in.
I have nested tree:
Category -> Subcategory (with products). In main category filters are working fine, but if I put them in subcategory template, they don't work, unless I add another nested subcategory and assing products in it.

Expected behaviour: Filters should work regardless of whether the category has a child category or not.

I'm using Elementor Pro with Crocoblock licence

**Comment by Floydtm** [comment]
@noob-webmaster, hi! We are working on this issue. Soon we will release an update that will fix the error. Keep for updates. Thanks you!

**Comment by breakerh** [comment]
Hey any update on this?
I always experience this.
Doesn't matter which block i use.
Woocommerce products archive, elementor pro products, elementor pro archive products etc..

**Comment by puregraphx** [comment]
@Floydtm three years later ... still not working ...
