### ISSUE TITLE
Multiple People Take Same Appointment (Classes)

### ISSUE THREAD

**Issue by SteStory** [Crocoblock/suggestions#1379]
Spoke to someone on support who said this functionality isn't yet available. I believe at the moment appointments are single use only?

I have a client who is a Personal Training Instructor and hosts classes. She wants the ability to put a class up as available, and then allow 20 people to register for the class at the same time.

Would it be possible to allow appointment/booking creations, that multiple people can pay for at once?

Cheers

**Comment by DirkHeilbron** [comment]
I second that for JetAppointment.

**Comment by MakhonkoDenis** [comment]
Hi, 
Functionality added in version 1.1.0 https://prnt.sc/1349uab
https://prnt.sc/1349vjj
