### ISSUE TITLE
Jet Booking manage weekdays

### ISSUE THREAD

**Issue by jannelundin** [Crocoblock/suggestions#1387]
It would be very good if it was possible to manage which weeday in booking calendar
teh week starts with like sunday or monday. Now in filters it´s monday and in
booking calendar it`s sunday.

It would also be very good if you could make seasonal prices for rooms and apppartments
because nearly all booking sites have that. It is also necesary to have different price
for short bookings like 2-3 days is one price and week> another.

It is very difficult to get a booking site working without those features

**Comment by UraraReika** [comment]
Hello everyone!

1. This functionality exist if you combine JetBooking with JetFormBuilder. Or you can use our API to fix this in your site https://gist.github.com/Crocoblock/0d73be0a11b07fa24c1490f5ad7d0d3a.
2. This functionality was presented in 2.4.0 version. You can fell free to check it out.

Thank you!
