### ISSUE TITLE
Smartfilters intersection in checkbox filters is not working

### ISSUE THREAD

**Issue by sumayyasaqib** [Crocoblock/suggestions#1388]
Hello!
So i recently installed smartfilters. Created a check box filter but the intersection option of the filter does not seem to be working. I have tried to reinstall the plug-in but no luck. Please update soon so that my problem get solved.
 Also please respond soon. Waiting thanks

**Comment by Floydtm** [comment]
Hey. We checked everything again and everything seems to be working fine. If you have difficulties with the plugin settings, please contact our support team
