### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by imariocup** [Crocoblock/suggestions#1390]
A plugin that lets you decide when to hide or show any Widgets or Sections in your pages.

https://wordpress.org/plugins/dynamic-visibility-for-elementor/
https://wordpress.org/plugins/dynamicconditions/

**Comment by vandijks** [comment]
Yes! We need this!

**Comment by kaskad88** [comment]
Use the `Dynamic Visibility` module in JenEngine https://tppr.me/dAz23
