### ISSUE TITLE
Lazy Load/ Infinite Scroll

### ISSUE THREAD

**Issue by NeoAcla** [Crocoblock/suggestions#1397]
Hi guys,

I was looking a widget to crocoblocks to supposedly to use on my current project but its not available.

If I may request a lazy load single post and infinite scroll for archive/product page.
The current available to crocoblocks right now is just the pagination.

Adding this widget to that lineup would be great.

Thanks.

**Comment by JLAcostaEC** [comment]
I made the request a while ago for the AJAX Scroll, but I did not get any comments, they will also have to take into account the JetSmartFilters, it would really be an excellent functionality and as I comment here:

[https://github.com/Crocoblock/suggestions/issues/1300](url)

I think it would be an excellent touch in terms of AJAX

@kaskad88 Please check this out, thank you very much.

:D

**Comment by stasonua0** [comment]
Вот еще туда же
https://github.com/Crocoblock/suggestions/issues/227
https://github.com/Crocoblock/suggestions/issues/1300

**Comment by UraraReika** [comment]
I merged this issue with #1300, which is on the same subject so we could deal with it more efficiently.
