### ISSUE TITLE
Кнопка "Добавить в корзину" с количеством

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#14]
Добрый день, по неизвестной причине Woocommerce с коробки не имеет такого функционала, хотя абсолютно все клиенты меня просят это внедрить. Возможность указать количество товара перед добавлением в корзину, без необходимости перехода на страницу товара. Очевидно что это очень удобно для посетителей. Поэтому прошу внедрить такой функционал в плагин Jet Woo Builder в виджет Add To Cart
Вот скрин, если не понятно из текста о чем речь - http://prntscr.com/mnp3j5

**Comment by CrocoBlock** [comment]
Thank you for sharing your suggestion.

Unfortunately, our team has now prioritized the Elementor-based tasks, and we evolve our products in the context of Elementor functionality.

However, when the tasks related to Elementor functionality and its specifics will be complete, our team will return to this suggestion and look into it.

Best regards from CrocoBlock team

Спасибо за то что поделились предложением.

К сожалению, наша команда на данный момент отдала приоритет в работе над задачами, связанными напрямую с функционалом Elementor. 

Однако, когда данные задачи будут решены, наша команда вернется к данному предложению и рассмотрит его. 

P.S. Пожалуйста, обратите внимание, что данный лог предложений находится в доступе для международного сообщества, и для удобства всех участников, а также во избежание дублирующихся запросов, будет более целесообразно формировать запросы на английском языке. 

Спасибо за понимание.

С уважением, команда CrocoBlock
