### ISSUE TITLE
JetEngine: Form: not able to insert media as post thumbnail

### ISSUE THREAD

**Issue by haobinliang** [Crocoblock/suggestions#1405]
**Describe the bug**
Photo uploaded as media field cannot be turned into post thumbnail.

**To Reproduce**
1. I've created a form that has media field named 'Photo'. I've restricted the upload type to be jpg or png.
2. In 'Post-submit Actions', I create 'Insert/Update Post' and map 'Photo' to 'Post Thumbnail'.
3. I go to the form and upload a photo and them submit the form.
4. The photo is uploaded to /wp-content/uploads/jet-engine-forms/ instead of media library. And also it does not become the thumbnail. 

**Expected behavior**
I expect the image become the thumbnail of the post therefore I can use it as a feature picture. Otherwise it's very difficult to generate the post grid.

**Screenshots**
<img width="1272" alt="Screenshot 2020-06-08 at 18 28 10" src="https://user-images.githubusercontent.com/7793969/84061552-028a9500-a9b6-11ea-9bb7-e6060ec7a418.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Chrome
 - 81

**Comment by Floydtm** [comment]
@haobinliang, hi! I think your media field is not configured correctly. Please check this option https://prnt.sc/t18na9 in the selection should be Attachment ID. Let me know if this helped you.

**Comment by incomewifi** [comment]
How to fix this error bro ! i have same error ! please help me thanks !

**Comment by Tahazargar** [comment]
@Floydtm My problem was solved with this solution, Thanks.

**Comment by eladyanai** [comment]
it doesnt add the image as featured for guests...
it says:
If checked new attachment will be inserted for uploaded file. Note: work only for logged-in users!
