### ISSUE TITLE
form check in check out calendar

### ISSUE THREAD

**Issue by neurohost** [Crocoblock/suggestions#1406]
in the check in and check out calendar it should be possible to select the month and year directly
https://prnt.sc/sw9asu

something similar to this example, but separating the month and the year
https://prnt.sc/sw9bwz

It would also be very good if the format of the date of check in and check out is available as follows

3 first letters of the selected day + day format number + year in number

https://prnt.sc/sw9dnl

**Comment by UraraReika** [comment]
> in the check in and check out calendar it should be possible to select the month and year directly
> https://prnt.sc/sw9asu
> 
> something similar to this example, but separating the month and the year
> https://prnt.sc/sw9bwz

This one will be in 3.5.1 release.

> It would also be very good if the format of the date of check in and check out is available as follows
> 
> 3 first letters of the selected day + day format number + year in number
> 
> https://prnt.sc/sw9dnl

For this one you need to implement some custom code. Originally  we used predefined set of date formats for better handling. And cant't predict all date formats. I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such complex cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.

**Comment by Crocoblock** [comment]
was released in JetBooking 3.5.1
