### ISSUE TITLE
Bug - Ordering monetary values does not work -  JET ENGINE

### ISSUE THREAD

**Issue by dantedanieltesta** [Crocoblock/suggestions#1413]
I have a vehicle listing, a value is displayed on the card ... when I sort by the sorting component the grid that is returned brings the values with the messy order ...

Ex: DESC Value (11,20,30,50,112,123)

Result: 112,11,123,20,30,50

I noticed that in Jet Engine when defining a field type it doesn't have a numeric format, only text exists!

The value field is using this text type.

I am formatting the output using the format_number of the dynamic field, even so the results of the sorting do not work.

How could I solve this BUG?

**Comment by Floydtm** [comment]
@dantedanieltesta, hi! After updating the plugin to version 2,4,0 a new field appeared - number https://prnt.sc/t1hi8l  If you place an order in a listing grid you must specify the necessary options https://prnt.sc/t1hm4p You can also contact our support team, they will help you set everything up.
