### ISSUE TITLE
Massive Performance Boost Needed For Mega Menu - Feature Request

### ISSUE THREAD

**Issue by TheOneWizard1** [Crocoblock/suggestions#1420]
Lazy loading in the mega menu:
https://www.loom.com/share/118db0ca0a7848eabccffa5b5c5d93d7

**Comment by shinTM** [comment]
you can use ajax-loading for mega content https://prnt.sc/ta9r2b its provide posibility loading mega content after when page has been loaded

**Comment by shinTM** [comment]
you can use ajax loading for mega content https://prnt.sc/v8gygs
