### ISSUE TITLE
JetBlog sort posts without custom query

### ISSUE THREAD

**Issue by JidWictut** [Crocoblock/suggestions#1421]
Hello,
since update to version 2.2.5 the plugin is useless for me (see here:https://github.com/Crocoblock/suggestions/issues/1324).

Is it possible to sort the posts (ASC/DESC order by title) in the future without using Custom Query? Then I could use the plugin as usual.

In version 2.2.8 the filter is available again but it just does not work!!!

Regards

**Comment by kaskad88** [comment]
Added in 2.2.9
