### ISSUE TITLE
Jetproduct image sync with variable product image

### ISSUE THREAD

**Issue by promocot** [Crocoblock/suggestions#1422]
Hello please ad function to sync image gallery slide with variable product in select. If i click on arrow slide in varibile product select color in list, that is, how this is done when choosing product variations for inventions, just do the opposite, too, from the choice of inventions, choose variations

**Comment by UraraReika** [comment]
Hello @promocot !

Our gallery builds differently from this functionality and we don't have in plans to add this at all. You can use one of variation swatches plugins from org.
