### ISSUE TITLE
JetEngine Listing Grid:  %current_author% ?

### ISSUE THREAD

**Issue by Yalpel** [Crocoblock/suggestions#1424]
Hello everyone,

On my website i have two custom post type: announcement and company. On the unique company page i want to show the announcement related to author ID. Like %current_author_company% = %current_author_announcement%

**Comment by Yalpel** [comment]
I want a query argument like : if Author is Current Author ; Show other posts by the current author.

**Comment by Floydtm** [comment]
@Yalpel, hi! If I understand you correctly, then you can implement this using the listing grid widget. In the settings you need to select these options https://prnt.sc/t0rr5e You can also contact the support team for help
