### ISSUE TITLE
JetBooking - Visual Order Management

### ISSUE THREAD

**Issue by wnt-it** [Crocoblock/suggestions#1425]
What about an visualized order management for admins on the back-end? 
Something like an calendar/table with rooms on the left side and days on the top.  
I did an example with excel so you guys can see. 

![Roomcalendar](https://user-images.githubusercontent.com/66781534/84382263-b07e8500-abea-11ea-9d69-cfdecf6dd2e5.png)

I think this would be great for hotels or restaurants if they could manage orders like that.

**Comment by Crocoblock** [comment]
was added in JetBooking 3.5.0 https://i.imgur.com/Pamkb0n.png

**Comment by SteliosTSa** [comment]
That is a great feature, but how about being able to visualize it on the front end! Of course with restricted permissions for visitors!
