### ISSUE TITLE
JetEngine Post Type as Product

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#1426]
Is it possible that when creating a new post type, that we can create a Product Post Type IF WooCommerce is installed? So, the CPT benefits from having all of the fields from Woo such as product pricing etc - this would be real handy in creating say tickets for an event.

**Comment by realstephenzhao** [comment]
I am afraid you can't create CPTs with repeated slug. And CPT can't inherit Woo's fields, they are all independant. What you can is to create relationship fields between them.
Woocommerce is an overkilled plugin that may slow down the performance of your website. You may not need it if you don't want a online shop like me.

**Comment by Floydtm** [comment]
@iamdanbarrett, hi! I think this is a bad idea. Why don't you create a separate post type with the necessary meta fields. I will close it becouse at the moment, we do not plan to introduce such functionality into our plugin.

**Comment by iamdanbarrett** [comment]
That does not answer my question in the slightest? Id just be then creating another post type with zero association to a product...
