### ISSUE TITLE
Hi - social media feeds ability

### ISSUE THREAD

**Issue by jojopa** [Crocoblock/suggestions#1428]
Hello! 
I'd like to suggest the ability to add the social media id# or token or something so that users can show off their own social media feed info on their profiles profiles. 

Example: the instagram widget now is for only 1 profile per site. If a site has for example 10 people, it would be great if they could add their own recent 10 pics from Instagram, or recent 10 youtube videos on their own 10 different individual profiles. 

Thank you for your consideration, and amazing work overall!

**Comment by Floydtm** [comment]
@jojopa, hi! you can use this option https://prnt.sc/t0ry0s

**Comment by jojopa** [comment]
Hi, I actually meant Dynamic info for Instagram accounts, such a field where a user can input their own id or token.
