### ISSUE TITLE
Jet Map Listing Set Coordinates

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#1429]
Hello, consider giving users a choice, entering exact addresses or coordinates in the "address" field.

/*Оригинал*/
Здравствуйте, рассмотрите возможность дать выбор пользователям, вносить в поле "адрес" точные адреса или же координаты.

**Comment by kaskad88** [comment]
Здравствуйте, уже реализовано https://prnt.sc/sxy59d . Обновитесь до последней версии
