### ISSUE TITLE
💡 Plugin Idea 💡 - JetEvents

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#1431]
An idea to add a way to create events using a new plugin called JetEvents. It would pretty much just be a ready-made CPT that you could add additional meta fields too in the same way.

The difference being it has additional functionality to manage the event and bookings on the event. The would work with WooCommerce or directly with payment gateways such as Stripe or PayPal etc.

**Comment by Willitbang** [comment]
I like this idea, it would be great if this worked with timestamps with the front end form. Then users could fill out the form to create new events, these could then be added into the calendar and map listing. It would also be great if you could have reoccurring events for example annual events, monthly events or even every Saturday for example. Then this would automatically input the number or recurring events into the new events CPT. I also agree that woocommerce, stripe and paypal integration is a must with this

**Comment by Floydtm** [comment]
We do not plan to make a separate plugin. However, we plan to implement this in the jetengine plugin

**Comment by iamdanbarrett** [comment]
I feel like your flooding JetEngine now though? I get that you want to make it really really flexible but its becoming more and more complicated.

**Comment by juliamux** [comment]
Where can I find a good tutorial on how to create an events site & manage registrations + payments? Everything I found so far is not complete to build an events site with your plugins (JetEngine/Jetappointment/Jetbooking) - thank you.

I see this thread is almost 3 years old so I would love to see something like this soon.
