### ISSUE TITLE
Jetwoo builder issue need enhancement

### ISSUE THREAD

**Issue by NeoAcla** [Crocoblock/suggestions#1432]
Hi guys,

Im not getting what I want to produce on my current project regarding shop page and category page.

Requesting additional feature for product grid "sorting the query by: menu order, category, taxonomies etc..." when Use Current Query is enabled.

![current query](https://user-images.githubusercontent.com/19571084/84422050-7f737400-ac2d-11ea-91e1-4430c7b62764.jpg)

The problem when Use Current Query is enabled is that the list of product items shown on the grid is not what I want to be on the top. And I don't have any option to put the important product to be on top.

When I disable the Use Current Query, then that's the time I can filter which product items should be on the top. But the negative side on this is that, Product Pagination is no longer working, My Menu are most category type and its not working as well.

![disabled current query](https://user-images.githubusercontent.com/19571084/84424528-4806c680-ac31-11ea-9c67-3866f430fe24.jpg)

So currently you have to decide on which one you want, Enable Use Current Query so you can properly use the menu and pagination but can not sort the product items or Disable it.

I hope you can fix this asap.

Thanks

**Comment by Floydtm** [comment]
@NeoAcla, hi! When the use current query option is enabled, the options from the customizer are activated on the widget https://prnt.sc/t0jynn. Here you can add the desired option for sorting products yourself
