### ISSUE TITLE
JetBooking / Forms

### ISSUE THREAD

**Issue by Hammer-ger** [Crocoblock/suggestions#1433]
Please add a function, that a loged in user can cancel his booking. for example allow to edit bookings via   front-end post submission.  

or a cancelling via url link. 

thank you!

**Comment by Hammer-ger** [comment]
Hello an happy new year,
are you still working on this request/feature, aren't you?

best wishes,
Hammer

**Comment by Crocoblock** [comment]
Hi @Hammer-ger!

This was added in JetBooking 3.3.0
Please, update the plugin
