### ISSUE TITLE
JetBooking set max nights per booking

### ISSUE THREAD

**Issue by Hammer-ger** [Crocoblock/suggestions#1434]
Hello Crocoblock-Team,

for our buissines we need the possibility to set the maximum of nights per booking to 3. There is the option to activate "one day bookings". Is there a opportunity to add a "three night bokkings" option? 

thx 

I found a way to do it with logical option in forms.
So you can ignore this request

**Comment by UraraReika** [comment]
I merged this issue with #4095, which is on the same subject so we could deal with it more efficiently.
