### ISSUE TITLE
JetEngine > Use googlemap to define address in custom fields

### ISSUE THREAD

**Issue by hellosubotai** [Crocoblock/suggestions#1449]
Hi, 
Can you provide / develop a Googlemap Field in Custom Post Types Custom Fields to use it in front end forms like ACF can do for this type of fields ?

It wil help user to select or choose the correct location for a post and be sure the address is Geocodable by Google.

 - Functionnality to add to JetEngine 
 - Result wanted : https://www.advancedcustomfields.com/resources/google-map/

I hope it's clear enough (I'm French... )

Thanks !

**Comment by Spacefunls** [comment]
This feature would be very handy for me as well.

**Comment by salasmx** [comment]
This is a must guys!

**Comment by AlaplayaW** [comment]
Same !

**Comment by pierresubotai** [comment]
Hi ! 
Any idea of a date of release of this functionnality ?

**Comment by kwsim539** [comment]
With mobile usage on sites taking over desktop sites, geolocation/zip code in filters/searches is one of the biggest asks from clients. 

I can't understand why Croco hasn't implemented this feature.

**Comment by salasmx** [comment]
Have you guys addressed this?

**Comment by MjHead** [comment]
Will be added with JetEngine 3.0.0. Beta will be available in a few weeks

**Comment by ALPSIT** [comment]
Yes please! This would be very handy for my clients who have Property Listings. I am working on a current project and this was a client request.

They would like to be able to auto complete address when adding a new property CPT.

I wish I could say Yes to my client.

**Comment by ALPSIT** [comment]
Another client example I might add - this can be a second phase perhaps.

Maybe more for JetFormbuilder, to be able to measure distance between two locations in km or mile and use that value in calculated field to provide price.

This would be good for quoting and booking travel.

A number of my clients currently need to use seperate software which allows this, but would be good if I could do with JetFormbuilder.

**Comment by kwsim539** [comment]
> Yes please! This would be very handy for my clients who have Property Listings. I am working on a current project and this was a client request.
> 
> They would like to be able to auto complete address when adding a new property CPT.
> 
> I wish I could say Yes to my client.

Doesn't Google already have this as part of one of their APIs?

[https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform](url)

**Comment by MjHead** [comment]
Added with 3.0.0 update
