### ISSUE TITLE
JetSearch option to style placeholder text

### ISSUE THREAD

**Issue by Artneo7** [CrocoBlock/suggestions#145]
Feature request based on this public ticket:
https://kava.ticksy.com/ticket/1954474/

It would be nice to implement a way to style the placeholder text for the JetSearch bar:
![style-placeholder](https://user-images.githubusercontent.com/17693529/55333703-3abb4d00-546e-11e9-8c23-dd47fba9657e.jpg)

Great plugin btw. Thanks!

**Comment by kaskad88** [comment]
Done. v1.1.2
