### ISSUE TITLE
🐞 Critical Bug (JetEngine): /jet-engine/includes/components/listings/render/listing-grid.php:295

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1453]
When using a dynamic tag with the Posts Query > post_params > Include posts by ID, the dynamic tag value doesn't get parsed to the query. The dynamic tag button shows up through. Version 2.4.1. @MjHead 

<img width="321" alt="image" src="https://user-images.githubusercontent.com/8274669/84791841-ae4d6980-afe2-11ea-8ca4-541c6fad64ea.png">

**Comment by MjHead** [comment]
This functionality will be added with JetEngine 2.4.2, I just checked release version of 2.4.1 - it not contain dynamic tags on the Include posts by IDs option

**Comment by altechzilla** [comment]
Great, thanks for the heads-up! I think I see those tags because I have the Dynamic Tags plugin, so it might be an incomplete code.

**Comment by altechzilla** [comment]
@MjHead - Looks like it was added with the latest jetEngine version, but the query is still not getting filtered properly.
