### ISSUE TITLE
Issue with jetForms file uploader in User Forms

### ISSUE THREAD

**Issue by numanagit** [Crocoblock/suggestions#1460]
**Describe the bug**
1. Can't remove an image. After uploading and saving image on user metadata I'm not able to remove it. I press the trash button, the image disapear and then, after saving the form, the image still there.
2. Can't replace the image without remove it using the trash button. Any image uploader with 1 file limit must allow to replace the image by only select a new one.

**To Reproduce**
1. Create a user form with image uploader
2. Check "Insert attachment" and select "Attachment ID" below
3. Upload an image in the form
4. Try to remove it
5. Try to replace it without remove it using the trash button

**Expected behavior**
An image must allow to remove it and leave the field value as null
The image must allow to replace it by only select a new one.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.97

JetEngine Version: 2.4.1

**Comment by altechzilla** [comment]
I also noticed that if you enable "Save to Media Library" and prefill the values for a user avatar (media field) it throws JSON errors when you try to upload files.

**Comment by codeorlov** [comment]
1. Ye, it is bug. I also found this. Needs urgent correction.  Also, when deleting an image, it’s good that it is deleted from the media library.

2. If I refuse to upload a picture to the library, the photo is displayed, but there is no picture in the WordPress profile.

**Comment by kaskad88** [comment]
Fix in JetEngine 2.4.9
