### ISSUE TITLE
Jet Engine po language file is not working for forms messages (image uploader)

### ISSUE THREAD

**Issue by numanagit** [Crocoblock/suggestions#1461]
**Describe the bug**
I want to translate alerts of the forms. eg: Maximum upload files limit is reached. Even if I create the po and mo file, translate the strings and put the files in /wp-content/languages/plugins/ is not working.

**To Reproduce**
1. Create a new po file from pot
2. Translate some string (like: Maximum upload files limit is reached) and save is as jet-engine-es_ES.po and jet-engine-es_ES.mo
3. Put them in /wp-content/languages/plugins/
4. Check the messages are not traslated using the form

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.97

**Comment by MjHead** [comment]
Hi! This messages can be changed on the form edit page, in the Messages Settings section - http://prntscr.com/tjgeha
