### ISSUE TITLE
Close MegaMenu on mobile, after click anchor item

### ISSUE THREAD

**Issue by mitothebee** [Crocoblock/suggestions#1463]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by mitothebee** [comment]
Hi, i use JetMenu (Mega menu) and I use anchor (scrool to section). I want the navigation to close on the mobile device when I click on the item.

Is it possible to solve this with some code in function.php?

Thanks

**Comment by shinTM** [comment]
since v2.0.5 https://prnt.sc/tadfxv
