### ISSUE TITLE
JetBooking - Price based on date

### ISSUE THREAD

**Issue by wnt-it** [Crocoblock/suggestions#1472]
a possibility to set prices for rooms based on the date, like the standard price for room 1 is 50$ but on a custom date (or date-range) its 60$. So Admins can set prices for rooms higher or lower in certain seasons or at events.

**Comment by Rubenzella** [comment]
Something like creating season from a data picker. and then you can decide if the price applied to each season can be daily, weekly, monthly, annually.

**Comment by Rubenzella** [comment]
In my old system, I had a page where I could create seasons: season A from 01/03 till 31/05, Season B from 01/06 till 31/07, season C from 01/08 till 30/09, and standard season that would cover the remaining days.
Then to these seasons, I could apply to each post type a different price that would be used to calculate the booking along with the extras.
![Screen Shot 2020-10-03 at 10 43 27 pm](https://user-images.githubusercontent.com/19385581/94991972-f8764d00-05c9-11eb-885d-56abd9b53a79.png)
![Screen Shot 2020-10-03 at 10 44 05 pm](https://user-images.githubusercontent.com/19385581/94991977-fc09d400-05c9-11eb-9069-b774f1cee067.png)

Hope this helps!

**Comment by 8persap** [comment]
Please can you add seasonal pricing as a priority? This plugin is so good and well thought out on every level but this. Seasonal pricing is key to any rental or hotel bookings. Without it, it rules out Jetbooking as a viable option. Please can you commit to addressing this? Thank you. 👍

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.4.0 version. You can fell free to check it out.

Thank you!
