### ISSUE TITLE
Add LINKED option to Dynamic field widget

### ISSUE THREAD

**Issue by pintolog** [Crocoblock/suggestions#1478]
Hi,
Please add the option LINKED in the Dynamic Field widget so it's possible to add meta fields & link them to the Permalink like in the Dynamic Image widget.

Here is a screen shot of the two widgets with the missing feature:
![image](https://user-images.githubusercontent.com/7497319/85287046-62943780-b49c-11ea-84e6-1542109dd045.png)

Thanks

**Comment by Floydtm** [comment]
I understand that you need this functionality. I discussed this issue with the developers and should refuse you this question. However, you can use the appropriate "Filter field output" and configure this field using the "Customize field output" option.
