### ISSUE TITLE
💡jetEngine: The ability to choose an attachment size for the "Custom Image" dynamic tag.

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1479]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/8274669/85306066-7db37700-b49d-11ea-8f57-8561b8204319.png">

**Comment by Floydtm** [comment]
@altechzilla, hi! For which widget do you need this option? You can use the image widget https://prnt.sc/t5ku2s

**Comment by altechzilla** [comment]
Hi @Floydtm, for elements using a background image. For example a listing grid item that has a background image with text on top of it, like this:

https://share.getcloudapp.com/YEupZO98

**Comment by altechzilla** [comment]
If the post thumbnail full image is larger, it will cause performance issues vs. just being able to select which image size you want rendered for that background image.

**Comment by altechzilla** [comment]
It’s the equivalent of doing a wp_get_image_attachment with an image size parameter on an inline style attribute on an element for background image.

**Comment by Floydtm** [comment]
I understand that you need this functionality. I discussed this issue with the developers and should refuse you this question. I think you can leave your request here https://github.com/elementor/elementor/issues

**Comment by altechzilla** [comment]
Cool, thanks! I assumed it would be a good fit for the custom image dynamic tag since Elementor has a bunch of different requests on it already but they’re not focused on it.
