### ISSUE TITLE
Jet Tricks - Dynamic image for hotspots widget

### ISSUE THREAD

**Issue by 3quid** [Crocoblock/suggestions#1486]
Add the standard dynamic image options available in many other widgets to enable hotspots to use a dynamic image. 

For example - this would mean it could be used on product pages to detail features of products that are the same shape/have the same feature set but with an image specific to that product.

**Comment by Michael-sr** [comment]
Hi everyone!
Please add not only work with dynamic field data, but also work with data from the Repeater fields.
We need these fields from the Repeater fields:
Label
Description
Link
Horizontal position
Vertical position

https://prnt.sc/v3apv8

You are cool, I really appreciate you! Thanks for your work.

**Comment by kaskad88** [comment]
@Gawuww need add compatibility with JetPlugins Dynamic Data Addon
