### ISSUE TITLE
JetCompare & Wishlist - remove from the list button function

### ISSUE THREAD

**Issue by Jozku** [Crocoblock/suggestions#1488]
A feature for **wishlist / compare button widgets** 

Alternate function of the button to remove the product from the wishlist instead of redirecting to the wishlist / compare page.
Right now it is only possible to remove a product from the list in the wishlist / compare pages which is not user friendly.

**Comment by UraraReika** [comment]
I merged this issue with #1193, which is on the same subject so we could deal with it more efficiently.
