### ISSUE TITLE
Add strings now, today, this week in Dynamic Visibility conditions to use as comparison

### ISSUE THREAD

**Issue by MayaNikolova** [Crocoblock/suggestions#1489]
It would be great to add strings like now, today, this week to use in the comparison conditions in Dynamic visibility for datetiem fields. Thank you
strtotime()-compatible strings (now, today, this week, etc.)
currently are not processed in Dynamic Visibility conditions.

**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by Floydtm** [comment]
merge with #1445

**Comment by realstephenzhao** [comment]
It has Already been fixed in JetEngine 2.4.5.
