### ISSUE TITLE
Bug report : JetEngine Grid Listing "Not found message" shortcode not always working

### ISSUE THREAD

**Issue by fhfournier** [CrocoBlock/suggestions#149]
Hi,

There is a bug in your "listing grid" widget.

If i don't select "Use as Archive Template".

![image](https://user-images.githubusercontent.com/3278753/55424820-14211300-554f-11e9-9f2c-ee2936a2514b.png)

The shortcode is working!

![image](https://user-images.githubusercontent.com/3278753/55424834-1aaf8a80-554f-11e9-8c26-6a7c8f8443ae.png)

But if i select "Use as Archive Template"

![image](https://user-images.githubusercontent.com/3278753/55424856-226f2f00-554f-11e9-9662-777c36ff0f79.png)

The shortcode is **not** working!

![image](https://user-images.githubusercontent.com/3278753/55424888-374bc280-554f-11e9-999b-3296777c52b1.png)

I think you have "addslash" inside your code because if i switch back and deselect "Use as Archive Template"

In the input the shortcode have slash in it just like "addslash" work in PHP

**Comment by MjHead** [comment]
Added in JetEngine 1.4,0
