### ISSUE TITLE
Global Custom Fields in JetEngine

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#15]
Good afternoon, I ask you to consider the possibility of introducing functionality into JetEngine with global arbitrary fields.

For example, phone numbers, company address, links to social networks, etc. can be displayed in the basement, header, contact page. I would like to create something like Theme options and create arbitrary fields there, then bring them to the right places, give them an individual style, and if you change this data in Theme Options, they would change throughout the site.

Functional Elementor Pro "Global Widgets" is not like because of the inability to set different styles

/*Оригинал на русском*/
Добрый день, прошу рассмотреть возможность внедрения функционала в JetEngine с глобальными произвольными полями.

Например, телефоны, адрес компании, ссылки на социальные сети и т.д. могут выводится в подвале, шапке, странице контактов. Хотелось бы создать что-то типа Theme options и там создать произвольные поля, после чего вывести их в нужные места, задать им индивидуальный стиль,  а при смене этих данных в Theme Options, они бы менялись по всему сайту.

Функционал Elementor Pro "Глобальными виджеты" не походит по причине невозможности задать разные стили

**Comment by alriksson** [comment]
+1!

Like how ACF do, and that we can fetch these global settings from different pages. Would be very useful! Think ACF call this options page: https://www.advancedcustomfields.com/resources/options-page/
