### ISSUE TITLE
Jetsmartfilter not populating attributes?

### ISSUE THREAD

**Issue by breakerh** [Crocoblock/suggestions#1501]
**Describe the bug**
It doesn't matter which kind of archive, product grid etc.. i use. But the attributes don't populate.
So it always returns an empty result.

**To Reproduce**
1. Setup attributes.
2. Create smart filter
3. Add them to archive/category template in elementor(pro)
4. test page, it has attributes with zero products. even when in the backend they do have products.

**Expected behavior**
Populated filters that wor

**Screenshots**
![image](https://user-images.githubusercontent.com/2008632/85748684-8956a600-b708-11ea-8ec7-59dd12602231.png)

**Desktop (please complete the following information):**
- all

**Smartphone (please complete the following information):**
 - all

**Additional context**
smart filter indexing on or off doesn't change a thing.

**Comment by Floydtm** [comment]
Hello! We checked your request and could not reproduce the bug. Please contact our support team. Provide details for accessing the site and we will try to solve your problem. Thank!

**Comment by damianrivadulla** [comment]
Hi how are you? Were you able to fix it? Thanks
