### ISSUE TITLE
Yoast doesn't work with JetEngine Custom Fields

### ISSUE THREAD

**Issue by tanujgoyal2006** [Crocoblock/suggestions#1502]
I found this important feature missing in plugin while working on one of the website. Yoast SEO plugin doesn't work with JetEngine Custom fields.

If you will add any text to jetEngine Custom fields then yoast will simply ignore its content and won't consider it for it's SEO algorithm

Kindly check attached screenshot where yoast plugin shows 0 words in text even there is a lot of text in JetEngine Custom Fields.

![image](https://user-images.githubusercontent.com/57218823/85759719-cdf53800-b72e-11ea-932e-c2157db2d310.png)

I expect Crocoblock team to look at this new feature request on urgent basis as many of the users who are working on this plugin are lacking this important feature.

Hope to get this feature added soon in the plugin.

Thanks in Advance

**Comment by andreschauer** [comment]
same problem here – we need a seo friendly blog! please fix – thank you!

**Comment by TheBigBanik** [comment]
This is urgent. SEO is the most important thing now days.

**Comment by bennybersier** [comment]
+1

**Comment by TheBigBanik** [comment]
This is a very crucial situation that must be a priority to your dev team. In 2020, we can not have non SEO friendly websites.

**Comment by sfutez** [comment]
any news about this?

**Comment by kaskad88** [comment]
Added in JetEngine v2.7.6

**Comment by TheBigBanik** [comment]
After a while I found out that to make this work we have to go to the Jet Engine main settings, SEO tab and select the meta fields we need to be parsed by Rank Math or Yoast. It is working fine. 5 stars to Crocoblock.
