### ISSUE TITLE
[Bug] Jetengine + Jet Smart Filters Bug : Index Filters not showing

### ISSUE THREAD

**Issue by dennylai1990** [Crocoblock/suggestions#1505]
**Describe the bug**

When deleting a CPT and assigning it's post to another CPT through JetEngine, Jet Smart Filter's "Index" function fails to work (Even when it's working for the old CPT before). 

I'm using JetEngine v2.4.3 with Jet Smart Filters v1.8.3

**To Reproduce**

1) I used JetEngine to create a CPT (Let's call it CPT A), created some custom fields, created some posts, created a listing to show the posts, and assigned multiple taxonomies to the CPT. Used Smart Filters to filter the listings with taxonomy as the data source and the "Index Filter" function to show the count. Works well.

2) I needed to change the name and slug of the CPT. So i went to create another CPT (Let's call it CPT B). I deleted CPT A, attached all posts(of CPT A) to CPT B, using the "attach all posts to another post type" function when you delete a CPT in JetEngine. I created the same custom fields for CPT B and reassigned the taxonomies from CPT A to CPT B. I did not change the "Data Source" for the Jet Smart Filters as it's the same taxonomy. I also changed the CPT source for my listings.

Everything but one worked; Jet Smart Filters is filtering my listing for CPT B correctly. The custom fields are getting pulled correctly. However, the Index always shows  (0). Went to Jet Smart Filter to click on the red "Index Filters" button multiple times but it does not work. You can see CPT B in action here https://bit.ly/3fWLl40

**Comment by breakerh** [comment]
If i'm correct even with indexing filters disabled you will also get 0 results right?
If so; I have the same issues only with woocommerce products. ( #1501 )

**Comment by dantedanieltesta** [comment]
I Have the same problem!

**Comment by Floydtm** [comment]
maybe you forgot to mark a new post type for indexing, check these settings https://prnt.sc/t96i97 let me know if this helped

**Comment by dennylai1990** [comment]
OMG! Yeah that did the job. Thanks!

**Comment by unitedonline** [comment]
@Floydtm - The screenshot of the settings you had posted has been removed.
Is it possible for you to repost please?
Thank you

**Comment by Floydtm** [comment]
https://prnt.sc/ia92-xvfYWt8 maybe these options

**Comment by unitedonline** [comment]
> maybe you forgot to mark a new post type for indexing, check these settings https://prnt.sc/t96i97 let me know if this helped

The screen shot has been removed. Is it possible that you can re-upload it?
Thank you

**Comment by lizmiz** [comment]
same here ? were is the screenshoot
