### ISSUE TITLE
Jet Smart Filter - Can't create a special filter for one specifique page

### ISSUE THREAD

**Issue by Biblothecaire** [CrocoBlock/suggestions#151]
**Describe the bug**
Hi,

I have create different destination : nosy be - antananarivo - london - paris, etc...
I create a PAGE for a special destination
So i want to purpose only the listing from this destination on this page. I create a tax query, work fine BUT when i use the filtrer, it filtrer ALL, not only the destination

Thanks for your help

**To Reproduce**
1. Go to https://madatest.com/hotels_nosy_be/
2. Click on 'filter 50.'
3. You can see hotel from toher destination

**Expected behavior**
The choice of the destination is made. so the filters should take into account only this destination

**Comment by Floydtm** [comment]
https://github.com/CrocoBlock/suggestions/issues/157
