### ISSUE TITLE
New Element for "order by"

### ISSUE THREAD

**Issue by MisterX75** [Crocoblock/suggestions#1519]
Hi.
Is there a way to edit order by, to set SKU as order-object? If so where can I change that? I don't know which file to use.

Greetings Marco

**Comment by Floydtm** [comment]
Could you describe your problem in more detail. provide screenshots or video

**Comment by MisterX75** [comment]
![2020-06-25](https://user-images.githubusercontent.com/53875975/86136302-3310ab00-baec-11ea-97db-97af94a87c40.png)

Our customer would like a standard SKU sorting. At the moment you can "product-grid" order by Date, Price etc. They would it by "SKU".

Thanks in advance.

Greetings
