### ISSUE TITLE
Booking Fhorm from jet engine

### ISSUE THREAD

**Issue by Biblothecaire** [CrocoBlock/suggestions#152]
**Describe the bug**
Hi,

I have create a Jet Engine booking fhorm. It work fine, just a detail I don't understand how to do.
Until know i use the elemontor pro widget for contact fhorm and it work well. I change  for your booking form and stop working on this point.
More easy, see the screahot in attache for the field i can't see on your from (step 3 screenshot)

In detail if need :
I am a relationship platform, so i have 3 email on a booking fhorm :

The email from the listing (my customer, N°1), a Meta field
The email from the booking fhrom, the customer (N°2) who are inrestest of the service of the mail N°1
The email to send email from the site (N°3)
So the email N°2 go to the N°1. And the N°2 want to answer to the N°1

For this, i have create a hieden field with a Meta field to get value from a meta field. It work fine, N°3 send the e-mail to N°2 

BUT, when N°2 click on answer, it answer to N°3, i want it answer to N°1

Thanks for your help

**Comment by Floydtm** [comment]
https://github.com/CrocoBlock/suggestions/issues/158
