### ISSUE TITLE
Document filters and actions for plugins

### ISSUE THREAD

**Issue by Sidlegionair** [Crocoblock/suggestions#1522]
It would be nice if the various filters and actions for the various crocoblock plugins would be documented somewhere, this is something that would take the ease of use and the customization of the plugin to the next level for developers. I often find myself digging through source code for ways to extend/change the widgets behaviour. Maybe you could make it an open source doc so the community can help documenting?

**Comment by UraraReika** [comment]
Right now our team working on documentation! If you have argent tasks you can ask our support team they will help you with  searching and advice .

**Comment by Sidlegionair** [comment]
Hey @UraraReika,

Any insights as to where I can find it? I'm looking to exclude a specific Listing Grid's query from Object Cache to make it display a randomized Post through the lazy loading functionality of the Listing Grid in the event the page is cached statically.
