### ISSUE TITLE
Gallery Slider Center Thumbnails Issue

### ISSUE THREAD

**Issue by GazDog** [Crocoblock/suggestions#1524]
I am using the JetProductGallery Slider and can't get the thumbnails to centre and can't find any setting for it either. Please see attached screenshot for a visual representation.

![Centered](https://user-images.githubusercontent.com/3781915/86202838-b7bfff80-bba6-11ea-85c1-870a878eb006.jpg)

**Comment by Floydtm** [comment]
@GazDog, hi! We have reviewed your request. All this can be done using the widget settings. Please contact our support team, they will help you.

**Comment by GazDog** [comment]
I went to your support and got this response, so one of you is wrong?

Yes, unfortunately, we don`t have an option to set the centered number of images in Gallery Slider. It automatically sets in one line.
In case if you have any ideas you consider worth implementation, please, add them here: https://github.com/CrocoBlock/suggestions/issues

**Comment by Floydtm** [comment]
Can you tell me the number of your ticket?

**Comment by GazDog** [comment]
Hi Floyd

Response was from Anna

Kind regards,
Alina.
Please, check your ticket status https://support.crocoblock.com/helpdesk/tickets/13406 <https://support.crocoblock.com/helpdesk/tickets/13406>



I may have overcome the problem in that I changed from Hello theme to OceanWP and now they seem to be centred! So
I am guessing it was a theme bug. But it would still good to be able to have alignment. :)


Cheers and thanks
Gaz







Garry Morrow
Phone: +61 402 502 120
Email: gmorrow@bigpond.net.au

**Comment by GazDog** [comment]
Hi Floyd

The response was from Anna
https://support.crocoblock.com/helpdesk/tickets/13406

I may have overcome the problem in that I changed from Hello theme to OceanWP and now they seem to be centred! So
I am guessing it was a theme bug. But it would still good to be able to have alignment. :)


Cheers and thanks
Gaz
