### ISSUE TITLE
JetBooking - Calendar

### ISSUE THREAD

**Issue by leehealy2** [Crocoblock/suggestions#1527]
Plugin: JetBooking
Section: Calendar
Issue: Selecting a 'Week Block' from the day of selection

being able to select a week from the JetBooking Calendar from the actual date selected and - not - as a week 'block'

at the moment it will only let you select the week block starting from that week (eg: if you chose Wednesday it would select Monday to Sunday for the week that the wednesday was selected)

instead, being able to select the wednesday and it booking 7 days from the Wednesday to Wednesday

ie: if selecting Tuesday, it will be tuesday to tuesday, 
if selecting Friday, it will be friday to friday

what ever date the user is selecting it will chose that date and 7 days after.

**Comment by Hammer-ger** [comment]
It is possible.
Add a calculatet Field to your booking-form an calculate
 (checkin/checkout) - (checkin/checkout) 

As the result you will get a specific number. 
(Ist ist not 7, but ist is specific dir every count of days you are booking.

Then use logical  conditions to hide the submit button, if the number is different than the number for 7 days. 

So you can not make a booking in you choose More or less than 7 days.

Best wishes

**Comment by csydesigns** [comment]
> Plugin: JetBooking
> Section: Calendar
> Issue: Selecting a 'Week Block' from the day of selection
> 
> being able to select a week from the JetBooking Calendar from the actual date selected and - not - as a week 'block'
> 
> at the moment it will only let you select the week block starting from that week (eg: if you chose Wednesday it would select Monday to Sunday for the week that the wednesday was selected)
> 
> instead, being able to select the wednesday and it booking 7 days from the Wednesday to Wednesday
> 
> ie: if selecting Tuesday, it will be tuesday to tuesday,
> if selecting Friday, it will be friday to friday
> 
> what ever date the user is selecting it will chose that date and 7 days after.

Yes, please add this feature!  We need this also.

**Comment by UraraReika** [comment]
Hello everyone!

Due to technical reasons, this is almost impossible to do in core of the plugin but this problem can be solved by installing JetBooking from the master + throw this code into `functions.php`:

```
add_action( 'wp_footer', function() {
	echo '<script>
		jQuery( document ).on( "jet-booking/init-field", ( $event, $field ) => {
			var silent = false;
			var format = $field.data( "format" ) || "YYYY-MM-DD";
			$field.bind( "datepicker-change", ( event, obj ) => {
				silent = ! silent;
				if ( silent ) {
					$field.data( "dateRangePicker" ).setEnd( moment( obj.date1 ).add( 7, "d" ).format( "YYYY-MM-DD" ) );
				}
			} );
		} );
	</script>';
}, 99 );
```
