### ISSUE TITLE
Jet Smart Filter - multi-level filter

### ISSUE THREAD

**Issue by Biblothecaire** [CrocoBlock/suggestions#153]
Hi,

To begin, i exeplain what I want to do and  how i do until know :

**Question 1: How to create a level system?**
Any record = level 1
Sheet of my choice = level 2
Another card of my choice level 3
**Question 2: How to make a multi level random filter?**
That is to say that each load, the whole page reloads randomly depending on the level.
Randomly between level 3 before others
Randomly between level 2 after level 3 but before level 1
Randomly between level 1 after others

I work from this page to tcheck what is possible : https://crocoblock.com/wp-query-generator/ 
A lot of things possible, but a point that does not work about the multi-level random filter

WE HAVE on Elementor -  Liting Grid : Post Query
order_offest, order by meta value ! GREAT, this answer my question 1, it work :D
Know stay only 1 detail and will be perfect !
On this 1 post Query, I want to ADD one other post Query : random
I test to add one other order-offset BUT only the last one is taken into account. 
**So we can create two, but only one is taken into account**

I test one other think, create a date_query.
order_offest + date_query - work good, the 2 filter work together
BUT, on the date!query i don't have a random ...

How can I create this double filter ?

Waiting for your help

Regards

**Comment by Floydtm** [comment]
https://github.com/CrocoBlock/suggestions/issues/159
