### ISSUE TITLE
Advanced Settings and Styling for 'Single Upsells' widget [JetWooBuilder]

### ISSUE THREAD

**Issue by raroDev** [Crocoblock/suggestions#1530]
We have this: 

![image](https://user-images.githubusercontent.com/38188761/86235332-8dffdc00-bb98-11ea-964d-e81aac26155e.png)

I would like to see options like in 'Products Grid' widget. Rich setting/carousel mode/ styling every element.

I'm wondering if it is possible to just add query filters in product 'Products Grid' widget for Upsells/Cross-sells.
![image](https://user-images.githubusercontent.com/38188761/86235876-69f0ca80-bb99-11ea-9926-e4a997ede729.png)

**Comment by Floydtm** [comment]
This widget adds the products which may also be needed by the customer when he purchases the product shown on the Single Product page. The upsell products can be set in Linked Products Upsells field available in Products > Product Data block.

**Comment by raroDev** [comment]
I didn't ask about what this widget is, and how to set it...

**Comment by Floydtm** [comment]
understood you. we will not do this for this widget
