### ISSUE TITLE
JetWooBuilder: Separate Blocks - Subcategories and Products

### ISSUE THREAD

**Issue by arekuusa** [Crocoblock/suggestions#1533]
In the page Archive (Jet Woo template) we need separate blocks.
1) How to hide subcategories in the widget Products Loop.
2) How to link the current term ID to the widget Categories Grid http://prntscr.com/ta7b8q 
Macros can be?

**Comment by Floydtm** [comment]
@arekuusa, hi!

**Comment by arekuusa** [comment]
1. Got it. Configured in the customizer.
2. Found another widget Product Categories http://prntscr.com/tackz1

It worked, thanks. http://prntscr.com/tae5u4
