### ISSUE TITLE
Problems JetWooBuilder and JetSmartFilter

### ISSUE THREAD

**Issue by arekuusa** [Crocoblock/suggestions#1534]
1) After the filter Color (Ajax) does not change - the widgets Products Result Count and Products Pagination from JetWooBuilder http://prntscr.com/ta7i3f
Widget Pagination from JetSmartFilter works.
2) After the filter Color (Page reload) in the category page Electronics.
- One color, for example, Black - true products.
- Two colors, for example, Black and Blue - true products. After a few seconds will be incorrect goods from Ajax.
Need to remove automatic Ajax. 
see GIF https://imgur.com/Y1r209T

**Comment by Floydtm** [comment]
@arekuusa, smart filters do not work with plugins of the wubilder https://prnt.sc/taair6 for the second question, please contact our support team

**Comment by arekuusa** [comment]
I see. And how will displays "1-12 of 15"?
Is there a widget other than the widget Products Result Count?
Or can you write in php functions?

**Comment by Floydtm** [comment]
We did not do backward compatibility with woobuilder widgets. However, we plan to make this a separate widget in jetsmartfilters. Stay tuned!
