### ISSUE TITLE
Booking filtering criteria

### ISSUE THREAD

**Issue by lazhar2020** [Crocoblock/suggestions#1537]
My customers need to book an appointment with my 2000 agents (freelance interpreters and translators) based on:

1. service type (interpreting, translating, dubbing...)
2. language combination (French - German for example --> select menu of all language combinations)
3. Whether agents are sworn, conference interpreters, ...)
4. location

That's it. Result: any agent available for the requested day, place, and time. 
Is this something I can design with your plugin? 
Thx

**Comment by UraraReika** [comment]
Hello. Thanks for the feedback.

Sorry for the long delay but yes you can achieve this with our plugins.

Thank you!
