### ISSUE TITLE
[JetEngine] Default form field padding not applied to time fields

### ISSUE THREAD

**Issue by oceandiveloper** [Crocoblock/suggestions#1542]
In an unstyled form the time field doesn't have the same default padding that all other fields have:

<img width="1220" alt="Screen Shot 2020-07-04 at 12 54 30" src="https://user-images.githubusercontent.com/43462095/86505359-0adbc180-bdf6-11ea-80cd-abddf40af103.png">

This can be easily remedied by adding custom padding under Style > Fields > Padding but the initial styling should still be consistent for all fields in the beginning.

**Comment by kaskad88** [comment]
@oceandiveloper The default padding for time fields should be applied from theme styles. Contact with the theme support
