### ISSUE TITLE
Jet-filter-loaded no longer working

### ISSUE THREAD

**Issue by jifola** [Crocoblock/suggestions#1543]
Hello I have used the following snippet but it no longer seems to work with your recent updates, what happened? I hope you can help me, thanks.
`$(document).on('jet-filter-loaded', function($scope, JetSmartFilters, provider, query, queryID) {`

**Comment by PPjev** [comment]
do we have this hook at the moment? Is there a hook after ajax load?

**Comment by SargasTM** [comment]
Now there is a new hook that fires after the content has been rendered

'jet-filter-content-rendered'

$(document).on( 'jet-filter-content-rendered', function (evt, $provider, filterData, providerName, queryId) { } );

Arguments
evt - is just an event
$provider - jQuery provider select
filterData - provider group filter object
providerName - provider name
queryId - provider ID
