### ISSUE TITLE
JetEngine Profile Builder: Posts restriction rules per CPT

### ISSUE THREAD

**Issue by oceandiveloper** [Crocoblock/suggestions#1545]
The user profile builder has the ability to limit the number of posts a user can create based on their user role.
This number will then be applied to all post types in the same way.

Sometimes you need different settings for different post types. For example in my current project users should be able to create an unlimited number posts for CPT 'events' but should only be able to create one post for CPT 'provider'.

Therefore it makes sense to extend the "Posts restriction rules" to specify the rules per CPT like this:

<img width="1064" alt="Screen Shot 2020-07-05 at 08 30 31" src="https://user-images.githubusercontent.com/43462095/86523123-492abc80-be9a-11ea-8a25-96f079522a23.png">

**Comment by Lonsdale201** [comment]
Useful idea, hope this will be an upcoming features in a near future. :)

**Comment by TheBigBanik** [comment]
Great great idea.
