### ISSUE TITLE
FEATURE REQUEST - Dynamic Tooltip

### ISSUE THREAD

**Issue by maurocarreraok** [Crocoblock/suggestions#1562]
The ToolTip functionality is very good. But is not Dynamic.

Practical example:

https://www.loom.com/share/24bf99ca76654681a0b7627305e3bc20

**Comment by maurocarreraok** [comment]
Video reuploaded.

**Comment by kaskad88** [comment]
Added in JetTricks 1.3.3. Feel free to update!

**Comment by maurocarreraok** [comment]
Hi,

Sorry but this is not working today.

![image](https://user-images.githubusercontent.com/68023943/103817953-63f70d00-5046-11eb-903a-b51a928e153a.png)

As you can see the Description is not Dynamic.

Thanks!!!

**Comment by kaskad88** [comment]
@maurocarreraok Are you sure that using the latest version? Because I look like all works fine https://prnt.sc/wi5wp7
