### ISSUE TITLE
FEATURE REQUEST please

### ISSUE THREAD

**Issue by liz36** [Crocoblock/suggestions#1564]
I would be using the Booking Calendar now if it had the ability to allow the client to pay a deposit or part payment.  
eg:  booking a reservation for an event is a total of $400....but the person can pay 50% deposit with the balance before the event.

Please can you add this to a future update asap?

**Comment by UraraReika** [comment]
I merged this issue with #5476, which is on the same subject so we could deal with it more efficiently.
