### ISSUE TITLE
🐞 All jetPlugins: PHP Notice: register_rest_route was called incorrectly. Namespace must not start or end with a slash.

### ISSUE THREAD

**Issue by altechzilla** [Crocoblock/suggestions#1571]
All plugins that use the `register_rest_route` function are using a namespace (stored in the `$this->api_namespace` variable) that starts with a slash. That slash needs to be removed across all plugins. 

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/8274669/87036513-7220b980-c1da-11ea-8170-e1dfcd942d36.png">

**Comment by kaskad88** [comment]
Add for next version.
