### ISSUE TITLE
Geolocation to the widget Maps Listing by JetEngine.

### ISSUE THREAD

**Issue by arekuki** [Crocoblock/suggestions#1574]
Hello. We need Geolocation in the Maps Listing by JetEngine widget. 

Here is an example [https://developers.google.com/maps/documentation/javascript/examples/map-geolocation](https://developers.google.com/maps/documentation/javascript/examples/map-geolocation)
and also we are here nearby somewhere, a block will appear http://prntscr.com/terzc9

**Comment by About2git** [comment]
This would be great!

**Comment by opwolken** [comment]
Yes please! I have a client with a product that is sold in over more than 300 shops in the Netherlands. I'm thinking about using the maps listing. But listing 300 shops without the maps being focust to current location is not working the way I would like. So i'm backing this suggestion!

**Comment by Dennisvb** [comment]
Geolocation is really a must!

**Comment by Antaracid** [comment]
I need it!! This would really great

**Comment by 3wfdev** [comment]
I need it too, everything else about this plugin is great, but a way of at least setting the centre of the map to current location would be good.

**Comment by EnvioMaik** [comment]
How is this implemented before implementing the ability for users to enter an address and radius to search listings? Makes no sense....

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
