### ISSUE TITLE
JetPopup and Login Form from JetBlocks - Ajax does not work

### ISSUE THREAD

**Issue by arekuusa** [Crocoblock/suggestions#1577]
Hello. After clicking the Login form error appears. Ajax does not work. The page reloads. http://prntscr.com/tetjg4
(JetPopup and Login Form from JetBlocks) 
How to do? Or do we need to write functions in php?
Waiting for answers

**Comment by Floydtm** [comment]
I checked your request and everything seems to be working correctly. Please contact our support team, provide access to your site. I hope they will help to solve your problem

**Comment by dayoherrera** [comment]
Buenas tardes, yo estoy utilizando jetpopup y jetblocks para realizar el login, pero cuando agrego credenciales invalidas se cierra el popup y es cuando lo vuelvo abrir que veo el mensaje, como podría solucionar esto que no se me cierre el popup para cuando las credenciales son invalidas?
