### ISSUE TITLE
JetWooBuilder: button Buy Now

### ISSUE THREAD

**Issue by arekuusa** [Crocoblock/suggestions#1578]
Hello. How to create a button Buy Now in a Single Product page and Archive Product page (JetWooBuilder)? Widget or plugin?

**Comment by Floydtm** [comment]
@arekuusa, hi! We don't have such a plugin. Now you can use this [solution](https://wordpress.org/plugins/buy-now-woo/)

**Comment by arekuusa** [comment]
Thanks for the plugin.

And you want to program on the button Buy Now? 
Sometime update version

**Comment by Floydtm** [comment]
In the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by arekuusa** [comment]
Understood thanks
