### ISSUE TITLE
JetEngine form with user AND post sources

### ISSUE THREAD

**Issue by oceandiveloper** [Crocoblock/suggestions#1580]
Hello Crocoblock team,

I have a simple contact form using JetEngine. 

<img width="642" alt="Screen Shot 2020-07-08 at 12 03 02" src="https://user-images.githubusercontent.com/43462095/87135745-08350c80-c2cd-11ea-9a47-99340acbd0d7.png">

It's supposed to pre-set the receiver's email address from the current post's meta field "provider_email". The other fields (name, email address) should be pre-set from the current user's name and email.

<img width="780" alt="Screen Shot 2020-07-08 at 12 03 31" src="https://user-images.githubusercontent.com/43462095/87135766-11be7480-c2cd-11ea-848c-b2ac8ad70a8c.png">

Your support told me that at the moment I have to decide for either "Post" or "User" source (#13783).

I would appreciate a solution where post AND user sources can be pulled in to build more user-friendly and powerful forms.

**Comment by iamdanbarrett** [comment]
@oceandiveloper I needed this recently (on a project I'm currently working on)
