### ISSUE TITLE
JetBooking - Different prices according to schedule

### ISSUE THREAD

**Issue by mustafamohsen** [Crocoblock/suggestions#1588]
I suggest having flexible rules for pricing properties in **JetBooking**

### Some examples

- Renting specific rooms on weekends has different pricing than weekdays 
- Seasonal pricing for resort facility (May 1st - Jul 30th: $200/night, Aug 1st to Dec 31 $180/night, ...etc)
- Even default/exception scheme such as: Renting this bike is $5/day except March 23 is $5.5/day)

I guess this is important specially to hotels and resorts, which have a varying pricing schemes

**Comment by davidteissier** [comment]
Really important for us to have this feature..

**Comment by pierresubotai** [comment]
Super important this feature ! Don't know how to user jetBooking for my GuestHouse if this feature doesn't exists ...

**Comment by tavolucas** [comment]
@Crocoblock  has not done anything and to solve this and it seems that they are not going to do it, I have been waiting for months ...

**Comment by gdelfava** [comment]
This feature is an absolute must. JetBooking is useless without it.

**Comment by webndesign** [comment]
This would be a game-changer! CrocoBlock is such a massive plugin - I don't get why this feature can't be implemented? Unless they don't want to go down this road and compete with specific companies offering hotel/accommodation booking plugins specifically!!!

**Comment by tavolucas** [comment]
Crocoblock simply does not listen, I have lost many hours of work because I did not realize the problem in time. in the end I have solved it with WooCommerce Bookings

**Comment by MjHead** [comment]
Seasonal pricing added with JetBooking 2.4, weekends pricing added before, exact date could be done with the seasonal pricing
