### ISSUE TITLE
JetEngine Show user fields 

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#1591]
I recently needed to show custom meta fields bound to a user profile. I created a repeater field to add multiple web addresses to that specific user. I initially used JetEngine but realised using the Dynamic repeater would not output this information, I repeated the same steps but instead using ACF along with the dynamic repeater field and it worked just fine.

<img width="673" alt="Screenshot 2020-07-11 at 09 49 27" src="https://user-images.githubusercontent.com/3041238/87220467-e33baa80-c35b-11ea-8928-95fb3514f447.png">
<img width="547" alt="Screenshot 2020-07-11 at 09 49 43" src="https://user-images.githubusercontent.com/3041238/87220469-e5056e00-c35b-11ea-9e5e-20a67dc51136.png">

**Comment by arekuki** [comment]
+1

**Comment by arekuki** [comment]
I checked the site after JetEngine 2.5.5 update
To admin http://prntscr.com/vklsd7
The site does not display http://prntscr.com/vkls3x

Can you fix it?

**Comment by Floydtm** [comment]
https://prnt.sc/vkolr5 will be available in the next release. Keep for updates

**Comment by arekuki** [comment]
Reinstalled plugin JetEngine. It worked.
Thank you
