### ISSUE TITLE
Тип поля Number в теме Kava

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#16]
Добрый день, на странице оформления заказа, в теме Kawa поле Number не содержит в себе стрелочек больше / меньше в браузере Chrome и Opera. Хотелось бы чтобы в дальнейшем это было исправлено. http://prntscr.com/mnpcx9

**Comment by CrocoBlock** [comment]
Thank you for sharing your suggestion.

Please, note, that this is the default WooCommerce functionality that is not supposed to be changed from the theme (it is not recommended). 

Also, our team has now prioritized the Elementor-based tasks, and we evolve our products in the context of Elementor functionality.

However, when the tasks related to Elementor functionality and its specifics will be complete, our team will return to this suggestion and look into it.

Best regards from CrocoBlock team

Спасибо за то что поделились предложением.

Пожалуйста, обратите внимание, что этот функционал нежелательно менять из темы. 

К сожалению, наша команда на данный момент отдала приоритет в работе над задачами, связанными напрямую с функционалом Elementor.

Однако, когда данные задачи будут решены, наша команда вернется к данному предложению и рассмотрит его.

P.S. Пожалуйста, обратите внимание, что данный лог предложений находится в доступе для международного сообщества, и для удобства всех участников, а также во избежание дублирующихся запросов, будет более целесообразно формировать запросы на английском языке.

Спасибо за понимание.

С уважением, команда CrocoBlock
