### ISSUE TITLE
JetTabs - Hamburger for mobile

### ISSUE THREAD

**Issue by liranta** [Crocoblock/suggestions#1600]
JetTabs is Great when using it on Horizontal screens.
Once using it on mobile there is a big competition on screen space between the tabs and their content.

I offer a simple solution: Hamburger for Tabs on Mobile.
So you can always see the content and to move between tabs you go to the Hamburger.

Adding this solution will make JetTabs the leading solution for multiple tabs on mobile.

Thanks in advance
Liran

**Comment by Floydtm** [comment]
Now you can place your tabs in the hamburger panel widget and display it on mobile devices. You can contact the support team, they will help you set up everything
