### ISSUE TITLE
Conditional Logic with Text Field (i.e number of characters)

### ISSUE THREAD

**Issue by Willitbang** [Crocoblock/suggestions#1604]
Hi, please add the capability to use conditional logic with the text/text area fields. i.e number of characters.

For example:
I have 2 fields called Short Name and Long Name. One of these fields would be empty depending on the the length (number of characters) of the name. 

if - text field is less than 15 characters - input in 'Short Name' field
if - text field is greater than 15 characters - input in 'Long Name' field

Then I could pull this through in the  Listing using the method mentioned above.
I would then use the hide if empty feature on the listings so I could achieve a consistent design.

Please add this feature as it would expand functionality and design options.

Thanks

**Comment by kaskad88** [comment]
It was implemented in JetEngine 3.2.0
