### ISSUE TITLE
Jet Reviews | Guest Review Submission

### ISSUE THREAD

**Issue by Sayeed1440** [Crocoblock/suggestions#1610]
Hi there,

In the new update (beta release) of Jet Review 2.0.0, I found that you guys have added an option to allow even guests to submit their review.

So, I tested it out on one of my client website (eCommerce).

It works well but there is a glitch.

The review form does not show name, email as a mandatory field in the form. So, basically, when someone submits a review, it shows up as Guest, Guest, Guest, and so on...

See it for yourself: http://wilsonwings.in/snooper/index.php/product/snooperbear/

This is totally wrong & maybe not even a good practice on an eCommerce website.

Can we have a form with email & name? I mean something similar to the one we have in the Woocommerce.

Something like this (scroll bottom): https://desipajamas.com/product/dark-blue-checkered-pajamas-3/

Do let me know if it can be added in the 2.0 final release.

Thanks. Keep up the good work.

**Comment by Sayeed1440** [comment]
Hi Guys,

Are you guys working on it?

Just let me know if it's in your timeline.

**Comment by Bookit24** [comment]
I guess this is something most review plugins have in place, and it makes me worry to see that this request was added 6 months ago and nothing has happened.. 
Might be safer to find a different plugin/solution

**Comment by shinTM** [comment]
sorry for delay, big delay actually) done v2.1.0
