### ISSUE TITLE
JetSearch: Add option to open results item in a new tab (target="_blank")

### ISSUE THREAD

**Issue by oceandiveloper** [Crocoblock/suggestions#1611]
There are use case where you want to open search results in a new tab rather than the same tab. Therefore it would be handy to be able to choose in the widget settings to open all result items in a new tab, e.g. like this:

<img width="278" alt="Screen Shot 2020-07-19 at 05 56 47" src="https://user-images.githubusercontent.com/43462095/87862628-b5222000-c984-11ea-805b-d271b838fc52.png">

At the moment I have a JS workaround in place (thanks to another community member) which works but adds unnecessary bloat:

```
jQuery(document).ready(function() {
    setInterval('SetLinks()', 2000);
});
function SetLinks() {
    if (jQuery('.jet-ajax-search__results-area show')) {
        jQuery('.jet-ajax-search__item-link').attr('target', '_blank');
    }
}
```
Could you please implement a cleaner solution for that?

**Comment by kaskad88** [comment]
Added to the next version!
