### ISSUE TITLE
JetSmartFilter indexer and filter by stock in attibute

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#1613]
Hello, we urgently need to filter only products that have stock in the variations. I am not talking about simple products, which we have already hidden from the catalog, but about variations. I sent a message to support and asked to send here, follow:

Hello, I would like to know if I can hide products that have variations without stock of filters.

For example, I have an attribute called "size", with the attributes: small, medium, large.

I would like that when I click on the "small", the variations without stock do not count.

Currently, this does not exist, showing all the attributes registered, whether with or without stock.

For example, see this link: https://www.lesantos.com/sapatos/?jet-smart-filters=epro-archive-products/default&_tax_query_product_cat=93

All size filters have the number (14), but some products have in stock, like these:

https://www.lesantos.com/tenis-ana-napa-branco/
https://www.lesantos.com/tenis-bota-napa-branco/

So the number "33" shouldn't show.

The same question is in relation to jetSearch, how to hide out-of-stock products from ajax search?

There are other requests for this feature https://github.com/Crocoblock/suggestions/issues/1186 and https://github.com/Crocoblock/suggestions/issues/643

It may seem silly, but it is super important for the customer to filter products that contain stock of the selected variations.

**Comment by marcofrasson** [comment]
Hello? This is super important for many businesses.

**Comment by marcofrasson** [comment]
Hello? @Floydtm

**Comment by marcofrasson** [comment]
@Floydtm

**Comment by Sayeed1440** [comment]
+1 

This is leading to poor user experience.

Imagine you add 4-5 filters & find a product (on the archive page) that is perfect for you. Now, you click on the product & on the product page you see that the product is out of stock for a particular variation (that you used while filtering).

This is a much need update.

**Comment by debihazelden** [comment]
+1 on this. I need this, my site is not very helpful at all without this functionality.

**Comment by debihazelden** [comment]
I'd like this feature also. When filtering by size attribute it makes sense only to the products that have that size in stock. Otherwise the filter is useless. e.g. filtering leggings by size Small - showing all products that actually have size small in stock would be the only common sense solution. I have purchased Jet Smart Filters for this reason and at the moment it's useless to me.
<img width="1506" alt="Screen Shot 2020-09-19 at 6 43 49 pm" src="https://user-images.githubusercontent.com/54105268/93713186-7f531080-fb5a-11ea-8ec6-c9aaddd1d8d9.png">

**Comment by debihazelden** [comment]
This is how someone has fixed the generic WooCommerce filter to hide out of stock attributes if this helps you to fix JetSmart Filters. I've tried it with the generic woocommerce filters and it works but it doesn't work when the Woo Builder plugin is activated for the archive pages.
https://github.com/ctuxboy/Woocommerce-out-of-stock-variations-loop 

Is there a different hook we could hook into to make it work with Woo Builder? this is the one they use woocommerce_before_shop_loop_item_title

**Comment by marcofrasson** [comment]
We are still waiting for that possibility.

This filter plugin works as expected https://codecanyon.net/item/woocommerce-product-filter/8514038

**Comment by honlapdavid** [comment]
Any news?

**Comment by nitsantbndt** [comment]
+1 big time

**Comment by naturalweb-business** [comment]
Hi Croco guys,

Woocommerce worked with a solution for variations, that can be abbled with this instructions https://www.google.com/amp/s/developer.woocommerce.com/2021/08/12/brace-yourselves-new-product-filtering-by-attributes-is-coming/amp/

The wooccomerce taxonomy's filter widget work fine but jetsmart filter don't work, the problem is because the url must be /siteshop/?filter_tax=pa_taxonomy_name

Are you working in a solution for this problem ??

**Comment by nitsantbndt** [comment]
Such shame. this is the most basic feature in filtering products.

**Comment by nitsantbndt** [comment]
if anyone knows a filtering plugin that works with jetwoobuilder (product grid element) please let me know.

**Comment by itsyosk** [comment]
This is the same problem I'm having

**Comment by petrovui** [comment]
Surely +1. Product Grid Plugin got his own sorting. Customize - Woocommerce default sorting not working for this widget. In most cases every ecommerce shop sort their products BY AVAILABYLITY (woocommerce stock status). So the Product Grid widget MUST HAVE an option to:
1. HIDE OUT OF STOCK PRODUCTS FROM GRID
2. CAN BE SORTED BY STOCK IF OUT OF STOCK PRODUCTS AREN'T HIDDEN

T.Y.

**Comment by petrovui** [comment]
Sry. Sooner i've found this https://youtu.be/3ImG8fvXMe4

**Comment by nitsantbndt** [comment]
> Sry. Sooner i've found this https://youtu.be/3ImG8fvXMe4

Irrelevant. This applies only to simple products.

**Comment by danidindan** [comment]
Waiting +1!!!

**Comment by art-n** [comment]
+1

**Comment by zahnd** [comment]
Oh boy, this one is old but still true 🙈 Did someone find a solution to this issue? Anyways, +1 from me.

**Comment by rikgevers** [comment]
+1 how long will be the list? haha

**Comment by PatrykPaziewski** [comment]
+1

**Comment by rikgevers** [comment]
ATTENTION!!!!

Crocoblock send me a php code and it works!!!!!!! 


https://support.crocoblock.com/helpdesk/tickets/141704 


Put the code in a snippet code plugin or in your function.php

goodluck :)

**Comment by zahnd** [comment]
@rikgevers Thank you for sharing. As the link is pointing to a ticket in your support account, we cannot access it. Or I'm doing something wrong. Can you share the code snippet or the direct link to the snippet?

**Comment by rikgevers** [comment]
oh, sorry, I didn't see that.  The code here below you can use.


<?php

class JSF_Variation_Attributes_Stock {

	public function __construct() {
		add_filter( 'jet-smart-filters/query/final-query', array( $this, 'modify_query' ) );
	}

	public function modify_query( $query ) {

		if ( ! function_exists( 'WC' ) || ! isset( $query['tax_query'] ) ) {
			return $query;
		}

		foreach ( $query['tax_query'] as $key => $item ) {
		
			if ( isset( $item['taxonomy'] ) && taxonomy_is_product_attribute( $item['taxonomy'] ) ) {

				if ( is_array( $item['terms'] ) ) {
					$terms = implode( ',', $item['terms'] );
				} else {
					$terms = $item['terms'];
				}

				global $wpdb;

				$prefix = $wpdb->prefix;

				$sql = "SELECT product_or_parent_id 
				        FROM {$prefix}wc_product_attributes_lookup 
				        WHERE term_id IN ( {$terms} )
				        AND in_stock = '1'";

				$posts = array_column( $wpdb->get_results( $sql, 'ARRAY_A' ), 'product_or_parent_id' );

				if ( ! empty( $posts ) && isset( $query['post__in'] ) ) {
					$query['post__in'] = array_intersect( $posts, $query['post__in'] );
				} elseif ( ! empty( $posts ) ) {
					$query['post__in'] = $posts;
				}

				if ( empty( $query['post__in'] ) ) {
					$query['post__in'] = array( 0 );
				}

			}
			
		}

		return $query;

	}

}

new JSF_Variation_Attributes_Stock(); 



Good luck

**Comment by rikgevers** [comment]
`<?php

class JSF_Variation_Attributes_Stock {

	public function __construct() {
		add_filter( 'jet-smart-filters/query/final-query', array( $this, 'modify_query' ) );
	}

	public function modify_query( $query ) {

		if ( ! function_exists( 'WC' ) || ! isset( $query['tax_query'] ) ) {
			return $query;
		}

		foreach ( $query['tax_query'] as $key => $item ) {
		
			if ( isset( $item['taxonomy'] ) && taxonomy_is_product_attribute( $item['taxonomy'] ) ) {

				if ( is_array( $item['terms'] ) ) {
					$terms = implode( ',', $item['terms'] );
				} else {
					$terms = $item['terms'];
				}

				global $wpdb;

				$prefix = $wpdb->prefix;

				$sql = "SELECT product_or_parent_id 
				        FROM {$prefix}wc_product_attributes_lookup 
				        WHERE term_id IN ( {$terms} )
				        AND in_stock = '1'";

				$posts = array_column( $wpdb->get_results( $sql, 'ARRAY_A' ), 'product_or_parent_id' );

				if ( ! empty( $posts ) && isset( $query['post__in'] ) ) {
					$query['post__in'] = array_intersect( $posts, $query['post__in'] );
				} elseif ( ! empty( $posts ) ) {
					$query['post__in'] = $posts;
				}

				if ( empty( $query['post__in'] ) ) {
					$query['post__in'] = array( 0 );
				}

			}
			
		}

		return $query;

	}

}

new JSF_Variation_Attributes_Stock();`

**Comment by zahnd** [comment]
@rikgevers Thank you very much 🙏🏻

**Comment by adansuku** [comment]
Here is the official code. put in your functions.php and it´s works

https://gist.github.com/Crocoblock/1e0ad2e28100fb41f7af0366370cc369

**Comment by naturalweb-business** [comment]
@adansuku Thanks so much :)

**Comment by russcastella** [comment]
> Here is the official code. put in your functions.php and it´s works
> 
> https://gist.github.com/Crocoblock/1e0ad2e28100fb41f7af0366370cc369

Holy crap worked like a charm. Thank you.

**Comment by Crocoblock** [comment]
added compatibility with product variables in JetSmartFilters 3.6.0
also added Hide Out-of-Stock Variations in Filter Results option https://i.imgur.com/h2Mg08D.png
