### ISSUE TITLE
Accordion using repeater field

### ISSUE THREAD

**Issue by TutoDS** [Crocoblock/suggestions#1614]
Add option to create accordion using an repeater field, like **ACF** and **Dynamic Content**

**Comment by Floydtm** [comment]
@TutoDS, hi! I do not quite understand your request. Can you add more details. At the moment we have such functionality https://prnt.sc/tn13gq for the backend. You can also display a [dynamic](https://crocoblock.com/blog/jetelements-dynamic-data-addon-the-key-to-adding-dynamic-content-to-jetelements-widgets/) accordion on the frontend.

**Comment by TutoDS** [comment]
Let's go:
1. On **ACF** I create a **Repeater Field** with 2 fields (Title and Description) (See Image: https://prnt.sc/tn1o7u)
2. On Elementor I use **Dynamic Content Plugin** and **ACF Repeater** to show accordion like this: https://prnt.sc/tn1po8

### Prints on Elementor
https://prnt.sc/tn1q8t
https://prnt.sc/tn1qgh

I use a lot this function to have an accordion with multiple lines, all lines inserted by user on repeater field.
You thing is possible create this using JetEngine?

**Comment by TutoDS** [comment]
If you want see one website where I use that function with ACF:
https://molar.pt/tratamentos

**Comment by Floydtm** [comment]
There is no separate widget in the jetengine plugin to solve your request. But you can use jetengine, jettabs and JetPlugins Dynamic Data Addon. On the backend you make the necessary repeaters https://prnt.sc/tn4l77 on the frontend display it using the accordion widget https://prnt.sc/tn4mi8

**Comment by higorferraco** [comment]
> Não há widget separado no plug-in jetengine para resolver sua solicitação. Mas você pode usar jetengine, jettabs e JetPlugins Dynamic Data Addon. No backend você faz os repetidores necessários https://prnt.sc/tn4l77 no frontend exibi-lo usando o widget de acordeão https://prnt.sc/tn4mi8

Thank you very much! Is there a way to create a template and display it inside the accordion?
