### ISSUE TITLE
[Feature Request] Include "Current Post URL" to QR Code for Dynamic Field widget

### ISSUE THREAD

**Issue by dennylai1990** [Crocoblock/suggestions#1616]
**Please, describe the feature request, making it clear to understand.**

The current QR code widget does not allow to generate QR code based on current post URL. https://prnt.sc/tlkkw5

**Comment by realstephenzhao** [comment]
You have opened a duplicated feature request to mine. -> https://github.com/Crocoblock/suggestions/issues/1238

**Comment by Semonxue** [comment]
I'm working on a project that need this feature to let user open a page from desktop to mobile.

**Comment by maxteria** [comment]
Hi Guys, I'm facing the same point. I need to show an Elementor single template with a **QR Code based on current post URL** using Dynamic Field and QR Code filter output. Thanks in advance

**Comment by et279** [comment]
Has anyone found a solution?

**Comment by kaskad88** [comment]
Added in the next release ( 2.11.3 ). From v2.11.3 the `Post ID` will be convert to `Post URL` in the QR Code callback https://prnt.sc/26qjc5v
