### ISSUE TITLE
Search field icon space issue in front-end

### ISSUE THREAD

**Issue by Artneo7** [CrocoBlock/suggestions#162]
**Describe the bug**
When there's an icon in the search bar it vanishes on click when editing with Elementor. But when viewing the front-end the icon's space remains there.

![Animated GIF-downsized_large](https://user-images.githubusercontent.com/17693529/55591874-1df07500-570d-11e9-9a58-621095a78f77.gif)

**To Reproduce**
See the vídeo below:
https://streamable.com/tbjoy

**Expected behavior**
The search icon should disappear when the bar is focused, so the typing starts at the left side instead of the right side of the icon.

**Comment by kaskad88** [comment]
Done. Available in JetSerch 1.1.4
