### ISSUE TITLE
Allow for Dynamic Content in JetTricks' Tooltips when using Listing Grid

### ISSUE THREAD

**Issue by nickkask** [Crocoblock/suggestions#1622]
I'd like to be able to use Dynamic Content from Custom Post Types in JetTricks' Tooltips when adding to a Listing Grid.
![inyellow](https://user-images.githubusercontent.com/25444915/88075598-0843d080-cb47-11ea-8784-7f68485fdfea.jpg)

**Comment by dennylai1990** [comment]
Seconded!

**Comment by kaskad88** [comment]
Added in JetTricks 1.3.3. Feel free to update!
