### ISSUE TITLE
Bug - Jet SmartFilters - Related Listing 

### ISSUE THREAD

**Issue by dantedanieltesta** [Crocoblock/suggestions#1630]
I have a LISTING, in this listing I put any fields about a post type, and have a relation with other post type... in the same listing I insert a linsting grid and related it with the parent post, this is working well, but the smart filters no works when I have this scructure..

I renamed de Query ID, but not works!!

have a solution?

**Comment by Floydtm** [comment]
Filters do not work with nested listings now. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality. Thank!
