### ISSUE TITLE
Connect pagination to JetEngine Map

### ISSUE THREAD

**Issue by webecks** [Crocoblock/suggestions#1631]
Please add another Additional Providers List to pagination that will connect to JetEngine Map.
https://d.pr/i/RL92fd

So changing to each page will result change the pin marker in the JetEngine Map.

This is very important for us because the current project stuck due to this missing functionality.
Please make this available in the next release.

Thank you.

**Comment by Floydtm** [comment]
Has discussed your request with the plugin developer and must refuse you. The fact is that there are difficulties with counting posts. for example in one provider there are 12 posts, and in another 6. what should pagination display? I hope you understand me. Thank!

**Comment by webecks** [comment]
Hi @Floydtm, thank you for your response, please see how this works here https://everythingaustinapartments.com/property-results-austin/. So the results on the JetEngine Map marker would always be in parallel with the results in the grids.

So right now, in this page https://staging1.everythingaustinapartments.com/home-full-map/, it is setup as 6 grids. In the reference site, there is a previous and next button to loop over the 6 results. Then clicking on the pagination 2, would show the next 6 grids and only these new 6 results are shown. Does this make sense?

So the JetEngine map and the Grid results would always be one to one match. Would you mind considering this again? We have bought the Croco full license and chose to go with JetEngine because this is the direction we are going forward.

Please help looking into this again as this is quite important for us and for sure going to add more features to your JetEngine Map. We are currently stuck as we cannot customize this ourselves, please consider this again. Thank you.

**Comment by Floydtm** [comment]
@webecks, hi! I understand that this is very important for you. But this can become a problem for other users who may have other use cases for pagination.

**Comment by webecks** [comment]
what if you create an option to connect pagination to jetengine map and jetengine listing grid?
If the option to connect to jetengine map is enabled, this will be strictly used for the jetengine map.

That approach would differentiate the use case for other user.
And if other user wants to create the same functionality as ours, then this would be great option. Hence, there are directory themes that connect to google map e.g. Houzz theme and few others that do this. This means that if you create this, you could definitely feature this as one awesome feature.

Houzz theme and those other themes are bloated with too many functionalities that might not be needed. The project that I am working on, simplify a lot of things using Crocoblock and it's Jets plugins.

I know this can be done without affecting the current use of pagination, I would not request this if this cannot be done. Please reconsider this one more time. Thank you.

**Comment by webecks** [comment]
Hi guys, I would like to check in about this one. It says it's closed, does this mean the functionality is on the way or has been added? The map is similar to what FaceWP has done, please see here https://vimeo.com/236259353 would you mind writing me back on this? thank you.

**Comment by webecks** [comment]
If it's not added yet, I hope you can add this very soon, because the current map functionality does not make any sense as it is not integrated to the pagination. If pagination changes from page 1 to page 2, the marker results on the map stays the same. First page, if the grid result is only 6, the result on the map should only 6 markers as well. They should match or at least, it should be the default functionality.

I can see this could be used in many similar niche projects.

**Comment by apatsidis123** [comment]
It is 2024 and the simple pagination filter does not have additional providers yet? I mean all the other filters include additional providers but not the basic one? just changing pages?

Do you intent to implement that any soon?

regards

**Comment by DoingMybestXr** [comment]
+1
