### ISSUE TITLE
Wysiwyg with more possibilities 

### ISSUE THREAD

**Issue by DeClaes** [Crocoblock/suggestions#1632]
The Wysiwyg in the Jetengine Form is very limited. For example you can't add photos to the text.

Is it possible to use the same Wysiwyg in the form as is used in the CPT backend? 

https://drive.google.com/file/d/105Cs2JkKzSdZVSOR4lVSg8M0O6Ort-D1/view

Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. Thanks!
