### ISSUE TITLE
The Single Reviews Form isn't displayed in Quick View Popup

### ISSUE THREAD

**Issue by dislokacia** [Crocoblock/suggestions#1633]
The Single Reviews Form isn't displayed in Quick View Popup

**Comment by UraraReika** [comment]
In our plugin, when creating widgets, we use default Woocommerce functions to ensure maximum compatibility with the Woocommerce plugin itself, as well as the themes that use it.
When building this widget, we use the `comments_template ();` function, which is a standard Woocommerce function and which provides a check for its scope
```
if (! (is_single () || is_page () || $ withcomments) || empty ($ post)) {
    return;
}
```
Therefore, the widget cannot be used in the quick view area.
