### ISSUE TITLE
JetSmartFilters - adding "All" and default selected taxonomy/post

### ISSUE THREAD

**Issue by arekuusa** [Crocoblock/suggestions#1636]
Hello. I created a filter - selected Filter Type Radio and Data Source Posts (or Taxonomies)
See screenshot http://prntscr.com/tnpcbd

Can you add a new "All" to JetSmartFilters? We really need it.

Example in the website, http://prntscr.com/tnpbvn

**Comment by arekuusa** [comment]
Waiting for answers, please. Clients are waiting for me

**Comment by Floydtm** [comment]
Hello! a radio type filter cannot display "all". this is the default behavior. I also want to add that there is no such thing in other filters, but we do not exclude the possibility that we will add this later. Thank!

**Comment by arekuusa** [comment]
Understandably. I came up to write for jQuery.
Example,
`$('.elementor-widget-jet-smart-filters-radio .jet-radio-list-wrapper').prepend('<div class="jet-radio-list__row jet-filter-row"><label class="jet-radio-list__item"><input type="radio" class="jet-radio-list__input" autocomplete="off" name="course_id" value="" data-label="All" checked><div class="jet-radio-list__button"><span class="jet-radio-list__label">All Testimonials</span></div></label></div>');`

Worked into the site
