### ISSUE TITLE
JetEngine - Update Font Awesome 5 to Field type Iconpicker

### ISSUE THREAD

**Issue by arekuki** [Crocoblock/suggestions#1637]
Deprecated Icons in Field type Iconpicker by JetEngine
See http://prntscr.com/tnpft6

You can update the version 5?

**Comment by arekuki** [comment]
When it will be? Time has gone

**Comment by Poklos** [comment]
+1

**Comment by barrychapman** [comment]
+2

**Comment by jspassov** [comment]
+3

**Comment by Crocoblock** [comment]
Was added and released in [JetEngine 3.4.0](https://github.com/Crocoblock/suggestions/issues/7361?fbclid=IwZXh0bgNhZW0CMTAAAR1p_9rhV7aZpdX-TlkVS_ipK8UEwNEwwUF-P9I0p4CpLTJgArl3rPK6PUM_aem_sHlCdhn-jlXw9SGg-LPRuA#:~:text=Custom%20libraries%20for,set%20as%20default.)
