### ISSUE TITLE
Fix variable products on archives with ajax add to cart buttons

### ISSUE THREAD

**Issue by Sidlegionair** [Crocoblock/suggestions#1640]
Example where it happens:
https://hantingdelivery.onetap.website/product-tag/umami-at-home/
1. Type 2595 in the popup
2. Select "Menu's"
3. Try to add one to your basket!

If I investigate the behaviour (because our ajax add to cart works on Single Product Pages) it seems to be because the input:

`<input type="hidden" name="variation_id" class="variation_id" value="0">`

Does not get updated with a variation_id, this makes it impossible to add them to cart, the reason this happens is because normally the following code would have been executed, but this does not happen again after filtering (and updating the DOM). If you run this from console after filter has been done loading it will solve the problem:

```
        if (typeof wc_add_to_cart_variation_params !== 'undefined')
        {
         jQuery('.variations_form').each(function ()
         {
          jQuery(this).wc_variation_form().find('.variations select:eq(0)').change();
         });
        }


```

I would like this to be added in the JetSmartFilters code base after ajaxRequestCompleted

**Comment by UraraReika** [comment]
Fixed in 1.7.2 release.
