### ISSUE TITLE
JetEngine Usage of dot separator in %date_meta|format_date()% Repeater macro

### ISSUE THREAD

**Issue by ihslimn** [Crocoblock/suggestions#1644]
Using %date_meta|format_date(d.m.Y)% (days/months/years are separated by a dot)
causes Dynamic Repeater to output not the date in d.m.Y format,
but the macro string as a plain text. 
Some other symbols like: "/", "-", ":", "," are processed correctly.

So if the field key is "iddate",
    %iddate|format_date(d.m.Y)%&nbsp
in Dynamic Repeater
will output
    %iddate|format_date(d.m.Y)% %iddate|format_date(d.m.Y)% %iddate|format_date(d.m.Y)%

**Comment by kaskad88** [comment]
Fixed in JetEngine 2.6.3
