### ISSUE TITLE
JetProductGallery: If only one image exists, then hide the slider since it's not needed

### ISSUE THREAD

**Issue by jhubsch** [Crocoblock/suggestions#1645]
Some of the products that are on the site I am building using this plugin only have on product image. And yet there is still a slider that appears under the image with the same one singular thumbnail below the big product image.  
  
Can we get an option in place so that, if there is just one product image, the slider is hidden?  

In looking at the code that is output, I'm thinking of a couple of ways this could be done:  
1) Check if product gallery is empty and, if it is, hide .slick-track (or add display:none to it)
2) Count LIs inside div with .slick-track class. If LIs <2 then hide .slick-track  

While these could both be written via external code piggy-backing onto the plugin itself, it would also be great if this was an option in the settings itself somewhere instead.

**Comment by jhubsch** [comment]
For reference and follow-up, I created the following code snippet that accomplishes this:  

`if (jQuery(".slick-track > li").length < 2) {
		jQuery (".jet-woo-slick-control-nav").addClass("hidethis");
	}`

I still think this would be good to be a toggle/setting in the Premium plugin itself but, until then, this should help anyone else that comes across this!

**Comment by jhubsch** [comment]
Posting here again because apparently my code snippet did not work properly and now hides the slider entirely. 
I even tried changing the length count to 3 but, if that snippet is active, the slider is hidden. If inactive, the slider returns but Products that have only one thumbnail still show a thumbnail slide in the slider even though it's the only image for that Product.  

Hoping for assistance in getting a code snippet right to hide the slider in situations like that while this is not inherently part of the plugin's settings...

**Comment by vandijks** [comment]
I'd like to see this functionality too. Who needs pagination if only one image exists? It looks silly.
