### ISSUE TITLE
User Dashboard for Jetengine and Jet booking for end-users to manage bookings.

### ISSUE THREAD

**Issue by ollyjaxx** [Crocoblock/suggestions#1651]
Hi,

It would be good to have a dashboard which connects jetengine and jetbooking.

For example, a travel agency.

Customers who have booked a room/holiday are able to change their booking directly through their dashboard, and can view their booking information such as cancel/view times/see PDF information regarding the booking, without needing to contact the admin to change this for them.

**Comment by Hammer-ger** [comment]
Super important

**Comment by UraraReika** [comment]
This functionality released in 3.3.0 version of JetBoooking plugin.
