### ISSUE TITLE
Jet Smart Filters: Radius filter for Maps Listing

### ISSUE THREAD

**Issue by Pinguinweb** [CrocoBlock/suggestions#1657]
In order to use the maps listing properly on websites with a lot of listing items a radius filter for adresses or postcodes is needed. We have 5 or 6 websites with maps listings and nearly every customer needs a radius filter.

**Comment by oceandiveloper** [comment]
that would be an awesome feature that would make me consider using JetEngine maps listing more often

**Comment by Willitbang** [comment]
This would be a great feature as this would give users more specific post/products for their location. I asked about this functionality on the live Q&A on youtube and the developers said that this will be implemented in the future so I hope this is a high priority. I have previously achieved this with ToolSet but have since switched to Crocoblock so this feature is a must for map listings.

**Comment by travelgu** [comment]
+1 one for this. Proximity-based results would be a huge advantage

**Comment by samuellembke** [comment]
+1 we need this!

**Comment by nicpie** [comment]
+1, essential!

**Comment by Lonsdale201** [comment]
+1

**Comment by velocityconcepts** [comment]
+1 I need this in order to even think about using the Maps in JetEngine

**Comment by startupweb** [comment]
+1 necessity for Geolocation posts near my location.  Great for a business directory.

**Comment by Spacefunls** [comment]
+1

**Comment by sharif09** [comment]
We need this.

**Comment by drwillems** [comment]
+1 Would be so useful to include!

**Comment by julianderyk** [comment]
+100

**Comment by lifeact** [comment]
are there any deadlines?  waiting for this functionality in the project

**Comment by MrBentley** [comment]
+1

**Comment by websightsrus** [comment]
+1 me on this please. I would even love if you could search multiple locations or cities at once.

**Comment by tannguyendalat** [comment]
+1 vote for, it has been a long time

**Comment by mister97** [comment]
+1

**Comment by valleywebdesigns** [comment]
+1 this would be a great feature to have in the toolbox.

**Comment by davejwnz** [comment]
+1 a required feature for mapping now

**Comment by EscaleCommunication** [comment]
+1

**Comment by maljassem** [comment]
+1 this feature is very important, we rally need it.

**Comment by kwsim539** [comment]
+1 This feature is a must-have and the biggest client request.

**Comment by perinbaselvan** [comment]
+1 this feature is very important, Still looking for this, please let us know if there is any way to achieve it via custom developments

**Comment by kwsim539** [comment]
+1 This is the most requested feature from clients when doing a filtered search.

**Comment by websightsrus** [comment]
I would love to see this feature available asap. If it's not added, it would be nice if the Address, Lat and Long info was stored differently in the database so one of the many plugins that can filter by proximity could read it / function with it.

I have a Lifetime license but would happily sponsor the advancement of this feature if I could

**Comment by websightsrus** [comment]
Would love if the ability to show the distance from the searched address to the result was possible.

Thank you!

**Comment by TheBigBanik** [comment]
This is a must. The radius should be in the user's preference and not in the admin's choice.

**Comment by kwsim539** [comment]
+1 Agreed. This is typical with all types of Geolocation search applications. Where a user can select to expand or contract the radius distance from their location to receive search results.

**Comment by ChristiS5** [comment]
+1  Need this please!!

**Comment by dreamsachiever212** [comment]
+1 need this please. it's been very long now any updates at least?

**Comment by kwsim539** [comment]
It has been Pending for the past 2 years. When will this be moved up the roadmap?

**Comment by nphough** [comment]
Yes 100% this is critical to create a robust location search

**Comment by simonclay** [comment]
I also need this feature. Toolset has had this feature for some time.

**Comment by tecnirf** [comment]
Pasaron 2 años y aún sigo esperando esta opción de filtros para el listado de mapas :'')

**Comment by Wapozon11** [comment]
+1 ... I also need this feature

**Comment by h1100** [comment]
+1 vote for, it has been a long time

**Comment by NLGLORY** [comment]
+1 waiting so loooooooooooooooong for this !!

**Comment by TheRealAxas** [comment]
+1 that feature would be game changing! Need it as fast as possible :)

**Comment by Crocsnative** [comment]
+1 We need this so bad! I believe in you Crocoblock-team!

**Comment by simonclay** [comment]
Now starting another project that needs this feature and again will have to use a different plugin to achieve it :(

**Comment by kwsim539** [comment]
> Now starting another project that needs this feature and again will have to use a different plugin to achieve it :(

Agreed! Metabox add-on has already had this in their toolbox for a while now

**Comment by oceandiveloper** [comment]
@MjHead @SargasTM  Phase 1 was implemented a while back. Could we please get an update on future plans for the Geo Search Filter? Currently it's not really usable in real life projects yet.

**Comment by kwsim539** [comment]
> @MjHead @SargasTM Phase 1 was implemented a while back. Could we please get an update on future plans for the Geo Search Filter? Currently it's not really usable in real life projects yet.

Agreed! Metabox add-on has already had this in their toolbox for a while now

**Comment by nphough** [comment]
> > Now starting another project that needs this feature and again will have to use a different plugin to achieve it :(
> 
> Agreed! Metabox add-on has already had this in their toolbox for a while now

I'd love to know what you end up using to achieve this!

**Comment by kwsim539** [comment]
> > > Now starting another project that needs this feature and again will have to use a different plugin to achieve it :(
> > 
> > 
> > Agreed! Metabox add-on has already had this in their toolbox for a while now
> 
> I'd love to know what you end up using to achieve this!

[https://metabox.io/plugins/meta-box-geolocation/](url)

**Comment by simonclay** [comment]
> > > Now starting another project that needs this feature and again will have to use a different plugin to achieve it :(
>
> > Agreed! Metabox add-on has already had this in their toolbox for a while now
> 
> I'd love to know what you end up using to achieve this!

I had to go with [Toolset](https://toolset.com/) to achieve it.

**Comment by TheBigBanik** [comment]
As I can read here, many of you have probable misunderstood what the @Pinguinweb requested. Smart radius filter is to set a Km or Miles radius around you location, not just geolocation. I searched Toolset and Metabox as you mentioned but there is no radius filter, just geolocation which is Ok, But we need radius filter around the geolocation. Crocoblock has already implement the geolocation filter feature https://crocoblock.com/knowledge-base/articles/jetengine-setting-geosearch-based-on-user-geolocation/
It would be great if Radius filter could be in the arsenal soon.

**Comment by jaredpooley** [comment]
This is a deal breaker for me, Only thing my project really needs that Crocoblock cannot currently support.

**Comment by nphough** [comment]
Agreed. I finally gave up and switched to FacetWP. I can’t run my directory site without a zip code search.

**Comment by jaredpooley** [comment]
> Agreed. I finally gave up and switched to FacetWP. I can’t run my directory site without a zip code search.

Thank you will have a look, does it do everything else you need?

**Comment by startupweb** [comment]
Following this.  This would tackle a lot of the features looking for in a directory.

**Comment by nphough** [comment]
> > Agreed. I finally gave up and switched to FacetWP. I can’t run my directory site without a zip code search.
> 
> Thank you will have a look, does it do everything else you need?

So far for me it does. (And maybe a little better). Keyword search, term search etc all great.  Not as easy to style with Elementor but can use CSS. I’m not sure if it has geolocation but I’d rather have radius search and I’m not sure Jet geolocation worked that great to begin with.   There’s probably a way to use the two together but I haven’t tried it.

**Comment by EnvioMaik** [comment]
+1000 this is like the most essential feature of map listings, can't make a directory if people can't even search with address and radius....

You can add a default address with radius on the backend. They just need to move that feature to the front end, so users can select a location and radius to filter listings.

**Comment by kwsim539** [comment]
> +1000 this is like the most essential feature of map listings, can't make a directory if people can't even search with address and radius....
> 
> You can add a default address with radius on the backend. They just need to move that feature to the front end, so users can select a location and radius to filter listings.

Everyone's requests are falling on def ears. This request was created 2 years ago, and two years ago @Floydtm assigned it to @SargasTM and set the status to Pending. Since then it has been dormant with no response from anyone.

It's best everyone here give up too and find other solutions, like [Metabox](https://metabox.io/) and [WP Gridbuilder](https://wpgridbuilder.com/) for the filter facets.

**Comment by TheBigBanik** [comment]
They are in war. I talked to them a lot and it is very difficult to work under these conditions. I am sure they will manage to make it work. Have a little faith on them. I am sure they are trying hard.

**Comment by kwsim539** [comment]
> They are in war. I talked to them a lot and it is very difficult to work under these conditions. I am sure they will manage to make it work. Have a little faith on them. I am sure they are trying hard.

I realize they are in a war and yet since this request was opened there has been 82 releases of JetEngine and 34 releases of JetSmartFilters. But not one response to this request. Seeing as how you have such knowledge of the inner workings of the Croco team, maybe you can provide some insight as to the status of this request and enlighten all that have supported it.

**Comment by Crocsnative** [comment]
Hi guys,
I hired someone to implement a radius-filter on my website, which is an event-database:

https://mynextrace.de/eventsuche/

(If you want to test it out, make sure to use germany city-names, as it is based in germany)
(Also note that the site is slow atm due to disabled cash and lower server capacities)

-> If someone is interested in the implementation of that function send me a reply

**Comment by kwsim539** [comment]
> Hi guys, I hired someone to implement a radius-filter on my website, which is an event-database:
> 
> https://mynextrace.de/eventsuche/
> 
> (If you want to test it out, make sure to use germany city-names, as it is based in germany) (Also note that the site is slow atm due to disabled cash and lower server capacities)
> 
> -> If someone is interested in the implementation of that function send me a reply

Really nice. Is there a way to see this working in a map view? Being able to see the locations in an area on a map is more an ideal UX than a simple list. Or maybe the list on one side and a map on the other with the pinned locations in the queried area.

**Comment by julianderyk** [comment]
how much would you offer for a solution? 
including Map View with visually adjustable search radius, location search, any other filter which is queriable with the wp_query possible, based on free Open street maps. NOT compadible with JSF or Listing grid. everything hard coded (excelent performence)
 if you need a proof just replay with an email address i can send a video link to.
peace

**Comment by Crocsnative** [comment]
> > Hi guys, I hired someone to implement a radius-filter on my website, which is an event-database:
> > https://mynextrace.de/eventsuche/
> > (If you want to test it out, make sure to use germany city-names, as it is based in germany) (Also note that the site is slow atm due to disabled cash and lower server capacities)
> > -> If someone is interested in the implementation of that function send me a reply
> 
> Really nice. Is there a way to see this working in a map view? Being able to see the locations in an area on a map is more an ideal UX than a simple list. Or maybe the list on one side and a map on the other with the pinned locations in the queried area.

I dont have a map version, because in my case its not so important, I think. But the team I worked with could do that, if needed.

**Comment by jaredpooley** [comment]
> how much would you offer for a solution? including Map View with visually adjustable search radius, location search, any other filter which is queriable with the wp_query possible, based on free Open street maps. NOT compadible with JSF or Listing grid. everything hard coded (excelent performence) if you need a proof just replay with an email address i can send a video link to. peace

I would quite possible be interested. Not quite at the stage I'm ready for such an implementation yet but will likely need it soon! Would you be up for sharing details and maybe looking at a price? My email is jared@jaredpooley.com.

**Comment by pierre-wts** [comment]
+1 this function is needed. Hard to imagine a property listing website without a search by localisation input by the user.

I managed to have pretty good results following this tutorial https://itchycode.com/filter-jetengine-map-listing-by-user-input-address-radius-distance-jetengine-jetsmartfilters-query-builder/

But it's hard to implement with other filers in place

**Comment by alexismendozave** [comment]
> Hola chicos, contraté a alguien para implementar un filtro de radio en mi sitio web, que es una base de datos de eventos:
> 
> https://mynextrace.de/eventsuche/
> 
> (Si desea probarlo, asegúrese de usar nombres de ciudades de Alemania, ya que tiene su sede en Alemania) (También tenga en cuenta que el sitio es lento debido a la desactivación del efectivo y la menor capacidad del servidor)
> 
> -> Si alguien está interesado en la implementación de esa función, envíeme una respuesta

me gustaria hablar con quien te ayudo, tengo probleamas para otros filtros

**Comment by bjoernzosel** [comment]
+1

**Comment by talexius** [comment]
+1

**Comment by Lonsdale201** [comment]
Check the new jetengine 3.3 beta update :)

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
