### ISSUE TITLE
Jet Engine - Filter

### ISSUE THREAD

**Issue by Biblothecaire** [Crocoblock/suggestions#166]
Hi,

I ask on support who ask me to submit this feature

On the archive pages created with JetEngine listing grid & elementor template - I want to display the number of articles in each taxonomy. How to do ?

example :
https://madatest.com/destination/antananarivo/
0 to 50 € (X)
50 to 100 (Y)
etc ...

Regards

**Comment by Floydtm** [comment]
Use indexer options for [jetsmartfilters](https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-set-indexer-option-for-filters/)
