### ISSUE TITLE
JetEngine: Dynamic Image widget lacks option to put Image Caption

### ISSUE THREAD

**Issue by agencymkt** [CrocoBlock/suggestions#1662]
Hi, I am making a Listing Item based on repeater fields.

One of the things I need is to put an Image with a custom Caption BUT I can not do it with the JetEngine Dynamic Image widget

Please could you add the option to attach a dynamic Caption image to the Dynamic Image widget?

Thanks.

**Comment by zanga7** [comment]
What are the plans/timeframes for this?

**Comment by voneff** [comment]
Hi @kaskad88, any news on this? I was surprised to find you that this isn’t possible yet. I would really appreciate an update. Thanks!

**Comment by klecka** [comment]
Three years in the making

**Comment by Crocoblock** [comment]
Added new controls https://imgur.com/4mEX2eW
Was added and released in JetEngine 3.6.2
