### ISSUE TITLE
JetPopup: Second Popup not working

### ISSUE THREAD

**Issue by arekuki** [CrocoBlock/suggestions#1669]
Hello.
There is a button in the Popup http://prntscr.com/trtn2m. After clicking does not work the second popup http://prntscr.com/trtmra.
Configured several times http://prntscr.com/trtoag and http://prntscr.com/trtoio 

Is there a bug? Or how to set up?

**Comment by shinTM** [comment]
check popup render conditions, please. Anyway https://gyazo.com/e5ade24042cd0e5824c73f8c539c3ce6

**Comment by arekuki** [comment]
After updating the plugin, I checked the popup. It worked.
Thanks you
