### ISSUE TITLE
Customize Taxonomy output order sorting by name or date in jetsmartfilters

### ISSUE THREAD

**Issue by asmarove** [CrocoBlock/suggestions#1673]
Hi there,

There is no option to filter the taxonomy order using the select filter in jetsmartfilters, this will be very helpful when we have a very big number of taxonomy items.

Also, It will be very helpful if we have a small ajax writing search in the select filter.

**Comment by Floydtm** [comment]
@asmarove, hi! At the moment we will not be able to implement it. You can use this [plugin](https://wordpress.org/plugins/simple-custom-post-order/) to customize the order of taxonomies in the select filter
