### ISSUE TITLE
JetEngine: We need the field Role in the form Registration

### ISSUE THREAD

**Issue by arekuki** [CrocoBlock/suggestions#1676]
Hello. We need the field Role in the form Registration. http://prntscr.com/tsl52b
And also need in Post-submit Actions/Notifications Settings http://prntscr.com/tsl5bk
Can you add to JetEngine?

**Comment by Floydtm** [comment]
@arekuusa, hello! It is not entirely clear to us what this is for. By default, the user role is adjusted in the WordPress settings. Or do you just need to display the user's role on the front-end?

**Comment by arekuki** [comment]
Two registrations (role: Subscriber and Author) in the site

**Comment by Floydtm** [comment]
I understand you, but I have to refuse this request because the role is tuned into the settings of WordPress. It is also not safe to give the user a choice of role for himself.
