### ISSUE TITLE
🐞Templates do not work

### ISSUE THREAD

**Issue by Hammer-ger** [CrocoBlock/suggestions#1679]
Did the tamplates with profile builder Crash?
If i click on a dynamik link (inside a listing Grid)to an tamplate on the Account page, i will be redicereted to the Account page and not to the tamplate. It worked fine till saturday night.
Please need your help.
Thanks a lot.
Maximilian (deHamty)

Hope this request is understandable

**Comment by Floydtm** [comment]
I checked your request and it seems to work well. I do not exclude the possibility that our sites are configured in different ways. Please contact our support team, provide access to the site. I hope they help solve your problem.
