### ISSUE TITLE
Dynamic Visibility and Form Conditional rules - Allow to compare values from other dynamic content

### ISSUE THREAD

**Issue by JohanKRS** [CrocoBlock/suggestions#1680]
Hello!

When setting rules for dynamic visibility or conditional rules in forms I can use an operator to compare my field contents against a fixed value on a list, but not against the value of another dynamic field. I think this would be very helpful.

One example:
I'm creating a form that allows for two different teachers to make independent verifications of certain documentations and assign a grade to a student. I wanted to compare the grades so that:

- if both teachers assign the same grade ("teacher A" graded 10 and "teacher B" also graded 10) = with conditional rules I can compare the value from field A and field B and set the value of a field C as the "final grade = 10";

- if the teachers assign different grades ("teacher A" graded 8 and "teacher B" graded 6) = with dynamic visibility on the listing I can compare the value from field A and field B and, since they are different, make visible a flag to mark it for revision.

There are many other funcionalities that will be made possible if we can compare one filed to another, and not to a fixed list. Thanks!

**Comment by JohanKRS** [comment]
![119137499_3080714868722564_4224722834816328995_n](https://user-images.githubusercontent.com/8008715/93333473-be4f3200-f7f9-11ea-93e1-e0e685adb04e.jpg)

**Comment by Lars8000** [comment]
This needs to be done for a lot of reasons.

**Comment by kaskad88** [comment]
Done
