### ISSUE TITLE
Set the automatic changelog for Jet plugins in an admin panel

### ISSUE THREAD

**Issue by blueberry11** [CrocoBlock/suggestions#169]
https://prnt.sc/n9kn99

**Comment by alriksson** [comment]
+1

**Comment by kaskad88** [comment]
- [ ] JetElements
- [ ] JetBlocks
- [ ] JetBlog
- [ ] JetCompareWishlist
- [ ] JetEngine
- [ ] JetMenu
- [ ] JetParallax
- [ ] JetPopup
- [ ] JetProductGallery
- [ ] JetReviews
- [ ] JetSearch
- [ ] JetSmartFilters
- [ ] JetTabs
- [ ] JetThemeCore
- [ ] JetTricks
- [ ] JetWooBuilder
