### ISSUE TITLE
JetWooBuilder: Products Grid Carousel smooth movement on mobile

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#1694]
***Need to be checked on mobile. 

References:
1. https://test2.auxilley.in/ - how it works now
2. https://www.noon.com/uae-en/ - how it's preferred to work

Requests:
1. in the mobile browser carousel not moving smoothly (getting stuck and move). 
2. when I leave mouse holding it is automatically moving until to grid full view. I want stop moving whenever user take hand from the screen / mouse hold (refer noon.com to check  how they use carousel.

**Comment by UraraReika** [comment]
https://gist.github.com/UraraReika/fe11dcf10002a55b8c7621bdd3f58c32 you this code to expand swiper slider options.
