### ISSUE TITLE
Calendar Repeat Event

### ISSUE THREAD

**Issue by jonburdon** [CrocoBlock/suggestions#1696]
The jet Calendar plugin should be enhanced to allow listings to be repeatable on a single day of the week or month.
Events should also be repeatable based on a start and end date.

Therefore a admin would be able to create a listing for the Calendar which started on next week's date and repeated every Monday until a specified end date.

**Comment by Marxal** [comment]
I completely agree, it's very nice that it covers one day event or several days in a row. But it doesn't cover the following case: Let's say I have one event that repeats every Saturday, so I'd like to list it every saturday for one month. Would it be very difficult to implement? Is there any work around?

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
