### ISSUE TITLE
JetElements Countdown Timer auto-reset/restart periodically

### ISSUE THREAD

**Issue by jcmatoskx** [CrocoBlock/suggestions#17]
Set a countdown (Countdown Timer widget from JetElements) that repeats/auto resets once it reaches zero.  For example, Set countdown to 15:00pm every day, and it counts everyday 24:00 down until it's 15:00pm, and then once it reaches zero it restarts again counting from 24:00.

My specific intention of this feature is to let clients know when we ship out products, since we ship them everyday at 15:00pm, so we can give clients a visual guide until when they can order daily if they wish to receive the item the next day.
My application is daily, but I guess ideally the period of countdown/reset should be set by the user, maybe some users have hourly, monthly or even yearly applications for periodic repeated events.

From my research at the moment it seems like this auto reset countdown feature for elementor isn't available anywhere.

**Comment by kaskad88** [comment]
Added for next version (1.15.15) - http://prntscr.com/o2rqpf.
Thanks for your report!
