### ISSUE TITLE
JetElements: Scroll Navigation - need add the ability to disable on mobile 

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#170]
Scroll Navigation requires the opportunity to be disabled on devices.

**Comment by jpknz** [comment]
@aksamitnaya - I came across this issue also and found a workaround (until such as time as the JetElements team have an elegant solution).

In wordpress go to Plugins -> Plugin Editor
Select the Jet Elements for Elementor Plugin
Locate the file assets -> js -> jet-elements.js

Within the file find line 2081 (nb I'm on version 1.15.9) - the line should look like the below.  It is the `} else {` line not the whole snippet below.
```
if ( ! isMobile ) {
					document.addEventListener( 'wheel', self.onWheel, { passive: false } );
				**} else {**

					document.addEventListener( 'touchstart', function( event ) {
```
Add `/*` after the `}`
Locate line 2149 - it will look like the below. It is just the middle line shown below (e.g. `}`
```
					}, { passive: false } );
				}
			}
```
Add `*/` after the `}`
At the bottom of the page click update file.
This will disable the scrolling on mobile devices.  NB it does not hide the dots on mobile pages however. Users can still tap these on mobile devices to move between the sections. To hide these you can use Elementor directly by selecting the scroll widget - advanced -> Responsive and then hide on mobile/tablet options

**Comment by bulutemre** [comment]
@jpknz, I tried your solution but it didn't work for me. Guys, it is an important subject why it waits so long? Because of this problem, it makes all Responsive design useless.

**Comment by bulutemre** [comment]
Hi guys, I apologize because JetElements team already made a fix. Now I see: https://ibb.co/6WD95XF
I think you can also close this issue ;D

**Comment by kaskad88** [comment]
Added for the next version
