### ISSUE TITLE
JetEngine: Pre-set form field values not working due to Repeater.

### ISSUE THREAD

**Issue by arekuki** [CrocoBlock/suggestions#1701]
Hello. Empty value to fields (Repeater) in page http://prntscr.com/tv8wbc
Probably Pre-set form field values not working due to Repeater. http://prntscr.com/tv8x7e

There's a bug. Are you fixing?

**Comment by Floydtm** [comment]
We are aware of this problem. The developers will fix this if possible. Stay tuned. Thank!

**Comment by Philipp372** [comment]
@Floydtm do you have info if this was fixed already and how it is used?
Thx a lot

**Comment by junior-maker** [comment]
https://www.youtube.com/watch?v=crkzY73iqGE

**Comment by junior-maker** [comment]
solution to this problem: https://www.youtube.com/watch?v=crkzY73iqGE
