### ISSUE TITLE
JetSmartFilters:  Add 'Show "All" Filter' option to Radio Filter

### ISSUE THREAD

**Issue by oceandiveloper** [CrocoBlock/suggestions#1703]
When clicking a filter item in a radio filter, there is no simple built-in way to go back to the default state showing all items. Yes I could use the "Remove Filter" widget and rename it to "All". But this solution is not ideal because it can break the layout in ugly ways when I want all filter items AND the "Remove Filter" widget to be displayed inline and grouped nicely, see here:

<img width="746" alt="Screen Shot 2020-08-07 at 12 43 04" src="https://user-images.githubusercontent.com/43462095/89609883-b2438c80-d8ab-11ea-8b5c-e004cb64d3d0.png">
<img width="345" alt="Screen Shot 2020-08-07 at 12 51 07" src="https://user-images.githubusercontent.com/43462095/89610330-c8058180-d8ac-11ea-8749-8b316d556a52.png">

It would be much more useful to have an option in the filter settings to add an "All" option. The "Posts Extra" widget of Extras for Elementor does exactly that and it works beautifully:

<img width="261" alt="Screen Shot 2020-08-07 at 12 47 01" src="https://user-images.githubusercontent.com/43462095/89610174-74933380-d8ac-11ea-9e16-1e743c2dd5c3.png">
<img width="747" alt="Screen Shot 2020-08-07 at 12 49 01" src="https://user-images.githubusercontent.com/43462095/89610182-78bf5100-d8ac-11ea-84ae-68e3b76b8878.png">

I've had this limitation on multiple projects and would really appreciate an easier approach.

**Comment by reachdigitalaus** [comment]
+1

**Comment by im-bot689** [comment]
+1

**Comment by raabmar** [comment]
Just started using JetSmartFilters with JetEngine and I am looking for exactly the same. Seems so trivial.. would be good to have this option

**Comment by fulloken** [comment]
+1 Please! An "All" option should be standard with the filter function.

**Comment by Floydtm** [comment]
https://prnt.sc/v5WYgwaanqwg
