### ISSUE TITLE
Options to define zoom on click in the map filtering when clicking on the filtered list on map listing (Map listing widget Issue)

### ISSUE THREAD

**Issue by Bejlali** [CrocoBlock/suggestions#1707]
Hello Crocoblock Developers, I need to get control on the map zooming when I click on the filtered list in the map listing widget.

So How I can change the value for zoom on the map listing after clicking on the filtered list?

Best Regards,
BE

**Comment by kaskad88** [comment]
You can use the Max Zoom option https://prnt.sc/15l1j73 to prevent zooms to the highest level
