### ISSUE TITLE
JetEngine: Edit JetEngine Options Pages Via JetEngine Forms

### ISSUE THREAD

**Issue by Racso201** [CrocoBlock/suggestions#1713]
Hi,

Firstly, thank you for creating crocoblock!

Please could you add a action to JetEngine forms to allow us to update JetEngine options pages via forms.

This would be great as it would expand on your frontend form offering, allowing us to create client dashboard with a options page where clients are able to change basic settings for there site that we add to a options page via JetEngine Options Page (which already exists)

Essentially no new functionality is actually required regarding JetEngine Options Page. Simply we need a action inside JetEngine Forms to be able to update data on a options page we have already created.

Thank You.

**Comment by kaskad88** [comment]
Added for the next version.
Thanks for your report!
