### ISSUE TITLE
Jet engine form - media

### ISSUE THREAD

**Issue by floorMM** [CrocoBlock/suggestions#1715]
I am looking for an option to let non-logged-in users upload a logo? How can I apply this?

I now use a form via jet engine that fills out a custom post type.

It says "Note: for security reasons this field will work only for logged-in users!"
Is there a way for this?

<img width="617" alt="Schermafbeelding 2020-08-10 om 16 04 03" src="https://user-images.githubusercontent.com/69144279/89791104-1de35f00-db23-11ea-8fff-16dd25f2590a.png">

**Comment by Floydtm** [comment]
For security reasons, we do not plan to implement this. Only logged in user can upload files
