### ISSUE TITLE
JetSearch exclude subcaegories

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#1716]
Hello, I am using JetSearch, please tell me how to exclude subcategories from the search and leave only the main ones. The support informed me that this is not implemented, I hope you can consider it!
https://downloads.intercomcdn.com/i/o/234860909/e8f0c2bd63364b7caaa49d08/image.png

**Comment by kaskad88** [comment]
Hello, @codeorlov. 
Solution: https://gist.github.com/kaskad88/3437974b92e12a88ff78dc5d95dc8233
Add this code to the functions.php file of the theme
