### ISSUE TITLE
Ability to show products filtered by custom taxonomy in products grid (JetWooBuilder)

### ISSUE THREAD

**Issue by caracol4** [CrocoBlock/suggestions#1720]
It would be great if there was the possibility to show products of a custom taxonomy, not only "tag". Having a fashion e-commerce, we use custom taxonomies for collections for example, and it would be great to use your grid and carousel to showcase that products.

**Comment by sara-kariv** [comment]
it's a MUST HAVE feature.

Please add the option to Query by custom taxonomy
