### ISSUE TITLE
Question: Undefine index error

### ISSUE THREAD

**Issue by NeoAcla** [CrocoBlock/suggestions#1723]
I created a staging site in Plesk and turned on debugging mode.

I updated the woocommerce and wp to latest version.

When I check the live staging site, i got this error message on the page.
Is this normal to staging environment or there is really a problem? I didn't check first the live staging site status before i did an update so I don't know if its an issue due the latest update.

Below screenshot

![undefine line](https://user-images.githubusercontent.com/19571084/89976187-d0790600-dc78-11ea-8776-e1353cc457e9.jpg)

if someone can explain before I continue doing the adjustments of my project. as I'm not a fan of coding.

Thanks in advance.

**Comment by Floydtm** [comment]
Hello! Please contact our support team. Provide access to your site and the guys will try to solve your problem. Thank!
