### ISSUE TITLE
JetPlugin Forms: Upload File (Media) Field for unregistered Users

### ISSUE THREAD

**Issue by LotteK** [CrocoBlock/suggestions#1724]
Dear all,
Unfortunately, it is currently not possible to add a file upload field to a form that non-registered users of the website could use.
Other form solutions (like the one from Elementor-Pro) allow users who are not logged in to upload their résumé along with other form data, for example.
If such a file upload through JetPlugin Form were possible, this could make the use of Elementor-Pro or another form solution unnecessary.
Regards,
Lothar

**Comment by philc100** [comment]
I also need this even if it was limited to images.

**Comment by donbloothoofddesign** [comment]
It would be nice if we seen this feature fast!

**Comment by viabit-dev** [comment]
I think it is a mandatory feature, although by default it was configured only for registered users.

My client asks me for the same thing, that people can send him curriculm vitae (pdf) and be able to manage them with a custom post types.

From Crocoblock support, I was told that this restriction is for security reasons, but let me decide if I want to leave this option open to the public in the forms. That's what recaptcha is for.

Thanks!

**Comment by mayanksdudakiya** [comment]
Yes, Please add this functionality

**Comment by kaskad88** [comment]
Added in JetEngine 2.6.0

**Comment by mayanksdudakiya** [comment]
@kaskad88 I am trying to upload an image from frontend to backend using the ACF plugin but still not working in 2.6.0

1) ACF Field
![image_2020_12_16T12_00_50_901Z](https://user-images.githubusercontent.com/34036151/102346256-902de980-3fc4-11eb-8993-9879a763c4cd.png)

2) Jet Form

![image_2020_12_16T12_00_50_901Z](https://user-images.githubusercontent.com/34036151/102346286-9b811500-3fc4-11eb-9da8-d49fc9e944df.png)

3) 

![image_2020_12_16T11_59_33_552Z](https://user-images.githubusercontent.com/34036151/102346310-a63baa00-3fc4-11eb-9bfc-de703d0e36ef.png)

**Comment by Vinya007** [comment]
Ya, but image not added in acf field.
![image](https://user-images.githubusercontent.com/45792827/102345852-ffefa480-3fc3-11eb-9588-e936886365e5.png)

**Comment by kaskad88** [comment]
@mayanksdudakiya Hi. I will check your case

**Comment by viabit-dev** [comment]
In my case, I can uploads files like a guest. But "download button" from jetelements doesn't work with files uploaded like a guest.

**Comment by LevelUpGit** [comment]
@kaskad88 Hi, in JetEngine when creating form for posting custom post, there is no way to save URL of uploaded image in custom field, when in guest mode of upload. Image gets uploaded, but not linked. I understand if it's not possible to upload it in gallery, but there must be a way to save link.
