### ISSUE TITLE
JetSmartFilters tax_query overrides JetEngine default tax_query on page reload.

### ISSUE THREAD

**Issue by lukechinworth** [CrocoBlock/suggestions#1727]
**Describe the bug**
We are using the JetEngine Listing Grid with JetSmartFilters. We have several tax_querys set on the Listing Grid to filter certain posts by default, and then we use JetSmartFilters (of type taxonomy) to filter the results further. Also, we use type Mixed on the JetSmartFilters so that we can bookmark the url. This works great when we load the page and then apply the smart filters, but when we reload the page with the JetSmartFilters in the url the tax_query from the JetSmartFilters overrides the default tax_query of the Listing Grid instead of merging with it.

**Steps To Reproduce**
1. Add a Listing Grid, and under Post Query add a Tax Query (e.g. for a Category)
2. Add a JetSmartFilter, and select type Taxonomy, and select a taxonomy (e.g. Tag)
3. Add a checkboxes filter to the same page and select the new JetSmartFilter, and select Apply type Mixed, and apply it to the Listing Grid.
4. Load the page. The grid is filtered to the default tax query set on the listing grid.
5. Select a checkbox to filter further. The grid is filtered to the default tax_query AND the JetSmartFilter tax_query, and the JetSmartFilter tax_query is added to the url.
6. Reload the page.

**Expected behavior**
The results are the same, i.e. The default tax_query and JetSmartFilter tax_query are merged just as they were via ajax before.

**Actual Behavior**
The results are not the same. The JetSmartFilter tax_query overrides the default tax_query instead of merging with it. This is caused by array_merge here:
* wp-content/plugins/jet-smart-filters/includes/providers/jet-engine.php:289
* wp-content/plugins/jet-smart-filters/includes/indexer/data.php:88

If you merge the tax_query from each it works. I imagine meta_query from each should be merged too.

**Environment**
 - OS: MacOS 10.15.5
 - Browser: Chrome 84.0.4147.125 
 - JetSmartFilters 1.8.4
 - JetEngine 2.4.9

**Comment by Floydtm** [comment]
Hello! We've checked your request and everything seems to be working well. However, we might have missed something. Please contact our support team. Provide access to the site and we will try to solve your problem. Thank!

**Comment by lukechinworth** [comment]
Ok thanks for taking a look. I'll try to setup an example for you.
