### ISSUE TITLE
Clean code: Crocoblock (if_not_used=true DO NOT LOAD)

### ISSUE THREAD

**Issue by alriksson** [CrocoBlock/suggestions#173]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.

**What problem is your feature request going to solve? Please describe.**
Crocoblock is OK but I'm frustrating new page builders like Oxygen page builder is doing a great job when it comes to smoothness, controls and performance. They do not load anything that isn't needed on that page. This means CSS and JS, if an element or function isn't used it will not load that code. See: https://youtu.be/RmIrqJ9Wd0U?t=623

**Describe the solution you'd like**
- Crocoblock has a lot of bottlenecks in compatibility and performance.
- Improve how things load, don't load unused CSS and JS or code in general that is not in use.
**- You really have to stop loading code that isn't used on a page!**

https://youtu.be/RmIrqJ9Wd0U?t=623

**Describe alternatives you've considered**
Other Elementor plugins, there is many!

**Additional context**
Just check the performance (non of you have optimized it, but using your own page builder to design)

Oxygen: https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Foxygenbuilder.com%2F

Crocoblock: https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fcrocoblock.com%2F

**Comment by MaxZiebell** [comment]
+1

**Comment by kaskad88** [comment]
I merged this issue with https://github.com/CrocoBlock/suggestions/issues/221, which is on the same subject so we could deal with it more efficiently.

Thanks for your feedback!
