### ISSUE TITLE
JetEngine Dynamic Repeater Fields Toggle/Accordian

### ISSUE THREAD

**Issue by iamdanbarrett** [CrocoBlock/suggestions#1730]
It would be a nice logical and complementary options to be able to have a widget to place repeater fields into an accordion/toggle widget on the front-end? I recently required this and I was advised there is a 3rd party 'add-on' out there but it pulled my website down.

**Comment by stasonua0** [comment]
This functionality is already there, use jet tabs + jet dynamic addon

**Comment by iamdanbarrett** [comment]
> This functionality is already there, use jet tabs + jet dynamic addon

Strange, after a support ticket and 2 chats with the support team I was advised it isn't possible?

**Comment by stasonua0** [comment]
it is possible, and I regularly use it in my work


сб, 15 авг. 2020 г., 10:32 Dan <notifications@github.com>:

**Comment by iamdanbarrett** [comment]
@stasonua0 Do you have an example I can see?

**Comment by stasonua0** [comment]
https://nr102.ru/uslugi/kompleksnyj-remont/evroremont/

сб, 15 авг. 2020 г., 14:50 Dan <notifications@github.com>:

**Comment by Lonsdale201** [comment]
You can do it with the "Jettabs" and with the "JetElements Dynamic Data".
![lookatmy](https://user-images.githubusercontent.com/23199033/90318213-57ef9f00-df2f-11ea-9f0c-cfb857b52583.png)

**Comment by Gitmarcc** [comment]
Hi, what if I want to display a dynamic gallery instead of just text inside the tab? https://prnt.sc/14kjry5
I'm only been able to get the img IDs. https://prnt.sc/14kk3c3
Any advice?
