### ISSUE TITLE
Improve Relationship Fields in Posts

### ISSUE THREAD

**Issue by apistoman** [CrocoBlock/suggestions#1734]
Instead of typing in the name of a relation in the relationship fields, surely it would be simpler to provide a select drop field, with singular choice on one - to - one and one - to many and multi select on many to many relationships (especially the latter). 

This would greatly enhance the user experience,  and in the case of many to many relationships considerably quicker, also you wouldn't have to try and remember the name of the relationship link, code wise you are looking at some SQL, as you already have for Ajax, and a code loop to build the select list.

First thing that popped in to my head when I so an example of the system on wptuts youtube video

**Comment by MjHead** [comment]
Re-factored with 2.11.0
