### ISSUE TITLE
BUG - Listing Grid - Slider Dots Unaligned

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#1746]
Hi guys!

As you can see the dots in the Listing Grid are not aligned to the center of the screen. I even try adding less "testimonials" and is not working.

https://www.loom.com/share/cf55d4a6df554bcd81cac0731690ed12

Theme used: Hello (latest version, elementor pro latest version, wp 5.5)

Thanks

**Comment by oceandiveloper** [comment]
> As you can see the dots in the Listing Grid are not aligned to the center of the screen.

This is not necessarily a bug in the plugin, just the default styling of the UL tag for the dots which adds left padding of 30px in Hello Theme. 
<img width="1149" alt="Screen Shot 2020-08-20 at 10 15 18" src="https://user-images.githubusercontent.com/43462095/90709191-38a99680-e2ce-11ea-9d15-542f11daf3ce.png">

You can usually fix this by adding some simple CSS (either to you global custom CSS or the listing grids custom CSS):

```
.jet-slick-dots {
    padding-left: 0;
}
```

This problem could be avoided entirely though if JetEngine's developers added this little fix to JetEngine's CSS file.

**Comment by maurocarreraok** [comment]
Hi @oceandiveloper ! Thanks, yes i know! I was only showing this error to Croco's Teams so they can fix it. :)
Thanks!!!

**Comment by maurocarreraok** [comment]
Hi, any news about this? @kaskad88

**Comment by maurocarreraok** [comment]
@Floydtm

**Comment by maurocarreraok** [comment]
Nothing yet? Really.....

**Comment by kaskad88** [comment]
Fix for the next version ( 2.9.3 ). Thanks for your report!
