### ISSUE TITLE
Jet Elements: Horizontal timeline no swipe/drag option with navigation on mobile  

### ISSUE THREAD

**Issue by jansolo76** [CrocoBlock/suggestions#1748]
A few days ago i tried the horizontal timeline widget and it's great. But i encountered a major downfall in usability, because on mobile i wasn't able to drag or swipe the slides when using the navigation option. It would be really handy if this option could be implemented.

Thanks, Jan

**Comment by simonclay** [comment]
I also would like to see this feature. 

Being able to swipe on mobile on table would make it a better experience for touch users.

Also, it would be great to be able to change the layout on smaller devices. On mobile, it doesn't always fit quite right using the 'middle' layout. I'd like to change it on mobile to be the 'above the timeline' layout.

To get around this I have had to create 2 versions of the same timeline and hide them on different devices.

**Comment by kaskad88** [comment]
Added in JetElements 2.5.8
