### ISSUE TITLE
Adding the Max number of Posts for Map Listing

### ISSUE THREAD

**Issue by dent77** [CrocoBlock/suggestions#1753]
Hi Croco team

It seems that the max number of posts that can be displayed in Listing Map is only 1,000.
I would like to kindly request if you could increase the max number of posts to 100,000 or even more..

You guys are doing so great! Keep it up...

Cheers

**Comment by kaskad88** [comment]
I merged this issue with #2163, which is on the same subject so we could deal with it more efficiently.
