### ISSUE TITLE
Advanced Carousel(dynamic) - Hide slides that don't have image

### ISSUE THREAD

**Issue by LevelUpGit** [CrocoBlock/suggestions#1754]
When using Advanced Carousel slides with **dynamic pulling** for: _slider image_ and _item link_ from **option pages**, slides that do not have image doesn't automatically hide, there is just blank slide. So i have to constantly adjust number of slides.
Is there a way to hide them, or am i missing something?

Thank you.

**Comment by githuphub** [comment]
I have the exact same issue. Sadly still no fix for this.

**Comment by Gawuww** [comment]
Added in JetElements 2.6.2

**Comment by LevelUpGit** [comment]
Thanks!!

**Comment by githuphub** [comment]
Happy to see it's solved :D
