### ISSUE TITLE
JetEngine - JetForms - Database Record for form entries and submissions

### ISSUE THREAD

**Issue by Josholo** [CrocoBlock/suggestions#1759]
JetForm needs to have the ability to either integrate with other 3rd party database plugins or incorporate this functionality natively within Crocoblock / Jet Family. 

I am using JetForms for sales enquiries and quote requests for a service-based business. JetForms is great for function and easy to use to create dynamic forms however it is lacking the ability to link with a database. 

Existing tools like contact form 7 includes integrations with basic databases stored as a CSV file in WordPress. Something that allowed us to link a database as a CSV file to enable import and export functions would be great and allow me and i'm sure others to capture the information and report on form submissions. 

In it's current state, JetForms can only export form submissions via email or to a custom post type. I don't believe its practical to rely on this as the only way to records form submissions especially emails. This makes it challenging if a end-user was to submit a form and complain that it was completed but never received by the business. With a simple database that has a meta field per column header with the metadata in each cell below, I could easily review records.

The feature i am requesting is achieved in contact form 7 via this plugin in the wordpress repository - https://wordpress.org/plugins/contact-form-cfdb7/

**Comment by MjHead** [comment]
This feature will be added in JetEngine 2.5.0

**Comment by Josholo** [comment]
Thankyou for this update. This is great news!



Kind Regards,



Joshua Holopainen

*Business Development & Marketing Manager*

[image: Email Logo 1]

*M)* 0477 014 462

*E)* Josh@rfsteelbuildings.com.au

*W)* www.rfsteelbuildings.com.au

[image: Facebook icon] <https://www.facebook.com/RFSteelBuildings>  Follow
us on Facebook!





*From:* Andrew Shevchenko <notifications@github.com>
*Sent:* Thursday, 10 September 2020 7:33 PM
*To:* Crocoblock/suggestions <suggestions@noreply.github.com>
*Cc:* Josholo <josh@rfsteelbuildings.com.au>; Author <
author@noreply.github.com>
*Subject:* Re: [Crocoblock/suggestions] JetEngine - JetForms - Database
Record for form entries and submissions (#1759)



This feature will be added in JetEngine 2.5.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Crocoblock/suggestions/issues/1759#issuecomment-690112905>,
or unsubscribe

**Comment by laurentgarin** [comment]
Hi, is it available now?
Thanks.

**Comment by jarahner** [comment]
> This feature will be added in JetEngine 2.5.0

Any news? It's marked as ready for release for almost a year now and JetEngine is already on 2.8.8
