### ISSUE TITLE
WooCommerce Widgets (Cart, Checkout & Account)

### ISSUE THREAD

**Issue by alexander-pankart** [CrocoBlock/suggestions#1762]
Hi **Crocoblock Nerds**!

I'm using Elementor Pro /w JetPlugins 💯 .

It would be awesome, if the **Cart**, **Checkout** and **Account Page** could be designed (without coding :P).
I've seen that feature a lot last time (for example: Elementor Powerpack).

![image](https://user-images.githubusercontent.com/69971188/90771933-3fe39b00-e2f4-11ea-914a-4fa6c1cbab5c.png)

All other Widgets for WooCommerce are pretty nice, but then -> Checkout (ugly (again, withoud coding))

You're the best.

best regards,
Alexander Pankart

**Comment by alexanderpankart** [comment]
#498 >>>

**Comment by UraraReika** [comment]
I merged this issue with #498, which is on the same subject so we could deal with it more efficiently.
