### ISSUE TITLE
Dynamic Visibility of JE with WC

### ISSUE THREAD

**Issue by bormotovva** [CrocoBlock/suggestions#1763]
1) I mean that I have the add to cart button but I want to hide it and show another in case there are variations in the product. 
https://www.facebook.com/groups/CrocoblockCommunity/permalink/3500129560078440/

2) I want to show a widget (button) when there are products on my woocommerce cart.  https://www.facebook.com/groups/CrocoblockCommunity/permalink/3507258696032193/

3) display some content on product page only if product was bought
https://www.facebook.com/groups/CrocoblockCommunity/permalink/3530809753677087/

4) Show an element (through dynamic visibility) just if the Woocommerce product attribute exist
https://www.facebook.com/groups/CrocoblockCommunity/permalink/3594701670621228/

**Comment by UraraReika** [comment]
JetEngine already has wide range of WooCommerce based dynamic visibility options so you can choose from them. Some options from your request done already something will be added soon.
