### ISSUE TITLE
Global styles in Dynamic Widgets

### ISSUE THREAD

**Issue by p34532** [CrocoBlock/suggestions#1767]
An option to be able to select Global colors and fonts in the Style tab of Dynamic Widgets.

Meaning we could configure Global Styles (introduced in Elementor 3.0) and select them in Dynamic widgets (from Crocoblock). Then after changing the values of Global Styles, the look of Dynamic elements using these styles would change accordingly.

**Comment by kaskad88** [comment]
I merged this issue with #1823, which is on the same subject so we could deal with it more efficiently.
