### ISSUE TITLE
Add additional JetEngine Listing Carousel Widget

### ISSUE THREAD

**Issue by deckerweb** [CrocoBlock/suggestions#177]
For JetEngine plugin:

**Please, describe the feature request, making it clear to understand.**

Currently the Listing Grid widget of JetEngine is working like a charm.
However, what I would need for various projects and views would be a **Carousel view** of the same thing.

In my opinion this should be implemented as an additional widget to the Grid based one, this allows for specifics regarding the carousel/sliding functionality if needed.

**Add an example of where this feature is already implemented.**

I will use this for example to make Reviews carousel on a website's homepage which is completely powered by a CPT defined in JetEngine. The Carousel widget then would me a allow to add a special listing with featured reviews.

But here the possibilities are endless. A carousel for the whole thing would allow to slide any data coming from a Listing of JetEngine consisting of anything like text and meta data etc.

**Comment by MjHead** [comment]
Added in JetEngine 1.4,0
