### ISSUE TITLE
Add sortable/draggable capabilities to "Posts" and "Relations" fields when multiple items.

### ISSUE THREAD

**Issue by quentinaurat** [CrocoBlock/suggestions#1770]
Hi,
It would be great to implement "sortable" functionality by drag and drop for the "Posts" and "Relations" field types. Assuming, the user set it to "Allow to select multiple values", obviously.
I dont know how easy it is to implement, but I think this would be a great addition for instance : when you have many many post to add with the field and you have to display them in the original field order. Now imagine you need to "insert" a new one in between the first and the second, but you have 10 items! You need to manually remove the 9 firsts, then add your black sheep, then recreate the removed items by hand.. Very frustrating. Or I just miss something.
Cheerz

**Comment by josephcylui** [comment]
I badly need this feature as well, I am adding a feature where the clients can pick a list of post as featured news items, but I am in the process of redoing it in ACF because of the missing drag and drop function, I really want to stay in crocoblock but the fields implementation has to be better.

**Comment by centtreize** [comment]
Same here, would love to see that functionality implemented.

**Comment by Matthew-Hillhouse** [comment]
This is the ONE feature I absolutely would love. I use relations for clients ALL the time, but always run into a problem with clients wanting wanting to order items in a specific way that falls outside of the normal options. Being able to drag&drop order them in the relations field and then being able to show listing grid in that order would be a game changer for most of the sites I build. ACF has this feature. I'd love it here.

**Comment by MjHead** [comment]
Relations is sortable since 3.6.0 update
