### ISSUE TITLE
JetEngine and Elelemtor (PRO) 3.0 produces E_ERROR

### ISSUE THREAD

**Issue by sigersmit** [CrocoBlock/suggestions#1772]
Update to Elementor 3 (+Pro) causes website to produce critical error. Switching off JetEngine solves the problem.
It happens on multiple websites using JetEngine.

Error:
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 49 van het bestand URL/public_html/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php. Foutmelding: Uncaught TypeError: Argument 2 passed to Elementor\Core\DynamicTags\Dynamic_CSS::__construct() must be an instance of Elementor\Core\Files\CSS\Post, string given in URL/public_html/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php:49
Stack trace:
#0 [internal function]: Elementor\Core\DynamicTags\Dynamic_CSS->__construct(2325, '990')
#1 URL/public_html/wp-content/plugins/elementor/core/files/manager.php(49): ReflectionClass->newInstanceArgs(Array)
#2 URL/public_html/wp-content/plugins/elementor/core/files/base.php(74): Elementor\Core\Files\Manager->get('Elementor\\Core\\...', Array)
#3 URL/public_html/wp-content/plugins/jet-engine/includes/components/elementor-views/dynamic-tags/manager.php(87): Elementor\Core\Files\Base::create(2325, '990')
#4 URL/public_html/wp-includes/class-wp-hook.php(287): Jet_Engine_Dynamic_Tags_Manag

**Comment by quentinaurat** [comment]
Same issue Here, tested with Elementor 3beta6 (with the pro and the free versions) : on a minimalist blank new install of WP, with jet-engine installed and configured as usual, the listing grid widget return a 500 error and freeze Elementor editor. Tried many things but nothing work actually. 
I've no tested everything, but it seems that the Jet suite (latest version at this date) is not ready for Elementor V3..

**Comment by XVII** [comment]
Can you change the title to "Elementor 3.0 Compatibility"? It's potentially a wider issue than just JetEngine.
I'm surprised validation is not a day #1 thing since Elementor 3.0 has been in developer beta for months.

- [Developers Deprecation Post](https://developers.elementor.com/v3-0-planned-deprecations/)
- [DOM Wrapper Changes](https://developers.elementor.com/dom-improvements-ahead-html-wrappers-removal-from-v3-0/)

**Comment by kaskad88** [comment]
Fixed in JetEngine v.2.4.10. Feel free to update
