### ISSUE TITLE
Sorting in Select filter of JetSmartFilters

### ISSUE THREAD

**Issue by rakpolek** [CrocoBlock/suggestions#1776]
Hi
The list in Select filter of JetSmartFilters is not sorted. It will be good to have an option to sort alpfabetically
Best Regards
Piotr

**Comment by Floydtm** [comment]
Hello! We understand that this is very important for you, but now we cannot implement it. However, we will try to return to this. Right now you can sort the list of items using the [Simple Custom Post Order plugin](https://wordpress.org/plugins/simple-custom-post-order/)
