### ISSUE TITLE
Smart Filters search multiple custom fields

### ISSUE THREAD

**Issue by stijnvanouplines** [CrocoBlock/suggestions#1785]
I made a custom post type with JetEngine that has 3 meta fields.

I want to filter the listing grid by these 3 meta fields with a JetSmartFilters search field.

The 'Search by' option 'Default WordPress search' only searches in the title of the custom post type. But I want to let it also search in the 3 meta fields. I can change the 'Search by' option to 'By Custom Field' then I can specify a query variable. But this is only one meta field. At this moment it's not possible to add more than one query variable.

**Comment by sahilpopli** [comment]
+1

**Comment by endlosweit** [comment]
+1

**Comment by mathiasdb** [comment]
Hi

This isn't a CrocoBlock solution but it utilizes the official WordPress filter hooks.
Make sure the Smart Filter uses the Default WordPress Search.
Just add these snippets to your themes functions.php or create a small plugin.

`add_filter( 'posts_join', function( $join, $query ) {

    if( !$query->is_search() ) return $join;

    //= maybe limit to one post type, or remove
    //if( !in_array( 'your_cpt', (array) $query->get( 'post_type' ) ) ) return $join;

    global $wpdb;
    $join .= " LEFT JOIN {$wpdb->postmeta} ON {$wpdb->posts}.ID = {$wpdb->postmeta}.post_id ";

    return $join;

}, 10, 2 );`

`add_filter( 'posts_where', function( $where, $query ) {

    if( !$query->is_search() ) return $where;

    //= maybe limit to one post type, or remove
    //if( !in_array( 'your_cpt', (array) $query->get( 'post_type' ) ) ) return $where;

    global $wpdb;
    $where = preg_replace(
        "/\(\s*" . $wpdb->posts . ".post_title\s+LIKE\s*(\'[^\']+\')\s*\)/",
        "( {$wpdb->posts}.post_title LIKE $1 ) OR ( ( {$wpdb->postmeta}.meta_key = 'your_first_meta_key' OR {$wpdb->postmeta}.meta_key = 'your_scnd_meta_key' OR {$wpdb->postmeta}.meta_key = 'your_thrid_meta_key' ) AND {$wpdb->postmeta}.meta_value LIKE $1 )",
        $where
    );
    return $where;

}, 10, 2 );`

Hope this helps.
Please do not that this may break your website, do not implement in a live environment.
Test it on a dev.

Kind regards
Matt

**Comment by trofimartya** [comment]
> Hi
> 
> This isn't a CrocoBlock solution but it utilizes the official WordPress filter hooks. Make sure the Smart Filter uses the Default WordPress Search. Just add these snippets to your themes functions.php or create a small plugin.
> 
> `add_filter( 'posts_join', function( $join, $query ) {
> 
> ```
> if( !$query->is_search() ) return $join;
> 
> //= maybe limit to one post type, or remove
> //if( !in_array( 'your_cpt', (array) $query->get( 'post_type' ) ) ) return $join;
> 
> global $wpdb;
> $join .= " LEFT JOIN {$wpdb->postmeta} ON {$wpdb->posts}.ID = {$wpdb->postmeta}.post_id ";
> 
> return $join;
> ```
> 
> }, 10, 2 );`
> 
> `add_filter( 'posts_where', function( $where, $query ) {
> 
> ```
> if( !$query->is_search() ) return $where;
> 
> //= maybe limit to one post type, or remove
> //if( !in_array( 'your_cpt', (array) $query->get( 'post_type' ) ) ) return $where;
> 
> global $wpdb;
> $where = preg_replace(
>     "/\(\s*" . $wpdb->posts . ".post_title\s+LIKE\s*(\'[^\']+\')\s*\)/",
>     "( {$wpdb->posts}.post_title LIKE $1 ) OR ( ( {$wpdb->postmeta}.meta_key = 'your_first_meta_key' OR {$wpdb->postmeta}.meta_key = 'your_scnd_meta_key' OR {$wpdb->postmeta}.meta_key = 'your_thrid_meta_key' ) AND {$wpdb->postmeta}.meta_value LIKE $1 )",
>     $where
> );
> return $where;
> ```
> 
> }, 10, 2 );`
> 
> Hope this helps. Please do not that this may break your website, do not implement in a live environment. Test it on a dev.
> 
> Kind regards Matt

Unfortunately not working... Do you have maybe new version of code that is more relevant?

P.S. +1 to this feature

**Comment by Floydtm** [comment]
Available since version 2.3.0 https://prnt.sc/y6sj7YS5nXGZ https://prnt.sc/tu2J6IA3WIlk

**Comment by trofimartya** [comment]
> Available since version 2.3.0 https://prnt.sc/y6sj7YS5nXGZ https://prnt.sc/tu2J6IA3WIlk

Ok but how to make it work to search by title and by meta fields? post_name is the post's slug. post_title not working for me... 
http://joxi.ru/vAWogXYS33z0yA
http://joxi.ru/KAgLQZMc550dLr

meta fields search works well 
http://joxi.ru/V2VoqDeSBBO5EA

**Comment by Floydtm** [comment]
#4939

**Comment by trofimartya** [comment]
> #4939

Still not working unfortunately... :(
