### ISSUE TITLE
JE Forms: Select label in the Email Notifications

### ISSUE THREAD

**Issue by bormotovva** [CrocoBlock/suggestions#1788]
In case we have in the Forms the select field type wherein we have filled the value and label fields, http://prntscr.com/u6p9li then on the front-end we see the labels available to be chosen in the list - http://prntscr.com/u6pacc
Let's go back to the form settings, to the email notification where we adjust this select field in the Content type with the macro %select_field_macro%
After form submitting we get the email with the value http://prntscr.com/u6pbp0, but I need to have the labels, the same as it appears on the front-end.
Thanks.

______***_________
and the same for the checkbox fields

**Comment by MjHead** [comment]
This functionality requires a lot additional calculations that will have impact on the whole form stability. So for such case we reccommend to set the same values into both - label and value options.
