### ISSUE TITLE
2 way iCal for JetBooking

### ISSUE THREAD

**Issue by boostlyapi** [CrocoBlock/suggestions#1795]
The biggest thing missing from JetBooking is iCal sync. Preferably 2 way. Import and export.

The best theme use of this I have tested is Homey: https://themeforest.net/item/homey-booking-wordpress-theme/23338013

There is a front end dashboard setup, with an import iCal URL field and an export URL generated.

The theme page templates includes an iCal page, which handles synchronization internally.

Can you reverse engineer this please? :) It will make Jet PERFECT!

What I need is an availability calendar on a listing page, showing live/updated booked/available dates.

This data would also need to be used on the checkin/checkout date picker and blocked dates are not allowed to be selected.

Also the data must be used when searching/filtering to only show available listings from iCal dates.

This is another iCal plugin that works perfectly: https://www.wpsimplebookingcalendar.com/

**Comment by Rubenzella** [comment]
This sounds like issue #1557

**Comment by WardenCommander** [comment]
following for update

**Comment by ghost** [comment]
plesase implement this or at least a manual way to mark some dates as unavailable

**Comment by zigy1981** [comment]
Hi, any news on this upgrade?

**Comment by Digitalsail-gr** [comment]
following for update

**Comment by UraraReika** [comment]
I merged this issue with [#1557](https://github.com/Crocoblock/suggestions/issues/1557), which is on the same subject so we could deal with it more efficiently.
