### ISSUE TITLE
Leaflet OpenStreetMap integaration  in JetElemets

### ISSUE THREAD

**Issue by smoookeee** [CrocoBlock/suggestions#18]
As far as google made maps not for free - maybe there is a chance to make Leaflet OpenStreetMap integaration  in JetElemets? / C тех пор как Google ввела плату за использование карт на сайтах - может есть возможность  в интеграции каких то бесплатных аналогов типа Leaflet OpenStreetMap?﻿

**Comment by CrocoBlock** [comment]
Thank you for sharing your vision and for your suggestions.

Unfortunately, our team has now prioritized the Elementor-based tasks, and we evolve our products in the context of Elementor functionality.

However, when the tasks related to Elementor functionality and its specifics are complete, our team will return to this suggestion about integration and look into it.

Also, please, note, that it's not necessary to use the paid version of Google maps to integrate maps to the website. Feel free to check this tutorial out: https://crocoblock.com/school/articles/how-to-create-google-map-api-key-to-use-advanced-map-widget-for-elementor/

Best regards from Crocoblock team

**Comment by rtpHarry** [comment]
Looks like this is coming now #5417 

<img width="910" alt="image" src="https://user-images.githubusercontent.com/1038062/170599972-de3c6fb5-f895-43f3-83b0-12d3fc932ee4.png">
