### ISSUE TITLE
Добавить отметку времени к Current Date в скрытом поле

### ISSUE THREAD

**Issue by Michael-sr** [CrocoBlock/suggestions#1803]
Сейчас выставляется только дата, прошу добавить время через букву "T" как в стандартном поле Datetime.
Сейчас, например, так: "2020-08-31"
А нужно так: "2020-08-31T15:30"
Заранее спасибо.
![WordPress - Google Chrome 1](https://user-images.githubusercontent.com/58707036/91827733-abb0f680-ec58-11ea-801f-b1135033a2bc.png)
![WordPress - Google Chrome 2](https://user-images.githubusercontent.com/58707036/91827737-ace22380-ec58-11ea-8431-f34f1b09e4bf.png)

**Comment by Floydtm** [comment]
Thank you for sharing your suggestion with our team,

We have already received the request to add this feature and it is added to our backlog already.

Also, please, pay attention that we accept feature requests in English only. Please, make sure to submit the requests in English in the future to let all the community members understand what's needed and prevent duplicated entries.

**Comment by Michael-sr** [comment]
Thanks.

**Comment by MjHead** [comment]
@kaskad88 - сделай плз или 2 новых опции - Current Datetime, Timestamp или поле для формата даты (но в таком случае все равно желательно добавить отдельную опцию для Timestamp )

**Comment by kaskad88** [comment]
In JetEngine v2.4.12 will be an ability to set the date format to the current date hidden field.
