### ISSUE TITLE
Automatic relationship with Profile builder (Agent and Property)

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#1807]
**Feature Request for JetEngine**

Recently in a video tutorial "How to set up database relationships" I asked about how to make the automatic relationship on the frontend, when an agent creates a new property using profile builder forms happen automatically without having to do it on the backend manually, due to having already registered as an agent, the idea was good and I was asked to register here!

![crocoblock-suggestion1](https://user-images.githubusercontent.com/6773491/91883169-70afc280-ec5a-11ea-866a-febe69f8284a.png)

Sorry for the bad English, I speak only Portuguese and I can't explain the idea better at the moment.

**Comment by MjHead** [comment]
Hi, sorry for delay. If "agent" is a WP user -  such relationship are created by default, because agent will be set as created post author. Could you please describe more specific your use case, maybe I'll can advice how to implement it or it helps to better understand what functionality we need to add into JetEngine

**Comment by khadimseck1996** [comment]
Hello I am looking for a similar function.
Consider that we have two types of Type A & Type B postings. I have configured the following regalation one by one. The Type A post is the parent of the Type B post.
I want a method to automatically attract the publication of the type B post to the publication of the type A post with a submission form.

**Comment by tizum** [comment]
> Hi, sorry for delay. If "agent" is a WP user - such relationship are created by default, because agent will be set as created post author. Could you please describe more specific your use case, maybe I'll can advice how to implement it or it helps to better understand what functionality we need to add into JetEngine

I don't remember what it is, but the idea was after watching a video tutorial on the channel, at this time I learned a lot about the user relationship between post types, if I encounter any barriers in the future I will issue a new call, thanks !!!!
