### ISSUE TITLE
Map Listing not working if 2 post are at the exact same address

### ISSUE THREAD

**Issue by viggo1964** [CrocoBlock/suggestions#1808]
I use the Map Listing, and it works fine. But if there are 2 post at exactly the same address nothing happens when clicking on the grouping showing “2” in a circle. 

I expect that when clicking on the (2), that 2 separate individual markers showed up slightly apart from each other. Like when you zoom in on the map for to adresses close to each other. 

This makes it impossible to use the widget for e.g. showing several events held at a venue. 

Victoria Bormotova recomended to add this issue.

**Comment by arekuki** [comment]
+1

**Comment by justinpatrickkeller** [comment]
Is this done and in a release? I'm still having the same issue. All plugins are up to date.

**Comment by justinpatrickkeller** [comment]
Oy, I figured out where the setting is but still have issues... It only splits off 1 of many. I have a location with 3 listings and it splits off 1 but then I'm left with a 2 cluster that is still not clickable. 
<img width="912" alt="Screen Shot 2020-12-04 at 7 07 04 PM" src="https://user-images.githubusercontent.com/38727926/101230700-1876cb00-3664-11eb-9da2-ebf40c0ae42b.png">
<img width="870" alt="Screen Shot 2020-12-04 at 7 07 15 PM" src="https://user-images.githubusercontent.com/38727926/101230703-19a7f800-3664-11eb-9802-d19fa7d5e7ba.png">

**Comment by exelentshakil** [comment]
@justinpatrickkeller did you find any solution for it?

**Comment by justinpatrickkeller** [comment]
Yes, found the setting in the plugin settings.. (not in the widget), once I cleared cache it worked.

**Comment by exelentshakil** [comment]
@justinpatrickkeller Im not using any caching plugin, what i have to do in this case? Can you please suggest

**Comment by justinpatrickkeller** [comment]
Jet Engine > Jet Engine > Maps Settings > Avoid Markers Overlapping (toggle "on"). Once you do that maybe reload and then re-save your page in elementor. I have had weird issues with crocoblock plugins needing me to re-save the page/post before the changes take place.

**Comment by exelentshakil** [comment]
Yes i did the same thing bro but still having the same issue. Really getting this weird issue like wasting 10+ hours now. https://imgur.com/a/Y18WDVc

1. Do i have to create pages and posts again?
2. Just have to save each single posts.

**Comment by justinpatrickkeller** [comment]
1. Be sure plugin is totally up to date. 
2. If still not having success I would delete the Map Listing element from the page. (Copy it to a different page if you want to save all your settings)... The save the page without the element. 
3. Add the element back (new element, don't copy/paste from the other page).. 
4. Then copy and paste the style only. 

Sometimes I've had to go that route with Jet Engine Listings & Filters.

**Comment by exelentshakil** [comment]
Really appreciate your help mate. Following the process. Thank you so much for your help.
