### ISSUE TITLE
Custom meta fields conditions

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#1814]
Please try to implement conditional logic to meta fields like ACF. We must be able to show/hide meta fields according to multiple scenarios like user role and other restrictions. At the moment we have to create additonal duplicates (from scratch because we cannot even duplicate exisitng meta boxes) and adjust each one manually which is extremely time consuming. The worst part is that we have to use ACF to achieve that but since Crocoblock Smart Filters are not fully compatible with ACF we cannot filter ACF meta fields like checkboxes and others.

**Comment by kaskad88** [comment]
Added in JetEngine v2.10.0
