### ISSUE TITLE
Jet Booking - Seasonal Pricing

### ISSUE THREAD

**Issue by maxie71** [CrocoBlock/suggestions#1818]
Please add seasonal pricing to Jet Booking... A basic requirement of any booking system, for a Hotel or holiday home is the ability to charge more for a booking during peak season... there needs to be an ability to set the daily / nightly rate for a resource between certain dates....
example - 
 10th Jan - 31st March £50 Per Night (low season)
1st April - 31st May £80 Per Night (Mid Season)
1st June - 31st September £ 150 per Night (High Season)
1st Oct - 20th December £ 80 Per Night (mid Season)
21st December - 9th Jan £150 Per Night (high Season)

**Comment by vittoriamannu** [comment]
I agree. Without this feature, JetBooking can't be use in a professional website that rent houses or rooms.

**Comment by maxie71** [comment]
Hopefully this will be a point of escalation…. I have raised it on Git Hub

**Comment by vittoriamannu** [comment]
Thank you. I am now creating a real estate site based ALL on Croco plugins (Appointment, Booking, Engine ...) and I have now realized that this feature is missing. If this functionality will not be implemented, I'll be forced to remove everything and rethink the site :(

**Comment by loupaok** [comment]
I think is very very important to add seasonal pricing for this plugin.

**Comment by maxie71** [comment]
> I think is very very important to add seasonal pricing for this plugin.

I had to invest in an alternative solution because a lack of seasonal pricing made it unfit for purpose.... If you need a good booking solution that provides seasonal pricing plus a lot of other functionality check out pluginhive... This is what i had to use to replace jet booking - https://www.pluginhive.com/product/woocommerce-booking-and-appointments/

**Comment by Floydtm** [comment]
merge with #1472

**Comment by tavolucas** [comment]
merge with #2452

**Comment by 8persap** [comment]
Please can you add seasonal pricing as a priority? This plugin is so good and well thought out on every level but this. Seasonal pricing is key to any rental or hotel bookings. Without it, it rules out Jetbooking as a viable option. Please can you commit to addressing this? Thank you. 👍

**Comment by slobodandzebo** [comment]
![Screenshot 2021-06-02 at 23-14-22 Grand Crafter 680 – Frieda's](https://user-images.githubusercontent.com/85258290/120554768-71989f00-c3fa-11eb-839f-7c5566825c02.png)
Here is my solution for now - this was wrote in one day, maybe someone have better solution....

1. On Booking Form add additional field called "additional_services", type: Text, field type: Text, default: 0, Custom CSS: hide-field ( this CSS will be used to hide field on front-end )
2. On calculate field, edit calculation formula like this "(%META::preis%+%FIELD::additional_services%)*%FIELD::_dates%" - without quotes
3. Add script to site 
`<script>
jQuery('body').on('DOMSubtreeModified', '.start-day', function(){
      var preis = jQuery('.elementor-element-1c56dd6 .jet-headline__first .jet-headline__label').text();  // get orginal price from header
      var low = '0'; 
      var middle = '20';  //  add season value to original price
      var high = '50';
	  var dt = jQuery('.start-day').text();   // get date from date picker
	  var month = dt.slice(3,-5); // trim date - date format DD.MM.YY
      
if (month >= 01 && month <= 02 && month <= 03) {       // change price per month
    jQuery('#additional_services').val(low);  // write value to field created in booking form earlier
    jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00"); // add price to heading - price per day
    console.log('+0');
}
if (month >= 04 && month <= 05 ) {
    jQuery('#additional_services').val(middle);
     jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(middle, 10)) + ".00");
    console.log('+20');
} 
if (month >= 06 && month <= 07 && month <= 08 ) {
    jQuery('#additional_services').val(high);
    jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(high, 10)) + ".00");
    console.log('+50');
}
if (month >= 09 && month <= 10 && month <= 11 && month <= 12) {
    jQuery('#additional_services').val(low);
    jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00");
    console.log('+0');
}
});
</script>`


Check for details on website 
https://strenua.de/vermietung/grand-crafter-680/

**Comment by damenvaz31** [comment]
> ![Screenshot 2021-06-02 at 23-14-22 Grand Crafter 680 – Frieda's](https://user-images.githubusercontent.com/85258290/120554768-71989f00-c3fa-11eb-839f-7c5566825c02.png)
> Here is my solution for now - this was wrote in one day, maybe someone have better solution....
> 
> 1. On Booking Form add additional field called "additional_services", type: Text, field type: Text, default: 0, Custom CSS: hide-field ( this CSS will be used to hide field on front-end )
> 2. On calculate field, edit calculation formula like this "(%META::preis%+%FIELD::additional_services%)*%FIELD::_dates%" - without quotes
> 3. Add script to site
>    `<script>
>    jQuery('body').on('DOMSubtreeModified', '.start-day', function(){
>    var preis = jQuery('.elementor-element-1c56dd6 .jet-headline__first .jet-headline__label').text();  // get orginal price from header
>    var low = '0';
>    var middle = '20';  //  add season value to original price
>    var high = '50';
>    var dt = jQuery('.start-day').text();   // get date from date picker
>    var month = dt.slice(3,-5); // trim date - date format DD.MM.YY
> 
> if (month >= 01 && month <= 02 && month <= 03) { // change price per month
> jQuery('#additional_services').val(low); // write value to field created in booking form earlier
> jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00"); // add price to heading - price per day
> console.log('+0');
> }
> if (month >= 04 && month <= 05 ) {
> jQuery('#additional_services').val(middle);
> jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(middle, 10)) + ".00");
> console.log('+20');
> }
> if (month >= 06 && month <= 07 && month <= 08 ) {
> jQuery('#additional_services').val(high);
> jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(high, 10)) + ".00");
> console.log('+50');
> }
> if (month >= 09 && month <= 10 && month <= 11 && month <= 12) {
> jQuery('#additional_services').val(low);
> jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00");
> console.log('+0');
> }
> });
> </script>`
> 
> Check for details on website
> https://strenua.de/vermietung/grand-crafter-680/

I'm trying to replicate your example but i can't make it work it out, i don't now why some times it worked and some times it doesn't write the additional service variable. Where did you put your script?

**Comment by slobodandzebo** [comment]
Put script in html element under Booking Form.

**Comment by damenvaz31** [comment]
No luck either. I'll be continue trying!!!!

**Comment by damenvaz31** [comment]
It works! Thanks a lot! Just to the community knowledge check first your elementor ID for the price, in my case it was different from @slobodandzebo ID.
Just inspect your element to get the ID: 
<img width="238" alt="Captura de Pantalla 2021-06-30 a la(s) 17 09 59" src="https://user-images.githubusercontent.com/4359850/124038016-17253b00-d9c6-11eb-8ccc-37144376715f.png">
So, after this my variable change to this:
var preis = jQuery('.elementor-element-7cfb1d9 .jet-headline__first .jet-headline__label').text();

Cheers!

**Comment by tavolucas** [comment]
I tried all the time and it didn't work for me, I can't find the id anywhere @damenvaz31. It's frustrating I've been waiting for months for @Crocoblock  to fix this and nothing...

**Comment by damenvaz31** [comment]
Hi @tavolucas , maybe this picture can help you to get the id.

<img width="1391" alt="Captura de Pantalla 2021-09-06 a la(s) 9 26 24" src="https://user-images.githubusercontent.com/4359850/132231856-00b0d7af-ab97-40a6-addf-6f5da32d4e5c.png">

On your reservation page, select your price, then right click over it and go to Inspect Element. Once the inspector open you could find your class ID.

**Comment by tavolucas** [comment]
@damenvaz31 Thank you very much I did everything correctly but it did not work for me, I had already lost many hours for this that I do not understand why Crocoblock does not solve it at once ... in order to finish by removing it jetBooking and installing WooCommerce Booking.

**Comment by Giulioski80** [comment]
I have tried too, changed ID but it isn't working. How sad a plugin made for bookings missing such an important feature.

**Comment by slobodandzebo** [comment]
> @damenvaz31 Thank you very much I did everything correctly but it did not work for me, I had already lost many hours for this that I do not understand why Crocoblock does not solve it at once ... in order to finish by removing it jetBooking and installing WooCommerce Booking.

Can you wrote your steps what you did, so I can help you. Also give me a link to website you are trying to do. Best regards

**Comment by slobodandzebo** [comment]
> I have tried too, changed ID but it isn't working. How sad a plugin made for bookings missing such an important feature.

Can you wrote your steps what you did, so I can help you. Also give me a link to website you are trying to do. Best regards

**Comment by nathannsc** [comment]
Hello,

Has someone been able to implement this? I've tried to follow @damenvaz31 suggestions but for me is not working.

**Comment by nathannsc** [comment]
> > I have tried too, changed ID but it isn't working. How sad a plugin made for bookings missing such an important feature.
> 
> Can you wrote your steps what you did, so I can help you. Also give me a link to website you are trying to do. Best regards

Could you please lend me a hand? I've been trying with this website: https://fazendafavorita.com.br/rooms/cabana-merlot/
Thank you!!

**Comment by damenvaz31** [comment]
> > > I have tried too, changed ID but it isn't working. How sad a plugin made for bookings missing such an important feature.
> > 
> > 
> > Can you wrote your steps what you did, so I can help you. Also give me a link to website you are trying to do. Best regards
> 
> Could you please lend me a hand? I've been trying with this website: https://fazendafavorita.com.br/rooms/cabana-merlot/ Thank you!!

Hi @nathannsc , I think you preis (price) variable should look like these:

var preis = jQuery('.elementor-element-dc96305 .jet-headline__first .jet-headline__label').text(); // get orginal price from header.

dc96305 is the data-id of your Cabana Merlot

The rest of the solution is the one giben by @slobodandzebo

Cheers.

**Comment by nathannsc** [comment]
@damenvaz31 Thank you very much for your quick reply, unfortunately, it still did not work. I will paste my script and formula - but I think I'm missing something here. I'm assuming I have to change "preis" to "price" in the script, so I did that. Perhaps changing for _apartment_price would work (?)

**Formula:**
(%FIELD::_dates%*(%META::_apartment_price%+%FIELD::additional_services%))+(((%FIELD::taxa%*%FIELD::guests%)+(150))*0)

**Script:**
<script>
jQuery('body').on('DOMSubtreeModified', '.start-day', function(){
var price = jQuery('.elementor-element-dc96305 .jet-headline__first .jet-headline__label').text(); // get orginal price from header
var low = '0';
var middle = '20'; // add season value to original price
var high = '50';
var dt = jQuery('.start-day').text(); // get date from date picker
var month = dt.slice(3,-5); // trim date - date format DD.MM.YY
if (month >= 01 && month <= 02 && month <= 03) { // change price per month
jQuery('#additional_services').val(low); // write value to field created in booking form earlier
jQuery('.price-field').html("R$"+ (parseFloat(price, 10) + parseFloat(low, 10)) + ".00"); // add price to heading - price per day
console.log('+0');
}
if (month >= 04 && month <= 05 ) {
jQuery('#additional_services').val(middle);
jQuery('.price-field').html("R$"+ (parseFloat(price, 10) + parseFloat(middle, 10)) + ".00");
console.log('+20');
}
if (month >= 06 && month <= 07 && month <= 08 ) {
jQuery('#additional_services').val(high);
jQuery('.price-field').html("R$"+ (parseFloat(price, 10) + parseFloat(high, 10)) + ".00");
console.log('+50');
}
if (month >= 09 && month <= 10 && month <= 11 && month <= 12) {
jQuery('#additional_services').val(low);
jQuery('.price-field').html("R$"+ (parseFloat(price, 10) + parseFloat(low, 10)) + ".00");
console.log('+0');
}
});
</script>

**Comment by damenvaz31** [comment]
Hi! The only think that i'm looking different is that my var format is different:

var month = dt.slice(3,5); 

So this my Formula:
```
(%META::_apartment_price%+%FIELD::additional_services%)*(%FIELD::_dates%)
```

This is my script:

```script
<script>
jQuery('body').on('DOMSubtreeModified', '.start-day', function(){
var preis = jQuery('.elementor-element-7cfb1d9 .jet-headline__first .jet-headline__label').text(); // get orginal price from header

var low = '0';
var middle = '20'; // add season value to original price
var high = '1000';
var dt = jQuery('.start-day').text(); // get date from date picker
var month = dt.slice(3,5); // trim date - date format DD.MM.YY
	
	
if (month >= 01 && month <= 02 && month <= 03 && month <= 04) { // change price per month
jQuery('#additional_services').val(high); // write value to field created in booking form earlier
jQuery('.price-field').html("$"+ (parseFloat(preis, 10) + parseFloat(high, 10)) + ".00"); // add price to heading - price per day
console.log('+50');
}
if (month >= 05 && month <= 06 ) {
jQuery('#additional_services').val(low);
jQuery('.price-field').html("$"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00");
console.log('+0');
}
if (month >= 07 && month <= 08 && month <= 09 ) {
jQuery('#additional_services').val(high);
jQuery('.price-field').html("$"+ (parseFloat(preis, 10) + parseFloat(high, 10)) + ".00");
console.log('+50');
}
if (month >= 10 && month <= 11) {
jQuery('#additional_services').val(low);
jQuery('.price-field').html("$"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00");
console.log('+0');
}
	
if (month == 12 ) {
jQuery('#additional_services').val(high);
jQuery('.price-field').html("$"+ (parseFloat(preis, 10) + parseFloat(high, 10)) + ".00");
console.log('+50');
}	
});
</script>
```
Hope that works. Cheers!

**Comment by jannelundin** [comment]
This looks like it is working, but if you select a date that returns the high value
and then go back to selecting a low value date the additional services field does not reset
so you will still get the high price for a low season. Do you know a solution for that?

**Comment by jannelundin** [comment]
> This looks like it is working, but if you select a date that returns the high value and then go back to selecting a low value date the additional services field does not reset so you will still get the high price for a low season. Do you know a solution for that?

**Comment by ghost** [comment]
This will not work precisely as it only consider start date, please crocoblock team implement seasonal prices

**Comment by ghost** [comment]
I implemented a custom solution with seasonal coefficients and custom periods, with the check done day per day and not just on start date. If someone interested he can contact me

**Comment by Queen-Eef** [comment]
@creativeprogramming Did you also find a solution for the issue jannelundin wrote;
> > This looks like it is working, but if you select a date that returns the high value and then go back to selecting a low value date the additional services field does not reset so you will still get the high price for a low season. Do you know a solution for that?

This also seems unacceptable to me.

**Comment by slobodandzebo** [comment]
Please look at https://friedasreisen.de/vermietung/chausson-627ga-frieda/ and tell me what exactly not working as it should.. Thx

![Screenshot 2022-01-14 at 11-17-10 Edit Form ‹ Friedas — WordPress](https://user-images.githubusercontent.com/85258290/149499960-e05d57f8-7429-46e1-a435-0cc9f75912ea.png)
![Screenshot 2022-01-14 at 11-18-43 Edit Form ‹ Friedas — WordPress](https://user-images.githubusercontent.com/85258290/149499963-8f4e38e8-4e31-48ce-b12a-ec5a8ec11236.png)

===Code===
`<script>
jQuery('body').on('DOMSubtreeModified', '.start-day', function(){
      var preis = jQuery('.elementor-element-1c56dd6 .jet-headline__first .jet-headline__label').text();
      var low = '0';
      var middle = '30';
      var high = '60';
	  var dt = jQuery('.start-day').text();
	  var month = dt.slice(3,-5);
      
if (month >= 01 && month <= 02 && month <= 03) {
    jQuery('#additional_services').val(low);
    jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00");
}
if (month >= 04 && month <= 05 && month <= 06 ) {
    jQuery('#additional_services').val(middle);
     jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(middle, 10)) + ".00");
} 
if (month >= 07 && month <= 08 ) {
    jQuery('#additional_services').val(high);
    jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(high, 10)) + ".00");
}
if (month >= 09 && month <= 10 ) {
    jQuery('#additional_services').val(middle);
     jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(middle, 10)) + ".00");
} 
if (month >= 11 && month <= 12) {
    jQuery('#additional_services').val(low);
    jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(low, 10)) + ".00");
}
});
</script>

<script>
jQuery('body').on('DOMSubtreeModified', '.selected-days-num', function(){
      var sd = parseInt(jQuery('.selected-days-num').text());
      var min = '6';
      jQuery('.minimal-days').hide();
    
if (sd >= min) { 
    jQuery('.elementor-303 .elementor-element.elementor-element-c50df44 .jet-form__submit').prop('disabled', false);
} else {
    jQuery('.elementor-303 .elementor-element.elementor-element-c50df44 .jet-form__submit').prop('disabled', true);
    jQuery('.minimal-days').show();
}

});
</script>
`

**Comment by Queen-Eef** [comment]
Hi slobodandzebo,
To be honest I didn't try you code yet because of the comment of @jannelundin.
But now I checked your website and it seems that comment isn't true anymore.

So I am gonna try your solution, but I have some questions because I don't know exactly what it al means.
- You have ParseFloat in your code. What does that mean/refer to? 
- And what is the 10 in (preis, 10) and (low, 10) for example?

Thanks for your help, hopefully I can manage to make it work ;-)
Kind regards,
Eefke

**Comment by slobodandzebo** [comment]
jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(middle, 10)) + ".00");
- this is a matter of formatting, to remove currency symbols
- you cannot calculate with a symbol (example: € 89 + 0)
- this code was written in a hurry and could be further improved

**Comment by Queen-Eef** [comment]
Okay, I'll let you know if it's works!

**Comment by Queen-Eef** [comment]
@slobodandzebo 
Should this also work if I'm using the advanced price rates?

**Comment by Queen-Eef** [comment]
@slobodandzebo
Okay I tried everything I could think off, but no result.
If you feel like helping...

FYI:
- I'm working with the advanced price rates.
- Build my form in JetFormBuilder -> replaced your additional_services field with a text field called season_price.
- Added a HTML field in the form with the code.
- Calculation formula; (%ADVANCED_PRICE::check_in_out_dates%*%FIELD::season_price%)+(%FIELD::additional_options%*%FIELD::check_in_out_dates%)

Changes in the script;
- Replaced preis with price
- the ID, but I'm not sure if I should use .elementor-1513 .elementor-element.elementor-element-1c56dd6 .jet-headline__first .jet-headline__label or .elementor-element-1c56dd6 .jet-headline__first .jet-headline__label.
- the var low, middle, high replaced with regular, high. I'm calculating with 25%. So high is now set as 1.25 and should be calculated *1.25.
- replaced all references to additional_services and low, middle, high with my 'names'.
- set my high and regular months and their values
- Deleted the jQuery('.price-field').html("€"+ (parseFloat(preis, 10) + parseFloat(middle, 10)) + ".00"); lines out of the code, because my settings are different. 
So now I have:
<script>
jQuery('body').on('DOMSubtreeModified', '.start-day', function(){
var price = jQuery('.elementor-element-1c56dd6 .jet-headline__first .jet-headline__label').text();
var regular = '1';
var high = '1.25';
var dt = jQuery('.start-day').text();
var month = dt.slice(3,-5);

if (month >= 12 && month <= 01 && month <= 02 && month <= 03 && month <= 04) {
jQuery('#season_price').val(high);
}
if (month >= 05 && month <= 06 && month <= 07 && month <= 08 && month <= 09 && month <= 10 && month <= 11) {
jQuery('#season_price').val(regular);
}
});
</script>

When I change my calculation formula to %ADVANCED_PRICE::check_in_out_dates%+(%FIELD::additional_options%*%FIELD::check_in_out_dates%) (so without the *%FIELD::season_price%) the formula works. But when I add that part again, it gives 0.00

Below you can check the screenshots.
Hope you feel like checking this for me, and hopefully you can find my mistake...
Thanks for your help in advance!
Kind regards,
Eefke

Screenshots:
<img width="1159" alt="Schermafbeelding 2022-01-18 om 17 27 50" src="https://user-images.githubusercontent.com/95771168/150021718-874abc09-ba89-4e87-8c42-c7001188f1db.png">
<img width="1010" alt="Schermafbeelding 2022-01-18 om 17 28 22" src="https://user-images.githubusercontent.com/95771168/150021726-f04684af-a2fa-4160-b35e-df1022b613d8.png">
<img width="1109" alt="Schermafbeelding 2022-01-18 om 17 28 48" src="https://user-images.githubusercontent.com/95771168/150021727-4f393339-9189-4333-a250-656015aff97c.png">
<img width="890" alt="Schermafbeelding 2022-01-18 om 17 29 09" src="https://user-images.githubusercontent.com/95771168/150021730-d674c879-cdc7-4c4b-a7ad-ea5e8dad1e5e.png">

**Comment by MjHead** [comment]
Added with JetBooking 2.4

**Comment by Queen-Eef** [comment]
@MjHead Thats great! And do you know when 2.4 will be released?

**Comment by jannelundin** [comment]
It is still the issue With checkin and checkout days,
If one customer book 7/8-14/8 the next customer can`t book
1/8-7/8 if you use some other booking plugin (motorpress) the checkin And checkout days are half occupied.

**Comment by IslamSultan** [comment]
Hi Everyone! I have created a booking form (Total price and dates and book button) and i have put it on listing of rooms(Jetengine listing.).

So i did it to filter the rooms and same time show total price for picked dates. (When i was using %meta::_apartment_price%*%field::dates%) it was ok on each listing card was showing total price. When i started use seasonal price, %Advanced_Price::dates% it is not calculating total price, but all rooms price are same but if enter to the room and book then it is working

Best regards, Islam

**Comment by chunibyuu** [comment]
Maybe you can help me out creating the script for additional price for 3 days booking . Currently the " add rates " is price per nights/days but what I want to implement is an additional ( for example $500 ) for 3 days booking . 1-2 days will be the original base price . I just need to add $500 for the 3 days booking . 

Thanks for any help .
