### ISSUE TITLE
JetReview is not working for dynamic custom posts.

### ISSUE THREAD

**Issue by niteshmanav** [Crocoblock/suggestions#182]
I am not able to make the JetReviews work for my custom single post type that I have created using elementor + jetreviews. 

The idea is to create a custom single post template for a review post... I want to include Jetreviews appear automically on the post when I enter the data on my post editor. 

But while creating the custom post type template for the review page, when I select 'content source' as 'meta' it doesn't fetch those data automatically which I have already posted in the backend. Here is what happens.

So, the only left for me is to manually put all the data for each review post.  Isn't there a way to be able to set make the review rating entry dynamic so that I can make it work with ACF pro or Pods?

Also, what is 'post meta' as a content source ? how it supposed to work? It seems like that it gives my website visitor an option to add reviews to my post.. right?

Also, I want to put an option at the bottom of my review post to add 'user's reviews' using jetreviews. How can I add that to the end of my post and how can I design it?

Overall, I believe JetReviews needs some work for it to be actually useful for creating a custom designed dynamic review website or may be I am missing something important about how to use effectively. 

Based on what I have asked the support here - https://kava.ticksy.com/ticket/1972712/

**Comment by shinTM** [comment]
done v2.0.0
