### ISSUE TITLE
JetEngine forms custom icons

### ISSUE THREAD

**Issue by stijnvanouplines** [CrocoBlock/suggestions#1821]
Is there an option to add a custom icon to checkboxes and radio buttons to build a form like this:

![Screenshot 2020-09-05 at 11 52 48](https://user-images.githubusercontent.com/16742744/92302689-5d5c6a00-ef6e-11ea-8562-b404e00db207.png)

**Comment by Floydtm** [comment]
@stijnvanouplines, Hi! You can use custom service template in jetengine forms https://prnt.sc/ucsw6q https://prnt.sc/ucswiy

**Comment by stijnvanouplines** [comment]
Hi, thank you! This is what I was looking for!

Is it also possible to use a meta field from the 'Services' custom post type as a value for a calculated field?

**Comment by Floydtm** [comment]
I understand that this is very for you, but now there is no possibility to use meta fields from services to calculate formulas. However, we are already thinking how to implement this in the future.

**Comment by stijnvanouplines** [comment]
Great, thank you!
