### ISSUE TITLE
Sidebar and filter mobile solutions

### ISSUE THREAD

**Issue by carlovanderpluijm** [CrocoBlock/suggestions#1822]
Hi team,

The plugin has great features already including filters (jetsmartfilters) and the sidebar in the theme blog layouts.

To take this to the next level, what I'm still missing is the option to, when going to a smaller screen, i do not want the filters and for example the calendar or archive sidebar in the blog) to be at the top or bottom of the content.

Instead i would like to have the opportunity to make this a button or icon like the mobile menu which on selection opens the filter menu or the sidebar in a modal screen.

That would make a huge difference in the usability

Cheers C

**Comment by Floydtm** [comment]
You can do this right now with Jet plugins. Alternatively, this can be done using a pop-up or hamburger panel. If you have any problems with this, please contact our support team, they will be happy to help you

**Comment by carlovanderpluijm** [comment]
Thanks for the fast reply.

I will see if I can find out how, otherwise I will contact support.

However, it would just be heart if it would be a setting
