### ISSUE TITLE
JetEngine: Global Fonts and colors not showing in Listing (Elementor v.3)

### ISSUE THREAD

**Issue by arekuki** [CrocoBlock/suggestions#1823]
I create a new one at JetEngine> Listing. But Global Fonts and colors don't render to any widgets. http://prntscr.com/ucvyv2

Can you fix it?

**Comment by tooweb** [comment]
I agree - there is such a problem

**Comment by kaskad88** [comment]
Fix for the next version.
Thanks for your report!

**Comment by arekuki** [comment]
I checked. thanks
