### ISSUE TITLE
Jet Engine | Boost up the form functionalities

### ISSUE THREAD

**Issue by Gugutete** [CrocoBlock/suggestions#1824]
hi there. thanks for your attention.
I have a form in a single CPT Service where my customer can fill the form that have already the calculated formula to get the meta price of the current post more the additional services. In this form is added a checkbox with Source= CPT Services + Jet Listing Template ).

Everything works,

it take in the total amount the meta=price of the Current Post and it should add the meta=price of the other services the customer select from the checkbox listing.

Now the problem is that after it take the current meta price of the current post when a customer select the service and the check marker is selected in my CPT Listing it add to the amount the ID Number of the single post instead it should take the meta price of the single post.

From the example of a jet preset theme I saw they insert manual input and gives a value. I activated the Source Post "services" with Custom Jet Listing they should be added automatically not manual as in the jet example.

How can I create in the calculated area the macro I need to get from the total amount correctly? %FIELD::_price%+%FIELD::additional_services%?

where %FIELD::additional_services% is a FIELD checkbox that get the options from CPT Services and is set with a jet Listing where I set up the Chech Marker. Actually it get the ID Number of each selected options instead to add the meta price of each service selected to the amount.

This could become a professional and dynamic configurator or calculator.

I can give you all credentials you need to operate directly on my website.

many thanks to everyone have a little moment to help me.

![118826281_10224664230341225_3335083410363387457_n](https://user-images.githubusercontent.com/54572067/92371386-d2a97580-f0fb-11ea-8dad-6f0f13bcdc1a.jpg)
![118852762_10224664276382376_1633961967862822728_n](https://user-images.githubusercontent.com/54572067/92371388-d3daa280-f0fb-11ea-9657-f0e06e14f020.jpg)
![118915435_10224664233461303_975698033021012256_o](https://user-images.githubusercontent.com/54572067/92371389-d4733900-f0fb-11ea-9971-7cda814e66b2.jpg)
![118951343_10224664230421227_7373325308570616437_n](https://user-images.githubusercontent.com/54572067/92371391-d50bcf80-f0fb-11ea-9370-2b0bd3bbb08a.jpg)
![118961048_10224664272182271_4465387291666791010_n](https://user-images.githubusercontent.com/54572067/92371395-d5a46600-f0fb-11ea-8091-bf0afe74d945.jpg)

**Comment by Floydtm** [comment]
I understand that this is very for you, but now there is no possibility to use meta fields from services to calculate formulas. However, we are already thinking how to implement this in the future.
