### ISSUE TITLE
Decimal separator and thousands separator to inherit WC settings

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#1825]
Please add ability to inherit or configure decimal and thousand separators

**Comment by MjHead** [comment]
Could you please specify your request - where exactly you need to inherit these settings?

**Comment by ghost** [comment]
Where you see 35.00€ it should be 35,00€ as my woocommerce is setup to have , as decimal separator and . as thousands separator
![image](https://user-images.githubusercontent.com/954291/92939851-9739de80-f44e-11ea-8f13-d2d0f82b75fa.png)

**Comment by UraraReika** [comment]
This options already exist in JetFormBuilder plugin - https://tppr.me/5Ah3q for calculated field. Unfortunately if you use JetEngine forms you wouldn't find it  because it legacy functionality. We recommend to use JetFormBuilder.

Thank you for understanding !

**Comment by fatimataghavi** [comment]
hi,
would you please explain how can we use decimal separator in a number field in which when a user is adding numbers, the separator displays, for helping them add the number correct,

**Comment by fatimataghavi** [comment]
Hi,
Could you please explain how we can use a decimal separator in a number field? This would allow users to see the separator when they enter a number, helping them to add prices correctly.

**Comment by yorkshiredesigner** [comment]
> This options already exist in JetFormBuilder plugin - https://tppr.me/5Ah3q for calculated field. Unfortunately if you use JetEngine forms you wouldn't find it because it legacy functionality. We recommend to use JetFormBuilder.
> 
> Thank you for understanding !

Yes but that is only for the calculated field, you can't input anything into that field. Would be super useful to have this option in the regular input field.
