### ISSUE TITLE
JetBooking:  minimum days to book

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#1833]
Additional options for booking:

 is that possible to set the booking system to not book for the current day ( to start available booking days from the day after today )? and also to make it for booking minimum days to be starting for 2 days and more?

**Comment by zsolthorcsik** [comment]
Hi! I would also highly appreciate this feature! A Client of mine wants to allow bookings from at least 3 (consecutive) days.

**Comment by KHRifat** [comment]
+1

For my project, I need minimum 2 days booking (no one can book less than 2 days).

@Crocoblock please update the JetBooking for adopting the Booking Policy.

**Comment by Hammer-ger** [comment]
@KHRifat 

it is possible via logical conditions. you can hide the submit button, if a booking is smaler then 2 days.

**Comment by breakused** [comment]
> @KHRifat
> 
> it is possible via logical conditions. you can hide the submit button, if a booking is smaler then 2 days.

Good idea. What value do you take for days? Thank you!

![1](https://user-images.githubusercontent.com/37920259/124201267-dfa6b380-dad7-11eb-86f4-95d48ba40a2c.png)

**Comment by TheBigBanik** [comment]
> > @KHRifat
> > it is possible via logical conditions. you can hide the submit button, if a booking is smaler then 2 days.
> 
> Good idea. What value do you take for days? Thank you!
> 
> ![1](https://user-images.githubusercontent.com/37920259/124201267-dfa6b380-dad7-11eb-86f4-95d48ba40a2c.png)

But how the form will understand that the guest has selected any number of days? The checkin selection is made by the Jet smart filters, not from a custom field.

**Comment by KHRifat** [comment]
> @KHRifat
> 
> it is possible via logical conditions. you can hide the submit button, if a booking is smaler then 2 days.

How.?

**Comment by KHRifat** [comment]
> it is possible via logical conditions. you can hide the submit button, if a booking is smaler then 2 days.

Hello @Hammer-ger, please see the above Comments of @breakused & @TheBigBanik

**Comment by TheBigBanik** [comment]
I was chatting with the elementor team. If we use the Jet Booking as a real hotel availability plugin, then we have to use the Jet Smart Filters to search for the availability of the accommodations. 

Case No1
STEP 1: Select dates through Jet smart filters
STEP 2: Redirect to the results page
STEP 3: Select room and proceed to checkout.
There is no way to select 3 days minimum by using the above steps.


Case No2 (if it is a solution)
STEP 1: We create a Jet form with checkin and checkout fields
STEP 2: We create a condition to hide the BOOK NOW (submit) button if days are less than 3 for example
STEP 3: How this form will redirect to checkout and how we can retrieve the total price in the checkout? It looks very complicated.

I am not sure that we can use Jet forms for bookings since the only thing we can achieve is send a form for availability request, Crocoblock has no solution on that, I mean connect Jet Bookings and Jet forms, unless there is a workaround that everone has missed.

**Comment by breakused** [comment]
I found a solution. It's not elegant, but it still works.
For min 3 days.

Plugin Editor > JetBooking >

**jet-booking/assets/js/booking-init.js**
Line 121:
`minDays: window.JetABAFData.per_nights ? 3 : 0`

**jet-booking/assets/lib/jquery-date-range-picker/js/daterangepicker.js**
Line 930:
`minDays: 3`

### ...and please do not forget: the plugin should **not** be updated.

I hope it helps ✌🏼

**Comment by tfrank7** [comment]
> 
If it's working, this number could be a variable and job done, Croco.

**Comment by stephanewillems** [comment]
It worked when I added a hidden calculated field where I take in the amount of days from %FIELD::_dates%.
The Submit button only appears when that value is greater than 6 (for 7days).
Then I added a field with text that appears when the number is less then 7 that gives the user a message when chosen less then 7.

![image](https://user-images.githubusercontent.com/47913741/147584490-1da08bde-6364-429b-9f84-53fafef02fc1.png)
![image](https://user-images.githubusercontent.com/47913741/147584525-c5c1fcaf-94d0-4c94-aa4c-a466e0981dee.png)

**Comment by alexanderpankart** [comment]
Of course, an explicit button with "Select the minimum number of days / nights" would still be beneficial, but that solves the problem - so it would just be a nice to have.

![image](https://user-images.githubusercontent.com/69971188/148289688-169659de-f3c8-4cd4-9a57-1e9149cddb07.png)

(Hide the booking button, if only 1 night is selected)
![image](https://user-images.githubusercontent.com/69971188/148289742-a97ed8a3-668b-4377-bdf2-e325b025d195.png)

Frontend - the Submit Button is hidden.

Thank's a lot for that solution <3

**Comment by Miguel2162** [comment]
Has anyone found or has a solution to limit which days reservations are made, for example, I need my calendar to disable the current day and the next two days, preventing customers from booking with less than 72 hours. Help

**Comment by tfrank7** [comment]
> Has anyone found or has a solution...

Hi,
I created a frontend form for the owner, on a hidden page, where she can book those days manually.
Few days later I just switched to Woo Bookings, because JetBooking is a pain at this stage. Sorry to saying this.
Hope they will listen for the customers needs... because I like this Croco enviroment.

**Comment by Miguel2162** [comment]
> Opciones adicionales para reservar:
> 
> ¿Es posible configurar el sistema de reservas para que no reserve para el día actual (para iniciar los días de reserva disponibles a partir del día siguiente)? ¿Y también para que la reserva de días mínimos comience por 2 días y más?

Enter these lines in the file jetbooking-init.js. With that you limit that users cannot choose the current day, nor the number of days that you specify in line 2 at the end, there you can move the reservation as the start day to future days

var date = new Date();
        date.setDate(date.getDate() + 2);
		
		config.minDate = date;
		config.startDate = date;

**Comment by darione88** [comment]
I have to set minimum 2 days but i saw is not possible :( this could be a very good and important feature for next version!

**Comment by boris-de-jong** [comment]
I really require a minimum days/nights feature as well. It would be perfect if periods that cannot fulfil the minimum days requirement because of other bookings, would automatically be blocked as well.

**Comment by JacsSalvador** [comment]
When I make a booking with JetBooking, the check-out is shown in the calendar as available and not busy. How can I solve this?

**Comment by UraraReika** [comment]
Release 2.6.0

**Comment by chunibyuu** [comment]
I can't even find that conditional logic to start with .
