### ISSUE TITLE
Required Fields for all field types

### ISSUE THREAD

**Issue by Kezaro** [CrocoBlock/suggestions#1834]
Good day. I was looking through the documentation for information about setting meta fields 'required'. I couldn't find any information about this.

The issue im having is that i noticed some meta fields types have a 'required' option, but not all. I have a client who would like to ensure their staff enters all the necessary information when entering data into the custom post types through the wordpress admin area. 

I previously submitted a ticket about this and was then advised that what i noticed is correct and that I should add my issue here so it can be added to the feature requests. I think Jetengine is a great plugin, but I also think its imperative to give us the option to determine which fields can or should be required.

**Official Request: For all fields types to include a 'required' option.** 

This way we can fully control how users enter data and avoid excuses they give like: 'I didn't notice that field', 'It wasn't required', 'There was no error notification' etc..

Thanks for you time and attention.

**Comment by Floydtm** [comment]
@Kezaro, I understand that this is important to you. However, there are some fields that do not require this option. We'll check this one again, maybe we're missing something. Thank!

**Comment by neosaveme-zz** [comment]
I have an even simpler request,
- Create [taxonomies ](https://www.advancedcustomfields.com/resources/taxonomy/)fields as already done by acf
- Make all the fields required 
- Add option to tell gallery put the first image as featured image 
( as I already do with this code ) 

```
add_filter('acf/save_post', 'gallery_to_thumbnail');
function gallery_to_thumbnail($post_id) {
	$gallery = get_field('property_photos', $post_id, false);
	if (!empty($gallery)) {
		$image_id = $gallery[0];
		set_post_thumbnail($post_id, $image_id);
	}
}
```
so the user/client has only one single job to do ! https://ibb.co/98fStt6
focus on a **single zone** fill the fields and press publish button 
https://makeagif.com/i/lkE3qX

**Comment by Kezaro** [comment]
> @Kezaro, I understand that this is important to you. However, there are some fields that do not require this option. We'll check this one again, maybe we're missing something. Thank!

@Floydtm Hope all is well. You are correct in some aspect, not all fields need to be required. However at the moment the plugin is missing some important logics in terms of required field validations, which I can explain for the specific fields I am using at the moment.

The specific fields I am using that should have a required setting are: 'Number', 'Checkbox' and 'Gallery',
_Note the following are based on the Property Management site i'm building, but these examples can apply to many other use cases._

1) Number Field: Used as a price field on Properties for Sale. (We hold the saying close to heart, that garbage in is garbage out) The client will like their staff to enter properties for sale into the website. Having the 'Number' field set as required, will ensure there is never a property entered into the site without a Sale Price. (Which currently happens from time to time).

2) Checkbox: At first glance you may think checkboxes do not need to be validated. However in a scenario like a multiple choice question i.e. Select the options that most accurately describes the correct answer (option a, option b, option c, option d) even if a default option is set for the 'checkbox' field a user can unselect all items and no validation will be done to ensure at lease one option is selected. (If only 1 option is needed, a Radio Button will be best suited, but if multiple options should be able to be selected, Checkboxes are used) So the idea is to basically have a validation setting to allow us to help users fill out all needed fields. I don't see the harm in giving us this feature as at the Custom Field level it should be up to us to determine what should be required or not based on the business logic of a client.

3) Gallery: Used for adding an image gallery of a Property added to the site. One of the business rules of the client we are doing this project for is, they dont want any properties listed on the website if there isnt a gallery for prospective buyers to view and make a choice. Can it be possible for Gallery to be required, so when a staff member is entering the properties, it would be impossible to save without adding at least one image. This will ensure that the person entering the properties cannot skip this step.

What i'v realize is that managers and business owners come up with business logics/ process flows that their employees need to follow. However, if left up to these employees to make sure and do things the way management wants it done, sometimes errors are made... Part of what we like to provide is a way to implement the business logics the management teams wants, and design/develop it in a way for employees to use it with little to no mistakes. Required fields/Field validations help tremendously with this. 

Thanks again for you time. And also thanks for adding this request to the JetEngine 2,5,1 milestone.

**Comment by Kezaro** [comment]
Good day,

I was following up on the issues I submitted previously. Is there any reason why this issue was removed? Please indicate because I purchased this plugin and now it feels like there seems to be little to no feedback on issues, no followups from your end, and as a paying customer i am totally out of the loop on these issues that my clients keep complaining about. Can you indicate why Number, Checkboxes, and Gallery cannot have a required field? if there is an alternative way to achieve the use case i presented on sep 28, can you please share it.

**Comment by raabmar** [comment]
> I have an even simpler request,
> 
> * Create [taxonomies ](https://www.advancedcustomfields.com/resources/taxonomy/)fields as already done by acf
> * Make all the fields required
> * Add option to tell gallery put the first image as featured image
>   ( as I already do with this code )
> 
> ```
> add_filter('acf/save_post', 'gallery_to_thumbnail');
> function gallery_to_thumbnail($post_id) {
> 	$gallery = get_field('property_photos', $post_id, false);
> 	if (!empty($gallery)) {
> 		$image_id = $gallery[0];
> 		set_post_thumbnail($post_id, $image_id);
> 	}
> }
> ```
> 
> so the user/client has only one single job to do ! https://ibb.co/98fStt6 focus on a **single zone** fill the fields and press publish button https://makeagif.com/i/lkE3qX

All of that! So necessary. I also did not know before I moved over to JetEngine that I am not able to set up every meta field as required. I did not know that I cannot add a taxonomy, and I think it is very essential from an Editor-usability point of view → one mask to fill out for everything.

ACF has a hidden feature where I can rename a field (image) to `_thumbnail_id` so that it automatically syncs with the featured image.

**Comment by secondsky** [comment]
Just imagine a site where you want to prevent that someone publishes something which does not have all the necessary fields filled out..... **Making fields required is a MUST!**

**Comment by raabmar** [comment]
It's such a tiny feature request that moves me again away from JetEngine. If there was at least some custom workaround for this after years.

It's absolutely necessary to make fields required. There is no way around it.

**Comment by kaskad88** [comment]
Added in JetEngine v3.1.0
