### ISSUE TITLE
Adding a quantity number box for the Woo Products Grid widget in the JetWoo Widgets For Elementor plugin for WooCommerce

### ISSUE THREAD

**Issue by Tejas-Suvarna** [CrocoBlock/suggestions#1837]
Dear Developers:

I would like you to add a quantity number box for every product displayed in the Woo Products Grid widget. An example would be the picture below.
![image](https://user-images.githubusercontent.com/36018013/92695448-16071c80-f366-11ea-86c1-5f841b582c29.png)

That option could be enabled in the Woo Products Grid widget Content settings. Maybe with a checkbox saying "Show quantity" like the image below.
![image](https://user-images.githubusercontent.com/36018013/92695578-46e75180-f366-11ea-8a2e-f9bc273ea160.png)

Currently, it looks like the image below. No option to add a specific quantity of products to the cart.
![image](https://user-images.githubusercontent.com/36018013/92695665-6b432e00-f366-11ea-90ad-0bb415535e59.png)

Hope you add this feature. Thanks a lot for your wonderful plugins. 😊

**Comment by knireis** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with #457, which is on the same subject so we could deal with it more efficiently.
