### ISSUE TITLE
Crocoblock Jet Appointment: Where can I change the Default time slot length from 30 Minutes to 15 Minutes?or the feature request

### ISSUE THREAD

**Issue by Bikinger** [CrocoBlock/suggestions#1838]
Is it possible to change the time slot length to 15 Minutes? The smallest is now 30 minutes. Is there any Code to change this??
Thank you!

**Comment by kirindi217** [comment]
SOLUTION

With ftp access, go to wp-content/plugins/jet-appointments-booking/includes/admin

Edit file : services-meta.php

Go to line 95 (maybe different with new update) and you will see code option "return Time_Slots::prepare_slots_for_js("

Change,

'from' => 30 * MINUTE_IN_SECONDS,

'to' => DAY_IN_SECONDS / 2,

'interval' => 15 * MINUTE_IN_SECONDS,

'format' => 'U',

to

'from' => 15 * MINUTE_IN_SECONDS,

'to' => DAY_IN_SECONDS / 2,

'interval' => 15 * MINUTE_IN_SECONDS,

'format' => 'U',

You can play and tweak the other setting too...

**Comment by Bikinger** [comment]
Hi!

Thank you for your great support, you saved a little bit of my life.

Best greetings from Austria

Robert Prax

**Comment by creativeart** [comment]
I don't find this, does it change to new version ? Is it still working ? 
My client want appointment for COVID test (each 15 minutes) and I don't find a solution.

**Comment by AndreyPant** [comment]
II have the same problem. The required code is not in the specified file. I found it in another place, but changing 30 to 15 doesn't do anything there. It is important to be able to record for 15 minutes. For example, this time is taken by a consultation. 
Hello from Russia)))

**Comment by MakhonkoDenis** [comment]
In version 1.3.0, a new time picker has been added. Time range from 1 minute to 24 hours.
