### ISSUE TITLE
Jet Woo Template applicable to Wishlist and Compare

### ISSUE THREAD

**Issue by noxdiurna** [CrocoBlock/suggestions#1839]
Hi.

As I was building a e-commerce website, I created a grid template with Jet Woo Template. The latter is obviously applicable to all types of grids, including Upsell and Similar products thru configuration on Woocommmerce from Dashboard. 

That's all great but it seems like that there is no way to apply the same template on Crocoblocks's own Wishlist and Compare page. 

In order to have a refined and homogenous product information around the website, I would like to request the implementation of custom Jet Woo Template to Wishlist page's product grid and comparison grid. 

Thank you.

**Comment by shenom-x** [comment]
Thumbs up!

This is just a logical function that should to be available.

**Comment by Camilo517** [comment]
@UraraReika @Floydtm 
Please check the amount of queries that are made when they should not be done, the duplicate queries and the slow queries
Thank you
http://prntscr.com/vunsn1
