### ISSUE TITLE
 make the url field(s)of the "Video Playlist Widget" dynamic

### ISSUE THREAD

**Issue by MPHood** [CrocoBlock/suggestions#184]
The kava.ticksy support sent me here.

It would be great if you could make the url field(s)of the "Video Playlist Widget" dynamic (so that it works with ACF). Its part of the Jet blog Plugin.

Or can you provide a Hotfix for now?

Thanks!

**Comment by kaskad88** [comment]
Done. Available in v2.1.13

**Comment by MPHood** [comment]
Thank You! Excellent Work!
