### ISSUE TITLE
Jet Reviews BUG

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#1841]
Hello, I started posting reviews on sites through the Jet Reviews plugin and began to receive messages from Google about errors in microdata - https://prnt.sc/uf4h33  https://prnt.sc/uf4j5t  
You can check through the service  https://search.google.com/structured-data/testing-tool/u/0/?hl=ru#url=https%3A%2F%2Fantava.com.ru%2Fotzyvy%2F

https://antava.com.ru/otzyvy/

/*Оригинал*/
Здравствуйте, начал ставить на сайтах отзывы через плагин Jet Reviews и стал получить от Google сообщения об ошибках в микроразметке - https://prnt.sc/uf4h33  https://prnt.sc/uf4j5t  
Можете проверить через сервис  https://search.google.com/structured-data/testing-tool/u/0/?hl=ru#url=https%3A%2F%2Fantava.com.ru%2Fotzyvy%2F

https://antava.com.ru/otzyvy/

**Comment by shinTM** [comment]
done
