### ISSUE TITLE
JetEngine: invalid path when changing the path to the plugin folder

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#1846]
To be honest, I'm not sure that this is an error with jetengine, but I only see errors in the console from it.

So. I decided to change the standard path to the plugins folder. Now all my plugins are located in site.com/modules

In wp-config I have the following written:

`define( 'WP_PLUGIN_DIR', dirname(__FILE__) . '/modules' );`
`define( 'WP_PLUGIN_URL', 'https://example.com/modules' );`
`define( 'PLUGINDIR', dirname(__FILE__) . '/modules' );`

In the end, everything works, but JetEngine in the console gives 404 errors on cx-vue-ui.js and vue.min.js.

The fact is that the new path to the folder with plugins is duplicated for some reason and looks like this:

> //example.com/var/www/example/data/www/example.com/modules/jet-engine/framework/vue-ui/assets/js/cx-vue-ui.js

> //example.com/var/www/example/data/www/example.com/modules/jet-engine/framework/vue-ui/assets/js/vue.min.js

I was looking for a solution to the problem and thought that something was wrong with my settings, but what is strange, everything works in the admin panel, except jetengine.

**Comment by serg-pervushin** [comment]
Guys, the problem is still relevant and I couldn't find a solution to it. Please respond. I remind you that there are about 20 plugins and all work correctly, I only see problems with paths in jetengine.

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!

**Comment by bigg01** [comment]
In our setup we still getting this issue. Is there a work around or how does the fix look like?
