### ISSUE TITLE
jet wishlist

### ISSUE THREAD

**Issue by promocot** [CrocoBlock/suggestions#1851]
add variable product compatibility. At the moment, a variable product is added as a product card, and not by color and size, as well as a button on the favorites or comparison page to see options and not add to the cart

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. 

Right now you can use third party plugin to make separate product from variation it can partly solve your problem.

Thank you for your understanding.
