### ISSUE TITLE
Add Skip Cart & Go Direct To Checkout!

### ISSUE THREAD

**Issue by anthonyclose** [CrocoBlock/suggestions#1852]
Really surprised that you don't offer this.  Please do.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.
