### ISSUE TITLE
JetSearch: add the option to use Default Wordpress search or integrate with relevanssi

### ISSUE THREAD

**Issue by numanagit** [CrocoBlock/suggestions#1856]
I need to do search in productos and search by custom taxonomies. Right now ajax search does not allow to do it so maybe will be better to delegate this functions to dedicated search plugins, like relevanssi that uses default wordpress search integrating this features. Maybe adding the option to use default Worpdress Search i can integrate jetSearch with Relevanssi plugins features.

Thanks

**Comment by jesskiri** [comment]
Would definitely be useful to search by custom taxonomies. For example, I have a custom taxonomy which is similar to Tags and that I use as keywords to describe my CPT. I just found out today that the Ajax search doesn't work with them. Would definitely be a great feature!

**Comment by dattadsphera** [comment]
Hi,
I am stepping up to the request!
In Jet Smart Filter The search is limited at the title's post. If I use Jet Search, the research is limited for one field and in any case the result is visible in another page. I want the search for more several parameters together: title, content, taxonomy, custom fields ... The result must will be in combination with the other filters created with Jet Smart Filters and in page with Ajax method

**Comment by dattadsphera** [comment]
**W Relevanssi**, the Author's plugin is ready for the implementation! He tell me that waits only Jet Staff... it's a simply modify

**Comment by marcofrasson** [comment]
Any update?

**Comment by jacktaffa** [comment]
#4631

**Comment by AzizbekJumanazarov** [comment]
@jacktaffa Thanks. It works with Relevansssi plugin.

**Comment by pitchpublications** [comment]
So Jetsearch now works with Relevanssi?

**Comment by AzizbekJumanazarov** [comment]
> So Jetsearch now works with Relevanssi?

Yes, i used AjaxSearch form of Jet and simple search form, then i also installed Relevanssi plugin, corrected the settings for working with taxonomies and worked perfect. But, now Crocoblock already added a feature that searches products by taxonomies as well. I would suggest to try their new feature before considering other plugins.
