### ISSUE TITLE
Missing functionalities allowing to customize buttons

### ISSUE THREAD

**Issue by martabernat** [CrocoBlock/suggestions#1860]
**Describe the bug**
I found an issue with a product grid customization. 
If You want to change a style of the buttons in for example "Preset 9" You can make changes to displayed txt, icon, width, height and change the order with all of them but You cannot change the "add to cart" I've spent already some days trying to fix it and it is very frustrating. If I want to achieve display order: wishlist / add to basket / quick view is possible only by changing margins but it's still not fixing a problem because the button is staying extra small and don't have an icon which I would like to.
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Adding the function to change width, height, icon and text and the order of the "add to basket" button
**Screenshots**
This is the look which I wanted to achieve 
![image](https://user-images.githubusercontent.com/71337335/93231750-5f49d880-f779-11ea-90ad-ed5f9ef449cf.png)

This is what i get 
![image](https://user-images.githubusercontent.com/71337335/93232065-c23b6f80-f779-11ea-9704-4f2c2d46d032.png)

https://fitinbalance.pl/sklep/

**Desktop (please complete the following information):**
 - windows
 - chrome

 

**Additional context**

**Comment by Floydtm** [comment]
@martabernat, hi! We won't be adding any more options for the products grid widget at this time, you'd better make a separate product card using jetwoobuilder. Thank you!
