### ISSUE TITLE
JetBlog Video Playlist - display youtube video date

### ISSUE THREAD

**Issue by pashosha** [CrocoBlock/suggestions#1861]
Hi,
The video playlist displays duration, which is great, but I find that clients also want the video upload date to be visible, too.
Is it possible to add this display as meta?
Thanks,
LiaD

**Comment by IrynaBerezhnaya** [comment]
Three options have been added: 

'Show Video Publication Date' (works only with the API), 
'Human Readable Date Diff', 
and 'Date Format'.

**Comment by Crocoblock** [comment]
was added in JetBlog 2.4.0
