### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by JorgeBorda** [CrocoBlock/suggestions#1864]
Hello, the people and me  will need a functionality in the Listing Icons...

This feature is missing from the products.

When we have a field of a CPT as DATE, with a Timestamp format, we can not show the DATE in format yyyy/mm/dd, 
Because It is not posible, to use the callback in the dynamic field settings as the dynamic field widget https://prnt.sc/uh16mo

![ListOfIcons](https://user-images.githubusercontent.com/25769249/93357179-507a2900-f840-11ea-9cb0-9319eb7e4b89.png)

**Comment by Floydtm** [comment]
@JorgeBorda, hi! Leave your request here https://github.com/elementor/elementor/issues
