### ISSUE TITLE
Change (localize) the date format of date range smartfilter

### ISSUE THREAD

**Issue by xavipijuan** [CrocoBlock/suggestions#1865]
Hello, 

I hope you can take this request in consideration.

I'm spanish and i do websites for spanish people and other european people with different english date sort of numbers when represent a complete date.

Example in english: 01/06/2020 --> is: **DAY** --> 6 || **MONTH** --> january || **YEAR** --> 2020
Example in spanish: 01/06/2020 --> is: **DAY** --> 1, **MONTH** --> june || **YEAR** --> 2020

I have an anoying issue working with dates using smartfilters date range, because, i i've seen the dates are in english:
The first problem is I can't change the name of the months
The second problem (and maybe the most important) is I can't change or rearrange where the day and where the month where positioned.

I asked about this problem in support, but they suggested that I open a request here.

Can you do changes to 'smartfilters date range' to let the user to select how to show the dates or add an option like the configuration that's available in jetengine dynamic fields? 
Dynamic field has an option called filter field option: it returns months or entire date (translated) in correct format and, it let the user to rearrange the info. But smartfilters date range haven't got any kind of customization for dates. 

Smartfilters date range is a powerful tool, but if it can't be represent the dates in the 'standard' order in other countries, it produces an unespected problem for non english.

Thanks a lot!!
have a nice day!!!
(excuseme for my english :) )

**Comment by Floydtm** [comment]
@xavipijuan, hi! In one of the updates we added a new option https://prnt.sc/uq42o1 https://prnt.sc/uq42yr I think this should solve your request. Let me know if it helps you!

**Comment by julianohammerle** [comment]
Hello good day.
Has this feature been removed? Because I can't find how to adjust the Date Format.

**Comment by julianohammerle** [comment]
Hello good day.
Has this feature been removed? Because I can't find how to adjust the Date Format.
