### ISSUE TITLE
Get the "Current user meta" field value on jetforms

### ISSUE THREAD

**Issue by alexmathias** [CrocoBlock/suggestions#1879]
Hey guys!
I can think in dozens of cases where getting the "Current user meta" field value (also for current user custom meta) and feed it into hidden a form field to replicate it in a post type taxonomy would be very very useful.
Right now I´m in project and need to do so.
<img width="451" alt="screenshot_754" src="https://user-images.githubusercontent.com/66876358/93490656-2166c480-f8df-11ea-978a-266963e441de.png">

**Comment by alexmathias** [comment]
Just knew about freemium "Extend form actions", not sure if it will solve. Gonna test it now!

**Comment by kaskad88** [comment]
Added in JetEngine 2.5.2
