### ISSUE TITLE
Make initial zoom level on JetElements Google Map widget dynamic

### ISSUE THREAD

**Issue by darylbowers** [CrocoBlock/suggestions#188]
Could you make the zoom level on the JetElements Google Maps widget dynamic please?

I have a holiday rental listing site and some properties are in the middle of town, where a close-in detailed map view is appropriate, others are in the countryside, and a larger scale would be useful for seeing where the property is located in relation to the nearby towns.

Currently I have to choose one or the other, or somewhere in between, which is appropriate for neither.

Thank you!

**Comment by kaskad88** [comment]
Currently, Elementor doesn't allow added dynamic tag to number control https://github.com/elementor/elementor/issues/5952.
