### ISSUE TITLE
Listing grid slider: Add option to disable "stop animation on hover" 

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#1888]
This option is missing now. Add a switcher to the listing grid slider that allows to en-/disable animation stopping on hover.

**Comment by bennybersier** [comment]
i second this!

Does anyone have a wordaround with css or javascript in the meantime?

**Comment by bennybersier** [comment]
thanks to Vasiliy Leytman, here is a jquery snippet to add in a html widget to turn off the pause on hover: 

<script>
jQuery(document).ready( () => {
setTimeout( () => { jQuery('.slick-slider').slick("slickSetOption", "pauseOnHover", false, true) }, 10); });
</script>

This will stop ALL the sliders on the page, if you want to target only a certain one: add a class "slider-top" to your listing grid and then change the code to: 
<script>
jQuery(document).ready( () => {
setTimeout( () => { jQuery('.slider-top .slick-slider').slick("slickSetOption", "pauseOnHover", false, true) }, 10); });
</script>

thank you Vasiliy!!!

**Comment by limacon12** [comment]
> [bennybersier](/bennybersier)

Kudos for that

**Comment by kaskad88** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
