### ISSUE TITLE
Yoast SEO + JetWooBuilder

### ISSUE THREAD

**Issue by bormotovva** [CrocoBlock/suggestions#1889]
The issue lay in the compatibility of Yoast SEO with JetWooBuilder.
When we set up the quick view functionality with JetPopup and JetWooBuilder it worked well.
But then after changing the Single template (applied to quick view) the changes weren't applied.
After Yoast SEO disabling everything displayed well then.

**Comment by gianpaolo-mowgli** [comment]
same issue here.

Dynamic fields are not displayed when yoast is active

**Comment by UraraReika** [comment]
1.7.3 release.
