### ISSUE TITLE
JetEngine no Number type? also ID does not auto populate

### ISSUE THREAD

**Issue by studi778** [Crocoblock/suggestions#189]
quick suggestion for JetEngine... when adding in meta fields, the Name / ID should automatically populate in lowercase and underscores like ACF does as this is a big time saver..... your JetEngine just leaves it blank. This would be a simple but big improvement
i also notice there is no "Number" in the Type?

**Comment by luxpatrick** [comment]
I'm missing the number field too. This is really basic... 
Are there any news?

**Comment by petturik72** [comment]
Since Elementor now added support for dynamic number fields, when will JetEngine have a number type field?

**Comment by kaskad88** [comment]
I merged this issue with #1009, which is on the same subject so we could deal with it more efficiently.
