### ISSUE TITLE
JetEngine: Forms - WYSIWYG editor is marked as required even though there is no required option on setup.

### ISSUE THREAD

**Issue by dynamicwebdev** [CrocoBlock/suggestions#1897]
WYSIWYG editor field is marked as required even though there is no required option on setup. Need to remove the required asterisk and need.

**Comment by MjHead** [comment]
Hi! Can't reproduce this bug:
![image](https://user-images.githubusercontent.com/4987981/94130305-27bbea00-fe65-11ea-8e20-ea676c8daa53.png)
Could you plese share a website with the problem and screen of WYSIWYG set up

**Comment by kaskad88** [comment]
Fixed in JetEngine 2.5.2
