### ISSUE TITLE
Instagram Feed Widget

### ISSUE THREAD

**Issue by catherinewiltshire** [CrocoBlock/suggestions#190]
Can I make a suggestion on improving the instagram widget? Perhaps add a lazy loader option - as I can only show a max of 18 photos, but I would like to be able to show them all.

Also perhaps an option of having the caption below the photo instead of as an overlay - at least on mobile if not a general option? As it looks a bit bare on mobile as there is no hover function!

Hope this is the right place to put this!

**Comment by kaskad88** [comment]
Lazy uploading photos from Instagram is now impossible. To display more photos, we changed the maximum value of the option `Number of Instagram posts` now equal to 50
