### ISSUE TITLE
JetEngine - Show or hide some custom fields depending on taxonomies

### ISSUE THREAD

**Issue by creativeart** [CrocoBlock/suggestions#1902]
Hi, it would be awesome if we could show or hide some custom fields depending on the woocommerce category, for example.

Here is an example of a simple example with ACF : https://drive.google.com/file/d/1XjBQwhkE7tIiKafChW7Sdx40UtRW93C1/view

My example is for a client who wants to sell bottles of wine AND event training in the same Woocommerce (very different products, so the fields must be different depending on the category).

**Comment by MjHead** [comment]
https://github.com/Crocoblock/suggestions/issues/4234
