### ISSUE TITLE
Jet Engine - add metabox for specific category on post type

### ISSUE THREAD

**Issue by yaron86** [CrocoBlock/suggestions#1903]
Hello Guys

under the wp posts i have few categories.
i want to show specific metaboxes only when i assign the V check to a specific category.

i know for sure acf has that feature, on acf i can add custom fields and assign it to a category, and when i write a post and assign the V checkbox for the specific category then the custom fields i created appears.

that would be a great feature to have also.
cause currently i can assign metaboxes to cpt only

**Comment by Floydtm** [comment]
I merged this issue with #1902 , which is on the same subject so we could deal with it more efficiently.
