### ISSUE TITLE
Datepicker in date range filter from booking form doesn't work in popup

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#1905]
Datepicker in date range filter from booking form doesn't work in popup
http://ld.crocoblock.com/testing/rookkalo/
http://prntscr.com/umm8rc
Please, fix it before the next update

**Comment by boris-de-jong** [comment]
Is this fixed yet?

**Comment by UraraReika** [comment]
Yes this problem already solved.
