### ISSUE TITLE
CONDITIONAL LOGIC Booking Form

### ISSUE THREAD

**Issue by gringadgets** [Crocoblock/suggestions#191]
Hope you can make this features not just Hide or Show function but how it behaves on sending like conditional receiver on email. If the user select a function on a form the admin can choose who can received it base on the selections of the form. 

This functions can be very helpful if your making the form as a support system. i.e. if the user select a billing support the notification can be sent to support emails or if it is a product the emails can be sent to the one who managing that products.

**Comment by KittyFolks** [comment]
Another conditional that would make lots of sense is for instance that a checkbox is selected and another field will be hidden and un-required and a calculated field is updated with it's selected value. Any news on the previous functionality suggested?

**Comment by MjHead** [comment]
Done
