### ISSUE TITLE
Global colors and fonts - integrated into Templates out-of-the-box

### ISSUE THREAD

**Issue by p34532** [CrocoBlock/suggestions#1911]
Meaning after installing the Dynamic or Design Template, you could then go to the Global styles panel in Elementor, change the value of a global color and **the change would be instantly reflected through the entire website**.

This would work if Global styles would be connected with the templates by default, out-of-the-box.

It would reduce the design time of the website by 90%.

**Comment by UraraReika** [comment]
I merged this issue with #1768, which is on the same subject so we could deal with it more efficiently.
