### ISSUE TITLE
JetSmartFilters : automatically auto indexing new post / or custom post

### ISSUE THREAD

**Issue by mediascite** [CrocoBlock/suggestions#1913]
Hi,

the fact we need to update manually the indexer by clicking on INDEX FILTERS red button after each new post published is not very usable. If we don't click on the button, the number of items in brackets is not updated.  

Can you add this feature please ?

Ben

**Comment by cgatt82** [comment]
Either have it update automatically or provide a cron link or hook which we can run after a form submit would be great ;) 
Kind Regards
Chris

**Comment by mattlecount** [comment]
This functionality is really important. We're unable to use Smart filters across a number of site due to this restriction.

**Comment by Floydtm** [comment]
#1159

**Comment by pierrehansen** [comment]
Yes, please. This is absolutely crucial! Please provide this function in a near update.
