### ISSUE TITLE
JetEngine > Checkbox | Cannot uncheck the second time

### ISSUE THREAD

**Issue by Rubenzella** [CrocoBlock/suggestions#1917]
1. Create a checkbox field and add a new field
2. Save the post type.
3. Go to the post type and check/uncheck the field twice. You won't be able to uncheck it the second time.

You would expect that you can check/uncheck that field how many times you want, but it doesn't.

Refreshing the page will bring you back to step 3.

Tested on an updated version of Chrome for OSX.

**Comment by kaskad88** [comment]
Fixed in JetEngine 2.4.13.  Feel free to update!
