### ISSUE TITLE
Related Products Slider for JetWooBuilder

### ISSUE THREAD

**Issue by leorcdias** [CrocoBlock/suggestions#1922]
Crocoblock plug-ins provide many options for widgets for someone who will create ecommerce with Woocommerce. I believe it is essential to create a widget slider of related products for the JetWooBuilder plugin to be used on single product pages or similar. This would add a lot of time for customers to view a product and be able to see another from it, in addition to becoming visually cleaner.

The current way in which related products are classified is a little bad for the page layout (in my view), as it is not interesting to have more than one line displaying the related products (takes up a lot of space), and to display only one line (with 4 or 5 products) becomes a limitation, especially when you want to display 12 related products, for example.

Example of the requested widget:
https://i.imgur.com/7LjJsUq.gif

[Link of suggestion](https://www.rafarillo.com.br/sapatenis-fly-58009-00-58009-00/p)

I hope you can meet the feature request, as I'm sure many users will use it!

**Comment by fatjay1979** [comment]
You can do that the Listing

**Comment by leorcdias** [comment]
> You can do that the Listing

Listing is just for JetEngine, right? My suggestion is to add such an option to JetWooBuilder. I looked for another solution to create this (having the "E-Commerce" plan) and I didn't find anything like that

**Comment by fatjay1979** [comment]
You can make product loops ... with the Listing ...  very ez ...

**Comment by UraraReika** [comment]
Hello @leorcdias!
You can achieve this result with the help of Products Grid widget. When you put this widget in the single product template and only on this template widget has three additional options https://prnt.sc/upslxz. You can choose what ever you want  and then you can you carousel functionality which this widget has too.

**Comment by leorcdias** [comment]
Thank you for the feedback @UraraReika!

I looked for this query option here and, unfortunately, I didn't find it. Can you help me how to display the same additional options as your image?

My options here: http://prntscr.com/uq53kp

PS.: Site without JetEngine plugin. Need him?
