### ISSUE TITLE
JetWooBuilder 1.7 Feature Request (Localisation / Translation)

### ISSUE THREAD

**Issue by alexander-pankart** [CrocoBlock/suggestions#1923]
Thanks for finally designing the Account, Checkout, Cart and Thank You Page pages with JetWooBuilder 1.7

Is it possible to **write your own text for buttons and headlines**? Unfortunately some of them are in English, some parts of them in my language (Not English :D)

It is a mix of several languages (picture attached, German and English)

![image](https://user-images.githubusercontent.com/69971188/94477809-ac469980-01d2-11eb-8cdc-60319311e46d.png)

I know that the release is very fresh, but that would be necessary to go live with one site.

Thanks for reading.
You guys are great.

**Comment by UraraReika** [comment]
Hello @alexander-pankart! Widgets are built in different ways and in the login form there are some strings that require translation, but in the next updates everything will be done.

**Comment by alexanderpankart** [comment]
Thank you ;3

**Comment by tomherold** [comment]
Yes, please!
