### ISSUE TITLE
JetWooBuilder 1.7 remove .site-main class

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#1924]
In the cart and checkout template a main section is created and a class .site-main is added.  For me this class overwrites the defined maximum width in Elementor and reduces it to 960px. This CSS class is not necessary from my point of view, or am I wrong?

**Comment by UraraReika** [comment]
Hello! Despite you create custom page template, it's basically put template into cart page which created as default woocommerce page. And in this case you can go to page settings in admin area, find and set Page Attributes Template https://prnt.sc/uprupr, and everithing will be okey.
