### ISSUE TITLE
JetElements Slider - Missing Dynamic Fields

### ISSUE THREAD

**Issue by DevGregory** [CrocoBlock/suggestions#1925]
Hi all,

Would it be possible to add/fill in the missing dynamic fields to the Slider widget from JetElements? I have noticed the "Primary Button Text" is not a dynamic field, meaning this can only be set manually using the Elementor editor.

It would also be useful to add in a "Control CSS ID" to each slider, similar to how JetTabs implements this on it's "Tabs" widget. This feature would be really useful for dynamically turning slides on and off when not needed, without accessing the Elementor editor.

![image](https://user-images.githubusercontent.com/72046842/94484153-de0c3000-01d3-11eb-85a3-be3be922d5c8.png)
_This screenshot shows the fields within each slide. The "Button Text" fields are not yet dynamic, which is a shame._

![image](https://user-images.githubusercontent.com/72046842/94484332-2592bc00-01d4-11eb-90e9-db1eecf0862b.png)
![image](https://user-images.githubusercontent.com/72046842/94484406-4529e480-01d4-11eb-878a-fb5721e33db6.png)
The pair of screenshots above show how I have used the "Control CSS ID" function to dynamically turn off unwanted tabs. This would also be a useful addition to the "Slider" widget.

Thanks! Greg.

**Comment by DevGregory** [comment]
Hi all, thanks so much for implementing my first request, it works a treat!

I was just wondering if there's any update on adding the "Control CSS ID" field to the Slider widget as of yet?

Thanks again, Greg.

**Comment by DevGregory** [comment]
This request has since been removed from the plugin, with support insisting it was never actually added in the first place? Could you update me on this? "Primary Button Text" was dynamic just last week..

**Comment by Floydtm** [comment]
@DevGregory, hi! Your issue is pending. We will be able to take this to work in the near future. Keep for updates. Thank you!

**Comment by DevGregory** [comment]
@Floydtm Thanks Floyd, I'm not sure why, but this was added in a previous version and then removed.. I understand you may still be working on adding this, so please keep me updated.

**Comment by kaskad88** [comment]
Added in JetElements 2.5.3

**Comment by DevGregory** [comment]
Hey all, thanks so much for adding this for me, the buttons are working great.

The CSS ID also works to a certain extent, but it only turns off the slide content, not the slide itself (See image below).

![image](https://user-images.githubusercontent.com/72046842/102499390-06892500-4073-11eb-91f0-2284286bb201.png)
![image](https://user-images.githubusercontent.com/72046842/102499446-17d23180-4073-11eb-9b63-80eaa2d9e4ef.png)

You can see above, I have set a CSS ID for the first slide and set it as display: none, this has removed the content but the slide itself is still showing.

Is there any way we can turn the whole slide off? I noticed .sp-grab controls the slides themselves, but I can only turn the whole lot off.

Thanks again! Greg.
