### ISSUE TITLE
Create Ability to Set Template Type JetWooBuilder

### ISSUE THREAD

**Issue by envyyycreative** [CrocoBlock/suggestions#1926]
Currently you cannot choose between "Default Template", "Elementor Full Width", and "Elementor Canvas" when editing a WooBuilder Page. As a result it becomes necessary to use Elementor's "Stretch section to full width using JS" feature, which doesn't react correctly to padding (esp. in %).

**Comment by UraraReika** [comment]
Hello @envyyycreative! Despite you create custom page template, it's basically put template into cart page which created as default woocommerce page. And in this case you can go to page settings in admin area, find and set Page Attributes Template https://prnt.sc/uprupr, and everything will be okay.
