### ISSUE TITLE
Add Ability to Use Elementor Global Colors JetWooBuilder

### ISSUE THREAD

**Issue by envyyycreative** [CrocoBlock/suggestions#1927]
Currently you can not set a global color for any widget on any WooBuilder page. This means colors can change dynamically in the final stages of a website everywhere except in the WooBuilder Templates, which have to be adjusted manually on every single widget.

**Comment by UraraReika** [comment]
Hi @envyyycreative! 

Basically everything works fine, but you should notice that you work with woocommerce elements, and they can be styled in themes or in other plugins, not to mention about woocommerce plugin styles. 
So if you inspect the elements you will see, that global styles exist but they overwritten from the beginning.

In last update we added Global styles compatibility, and now you can use this option https://prnt.sc/upwpjg to choose global color which you set, color https://prnt.sc/upwpyq, or whatever you want.
