### ISSUE TITLE
Listing Grid Load More Bug

### ISSUE THREAD

**Issue by chrisecostanza** [CrocoBlock/suggestions#1928]
**Describe the bug**
When I click the load more button it is returning some duplicate results from the original items that are shown.

**To Reproduce**
1. Go to https://indianaartisan.lc453fem-liquidwebsites.com/artisans/
2. Click on load more button
3. See occasional duplicate artisans (initial display of artisans is set to random)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)
 - JetEngine 2.4.12

**Comment by Floydtm** [comment]
We checked everything again and it seems to work well. However, I do not exclude that our plugin is configured differently. Contact our support service and provide access to the site. Thank you!
