### ISSUE TITLE
Form Post-Submit Action Redirect to New Post

### ISSUE THREAD

**Issue by Kyle7885** [CrocoBlock/suggestions#1930]
A feature I would like to have is the ability to immediately view a new post that is created by a form.

I have created a form for users to create a custom post.  I have an Elementor Template to view the post once that form has been submitted.  In the Post-submit Action / Notifications Settings, there is an option to Redirect to Page.  I selected the option Redirect to:  Custom URL and in the Redirect URL: field I copied and pasted the permalink for the Elementor Template to view the post and selected the Add query arguments to the redirect URL: for inserted_post_id.  However, this just takes me to an existing post rather than the one that was just created.

I think there should be an option to Redirect to the New Post.

**Comment by MjHead** [comment]
Hi! We implemented this as separate addon - https://github.com/Crocoblock/jet-forms-new-post-redirect-notification
