### ISSUE TITLE
JetWooBuilder: templates conditions

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#1935]
need create 2 or 3 templates for single product. It's better to set the display conditions per each custom template instead of single product. Like for example: show Y on X taxonomy/terms, child of, etc.. or other conditions as Elementor Theme Builder does..

**Comment by DmitryBychenko** [comment]
Is it possible to set display conditions with Elementor free?
Or may be I understood you wrong?
Can you explain in little more details what you mean.
