### ISSUE TITLE
Buy now button JetWooBuilder

### ISSUE THREAD

**Issue by bormotovva** [CrocoBlock/suggestions#1936]
Hello I, have the add to cart button in my product page. I want to add a second button with the buy now option and redirect to the payment page

https://woocommerce.com/products/quick-buy-now-button-for-woocommerce/

**Comment by arekuki** [comment]
+1

**Comment by UraraReika** [comment]
You can use this plugin https://wordpress.org/plugins/woocommerce-quick-buy/. Its perfectly work with our templates.
