### ISSUE TITLE
How can i put term section (like category label) just below title ?

### ISSUE THREAD

**Issue by Nohud** [CrocoBlock/suggestions#1937]
Hello,
I wish to know how to put the terms section (like category) just below post title instead of on post image.
Here is an example : https://zupimages.net/up/20/40/y4cs.jpg
![téléchargement](https://user-images.githubusercontent.com/39729229/94688288-a87b5a00-032d-11eb-8c7c-a5cdaa800fa9.jpg)

I already tried to change margin in order to put it where i want but it's not working when title as 2 lines for example. I need to have this section directly below title.
In other words to put this code line :
```
<div class="jet-smart-listing__terms">
      <a href="#" class="jet-smart-listing__terms-link jet-smart-listing__terms-link--3">My Category</a>
</div>
```
Juste below this line :
```
<div class="jet-smart-listing__post-title post-title-simple">
      <a href="#">My Title</a>
</div>

```
If you can't do it this new feature soon, can you just tell me what file should i change to do what i need ?
Thank  you very much for your help.

**Comment by Floydtm** [comment]
You can implement this with styles in the widget https://prnt.sc/uqo7kn if you have any problems please contact our support team

**Comment by Nohud** [comment]
Thank you Floyd (i'm a fan too :) )
I don't really understand how to put like i said. In your screen, you put it on top but what i need is below post title. 
I contacted support (Julia answered me) but she asked me to make a feature request on Github.
Thank you for your help.
