### ISSUE TITLE
jetmenu mega menu on mobile is embarrassing to use.

### ISSUE THREAD

**Issue by mattiebrownoz** [Crocoblock/suggestions#194]
**Describe the bug**
It is simply useless on mobile. the user cant click away or close after it has been pressed

**To Reproduce**
click on a jetmenu megamenu. It can not be closed. The user will have to navigate away to another link to advance anywhere on the website.

**Expected behavior**
I expected it to close or respond much better on mobile

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 all smartcphones and mobile devices

**Additional context**

**Comment by mattiebrownoz** [comment]
Cmon guys. Please allow this to happen. It’s not a feature request, it’s more of a bug in my opinion. The user can’t close the menu on opening on mobile. What about if the scroll had a floating ‘close’ tab follow the users scroll and be able to be positioned?

**Comment by zuroma999** [comment]
I'm also waiting for this fix. It's sorely needed.

**Comment by Biblothecaire** [comment]
+1, need this too.
Or possible to not use the jetmenu only for mobile ? And use the theme menu ?

**Comment by Martinevdhouten** [comment]
This needs to be fixed, it is counter-intuitive to only be able to open a megamenu with the arrow and not close it. If Jet menu won't improve on mobile, I don't think people will continue using it

**Comment by mattiebrownoz** [comment]
I know... so many months

**Comment by realstephenzhao** [comment]
I don't need the toggle button to be float. Please make it static.

**Comment by oliverf72** [comment]
+100 I need to add another menu for mobile due to these restrictions...check this on mobile f.ex. https://www.allgaeuer-berghof.de/
not possible with jet menu

**Comment by Floydtm** [comment]
Guys, we redid the mobile menu. A beta version of the jetmenu plugin is now available in your account

**Comment by Martinevdhouten** [comment]
Awesome yay thanks!

**Comment by oliverf72** [comment]
Much better, but full screen and animation effects are missing. And I have a mega menu for one main menu item which does not show correctly on mobile (the items in the mega menu are not responsive). but great to have more options now..would be great to have features like superfly menu... ;-) thanks for your work...
