### ISSUE TITLE
Possibility of controlling the offset of the listing grid in archive mode

### ISSUE THREAD

**Issue by secktd** [CrocoBlock/suggestions#1941]
It happens for projects to want to create custom  designers.
For a project I would like to implement a design for an archive page but I cannot do it because the listing grid widget does not allow to control the offset when the archive option is selected.
I think that we should give the possibility to control the options of the listing grid in archive mode.

I put a capture to show you the design that I want to reproduce but it is not currently possible
<img width="984" alt="Capture d’écran 2020-09-30 à 23 27 10" src="https://user-images.githubusercontent.com/72172102/94749943-83f6a080-0374-11eb-9e4d-d13c7e87dae9.png">

**Comment by Floydtm** [comment]
Sorry, but there is no way to use these options on the archive page

**Comment by kwsim539** [comment]
This is stupid. How can we have any creative latitude on the archive pages if we can't Offset & Order an archive grid? Why can a simple plugin like [Ele Custom Skin Pro](https://dudaster.com/) can accomplish this and you can't? I'm starting to give second thoughts about making JetEngine a viable replacement to the other grid plugins I currently use.
