### ISSUE TITLE
JetEngine Map Listing - Ability to toggle clustering

### ISSUE THREAD

**Issue by jim-zero1zero** [CrocoBlock/suggestions#1945]
At the moment the map seems to cluster markers that are close using the markerclustererplus.min.js library. 
There are cases where we would like to be able to either style the clusters or to turn off clustering completely.

**Comment by kaskad88** [comment]
This feature is already available https://gyazo.com/af82faa1308d13927e66be11a7fe1a43

**Comment by RomainLaf** [comment]
How to style the cluster marker ? Currently on my website it's a blue circle. I would like to change it's color. https://i.ibb.co/YdnnSyB/Screenshot-Arc-06-11-17-13.png
