### ISSUE TITLE
Jet Engine Dynamic link not work properly in v 2.5.0

### ISSUE THREAD

**Issue by P258tiwari** [CrocoBlock/suggestions#1949]
I am using listing to create portfolio in my website and I also create edit form frontend by user account using jet profile builder but new update dynamic link not take link from other sub domain 
e.g
https://domin.com/account is my account page and I set edit in account sub page update https://domin.com/account/update/?post_id=1 but new update dynamic link not work properly when I click on Update button it redirect me to https://domin.com/account/?post_id=1 

Supported Image 
![Screenshot (14)](https://user-images.githubusercontent.com/64008801/94900883-667c2080-04b3-11eb-965b-c6748fb8040f.png)

![Screenshot (15)](https://user-images.githubusercontent.com/64008801/94900903-6f6cf200-04b3-11eb-9134-d73ed462a053.png)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome
 - Version Jet engine 2.5.0

**Additional context**

**Comment by P258tiwari** [comment]
CCT is not support color field 
e.g. I added color field in CCT but in listing it not work

**Comment by Floydtm** [comment]
We have released a plugin update that fixes the dynamic link bug. As for the second question. I'll tell the developer about it and if possible we will fix it in the next update. Thank you!

**Comment by P258tiwari** [comment]
Thanks
