### ISSUE TITLE
jetelements has a table widget which I can't even enter dynamic fields into from jetengine. It's your own plugin and widget.

### ISSUE THREAD

**Issue by mattiebrownoz** [CrocoBlock/suggestions#195]
I can use other table widgets from other providers to bring in dynamic fields from ACF and Jet Engine, but if I try to use Jet Elements Table widget there is no way to use dynamic fields. This has to change. 

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

It should be added to support your own product. How can you have a widget which does not accept your own dynamic field?

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Tables. Tables. Tables. Dynamic fields NEED to be able to be used within your own Table widget from Jet Elements !

Thank you.

**Comment by mattiebrownoz** [comment]
Please please please allow your table widget the ability to add jet engine dynamic fields ASAP. It’s driving me crazy with a project in limbo waiting for this feature. I’ve got other plug ins which have a table widget and allow your jet engine dynamic fields.

**Comment by mattiebrownoz** [comment]
Great to see progress on this. Thumbs up!

**Comment by kaskad88** [comment]
Added for next version (1.15.14).
Thanks for your report!
