### ISSUE TITLE
Add Multi Step Checkout to JetWooBuilder

### ISSUE THREAD

**Issue by Sellerielutz** [CrocoBlock/suggestions#1950]
Dear Crocoblock Team, 
Thank you for making such amazing plugins for Elementor. Especially your recent update to. JetWooBuilder made me. very excited! 

I would love to see a functionality in JetWooBuilder that allows us to enable a **multi-step checkout** in Woocommerce so we could rebuild a "Shopify like" checkout experience in Woocommerce. 

This would be awesome!
Thank you for your work and consideration of this feature!

**Comment by Floydtm** [comment]
We have no plans to do this at the moment. However, you can use a third party [solution](https://wordpress.org/plugins/search/Multi+Step+Checkout/). Thank you!
