### ISSUE TITLE
JetEngine: FontAwesome icons not shown

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#1953]
If the JetEngine ListingGrid Slider is activated with navigation arrows, they will not be shown if no native elementor widget with icons is set on the same page. I think this is because of the new performance optimization. Elementor will not load FontAwesome if no widget with icon is set on the page.

**Comment by uriklar** [comment]
@petranca Hi! Do you remember what the solution for this was? I'm using jet engine gallery and my icon doesn't appear. I tried putting an icon box on the page with the same icon but it still won't appear inside the jet plugin. 
Thanks!

**Comment by uriklar** [comment]
For anyone getting here, this is how I solved it (jet engine was using the wrong font family)
```
.jet-engine-gallery-item-wrap::before {
  font-family: "Font Awesome 5 Free" !important;
  font-weight: 900 !important;
}
```

**Comment by mikraxx** [comment]
Thanks @uriklar that just solved my problem too. But I keep wondering why is happening, I might open a ticket in Crocoblock support forum and let you know :)
