### ISSUE TITLE
JetSearch Roadmap: Add advanced features for more flexibility and better conversions for ecommerce

### ISSUE THREAD

**Issue by oceandiveloper** [CrocoBlock/suggestions#1954]
In yesterday's live webinar for JetEngine 2.5 towards the end I asked in the chat about plans for JetSearch and the fantastic @MjHead indicated that there is not a real roadmap yet for a new JetSearch release. Since they listen to the community I thought I activate the community to help me get some new important search features for the Crocoblock suite.

JetSearch is a great solution for posts and other custom post types. It just lacks some advanced functionality to be a great option for many use cases. Here is my wishlist of some requests that elevate JetSearch even higher: 

- **listing support**: allow to build our own search results via listings (to add dynamic terms, "add to cart" buttons etc.)
- **search phrase highlighting in the results** to quickly identify if the product is what I'm looking for
- **search inside taxonomies terms** (possibly even term description)
- option to display (primary) **taxonomy term in the search results**
- option to **filter for a specific post type** and **display post type in results** (if we have multiple post types in one search - e.g. events, products, services)
- option to open a **full screen live search** after clicking on search icon button

Then there are eCommerce websites. For WooCommerce products we can already add the price and the rating but that's not enough to compete with other WooCommerce Live Search solutions. An online shop with many hundreds/thousands of products depends on a helpful search. Even if there isn't any result that perfectly matches the search phrase, there should be possibilities to find other useful results automatically. 

I've done a bit of research and found very cool features in other plugins that would make JetSearch unbeatable. A proper search & suggestion engine would be a great addition to achieve any of the following:

- fast **autocomplete function** to suggest products and or categories that match the search phrase
- **fuzzy search** (if there is a typo)
- **search for synonyms** (e.g. when I search for "laptop" also suggest products for "notebook" or "computer")
- record search phrases and **suggest popular searches**
- offer **search statistics** that help shop owners to know what visitors are looking for
- **recommend products if no search results are found**
- show **recently viewed products** before the user starts typing for search
- show **recently searched products** before the user starts typing for search

I'm aware that's a big list and of course not everything can be developed quickly. I mostly want to get the attention of the developers to see how a more advanced JetSearch can make a lot of users very happy. I hope you agree.

**Comment by JamesJosephFinn** [comment]
Fuzzy / autocomplete is a must. I'm going to use another solution because JetSearch only returns exact matches.

**Comment by trouaud** [comment]
Must needed functionnalities. I will also go for another plugin because JetSearch is lacking some.

**Comment by Morgunov-Vitaly** [comment]
+1 search phrase highlighting in the results

**Comment by MjHead** [comment]
- Search hightlight and search in terms added with 3.0.0 update.
- part related to change results output is possible from the code. At the moment there is no plans significantly change it bacause it related a lot of compatibility issues.
- the part related fro eCommerce improvements is in the roadmap for the 3.1 and 3.2 updates (maybe not exactlyy all the things but most of them)
