### ISSUE TITLE
JetWooBuilder - Germanized price

### ISSUE THREAD

**Issue by bormotovva** [CrocoBlock/suggestions#1958]
In Germany we have to show a baseprice undearneath the normal price (See attached screenshot). For this I have a plugin called gemanized that allows you to add an aditional price in Woocommerce. This Price is then displayed in the normal Elementor Product Grid but not in the on from JetWooBuilder.
 
There is a shortcode that can be used to add it to the price through an add fuction: The shortcode is [gzd_product_unit_price] and I want to display it underneath the normal products price. Maybe you can send me the code, as I have no coding skills.

Best Regards
Wael

**Comment by Wael890** [comment]
Hello, how can I add a shortcode (which contains a base price e.g. per liter) under the exisiting price.

**Comment by UraraReika** [comment]
Hello @Wael890 !

You need to use filter `'jet-woo-builder/template-functions/product-price'`. This filter handle woocommerce price HTML. In your function.php file you can override it like this:

```
add_filter( 'jet-woo-builder/template-functions/product-price', 'get_gzd_product_unit_price' );

function get_gzd_product_unit_price( $price_html ) {
	$price_html .= do_shortcode( '[gzd_product_unit_price]' );

	return $price_html;
}
```

**Comment by Wael890** [comment]
Thank you, that worked fine. Is there any way to not display the price in a
smaller size than the normal price?


Am Mi., 21. Okt. 2020 um 10:17 Uhr schrieb Oleksandr Rudyi <
notifications@github.com>:

**Comment by UraraReika** [comment]
@Wael890 
`[gzd_product_unit_price]` return it`s own HTML markup that is not effected by our widgets controls.

**Comment by UraraReika** [comment]
And in this case you need to style it by css code.
