### ISSUE TITLE
SVG images display image in media library

### ISSUE THREAD

**Issue by alriksson** [CrocoBlock/suggestions#196]
**Describe the bug**
SVG is enabled in crocoblock but does not display the thumbnails in media library

**Expected behavior**
Expect crocoblock also make them display properly in the Media grid. But that's broken now. Right now the function is redundant. And poor for me as a user which force me to install another plugin, would be great if you could solve this bug.

In all views:
Single image view
Grid view
List view

**Screenshots**
https://tppr.me/UfNvI

**Comment by kaskad88** [comment]
Done. Available in v1.15.11
