### ISSUE TITLE
JetEngine Listing Grid Lazy Load isnt working with Posts queries

### ISSUE THREAD

**Issue by peterhrnciar** [CrocoBlock/suggestions#1960]
New JetEngine feature for Listing Grid Lazy Loading isnt working with Posts queries.
After turning lazy load on, it shows all listings, not only which should be displayed according to settings in Post query.

**Comment by Floydtm** [comment]
@peterhrnciar, hi! We checked the plugin again and everything works correctly. However, we do not rule out that your site is configured differently. Please contact our support team, they will help you. Thanks!
