### ISSUE TITLE
JetSmartFilters: add GEO range filter to use it in Advanced Map

### ISSUE THREAD

**Issue by AlexIM-dev** [CrocoBlock/suggestions#1967]
The suggestion is to add range filter in order to filter objects in the listing which contain Advanced Map widget. The listing items have dynamic location coordinates received from meta fields of its parent post. The GEO filter allows to a user set a distance to locations to get the only listing objects which are closer than the set distance. The filtering is based on current user location.  
It is also valuable for working with the Map widget outside the listing e. g. if there is a number of store locations, a user could filter them by distance.

**Comment by bennybersier** [comment]
I second this 
Would be very useful to have a geo range filter both on advanced maps and maps listing

**Comment by RodSuper** [comment]
This would be the next step for property and hotel websites created with JetEngine Listing Grid and Maplisting

**Comment by Joshuamajch** [comment]
Jes! Hope this feature comes soon and we do not have to mix up jetengine with other plugins just to achieve the geo filtering. Fingers crossed

**Comment by evolvenl** [comment]
> Jes! Hope this feature comes soon and we do not have to mix up jetengine with other plugins just to achieve the geo filtering. Fingers crossed

If I may ask: Which other plugins do you use at the moment for geo filtering?

**Comment by Joshuamajch** [comment]
Hey evolvenl, I have not yet implemented geo filtering as I am still hoping for Jet to release it. i will take care of all the rest of my platform first before implementing this critical feature. 

Worst case, I'll have to pay someone to implement it in Jet or switch to another filtering plugin such as wp facet

**Comment by lucariomegaform** [comment]
This will be a gamechanger for us - it would be great to see it added to JetSmartFilters this year. We've been redeveloping core areas of our website using Crocoblock plugins, which are great, but there are two major sections (a member directory and events search) that still need the WP Facet proximity filters. WP Facet works well but its implementation is kind of clunky, and we'd prefer to use the same tools across the whole site.

As soon as we can use proximity filters (ie. search for members within [X] miles of [LOCATION]) alongside other faceted searching we'll be able to shift completely over to JetSmartFilters.

**Comment by Rubendj1** [comment]
I would love to see this functionality!

**Comment by startupweb** [comment]
This would be wonderful.   This would be perfect for a directory listing to find posts types near your or near a certain area.

**Comment by Spacefunls** [comment]
Agreed, would also need this functionality

**Comment by BEKWL** [comment]
Upvote please

**Comment by opwolken** [comment]
+1

**Comment by Scoots78** [comment]
I want this so so bad +1

**Comment by taidang26** [comment]
+1

**Comment by Micheldebo** [comment]
I want this!

**Comment by kochhase** [comment]
must have!

**Comment by cangulostudios** [comment]
+1

**Comment by neylwalecki** [comment]
+1

**Comment by developer784** [comment]
+1

**Comment by renegademarketer** [comment]
+1 This is THE main feature stopping us and others from going all-in with Crocoblock for directory-like websites. Please add this functionality soon!

**Comment by developer784** [comment]
ASAP...... trying to come up with a custom solution and still use
Crocoblock.  HAVE NO IDEA WHERE TO START!

Need this feature live in a matter of days.

If you know anyone who can do this, hit me up.

**Comment by leofierro** [comment]
I hope this functionality will be added soon...

**Comment by Catching-Eyes-Media** [comment]
This definitely should have been a high priority for the original map integration.
+10,000!

**Comment by evcircle** [comment]
Is this not out yet? I want it as well for my auto listing website. so +1 for this suggestion.

**Comment by evcircle** [comment]
Reiterating: Can we have this feature where it auto-detects the user's location and shows listings/Map with multiple listings nearby

**Comment by Zach-Toth** [comment]
+1 really need this feature for a client site!

**Comment by joehdevwp** [comment]
+1 upvote for this feature

**Comment by Kytab** [comment]
want it !!!

**Comment by Smalyleinchen** [comment]
+1

**Comment by Crocsnative** [comment]
I would love this feature for filtering posts by location (for an event-searching-website)!

If someone can programm that or knows someone who can do that, you might have an offer from me, so let me know

Email: janvelske@gmail.com

**Comment by swinggraphics** [comment]
+1 for making it easier to do with an entered location, that doesn't rely on JS location API.

Found these searching "crocoblock distance filter":

https://itchycode.com/filter-jetengine-map-listing-by-user-input-address-radius-distance-jetengine-jetsmartfilters-query-builder/

https://facetwp.com/help-center/facets/facet-types/proximity/

**Comment by Miheyeugene** [comment]
> +1 for making it easier to do with an entered location, that doesn't rely on JS location API.
> 
> Found these searching "crocoblock distance filter":
> 
> https://itchycode.com/filter-jetengine-map-listing-by-user-input-address-radius-distance-jetengine-jetsmartfilters-query-builder/
> 
> https://facetwp.com/help-center/facets/facet-types/proximity/

Hi guys! Hi [swinggraphics](https://github.com/swinggraphics)! Thank you for nice tutorial, it helped me. But it would be more better if somebody knows how to do radius search by zoom/pan the Map Listing to a specific area than the Listing Grid updates accordingly

**Comment by levin-roski** [comment]
+1

**Comment by SyedQalab** [comment]
+1

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140

**Comment by lucariomegaform** [comment]
Great news!
