### ISSUE TITLE
JetPopup Elementor Form in popup with Loading content with Ajax on breaks the page

### ISSUE THREAD

**Issue by ihslimn** [CrocoBlock/suggestions#1968]
If Elementor Form widget is put inside JetPopup with "Loading content with Ajax" option enabled,
and that popup is attached to any widget on the page, the page will crash with an error:

   Fatal error: Uncaught Error: Call to a member function get_main_id() on null
   in /home/crocoblo/public_html/ld/testing/wp-content/plugins/elementor-pro/core/utils.php on line 73

1. Create JetPopup.
2. Add Elementor Form to it.
3. Enable "Loading content with Ajax" option.
4. Attach the popup to any widget.
5. Page will not load properly because of the above-mentioned error.

**Comment by davidfrx** [comment]
I have the same Problem. Updated from v1.3.1 of JetPopup to 1.5.2 and it breaks the site. Noticed that already a few months ago and therefore waited with updating a page to a newer version. But the problem still remains. Any solutions to fix this?

**Comment by lgpguga** [comment]
Hi, I have the same error now after Elementor Pro 3.30 update.
"Call to a member function get_main_id() on null in wp-content/plugins/elementor-pro/core/utils.php:72"
It shows after I Enable "Loading content with Ajax" option
Please help us!
My Web app is not offline because of it

**Comment by uiliw** [comment]
Is there any fix for this? same problem here with jetpopup 1.5.5

**Comment by siscanu** [comment]
The same problem with Elemente 3.4.4 and JetPopup 1.5.5.

**Comment by siscanu** [comment]
If someone knows how to solve this proble, please let us now. Thanks.

**Comment by siscanu** [comment]
To fix this issue, you need to use widget only from Jet Plugin. If you use a form, use jet engine form.

**Comment by shafqatkhan60** [comment]
Hey!
Any update on this issue please?

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed in 1.6.0 ver. If you have a problem with this, please let us know.
