### ISSUE TITLE
Dynamic image/icon in JET Headline

### ISSUE THREAD

**Issue by alriksson** [CrocoBlock/suggestions#197]
**Please, describe the feature request, making it clear to understand.**
Add dynamic support for JET Headline for decorative elements, image field is only supporting static not dynamic.

**Comment by kaskad88** [comment]
Added in JetElements 1.15.10

**Comment by alriksson** [comment]
@kaskad88  I updated JetElements yesterday and I can still not see dynamic. Can you please show me where?

**Comment by kaskad88** [comment]
@alriksson Release JetElements 1.15.10 will be tomorrow.

**Comment by alriksson** [comment]
@kaskad88 Okay, got it! Did nto check version consider the last update was yesterday or the day before so though you referred to that one. Great thanks! Implement dynamic into all functionalities please! :)
