### ISSUE TITLE
JetEngine - Dynamic Visibility is not Working

### ISSUE THREAD

**Issue by vinitha2998** [CrocoBlock/suggestions#1971]
Dynamic Visibility is not working.
am adding one video in video gallery and set the condition in dynamic visibility . but it not visible
am  attaching screen shot

This is the login URL

Issue page URL : https://wordpress-463956-1475351.cloudwaysapps.com/wp-admin/post.php?post=2017&action=elementor#

![KULHUL (1)](https://user-images.githubusercontent.com/72502280/95329365-71c0b900-08c4-11eb-9dba-a47892043b96.png)
![Uploading UKIYK (1).png…]()

**Comment by Floydtm** [comment]
@vinitha2998, Hey. I want to say that it is not safe to leave your login details here. Please contact our support team, and also change your password for security

**Comment by vinitha2998** [comment]
Thank You , I changed it.

am already asked the support team, they recommend to leave a request here
I need a solution for **Dynamic Visibility**
