### ISSUE TITLE
Jet Search against CCT's

### ISSUE THREAD

**Issue by panda1966** [CrocoBlock/suggestions#1976]
**Jet Search**

Is it possible to make the Jet Search plugin to deliver results based upon custom fields only that would then show in a sear results area on same page.

i.e., state, license expired, last name and other custom fields.

**Comment by MjHead** [comment]
@panda1966 at this moment you can use search filter from JetSmartFilters, but in the future we'll try add compatibility with JetSearch

**Comment by SayDevz** [comment]
any update on this ?

**Comment by jacktaffa** [comment]
up

**Comment by MjHead** [comment]
Added in JetEngine 3.5.5
