### ISSUE TITLE
Dynamic Data in Content Type Query

### ISSUE THREAD

**Issue by moxet** [CrocoBlock/suggestions#1978]
I am using CCT from few days and it works as expected. I have one question. While grabbing data from database which is saved with a unique ID of user. I want to show data to the user which belongs to him. When in **Content Type Query** i filter data with USER it works fine for static data.

But what if i want to show it for the logged in user?
https://prnt.sc/uuxg8o

**Comment by Floydtm** [comment]
Could you please provide more details with screenshots or video. You can also contact our support team. Maybe you just need to use the dynamic visibility module https://prnt.sc/uw1puq https://prnt.sc/uw1q4h

**Comment by moxet** [comment]
@Floydtm i did contact customer support.

I am aware of the dynamic visibility, the thing is i have saved CCT data in database with a unique user_id. When i pull data it shows all data whereas i need for user_id suppose 5. in Content Type Query when i type 5 it works fine but i want this 5 number to be dynamic id of a user which is logged in.

**Comment by MjHead** [comment]
Hi @moxet CCT query settings at this moment supports only JetEngine macros (since JetEngine 2.5.2). For your case you can try to use %queried_user_id% macros.

**Comment by moxet** [comment]
@MjHead Thank you so much for this query, this is what i was expecting. It works fine with me now.
