### ISSUE TITLE
JetEngine Dynamic Visibility - WooCommerce Category

### ISSUE THREAD

**Issue by hNilsen90s** [CrocoBlock/suggestions#1983]
It would be great if we could decide to show or hide information based on the WooCommerce category.

For example, if you are inside of a single product page viewing something that requires additional information, it would be easy to display this based on that category the product was placed in.

**Comment by serg-pervushin** [comment]
I support it, it is necessary.

**Comment by UraraReika** [comment]
This issue can be solved with the help of `Post has term` visibility option.
