### ISSUE TITLE
Keep order (DESC or ASC) after in listing grid after submit a fikter

### ISSUE THREAD

**Issue by jeffreyT836** [CrocoBlock/suggestions#1984]
We have an order and offset set in the listing grid on meta value ASC and then Title ASC, but after selecting an e.g. 'branche' in the filter the order is reset to Date DESC.
Can you fix this and preserve the orde or is that nog possible,

**Comment by Floydtm** [comment]
We tested it and everything seems to be working correctly. However, I do not exclude that our sites are configured differently. Contact our support team, provide access to the site, we will try to solve your problem.
