### ISSUE TITLE
JetEngine – forms – Integration with Mailerlite

### ISSUE THREAD

**Issue by CathJex** [CrocoBlock/suggestions#1987]
JetEngine Forms (profile builder) has limited integrations with 3rd party mailing list services. Unless you have a paid Zapier account, then users are limited to 100 zaps/month, which is potentially not enough for a small–mid-sized membership site. And even with Zapier, it introduces an unnecessary 3rd step between JetEngine and a mailing list service. And the inbuilt 'send email' function is limited in terms of design options, which doesn't make a great impression on new users.

Therefore, I request further integrations with a wider range of mailing list services, removing the need for Zapier. My personal request is for Mailerlite, since they have a more flexible free pricing plan than MailChimp and offer good GDPR solutions for EU-based websites/customers/members. 

Adding more integrations, will immediately ease the workflow in JetEngine when registering new users or subscribing them to mailing lists. It will also provide greater flexibility and choice to JetEngine users, when deciding which mailing list service to use and when deciding whether to buy JetEngine or another membership plugin. For example, they may need to transfer existing mailing lists over to JetEngine profile builder and might not want the added complication/limitation of using Zapier. This will make JetEngine a more competitive choice compared with other site-membership plugins.

Elementor already has a wide range of 3rd party mailing list vendors for their form widgets. But this cannot be used by most JetEngine users when managing new user/member registrations. This use case is particularly crucial for JetEngine subscribers.

**Comment by Ninesse** [comment]
Would really love a MailerLite Integration!

**Comment by Dennisvb** [comment]
Yes!, Really need integration with MailerLite.

**Comment by mangelcc** [comment]
I agree, this Jet Engine function with Mailerlite. November 2022

**Comment by girafffee** [comment]
You must try this addon. It can be used both with JetEngine Forms and with JetFormBuilder
https://jetformbuilder.com/addons/mailerlite-action/
