### ISSUE TITLE
💡 JetWooBuilder Products Grid - Order by Title

### ISSUE THREAD

**Issue by redpanama** [CrocoBlock/suggestions#1988]
Please implement the order by title in the Products Grid widget. It's mind-boggling why this simple feature isn't there since day 1.
Because of this, I'm forced to use different elementor plugin that I don't want to.

Thanks 

![image](https://user-images.githubusercontent.com/18248955/95563271-7b116900-0a1d-11eb-8d77-b2c01e2b57d8.png)

**Comment by Rstoelwinder** [comment]
Yes!!! Really looking forward to this one!

**Comment by redpanama** [comment]
Thanks @Floydtm

**Comment by redpanama** [comment]
Thanks @UraraReika 👍
