### ISSUE TITLE
JetEngine Forms Add option select a custom user role for each registration form

### ISSUE THREAD

**Issue by mrfabian7** [CrocoBlock/suggestions#1994]
Add in the new user record type, the option select a custom user role for each registration form
https://prnt.sc/uwpo51

thanks

**Comment by moxet** [comment]
You can try from wordpress core setting that what will be the default user role. It might work.

**Comment by mrfabian7** [comment]
> You can try from wordpress core setting that what will be the default user role. It might work.

Yes, I understand that this is how it works now, but I want to select a custom user role per form
