### ISSUE TITLE
Jet Woo Builder - Full width can't be set

### ISSUE THREAD

**Issue by Bawoosch** [CrocoBlock/suggestions#1999]
Please add the possibility to set all Jet Woo Templates to "full width". It's not possible for "product" and "category" pages when using the Elementor "hello" theme.

Maybe check out this Plugin which can do the trick:
https://codecanyon.net/item/woocommerce-page-builder-for-elementor/23339868

Thanks in advance.

**Comment by Floydtm** [comment]
You can configure this in the plugin. If you have any problems with this please contact our support team. They will help you!

**Comment by Bawoosch** [comment]
I contacted the support team and they send me here. I'm really upset about this unprofessional answer!
I saw other people describing this problem which you couldn't solve yet and nobody from the crocoblock team ever replied in the FB Group

**Comment by Floydtm** [comment]
Sorry. Maybe the guys didn't understand your question the first time. You can change the settings of the template in the product itself https://prnt.sc/uxswxt However, I want to say that a lot depends on the theme you are using. The jetwoobuilder plugin itself creates a template and inserts it into the page. But we have no effect on the width of the page itself.

**Comment by Bawoosch** [comment]
Okay, i'm sorry. Partly my mistake. Yes, it is possible for the "products" as you say. But it isn't possible for the "category" pages.

**Comment by Floydtm** [comment]
https://prnt.sc/uxtaur make these settings for the shop page Let me know if this helps

**Comment by Bawoosch** [comment]
I just tried it out. Unfortunately, it isn't working like this. Not on the "shop" page and also not on the "categories".

**Comment by Bawoosch** [comment]
I can do the trick with this little Code: 

`.site-header, body:not([class*=elementor-page-]) .site-main {
    max-width: 100%;
    padding-left:0px;
    padding-right: 0px;
}`

But I would prefer to have it natively out of the box to be fail-safe for future updates. (And also for a user who doesn't know how to do it)

**Comment by Floydtm** [comment]
I understand that this is important to you. I checked this again and everything works correctly. However, I do not exclude that our sites are configured differently and I do not know all your settings. Therefore, I sent you to the support team, they will definitely help you. I'm glad you set up your store.

**Comment by ingramleedy** [comment]
@Bawoosch I tried you CSS code without any luck. Is there a trick or other method to get the Hello theme to go full-width?

**Comment by ingramleedy** [comment]
Needed the !important or fix the ordering of css,

`.site-header, body:not([class*=elementor-page-]) .site-main {
	max-width: 100% !important; 
	padding-left:0px; 
	padding-right: 0px; 
}`

**Comment by tizum** [comment]
+1 Please Add this Feature

I need to set my new Single products page to full width on elementor.

![image](https://user-images.githubusercontent.com/6773491/152668500-35a9c891-f46f-4ced-a365-714f0a236d38.png)
This category link that is automatically popping up is making me bored

**Comment by x3mp** [comment]
Please just add this feature already! There is no way to simply set a boxed width or full width. Its a basic functionality how is this not implemented yet!?

**Comment by tizum** [comment]
> Please just add this feature already! There is no way to simply set a boxed width or full width. Its a basic functionality how is this not implemented yet!?

I believe that everyone looks for this functionality when falling into this problem.
