### ISSUE TITLE
Автоматическое создание оглавлений на базе заголовков h1-h2-h3 в статьях/записях 

### ISSUE THREAD

**Issue by smoookeee** [Crocoblock/suggestions#20]
Интересует автоматическое создание оглавлений на базе заголовков h1-h2-h3 в статьях и записях wordpress. Для создания Оглавления  или Содержания статьи/записи сейчас нужно подключать сторонние плагины, которые с элементор в основном не дружат, при этом оглавления статей/записей (любых) в вордпрес необходимы для правильного seo . Оглавление должно быть в открытом виде - классические . Cкрытые и выезжающие как у элемент-пэк допустим для seo никакой пользы не несут﻿.
Вот плагин Оглавления/Содержания, как пример: Easy Table of Contents (но он с элементор плохо дружит и его на странице или записи не разместишь в том месте где тебе нужно - встает по дефолту) . у элементор пэк - есть решения - но они кривоватые, лучше за основу брать вышеприведенный бесплатный плагин - он есть в репозитории вордпресс﻿

**Comment by stasonua0** [comment]
Simply put, do you want an analog widget from the Element Pack called Table of Content?
https://elementpack.pro/demo/table-of-content-test-post/

**Comment by CrocoBlock** [comment]
Dear client, 

Thank you for sharing your suggestion with our team,

We have already received the request to add this feature and it is added to our backlog already. 

Also, please, pay attention that we accept feature requests in English only. Please, make sure to submit the requests in English in the future to let all the community members understand what's needed and prevent duplicated entries. 

Best regards from CrocoBlock team

Здравствуйте, 

Спасибо за предложение, 

Наша команда уже внесла его в беклог. 

Пожалуйста, обратите внимание, что в данном логе рекоммендуется оформлять запросы на английском языке, т.к. для тех членов сообщества, кто не владеет русским, важно понимать о чем речь, чтоб не дублировать запросы в будущем. 

Спасибо за понимание.

С уважением, команда CrocoBlock

**Comment by stasonua0** [comment]
Обратите внимание, что автор того поста не я, я просто оставил комментарий
и это сделал на английском)))

чт, 21 февр. 2019 г. в 17:19, CrocoBlock <notifications@github.com>:

**Comment by alriksson** [comment]
+1 for TOC and +1 for keeping the threads in English!

**Comment by alriksson** [comment]
> Interested in the automatic creation of tables of contents based on h1-h2-h3 headings in wordpress articles and entries. To create a Table of Contents or Content of an article / entry, it is now necessary to connect third-party plug-ins, which are mostly not friendly with Elementors, while the contents of articles / entries (any) in WordPress are necessary for proper seo. Table of contents should be in clear form - classic. Hidden and traveling like an element pack, let's say for seo do not carry any good. 
> Here is the Table of Contents / Contents plugin, as an example: Easy Table of Contents (but it’s not good friends with the elementary and cannot be placed on the page or the record in the place where you need it - it defaults). At elementary puck - there are solutions - but they are crooked, it is better to take the above free plugin as a basis - it is in the WordPress repository

Google translated:

Interested in the automatic creation of tables of contents based on h1-h2-h3 headings in wordpress articles and entries. To create a Table of Contents or Content of an article / entry, it is now necessary to connect third-party plug-ins, which are mostly not friendly with Elementors, while the contents of articles / entries (any) in WordPress are necessary for proper seo. Table of contents should be in clear form - classic. Hidden and traveling like an element pack, let's say for seo do not carry any good. 
Here is the Table of Contents / Contents plugin, as an example: Easy Table of Contents (but it’s not good friends with the elementary and cannot be placed on the page or the record in the place where you need it - it defaults). At elementary puck - there are solutions - but they are crooked, it is better to take the above free plugin as a basis - it is in the WordPress repository﻿

**Comment by alriksson** [comment]
> Интересует автоматическое создание оглавлений на базе заголовков h1-h2-h3 в статьях и записях wordpress. Для создания Оглавления или Содержания статьи/записи сейчас нужно подключать сторонние плагины, которые с элементор в основном не дружат, при этом оглавления статей/записей (любых) в вордпрес необходимы для правильного seo . Оглавление должно быть в открытом виде - классические . Cкрытые и выезжающие как у элемент-пэк допустим для seo никакой пользы не несут﻿.
> Вот плагин Оглавления/Содержания, как пример: Easy Table of Contents (но он с элементор плохо дружит и его на странице или записи не разместишь в том месте где тебе нужно - встает по дефолту) . у элементор пэк - есть решения - но они кривоватые, лучше за основу брать вышеприведенный бесплатный плагин - он есть в репозитории вордпресс

**Google translated:**
Interested in the automatic creation of tables of contents based on h1-h2-h3 headings in wordpress articles and entries. To create a Table of Contents or Content of an article / entry, it is now necessary to connect third-party plug-ins, which are mostly not friendly with Elementors, while the contents of articles / entries (any) in WordPress are necessary for proper seo. Table of contents should be in clear form - classic. Hidden and traveling like an element pack, let's say for seo do not carry any good. 

Here is the Table of Contents / Contents plugin, as an example: Easy Table of Contents (but it’s not good friends with the elementary and cannot be placed on the page or the record in the place where you need it - it defaults). At elementary puck - there are solutions - but they are crooked, it is better to take the above free plugin as a basis - it is in the WordPress repository﻿

**Comment by itolimp** [comment]
+1 for TOC

**Comment by smoookeee** [comment]
Also there would be a huge advantage if there will be the possibility to edit h1-h2-h3 manualy in TOC plagin. For example: you have long h1 in article and you want to stay it long there  but you need to make h1-h2-h3 shorter on the top of the page in toc-plagin without changes in the body of the article. That wold be a great plus to it.

**Comment by itolimp** [comment]
https://github.com/elementor/elementor/issues/5171


https://github.com/dbjpanda/kb-elementor Hi developers, you can see this plugin also

**Comment by dbjpanda** [comment]
@smoookeee Thanks for the idea. I am going to work on this feature. #https://github.com/dbjpanda/kb-elementor/issues/18

**Comment by kaskad88** [comment]
Thanks for your feedback. We currently do not plan to do this.
