### ISSUE TITLE
Booking Fhorm from jet engine

### ISSUE THREAD

**Issue by Biblothecaire** [CrocoBlock/suggestions#200]
Hi,

The 1.4 fix the probleme for sending, thanks for your work ! 👍 

We need one other think that the elementor contact form offers your don't have in jet engine contact form :  **The ability to redirect to another page after form validation (/ thanks /)**

This is important in order to track goals with google analytics

In elementor the function is available from the form via
Action after sending = redirection = Redirect to = / thanks (for example)

**Comment by Floydtm** [comment]
Hi! 
You can set up a redirect in the booking form settings. But for this you need to add some code to your theme. 

For example:

1. http://prntscr.com/nfqx3d 

2. paste this code into your theme

add_action ('jet-engine-booking/redirect_page', 'redirect_page');
function redirect_page () {
wp_redirect ('https://wordpress.org/');
exit;
   
}
