### ISSUE TITLE
Jet Woo Builder: Full width isn't working

### ISSUE THREAD

**Issue by Bawoosch** [CrocoBlock/suggestions#2000]
Please add the possibility to set all Jet Woo Templates to "full width". It's not possible for "product" and "category" pages when using the Elementor "hello" theme.

Maybe check out this Plugin which can do the trick:
https://codecanyon.net/item/woocommerce-page-builder-for-elementor/23339868

Thanks in advance.

**Comment by Floydtm** [comment]
I am closing this because there is a response in the previous request #1999

**Comment by Bawoosch** [comment]
But the response wasn't correct, so i had to open another one to report the bug! As you described it isn't possible. So it's a bug which needs to be solved.
