### ISSUE TITLE
I would like to see this functionality in jet engine forms

### ISSUE THREAD

**Issue by EvgenDoman** [CrocoBlock/suggestions#2003]
here is the link where the example is
https://codecanyon.net/item/dhe-form-wordpress-form-builder-with-elementor/23946043

**Comment by moxet** [comment]
What exactly you are looking for, 90% are already covered

**Comment by EvgenDoman** [comment]
what would be visually possible to make a form that is very convenient!here is a video example
https://www.youtube.com/watch?v=YSfuKljEsJo&list=PLpGoS1NMApN-8l9YJ_ZMkpY_oiuf3N9K2

**Comment by Floydtm** [comment]
@EvgenDoman, hi! I understood what you need. However, now we will not be able to implement it. Perhaps we will reconsider this issue in the future
