### ISSUE TITLE
Loading more buggy 

### ISSUE THREAD

**Issue by neosaveme-zz** [CrocoBlock/suggestions#2008]
hello , 

Clean install wordpress + **jetengine** [all lastest versions]

in post grid ,  loading more goes directly to the bottom of the posts 

I took care to check in several installations , always the same behavior

**it goes directly to the bottom of the posts**

very very very annoying I don't understand what is happening...

I was forced and obliged to use another plugin  **[extra post](https://shop.namogo.com/elementor-extras/widgets/posts/)**

can you see what's going on in your code and maybe update it and force the rules ? elementor 3.0 conflits maybe ? 

can you also take inspiration from what is already doing by **[extra post](https://shop.namogo.com/elementor-extras/widgets/posts/)** ??

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know.
