### ISSUE TITLE
JetElements Advanced Google Maps Fails to Load Location(s)

### ISSUE THREAD

**Issue by bowmandesign** [CrocoBlock/suggestions#2009]
**Describe the bug**
Crocoblock JetElements Advanced Google Maps fails to display maps, showing the error, "No Locations Found".

The issue is caused by only using one API key to make two different requests to two different Google APIs. 

**Client Side Requests** (_loading the map_ with **Maps JavaScript API**) and 
**Server Side Requests** (_lat/long address lookups_ with **Geocoding API**).

**Client Side Requests** for the **Maps JavaScript API** are compatible only with _HTTP referrer restrictions_, while
**Server Side Requests** for the  **Geocoding API** are only compatible with IP restrictions.

It is **important** for the user to restrict access to their Google Map API keys and it is recommended by Google.

The goal would be to empower Crocoblock users to add two API keys for Google Maps Integration:
**API Key 1:** **Maps JavaScript API** restricting use via HTTP referrers.
**API Key 2:** **Geocoding API** restricting use via IP addresses.

Here is a chart showing what restrictions each Google API requires:
( Crocoblock users require both **Maps JavaScript API** & **Geocoding API**)
https://developers.google.com/maps/faq#keysystem

Maps JavaScript API = HTTP referrer restrictions
Geocoding API web service requests (and all web service requests) = IP restrictions

**To Reproduce**
1. Create Google Map Project at https://console.cloud.google.com/
2. Create API Key with HTTP referrer restrictions
3. Restrict API to Geocoding API & Maps JavaScript API
4. Navigate to wp-admin/crocoblock/JetElements/Integrations
5. Enter Google Map API key
6. Create page and add the Crocoblock/JetElements/Advanced Google Map Widget
7. Add a location via coordinates or address
8. Publish
9. Map intermittently fails when Geocoding API is called by JetElements Advanced Google Maps
10. ERROR: No locations can be found.

**Expected behavior**
1. Add the ability to have multiple API keys for Google Map Integration, or at least 2 API Keys.
2. Maps display correctly.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
With only 1 API Key for integrations, adding HTTP referrer restrictions will cause Geocoding API requests not to work, and adding IP restrictions will cause the map not to load.

**Comment by bowmandesign** [comment]
Hi Crocoblock,

First, thank you for all that you do. You have created a great framework!

I was hoping to learn if there is an ETA on fixing this bug? 

I would like to be able to successfully restrict refers via HTTP for Google Maps JavaScript API and restrict refers via IP address for Google Geocoding API web service requests. Both APIs are used by JetElements Advanced Google Maps.

HTTP restrictions only work with Google Maps JavaScript API.
IP restrictions only work with Google Geocoding API web service requests.

Meeting this Google requirement is currently not possible with only one API key input integration provided by JetElements.

Once I can restrict both with two or more API key options integrated into the JetElements UI and JetElements Advanced Google Maps, using Crocoblock JetElements Advanced Google Maps would be much easier and safer.

Thank you again, your Framework has opened up so many possibilities all within one solution.

Best regards,
Bill

**Comment by bowmandesign** [comment]
Hello Team Crocoblock,

Thank you again for all that you do, you have created a great framework.

Today, 11.10.20, I saw your 2.5.0 update for JetElements.

Looks like this ticket, #2009, did not make it in yet.

I know you have a lot on your plate, but was hoping for an ETA on this issue I opened a month ago.

It would be great to be able to use your Advanced Google Maps add-on and successfully restrict refers.

Thanks again,

**Comment by bowmandesign** [comment]
Hi Team Crocoblock,

Thank you for all that you do, amazing work.

I was a bit disappointed this issue was not addressed in your last few updates. 

I understand your current focus on CCT, but this issue is now close to 60 days old.

Is there a chance you could provide me an ETA for the solution? 

In absence of a fix, I am close to the time when I will need to find another secure Google map solution.

**Comment by bowmandesign** [comment]
It would be great to have any communication from @Crocoblock on this issue, I see more issues coming in regarding the same topic. #2577

**Comment by rtpHarry** [comment]
Keen to see an update on this as well. 

Having one key for server side requests and client side requests makes the feature unusable in its current state. 

The only option is to use the unrestricted key which can be stolen and used by anyone then, resulting in thousands of £ potentially appearing on your Google Maps API bill.

**Comment by kimradford** [comment]
Any updates on this issue?

**Comment by unstopp** [comment]
I have the same issue in May 2022. Worked before some updates. Not sure what happened but I will soon change the widget, this is unusable

**Comment by andretoldo** [comment]
It works at some older sites but I can't configure it into new ones =(

**Comment by rtpHarry** [comment]
Woohoo 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1038062/170598442-0aff182e-cba5-4713-8104-5f0ce36a2a83.png">

#5417

**Comment by MjHead** [comment]
Added with 2.6.7 update

**Comment by unstopp** [comment]
Did you even test before closing the thread? As of 13rd Jan 2023, adding the default map and not modifying anything is still not visible

**Comment by Sapper-Morton** [comment]
Again with this issue "API keys with referer restrictions cannot be used with this API."
Still getting the error. I really can't understand why JetEngine requires no restrictions on the API. No restrictions opens ways to abuse the keys.

**Comment by Studio-33-nl** [comment]
It's 11 December 2024, the original post was on 13 October 2020. How is this still an issue? Why advertise with a advanced map widget, when it's not working properly? These malicious practices makes me hate crocoblock more and more. This is not the first time they do this.

**Comment by zavants** [comment]
Same issue here, is not solve

**Comment by Crocoblock** [comment]
https://crocoblock.com/knowledge-base/jetengine/jetengine-choosing-different-map-providers-for-map-listings/#placing-map-listing-onto-a-gutenbergbuilt-page:~:text=Separate%20Geocoding%20API,key%E2%80%9D%20is%20selected%3B

**Comment by RomainLaf** [comment]
So basically we need to create API key with **no Application restrictions** and **no API restrictions** to be able to use it with JetElement ? 
It's the only configuration that was working for me :

![Screenshot-Arc-09-01-11 47](https://github.com/user-attachments/assets/7ed92e6b-7840-4ea2-b571-a6f89f503142)

**Comment by e-cubed** [comment]
+1 This is exactly the same for me. Though this is not a secure approach as others could potentially use the API key? 

> So basically we need to create API key with **no Application restrictions** and **no API restrictions** to be able to use it with JetElement ? It's the only configuration that was working for me :
> 
> ![Screenshot-Arc-09-01-11 47](https://github.com/user-attachments/assets/7ed92e6b-7840-4ea2-b571-a6f89f503142)

**Comment by apatsidis123** [comment]
There is not any solution for this yet after 5 years? Why just can't we use the domain restriction so only the requests from our domain be accepted, this would be safe for all of us. 

Thought the request looks "Closed", can we restrict our keys or not?

regards

**Comment by JeroenKeijzer** [comment]
Just steal Crocoblock their key and use that, since they don't care to fix this, they can't be bothered if i use their key, right? I mean, it's just in the public domain, so why not use that, right?

**Comment by jtas01** [comment]
March 30, 2025 - this issue is still there.

**Comment by apatsidis123** [comment]
if i set on the restrictions allow list:

https://mydomain.com/
https://mydomain.com/*
https://www.mydomain.com/
https://www.mydomain.com/*

The front end loads fine, but for the back end when i create the post, on the map meta field when i search for any address regardless what i set i get "no results found" . I guess there is something else that i need to add

i tried https://www.mydomain.com/wp-admin/* but still no, thought the asterisk on the https://www.mydomain.com/* should include the wp-admin page as well but anyway i tried.

I have created a ticket on Crocoblock lets hope they gonna help me.
