### ISSUE TITLE
Jet Element - Posts carousel = does not display well

### ISSUE THREAD

**Issue by Biblothecaire** [CrocoBlock/suggestions#201]
You purpose a post plugin for "related post". 
In normal use it work fine but the "carousel" mode have a little bug :

I choose post number "6" and columns "4"
If i have 4 related article or more in the categorie it work well 
Exemple : https://madagascar-hotels-online.com/hotels/home-the-residence/

BUT, if i have a categorie with only 3 articles, the display fits completely, even the 3 items are almost invisible on all device.
Exemple with 3 articles catégories : 
- https://madagascar-hotels-online.com/hotels/floridas-eden-ambilobe/

**Comment by Floydtm** [comment]
@Biblothecaire update the jetelements plugin and check the work of the posts widget

**Comment by kaskad88** [comment]
Fixed in JetElements 1.15.13
