### ISSUE TITLE
'Team Member' widget link should be target _blank rather than new window

### ISSUE THREAD

**Issue by raroDev** [CrocoBlock/suggestions#2011]
Browser is blocking link, when 'open in new window' is set. On button with this option on there is no problem.
https://www.loom.com/share/eecde8906e4c42169ac86e7d75b8c4ad

**Comment by Floydtm** [comment]
We have tested this and it seems to work well. However, our sites may be configured differently. To solve this problem, you need to contact our support team and provide access to the site
