### ISSUE TITLE
Alert when appointment has been made

### ISSUE THREAD

**Issue by wtkruythoff** [CrocoBlock/suggestions#2013]
Is it possible to add an alert in JetAppointment to know when a client has made an appointment. And is it possible to connect the appointments in for example Outlook Calendar and be able to export as for example a csv file.

**Comment by Floydtm** [comment]
Right now you can add notification and receive an email when an item is booked on the site. Also in the form, you can use a web hook and write data from the form to the calendar. https://crocoblock.com/knowledge-base/articles/jetengine-booking-form-send-email-notification-overview/
