### ISSUE TITLE
Product Bundles add to cart button does not work when using jetwoo templates and Woocommerce product bundles

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#2015]
https://fenwickhill.com.au/atest-bundled-product/

**the Product Bundles add to cart button does not work 🙁**

I've asked the product bundles folks and they say to ask you...

> Hi there Peter,
> Thanks for getting in touch!
> Taking a look at the product link you sent us, I can see that you are using AJAX Add to cart buttons in the single product page: https://a.cl.ly/geuqoKLQ. We've seen similar issues in the past with this type of Add to cart buttons and Product Bundles.
> By default, WooCommerce supports AJAX functionality for Add to Cart buttons in Shop Archives. Making AJAX-enabled add-to-cart buttons work correctly in single-product pages requires a bit more work -- most themes/plugins that use AJAX Add to Cart buttons fail to post all form contents when these buttons are clicked. 
> 
> As far as I understand, these buttons are managed by the JetWooBuilder For Elementor extension you are currently using -- since the issue is resolved when you disable this extension. With that said, the best way to proceed with this is to bring this issue to the attention of their support team. Keep in mind that most plugin developers who advertize WooCommerce support are committed to fixing compatibility issues like this one -- <ins>_however, the only way to find out is by reaching out to them. In case they are not able to resolve this, then it is possible that they can help you disable AJAX functionality on specific pages -- for example, for Product Bundle pages._ </ins>
> 
> Does this help?
> Cheers,
> Maria
> Support Engineer

I've disabled the ajax add to cart and it still isn't working...

thanks

Peter Williamson
Developer.
peter@t1.co.nz
Skype: t1peter

**Comment by ghost** [comment]
Hi there,
Any Progress/ timeline on fixing this?
This is holding up makeing this site live...

Thanks

**Comment by UraraReika** [comment]
Hi @pumpCMS !

Taking into account the specifics of a grouped product and how it is formed, there is no way to add it to the cart using an ajax request on the product page. 

We apologize for the wait and the fact that we did not take it into account right away. In the next update, there will be a condition that will allow you to add a grouped product to the cart as before.

**Comment by ghost** [comment]
Great! How long before the next update, we need this for the site to go live!
