### ISSUE TITLE
JetEngine - Listing Grid Slider - Items to show and scroll improvement

### ISSUE THREAD

**Issue by viabit-dev** [CrocoBlock/suggestions#2018]
This kind of mobile navigation is widely used in google, youtube, facebook, instagram, etc (especially to show the horizontal list of stories) Examples:
![youtube](https://user-images.githubusercontent.com/57798462/96108012-65001e80-0edd-11eb-9957-25630a73b474.gif)
![facebook](https://user-images.githubusercontent.com/57798462/96108027-6a5d6900-0edd-11eb-944d-cd863f5a2ea0.gif)

If we activate the listing grid slider functionality, a similar behavior can be achieved. But more uncomfortable and less intuitive because only shows a whole number of items and the scroll is repositioned and centered everytime we slide with the finger.

I think that allowing to show halves of items (2 and a half for example) and that when sliding the items will not be repositioned / centered, an identical behavior could be achieved.

I looking this feature for show posts on a digital newspaper.

**Comment by petranca** [comment]
Maybe a few more settings, like vertical animation and so on... :-)
https://swiperjs.com/demos/

**Comment by dsmoina** [comment]
Great to see someone requests this feature! I run a news blog that also features video and this would be a welcome addition to the Listing Grid.

**Comment by viabit-dev** [comment]
I think it is the best way to browse entries for mobile designs

**Comment by MjHead** [comment]
Добавить возможность включать обычный CSS скролл для листинг грида. Тут 2 варианта:
1. Сделать такую настройку глобально с возможностью переключать для телефонов и планшетов.
2. Сделать свичер, что-то вроде Scroll on mobile

плюс под эту логику наверное надо сдлеать возможность задавать статическую ширину для колонок листинга вместо кол-ва колонок.

**Comment by viabit-dev** [comment]
Hi, thanks for add this feature on 2.6.0.

But I don't know how archieve this new behavior of the listing grid. ¿Can someone translate MjHead message from russian to english? I think he explains something important about this, but I dont understant correctly the google translator traduction.
