### ISSUE TITLE
JetEngine: lazyload listing grid and a popup listing

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#2021]
Lazyload for the listing grid is a very good thing! But I noticed that when lazyLoad is enabled for the listing grid, the popup listing doesn't work. The popup just doesn't open.

**Comment by MjHead** [comment]
@serg-pervushin You need to set page with lazy loaded listing into display conditions of popup - http://prntscr.com/v0fnqa. It shoul work after this. If you using Listing grid widget to show CCT items list - it will not work correctly at this moment we'll fix this with JetEngine 2.5.3 update

**Comment by smiljimenez** [comment]
@MjHead @Crocoblock This issue is still present after four years. I have a CCT grid that loads lazily and a button linked to a JetPopUp modal. It would be great if you could follow up on this. Thanks!

**Comment by Crocoblock** [comment]
Hi @smiljimenez 
We've tried reproducing your issue, and everything works fine. Maybe you're not using conditions for popups, check this again. If the issue still exists, please, contact [our support team](https://crocoblock.com/help-center) regarding this case, and create a ticket including access details for the site where the issue occurred to ensure we can help you.
