### ISSUE TITLE
JetEngine: Assign meta boxes conditionally

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#2022]
If we now want assign metaboxes to taxonomies or pages, we can assign them to specifically types or exclude them specifically.

But if my customer constantly adds/removes pages or taxonomies I have to reassign them each time in the meta box.

One way to fix this is to assign the meta box conditionally.

For example like this:

Meta Box For: Post
Enable Post Types: Pages
Conditional: None / Direct Child Of / Any Child Of /
Specific Posts: Service

Now the meta box will be automatically added to all child pages of  "Service", without me having to assign this each time. The same should work with taxonomies.

**This would be a light version only and would be enough for the beginning. But of course it would be great if we could control it in the future in the same way as it is currently possible with ACF via "Location Rules".**

https://s3.amazonaws.com/docs-content.theme.co/basics/extensions/acf-pro/images/acf-pro-07.png

**Comment by MjHead** [comment]
https://github.com/Crocoblock/suggestions/issues/4234

**Comment by mangandini** [comment]
While this issue has been closed, actually the functionality was not implemented, there is no option to assign a meta box conditionally on Parents / Childs

@MjHead do you know if this is on the roadmap?
