### ISSUE TITLE
Add option to Change Cart and checkout labels in Jetwoobuilder

### ISSUE THREAD

**Issue by RoyRobles** [CrocoBlock/suggestions#2026]
Hello
I made a cart and checkout page with Jetwoobuilder but sadly the labels are in English. Woocommerce and WordPress are in Spanish, but all labels in Cart and checkout pages are in English, so Crocoblock Jet Woo Builder is useless if you can only have Labels in English. 

You should add the option to edit the labels or the plugin should use the language of the woocommerce. 

I hope you can fix it. 

Regards 

![FB_IMG_1602825730470](https://user-images.githubusercontent.com/72961267/96216576-497d2e00-0f46-11eb-97f2-9b2098e6da0c.jpg)

**Comment by Floydtm** [comment]
We will add this in the next release. Keep for updates. Thank you!
