### ISSUE TITLE
Product Add-ons for WooCommerce styling.

### ISSUE THREAD

**Issue by YoavBco** [CrocoBlock/suggestions#2030]
Hey i was wondering if there's an option to add styling option for "Product Add-ons for Woocommerce" plugin classes: Checkboxes, Headers and etc.. via Elementor & JetWooBuilder. 
For better customer experience and  more beautiful Single product templates.
![github1](https://user-images.githubusercontent.com/72974968/96250274-42423880-0fb7-11eb-9bc9-50b2befaf603.jpg)

**Comment by Floydtm** [comment]
Hello! I understand that this is very important to you, but we cannot add additional options for a third party plugin. Thanks!

**Comment by YoavBco** [comment]
Hey @Floydtm , Its an official WooCommerce plugin. you've made JetWooBuilder didnt ya?

**Comment by Floydtm** [comment]
Our development team made the jetwoobuilder plugin. However, your request is for a different plugin. I think you need to contact the developers who made it. Thanks!
