### ISSUE TITLE
it would be great to set duration of a service to 15 minutos. The "duration" select menu starts at 30minutes

### ISSUE THREAD

**Issue by rodolfofloresbravo** [CrocoBlock/suggestions#2033]
It would be even better is i can set the duration to a custom value, like 20 minutes, as example.

**Comment by ciprianpentelescu** [comment]
Or even better, it we could set the number of minutes manually instead of choosing from a predefined list. Like setting 5 would make all of the intervals 5 minutes.

**Comment by MakhonkoDenis** [comment]
Issue is duplicate. https://github.com/Crocoblock/suggestions/issues/1838
This feature will appear in the next release.
