### ISSUE TITLE
JetWooBuilder Text-Domains

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#2036]
Hello dear crocoblock team

Some text-domains has to be changed from "jet-woo-builder" to "woocommerce". For an example, the Text "Additional information" here (jet-woo-builder\templates\jet-checkout-additional-form\global\index.php) shoud better have textdomain "woocommerce". Why to change? Because this is a built in string which is also present in woocommerce core and has already been translated to multiple languages.

Same for the text "Your Order" and "Ship to a different address?":
jet-woo-builder\templates\jet-checkout-order-review\global\index.php
jet-woo-builder\templates\jet-checkout-shipping-form\global\index.php

**Comment by Floydtm** [comment]
Your request will be added in the next plugin releases. Thanks!
