### ISSUE TITLE
Two pagination widgets at the same time

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#2037]
I created a listing and i needed the pagination to be shown above and below it, but it seems it doesn't work with 2 pagination widgets at the same time on page.
I found a workaround, but maybe for the future you will fix this bug.
My workaround:

```
<script>
//add 1 pagination + 1 html widget
//give them ids as below
var $=jQuery.noConflict();

$(document).ready(function(){
    
    $('#pagination').ready(function(){
        var custhtml=$('#pagination').clone(true);
        $('#customhtml').html(custhtml); 
    }); 
    
    $("body").on('DOMSubtreeModified', "#pagination", function() {
         var custhtml=$('#pagination').clone(true);
        $('#customhtml').html(custhtml); 
    });
    
});

</script>

```

**Comment by Floydtm** [comment]
Hello! We've checked your request and everything is working well. However, our sites can be customized in different ways. Please contact our support team, grant access to the site and we will check it again. Thanks!
