### ISSUE TITLE
Disable redirect on JetSearch 

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#2039]
It would be a nice feature to have, so you are not redirected if hitting {enter} on the field, and the results are shown only in the results area.

**Comment by Rubendj1** [comment]
Thit would be a great addition to JetSearch.

**Comment by drakulux** [comment]
+1 for being able to disable the redirect on the search, and possibly setting a redirect link instead of the default search page.

**Comment by Crocoblock** [comment]
was added in version 3.3.0

**Comment by klmbr** [comment]
Great answer... could you tell us where is the option to deactivate the redirect to result page please? Thank you.

**Comment by SolunaCG** [comment]
> Great answer... could you tell us where is the option to deactivate the redirect to result page please? Thank you.

![jetengine_disable_redirect_on_enter](https://github.com/Crocoblock/suggestions/assets/114682524/b261fd52-b1af-4839-a9ed-5c390b7ac9c4)

When you click on the "Ajax Search" widget, you can find it here :-)
