### ISSUE TITLE
Design Template for Health Professionals and Location Based eg Farmers Markets

### ISSUE THREAD

**Issue by Chrisd23680** [CrocoBlock/suggestions#2041]
I would like to see two new Design Templates.

The first is for Health Professionals such as Psychiatrists, Counsellors, Doctors.

The second for a locations based Template for business such as Wineries and Farmers Markets.

I am also fine with contributing some money towards these being developed if that helps.

Fingers crossed
Chris

**Comment by Floydtm** [comment]
Hello! I conveyed your wish to the management. Thanks!
