### ISSUE TITLE
JetAppointments ability to have different time-slot time periods for different appointments

### ISSUE THREAD

**Issue by Schluck** [CrocoBlock/suggestions#2050]
It would be very helpful to be able to set up different appointments to have different time-slot lengths. Many companies offer multiple services with each service taking a different amount of time. Because of this, being able to set the calendar up so that depending on the service that you select a different appointment length is set would be great.

**Comment by Floydtm** [comment]
@Schluck, hi! Right now, you can use a custom schedule for your services. https://prnt.sc/v4mrdv
