### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by sochadesign** [CrocoBlock/suggestions#2052]
I'using JetProductGallery 1.1.5 and it works fine, but I'm missing one important feature. After you click on a single product image the lightbox opens for the zoom view. There are no arrows to view the next or previous product images. Instead of that you need to close the lightbox, select another product image and then open the lightbox again.

Please have a lokk at: https://sochadesign.com/produkt/straight-line-red-15-6/
please open the lightbox - there are no arrows

Next example is what we need:
https://www.strathberry.com/products/biscuit-bag-maze-raspberry-burgundy#&gid=1&pid=1

Can this features been added?

**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by UraraReika** [comment]
This functionality exist in our plugin. The issue you faced if conflict of JetProductGallery lightbox and Elementor build in lightbox. Just disable Elementor lightbox like this - https://tppr.me/LCqfU
