### ISSUE TITLE
JetSearch add possibility search by the product attributes

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#2056]
JetSearch add possibility search by the product attributes
https://prnt.sc/v3sbbo
https://prnt.sc/v3sbsg

**Comment by enuzzo** [comment]
I endorse this request. That's fundamental to be able to search custom attributes and not terms of attributes.
Example: we're setting up a shoes store. Product name is "Air Jordan", product attribute "Brand" will be "Adidas" > a lot of people will search "Adidas" in the Ajax Search field. The missing of this feature makes the whole widget pointless, although is a great and fast search plugin.
