### ISSUE TITLE
JetEngine Forms conditional logic ability to compare the metafield value and the printed text in the text field in the form

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#2057]
JetEngine Forms conditional logic ability to compare the metafield value and the printed text in the text field in the form
I have the metafield for the codes in the single of the CPT. I want to add possibility to check if the user writes the right code in the form on the current single, than he can submit the form. I've added the hidden field to the form and get the field from the metafield of the post. Than I add the conditional logic and want to show the submit button if the value of the text filed in the form matches the value in the post's metafield. But for now it is can't be done. Could you add such a possibility?

**Comment by kaskad88** [comment]
Added to the next version
