### ISSUE TITLE
Add Dynamic Function in the Dynamic Field Widget so that we can use Callback Filter field output to filter the numbers Example: 100,000 Fcfa money (Central Africa)

### ISSUE THREAD

**Issue by sixmanstone** [CrocoBlock/suggestions#2063]
Add Dynamic Function
in the Dynamic Field Widget so that we can use Callback Filter field output to filter the numbers Example: 100,000 Fcfa money (Central Africa)

![image](https://user-images.githubusercontent.com/73070227/96908729-f13db300-1494-11eb-81fc-09fa3a5f4264.png)

![image](https://user-images.githubusercontent.com/73070227/96908809-0ca8be00-1495-11eb-8df4-e7a19c352c07.png)

**Comment by MjHead** [comment]
@kaskad88 Добавить в Динамические функции настройки для форматирования выводимого числа (thousands separator and decimals separator)

**Comment by sixmanstone** [comment]
Effectively, we will need a thousands separator and a decimal separator

**Comment by sixmanstone** [comment]
Thanks for adding this option, you are awesome.

**Comment by sixmanstone** [comment]
Thanks for adding this option, you are awesome.
