### ISSUE TITLE
JetSmartFilters and JetElements show nothing on some Hosting Providers

### ISSUE THREAD

**Issue by alexander-pankart** [CrocoBlock/suggestions#2071]
JetSmartFilters and JetElements show nothing.

Hello, I have already noticed with 2 hosting providers that some widgets and functions are not displayed.

The Instagram Widget shows the following: "Posts not found". I entered #cats there (there are plenty of them on Instagram).

With JetSmartFilters all filtered elements disappear. On the staging website (Other Hosting) everything works fine. Nothing has been changed either.

Which settings could be checked or what could be the reason that the queries are not executed?

Hosting on which it does not work: SiteGround (which is actually even recommended by Crocoblock).
The PHP Memory limit is 756MB (So by far more than needed)

What information can I give you so you can help me?

**Comment by Floydtm** [comment]
@alexander-pankart, hi! To solve this problem, you need to contact our support team. Provide access to your site. After that, our developers will see what is wrong with your site. Thanks!
