### ISSUE TITLE
No selection option in dynamic user value selection in default value

### ISSUE THREAD

**Issue by P258tiwari** [CrocoBlock/suggestions#2072]
**Describe the bug**
To set dynamic default value in form for user is not available. 
![Screenshot (17)](https://user-images.githubusercontent.com/64008801/97053052-cab86e80-159f-11eb-93cd-31ae57d15384.png)

**To Reproduce**
1. Go to form create
2. Click on add any field
3. go to default and click dynamic button
4. select source user
5. bug for not getting value field same as image

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Microsoft Edge, Chrome

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
