### ISSUE TITLE
Add possibility to show product's description and meta fields, attributes directly in Products Grid/List widgets

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#2073]
Add possibility to show product's description and meta fields, attributes directly in Products Grid/List widgets

**Comment by UraraReika** [comment]
You can do it by overriding plugin template in your child theme.

First of all you need to copy folder of widget which you want to override. Go to `wp-content/plugins/jet-woo-builder/templates`, copy` jet-woo-products` for Products Grid widget,` jet-woo-products-list` for Products List widget. Then paste it in your child theme or theme, whatever you use. You need paste it in the jet-woo-bilder folder, which you must create in the theme root folder, https://prnt.sc/v6wrvp like this, https://prnt.sc/v6ws71. Then pick the file where you want to add functionality and the other files shuild be deleted. Open this file in editor and do whatever you want. 

https://prnt.sc/v6wu3l example how to echo products attributes.
