### ISSUE TITLE
Feature request: Add CSS field to Jetwoo templates

### ISSUE THREAD

**Issue by getwebcare** [CrocoBlock/suggestions#2074]
Is it possible to add css boxes for new checkout, cart, shop, thank you page types?
Currently I need to go to pages to edit the checkout page to add css and then go to checkout template to edit design.

![checkout](https://user-images.githubusercontent.com/32192439/97117932-a67b9f80-170f-11eb-89e4-0cc2f3d826f6.png)

**Comment by Floydtm** [comment]
We do not plan to do this yet. Now our developers are busy with more important tasks. Thank you!
