### ISSUE TITLE
Pagination Widget Error - Not working

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#2076]
If i put 2 pagination widgets on the same page they don't work. (when using the reload page option)

I made a demo page for you to test the error:

https://miorganics.ro/debug/

I put one widget above, and one blow the listing (it doesn't really matter where you put them, when they are 2 they cancel each other).

How to see the error in action:
Change the page, for example to 3.
Try to change it again to 2, or 4.  (it's always stuck to the previous page you clicked)

**Comment by ciprianpentelescu** [comment]
Until the error is fixed you can use my workaround:
you add only one pagination widget, and a html widget, inside the html you can paste the following code, then you give them IDs as in the code (#pagination for 1st one, #customhtml for the 2nd)
```
<script>

var $=jQuery.noConflict();

$(document).ready(function(){
    
    $('#pagination').ready(function(){
        var custhtml=$('#pagination').clone(true);
        $('#customhtml').html(custhtml); 
    }); 
    
    $("body").on('DOMSubtreeModified', "#pagination", function() {
         var custhtml=$('#pagination').clone(true);
        $('#customhtml').html(custhtml); 
    });
    
});

</script>
```

**Comment by Floydtm** [comment]
Hello! We've checked your request and everything is working well. However, our sites can be customized in different ways. Please contact our support team, grant access to the site and we will check it again. Thanks! 
[pagination.zip](https://github.com/Crocoblock/suggestions/files/5437719/pagination.zip) Have you contacted our support team?

**Comment by ciprianpentelescu** [comment]
Its the 2nd website i encounter the error on, ill contact the support team and grant access. Thank you!
