### ISSUE TITLE
Jet Smart Filters show the number of post found

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2078]
Hello, my customers in various fields of activity often asked me to add how many records were found after filtering - https://prnt.sc/v6wipg. If possible, please add such functionality.

/*Оригинал*/
Здравствуйте, мои заказчики в разных сферах деятельности часто стали просить добавить сколько всего записей было найдено после фильтрации - https://prnt.sc/v6wipg. Если есть возможность, добавьте пожалуйста такой функционал.

**Comment by markobakic-srb** [comment]
@stasonua0 Hello, how did you manage to achieve this? Thanks

**Comment by Floydtm** [comment]
Currently, your case can be implemented using the jetengine plugin https://crocoblock.com/knowledge-base/jetengine/query-results-count-dynamic-tag-for-wordpress/
