### ISSUE TITLE
JetElements Bar Chart Widget Tooltip Design

### ISSUE THREAD

**Issue by joho2020** [CrocoBlock/suggestions#2079]
Bar Chart Widget: In the tooltip, please add a small space between color example and label text
See here:
![image](https://user-images.githubusercontent.com/73476552/97173689-40376100-1791-11eb-8999-42c83c65cc13.png)

Also applies to other charts with tooltips.

**Comment by kaskad88** [comment]
Added in JetElements 2.5.5
