### ISSUE TITLE
JetElements Bar Chart Widget Individual Bar Color templates

### ISSUE THREAD

**Issue by joho2020** [CrocoBlock/suggestions#2080]
Add option for Bar Chart Widget: ability to define specific color templates for a single bar in a series, instead of whole series only

![image](https://user-images.githubusercontent.com/73476552/97173984-b340d780-1791-11eb-902a-c4453286dec0.png)

**Comment by Floydtm** [comment]
We will not do that at the moment. Our developers are busy with more important tasks. Thank you!
