### ISSUE TITLE
JetMenu AuthLinks widget is not udating user status when put in header/before/after templates

### ISSUE THREAD

**Issue by ihslimn** [CrocoBlock/suggestions#2084]
If AuthLinks widget is put to a header/before/after templates of Mega Menu, it will not show the status of the current user properly:
https://prnt.sc/v781ai
(AuthLink on the page shows that the user is logged in, but AuthLinks in above-mentioned templates do not reflect that).

**Comment by ZemezLab** [comment]
v 2.0.7 (added template cache option)https://prnt.sc/v7vcxm
