### ISSUE TITLE
Add the ability to compare post date (or date in custom field) to today's date in query

### ISSUE THREAD

**Issue by bejuland** [Crocoblock/suggestions#209]
Add the ability to compare post date (or date in custom field) to today's date in query.
Would be useful for calendar in list form (previous events, next events)
Also ability to compare to current day, current week, current month, current year would be nice options for event classifications in a list form.

When I asked that the Crocoblock support, they made me add that to my theme functions.php 

add_filter( 'jet-engine/listings/macros-list', '__your_prefix_add_jet_engine_new_marcos' );

function __your_prefix_add_jet_engine_new_marcos( $list ) {
	$list['current_day'] = '__your_prefix_jet_engine_current_day_cb';

	return $list;
}

function __your_prefix_jet_engine_current_day_cb() {
	return mktime( 0, 0, 0, date( 'n' ), date( 'j' ), date( 'Y' ) );
}

And then I was able to use the %current_day% macro in my query (see image below)

It should be integrated in standard in jetengine, since there is already a calendar function, the event listing function would be useful... Thanks !

<img width="369" alt="Capture d’écran 2019-04-23 à 08 16 07" src="https://user-images.githubusercontent.com/49908953/56581238-772c2580-65a2-11e9-915e-8a7cd28d917f.png">

**Comment by johnberkoski** [comment]
+1 for this.  Desired scenario - create a custom Event post type with an Event Date field, then use the date query on the listings grid to filter out past dates e.g. event_date (greater or equal) {now}.

**Comment by MjHead** [comment]
Hi! Sorry for delay with response. You can just use regular words for such cases, for example today, this month, etc. Just set type Date here - http://prntscr.com/oe250m. Also, to make sure you word is "convertible" into timestamp, you can check it here - http://strtotime.onlinephpfunctions.com/ - set your word into time field, press execute and check result, if it shows big number, it works http://prntscr.com/oe2bx3

**Comment by redordev** [comment]
Hi @MjHead ,

So what should i be adding? Urgently trying to get it to work - used strtotime('today') and strtotime('now').... - both not working?


![listing](https://user-images.githubusercontent.com/49266636/68843089-80c5d800-0702-11ea-951f-9531e24eb843.png)

**Comment by Floydtm** [comment]
@redordev, try to do as in the example http://prntscr.com/pwzdu9

**Comment by redordev** [comment]
Hi @Floydtm 

I just tried that one as well and didn't get any results back. My date field is date only - no time. Do you think that affects it?

![no-data](https://user-images.githubusercontent.com/49266636/68907798-0ccc1400-0784-11ea-8783-6239aef53f33.png)
![start-date](https://user-images.githubusercontent.com/49266636/68907799-0d64aa80-0784-11ea-93de-7a3e36622a0f.png)

**Comment by redordev** [comment]
Ah ok if i change to datetime and save as timestamp it works - thanks!

**Comment by OppositeX** [comment]
Hey guys
if I submit a front-end form using a date field with the timestamp option added - my saved date displays 1970 instead of the selected value from the date picker

any work around for that ?any ideas how i can solve this ?

**Comment by Floydtm** [comment]
@OppositeX look at this solution https://gist.github.com/MjHead/66bf31e429f14f9224771f15ccd3b569 replace _date_field with the name of your field from the form

**Comment by OppositeX** [comment]
> @OppositeX look at this solution https://gist.github.com/MjHead/66bf31e429f14f9224771f15ccd3b569 replace _date_field with the name of your field from the form

hey Floydtm !
thank a lot for the quick response!
Unfortunately it didn't work
i am not using booking - just regular CPT with file submission

also my field is "date" rather than "timedate" 

thanks again

**Comment by Floydtm** [comment]
@OppositeX contact our [support](https://crocoblock.com/help-center/). Guys will help you
