### ISSUE TITLE
JetEngine: Taxonomies/Tag created before enabling Menu are not visible in Menu Item.

### ISSUE THREAD

**Issue by pravinlpatel** [CrocoBlock/suggestions#2090]
**Describe the bug**

What I have observed that, Taxonomies/Tag created before enabling Menu are not visible in Menu Item and Taxonomies/Tag created after enabling Menu are visible in menu Item.

**To Reproduce**
1. Install Wordpress along with JetEngine
2. Create few Taxonomies/Tag
3. Go to Appearance -> Menu -> Enable Menu
4.  Create few more Taxonomies/Tag

**Expected behavior**
Taxonomies/Tag created using JetEngine should be available in Menu Item

**Screenshots**

1. Here you can see Taxonomies created after enabling Menu on fresh Wordpress and it is available Menu in items  -> https://snipboard.io/rv1BQX.jpg

2. Here you can see what Taxonomies created before and after -> https://snipboard.io/VQ9pHo.jpg

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Floydtm** [comment]
@pravinlpatel, hi! We checked everything again and everything works correctly. Check these taxonomy options https://prnt.sc/v8h3b7 if they are disabled then taxonomies will not be available in the menu

**Comment by pravinlpatel** [comment]
@Floydtm Those setting are default and enabled.

I am able to discover Taxonomies/Tag which created before enabling Menu from 'Screen Options'. I had to manually select required Taxonomies/Tag from screen options to list them under Menu Items.

Ref: http://prnt.sc/v8m277

Is this default behavior of WordPress or JetEngine? 

Not sure if any future taxonomy terms will be auto inserted in Menu for selected Taxonomy. For example, 'Subject' Taxonomy will have many subject hierarchy in the future.

**Comment by Floydtm** [comment]
@pravinlpatel I cannot call this a bug. Checked your request on two sites and it works well. However, our sites can be customized in different ways. But you can customize the screen potions as you need. I can advise you to contact the support team and provide access to your site. The developer can then look for this problem. However, I think it will be fast because we cannot reproduce the problem on our side. Thanks!

**Comment by pravinlpatel** [comment]
@Floydtm I agree with you. Initially, I contacted support but they were not able to troubleshoot the issue. 

I am closing this thread considering my issue is resolved. Appreciate your help.
