### ISSUE TITLE
Favorite post per user

### ISSUE THREAD

**Issue by Hannah2626** [CrocoBlock/suggestions#2091]
Hi

I have looking for a way to display the list of posts or custom posts that a user has viewed.
You can see the screenshot below where there is an example in another website. It shows the properties that the user has just seen where he has signed in before.
![favorite post on a website example](https://user-images.githubusercontent.com/19798847/97327368-92ee4700-187d-11eb-88b7-d60b00ce5591.png)
I thought that we can do it with a jquery but the support told me that there is no such feature.
I think that a lot of websites have this feature and I was wondering whether you can develop it.
Thanks for letting me know
Best regards
Hannah

**Comment by stasonua0** [comment]
Same way https://github.com/Crocoblock/suggestions/issues/1154
