### ISSUE TITLE
[JET ENGINE] Conditional logic for repeater fields

### ISSUE THREAD

**Issue by FelloDuarte** [CrocoBlock/suggestions#2092]
Hi! thanks for this amazing plugin.
Would be great to have the same conditional logic you added for 2.4 working inside repeater fields. And be conditional between each element of the repeater
I know AFC has this 

thanks!

**Comment by quentinaurat** [comment]
+1

**Comment by Willitbang** [comment]
+1

**Comment by anybany** [comment]
+1

**Comment by frydhogg** [comment]
any update about this?

**Comment by kaskad88** [comment]
It was implemented in JetEngine 3.2.0

**Comment by chitiore** [comment]
Hi @kaskad88, as far as I had noticed, this suggestion hasn't been implemented yet. Or maybe I'm not able to see it. Can you guide me please?

**Comment by Crocoblock** [comment]
@chitiore 
As kaskad88 mentioned earlier, it was added in JetEngine 3.2.0

![Image](https://github.com/user-attachments/assets/71e48e05-542a-459b-8642-6673058d7c88)

If you have some other questions, please get in touch with our support team https://crocoblock.com/help-center

**Comment by chitiore** [comment]
Thanks. To be honest, it’s not intuitive at all. Without your guidance and the screenshot, I would have never figured it out. Have a great day!
