### ISSUE TITLE
JetEngine - Reactive Map Markers  |  Connect listing grid items to interactive map markers 

### ISSUE THREAD

**Issue by travelgu** [CrocoBlock/suggestions#2097]
Hello Crocoblockers, 

A feature request to connect the map markers to the items in the listing grid.  If showing both the Map Listing and Listing Grid, the map markers should bounce or have a hover effect when the user hovers or clicks over the connected item in the listing grid. 

Example Feature - https://theculturetrip.com/europe/united-kingdom/articles/30-stunning-uk-spots-that-feel-like-paradise/ 

Keep up the great work!

**Comment by kaskad88** [comment]
This feature is already available. Use the Listing Settings https://gyazo.com/4f53100858d91b77ee9d373e3825b07b or dynamic tags https://gyazo.com/d9a0f4294d27baeb2cefa29f10914a1c

**Comment by dcunego** [comment]
Hi, @kaskad88 you say feature is already available but i not found bounce effect for marker. Is it possible animate with bounc effect the marker after click? Thanks, regards

**Comment by nimac99** [comment]
This feature is still not available. We are not talking about a popup but a way to highlight the marker itself, for example bouncing, changing color, etc while user hovers over the item in listing grid.
