### ISSUE TITLE
Произвольные шаблоны для категорий товаров 

### ISSUE THREAD

**Issue by ink80** [Crocoblock/suggestions#21]
Было бы здорово. Если бы можно было создавать с помощью джет вубилдер произвольные шаблоны для вывода разных категорий товаров. Сейчас можно сделать кастомный шаблон для вывода категорий товаров, но он к сожалению общий для всех категорий.

**Comment by CrocoBlock** [comment]
Dear customer, 

Please, tell have you tried setting the archive templates from a specific category using JetThemeCore functionality? http://prntscr.com/mo6a7k 

You'd need to use the Listing and Listing Grid to display products from the category, however, this should help.

If this solution doesn't fit the purposes, please, can you describe it in more details? 

Also, please, note, that we accept the feature requests only in English. 

Best regards from CrocoBlock team

**Comment by UraraReika** [comment]
I merged this issue with #553 3, which is on the same subject so we could deal with it more efficiently.
