### ISSUE TITLE
Select Several CPT's as Booking Instances for JetBooking

### ISSUE THREAD

**Issue by fabianpuetz-hsfurtwangen** [CrocoBlock/suggestions#2100]
Hey Croco Devs,
It would be amazing if it would be possible, to select more than 1 cpt as booking instance for JetBooking. 
For example i want to offer motorbike rentals AND also tours on my website. 
The problem is, that i can just select one of them at the moment.

Would be really happy if you can implement this feature.

Have a wonderful day,

Fabian

**Comment by Floydtm** [comment]
@fabianpuetz-hsfurtwangen, hi! Hello! We have reviewed your request with the plugin developer. At the moment we cannot do this. However, you can categorize your posts. Thanks you!
