### ISSUE TITLE
JetMenu: More Options for styling 'First' & 'Last' Item

### ISSUE THREAD

**Issue by shenom-x** [CrocoBlock/suggestions#2102]
Hi.

The options 'First/Last item custom styles' are very cool & welcome!

If You could expand these with a margin field - that woud be perfect. Imagine a vertical menu where I can set some space between them and make them once more stand out from the other menu items.

Like this:

Item A
Item B
Item C

Item Last

**Comment by Floydtm** [comment]
Hello! We will not add this to the plugin at this time. Now you can do it with CSS
