### ISSUE TITLE
Progress Bar Widget Needs Absolute Option (which is already offered in Circle Progress widget)

### ISSUE THREAD

**Issue by gaiuskong** [CrocoBlock/suggestions#2108]
Circle Progress widget has Absolute. Could you also allow the Progress Bar widget to display Absolute values? 

Many listing websites need this. In my case, GRE score is 340 max, and I want to display 320/340. (GMAT has 800 max, LSAT 800, TOEFL 120, ACT 36, etc)

In those situations, the Circle Progress widget isn’t suitable. Progress Bar widget with Absolute values is needed. 

Preferably with a label to show a range ("label open" value and "label close" value). For example, in a community, Trump supporters donate between $100 to $1000, and mostly in the range between $400 (label open) and $600 (label close).  For another example, this graduate program admits students with GRE in the range of 315-322. 

 
<img width="473" alt="XvikPVJsAUZ0Px_aIHTuhbvempXucv7n2w" src="https://user-images.githubusercontent.com/7755561/97879539-1d0b3500-1cee-11eb-9455-26c8ce39df61.png">

**Comment by zahnd** [comment]
Hi. Please also add the unit's prefix and suffix fields to the progress bar :). Thank you
