### ISSUE TITLE
Seasonal  Pricing & Woocommerce Order Description

### ISSUE THREAD

**Issue by loupaok** [CrocoBlock/suggestions#2112]
Hi everyone,

I start create a Car Rental website and now i start create a Hotel Booking Website but missing **2 VERY IMPORTANT** fields in Jetbooking and Jetwoo plugins.

1) JetBooking Plugin
There is not Seasonal Pricing that can i create my plan once for each day, week or month.
Example:
January - February: $20/ per day 
March - May: $30/ per day 
June - August: $50/ per day
etc.. and i can use multiple options for different cars or rooms if possible,

2) Jetbooking and Jetwoo
I try to make some demo book a room to see how works and and they were missing the days or locations from Order Overview in Woocommerce.
For example i booked a car with Pick-up location New York Jersey City and Return location New York Brooklyn and when i finish the booking I tried to find were was these fields in order and these fields are missing.

I think in very important to add both fields for Booking option.

**Comment by EvgenDoman** [comment]
+1

**Comment by WardenCommander** [comment]
+1 need this to, very important

**Comment by RiKaZaRai** [comment]
Yes!! It's very important for rental website

**Comment by UraraReika** [comment]
Hello everyone!

1.This functionality was presented in 2.4.0 version. You can fell free to check it out.
2. You can setup it here https://tppr.me/1pQzq, https://tppr.me/wXFbc

Thank you!
