### ISSUE TITLE
Let customer choose productpicture in productsgrid

### ISSUE THREAD

**Issue by takemeoutevents** [CrocoBlock/suggestions#2115]
Hi there,

For some products displayed in a productgrid it would be crucial to be able to select which productimage is displayed in the productgrid.

For instance we have a product that has very different productimages for men and for women.

We have made 1 productpage that has 1 featured image that shows women but it also has more productimages that shows the product for men.

We have sperate landing pages showing our products for women and products for men.

In the productgrids shown on the landing page for men i would like to choose the productimage for men but at this time it is showing the featured image for women because i can't change this.

So giving us the choice to select which image we display could drasticly improve sales for unisex products!

I hope this is a nice feature and will be added to this amazing plugin!

I would be open for a paid customisation as well offcourse. Give me a quote if you like!

Kind regards,

Dominic

**Comment by UraraReika** [comment]
Hello @takemeoutevents ! Could you please describe in more details how you add images into product post? Is there some kind of separation, or some kind of marking that can tell us which gender connected to this item?

**Comment by takemeoutevents** [comment]
Hi there,

Let me explain a bit more detailed :)

In the backend of a product post i can add a product image AND i can add images to the productgallery.

Some products we have are both cool for men and for women. The product image (featured image) is unisex and is somewhat appealing to both men and women. In the productgallery we have added images for every unisex product that are more appealing to the specific genders.

On a landingpage for men in would like to be able to select an image from the productgallery of every product i add to the productsgrid.

This is nessecary so that i can select images that appeal more to men in stead of showing the product image (featured image) that is somewhat unisex.

This would massively increase my sales for sure!

I have made a video with an example in my website!



https://www.loom.com/share/fd717dbd1845428a9fcf93de36ecc8f7


Kind regards,

Dominic

**Comment by UraraReika** [comment]
I got it. But unfortunately such functionality will not be added to out plugin. 

Contact with out support team and refer to this issue so they can redirect it to me, I`ll help you to achieve this result with alternative way built in our plugin.

**Comment by takemeoutevents** [comment]
Dude,

You are the best this solution is genius!

Thanks very much!

Kind regards,

Dominic
