### ISSUE TITLE
JetSmartFilters: refinements

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#212]
An example of a page with filters over content.

https://www.tme.eu/en/katalog/batteries_100346/

Also pay attention to the categories on the left. Reasonably comfortable tree http://prntscr.com/nfveyl

So far I haven’t understood it in detail, but it seems that taxonomy filters can also be output. Or use the menu for a similar category tree. It is necessary to test both.

By the way, I drew attention to 2 interesting possibilities for filters that I had never met before: checkbox "select all" and the ability to customize the filter list http://prntscr.com/nfvgwc  It’s hard to say how much these features are needed on a real site, you need to test looks good.

**Comment by javiercriado** [comment]
to create a checkbox "select all" simply add an option with the label you want but without a value

**Comment by realstephenzhao** [comment]
> 
> 
> to create a checkbox "select all" simply add an option with the label you want but without a value

What about hierarchy? "Select All" doesn't belong to the category structure.
