### ISSUE TITLE
 Export custom content types

### ISSUE THREAD

**Issue by sixmanstone** [CrocoBlock/suggestions#2124]
Export custom content types
![
Export custom content types](https://user-images.githubusercontent.com/73070227/98343161-b6e62100-2011-11eb-8832-b705599b1647.png)

**Comment by EvgenDoman** [comment]
+1

**Comment by LilaMiaou** [comment]
+1

**Comment by hum-bug** [comment]
+ 1

**Comment by kaskad88** [comment]
I merged this issue with [#3683](https://github.com/CrocoBlock/suggestions/issues/3683), which is on the same subject so we could deal with it more efficiently.
