### ISSUE TITLE
JetEngine: Listing Grid "Load More" with better loading indication

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#2126]
If Read More with Button or Infinite Scroll is activated, the opacity changing on actual items only weakly indicates that new content is being loaded. 

It would be better, if in addition, where the new content is inserted, i.e. at the very bottom a loader animation is added. Like e.g. the lazy load. This way the user can immediately guess that content will be added underneath. This is especially helpful if the user/server has a bad connection and loading takes longer than expected.

**Comment by cultweba** [comment]
This feature would be really useful.

**Comment by sifatullahsu** [comment]
I solved this issue by doing some peach of CSS codes. This is the CSS class "**jet-filters-loading**" that will be added on the "**listing-grid / dynamic table**" when someone changes something with the jet smart filter.

**Video Preview** [https://www.sifatullahsu.com/wp-content/uploads/2022/02/loading-video.wmv](https://www.sifatullahsu.com/wp-content/uploads/2022/02/loading-video.wmv)

**This is the CSS code...**
```
.jet-filters-loading::before {
	content: url('https://www.sifatullahsu.com/wp-content/uploads/2022/02/loading.gif');
	width: 40px;
	height: 40px;
	display: inline-block;
	background: #000;
	position: absolute;
	z-index: 1;
	color: #fff;
	padding: 5px;
	border-radius: 4px;
	top: -50px;
	left: 160px;
}
```

**Comment by cultweba** [comment]
Thank you for your explanation. It was very helpful to me

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by portrayaloflife** [comment]
@sifatullahsu That was super helpful! Thank you!
