### ISSUE TITLE
Listing Element - Hide if value is empty

### ISSUE THREAD

**Issue by Biblothecaire** [Crocoblock/suggestions#213]
Hi,

You purpose a"Hide if value is empty" in dynamic Field ONLY
It is a really good option !

Wy can't purpose the same for the other element ?
- Dynamic Link 
- Booking Form 

Will be really usefull, especially the form! So "if" fields "X" not filled "then" Hide

**Comment by Floydtm** [comment]
Added in JetEngine 1.4.2

**Comment by Biblothecaire** [comment]
Hi,

I just test  :

1. Work fine for Dynamic Link (listing element)
2. Don't work for Booking Form (jet engine)

**Comment by Floydtm** [comment]
Hi,
please, check this options http://prntscr.com/nscfir for form field

**Comment by Biblothecaire** [comment]
Thanks for your answer, but it's not what i need, i don't need to hyde only one field, i need all the form
I explain :
My site is a guide for Madagascar. All hôtel can have a page (CPT) with information.
BUT only the hotel who paid can have the form.
WHEN the hotel paid, i fill the mail box
So, what i need is : 
 "if" fields "X" (X = e-mail fields) not filled "then" Hide

**Comment by Floydtm** [comment]
Sorry, but so far there is no such functionality. But we plan to add it soon. I will re-open your request, stay tuned.

**Comment by kevindaus** [comment]
If anyone encounters this problem wanting their widget to hide if custom field is empty / not available . 
You can use regex . 
![image](https://github.com/user-attachments/assets/3860264d-f19a-4cb9-8dde-899b32aa3383)

**Comment by natequreshi** [comment]
> If anyone encounters this problem wanting their widget to hide if custom field is empty / not available . You can use regex . ![image](https://github.com/user-attachments/assets/3860264d-f19a-4cb9-8dde-899b32aa3383)

There may be more techniques like these, can you post in a proper blog .

**Comment by poesjemiauw** [comment]
regexp works but still after all these years no simple solution?
