### ISSUE TITLE
Jet Engine: Add user Relation

### ISSUE THREAD

**Issue by infun8** [CrocoBlock/suggestions#2131]
It would be great to create a relation between a custom post type and a user.

It would make the user listings work way better. For example, I have a custom post type "Projects"

I want to display a listing of the related members, using the listing template I created for users, as it contains specific style and content related to the post type.

Alternatively, making a custom field of "select user" and adding the ability to filter the listing grid by that field (display users by ID)

![Screen Shot 2020-11-07 at 5 02 26 PM](https://user-images.githubusercontent.com/33790084/98453138-825e8c00-211b-11eb-82aa-2bf65b8d4808.png)

I have just manually made the listing contain the user ID's in a comma separated list, but I'm trying to create a dynamic template which will show the "related users" in the listing grid for each project.

I have a listing for the Member, then a template which is called for the listing which should be filtered either by a relation to the user, or by displaying the users by the ID's entered into the metafield. Ideally you would be able to search for the user by user or nice name, then add them to the field so they can later be used in the members listing grid.

![Screen Shot 2020-11-07 at 5 09 48 PM](https://user-images.githubusercontent.com/33790084/98453236-96ef5400-211c-11eb-8e5f-c99b3c64c586.png)

If you were going to add that feature, probably would be the same for exclude, which would also be useful in some cases.

Thanks. 
I'm happy to elaborate, test etc...

**Comment by opwolken** [comment]
Yes, please! +1

This is perfect for some of my clients where they add new employees to the site as wordpress 'User', those users are able to post blogs, projects and references. I would to use this function to dynamically cross reference throughout the website. I.E. 'Projects by employee' and 'employees on this projects'. I get the same result now with CPT 'Employee' but of course that CPT doesnt have the user capabilities I also want.

**Comment by kochhase** [comment]
Hi crocoteam, is there something ready for using? please help

**Comment by kochhase** [comment]
Hi Croco, 
the workaround with the id of users is not working for me, because the if insert  the id as commatas than i get the listing with order of the first name field from users. no way to get some other ordering right now. please help !!!

**Comment by kochhase** [comment]
Hi there for others in the funktion.php

function my_user_sort( $query_args ){
    if( !isset($_GET['orderby']) ) {
        $query_args->query_vars['orderby'] = 'ID';
    }
    return $query_args;
}
add_action( 'pre_get_users', 'my_user_sort' );

or with usermeta fields:

function action_pre_user_query( $u_query ) { 

    $u_query->query_vars['orderby'] = 'meta_value_num';
	$u_query->query_vars['meta_key'] = 'membersorting';
    $u_query->query_vars['order'] = 'ASC';

}
add_action( 'pre_get_users', 'action_pre_user_query');

**Comment by rolfkrue** [comment]
+1 - very much needed here!

**Comment by kochhase** [comment]
Hi crocoblock, is there something ready in Jetengine 2.8.x . How to make an relation between user and CPT company. We need this very soon.!!!

**Comment by its4youb** [comment]
Hello Crocoblock team, is there something ready or in development to make a relation between Users and CPT?
It functionally will be very welcome, please, could you focus on finding a solution for us?

**Comment by milwagh** [comment]
+1 for this 'user' field availability in JetEngine

**Comment by bitiplusadmin** [comment]
I need this too

**Comment by Joseins** [comment]
- I would urgently need this too. Thanks.

**Comment by MjHead** [comment]
Added with 2.11.0
