### ISSUE TITLE
Add an option 'Prevent page scrolling' For an open pop-up

### ISSUE THREAD

**Issue by uri647** [CrocoBlock/suggestions#2132]
Hi
I recently used a jet popup
And I saw that there was no possibility of '**Prevent page scrolling**' When the pop-up is open
(As there is in Elementor's simple popup)

I would love to get a solution

![image](https://user-images.githubusercontent.com/74133897/98461700-087be080-21b7-11eb-9e21-30d596fa9890.png)

**Comment by stijnvanouplines** [comment]
Put this Javascript code somewhere on the page where you use the popup:

```javascript
( function( $ ) {

    'use strict';

    $( window ).on( 'jet-popup-open-trigger', function( ) {
        $( 'html, body' ).css( 'overflow', 'hidden' );
    });

    $( window ).on( 'jet-popup-close-trigger', function( ) {
        $( 'html, body' ).css( 'overflow', 'auto' );
    });

}( jQuery ) );
```

**Comment by shinTM** [comment]
done v1.5.0
