### ISSUE TITLE
JetBooking. Price by month and season

### ISSUE THREAD

**Issue by thetallman4444** [CrocoBlock/suggestions#2133]
Everything is fine, but there is a wish, if I write there of course:
I really miss the opportunity to change the price depending on the month or seasons. A fairly simple primitive function. When creating a website for a hotel-this is a very important moment. Very important. In fact, some hotel projects can't be completed with your plugin because of such a necessary feature. At least correct me if I haven't figured out how to implement it.

**Comment by Floydtm** [comment]
merge with #1472

**Comment by tavolucas** [comment]
merge with #2452

**Comment by UraraReika** [comment]
This functionality was presented in 2.4.0 version. You can fell free to check it out.
