### ISSUE TITLE
Implement re-order support for JetEngine select2 multiselect fields

### ISSUE THREAD

**Issue by Sidlegionair** [CrocoBlock/suggestions#2138]
Hi,

I'd like to make it possible to change sorting for select2 fields, you could use the following library: http://finn.heemeyer.net/select2.sortable/

**Comment by kochhase** [comment]
yes please !!

**Comment by Floydtm** [comment]
I understand that this is very important to you. However, you'd better leave your request [here](https://github.com/elementor/elementor/issues)
