### ISSUE TITLE
JetTricks Tooltip Needs to be Dynamic (a use case)

### ISSUE THREAD

**Issue by gaiuskong** [CrocoBlock/suggestions#2139]
You’re looking at a Single post template. 
I’m building a famous people website, 
and each person has four scores. I would
like to have tooltips showing my comments
that explain why the person gets this score,
so I need the tooltip to be dynamic, so that
I can pull data from custom fields where my
comments are stored for each person.  

<img width="737" alt="WX20201110-194736@2x" src="https://user-images.githubusercontent.com/7755561/98751278-d2448980-238d-11eb-897b-4349d1de66c0.png">

**Comment by WardenCommander** [comment]
as much as possible of inputs, descriptions, pictures, and so on would have to be dynamic everything is moving in that direction

**Comment by kaskad88** [comment]
Added in JetTricks 1.3.3. Feel free to update!
