### ISSUE TITLE
JetWoo: Add more templates to My Account to customize orders, downloads etc. pages

### ISSUE THREAD

**Issue by getwebcare** [CrocoBlock/suggestions#2141]
Currently you can only edit the my account page and add all the my account widgets to a single page.
But I would like to customize the orders, view-order, downloads, edit-account, edit-address, payment-methods, lost-password pages.

![jetwoo](https://user-images.githubusercontent.com/32192439/98799075-5131d480-2417-11eb-92ac-9e5e4a1e358f.png)

**Comment by getwebcare** [comment]
Hey guys, any feedback on this?

**Comment by getwebcare** [comment]
Anyone?

**Comment by UraraReika** [comment]
Latest release!

**Comment by iMagoo** [comment]
Sounds good, will it be added to the next release ? :)

**Comment by UraraReika** [comment]
> Sounds good, will it be added to the next release ? :)

1.7.4 release.

**Comment by BlueteraLLC** [comment]
Still no option to edit the "view-order" template for single order details?

**Comment by rtpHarry** [comment]
No option for the lost-password page either that I can find. 

It seems like in some way this has been developed (I can go to /my-account/lost-password/) but not as a setting in the endpoint configuration, and its broken when you click the lost password on the checkout login widget (points at https://example.com/lost-password/?jet-woo-builder=knepp-customer-account-orders)

**Comment by morosmo** [comment]
+1
