### ISSUE TITLE
Pleasea add this code to compatible with Plugin: WooCommerce Variation Swatches Pro

### ISSUE THREAD

**Issue by daigiaknight2** [CrocoBlock/suggestions#2142]
This code can add like this screenshot to compatible with Plugin: WooCommerce Variation Swatches Pro.
![image](https://user-images.githubusercontent.com/74295943/98801681-bc45d000-2444-11eb-99ff-368060fca6e9.png)

**Why it is important to add it?**
To show the variation swatches in product grid widget. Very important!

**Describe what effect or functionality you want to achieve as a result.**
And the result here, you can see screenshoot:
![image](https://user-images.githubusercontent.com/74295943/98802174-789f9600-2445-11eb-97cd-80e0f2b5d28c.png)
![image](https://user-images.githubusercontent.com/74295943/98802626-257a1300-2446-11eb-88e9-35f2e4d09083.png)

=>>>> The code is here: The code is here: ?php do_action('wvs_pro_variation_show_archive_variation'); ? (please add < in the beginning code and the end by >)
Thank you!

**Comment by daigiaknight2** [comment]
The code is here: <?php do_action('wvs_pro_variation_show_archive_variation'); ?>

**Comment by daigiaknight2** [comment]
The code is here: "<?php do_action('wvs_pro_variation_show_archive_variation'); ?>"

**Comment by daigiaknight2** [comment]
The code is here: ?php do_action('wvs_pro_variation_show_archive_variation'); ? (please add < in the beginning code and the end by >)

**Comment by EvgenDoman** [comment]
and it is better to make an alternative to Variation Swatches that it would be in Crocoblock

**Comment by daigiaknight2** [comment]
That's right! 

> and it is better to make an alternative to Variation Swatches that it would be in Crocoblock

**Comment by Floydtm** [comment]
Guys, we have a [tutorial](https://crocoblock.com/troubleshooting/articles/how-to-add-attractive-variation-swatches-to-woocommerce-archive-page/) on how to do it. We will not add it to the plugin as not everyone will need it. Thanks you!

**Comment by daigiaknight2** [comment]
Hi Floydtm,
Can it work on Product Grid Widget?
Thank you!

**Comment by Floydtm** [comment]
@daigiaknight2, yes it should work
