### ISSUE TITLE
Jet Menu not working in Samsung Internet Browser

### ISSUE THREAD

**Issue by jonburdon** [CrocoBlock/suggestions#2145]
Clicking on hamburger icon in Samsung Internet 

1. Go to 'Hamburger Widget'
2. Click on 'Hamburger Icon'
4. See error - icon just swirls.

**Expected behavior**

Open dropdown normally

**Smartphone (please complete the following information):**
 - Device: Samsung A40
 - OS: Android
 - Browser Samsung Internet
 - Version 12.1.4.3

There should be a media query to use pure css if this does not work in some browsers

**Comment by Floydtm** [comment]
I understand that this is important to you. However, we will not be doing this right now. If we collect more requests in this regard, then we will definitely return to this. Thanks you!
