### ISSUE TITLE
Add FreeMode Scrool option to Slider Listing Grid Mobile

### ISSUE THREAD

**Issue by Felipemauah** [CrocoBlock/suggestions#2147]
I would like to suggest something that will REALLY raise the level and use of the sliders listing grids and I believe I am not the only one with this need.

It would be really cool if we had the option to enable freemode or freescroll for the listing grid when I use the Slider option.

On the desktop this option does not make much sense, however, on mobile it does, and a lot.

When I use the slider on mobile I am obliged to make a very extensive and tiring movement with my finger so that the slider moves completely and in my case that I have a Netflix style content platform, it is a negative experience for users because 90% of the mobile navigation of my platform is via Carousel.

Another negative point of not having the Freemode option is that due to the fact that the Slider has to align the image to the screen, when it is necessary to go and return the same Slide, the Carousel does not obey the command of the finger and locks, giving the feeling that the website is slow.

I saw that there is the Freemode Scroll option in the Horizontal Timeline widget, however, it is not possible to use listing grids in this widget. It would be a good starting point for the code for this function that I am suggesting.

Widget link with Freescroll / Freemode: 
https://crocoblock.com/widgets/horizontal-timeline/

I bought the complete Crocoblock package and I am very satisfied, you are excellent, but given my need, which I believe is not just mine, I found this point that can be improved and make your product even better.

thanks for the beautiful work !!

**Comment by Floydtm** [comment]
We are working on it. Keep for updates. Thanks you! https://prnt.sc/vsukdw

**Comment by Felipemauah** [comment]
Thank you very much !!! The final result was amazing !!! You guys do an excellent job! congratulations!
