### ISSUE TITLE
JetBooking - API/XML integration with OTA

### ISSUE THREAD

**Issue by WardenCommander** [CrocoBlock/suggestions#2148]
Hello,

would it be possible to integrate connection with OTA through API/XML ?
If not directly then through API providers that charge per API usage
like:
channex.io
otagateway.com

this would allow development of full sync of prices, availability, check in/check out dates, min reservation days
and so on.

**Comment by Floydtm** [comment]
Hi, I understand that this is important to you, but we must deny you this request. To solve your question, you need a custom solution. Thanks you!
