### ISSUE TITLE
Add a class to Jet Engine listing grid to enable alternative 'loader' styling

### ISSUE THREAD

**Issue by Sidlegionair** [CrocoBlock/suggestions#2151]
Hi,

Could a class be added to the element with 'jet-listing-grid jet-listing' or 'jet-listing-grid__items' when lazyload is doing its AJAX fetch to enable alternative loader styling?

Thanks!

**Comment by BenKalsky** [comment]
+1

**Comment by danielemuscia** [comment]
+1

**Comment by keer-z** [comment]
+1

**Comment by kaskad88** [comment]
Hello.
You can use the following css selector `.jet-listing-grid--lazy-load.jet-listing-grid-loading`

Also, you can use the following wp filter `jet-engine/listing/grid/loader/format` to change the loader html https://prnt.sc/EgBe1kcxIYyp
