### ISSUE TITLE
Hide / display fields in checkout billing form widget

### ISSUE THREAD

**Issue by lv986** [CrocoBlock/suggestions#2153]
Hi,

It will be nice when we can choose wich fields are displayed in the checkout billing form widget of jetwoobuilder. Also changing the order of these fields and the label of each field will be nice. There are other plugins, like woolentor and woolementor, who are doing this, but the template system and the stability of the crocoblock plugin is much better.

Thanks,
Luc

**Comment by UraraReika** [comment]
Hello @lv986 !

Our team was thinking about how to implement such functionality into their plugin, but as a result they abandoned this idea. We do not want to overload our plugin with functionality that is presented in many other plugins strictly focused on this. You can use one of them and they will all be fully compatible with our widgets. Here are some free options:

https://wordpress.org/plugins/add-fields-to-checkout-page-woocommerce/
https://wordpress.org/plugins/flexible-checkout-fields/
https://wordpress.org/plugins/woo-checkout-field-editor-pro/
https://wordpress.org/plugins/woo-checkout-regsiter-field-editor/

There are also paid versions:

https://codecanyon.net/item/advanced-custom-fields-for-woocommerce/18705467?ref=robin90&irgwc=1&clickid=WzvxBa2I0xyLWguwUx0Mo3EFUkEzd%3AVG53YfyY0&iradid=275988&irpid=419086&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_419086&utm_medium=affiliate&utm_source=impact_radius&clickthrough_id=1420448117&redirect_back=true
https://codecanyon.net/item/woocommerce-checkout-field-editor/11725925?ref=robin90&irgwc=1&clickid=WzvxBa2I0xyLWguwUx0Mo3EFUkEzd%3AVu53YfyY0&iradid=275988&irpid=419086&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_419086&utm_medium=affiliate&utm_source=impact_radius&clickthrough_id&redirect_back=true
https://codecanyon.net/item/woocommerce-easy-checkout-field-editor/9799777?ref=robin90&irgwc=1&clickid=WzvxBa2I0xyLWguwUx0Mo3EFUkEzd%3AVP53YfyY0&iradid=275988&irpid=419086&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_419086&utm_medium=affiliate&utm_source=impact_radius&clickthrough_id&redirect_back=true

And also from the developers themselves: https://woocommerce.com/products/woocommerce-checkout-field-editor/?_ga=2.226502621.1588695400.1605856602-979700640.1605856602
