### ISSUE TITLE
JetEngine: Listing Item with link is an empty anchor link

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#2157]
Listing grid item with link provokes an empty anchor link. This is not an optimal condition for SEO. 

https://ibb.co/fvsgZp8

Either place the link around the listing item and not at the end, or enable a dynamic entry like "post title" which can be hidden with css if necessary.

Or maybe add this feature

#363

**Comment by petranca** [comment]
+1

**Comment by MjHead** [comment]
Can't be recreated in a different way due to technical reasons
