### ISSUE TITLE
JetElements: additional features

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#216]
- Not enough work with maps. Usually they use Google Maps, but in my practice I often need to use Yandex Maps https://yandex.ru/maps/ As I understand it, there are 2 possible output options: API and HTML. There is no such function in ACF by default, it is added through the add-on https://ru.wordpress.org/plugins/map-for-acf/

- The HTML field is also periodically required to display the code of third-party services. The visual editor is not suitable for such purposes, because almost always distorts the original code, removing different tags from it.

Yandex Map for ACF
https://ru.wordpress.org

**Comment by Floydtm** [comment]
We need to develop two separate addons.

1 yandex map for jetengine 
2 HTML editor
