### ISSUE TITLE
JetSearch with button add to cart

### ISSUE THREAD

**Issue by marcofrasson** [CrocoBlock/suggestions#2169]
It would be interesting to have the option of placing the buy button in the product results, this way the end user can add several products via ajax to the cart without leaving the search.

It would also be good to lock the result box so as not to hide when you accidentally click outside it, maybe put a close button like you have in popups.

**Comment by Floydtm** [comment]
If you have jetwoobuilder plugin you can do it right now https://prnt.sc/vtd74g at the moment this is one way to implement your request. Thanks you!
