### ISSUE TITLE
JetSmartFilters inompatibility issue with Elementor Pro Archive Products

### ISSUE THREAD

**Issue by KostB** [CrocoBlock/suggestions#2170]
**Describe the bug**

I've tried to incroprorate JetSmartFilters with the Elementor Pro Archives Products widget (which is enabled in JetSmartFilters' settings). I did that using Kadence's template builder. However, the product archive behaved weird. It filtered out everything when I moved one slider in the range filter, but didn't reveal anything anymore when I moved it back. I removed Archive Products and replaced it with Elementor Pro Products. It worked.
I looked to see if there was a query ID mismatch, or whether I selected the wrong widget. But no. The issue persists with Archive Products in specific.

To test any compatibility issues. I've created a staging site, I deactivated every plugin except for JetSmartFilters, Elementor and Elementor Pro. And subsequently changed from Kadence theme to the Twentynineteen. And rather than creating templates in Kadence's editor, I used the regular Elementor Pro theme builder. Followed all the same steps. But again, it did not work. It worked on the Elementor Products widgets. But not the Archive Products widget.
It must be some sort of bug.

**To Reproduce**

1. Go to Elementor > Templates > Theme Builder > Products Archive
2. Add Archive Products widget and Range Filter
3. Move one end of range filter, see entire archive disappear, move back and see it stays disappeared

**Expected behavior**
What I expected to see is for the filters to gradually remove every product that does not adhere to the range set within the range filter. This did not happen.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome
 - Version: 86.0.4240.198 

I have not checked this on mobile.

**Comment by Floydtm** [comment]
We checked everything and everything seems to be working well. However, our sites can be customized in different ways. I suggest you contact our support team. Perhaps they will help you. Thanks you! 
[bandicam 2020-12-01 09-36-48-699.zip](https://github.com/Crocoblock/suggestions/files/5620942/bandicam.2020-12-01.09-36-48-699.zip)
