### ISSUE TITLE
Schedule indexfilters

### ISSUE THREAD

**Issue by alexmathias** [CrocoBlock/suggestions#2178]
As you know, jetsmartfilter widgets counters depends on manual indexing to show up-to-date results and counters, and for that reason and are pretty useless if you have subscribers creating posts you need to filter/count in an hour or daily basis, unless you pay someone to sit on a chair and mannually index several times a day.
So, I think we have e strong argument for a very usefull feature: the possibility to schedule index filters, using minutes, hours, days, weeks and months as indexing parameters.
![image](https://user-images.githubusercontent.com/66876358/99441813-2fdd5680-28f7-11eb-853c-d23799401543.png)

**Comment by stasonua0** [comment]
+1

**Comment by Lonsdale201** [comment]
+1 :)

**Comment by MelRoute66** [comment]
+1!

**Comment by kkohlmann55** [comment]
+1

**Comment by anrob** [comment]
+1

**Comment by Floydtm** [comment]
#1159
