### ISSUE TITLE
JetSmartFilter > Group terms by parents for "Select" filter type

### ISSUE THREAD

**Issue by Rubenzella** [CrocoBlock/suggestions#2179]
as per the checkbox filter type where this "Group terms by parents" option already exists, I would like to be able to have it also for select filter types in order to have the dropdown filter nicely organised on the frontend. 
At the moment the taxonomies, parent and child, are shown in alphabetically order which is confusing in some cases.

**Comment by Floydtm** [comment]
I understand that this is important to you, but we cannot do it right now. Perhaps we will come back to this in the future. Thanks you!
