### ISSUE TITLE
Advanced Carousel dynamic

### ISSUE THREAD

**Issue by alriksson** [CrocoBlock/suggestions#218]
**Please, describe the feature request, making it clear to understand.**

- Disable enable image. If image is not used possibility to disable.
- Button text is missing dynamic feature
- Possibility to use text title as link target instead of forcing to use button.

Straight forward fix for development team to sort. Would extend the possibility and what I want to use the carousel for. To slide content and to not limit the widget/element to image carousel.

And critical to add customisation of headline HTML tag. from H1-H6, span and p.

**Comment by alriksson** [comment]
@Floydtm @kaskad88 Ping.

**Comment by kaskad88** [comment]
> Disable enable image. If image is not used possibility to disable.
If an image is not used, a default image can be deleted by clicking on this button http://prntscr.com/ntwhhd

Other suggestions - done

**Comment by kaskad88** [comment]
Available in JetElements 1.15.13

**Comment by alriksson** [comment]
@kaskad88 will be released when?

**Comment by Floydtm** [comment]
@alriksson we will try to make a release at the end of the week

**Comment by alriksson** [comment]
Sounds great!

> If an image is not used, a default image can be deleted by clicking on this button http://prntscr.com/ntwhhd


isn't the img tag and divs still added7executed on the frontend but empty by doing so? can't remember.
