### ISSUE TITLE
JetSmartFilters does not trigger custom events

### ISSUE THREAD

**Issue by mbaierl** [CrocoBlock/suggestions#2181]
For a special requirement I need to run some JavaScript code every time the JetSmartFilter changes and has finished updating the posts list.

The "support" suggested to use the event "jet-filter-content-rendered", but this string does not exist anywhere in the code. 

They also suggested to use the code
`$( document ).on( 'jet-filter-content-rendered', function() {`
which does not do anything at all and is only defined in the maps component.

**Expected behavior**
A clear and documented way of running custom JavaScript right after JetSmartFilters has updated the post list.

**Comment by mbaierl** [comment]
Any update on this?

**Comment by Bookit24** [comment]
I'm looking for the same functionality!

**Comment by formulaclick** [comment]
This worked for me.




		jQuery( document ).on( 'jet-filter-content-rendered', function() {

                       alert('content rendered');

		});

**Comment by bfa** [comment]
Where are the developer docs for these hooks? I would really want to reference them to extend the functionality of JetSmart Filters.

**Comment by lambia** [comment]
The solution of @formulaclick does work for me too.
But where is the documentation guys? There nothing about custom events, hook names or anything.
Come on guys, you're getting payed for this shit.

**Comment by damianrivadulla** [comment]
Hi! I need that hook after the content is rendered. Is there some documentation?
This doesn't work, because don't inclue the search results.
Thanks

**Comment by SargasTM** [comment]
After rendering content hook

$(document).on( 'jet-filter-content-rendered', function ( evt, $provider, filterData, providerName, queryId ) {  } );

Arguments
evt - is just an event
$provider - jQuery provider select
filterData - provider group filter object
providerName - provider name
queryId - provider ID

**Comment by lukechinworth** [comment]
They updated this with custom event bus, so now you can do 
```
window.JetSmartFilters.events.subscribe('provider/content-rendered', ()=>{
	console.log('Content rendered')
})
```

You can see the other events (loading start/end, etc) in `wp-content/plugins/jet-smart-filters/_dev/src/js/FilterGroup.js`

IMPORTANT: be sure to include your js after jet smart filters, because it clears out all listeners when it initializes.

**Comment by ihslimn** [comment]
There is also an ajaxFilters/updated event

```js
document.addEventListener( 'jet-smart-filters/inited', function( initEvent ) {
        
        jQuery( function( $ ) {
            
            window.JetSmartFilters.events.subscribe( 'ajaxFilters/updated', function( provider, queryId ) {
                
                let filterGroup = window.JetSmartFilters.filterGroups[ provider + '/' + queryId ],
                    $provider   = filterGroup.$provider;
                
                //your code here, $provider is a jQuery object which is a rendered widget
                
            } );
        
        } );
    
    } );
```
    
this event fires any time ajax filtering is completed

**Comment by launchthatbrand** [comment]
> There is also an ajaxFilters/updated event
> 
> ```js
> document.addEventListener( 'jet-smart-filters/inited', function( initEvent ) {
>         
>         jQuery( function( $ ) {
>             
>             window.JetSmartFilters.events.subscribe( 'ajaxFilters/updated', function( provider, queryId ) {
>                 
>                 let filterGroup = window.JetSmartFilters.filterGroups[ provider + '/' + queryId ],
>                     $provider   = filterGroup.$provider;
>                 
>                 //your code here, $provider is a jQuery object which is a rendered widget
>                 
>             } );
>         
>         } );
>     
>     } );
>     ```
>     
>     this event fires any time ajax filtering is completed
> ```

How can i use these events to get the values in currently active filters and set them to a cookie, and be read on a reload?
I am able to get a console log of the whole object, but cant find where in it i can get active filter values

**Comment by Abdulhakeem-Salawu** [comment]
How can we access the JetSmartFilter Filter values, so we can filter our own custom posts types.

For example,

I want to have the ability to filter custom post types with the filter values from the JetSmartFilter, whenever a search is made with a Checkbox or Dropdown.

I want to access that value from the checkbox, so I can use that to filter some posts in the page.
