### ISSUE TITLE
Hide calendar on certain product pages

### ISSUE THREAD

**Issue by iuliagramonsuba** [CrocoBlock/suggestions#2183]
Hello,

I have been trying to create a switcher to hide the calendar from Jet Appointments, from certain product pages. But this is not working. Is this something that Jet Engine can achieve? If yes, can you guide me through this? 

link: https://iesilajoaca.ro/store/ateliere/family-hub-chiajna/

Thanks.

Kind regards,
iulia

**Comment by Floydtm** [comment]
You can do this with the jetengine plugin. for this you need to use the dynamic visibility module. Thanks you!

**Comment by iuliagramonsuba** [comment]
I have tried this before contacting you and it did not work. I created a switcher for it and it did not work at all. :(

**Comment by Floydtm** [comment]
if you have any problems with this, then you need to contact our support team. The guys will help you set up everything

**Comment by iuliagramonsuba** [comment]
Thanks, but they said they cannot do it and they asked me to write about this in here, saying that you can help...
