### ISSUE TITLE
JetEngine Listing Grid Injections: add by taxonomy or post type

### ISSUE THREAD

**Issue by Sarah-p** [CrocoBlock/suggestions#2184]
When creating a listing grid injection it would be helpful to be able to choose a taxonomy and/or a different post type. If the archive for search is pulling from multiple post types and/or taxonomies then it would be nice to highlight that they are different.

**Comment by Jixart** [comment]
This is a must :/ did you found out how to achieve this ?

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
