### ISSUE TITLE
Radio filter count is not showing counter properly for terms

### ISSUE THREAD

**Issue by alexmathias** [CrocoBlock/suggestions#2186]
I´m having issues on radio filtering terms counters after JetEngine 2.5.6 (November 18, 2020) update. 
Active filters works fine, but all the other terms counters go to "zero" (JetEngine 2.5.6 SmartFilters 2.0.4)
Indexes are up-to-date and filtering is working fine, but all counters except for selected one go to "zero" when any filter is active (radio selected).

Edit: After a chat with support I was told this is not a bug. Comprehensible, but not logical from the user point of view, once independently of an active filter he would like to know the counter for the others, dont you agree??

![image](https://user-images.githubusercontent.com/66876358/99732627-905ac800-2a9e-11eb-9b1e-94d01b0cbc52.png)

**Comment by Floydtm** [comment]
I understood you. You need to customize the indexer as it suits you https://prnt.sc/vtoogf
