### ISSUE TITLE
JetCompare&Wishlist for other post listings

### ISSUE THREAD

**Issue by LiamX2** [CrocoBlock/suggestions#2187]
Looking for the Compare&Wishlist function for supporting post listings that not woocommerce products. Thanks

**Comment by MjHead** [comment]
@LiamX2 Hi! You can use Data Stores module from JetEngine for this

**Comment by LiamX2** [comment]
@MjHead Hi Mate, Thanks for your suggestions, Data store works perfect for wishlist, but it doesn't support comparison, pls correct me if I was wrong. Cheers Liam

**Comment by LiamX2** [comment]
@MjHead Or do you have any other suggestions for comparison posts? I was looking for comparison function for two/multiple property listings, like the listing features, price, locations, etc. Thanks in advance.
