### ISSUE TITLE
JetEngine : allow Profile Builder to be built with JetTabs

### ISSUE THREAD

**Issue by futureyoon** [CrocoBlock/suggestions#2188]
I understand that account page of profile builder is somewhat imported and due to that, the range of design that can be edited is very limited. 

so I would like to suggest JetTabs to be able to build the Profile Builder. 
By doing so, within the Account page, a user can do add post, edit post, user settings without the page is getting loaded.

**Comment by MjHead** [comment]
@futureyoon Hi! You already can do this inside single Profile Builder page - just add tabs widget and separate templates for different tabs. But if you want to create separate pages in profile builder settings and than output its with tabs - it will not work this way because it breaks the default logic.

**Comment by futureyoon** [comment]
@MjHead Yes, that's the feature I am requesting - creating a page working like profile builder but out from the profile builder. 
as you mentioned, it breaks the logic.. it doenst seem working after I have given lots of tries in different methods.. 

my ticket number : https://support.crocoblock.com/support/tickets/20644
outcome of Profile Builder feature has alot of limitation 
1. left menu design 
2. it's not ajax loading - but page reload for each differnet menu
3. I cant embed this into existing page bcoz of 'edit post' is always pointing at the specific URL 
(e.g. https://domain.com/account/edit-post altho the page that i embed a new profile builder with jetengine (as a shortcode) is https://domain.com/members/futureyoon, futureyoon is dynamic username) 

I hope I made the points clear. would you be able to reopen and look into this? 

I saw the jetengine 2.6 has a few updates on profile builder, but not sure if above feature can be addressed by the 2.6.
