### ISSUE TITLE
Too many redirects on Jet Forms submit

### ISSUE THREAD

**Issue by diickens** [CrocoBlock/suggestions#2195]
**Describe the bug**
Hello there. I made a custom form for a customer with lots of fields and also some file upload.

The problem is, when I hit submit it tells me, that there are too many redirects. Also the url doesnt stay on same page (https://lietreu.ch/wohnungsbewerbung) it switches to root page (lietreu.ch) and tries to submit the variables there (https://lietreu.ch/?status=validation_failed&fields=personalien_haustiere%2Cpersonalien_kinder%2Cfield_name&values%5Bpost_id%5D=2976&values%5Bliegenschaft_wohnung%5D=asdf&values%5Bvermieter_name%5D=asdf&values%5Bliegenschaft_adresse%5D=asdf&values%5Bvermieter_telefon%5D=34834&values%5Bvermieter_kontaktieren%5D=Ja&values%5Bpersonalien_geschlecht%5D=Herr&values%5Bberuf_arbeitgeber%5D=medafd&values%5Bberuf_telefonnummer%5D=4054054&values%5Bpersonalien_vorname%5D=asdf%20&values%5Bpersonalien_name%5D=asdf&values%5Bpersonalien_strasse%5D=sadf%20a8&values%5Bberuf_einkommen%5D=4384848&values%5Bberuf_kontaktieren%5D=Ja&values%5Bpersonalien_Ort%5D=asdfsadf&values%5Bpersonalien_plz%5D=4343&values%5Bpersonalien_telefon%5D=069658&values%5Bpersonalien_email%5D=marc.dick%40xenoteam.ch&values%5Bpersonalien_nationalit%C3%A4t%5D=Schweiz&values%5Bmietvertrag_termin%5D=2022-11-30&values%5Bpersonalien_geburtsjahr%5D=1992&values%5Bpersonalien_Zivilstand%5D=ledig&values%5Bmietvertrag_monatsmieten%5D=3%20Monatsmiete&values%5Bpersonalien_haustiere%5D=0&values%5Bpersonalien_kinder%5D=0&values%5Bversicherung_gesellschaft%5D=asdf&values%5Bversicherung_police_nummer%5D&values%5BSubmit%5D)

**To Reproduce**
Try to fill out the form on the website mentioned
https://lietreu.ch/wohnungsbewerbung/

**Screenshots**
<img width="1403" alt="Bildschirmfoto 2020-11-20 um 10 23 10" src="https://user-images.githubusercontent.com/1793544/99783224-7068ea00-2b1a-11eb-8c48-73ff45490028.png">

**Comment by Floydtm** [comment]
I don't know how your form is configured. Please contact our support team and grant access to the site. The guys will try to help you. Thanks you!

**Comment by alexis-mg** [comment]
Hi guys, I have the same problem, could anyone solve it?
