### ISSUE TITLE
JetAppointment: Possibility to style fully booked dates (generally available but no time slots left) by css selector

### ISSUE THREAD

**Issue by LisaMaNi22** [CrocoBlock/suggestions#2198]
JetAppointment plugin:
In the appointment booking process when viewing the calendar, 
NOW:
- you CANNOT SEE at first sight WITHOUT CLICKING WHICH DATES ARE ALREADY FULLY BOOKED. 
- They look just the same as the other available dates 
- the customer has to click on every single day to see wether there are time slots left available or not
- when we have a quite full calendar this is very nasty for the customers!!!

OUR REQUEST:
- our customers WANT TO SEE at first sight WITHOUT CLICKING on every single date WHICH DATES HAVE available timeslots!!!
- So please make the already-booked-out dates stylable separately by css selector
- automatically add css class, for example ".jet-apb-calendar-date--full" to the div together with the current class .jet-apb-calendar-date
- just like you already have it for the disabled dates ".jet-apb-calendar-date.jet-apb-calendar-date--disabled"
- like this you can see at first sight which days are actually worth clicking because they DO have free time slots while the others with the new selector (e.g. .jet-apb-calendar-date--full) are marked e.g. by different colors so the customers know they are already full

THE RESULT
would be for example
- First sight calendar overview with 3 colours 
--- green for bookable days with available time slots (by selector .jet-apb-calendar-date)
--- grey for disabled days (by selector .jet-apb-calendar-date--disabled)
--- red for already fully booked days (by NEW selector .jet-apb-calendar-date--full)

We have spent a whole week looking for a plugin fitting our needs and your JetAppointment PLugin is the only one out of a minimum of 20 plugins we tested which is well developed and flexible to do what we want.
This issue described above is the only little but crucial point why we would not be able to decide to use it.
PLEEEEEEEASE MAKE IT POSSIBLE :-))
We are happy to write you amazing reviews and recommend you to all our collegues and customers!!!
Thanks for your help & best wishes from Germany! Lisa

**Comment by catherinewiltshire** [comment]
+1

**Comment by MakhonkoDenis** [comment]
Version 1.3.0 
If the date is fully booked, the .jet-apb-calendar-date-disabled class is added to it.

**Comment by avs-alexandra** [comment]
+1
