### ISSUE TITLE
Jetengine - missing remove button on listing grid (maybe bug?)

### ISSUE THREAD

**Issue by joseehilton147** [CrocoBlock/suggestions#2199]
I dont know if was planned but when we create a listing grid posts query come with 0 items... if we create a single item we cant remove them... is this right? doesnt seems right for me...

if we add another item the remove button shows up... see image 2

![1](https://user-images.githubusercontent.com/53986027/99864427-f79d7880-2b81-11eb-9a3a-e32ee85afd19.png)
![2](https://user-images.githubusercontent.com/53986027/99864477-4fd47a80-2b82-11eb-8ce8-139c8f7f443b.png)

**Comment by Floydtm** [comment]
at the moment this does not affect the work of the plugin. We'll fix this if possible. Thanks you!
