### ISSUE TITLE
Adding Image Upload button to Jetengine WYSIWYG form field.

### ISSUE THREAD

**Issue by satomiao** [CrocoBlock/suggestions#2201]
Currently there is no option for users to upload image when they submit a post via Jetengine front-end form. It is very inconvenient for them to compose a decent blog post with texts and images unless they upload the images to third-party platform first.  Please consider to implement this functionality.

**Comment by Floydtm** [comment]
We will not do this. It is not safe. Thanks you!

**Comment by ATSFNL** [comment]
See also post: https://github.com/Crocoblock/suggestions/issues/2586#issuecomment-879796065
WP USER FRONTEND plugin has this functionality. I switched to Crocoblock and then find out they do not have this option!

**Comment by thiagosouzafx** [comment]
> See also post: [#2586 (comment)](https://github.com/Crocoblock/suggestions/issues/2586#issuecomment-879796065)
> WP USER FRONTEND plugin has this functionality. I switched to Crocoblock and then find out they do not have this option!

Not only this one, ACF does aswell and even gives you the option to enable it in the back-end.

I really need this functionality as i'm creating a news blog that often need to add images in the body of the post.
![image](https://user-images.githubusercontent.com/25484147/127021674-a0639ff7-a623-4e2f-bbfe-719f18df506c.png)

**Comment by MolyMalon** [comment]
Yo tambien tengo un blog de noticias y estoy pensando en cambiarme ha ACF de nuevo con ACF Forms Elementor
