### ISSUE TITLE
JetWooBuilder - Widget price bug

### ISSUE THREAD

**Issue by Camilo517** [CrocoBlock/suggestions#2203]
Hi
When you add the price widget, and add two variations, one with one price and one with another, the price widget does not update

It should be updated according to the price of the variation that has been selected

**Comment by Floydtm** [comment]
I think you're talking about a widget on a single product. If I understand you correctly, the widget should not change the price. It shows the price range https://prnt.sc/vvtyks after choosing a product option the price is displayed here https://prnt.sc/vvtz9w
