### ISSUE TITLE
Jetwoobuilder products loop doesn't show all thumbnails

### ISSUE THREAD

**Issue by TODO4EVER** [CrocoBlock/suggestions#2204]
**Describe the bug**
When I am using custom loop, not all thumbnails appear.
https://i.imgur.com/5lSKinL.png
This only happens when I use products loop and assign a template for the grid
This doesn't happen in firefox, but still occur when using Chrome and Edge
This still happens on my phone using Chrome & Samsung Internet
This doesn't happen when I use Kava theme, but still occur when I use astra pro or hello elementor
This doesn't happen in List format, only grid format
This doesn't happen when I use products grid.
When I hover over the title the thumbnail suddenly reappears, looks like lazy loading behavior ?
I have "Enable Woocommerce Pages Templates Styles" enabled.
No server side nor plugin caching is enabled

**To Reproduce**
1. Imported a custom shop page
2. Created a grid template & List template
3. Used these templates in the switching area in the products loop

Plugins list
https://i.imgur.com/cKnn8gl.png
Everything is up to date

**Comment by Floydtm** [comment]
We checked everything and everything seems to work as it should. Please contact our support team and provide access to your site. The guys will help you solve this issue. Thanks you!
