### ISSUE TITLE
Jet Popup to appear only on desktop/mobile 

### ISSUE THREAD

**Issue by evytgat** [CrocoBlock/suggestions#2208]
Add option to hide Jet Popup by device (desktop/mobile/tablet)

**Comment by shinTM** [comment]
done v1.5.0

**Comment by evytgat** [comment]
Sorry, but I'm new here.
Thas means that the offer will be made in the version 1.5.0?

**Comment by shinTM** [comment]
hi, meaning that this has already been done in v1.5.0, but this version has not yet been released, i think tomorrow(26.11.20). By this time I plan to do several more issues. Anyway https://prnt.sc/vpx5yc
