### ISSUE TITLE
RTL Bugs: Reversed Product Carousel buttons

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#2214]
**Describe the bug**
I'm using an RTL site, and when clicking the product carousel arrows, the products carousel is moving the opposite way.

**To Reproduce**
1. Go to 'http://omerg24.sg-host.com/'
2. Click on 'one of the carousel buttons'
3. See error: carousel going the opposite way

**Expected behavior**
carousel is moving the opposite way.

**Additional context**
There is a couple more RTL issues and I'll add them soon. I am 100% willing to cooperate and help to solve this bugs. Thank you!

**Comment by ghost** [comment]
The same error goes for the 'Advanced Carousel' element

**Comment by UraraReika** [comment]
Latest release!
