### ISSUE TITLE
RTL Bugs: Checkmark is overlapping text when using 'Ajax add to cart' feature.

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#2215]
**Describe the bug**
On the 'Product Grid' widget with the 'Ajax add to cart' option, when you click the 'add to cart' button, there is a animated checkmark spinning and overlapping the text.

**To Reproduce**
1. Go to 'http://omerg24.sg-host.com/'
2. Click on 'one of the carousel 'add to cart' buttons'
3. See error: spinning and overlapping checkmark icon.

**Expected behavior**
Not having the checkmark overlapping the text. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74980230/100126061-2d927380-2e86-11eb-8435-6e94ca5f11e8.png)

**Additional context**
There is a couple more RTL issues and I'll add them soon. I am 100% willing to cooperate and help to solve this bugs. Thank you!

**Comment by UraraReika** [comment]
Latest release!
