### ISSUE TITLE
Remove Filter button should have visibility function

### ISSUE THREAD

**Issue by msulaimanmisri** [CrocoBlock/suggestions#2217]
User should have capabilities to make the button always appear and clear the filters or appear only when someone checked the input.

your documentation show that the remove filter appear even though the user are not checked anything in the filter (please refer to https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-use-remove-filters-widget/ )

Please give this function available for the next update.

**Comment by Floydtm** [comment]
@msulaimanmisri, hi! [remove filter.zip](https://github.com/Crocoblock/suggestions/files/5660344/remove.filter.zip)
This filter works right now. Thanks you!
