### ISSUE TITLE
Add text align buttons to WYSIWYG editor in frontend forms

### ISSUE THREAD

**Issue by peterforensys** [CrocoBlock/suggestions#2218]
I think that's pretty understandable. I would like to have text-align buttons in the WYSIWYG editor on the frontend form of Jet Engine. 

![image](https://user-images.githubusercontent.com/69253541/100206788-121b7d00-2f07-11eb-9a0c-a76511761af3.png)

**Comment by blackge** [comment]
Upvoted. 

I'd go further on this and allow a more complete set of functionality on the form. Particularly the formatting options (e.g. H1, H2 etc) and attach image.

**Comment by kaskad88** [comment]
Added for the next version. Thanks for your report!
