### ISSUE TITLE
Add color filters widget in SmartFilters

### ISSUE THREAD

**Issue by addekk** [Crocoblock/suggestions#222]
Can I ask you to add color filters? Currently, we can create based on a verbal choice, but it would be good to choose with color windows.

**Comment by croydonrugs** [comment]
This is the most have feature for WooCommerce, Premmerce does it and WOOF Product Filters too.
Are you going to up the game for a top-notch feature that not only allows HexColorCodes but also to use a custom image, like in the attached files???
![000-Ticket-Colour-Selection-Dynamic-Filters](https://user-images.githubusercontent.com/51163771/58560067-3916c700-821c-11e9-8c47-87c517b4162d.PNG)
![000-Ticket-Colour-Selection-Dynamic-Filters2](https://user-images.githubusercontent.com/51163771/58560069-3916c700-821c-11e9-8eb8-e0ab676de46d.PNG)

**Comment by Morgunov-Vitaly** [comment]
And Add the dynamic color option for dynamic terms and dynamic field widgets at least. To display dynamically colored tags, headers and etc.

**Comment by Floydtm** [comment]
@croydonrugs, Hi! We have already added a new visual [filter](https://crocoblock.com/widgets/visual-filter/).
@Morgunov-Vitaly, Hi! Once elementor implements it will be available in our product.
