### ISSUE TITLE
Jetforms Recurring Payments

### ISSUE THREAD

**Issue by ekazoom** [CrocoBlock/suggestions#2220]
I'd like to see a jetform feature where we can charge people for access to add/edit a jetengine CPT entry via the frontend jetforms.

An example would be a directory listing site where they pay to be a part of the directory.  As long as their subscription is active, their listing will be live and/or they will have access to editing their listing.  If their subscription lapses, their listing will be removed and/or they won't be able to edit their listing.

This could be implemented via woocommerce and a subscription plugin like Yith woocommerce subscription:
https://wordpress.org/plugins/yith-woocommerce-subscription/

Or a native solution to pay recurring fees for this would also be welcome.

**Comment by anrob** [comment]
+1 native solution to pay recurring fees

**Comment by julianderyk** [comment]
+1

**Comment by EvgenDoman** [comment]
+1

**Comment by Willitbang** [comment]
+1

**Comment by Gabrymi93** [comment]
+1

**Comment by Noob86** [comment]
+1 (or as many as possible) for adding recurring payments in Jet Formbuilder. I've been looking for a plugin to do this for a really long time now, but even other great form builders struggle with these payment subscriptions. 

Also, we are just a group of volunteers working for a good cause; we don't have the financial room to invest big numbers for just small donations and a few (around 80 at the time) members. We would really love two types of payments: donations and recurring payments for members. I still haven't found the right solution to do this. 🙏🏼🙏🏼

**Comment by GCG82** [comment]
+1 for PayPal and Stripe Addon

**Comment by ethanwanoreck** [comment]
This would be great to have, especially for a membership plugin.

**Comment by girafffee** [comment]
An addon for PayPal Recurring payments has been released
https://jetformbuilder.com/addons/paypal-recurring-payments/

For Stripe will be in the future
