### ISSUE TITLE
Add "Users" field type to JetEngine

### ISSUE THREAD

**Issue by cvl01** [CrocoBlock/suggestions#2222]
**Please, describe the feature request, making it clear to understand.**

In JetEngine, I'd like to see a new field type "Users", a select field like the current "Posts" field type, but then for users.

This way you can select 1 or multiple users in a custom field. 

Some example scenarios:
- You have a CPT for events, and you want to select all users that manage this event.
- You want to add a second author field to your CPT or add an custom author field that allows to select multiple authors.

**Add an example of where this feature is already implemented.**

Advanced Custom Fields has this type of field, currently it is the only field I am missing from JetEngine to be able to fully replace ACF with JetEngine. 

ACF documentation on the user field, can be found here: [ACF User Docs](https://www.advancedcustomfields.com/resources/user/
)

**Comment by Kyzoe** [comment]
+1

**Comment by witoldlitwin** [comment]
That's what I'm missing from JetEngine too. Please add this as soon as possible.

**Comment by DaxPG** [comment]
While yes this is super cool to be added. Is it possible to add jt by combining acf with jetengine?

**Comment by arekuki** [comment]
+1

**Comment by witoldlitwin** [comment]
> While yes this is super cool to be added. Is it possible to add jt by combining acf with jetengine?

In theory, yes. I even tried that, but for some reason wasn't able to access user's values in Elementor. I probably did something wrong, but didn't dig around it long enough to find out what it was.

**Comment by julianderyk** [comment]
+1

**Comment by cvl01** [comment]
If you are implementing this, please also add a filter to customize the name of the user.

See for what I mean #2315

**Comment by kochhase** [comment]
yes users are very importent for membership sites. See as well #2131. we need some posibilty for relations of users and cpt like 1:1 and 1:n and m:n. 
pleasee !!!

**Comment by MateuszKlups** [comment]
+1

**Comment by rolfkrue** [comment]
+1

**Comment by kochhase** [comment]
please give us an timeline !!

**Comment by fabio323ti** [comment]
+1

**Comment by jakobmayerhofer** [comment]
Yes, this would also help me with my projects.

**Comment by kochhase** [comment]
have a look at the beta 2 of jetengine .2.11. there is now some progress

> Yes, this would also help me with my projects.

**Comment by jakobmayerhofer** [comment]
> have a look at the beta 2 of jetengine .2.11. there is now some progress
> 
> > Yes, this would also help me with my projects.
> 
> 

Where can I view the Beta version changelog / is it possible to test beta versions?

**Comment by MjHead** [comment]
Added with 2.11.0 (as part of new relationships)
