### ISSUE TITLE
Register Custom Post Type Meta fields in wordpress REST API.

### ISSUE THREAD

**Issue by blackge** [CrocoBlock/suggestions#2227]
Currently the custom post types are registered in the REST API, however, the API does not allow any of the custom meta fields that are associated with the CPT to be managed through the API.

For any integrations with external systems (e.g. through Zapier) this significantly limits the value of creating CPT's using JetEngine.

**Comment by juustcrnt** [comment]
Any news on that ? Currently my entire system is built on Jetengine and I really need to be able to update my metadata rapidly

**Comment by zorrobiwan** [comment]
Would be really useful for me too !
Thanks !

**Comment by andrewpros** [comment]
Any updates?

**Comment by SaidBahaDev** [comment]
@Floydtm any update ? i think this is more important to have for CPT then to have for CCT ?? toolset , metabox, pods ... already have this option but not jetengin so sad

**Comment by SaidBahaDev** [comment]
@juustcrnt i am on the same situation , did you find a solution ? thnks

**Comment by chunterb** [comment]
I am facing a similar issue at the moment. I am looking to create CPT's externally with an API (preferably the WP API).

Are there any alternate approaches that someone can suggest for now?

I know of CCTs, but I've learned that it is not really possible to make standalone pages for each CCT. Please correct me if I am wrong about this.

Thank you.

**Comment by SaidBahaDev** [comment]
@chunterb you can use toolset or pods or metabox they all support rest api, only jetengine that instead of adding it first to CPT they are doing it for CCT !

**Comment by andrewpros** [comment]
@chunterb Only by some code additions, but, there is no documentation how to do it, i needed to know this only cuz my client is using this plug-in, but overall it seem it is not created for devs, so no technical php docs, no way to know what and how to change to at least connect things, the only way is to wait for updates, due to this and wp api being slow in my case, i will not use it for the original idea.

One thing to note, using CCT makes you dependant on the plugin, so consider it carefully.

**Comment by Ilyagurm** [comment]
This would be super useful

**Comment by zorrobiwan** [comment]
any news ?

note that https://fr.wordpress.org/plugins/wp-rest-api-controller/ does the trick

**Comment by MjHead** [comment]
Added with 3.0.0 update

**Comment by zorrobiwan** [comment]
amazing, thx !

**Comment by zeroazulagencia** [comment]
I can't figure this, they say in 3.0.0 the Custom Post Type Meta is available in API but still can't see it...

**Comment by muhammadmoazzam** [comment]
> I can't figure this, they say in 3.0.0 the Custom Post Type Meta is available in API but still can't see it...

For future ref:
I also faced the same issue but I forgot to add the Content-Type in the request headers.
Make sure you're setting the **Content-Type: application/json** in the header

Example: 
headers = {
  'Content-Type': 'application/json',
 }
payload = {
  "title": "Something",
  "status": "draft",
  "meta": {
    "_meta_key": "value to send"
  }
}

**Comment by ManishCodeLover** [comment]
Any way to add api data in custom post type
