### ISSUE TITLE
JetThemeCore - Request to add custom fonts feature like Elementor Pro

### ISSUE THREAD

**Issue by nejumislam** [CrocoBlock/suggestions#2229]
Can you guys please add an option to add custom fonts on JetThemeCore as like Elementor Pro?

Last day I trayed to add custom fonts to a project but I did not find any easy way to add custom fonts to my website like Elementor Pro. I am a user of the All-Inclusive plan so not interested to add a third-party plugin to add this feature which can slow down my website.

Request: Add custom fonts feature on JetThemeCore.
Example: Elementor Pro has this feature.

Thanks

**Comment by Floydtm** [comment]
I understand that this is important to you, but right now we cannot do it. As soon as we get more requests we will come back to this. Thanks you!

**Comment by rquirola** [comment]
+1 Many of us are promoting the use of Elementor Free + Crocoblock, custom fonts are an essential feature to continue with this plan, please reconsider the need to incorporate custom fonts.

**Comment by Elsteck** [comment]
@Floydtm with the recently new functionality of JetThemeCore you may consider reopening this issue, also in light of GDPR problems with Google fonts that makes being able to locally source (custom) fonts a necessary feature

**Comment by mojtababouraghi** [comment]
Hello
I also agree with the addition of this feature
please check it
is very important
Thanks.

**Comment by ALPSIT** [comment]
Also agree, I pretty much purchase Elementor Pro for Custom Fonts feature.

**Comment by Elsteck** [comment]
@Floydtm can you please reopen this issue? Now with the update JTC 2.x and Gutenberg support it has become more important to be able to use a custom font. Also in light of GDPR legislation.

**Comment by buithucdong** [comment]
I think this is a necessary feature for every project and will be more reliable and compatible if built from the Crocoblock team.

Hope you pay attention to this issue.

**Comment by righijavier** [comment]
+1

**Comment by Marcoqwerty78** [comment]
Super interested, also because its a feature of Elementor Pro and if you buy the Pro you will carry of tons of Widged and stuff that slow down the website.
We bought this amazing suite also to forget Elementor Pro stuff.

**Comment by Elsteck** [comment]
For the time being maybe https://wordpress.org/plugins/custom-fonts/ offers a solution
