### ISSUE TITLE
JetElements features

### ISSUE THREAD

**Issue by VeikiCroco** [CrocoBlock/suggestions#223]
1) Jet Elements post grid: Ability to select individual "Pages" from a drop down list of pages. (rather than entering id's). Similar to selecting Categories for Posts, which has a drop down of categories.

2) Jet Elements post grid: Some type of animation when hovering over the post image. The only animation currently is when you hover over the button. Often i prefer no button, so some kind of animation on the image would be nice (similar to some of the banner effects).

3) Jet Elements banner items: Ability to select a "Page" to link to from a drop down list. As an alternative to entering a "Link".

**Comment by kaskad88** [comment]
1, 3 - break backward compatibility
