### ISSUE TITLE
Using jetappointment without having to select a service

### ISSUE THREAD

**Issue by PrimeMediaNL** [CrocoBlock/suggestions#2230]
Dear Crocoblock,

The jetappointment widget looks really awesome, like all your tools.
However, i miss a very basis feature in the widget, and that is being able to use it without having to select a service or anything like that.

Imagine someone wants to use it as a reservation form for a restaurant. There is no need to select a service, cause by default people know it is for a reservation. Or someone wants to make appointment at a barber, without having to select what kind of haircut and so on. Just a simple appointment; choose the day, time., fill in personal info and that's it.

Or if that is not possible, being able to select a default service would also work. Then you can set the default service to something like: "reserver a table" or "Make appointment", without the website user having to select it.

Thank you

Karim

**Comment by futureyoon** [comment]
I have not used jetappointment much yet (going to use alot) but this suggestion comes with little surprise. 
Just would like to clarify with you that there is no shortcode that is service is already selected? 
something like [jetappointment service ='1' employee ='1']

**Comment by PrimeMediaNL** [comment]
I don't mean a shortcode. Just the option to make an appointment via the calender without having to choose a service first . I can imagine if you have several services that it is handy to choose the service first when making an appointment. But when you have only one service, it makes no sense to have to choose the service first. Just selecting the date, the time and fill in the personal information is more then enough. In the current version you can't make an appointment without having to select a service first. I think adding this option to the widget makes it much more powerfull for website builders.

I hope you understand what i mean

**Comment by MakhonkoDenis** [comment]
Hey. 

It's very easy to do.
1. Add one service for example "Restaurant"
2. Copy the service ID. https://prnt.sc/vyb3v3
3. Open the appointment form
4. Adjust the appointment field https://prnt.sc/vyb52b
	- Get Service ID From: Manual Input
	- Set Service ID: Your Service ID

**Comment by PrimeMediaNL** [comment]
Hello Denis,

Thank you so much for the help, i really thought it can't be done. :)

Really awesome..

**Comment by MakhonkoDenis** [comment]
@PrimeMediaNL  You're welcome ;)

**Comment by Uxramon** [comment]
Can explain or upload the screenshots again? 

I have problems to configure the id services

**Comment by mikkiweb** [comment]
would be appreciated, having trouble to set the default service
