### ISSUE TITLE
JetAppointments or JetBooking Calendar Picker

### ISSUE THREAD

**Issue by vanporciuncula** [CrocoBlock/suggestions#2232]
I would like to suggest to have a more intuitive picker to create a date range when selecting the check-in and check-out date. Pretty much like agoda.com or any other booking engine. This will be a big help for users, specially those who are already accustomed to the other booking engines available online.

**Comment by futureyoon** [comment]
+1

**Comment by WardenCommander** [comment]
+1

**Comment by Floydtm** [comment]
I understand that this is important to you, but right now we cannot do it. As soon as we get more requests we will come back to this. Thanks you!

**Comment by zhapes** [comment]
This it’s needed a long time ago, the date picker it’s horrible planned. the date pickers of the form and elementor widget search don’t match each with other, talking about User experience this is a complete mess. I buyed this plugin thinking after two years of begin launch it was to be better but not it’s a total mess omg.
