### ISSUE TITLE
JetWooBuilder do not customize WooSubscriptions "Related Subscriptions" section

### ISSUE THREAD

**Issue by alexmathias** [CrocoBlock/suggestions#2235]
Hey there!

I notice that WooBuilder do NOT apply typography to "Related Subscriptions" in the "Thank you order details" widget.
This section only appears when WooCommerce Subscriptions is installed and active.

![image](https://user-images.githubusercontent.com/66876358/100656140-02e36780-332b-11eb-899c-ea9df0324722.png)

**Comment by Floydtm** [comment]
I understand that this is important to you, but right now we cannot do it. As soon as we get more requests we will come back to this. Thanks you!
