### ISSUE TITLE
Files from completed forms added as attachments.

### ISSUE THREAD

**Issue by Tomgitom** [CrocoBlock/suggestions#2236]
Currently, only a link to a file is produced when a form is completed. 

This rules out jet engine for our job board, it would be good if files were handled like CF7 and you could deliver the file as an attachment.

This would enable us to use zapier to send files, the true issue here is that we want to create a candidate on our CRM automatically everything works fine via a webhook, all but the file. So if an email could be sent with an attachment we could use Gmail as a trigger to parse the data instead of a webhook.

Having this functionality would mean that recruitment companies and job boards could use crococlobcks as users uploading Cv's is an integral part of the process.

**Comment by Floydtm** [comment]
@busmoose, hi, right now our forms can do it https://prnt.sc/w2d8kd However, only a logged in user can do this
