### ISSUE TITLE
Add a widget to generate a pdf at the end of a form 

### ISSUE THREAD

**Issue by Hannah2626** [CrocoBlock/suggestions#2237]
hi

I found useful to add a functionality at the end of a form that allows generating a pdf as elementor.
https://www.youtube.com/watch?v=po4rJ9DX988
The pdf will be generated when we click send at the end of the form and we can store it or dend automatically via the notification.
Best regards
Hannah

**Comment by anderoav** [comment]
Any updates?

**Comment by jamsheehan** [comment]
+1

**Comment by BatcomAus** [comment]
There are multiple requests like this one but none of them are being worked on and it's been over 18 months since this was suggested

**Comment by Crocoblock** [comment]
Hello! I am glad to inform you that we have just released the PDF Attachment Addon. Feel free to [check it out](https://jetformbuilder.com/addons/pdf-attachment)
