### ISSUE TITLE
JetElements Posts ordering 

### ISSUE THREAD

**Issue by WildHund** [CrocoBlock/suggestions#225]
Please add to Posts widget the ability to order posts by the number of views of the post. E.g. those posts that are most often opened by visitors are displayed above.

**Comment by Floydtm** [comment]
@WildHund 
You should have the functionality of counting the number of views of posts and saving it in the post-meta. Then, using Сustom Query Generator, you can get what you want by pointing the meta key where the number of post views is stored.
https://prnt.sc/nvabu0
