### ISSUE TITLE
Post restriction rules in profile builder

### ISSUE THREAD

**Issue by atalzen** [CrocoBlock/suggestions#2250]

**Comment by atalzen** [comment]
In Jetengine >> user porfile builder >> advanced: I selected my custom post type and user role and set the number of post allowed to 1. Is there any possibility to allow the user to post again when he deleted his first post. It appears that the post count stay 1 even when deleted and therefore the user cannot post anymore.

**Comment by Floydtm** [comment]
You must completely delete the message. If it is in thrash, then delete it. Then the rules will work
