### ISSUE TITLE
Out of stock button missing

### ISSUE THREAD

**Issue by slayeat** [CrocoBlock/suggestions#2253]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by slayeat** [comment]
Hello, I am using JetWooBuilder. When an item is out of stock  there is nothing which says "out of stock" the add to cart button just fade away. Now because of this I have to add new plugin. I tried to search for info around but nothing pipes up for this topic.

**Comment by UraraReika** [comment]
Hello @slayeat!

Can you be more specific. In which widget you get such issue? 

For example if you use Single Product Add to Cart widget from JetWooBuilder and product is out of stock then you will get this message https://prnt.sc/vzktpx. 
 
If you use some loop widget then it just can be hidden or if you want it to be visible then it will be look like this https://prnt.sc/vzkvxn.
