### ISSUE TITLE
Add Dynamic option to the BUTTON Fold & Unfold field

### ISSUE THREAD

**Issue by pintolog** [Crocoblock/suggestions#226]
There is Dynamic option to the content field but not to the **Button** field for the Fold & Unfold option.

Please make it Dynamic also so it will be possible to build with JetEngine
Thanks.

![image](https://user-images.githubusercontent.com/7497319/57026922-9894ad80-6c43-11e9-9205-1f329e7dc08b.png)

**Comment by pintolog** [comment]
More Info:
The **FOLD & Unfold text fields** should have a **Dynamic capability** to connect it to JetEngine field so it can be connected & controlled to a JetEngine filed that are created.

**Comment by kaskad88** [comment]
Added in JetTricks 1.3.3
