### ISSUE TITLE
JetTricks Tooltip and Listing Grid LazyLoad: tippy is not defined

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#2261]
1. Creating a new listing (CCT data source).
2. Add the question icon and enable the Tooltip option.
3. Add the Listing Grid widget and enable the LazyLoad function there.

I see a preloader on the page, it is constantly spinning, data is not loading, and I see an error in the browser console https://yadi.sk/i/MIAaGhNG0r6ghw

If you disable Lazyload, everything loads correctly.

And in addition. This is not a bug, but it would be good to add dynamic data to the Tooltip.

**Comment by kaskad88** [comment]
Fix for the next versions JetEngine and JetTricks.. Thanks for your report!
