### ISSUE TITLE
JetElements Image Comparsion and Listing Grid LazyLoad: Cannot read property 'scanPage' of undefined

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#2262]
1. Creating a new listing (CCT data source).
2. Add Image Comparsion widget.
3. Add the Listing Grid widget and enable the LazyLoad function there.

I see a preloader on the page, it is constantly spinning, data is not loading, and I see an error in the browser console https://yadi.sk/d/FYF_Xw7vhd6ywg

If you disable Lazyload, everything loads correctly.

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
