### ISSUE TITLE
Jet engine Dynamic Visibility: Add date and time visibility

### ISSUE THREAD

**Issue by P258tiwari** [CrocoBlock/suggestions#2263]
Great feature rich plugin

I'm using jet engin for my event website and attendance website for my client. Where I need dynamic visibility based on time. For e.g. Only people submit form in day time like 8:00AM to 9:00PM but write now its not possible by using jet engine.
For refrance you check Dynamic Content plugin for wordpress
https://www.dynamic.ooo/widget/dynamic-visibility-for-elementor/

Thanks for helping me 
I hope this option we will see in future in jet engine 
😊😊

**Comment by stapolin** [comment]
Not sure if it's always worked, or not, but I had to do something similar recently. I needed to show a button x number of days before an event date (date custom field). What I did was 

> 'Show element if condition is met'
> Condition 'Less Than'
> Field > Custom date field
> Value > '+7 day'
> Datatype > Datetime

I'm basically just using the PHP format for calculating the number of days.

**Comment by 93petter93** [comment]
+1

**Comment by Poklos** [comment]
@stapolin does it work that way??
I need to display button on posts older than 2 years but i cannot figure it out how...
I used similar settings as yours but no success. 

'Show element if condition is met'
Condition 'Less Than'
Field > Post Date
Value > '-2 year'
Datatype > Datetime

**Comment by RibeiroM4E** [comment]
> Not sure if it's always worked, or not, but I had to do something similar recently. I needed to show a button x number of days before an event date (date custom field). What I did was
> 
> > 'Show element if condition is met'
> > Condition 'Less Than'
> > Field > Custom date field
> > Value > '+7 day'
> > Datatype > Datetime
> 
> I'm basically just using the PHP format for calculating the number of days.

Not working for mme as well...

**Comment by ofmarconi** [comment]
News?

**Comment by Willitbang** [comment]
+1

**Comment by Radzio1615** [comment]
+1

**Comment by kaskad88** [comment]
> @stapolin does it work that way?? I need to display button on posts older than 2 years but i cannot figure it out how... I used similar settings as yours but no success.
> 
> 'Show element if condition is met' Condition 'Less Than' Field > Post Date Value > '-2 year' Datatype > Datetime

Fix in the next version JetEngine ( 3.0.5 )

**Comment by secondsky** [comment]
@kaskad88 thx for letting us know. I just realized that the last version broke this seemingly. Worked like a charm up to the last release 3.0.4

Any estimated release date for the new version?

**Comment by stapolin** [comment]
@RibeiroM4E @P258tiwari @kaskad88 
This is how I have it now, and it works fine.

![screenshot-photographytoursireland ie-2022 09 28-23_41_10](https://user-images.githubusercontent.com/17647985/192901344-553d77a3-f5d9-4e25-9e6a-ddcc3700928c.png)

**Comment by secondsky** [comment]
> @RibeiroM4E @P258tiwari @kaskad88 This is how I have it now, and it works fine.

@stapolin 
And you are sure that you have Version 3.0.4 ?
For me the date functions stopped to work with that version.

**Comment by kaskad88** [comment]
@secondsky  JetEngine v3.0.5 will be released in a few days

**Comment by kaskad88** [comment]
Added in JetEngine v3.1.0
