### ISSUE TITLE
An Infinity Scroll option for JetEngine Listing Grid

### ISSUE THREAD

**Issue by Shininglow** [Crocoblock/suggestions#227]
The Infinity Scroll option is needed to display the larger number of posts on scroll instead of using the pagination for JetEngine Listing Grid. 
More details: https://www.facebook.com/groups/CrocoblockCommunity/permalink/2406796709411736/

**Comment by Floydtm** [comment]
+ #304

**Comment by stasonua0** [comment]
+1

**Comment by utich78** [comment]
+1

**Comment by crypto-vault** [comment]
+1

**Comment by toopixel** [comment]
+1 this is a must have

**Comment by Movinmotion** [comment]
Would be great to have an infinite scroll options next to the load more function.

**Comment by logobby** [comment]
It's very very needed

**Comment by Floydtm** [comment]
#1648

**Comment by logobby** [comment]
Hi,
I can see that the milestone was for 2.3.0 but we are already on 2.4.7...have you another milestone?
Thanks in advance

**Comment by Movinmotion** [comment]
Any update on this functionality? 

I believe there are lots of users that would like to see this feature. 

Hope to hear from you guys soon.

**Comment by trueqap** [comment]
Hello, What's news with this? Can we help? :)

**Comment by kaskad88** [comment]
I merged this issue with #1247, which is on the same subject so we could deal with it more efficiently.

**Comment by futureyoon** [comment]
I see those tasks regarding infinite scroll were merged into this.. 

and all of tasks status is closed. so I would like to confirm if 'infinite scroll' in jetblog has been implmented? 

Anyone can confirm this?
