### ISSUE TITLE
JetEngine>Listing>Layout switcher(Like in Product Loop widget)

### ISSUE THREAD

**Issue by lolirado** [CrocoBlock/suggestions#2277]
Add Layout switcher Like in "Product Loop" widget in Listing widget
Why you do this to us ? LOL
You give this features to the new girl "JetWoobuilder" but totally forgot about your main loving family "JetEngine".

**Add an example of where this feature is already implemented. **
 in Product Loop widget
[](https://www.youtube.com/watch?v=tG6kIyUqH1c&t=175s)

**Comment by stasonua0** [comment]
+1 Important function

**Comment by vogelmy** [comment]
+1

**Comment by rh-hridoy12** [comment]
Hi every one, you can use jet tabs for this problem ..

**Comment by wearenv-digital** [comment]
+1 ! This is so vital

**Comment by namealreadytaken2** [comment]
+1

An idea I would like to add: 

Switching layouts should show different column options for Desktop and mobile devices:

For example:
Desktop -> Switch between 3 or 4 columns
Mobile -> Switch between 1  or 2 columns

**Comment by mkAbele** [comment]
lol, any updates?

**Comment by unitedonline** [comment]
Any news on this?

**Comment by kaskad88** [comment]
@unitedonline the status of this issue is **In work**

**Comment by MjHead** [comment]
Beta version released - https://github.com/Crocoblock/suggestions/issues/7100

Close current issue in prefer of beta version-issue.

**Comment by Duckstick** [comment]
> Hi every one, you can use jet tabs for this problem ..

You can but you are limited to where you can have the switcher button. This beta release is amazing.
