### ISSUE TITLE
Hover color on Dynamic Field

### ISSUE THREAD

**Issue by joseehilton147** [CrocoBlock/suggestions#2281]
Today we can only define a color for text and we cant define a color for hover (i know we can do that using css, but isnt pratical do that every time we use this widget) so i proprose to let us put hover color on links.

![111](https://user-images.githubusercontent.com/53986027/101491209-3ed98680-3942-11eb-9f83-9157bfeede31.png)

**Comment by Floydtm** [comment]
You can use the dynamic link widget right now
