### ISSUE TITLE
Enable product thumbnails to switch on hover - Disable on Tablet/Mobile

### ISSUE THREAD

**Issue by RefinedEarth** [CrocoBlock/suggestions#2285]
Hi

Please could there be an option to disable this Jetwoobuilder feature when on mobile or tablet -'Enable product thumbnails to switch on hover'.

This is because you obviously cannot hover with a mouse when using mobile or tablet and the effect only happens when you tap on the image which can be confusing to users.

We have received feedback that it makes people think that they are being taken to a different product because the image changed after tapping on it.....however with the hover effect on desktop this has not been a problem.

**Comment by UraraReika** [comment]
Hello @RefinedEarth ! 

In the last release of JetWooBuilder for Elementor have added "Mobile hover on touch Products Grid & Categories Grid widgets". So when you use mobile or tablet and tap on product it shows hover effect, second tap will redirect to the product.

**Comment by Salimoh** [comment]
Hi
is there any method to lazyload hover images? it seems that they all load at once and elementor lazyload feature and wp rocket can not lazyload them

**Comment by UraraReika** [comment]
> Hi is there any method to lazyload hover images? it seems that they all load at once and elementor lazyload feature and wp rocket can not lazyload them

If you use Thumbnails Effect in widgets- https://tppr.me/y1N3Gr then there is no way to use lazy loading because it will breaks widgets layout.
