### ISSUE TITLE
Post Type Name as a Dynamic Field

### ISSUE THREAD

**Issue by Andreas2209** [CrocoBlock/suggestions#2288]
Hi, 
I have different post archives, or pages with listing grid or posts widgets. Some of them have custom queries with different post types. When there is a mix of posts of different post types on one of those pages i want to display the label/name of that post type.
This would be super helpful.

Best regards,
Andreas

**Comment by Andreas2209** [comment]
any news on this issue?

**Comment by schndr-cdn** [comment]
+1

**Comment by Deswegen** [comment]
+1

**Comment by kaskad88** [comment]
Add for the next version v3.0.6
