### ISSUE TITLE
JetAppointment's Dashboard responsive design 

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#2291]
https://prnt.sc/vzbdtw
If the value added through the Form will be too long it crashes the Appointment's responsive design

**Comment by catherinewiltshire** [comment]
Yeah this is quite an eyesore

![Untitled-3](https://user-images.githubusercontent.com/40239762/103538532-43845280-4e8e-11eb-922f-d1a30f50ca46.jpg)

**Comment by hybridmuse** [comment]
Yes! Please fix this

**Comment by molnarbalazs950817** [comment]
+1

**Comment by MakhonkoDenis** [comment]
Hi,
We changed the admin panel in version 1.4.0
