### ISSUE TITLE
Overlapping markers with the same addresses not working on satellite view

### ISSUE THREAD

**Issue by exelentshakil** [CrocoBlock/suggestions#2297]
After updating to the latest version the roadview overlapping is working fine but when switching to satellite view the cluster stuck without showing markers. Can you guys please tell me what happening? It will be a real help as im with it almost for weeks, without solving this it will be a huge waste. If anyone faced same issue and can solve this, it will be a huge help for me.

Roadview (working fine): https://imgur.com/ekdRwL0
Satellite: https://imgur.com/ei2xCwP

1. Marked, "Avoid markers overlapping, Add a slight offset to avoid overlapping markers with the same addresses"
2. Cleared cached millions time.
3. Recreated huge times the same map listing but no luck.

**Comment by exelentshakil** [comment]
@MjHead @MakhonkoDenis Any thoughts please? More detail, map zoom out the bound sometime working for roadview sometimes not, and not working all the time with satellite view, there's always two-three marker staying together and after click its just sliding left-right not zoom to show markers. Also the markers showing on the roadview not showing satellite view just zoomed out when switching to satellite view. I need to fix this asap, please suggest me something to fix it up or its something awaiting for next bug fixes?

**Comment by kaskad88** [comment]
Thanks for your feedback.
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
thanks.
