### ISSUE TITLE
JET Blocks - Dynamic visibility

### ISSUE THREAD

**Issue by Gugutete** [CrocoBlock/suggestions#2305]
**Describe the bug**
After I update my site to wp 5.6 and jetsmartfilters and jet blocks to last ones the dynamic visibility is not working anymore, in my case specific there where many section on dynamic based to be visible only if "In the list" field value... and they was working pretty fine before to update. I use just hello elementor as theme and few pluging, almost just yours.

**Comment by kaskad88** [comment]
Fixed in JetEngine 2.6.1
