### ISSUE TITLE
JetEngine Form: Add Honeypot spam detection

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#2307]
At the moment there is only the possibility to include recaptcha. However, the honeypot method works quite well and is easy to implement. It would be great if we could add such a field to the form.

https://www.thryv.com/blog/honeypot-technique/
https://wordpress.org/plugins/contact-form-7-honeypot/

**Comment by NobleLarry** [comment]
+1 for this. I would also like to see the ability to choose between reCaptcha v2 and v3. reCaptcha v3 currently results in far too many false positives and isn't reliable enough as it filters out some genuine submissions.

**Comment by incircolo** [comment]
+1 for this

**Comment by andretoldo** [comment]
+1

**Comment by kellyrenee814** [comment]
+1

**Comment by serg-pervushin** [comment]
+1

**Comment by dennzo** [comment]
+1 please

**Comment by ghost** [comment]
+1

**Comment by serg-pervushin** [comment]
+1

**Comment by emirefek** [comment]
Why isn't it added yet? It's very easy implementation. It's must thing it 2021. Please add it.

**Comment by schndr-cdn** [comment]
please...

**Comment by juanisidoro** [comment]
HoneyPot works great, it removes a lot of spam. Cheers up crocoblock team! we're waiting

**Comment by schndr-cdn** [comment]
Yes, actually the reason for the need is that we don't have to worry about the GDPR. Google reCAPTCHA brings more work to us..

**Comment by ewancluckie** [comment]
+1 for this

**Comment by IFTTD** [comment]
Definitely need this. At least have the ability to adjust the reCAPTCHA score.

**Comment by mikkelfaartoftjensen** [comment]
+1 for this - needed feature

**Comment by Smalyleinchen** [comment]
+1

**Comment by ArkeyWave** [comment]
+1 for this

**Comment by timo-mediad** [comment]
+1

**Comment by fostira** [comment]
How can we make this happen? ++100000

**Comment by tusharttyagi** [comment]
Lets goooooo + 10000000^257856
Need this. 
I'm desperate.

**Comment by Zegklitz** [comment]
+1

**Comment by mAAzes** [comment]
Aye +1

**Comment by donstefanos** [comment]
In germany DSGVO or GDPR is no fun, so Honeypot would be a faster Solution than Google Solutions. 
Is it not possible to do this with conditional fields and hidden fields?

**Comment by MPHood** [comment]
+++++ 10000

**Comment by morosmo** [comment]
+1

**Comment by tomwesterling** [comment]
Really need this feature! Crocoblock, please implement the honeypot option as a powerful alternative for the critical Google's reCAPTCHA... Thank you!!

+1

**Comment by torsten3d** [comment]
+1
Can't belive it isn't still implemented.
So i have to switch back to my former option without that.

**Comment by MPHood** [comment]
> +1 Can't belive it isn't still implemented. So i have to switch back to my former option without that.

Thats what I did ^^

**Comment by RonnyBode** [comment]
Well, what can I say... Please put it on your to-do list and give it a high priority. SPAM is a plague and GDPR is an exhausting necessity.

Thanks for your great work

**Comment by Nachtkastje** [comment]
+100 

Google reCaptcha makes the website dog-slow....

**Comment by MjHead** [comment]
will be added with JetFormBuilder 3.1.0 update. Currently on testing stage, so I hope will be released in 3-4 weeks

**Comment by TIIUNDER** [comment]
So you need to migrate to JetFormBuilder?
