### ISSUE TITLE
Add taxonomy filters to Admin UI for JetEngine Post Types

### ISSUE THREAD

**Issue by arnohesse** [CrocoBlock/suggestions#2308]
In Post Types, terms and meta fields can be added as columns to the Admin UI.

We need to be able to select taxonomies as filters on top of the Admin UI. (in the same way Woocommerce adds Product Categories to their Admin UI for their Product custom post types)

**Comment by AjayToker** [comment]
Sorting AND Filtering for Admin columns is a must when working with custom databases, please! =) 
I had to delete all my admin columns created with JetEngine and use Admin Columns Pro to do the same function.

**Comment by kochhase** [comment]
+1 yes  and have a look at toolset types. there you can do some grate things with the admin UI. some M-N function for adding some content from one CPT to another CPT without to leave the CPT. Thats very usefull for editing. see... 

![grafik](https://user-images.githubusercontent.com/6199062/107569894-1cd1de00-6be9-11eb-926f-29d69bdd7c83.png)

**Comment by maurocarreraok** [comment]
+1

**Comment by youlikeitcp** [comment]
+1

**Comment by Gabrymi93** [comment]
+1 please this is a must

**Comment by creps** [comment]
+1 It would be amazing

**Comment by cultweba** [comment]
The implementation of this feature is very often needed. And if it could be done using JetEngine it would be great.

**Comment by E-Markers** [comment]
+1

**Comment by MjHead** [comment]
https://github.com/Crocoblock/suggestions/issues/4234

**Comment by Dudaevskiy** [comment]
+1

**Comment by fabricioventura** [comment]
+1

**Comment by Zegklitz** [comment]
+1
