### ISSUE TITLE
Dynamic Image Selection for Hot Spots

### ISSUE THREAD

**Issue by Messydesk** [CrocoBlock/suggestions#2309]
**Please, describe the feature request, making it clear to understand.**
Hi there, 
Dynamic Image selection for the Hot Spot widget in Jet Tricks would be valuable so as to allow the widget to work better on templates in the elementor theme builder.

The way we are looking to use it is to have a media custom field from a product be pulled into the HotSpot widget. We would place all the hot spots in the correct position and all the dynamically loaded images would be of the same dimensions so that the product features are in the correct placement.

**Add an example of where this feature is already implemented. **

We're currently using the Essential Elements Hot Spot image as a solution as it has this feature, but we would like to minimize our plugins and go all-in on Crocoblocks.

You can find a screen cap below with Jet Tricks hot spot on top and Essential Elements Hot Spot on bottom. The main difference being the ability to select an image dynamically.

https://photos.app.goo.gl/kPZQzBafMxt6s7gWA

**Comment by kaskad88** [comment]
Added in JetTricks v.1.3.3. Feel free to update!
