### ISSUE TITLE
JetBlog Preview Image Optimizaiton

### ISSUE THREAD

**Issue by garciacrew** [CrocoBlock/suggestions#231]
I keep getting page speed notices that images related to the YouTube videos on the JetBlog playlist and video player should be smaller and optimized.  It would be great if this could be either an option or done by default.  As an option, choose which size of YouTube preview image to pre-load, or set using srcset so the best is chosen based on screen size.

**Comment by kaskad88** [comment]
Hi @garciacrew.
The YouTube API does not provide the ability to get a thumbnail of the desired size, but in JetBlog 2.1.13, the `CustomThumbnail` and `Thumbnail Size` controls were added to the Video Playlist widget, which gives you the ability to set the desired thumbnail size. http://prntscr.com/o019hc

Thanks for your report!
