### ISSUE TITLE
Allow to set Dynamic Function counter of Jet Smart Filter results

### ISSUE THREAD

**Issue by dorshiff** [CrocoBlock/suggestions#2311]
Description:
---
When using Dynamic Function from Jet Engine to count posts it counts the total amount of posts.
I want to add an option to count only the filtered posts.
This way I will be able to show the number of posts compatible with the filters the user set.

Related products:
- Jet Smart Filters
- Jet Engine

Example
---
https://www.asos.com/men/ctas/fashion-online-1/cat/?cid=13498&ctaref=hp|mw|prime|hero|1|edit|logos&currentpricerange=30-605&refine=brand:16563

Before Filtering - https://i.imgur.com/ADTQiKY.png
After Filtering - https://i.imgur.com/HFO0AyR.png

**Comment by Floydtm** [comment]
#1103
