### ISSUE TITLE
Smart Post Tiles in carousel form for mobile view.

### ISSUE THREAD

**Issue by tanaysankhe** [CrocoBlock/suggestions#2314]
In Jetblog plugin by Crocoblock, there is a widget named 'Smart Post Tiles'. This widget after designing looks great for Desktop and Tablet mode. But, in mobile view, it defeats the whole purpose. The tiles are stacked one below the other which doesn't look good. So, a feature where the Smart Post Tiles will be in the form of a carousel/slider for the mobile view only is what I want my request is.

**Comment by Morgunov-Vitaly** [comment]
+

**Comment by Crocoblock** [comment]
Was added in JetBlog 2.3.8 https://i.imgur.com/o9a0wSu.png
