### ISSUE TITLE
JetPopUp: close all popup button

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#232]
need a global button that close all popup and not only one

**Comment by shinTM** [comment]
done

**Comment by codezz** [comment]
Hi, how to use this and close all popups?

**Comment by Floydtm** [comment]
@codezz HI! The widget Popup Action Button has additional options http://prntscr.com/pl2f89 With these options you can close all popups with one click

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/popup-action-button-widget-overview/

**Comment by TecnoTriks** [comment]
Esse código me resolveu.
This code solved it for me.
![Captura de tela 2024-05-29 190859](https://github.com/Crocoblock/suggestions/assets/20442409/b63e55dd-04b9-492a-acad-7ab586c2d022)
Code:
`<script type="text/javascript">
jQuery(document).ready(function($) {
    // Intercepta o envio do formulário ao clicar no botão "Atualizar"
    $('.jet-form-builder__action-button').on('click', function(e) {
        var $this = $(this);
        // Aguarda 2 segundos após o clique no botão de enviar do formulário
        setTimeout(function() {
            // Simula o clique no botão de fechar o pop-up
            $('.jet-popup-action-button a').trigger('click');
            // Se você deseja enviar o formulário após clicar no botão "Atualizar", remova o comentário da linha abaixo
            // $this.closest('form').submit();
        }, 2000); // Tempo em milissegundos (2 segundos)
    });
});
</script>
`
