### ISSUE TITLE
Jet Tricks Read More Widget Compatible with Jet Engine listing

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2320]
Hello! Consider integrating Jet Tricks Read More Widget into Jet Engine listing
Example: https://www.loom.com/share/79e1541c868544afab1c38f67404697c
At the moment Jet Tricks Read More Widget works by ID, which excludes its integration with listings.

/*Оригинал*/
Привет! Рассмотрите возможность интеграции Jet Tricks Read More Widget в Jet Engine listing
На данный момент Jet Tricks Read More Widget работает по ID, что исключает его интеграцию с листингами.

**Comment by julianderyk** [comment]
+1

**Comment by Michael-sr** [comment]
+1

**Comment by MjHead** [comment]
JetTricks Read More widgets created for a bit different purposes. For the Listing grid widget you need to use Load More functionality of the Listing Grid widget itself

**Comment by stasonua0** [comment]
Load More was created to show more posts, and the video is about "show more" not posts, but additional content inside one listing card. Please watch the video again.

/*рус*/
Load More создан чтобы показать еще посты, а на видео речь о "показать еще" не постов, а дополнительный контент внутри одной карточки листинга. Посмотрите пожалуйста еще раз видео.

**Comment by stasonua0** [comment]
If the video does not understand what is meant, please see an example on a live site with your listings
http://grand.web-creation.dn.ua/avtobus-doneck-moskva/

Если на видео не понятно что имеется ввиду, посмотрите пожалуйста пример на живой сайте с вашими листингами
http://grand.web-creation.dn.ua/avtobus-doneck-moskva/
