### ISSUE TITLE
JetEngine: WYSIWIG

### ISSUE THREAD

**Issue by kalko1234** [CrocoBlock/suggestions#2323]
After updating Wordpress to version 5.6 it is not possible to use WYSIWIG from Jet Engine 2.6.0.

**Comment by stasonua0** [comment]
Same problem, it is impossible to edit / add text. Please promptly correct

**Comment by kalko1234** [comment]
The problem still persists after updating JetEngine to version 2.6.2

**Comment by kaskad88** [comment]
@kalko1234 @stasonua0 Could you please attach a screen or describe more detail because I tried to reproduce your issue and looks like all works fine

**Comment by stasonua0** [comment]
> @kalko1234 @stasonua0 Could you please attach a screen or describe more detail because I tried to reproduce your issue and looks like all works fine

https://www.loom.com/share/21bfaef04fab4b04903cf55142fd7254

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report! 
Temp solution: install and activate the Enable jQuery Migrate Helper plugin.
