### ISSUE TITLE
Add a "file type" meta field in post types(CPT) and repeater fields just like ACF

### ISSUE THREAD

**Issue by azimdotnet** [CrocoBlock/suggestions#2325]
I am missing the file upload meta field from the Advance custom field(ACF) plugin.
Where I have the option to restrict file size and file types.
Example: I can restrict the user to upload pdf only and a maximum size of 2 MB.
File upload meta field will Return Value on the front end: 1) File Array 2) File URL 3) File ID

![file type](https://user-images.githubusercontent.com/26623136/102348066-56aaad80-3fc7-11eb-899c-53f95fb77c8c.jpg)

![File upload option](https://user-images.githubusercontent.com/26623136/102347540-8a390800-3fc6-11eb-8a21-e4ea3cb7e86c.jpeg)

**Comment by jamsheehan** [comment]
Umm, you could just use the media type. 
![image](https://user-images.githubusercontent.com/223342/102648147-d77abe00-411b-11eb-804b-df2913452a26.png)

**Comment by jamsheehan** [comment]
Is this not covered by Media Type?

![image](https://user-images.githubusercontent.com/223342/102648216-f5e0b980-411b-11eb-8acc-500e8f7ad9b5.png)

**Comment by Floydtm** [comment]
Hello! We are working on it. Keep for updates.
