### ISSUE TITLE
JETENGINE: Get Media url instead of id using CCT Rest API

### ISSUE THREAD

**Issue by villelai** [CrocoBlock/suggestions#2327]
In this article: https://crocoblock.com/knowledge-base/articles/jetengine-how-to-display-custom-content-type-items-using-rest-api/ there is a note:
NOTE. Using the REST API, you can receive nothing more but the values of the fields. This means that instead of pictures (from the Media-type field) you will get only their ID numbers.

Is it possible to get media url instead of id? How can this be done?

**Comment by MjHead** [comment]
As for now this could be done by changing Media field args:
![image](https://user-images.githubusercontent.com/4987981/129369640-3a886817-3d90-4f38-b971-fad7449fa39a.png)
Please note, if you changing Media field type after CCT created, you also need to change field name to ensure DB column type was changed correctly.

Also from JetEngien 2.8.9 will be available 2nd way, by applying filterng function to API response. Here is an example for the image - https://gist.github.com/MjHead/f3e883c19cd0f754761719b5101a1f62#file-rest-api-filter-example-php-L19-L27

**Comment by mendozalz** [comment]
En VALUE FORMAT a mi me ha resultado dejar MEDIA URL y hacer la solicitud por DYNAMIC IMAGE sin problemas después de haces varias permutas...
