### ISSUE TITLE
JetEngine - text while loading more posts for infinite scroll

### ISSUE THREAD

**Issue by joseehilton147** [CrocoBlock/suggestions#2329]
Hi, its possible to add a text while posts are loading in infinite scroll and when the posts load this text auto hidden... for example:  if a user has a low internet connection will take sometime to load more posts and to make clear to user isnt a bug on website a text display telling to wait why are loading... something like this:

can be a gif with this text on full screen and cant be disable while finish load for example... or text above scrolling to load... i know theres a little effect showing its loading but it can be better
![1](https://user-images.githubusercontent.com/53986027/102445066-64812280-4009-11eb-94b7-fd07ebfdb9cf.png)

**Comment by Cosirax** [comment]
+1  the possibility to choose text or icon / svg would be awesome!

**Comment by Zegklitz** [comment]
+1

**Comment by Gidsa** [comment]
+1

**Comment by madudesign** [comment]
+++1 
Would love to see this feature, since UX is not clear here, or if there is any js turnaround or so in the meantime, it would be very appreciated ;)

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
