### ISSUE TITLE
New Meta Field for Embed Url-Iframes (Bandcamp embed url)

### ISSUE THREAD

**Issue by d27admino** [CrocoBlock/suggestions#233]
Hi,

My request is for a module to dynamically show "embed URL", and in my case, Bandcamp albums in a dynamic listing grid.

MY ATTEMPTS AND WHY A NEW MODULLE IS NEEDED
======================================
A bandcamp embed URL  is like this:
<iframe style="border: 0; width: 400px; height: 307px;" src="https://bandcamp.com/EmbeddedPlayer/album=2863030352/size=large/bgcol=ffffff/linkcol=0687f5/artwork=small/transparent=true/" seamless=""><a href="http://fandorsonore.bandcamp.com/album/introduction">Introduction by Fandor</a></iframe>

In order to make it work with a Jet Engine Meta Field, you need the following:
1 - Meta field = Text area
2 - Truncate the embed to keep only the href: https://bandcamp.com/EmbeddedPlayer/album=2863030352/size=large/bgcol=ffffff/linkcol=0687f5/artwork=small/transparent=true/" seamless=""
3 - Load an iframe module and dynamically assign Jet Engine meta field to populate the field.

PROBLEM
=======
It requires manipulations from the admin - nand the Iframe module that I use (the only one i found) has a pre-detremined height, and it will take space even if the field is empty (no urll).  
So it breaks the design and makes the technic questionable/un-useable.

REQUIREMENTS
=============
1// It would be great to have a module that can manage embed urls like bandcamps, by a simple copy/paste of the url.  The url should be populated either from a Jet Engine  meta field or from a meta field from another app (I use WPform to create user post submissions and gather all the info for the listing). 

2// The module should take no space if there is no url to embed (empty field - no need to take up empty space). That would be a great feature.

3// Would be great to have the same for soundcloud; the module i have works fine but takes too much space if the field is empty. 

GO FURTHER
=========
It should work with any embed urll/iframe type from any service. I guess they are all more or less the same ? 

Let me know if you need more info

**Comment by d27admino** [comment]
Hi,

Great to see this assigned. In the meantime I have turned to Spotify

urls are like this  
https://open.spotify.com/artist/6wgL3WRNHXwsLzT6aE1eoY

Good news, they work in the soundcloud (from elementor pro) widget, but the settings are not good.

I have opened another request to have a module that can display soundcloud or spotify (and if you can add bandcamp, it is the cherry on the cake).

**Comment by d27admino** [comment]
Here the other thread.
https://github.com/CrocoBlock/suggestions/issues/241

I can now show **either** soundcloud or Spotify, because the soundcloud module shows urls. 
However, settings are for soundclloud.

Would still be great to be able to embed iframe types like bandcamp etc.



Other embed services ideas
flickr,
video services etc

**Comment by MjHead** [comment]
This feature already exists in Dynamic Field widget. You need to add text custom field. Put required URL into it. Then in Dynamic field widget enable Filter Field Output option and select Embed URL callback. Here an example with Spotify playlist - http://prntscr.com/npvzdt

**Comment by juniorveigabr** [comment]
I managed to follow this tutorial, however, when I directly edited the PHP of the theme with the code editor, it crashed my entire website.


https://crocoblock.com/troubleshooting/articles/cannot-display-iframe-with-dynamic-widgets/
