### ISSUE TITLE
JetBlog Smart Post Tiles: Main Box Width for Tablet

### ISSUE THREAD

**Issue by worldoptimizer** [CrocoBlock/suggestions#2333]
**Describe the bug**
The Main Box Width can't be set according to device type (Desktop, Tablet, Mobile). This is a problem because many of the layouts don't fit into the tablet view. Hence, we need a way to set the width based on Device type. Maybe also a special rule when setting it to 100% to activate the regular mode found under Mobile (stacking all boxes). That would allow to set this also on Tablet. 

Alternative: Minimal fix a setting for Desktop and one setting for Tablet as mobile probably always goes to 100% and stacks the tiles.

**To Reproduce**
1. Create a  Smart Post Tiles
2. Set the Max Box Width
3. Play around with different content and see it overlap the available width on the Tablet view

**Expected behavior**
Setting for Max Box Width on tablet is clearly missing breaking this Elementor widget on table (in my case)

**Comment by worldoptimizer** [comment]
![CleanShot 2020-12-17 at 13 16 13@2x](https://user-images.githubusercontent.com/1752114/102489707-25d18380-406e-11eb-8790-2913e7ae00a7.png)

**Comment by AxelFerlin** [comment]
I have the exact same issue, would love a solution. :)

**Comment by Gawuww** [comment]
Added in JetBlog v2.2.17
