### ISSUE TITLE
JetEngine: add Woocoomerce "add to cart" compatibility in listings

### ISSUE THREAD

**Issue by Tropicalestudio** [CrocoBlock/suggestions#2337]
I think it would be very useful to create product grids with the integrated Woocommerce add to cart button.

Thanks a lot.

**Comment by sara-kariv** [comment]
that is very needed

**Comment by tothld** [comment]
Agreed!

**Comment by simonvanoordt** [comment]
Same for me

**Comment by UraraReika** [comment]
I merged this issue with #2154, which is on the same subject so we could deal with it more efficiently.
