### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by maryeller** [CrocoBlock/suggestions#234]
Hey!
I would like to build a page using the Dynamic Images Widget from jetEngine but it doesn't have the option to "Hide if empty" on the settings.
When I use Dynamic Fields I have the option to Hide if the field is empty and I don't have that option on the Dynamic Images.

It would be really nice to have that toggle option also for the images because right now, the empty widget doesn't show anything but takes place on my page.

Thanks!

**Comment by MjHead** [comment]
Added in 1.4.2
