### ISSUE TITLE
Ability to use the Calendar on several pages

### ISSUE THREAD

**Issue by zsolthorcsik** [CrocoBlock/suggestions#2344]
I am using the Jet Booking Plugin. I have a single apartment accommodation, and on it's page I'm using the built in (Elementor draggable) calendar. 

I would like to use this calendar also on other pages, however, when I place it on a page the booked dates are not showing up. I suppose the calendar is using the Post ID, to see which accommodation it should show the availability for. 

There should be an option in the Elementor panel, to add a custom accommodation id. Alternatively there could be simply a shortcode where one could choose the post id. Is there perhaps a way to invoke the calendar from php code, or some other way to display the booked dates on pages other than the accommodation page itself?

Thanks in advance.

**Comment by Floydtm** [comment]
At the moment, you can only use the calendar on a single booking post.
