### ISSUE TITLE
JetEngine/Forms: EMail notifications allow ShortCodes

### ISSUE THREAD

**Issue by skellenb** [CrocoBlock/suggestions#2345]
When adding Forms-> Send Email
I can choose between HTML and Plain text and some macros are available.

But for formatting the content to my needs, it would be great if i can use some custom Shortcodes

**Comment by cvl01** [comment]
Adding to this, could the Email notification feature add a regular WordPress wysiwyg / tinymce editor so that we can easily add lists, bold text etc?

**Comment by kaskad88** [comment]
Added to the next version ( v2.10.1 )
