### ISSUE TITLE
Add option to query multiple post types for Calendar Listing

### ISSUE THREAD

**Issue by aaronkine** [CrocoBlock/suggestions#2346]
The Listing Grids has the option to use as many Custom Post types as you want but the Calendar Listing Element only has the option to choose one. The site we are building has two different post types; Events, and Featured Events.  This allows us to customize the featured events differently across the site.

I only see benefits to allow multiple post types to the Calendar widget.

**Comment by kaskad88** [comment]
Added for the next version ( v2.10.1 )
