### ISSUE TITLE
Backend for relations 1-n or n:m like toolset

### ISSUE THREAD

**Issue by kochhase** [CrocoBlock/suggestions#2347]
As you can see the backend of toolset is good to use for working. So clients could make there work there. especially if you want to run a footballer website or a site with information related to two CPT.

![2020-12-21 21_23_21-Edit Fußballer ‹ Prüss Oberliga — WordPress](https://user-images.githubusercontent.com/6199062/102819020-02db0280-43d3-11eb-8286-f9592d25d909.png)
![2020-12-21 21_19_21-Fussballer ‹ Prüss Oberliga — WordPress](https://user-images.githubusercontent.com/6199062/102819023-03739900-43d3-11eb-8d15-4c8014fd1444.png)

**Comment by MjHead** [comment]
Added with 2.11.0
