### ISSUE TITLE
[JetBooking] Multiple bookings in the same form

### ISSUE THREAD

**Issue by JoeKns** [CrocoBlock/suggestions#2352]
It's not possible to book multiple rooms in 1 go at this point.

Imagine I want to book 12 rooms for a total of 40 people. I would have to fill out the same form about 15-20 times. If I can book multiple rooms, with each a selectable number of persons per room this would be a lot better. Right now, no serious hotel or hostel would be able to use the Crocoblock plugin because of this.

This makes the plugin a lot more group-friendly. 

------------------

Also, if the additional services like breakfast could be selectable in number per room. So 1 room, booked for 3 people, yet only 2 people want breakfast. And 1 person wants a city map.

**Comment by KHRifat** [comment]
Same to you. I want to build a Car booking system, But it's not allowing multiple same-day bookings on a single form/category when I have multiple cars in the same location/category.

I request @Crocoblock to Upgrade the plugin for Multiple Booking Support with Pre-booking and cancellation policy.

**Comment by sandornemeth86** [comment]
Same here. I am building a car booking system too, and have the same request for Multiple booking support.
Thanks.

**Comment by avydigital** [comment]
I also have the same problem, trying to create a tour booking system.
Each tour can have 20 participants - currently only 1 booking can be made ..

**Comment by tonop01** [comment]
I have same problem. we would like 1 room 7times. in same time.

**Comment by pixallusdev** [comment]
no movement on this huh?

**Comment by razkoko1** [comment]
+1...

pls, this feature is a must.

**Comment by ighalo87** [comment]
Is it possible using jetbooking for jetengine Profile builder ( user )
Not using a CPT on my website

**Comment by vladvaleanu** [comment]
+1
would really help!

**Comment by dbfischer** [comment]
This morning I have another feedback that it is not accepted by customers if 4 bikes for a family are needed and each one should be booked separately.

**Comment by EvanPluchart** [comment]
I've the same problem, I would like to be able to book several rooms at once but the only way I have is through "Hotel Booking by MotoPress" and I prefer to stay with JetBooking.

**Comment by dbfischer** [comment]
I have just discovered another problem. When I book a bike, I come straight to the checkout.
When I go back to the shopping cart, I can increase the number as much as I want, more than the available bikes for that date.

**Comment by JoeKns** [comment]
As OP, I've moved on from the Crocoblock stack (and Elementor) for years now. Either do the same, or do not expect ever to be able to deliver fast, reliable products in a professional manner to clients — and thus stop trying to get some random fix or update to save you. It won't.

**Comment by Qubadi** [comment]
1+

**Comment by MjHead** [comment]
Since JetBooking 3.0.0 this could be done in WooCommerce mode

**Comment by awebguy99** [comment]
What have you moved onto?

**Comment by awebguy99** [comment]
> As OP, I've moved on from the Crocoblock stack (and Elementor) for years now. Either do the same, or do not expect ever to be able to deliver fast, reliable products in a professional manner to clients — and thus stop trying to get some random fix or update to save you. It won't.

What have you moved onto? Bricks?
