### ISSUE TITLE
Booking plugin to supports syncing with third-party sites like Airbnb, TripAdvisor, and Booking.com

### ISSUE THREAD

**Issue by apconcepts** [CrocoBlock/suggestions#2355]
I highly recommend and would LOVE if you guys could add the feature into the wordpress booking plugin -- to support syncing with third-party site bookings like Airbnb, TripAdvisor, and Booking.com.

This way when people book out my villa on the website where I'm using the crocoblock booking system, that it won't be able to overlap with the same villa bookings from my airbnb and booking.com listings (and vice versa). 

I know many booking plugins have this capability, and to me it's a crucial one. If I would have known that this feature wasn't offered, I most likely wouldn't have gone with the crocoblock booking plugin. 

May need to switch actually, unless this might be something that can possibly be done quickly?

https://www.airbnb.com/help/article/99/how-do-i-sync-my-airbnb-calendar-with-another-calendar
Here's a link that shows how you do it from airbnb to other listing sites (ideally would work into my personal site as well, where I am using the crocoblock booking plug-in to avoid overlapped bookings). 

Thank you so much,
Andre

**Comment by webndesign** [comment]
Definitely a Must! if you guys are serious about competing with independent Booking Widgets/Plugin companies that offer this functionality already!
I'm building sites just for this industry, so if you implemented this in your Booking Engine, (among other features I've seen on comments in your YT channel, like seasonal prices), I would upgrade my Croco license immediately. 
I don't know why all of you offering such booking widgets, offer one functionality and not another!

What you actually need, is a person who has tons of experience in the Hospitality Industry, (like me for example - no suggestions here;-) to guide you on ALL the must-have features a booking engine should have!
Then, we're talking about a complete Booking solution that is worthy of competing with any other company outhere and rising above the rest!

Thank you for reading..and hopefully, we should see some of these features implemented soon!

**Comment by apconcepts** [comment]
No response? Well looks like if anyone see's this, that it wouldn't be integrated anytime soon. It's really a shame! I am going to have to use another plugin widget for booking on my site now and request a refund.

**Comment by humanwebs** [comment]
Hi guys, I know there is no set milestones and no development to achieve this topic but I also bought JetPlugins to develop a house booking website and it makes no sense to do it if I can't sync with third-party booking sites.. My client's web page can't compite against booking.com or AirBnb in terms of users and searches. And offering a registration form in the client's web page that doesn't sync with the biggest booking systems lead to overlapping booking -> angry people, sorries and refunding problems. 

So it makes JetBooking useless to me too.. Any chance to give this topic a future implementation? Technically it doesn't seem to be harder than the Google Calendar Sync that you guys already have here: https://crocoblock.com/knowledge-base/articles/jetbooking-how-to-transfer-bookings-from-google-calendar-via-ical-synchronization/
Actually it looks almost the same method as in here https://www.airbnb.com/help/article/99/how-do-i-sync-my-airbnb-calendar-with-another-calendar

Thanks!

**Comment by JackobStuard** [comment]
Hi devs, @Crocoblock @MakhonkoDenis 

Is there any update for this feature? Status is "in work" for more than 8 months?
I see that is possible to use external API from big companies like Booking.com https://developers.booking.com/api/index.html, Airbnb https://www.airbnb.com/partner to make good sync between JetBooking and other calendars!
I hope that will be implemented soon, I think that all users want this feature to have on JetBooking :)

Thanks!

**Comment by evolvenl** [comment]
Any updates on this?
If u really want to be taken seriously in the booking market, sync with the major players like booking.com and Airbnb is an absolute must!

**Comment by clibarnes** [comment]
any update?

**Comment by borjacachan** [comment]
any update? We need Google Calendar Sync with AirBnB and Booking.com
It is not usable tu make reservation manually if we have another reservation in other plattorms. Has no sense. How can we integrate it?

**Comment by dawidwgd** [comment]
We need that so much! any update?

**Comment by SolunaCG** [comment]
+1

**Comment by UraraReika** [comment]
We already had this functionality since iCal option, but in the lates release we made this even better please check out our articles about it:
- https://crocoblock.com/knowledge-base/articles/jetbooking-how-to-transfer-bookings-from-google-calendar-via-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-reverse-booking-and-google-calendar-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-two-way-booking-and-google-calendar-ical-synchnization/

Please take a note that you can make such integration with every service that provide iCal functionality.

**Comment by ofmarconi** [comment]
@UraraReika Is this sync working well with Airbnb? If someone books on Airbnb the date is locked and if the reverse happens on Airbnb it is locked?

Thanks
