### ISSUE TITLE
GEO Location For Posts

### ISSUE THREAD

**Issue by BIGSHOTInt** [CrocoBlock/suggestions#2357]
It would be great to be able to locate posts by GEO location so that they can be shown to users based on their ip address. For example, we are using Cocoblock + Jet to create a directory. It would be nice to be able to add "near me" in the search to show the user the profile posts, created in a Jet CPT, with an address near them. 

Thanks for all you do!

**Comment by julianderyk** [comment]
+1

**Comment by stasonua0** [comment]
+1

**Comment by startupweb** [comment]
Same, have posted this request as well on a separate suggestion post.

**Comment by Scoots78** [comment]
Exactly what i need too, users are used to this as it is available in google maps. Used with the Jet Engine maps would be very useful, i may have to switch to another plugin without it.. any idea if this will happen Crocoblock?

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
