### ISSUE TITLE
CCT number field doesn't work with decimals. Custom Content Type

### ISSUE THREAD

**Issue by quickDESIGNnl** [CrocoBlock/suggestions#2359]
- When using a **CCT** number field,  you can setup step value to be 0,01
- But when you want to put in 15,75 for example the software removes decimals and corrects it to 16

How to reproduce this CCT problem:
![Knipsel3](https://user-images.githubusercontent.com/68347993/102994839-28295700-4520-11eb-9d55-f3be390f2739.PNG)

Before save:
![Knipsel](https://user-images.githubusercontent.com/68347993/102994841-295a8400-4520-11eb-807b-c7ce5cc3bf10.PNG)

After Saving:
![Knipsel2](https://user-images.githubusercontent.com/68347993/102994840-28c1ed80-4520-11eb-8039-270d0d24f3cb.PNG)

**Additional context**
Had contact with Crocoblock chat and they confirmed this bug.

(Decimals do work this way with normal CPT)

**Comment by MjHead** [comment]
Fix will work only for a new CCTs, because existing into the DB already set column type Integer. To make it to work for existing CCTs you need to rename field with number. But please note, all existing data in these CCT fields will be lost

**Comment by TinyHalo33** [comment]
Can you please explain a little more about the fix since I'm having this exact same problem? I'm a newbie at everything tech and would really appreciate any additional info.

**Comment by inveress** [comment]
I had this same problem today but worked out that decimals are usable if you specify an appropriate step (I had left the step field empty). ie, if you want to allow values to two decimal places, you should give the field a step value of 0.01

**Comment by TinyHalo33** [comment]
Thanks! I sure appreciate that. :)

**Comment by gualtier** [comment]
Tried to reproduce all solutions above but yet no results. It seems to being forced by the pattern attribute. 

![Captura de Tela 2023-10-26 às 12 36 42](https://github.com/Crocoblock/suggestions/assets/85246249/7f33283a-5056-4bd5-86b9-54afeb6a2abe)

**Comment by kaskad88** [comment]
> Tried to reproduce all solutions above but yet no results. It seems to being forced by the pattern attribute.
> 
> ![Captura de Tela 2023-10-26 às 12 36 42](https://user-images.githubusercontent.com/85246249/278400820-7f33283a-5056-4bd5-86b9-54afeb6a2abe.jpg)

@gualtier Fix will be in JetEngine v3.2.7

**Comment by gualtier** [comment]
@kaskad88 Alright!  We are stuck on a project we have to delivery this week :(

But thank you!

**Comment by swanlike** [comment]
I also stopped with my work because of this error... I can't work with decimals which are crucial in my project. When we can expect 3.2.7 version??

**Comment by kaskad88** [comment]
@gualtier @swanlike 
Release 3.2.7 will be in 1-2 weeks
But you can rollback to version 3.2.5.2 and continue working on the project https://tppr.me/Osgih

**Comment by gualtier** [comment]
> @gualtier @swanlike Release 3.2.7 will be in 1-2 weeks But you can rollback to version 3.2.5.2 and continue working on the project https://tppr.me/Osgih

Many thanks, just did the rollback and now its working!
