### ISSUE TITLE
JetSmartFilters: checkboxlist inside the select filter

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#236]
I want to use a select filter but need to have the option to select more than one item from the list. so either a checkboxlist inside the select filter or the option to select one after the other and add it to activated filters. 

Like here: https://shop.photoadventure.eu/ticket/seminar/?utm_source=wysija&utm_medium=email&utm_campaign=FP18-11

**Comment by Floydtm** [comment]
will be implemented in this issues https://github.com/CrocoBlock/suggestions/issues/205
