### ISSUE TITLE
JetEngine Form: Hierarchy Selection in Front End Form

### ISSUE THREAD

**Issue by rentaterry** [CrocoBlock/suggestions#2360]
Hi! Is it possible to make hierarchy selection fields in profile form, so users can limit the selections (like car brands and models)? I love what similar on JetSmartFilters.

**Comment by kochhase** [comment]
+1

**Comment by rajas91** [comment]
+1
This is a much needed feature for jet front end forms.

**Comment by Lonsdale201** [comment]
+1. Good and useful idea :)

**Comment by mattkub** [comment]
+1

**Comment by Willitbang** [comment]
+1

**Comment by Elsteck** [comment]
+1

**Comment by owong** [comment]
+1

**Comment by razkoko1** [comment]
+1

**Comment by gurkanucar19** [comment]
+1000000000!!! This is a very important and basic action that needs to be done immediately. Easy to do for the Crocoblock team.
We are waiting...

**Comment by tommyyueh5** [comment]
Very necessary, such as the relationship between the country and the city

**Comment by MjHead** [comment]
Added as add-on for JetFormBuilder

**Comment by fabio323ti** [comment]
Please add that on Jetengine legacy form feature

**Comment by deepwaterpixel** [comment]
This should not be closed -- adding the feature to JetFormBuilder is nice, but right now I can't upload images on JetFormBuilder, so I have to use JetEngine forms.  Now, I have a taxonomy with many children and grandchildren that are just shown as a single alphabetical list :(

The request was for JetEngine's forms feature, not JetFormBuilder.

**Comment by morosmo** [comment]
+1

**Comment by Floatcreators** [comment]
+1
