### ISSUE TITLE
lightbox for dynamic image

### ISSUE THREAD

**Issue by chiku012** [CrocoBlock/suggestions#2361]
For the dynamic image widget, there is no option to open the image in the lightbox or it doesn't trigger the elementors default lightbox.

**Comment by JMartinCollins** [comment]
+1

**Comment by JMartinCollins** [comment]
Or at least link to full size image url, since I want to make repeater galleries and only dynamic image/dynamic link will work here.

**Comment by Gitmarcc** [comment]
+1

**Comment by liranbp** [comment]
+1

**Comment by radox73** [comment]
+1

**Comment by SirChopper** [comment]
++1 please

**Comment by nickj-git** [comment]
This would be a welcome addition. Is this being considered for a near future release?

**Comment by kaskad88** [comment]
This feature is already available from JetEngine v3.0.7
https://tppr.me/aFELq 

**To use it is necessary:**
1) Turn on `Linked image`
2) Select the `Media File` in `Link Source` setting
3) Turn on `Lightbox`

**Comment by DigitaleCreaties** [comment]
Options does not show when using an image from taxonomy or other custom field. 
![Schermafbeelding 2024-07-16 om 17 02 43](https://github.com/user-attachments/assets/51bbbb00-8fee-497a-b4d9-9baa0c5f9901)

**Comment by BayTheWebGuy** [comment]
> This feature is already available from JetEngine v3.0.7 https://tppr.me/aFELq
> 
> **To use it is necessary:**
> 
> 1. Turn on `Linked image`
> 2. Select the `Media File` in `Link Source` setting
> 3. Turn on `Lightbox`

This isn't an option for me?

- I have a custom post type, with a repeater field, where 1 field is a gallery.
- I can use the dynamic image widget to display them successfully on the front end.
- However, "media file" is not an option within the link source drop down.
- There is never an option to choose "lightbox"

I'll send £50 via Paypal if anyone can fix this within 21 days :)

Screenshots:
![image](https://github.com/user-attachments/assets/6d1edc57-45fe-4db7-b7fa-0e627fb279cb)
![image](https://github.com/user-attachments/assets/e5296c8d-7d94-493e-a577-7b9fbfbe5078)

**Comment by SnugSite** [comment]
Still not available. This would be a very useful feature.

**Comment by VICSnl** [comment]
+1

**Comment by Crocoblock** [comment]
Hi 
It's a known bug and we'll fix it in the 3.6.2 version

**Comment by AlvyIT** [comment]
@Crocoblock 
Hi, was it fixed? As the current version of jet-engine is 3.6.4.1

**Comment by Crocoblock** [comment]
@AlvyIT 
Yes, in 3.6.2

If you still have an issue, please contact [our support team](https://crocoblock.com/help-center) regarding this case and create a ticket including access details for the site where the issue occurred to ensure we can help you.

**Comment by Joe-Bloggs** [comment]
@Crocoblock any way to open dynamic images in lighbox using Bricks? 

<img width="343" alt="Image" src="https://github.com/user-attachments/assets/d22d0d61-e2a2-4114-ae5f-f6566df06f92" />

This doesn't seem to be an option in Bricks.
