### ISSUE TITLE
JetWooBuilder - A badge for "out of stock" widget

### ISSUE THREAD

**Issue by fkirtunc** [CrocoBlock/suggestions#2362]
Hello crocoblock, love the plug-in! So I have a question. I want to add a badge of my stock information instead of a simple "out of stock" text on top of the image. Is this something to be done with crocoblock? Thanks :)

**Comment by arekuki** [comment]
+1

**Comment by Floydtm** [comment]
you can use this [widget](https://prnt.sc/xswyg9) in jetwoobuilder plugin

**Comment by chervince** [comment]
+1
