### ISSUE TITLE
Creation of appointments in JetAppointment from admin

### ISSUE THREAD

**Issue by erubianes1** [CrocoBlock/suggestions#2363]
Hello,

Nowadays it is not possible to add manual appointments from the backend in JetAppointment. It is a must very neccesary to add control to the admin internally to add bookings manually.

Please, consider this because if the plugin doesn't permit this is not complete and usfull enough.

Thank you very much.

**Comment by UraraReika** [comment]
This functionality was presented in 1.4.0 version. You can fell free to check it out.
