### ISSUE TITLE
Edit date and hours of bookings in JetAppointment from the admin

### ISSUE THREAD

**Issue by erubianes1** [CrocoBlock/suggestions#2364]
Hello,

I have a request about edition of appointments in JetAppointment, whose are VERY VERY important to manage internally the booking system by the administrator:

Nowadays it is not possible to edit an appointment in terms of day and hour. If a customer ask for a change in his/her booking it. It is possible to change the customer info and status, but not the date.

Please, consider this because if the plugin doesn't permit this is not complete and usfull enough.

Thank you very much.

**Comment by MakhonkoDenis** [comment]
Hi,
This feature was added in version 1.4.0
