### ISSUE TITLE
create new plugin JetScroll

### ISSUE THREAD

**Issue by promocot** [CrocoBlock/suggestions#2367]
Good afternoon, you have a page scrolling widget, but its functionality is very limited, you cannot do horizontal scrolling, for example. Third party developers offer tons of options for full page scrolling. Expand the functionality with a new plugin to create a cool website design

Reference :https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/

**Comment by Floydtm** [comment]
merge with #44
