### ISSUE TITLE
Jet Engine Forms counting repeater field does not work

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2371]
Hello, https://prnt.sc/wa5ypj

**Comment by stasonua0** [comment]
Уточните, это считается небольшим багом и поэтому заявка не берется в работу 4-й месяц?

**Comment by kaskad88** [comment]
@stasonua0, свяжитесь с нашей службой поддержки https://crocoblock.com/help-center/, чтобы получить рекомендации по решению этой проблемы (и укажите все детали проблеми со скринами или видео и примером вашей формы )

**Comment by junior-maker** [comment]
the solution to the problem is here: https://www.youtube.com/watch?v=crkzY73iqGE
