### ISSUE TITLE
Jetengine listing query date by "today" (custum date field) uses UT not UTC time

### ISSUE THREAD

**Issue by LevelUpGit** [CrocoBlock/suggestions#2373]
System:
Wordpress 5.6
Nginx, php 7.4
Elementor + crocoblock latest plugins
UTC +2

Replicate:
- Jet engine: custum post type with custum date field saved as Unix timestamp,
- Jet engine: listing created
- Elementor: pulling that listing
- Jet listing query: , Post query > Meta query > key (date field from before), operator: equal, and VALUE: "today"

Expected:
pulling posts from today, by UTC time

Problem result
pulling posts from today, by UT time, so post are not changing at 00:00 but at 1:00

Thank you for your support.

**Comment by Crocoblock** [comment]
Hi @LevelUpGit 
in the JetEngine 3.5.4 added `Adjust` option  https://imgur.com/q0xpBLB , try it.

**Comment by LevelUpGit** [comment]
On 2024-08-19 11:38, Crocoblock wrote:

> Hi @LevelUpGit [1]
> in the JetEngine 3.5.4 added Adjust option https://imgur.com/q0xpBLB , 
> try it.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>

Hi,

thank you, this is the solution for our long standing issue.

Best whishes

Links:
------
[1] https://github.com/LevelUpGit
[2] 
https://github.com/Crocoblock/suggestions/issues/2373#issuecomment-2296122789
[3]
