### ISSUE TITLE
Animated line in Hebrew looks like mirror

### ISSUE THREAD

**Issue by pintolog** [CrocoBlock/suggestions#238]
Hi,
Please fix the RTL in the **Animated Text** element
The middle animated line is not looks correct when typing in Hebrew.

The text in Hebrew should be from Right to Left, It's working good on the lines that are not animated.

Elementor + Pro: Version 2.5.15 
JetBlog For Elementor: Version 2.1.13

![image](https://user-images.githubusercontent.com/7497319/57368629-41875f00-7194-11e9-9077-b325d5db7203.png)

**Comment by kaskad88** [comment]
Added `Text Direction` option. Available in JetElements 1.15.13
