### ISSUE TITLE
WooCommerce Email Designer

### ISSUE THREAD

**Issue by pixellover** [CrocoBlock/suggestions#2382]
Hello guys!!! I would like to leave a suggestion that would help a lot when customizing WooCommerce emails. There is a plugin that was indicated to me and it does this customization, but the ideal would be if it had this option within the JetWooBuilder itself.

Here is the name of the reference plugin: Kadence WP: WooCommerce Email Designer: Customize the default WooCommerce email templates design and text through the native WordPress customizer. Preview emails and send test emails.

(https://www.kadencewp.com/product/woocommerce-email-designer/).

![email_designer_01](https://user-images.githubusercontent.com/74419376/103321475-8e2e4680-4a18-11eb-8820-9d0d229657c2.jpg)

**Comment by Floydtm** [comment]
Hi, I understand that this is very important to you. However, we cannot do this right now. To do this, you can use one of the free [plugins](https://wordpress.org/plugins/search/woocommerce+email/).
