### ISSUE TITLE
Two Jet Booking feature requests

### ISSUE THREAD

**Issue by Lee1311** [CrocoBlock/suggestions#2387]
**Request one: Booking Form guest numbers**
The min and max values for the number form field used to determine the number of guests being booked in, is not sufficient to prevent people adding more than the room's capacity. This should be changed so that a chosen meta field (ie: the room's capacity) should determine the min and max values. 

**Request two: Set min/max values for check in/check out** 
Currently, it is not possible to force customers to choose a minimum of two or three nights. This is a common feature for B&B establishments and should be incorporated into the Jet Booking date picker and check in/check out form field.

**Comment by UraraReika** [comment]
**Request one: Booking Form guest numbers**

You can create mets field for Apartments Post type for guests number and set maximum count of guests - https://tppr.me/HGSoi. Then in JetFormBuilder setup select field like this - https://tppr.me/Jsy68 where you specify your meta field key. And then in the frontend you will get numbers from one to number you specify in meta field for guests number.

**Request two: Set min/max values for check in/check out**

This functionality was presented in of of the latest release.
