### ISSUE TITLE
Notice: Undefined index: _id in .../plugins/elementor/core/files/css/base.php on line 703

### ISSUE THREAD

**Issue by jpknz** [CrocoBlock/suggestions#239]
**Describe the bug**
The below notice is displayed in the latest version when pages are viewed as admin under appearance -> customize. It does not appear when viewed as end user or when viewed in the elementor editor directly
Notice: Undefined index: _id in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/elementor/core/files/css/base.php on line 703

**To Reproduce**
With the latest version of the plugin view any elementor page within the admin area of wordpress under appearance -> customize and this line will be displayed at the top. It may be hidden by your header in which case adding the below css will allow you to see it (within the admin area)
```
.content {
	padding-top: 190px;
}
```

**Comment by kaskad88** [comment]
Hi @jpknz 
We cannot reproduce your issue. Check if the issue still persists.
If the problem persists, let us know.
