### ISSUE TITLE
Much more customizable Wishlist

### ISSUE THREAD

**Issue by Lance2j** [CrocoBlock/suggestions#2399]
It would be awesome to have Wishlist with the same features as in [MyLists Add-on for JReviews](https://www.jreviews.com/addons/mylists). So far, I haven't found anything else that is even remotely comparable.

**Comment by UraraReika** [comment]
Hello @Lance2j!

In update 1.2.2 JetCompareWishlist and 1.7.3 JetWooBuilder, we added the ability to create a product card using JetWooBuilder. 

- https://prnt.sc/wgq14u > https://prnt.sc/wgq3e7 > https://prnt.sc/wgq6zx
- Then, in the Woocommerce settings, you need to select this card for the Wishlist widget. https://prnt.sc/wgq858 > https://prnt.sc/wgq9ef > https://prnt.sc/wgq9nn > https://prnt.sc/wgq9v6, don`t forget to save settings
- https://prnt.sc/wgqc6d set such setting for this layout
- result https://prnt.sc/wgqcpe

If this is not exactly what you had in mind, then we ask you to describe in more detail the features that you would like to see.
