### ISSUE TITLE
Add product card editor on the archives and catalog page. JetWooBuilder Plugin

### ISSUE THREAD

**Issue by tooweb** [CrocoBlock/suggestions#24]
Add product card editor on the archives and catalog page. JetWooBuilder Plugin

For example, we can already edit individual pages of the creatures and pages of the store, but we cannot fully edit the product cards themselves that are shown to us on the store page.
Here's an example: I want all the products to appear in the list - it looks not bad, but standard.
![image](https://user-images.githubusercontent.com/47851564/53162037-02159180-35ed-11e9-800f-e736fcc58448.png)

If I want to add the buttons of the wish list and the list of comparisons to these cards, then it turns out to be terrible)))

![image](https://user-images.githubusercontent.com/47851564/53162146-37ba7a80-35ed-11e9-8688-08284c32e2f6.png)

Why not make the designer of such a card separately?
![image](https://user-images.githubusercontent.com/47851564/53162928-d5627980-35ee-11e9-9383-671afed00d07.png)
Agree it looks better?

Thereby, users will be able to make completely univall cards of goods with a wide phonktsionalom and there will be no problems with the display of elements inside the parent unit.))
Thanks for attention!

@CrocoBlock

**Comment by CrocoBlock** [comment]
Dear client,

First, let us thank you for the detailed explanation of what is needed. Yet, we still need to make sure we understand everything correctly. 

As far as we know, the separate product card can be styled and created from scratch using Archive template (it is actually the template where one can set the layout and elements needed to be displayed for each of the products). 

http://prntscr.com/mo7832

When you're creating an archive, you're creating the looks of one product from the archive to showcase it then in the Shop or on Archive page. 

http://prntscr.com/mo78pv

Then it's important to set the layout (the number of columns, etc.) http://prntscr.com/mo78xc and set the created template as the one prioritized in the WooCommerce > Settings > JetWooBuilder http://prntscr.com/mo79se .

To pull this archive to the Shop page you'd need to use Products Loop widget. http://prntscr.com/mo7aq5

If there are any specific features are needed when creating an Archive (the separate product card), please, specify them. 

Best regards from CrocoBlock team

**Comment by stasonua0** [comment]
Everything can be done, except for one, choose the quantity of goods immediately from the item card http://prntscr.com/mo88un
Earlier, I wrote to you about the importance of such refinement.

**Comment by tooweb** [comment]
> Dear client,
> 
> First, let us thank you for the detailed explanation of what is needed. Yet, we still need to make sure we understand everything correctly.
> 
> As far as we know, the separate product card can be styled and created from scratch using Archive template (it is actually the template where one can set the layout and elements needed to be displayed for each of the products).
> 
> http://prntscr.com/mo7832
> 
> When you're creating an archive, you're creating the looks of one product from the archive to showcase it then in the Shop or on Archive page.
> 
> http://prntscr.com/mo78pv
> 
> Then it's important to set the layout (the number of columns, etc.) http://prntscr.com/mo78xc and set the created template as the one prioritized in the WooCommerce > Settings > JetWooBuilder http://prntscr.com/mo79se .
> 
> To pull this archive to the Shop page you'd need to use Products Loop widget. http://prntscr.com/mo7aq5
> 
> If there are any specific features are needed when creating an Archive (the separate product card), please, specify them.
> 
> Best regards from CrocoBlock team

**Thanks you! it helped me!**

**Comment by Floydtm** [comment]
by default, the woocommerce does not provide for the withdrawal of a counter on the product card
