### ISSUE TITLE
JetSmartFilters: Ability to search multiple meta fields at the same time

### ISSUE THREAD

**Issue by rentaterry** [CrocoBlock/suggestions#2409]
Hi guys!

Right now the search filter can be set by "Deafult WordPress search" or "By Custom Field (from Query Variable)".
Is it possible to give the ability of setting "By Custom Field (from Query Variable)" a multiple values, like:
Query Variable(s)*: meta-1, meta-2, term-1, term-2..., instead of title-only or single field searching ?

It would be great that I don't have to place many search boxes.

**Comment by anderoav** [comment]
+1

**Comment by Lonsdale201** [comment]
+1

**Comment by JMartinCollins** [comment]
+1

**Comment by Chalooo1993** [comment]
+1!

I was able to include multiple meta fields within the search criteria, unfortunately using an external plugin. It would be great if we can use JetSmartFilters to achieve this.

**Comment by delightfuldude** [comment]
> I was able to include multiple meta fields within the search criteria, unfortunately using an external plugin. 

Could you please tell us the name of the external plugin? I'm also in desperate need of this function.
Thank you!

**Comment by Dennisvb** [comment]
This would be a nice feature

**Comment by eSilverStrike** [comment]
This is now possible by separating the fields by a comma. 

Crocoblock still needs to update their docs as it does not mention this: https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-create-a-search-filter/

Unfortunately there appears to be no way to search by "Default WordPress Search" and a list of custom fields. I want a single text box that will search the title, editor, and any custom field I want of a custom post type. I guess I will need to add a separate feature request for this.

**Comment by MjHead** [comment]
Already implemented (you can separate the fields by a comma)

**Comment by damianrivadulla** [comment]
Although it allows you to add the fields separated by commas, when you perform the search if you put information from 2 different fields it does not find anything. 
The only way to show results is to put information from a single field, it doesn't make much sense how it works.
You can't mix information from different fields when you are searchig. Dont know why!

**Comment by araujolima129** [comment]
mesmo problema.
Basicamente quanto criamos um listing baseado em uma query quando utilizamos o smartfilter ele só funciona se colocarmos apenas uma queryvariable.
Será que a Crocoblock já está trabalhando em uma solução? Ou será que por código é possivel resolver o problema? Parece que até agora ninguem conseguiu.
