### ISSUE TITLE
Multi-Embed module

### ISSUE THREAD

**Issue by d27admino** [CrocoBlock/suggestions#241]
Hi,
My request is further to a previous request here: https://github.com/CrocoBlock/suggestions/issues/233

Now I have a better idea because I have noticed that the soundclound module from elementor can display other links such as spotify

idea
====
An embed module that can work decently with various embed urls from various services. 

The Current Soundcloud modules
======================
I can display ** either ** soundcloud or spotify or other urls. 
I guess it can even show youtube videos (not yet tested)

Shortcomings 
==========
The current soundcloud module has settings for souncloud, that does not have any effect on the other lists.  it is also possible that future updates of this module break its general compatibility.
 
soundcloud *playlist* url example https://soundcloud.com/user-442800355/sets/fmz
spotify *artist profile page share* example  https://open.spotify.com/artist/6wgL3WRNHXwsLzT6aE1eoY

Same or Different modules? 
====================
I guess a multi-module is complicated or heavier.
it Could be different modules (1 by service) if they can be hidden if empty (no space taken if possible).
That way it can still simulate an "either .... or ...." kind of function.

**Comment by MjHead** [comment]
This feature already exists in Dynamic Field widget. You need to add text custom field. Put required URL into it. Then in Dynamic field widget enable Fielter Field Output option and select Embed URL callback. Here an example with Spotify playlist - http://prntscr.com/npvzdt
