### ISSUE TITLE
Wishlist & Compare for custom post types

### ISSUE THREAD

**Issue by anderoav** [CrocoBlock/suggestions#2411]
Let's say the custom post type has Properties, I would like to add them to the wishlist and compare them by their meta fields. Wishlist is more needed, but comparing would come in handy.

This plugin has a similar action, but I wouldn't really need the option to make custom Wishlist "lists":
https://wpmissing.com/plugins/post-product-wishlist/

**Comment by Lonsdale201** [comment]
Why not use the data store? :)

**Comment by anderoav** [comment]
Do you have some tutorial to share, I didnt find anything 👎

**Comment by Lonsdale201** [comment]
https://youtu.be/z68WquK-LMU

I have many tutorial videos for crocoblock and elementor, example the simple compare system with jetengine data store modul, but unfortunately not have english language. but if you look carefully, you will understand the method. :)

**Comment by UraraReika** [comment]
Hello @anderoav !

Here official overview https://www.youtube.com/watch?v=aP_jHmX9hd4&feature=emb_logo&ab_channel=Crocoblock https://prnt.sc/wgqkp7

And documentation https://crocoblock.com/knowledge-base/articles/jetengine-data-stores-module-overview/?utm_campaign=need-help&utm_source=jetengine-modules&utm_medium=data-stores

**Comment by ardaniela** [comment]
> Hello @anderoav !
> 
> Here official overview https://www.youtube.com/watch?v=aP_jHmX9hd4&feature=emb_logo&ab_channel=Crocoblock https://prnt.sc/wgqkp7
> 
> And documentation https://crocoblock.com/knowledge-base/articles/jetengine-data-stores-module-overview/?utm_campaign=need-help&utm_source=jetengine-modules&utm_medium=data-stores

HI. It doesn't allow to introduce compare function jet?

**Comment by Lonsdale201** [comment]
> HI. It doesn't allow to introduce compare function jet?

With the Data store you have many options. Like as : compare, like , favorit, following etc.. What are you not understand? :)

**Comment by ardaniela** [comment]
> > HI. It doesn't allow to introduce compare function jet?
> 
> With the Data store you have many options. Like as : compare, like , favorit, following etc.. What are you not understand? :)

oh thanks 😅, I was seeing crocoblock data store tutorial (where the add favorites), now I saw your video where you create your compare button. Thanks for that.

btw, I can´t understand your videos tittle very well, so please, if you have any tutorial where you setting "listing map" widget for realestate website, share the link here 🙏
