### ISSUE TITLE
JetEngine Img Error in Oxygen Builder 

### ISSUE THREAD

**Issue by gaiuskong** [CrocoBlock/suggestions#2413]
JetEngine works flawlessly with Oxygen builder, except for the image field. 

Open any page/post using Oxygen on a clean/new/empty site, and you'll find all fields are working fine except the image field. It doesn't pull out the image.  

I wish to mention that JetEngine is ten times better than ACF Pro. Even though many people switched from Elementor to Oxygen, they still want to use JetEngine!  Please help.

**Comment by stasonua0** [comment]
Do all Jet Engine features work in Oxygen except image?

**Comment by gaiuskong** [comment]
I haven’t tested all of them, but all of the field types I needed work well
except the image field.

I’m willing to take a deeper look when I get back home tomorrow (right now
I’m in Washington DC supporting Trump, no computer access) and write you a
report.

In Oxygen group, we all say if Crocoblock works with Oxygen, it’ll be the
perfect combination in Wordpress.

Some Elementor users gradually switched to Oxygen and 100% who switched
never look back, like using Mac over PC.

You guys should seriously consider at least a Jet Engine integration with
Oxygen. I also pushed the same request on Oxygen side.

Since you replied (which means you may consider the request), I will put up
a post in Oxygen group asking at least two people to express the same.

I’m a huge fan of both, and I’m willing to advocate this combination for
free (writing reviews and marketing materials, posting in groups and
answering people’s questions)


Stanislav <notifications@github.com>于2021年1月6日 周三上午5:12写道：

**Comment by TODO4EVER** [comment]
I am only using elementor because of crocoblocks.

**Comment by johodesign** [comment]
I am exacty in the same shoe... Please make it work with Oxygen! I have changed to Oxygen from Elementor and JetEngine the only thing because of which I regret...

**Comment by ayhanmalkoc** [comment]
+1

**Comment by eddie-cleary** [comment]
I'm not leaving oxygen but I would buy crocoblocks if it were available for oxygen

**Comment by InternetSemplice** [comment]
Andrea 

*** 
If you, **friends @Crocoblock**, integrate **(at least) JetEngine with Oxygen Builder** not only you will **enlarge your customer base** (only the Official Oxygen User Group has 24.2K members – read Developers, mostly, with many clients and websites...) but... YOU WILL MAKE OUR LIFE MUUUUUCH EASIER! 
THX, Andy

**Comment by viabit-dev** [comment]
Another +1. 

Every day I look forward to some good news regarding Crocoblock and Oxygen Builder.

**Comment by michalczajka** [comment]
+1 

use crocobeock ltd with elementor but switch to oxygen - would love to use it with it.

**Comment by Josh-PCD** [comment]
+1

Migrating from Elementor to Oxygen due to performance improvements. Would love to keep using JetEngine et al instead of ACF, etc.

**Comment by igorek-zxz** [comment]
+1

**Comment by Floydtm** [comment]
https://www.facebook.com/groups/CrocoblockCommunity/posts/4533744080050311/

**Comment by r3th1nk** [comment]
+1
