### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by Delecroixfr** [CrocoBlock/suggestions#2417]
Hi

For galery slider, we chan choose if pictures thumbnail are showing vertical or horizontal. As desktop and mobile versions have different layouts, it will be nice to be able to choose different settings according to mobile or desktop. For now I am hiding vertical thumbnail slider on mobile and horizontal on computer, but it increases the loading time, as picture are often the more heavy file.

**Comment by UraraReika** [comment]
Hello @Delecroixfr !

We transfer our gallery slider from slick to swiper. With this we add some options hooks and now you can add following code to your child theme to get needed result.

```
add_filter('jet-woo-product-gallery/slider/options', 'aditional_gallery_settings' );
add_filter('jet-woo-product-gallery/slider/thumb-options', 'aditional_gallery_settings' );

function aditional_gallery_settings( $options ) {

	if ( ! array_key_exists( 'breakpoints', $options ) ) {
		$options['breakpoints']  = [
			0    => [ 'direction' => 'vertical' ],
			768  => [ 'direction' => 'horizontal' ],
			1025 => [ 'direction' => 'vertical' ],
		];
	} else {
		$options['breakpoints'][0]['direction'] = 'vertical';
		$options['breakpoints'][768]['direction'] = 'horizontal';
		$options['breakpoints'][1025]['direction'] = 'vertical';
	}

	return $options;
}
```
