### ISSUE TITLE
Filter and sort custom post type by JetReview rating

### ISSUE THREAD

**Issue by Bookit24** [CrocoBlock/suggestions#2419]
The filter type "rating" in JetSmartFilter makes it possible to filter WooCommerce products by rating.
But it's currently not possible to filter custom post types in a listing by average rating from JetReview.

Also, it's not possible to sort the list of custom post type in a listing by average rating from JetReview.

As both JetSmartFilters and JetReview are your products, it would be nice to be able to filter and sort based on rating values from JetReview :)

**Add an example of where this feature is already implemented. **

I have multiple post types created by JetEngine, and I use JetReview to allow visitors to review the posts.
There are several reasons why it won't make sense in my case to use WooCommerce and products, and custom post types works well. 

I've also created listings for each post type with JetSmartFilter to allow visitors to filter the posts.
However, it would be a nice feature for visitors to be able to sort by and filter by average rating of the posts.
But this doesn't work at the moment (I was in contact with support, and they advised me to add a feature request here).

**Comment by davedenis** [comment]
This seems like a no-brainer and I was surprised to see it's not possible currently.

**Comment by Dennisvb** [comment]
This functionality is a must!

**Comment by sara-kariv** [comment]
here they say here "JetSmartFilters plugin is a useful tool for applying filters to WooCommerce and Custom Posts."
https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-filter-woocommerce-products-by-rating/

but it's not realy working, why?

I Really need that please add this functionality

**Comment by Semonxue** [comment]
I just need user filter articles(not products) by rating. Please add this.

**Comment by shinTM** [comment]
done v2.1.0. Now you can add post average value to post metadata, and that mean you can filter you posts by the 
JetSmartFilters
