### ISSUE TITLE
JetCompareWishlist: Ability to Add Multiple Pre-Defined Lists

### ISSUE THREAD

**Issue by Lance2j** [CrocoBlock/suggestions#2426]
I need to be able to have MULTIPLE Predefined, publicly viewable Lists (not just wishlists) - i.e. wishlist, inventory, favorites, etc. I am currently using [Dynamic Content for Elementor's Add to Favorites widget](https://www.dynamic.ooo/widget/add-to-favorites/) to provide this feature on my site ([figvarieties.com](https://figvarieties.com/)). An example is located at [https://figvarieties.com/fig_varieties/black-madeira-ucd/](https://figvarieties.com/fig_varieties/black-madeira-ucd/), then select the Member Lists tab. It displays like this:

![Screen Shot 2021-01-07 at 6 55 09 AM](https://user-images.githubusercontent.com/57176884/103896997-7e69ce80-50b8-11eb-82d3-a5319ed4d353.png)

[JReviews](https://www.jreviews.com/) also has this feature, along with many other excellent advantages, but its product, 
[MyLists Add-On](https://www.jreviews.com/addons/mylists), is specific to its own product. But JReviews does an excellent job of implementing this feature:

![Screen Shot 2021-01-07 at 7 24 37 AM](https://user-images.githubusercontent.com/57176884/103897694-8b3af200-50b9-11eb-9eb4-e1c45516e093.png)

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

You can although use Data Store functionality from JetEngine plugin to achieve this results.

Thank you for your understanding.
