### ISSUE TITLE
Clean up JetSmartFilter filter result URL string 

### ISSUE THREAD

**Issue by justinpatrickkeller** [Crocoblock/suggestions#243]
I'm using JetSmartFilters (successfully) but am noticing a very unsightly (ugly) url string when applying a filter.

example: https://calendar.trailsisters.net/?jet-smart-filters=jet-engine%2Fdefault&_tax_query_month%5B0%5D=43&_tax_query_distance%5B0%5D=9&_tax_query_listing%5B0%5D=153

Is there any reason this needs to be this long? Here is an example from a well run website with a filter applied.

https://www.backcountry.com/Store/catalog/search.jsp?s=u&q=Ultimate+Direction

Is there anything that can be done to reduce the length of the text for JetSmartFilters search results? 

I think it would provide a much cleaner solution and more professional appearance. 

(note their use of u&q vs something much much longer)

Perhaps some modifications could be: 

jet-smart-filters (replace with 'f')
jet-engine (replace with 'j')
tax_query (replace with 't'
Regarding my filter names: (month, distance, listing) = Where can I change these to affect the URL string? I think I would like to change these to M, D, L for sake of brevity... 

Please let me know if there if there is a solution for the first part or if that is something that can be addressed in a future update. 

This could end up looking like: 

https://calendar.trailsisters.net/?f=j%2Fdefault&_t_m%5B0%5D=43&_t_d%5B0%5D=9&_t_l%5B0%5D=153

furthermore: is there any way to get the URL string to return the value of the search parameter instead of the post number. 

Essentially I think an enhancement that would make the filter result URL more clear and concise would be great. It would be more professional and would build trust with users of the platforms it's used on. Many times people use these links to link directly to a search/filter result. 

Thank you,
Justin

**Comment by vincenzoquarta** [comment]
I support user friendly filter results URL!

**Comment by realstephenzhao** [comment]
I need this functionality too!
Please make us a clean filter result URL.

**Comment by glissprints** [comment]
+1 for this!!! We need to be able to link directly to a product category/attribute!

**Comment by Juanmafortes** [comment]
+1, much needed...

EDIT: already changed filtering plugin.

**Comment by mcj777** [comment]
+1

**Comment by maxdegraaf0803** [comment]
Same issue overhere, I am thinking of using an other shop filter plugin :(

**Comment by vandijks** [comment]
We need this! Any update Crocoblock?

**Comment by mcj777** [comment]
+1

**Comment by moxet** [comment]
This issue is still there or any resolution?

**Comment by hybridmuse** [comment]
+1 Clients complain about those ugly urls and we're forced to tell them we can't do anything... Query parameters really shouldn't expose the plugins used under the hood : `?jet-smart-filters=woocommerce-archive%2Fdefault&jet_paged=2`

Is this fix on your roadmap?

**Comment by yeahoni** [comment]
+1
All my clients complain about these ugly addresses
Any news ?

**Comment by justinsideris** [comment]
+1. Badly needed plugin maintenance

**Comment by headghost** [comment]
Sadly this really is a dealbreaker for us. Love the functionalities so far, but these urls make the projects look amateurish and therefore unshippable by our standards.

If this doesn't get a response before the end of our trial period we will have to ask for a refund.
A careful search and replace in your plugin repos should fix this in no time.

@Floydtm @kaskad88 @SargasTM please kindly let us know your roadmap for this.
Thank you

**Comment by jonburdon** [comment]
Please prioritise this

**Comment by Floydtm** [comment]
Guys, we're working on it. We are gaining patience and stay tuned for updates. Thank you!

**Comment by andretoldo** [comment]
+1

**Comment by Floydtm** [comment]
https://prnt.sc/10js90p

**Comment by realstephenzhao** [comment]
> 
> 
> https://prnt.sc/10js90p

An in-depth explanation of how to do?

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/jetsmartfilters-filter-settings-overview/

**Comment by hybridmuse** [comment]
Thank you for working on this.
Will these features be implemented too? :
1- Customize filter slugs
2- Let search parameter values be slugs instead of ids
Thanks

**Comment by realstephenzhao** [comment]
But URL in plain mode is still NOT fixed, and there is still brand prefixes in permalink mode(like `/jsf/jet-engine/meta/.../pagenum/2` Wouldn't that result in SEO issues?).

What we want is this format `example.com/product/?mode=xxx+xxx&type=xxx...`, not `example.com/product/?jet-smart-filters=jet-engine%2Fdefault&mode=xxx+xxx&type=xxx` 

See FacetWP demo here. https://facetwp.com/demo/cars/?_vehicle_type=car&_driven_wheels=all-wheel-drive&_paged=2&_sort=horsepower 
See WP Gridbuilder demo here. https://demos.wpgridbuilder.com/?_product_type=backpacks&_product_price=11%2C190&_product_rating=3&_product_order=wpgb_product_price_active_asc&_page=2 
@Floydtm

**Comment by 93petter93** [comment]
+1

**Comment by Theo789595** [comment]
Do we have anything on this? Customizing url string to be simple and logical is important. Any solutions? Can we edit any plugin file to achieve this ourselves?

**Comment by paradisiacor** [comment]
This is a needed feature! Currently, the URLs are so ugly and bad for SEO. The URLs are necessary when you want to show prefilled hierarchical dropdowns etc. However, the URLs should be friendly and not 'ugly'.

**Comment by FabulousAgency** [comment]
+1 ... Just bought it and I am very disappointed by those ugly URLs

**Comment by pjfc** [comment]
+1 here. In my case the slug is /shop/jsf/jet-woo-products-grid/tax/

Especially the fact that Crocoblock productname is in the url is a big no-no, and should be fixed with priority.

I would advise to choose a neutral term like 'filter' instead of 'jet-woo-products-grid' (or similar brand names depending on the object that is being filtered), and additionally the option to rename that part of the slug to something appropriate for the site in question.

(I also I have no idea why the word 'tax' is in the slug, but that may be specific for my site and not related to this issue).

**Comment by hamed-azimi** [comment]
Users really don't care and don't want to see jet-smart-filters or jet-engine or tax_query and... in the URL. Instead, they want to see very short and clear URLs.

Instead of:
site.com/?jet-smart-filters=jet-engine%2Fdefault&_tax_query_brand%5B0%5D=43&_tax_query_material%5B0%5D=9&_tax_query_color%5B0%5D=153

They want:
site.com/brand/lg/material/metal/color/black/

(very clean, short, and user-friendly)

The way it currently is, is very confusing, with an ugly URL, which is also not good for SEO.  Imagine we want to share a URL of a page, where products are filtered based on 12 different fields/attributes. We end up having an essay instead of a short URL, which the user will have absolutely no clue what the URL is talking about.

On top of that, it is against the security in cases where we fully hide any evidence showing our website is based on WP. It literally exposes the fact that we use WP, and even some of the plugins we are using. Increases the change of attacks.

**Comment by hungryjos** [comment]
I agree that the urls are ugly. But if you want to share a pretty url, you could create some redirections in your site. (pretty url to ugly url)
Agreed: not an efficient solution, but a solution.

**Comment by hamed-azimi** [comment]
> I agree that the urls are ugly. But if you want to share a pretty url, you could create some redirections in your site. (pretty url to ugly url) Agreed: not an efficient solution, but a solution.

Although this can be called a "solution" for a very small website, but is literally a "nightmare" for my client's store with over 3K products, 100+ categories, +200 attributes/filters/meta -fields, and +100 brands.

**Comment by hungryjos** [comment]
Yes indeed, not an efficient solution, as I mentioned. 😊

**Comment by hybridmuse** [comment]
@Floydtm please reopen this issue

**Comment by pjfc** [comment]
In my case the slug is: /shop/jsf/jet-woo-products-grid/tax/

The fact that Crocoblock productname is in the url is a big no-no, and should be fixed with priority. Reasons:

- It looks unprofessional
- It is bad for SEO
  And less important but more of an irritant:
- I do not want to advertise Crocoblock in every filtered URL

I would advise to choose a neutral term like 'filter' instead of '/jsf/jet-woo-products-grid' (or similar brand names depending on the object that is being filtered), and additionally the option to rename that part of the slug to something appropriate for the site in question.

As an aside:
I also have no idea why the word 'tax' is at the end of the slug, but that may be specific for my site and not related to this issue.

**Comment by hungryjos** [comment]
/tax/ is probably from 'taxonomy'

**Comment by ghost** [comment]
Big +1. @Floydtm can you please let us know if the team is working on an update to improve the search slugs? I can't ship as is, and need to swap to another filter plugin if there isn't a fix in the pipeline.

**Comment by pjfc** [comment]
> /tax/ is probably from 'taxonomy'

Ah thanks, that makes sense.

**Comment by paradisiacor** [comment]
It would be great if we could get some intel on this from devs.

**Comment by e-cubed** [comment]
+1 Not only is the long URLS ugly, it's also impacting SEO.

**Comment by portalzine** [comment]
I have been following this thread for a while. 
I love JETEngine and Smartfilters, even switched from FacetWP on some projects!

Cleaning up the urls is possible, with some elbow grease ;)   

You have a couple of solutions to make this work:

Option 1:
// Filter the request itself and map to your own set of vars
//  parse_str + $_SERVER['QUERY_STRING'] + cleanup array + http_build_query 
`add_filter( 'request', function( $request ){});
`

Option 2:
// Do a template redirect, if you hate certain parameters, not ideal but it works 
// use the request filter for the rest
`add_action('template_redirect', function( ){} );
`

Option 3:
You can also use your own rewrite rules and mod proxy to cleanup urls.


Option 4:
As a big fan and user of Timber, you can also use their Routing Class
```
// Use Timber Router (https://github.com/Upstatement/routes)

	\Routes::map('your_request/:val', function($params){
            $query = array(				
				's' => $params['val']
			);
			$_REQUEST['s'] = $params['val'];
			$_REQUEST['_s'] = $params['val'];
			$_REQUEST['jsf'] = 'jet-engine';
            \Routes::load('search.php', $params, $query);
        });
```
Crocoblocks are using jsf_engine / jsf + others for values or keys, as they need to prevent collision of url variable keys.

But it would be nice, if the Crocoblocks devs could provide some easy filters to accomplish the above in a simple way.
WP FILTERS are so easy to add and not many devs seem to get it. Crocoblocks has established a good ecosystem, but in some areas they have grown too fast. Hard to keep up with documentation / requests ;)

BTW query vars are not bad for SEO, they are just ugly. Human readable urls are better for usability and offer a clearer hierarchy! Hierarchy has a SEO benefit, but i dont want every search result to get indexed, they were supposed to be "noindex"  in the past - changing lately ;)

Cheers and keep the good work up!
Alex

**Comment by vmavrikios** [comment]
This thread has been going on for 3 years now..
Some people added very constructive feedback.
But the issue of pretty url is still not addressed - which is a pity.
The revolutionary concept that Crocoblock caught the wave ..was to 'beautify' code and add a UI to dynamic functionalities that were not accessible to designers like me in the past.
Pretty urls is part of that wave and should follow soon ..hopefully.

I realized as I was writing to this thread now ..that these are hard times for Ukraine, hence for Crocoblock too.
May the force be with you ..and with us all.
Peace out!

**Comment by shahzaib786** [comment]
> I need this functionality too! Please make us a clean filter result URL.

Same here, I would need the clear permalinks like www.blabla.com/{category_name}  when filtering or clicking on each category.

**Comment by shahzaib786** [comment]
Could somebody tell me where is the solution for custom permalinks/slug when filtering?

**Comment by snelly1998** [comment]
Im guessing they haven't released a fix yet?

This shouldn't be closed

**Comment by riandeodato** [comment]
+1

**Comment by e-cubed** [comment]
+1

**Comment by fabio323ti** [comment]
@shahzaib786 - terribly sorry that I cannot use the filter within the categories page ... there was a snippet that allowed to correct the permalink but it has been removed. -
Did you solved?

**Comment by LincolnBinda** [comment]
My client complained about this url in the jetsmartfilter filter when I'm dealing with a custom post type, I just searched in several places and I can't find the solution... until I land here and see that many have this problem... Does anyone know if is it possible to remove or modify the part of "/jet-engine:xxxxxxx/ in the url?

**Comment by creativeart** [comment]
+1

**Comment by awebguy99** [comment]
I'm a bit confused if this can be done or not with the new Permalink or Plain options.
Can it be set so that the URL is something like mysite.com/shop-category/clothes/t-shirts ?
(Clothes being a category and t-shirts being a sub category)

If not, then +1 to this change.

**Comment by Bharat610** [comment]
+1...... waiting!!

**Comment by thorsolutions** [comment]
+1 

It is shocking that this critical usage of a Powerful Filtering solution is being ignored. It is quite basic as the basic requirement for any woocommerce website is to have the ability to share pre filtered lists.

**Comment by martinsober** [comment]
+1

The only reason I am considering other plugins

**Comment by morosmo** [comment]
+1

**Comment by Micheldebo** [comment]
+1 Need this!

**Comment by otomasz** [comment]
@Floydtm 
Will you solve the issue? 🤔

**Comment by realstephenzhao** [comment]
This is a major SEO issue. See this https://github.com/Crocoblock/suggestions/issues/2660 as well

**Comment by mbaierl** [comment]
> @Floydtm Will you solve the issue? 🤔

Very likely it will never be fixed. Unfortunately there are not a lot of alternatives for simply filtering products, posts or any other post type with Elementor.

**Comment by bbua97** [comment]
+1 This is much needed

**Comment by oryancooper** [comment]
+1 much needed for seo, just remove the plugin

**Comment by siscanu** [comment]
+1

**Comment by PavloPopravkin** [comment]
How much longer do we have to wait? How hard can it be?

**Comment by jeanlorencini** [comment]
I can't believe this hasn't been implemented yet

**Comment by moxet** [comment]
I guess they have covered the feature recently via
https://www.youtube.com/watch?v=n4whMIqMdRQ

**Comment by e-cubed** [comment]
Thanks for sharing @moxet ! Though pasting the friendly URL in the browser does not maintain the filters I don't think.

**Comment by blockmonkey** [comment]
@moxet thanks for sharing that video. It's so close to exactly what I need. Doesn't appear that you can use the Category Name as a Filter.

> I guess they have covered the feature recently via
> https://www.youtube.com/watch?v=n4whMIqMdRQ

**Comment by tompbsmith** [comment]
> @moxet thanks for sharing that video. It's so close to exactly what I need. Doesn't appear that you can use the Category Name as a Filter.
> 
> > I guess they have covered the feature recently via
> > https://www.youtube.com/watch?v=n4whMIqMdRQ

It would be great if we could have this feature too.

I've got pretty-ish URLs with the filter names showing up nicely e.g. **/projects/filter/services:226**

However it would be great if the ":226" could be replaced with the Taxonomy category's slug e.g. **/projects/filter/services:land-survey** and **/projects/filter/sector:construction**

There is already the functionality to add a custom slug for Taxonomy categories, so it would be great if we could replace the category ID in the URL with the category slug.

Are there any plans for this?

P.S. For now I'm manually adding about 50 aliases for each such as: /services:226 -> /services:land-survey which works but is obviously a lot of manual work if you have a lot of taxonomies with a lot of categories!

**Comment by mrjayy5** [comment]
> > @moxet thanks for sharing that video. It's so close to exactly what I need. Doesn't appear that you can use the Category Name as a Filter.
> > > I guess they have covered the feature recently via
> > > https://www.youtube.com/watch?v=n4whMIqMdRQ
> 
> It would be great if we could have this feature too.
> 
> I've got pretty-ish URLs with the filter names showing up nicely e.g. **/projects/filter/services:226**
> 
> However it would be great if the ":226" could be replaced with the Taxonomy category's slug e.g. **/projects/filter/services:land-survey** and **/projects/filter/sector:construction**
> 
> There is already the functionality to add a custom slug for Taxonomy categories, so it would be great if we could replace the category ID in the URL with the category slug.
> 
> Are there any plans for this?
> 
> P.S. For now I'm manually adding about 50 aliases for each such as: /services:226 -> /services:land-survey which works but is obviously a lot of manual work if you have a lot of taxonomies with a lot of categories!

Agreed, using the slug instead of IDs would make more sense nowadays. Hope this update is already planned.

**Comment by jonathanbeadle** [comment]
> > @moxet thanks for sharing that video. It's so close to exactly what I need. Doesn't appear that you can use the Category Name as a Filter.
> > > I guess they have covered the feature recently via
> > > https://www.youtube.com/watch?v=n4whMIqMdRQ
> 
> It would be great if we could have this feature too.
> 
> I've got pretty-ish URLs with the filter names showing up nicely e.g. **/projects/filter/services:226**
> 
> However it would be great if the ":226" could be replaced with the Taxonomy category's slug e.g. **/projects/filter/services:land-survey** and **/projects/filter/sector:construction**
> 
> There is already the functionality to add a custom slug for Taxonomy categories, so it would be great if we could replace the category ID in the URL with the category slug.
> 
> Are there any plans for this?
> 
> P.S. For now I'm manually adding about 50 aliases for each such as: /services:226 -> /services:land-survey which works but is obviously a lot of manual work if you have a lot of taxonomies with a lot of categories!

Any plans for this functionality? It would be very useful.

**Comment by robbygeybels** [comment]
any progress on this ?

**Comment by blockmonkey** [comment]
Following up any progress?
