### ISSUE TITLE
Line Chart and Bar Chart pull data from Repeaters. Also dynamic Scale Axis Range and Step Size in charts

### ISSUE THREAD

**Issue by TODO4EVER** [CrocoBlock/suggestions#2433]
Hey, Is there anyway to add the ability to make charts pull data from JetEngine Repeaters ? I am looking for something like this
https://i.imgur.com/mmOHtrl.png
Where the client enters keeps entering dates and values like this
https://i.imgur.com/GsuQ40e.png 

I tried the dynamic addon but the charts are not supported :(

**Comment by reganmcgregor** [comment]
+1

**Comment by anderoav** [comment]
+1

**Comment by AaronHaehnerDesign** [comment]
+1

**Comment by kaskad88** [comment]
Added in JetElements v2.5.6

**Comment by TODO4EVER** [comment]
Hello, can we also please include the "Labels" in the dynamic repeater function ? This one https://bit.ly/3mTQiiQ
I am finding in difficult to do what I want with the current implementation.
Thanks in advance.

**Comment by remygfx** [comment]
Question: Why is this closed? the dynamic data with repeater fields doesn't appear to work
If it does, you perhaps need to explain what format is expected

I want to send 3 repeater fields: 1. the array series names, each item = text field, 2. the array of data labels, each item = text field, 3. the array of data items in same order as the array of data labels , each item = number field

 when you enable dynamic data, my entering various combinations does not produce any effect
