### ISSUE TITLE
Jetwoobuilder: Add option to exclude sale products in productgrid

### ISSUE THREAD

**Issue by knireis** [CrocoBlock/suggestions#2435]
In jetwoo products grid i can query by and include sale items. 
Can you make it an option so i can exclude sale items as well?
Now there is only an option to exclude by product id, which with 100+ sale products is not practical

**Comment by UraraReika** [comment]
Hello @knireis!

For cases with custom queries and specific parameters we implement "Query id" option https://prnt.sc/xaiohw. So you can put some value here https://prnt.sc/xais2p like that. Than you can write action in your child theme `jet-woo-builder/query/without-sales`, and this action will only have influense on particular widget that has this `without-sales` query id value.

**Comment by knireis** [comment]
thanks, mean this https://crocoblock.com/freemium/tools/wp-query-generator/?

could you make a screenshot of how to set this up in the query with non-sale item?

**Comment by UraraReika** [comment]
As i said, add this `without-sales`, for example to Query ID option in Product Grid widget. Then write this code to your child theme:
```
add_action( 'jet-woo-builder/query/without-sales', 'get_products_without_sales');

function get_products_without_sales( $query ) {
	$product_ids_on_sale    = wc_get_product_ids_on_sale();

	$query->query_vars['post__not_in'] = $product_ids_on_sale;

	return $query;
}
```

**Comment by knireis** [comment]
Thanks, but saving the code in childtheme functions.php gives an error and i cannot save it

**Comment by knireis** [comment]
it is not working as expected unfortunately, i still see sale items in the grid

**Comment by UraraReika** [comment]
Please connect with our support team.
