### ISSUE TITLE
JetSmartFilters: Show or hide filters based on a selected filter

### ISSUE THREAD

**Issue by maxwellhibbert** [Crocoblock/suggestions#244]
It would be good if specific filters could be shown only for relevant products. So if a user selects a product category, then only filters relevant to products in that category are then shown..

**Comment by mcj777** [comment]
+

Поддерживаю! Отображать в фильтрах только значения, которые имеют товары из текущего списка на странице более разумно, чем выводить полностью все значения на каждой странице.

**Comment by jcmatoskx** [comment]
Supported 100%

**Comment by davidk82** [comment]
100% supported

**Comment by javiercriado** [comment]
I think JetSmartFilters have a really good potential of being a powerful search tool.

This feature among others could make it a better search system.

**Comment by donderjager** [comment]
I support this request.

In the meantime. Is there a plugin that does have this feature?

**Comment by javiercriado** [comment]
No. Just a good old jQuery coding my dear

**Comment by vincenzoquarta** [comment]
Supported

**Comment by cookra** [comment]
This is an absolute must, bad ux experience without.

**Comment by Floydtm** [comment]
@maxwellhibbert, You can implement this using the [indexing](https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-set-indexer-option-for-filters/) options.
