### ISSUE TITLE
Allow multiple post types for the Calendar Listing

### ISSUE THREAD

**Issue by aaronkine** [CrocoBlock/suggestions#2443]
I have two post types... Event and Featured Event. I need the ability to display both post types on the Calendar.

The Listing Grid Element allows you to add multiple custom post types as shown here...
https://pasteboard.co/JIJ5yBt.jpg

I would like that same functionality for the Calendar Widget
https://pasteboard.co/JIJ6ChO.jpg

So I figured out how to do this by editing the "listing-item.php"  and changing line 65:
Line 65:				'type'    => Elementor\Controls_Manager::SELECT,

I deleted that line and added this:
				'type'        => Elementor\Controls_Manager::SELECT2,
				'label_block' => true,
				'multiple'    => true,

Here is what that code did: CROCOBLOCK! Can you please make this change to the JenEngine Core Code (listing-item.php Line 65) to allow multiple post types to be added to the Calendar Listing Item.
https://pasteboard.co/JILPvnf.jpg

**Comment by pietrondo** [comment]
I don't understood. I need to have in my calendar multiple listing but, how can i do? thx

**Comment by kaskad88** [comment]
Added for the next version ( v2.10.1 )
