### ISSUE TITLE
 JetSearch issues.

### ISSUE THREAD

**Issue by salbatyku** [CrocoBlock/suggestions#2444]
Hello,

I have built a guitar shop with elementor+hello-elementor theme + crocoblock.
I have a difficult issue with JetSearch.

Always when searching for a product it returns this.

**Warning: get_object_vars() expects parameter 1 to be object, null given in /public_html/wp-content/plugins/jet-search/includes/ajax-handlers.php on line 142**

Php Version: 7.3
Latest Wordpress Version
Latest Elementor Version
Few additional plugins (for amazon/ebay listings), some checkout fields editor and thats pretty much it.
Can you please help me sort out this issue?

Thank you in advance, lets fix the bug!

**Comment by honlapdavid** [comment]
@salbatyku 

TIP FOR YOU

check your wordpress version and update!
and try rollback (downgrade) plugin.

**Comment by salbatyku** [comment]
@honlapdavid already tried rolling back the plugin versions.
But it was working 1 week ago with no problems, i have not updated anything (until i saw the error). 
So error occured, updated (thinking it would solve), after that i rolled back and still wasn't working. 
I ended up hidding the 'warning'
But is it worth checking the plugin code.

**Comment by kaskad88** [comment]
@salbatyku Thanks for your feedback.

We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
