### ISSUE TITLE
JetAppointments: Missing "Add new reservation" in admin

### ISSUE THREAD

**Issue by honlapdavid** [CrocoBlock/suggestions#2449]
This feature missing for me (for admin). Because sometimes clients want to book by phone.

<img width="1818" alt="Snímka obrazovky 2021-01-11 o 8 04 37" src="https://user-images.githubusercontent.com/54839439/104153986-036c2500-53e4-11eb-8557-15d63627adcf.png">

**Comment by catherinewiltshire** [comment]
+1 this is essential!

**Comment by catherinewiltshire** [comment]
@MakhonkoDenis any update on this?
Also the ability to mass import appointments (with .csv file etc) is essential for this type of plugin.

The appointment plugin feels so unfinished, an update or a milestone on when this essential functionality will be added would be great!

**Comment by hybridmuse** [comment]
+1

Workaround for now (for membership websites):
Use [User Switching plugin](https://fr-ca.wordpress.org/plugins/user-switching/), connect as user and book appointment through frontend UI.

**Comment by MakhonkoDenis** [comment]
Hi,
This feature was added in version 1.4.0
