### ISSUE TITLE
Set up advance prices by seasons or date ranges

### ISSUE THREAD

**Issue by tavolucas** [CrocoBlock/suggestions#2452]
For any professional reservation plugin it is essential to be able to adjust different prices for different seasons: High Season, Low Season, Holidays. It occurs to me that it would be a very good idea to include this option in the "Sep up advance pricing rates" window where we could define a "special price" for a certain date range

**Comment by DigitalBerry** [comment]
Any update on this? If not coming soon, I will be looking for a refund and find another solution...

**Comment by 8persap** [comment]
Please can you add seasonal pricing as a priority? This plugin is so good and well thought out on every level but this. Seasonal pricing is key to any rental or hotel bookings. Without it, it rules out Jetbooking as a viable option. Please can you commit to addressing this? Thank you. 👍

**Comment by maxie71** [comment]
I originally raised this in September 2020 in - Jet Booking - Seasonal Pricing #1818. As yet I have not seen any update on this? Please can someone do the courtesy of providing an update as to whether this has made it to the development road map or not and if so please provide some form of timeline for delivery of such critical functionality for a booking plugin, or at least one that want to be taken seriously.

**Comment by tavolucas** [comment]
You are right. it's a shame they don't take us seriously. I had to change the entire reservation system to woocomerce booking because they never gave it a solution. Anyway, what else can be done? I want to retire to pass all these plugins that have us kidnapped

> I originally raised this in September 2020 in - Jet Booking - Seasonal Pricing #1818. As yet I have not seen any update on this? Please can someone do the courtesy of providing an update as to whether this has made it to the development road map or not and if so please provide some form of timeline for delivery of such critical functionality for a booking plugin, or at least one that want to be taken seriously.

**Comment by slobodandzebo** [comment]
I wrote short tutorial for make it work
https://github.com/Crocoblock/suggestions/issues/1818#issuecomment-853396224

**Comment by BlueteraLLC** [comment]
I would like to see this too.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.4.0 version. You can fell free to check it out.

Thank you!
