### ISSUE TITLE
JetWooBuilder Custom Checkout Payment Widget

### ISSUE THREAD

**Issue by mrd1Que** [CrocoBlock/suggestions#2454]
**Describe the bug**
I use the plugin "Germanized" for our special privacy in germany. with this plugin, the heading and conditions checkbox in the payment widget is shown twice.
i also contacted the developer of "Germanized" and he told me:

there is a bug in the jet-woo-builder/templates/jet-checkout-payment/global/index.php.
the hook woocommerce_review_order_before_payment is also called in the function woocommerce_checkout_payment() (woo-template checkout/payment.php)

Please fix this bug.

**To Reproduce**
1. Go to 'https://mookho.de/shop/'
2. Add a product in the cart
3. Go to 'https://mookho.de/kasse'
4. See the payment widget

**Screenshots**
https://prnt.sc/wl3dhk

**Comment by T-Mack78** [comment]
I have this same issue. The support from Crockblocks was not able to help me. How can this hook be fixed. Please help.

**Comment by UraraReika** [comment]
For quick fix you can simply override this template file in your child theme. From our side we will implement this fix in closest release after 1.7.5

**Comment by alexanderpankart** [comment]
#2485

**Comment by Robinsgood** [comment]
Hi do you have a solution for this problem?

**Comment by Robinsgood** [comment]
@UraraReika Hi do you have a solution for this problem? On my checkout are also 2 payment sections using Jetwoobuilder and Germanized

**Comment by ThomasTester** [comment]
Any Updates? Is there a solution to this Problem? I hide the “double Boxes” with CSS, but there are some other Layout-Problems like "moved input fields":-( In the Elementor preview everything looks fine, but not in the live site ... no matter whether “kava” or another theme is used.

**Comment by pbaddock** [comment]
I am having the same issues - was a fix ever delivered for this?

**Comment by pbaddock** [comment]
> I am having the same issues - was a fix ever delivered for this?

(actually my prob was different - my entire checkout page contents were being duplicated but it was caused by me not understanding how to configure the setting in woocomm > jetwoobuilder - i had not separated out the coupons into their own separate jetwoo template - sorry for the distraction)
