### ISSUE TITLE
JetEngine Forms Steps problem with Next button disabled if previous field is Required and Chrome is used

### ISSUE THREAD

**Issue by marcosrijo** [CrocoBlock/suggestions#2456]
**Describe the bug**
Good afternoon! It happens to someone else in Chrome that in a form divided into steps, when filling in a required field and clicking Next, the button is not enabled? Just by clicking outside you can, if not the cursor remains in the field. It only happens in Chrome, in Firefox when being in a required field you can go directly to the Next button without clicking outside the field.

**To Reproduce**
1-Create a form in steps
2-That the last field of the first step is a Required Input
3-Click Next (it could not be done because the button is still disabled and the cursor is at the last Input)
4-Click outside any entry
5-Click Next (now if you go to the next step)

**Expected behavior**
That when you finish filling in any input and click Next, the button is enabled as in Firefox.
Several users reported to me that they could not fill in the form since it is a natural behavior to go from one field to another or to a button and clicking elsewhere to enable a button is not what is expected.

**Desktop:**
 - Windows 10 64 Bits
 - Chrome Versión 87.0.4280.141 (Build oficial) (64 bits)
 - Firefox Versión 84.0.2 (64-bit)

**Comment by julianderyk** [comment]
+1

**Comment by stasonua0** [comment]
+1 Wrote several times already on this issue, inserted this script to solve the problem

<script>
jQuery(document).ready(function ($) {
  $(".jet-form__field").keyup(function () {
    $(this).trigger('change');
  });
});
</script>

**Comment by marcosrijo** [comment]
> +1 Wrote several times already on this issue, inserted this script to solve the problem
> 
> <script> jQuery(document).ready(function ($) { $(".jet-form__field").keyup(function () { $(this).trigger('change'); }); }); </script>


That solved the problem! Thank you!

**Comment by MPHood** [comment]
This should be implemented as default behaviour! Thanks for the code!

**Comment by kaskad88** [comment]
Fix for the next version! Thanks for your report!

**Comment by tyekynan** [comment]
> +1 Wrote several times already on this issue, inserted this script to solve the problem
> 
> <script> jQuery(document).ready(function ($) { $(".jet-form__field").keyup(function () { $(this).trigger('change'); }); }); </script>

Pardon my stupidity, but I am having this issue. Where can I place this script? Thanks
