### ISSUE TITLE
Move the < a href > tag inside the < div class="jet-woo-products__inner-box" > on the Products Grid widget

### ISSUE THREAD

**Issue by tiago-123** [CrocoBlock/suggestions#2461]
Hello,

My request is regarding the Products Grid widget.
I would like to suggest to move the < a href > tag inside the < div class="jet-woo-products__inner-box" >, in order to make the whole product box clickable, instead of just the thumb and title. This would be much better for mobile users!
Also, this should not impact functionality with other plugins such as whishlist and compare, because those buttons are usually placed on top of the thumbnail (which is already clickable). Therefore, as long as those buttons continue to be on top of the product box, it wouldn't affect their functionality.

Thank you.
Sincerely,
Tiago.

**Comment by Floydtm** [comment]
Thank you for contacting us! However, we are forced to deny your request. All this you can do in the plugin yourself. To do this, you need to rewrite the template. Thank you!
