### ISSUE TITLE
Pagination doesn't work correctly

### ISSUE THREAD

**Issue by typ7280** [CrocoBlock/suggestions#2467]
I have created Custom Type Content and added to page by using Dynamic listings. I have also created pagination but when I clicked to page 2, it cannot click back to page number 1. Moreover, page number active is stuck at number 1 too. How can I solve this solution?
![sss](https://user-images.githubusercontent.com/25146317/104429910-b2615a00-55b8-11eb-9a1f-f79b32521b33.gif)

Here is Listing Grid setting:
![Screen Shot 2564-01-13 at 16 01 24](https://user-images.githubusercontent.com/25146317/104430391-30256580-55b9-11eb-8c43-bd2ec97e6240.png)

And JetSmartFilters Pagination setting: 
![Screen Shot 2564-01-13 at 16 01 38](https://user-images.githubusercontent.com/25146317/104430418-387da080-55b9-11eb-9d14-f4eb5dadb18e.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 
 - Browser: chrome
 - Version Version 87.0.4280.141 (Official Build) (x86_64)

**Comment by UraraReika** [comment]
To resolve your request, you need to contact our support team and provide access to your site. Thanks you!
