### ISSUE TITLE
Jet Engine Slider Trend

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2468]
Hello, consider making a similar display in Jet Engine Slider https://prnt.sc/wmgohk, namely, the part of the post on the right / left goes out of the screen and is not visible to the user.

I see that this is a direct trend in the case of mobile versions of sites.

It is also necessary to enable this function and, in general, display the listing as a slider only on mobile devices.

/*Оригинал*/
Здравствуйте, рассмотрите возможность сделать в Jet Engine Slider подобное отображение https://prnt.sc/wmgohk, а именно часть поста справа / слева выходит на пределы экрана и не видна пользователю. 

Вижу что это прям тренд в случае с мобильными версиями сайтов. 

Так же необходимо дать возможность включить эту функцию и в целом отображение листинга в виде слайдера только на мобильных устройствах.

**Comment by Floydtm** [comment]
Check these options in the listing grid widget https://prnt.sc/x7otkw

**Comment by stasonua0** [comment]
Thanks, didn't notice this feature

**Comment by stasonua0** [comment]
https://prnt.sc/x7qo5a I have it wrong

**Comment by Floydtm** [comment]
Disable the slider. Then you will have the option you need https://prnt.sc/x7rjz7

**Comment by stasonua0** [comment]
Thanks!
