### ISSUE TITLE
Date field from JetEngine not showing correct in the listing

### ISSUE THREAD

**Issue by pintolog** [CrocoBlock/suggestions#247]
Hi,
I created a date field with JetEngine.
When i fill it with date, it's showing good in the editor,
In the live site & elementor i see a random numbers instead of the date

![image](https://user-images.githubusercontent.com/7497319/57559575-39454480-738b-11e9-95f0-826da964f8b6.png)

**Comment by Floydtm** [comment]
Hi,

**Comment by ibtisamahmad** [comment]
Facing Same issue but your image link not working
