### ISSUE TITLE
JetEngine - Yoast SEO reading of JetEngine's Custom fields

### ISSUE THREAD

**Issue by danielbimson** [CrocoBlock/suggestions#2471]
Sorry if it has already been asked but It would be brilliant if Yoast SEO could work with JetEngine's Custom Fields. Just like ACF has. If there are any workarounds I would like to know as well in the mean time.

**Comment by anderoav** [comment]
+1

**Comment by iAbhinavJain** [comment]
+1

**Comment by jesskiri** [comment]
+1 
This is a must!

**Comment by kaskad88** [comment]
I merged this issue with #1502, which is on the same subject so we could deal with it more efficiently.
