### ISSUE TITLE
Double opt-in for registration possible?

### ISSUE THREAD

**Issue by alexander-pankart** [CrocoBlock/suggestions#2473]
Hi,

registration without double opt-in is becoming quite problematic in the EU.

Can this "simply" become part of the registration widget or do other areas of WordPress play a role here?

I think it would be an immense plus for many users if this could be covered by a Crocoblock widget.

1. user creates an account
2. this account is only activated when the user clicks on the link in his email.
3. webmaster happy, lawyers happy, customers happy

Is this already covered by another Jet widget? (The "Subscribe" widget for newsletters works here with double opt-in, but without creating an account. Just a newsletter).

Best regards,
Alexander

**Comment by kochhase** [comment]
+1

**Comment by RonnyBode** [comment]
+1

**Comment by Spacefunls** [comment]
+1

**Comment by alexanderpankart** [comment]
Any updates on that?
Maybe with JetFormBuilder?
The EU Law won't go away any time soon :D

**Comment by girafffee** [comment]
Hi everyone)
This feature was included in version 3.2.0

https://jetformbuilder.com/features/how-to-create-registration-form-with-email-verification/
