### ISSUE TITLE
Add support for Jetwoobuilder products grid with "Products By Attributes and Variations for WooCommerce" 

### ISSUE THREAD

**Issue by ingramleedy** [CrocoBlock/suggestions#2474]
"Products By Attributes and Variations for WooCommerce" and its link: https://woocommerce.com/products/products-by-attributes-variations-for-woocommerce/ allows to display variations in the product listing grid.  However JetWooBuilder doesnt display. Please add support to this (and I would assume this would also allow JetWooFilters to work)

**Comment by UraraReika** [comment]
Hello @ingramleedy !

We have troubleshooting post about such kind of integration. 
Check this out https://crocoblock.com/troubleshooting/articles/how-to-add-attractive-variation-swatches-to-woocommerce-archive-page/
