### ISSUE TITLE
JetReviews: RE-SUBMISSION - Add Content Field & Styling for “Details” Button Label

### ISSUE THREAD

**Issue by Lance2j** [CrocoBlock/suggestions#2475]
I need to work on being more clear. This is a re-submission (previously #2442).

What I stated before: There does not appear to be a content field for the "Details" label. It will also need styling.

What I mean is:

![Review Details Field](https://user-images.githubusercontent.com/57176884/104620173-50eec900-5654-11eb-8fb2-882dc007154f.png)

**Comment by shinTM** [comment]
this label is deprecated, we decided to change the view of the details, for now its option https://prnt.sc/xn46wm Now you can choose one of the options for displaying the rating fields. You can find it in next release v2.1.0

**Comment by Lance2j** [comment]
Thanx.
