### ISSUE TITLE
Please add Icon Gap + Before/After text  in "Dynamic link" widget

### ISSUE THREAD

**Issue by d27admino** [CrocoBlock/suggestions#248]
I think this one is easy :-) 

Please add a **Gap" setting for the Icon in the Dynamic Link** widget
Would also be great to have a **before/after** text holder.

So I can input something like;  (( [icon] gap [Website of the user] : click me  )) 
where "click me" receives the dynamic url.

Thanks a lot !
Mehdi

**Comment by MjHead** [comment]
Icon Gap option added (rather, visibility of this option fixed :) ) into Style Tab - http://prntscr.com/nq4s72. This update will came with 1.4.2 version. At this moment you can make this option visible if switch Icon Position option to After Label and back.
As for second part of suggestion - you can already do this if combine macros and static value in Label
option - http://prntscr.com/nq4tpl
