### ISSUE TITLE
JetEngine - Focus on conditional fields

### ISSUE THREAD

**Issue by iamdanbarrett** [CrocoBlock/suggestions#2480]
Can the forms be update or at least add an option so that if a user enters data into a field, that the conditional field you wish to reveal appears immediately if there is a match?

**Example: Access Code**

If there is a field with an access code (preset) and you wish to reveal a new field IF the code matches, the field should appear without clicking out of the field as it confuses the user. Currently, the focus needs to be removed from the field in order fo the hidden field to reveal itself.

**Comment by kaskad88** [comment]
Added to the next version.

**Comment by iamdanbarrett** [comment]
> Added to the next version.

Was this added to the latest release?
