### ISSUE TITLE
(Bug, Woo Builder Output) Duplicate headings, elements and missing buy button in checkout

### ISSUE THREAD

**Issue by alexander-pankart** [CrocoBlock/suggestions#2485]
In the checkout, certain areas are displayed twice or are not displayed if you work with the "Germanized" plugin. Since there are only 2 legally compliant plugins in the entire German-speaking area (DSGVO), and this is the only one with a free version, I guess that many will work with it.

[Plugin](https://vendidero.de/woocommerce-germanized)

The "buy" button disappears completely.
The terms and conditions checkbox is displayed twice.
Some headings appear twice.
The payment method has to be selected twice.

![WooSettings](https://user-images.githubusercontent.com/69971188/104834509-1f6a3d80-58a0-11eb-8d92-5c4bc3792d3f.PNG)

![NoBuyButton](https://user-images.githubusercontent.com/69971188/104834559-7a9c3000-58a0-11eb-9b29-59dc4cbc7292.PNG)

Also tried on Kava /w Zolden Template from Crocoblock:

![zolden](https://user-images.githubusercontent.com/69971188/104836793-ca82f300-58b0-11eb-805d-96b4bdf3b0be.PNG)

This affects the Widget: "Checkout Payment" in Woo Builder.
In Edit with Elementor, there is no graphical or technical bug. Only in Frontend.

![ElementorBackendButton](https://user-images.githubusercontent.com/69971188/104834601-d5358c00-58a0-11eb-8190-d9b36c1e4652.PNG)

Best regards,
Alexander

**Comment by alexanderpankart** [comment]
Thank you very much for assigning my request.

**Comment by UraraReika** [comment]
I merged this issue with #2454, which is on the same subject so we could deal with it more efficiently.
