### ISSUE TITLE
Jet Elements Pricing table HTML tag

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2486]
Hello, make it possible to independently choose the necessary tags for titles and subheadings in the Pricing Table widget - https://prnt.sc/wz1kxg

/*Оригинал*/
Здравствуйте, дайте возможность самостоятельно выбирать нужные теги для заголовков и подзаголовков в виджете Pricing Table - https://prnt.sc/wz1kxg

**Comment by kaskad88** [comment]
Added to the next version!
