### ISSUE TITLE
Add dynamic display text for DYnamic Link widget

### ISSUE THREAD

**Issue by d27admino** [CrocoBlock/suggestions#249]
Once request https://github.com/CrocoBlock/suggestions/issues/248#issue-442933979

May be it is interesting to make an advanced dynamic link module

Exeample: 
dynamic link = http....
and  dynamic displayed text = User's website Website name

result = clickable text where both text and url are defined by the user input.
So the link can show different thing in a listing, without the need to add addditional text.
+ it also needs the icon and gap settings + before/after texts.

I populate the fields with the " enter post meta field key"   option, so i also need that one :-)

Thanks a lot
Mehdi

**Comment by MjHead** [comment]
We fixed %current_meta% macros to force it work this way. http://prntscr.com/nq4voz, https://prnt.sc/nq4vyw. This fix will be released wit 1.4.2 in few days.
