### ISSUE TITLE
Jetengine Exclude parents taxonomies ?

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#2492]
As soon as I realized that I couldn't display just one, or more parent taxonomies with jetengine or elementor I tried to do it myself (with a lot of suffering)

```
/*output only taxonomy parent*/
add_shortcode( 'parent', 'taxonomy_parent' );
function taxonomy_parent( $atts ){
  
    $atts = shortcode_atts( array(
        'link' => 'true',
        'taxonomy' => 'property_type' // my default taxonomy 
    ), $atts, 'parent' );

    global $post;
    $terms = wp_get_post_terms( $post->ID, $atts['taxonomy'] );

    ob_start();
    foreach( $terms as $term ){
        if( $term->parent != 0 ){
            $parent_term = get_term( $term->parent, $taxonomy );
            if ($atts['link'] !== 'false') {
                printf( '<a href="%s">%s</a>', esc_url( get_term_link($parent_term) ), $parent_term->name );
            } else {
                echo $parent_term->name;
            }
        }	   
    }

    return ob_get_clean();
}
```

usage :
[parent]
[parent link = "false"]
[parent taxonomy = "your_taxonomy"]

I thought I was **saved** now ! and go back to jetengine finish some modifications and this time **exclude** the parents from my listing
and it was at this **precise moment** that I realized [my nightmare is not over yet !](https://www.awesomegifs.com/wp-content/uploads/no.gif) what ?

![jetengine 1](https://user-images.githubusercontent.com/75816572/104861462-3e181500-5930-11eb-9edd-849284c82838.jpg)
![jetengine 2](https://user-images.githubusercontent.com/75816572/104861472-43755f80-5930-11eb-90b1-8719e2c8df96.jpg)

why is my life so difficult with taxonomies?
someone explain to me where to find the code for that or if I missed an episode to manipulate the taxonomies?

you got what will be even more terrible? it is not to receive a response or solution to this situation and I will spend the next few days finding codes for this task. my life is really hard with wordpress. 
don't worry I will come back to share my codes with you :)

**just a small note,** you have to exclude them dynamically, like %parent% ?? my client or my clients will have the possibility to play and modify and add taxonomies, I let you imagine the terrible **disaster** if I put IDs like 150 and 151 (in my case precise) tomorrow there will be what? ID 164 and 198?

**Comment by pierrehansen** [comment]
I'm having the same exact problem. I want that Jet listing widget only show posts that have a parent category and leave out all children. So many possibilites, so many fields in thoses widgets. None of them are working. Very time consuming.

**Comment by jtas01** [comment]
I tried running your code, but it gives me a blank page. Maybe this will help.

    add_shortcode( 'parent', 'taxonomy_parent' );
    function taxonomy_parent(){
	    $taxonomies = get_terms( array(
		    'taxonomy' => 'property_type',
		    //'parent'   => 0, //you can show parent from here as well - no need for the below if conditions then.
		    'hide_empty' => false
	    ));
	
	if ( !empty($taxonomies) ) :
	$output = '<ul class="parent" >';
	foreach( $taxonomies as $category ) {
		if($category->parent != 0){ // change != to == to get only parents; remove this condition if set parent earlier in get_terms()
			$output.= '<li>';
			$output.= esc_html( $category->name );
			$output.='</li>';
		}
	}
	$output.='</ul>';
	echo $output;
	endif;
}

**Comment by iamamolsarker** [comment]
You can achieve this with custom query builder from jetEngine he first query you build to get all parent categories: https://prnt.sc/yFy_ZcYUcBlO
The second query - you exclude categories from the first query
https://prnt.sc/uI4TQxUdxpAB
Then select the second query in the listing grid widget

**Comment by ghost** [comment]
> You can achieve this with custom query builder from jetEngine he first query you build to get all parent categories: https://prnt.sc/yFy_ZcYUcBlO The second query - you exclude categories from the first query https://prnt.sc/uI4TQxUdxpAB Then select the second query in the listing grid widget

thank you this post is from 2021...
 since I switched to bricks builder I no longer have to worry
I close this post thank you.
