### ISSUE TITLE
WooBuilder Shop Page Template View Default Toggle By Device

### ISSUE THREAD

**Issue by bunkermediauk** [CrocoBlock/suggestions#2494]
The ability to set which custom template for shop/archive pages displays by default across devices, depending on the media query/device size would be a huge asset to the features of the WooBuilder.

For example, on Desktop and Tablet, the "grid" option would be viewed by default, but on mobile the "list" view template could be toggled to default to allow for a cleaner user experience.

**Comment by UraraReika** [comment]
Hello @bunkermediauk!

If you use Archive Item Template then you can customize it in different ways, and with the help of Elementor media controls achieve result that you need.
