### ISSUE TITLE
Checkbox filter not working

### ISSUE THREAD

**Issue by KostaDokosic** [CrocoBlock/suggestions#2497]
Checkbox filter not working (ajax). Multiselection not working. 
The first time you click on a category it works. every time after that it doesn't work.
I'm using this plugin with elementor pro.

https://gyazo.com/6acc69cdda75fdc737513ff92645c2cb
video

**Comment by KostaDokosic** [comment]
Solved

**Comment by Jescaro** [comment]
@LAVendeta I encounter the same issue. How did you solve this?

**Comment by KostaDokosic** [comment]
> @LAVendeta I encounter the same issue. How did you solve this?

Updating plugin & PHP version.
