### ISSUE TITLE
JetEngine Dynamic Field: Automatically pulled excerpt

### ISSUE THREAD

**Issue by Crocoblock** [Crocoblock/suggestions#25]
An ability to add an excerpt that is automatically pulled from the content and trimmed instead of the excerpt manually set in the Excerpt field. 

Needed in Dynamic Field widget, JetEngine plugin.

**Comment by daniele77ba** [comment]
Can’t see this feature, how can I achieve that ?

**Comment by pgirzalsky** [comment]
> Can’t see this feature, how can I achieve that ?

I know it has been a long time but I just came across the same issue and found the solution:

![Screenshot_1](https://user-images.githubusercontent.com/48622652/136409846-91973eb9-a310-4233-ad93-d6a810f19603.png)

**Comment by daniele77ba** [comment]
Hi Philippe,
I appreciate even if at the moment I cannot remember the project involved
by this issue.

Best regards,
Daniele

Il giorno gio 7 ott 2021 alle ore 16:56 Philipp Girzalsky <
***@***.***> ha scritto:

**Comment by HerbertVdP** [comment]
Hi all, 

Why is this not available in the case of pulling meta data? This would be helpful to limit the amount of either words or lines of text based on a custom text field. 

Kind regards, Herbert
