### ISSUE TITLE
Map Listing - Ability to set initial zoom level

### ISSUE THREAD

**Issue by NilsDannemann** [CrocoBlock/suggestions#2508]
It would be handy to be able to set the **initial zoom** for map listings. 
The need for this becomes obvious when only one listing item is shown. 

Right now the map initially zooms to the highest level in such a case.

Result:
![image](https://user-images.githubusercontent.com/1572663/105232377-98031f80-5b68-11eb-81eb-dde9ccb6c392.png)

This even happens in populated areas. 
Such a map is not really helpful to anyone.

Zooming out manually two times gives me this:
![image](https://user-images.githubusercontent.com/1572663/105232221-5a05fb80-5b68-11eb-9d08-eecec6c4c27c.png)

A bit better.
But I'd love to see this (after zooming out manually a couple of times):
![image](https://user-images.githubusercontent.com/1572663/105232274-7013bc00-5b68-11eb-9852-f3ed3210d088.png)

This is now really good, because it adds value to the visitor.
The User can now quickly see in what part of the city the location is.

Would love to see a solution for this.

**Comment by kaskad88** [comment]
You can use the `Max Zoom` option https://prnt.sc/15l1j73
