### ISSUE TITLE
Something really wrong with the Stars in JetReviews

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#2509]
1. Go to https://www.fornye.no/mobilabonnementer/yng-6-gb/
2. Scroll down to the review section.
3. Look at the review stars, and you can see they are corrupted.
4. Here is a screenshot for you [https://prnt.sc/xbkv66]

Is there a simple fix? Is this a error on your part? Or something wrong with my system?

**Comment by Floydtm** [comment]
I understand that this is important for you, but we checked everything and everything is fine from our side. It seems to me that this is due to the caching plugin. You'd better contact our support team. Thank you!
