### ISSUE TITLE
Option for a guest to leave their name as part of a Review

### ISSUE THREAD

**Issue by bizmachinesa** [CrocoBlock/suggestions#2511]
Currently on Jet reviews, if a guest leaves a review is shows the name as guest.
I had a client whom I have installed this plugin for request that the guests can enter in the name as well.

This will bring more credence to the reviews rather than a generic title

**Comment by alexanderpankart** [comment]
I think that would be a valuable addition.

**Comment by Medienor** [comment]
+1 !

**Comment by shinTM** [comment]
done v2.1.0
