### ISSUE TITLE
Hide filters in a button / Checkboxes Filter menu over accordion

### ISSUE THREAD

**Issue by temporalnaut** [CrocoBlock/suggestions#2514]
Hi,
I created an accordion via the Classic Accordion plugin and inserted filters from the JetSmartFilters plugin. However, the height of the expanded Checkboxes Filter menu is limited by the height of the accordion (I am attaching a screenshot). 
![138654460_209722330876704_7265750201804258509_n](https://user-images.githubusercontent.com/33429680/105364882-f5957b80-5bfd-11eb-9210-ffc41aa6b6d9.jpg)
I asked for support via ticket but I was told that it could not be changed at the moment.
So my request for new functionality is either:

1) To display the expanded Checkboxes Filter menu above Classic Accordion. For example, the Sorting Filter (JetSmartFilters plugin) expands above the accordion (I know it's some other kind of menu).

2) Or use a button to hide JetSmartFilters widgets instead of Classic Accordion. This site is one example of what this might look like:
https://www.alza.co.uk/televisions/18849604.htm
look at the left panel, there is a blue button "All Parameters" at the bottom below the filters, after clicking on it all filters will be displayed in a pop-up window.

Thank you

**Comment by Floydtm** [comment]
I understand that this is important to you, however you should understand that this is how the accordion works. We can't fix it
