### ISSUE TITLE
Add Ability to Query Repeater Fields (also, add dynamic visibility for repeater fields)

### ISSUE THREAD

**Issue by Willitbang** [CrocoBlock/suggestions#2515]
I want to be able to create a nested repeater and use a query for repeater items. Also, I would like to add dynamic visibility based on repeater values to a section (this section is a repeater listing item).

I was told in the Crocoblock facebook group that this is not currently possible. (see original example in post below)

Please add this funtionality to enhance what can be done with repeaters.

Hi
I have a question about the date query with nested repeaters.
I have 2 repeaters within my CPT that both include date fields. I have created Listing Items for both repeater fields.
- CPT - Class - (Orange Border) 
- Repeater 1 - Class Date - (Blue Border)
- Repeater 2 - Class Register - (Green Border)

I have the repeater 2 listing grid nested inside the repeater 1 listing template. 

How can I query the date fields in the repeaters? Essentially I only want to show the relevant Class Register Repeater within the correct Class Date Repeater?

![Nested Repeater Screenshot](https://user-images.githubusercontent.com/66962693/105372885-fc23f300-5bfd-11eb-941b-deac45e53464.png)

**Comment by JMartinCollins** [comment]
+1 Nested repeater templates functionality.
Listing grid widget > posts query could use with the addition of a "query from repeater field" type when listing a repeater listing. This could be useful for filtering listings with url parameters as well.

**Comment by Highway596** [comment]
+1 for the ability to set dynamic visibility of repeater fields in listing widgets

**Comment by necdetemre** [comment]
+1 for the ability to set dynamic visibility of repeater fields

**Comment by jhgeluk** [comment]
+1

**Comment by rtpHarry** [comment]
I've written a plugin which integrates repeater values with dynamic tags (which dynamic visibility supports), so you can solve part of this issue with it:

https://github.com/rtpHarry/jet-engine-repeater-values

**Comment by lordloadalot** [comment]
+1 - Maaan why is this not a feature yet ?
I wanted to make a  client-dashbord in the backend ( optionspage ) for him to enter his employees with their departments and then output them automatically on 3 different department team member pages. @rtpHarry hope your plugin helps. thanks for your time !!

**Comment by JensSwaenepoel** [comment]
+1

**Comment by ZacharyN** [comment]
+1

**Comment by mic647** [comment]
+1

**Comment by jodamo5** [comment]
+1
It would be very useful to be able to query repeater fields.  We have a number of "quick links" that are saved in global options as a repeater. However, when the links are shown, there is no way to exclude a link to the current page from being included, because we can't query the repeater.

**Comment by Gcpho1991** [comment]
+1

**Comment by morosmo** [comment]
+1

**Comment by joelcrump** [comment]
Being able to use jet filters and filtering a repeater field of dates would be great. I always run into this issue.

**Comment by sherikk** [comment]
+1

**Comment by aayla-secura** [comment]
+1

**Comment by MjHead** [comment]
This can be accomplished by Repeater Query + Listing - https://tppr.me/jdlfe
