### ISSUE TITLE
[JetSmartFilters] Add option to filter WooCommerce by items on "sale"

### ISSUE THREAD

**Issue by mbaierl** [CrocoBlock/suggestions#2516]
The "support" asked to open a ticket here ... instead of directly talking to the devs?

Anyhow, currently there is no way in JetSmartFilters to filter WooCommerce products by their "sale" status.
The JetWooBuilder properly renders the "sale" class, but I can't filter.

Would be amazing to have that option.

**Comment by petranca** [comment]
+1 yes please, its a standard for every good shop

**Comment by Floydtm** [comment]
#2811
