### ISSUE TITLE
Jet Woo Builder Carousel Product

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2517]
Hello, consider displaying products as a carousel, similar to how you can do it in Jet Engine listings.

/*Оригинал*/
Здравствуйте, рассмотрите возможность выводить товары в виде карусели, аналогично как это можно делать в листингах Jet Engine.

**Comment by stasonua0** [comment]
I see that there is a carousel in the Product Grid widget, but there is no way to select a product card that I created through Jet Woo Builder https://prnt.sc/xdu2g9

**Comment by UraraReika** [comment]
Hello @stasonua0!
In 1.7.5 version of JetWooBuilder we added compatibility with JetEngine listing. It means that if you create listing for Products then in editor you can use Archive Product WIdgets, and when you create listing for Product Categories - you can use Archive Category Widgets. Then of course you put this listing in listing grid, make it carousel and query it whatever you want.

**Comment by stasonua0** [comment]
In this scheme there is 1 minus, that the template eventually needs to be created 2. One in the Jet Engine, the second in the Jet Woo Builder.

**Comment by UraraReika** [comment]
In this case you dont need to create template in JetWooBuilder

**Comment by stasonua0** [comment]
> In this case you dont need to create template in JetWooBuilder

If you add a listing to the store's archive and make it archived, then when you enable the display of subcategories instead of products in the Woocommerce settings, the listing will still show products and will not react to the Woocommerce setting


/*Оригинал*/
Если в архив магазина добавить листинг и сделать его архивным, то при включении в настройках Woocommerce отоборажение подкатегорий вместо товаров https://prnt.sc/z3trqi, листинг будет показывать всё равно товары и не реагировать на настройку Woocommerce

**Comment by UraraReika** [comment]
If you use Listing instead of Products loop then yes Customizer Woocommerce display settings will not work.

**Comment by stasonua0** [comment]
> If you use Listing instead of Products loop then yes Customizer Woocommerce display settings will not work.

Therefore, you have to create two identical templates.

**Comment by UraraReika** [comment]
The Products Loop widget uses a standard WooCommerce cycle to display products that are only used on archived pages. Based on this, it fully supports all the functions of the WooCommerce. And he can use custom templates because he is an archived widget for displaying products, it is for them that we create custom cards.

When you turn on the display of categories at the level with products, then they are displayed in one wrapper and are not separated in any way from each other. Therefore, it is not advisable to implement a carousel into this functionality.

You also clarified that you want a carousel like in Listing, but now you can make this carousel a listing. In turn, this is no longer enough for you and you want to make such a custom solution all-round compatible with all the WooCommerce functionality, which, as already mentioned, is not possible.

I also can't understand why you claim that you need to create two identical templates?

**Comment by stasonua0** [comment]
Example.

1. On the main page there is a carousel of goods made by Jet Engine Listing. https://prnt.sc/z7vwep and this is the product card template # 1.

2. There is an archive of goods and there you need the same product card as on the main page in the carousel https://prnt.sc/z7wa64 and this is template number 2, completely identical to the first.

3. There is a need to display the same product card in the carousel in the product page template, where Upsells will be shown, and I already need to make template # 3, completely identical to the first and second points. Why didn't you take the template from the second paragraph? Because in the template of the second paragraph, when creating it, 3 columns were selected, and Upsells must be displayed in 4 columns and only because of this it is necessary to create a new identical template

In total, we have 3 identical templates and how to create them initially is half the problem, but they also need to be edited periodically and not forget to make changes to all three templates.

The tasks described above are not some mega custom functionality, but in fact, the standard of any not even a premium theme, and in order to implement this standard, you need to create three identical product card templates ...

And the solution could be simple, teach this widget to display in addition to its 10 presets, a template created in Jet Woo Builder + add here https://prnt.sc/z7xhyp Upsells products


/*Оригинал*/
Пример.

1. На главной странице есть карусель товаров, сделана через Jet Engine Listing. https://prnt.sc/z7vwep и это шаблон карточки товара №1.

2. Есть архив товаров и там нужна такая же карточка товара как на главной странице в карусели https://prnt.sc/z7wa64 и это шаблон №2, полностью идентичный первому.

3. Есть необходимость вывести такую же карточку товара в карусель в шаблоне странице товара, где будут показаны Upsells и мне уже нужно сделать шаблон №3, полностью идендичный первому и второму пункту. Почему не взял шаблон из второго пункта? Потому что в шаблоне второго пункта при его создании выбрано 3 колонки, а Upsells нужно вывести в 4 колонки и только из-за этого необходимо создать новый идентичный шаблон

Итого имеем 3 идентичных шаблона и как бы создать их изначально это половина проблемы, но их же периодически нужно редактировать и не забыть внести изменения во все три шаблона.

Задачи описанные выше это же не какой-то мега кастомный функционал, а фактически стандарт любой даже не премиум темы и чтобы реализовать этот стандарт, нужно создать три одинаковых шаблона карточки товара...

А решение могло быть простым, научить этот виджет выводить кроме своих 10 пресотов, шаблон созданный в Jet Woo Builder + сюда добавить https://prnt.sc/z7xhyp товары Upsells

**Comment by UraraReika** [comment]
Why you create 3 templates? You just use same template in Listing Grid Widget. The Widget has different settings controls in different pages you can do different stuff. If you want to change something, everything in one template. To be more clear you can use one template in multiple Listing Grid widgets without conflict.

**Comment by stasonua0** [comment]
Can't use listing in Woocommerce product templates because it doesn't respond to this option https://prnt.sc/z8dzbj

I can not use the listing to display Upsells because the listing does not know about their existence.



/*Оригинал*/
Не могу использовать листинг в шаблонах товаров Woocommerce потому что он не реагирует на эту опцию https://prnt.sc/z8dzbj

Не могу использовать листинг для вывода Апсейлов потому что листинг не знает об их существовании.

**Comment by UraraReika** [comment]
You can use another widget to display categories, and use the display condition on the listing grid widget itself. Until you manage to achieve the result that you expect and have to go to some tricks.
