### ISSUE TITLE
Advanced Map: Ability to Adjust Pin Icon Size

### ISSUE THREAD

**Issue by Lance2j** [CrocoBlock/suggestions#2519]
The ability to adjust the pin icon/marker size would make Advanced Map much easier to use with current logo/pin library. Here's an example of what I use with a different map widget:

![Screen Shot 2021-01-21 at 2 26 34 PM](https://user-images.githubusercontent.com/57176884/105408880-2c1ac880-5bf5-11eb-90d9-c4ef21f71ff3.png)

**Comment by kaskad88** [comment]
Added in JetElements v2.5.6

**Comment by Lance2j** [comment]
Much thanx!
