### ISSUE TITLE
Advanced Map: Ability to Add a Link Field to Each Location Description Balloon

### ISSUE THREAD

**Issue by Lance2j** [CrocoBlock/suggestions#2520]
The ability to add a link button to the location description balloon would be helpful for linking to internal or external pages about that location.

**Comment by Lance2j** [comment]
Here's an example from one of my Member pages:

![Screen Shot 2021-01-21 at 2 47 23 PM](https://user-images.githubusercontent.com/57176884/105410721-02af6c00-5bf8-11eb-91b6-c6cf4f0db5e4.png)

**Comment by alexanderpankart** [comment]
I would welcome that. I also work with this map and have all service providers listed on a world map. A link to their subpage would be great here.

**Comment by kaskad88** [comment]
Added in JetElements 2.5.8
