### ISSUE TITLE
Advanced Map: Ability to Name the Pin Items

### ISSUE THREAD

**Issue by Lance2j** [CrocoBlock/suggestions#2521]
I've been adding dozens of pin items to maps and having them display as merely "Item 1", etc makes it very difficult to find previously entered pins for editing. Here's an example of how I use it with another map system:

![Screen Shot 2021-01-21 at 2 40 07 PM](https://user-images.githubusercontent.com/57176884/105409788-954f0b80-5bf6-11eb-9ec8-48042d001971.png)

**Comment by kaskad88** [comment]
Added to the next version!

**Comment by Lance2j** [comment]
> Added to the next version!

Thank you!
