### ISSUE TITLE
Advanced Map: Include More Map Style Options

### ISSUE THREAD

**Issue by Lance2j** [CrocoBlock/suggestions#2522]
Additional map styles would be very helpful. I'm especially interested in Google's "Dark" theme, which is a black/grey theme. It looks like this:

![Screen Shot 2021-01-21 at 3 03 09 PM](https://user-images.githubusercontent.com/57176884/105412067-d268cd00-5bf9-11eb-9339-3e52146c2678.png)

I also currently use other Google themes:

![Screen Shot 2021-01-21 at 2 59 05 PM](https://user-images.githubusercontent.com/57176884/105411903-9fbed480-5bf9-11eb-87d1-489502e37763.png)

**Comment by Floydtm** [comment]
Hi! Use this options https://prnt.sc/xpsvxh

**Comment by Lance2j** [comment]
Maybe others would find this helful: [Easily Add a Custom JSON Style/Theme to Crocoblock Google Advanced Map](https://youtu.be/Wo4SMRuQg8g)
