### ISSUE TITLE
JetElements Charts: Add Prefix Or Suffix

### ISSUE THREAD

**Issue by reganmcgregor** [CrocoBlock/suggestions#2523]
I would like the ability to add a prefix or a suffix to the chart in particular Bar & Line.

My use case is that I have a chart showing Salaries from High to Low. I would like to display the numbers with a **$** at the front. In another use case, I would like to add a suffix of **%**.

It would also be great to add a thousand separators to the charts i.e. 10,000.

**Comment by reganmcgregor** [comment]
This might be small but it's very important to our website. Is there a hack around this perhaps? Maybe using CSS :before or some custom PHP. Here is an example of the page we are trying to achieve this on:

https://vervoe.com/recruitment-guides/how-to-hire-a-chief-marketing-officer/

**Comment by kaskad88** [comment]
Added in JetElements 2.5.8
