### ISSUE TITLE
JetReviews: Add input field for name & e-mail adress in JetReviews (Review Section)

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#2526]
We recieve many reviews on different services, and our partners would like to know the name and e-mails of the customer who leave the review.

This is not possible at this time with JetReviews.
Can you please add 2 extra input fields, for full name & e-mail adress that has to be filled out by person typing review?

Please see screenshot for example
https://prnt.sc/xg5rct

**Comment by shinTM** [comment]
done https://prnt.sc/xlri0f v2.1.0

**Comment by Medienor** [comment]
Oh my god! Incredible & fast work!

Is v2.1.0 released for JetReviews?

**Comment by OrangeAdmin** [comment]
Hi I cannot find this option as per your prnt.cs image
