### ISSUE TITLE
JetCompareWishlist: contact form

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#253]
I would like to have a contact form of any kind which will send an email containing the wishlist items a person added to his wishlist from the WooCommerce product page combined with JetCompareWishlist plugin in Elementor.

**Comment by marclucraft** [comment]
BUMP

100% in need of a way of emailing the contents of a wishlist

**Comment by mcj777** [comment]
+1

**Comment by marclucraft** [comment]
Whats the update on this? It's a key feature for a wishlist IMO.

**Comment by marclucraft** [comment]
For anyone interested, I was able to add my wishlist to a form using a shortcode. It's very basic, but it works for me for now.

I basically add the shortcode as a Dynamic Tag in a Hidden form field on elementor

The plugin code is [here](https://gist.github.com/marclucraft/3d52cba17f661a59b0bddf5e308dcc69#file-render-wishlist-php)

**Comment by UraraReika** [comment]
Unfortunately we do not plan to introduce such functionality into the core our plugin. Now our team is working on more priority tasks and this task does not correspond to the functionality of our plugin But I recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/  

Thank you for your understanding.
