### ISSUE TITLE
Jet Engine layout switcher

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2531]
Hello, consider introducing the same functionality into Jet Engine Listing - https://prnt.sc/xhyw0y

/*Оригинал*/
Здравствуйте, рассмотрите возможность внедрить такой же функционал и в Jet Engine Listing - https://prnt.sc/xhyw0y

**Comment by GlobalHive** [comment]
+1 Would be awesome

**Comment by jarahner** [comment]
There's already an open issue for this suggestion: https://github.com/Crocoblock/suggestions/issues/2277

**Comment by MjHead** [comment]
Beta released - https://github.com/Crocoblock/suggestions/issues/7100
