### ISSUE TITLE
Jet Advanced Carousel Pagination (Fraction)

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2532]
Hello, consider making the carousel count pagination.
Your competitor Element Pack already knows how to do this https://elementpack.pro/demo/element/custom-carousel/ https://prnt.sc/xi2xyt

/*Оригинал*/
Здравствуйте, рассмотрите возможность сделать для карусели пагинацию в виде подсчета элементов.
Так уже умеет делать ваш конкурент Element Pack https://elementpack.pro/demo/element/custom-carousel/ https://prnt.sc/xi2xyt

**Comment by stasonua0** [comment]
Slider widget needs this too

**Comment by kaskad88** [comment]
Added in JetElements 2.5.8
