### ISSUE TITLE
JetWooBuilder - Product Loop - Equal Height

### ISSUE THREAD

**Issue by GlobalHive** [CrocoBlock/suggestions#2534]
There is literally everywhere an option to check "Equal Height", but not on
the Product Loop, they differ in height, whats really bad if my text has only 1 row instead of 2

**Comment by Rok-fullstack** [comment]
Hello, is there any update on this? Woul be great, to have option to check "Equal height" + some styling, margins/padding between products. At the moment I have it done with the custom css.

**Comment by UraraReika** [comment]
Hello @Rok-fullstack !

All this options already exist in our plugin here https://tppr.me/P6TVw. If you have some difficulties then contact our support team.

Thank you!

**Comment by ossamainternational** [comment]
> Hello, is there any update on this? Woul be great, to have option to check "Equal height" + some styling, margins/padding between products. At the moment I have it done with the custom css.

Hi dear, could you please share the CSS code? I'm facing the same problem tho I make the equal column button ON!

**Comment by UraraReika** [comment]
Hello @ossamainternational !

You can find this option while you edit your Archive Item template https://tppr.me/tZNbl
