### ISSUE TITLE
PLS, ADD (at least) an OR CONDITION to Conditional Logic on JetEngine

### ISSUE THREAD

**Issue by InternetSemplice** [CrocoBlock/suggestions#2536]
**PLS, ADD (at least) an OR  (and NOR) CONDITION to Conditional Logic on JetEngine** (Version 2.6.2 on 2020.01.25)

* the feature is already added to the backlog or in work? NO
* the feature is missing from the products? YES

On JetEngine at Conditional Logic is written: 
Toggle this option to set meta field display rules. Note: relation type is AND.

**With ONLY AND relation type available, how can we add a real logical condition?**

Thx!!!

**Comment by Zegklitz** [comment]
+1

**Comment by davispe** [comment]
+25
Why is there no OR operator, this makes no sense.

**Comment by kaskad88** [comment]
It was implemented in JetEngine 3.2.0
