### ISSUE TITLE
Replace WooCommerce product attributes with graphics

### ISSUE THREAD

**Issue by gitcubefree** [CrocoBlock/suggestions#2537]
My feature request regards using woocommerce product options of a single product in an Elementor template.
e.g. Pretend I am a made-to-order sauna manufacturer. 
I have a product called "5x7 Sauna" with an attribute called "Bench Layout".
The choices for the Bench layout are called "Standard, High/Low and "L". However, I don't want to list these choices as simple text. Instead I want to have the customer see a graphic representation of the attribute.
thus the do NOT see "Standard", instead they see a graphic like so: 
Thx!!

**Comment by UraraReika** [comment]
I merged this issue with #361, which is on the same subject so we could deal with it more efficiently.
