### ISSUE TITLE
Jet Woo Builder Conditions Template

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2540]
Hello, I looked at how the system of assigning templates for certain categories, products or store pages works and realized how inconvenient it is compared to, for example, the standard Elementor system.

Consider rethinking the system for assigning templates to specific categories, products, store pages globally, such as:
1. All products from the category "Bicycles" have a template like this.
2. Set this template for all child categories (it's important when parent categories display not products, but category cards and they don't need a sidebar with filters ....)
3. Set the following template for all child categories "Bicycles".

In general, you do not need to reinvent the wheel, just see how it works in the Elementor Pro templates

An example of an inconvenience:
If I need one template for the "Store" page, and another for 123 other categories, then I need to first create two templates (maganin and category archive), and then go to each of 123 categories and manually assign it the desired template.

** How would this be done in the Elementor templating system? **
One template is assigned to the store page, another template is assigned to categories (1 minute of business)

** Why didn't you use the Elementor templating system then? **
Because there is no way to insert a Product Loop widget in Elementor templates.

** Why didn't you use the standard Elementor widget - Products then? **
The Products widget does not understand this setting https://prnt.sc/xnizhl and only shows products at all times

/*Оригинал*/
Здравствуйте, посмотрел как устроена система назначения шаблонов для определенных категорий, товаров или страницы магазина и понял насколько это неудобно по сравнению например со стандарной системой Elementor.

Рассмотрите возможность пересмотреть систему назначения шаблонов для определенных категорий, товаров, страницы магазина на глобальном уровне, типа: 
1. Всем товарам из категории "Велосипеды" задать вот такой шаблон. 
2. Всем дочерним категориям задать вот такой шаблон (актуально когда родительские категории выводят не товары, а карточки категорий и им не нужен сайдбар с фильтрами....)
3. Всем дочерним категориям "Велосипеды" задать вот такой шаблон.

В общем не нужно изобретать велосипед, просто посмотреть как это устроено в шаблонах Elementor Pro 

Пример неудобства:
Если мне нужен для страницы "Магазин" один шаблон, а для 123 других категорий другой, то мне нужно сначала создать два шаблона (магазин и архив категорий), а затем зайти в каждую из 123 категорий и вручную ей назначить нужный шаблон.

**Как бы это было сделано в системе шаблонов Elementor?**
Странице магазин назначен один шаблон, категориям другой (1 минута делов)

**Почему тогда не использовал систему шаблонов Elementor?**
Потому что в шаблонах Elementor нет возможности вставить виджет типа Product Loop.

**Почему тогда не использовал стандартный виджет Elementor - Товары?**
Виджет Товары не понимает эту настройку https://prnt.sc/xnizhl и показывает всё время только товары

**Comment by stasonua0** [comment]
What does the "question" status mean? Do you need more information from me?

**Comment by UraraReika** [comment]
@stasonua0 right now we working on this functionality. By the way Elementor pro has Archive products widget than takes Custom archive item template from JetWooBuilder and option that you mentioned.

**Comment by ColinHiom** [comment]
I was surprised to see that JetWooBuilder doesn't have this feature (or something very similar) already. On the Flatsome (woo) them it's integrated into the category settings. New kid on the block Bricks Builder already has this ability too - which you apply through a robust set of display conditions (more similar to how Elementor Pro handles it and how you have conditions that we can apply to page templates - and so it seems surprising you don't have this feature already for Woo categories. Without this I would have thought this restricts JetWooBuilder to quite small commerce sites - unless there is some other way I've missed (and your support team too)? Image grab of Flatsome approach here (although Flatsome's weakness is that the template doesn't flow down through sub-categories).
![image](https://user-images.githubusercontent.com/72506215/129563971-a0d06932-0b41-4198-b80e-1fae0441a1a7.png)

**Comment by UraraReika** [comment]
@ColinHiom check this https://crocoblock.com/knowledge-base/articles/jetwoobuilder-how-to-set-up-a-custom-product-taxonomy-template/

**Comment by ColinHiom** [comment]
Thanks so much Oleksandr. I must admit I very surprised that you didn't
seem to have this requirement covered - but you may need to check that your
support staff understand this to as someone called Viktoria (or something
very similar) told me categorically that this feature wasn't supported.
I'll test this asap later today - but thanks again.

**Comment by ColinHiom** [comment]
Hey Oleksanddri/Urara: I thought I'd better check this with you again (in case Viktoria was correct) but following the above link/tutorial I can't get a test Single product template to show in template selector (see image here). The tutorial doesn't go into quiet enough detail about this (template type required etc) but if you wouldn't mind confirming that this should be working I'll delve further. IE If my clients were selling cars, tractors and motor bikes (ie categories, or bags, shoes and dresses) we would need a different product template type by category and I can only presume you're saying that this is what the 'custom product taxonomy template' should allow - in which case I investigate further why my test templates are showing up in the selector (as shown in the grab). Many thanks, in advance, if you could confirm.
![image](https://user-images.githubusercontent.com/72506215/129920514-87ca5bc2-569d-4523-b006-b074fd923972.png)

**Comment by UraraReika** [comment]
@ColinHiom if i understand you correct you need for single product from some category separate template look?

**Comment by ColinHiom** [comment]
Yes, exactly Urara - thanks. So presumably a new JetWooBuilder single product template is what should be showing up in that Custom Template dropdown (previous grab)? IE It isn't but that what I was expecting...

**Comment by StevenVanWingerden** [comment]
Please add this feature!

**Comment by rivoi** [comment]
Have you added such a feature?

**Comment by stasonua0** [comment]
Didn't see this functionality.

**Comment by rtpHarry** [comment]
This would have been a very helpful feature for a big project I'm working on now.

**Comment by ColinHiom** [comment]
@UraraReika My apologies for not replying earlier. I didn't see that one. @rtpHarry and @stasonua0 I recently realised that I could achieve what I wanted but this seems better now and I'm not WooBuilder templates have been improved sine my last comments/August 2021 but I did find the names/labels applied to each type of template very confusing at first and realised my expected template type was the wrong one. Once I found the right ones I could build out the store fine. To create category landing/archive pages, for instance, you have to create and assign a 'shop' template, which doesn't make much sense. This doesn't address @stasonua0 opening comments and my later ones about being able to apply a 'cascading' (or condition-based) templates (that you want to apply to all 'bicycle' subcategories, @stasonua0 example). The Flatsome theme has the same defect in this way, as all subcategories also need to applied individually. Not sure if they're importable though?@stasonua0 (and my) request to have these assigned conditionally would especially make sense on larger stores - although if they could be assigned on import that would help. Baring in mind that larger stores can have thousands of of subcategory items I would have thought Crocoblock should put the resources into that to open up the 'larger store' market a little more for everyone like that. Hope that helps.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was added to JetThemeCore in 2.0.1 version. So if you use it in combination with JetWooBuilder you will get needed result.

Thank you!

**Comment by rtpHarry** [comment]
I've implemented a version of this, as a plugin, which lets you assign product single templates based on the product category:

https://github.com/rtpHarry/jet-woo-builder-category-custom-product-template

It adds configuration options into the WooCommerce Product Category taxonomy to let you select the "product single" template to apply to all products with that category.

I actually didn't see this announcement of JetThemeCore supporting this until after I had written this, but my plugin is super focussed on that one issue rather than adding in another entire system into the mix. So if you want just that feature then I think my plugin could still be useful.

**Comment by kiranz11** [comment]
> I've implemented a version of this, as a plugin, which lets you assign product single templates based on the product category:
> 
> https://github.com/rtpHarry/jet-woo-builder-category-custom-product-template
> 
> It adds configuration options into the WooCommerce Product Category taxonomy to let you select the "product single" template to apply to all products with that category.
> 
> I actually didn't see this announcement of JetThemeCore supporting this until after I had written this, but my plugin is super focussed on that one issue rather than adding in another entire system into the mix. So if you want just that feature then I think my plugin could still be useful.

YOU ARE A LEGEND! SAVED ME HOURS OF WORK WITH THIS! If you need to assign a croco product single template in bulk to specific categories then this plugin will do the job! without this you will need to individually assign the product single template to each product...thanks so much for this!
