### ISSUE TITLE
Display related products using Products Grid widget

### ISSUE THREAD

**Issue by tiago-123** [CrocoBlock/suggestions#2541]
The process of displaying related products with JetWooBuilder is currently overcomplicated and limited (_e.g._, it is impossible to display related products in a carousel).

Curiously, when you create an archive product page with JetWooBuilder and add the Products Grid widget to it, there is an option to query by 'related', 'upsells' or 'cross-sells'. However, such options are not available when you place the same widget directly on single product pages. Not to mention that querying by 'related', 'upsells' or 'cross-sells' in an archive page is useless.

Please, add the function to display related products using the Products Grid widget on single product pages.

**Comment by UraraReika** [comment]
Hello @tiago-123!

Option to query by 'related', 'upsells' or 'cross-sells' available only on single product page template. But if you have such an issue on your installation please contact out support team and we will check everything properly.

**Comment by tiago-123** [comment]
@UraraReika thank you for addressing this issue.

I already opened a support ticket and I was told that the only way to display related products is this: https://crocoblock.com/knowledge-base/articles/woocommerce-jetwoobuilder-settings-how-to-create-and-set-the-related-and-up-sells-product-page-template/

Are you saying that there is already a way to query by related products using the Products Grid widget? Because what I've seen is that the widget shows the option to query by 'related' when you place it on archive pages, but not on single product pages.

If this is an installation problem, please include some information regarding the Products Grid widget so that I can reference this discussion to the support team.

Thanks once again.

**Comment by UraraReika** [comment]
@tiago-123, here is steps to see query by 'related', 'upsells' and 'cross-sells':

- Create single page template with JetWooBuilder;
- Add Products Grid or Products List widget to template;
- Refresh editor so widget can get options to queryby control.

Although i can`t tell you exactly what is your problem and why you see those options on archive template. But for sure current options available only in single product template.

**Comment by tiago-123** [comment]
@UraraReika
That worked beautifully!! Thank you so much.
Yeah, indeed the step of refreshing the editor was the big issue for me. But it worked! :D
