### ISSUE TITLE
JetAppointment JetBooking Translation of admin Appointments section and Booking "Details" on Thank You Page

### ISSUE THREAD

**Issue by ihslimn** [CrocoBlock/suggestions#2544]
https://prnt.sc/vycwb8 - "Select..." placeholder in Appointments (JetAppointmentBooking)
and https://prnt.sc/xo4ycg - Booking Details (JetBooking) text seem not to be translateable through LocoTranslate.

**Comment by honlapdavid** [comment]
I have same problem

https://github.com/Crocoblock/suggestions/issues/2446

**Comment by MakhonkoDenis** [comment]
Hi,
This has been fixed in the latest versions of the plugins.
