### ISSUE TITLE
Creation of child theme for Kava

### ISSUE THREAD

**Issue by rithvikpodduturi** [CrocoBlock/suggestions#2549]
Existing solution:
We can export the design just like a template. which everyone might not understand.

What can be done :
The ability to build a complete design and export it like a child theme for kava, where my clients can install it directly just like a theme instead of importing templates

**Comment by Floydtm** [comment]
You can make a child theme in the desired section of the theme core https://prnt.sc/xrawcd https://prnt.sc/xrax7a
