### ISSUE TITLE
JetSmartFilters: add compatibility with Ultimate Add-ons for Elementor (Woo - Products widget)

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#255]
I use the "Woo - Products" elementor widget from Ultimate Add-ons for Elementor plugin on my woocommerce page.
I would like to use JetSmartFilter for this plugin.
I see you support Elementor Pro and your JetWooBuilder plugin but not Ultimate Add-ons for Elementor.
Would it be possible to add support for this pluign please?
This the plugin website: https://uaelementor.com/
This plugin is created by elementor.

**Comment by realstephenzhao** [comment]
This plugin is not created by Elementor! It's a paid plugin from Brainstorm Force(team from Astra theme), and it's overpriced!

I don't think JetSmartFilters should be compatible to this 3rd plugin for Elementor page builder, it may increase complexity and slow down other urgent issues.
