### ISSUE TITLE
JetPopup- Product Quick View popup auto close feature when "Add to cart" is clicked

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#2551]
**Describe the bug**

In  **product quick view popup** it is normal and expected behavior that when user click on "Add to cart" button inside, the popup will auto close. When the popup stays open, the user cannot realise that the product is in the cart already. This feature is missing and I think it is very important to have it, because it is bad user experience to have to click again for closing and to guess if the product is added to cart or not.

**Comment by tizum** [comment]
+1 for this amazing feature

**Comment by sonnesworld** [comment]
+1

**Comment by dyonatandias** [comment]
ac

**Comment by lamlai** [comment]
+1
