### ISSUE TITLE
Jet Appointment - Appointments intrude beyond the opening hours

### ISSUE THREAD

**Issue by CGW-GmbH** [CrocoBlock/suggestions#2553]
Example: A service takes 1 hour 
The working day starts at 9:30 am. Lunch break is from 12:00 to 12:30.
The form offers the selection from 11:30 to 12:00 for this 1h service!
The service shouldn't interrup the lunch break. Means the last 1 hour service should be available at 11:00.

You can view it online: https://kurz-karkassenhandel.de/reifen/termin-fur-reifenservice/
The service that takes 1 hour is: "Komplettmontage".

**Comment by MakhonkoDenis** [comment]
Issues are duplicated #2554
