### ISSUE TITLE
JetSmartFilters repeater fields

### ISSUE THREAD

**Issue by anderoav** [CrocoBlock/suggestions#2558]
Please add possibility to make a filter with repeater field.
I have button in form which adds custom checkbox values to the meta and I want users to be able to filter by them.

**Comment by frydhogg** [comment]
+1 this, please add more functionality to jetsmartfilter. because nowadays the data from repeater is more often to be used

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
