### ISSUE TITLE
JetSearch "Ajax Search" with button add to cart

### ISSUE THREAD

**Issue by StudioFika** [CrocoBlock/suggestions#2559]
Hey!

So I'm actually looking to get a **"Add to cart" button in the Ajax Search bar results.**
Sounds easy enough right?
Well, I cant get it to work!
So you might wonder what did I try? Well I did some searches on the internet and came up with this very recent topic on [GitHub.](https://github.com/Crocoblock/suggestions/issues/2169)
The actual request is exactly the same thing I want. However, the reply with the "solution" doesn't work for me. No matter what template I create, it doesn't show up in the search results. 
I've attached 2 files, the first one is what it looks like right now. The second one is what I'm trying to achieve.

What I have right now:
![What I have right now](https://user-images.githubusercontent.com/78099360/106025234-d2b90a80-60c8-11eb-98b9-04f21dda05a2.jpg)

What I want to have:
![What I want to have](https://user-images.githubusercontent.com/78099360/106025235-d351a100-60c8-11eb-85e6-6d721f38f3a6.jpg)

I'm really hoping you can help me!

( Running the latest version of WordPress, Elementor + Elementor Pro, and the Full Setup for Crocoblocks ).

Thanks in advance,

Sebastiaan Gouman
-Studio Fika

**Comment by 8WiaM8** [comment]
I came here for this same request! With an amount input field definitely!

**Comment by kvokocom** [comment]
> Hey!
> 
> So I'm actually looking to get a **"Add to cart" button in the Ajax Search bar results.**
> Sounds easy enough right?
> Well, I cant get it to work!
> So you might wonder what did I try? Well I did some searches on the internet and came up with this very recent topic on [GitHub.](https://github.com/Crocoblock/suggestions/issues/2169)
> The actual request is exactly the same thing I want. However, the reply with the "solution" doesn't work for me. No matter what template I create, it doesn't show up in the search results.
> I've attached 2 files, the first one is what it looks like right now. The second one is what I'm trying to achieve.
> 
> What I have right now:
> ![What I have right now](https://user-images.githubusercontent.com/78099360/106025234-d2b90a80-60c8-11eb-98b9-04f21dda05a2.jpg)
> 
> What I want to have:
> ![What I want to have](https://user-images.githubusercontent.com/78099360/106025235-d351a100-60c8-11eb-85e6-6d721f38f3a6.jpg)
> 
> I'm really hoping you can help me!
> 
> ( Running the latest version of WordPress, Elementor + Elementor Pro, and the Full Setup for Crocoblocks ).
> 
> Thanks in advance,
> 
> Sebastiaan Gouman
> -Studio Fika

Hello!
did you add button add to cart?

**Comment by Crocoblock** [comment]
was added and released in 3.4.0
