### ISSUE TITLE
JetWooBuilder: Add Badge for "Out of stock" or "Sold out"

### ISSUE THREAD

**Issue by Isilnelus** [Crocoblock/suggestions#256]
Hi, i've noticed thar only SALE badge is on the settings. I'd to have also the Out of Stock or Sold out badge for the Product Grid
![Anotación 2019-05-14 231154](https://user-images.githubusercontent.com/50640492/57732593-b62f3180-769d-11e9-910e-537c15bcffdf.jpg)

**Comment by UraraReika** [comment]
Done. Next release.

**Comment by dollhauss** [comment]
Out of Stock badge is now added to Product Grid.

Can it also be added to Product List?

**Comment by Floydtm** [comment]
@dollhauss, hi! We will add this in the next release.

**Comment by dollhauss** [comment]
@Floydtm You guys are awesome! ;-)
