### ISSUE TITLE
JetEngine - Listings Grid Widget Get Featured Products

### ISSUE THREAD

**Issue by iamdanbarrett** [CrocoBlock/suggestions#2560]
Can you add the post query to by products that are featured - I needed this today as I wanted I had created a listing for posts to utilise a new meta field for a 'featured slider' image instead of the featured thumbnail.

Speaking to the support team this wasn't possible currently.

**Comment by stasonua0** [comment]
It can be done like this https://prnt.sc/xr36f4

**Comment by iamdanbarrett** [comment]
> It can be done like this https://prnt.sc/xr36f4

Works! Thanks.
