### ISSUE TITLE
Jet Elements -> Images Layout -> disable linking and hover effect

### ISSUE THREAD

**Issue by kskonovalov** [CrocoBlock/suggestions#2562]
Hi there!
Images layout is a really handy feature, but not always you need to link the images, but currently you can only select between 'external link' or 'lightbox'. Would be cool having the option to not make the image a link.

Same thing for hover effect: not always you need to show title & description & overlay, so it's cool to have the ability to disable it.

Not so complicated things to change but would be very helpful, thank you!

**Comment by kaskad88** [comment]
Added in JetElements v2.5.6
