### ISSUE TITLE
JetCompareWishlist: meta fields callback filter > Checkbox field values

### ISSUE THREAD

**Issue by computerfreak84** [CrocoBlock/suggestions#2566]
I'd like to use the Compare feature for meta fields that are checkboxes.

Would it be possible to add the callback functions like in the Dynamic field widget?

In Compare when I use a meta field that has multiple values (checkbox, radio), it just shows "array". I would need the callback functions to display the Checkbox field values.

Similar issue: https://github.com/Crocoblock/suggestions/issues/424

![filter-field-output](https://user-images.githubusercontent.com/16098457/106268830-ee88f180-622b-11eb-855e-6c7debbb3d0e.png)

![Bildschirmfoto 2021-01-29 um 12 19 27](https://user-images.githubusercontent.com/16098457/106269057-432c6c80-622c-11eb-86c5-8c195e446ca1.png)

**Comment by UraraReika** [comment]
Hello @computerfreak84!

Custom field functionality in compare table is quite new so we didn't add any callbacks as options but you can easily did that with the help of filter hooks.
