### ISSUE TITLE
Filter woo products with NOT operator

### ISSUE THREAD

**Issue by dcambria** [CrocoBlock/suggestions#2569]
Hi, I would like do suggest a NOT operator to Dynamic Filters to select things like items that NOT appear into recipes.
Thank you.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
