### ISSUE TITLE
Widget Single Upsells and Single Related Products show carousel product

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2570]
Hello, consider adding functionality to widgets from Jet Woo Builder - Widget Single Upsells and Single Related Products displaying products in a carousel.

/*Оригинал*/
Здравствуйте, рассмотрите возможность добавить функционал виджетам от Jet Woo Builder - Widget Single Upsells and Single Related Products вывод товаров в карусель.

**Comment by UraraReika** [comment]
Hello, @stasonua0!
If you want to show that kind of products in carousel you can use Products Grid widget. When you use Products grid or products list widget at single product template the queryby control get some specific parameters for single product, such as related and upsells.

**Comment by stasonua0** [comment]
The product grid does not allow you to select my product card template.

**Comment by UraraReika** [comment]
Then like in this issue #2517 you can use Listing.

**Comment by stasonua0** [comment]
Listing cannot output Upsells

**Comment by UraraReika** [comment]
Use this small snippet 

```
add_filter( 'jet-engine/listings/macros-list', 'jet_register_custom_macros' );

function jet_register_custom_macros( $macros_list ) {
	$macros_list['jet_upsell_ids_products'] = 'jet_upsell_ids_products';
	return $macros_list;
}

function jet_upsell_ids_products() {
	global $product;

	if ( ! $product ) {
		return;
	}

	$upsells_products = $product->get_upsell_ids();

	return implode( ',', $upsells_products );
}
```

**Comment by stasonua0** [comment]
Thanks!

**Comment by stasonua0** [comment]
Please tell me, I inserted your code into function.php, but here's what to do in the listing settings to display it, until I figured it out

**Comment by UraraReika** [comment]
https://prnt.sc/105qus6 use it like this.

**Comment by chaseluikart** [comment]
#### Thank You @UraraReika!
- This snippet still works perfectly, as of JetEngine v3.0.3.1 & JetWooBuilder v2.0.3
- The macro, jet_upsell_ids_products, will also now show up in macro select dropdowns w/in Elementor dynamic fields & will also be available within the new JetEngine Query Builder.
- very simple modification of @UraraReika's snippet below for review
   (or if anyone else is looking for a way to get WooCommerce Cross-Sells with @Crocoblock's JetEngine macros)

#### Register JetEngine Macros for WooCommerce Upsells & Cross Sells:

```
add_filter( 'jet-engine/listings/macros-list', 'jet_register_custom_macros' );

function jet_register_custom_macros( $macros_list ) {
	$macros_list['jet_upsell_ids_products'] = 'jet_upsell_ids_products';
	$macros_list['jet_cross_sell_ids_products'] = 'jet_cross_sell_ids_products';
	return $macros_list;
}

function jet_upsell_ids_products() {
	global $product;

	if ( ! $product ) {
		return;
	}

	$upsells_products = $product->get_upsell_ids();

	return implode( ',', $upsells_products );
}

function jet_cross_sell_ids_products() {
	global $product;

	if ( ! $product ) {
		return;
	}

	$cross_sell_products = $product->get_cross_sell_ids();

	return implode( ',', $cross_sell_products );
}
``` 
*(fyi, this cross-sells macro appears to work correctly on my end,  but please do let me know if there are any issues or mistakes with combining the two macros like this - i'm learning)*


#### (**Huge thanks to @stasonua0 for raising the concern & starting this thread!**)

- @Crocoblock - I definitely agree with @stasonua0 that upsell_ids & cross_sell_ids are probably worth just adding into JetEngine core/default macros for products in the future.
