### ISSUE TITLE
jetwoobuilder 1.7.5 product grid not working with jetsmartfilters 2.1.0

### ISSUE THREAD

**Issue by maxdegraaf0803** [CrocoBlock/suggestions#2580]
When I updated jetwoobuilder to version 1.7.5 and jetsmartfilters 2.1.0 it was not possible to filter my shop page anymore. I put jetwoobuilder back to version 1.7.4 and it worked again. Elementors standard product grid does work with jetsmartfilters 2.1.0 so this plugin is not bugged.

It is not a critical issue but it would be nice if this would be debugged in the future. 😃  

Used browser on pc is chrome.
Used browser on smartphone is safari on iphone 8+.

**Comment by Hotcooler** [comment]
+1

Suspect jQuery changes.

**Comment by UraraReika** [comment]
New JetSmartFilter release will fix this bug. This release will be today.
