### ISSUE TITLE
Hide filters in button

### ISSUE THREAD

**Issue by temporalnaut** [CrocoBlock/suggestions#2585]
Hi,
Please add a new feature that would hide the defined set of filters (JetSmartFilters) and would appear when you press a button, in the form of a popup window or sidebar. This site is one example of what this might look like:
https://www.alza.co.uk/televisions/18849604.htm
look at the left panel, there is a blue button "All Parameters" at the bottom below the filters, after clicking on it all filters will be displayed in a pop-up window.
Now in Elementor, when I create a popup and insert your filters in it, the page does not respond to them.

Thank you

**Comment by Floydtm** [comment]
Right now it works with popups. If you have any difficulties with this, please contact our support team. Thanks!
