### ISSUE TITLE
Jet Engine plugin (Booking Forms)

### ISSUE THREAD

**Issue by Biblothecaire** [CrocoBlock/suggestions#259]
Hi,

I have a probleme with SPAM, so i want to ad the Google Re-captache https://www.google.com/recaptcha/intro/v3.html. 
Work fine with Elementor Pro form, but with the booking forms from Jet Engine plugin I can't use Captache so I have to many spam every day ...

I test to instal the Advanced noCaptcha reCaptcha Setup Instruction but don't understand what i need to do ...
Instruction = 
If you want to implement noCaptcha in any other custom form
To show noCaptcha in a form use do_action( 'anr_captcha_form_field' ) OR [anr-captcha]
To verify use anr_verify_captcha(). It will return true on success otherwise false.

For the "verify", don't understand too ... With Elementor really simple, can you do something like them ? Simple setting ?
Or a tuto for the Advened nocaptcha setting ?

Thanks for your help

**Comment by MaxZiebell** [comment]
+1

**Comment by Floydtm** [comment]
Added in JetEngine 1.4.2

**Comment by Biblothecaire** [comment]
Test, it work know, fine, thanks :D
