### ISSUE TITLE
Bug on custom hook usage

### ISSUE THREAD

**Issue by danillolima** [CrocoBlock/suggestions#2590]
**Describe the bug**
Hello guys,
just wanna know if this is a bug or I'm doing something wrong. I'm trying access the data passed to hooks from form modules but my webserver give me internal  error 500 when I put 4 parameters in the filter or 3 parameters in add_action('jet-engine-booking/send'..') function callback. 

 PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function my_custom_hook_call(), 1 passed in PATH..\\class-wp-hook.php on line 289 and exactly 4 expected in PATH..\\functions.php:431
 
 \nStack trace:\n#0 PATH..\\class-wp-hook.php(289): teste_call(true)\n#1 PATH..\\plugin.php(206): WP_Hook->apply_filters(true, Array)\n#2 PATH..\\wp-content\\plugins\\jet-engine\\includes\\modules\\forms\\notifications.php(1107): apply_filters('jet-engine-book...', true, Array, '2729', Object(Jet_Engine_Booking_Forms_Notifications))\n#3 PATH..\\class-wp-hook.php(289): Jet_Engine_Booking_Forms_Notifications->hook(Array)\n#4 PATH..\\class-wp-hook.php(311): WP_Hook->apply_filters('', Array)\n#5 PATH..\\plugin.php(478): WP_Hook->do_action(Array)\n#6 PATH\\wp-content\\plugins\\jet-engine\\includes\\modules\\forms\\ in PATH..\\wp-content\\themes\\custom-theme\\functions.php on line 431

**To Reproduce**
1. Activate custom call of hook on a form

2. Use the function with four parameters
function my_custom_hook_call($result, $data, $form, $notifications ){
        //do something
	return $result;
 } 
add_filter( 'jet-engine-booking/filter/send', 'my_custom_hook_call' );

Expected: receive the hooks arguments but I'm just receiving with one argument and just the form data in array format.

**Comment by formulaclick** [comment]
Maybe this should work:

add_filter( 'jet-engine-booking/filter/send', 'my_custom_hook_call', 10, 4 );

4 is the arguments number, and should be added to add_filter

**Comment by kaskad88** [comment]
Hi @danillolima. Use the example from @formulaclick. 
Example for the action:
`add_action( 'jet-engine-booking/filter/send', 'my_custom_hook_call', 10, 3 );`
