### ISSUE TITLE
BUG: JetEngine: Forms: Media files do not attach in Elementor Popups

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#2591]
**Describe the bug**
Media files do not attach in Telementor Popups for JetEngine CPTs

**To Reproduce**
1. Create a form with a media attachment (JPEG and PNG if you want to be specific)
2. Create a Popup and embed the form
3. Create a page with a button to launch the form
4. Attempt to attach media and submit

**Result**
You should see the post submit but the media attachment did not upload

**Expected behavior**

Media Forms should attach as it does in regular pages

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Windows 10 / Chrome 88
- Macbook Air / Chrome 88 / Firefox 85

**Comment by Floydtm** [comment]
We have checked your case and everything is working well. Perhaps your form is not working correctly. Please contact our support team. They will help you. Thank!
