### ISSUE TITLE
JetWooBuilder: Products Result Count

### ISSUE THREAD

**Issue by RuiCadete** [CrocoBlock/suggestions#2592]
This widget should react to the filtering. As is, is **useless**...

When filter are applied via AJAX call the info presented is always the same.

Should be something like this:
_Showing **_n_** results of **_y_** in total._ 

**_n_** -> displayed results depending on the pager configuration
**_y_** --> total depending on the filter

Regards.

**Comment by fabi20x** [comment]
+1
+ possibility to change the count on page

**Comment by stasonua0** [comment]
+1

**Comment by andre-xavier-berger** [comment]
I confirm that it is useless, should be considered as a blocking bug...

**Comment by DevDietheR** [comment]
@UraraReika 
Any news on this issue ?

**Comment by UraraReika** [comment]
This widget would not be compatible with JetSmartFilters. Please wait for some nearest JetEngine updates (query builder). With the help of this functionality you will be able to create such a view and fully compatible functionality (JetWooBuilder with JetEngine with JetSmartFilters).

**Comment by vaccinemedia** [comment]
Is there an update on this @UraraReika ? If this has been resolved, can you post a link to some instructions on how to do this please? This is also a blocking bug for me. I am currently having to use default filters with Kadence theme to have results updating above the product grid and would much prefer to use the better jetsmartfilters instead.

**Comment by petrovui** [comment]
Please add an instruction how to create Dynamic Products Result Count with Query Builder/JetWooBuilder + Load More button

**Comment by UraraReika** [comment]
> Please add an instruction how to create Dynamic Products Result Count with Query Builder/JetWooBuilder + Load More button

Sorry but for now JetWooBuilder Load more button doesn't work with this functionality. But you can use JetEngine listing grid to make it happen.

**Comment by heysash** [comment]
+1

**Comment by lorro** [comment]
This is still an issue? 
I want to create a productcategory taxonomy custom template. All works like I want but I still can't get a working "Result count" indicator that updates after filtering with JetSmartFilters via ajax.

**Comment by Kronan** [comment]
still issue...
