### ISSUE TITLE
Cannot submit Forms including post_id

### ISSUE THREAD

**Issue by mamecasa** [CrocoBlock/suggestions#2594]
Hi,

I created a Form to submit new Posts. All works fine, except I set the post_id option in my Form.

If I want to submit the Form i get this Message -> There was an error trying to submit form. Please try again later.

I really dont know what to do.

User Role is Subscriber
New Post and Edit Post are the same

If you need more information please ask me.

Thanks

**Comment by julianderyk** [comment]
In a Form for a new post podt_id has nothing to do there

**Comment by mamecasa** [comment]
thanks!
