### ISSUE TITLE
JetEngine: Be able to pull in Featured Image/Thumbnail from Relationships/Posts field

### ISSUE THREAD

**Issue by simplicity17** [CrocoBlock/suggestions#2599]
I can't believe this isn't already a feature.

I setup a repeater field on one of my custom post types. Within this repeater field is a posts/relationship field where users choose from another custom post type and a text field. I am creating a Listing for Repeater and have successfully been able to pull in the relationship post's title of this nested Relationship/Post field within the Repeater, but have not been able to pull in the post's Featured Image/Thumbnail. I have been informed by support that this is not possible.

For the post's title, I have been able to pull in the name of the post by entering the repeater field and setting the callback to "Get post/page title". With the Dynamic Image, I set the same custom meta field/repeater key but have not been able to get the featured image/thumbnail to render. I don't see why this can't easily be done. All field in the relationship/posts field should be able to be rendered on the front end.

**Comment by simonmilz** [comment]
Any updates on this? I am running into the same issue.

**Comment by simplicity17** [comment]
I ended up using Dynamic.ooo plugin for areas where I needed this feature.

Emily McKenna
Owner, Simplicity Design and Marketing
***@***.***

https://simplicitydesign.business

**Comment by MjHead** [comment]
@kaskad88 Добавить колбек для Dynamic Field с опциями: размер картинки, ссылка на пост (есть/нет)

**Comment by MikeLikesThat** [comment]
Looks to have been added to V2.11.6 today but how I did this was to create another list with just the image and then add that listing grid inside of the main list. I was stumped too till I found I could "listception" data.

**Comment by imihaiart** [comment]
It looks like it's Done, but I cannout figure it out how to achive this.
I'm trying to pull featured image for this form field:

I have a repeater field with following fields:
1. Posts select field
2. Number field
3. Text field.

When I display the repeater field inside frontend page should pull the featured image for every Post inserted within the repeater field.

Anyone found a solutions for this?
