### ISSUE TITLE
JetEngine feature: Listing slider and carousel

### ISSUE THREAD

**Issue by RodSuper** [CrocoBlock/suggestions#26]
Currently the 'Listing Grid' Element is a powerful way to show cards the way you need them.

I would love to see a Slider and Carousel option for displaying listings. This way you can create powerful custom slideshows/carousels of Events, Real Estate and much more.

**Comment by stasonua0** [comment]
+1

**Comment by fxaviers** [comment]
+1
We really need this to abandon others sliders plugins.

**Comment by MjHead** [comment]
Added in JetEngine 1.4,0
