### ISSUE TITLE
BUG for SEO with LISTING ELEMENTS - Dynamic Field

### ISSUE THREAD

**Issue by Biblothecaire** [CrocoBlock/suggestions#260]
Hi,

Last time the responsive don't work fine.
You fix that, really good :D

Know one other bug I see when i teach my team about seo picture (alt)
The "alt" picture are not show / took into account with the Dynamic Field Galerie from LISTING ELEMENTS

Exemple on this page : https://madagascar-hotels-online.com/hotels/home-the-residence/
All alt are filled on back office.
You can see 
- the logo alt OK
- The principal picture ok
- ONLY the Galerie, no alot
- ALL other picture ok

About SEO it's bad
Thanks to see to fi that for net uptade

Regards

**Comment by Floydtm** [comment]
Added in JetEngine 1.4.2

**Comment by Biblothecaire** [comment]
Test, it work know, fine, thanks :D
