### ISSUE TITLE
Adding Link with Column/Section

### ISSUE THREAD

**Issue by saudalhossain-dev** [CrocoBlock/suggestions#2601]
Hello Team

Hope you are doing well.
I have used the Team-Member widget. After that, I want to add a link in the column with another page. But there is no such functionality.
It would be helpful if you make it available.

Looking Forward.

Cheers!

**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by stasonua0** [comment]
+1

**Comment by Floydtm** [comment]
Guys, we have studied your request once again and will abandon it for now. Right now you can find a ready-made solution on wordpress.org
