### ISSUE TITLE
Need Rank Math SEO to see JetEngine custom fields

### ISSUE THREAD

**Issue by techdaze** [CrocoBlock/suggestions#2608]
According to Rank Math this is a quick project with their API.  I know you’re working on Yoast (or I think you are)...could you add Rank Math as well.  It’s one of the most popular SEO plugins now.  Thanks.

**Comment by getunrealtoday** [comment]
Yes please, this is important to me as well!

**Comment by kaskad88** [comment]
I merged this issue with #1228, which is on the same subject so we could deal with it more efficiently.
