### ISSUE TITLE
Jetelements Bar Chart Widget: "Stepsize" setting not working

### ISSUE THREAD

**Issue by joho2020** [CrocoBlock/suggestions#2613]
Regarding 
JetElements Bar Chart Widget -> Chart Data ->Stepsize.  
This setting doesn't seem to work properly.

I set the stepsize to 1, but then, when there are relatively small values in the chart, it still shows smaller step sizes such as 0.5.
This is irritating for bar charts with data that only makes sense for whole integers.

Please have a look and fix this.

![image](https://user-images.githubusercontent.com/73476552/107338146-818f1a80-6abb-11eb-9fdb-303a5c2b9900.png)

![image](https://user-images.githubusercontent.com/73476552/107338079-6f14e100-6abb-11eb-8764-833fd5d004ec.png)

**Comment by Floydtm** [comment]
We have checked your request again and everything is working well. However, our sites can be customized in different ways. Please contact our support team.
