### ISSUE TITLE
Hamburger Menu (JetMenu) not working in Mobile (iPhone)

### ISSUE THREAD

**Issue by arekuki** [CrocoBlock/suggestions#2616]
Hello. There is a problem widget Hamburger Menu in two sites.

Dektop: http://prntscr.com/yy3j0o and http://prntscr.com/yy3kou
Mobile: http://prntscr.com/yy3z7x and http://prntscr.com/yy3qku in Firefox (DevTools)

Can you fix the glitch?

Some time later worked widget Mega Menu
Mobile: http://prntscr.com/yy47x5 and http://prntscr.com/yy49fv

**Comment by Floydtm** [comment]
We checked your request and everything seems to be working correctly. Please contact our support team and grant access to the site. Thank!
