### ISSUE TITLE
Oxygenbuilder compatibility 

### ISSUE THREAD

**Issue by savvaszi** [CrocoBlock/suggestions#2617]
Crocoblock's jet engine is really amazing!
Please make full compatibility with oxygen builder!!

**Comment by ChrisGV04** [comment]
Totally agree! It would be wonderful to at least have JetEngine and JetSmartFilters full compatibility with Oxygen Builder. I would absolutely sign up for that!

**Comment by CriandoSites** [comment]
I agree. It would be fantastic

**Comment by bagginslothnado** [comment]
Please make this happen Croco :D 

The Gutenberg support is a step in the right direction, you should move into a full third party solution for users with other builder tools, but specially Oxygen

**Comment by ghost** [comment]
+1 for this feature!

**Comment by Josh-PCD** [comment]
+1 JetEngine and JetSmartFilters integration please!

**Comment by Floydtm** [comment]
https://www.facebook.com/groups/CrocoblockCommunity/posts/4533744080050311/

**Comment by smithy5021** [comment]
+1 for full compatibility with Oxygen builder
