### ISSUE TITLE
Add an option to exclude featured image from JetProductGallery images

### ISSUE THREAD

**Issue by jaimomo65** [CrocoBlock/suggestions#2618]
Hi!
I would like to be able to choose to show only the gallery images, without including the featured image of the product, just like other gallery plugins do (elementor's pro gallery, for example).
Thanks for your great work!
Jaime

**Comment by oliveandlake** [comment]
Agree. It would be nice if the slider was compatible with "WooCommerce Additional Variation Images" plugin too!

**Comment by getunrealtoday** [comment]
Agreed 100%. I just had to ditch JetProductGallery because of this very reason. I only wanted to show gallery images and discovered that the main product image was also unexpectedly displayed...
