### ISSUE TITLE
Jet Engine v2.6.3: Jet smart filter pagination not shown for jet engine listing grid on woocommerce product archive.

### ISSUE THREAD

**Issue by lukechinworth** [CrocoBlock/suggestions#2620]
**Describe the bug**
We use a jet engine listing grid on our woocommerce product archive template. We leave "Use as archive template" disabled, because we need to add multiple clauses to the query. We use jet smart filters on this page to filter by attributes and for pagination. The update from Jet Engine 2.6.2 -> 2.6.3 caused the pagination to not display. Logging the global js var `JetSmartFilterSettings` showed that `props` does not have the key `jet-engine`. This is caused by the addition in `wp-content/plugins/jet-engine/includes/compatibility/packages/woocommerce.php` on line 239. For some reason adding `wc_query` to `$args` causes the key `jet-engine` to be missing from `JetSmartFilterSettings.props`. 

As a temp workaround we filter `$args` and unset `wc_query`.

**Steps To Reproduce**
1. Install jet engine, jet smart filters, woocommerce, and elementor.
2. Add enough products for multiple pages of results.
3. Create product archive template with elementor, and add a listing grid with smart filter pagination.
4. View the archive on the frontend. 

**Expected behavior**
Pagination displayed to navigate to next page of results.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Chrome
 - Jet Engine: 2.6.3

**Comment by Floydtm** [comment]
It seems to me that all this can be solved with the settings. Please contact our support team and provide access to your site. Thanks!
