### ISSUE TITLE
Allow for duplication of meta boxes

### ISSUE THREAD

**Issue by lkoskova** [CrocoBlock/suggestions#2625]
Hello again,

I am creating a website listing products that will have similar meta fields in metaboxes, and instead of rewriting most fields over and over, i would like to simply duplicate the metabox and edit for my different posts. thank you!

**Comment by needlestack-sc** [comment]
Yes, I second. This would be very helpful! Thank you!

**Comment by lordloadalot** [comment]
+1  –  I have a metabox with **81** Meta fields. Is there really no switch for duplictaing yet ??

**Comment by kaskad88** [comment]
Added for the next version (2.11.5)

**Comment by lordloadalot** [comment]
You are great ! Thanks a lot from Loadalot!
