### ISSUE TITLE
A way to customize the endpoints in WooCommerce

### ISSUE THREAD

**Issue by myfrontendproject** [CrocoBlock/suggestions#2627]
At this moment, we can customize pages for Woocommerce.

No all widgets work perfect though (the widget “thank you for your order” does not edit all contents on that page as when changing the header font and color, it does not take effect on the “download” heading)

Anyway, endpoints...

These can not be customized in any way other then writing your own custom CSS which is not really convenient

above all not all text takes the styling set for the website and the custom WC pages and also the buttons do not take the styling set in the site settings or in the custom pages, these stick with the default WC settings

So in order to have a real killer tool, it would be awesome if we could style the endpoints as well

Thanks

**Comment by UraraReika** [comment]
@myfrontendproject, please specify  which endpoints you would like to customize
