### ISSUE TITLE
[Feature Request] JetEngine: Dynamic Visibility on Repeater Fields

### ISSUE THREAD

**Issue by koermedia** [CrocoBlock/suggestions#2632]
I would love to see Dynamic Visibility for individual Repeater Fields. 

For instance, I have a sports website where I use custom fields to add matchup data to blog posts. I use the repeater field to list various stats and information about the game. I then use a Repeater Listing to showcase this data. I would like to have the ability to use Dynamic Visibility functions in the Repeater Listing to show/hide specific data about the game. 

Currently, this is not possible.

This feature would help me create a more dynamic and unique website and I could see it being very useful for people using listing-based websites.

Thanks!

Jeremy

**Comment by Highway596** [comment]
I second this request, very important to be able to hide dynamic repeater listings via a meta value (switcher, etc).

**Comment by eatshootrock** [comment]
Just found out that this is not possible. I would love for this feature to be added. Currently I have a repeater field on my custom post. 

I want to hide that section if there are no data available.

**Comment by Nedo90** [comment]
I have the same problem. On several websites I have media-downloads with a headline over each, which should be hidden with dynamic visability if no content is included. This would definitely be an important option to dynamically show and hide all dynamic content fields including dynamic repeater fields.

**Comment by Willitbang** [comment]
+1

**Comment by 3wfdev** [comment]
Yes, I really need this too. On a related note, would be great if the switchers and conditional fields work in repeaters on the Admin side too (similar to ACF)

**Comment by marlokessler** [comment]
+1

**Comment by Jonathlee** [comment]
+1

Important to have "conditional" for repeater field + columns in repeater field.

I need it to show "if have item have value" = "show this item with link 
`<a href="%item_link%">%item_name%</a>` 

else just show item name 

`%item_name%`

**Comment by alisanie** [comment]
+1

**Comment by kervis** [comment]
+1

**Comment by terracellc** [comment]
+1

**Comment by jhgeluk** [comment]
+1

**Comment by lucasgueiros** [comment]
I need this feature too!
I need to hide a Dynamic Field on a Repeater Listing based on the value of another repeater field and also based on another field of the same Custom Post Type.

**Comment by rtpHarry** [comment]
Argh I just finished building out all the repeater fields and now when I look in the Dynamic Visibility options it seems its not there. 

Is there not some way to enter the meta key manually? I'm not adverse to digging around in the code for this but not sure where to start.

**Comment by WebsiteWerk** [comment]
+1

**Comment by rtpHarry** [comment]
Actually, I accidentally implemented this a few days ago haha. 

I wrote a Dynamic Tag so that I could bind repeater values to my widgets.

I just checked and the Dynamic Visibility actually supports Dynamic Tags, so like I said, it's accidentally already implemented with my plugin!

Example:

![image](https://user-images.githubusercontent.com/1038062/146567338-b05a1cc1-d746-4fe2-addc-b19af53cc3b3.png)

The plugin is here:

https://github.com/rtpHarry/jet-engine-repeater-values

And some more discussion of this plugin is here:

https://github.com/Crocoblock/suggestions/issues/4235

It only supports "text" fields at the moment, but I plan to expand it to support the other types of field like url, color, image, etc. If anyone has any urgent requirements please let me know and I'll focus on that.

**Comment by rtpHarry** [comment]
I've updated this to v1.1.0 now which adds support for all the types of dynamic tags including text, url, color, post meta, number, gallery, image, and media:

https://github.com/rtpHarry/jet-engine-repeater-values

**Comment by luisceladita** [comment]
+1

**Comment by ofmarconi** [comment]
> Atualizei para a v1.1.0 agora, que adiciona suporte para todos os tipos de tags dinâmicas, incluindo texto, URL, cor, meta de postagem, número, galeria, imagem e mídia:
> 
> https://github.com/rtpHarry/jet-engine-repeater-values

![image](https://user-images.githubusercontent.com/6594795/155461004-5fd5c4b4-8eb5-44af-a32f-708368f3b794.png)

I'm trying to run this logic:

If there are any number of repeaters other than 0, display.

I'm recreating Highlights from Instagram:
![image](https://user-images.githubusercontent.com/6594795/155461148-8ba6ec0d-d9e2-4bbd-9f38-ddfaaf0c0156.png)

When I don't have any, I want this section not to be displayed.

**Comment by nolabelstudios** [comment]
> Argh I just finished building out all the repeater fields and now when I look in the Dynamic Visibility options it seems its not there.
> 
> Is there not some way to enter the meta key manually? I'm not adverse to digging around in the code for this but not sure where to start.

@rtpHarry I couldn't get your plugin to work. I didn't have any items in a repeater, set the display conditions to hide if nothing exists and it still showed up. What are the correct settings to set to hide a section if no items exist in a repeater field?

**Comment by rtpHarry** [comment]
Sorry, that's not what my plugin does. 

My plugin is for when you are building JetEngine "listings" templates. 

When you want to display the contents of a repeater, you set up a listing template for it.

So the concept is that when you are building that single template, which is repeated once for every "row" of the repeater, you could only the Dynamic user controls to display the repeater data. For example the [Dynamic Field](https://crocoblock.com/knowledge-base/articles/jetengine-dynamic-field-widget-overview-how-to-use-filter-field-output/) widget, and there are a few others.

My plugin expands the range of widgets you can use within that listing template, such that instead of adding a Dynamic Field widget and having to manually add the snippet of `<img src="%s" alt="" />` or something like that, then instead you could now just drop in a proper Image widget, and set the source using a Dynamic Tag and my plugin.

Following the same concept, within the repeaters listing template, you can also use the dynamic tag in the dynamic visibility options.

**Comment by rtpHarry** [comment]
I just looked into this a bit further. Couldn't you just use this option on the Listing Grid if you are trying to display a repeater that is empty?

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1038062/159036287-978204b8-4dd3-4a9c-9672-286cdf13875a.png">

**Comment by carlpolson** [comment]
So just curious if there is any way to use the Jet Engine Repeater Feild to hide or show the date fields? I am trying to use this to show dates (not in a series) on Jet Engine Calendar.

**Comment by GaribayMarketing** [comment]
+1

**Comment by RobertCastro** [comment]
> He actualizado esto a v1.1.0 ahora, que agrega soporte para todos los tipos de etiquetas dinámicas, incluidos texto, url, color, meta de publicación, número, galería, imagen y medios:
> 
> https://github.com/rtpHarry/jet-engine-repeater-values

it worked for me, thanks

**Comment by brunoalbim** [comment]
> I've updated this to v1.1.0 now which adds support for all the types of dynamic tags including text, url, color, post meta, number, gallery, image, and media:
> 
> https://github.com/rtpHarry/jet-engine-repeater-values

Worked perfectly! Congratulations

**Comment by nreljed** [comment]
the plugin no longer works under **Jetengine 2.11.11** maybe it's time for it to make its entry in jetengine 3.0.1?

**Comment by filwi** [comment]
In JE v3.0.0, rptHarry's plugin (v1.1.1) works, but you've got to use "Hide element if conditons are met" rather than show. 

So it's the opposite of how it should work ;)

**Comment by briski-design** [comment]
Works wonderfully! Many thanks for the plugin!

**Comment by pauserratgutierrez** [comment]
Hi, I have a checkbox inside a repeater field in a CPT. I would like to dynamically display an image depending on which box is selected.

Here you can see the checkbox inside the repeater. I'm not able to target the selected checkbox in any way. The dynamic visibility doesn't work
![image](https://user-images.githubusercontent.com/73240206/188213102-1c3791d1-9514-4bb5-b8c2-185f24b5a525.png)
![image](https://user-images.githubusercontent.com/73240206/188213304-5eca41c3-7d5c-4ea3-820f-755c7d75ae61.png)

**EDIT: The main issue is that Dynamic Visibility doesn't allow us to use "Filter Field Output"**

**Comment by breakused** [comment]
+1

**Comment by taropaa** [comment]
Yup this seems to be broken or unfinished as I would expect this to work.

**Comment by Zegklitz** [comment]
+1

**Comment by borjamerino-v** [comment]
+1

**Comment by morosmo** [comment]
+1
Also Its very hard to add two different condition using dynamic visibilty.
I try building woocommerce product lisitng . There are heading widget on lisitng which i want to show in listing if product is featured. This is easy to done but what if I want to hide it if product is on sale also. 
There is no option to set condition for that also woocomerce vsisibilty option only provide the option called "Product is on sale" If we can get further conditon in that like product sale and then we can select true or false so if product is not on sale we can select the condition product on sale and then on dropdown chosse true or false.

**Comment by kaskad88** [comment]
Hello.
Now it is possible to use Dynamic visibility for repeater fields through the `Current Object Field` dynamic tag for repeater listings created using `Repeater Query`.

Steps:
1) Create query for repeater field - https://tppr.me/Frp7y
2) Create listing for repeater field by query - https://tppr.me/Z6XAP
3) And use the `Current Object Field` dynamic tag for Dynamic Visibility conditions https://tppr.me/Z6XAP https://tppr.me/Swqz4

**Comment by righijavier** [comment]
> I've updated this to v1.1.0 now which adds support for all the types of dynamic tags including text, url, color, post meta, number, gallery, image, and media:
> 
> https://github.com/rtpHarry/jet-engine-repeater-values

Excellent! You are awesome! I was able to solve the problem with the plugin after spending 3 hours with a Crocoblock operator without reaching any solution!

**Comment by muztagol** [comment]
> > I've updated this to v1.1.0 now which adds support for all the types of dynamic tags including text, url, color, post meta, number, gallery, image, and media:
> > https://github.com/rtpHarry/jet-engine-repeater-values
> 
> Worked perfectly! Congratulations


does not work with an accordion repeater :(

**Comment by fernandesadrian** [comment]
This was working perfectly until the recent jet engine or Elementor update. The "Repeater field" doesn't appear in the dynamic visibility section. Is there another alternative to achieve the same?

P.S: I ended up using Query Builder with the "Repeater Query" type function to get the desired output. 

![SCR-20230919-nf1](https://github.com/Crocoblock/suggestions/assets/19342681/19aba808-8e14-4667-b67d-36d6d8dfe5b2)

**Comment by minide** [comment]
> I've updated this to v1.1.0 now which adds support for all the types of dynamic tags including text, url, color, post meta, number, gallery, image, and media:
> 
> https://github.com/rtpHarry/jet-engine-repeater-values

Hey
how can I use the plugin?
Where do I download it from?

**Comment by srestre** [comment]
> +1
> 
> Important to have "conditional" for repeater field + columns in repeater field.
> 
> I need it to show "if have item have value" = "show this item with link `<a href="%item_link%">%item_name%</a>`
> 
> else just show item name
> 
> `%item_name%`

I've been lookin for solution to this problem for a long time... Anyobody could help us solve this? Thanks!

**Comment by cendezgh** [comment]
@rtpHarry 

> Actually, I accidentally implemented this a few days ago haha.
> 
> I wrote a Dynamic Tag so that I could bind repeater values to my widgets.
> 
> I just checked and the Dynamic Visibility actually supports Dynamic Tags, so like I said, it's accidentally already implemented with my plugin!
> 
> Example:
> 
> ![image](https://user-images.githubusercontent.com/1038062/146567338-b05a1cc1-d746-4fe2-addc-b19af53cc3b3.png)
> 
> The plugin is here:
> 
> https://github.com/rtpHarry/jet-engine-repeater-values
> 
> And some more discussion of this plugin is here:
> 
> #4235
> 
> It only supports "text" fields at the moment, but I plan to expand it to support the other types of field like url, color, image, etc. If anyone has any urgent requirements please let me know and I'll focus on that.


Nice, it works. Thanks.

Surprised why Crocoblock doesn't include this option yet.

**Comment by banch3v** [comment]
I just found a way that does not require rtpHarry's plugin. 

You just get the name of the master repeater field:
![image](https://github.com/user-attachments/assets/0a60c9d1-e2fa-44af-bd07-9e2b9f56bf84)

then you paste it in the section or wherever you want to set dynamic visibility with these settings:
![image](https://github.com/user-attachments/assets/fc6e2432-0662-4fa7-8593-eb9df0ebb903)

That's it.

-----

As far as rtpHarry's solutions. Thank you for supporting the community! I was about to use your plugin but then I found this.

**Comment by ofmarconi** [comment]
@banch3v wow, very simple, how did we not think of this before, this actually solves all the requests of this issue, right?

**Comment by banch3v** [comment]
> @banch3v wow, very simple, how did we not think of this before, this actually solves all the requests of this issue, right?

For me, it worked just fine. My goal was to give my custom post type the option to show or hide a section (with other aswell information besides the repeater fields) based on whether any value is added in the post's repeater field. Essentially, it allows the repeater field to function like any other custom meta field when it comes to dynamic visibility.

Give it a try. I'm confident it would work for you too.
