### ISSUE TITLE
TinyMCE WYSIWYG Editor is not working after updating JetEngine to 2.6.4

### ISSUE THREAD

**Issue by pravinlpatel** [CrocoBlock/suggestions#2639]
Hi Team,

It seems that JetEngine 2.6.4 is not orking well with TinyMCE WYSIWYG Editor plugin. Please refer following screen.

Before updating to JetEngine to 2.6.4

https://prnt.sc/zh4qvu

After updating  JetEngine to 2.6.4

https://prnt.sc/zh4udn

**Comment by pravinlpatel** [comment]
FYI, I rolled back JetEngine to 2.6.3 and everything is working fine now.

**Comment by kaskad88** [comment]
@pravinlpatel Could you please provide a list of your plugins

**Comment by kochhase** [comment]
I see he is using the https://de.wordpress.org/plugins/tinymce-advanced/
advanced tinymce editor

**Comment by kaskad88** [comment]
@kochhase thanks !

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!

**Comment by pravinlpatel** [comment]
@kaskad88 . Thanks for supplying quick fix. 

Would be great if you can confirm JE version under which issue is fixed.

**Comment by kaskad88** [comment]
> @kaskad88 . Thanks for supplying quick fix.
> 
> Would be great if you can confirm JE version under which issue is fixed.

Fixed in 2.6.4
