### ISSUE TITLE
jet-woo-builder thumbnail to select correct image for variable product

### ISSUE THREAD

**Issue by jspassov** [CrocoBlock/suggestions#2642]
When you have a lot of variation products with variations (mainly color) and have a separated gallery of images for each variation (via 3th party plugin like Variation Images for Woocommerce) when you are using "thumbnail" from jet-woo-builder widgets in elementor it show only main image for the product - not for variation selected. Moreover, if the options "Enable Thumbnail Effect" is ON - same widged display two images and slide both on hover (thumbnail effect is set to slide left). 

It would be nice to have a correct image if variation is selected (and also second image from variation /if any/ for thumbnail effect) or single product image if no variation is selected or if this is a simple product (with no variations).

I suppose that it would be not so difficult to achieve. Just need to check if product has variation and get the correct images.

**Comment by UraraReika** [comment]
Hello @jspassov ! Please describe the problem in more detail, attaching screenshots for a better understanding, so that we can more accurately recreate this problem in ourselves to fix it. 

You can also contact our support and refer to this issue, then we can consider everything directly at your site.

**Comment by jspassov** [comment]
No Problem. Here you have some screenshots:

![image](https://user-images.githubusercontent.com/3731269/107940764-6a579d80-6f91-11eb-9a2e-930cbf33e74a.png)

This is a fresh install with another 3th party plugin (WooCommerce Product & Gallery Images) for variation images ending with the same result.
As you can see, when using thihumbnail (with thumbnail effect ON) instead of effect you will receive a defect :-)
If you remove 3th party plugin for Variation Gallery - it will work OK (but not for variable product)

What I want to achieve (and I hope other users too) are the following images:
This is the same product with two variation and correct image (depend on selected variation) but not using a jet-woo-builder thumbnail gadget (it is not working as I mentioned earlier)> So the template are using Woo-Lentor Advanced Image gadget.
![image](https://user-images.githubusercontent.com/3731269/107941417-5bbdb600-6f92-11eb-841d-cb64d43f7b37.png)
You can see also my ticket about this for more descriptive information at https://support.crocoblock.com/support/tickets/25494

**Comment by UraraReika** [comment]
I try to recreate the issue using Additional Variation Images Gallery for WooCommerce and Variation Swatches for WooCommerce plugins. I didn't get such defect https://prnt.sc/103kr8b. The only problem that appears is that there is no compatibility between swatches functionality and thumbnail effect. And when you select variation two images change same with reset.

**Comment by jspassov** [comment]
Just try to enable thumbnail effect in JetWooBuilder ad you will see the effect 😊

**Comment by UraraReika** [comment]
All your steps were reproduced.

**Comment by birkhoff20** [comment]
Im having the same problem. Any solution?

**Comment by UraraReika** [comment]
@birkhoff20, please contact our support team

**Comment by birkhoff20** [comment]
My problem was the Lazy Load from Smush PRO.
