### ISSUE TITLE
 Error calling function: jet_woo_builder_shortocdes in jet-smart-filters/includes/providers/jet-woo-products-grid.php

### ISSUE THREAD

**Issue by dleicam** [CrocoBlock/suggestions#2644]
At line 361 of the file "jet-smart-filters/includes/providers/jet-woo-products-grid.php" is:

shortcode = jet_woo_builder_shortocdes()->get_shortcode('jet-woo-products');

and should be:

shortcode = jet_woo_builder_short**co**des()->get_shortcode('jet-woo-products');

**Comment by UraraReika** [comment]
I merged this issue with #2633, which is on the same subject so we could deal with it more efficiently.
