### ISSUE TITLE
GEO LOCATION FOR SMART FILTERS

### ISSUE THREAD

**Issue by Joshuamajch** [CrocoBlock/suggestions#2646]
**Please** add the Geo Location "Filter by Proximity" from given Address to the Smart Filters. 

Jetengine has all the features needed build in, like geocoding address fields and such. Why is it not having the most essential feature of them all when it comes to geolocation? 

This feature will make the plugin a powerfull tool to replace all the crappy listing themes out there. 

```
**Request Details :** 

- Add a box where user can enter his address or geolocate himself
- Let user select a range of distance
- filter listings grid by change / or "apply" button pressing
```

**Comment by travelgu** [comment]
+1

**Comment by lifeact** [comment]
+1

**Comment by Scoots78** [comment]
Yeah, a 'Near Me' function search within a specified radius would be great

**Comment by Matt-Finnegan** [comment]
Is there a solution for this yet? Even with some Javascript...

**Comment by eSilverStrike** [comment]
+1

**Comment by developer784** [comment]
+1000

**Comment by Catching-Eyes-Media** [comment]
This definitely should have been high priority for the original map integration.
+10,000!

**Comment by Kytab** [comment]
PLEEAAASSEEE DO IT !

**Comment by rlb222** [comment]
+1 Very much need this! Thank you. First item for me could be simpler:

> - Add a box where user can **enter an address** 
> - Let user select a range of distance
> - filter listings grid by change / or "apply" button pressing

**Comment by mmarzanweb** [comment]
I really don't know why this feature hasn't been implemented yet. :( It seems to be a demand from the entire community that uses map listing.
Pleeeeeeeeeease, do it! :)

**Comment by youlikeitcp** [comment]
Any news??

**Comment by EnvioMaik** [comment]
+1000 I have no clue why this isn't implemented yet, it's the most needed feature, like almost the only one that matters XD

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
