### ISSUE TITLE
Widgets to display variations and prices on single product page

### ISSUE THREAD

**Issue by jrmyfranck** [CrocoBlock/suggestions#2654]
It would be very useful to be able to **control how JetWoobuilder displays product variations and prices on the single product page**, instead of the standard dropdown in the 'Add to Cart' widget — something that would allow to choose between dropdown, radio buttons, swatches, etc., and style them visually. 

Right now, this is possible by relying on third party plugins such as "Variation Swatches for WooCommerce" by Themehigh, but it offers very little styling control (and don't display properly inside of the Elementor editor), which really isn't ideal.

BriefcaseWP offers dedicated widgets for this (see here: https://briefcasewp.com/how-to-create-a-dynamic-price-on-woocommerce-variation-product/), but it would be nicer to be able to further customize the product page inside JetWooBuilder to make it look really unique. 

Here are a few elements of the page that could be customized for an amazing look: 
- Price (notably, replace the "min-max" range by either the min or max price)
- Variations (dropdown, radio, swatches, images, etc.)
- Quantity (control how plus, minus and the number field are displayed)
- Add to Cart (show or hide quantity, and possibly link to a form on the page + dynamic price for options)
- Product image gallery
- Product meta
- etc.

**Comment by fabi20x** [comment]
+1

**Comment by Lonsdale201** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello @jrmyfranck !

Lets go through the list: 
1 - We will not implement this functionality to our plugin but we use standard WC functions to display products prices. So in this case you can use hooks to rewrite the price output. You can use this hook `woocommerce_get_price_html` it's look like this in the code https://i.gyazo.com/dadd663dccb1598c0747f1a0010af7d7.png.

2 - Track this issue https://github.com/Crocoblock/suggestions/issues/361 

3 - Track this issue https://github.com/Crocoblock/suggestions/issues/2711

4 - For hiding quantity inout then use enable this option in single product settings https://i.gyazo.com/cf27c73c38afe5c4734aeadcc3f17e5b.png. Please describe in more details form suggestion using this template https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md. If you select product variations then you get variation price https://i.gyazo.com/d6b3ab5430d194ad60a049e95fcdd459.png.

5 - Use JetProductGallery plugin.

6 - Use this widget https://i.gyazo.com/952a5a615b704ad2fbdedaad19cef615.png
