### ISSUE TITLE
JetEngine Listing Grid > load more / infinite scroll and JetSmartFilters

### ISSUE THREAD

**Issue by computerfreak84** [CrocoBlock/suggestions#2657]
Hi

Is it normal behavior that after filtering with JetSmartFilters, the "load more" or infinite scroll feature of the listing grid cannot load more results than the "Posts number" that is set in listing grid?

Tried every possible combination, as soon as filters are applied (button or ajax does not matter), it does not want to show more posts.

Thanks.

**Comment by Floydtm** [comment]
Hi! The listing grid is working correctly.
