### ISSUE TITLE
JetSmartFilters Indexer for custom fields / meta fields

### ISSUE THREAD

**Issue by computerfreak84** [CrocoBlock/suggestions#2658]
Hi

Should Indexer work on custom fields or is it normal that it doesn't work?

Thank you.

![Bildschirmfoto 2021-02-17 um 15 43 29](https://user-images.githubusercontent.com/16098457/108220470-0bcc2400-7137-11eb-9df5-f517e026f11c.png)

**Comment by Floydtm** [comment]
The indexer should work. You may have configured something wrong. Please contact our support team. The guys will help you!
