### ISSUE TITLE
Custom Callback in Admin Columns for Radio Field type

### ISSUE THREAD

**Issue by daandegroot123** [CrocoBlock/suggestions#2659]
When you use the Radio field type on a CPT's meta field, it is currently not possible to create a human-readable value to show within the admin column. There are Custom Callbacks for Select, Switcher en Checkbox but no option for Radio. The functionality is basically the same as for the other callbacks.

![image](https://user-images.githubusercontent.com/41082044/108229130-cfe98c80-713f-11eb-8b47-b983082763d3.png)

I have no good examples or anything but the image above shows my Admin Column displaying the value instead of the human-readable labels of the options (Prijs is op aanvraag).

**Comment by mateitudor** [comment]
It's almost 2023...

**Comment by kaskad88** [comment]
You can use the `jet_engine_custom_cb_render_select` callback for radio field.
