### ISSUE TITLE
Jet Smart Filters SEO

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2660]
Hello, please tell me, is it possible to consider the idea of making an SEO filter from Jet Smart Filters?

For example:
https://prnt.sc/zvdiph The URLs that the filter generates are included in the site map and then in the search engine index, and each page has its own unique title and description (set by the template in the filter settings)

This can be done by Berocket Filter https://prnt.sc/zveo4a in the paid version for Woocommerce, and this is so lacking in Jet Smart Filters.

Is there any chance that you will consider implementing it?

/*Оригинал*/
Здравствуйте, скажите пожалуйста, возможно ли рассмотрение идеи сделать SEO фильтр из Jet Smart Filters?

Например:
https://prnt.sc/zvdiph URL которые генерирует фильтр попадают в карту сайта и затем в индекс поисковых систем, при этом каждая страница имеет свой уникальный title и description (задается шаблоном в настройках фильтров)

Такое умеет делать Berocket Filter https://prnt.sc/zveo4a в платной версии для Woocommerce и этого так не хватает в Jet Smart Filters.

Есть ли вероятность что вы рассмотрите возможность внедрения?

**Comment by realstephenzhao** [comment]
Yes, still not fixed. The URL in plain mode of filtering URL structure is not elegant. 

They actually release a feature to alter frontend URL in another way(permalink mode). See https://github.com/Crocoblock/suggestions/issues/243 
It can shorten filtering URL length, but it still has prefixes like `/jsf/jet-engine/` followed by weird `/meta/xxx/pagenum/2`. And the permalink structure would mislead visitors too and may cause SEO issues. 

For Ajax, I would like the FacetWP filter URL format, see demo https://facetwp.com/demo/cars/?_vehicle_type=car&_driven_wheels=all-wheel-drive&_paged=2&_sort=horsepower 

For more SEO-friendly URLs, I would like the FilterEverything Pro style: https://demo.filtereverything.pro/product-category/clothing/women/color-black/c-kind-dress/?max_price=250

**Comment by mattkub** [comment]
+1

**Comment by focuswebagency** [comment]
+1

**Comment by honlapdavid** [comment]
+1

**Comment by 93petter93** [comment]
+1

>

**Comment by siraulo1000** [comment]
+1

**Comment by ILYAUSA** [comment]
+1

**Comment by nreljed** [comment]
I add [another example to inspire](https://filtereverything.pro/)
this solution 
combines the best of both worlds
please see the demos 🙏

**Comment by ILYAUSA** [comment]
+1
И что бы фильтр не сбрасывался по переходам по страницам.

**Comment by frussane** [comment]
+1

**Comment by Imageburst** [comment]
+1! I can't believe it's been this long and still no solution to this issue or even an workaround solution for temporary measures.

**Comment by ryanfurtner** [comment]
+1 Damn, I really need this for a client site I have to present in a month. Theyre going to wonder why their URL's have 'jet-filter' in them. Heres to hoping this gets fixed in the next few weeks! :P

**Comment by koystrubvs** [comment]
+1

**Comment by otomasz** [comment]
@MjHead
When can you expect a solution to this problem?

**Comment by oryancooper** [comment]
+1

**Comment by jeanlorencini** [comment]
+1

**Comment by jeanlorencini** [comment]
this should be considered as basic

**Comment by limacon12** [comment]
+1

**Comment by MjHead** [comment]
At the moment, in 3.5.0 version, we added an ability to generate sitemap with unique URLs for combinations of the filters. This sitemap can be directly added into Google Search Console, or you can add it into sitemap indexes, generated by SEO plugins (later we'll probably will do this automatically). For 3.6.0 planned to add an ability to generate dynamic texts based on filters selection. These texts could be used as meta title/description and directly on the page.
