### ISSUE TITLE
BUG: Show variations of products as individual products on shopping page. (JetWooBuilder)

### ISSUE THREAD

**Issue by Didier-F** [CrocoBlock/suggestions#2665]
**Describe the bug**
I used the plugin WooCommerce Show Single Variations and it will cause a problem that mess up the shopping page. I Asked the pluginmakers and they told me there is a error coming from JetWooBuilder.

---
I checked and the issue was caused by your plugin Jet Woo Builder on how it displays the loop items. If you will check the Error log you will see that there is an error coming from JetWooBuilder:

2021-02-18T03:49:08+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on bool in /home/deb100204/domains/iexist-build5.nl/public_html/wp-content/plugins/jet-woo-builder/templates/jet-woo-products/global/loop-item.php:9
Stack trace:
#0 /home/deb100204/domains/iexist-build5.nl/public_html/wp-content/plugins/jet-woo-builder/includes/shortcodes/jet-woo-products-shortcode.php(818): include()
#1 /home/deb100204/domains/iexist-build5.nl/public_html/wp-content/plugins/jet-woo-builder/includes/base/class-jet-woo-builder-shortcode-base.php(187): Jet_Woo_Products_Shortcode->_shortcode(NULL)
#2 /home/deb100204/domains/iexist-build5.nl/public_html/wp-content/plugins/jet-woo-builder/includes/widgets/global/jet-woo-products.php(604): Jet_Woo_Builder_Shortcode_Base->do_shortcode(Array)
#3 /home/deb100204/domains/iexist-build5.nl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1892): Elementor\Jet_Woo_Products->render()
#4 /home/deb100204/domains/iexist-build5.nl/public_html/wp-content/plugins/elementor/includes/base/w in /home/deb100204/domains/iexist-build5.nl/public_html/wp-content/plugins/jet-woo-builder/templates/jet-woo-products/global/loop-item.php op de lijn 9

If you will also disable JetWooBuilder, Variations will display without any issues as well.

Since we have isolated that the is coming from JetWooBuilder, the next course of action would be contacting the developer of this plugin and if you can ask them to have a look at this issue as well.

---

What happens:
<img width="1578" alt="Schermafbeelding 2021-02-18 om 09 47 18" src="https://user-images.githubusercontent.com/79250701/108331105-b5aabf80-71ce-11eb-97c3-44d62816c2fa.png">

Expected:
<img width="1180" alt="Schermafbeelding 2021-02-18 om 09 50 46" src="https://user-images.githubusercontent.com/79250701/108331171-c9562600-71ce-11eb-9324-299b536e21a5.png">

If you need any more information, please tell me!

Regards,

Didier

**Comment by surajlulla** [comment]
@Didier-F @UraraReika @Floydtm were you able to use "WooCommerce Show Single Variations" on the Shop/Archive page? It's not working for me.

**Comment by Didier-F** [comment]
I'm not using the plugin anymore.
