### ISSUE TITLE
JetReviews: When Guest leave their 'name' in field it will not registrer in the review.

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#2668]
With the new JetReviews 2.1.0 it is now possible to leave your name & e-mail as a guest reviewer.
We did a test, when you leave your name in the form it will say your name in the final review is "Guest".

So it dosent change the review.

Here is a screenshot of the form where we add name: https://prnt.sc/zyud2s
Here is a screenshot of the name not changing: https://prnt.sc/zyuwpg

1. Go to https://www.fornye.no/mobilabonnementer/telenor-frihet/
2. Scroll to bottom and leave a review "Skriv omtale"
3. After you fill out review + uniqe name scroll down to see review
4. Name in review is still "Guest" see error

**Comment by Bookit24** [comment]
I see the exact same problem, hope this can be fixed quickly as we've been waiting for this functionality. 

I have an open support ticket, but no changes so far. The guest user name/email is registered in the jet_review_guests table, but I can't see any relationship to the jet_reviews table? I might be wrong, but at least I have the same problem where all guest users still just show with the name "guest" (both on the review, and in dashboard -> all reviews)

**Comment by Floydtm** [comment]
please create ticket https://support.crocoblock.com/support/tickets and we will help you

**Comment by GastonIsDead** [comment]
+1
https://app.intercom.com/a/inbox/rn7ho5ox/inbox/admin/5563737/conversation/133270500261819?view=List
