### ISSUE TITLE
[JetBooking] Multiple Booking with Pre-booking and cancellation policy

### ISSUE THREAD

**Issue by KHRifat** [CrocoBlock/suggestions#2670]
**Multiple same-day booking for the same form/category/location is very important.** Without multiple bookings no serious company can use JetBooking. At this moment this is only useable for the single person who personally renting his/her single car/room/bike or providing freelance services.

BTW, this is good for salon-like services because people book there a single person. But it's not totally useable for business (Hotel/Cars/Travel) with multiple same category products/services & that needs to get booking using one form.

So @Crocoblock please upgrade the JetBooking & support the following features:
1. Multiple Bookings for the same form.
2. Pre-booking and cancellation policy

**Comment by sandornemeth86** [comment]
I agree, please Crocoblock team take this issue seriously.

**Comment by KHRifat** [comment]
Hello @MakhonkoDenis 

is there any update for the JetBooking plugin.? Can we get the following features:

1. Multiple Bookings for the same form.
2. Pre-booking and cancellation policy.

**Comment by dbfischer** [comment]
Hello, 
I have the same problem. Booking for bikes. If a family wants to book several bicycles, this is not possible.

**Comment by UraraReika** [comment]
I merged this issue with #2352, which is on the same subject so we could deal with it more efficiently.
