### ISSUE TITLE
[JetBooking] Add sync with a json url for Availability

### ISSUE THREAD

**Issue by danielbimson** [CrocoBlock/suggestions#2671]
My client uses Bookster and their iCal is useless but they have a decent JSON URL.  So to have an integration with Bookster would be great.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. 

iCal is a standardized format widely supported by calendar apps like Google Calendar, Apple Calendar, Outlook and also by booking related websites. JSON requires custom parsing and is not universally compatible. iCal includes built-in support for events, recurring events, time zones, and alarms, which JSON lacks unless customized.

If in your case iCal is useless you can [contact](https://support.crocoblock.com/support/home/ ) our support team and they can help you solve your problem.

Thank you for your understanding.
