### ISSUE TITLE
Post Info Widget - why only display the date created and not the date last modified or updated?

### ISSUE THREAD

**Issue by rammyleeds** [CrocoBlock/suggestions#2672]
Hi there, 
the post info widget only displays the date on which the post or page was created.   But most users will want to see when a page was last updated.    So, can I request for there to be an option to change this to show the "last update date" in addition to "page created date".  Allow the web designer to decide which one.    Or perhaps even enable both to be shown, or not show, or one to be shown.

I am very surprised it's not already in there or wasn't thought about during creation.   Searching the web - hundreds of WordPress users are begging for this!

Many thanks

Rammy

**Comment by kaskad88** [comment]
Added in JetElements 2.5.8

**Comment by rammyleeds** [comment]
Thank you Dmitriy, can you tell me what is the element called within jet elements
