### ISSUE TITLE
JetSearch: Include taxonomy (categories, tags) in AJAX search results

### ISSUE THREAD

**Issue by mike196flavors** [CrocoBlock/suggestions#2679]
Hello Crocoblock team, I am about to redesign my entire site on Elementor Pro and I am seriously considering getting a lifetime subscription to all your plugins as I intend to use several of them. However, the most important for me is the JetSearch plugin. Our multilingual site is pretty large (15 M PV in 2020, growing at 60-70% every year) and we need to offer our visitors a way to easily find content (among more than 3500 posts, but also dozens of categories and tags). I love the AJAX assisted search but a key functionality is missing.

Let me explain the use case (which I am sure a lot of content heavy sites have):

Our site 196flavors.com features recipes from all around the world. We use categories for countries (as well as continent, course type, diet, etc) and tags for ingredients.

If a user starts typing "France" in the search bar, we not only want to show posts including the keyword "France" which might include French recipes (but not only) but we also expect the drop-down (AJAX search results) to include a section that shows all categories including "France" (only one in this example). If they type Africa, we might show them "East Africa", "North Africa" and "West Africa" (as all are actual category names).

If they type onion, we will show them "red onion", "white onion", "spring onion" (in a tag section inside the same AJAX drop down search results).

If they click on the suggested category, the behavior would be that it would take the visitors to a search result page of all the posts categorized in "France" (for example) as opposed to all the posts that include the word "France" if they were clicking on the submit button after entering the keyword "France". I do not think this is a huge development effort and it would benefit your customers tremendously. I really love your plugins and the search is really the most important for us. I don't really want to start looking for another search plugin, which is why I am contacting you to see if you could include this request in your roadmap, and provide a clear ETA for it.

Thanks a lot!

**Comment by Marcoirrera** [comment]
I agree, this missing feature is very limiting each time you have a large amount of taxonomy values. 
Jet search in other hand doesn't support autocomplete function which is very limiting, for an example, if you need to filter for geographic entities (90% of search would have no results which is nothing good for user experience).

A search filter for taxonomies/tags with an autocomplete is a must have feature in 2021 in so many cases.

**Comment by Cosirax** [comment]
I agree with the others. That's a must have for this plugin. I would love to see this feature in the next release.

**Comment by vjchandelia** [comment]
Even I am in the same situation and looking for a way to search by taxonomies using a search field. Hopefully Crocoblock is working on it.

**Comment by DevDietheR** [comment]
What's the progress on this?

**Comment by simon-womersley** [comment]
I agree this is a needed feature + spelling corrections (did you mean suggestions), auto-complete, searching within product descriptions, and highlighting the search term showing why it's relevant.

**Comment by RuanPienaarCode** [comment]
Bump, This is sorely limiting the function, will need to look for alternative search plugin. Hope you can add features other people mentioned.

**Comment by hamed-azimi** [comment]
Absolutely a MUST. JetSearch is a great plugin that is letting users easily do a quick search, and the fact that the search result area is customizable is awesome. But there are a few features lacking that is critical. One is what @mike196flavors discussed here.

We have over 3000 products in +100 categories and +150 brands. Giving the option to users to narrow down the results right in the search area is a game-changer and increases sales.

Hope to see it coming into the plugin after almost 1 year.

**Comment by Zaanone** [comment]
+1. 
I am building a website which sells wine. Some of the wines have tags like 'New Years', 'Christmas', 'Summer', etc.. 

It would be great if Jetsearch would automatically search through all product tags (like the ADVANCED WOO SEARCH plugin).

**Comment by MjHead** [comment]
At the moment implemented the ability to add into the search results posts which has terms with search query. We'll consider an adding taxonomy terms itself into the search results (instead of posts, optionally)

**Comment by bbua97** [comment]
+1

**Comment by tmaeder** [comment]
Any news on that?

**Comment by MHub2021** [comment]
After 4 years since this post was made, we still don't have this option.

**Comment by Crocoblock** [comment]
@MHub2021, it was added in JetSearch 3.5.0

**Comment by MHub2021** [comment]
> @MHub2021, it was added in JetSearch 3.5.0

Thank you for your reply. I may be on the wrong topic.

I tried with "AJAX search widget" to make Taxonomy to get displayed in the autocomplete results, but it only shows the post from that specific taxonomy.

For example if I search "Par" in AJAX search widget, I want the widget to display the Taxonomies that start with "Par" such as Paris. At this moment it displays ONLY the list of post from Paris Taxonomy not the taxonomy itself. (please see attachement)
![AqWFu3_ch9UQnga7-n64wXsv7NncYFvRzw](https://github.com/user-attachments/assets/c66e7d45-07ff-4a02-948c-438d3e9bac21)


I hope it makes sense. 

I also opened a ticket to Crocoblock support and they finally said:
_"If you need to search terms by terms and show them only in the dropdown, it can be implemented partly only. 
According to our developers, it is not possible to remove posts from the results dropdown. It is only possible to change the order of the results in the dropdown. 

In the meantime, I'll add the possibility to exclude dedicated CPTs from the search to our feature requests list."_

**Comment by Crocoblock** [comment]
Hi @MHub2021 
Please create a separate issue
