### ISSUE TITLE
Schema Markup for JetReviews plugin 

### ISSUE THREAD

**Issue by Akavantseva** [CrocoBlock/suggestions#268]
I would like to suggest to add schema markup for JetReviews plugin so that Google recognizes the rich snippets and ranks them high up. And reviews get 5 stars.

**Comment by ZemezLab** [comment]
done

**Comment by shinTM** [comment]
Use this http://prntscr.com/o0sd97 special fields to add micromarking

**Comment by magdakubis** [comment]
Google does not see reviews on my page. I get a message in the console: Missing field "aggregateRating" - how can this be fixed?
