### ISSUE TITLE
JetEngine: Repeater Fields In Admin Columns

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#2681]
I don't know if its possible to add repeater fields also to the admin columns of custom post types, but it would be cool  to have this information also in the admin area.

**Comment by kochhase** [comment]
yes the admin fields tool of Croco is not ready in the moment. I use this plugin for that funktions until it has enough features,
https://www.admincolumns.com/

**Comment by Floydtm** [comment]
I understand that this is important to you. However, we cannot implement this. As soon as we collect more requests we will come back to this. Thank!

**Comment by eatshootrock** [comment]
Would love to add repeater on the admin column too

**Comment by ConsultMePL** [comment]
I was sooo surprised so it's not there! 

My case: I want to give a client opportunity to display prices. In order to heaver fewer design templates, I decided to use repeater. As either I'd have to create three separate meta fields (like pizza has three sizes so three prices, but other products only one size so one price). So it was better to have a repeater, as the client can decide the number of fields. Now, it's quite important to be able to display prices in the admin fields...

Typical Croco - how so many bloat and useless features, but those that would be useful are not there...

**Comment by zeinzulaziz** [comment]
Would love to add repeater on the admin column too

**Comment by NarfArf** [comment]
We wound up creating a custom callback in functions.php for this based on the existing jet_engine_custom_cb_date callback, here's a code snippet in case anyone finds it useful.

This one specifically outputs dates (from UNIX values) from a repeater field in a chosen format separated by line-breaks.

In our use case, the custom callback wound up looking something like this: 
`jet_engine_custom_cb_date_repeater::INSERT_REPEATER::j. F Y
`
```
/**
 * Returns formatted dates from an array of post meta by post id and field
 *
 * @param  integer $post_id [description]
 * @param  string  $field   [description]
 * @param  string  $format  [description]
 * @return string|null      Comma-separated list of formatted dates or null if not found
 */
function jet_engine_custom_cb_date_repeater( $post_id = 0, $field = '', $format = '' ) {

    $dates_array = get_post_meta( $post_id, $field, true );

    if ( is_array( $dates_array ) && ! empty( $dates_array ) ) {
        $formatted_dates = array();

        foreach ( $dates_array as $entry ) {
            if ( isset( $entry['INSERT_YOUR_REPEATED_FIELD'] ) && ! empty( $entry['INSERT_YOUR_REPEATED_FIELD] ) ) {
                $formatted_dates[] = date_i18n( $format, $entry['INSERT_YOUR_REPEATED_FIELD'] );
            }
        }

        if ( ! empty( $formatted_dates ) ) {
            return implode( '<br>', $formatted_dates );
        }
    }

    return null;
}

```

**Comment by dannyfoo** [comment]
I'd appreciate having the ability to display my repeater Text field in Admin Columns.

I'm building an internal directory and using the repeater Text field to store contact numbers. By having an admin column , other team members can quickly look up a needed contact number when searching for the contact person.
