### ISSUE TITLE
JetEngine Listing Grid Injections not working with Custom Content Types

### ISSUE THREAD

**Issue by ChrisGV04** [CrocoBlock/suggestions#2682]
**Describe the bug**
I was trying to use Listing Grid Injections for a "News" Custom Content Type (CCT) in my website to change the style of a card based on a select field inside the CCT. I tried using it with Custom Post Types and it worked fine, but with CCT it didn't make any changes. I think it wasn't reading the fields correctly.

**To Reproduce**
1. Create a CCT with a "select" field with 2 options inside.
2. Enable Listing Grid Injections in JetEngine's settings.
3. Create two different listings for that CCT.
4. Add listing grid widget to any page and enable the "Inject alternative listing items" option.
5. Set Injection conditions to “Depends on item meta field value” and refer to one of the values of the options inside of the select field of the CCT and change the view to the second listing design.

**Expected behavior**
In CPT's I see that the elements that meet the condition change its design to the second listing type. However, with CCT's I don't see any changes, even if the select field condition is met. I would expect that the elements that meet the selected field condition would be displayed with the second listing design, but they aren't.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome & Firefox
 - Version: 88.0.4324.182 (Chrome) & 85.0.2 (Firefox)

**Comment by EDR1EN** [comment]
This would be great to have! Just stumbled across the exact same problem.

**Comment by kaskad88** [comment]
Fix for the next version ( v2.10.1 ).
Thanks for your report!
