### ISSUE TITLE
i need a custom scrolling section event elementor.

### ISSUE THREAD

**Issue by jiwoo79** [CrocoBlock/suggestions#269]
The existing functionality is somewhat customizable.
https://metalabs.cellact.me/

Like the site you want to implement
I would like to add a function to insert label hint position and text or images in section scroll.

I try to implement it with an attached script, but the implementation is not good. ;;

//$(window).on('scroll', function() {
    //$('.target').each(function() {
        //if($(window).scrollTop() >= $(this).offset().top) {
           // var id = $(this).attr('id');
           // $('.section-button').removeClass('active');
          //  $('.section-button[href=#'+ id +']').addClass('active');
       //}
    //});
//});

**Comment by Floydtm** [comment]
@jiwoo79 Could you describe in more detail what you want to get
