### ISSUE TITLE
JetBooking: Booking Policy Feature (Minimum Days to Book)

### ISSUE THREAD

**Issue by KHRifat** [CrocoBlock/suggestions#2692]
Booking policy (minimum days to book, like 2 days booking) is very important feature. 

I see lots of people are looking for this feature.

I would really appreciate if you (@MjHead, @Crocoblock) adopt this feature with Multiple Booking.

Thanks in Advance.!

**Comment by UraraReika** [comment]
I merged this issue with #1833, which is on the same subject so we could deal with it more efficiently.
