### ISSUE TITLE
JetEngine: relations feature

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#270]
EN:
Now we can create relationships between post types (Post Type). I think we need to add here the possibility of working with taxonomies. That is, create a relationship between two taxonomies. Perhaps this is not obvious, so I will give an example where I need to practically apply it.

On the site, I do not use a hierarchical structure for product categories. All taxonomies that are added to a product are created as tags. And they are logically divided: "Sections of goods", "Groups of goods", "Tags of goods", etc. - From general to specific. When working with a large semantic core, this separation is clearly visible.

In the usual hierarchy, what I called a group of products is a sub-category of the section of goods. But, since This scheme is dead-end and inconvenient, I refused it. The reason is simple - in practice, many different groups fall into one section, and in the hierarchical structure there can be only one group (child category).

However, sections with groups must be connected. For example, the group "Lighters" directly relates to the section "Tobacco accessories" and between them you need to establish relationships.

Also work with taxonomies is still worth adding to metaboxes. In ACF, there is a similar functionality and it is very good. In practice, it is more convenient to add terms for writing in the ACF fields, and you can optionally synchronize them with standard wordpress metaboxes, where these terms are added.

RU:
Сейчас мы можем создавать отношения между типами записей (Post Type). Думаю, нужно добавить сюда ещё возможность работы с таксономиями. То есть, создавать отношения между двумя таксономиями. Возможно, это не очевидно, поэтому приведу пример, где мне необходимо это практически применить.

На сайте я НЕ использую иерархическую структуру для категорий товаров. Все таксономии, которые добавляются к товару, созданы, как теги. И логически они разделены: "Разделы товаров", "Группы товаров", "Теги товаров" и т.п. - от общего к частному. При работе с большим семантическим ядром это разделение хорошо видно.

В обычной иерархии то, что я назвал группой товаров - это подкатегория раздела товаров. Но, т.к. подобная схема тупиковая и неудобная, я от неё отказался. Причина простая - на практике в один раздел попадают много разных групп, а в иерархической структуре группа (дочерняя категория) может быть только одна.

Тем не менее разделы с группами надо соединить. К примеру, группа "Зажигалки" напрямую относится к разделу "Табачные аксессуары" и между ними нужно установить отношения.

Также работу с таксономиями ещё стоит добавить в метабоксы. В ACF подобный функционал есть и он очень хороший. На практике более удобно добавлять термины для записи в полях ACF, также их можно по желанию синхронизировать со стандартными метабоксами вордпресса, где эти термины добавляются.

**Comment by MjHead** [comment]
Added with 2.11.0
