### ISSUE TITLE
JetEngine grid listing 'load more' leaves focus at bottom of grid

### ISSUE THREAD

**Issue by getunrealtoday** [CrocoBlock/suggestions#2705]
When the 'load more' option is selected for a JetEngine Listing Grid, after loading additional list items, the focus is left at the bottom of the grid, rather than at first new item loaded into the grid. This happens regardless of whether more items are loaded 'by click' or with the infinite load option.

This behavior is problematic because:

1. It is not obvious that more listing items have been loaded
2. The user may miss some or all of the newly loaded items because they are off-screen
3. Even if the user notices that new items have been loaded, the user is forced to scroll up to the top of the newly loaded items. On a mobile this could mean having to scroll up several screens.

At best, the behavior is counter-intuitive and annoying. At worst, it will cost me sales because visitors are missing new products loaded into the grid.

**To Reproduce**
1. Create a listing grid (any listing type will do)
2. On the Content tab under 'General', specify a number of posts to load
3. Set the 'Load more' option to 'YES'
4. 'Load more type' can be set to either 'Infinite scroll' or 'By click'

**Expected behavior**
The focus should stay at the top of the newly loaded items, not at the bottom.

** Devices and Browsers **
I have tested this on Windows 10 with Edge, Firefox and Chrome, and the problem is present on all.
I did notice that on my iPad, using Safari, the issue is not there. So if you want to see what the correct behavior should be, try it on and iPad with Safari.

I notice that this issue has been raised before:
https://github.com/Crocoblock/suggestions/issues/2008
https://github.com/Crocoblock/suggestions/issues/1969

**Comment by getunrealtoday** [comment]
After further testing I have narrowed to issue down to a conflict between the JetEngine Listing Grid and the [Elementor shape divider](https://elementor.com/help/shape-divider/). The conflict only occurs when a shape divider is added to the bottom of an Elementor section which contains a Listing Grid. I am not sure whether this is something that needs to be fixed by Crocoblock or Elementor...

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know.
