### ISSUE TITLE
JetTricks Sticky Column Not Working

### ISSUE THREAD

**Issue by ayhanmalkoc** [CrocoBlock/suggestions#2709]
Inspection in test environment. It does not work with the following themes and plugins. Please check.

Wordpress 5.6.2
JetEngine 2.7.2
JetTricks 1.3.4

**Comment by Floydtm** [comment]
We have checked everything and everything is working correctly. However, our sites can be customized in different ways. Check for updates or contact our support team. Thanks you!

**Comment by ayhanmalkoc** [comment]
thank you
