### ISSUE TITLE
Change the type of selection for the quantity of product

### ISSUE THREAD

**Issue by Bertnick1** [CrocoBlock/suggestions#2711]
Hi,
I wanted to ask for the possibility of having a different selection for adding quantities of product. The arrows now present are a little uncomfortable and often create some discomfort.  I am attaching an example possibility with the symbols + and -

![eco1](https://user-images.githubusercontent.com/72300193/109163479-acdf5e00-7779-11eb-8073-029219c58d5a.JPG)
![eco2](https://user-images.githubusercontent.com/72300193/109163485-ae108b00-7779-11eb-817a-b0ec16d2d188.JPG)

**Comment by fabi20x** [comment]
+1

**Comment by sonnesworld** [comment]
+1

**Comment by 79ho3ein** [comment]
Yes, this feature is very important and necessary.

**Comment by Hans-101** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by creativeart** [comment]
+1

**Comment by 79ho3ein** [comment]
hello @UraraReika, excuse me...
What does the **pending** label mean? may you tell?

thank you

**Comment by Dhaump** [comment]
+1

**Comment by UraraReika** [comment]
You can check this [page](https://crocoblock.com/freemium/tools/) for additional plugin or download directly from [repo](https://github.com/UraraReika/jet-woo-builder-custom-quantity-selectors).
