### ISSUE TITLE
JetBooking add specific pricing to each day of the week

### ISSUE THREAD

**Issue by NicolasMarkl0** [CrocoBlock/suggestions#2717]
Hi there, 

I wanted to add another feature I am currently missing.

There should be a feature which extends the advanced pricing feature. You should be able to define spezific prices for each day of the week. For example when you book something the price is higher on the weekend than during the week. 

In many businesses the price for the weekend is always higher than during the week so this feature would have great value to many people.

I hope you can implement this as soon as possible. We really need it! 
Thank you your plugins are awesome!

**Comment by TODO4EVER** [comment]
Hey, Is it seasonal or do you just want higher weekend prices ? 
If the latter, you can workaround it by creating multiple custom posts and assign each post with specified days. Make the form as which days first before displaying the calendar.
Not very convenient thought.

**Comment by UraraReika** [comment]
This functionality already released. You can fell free to check it out.
