### ISSUE TITLE
Calendar "Next Arrow" points in wrong direction

### ISSUE THREAD

**Issue by Audiotuete** [CrocoBlock/suggestions#2718]
![Next Arrow](https://user-images.githubusercontent.com/13610803/109291426-43b72380-7829-11eb-9bdd-65aaaa7ce8db.png)

**Comment by catherinewiltshire** [comment]
Same on mine

![calendar-arrows](https://user-images.githubusercontent.com/40239762/110141995-9b2b3580-7dcd-11eb-8891-aa896f65163c.jpg)

**Comment by kaskad88** [comment]
@Audiotuete @catherinewiltshire,  thanks for your report! This issue will fix in the next version. The temporary solution is to paste the following CSS code in the custom CSS section in the customizer 
`body:not(.rtl) .jet-calendar-nav__link.nav-link-next svg {
    transform: scaleX(-1);
}`
