### ISSUE TITLE
JetEngine: dynamic feature for video widgets

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#272]
EN:
Faced an interesting problem. In short - in the Product Archive  you need to display a list of videos. I imagine this process as dynamic.

1. I create a Repeater field in the metabox, in which I insert links to YouTube, other hosting or video files.

2. Create a listing based on these fields.

3. I display listing in the necessary template.

In practice, this did not happen. As I understood in widgets, not only in Jet, but in general in all, support for oEmbed is not provided, plus the video widgets for this do not support the dynamics. Today, you can only insert one video on the page directly or as a background, and that’s it.

To solve my problem, there is another option - to create a type of Video post and configure it to work with video content. One entry = one video. And then output in listings and other widgets, like regular entries.

RU:
Столкнулся с интересной проблемой. Если кратко - в карточке товара надо вывести список видеозаписей. Я себе представляю этот процесс динамическим.

1. Создаю в метабоксе поле Repeater, в который вставляю ссылки на ютуб, другие хостинги или видеофайлы.

2. Создаю листинг на основе этих полей.

3. Вывожу листинг в нужном шаблоне.

На практике сделать этого не получилось. Как я понял в виджетах, не только в Jet, а вообще во всех, не предусмотрена поддержка oEmbed, плюс к этому виджеты для видео не поддерживают динамику. Сегодня можно только вставить одно видео на странице напрямую или как фон и на этом всё заканчивается.

Чтобы решить мою задачу, есть ещё вариант - создать тип поста Видео и настроить его для работы с видео контентом. Одна запись = одно видео. А потом уже выводить в листингах и других виджетах, как обычные записи.

**Comment by MjHead** [comment]
Added filter "embed_url" for repeater items
