### ISSUE TITLE
Testimonial Widget - Dynamic Settings Not Pulling Through Correctly

### ISSUE THREAD

**Issue by martinjacksonuk** [CrocoBlock/suggestions#2723]
As per the uploaded image the icon and comment field don't appear to be pulling through correctly from the post meta repeater fields.

Icon - displays a question mark

Comments - display at the top and not within the blue place holder.

<img width="1774" alt="2021-02-26_18-28-36" src="https://user-images.githubusercontent.com/78558151/109340377-d921da00-7860-11eb-8317-7a6477032c4b.png">

**Comment by kaskad88** [comment]
Hi @MartinJacksonUK. To display an icon use a filter `render_fa_icon`. For your case in the Icon filed need to add - `testimonial-icon|render_fa_icon`

**Comment by kaskad88** [comment]
The comment display issue will fix in the next version. Thanks

**Comment by martinjacksonuk** [comment]
Hi Dmitriy

Can you point me in the direction of the reference material and where exactly do I place the filter.

Many thanks

Martin


Martin Jackson
DiGenie Limited

[A picture containing vector graphics  Description automatically generated]<https://www.digenie.co.uk/?utm_source=logo_banner&utm_medium=email&utm_campaign=email_signature>
T: 0161 823 1188 | M: 07723 725833| E: martin.jackson@digenie.co.uk<mailto:martin.jackson@digenie.co.uk> | W: digenie.co.uk<https://www.digenie.co.uk/?utm_source=web_link&utm_medium=email&utm_campaign=email_signature>
Registered in England | Company registration number: 12317396 | Registered address: Jactin House, 24 Hood Street, Ancoats, Manchester, M4 6WX, United Kingdom
This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of DiGenie Limited.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by martinjacksonuk** [comment]
Ok Dmitriy

When is the next version coming  and can you suggest a work around until the next version is available?

Many thanks

Martin



Martin Jackson
DiGenie Limited

[A picture containing vector graphics  Description automatically generated]<https://www.digenie.co.uk/?utm_source=logo_banner&utm_medium=email&utm_campaign=email_signature>
T: 0161 823 1188 | M: 07723 725833| E: martin.jackson@digenie.co.uk<mailto:martin.jackson@digenie.co.uk> | W: digenie.co.uk<https://www.digenie.co.uk/?utm_source=web_link&utm_medium=email&utm_campaign=email_signature>
Registered in England | Company registration number: 12317396 | Registered address: Jactin House, 24 Hood Street, Ancoats, Manchester, M4 6WX, United Kingdom
This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of DiGenie Limited.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by kaskad88** [comment]
@MartinJacksonUK paste `testimonial-icon|render_fa_icon` in the Icon field - https://prnt.sc/10a6f9r . The next release planned in 1-3 days.

**Comment by martinjacksonuk** [comment]
Ok thank you.

So for future reference it’s the “name/ID” of the repeater field then “|” and then the “filter”

Is there any more reading material on this subject?

And look forward to the next release.

Thanks for all your help

M


Martin Jackson
DiGenie Limited

[A picture containing vector graphics  Description automatically generated]<https://www.digenie.co.uk/?utm_source=logo_banner&utm_medium=email&utm_campaign=email_signature>
T: 0161 823 1188 | M: 07723 725833| E: martin.jackson@digenie.co.uk<mailto:martin.jackson@digenie.co.uk> | W: digenie.co.uk<https://www.digenie.co.uk/?utm_source=web_link&utm_medium=email&utm_campaign=email_signature>
Registered in England | Company registration number: 12317396 | Registered address: Jactin House, 24 Hood Street, Ancoats, Manchester, M4 6WX, United Kingdom
This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of DiGenie Limited.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by kaskad88** [comment]
https://github.com/ZemezLab/jet-elements-dynamic-data/blob/master/README.md

**Comment by martinjacksonuk** [comment]
Thank you, have a great day!!



Martin Jackson
DiGenie Limited

[A picture containing vector graphics  Description automatically generated]<https://www.digenie.co.uk/?utm_source=logo_banner&utm_medium=email&utm_campaign=email_signature>
T: 0161 823 1188 | M: 07723 725833| E: martin.jackson@digenie.co.uk<mailto:martin.jackson@digenie.co.uk> | W: digenie.co.uk<https://www.digenie.co.uk/?utm_source=web_link&utm_medium=email&utm_campaign=email_signature>
Registered in England | Company registration number: 12317396 | Registered address: Jactin House, 24 Hood Street, Ancoats, Manchester, M4 6WX, United Kingdom
This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of DiGenie Limited.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.
