### ISSUE TITLE
Jet Booking seasonal price.

### ISSUE THREAD

**Issue by jannelundin** [CrocoBlock/suggestions#2726]
I would wich that you add seasonal pricing in jet booking, beacause it is very
important that you can put different prices for different months or seasons.
I find jet booking quite good otherwise but without this feature it is nearly
useless.

**Comment by 8persap** [comment]
Please can you add seasonal pricing as a priority? This plugin is so good and well thought out on every level but this. Seasonal pricing is key to any rental or hotel bookings. Without it, it rules out Jetbooking as a viable option. Please can you commit to addressing this? Thank you. 👍

**Comment by Giulioski80** [comment]
I found out right now that this feature is missing making the plugin useless.  
Would be great having it. I'm working on a project but without it I need to find different way to make it.

**Comment by jannelundin** [comment]
This issue have been posted for morse then a year
It does not look like they take this serious.
And there is also a problem when you book for example 
10/4-17/4, you cant book 5/4-10/4, because the 10 is fully
Occupied.

**Comment by jannelundin** [comment]
I have now skipped jet bokning, I have to find another solution
I worked on this for a year hoping something Will happenings, but no so now I skip jet booking😡😡

**Comment by ghost** [comment]
@jannelundin what are you using now?
JetBooking is perfect for search filters integration, custom objects with JetEngine, but this missing feature make it unusable for serios purposes

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.4.0 version. You can fell free to check it out.

Thank you!
