### ISSUE TITLE
Timed Widget Visibility/Display Options

### ISSUE THREAD

**Issue by shoutcloudstudios** [CrocoBlock/suggestions#2729]
I have searched and searched and no one has this ability. I think this would be a valuable addition to your unique Elementor features. 

I have a need for a widget feature that no one has created and I think you guys could build yet another unique and simple widget capability that no one has that will help make your plugin as desirable and unique as possible.

Look at the following page in the top hero video section: https://barts.shoutclouddev.com/

I would like to have the Elementor Headline Widget (or any other widget) appear and disappear on a timed basis on top of this video background. 

For example, I want the name of each building to appear on top of the video when each specific building comes into focus. And then have the name of that building disappear at the appropriate time. So I would need the ability to loop, to have a start time and an end time. 

As it is right now, I can only delay the starting visibility of a headline widget using Elementor Motion Effects. I cannot have the headline widget disappear after an amount of time like I would want it to. Once it comes in, it stays, and I don't want that in this case. I want to be able to:

1) I have 4 different groups of content to display, each group needs to be treated as its own content layer that accepts text, images, html, video, or whatever. 

2) Have a beginDisplayTime, example 5 seconds after the page load

3) Have a stopDisplayTime, example 12 seconds after the page load

4) Have a effectLoopTime, example 22 seconds after the page load it starts over again

5) Also needs the animation options that exist in the Elementor Motion Effects feature. https://i.imgur.com/v34CE4P.png

I would like you to consider creating a Motion Effects plugin or widget that gives me the ability to have layers that fade in and fade out and loop like what is described here. 

![](https://i.imgur.com/52okKjd.png)

![Elementor _ Home - Google Chrome 2021-02-28 at 8 17 17 AM](https://user-images.githubusercontent.com/66252860/109421680-ebedf900-799d-11eb-8a3f-433dc40ff466.png)

**Comment by Floydtm** [comment]
We will not do this for now. You'd better look for another solution for your case. Thank!
