### ISSUE TITLE
Suggestion: Table layout for JetWooBuilder

### ISSUE THREAD

**Issue by MacGuyver-jv** [Crocoblock/suggestions#273]
I like the idea JetWooBuilder, but I really think a table layout would be great. I feel that the list layout is a bit restrictive on the options, and I would like the ability to customize it a bit more.

As it is now I have found many other table layouts, but I would like one that integrates with your filters.

Thanks

**Comment by UraraReika** [comment]
This feature will be added as separate module with JetEngine 2.9.0. More details here - #3803
