### ISSUE TITLE
JetEngine: Custom Post Type visibility 

### ISSUE THREAD

**Issue by pixallusdev** [CrocoBlock/suggestions#2730]
It would be a nice feature to include a toggle for logged-in/public visibility when creating new post types. For example, when the toggle for logged-in users is On, than the CPT is only visible to logged-in users. 

![Screen Shot 2021-03-01 at 1 13 36 AM](https://user-images.githubusercontent.com/7123064/109458745-6add4300-7a2b-11eb-9c89-c9f458466dc9.png)

**Comment by Floydtm** [comment]
Your request is related to a custom solution. We will not add this to the plugin. Thank!
