### ISSUE TITLE
calendar with multiple same posts based on repeater data

### ISSUE THREAD

**Issue by Zegklitz** [CrocoBlock/suggestions#2731]
Hello, 

I have a question if it would be possible to add functionality possible to create calendar with multiple same posts based on dates filled in repeater in post detail.
In my situation I have Woo product. This product is conected with one Zoom meeting. This meeting is however split in several sup-meetings (technicly it is one Zoom meeting with one join link, but the people will meet multiple-times in different times and dates).
In order for customers to know on what days and at what time to meet, I created a repeater field in the product detail. There, the administrator fills in the dates and times of individual "sub-meetings", which are then displayed on the frontend on the product detail page.
I would like to create a calendar that would display the same Zoom meeting (product) based on individual dates from the repeatr field from the product detail.
Would it be possible to add this feature? I think it would have use in many other situations.

**Comment by Floydtm** [comment]
We will not do this for now. As soon as we collect more requests we will return to this. Thank you!
