### ISSUE TITLE
Display individual rating fields.

### ISSUE THREAD

**Issue by siscanu** [CrocoBlock/suggestions#2733]
I have 3 star rating fields for each post. I can display only an average rating for all 3 fields. I need to have the possibility to display the average rating for each field. Thanks.

**Comment by Floydtm** [comment]
Describe your request in more detail. Attach screenshots or videos. Thank!

**Comment by Radzio1615** [comment]
I need the same functionality! For example, users can rate Design, Quality and Performance of the product. I need to display average rating of each parameter and overall average rating.

![rating](https://user-images.githubusercontent.com/40895581/150408792-b1507d13-af21-4245-8066-ce95ab66d8fa.png)

**Comment by Floydtm** [comment]
I noticed that you are using the old reviews widget. To implement your request you need to use the new reviews widget https://crocoblock.com/knowledge-base/articles/jetreviews-how-to-add-reviews-to-the-post/

**Comment by Radzio1615** [comment]
I use JetReviews 2.2.4. I know how to display Reviews Listing. I need help with Static Review widget. I want to display dynamic average rating for all items. I need to use a dynamic tag in the "Field Value" to get average rating of "Design". But there is no proper dynamic tag.
 

![image](https://user-images.githubusercontent.com/40895581/150554235-510bd8f9-4827-4fd6-90b4-7cf9fc189e83.png)

![image](https://user-images.githubusercontent.com/40895581/150556090-61f7e819-2153-4960-8dd5-5a6f19f1c04b.png)
