### ISSUE TITLE
Waveform to audio player

### ISSUE THREAD

**Issue by josiase95** [CrocoBlock/suggestions#2734]
Would be very nice to have the abillity to customize the audio player to the waveform of the track. 

Something like this: 

![image](https://user-images.githubusercontent.com/42859324/109497658-aa8b4580-7a92-11eb-8970-b48b96af40cb.png)

**Comment by Floydtm** [comment]
We're not going to do that right now. developers are busy with more complex tasks. As soon as we collect more similar queries, we'll come back to this. Thank!
