### ISSUE TITLE
Securing the forms via Honey Pot - GDPR 

### ISSUE THREAD

**Issue by Michael1983De** [CrocoBlock/suggestions#2737]
Sadly here in the EU it is a big concern, if user data is send outwards to google etc.

But for f.e. #JetApppointment , the only way to secure the form is atm ReCaptcha.

Other forms, f.e. the normal form of the elementor, has the option for a honey pot.

Is there a existing way to include that feature, or to integrate it in a feature update?

Greetings
Michael

**Comment by IFTTD** [comment]
Definitely need this. At least have the ability to adjust the reCAPTCHA score till it can be implanted.

**Comment by Floydtm** [comment]
#2307
