### ISSUE TITLE
Badge System

### ISSUE THREAD

**Issue by diogui** [CrocoBlock/suggestions#2739]
System to create badges and choose which badge to show in each product. Examples like: New, Editor's Choice, {Category Name} (to call users attention for a specific category). 

While editing the product, user could choose which badge want to show. 

Useful if the badge show on product grid/list and on the Product single page.

**Comment by enuzzo** [comment]
I totally endorse this request. Every client is asking for something like that. "New" / "Best seller" / etc.
I tried almost any of the best selling plugins but they are not compatible with croco loops.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
