### ISSUE TITLE
Add input fields for the Range Filter widget (JetSmartFilters)

### ISSUE THREAD

**Issue by SMolodoy** [CrocoBlock/suggestions#2746]
At the moment, the Range Filter widget allows you to adjust the value only by using the slider. 
![image](https://user-images.githubusercontent.com/8123380/109776410-9589f000-7c13-11eb-9abb-f239b88ddb48.png)

With a large range, it can be difficult to "catch" the desired value, not to mention the mobile versions of the site. In this case, it would be a good solution to add input fields.
![image](https://user-images.githubusercontent.com/8123380/109776270-74290400-7c13-11eb-87f4-7f2f17b08467.png)

Please, review this request.
Thank you!

**Comment by Medienor** [comment]
Beutiful SMolodoy, 1+ WE WANT THIS ALSO! 👍

**Comment by Floydtm** [comment]
We are working on it. Keep for updates. Thank you!
