### ISSUE TITLE
Suggestion: Shopping Cart Price Rules 

### ISSUE THREAD

**Issue by Dimi33** [Crocoblock/suggestions#275]
It will be great to add on jetwoo builder or other crocoblock plugins new function Shopping Cart Price Rules

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
