### ISSUE TITLE
Add Or Integrate Jet Engine with OXYGEN BUILDER

### ISSUE THREAD

**Issue by kunalllll** [CrocoBlock/suggestions#2753]
Hello, I am a User of your plugin for a long time now but now I have migrated for Elementor to Oxygen Builder and I miss Jet Engion Feature and Function and Easy to Use Thing and I know you guys are working on The Interrogation of Jet Engion with oxygen but you Guys has not yet clarified the date or any king of Alpha or Beta Release allowancement so as I type this message I know many of the Elementor User has already migrated to Oxygen Builder because of many Factor so I hope I get Response soon!!!

**Comment by ayhanmalkoc** [comment]
+1

**Comment by siscanu** [comment]
If you do this, please make a  separate plugin for Oxygen. I appreciate a well-coded plugin, without bloat.

**Comment by kunalllll** [comment]
Yes i totally with you @siscanu and also they combine Feature's of **#JET ENGINE** and **#JET SMART FILTER** with in 1-plugin and remove all the bloat and **I guarantee that this plugin will sell like crazy** what are your thought in this matter..

**Comment by jmcward007** [comment]
Would love Jet Engine to work with Oxygen!!!

TX

**Comment by Floydtm** [comment]
https://www.facebook.com/groups/CrocoblockCommunity/posts/4533744080050311
