### ISSUE TITLE
Booking-Form only send Email, if the booking was succsessfull

### ISSUE THREAD

**Issue by Hammer-ger** [CrocoBlock/suggestions#2758]
Is ist possible, that a E-Mail is send only, if the booking was succsessfull? 
At the Moment the emails from the "send email" action will send an email every time the submitbutton is pushed. 

Hope my request is understandable?

Best wishes,

Hammer

**Comment by UraraReika** [comment]
Hello. Thanks for the feedback.

During plugin development this issue was solved. But we highly recommend to use JetBooking in combination with JetFormBuilder.

Thank you for your understanding.
