### ISSUE TITLE
Pagination for Listing Grid

### ISSUE THREAD

**Issue by MPHood** [Crocoblock/suggestions#276]
It would be great if pagination was implemented in to the listing grid widget. 

Right now i have to install "jet smartfilter" in addition to jet engine to get what I need.

In this specific project, i dont need jet smart filter, except for the pagination.

Its not optimal to be forced to use two plugins if only one would also do the job.

**Comment by redordev** [comment]
+1

Please please please add pagination for listing grid! Ideally these options:

1) pagination
2) load more
3) infinite scroll

**Comment by MjHead** [comment]
Done (pagination with JetSmartFilters)

**Comment by Reshma62** [comment]
I faced faced the issue when i use listing grid and click the next button the pagination not render <div class="jet-filters-pagination"><div class="jet-filters-pagination__item prev-next prev" tabindex="0" data-value="prev" disabled=""><div class="jet-filters-pagination__link">Previous</div></div><div class="jet-filters-pagination__item jet-filters-pagination__current" tabindex="0" data-value="1"><div class="jet-filters-pagination__link">1</div></div><div class="jet-filters-pagination__item" tabindex="0" data-value="2"><div class="jet-filters-pagination__link">2</div></div><div class="jet-filters-pagination__item" tabindex="0" data-value="3"><div class="jet-filters-pagination__link">3</div></div><div class="jet-filters-pagination__item" tabindex="0" data-value="4"><div class="jet-filters-pagination__link">4</div></div><div class="jet-filters-pagination__item prev-next next" tabindex="0" data-value="next"><div class="jet-filters-pagination__link">Next</div></div></div>-- this is my first page ========
<div class="jet-smart-filters-pagination jet-filter" data-apply-provider="jet-engine" data-content-provider="jet-engine" data-query-id="all-scholarships" data-controls="{&quot;items_enabled&quot;:true,&quot;pages_mid_size&quot;:0,&quot;pages_end_size&quot;:0,&quot;nav_enabled&quot;:true,&quot;prev&quot;:&quot;Previous&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;hide_inactive_nav&quot;:false,&quot;load_more_enabled&quot;:false,&quot;provider_top_offset&quot;:0}" data-apply-type="ajax" jsf-filter="" style="display: block !important; visibility: visible !important; opacity: 1 !important; height: auto !important;"></div>--- and my second page is show any pagination
