### ISSUE TITLE
Conditions | Visibility Column still there...

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#2766]
**Describe the bug**
When you add a Visibility Condition into a "Column" is not showing the column, but the space is "still there".

Here the column have the condition "show if logged in".

![image](https://user-images.githubusercontent.com/68023943/110223986-95f5e580-7eb6-11eb-849d-e4781896e18e.png)

Works PERFECT!
![image](https://user-images.githubusercontent.com/68023943/110223996-a3ab6b00-7eb6-11eb-9792-be19bef4538c.png)

But, when u are not logged in, instead of making the other elements "bigger" or "full-width", shows an empty space... Like this...

![image](https://user-images.githubusercontent.com/68023943/110224012-c8074780-7eb6-11eb-9d0a-18f78d1f3765.png)

This is how this need to work:

![image](https://user-images.githubusercontent.com/68023943/110224032-06046b80-7eb7-11eb-90bb-377f2a65366f.png)

**Comment by kaskad88** [comment]
Hi, @maurocarreraok. You need to enable the **Resize other columns** option https://prnt.sc/10f58v6 for your case.

**Comment by maurocarreraok** [comment]
Thanks!!! :)
