### ISSUE TITLE
Self-closing unfold widget

### ISSUE THREAD

**Issue by getunrealtoday** [CrocoBlock/suggestions#2767]
At the moment there are two buttons for the unfold widget, one to unfold (open) and the other to fold (close). Once the widget is unfolded, the only way to fold it again is to click the relevant button.

It would be great to have the following additional options:

1. Close (fold) the widget on click anywhere outside the unfolded content
2. Auto-fold the widget again after a specified amount of time

Thanks!

**Comment by Gawuww** [comment]
Added in 1.3.9
