### ISSUE TITLE
Dynamic Links in JetMenu

### ISSUE THREAD

**Issue by imCorfitz** [CrocoBlock/suggestions#2772]
In the JetMenu settings, I suggest adding an overwriting link field that is determined based on variables set. I my case, I have created a CPT in JetEngine for releases of our monthly magazines, and I would like a link in the nav menu to always link to the latest version on ISSUU.

Using listings I am able to always include the latest version with cover in our mega navigation but would like a main menu link to also look for the latest ISSUU link added. 
 
![Screenshot 2021-03-09 at 10 14 58](https://user-images.githubusercontent.com/52371939/110455412-500c6d80-80c0-11eb-9434-b7795bfbb1ae.png)

**Comment by Floydtm** [comment]
Hi! I understand that this is important for you, but now our developers are busy with more important tasks and we cannot add this to the plugin right now. Thank!
