### ISSUE TITLE
Booking cut off time

### ISSUE THREAD

**Issue by PaulusG** [CrocoBlock/suggestions#2778]
Hey, working on a rental site. We want to exclude bookings after a certain time slot. eg. You can not book a machine for today, after  0400 o'clock in the morning. The rental company needs some time to prepare the rental.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1597, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
