### ISSUE TITLE
JetElements: Instagram widget

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#278]
Need option to display images in square form with high resolution remained.

Case: Putting the setting to "original" (or any other then thumbnails 150x150px) displays the images in their original aspect ratio, and we want to have them displayed as squares.

**Comment by Floydtm** [comment]
At the moment we can not implement this functionality. At the moment you can display images with such options http://prntscr.com/nsuae0 http://prntscr.com/nsuar4

**Comment by imCorfitz** [comment]
I would consider it a bug, that "standard" should return 640 x 640 square image, but still returns the full original image. 
![Screenshot 2021-03-30 at 11 58 38](https://user-images.githubusercontent.com/52371939/112980590-f8f33900-9151-11eb-9018-1f20fdfe1829.png)

**Comment by imCorfitz** [comment]
I have provided a simple alternative solution at #2190
