### ISSUE TITLE
CCT Relationships

### ISSUE THREAD

**Issue by numanagit** [CrocoBlock/suggestions#2784]
CCT are very powerful to develop complex data structure. But it is on early development state. Today to make a relationship between CCTs we have to do it as usual, adding foreing keys. It will be awesome if we use similar relatioships method as CPT.

Thanks

**Comment by hynesight** [comment]
It seems such an obvious progression for the tool and whilst I have no idea of the complexity for enabling this sort of feature into the Jet Engine platform, it just makes sense.

**Comment by MjHead** [comment]
Added with 2.11.0
