### ISSUE TITLE
JetEngine: Add the ability to assign Meta Boxes to Relationship

### ISSUE THREAD

**Issue by vovkasolovev** [CrocoBlock/suggestions#2785]
Often it is not enough to have just a **Relationship** between **Post Types**. Usually you also need to specify the _parameters_ of that _particular relationship_. This information does not belong to any of the CPTs for which the relationship is configured, but every CPT needs it. It would be great if a **Meta Box could be assigned specifically to the Relationship itself**, not just to one or the other Post Type.

Examples:
### 1) A website with a creative team portfolio.
There are CPT "**Projects**" and CPT "**Participants**" which should have a Meta Box **Relationship** that contains information about what work was performed by a participant in a specific project. In a **Project** a **Participant** could be an _author of a text_, in another **Project** a **Participant** could be a _consultant_, an _assistant_, an _editor_, a _photographer_, and so on. On the **Project post page**, you can see which Participants acted in what role. On the **Participant post page** you can see his roles in each of the projects.

### 2) News aggregator site.
CPT "**News Reposts**" and CPT "**Sources**" should have a **Relationship** that specifies via Meta Box information about a particular _URL_ of a particular news source, _news headline on the source_ (or several URLs and headlines, using Repeaters). The **News Repost post page** will contain a nice _titled link_ to the news at the source. The **Sources post page** will collect _headlines_ with _URL_ to the original news that was reprinted on this aggregator site.

**Comment by kochhase** [comment]
For now I only no that toolset is doing this kind of things.  And the backend to do some kind of infos to the relationsships is missing to. See toolset

![2021-03-11 13_50_22-Edit Fußballer ‹ Prüss Oberliga — WordPress](https://user-images.githubusercontent.com/6199062/110790019-d071d080-8270-11eb-88bd-b58a52d9cab2.png)

**Comment by vovkasolovev** [comment]
With the JetEngine 2.11 update it is now possible to add Meta Fields to Relations. I think this issue can be closed. Video about it (5:51): https://youtu.be/4ZNF_BTBQ8M?t=351

Thank you, Crocoblock Team!
