### ISSUE TITLE
JetEngine: Checkbox «Allow custom»

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#2787]
This is a good solution to allow you to add new data immediately when adding records. But the bad thing is that there is no way to remove the extra ones there. Consider this possibility, I think it will be useful.

**Comment by Floydtm** [comment]
Hello. If you do not fill in with custom, then it will not be saved. If you delete the label and save the post, the custom will disappear. However, this will not work if this option is enabled https://prnt.sc/10pp9hn Maybe we will revise the UI
