### ISSUE TITLE
JetEngine | JetBooking - Display CPT title after choice in forms checkbox list

### ISSUE THREAD

**Issue by admiraldon** [CrocoBlock/suggestions#2788]
In my booking form I have a checkbox list created by CPT “Addons”. If I don't specify a meta field only the post id will show up in the booking details, meaning numbers instead of clear text...useless for the customer.

I found a solution for, because support confirmed that this feature is missing. You only have the choice between post id or meta field. But for most logical case would be displaying choice of form user in text in the booking detail.

![image](https://user-images.githubusercontent.com/80383757/110750792-4e1ee780-8243-11eb-9e89-9f420f3ae14c.jpeg)

![image](https://user-images.githubusercontent.com/80383757/110750814-5b3bd680-8243-11eb-926c-8369ca343604.jpeg)

Thx for your passion

**Comment by UraraReika** [comment]
Hello. Thanks for the feedback.

In the next version of our plugin we will add hook that can help you to handle some fields output.

Thank you for your understanding.
