### ISSUE TITLE
Export/Import entire jetengine setup

### ISSUE THREAD

**Issue by Abz2604** [CrocoBlock/suggestions#2790]
A lot of people use demo installations to experiment/research/implement new features.

Once complete, users should have an ability to transfer the features (only) created using the Crocoblock plugins to a new site. So that we can create features in sandbox kind of environments, and once done, transfer it to a live site and get it up and running with minimal configuration. Sort of like a "feature recipe".

**Comment by Floydtm** [comment]
Right now there are many options for transferring content from site to site. if you have any problems with this, then you better contact our support service.

**Comment by Abz2604** [comment]
I'm talking about transferring the Crocoblock configuration, not the content...
