### ISSUE TITLE
Image in wysiwyg type

### ISSUE THREAD

**Issue by henriquebarcellos** [CrocoBlock/suggestions#2791]
Allow the inclusion of images through the JetEngine form when the field is of the wysiwyg type.

**Comment by Floydtm** [comment]
For now, we refuse to do this in our security plans. Thank!

**Comment by ATSFNL** [comment]
> For now, we refuse to do this in our security plans. Thank!

You are not making friends!
See how its is done by WP USER FRONTEND plugin.
Also see this post: https://github.com/Crocoblock/suggestions/issues/2586#issuecomment-879796065
