### ISSUE TITLE
JetEngine Forms: hCaptcha support 

### ISSUE THREAD

**Issue by DmitryBychenko** [CrocoBlock/suggestions#2792]
Google Captcha is going to become paid service.

hCaptcha is free, and offers to earn when visitors solve captchas on your website.

Can you add support of hCaptcha to JetEngine forms?

**Comment by mbhzpi** [comment]
I also need a feature to integrate hCaptcha in a JetEngine Form!

**Comment by girafffee** [comment]
Hi everyone)
This feature was included in JetFormBuilder 3.1.0

https://jetformbuilder.com/features/adding-hcaptcha-to-form/
