### ISSUE TITLE
 Issue: Tooltip from widget hotspots

### ISSUE THREAD

**Issue by Dimi33** [Crocoblock/suggestions#280]
Is not right that tooltip of specific hotspot hides under the other hotspot, it should cover other hotspots, I think that is the point when someone wants to see all contain text on tooltip. You can not read all the text of the tooltip if it is hidden under other hotspots. It should be resolved in new updates!

**Comment by Floydtm** [comment]
Sorry, we can not reproduce the bug. Could you provide more information on this request? Thanks you!
