### ISSUE TITLE
Oxygen Builder Architecture and CrocoBlock Support

### ISSUE THREAD

**Issue by ayhanmalkoc** [CrocoBlock/suggestions#2804]
Oxygen Generator Architecture

Hello, as an elementor user, I am a developer using other page builders due to lack of speed and performance. Oxygen generator creates a theme framework rather than a page builder that does what it says and is about speed. I have been using it since the day oxygen came out. I'd like to share a few tips that will benefit you.

1- Oxygen Builder inherits the existing theme structure.

2- All post types, custom fields, period etc. Supports.

3- You can call php one-to-one with the code block widget.

4- You add all css and html elements as they are.

Example: section> div (this is the output of dom. That's it.)

5- You can call all wordpress data and functions with the Text widget.

6- With Repeater Widget, wp query works for all post types.

7- With Easy Post Widget, you can support all post types and interfere with the entire html code.

8- Supports Wordpress Widgets.

9. Supports Gutenberg. In other words, a page created in Gutenberg with JetEngine and dynamic widget runs exactly the content of the article.

10- It has a Woocommerce page builder.

11- There is a shortcode widget.

12- With Selector Detector, you can customize a form added with a code block or a short code with css.

13- All widgets support gridbox, flexbox and all css.

My suggestion is that you don't need to develop a lot of widgets to get started with Oxygen. Supports Dynamic fields, Dynamic meta, Dynamic terms.

I guess you can support it by hooking for oxygen widgets.

With 3 Widgets, it can fully connect with crocoblock oxygen generator.

How:

1- Dynamic Item; Call all custom fields, meta, terms, link, view fields with "Source".

2- Dynamic Repeater; Search all repeatable areas.

3- Listing; List the "item template" types made with Gutenberg or oxygen.

so much.

#2753
#2617

**Comment by ayhanmalkoc** [comment]
What is the roadmap for Oxygen builder?

**Comment by ayhanmalkoc** [comment]
#2753
#2617

**Comment by Floydtm** [comment]
https://www.facebook.com/groups/CrocoblockCommunity/posts/4533744080050311
