### ISSUE TITLE
The option to add a filter, which shows only products on sale

### ISSUE THREAD

**Issue by Magn2871** [CrocoBlock/suggestions#2811]
Hi guys

Like on most e-commerce shops i have a lot of products on sale, which i want to sell. Here on the most shops it is possible for the user to apply a filter to only show products, which are on sale.

I think this feature is very needed and would make it easier for the users to find and see these sale products.

I sincerly hope, that you would take this in consideration and make this feature in the future.

Best regards
Magnus Guldbech

Guldbech.dk

**Comment by serg-pervushin** [comment]
I also faced this task.

For example, I add the checkbox filter type. Data source - manually enter "Discounted products". Value = 1. Query Variable = "on_sale". Does not work.

**Comment by Floydtm** [comment]
Guys, in order to solve your question, you need to know more information. It seems that all this can be done right now. What widget do you display products?

**Comment by serg-pervushin** [comment]
@Floydtm that would be great, thank you!

For example, I have a product catalog on https://wordpress-demo.ru/shop/ (made using the listing grid JetEngine). There is one product with a discount https://take.ms/RoKRE

There are filters (Jet Smart Filters) and all work correctly. But one filter does not want to show the necessary product cards. This is the "Discounted Products" filter https://take.ms/FH7WW

The filter itself was added as a checkbox with a custom label and a value of 1 (tried true). I tried adding _sale_price, on_sale, onsale to the query string. https://take.ms/sZHgc

It doesn't find anything, although there is still one product with a discount.

**Comment by Floydtm** [comment]
Now I Understand You. Make such a filter with the following settings https://prnt.sc/10tazy2 It works as you need https://prnt.sc/10tb1lv https://prnt.sc/10tb232

**Comment by serg-pervushin** [comment]
Thanks for the reply.

But it didn't seem to help me. So, I created a radio filter -> added a value «^[0-9]*$» -> Query Settings «_sale_price» and REGEXP https://www.screencast.com/t/x2vIdRRTOG

But still does not give the goods at a discount.
https://www.screencast.com/t/SpOkYYG5M88
https://www.screencast.com/t/kNSSYKMKjRiT

**Comment by Floydtm** [comment]
It is strange that this does not work for you. You can contact our support team and provide access to the site. Perhaps I missed something or our sites are configured differently. Thanks you!

**Comment by serg-pervushin** [comment]
Thank you, I understand. A friend of mine activated the license on the site, but I do not have access to my personal account and support. Do I need to solve this through him?

**Comment by Floydtm** [comment]
Probably yes. Support needs to verify your license

**Comment by petranca** [comment]
but this is not working with variations!

**Comment by serg-pervushin** [comment]
Yes, this is probably the case, I have variable products.

**Comment by Floydtm** [comment]
Guys, this doesn't work with variable products due to the fact that each variation has its own unique key. You can add a separate meta field to the products and mark the products for sale.

**Comment by petranca** [comment]
@Floydtm Yes this is already arrived. But the origin of this post assumed that there should be an option in JetSmartFilter that supports this natively.

If widgets already make it possible to display products with variations on sale, it should not be so complex to create such a "fixed" filter. Or maybe I'm wrong?

Certain sales are scheduled. I cannot expect that the customer has to make a separate note in a calendar for  products  where he has to deactivate the custom metabox "on sale" again.

Such a filter should  be included in an online shop.

**Comment by Floydtm** [comment]
We are actually thinking about it. However, you should understand that we cannot guarantee this yet.

**Comment by PSBV** [comment]
Why is this issue closed ? Solution NOT yet available... Essential in my opinion! Hopping to ear from you soon. ;)

**Comment by WebTechPT** [comment]
Hi @Floydtm any Update? I need this solution to my clients...

**Comment by Marcoqwerty78** [comment]
Please fix this! Variations products on sale must be fixed!

**Comment by JaxxOlly** [comment]
I have created a fix and solution for this problem, use jet engine and create a SQL query for the below:

`SELECT DISTINCT p.ID, p.post_title
FROM {prefix}posts p
-- Join term tables to confirm it's a variable product
INNER JOIN {prefix}term_relationships tr ON p.ID = tr.object_id
INNER JOIN {prefix}term_taxonomy tt ON tr.term_taxonomy_id = tt.term_taxonomy_id
INNER JOIN {prefix}terms t ON tt.term_id = t.term_id
-- Join stock and price on parent (optional if needed)
INNER JOIN {prefix}postmeta pm_stock ON p.ID = pm_stock.post_id AND pm_stock.meta_key = '_stock_status' AND pm_stock.meta_value = 'instock'
-- Join to variations
INNER JOIN {prefix}posts v ON v.post_parent = p.ID AND v.post_type = 'product_variation' AND v.post_status = 'publish'
-- Variation must have sale price
INNER JOIN {prefix}postmeta v_sale ON v.ID = v_sale.post_id AND v_sale.meta_key = '_sale_price' AND CAST(v_sale.meta_value AS DECIMAL) > 0
-- Variation must have a regular price too
INNER JOIN {prefix}postmeta v_regular ON v.ID = v_regular.post_id AND v_regular.meta_key = '_regular_price' AND CAST(v_regular.meta_value AS DECIMAL) > CAST(v_sale.meta_value AS DECIMAL)
WHERE p.post_type = 'product'
  AND p.post_status = 'publish'
  AND tt.taxonomy = 'product_type'
  AND t.slug = 'variable';
`
