### ISSUE TITLE
More badges to show on product than just sale

### ISSUE THREAD

**Issue by Magn2871** [CrocoBlock/suggestions#2812]
Hi Guys

As seen on a lot of other e-commerce shops then you have the option to add multiple badges to your products. For an example you could a badge saying "most popular" "best Seller" "2 for 1 price" and stuff like that.

I think that this is very needed and would help your users to increase their conversion rates on these specific products.

**Comment by UraraReika** [comment]
I merged this issue with #2680, which is on the same subject so we could deal with it more efficiently.
