### ISSUE TITLE
JetProductGallery for Elementor version 1.2.2 make my product image disappear.

### ISSUE THREAD

**Issue by msulaimanmisri** [CrocoBlock/suggestions#2815]
**Describe the bug**
So I update the plugin to version 1.2.2. Right after I update, the image (Gallery Slider) disappear. However if I insert again the widget, the new one appear. But I need to re-do back all the custom styling.

**Expected behavior**
When we update the version, the old widget should not disappear. If the widget set as legacy or not compatible with Elementor version, should notify user.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Brave, Mozilla Firefox

**Comment by UraraReika** [comment]
Hello @msulaimanmisri !
Release 1.2.2  contains only some minor fixes and can effect site like this. Please contact our support team so we can take closer look.

**Comment by msulaimanmisri** [comment]
I see. Okay then. Thank you 👍🏼
