### ISSUE TITLE
Dynamic visibility for Wishlist Count Button widget and Compare Count Button widget

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [CrocoBlock/suggestions#2818]
Unfortunately I can't find the metafield name or JS data to use the value for making visibility of the wishlist count and compare count widgets dynamicaly.
Could you please give instructions or implement the abiliy to hide widget if count = 0.

**Comment by UraraReika** [comment]
Hello @Morgunov-Vitaly !

You can use this [plugin](https://github.com/UraraReika/jet-engine-custom-visibility-conditions) to add extra Dynamic Visibility options.

**Comment by UraraReika** [comment]
Controls for hide empty counter will be added in feature release.
