### ISSUE TITLE
JetEngine Listing Grid Slider - improvements and suggestions

### ISSUE THREAD

**Issue by Crocoblock** [Crocoblock/suggestions#282]
1. An easier way to use the slider option on mobile devices. Now it takes much effort to go to the next slide (especially on mobile). It "sticks" to its place. 

2. More styling options to the arrow icon, the ability to change the border radius of the background of the arrow icon.

3. An ability to display a part of the next slide (now we can only display full slides). 

The original request [here.](https://www.facebook.com/groups/CrocoblockCommunity/permalink/2455922434499163/)

**Comment by KoenVanO** [comment]
Hi! Any idea when this will be fixed? Thank you!

**Comment by ludertal** [comment]
Feature requests

1. choose direction for slider animation LTR or RTL
2. option "don't stop animation on hover" on slider

**Comment by ludertal** [comment]
One year without any reply or comment, is it so difficult to add those "must have" options ?

Feature requests

- option "don't stop animation on hover" on slider
- choose direction for slider animation LTR or RTL

**Comment by VenkmanNL** [comment]
+1

I would also like to be able to have the option "don't stop animation on over"

**Comment by PabloLombriz** [comment]
me too, would like to be able to have the option "don't stop animation on over"

**Comment by petrovui** [comment]
- Slick Centered mode to Listing Grid Slider Mode. Like in Advanced Carousel.
- Listing Grid next/prev buttons widgets, to place slider buttons anywhere without jquery coding.

**Comment by w3dzign** [comment]
yes the  Centered mode like advanced carousel could be like 1 listing item and a piece only and see one item in the front and small piece in the right without arrows

**Comment by raroDev** [comment]
I really miss center mode :( Any chance for that in 2021 @Floydtm?

**Comment by donvanbaar** [comment]
Also waiting for a possibility to disable 'stop slider on mouse hover' option! Any idea on when this will be implemented?

**Comment by dennylai1990** [comment]
+1 for Center mode. Would also be great if we can change the number of post per device to better optimise for mobile devices.

**Comment by petrovui** [comment]
Still waiting fo Center Mode in Listing Grid Slider!!!

**Comment by bombarda-rpd** [comment]
What about the possibility to upload your own icon?

**Comment by DevDietheR** [comment]
Up

**Comment by heikodietze** [comment]
I would also like to be able to have the option "don't stop animation on over"

**Comment by milesdeelite** [comment]
+1 for the original offset feature idea (values like 1.2), to get a better idea that more slides are available on mobile.
Isn't slick slider deprecated by now? Last commit was 27 Nov 2019.
swiperJS would be a much better fit.

**Comment by pgirzalsky** [comment]
@Crocoblock Please consider what @milesdeelite wrote.
Slick is deprecated and should be replaced by swiper which is much more performant, customizable and modern. 
Also, the option to have a custom slidesToShow number like 1.2 etc. is crucial for me in so many projects already!

**Comment by bortraws** [comment]
The slider option doesn't work when a grid of alternative Listing items is used. The created grid falls apart as soon as the Slider option is turned on. Each item is then automatically placed on its own row instead of sliding the grid as a whole. See this issue for details: #6079

**Comment by v-nahornyi** [comment]
@Crocoblock @MjHead It's still crucial to have float number of slides implemented, thank you

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140

**Comment by veniromediasolutions** [comment]
Hi! Is it possible to get a linear slider speed? We want a constant slider speed to appear on all of the items.
