### ISSUE TITLE
JetProductGallery - Add image_link and additional_image_link attributes to comply with Google Merchant Center guidelines

### ISSUE THREAD

**Issue by tiago-123** [CrocoBlock/suggestions#2820]
Hello,

I am facing an issue trying to add my products to Google Merchant Center. The issue is that Googlebot is not being able to crawl the product images. I have contacted Google Support and they told me that my images do not contain appropriate image_link and additional_image_link attributes, as described in this topic: https://support.google.com/merchants/answer/6240184?hl=en

Since I'm using the JetProductGallery plugin, I imagine that the issue might be caused by the way the plugin is generating the HTML code for the images.
Can anyone help?

Best regards,
Tiago.

**Comment by UraraReika** [comment]
Hello @tiago-123 !

Tell us please this attribute additional_image_link added by some plugin? Although you can easily override images template and put needed attribute.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
