### ISSUE TITLE
[JETENGINE - data store] - public favorite list of specific users

### ISSUE THREAD

**Issue by saltkinmedia** [CrocoBlock/suggestions#2822]
Add the possibility of showing the data stores of a user on their user profile page.
Example: Visiting the user profile page, a visitor could see what articles that user added to his favorites lists

**Comment by GerardoZenteno** [comment]
+1

**Comment by naturalweb-business** [comment]
+1
And i add this:

The possibility to show the posts (products) in the Data Store added of one user to all users, i mean, implement that the users create a list of products and that it be public, then another users would can see that list and buy one of this products.

**Comment by MjHead** [comment]
https://github.com/MjHead/jet-engine-public-user-meta-stores - from now you can do this with the addon. It works only with User Meta stores. It adds Dynamic tags and Macros to get User Store contents by selected user context - for current user, for current post author or for currently queried user from Profile Builder. You can use the last context to show listings of posts from users data stores on their profile pages

**Comment by giacozama** [comment]
the addon works but right after activation suggests updating it. Updates results in an error that deletes the addon
