### ISSUE TITLE
JetWooBuilder / Smart Filter - Result count doesn't update With Ajax

### ISSUE THREAD

**Issue by ivntrdata** [CrocoBlock/suggestions#2824]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UraraReika** [comment]
I merged this issue with #2592, which is on the same subject so we could deal with it more efficiently.
