### ISSUE TITLE
I suggest you to make the currency format feature in the jet engine plugin form section or in the jet form plugin

### ISSUE THREAD

**Issue by zuhdi-in** [Crocoblock/suggestions#2827]
so I am making the total price on jetform with element calculate, but the calculation results are only numbers without using any format, so that the results match the currency format, how do I change it? the format I want is that every 3 digits has a dot after it, example : Rp 2000000 => Rp 2.000.000

**Comment by UraraReika** [comment]
This functionality already released in JetFormBuilder plugin. You can fell free to check it out.
