### ISSUE TITLE
JetMenu: Can you make Menu Items have "drop" effect rather than slide effect

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#2836]
Hey with JetMenu when you click a "category" in the menu, it has a slide effect it switches sides.
Would it be possible to make a collapse/fall effect where the menu falls down? and goes up again?

https://prnt.sc/10pcxtn

**Comment by Medienor** [comment]
https://prnt.sc/10pcl7l

**Comment by Floydtm** [comment]
Hi, these settings are there right now https://prnt.sc/10t91k2 https://prnt.sc/10t91z0
