### ISSUE TITLE
Please add link attributes (open in new window) for JetWooBuilder linked items

### ISSUE THREAD

**Issue by ingramleedy** [CrocoBlock/suggestions#2837]
Please add link attributes (open in new window) for JetWooBuilder linked items, Add To cart button, Read More, Image Links, Title Links. anything that has a link attribute.

The use case here, is that since the JetSmartFilter Ajax resets when viewing a product page and clicking back to the search, the search resets.   Another option would be to have all the links on the archive page open a new window for each product.

**Comment by 79ho3ein** [comment]
Does this feature mean the opposite image?  https://prnt.sc/12l1pix

**Comment by UraraReika** [comment]
@79ho3ein yes
