### ISSUE TITLE
Elementor popup template content cannot be loaded by JetEngine listing

### ISSUE THREAD

**Issue by kbcelik** [CrocoBlock/suggestions#2847]
**Describe the bug**
Media files do not attach in Telementor Popups for JetEngine CPTs

**To Reproduce**

1. Create custom post type and set youtube video link with custom field
2. Create a Popup and embed the youtube video dynamically
3. Create JetEngine Listing (add popup button) for CPT 
4. Create custom post listing page via jetengine listing in posts

**Result**
When listing page, click the popup button, popup content not loaded.

**Expected behavior**
The video appears in the popup

**Screenshots**
https://imgur.com/a/pqFYJOt

**Comment by Floydtm** [comment]
This will not work with the elementor popup. You can use JetPopup to display dynamic content. Thanks you!

**Comment by kbcelik** [comment]
is this new? it was working this way before.
