### ISSUE TITLE
Add an option for differentiated prices for weekend or on/off season 

### ISSUE THREAD

**Issue by MHub2021** [CrocoBlock/suggestions#2870]
Please add an option for differentiated prices for weekend or on/off season for Hotel booking Dynamic templates or Crocoblock plugins beacause I think is a really important feature for a Hotel booking website.

**Comment by jannelundin** [comment]
I have to Agree, a bokning website without seasonal
Price are nearly uselts. I think this must bee a priority.

**Comment by jurijboni** [comment]
I agree, I have designed some B&B websites and for this reason I have not used crocoblock. This is a key feature for a booking plugin.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.4.0 version. You can fell free to check it out.

Thank you!
