### ISSUE TITLE
Jetengine repeater quality and bug

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#2872]
It seems that you have better repeater in glossary than repeater field itself which bug and it is unusable in addition to the lag. 
it is not normal

![glossaire repeater](https://user-images.githubusercontent.com/75816572/112493944-2024c180-8d72-11eb-9cb6-9c7f6801e164.gif)

**Actual jetengine repeater field** 
![jet repeater](https://user-images.githubusercontent.com/75816572/112494527-a7723500-8d72-11eb-9671-3a141f0df7ac.gif)

The idea is to quickly correct this, unify the repeater and improve it  to allow us a horizontal inline alignment (like acf) 
actual jetengine repeater takes up too much space.

![acf repeater](https://user-images.githubusercontent.com/75816572/112494442-91fd0b00-8d72-11eb-8487-c05f818ef063.gif)

I'm really worried if anyone reads me. these details nobody mentions them...

**Comment by nreljed** [comment]
#3514

**Comment by kaskad88** [comment]
Added in JetEngine 2.10.2 https://prnt.sc/20xamn3
