### ISSUE TITLE
Calculate service in booking form.

### ISSUE THREAD

**Issue by Alks** [CrocoBlock/suggestions#2883]
How to calculate service in booking form.. I mean, if some hotels provide different services, it is possible to be calculated in booking for, if they are checked from customer?
Now in booking form have service but they not adding in listings...

#28722 How to calculate service in booking form.

**Comment by jannelundin** [comment]
This is not automatic you need to add a few calculating fields where you put your data.
<img width="605" alt="Skärmavbild 2021-03-31 kl  15 19 59" src="https://user-images.githubusercontent.com/65285087/113151840-ca4e8e80-9235-11eb-8fd6-fbb0e952ce66.png">
<img width="535" alt="Skärmavbild 2021-03-31 kl  15 18 54" src="https://user-images.githubusercontent.com/65285087/113151850-cc185200-9235-11eb-92c0-1384ef7ed37f.png">

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/jetbooking-how-to-set-automatic-price-calculator/ https://crocoblock.com/knowledge-base/articles/how-to-use-hidden-and-calculated-field-types-to-create-formulas-based-on-the-values-from-the-booking-form-fields/#title2 https://crocoblock.com/knowledge-base/articles/jetformbuilder-how-to-combine-hidden-and-repeater-fields-with-the-calculated-field/ https://crocoblock.com/knowledge-base/articles/jetformbuilder-form-fields-overview/#title6
