### ISSUE TITLE
Vertical Timeline Horizontal Alignment Line Broken

### ISSUE THREAD

**Issue by MikeLikesThat** [CrocoBlock/suggestions#2885]
When changing the layout to Left or Right Horizontal Alignment the Line becomes aligned to the wrong side.

1. Insert Vertical Timeline into a section
2. Under Content-Layout-Horizontal Alignment-Select Left or Right

**Expected behavior**
![right-correct](https://user-images.githubusercontent.com/81569362/112879298-f4b61580-9096-11eb-9a86-dcf895e2fbc5.JPG)

**Wrong behavior**
![right-wrong](https://user-images.githubusercontent.com/81569362/112879388-10b9b700-9097-11eb-8c30-ec26a6655372.JPG)

Desktop:
 - OS: Windows 10
 - Browser: Chrome
 - Version 89.0.4389.90

**Comment by Floydtm** [comment]
Hi! We will fix this in the next updates. Thanks you!
