### ISSUE TITLE
Can you please add feature of custom post Comparison in Jet Compare & Wishlist Plugin?

### ISSUE THREAD

**Issue by AneeqAkram59** [CrocoBlock/suggestions#2891]
**i want to request to you guys that enable a feature of custom post comparison without WooCommerce in the "Jet Compare and Wishlist plugin" **

By adding this feature costumers like me will be able to compare room or flat for hotel booking sites, or the sites that are working without WooCommerce. you guys done this before on Jet Smart filter, where we can filter woocommerece products and filter the WordPress post too.

**As like [this plugin](http://preview.codecanyon.net/item/alike-any-post-comparison-wordpress/full_screen_preview/15538788?_ga=2.265413516.268365425.1617168879-1714505372.1615266071) is doing, but I'm not happy with that because of its low option to control comparison system **

I think you guys can do that by focusing on post's meta boxes, As like this Plugin is doing that ([Screenshot](https://www.screencast.com/t/jiJzzOHYxAY).

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

We recommend to use Data Store functionality from JetEngine plugin.

Thank you for your understanding.
