### ISSUE TITLE
Jetengine form: double opt-in and send data stored list via e-mail

### ISSUE THREAD

**Issue by Crazy-Psychokitty** [CrocoBlock/suggestions#2892]
Hello everyone,

**Double opt-in:** 

I would like to see a double opt-in solution for jetengine form.

I´m from Germany and because of the DSVGO / GDPR issue we often need double opt-in possibilities in forms. (Double opt-in means that a user sends a request with private data and before this e-mail is seen bei the client, the user has to confirm via a second e-mail with a confirmation link, that his request is serious. similar to a newsletter system)

**Send favouritet list created with data store via order form**

It would be nice if the user can send his favourite list via form to the client. 

In my case, I´m building a product catalogue without woocommerce because its slowing down my performance. In the product catalogue the user can fill out an order form if they ´re interested in a single product. For orders with multiple products, I´m searching for a solution to build some kind of cart page with the help of data store. 

The user can put his products in his favourite list and this list can be mailed to the client.

It would be great if those features would be possible.

In kind regards

**Comment by dantetesta** [comment]
Create a function to send data stores to email or send that information to a post type ...

The idea is to make a Fake ShopCart to request quotes ... but it is very important that there is a field to define the quantity of items added to this fake cart!

**Comment by Crazy-Psychokitty** [comment]
That´s true

would the quantity part be a feature in the future?

**Comment by mcj777** [comment]
+1

**Comment by alexanderpankart** [comment]
#2473

**Comment by girafffee** [comment]
Follow this issue https://github.com/Crocoblock/suggestions/issues/2473
