### ISSUE TITLE
JetEngine Listing Grid: post query for posts with same taxonomies

### ISSUE THREAD

**Issue by Stiwano** [CrocoBlock/suggestions#290]
Very much needed to realize something like „similar products" as often used in shops. The query should be able to look for posts with the same taxonomies. I.E. if I have a post type "photo courses“ with a category "course categories" with taxonomies like "landscape“ "portrait“ "black and white". The query should show all courses that share the same taxonomies. At the moment I need to fill in the taxonomies id or slug, but this should be dynamical.

**Comment by Floydtm** [comment]
@Stiwano Hi, please check this tutorial https://documentation.zemez.io/wordpress/index.php?project=jetengine&lang=en&section=jetengine-layouts http://prntscr.com/nv95xn

**Comment by Stiwano** [comment]
Please read my note attentive. I'm already working a lot with JetEngine and I know quite well about the basics you refer to. But it is not possible to show posts that share the same taxonomies dynamically. Only if I fill in the id of the taxonomy or the slug. See again, I have:
Foto courses (post type) –> course categories (category) –> Taxonomies (landscape, portrait, black and white … ) It is possible to show all the post that have a course category but not the ones that share one or many of the taxonomies of the current post. 
![Bildschirmfoto 2019-05-29 um 13 34 06](https://user-images.githubusercontent.com/4234807/58618184-3f5f7e80-82c2-11e9-995d-5b093dfc8cb1.png)
![Bildschirmfoto 2019-05-29 um 13 41 50](https://user-images.githubusercontent.com/4234807/58618190-438b9c00-82c2-11e9-867c-39b43dd07fc4.png)

**Comment by MjHead** [comment]
@Stiwano please try to use %current_terms|taxonomy-slug% macros

**Comment by Stiwano** [comment]
Of course, I already use these macros because I have no other choice. So no interest in my suggestion for improvement?

**Comment by MjHead** [comment]
Sorry, but as I understand the main point of your suggestion is allow to dynamically select posts with the same terms of some taxonomy as for parent post. This macros was done exactly for such cases. If you mean we should add a separate control (like switcher or dropdown or etc.) - I think its not the best choice - this control will do the same as macros on back-end. At this moment controls for querying posts so close as possible for native WP_Query arguments. So any additional controls will just be a combination of existing ones at back-end. So we prefer to implement any custom functionality for posts query with macros and add controls only for things which couldn't be done with macros.

**Comment by Stiwano** [comment]
That's not the point. If there is a Macro that would do what I want please tell me wich. It would need to say: "Show posts that have the same taxonomies". Then I'm lucky.

**Comment by MjHead** [comment]
I agree that we need to improve documentation about macros and maybe add macros suggestions to input fields where particular macros can be used. But its not the same as add separate control to such specific things.

**Comment by Stiwano** [comment]
I never spoke of any separate controls. I just want to get this working as described. And at the moment there is no Macro, as far as I know, doing that. Why does nobody see this? English is not my mother language, but do I explain so bad, that it is not possible to see the point I make?

**Comment by MjHead** [comment]
Sorry maybe not clearly understand your previous messages. Here is an example of functionality you want. 

I have Courses post type and Course Tags taxonomy. I created courses listing to show it as related on single course page. You need to do something like this - http://prntscr.com/nvrpy6, where:
- select Tax Query as Posts Query type
- select required tax in `Taxonomy` field
- add macros %current_terms|course_tags% into `Terms` field, where 'course_tags' you need to replace with a **slug** of your taxonomy

**Comment by MjHead** [comment]
Also to make sure you current post not appears in Related Posts you need to exclude it in Posts Query settings, just add new item with such config - http://prntscr.com/nvrtvg

**Comment by Stiwano** [comment]
Great! Thank you so much. I apologize because you told me before and I didn't understand right. Now I got it.

**Comment by Stiwano** [comment]
A better Documentation for Macros would be helpful. :)

**Comment by fvenuto** [comment]
+1 for better macros documentation.
Using the link: https://crocoblock.com/knowledge-base/articles/jetengine-macros-guide/
i was unable to know that i can use: %current_terms|taxonomy-slug%

**Comment by ankit551** [comment]
Add %queried_term% inside terms field and field should be term id under operator in
![image](https://user-images.githubusercontent.com/16338188/130654327-583cde0b-7404-49e2-96e8-9f6099aebc06.png)

**Comment by natequreshi** [comment]
can we use custom fields where we mention terms and it shows accordingly.

I created a custom post which show some industry information here I want to show posts which have tags from default wp posts.

what macro should I use like show posts if they have tags are food-beverages..
