### ISSUE TITLE
JetReviews: Hide Gravatar (Image next to review)

### ISSUE THREAD

**Issue by Didier-F** [CrocoBlock/suggestions#2900]
**Please, describe the feature request, making it clear to understand.**
I like a function at the JetReviews to hide the image (gravatar) next to a review.

<img width="239" alt="Schermafbeelding 2021-04-01 om 10 01 23" src="https://user-images.githubusercontent.com/79250701/113262728-38945f00-92d1-11eb-92e9-f34cc700de91.png">

**Comment by shinTM** [comment]
done v 2.2.0
