### ISSUE TITLE
JetReviews: Change the order of the entry fields for a review

### ISSUE THREAD

**Issue by Didier-F** [CrocoBlock/suggestions#2901]
When you write a new review, you can fill in a number of fields. It would make more sense if the order were:

1. Number of stars
2. Title of review
3. The review itself

<img width="639" alt="Schermafbeelding 2021-04-01 om 10 35 34" src="https://user-images.githubusercontent.com/79250701/113266835-ff122280-92d5-11eb-851b-66a890d05c20.png">

**Comment by shinTM** [comment]
you can use custom css for this, in particular order property https://developer.mozilla.org/ru/docs/Web/CSS/order
