### ISSUE TITLE
Switcher Tab: 3 Options Instead of Just 2

### ISSUE THREAD

**Issue by SovereignService** [CrocoBlock/suggestions#2907]
Hello, right now the "Switcher" widget is working wonderfully on my site - thank you for this awesome plugin.

It only allows 2 and it would be amazing if it allowed 3 options (or more)

So in this example:
 - Allies would be #1
 - Mentors #2
 - And then a new item for #3 

<img width="230" alt="Screen Shot 2021-04-02 at 10 10 15 AM" src="https://user-images.githubusercontent.com/81793861/113437751-11569400-939c-11eb-833c-62206465836a.png">

**Comment by Floydtm** [comment]
You can use tabs for this. Thanks you!
