### ISSUE TITLE
Dropbar, Make a standard Wordpress editor

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2910]
Hello, please make a standard Wordpress editor here https://prnt.sc/113w48x so that you can do text formatting without the need for HTML knowledge.

/*Оригинал*/
Здравствуйте, сделайте пожалуйста тут https://prnt.sc/113w48x стандартный редактор Wordpress, чтобы была возможность делать форматирование текста, без необходимости знаний HTML.

**Comment by kaskad88** [comment]
Added in JetElements v2.5.6
