### ISSUE TITLE
Show appointment and booking available dates for Jetengine Calendar Widget Source

### ISSUE THREAD

**Issue by ayhanmalkoc** [CrocoBlock/suggestions#2912]
To the calendar widget source "date field name" jetappointment
 Add available date and time support so you can list your services.

Thus, with the "jetengine calendar", we can show a calendar according to the dates of the cpt services linked to booking and appointments. please discuss this.

**Comment by UraraReika** [comment]
Hello @ayhanmalkoc. Thanks for the feedback.

 Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. 

Thank you for your understanding.

**Comment by UraraReika** [comment]
We’ve not heard back from you in a while, so I’m marking this thread as resolved. Hopefully, you were able to find a solution to your problem! If you have further questions, please feel free to open a new topic.
