### ISSUE TITLE
Add Is required option for all fields of Post Type Metabox and Metabox

### ISSUE THREAD

**Issue by ayhanmalkoc** [CrocoBlock/suggestions#2914]
Add Is required option for all fields of Post Type Metabox

Gallery
Number
Repeater
etc.

**Comment by kochhase** [comment]
+1

**Comment by raabmar** [comment]
Absolutely necessary, just started with JetEngine yesterday, and on day one I miss this already. It does work with some fields, but not all - e.g. checkbox, radio, etc.

**Comment by kaskad88** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1834, which is on the same subject so we could deal with it more efficiently.
