### ISSUE TITLE
Place holder ("username" and "password") for the login widget in jet_bocks

### ISSUE THREAD

**Issue by Xrilion** [CrocoBlock/suggestions#2916]
**Hello Team,**

I requesting a rather important visual cue on the login widget of the jet-blocks plugin.

As we know the "Register" and "Login" widgets in the jet-blocks plugin go hand in hand. That being said the "Register" one has options to enable and disable both Labels and Placeholders, while on the other hand on the "Login" widget you will find only Labels and no placeholders. Why?

As you can imagine this forces web owners to avoid the placeholder option at all since having that design route on the register and not on the login page is not a good design flow for users. Why would you disable them for the login if you have them on the register, it's a bit confusing. So have the option on both so people can choose either place holder option for both (register and login) - which is what I want, or a Label option for both (which exists already).

So to be clear the feature request is: "add a Placeholder toggle option for the Login widget in Jet_Blocks". 

See screenshots below.

[http://prnt.sc/114l9yb](url)

**Comment by Xrilion** [comment]
If you can't preview the screen shot, you may view it here.

![444](https://user-images.githubusercontent.com/81950329/113986896-6159ae80-9813-11eb-98d7-2e1fcc3cf846.jpg)

**Comment by kaskad88** [comment]
Added to the JetBlocks 1.2.9
