### ISSUE TITLE
Forgot Password Page JetWooBuilder Customize

### ISSUE THREAD

**Issue by xC4M** [CrocoBlock/suggestions#2918]
Hi team!!

I'd like to give you'all some suggestions that should be added in the JetWooBuilder.

JetWooBuilder is a great plugin to customize every important part of Woocommerce pages, but there's missing something that is very important... and that's the Forgot Password Page. When you click on the forgot password's link, i takes you to the page, but most of the time it isn't customized as you whole website design using JetWooBuilder; in the other case, the Forgot Password Page is displayed without margins or behind the Nav menu, and those things. Also, it's hard to change the text above "Username or email" field in the forgot password page.

The point is that would be great having the opportunity to customize that special page using JetWooBuilder, and it'd be, obviously, integrated with JetEgine Forms to modify the message that the user is going to receive.

**Comment by Lonsdale201** [comment]
+1

**Comment by computerfreak84** [comment]
+1
please make this a priority!
customer account endpoint template for forgot password or something more complete for the whole login-register-forgot procedure for WooCommerce and other projects with user logins. I don't want my customers to see wordpress login forms.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/2721, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
