### ISSUE TITLE
JetProduct Gallery - Additional Variation Images suggestion

### ISSUE THREAD

**Issue by xC4M** [CrocoBlock/suggestions#2919]
Hey there!

JetProduct Gallery plugin works fine when it's focusing on one gallery of product. I meant... If I have a product, and this product has some colors as a variation, Woocommerce let me add a picture to identify each variation, and also let me add a Product Gallery, but it is a product general gallery, It doesn't matter the images variation.

There are some plugins that let me add, for example, two or more additional pictures to each variation (it should be a variation gallery), and when I select a Variation, it shows me the picture and the others additional picture form the variation that I selected, that should be the right way. But JetProduct Gallery doesn't work like that, it doesn't support those kinds of things.

Crocoblock should add an Additional Images Variation support, it should be from third party plugins, or you include it in an incoming  update, because I would like that users could watch a gallery from the variation selected and not the general product gallery.

**Comment by lifeact** [comment]
+1

**Comment by BioJimmy** [comment]
Totally agree! If you don't support multiple product variation images yourself, PLEASE provide a solution to make it work with other plugins (e.g. Additional Variation Images Gallery for WC (by Emran Ahmed)

**Comment by UraraReika** [comment]
I merged this issue with #2619, which is on the same subject so we could deal with it more efficiently.
