### ISSUE TITLE
JetSmartFilters: Best New Improvement

### ISSUE THREAD

**Issue by uleadaniel** [Crocoblock/suggestions#292]
Hi, i suggest you to add at the Filter Settings -> Select, the option to select full pages, or templates made with Elementor, so us, user to can make something like Apple compare pages: https://www.apple.com/ipad/compare/

Thank you for the great work. Hope you'll implement this soon.

**Comment by Floydtm** [comment]
I think it can be implemented with current versions of plugengs jetengine and jetsmartfilters
