### ISSUE TITLE
JetEngine : Woocommerce Product Grid including Global/Custom Attributes 

### ISSUE THREAD

**Issue by meisterx2020** [CrocoBlock/suggestions#2921]
I use JetEngine, Woocommerce and Gutenberg (not Elementor).
I want to create Woocommerce Product grid including Global/Custom Attributes. 
I create Listing Item at first.
How can I display a product global/custom attribute (generally color, size etc.) in the Listing Item?
I tried Dynamic Field Block, but I can't find how to display attributes.

**Comment by Floydtm** [comment]
Most likely you will have problems with this, but you can customize something. In the dynamic field, you need to specify the required meta keys, like this https://prnt.sc/115npxa https://prnt.sc/115nq7q

**Comment by meisterx2020** [comment]
When I set "attribute_pa_color", it doesn't work.
When I set "_product_attributes" in that field, the error occured.
https://prnt.sc/115rlb0

I switched on "Filter field output" toggle , but the "Get child value" callback doesn't exist.
