### ISSUE TITLE
Full edit of the payment form with the jet woobuilder plugin on the payment slip.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2925]
Please add the ability to completely edit the payment field, such as deleting, making the payment field necessary or unnecessary, to the Jet Woo Builder plugin. Like the woolentor plugin that has this feature.
(Also the ability to edit the city and province field)

This feature can make jet woobuilder more attractive. Because you will no longer need to install an additional plugin to edit the payment field.

thanks

**Comment by UraraReika** [comment]
I merged this issue with #2721, which is on the same subject so we could deal with it more efficiently.
