### ISSUE TITLE
Change the style of the product number of inputs to the shopping cart button

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2926]
Please update the style of the number of product inputs on the single product page.
In the current mode, the number of products with the up and down arrows increases and decreases.
While in the updated design, the value is increased and decreased with the + and - buttons.

This feature can make jetwoobuilder very attractive and wonderful. Please add it soon.

thanks

**Comment by UraraReika** [comment]
I merged this issue with #2711, which is on the same subject so we could deal with it more efficiently.
