### ISSUE TITLE
Change quantity on product archive page

### ISSUE THREAD

**Issue by sonnesworld** [CrocoBlock/suggestions#2929]
Hi, it would be great if it's possible to change quantity on product archive page. It's annoying for customers to visit the product (detail) page to add more then one of the same product to cart. Many thanks.

<img width="737" alt="Product-quantity-archive-page" src="https://user-images.githubusercontent.com/57396134/113755360-86192d80-9710-11eb-9a5e-620f03646b60.png">

**Comment by UraraReika** [comment]
I merged this issue with #2711, which is on the same subject so we could deal with it more efficiently.
