### ISSUE TITLE
JetEngine dynamic bug

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#293]
If Excerpt is empty, WordPress automatically creates an excerpt using the first 55 words of the post. this does not work with the dynamic field http://prntscr.com/nvh0qh

**Comment by Biblothecaire** [comment]
I will create a post for the same !
+1 for me !

**Comment by Biblothecaire** [comment]
I see this ticket closed
I go test this
For me don't work ... Maybe i don't do good think ? Can you explain how i need to do ?
Thanks for your help

**Comment by Floydtm** [comment]
@Biblothecaire, please check if you have this option enabled http://prntscr.com/ovnsbh

**Comment by Biblothecaire** [comment]
I just test it, it work, thanks :D
