### ISSUE TITLE
Add feature to display Listing Results for Archive Pages

### ISSUE THREAD

**Issue by mertmutlu1998** [CrocoBlock/suggestions#2931]
With JetWooBuilder its possible to add Products Result Counter but its not possible to show the result counter on normal Archive Pages like for Car Listings. Would be a must have feature. Please add like here:

https://paste.pics/1eb9dda46288262263cbadb69c38c878

**Comment by Floydtm** [comment]
We are working on it. Keep for updates. Thank you!
