### ISSUE TITLE
Custom Fields in Jet Engine Display on Products Grid

### ISSUE THREAD

**Issue by Putitontheground** [CrocoBlock/suggestions#2932]
Hi Crocoblock Team,

Would it be possible to add the option of adding custom fields created in jetengine to display on the jetwoo products grid. In my case I am creating a bookshop ecommerce site. The book title and price are displayed but I would like to also show the name of the author of said book.

**Comment by stasonua0** [comment]
This can be done now by changing this setting https://prnt.sc/119n1kh

But for myself I concluded that even to create a product card, it is better to use Jet Engine

**Comment by Putitontheground** [comment]
I don't know what setting you have changed it to as I don't speak Russian.

**Comment by UraraReika** [comment]
Hello @Putitontheground !

You can use this [solution](https://github.com/UraraReika/jet-woo-builder-products-grid-custom-fields) in closest time will be added to [Crocoblock DevTools](https://crocoblock.com/freemium/tools/) .
