### ISSUE TITLE
Jet smart filter plugin paging widget vs. product grid widget plugin woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2933]
When we use the jet smart filter plugin paging widget for the jet woobuilder plugin products grid widget,If the number of pages is large, it first displays only page numbers 1 and 2,And when we click on number 2, the rest of the page numbers are displayed.

You can see the bug on this website : https://avangwebsite.ir/product-category/phone/

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein! Please contact our support team.
