### ISSUE TITLE
Request to add header shopping cart widget to jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2940]
The jet woobuilder plugin requires a menu cart, because the mentor cart itself is very simple.
This widget is really needed. Please add it to jet woobuilder.
please check it.

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein ! We have one in JetBlocks. Check this https://crocoblock.com/widgets/shopping-cart/.

**Comment by 79ho3ein** [comment]
Yes, it is in jet blocks, but the shopping cart belongs to the store builder and is required for jet woobuilder.For example, I now need the shopping cart menu. And it is not optimal to install an additional plugin for a widget.  I hope this widget will be added to jet woobuilder soon.Thank you for your responseSent from my Galaxy
-------- Original message --------From: Oleksandr Rudyi ***@***.***> Date: 08/04/2021  16:05  (GMT+03:30) To: Crocoblock/suggestions ***@***.***> Cc: 79ho3ein ***@***.***>, Mention ***@***.***> Subject: Re: [Crocoblock/suggestions] Request to add header shopping cart widget to jet woobuilder plugin (#2940) 
Hello @79ho3ein ! We have one in JetBlocks. Check this https://crocoblock.com/widgets/shopping-cart/.
