### ISSUE TITLE
Jet Woo Builder - Thank You Order Details options for Enable and Disable: Add link to title

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#2943]
Hi, My customer would like it to not be possible to access the product page by clicking on title.

![thank you page](https://user-images.githubusercontent.com/6773491/113940095-4ebf8500-97d3-11eb-81f7-6eb6db2be7d1.jpg)

**Comment by UraraReika** [comment]
Hello @tizum !
You can rewrite WooCommerce item template in which remove link functionality. This template https://github.com/woocommerce/woocommerce/blob/trunk/templates/order/order-details-item.php.
