### ISSUE TITLE
*Important -- Cart Usability and Flow for users. (JetWoo Builder)

### ISSUE THREAD

**Issue by Xrilion** [CrocoBlock/suggestions#2945]
**The number one thing that drives customers away from your site is speed lag and the "number of steps" it takes to reach your end goal: be it a purchase or a download.**

I'd like to request a rather genius idea for all "Digital Products" owners out there. And a good opportunity to stand out for Crocoblock. On the JetCW (Compare and Wishlist) plugin, there is a functionality to add a wish list button to the products grid on any place on the site. **When you add items to the wish list, that button you clicked turns into a tick. Click again on that tick and it removes the item from the wishlist and turns back to the Normal wish list button.**

__ This is very nice for users since they don't have to go to the wish list page, they can see right there which products they've added to the wish list and they can remove them without moving away from the page. VERY NICE UX! 

We wanted this same functionality for the cart as well! Since the cart button is baked in right into the "Products Grid" widget in Jetwoo Builder, you would only need to add the functionality in there as well. This way users can add items to the cart and remove them right from the grid area! - Everybody wins.

**Comment by Xrilion** [comment]
To let you see what the "added to wish" item looks like. Here is a SS.

**Comment by Xrilion** [comment]
![image](https://user-images.githubusercontent.com/81950329/113988689-556eec00-9815-11eb-8f8e-b411c35b3433.png)

**Comment by Xrilion** [comment]
We wanted that for the cart as well. 


By the way, I'd like to thank you the Crocoblock developers' team, for looking into this repository on Github. Very thoughtful.

**Comment by UraraReika** [comment]
Hello @Xrilion !

> When you add items to the wish list, that button you clicked turns into a tick. Click again on that tick and it removes the item from the wishlist and turns back to the Normal wish list button.

https://prnt.sc/117c503 we added this long tie ago. You can enable it here https://prnt.sc/117c6cv for example.

As for cart remove functionality we will not add this like this. You can use cart widget from JetBlocks plugin and after adding product to cart remove it from widget. Or you can use JetPopup plugin.  You can style the popup whatever you want and then https://prnt.sc/117bdbw use in with this option. This option control exist in every widget connected with add to cart functionality. So after you product added to cart popup comes and in it you can delete product.
