### ISSUE TITLE
Report 3 important "bugs" in jet smart filter plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2948]
The jet smart filters plugin has two bugs that should be fixed as soon as possible.  I will explain these bugs:

1- In the price range widget, sometimes the hold buttons do not move. And we have to click on the range to move.
While the holding buttons should move at the same time as moving the finger.Of course only on mobile.

2- When we use the jet smart filter paging widget for the poroduct grid widget of the jet woobuilder plugin, if the number of pages is large(More than 2 pages), it first displays only 2 page numbers.If page number 2 is clicked, the rest of the page numbers will be displayed.Otherwise, only 2 screens will be displayed. This is really bad.
You can see this problem on this website: avangwebsite.ir/product-category/phone/

3- The search field of this plugin has a severe bug in Safari browser.  In appearance

Please check.

Thanks

**Comment by Zaanone** [comment]
I can confirm the first bug is still active. On mobile, a lot of times the range circles won't move when I hold and drag them. Only clicking somewhere on the range filter moves the circles (which is highly inaccurate for precise filtering).

**Comment by Floydtm** [comment]
1 - we cannot reproduce the problem on our side. Please contact our support team. 2 - I can't see the problem on your site. 3 - Let's try to fix it for iOS
