### ISSUE TITLE
Jet Filter include/exclude

### ISSUE THREAD

**Issue by davidk82** [Crocoblock/suggestions#295]
Hi there,

for woocommerce-category-filters there should be an option in backend to define which categories should be included in filter. f.e. there could be seasonal categorys which should be hidden for a while. or categories to adress and inject google shopping products - but these categories cannot appear as a filter option. so there should be another option to include or exclude specific categories. (like in screenshot example)
![exclude](https://user-images.githubusercontent.com/9461795/58688366-831abc80-8384-11e9-95ad-1b8015dd02fb.PNG)

thanks
david

**Comment by Floydtm** [comment]
@davidk82, hi! this has been added to the plugin since version 1.4.0 http://prntscr.com/rhq7e0
