### ISSUE TITLE
JetSearch Feature Request

### ISSUE THREAD

**Issue by mertmutlu1998** [CrocoBlock/suggestions#2952]
Please add the feature to search for post id of a Custom Post. Would be very helpful.

**Comment by rentaterry** [comment]
+1
The situation is, I use Post ID for the unique item number. Without the feature, uses are not be able to find the items easily by just input the ID (unique item number)

**Comment by Crocoblock** [comment]
In JetSearch 3.5.0 was addedd hook 
```jet-search/ajax-search/search-by-post-id```

Please, try this
`add_filter( 'jet-search/ajax-search/search-by-post-id', '__return_true' );`
