### ISSUE TITLE
Bricks builder/theme and CrocoBlock plugins support

### ISSUE THREAD

**Issue by malygic** [CrocoBlock/suggestions#2955]
Hi. I was long time Elementor user and I liked to develop advanced sites with Crocoblock plugins. But now with new core web vitals update from Google I started look for new solutions how to build good-looking and fast websites with clean code.

Bricks theme / builder is one of the best options on the market, because it has similar interface like Elementor does, with great speed performance, sites on Bricks could get 90+ score on the mobile without any speed optimization.

In my opinion after Googles update many people will switch from Elementor to builders that are faster, and Bricks is one that makes this transition very easy for them, because people can create in it the same way as in Elementor.

It would be great if we can create with Crocoblock in Bricks!

**Comment by Lonsdale201** [comment]
Elementor every new updates including new performance boost. Elementor + Gutenberg and hope soon + Oxygen enough, and much. I think useless to make every new pagebuilder compatibility. Better the focus this segment.

**Comment by Silverlion009** [comment]
Please make Jetengine compatible with Bricks builder.

**Comment by cristianuibar** [comment]
Compatibility for Bricks would be great indeed. Please consider it.

**Comment by gsuez** [comment]
jet engine + jet smart filter

**Comment by Satal** [comment]
I'd definitely be interested in seeing this as well.

**Comment by tole011** [comment]
> Elementor every new updates including new performance boost. Elementor + Gutenberg and hope soon + Oxygen enough, and much. I think useless to make every new pagebuilder compatibility. Better the focus this segment.

Maybe you are right but look at Meta Box, ACF... Those are JetEngine competition. AFC is compatible out of box, and Meta Box CEO announced compatibility very soon. So...

**Comment by gem-design** [comment]
Yes please, it's a very well written plugin and Elementor isn't cutting it anymore (they pretend to improve performance by cutting a few bites of JS/DOM while TTFB keeps going up and up). Also day after day Gutenberg is starting to show that it is a deadend project. Oxygen is failing too, seems like they gave up on it. 
 
Bricks + JetEngine + (if possible) JetPopup = I'll move right away and willing to pay for another subscription for it.

**Comment by Saultejera** [comment]
Bricks is showing with each update that it is a serious project with a great future, and with the latest update, stable pages can be made with a certain complexity. I hope Crocoblock doesn't fall asleep and beat the competition. They must take advantage of the pull of the new visual constructors to position themselves as a reference. As @tole011 said, look at the movements of ACF and Meta Box.

**Comment by TRADEREXDE** [comment]
any comment from croco? Bricks is the newcomer

**Comment by Floydtm** [comment]
"Sorry, guys, but we are not planning to integrate with Oxygen as well as Bricks, Divi, Brizy, Beaver, or other website builders.
Why?
Our team still has limited capacity, so right now we need to choose.
Ether we integrate our product with all popular builders out there and support those integrations till we die )) or we dedicate all our time and effort to our primary builder - which is Elementor so far. This means that we`ll have more time to amaze you with the new features and other revolutionary stuff you all love so much."
https://www.facebook.com/groups/CrocoblockCommunity/posts/4533744080050311/
