### ISSUE TITLE
Product Grid Overrides The Woocommerce Image Ratio

### ISSUE THREAD

**Issue by Putitontheground** [CrocoBlock/suggestions#2959]
I've set up a product grid for a bookshop website, I want to keep the book images in a 2:3 ratio like this. (this example is from another site I made through squarespace). 

![Screenshot 2021-04-10 125707](https://user-images.githubusercontent.com/30221115/114253007-58780100-99fc-11eb-9936-50f5a096f1f5.jpg)

The images maintain their ratio but overflow to a container with a 2:3 ratio. The result is responsive and looks tidy in a grid.

When I set the woocommerce image ratio to the same for a product catalog it doesn't apply in the product grid and no amount of css changes anything. There are also very limited options to change how to display the images. I also can't crop the images because on the product page it shows the cropped result instead of the full image. 

![image](https://user-images.githubusercontent.com/30221115/114253218-69754200-99fd-11eb-8b0e-8e26da690eea.png)

Is there any way around this?

**Comment by Putitontheground** [comment]
The result of the un even grid can be see here on the shop page https://lamplightbooks.co.nz/shop/

**Comment by UraraReika** [comment]
Hello @Putitontheground !
Please contact our support team. Or in you case you just need to reupload you media images so them can be cropped to your theme sizes or use one of images crop plugin from the org.
