### ISSUE TITLE
A suggestion for the jet woobuilder plugin،Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2961]
hello

Please add an option that displays the desired text instead of the price if the product is not available.
Like call or non-existent.
This feature will be great for the product grid widget of this plugin.
Please check.

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein !

In Products Grid and Products List widgets we have such options https://prnt.sc/11afktz. So you can write whatever you want label for your products. If you although want hide price then in this case you can override price template.
