### ISSUE TITLE
Request: Ability to delete the text from the "add to cart" button

### ISSUE THREAD

**Issue by jurijboni** [CrocoBlock/suggestions#2963]
Sometimes it would be necessary to use the "add to cart" button as a simple icon. This cannot be done now because it is not possible to delete the "add to cart" text from the button.

**Comment by UraraReika** [comment]
Hello @jurijboni !

We have no plans in nearest future to add this functionality. Because it more complex task than its look like but you can use this solution https://docs.woocommerce.com/document/change-add-to-cart-button-text/.
