### ISSUE TITLE
Responsiveness in Jet Woo Gallery

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2965]
Здравствуйте, сделайте пожалуйста адаптивный выбор этой опции - https://prnt.sc/119invq . Спасибо.

/*Оригинал*/
Hello, please make the adaptive selection of this option - https://prnt.sc/119invq. Thank you.

**Comment by UraraReika** [comment]
Hello @stasonua0! 

This particular option has influence on other option controls and if it becomes responsive it will make some mess in editors controls panel. For this case we implement some filter hooks such as `jet-woo-product-gallery/slider/options` for main slider and `jet-woo-product-gallery/slider/thumb-options` for thumbnail slider. So you can use it like this:

```
add_filter('jet-woo-product-gallery/slider/options', 'additional_gallery_settings' );
add_filter('jet-woo-product-gallery/slider/thumb-options', 'additional_gallery_settings' );

function additional_gallery_settings( $options ) {

	if ( ! array_key_exists( 'breakpoints', $options ) ) {
		$options['breakpoints']  = [
			0    => [ 'direction' => 'vertical' ],
			768  => [ 'direction' => 'vertical' ],
			1025 => [ 'direction' => 'horizontal' ],
		];
	} else {
		$options['breakpoints'][0]['direction'] = 'vertical';
		$options['breakpoints'][768]['direction'] = 'vertical';
		$options['breakpoints'][1025]['direction'] = 'horizontal';
	}

	return $options;
}
```
