### ISSUE TITLE
Importing data into a csv / xls glossary

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2967]
Hello, consider importing data from csv / xls files into a glossary.
I have a task to add to the glossary all metro stations of one city, there are 236 of them, it would be great to import them from a csv or xls file, and not to drive in one by one manually.

/*Оригинал*/
Здравствуйте, рассмотрите возможность сделать импорт данных с файлов csv/xls в глоссарий.
У меня задача добавить в глоссарий все станции метро одного города, их 236 шт., было бы здорово импортировать их с файла csv или xls, а не вбивать по одному вручную.

**Comment by numanagit** [comment]
+1

**Comment by MjHead** [comment]
Will be added with JetEngine 2.9.0. More details here - https://github.com/Crocoblock/suggestions/issues/3803
