### ISSUE TITLE
Request a feature for the jet woobuilder plugin. Please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2968]
Please add a query of bestsellers to the home page as well.
Currently, bestsellers can only be used on a single product page.
Usually on sites, best-selling products are displayed on the main page. Not a single product page.

Please check.
thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein!

You can do it right now by setting options like this in Products Grid or Products List widgets https://prnt.sc/11bt8d0. This option setup works same like WooCommerce Best Sellers from JetElements. Which you can use too. In nearest update i think we will change option label for better understanding.
