### ISSUE TITLE
✨ JetEngine Feature Request: Colored & Filterable Backend Section

### ISSUE THREAD

**Issue by perks98** [CrocoBlock/suggestions#2969]
![image](https://user-images.githubusercontent.com/55829113/114406751-b264fc00-9b9f-11eb-9dfd-962b6ea2e826.png)

As a feature request if possible have the backend posts, be it custom or WordPress default like pages, be able to mark them with color and filter by color, category and other custom attributes. With color have posts in a hierarchy inherit that color unless specified otherwise or make it a slightly darker shade to indicate a child element.

The filtering at the moment, from what I've seen, is very static. E.g. added categories to Pages post type by I cannot filter by each category unless I create a dedicated page on the frontend as a feed, when I want these categories to be private.

I don't know, just spitballing, could be a bad idea. Any thoughts?

**Comment by perks98** [comment]
![Capture240](https://user-images.githubusercontent.com/55829113/114408642-88143e00-9ba1-11eb-94a6-349779672bdb.PNG)

UPDATE:
Just noticed on a site I'm editing that you do add classes to them. For instance in the image above I create a taxonomy called Page Purposes, so if I assign a page a Campaign category then with some backend CSS you can add a bit of color. It is possible to implement with what is there currently with the color side of the feature request. Maybe have a CSS injector option on certain backend pages?

**Comment by Floydtm** [comment]
Your request is not related to the functionality of the plugin

**Comment by perks98** [comment]
> Your request is not related to the functionality of the plugin

ok... was just pointing out in my feature request a potential feature... to help better manage custom posts in a better visual way or to better filter. I have many customers that add pages of content under a custom post type, some stuff is hierarchical and can be grouped together, so if you could construct a better custom filtering system on the backend so analysis and developers can find the data that would be helpful. Maybe as part of JetEngine you could find a way to use Elementor on the backend so you can use Elementor, JetSmartFilters and JetEngine to create a custom grid for developers.

But if you don't see the need within JetEngine that's fine.
