### ISSUE TITLE
provide 'Listing Grid' options for a table or list using html tags

### ISSUE THREAD

**Issue by jackcarrington** [CrocoBlock/suggestions#2970]
The main advantage Dynamic.ooo plugin has over the Crocoblock sweet is that their Listing Grid equivalent has the option to add a skin for table or list, which in turn creates a loop with the td, th, tr, html tags. Or create a list / an ordered list with ol, li, html tags.

Having these options present when creating a 'Listing Grid' would be a great help, and open up the breadth of dynamic content with additional technical SEO perks.

**Comment by MjHead** [comment]
This feature will be added as separate module with JetEngine 2.9.0. More details here - https://github.com/Crocoblock/suggestions/issues/3803
