### ISSUE TITLE
Compatible with WCFM multivendor

### ISSUE THREAD

**Issue by lkoskova** [CrocoBlock/suggestions#2973]
Please become compatible with WCFM multivendor

**Comment by chaser32419** [comment]
I'd like to add a vote for this to happen as well.

Also I'd like to suggest having jetpopup to be compatible with this as well to be able to make dynamic pups.
So that we can add popups to user accounts/post/products for asking for donations, that is becoming a popular thing.

**Comment by UraraReika** [comment]
Use one of this templates to describe you suggestion in more details https://github.com/Crocoblock/suggestions/tree/master/.github/ISSUE_TEMPLATE
