### ISSUE TITLE
Checkout Widgets fully customizable

### ISSUE THREAD

**Issue by lkoskova** [CrocoBlock/suggestions#2974]
Please make Checkout Widgets fully customizable

**Comment by UraraReika** [comment]
@lkoskova, please describe your suggestion in more details.

**Comment by 79ho3ein** [comment]
Hello
Yes, this option is required for this plugin.
It would be great if the personalization was such that the fields could be removed or added, as well as whether they were necessary or not.
This option would be great for jet woobuilder. Because it eliminates the need for the WooCommerce Payment Field Editor plugin.
please ckeck

thanks

**Comment by lkoskova** [comment]
Hello Oleksander,

I noticed that widgets for billing and shipping have different box sizes
and i cant edit those (maybe it was only on backend because in attached
screenshot i dont see it anymore)

I also noticed some boxes have different border weight.

Also in checkout top of page, coupon and login widgets, i cant edit the box
size nor color of the buttons, or make border display all around instead of
only above and below.

Also payment widget. The pictures of payment options were too large and thr
only thing that change them to display correctly was when in woocommerce i
chose "distraction free" checkout, then the images became a normal size.

I also cannot edit the "additional notes" background color or background
color for checkout summary.

Im still very happy with what I can already do, don't get me wrong.
Crocoblock is amazing.

Thanks again

**Comment by lifeact** [comment]
follow

**Comment by UraraReika** [comment]
@79ho3ein , @lkoskova thnx for details we will work on it.

**Comment by 79ho3ein** [comment]
Please add this feature so that we can edit selected fields such as city and province of the country. It's so important. Thank you
https://prnt.sc/1213wzk

**Comment by 79ho3ein** [comment]
hi @UraraReika 
Excuse me, is it clear when the ability to fully edit payment fields will be added to the plugin? Next update or next updates?
Thank you in advance for your efforts.

**Comment by 79ho3ein** [comment]
Hi there, is there any news on this?

**Comment by 79ho3ein** [comment]
thank you so much @UraraReika 🌹
