### ISSUE TITLE
Add a query of best-selling products to the product grid widget The jet woobuilder plugin, for use on the home screen.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2977]
Please add the query of best-selling products to the product grid widget so that we can use it on the main page as well. Currently, this query can only be used on the single product page. I think it is better to display the best-selling products on the main page.
Please check. This is very important.

**Comment by UraraReika** [comment]
I merged this issue with #2968, which is on the same subject so we could deal with it more efficiently.
