### ISSUE TITLE
Add shopping cart widget to jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2978]
Hello, please add the menu cart widget to this plugin.
jet woobuilder really lacks such a widget.
I look forward to adding this widget.
WooCommerce currently has this widget, but it is not at all satisfactory.
jet woobuilder can be great and attractive by adding this widget. Please check.

Widget like this image: https://prnt.sc/11buv49

thanks

**Comment by UraraReika** [comment]
I merged this issue with #2938, which is on the same subject so we could deal with it more efficiently.
