### ISSUE TITLE
Report a bug from the new update of the jet smart filter plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2981]
The Delete Filters button is active when the archive page opens.
While no filter is enabled by the user.
Product archive is made with the product grid widget jet woobuilder plugin.

**Comment by Floydtm** [comment]
We checked this point and it looks like everything is working correctly. However, our sites can be customized in different ways. Please contact our support team. We will try to solve the problem on your site. Thank you!
