### ISSUE TITLE
Unique URL for JetCompareWishlist

### ISSUE THREAD

**Issue by obimidasobi** [CrocoBlock/suggestions#2983]
**Unique URL for JetCompareWishlist**

My suggestion is that it would be really awesome if the JetCompareWishlist is structured in such a way that every wishlist created by a logged-in user has a unique URL that can be shared on social media or anywhere on the web.

**Please, describe the feature request, making it clear to understand.**

It is very obvious that the wishlist functionality helps shoppers on an e-commerce website save items for a later purchase. 
This functionality can be enhanced to a scale where it is possible for these wishlists to be able to be shared by the individuals who created them on social media or as a unique URL to that specific wishlist page.

**An example of where this feature is already implemented. **

This feature is specifically relevant to e-commerce store owners because it would give their buyers an option to save, share and eventually buy items which for whatever reason they could not buy at that moment. 

**Here's an example from Template Invaders** https://templateinvaders.com/documentation/ti-woocommerce-wishlist/sharing-settings/

Thanks in advance.

**Comment by UraraReika** [comment]
I merged this issue with #580, which is on the same subject so we could deal with it more efficiently.
