### ISSUE TITLE
Wishlist doesn't work for guests

### ISSUE THREAD

**Issue by imCorfitz** [CrocoBlock/suggestions#2984]
**Describe the bug**
Wishlist doesn't work for guests. I imported the Zolden tempalte to a clean WP installation, and activated the Wishlist functionality in plugin settings. Going to the site and adding to wishlist gives to impression that the action has been made, but when looking in the wishlist page, nothing is listed. And this is the same on the Zolden Demo.

I tested the functionality as a logged in user, which worked perfectly fine,  but not as a guest.

**To Reproduce**
1. Go to [Zolden Demo](https://demo.crocoblock.com/zolden)
2. Click on Shop
3. Click on a Heart icon for any product
4. Icon turns red, and counter in header is increased by 1
5. Click on the Wishlist button in header
6. Wishlist is empty

**Expected behavior**
I would have expected the product I added to the wishlist to be visible in this page.

**Comment by stasonua0** [comment]
https://prnt.sc/11dnr5w

**Comment by stasonua0** [comment]
and try use plugin "WP Session Manager"

**Comment by imCorfitz** [comment]
If I deactivate the "Save for logged users only" it doesn't work for neither guests nor logged in accounts.

**Comment by 79ho3ein** [comment]
Yes it is true.I have the same problem.
Please make sure that when the guest user clicks on the Favorites checklist, he will be redirected to the registration page.
This may be the best option.

thanks

**Comment by martinjakse** [comment]
Hi, any news regarding the issue ? It still isn't working
