### ISSUE TITLE
The Ability to Add Values from Repeater Fields to the Circle Progress Widget??

### ISSUE THREAD

**Issue by haythamat** [CrocoBlock/suggestions#2985]
My Name is Haytham Abu Atiyyeh; I'm the operation Manager at Center for Defending Freedom of Journalists CDFJ, a non-profit organization based in Amman, Jordan, and working on the field of Media Freedoms and Human Rights.

I'm working to build a page for Media Freedoms Index in the Arab world.
So from the post type I've created, there were some custom fields about the "current value" and "Max Value" of the general index that I can use in the circle progress widget's dynamic values.

When I tried to create a repeater for the specific index sections, each one has a current value and max value, and try to apply them to the circle progress widget, and I can't find the repeater fields to be selected.

It is crucial to make this step; I hope you can help me with this or show me another way to do it.

Please, if you need access to my website or more further information, please let me know.

**Comment by Floydtm** [comment]
I understand that this is important for you, but we will not implement it right now. Thank you!
