### ISSUE TITLE
Shop page is not assigned to search page

### ISSUE THREAD

**Issue by alexanderchacon** [CrocoBlock/suggestions#2988]
Hi! 

I created the shop page with woo Page Builder and inside I added a products grid with the query in "Use current query" and in woocommerce I select my page as a Shop page 

But the search page is still with the base search template

How can I show my shop page as a result page? or do I need to create another page?

**Comment by UraraReika** [comment]
Hello @alexanderchacon!

I check this issue on my installation and everything work proper. Please contact our support team so we can check on your site.

**Comment by alexanderchacon** [comment]
Hi! thanks for your answer.

If anyone else needs ands answer here the problem is that you need to check that your template has full support from woocommerce

In my case I started to work with a skeleton theme with no full support of woocoomerce
