### ISSUE TITLE
Tabs optimization 

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#299]
​And then you have the text and content block after the headline which shows on click to open. Here we might have links hrefs. And that color is controlled globally. And when open and close the fade in is delayed on the link color compared to the surrounding text when open and close.​ Add it to a static file e.g with csshero or child theme css or whatever suits you, and you will see the same issues. ​ In the accordion I can only pick before and after icon. But I would surely think it would be suitable to align the icon to the right or left. Meaning I want the icon in the very right end not right after the headline in the accordion. Like this: https://tppr.me/zNqt4​

**Comment by Floydtm** [comment]
@WildHund hi, nothing is available on your link http://prntscr.com/nx108r

**Comment by WildHund** [comment]
https://tppr.me/zNqt4

**Comment by alriksson** [comment]
+1

**Comment by kaskad88** [comment]
We tried to reproduce your issue based on the information you provided, but without success.
