### ISSUE TITLE
Display WooCommerce notifications as a pop-up in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2990]
Hello
Please add an option to this plugin so that WooCommerce notifications, such as: the product has been added to the cart or the coupon is not valid and all WooCommerce notifications are displayed as pop-ups.
Currently, on a website built with elementor, WooCommerce notifications are displayed in a way that is not interesting at all.
This option is very necessary. Please check.
Please share your opinion on this

Thanks

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently.
