### ISSUE TITLE
JetEngine - CCT - Repeater field display on the front-end

### ISSUE THREAD

**Issue by tamasgt** [CrocoBlock/suggestions#2991]
Hello Team!

Please add it to JetEngine to display the CCT (not CPT) repeater field on the front end. Unable to display at this time, the Dynamic Repeater and Listing Items do not know this.

Thanks, Tamas

**Comment by edeliz** [comment]
please ... look for the same functionality

**Comment by nreljed** [comment]
#3514

**Comment by VinT08** [comment]
+1 I am looking for the same functionality too.

**Comment by IFTTD** [comment]
I can't believe this was missed. I need this for a project I'm working on now.

**Comment by mohizahmad** [comment]
I always thought since CCT's have repeater regions, this would show up in the front end as well. Planned entire project, started working on it only to find out it can't be done.

It should be a priority to add flexibility to CCT's as well.

**Comment by kaskad88** [comment]
Added in JetEngine v2.11.8
