### ISSUE TITLE
JetEngine Custom Permalink for CPT

### ISSUE THREAD

**Issue by laurentgarin** [CrocoBlock/suggestions#2992]
Hi,

Add the possibility to custom the permalink structure of items to have for example
www.website.com/Term/Item-name instead of 
www.website.com/Post-type-name/Item-name

Thanks for your grat work team.

**Comment by Floydtm** [comment]
We cannot realize this right now. You can find the solution here https://wordpress.org/plugins/search/permalink/ Thank you!
