### ISSUE TITLE
Report a bug in the new update of the jet smart filters plugin. Please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#2995]
Hello
In the new update of this plugin, Ajax will be loaded automatically when the product page opens. The button to delete active filters is also activated, while no filter is active. Please check. The bug is very problematic.
It is better to say that this filter along with the product grid widget has caused a problem with the jet wobuilder plugin. I do not know if these bugs exist with other plugins.
Please check

thanks

**Comment by Floydtm** [comment]
Contact our support team, we will check your site. Thank you!
