### ISSUE TITLE
Making a static Booking Form, just like in Appointment plugin

### ISSUE THREAD

**Issue by poiterdesign** [CrocoBlock/suggestions#2997]
Hi,

Really would like to see this feature.
Also as the Appointment plugin has the possibility to make a static form, this is also needed for the Booking plugin. Making it more user friendly, because less clicking to the form.  

Thank you in advance!

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/456, which is on the same subject so we could deal with it more efficiently.
