### ISSUE TITLE
JetWooBuilder > Products Grid - Not found message should work for two different cases when using with SmartFilters

### ISSUE THREAD

**Issue by xitromedia** [CrocoBlock/suggestions#3006]
When using Products Grid with Smart Filters

In Products Grid general settings i can set a "Not found message". But there are two cases for which this message applies and it should be possible to set also two different messages.

One case is if there are no products at all returned by the query. Then i need a message like "No products in this category".
The second case is if the query returnes items but the set filters lead to a display of zero products. Then i need a message like "Your filter settings do not return a match. Please choose other options".

Only one message for all cases may irritate the customer if only one of the cases occurs.

**Comment by UraraReika** [comment]
In the next release Products Grid/List widgets will have filter hooks:
PG - `jet-woo-builder/shortcodes/jet-woo-products/not-found-message`;
PL - `jet-woo-builder/shortcodes/jet-woo-products-list/not-found-message`.

So you can handle it whatever you want like this https://gist.github.com/UraraReika/98bfcc2ae6863108778bddc0dde9b80c.
