### ISSUE TITLE
Redirect guest users to the login page, if they wish to see the favorites list. After logging in, they can see their favorites list

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3009]
Hello
in compare and wishlist plugin...
Please **add settings** to this plugin so that guest users who want to view their favorites list will be **redirected to the login page** so that they can view their favorites list after logging in.
For now, if guest users add a product to their wish list, and then want to view their wish list, **they will not see anything** **and think it is a bug**. And this is not good at all.
Please share your opinion in this regard.

thanks

**Comment by 79ho3ein** [comment]
hi @UraraReika 
Do you have a plan to add this feature to the plugin?
I have reviewed several reputable sites and they also use this feature.
This feature completely fixes bugs related to unregistered (unregistered) users.
Thanks.

**Comment by UraraReika** [comment]
Hello @79ho3ein ! 

You already can achieve this functionality with our plugins. You can use this free [extention](https://github.com/UraraReika/jet-engine-custom-visibility-conditions) with compare and wishlist visibility conditions. Then add necessary buttons and labels to your template. Hide and show them when you need it and it can redirect whatever page you need.
