### ISSUE TITLE
Execute border radious code separately for each product carousel flash box, in jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3011]
Hello
Please add a feature to the carousel flash box of the prodct gid widget product of this plugin so that we can apply border-radious to each box separately. In the current situation, we can not design a box **similar to the submitted image**. Because border-radious applies to both boxes. image :https://prnt.sc/11izsb4
This is a small but interesting idea. Please check it out.

thanks

**Comment by UraraReika** [comment]
Please correct me if i didn't understand you. You want to style navigation arrows separately https://prnt.sc/11ouwa7? Products Grid widget.

**Comment by 79ho3ein** [comment]
Hello, thank you for your attention.
You see, at the moment, we can not build something like this (https://prnt.sc/11ozfws) with jet woobuilder(In terms of border-radious context.). Because the border-radious value is **applied to both fields of the product carousel arrow**.
For example, this image (https://prnt.sc/11oyber) is from jet woobuilder, which I wanted to create like the image above.
But it is not possible. Because the border-radious value is applied to both fields of the product carousel arrow.
As you can see in this image, I have given the fields a value of px10 px0 px0 10px. Only the right field is correct.
And the left arrow field is exactly the opposite of the right (https://prnt.sc/11oyber).
If each box can have a different radius, then it can be made like this. This is a small but great feature.
I hope I have conveyed my point well.

thanks
