### ISSUE TITLE
Improved the appearance of the selection filter in the jet smart filter plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3014]
Hello
Please improve the appearance of the jet smart filter plugin selection widget. It is very simple and ugly. https://prnt.sc/11kwi6z

Similar example for improvement : https://prnt.sc/11kwvxz

please check. thanks

**Comment by Floydtm** [comment]
Hi, I understand that this is important to you, but we are not going to do it right now. Thank you!
