### ISSUE TITLE
Multistep Checkout

### ISSUE THREAD

**Issue by lkoskova** [CrocoBlock/suggestions#3016]
Hello,

Please allow for multistep checkout

**Comment by Hans-101** [comment]
+1

**Comment by UraraReika** [comment]
It can be already complete with combination of JetWooBuilder and JetTabs plugin.

**Comment by UraraReika** [comment]
Use this https://www.youtube.com/watch?v=ZpBTAYJ3vLA&ab_channel=Crocoblock
