### ISSUE TITLE
Report a serious bug in the jet compare & wishlist plugin for guest users

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3018]
Hello
In the new update, this plugin has a very bad bug for guest users. So that even if the product is removed from the wish list, the product still remains in the list. There is even more bugs.

A simple suggestion to fix all the bugs of this plugin: Add settings so that the guest users will be directed to the login or registration page if they see their favorite items. Once logged in, they can view their favorites. this is very good

please check.thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein !

> In the new update, this plugin has a very bad bug for guest users. So that even if the product is removed from the wish list, the product still remains in the list. There is even more bugs.

In latest version of JetCompareWishlist we fix some bug with this issue. If you still have some problems with this then contact our support team.

> A simple suggestion to fix all the bugs of this plugin: Add settings so that the guest users will be directed to the login or registration page if they see their favorite items. Once logged in, they can view their favorites. this is very good

I merged this issue with #3009, which is on the same subject so we could deal with it more efficiently.
