### ISSUE TITLE
Jet Smart Filters: Indexer Users

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#3019]
Hello, consider making Indexer functionality in post types Users https://user-images.githubusercontent.com/34642272/115143755-dddd6000-a051-11eb-9ad8-8c15fce5fa89.png

/*Оригинал*/
Здравствуйте, рассмотрите возможность сделать функционал Indexer в типах записей Пользователи https://user-images.githubusercontent.com/34642272/115143755-dddd6000-a051-11eb-9ad8-8c15fce5fa89.png

**Comment by Floydtm** [comment]
Available from version 2.3.3
