### ISSUE TITLE
Request to blur the space around the megamenu when opening the jet menu plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3021]
Hello
Please add a mode to this plugin, so that when the user opens Megamenu, the space around it becomes blurred (like the picture)
Please check this feature. It is very important and practical.
Like this picture : https://prnt.sc/11nc7mx

thanks

**Comment by Floydtm** [comment]
Hi, I understand that this is important to you, but we are not going to do it right now. Thank you!
