### ISSUE TITLE
Range Filter Bug

### ISSUE THREAD

**Issue by Zaanone** [CrocoBlock/suggestions#3022]
EDIT:
Problem is in the 2.2.2 update. Reverted to 2.2.1 and the problem is not there anymore.

**Describe the bug**
Jet Smart Filters bug (range filter)
- I've got a comparison website with 2 range filters and 5 (dropdown) checkbox filters.
- I've made a test where people can see what product (hosting plan) fits their needs
- After submit, people get redirected to a url. In this url I inserted filter parameters. A link could look like this for example: https://vergelijkhosting.nu/vergelijk-hosting/?jsf=jet-engine:vergelijkmain&meta=schijfruimte!range:5-133;prijs-per-maand!range:0-5;dataverkeer_select!is_custom_checkbox:Onbeperkt
- After submit, people get redirected to a page where all the filters are set up for them.
- However (this is the bug). When people get redirected via this url, the range filters wont work anymore. I can still slide and change the values,, but nothing happens.
- The checkbox dropdowns still work.

**To Reproduce**
1. Go to https://vergelijkhosting.nu/vergelijk-hosting/. Test the range filters, they work right?
2. Go To https://vergelijkhosting.nu/vergelijk-hosting/?jsf=jet-engine:vergelijkmain&meta=schijfruimte!range:5-133;prijs-per-maand!range:0-5;dataverkeer_select!is_custom_checkbox:Onbeperkt  This is an example link that visitors could get after they finished the test.
3. Try sliding the range filter. It wont work anymore. (Tried different settings on both Chrome and FireFox)
4. The crazy thing is... On my (Android) Phone, they still seem to work.

- Apply type : AJAX
- apply on : value change
- I've tried different setting, but the range filters wont work

**Expected behavior**
I expect the range filter to still work after the redirect.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Firefox. Newest versions
 - Elementor

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T Pro
 - OS: Android
 - Browser: DuckDuckGo

EDIT:
Problem is in the 2.2.2 update. Reverted to 2.2.1 and the problem is not there anymore.

**Comment by 79ho3ein** [comment]
Yes, that's right. The recent update (2.2.2 version) of the jet smart filters plugin came with a lot of bugs. I hope they release the perfect new version as soon as possible.

**Comment by Zaanone** [comment]
I hope so. I had it all set up pretty well. Visitors complete a test with typeform, typeform redirects the visitor to a custom url (with filter meta included).. But now the filter options on my website are pretty broken :S

**Comment by 79ho3ein** [comment]
In the new update, for me, when the product archive is opened, Ajax will load automatically and the button to delete active filters will appear. If no filter is activated.
I am using the product grid widget of the jet woobuilder plugin for product archiving. I hope these bugs are fixed in the new version.

**Comment by Zaanone** [comment]
Btw, thanks for your comment!! I just reverted the 2.2.2 version to 2.2.1 and the range filter works again (after the url redirect). Hopefully they'll fix it though, otherwise I'm stuck at 2.2.1 :S

**Comment by 79ho3ein** [comment]
Yes, I am on the previous version. They will definitely see our comments and fix them. crocoblock is a big company. good luck my friend

**Comment by Zaanone** [comment]
You to my wise friend whom I just met. May the force of the filters be with you.

**Comment by 79ho3ein** [comment]
thanks bro

**Comment by Floydtm** [comment]
Guys, for a quick solution to the problem, you need to contact our support team. We will try to fix everything. Thank you!
