### ISSUE TITLE
Jet Smart Filters Range Input boxes (min amount - max amount)

### ISSUE THREAD

**Issue by Zaanone** [CrocoBlock/suggestions#3023]
Hi,

What would be really great is to have a range filter where you can type a minimum and/or maximum amount. I've got a comparison website where most products are between 1 and 20 euro's. A few products however are 1000+ euro's. This makes filtering with the range slider really annoying. Lets say a visitor wants the minimum product price to go from 2 euros to 5 euros. It's practically impossible to do so with the range slider if the maximum amount is 1000. The smallest slide with your finger or the cursor already means that the price will change tens of euro's.

I could reaaaally use a range filter where people can simply type in their minimum and/or maximum values. 

Examples (some dutch websites. they both have min-max boxes on the left):
- https://hostingvergelijker.nl/webhosting-vergelijken/vergelijk-nu/
- https://www.webhosters.nl/vergelijken/

Hope you can include this filter in a next update!

Kind regards
Casper

EDIT: suggestion is also mentioned here:
- https://github.com/Crocoblock/suggestions/issues/2998
- https://github.com/Crocoblock/suggestions/issues/2823
- https://github.com/Crocoblock/suggestions/issues/1131
- https://github.com/Crocoblock/suggestions/issues/917

**Comment by 79ho3ein** [comment]
Yes, it would be really great

**Comment by Medienor** [comment]
FOR THE LOVE OF GOD YES! People have been asking months for this feature.

**Comment by kochhase** [comment]
> 
> 
> FOR THE LOVE OF GOD YES! People have been asking months for this feature.

Yes I use now facetwp for that.

**Comment by MjHead** [comment]
Done
