### ISSUE TITLE
An important request for the jet woobuilder plugin. please check it.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3024]
Hello
Please add a feature to this plugin so that we can display WooCommerce notifications, such as a product added to or removed from the cart, coupons are invalid, payment page notifications, and all WooCommerce notifications as a pop-up.
This is a request of many users of this plugin. Please check

thanks

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently.
