### ISSUE TITLE
Display custom text, instead of prices on non-existent products،in jet woobuilder plugin.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3029]
Please add a feature to this plugin, so that we can write our own text instead of the price on non-existent products. For example, non-existent! like this image https://prnt.sc/11p0msv
This feature is very useful, especially in the product grid widget. Please check.

thanks

**Comment by UraraReika** [comment]
By a non-existent product you mean out of stock product?

**Comment by 79ho3ein** [comment]
Yes, products that are out of stock.This feature is very useful. I saw it on a great website.
I hope I have conveyed my point well.

Thank you for your attention

**Comment by UraraReika** [comment]
In Products Grid widget we have a some amount of controls https://prnt.sc/11pbkq4. In your case we need this one https://prnt.sc/11pbo88. https://prnt.sc/11pbpq9 when you enable this you can put whatever you want text.
