### ISSUE TITLE
Jet Search issue not linking to Archive search page if search on home page

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#303]
Currently using the Jet search plugin on my home page. I also have an archive page configured with filters, that is my main search page.

Currently, if I do a search on the home page it will redirect to the archive page but the filters are not linked.

Take a look at this sample site to see what I mean. If you choose date drop down or the destination, it will redirect you to the search results archive page, and then allows you to carry on with the filters and finding the product you want.

Currently, I don't believe jet search can work in this way and feel it will be a great addon as all sites like to have a good search function like this.

https://travel.padi.com/

thanks

**Comment by Floydtm** [comment]
@scubaninja1977 Hi, could you describe in detail your case with screenshots or videos from your site. Thank!
