### ISSUE TITLE
Display bestsellers on the home page by the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3030]
Hello
Please allow us to display best-selling products on the home page.
Currently, this is only possible on the single product page.
While it is better to display best-selling products on the main page so that the user can see it at first glance.
Please review this item and please add it soon. I personally need it very much.

thanks

**Comment by UraraReika** [comment]
You can achieve this result with the help of this options https://prnt.sc/11pav43.
