### ISSUE TITLE
Add the ability to quantify as a product in the favorites list

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3031]
Hello
Please add a feature to the jet compare and wishlist plugin, so we can quantify as products.
Just like the jet woobuilder plugin.
This feature is required. Please check.

Thank you

**Comment by UraraReika** [comment]
Please describe your issue in more details.

**Comment by 79ho3ein** [comment]
I meant this feature for the title : https://prnt.sc/11pbb2v

**Comment by 79ho3ein** [comment]
Thank you
