### ISSUE TITLE
Equalize size feature, for woobuilder jet plugin pagination box.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3032]
Hello
Please add a feature to the paging widget, so that the paging box is equal in length and width.
Currently, pagination box # 1 is smaller than the rest.And this is not interesting. For example : https://prnt.sc/11pad3t
It would be great if you add settings that we can make like the image in front of :  https://prnt.sc/11pa5ru

please check. thanks

**Comment by UraraReika** [comment]
Use this control to equalize size https://prnt.sc/11wx6qy , https://prnt.sc/11wx795
