### ISSUE TITLE
Equalize size feature, for jet smart filters plugin pagination box.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3033]
Hello
Please add a feature to the paging widget, so that the paging box is equal in length and width.
Currently, pagination box # 1 is smaller than the rest.And this is not interesting. For example : https://prnt.sc/11pad3t
It would be great if you add settings that we can make like the image in front of : https://prnt.sc/11pa5ru

please check. thanks

**Comment by 79ho3ein** [comment]
In previous issues, I wanted to tell jet smart that I mistyped jet woobuilder.

**Comment by Floydtm** [comment]
I understand that this is important for you, but I want to say that most people customize the styles on their own. We cannot consider this to be a bug. Thank you!

**Comment by 79ho3ein** [comment]
اشکال نیست.پیشنهادی برای بهبود هستSent from my Galaxy
-------- Original message --------From: Floyd ***@***.***> Date: 22/04/2021  16:15  (GMT+03:30) To: Crocoblock/suggestions ***@***.***> Cc: 79ho3ein ***@***.***>, Author ***@***.***> Subject: Re: [Crocoblock/suggestions] Equalize size feature, for jet smart filters plugin pagination box.please check (#3033) 
I understand that this is important for you, but I want to say that most people customize the styles on their own. We cannot consider this to be a bug. Thank you!

**Comment by 79ho3ein** [comment]
No problem. There is a suggestion for improvementSent from my Galaxy
-------- Original message --------From: Floyd ***@***.***> Date: 22/04/2021  16:15  (GMT+03:30) To: Crocoblock/suggestions ***@***.***> Cc: 79ho3ein ***@***.***>, Author ***@***.***> Subject: Re: [Crocoblock/suggestions] Equalize size feature, for jet smart filters plugin pagination box.please check (#3033) 
I understand that this is important for you, but I want to say that most people customize the styles on their own. We cannot consider this to be a bug. Thank you!
