### ISSUE TITLE
JetBooking - Two way sync with Google Calender

### ISSUE THREAD

**Issue by Zaanone** [CrocoBlock/suggestions#3035]
Hi,

- A customer of has his appartement on AirBnb so that people can rent his appartement. AirBnb syncs with his Google calender. So if somebody books his appartment, a event is automatically made in Google Calender. 
- It also works the other way around. If my customer manually ads an event to his Google Calender, then these dates wont be available anymore on Airbnb.
- My customer now wants his own website where he can also put his place for rent. However, to avoid double bookings it would be amazing if JetBooking could also do a two-way sync with Google Calender. Untill this point, Jetbooking only allows a one-way sync from JetBooking to Google Calender, but not the other way around.

I think this is kind of a crucial addition to the plugin. A lot of people (like my customer) have their apartment for rent on several different websites. To avoid double bookings, a two-way sync with a common agenda (like Google Calender) is important.

I've seen one other plugin that allows for a two-way sync (https://www.youtube.com/watch?v=rKlRJn9Y5N8). But since I already bought the Crocoblock suite, I'd rather not also spend money on another expensive plugin.

Do you think this feature will be implemented somewhere in the (near) future?

**Comment by UraraReika** [comment]
Hello @Zaanone !Thanks for the feedback and sorry for delayed answer.

You can take a closer look at our knowledge base where you can find section for Google calendar https://crocoblock.com/knowledge-base/article-category/jetbooking/. And right now we working on some functionality that will help you to set up this better.

Thank you for your understanding.
