### ISSUE TITLE
JetBooking - Restrict check-in and check-out days

### ISSUE THREAD

**Issue by Zaanone** [CrocoBlock/suggestions#3036]
Hi,

- There is already a feature in the JetBooking plugin to allow for only booking single days or 7 days.
- It would be great if you guys could expand this feature a bit. I've got a customer who wants to rent his apartement to customers. However, he only wants to do this from monday - friday or the weekends.
- In other words, the only check-in days are monday and friday. The only checkout days are friday, sunday and monday.

- I can't find this option in JetBooking. Is it possible to add this?

**Comment by CaseFixedWebdesign** [comment]
+1

**Comment by UraraReika** [comment]
Hello. Thanks for the feedback.

I've checked your request. Such a goal can be reached using a custom solution only.
I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.
