### ISSUE TITLE
JetEngine Grid Listing "Load more [posts]" button

### ISSUE THREAD

**Issue by henrique-voni** [Crocoblock/suggestions#304]
I'd like to suggest the option to add a "Load more [your CPT here]" button for Grid Listing.

- Feature: "Load more" button for listings

- Expected result: A widget or Listing setting that creates a button which loads more posts to the listing using AJAX. 

- Expected settings: Styling, button title, quantity of posts loaded per click, "loading" text title.

Here is something similar:

![image](https://essential-addons.com/elementor/wp-content/uploads/2018/02/8-2.gif)

**Comment by stasonua0** [comment]
+1

**Comment by utich78** [comment]
+

**Comment by MPHood** [comment]
+1

**Comment by utich78** [comment]
+1

**Comment by andrearuffini** [comment]
+1

**Comment by utich78** [comment]
Been 3 months waiting. When will this miracle happen?

**Comment by redordev** [comment]
Woo ready for release soon?! Ideally on jet listing grid have these 3 options:

1) pagination
2) load more
3) infinite scroll

but even load more by itself will be amazing!

**Comment by AjayToker** [comment]
> Woo ready for release soon?! Ideally on jet listing grid have these 3 options:
> 
> 1. pagination
> 2. load more
> 3. infinite scroll
> 
> but even load more by itself will be amazing!

Pagination widget is available via JetSmartFilters - just FYI.

**Comment by winmkt** [comment]
+1 - please add this!!

**Comment by Biblothecaire** [comment]
Hi,

I see "closed", so it add ?
I test to add it on me archive template but it don't work ...
I read your tuto "https://crocoblock.com/knowledge-base/articles/jetengine-listing-functionality-how-to-create-a-new-listing-to-apply-for-the-certain-post-type/" but i don't uderstand how to fixe it ?

The probleme i think is the fact that i can't chose a "post number" when i have "use as archive mode", so my 400 post load same time, more than 2 min to charge the site ...

thanks for your help
