### ISSUE TITLE
Report an important bug of the jet woouilder plugin in Persian.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3042]
In Persian, the price unit in the recent update has gone to the right of the price, while before that, it was on the left.
This problem only exists in the Android Chrome browser.
Please check. This bug is very bad. https://prnt.sc/11rhkjt
thank you

**Comment by UraraReika** [comment]
Did you use this option https://prnt.sc/11x617s?

**Comment by 79ho3ein** [comment]
No, it is true inside all browsers and devices. The problem is only in the Android Chrome browserSent from my Galaxy
-------- Original message --------From: Oleksandr Rudyi ***@***.***> Date: 23/04/2021  16:39  (GMT+03:30) To: Crocoblock/suggestions ***@***.***> Cc: 79ho3ein ***@***.***>, Author ***@***.***> Subject: Re: [Crocoblock/suggestions] Report an important bug of the jet woouilder plugin in Persian.please check (#3042) 
Did you use this option https://prnt.sc/11x617s?

**Comment by UraraReika** [comment]
Please check everything more accurate. In our widgets we use standard WooCommerce price display so if the problem exist it belongs to WooCommerce. Although did you check this on another widget or default product loop?

**Comment by 79ho3ein** [comment]
Yes, definitely not the problem of jet woobuilder.  Thank you for your attentionSent from my Galaxy
-------- Original message --------From: Oleksandr Rudyi ***@***.***> Date: 23/04/2021  17:25  (GMT+03:30) To: Crocoblock/suggestions ***@***.***> Cc: 79ho3ein ***@***.***>, Author ***@***.***> Subject: Re: [Crocoblock/suggestions] Report an important bug of the jet woouilder plugin in Persian.please check (#3042) 
Please check everything more accurate. In our widgets we use standard WooCommerce price display so if the problem exist it belongs to WooCommerce. Although did you check this on another widget or default product loop?
