### ISSUE TITLE
CROCOBLOCK – Please integration discount calculation in the JET ENGINE FORMS

### ISSUE THREAD

**Issue by L6ZB3W9** [CrocoBlock/suggestions#3046]
Please integrate a discount calculation in the calculation formular of JET ENGINE FORMS. 

For example:

10% discount from 5 pieces 
20% discount from 10 pieces
30% discount from 25 pieces
35% discount from 50 pieces

Thank **you...**

**Comment by Floydtm** [comment]
All this can be done. Check out the documentation or contact our support team. Thank you! https://crocoblock.com/knowledge-base/article-category/jet-engine/
