### ISSUE TITLE
Product Gallery - no support for vertical/portrait video or fit to space

### ISSUE THREAD

**Issue by yapofire** [CrocoBlock/suggestions#3047]
Vertical/Portrait videos are no longer supported in the Product Gallery plugin

They used to be as can be seen here in the Crocoblocks Youtube video:

https://www.youtube.com/watch?v=13nza5_IzQU

(8:53 in video above)

Can this functionality be added back urgently?

Having a product gallery that shows full portrait photos, but then a tiny 16:9 video looks really bad, almost to the point of not being worth adding video at all

Here is a link to what it looks like when you add a Vimeo Portrait video currently: (https://user-images.githubusercontent.com/82288635/115547719-7f58f180-a29e-11eb-84e2-108a70047356.png)

If there is any quick workaround that would be really gratefully received :-)

Thanks

**Comment by Floydtm** [comment]
In this video, the video was selected 800 * 1200 You need to choose the desired video size

**Comment by yapofire** [comment]
> In this video, the video was selected 800 * 1200 You need to choose the desired video size

Hi Floyd, I have video like you suggest that is 2:3 ratio.

However you cannot select this ratio in the plugin, see image of options below (2:3 is not an option):

https://ibb.co/qDnykXB

Do I need to use custom CSS? Or is there another way to choose a 2:3 video ratio?


Thanks
