### ISSUE TITLE
A few tips that the jet woobuilder plugin lacks

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3048]
1- The product image (single product) of this plugin can not be aligned.
2- The two overlap. That is, they move together. Either right or left https://prnt.sc/11svm8r
3- It is better to display thumbnail images as a slider on a single product page : https://prnt.sc/11svjr0
4- For me, the single page product title is not displayed. I do not know what the reason is

**Comment by UraraReika** [comment]
1 - done
2 - need more details
3 - Use JetWooProductGallery plugin.
4 - contact our support team https://support.crocoblock.com/support/home/

**Comment by 79ho3ein** [comment]
2- When we align the product title, the shopping cart update button moves with it.
3- I tried, but I could not do such a thing with the jet product gallery. : https://prnt.sc/11xbz8s

thanks

**Comment by UraraReika** [comment]
2 - You trigger this align control https://prnt.sc/122ygo9 which effects all table cells, and this area is table cell https://prnt.sc/122yk15.
3 - contact our support team https://support.crocoblock.com/support/home/.
