### ISSUE TITLE
Allow to use other than username in the Auth Links widget

### ISSUE THREAD

**Issue by adelapuentep** [CrocoBlock/suggestions#3049]
By default, WordPress shows the username as the Display name of an user. Therefore, if you add the `%s` macro in the Auth Links widget prefix, it will show the username.

So, if I change the 'Display name publicly as' from my profile it will render whatever option I select. For example, First Name or Last Name or First Name + Last Name or Last Name + First Name.

Since there is no way to change the user's default display name without coding, it will be nice if Crocoblock allow us to do so or if it creates another macro (or other way) to allow us to change the display name from username to any of the options mentioned before.

**Comment by Floydtm** [comment]
@Gawuww add an option to select the source of data output

**Comment by kaskad88** [comment]
Added to the JetBlocks 1.2.9
