### ISSUE TITLE
Request upgrade button to add to cart, on single product and cart page in jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3051]
Please change these buttons, because this style of buttons is old and only old sites use this style.
This model is also available in the shopping cart table widget.
It would be great if you could update these buttons. jet woobuilder really needs this.
Current example of add to cart button : https://prnt.sc/11t9eeg
Example of a button to add to a new shopping cart : https://prnt.sc/11t99yf
please check

thanks

**Comment by P-happiness** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with #2711, which is on the same subject so we could deal with it more efficiently.
