### ISSUE TITLE
Request complete editing of checkout forms, in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3053]
I apologize for making this request again.Because this feature is very important. And jet woobuilder really needs it.
If this feature is added, there will be no need to install additional plugins. Add-ons that cause worse damage to the site.
I will describe the options :
Ability to delete unnecessary fields.
Ability to apply necessary or unnecessary value to fields.
Full custom appearance of the fields, which of course already exists.
Ability to edit selected fields such as city and province.
Ability to move the desired fields (in order)

Please check these items. I have many ideas for improving jet woobuilder.
This plugin will definitely be unique.
Thanks to the crocoblock team

**Comment by UraraReika** [comment]
I merged this issue with #2974, which is on the same subject so we could deal with it more efficiently.
