### ISSUE TITLE
Display WooCommerce notifications as a pop-up in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3054]
Please add a feature so that we can display WooCommerce notifications as a pop-up. Like notification: Product added to cart, or coupon is not valid. There are currently no plugins available for this. If jet woo adds it it will be really great.
This is a request of many users of this plugin. Because at the moment, these announcements make the site look ugly. Please check.
thanks.

**Comment by Lonsdale201** [comment]
You can use the jetpopup with add to cart notifications.
https://crocoblock.com/knowledge-base/articles/jetwoobuilder-how-to-display-a-products-cart-in-a-popup-based-on-jetpopup/

**Comment by 79ho3ein** [comment]
True, but jet woobuilder is better to have it. The less plugins you install, the better.

**Comment by P-happiness** [comment]
Speaking of WooCommerce Cart Notification:
It would be great to show the Remaining Amount to Reach Free Shipping Threshold in the WooCommerce Shopping Cart Widget.
I've found a PHP Snippet that should work on Cart Page, but it would be great to have this notification inside the Off Canvas WooCommerce Shopping Cart.
Do you think it is possible?

**Comment by 79ho3ein** [comment]
Yes, pop-up display of WooCommerce notifications is very important. I hope it will be added soon.

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently.
