### ISSUE TITLE
Query best-selling products in jet woobuilder plugin not working.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3058]
hello
When I set this query, it shows all the products : https://prnt.sc/11pav43
While no products are sold on the site.
Since the site does not have sales, it should not display the product, right?
But it shows all the products. Please check.

Thank you

**Comment by UraraReika** [comment]
Use Query ID option https://i.gyazo.com/c63d9da5d756a893a2e4caeb1202f673.png.

```
add_action( 'jet-woo-builder/query/best-sellers', '__your_theme_prefix_get_bestsellers_products' );

function __your_theme_prefix_get_bestsellers_products( $query ) {
	$query->query_vars['meta_query'][] = [
		'key' => 'total_sales',
		'value' => 0,
		'compare' => '>'
	];
}
```

**Comment by 79ho3ein** [comment]
@UraraReika 
thank you
only one question...
Does this mean that this feature will not be added directly to the plugin?

**Comment by UraraReika** [comment]
You got it right
