### ISSUE TITLE
JetWooBuilder’s option to modify Woocommerce Notices

### ISSUE THREAD

**Issue by xC4M** [CrocoBlock/suggestions#3059]
As a suggestion Crocoblock can include an option in the JetWooBuilder where we can modify all the Woocommerce’s notices. It could be similar to the options in the JetEngine where I can modify the form’s notices.

Crocoblock is awesome, and this “little” thing that I’ve just suggested make it bigger.

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently.
