### ISSUE TITLE
Listing grid ordering, 

### ISSUE THREAD

**Issue by scubaninja1977** [CrocoBlock/suggestions#306]
I have created an event listing grid and I need to be able to set the order by the event start date, so for example, 

it is currently displayed in the listing grid as June 17, 2019, and then June 10 2019, i need to order it by date so show the most relavent date first, so June 10 2019, June 17 2019 and so on.

cant seem to find a straight forward way of doing this.

thanks

**Comment by Floydtm** [comment]
@scubaninja1977 Hi, I think this should help you. See the Posts Query item. https://documentation.zemez.io/wordpress/index.php?project=jetengine&lang=en&section=jetengine-layouts
