### ISSUE TITLE
Some important suggestions for upgrading a single product image widget in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3065]
This widget does not have good features at the moment. And I personally do not use it.
But I suggest a few things to improve this widget :
1- Add an option so we can specify the number of thumbnails. : https://prnt.sc/11vd1jb
2- Add an option so that if the number of thumbnails exceeds the desired number (number 1), the images will be displayed in a slider. :  https://prnt.sc/11vd9f1
3- At the moment,By default, the image is not in the middle. Please add the alignment feature.
5- Add alignment option to thumbnail images. Default is on the right. : https://prnt.sc/11ve8il
6- When zooming in on the main image, the + symbol is displayed.

please check. thanks

**Comment by UraraReika** [comment]
All the features presents in Gallery slider widget from JetProductsGallery for Elementor plugin. Please check it out.
