### ISSUE TITLE
Ability to display color or size on a single page of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3066]
Please add a feature so that we can display the color or size of the products on a single product page. In this case, there will be no need to install additional plugins. : https://prnt.sc/11veol3
This feature is much needed.
The jet woobuilder is unique, but it becomes even more unique.

Thanks to the jet woobuilder team.

**Comment by UraraReika** [comment]
I merged this issue with #361, which is on the same subject so we could deal with it more efficiently.
