### ISSUE TITLE
Report a bug in the jet woobuilder plugin > Product carousel

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3067]
Currently, we can not determine the number of product calls per scroll, but in the size of the mobile.
Whatever number we put, only one product is added after the sheet is rolled.
This bug is in the product grid> Product carousel widget.
please check. thanks

**Comment by UraraReika** [comment]
It's not a bug it's a way how it works on touch screen devices. In future update we will release freeMode functionality and on such devices everything will work much better.

**Comment by 79ho3ein** [comment]
Thank you for your attention.Sent from my Galaxy
-------- Original message --------From: Oleksandr Rudyi ***@***.***> Date: 26/04/2021  14:17  (GMT+03:30) To: Crocoblock/suggestions ***@***.***> Cc: 79ho3ein ***@***.***>, Author ***@***.***> Subject: Re: [Crocoblock/suggestions] Report a bug in the jet woobuilder plugin > Product carousel (#3067) 
It's not a bug it's a way how it works on touch screen devices. In future update we will release freeMode functionality and on such devices everything will work much better.
