### ISSUE TITLE
🔥[Jetengine forms] limit the confusion of mappings fields. 🐛caught bug with page options 

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3068]
Hello Friends ,

I start to work a lot with jet engine forms, I'm used to it but there is really a disturbing detail which disrupts my ideas and my structure. 
the solution is simple

solution 1: force the map fields to always respect the established order of field setting.
solution 2: allow us to arrange all the map fields according to our composition

😕Confusion and disorder
![maps setting](https://user-images.githubusercontent.com/82481592/115748306-f4efbb00-a38d-11eb-93ba-39c294b88936.jpg)

![update options](https://user-images.githubusercontent.com/82481592/115748381-0638c780-a38e-11eb-80b3-b0626015e967.jpg)

🐛Bug forms with "page option"

I created an option page with simple company phone, mail etc fields
I created a form to update this information, everything works fine, except if you want to update with value "empty" it doesn't work.
in backend it works.

![site option](https://user-images.githubusercontent.com/82481592/115750034-a3483000-a38f-11eb-94e0-2b53f6ae0d4d.gif)

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
