### ISSUE TITLE
Some bugs in IPhone X with Safari browser using JetTabs and JetWooBuilder in the construction

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#3069]
I'm in the process of finalizing and delivering to the customer a delivery system, when asking a group of friends to carry out tests for bugs, only two friends reported me failures when trying to add the item to the cart, and also when trying to access the other tabs of the site as "Combos e Bebidas", both use IPhone and the browser is Safari.

The Bug and details:

1 - By clicking on ADD to Cart ("PEDIR") the site reloads.
2 - By clicking on the Tab ("ESFIHAS, COMBOS & BEBIDAS") the site reloads again.

Below left the video

https://user-images.githubusercontent.com/6773491/115766793-c1596480-a37e-11eb-9e5e-e43b1adc02d1.mp4

**Comment by dyonatandias** [comment]
same error here

**Comment by UraraReika** [comment]
@tizum @dyonatandias 
Do you use this option https://prnt.sc/11wuzte?

**Comment by dyonatandias** [comment]
no

**Comment by tizum** [comment]
I found that the problem shown in the video is caused only if the add to cart button is clicked before the Elementor / Page is fully loaded, as the ajax function does not work correctly and passes the url on the link and reloads each time it is clicked on any other item ...

The bug keeps happening, but only with people who click quickly to add some product, what do you recommend me to do in this case?

**Comment by UraraReika** [comment]
@tizum in this case you can use cache plugins and setting up correctly. Jr you can use preloader to hide your page before its fully loaded.

**Comment by tizum** [comment]
@UraraReika thanks, this issue has been resolved, preloader is a great option!
