### ISSUE TITLE
jetwoobuilder - how to edit the view-order endpoint

### ISSUE THREAD

**Issue by justrahe** [CrocoBlock/suggestions#3071]
Hi there
I am customizing My Account and got things working. Jetwoobuilder provides widgets to style the content of the main endpoints (like adress, order, etc. ) but what is about the other endpoints. sure I can visulaize all endpoints using the myaccount widget in the dashboard, but I ca not custimize the design. just to be clear, the endpoint "order" is showing the table of my orders and a button to "view order". once I hit the button, a new endpoint shows up (endpoint "view-order") but in the default style and as my customized styles....  any idea how to solve this?

**Comment by UraraReika** [comment]
Hello @justrahe .

We provide this functionality in the latest release. This style controls placed in  My Account Content widget https://prnt.sc/11wtulw

**Comment by justrahe** [comment]
Thank you for your advice. I guess it will work for me, unless for some  woocommerce extention endpoints like woocommerce bookings with specific endpoints for the bookings – which I can´t edit than I fear. Any tip how to edit those endpoints?

 

 

Da: Oleksandr Rudyi ***@***.***> 
Inviato: Freitag, 23. April 2021 08:13
A: Crocoblock/suggestions ***@***.***>
Cc: justrahe ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Crocoblock/suggestions] jetwoobuilder - how to edit the view-order endpoint (#3071)

 

Hello @justrahe <https://github.com/justrahe>  .

We provide this functionality in the latest release. This style controls placed in My Account Content widget https://prnt.sc/11wtulw
