### ISSUE TITLE
Some important suggestions for improving the widgets of the jet woobuilder plugin checkout page. please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3072]
Suggestions for checkout page widgets :
1- Please add a feature so that we can delete this text completely. : https://prnt.sc/11x1oru
2- Please add a feature so we can make this button full width. : https://prnt.sc/11x1qb9
3- Please add a feature to this widget so that we can heighten its field. That would be great : https://prnt.sc/11x1t3n
4- Also the ability to edit these two texts.If this happens, no plug-in will be needed. : https://prnt.sc/11x1vo4
5- Another thing that is very important. And I personally look forward to it, it's covered in this issue. # 2974
These will be great if added. Please check.
Thanks to the unique crocoblock team.

**Comment by UraraReika** [comment]
1 - Check default WooCommerce customizer settings https://prnt.sc/123eo3f
2 - done
3 - done
4 - done
5 - Will add in some future release

**Comment by 79ho3ein** [comment]
thanks. You are wonderful

**Comment by 79ho3ein** [comment]
When will the new version be released?
