### ISSUE TITLE
Advanced carousel and number of slides to scroll

### ISSUE THREAD

**Issue by pako69** [CrocoBlock/suggestions#3076]
Could you please add 3 differents settings for the[ slides to scroll options](https://i.postimg.cc/d10XsyvQ/slides-to-scroll.jpg): 

1. desktop
2. tablet
3. mobile

Because if I set 5 slides to scroll and I'm on a mobile it jump to far ins the slides.

Thanks

**Comment by Floydtm** [comment]
Which plugin does your request refer to?

**Comment by pako69** [comment]
JetElements 2.5.6

**Comment by kaskad88** [comment]
Added in JetElements 2.5.8
