### ISSUE TITLE
A very practical idea for the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3077]
Please add a feature so that we can show the user the remaining discount time. Like this picture: https://prnt.sc/11xcbrg
This feature is really great. I count the moments to add it.
Of course, please add this feature to the product grid widget if approved.please check

Thanks to the great crocoblock team.

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Sorry but we will not implement this feature to our core! There a lot op plugin with that kind of functionality and you can easelly use it and put whatever you want by rewritten one of products grid templates.
