### ISSUE TITLE
A very practical idea for the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3078]
Please add a feature so that we can display the number of products sold or left over from the special sales product as an image.
https://prnt.sc/11xci0e
This feature will be excellent and practical.
Of course, please add this feature to the product grid widget if approved.

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Sorry but we will not implement this feature to our core! There a lot op plugin with that kind of functionality and you can easelly use it and put whatever you want by rewritten one of products grid templates.
