### ISSUE TITLE
An idea for combining issues # 3016 and # 2974 for jet woobuilder checkout page.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3081]
You can design a payment form as an elementor form widget, which has the default WooCommerce fields. : https://prnt.sc/11yjnlo
Also, like the elementor form, put an option called step between the default fields, so that the web designer can customize the payment form in several steps. https://prnt.sc/11yjrh6

This feature is unique. Please review it and share your opinion in this regard.
thanks.

**Comment by UraraReika** [comment]
I merged this issue with #3016, which is on the same subject so we could deal with it more efficiently.
