### ISSUE TITLE
Request a feature for a single product page in the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3084]
Please add a feature to the Add to Cart widget, so that if the product was not available, the previous button would remain the same, but instead of the Add to Cart text, the text "Not Available" will be displayed to users.
Currently, for a non-existent product, the Add to Cart button is hidden and the phrase "Not Available" is displayed instead. And it does not have an interesting user interface.
please check

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein ! 

For single add to cart widget we use default WC function for displaying add to cart functionality and we will not add such feature for custom purpose. But we provide template system where you can rewrite widget template and implement whatever you want functionality.
