### ISSUE TITLE
A suggestion for the jet smart filter plugin paging widget.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3087]
Please add a feature to this plugin, so that with one button, we can display more products in Ajax, on the store page or product archive. More upload button :  https://prnt.sc/11zv8bj

**Comment by Floydtm** [comment]
For this you cam use listing grid https://crocoblock.com/knowledge-base/articles/jetengine-how-to-use-load-more-functionality-within-listing-grid-widget/
