### ISSUE TITLE
🐛[Jetengine Bug] Display name does not display the name (what?)

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3089]
Hello ,
I come across a very annoying bug that can create disasters if not fixed.
basically while changing names in profile. dynamic value "display name" does not update with new changes.

Watch carefully
imagine you have people updating their names in their profiles

![changname](https://user-images.githubusercontent.com/82481592/116010736-cafdf900-a618-11eb-8c2a-a7b14edfd5cd.jpg)

Result here

![changed my name](https://user-images.githubusercontent.com/82481592/116010759-013b7880-a619-11eb-89fa-a5d1b135f77e.jpg)

"display name" cannot update the name... (what? wait..) by investigating more in wrodpress> users> profile

![changed name](https://user-images.githubusercontent.com/82481592/116010681-5d51cd00-a618-11eb-9fa8-6d2fd8ec2de8.jpg)

It seems that wordpress has struggled to manage this change it keeps the old name "John Doe".

Imagine you have 200 people updating their names .. it's over your site is showing incorrect information.

The solution is to force the information to be updated and respect users' modifications.

while waiting to see what causes this bug in wordpress.

**Comment by kaskad88** [comment]
Thanks for your feedback.
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue.

Thanks.
