### ISSUE TITLE
JetSmartFilters: hide filters on specific archive pages

### ISSUE THREAD

**Issue by donderjager** [Crocoblock/suggestions#309]
I currently run on a website with Elementor Pro + Hello Theme + JetSmartFilters and JetEngine.

I have the issue that JetSmartFilters are showing all taxonomy's on specific category archive pages.

What I want is that JetSmartFilters is only showing filters that are used on specific post on that specific category page.

For example see: https://quiza.nl/quiz/star-wars/

I have posts that share the same taxonomy's. Like Difficulty - Medium. If I check this filter it's also showing posts from another category. 

If I uncheck the filter it even shows up all my posts on my website. 

Please let me know if there is a solution.

**Comment by davidk82** [comment]
yes!!! pls realize this feature soon. thanks!

**Comment by vincenzoquarta** [comment]
Same feature request!

**Comment by Floydtm** [comment]
Guys, currently, filters cannot work like this. But, as an option, you can make a custom template for any taxonomy and display the desired filter there

**Comment by paradisiacor** [comment]
We need this, otherwise you need 200 templates if you have 200 categories.
