### ISSUE TITLE
GDPR - Checkbox for acceptance of the confidentiality policy

### ISSUE THREAD

**Issue by RD4Ufr** [CrocoBlock/suggestions#3090]
Hello, a checkbox should be added to validate the acceptance of the GDPR confidentiality policy on the review form.
Because we need it in Europe to be on the guideline of legal properties.
Thanks a lot for your hard work.

**Comment by Floydtm** [comment]
You can add a separate checkbox for this right now. It is in jet forms

**Comment by RD4Ufr** [comment]
Thanks for the info.
However, I do not see how to implement it, and I do not find any documentation.

**Comment by Floydtm** [comment]
Unfortunately, we don't have a suitable tutorial. You'd better contact our support team to resolve the issue.
