### ISSUE TITLE
Customer service agent told me I bought a license from a fake site.

### ISSUE THREAD

**Issue by tsaijamey** [CrocoBlock/suggestions#3091]
I bought a 'crocoblock license key' from a really formal website via Youtube AD.
And it's really cheap.
And It sent me a license in deed.
And the license can active the crocoblock plugin.
I was happy of course. I thought it might be some coupon partner of Crocoblock. God knows.

And today I got some problem when the jetfilter ajax doesnt work correctly, so I search CROCOBLOCK via Google, and I want to ask a question and I think maybe some issue document or link would just help. And then an agent of customer service connected.

She said, sorry, the email you provided does not match.
I think 'Okay, I'll give the license.'
After she checked the license, again she told me the license is not sold from them.
I felt ... I dont know how to describe.
Then she said Sorry, we only provide support to our customer.

Okay, yeah, I bought a license key who pretends to be your coorprater. How should I know that?
And the agent again said, Of course they wont tell you they are not.
How Could I Know That?
And the point is : DO YOU SERVE YOUR USER or DO YOU ONLY SERVE MONEY?

Yeah, I'm so sorry, I made a stupid mistake I thought that's a coupon site BECAUSE THERE ARE COUPON SITES BEING IN THE REAL WORLD!
And if there is someone pretending to be your partner and YOU JUST DONT KNOW THAT, AND YOU DID NOTHING TO STOP THAT, it's my fault?
What kind of customer service you providing?
She only knows how to say 'sorry, but we are not responsive for you' for times and dont even ask what kind of problem you have.
WHY DONT YOU SAVE YOUR PLUGIN and DONT LET SOMEONE COPY THAT?
WHY DONT YOU SAVE YOUR BUSINESS?
WHY CANNOT YOU BE MORE FRIENDLY TO THOSE WHO MIGHT BE YOUR CUSTOMER CONTINUELY?

Okay, THAT Miss Victoriia, you're great.
It doesnt matter.
But I think anyone who would like to be your user, better to prepared his money, otherwise, it might be "who f**king care who you are and where you from, no monet? kick off."

Thanks for lesson.
THAT Great Customer Service Agent MISS VICTORIIA. Save your A**.

**Comment by Floydtm** [comment]
https://crocoblock.com/faq/#support
