### ISSUE TITLE
JetFilters: Is it possible too redirect users to listing site with custom filters activated?

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#3095]
Hello.

When our users check out this webpage - https://www.fornye.no/mobilabonnementer
Then can compare mobile contracts.

Is it possible we can make a uniqe link to let's say just show the 1 GB phone contracts?

" https://www.fornye.no/mobilabonnementer&data=1gb " would this be possible?

**Comment by Floydtm** [comment]
In theory, you can do this. Please contact our support team
