### ISSUE TITLE
An essential and practical suggestion for the jet smart filters plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3099]
hello
Please add a widget to this plugin so that we can display the filters in a slider on the mobile phone.
Just like this picture " https://prnt.sc/123d33w

Suggestion for the structure of this widget :
This widget can be a button, until the user clicks on it, the filters are displayed.
It should also be designed in such a way that the designer can place her filters in the theme builder element and in the form of sections.
Then connect the section designer to the new widget and the filters will be displayed.
Just like this widget in the elemntor plugin (https://prnt.sc/123dddh). The difference is that this widget does not have a button in elementor and does not open as a slider.
This feature is very important and the jet smart filter is in great need of it.

Of course, there is an easier way for this feature ...
Make the filters of this plugin compatible with the pop-up elementor.
So that we can open the pop-up as a slider and display the filters.

Please share your opinion in this regard. Thanks

**Comment by Floydtm** [comment]
Hi! Use jetpopup plugin or hamburger panel widget.please check before create new issue)
