### ISSUE TITLE
Add Post Timeline widget for JetBlog plugin

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#31]
Add Post Timeline widget for JetBlog plugin

**Comment by Pixelharmonist** [comment]
Long time ago, but i will happy with it, too! 
Someone find a way with cpt´s in timeline?

[Harmonic Greetings from the Pixelharmonie](https://pixelharmonie.de)

Stefan

**Comment by MjHead** [comment]
JetElements Timeline widget + JetEngine Query builder allow to create timeline for any data queried from the DB. https://crocoblock.com/knowledge-base/features/query-builder-overview/#advanced-carousel - here is an example for the Advanced Carousel widget, but for the Timeline works in the same way
