### ISSUE TITLE
JetBlog Smart Posts Tiles 

### ISSUE THREAD

**Issue by blueberry11** [CrocoBlock/suggestions#310]
1- Adding an alignment option for the custom field value (an ability to set the position of the content from the custom field). 

2- Adding a control, allowing set the size of the background of the custom field,  to change its dimensions.

Now it looks in such a way: http://prntscr.com/nz61yb (the arrow points to the custom field content.)

**Comment by kaskad88** [comment]
1 - done
2 - not approved

**Comment by kaskad88** [comment]
Added for next version (2.1.17)
