### ISSUE TITLE
A suggestion to improve the product number button on the shopping cart tab in jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3100]
These types of buttons are obsolete in modern design : https://prnt.sc/123ghyk
It would be great if jet woobuilder would update these buttons. Just like the picture : https://prnt.sc/123gmdn
Of course, this type of button is also available on a single product page : https://prnt.sc/123gp10
This feature is much needed. And it is very important for the user interface.

Thanks to the crocoblock team.

**Comment by UraraReika** [comment]
I merged this issue with #2711, which is on the same subject so we could deal with it more efficiently.

**Comment by 79ho3ein** [comment]
thanks
