### ISSUE TITLE
A unique offer for the payment page in the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3101]
Please add a feature so that the user can record their location on the map when registering their address on the payment page. In addition to the address field.
This feature is not required. But it is very practical. Because the user can register a more accurate address.

thanks.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
