### ISSUE TITLE
JetBlog (exclude displayed posts from other JetBlog widget on page)

### ISSUE THREAD

**Issue by worldoptimizer** [CrocoBlock/suggestions#3103]
![CleanShot 2021-04-26 at 14 32 15@2x](https://user-images.githubusercontent.com/1752114/116106801-b8d09900-a6b2-11eb-8d38-d19cc7443e66.png)

I have posts being displayed in different JetBlog elements. Now I want to avoid displaying the same item twice.

**Example:** 
(1) In one element I am displaying all posts with the tag "featured". 
In another element all post are displayed by specific categories… 

**Wish:**
(2) Now I want to exclude the posts from the category listing if they are featured above. Using an advanced query with tag_not_in doesn't work because also older post that had been featured before (we don't remove the tag every time) are now being removed from the element listing the categories. Hence, I just want to remove the posts from the featured element in the categories element, and we can't be excluding them each time by ID (manual process).

**Please, describe the feature request, making it clear to understand.**

Please allow a way to exclude posts that are already on page at the point of query 
**or even better** as it allows more control… please allow removing posts from a query that are displayed in another JetBlog widget on the same page . Meaning my favorite solution would be if I could configure in element (2): _exclude post displayed on the featured element (specific by some name or reference to the other element)_

**Comment by Floydtm** [comment]
Hi!yyou can exclude posts by id or use custom query

**Comment by worldoptimizer** [comment]
Both solutions don't work or require manual labor on each update.

**Comment by worldoptimizer** [comment]
You have been quick marking this "closed". Please, reconsider this evaluation as https://wordpress.org/plugins/ultimate-post/ is putting this feature on their roadmap.

Namely, you can't create an easy custom query to address articles currently displayed in another widget. Using IDs is an option but defies the purpose as it would require updating the exclusion every time a new article is posted manually.

I consider this request still "open"...

**Comment by Floydtm** [comment]
I closed your question because there is a solution for your request. You can contact our support team and the guys will help you solve this. Before closing this request, we checked it on our side. You should also understand that we do not provide support on the git.com, there is a support team for this. Thank you!

**Comment by worldoptimizer** [comment]
If you mean the query builder (JSON) than this is no solution. 

1. One JetBlog Element displays Tag **Feature**
2. One JetBlog Element displays Category **A** and **B** 

You can build a query that removes Tag **Feature** from the second (2.) but it removes them **all** and not only for the posts displayed in (1). You cannot remove the items from (1) without manual labor **each** time you create a new post.

The only solution that was presented **is not a practical solution for a news site** with daily posts is to **manually exclude the IDs each time** you create a new feature post. That is no solution, hence the feature request.

BTW I contacted support before making the feature request, and they said that there is no solution and that I have to create a feature request, and now you are telling me to contact support… my head is slowly spinning here.

**Comment by Floydtm** [comment]
We discussed this issue with the support team and understood your request. However, we will not be able to add this to the plugin right now. As soon as we collect more requests we will come back to this. Thank you!
