### ISSUE TITLE
Show the most searched words, in search results, in the jet search plugin.please chech

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3106]
Please add a feature to this plugin so that when users search, they will see the most words searched by other users.
This feature is very useful. Please check
thank you.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
