### ISSUE TITLE
JetEngine Archives Sorting and Excluding Posts

### ISSUE THREAD

**Issue by simplicity17** [CrocoBlock/suggestions#3107]
At the moment, once "Archive Template" is switched on for the Jet Listings template, all other functionality goes out the window. You can't sort posts. You can't set the number of posts to display per page on that specific archive. You can't exclude certain posts based on their taxonomy, etc. You can't show "Featured" posts at the top of the page in one layout and the remaining archive below in another layout.

This all seems like it should be pretty basic functionality based on what is already included with JetEngine, but for some reason, archives are severely lacking in functionality. Due to this, JetEngine users need to create numerous archive templates for the same taxonomy, which is a huge pain and defeats the purpose of having a template.

There should at least be a way to pull in posts on a taxonomy archive that share that taxonomy term. At the moment, there is no way to do this, so one must rely on the Archive Template switch.

**Comment by Floydtm** [comment]
You're right, but use archive should work this way. Stay tuned for updates we are going to redo the requests
