### ISSUE TITLE
A suggestion for the jet woobuilder plugin payment page editor that will be added in a future update.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3108]
Please let us edit the fields of the drop-down fields. Such as city and province field : https://prnt.sc/124r3j1
This section requires customizations such as padding, font changes, color and background color in hover and active mode.
----
There is also a search box in these fields, which would be great if it could be edited : https://prnt.sc/124rgdu

Thank you for your efforts

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Due to specific render on page we can add controls for styling select2 parts.

**Comment by 79ho3ein** [comment]
thanks
