### ISSUE TITLE
Dynamic Terms widget

### ISSUE THREAD

**Issue by blueberry11** [Crocoblock/suggestions#311]
У меня есть кастомные таксономии с пользовательским полем (сustom_taxonomy_logo). Данная таксономия применяется в Custom Post Type.

При организации листинга Custom Post Type, я хочу вывести значение поля Custom_taxonomy_logo при помощи виджета Dynamic Terms, но виджет позволяет вывести только название термина.

Добавьте пожалуйста возможность вывода и преобразования пользовательских полей таксономии.

I have custom taxonomies with a custom field (custom_taxonomy_logo). This taxonomy is used in the custom post type. 
When I create a custom post type listing, I would like to display the value of the Custom_taxonomy_logo field with Dynamic Terms widget, but the widget allows displaying only the term value.

Please, add an option to display and change custom fields of taxonomy.

**Comment by Floydtm** [comment]
Sorry, this widget is not intended for displaying custom images.
