### ISSUE TITLE
Add the ability to display the most visited products to the product grid widget of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3110]
Please add a feature to this widget so that we can display the most visited products to customers on the home screen.
This feature is very practical and user-friendly.

Please check,thanks

**Comment by Lonsdale201** [comment]
+1

**Comment by UraraReika** [comment]
For now and for future we will not add this functionality. There are a lot off plugins that add view functionality and create custom field for this purpose. Whet you set up such plugin then with the help of hooks for products grid or list widget you can query products depending on count of view. In you want to display counter you can rewrite widget template.
