### ISSUE TITLE
If possible, please add the jet woobuilder Paging widget to the plugin's public widgets.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3111]
If we want to use the product grid widget of this plugin in the theme builder to display the elementar plugin products as an archive, there is no paging widget for this plugin.
The paging widget is only available in the jet woobuilder plugin store section.
I think the paging widget includes general widgets and is very useful.
It would be great if we could use this widget in the theme builder of the elementor plugin.
This is a request of many users of this lovely plugin.

Please check.Thanks to the powerful crocoblock team.

**Comment by UraraReika** [comment]
We will not implement this functionality. Use JetSmartFilters pagination instead.
