### ISSUE TITLE
Add the Hover effect feature to the product grid widget of the jet woobuilder plugin.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3113]
Please add a feature to this plugin(product grid widget), such that when the user hovers the product box (https://prnt.sc/125kj1f) ,The product box will move up slightly. This feature greatly improves the user interface.
I am currently using this code for this mode :

**.jetwoo_sale .jet-woo-products__inner-box:hover {
    transform: translateY(-2px);
}**

Please check this feature.
Thank you.

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Sorry but for now and nearest future we will not implement this functionality.

**Comment by 79ho3ein** [comment]
Thanks.
