### ISSUE TITLE
[Bug] Jetcomparewishlist

### ISSUE THREAD

**Issue by jazir555** [CrocoBlock/suggestions#3116]
**Describe the bug**
I got this email from my wordpress installation: WordPress version 5.7.1 Current theme: Astra Child (version 1.0.0) Current plugin: JetCompareWishlist For Elementor (version 1.3.3) PHP version 7.4.8 Error Details ============= An error of type E_COMPILE_ERROR was caused in line 68 of the file /wp-content/plugins/jet-compare-wishlist/includes/settings/manager.php. Error message: require(): Failed opening required '/wp-content/plugins/jet-compare-wishlist/includes/settings/subpage-modules/compare.php' (include_path='.:/opt/php-7.4/lib/php')

**To Reproduce**
Unsure, happened automatically

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: centos 8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UraraReika** [comment]
Hello @jazir5 !

How often this error appears?

**Comment by jazir555** [comment]
I don't know, I've only received 1 error notification from the automatic
wordpress emails, but the site became slow and unusable once it occurred

**Comment by UraraReika** [comment]
Please contact our support team.
