### ISSUE TITLE
Add the ability to display WooCommerce notifications as a pop-up in the jet woobuilder plugin. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3117]
I apologize for making this request again.Because as a user of the jet woobuilder plugin, I find it very necessary.
WooCommerce notifications are currently displayed very poorly. Which has a very bad user interface.
WooCommerce notifications include adding the product to the cart, applying coupons and payment page messages, etc. that you are aware of.

Suggest to implement this request :
Please add a **pop-up template** in the **template builder of this plugin**. Just like the photo: https://prnt.sc/125sam3
By creating it, we can edit WooCommerce and pop-up messages.These edits can include the following :
**1- Length and width of the pop-up**   **2- Pop-up location**   **3- Color and size of WooCommerce notification text**
**4- And other pop-up settings**
Please check this and add it to the plugin soon. There are currently no plugins for this. I count the moments to add it.

Thanks to the great crocoblock team. I hope this feature is added.

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently.
