### ISSUE TITLE
A suggestion for the jet woobuilder plugin checkout page editor that will be added in a future update.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3118]
Please add this feature for the payment field so that we can specify the width of each field as a percentage.
In this case, we can display the fields in two columns with a width of 50/50.
Just like the form widget fields in the elementor plugin.
Please check.

Thanks🌹🌹🌹

**Comment by UraraReika** [comment]
I merged this issue with #2974, which is on the same subject so we could deal with it more efficiently.
