### ISSUE TITLE
Smart Filtering Result Count

### ISSUE THREAD

**Issue by flyartcom** [CrocoBlock/suggestions#3119]
Hello Dev Team

I would welcome a feature that seems essential to me. As of now it is not possible to show a product count result when applying smart filters but I think any eCommerce shop should be able to display the number of products available after smart filtering.

As the Product Grid does show the filtered product and the pagination to display those products it should be possible (much like the "Product Result Count") to Display the total of available products resulting from the smart (combined) filtering as well as the amount shown on the selected resulted page (showing 1-16 of XX products).

Any solid web shop should show the customer how many products result from their filtering.

Thanks for considering
Pascal

**Comment by Floydtm** [comment]
Hi, we are working on this feature. Keep for updates. Thank you!

**Comment by flyartcom** [comment]
Hi Floyd

That’s great news.. do you have an approx. time frame of when to expect that feature in the updates?

Thanks, Pascal
