### ISSUE TITLE
How do I set a minimum predetermined number of days?

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#3122]
Hello,
I need to be able to set the shortest booking days
JetBooking does not currently support such a function, but such a function is a common function in many Booking modules.
Can such a function be developed or is there any alternative?
Thanks.

**Comment by Hammer-ger** [comment]
You Can do ist with logical conditions in forms.

Hide the submit Button, if traveldate(number of booked nights) is lower than a specific number.

Then it is not possible to book (submit) if the number of nights is too short.

Stay safe

**Comment by UraraReika** [comment]
I merged this issue with [#1833](https://github.com/Crocoblock/suggestions/issues/1833), which is on the same subject so we could deal with it more efficiently.
