### ISSUE TITLE
Suggestions for improving the product description and comments section, on the single product page of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3124]
Please work more on this widget. It does not have a good user interface at the moment.
For example, the two sections highlighted in the image have many problems that I will describe : https://prnt.sc/1277vr8
The link of each tab does not completely cover the field. It only links around the text. That is, only the black box has a link.
Also, if we color the background, only the part that has the link will be colored, while the whole background should be colored.
The problem is clear in this image : https://prnt.sc/12786hr
Please add settings so that we can edit the margins of these tabs. We can not give it any style at this time : https://prnt.sc/1278f3l
Also, at the beginning, middle and end of each tab, there is a point that is not interesting at all : https://prnt.sc/1278jn0
please check.

thanks

**Comment by P-happiness** [comment]
+1
