### ISSUE TITLE
An important suggestion for improving the single page of the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3125]
Please add the ability to edit the user comments section of this plugin. https://prnt.sc/1278n7q
The comments section is very important. And now its editing is much needed.
Now, its appearance is by default. Which does not look interesting at all.
It will be great if you add this feature because there are no plugins for this section.
For now, I edited this section with code, but if you add this feature so we can edit this section, it will be a great achievement.
Please review this request. thanks.

**Comment by UraraReika** [comment]
You can use our JetReviews plugin.
