### ISSUE TITLE
Register before paying. Jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3126]
Please add a feature to the payment page, so that if the user is not registered, she will not be able to see the payment slip.
And be redirected to the registration form.This feature will be very useful.Of course, this feature can be optional.The designer may not be willing to do this.
please check.

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Before leaving issues request please make sure that this is our problem or our product cause it. Because there is such option in WooCommerce https://prnt.sc/127ej50.
