### ISSUE TITLE
Button number of products in the cart

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3129]
Now, the button to increase or decrease the number of products in the shopping cart is very old.And does not have a good user interface. It would be great if you could update the look of these buttons.Of course, this type of button is **also available on the product page.**
The suggested model for these buttons is as follows :  https://prnt.sc/127prrv
please check

thanks.

**Comment by P-happiness** [comment]
+1

**Comment by Hans-101** [comment]
+1

**Comment by Hans-101** [comment]
Could be merged with https://github.com/Crocoblock/suggestions/issues/2711 Quantity selector can be a widget added anywhere

**Comment by Dhaump** [comment]
+1
