### ISSUE TITLE
JetWooBuilder Products Grid: Gutter settings don´t take effect for Woo shortcodes

### ISSUE THREAD

**Issue by shenom-x** [CrocoBlock/suggestions#313]
It´s quite simple...

If You use any kind of Woo shortcode to display products in a grid view the widget gutter settings don´t take any effect.

**Comment by Floydtm** [comment]
@shenom-x Hi, Could you show where you cannot adjust the padding between the columns. If possible, add a screenshot or video.

**Comment by shenom-x** [comment]
@Floydtm Simply use the shortcode [products] in a page and setup a WooBuilder archive products template. There set the gutter settings to '0'. It should not accept it.

**Comment by Floydtm** [comment]
@shenom-x these settings should not work for shortcode. They will be triggered by the item you are creating.

**Comment by shenom-x** [comment]
@Floydtm Why not? In Your settings of WooCommerce > WooBuilder I can choose to use a WooBuilder template for shortcode output.

![grafik](https://user-images.githubusercontent.com/29519284/59503031-a7f05300-8e9f-11e9-8cb1-a600a880323c.png)

So the gutter settings in the WooBuilder template should take effect!?

![grafik](https://user-images.githubusercontent.com/29519284/59503120-e84fd100-8e9f-11e9-9af2-e4e428879ea2.png)
