### ISSUE TITLE
Report a bug in the jet woobuilder plugin shopping cart

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3130]
image : https://prnt.sc/127q7dd
When we move the table cells (blue border) to the left in the shopping cart table widget, the product update button(green border)also moves with it.These two parts move together.
It would be great if you could add this feature so that we can move the Update Cart button(green border) to the right or left.
This bug has been tested on two different websites.please check

thanks

**Comment by UraraReika** [comment]
I merged this issue with #3048, which is on the same subject so we could deal with it more efficiently.

Before adding a new feature request, please, make sure you’ve checked:

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.
