### ISSUE TITLE
An offer for the jet woobuilder plugin payment page

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3131]
Please add the full width of the payment button to this plugin. This small item is very important : https://prnt.sc/127qvsn
Also, please add this feature so that we can give this part the desired height : https://prnt.sc/127qywc

Thanks to the great crocoblock team.

**Comment by UraraReika** [comment]
Dear @79ho3ein please stop cloning issue requests. You already create such an issue here #3072 and we done it just wait for release. 

Although before adding a new feature request, please, make sure you’ve checked:

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.
