### ISSUE TITLE
Please Add more load button to product grid widget in jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3132]
This feature will be very practical and modern.In this way, if the user wants to see a large number of products, he clicks the upload button more to add other products. This feature also greatly improves the user interface.
Of course, this feature can be a separate widget, or come with a product grid widget.
Please review this feature and share your opinion about it. 

Thank you.

**Comment by Hans-101** [comment]
Yes please, it's so much better than pagination in many cases!

**Comment by UraraReika** [comment]
I merged this issue with #2683, which is on the same subject so we could deal with it more efficiently.

Dear @79ho3ein before adding a new feature request, please, make sure you’ve checked:

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.
