### ISSUE TITLE
Add center option to Post Thumbnail (Image) in the Posts widget

### ISSUE THREAD

**Issue by tamarw** [CrocoBlock/suggestions#3133]
Just talked to Yura and there are options to center align all options (meta, button, etc) but not the post image itself, which makes it look really bad on mobile since the images are left aligned but the title/meta/buttons are able to be center aligned. Low friction change (I had to add CSS) but please consider adding an alignment option so I don't have to finagle with CSS. Thanks!

**Comment by kaskad88** [comment]
Added in JetElements 2.5.8
