### ISSUE TITLE
MiniCart is not working on Cart and Checkout pages

### ISSUE THREAD

**Issue by wdm-janis** [CrocoBlock/suggestions#3136]
There is a big UX issue that mini cart is not working, showing products on cart and checkout pages. The problem is on Zolden theme and on the MiniCart element itself. If you say, that is no need to show mini cart, then it is wrong. The header for all websites is one with mini cart icon.

**Comment by UraraReika** [comment]
Hello @wpxagency .

This isn't an issue.  Zolden theme has specific headers for this pages where minicart functionality disabled. Although this was like that always, as this is as WooCommerce works by default with mini cart. This is a feature, as you typically wouldn’t need to see the mini cart if you’re in the real cart or checkout – as the items are visible in this paeges.
