### ISSUE TITLE
Dynamic functonaility hotstpot widget

### ISSUE THREAD

**Issue by wpsumo** [Crocoblock/suggestions#314]
All features in the hotspots widget are missing dynamic functionality!

https://tppr.me/SH1LS
https://tppr.me/RLWaM

Please add dynamic:
- image
- title
- description 

Added notes to the prints, if you check them once again. Very easy and quick for you guys to implement since this is already supported in many of crocoblocks widgets and in elementor.

Please consider making all widgets supporting dynamic in the nearest future as well.

**Comment by Michael-sr** [comment]
Hi everyone!
Please add not only work with dynamic field data, but also work with data from the Repeater fields.
We need these fields from the Repeater fields:
Label
Description
Link
Horizontal position
Vertical position

https://prnt.sc/v3apv8

You are cool, I really appreciate you! Thanks for your work.

**Comment by kaskad88** [comment]
I merged this issue with #1486, which is on the same subject so we could deal with it more efficiently.
