### ISSUE TITLE
Report a bug in the jet smart filter plugin paging widget.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3140]
As you can see in the picture, there is no space between boxes 1 and 2 : https://prnt.sc/129rxsa
While I gave the distance between the boxes 5 pixels.
This bug only occurs if the active page is number 1.That is, if the active page is number 1, there is no space until the next box (2) and they are stuck together.
But if we select page 2, this distance (5 px) is observed between boxes 2 and 3 : https://prnt.sc/129s83c
Please investigate this issue. I have tested several websites and this bug was there.

thanks

**Comment by Floydtm** [comment]
@SargasTM check RTL ver. please
