### ISSUE TITLE
Add Quantity Label and Improve the design to a + and - field to Single Add to Cart #jetwoobuilder

### ISSUE THREAD

**Issue by DevDietheR** [CrocoBlock/suggestions#3142]
Hi, I Hope you can add this request as soon as possbile, This thing is missing in the widget. The label for quantity. I hope you can add the label for quantity and of course to style them. Here I only use pseudo trick to create a label text for quantity.
![image](https://user-images.githubusercontent.com/42364592/116633117-451cdd80-a98b-11eb-8cd4-394fba12f7e4.png)

**Comment by 79ho3ein** [comment]
+1

**Comment by xC4M** [comment]
+2

**Comment by UraraReika** [comment]
I merged this issue with #2711, which is on the same subject so we could deal with it more efficiently.
