### ISSUE TITLE
Please make jet smart filters plugin widgets compatible with popup elementor.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3146]
Please add this feature so we can slide the filters. Of course, this feature will only be used on mobile : https://prnt.sc/12apben
This allows the user to experience a great user interface.
At the moment, when we put the filters of this plugin on the pop-up, it does not find the products and does not work at all.
Please check this item. This feature will be excellent and practical.

thanks

**Comment by P-happiness** [comment]
+1

I've created the Off Canvas Filters (Jet SamrtFilters) with JetPopup and they work only if you query for JetWoobuilder Product Grid.
If you query for Woocommerce Archive (inside Shop Template) they do not work anymore.
I'm going to open a support request about this, but since this tread is opened, I think that it would be great to have full compatibility also with Elementor Popup.

**Comment by 79ho3ein** [comment]
Yes, this feature is very important. I hope this request is heeded, and added as soon as possible.
I also hope that others will welcome this request.
thank you.

**Comment by DevDietheR** [comment]
+1
This is very important feature

**Comment by DevDietheR** [comment]
Update here ?

**Comment by 79ho3ein** [comment]
@Floydtm 
hi, Is it clear when this feature will be released?
thanks

**Comment by Floydtm** [comment]
Guys, you must understand that this takes time. In addition to requests for the git, our team also has a road map. Right now you can use jetpopups they are compatible with our filters. You can also wait until your request is completed. Thank you!

**Comment by DevDietheR** [comment]
Thank you @Floydtm , may i know where i can see your roadmap ?

**Comment by 79ho3ein** [comment]
hello
excuse me @Floydtm
Will this feature be added in 2021?

**Comment by 79ho3ein** [comment]
Is it clear when this feature will be added? may you answer?

**Comment by Michaelgimii** [comment]
hello @Floydtm , Is there a time for the release of this feature?

**Comment by Michaelgimii** [comment]
hello @Floydtm
Is there any news about this? Please make us happy

**Comment by hamed-azimi** [comment]
This indeed is a must. Hope to see a fix soon.

**Comment by DevDietheR** [comment]
Up

**Comment by MjHead** [comment]
fixed with 2.3.10

**Comment by 79ho3ein** [comment]
thanks crocoblock Team!

**Comment by Michaelgimii** [comment]
Friends, does the price suffering filter in elementor popup work for you?
I use the price range widget and the active filter removal widget. When I activate the price range filter, it works as expected. But when I close the pop-up and open it again, the delete active filter button is not displayed.
This bug only exists in the price range widget. Do you have a similar experience?

**Comment by 79ho3ein** [comment]
> Friends, does the price suffering filter in elementor popup work for you? I use the price range widget and the active filter removal widget. When I activate the price range filter, it works as expected. But when I close the pop-up and open it again, the delete active filter button is not displayed. This bug only exists in the price range widget. Do you have a similar experience?

Yes, this bug is there for me too. I hope it will be fixed in the next version.

**Comment by Michaelgimii** [comment]
@Floydtm , Are you aware of this?

**Comment by Floydtm** [comment]
as far as I know this bug is written in another issue and will be fixed
