### ISSUE TITLE
Front End Form Checkbox And Select from Post Type Sorted

### ISSUE THREAD

**Issue by SonjaZ** [CrocoBlock/suggestions#3147]
It was requested that I add a feature request here for the Front End Forms.

When displaying a list of options for the users to choose from, it would be nice to have a sort feature or the ability to link a thumbnail to the selection/checkbox/radio.

This makes it much easier for end users to make their selection on the form. 

Since the items populate in the field based on ID that makes it harder for users to find a name in a list if it isn't sorted alphabetically or doesn't have a picture nearby. 

If either one would become a possible feature that would make it much for end users to enter front end content from a dynamic source. 

Thank you!

**Comment by Floydtm** [comment]
I think this option should help you https://prnt.sc/12goj5l

**Comment by SonjaZ** [comment]
I have tried making a custom item template, but I was unable to get the check boxes to populate. Have you had success with one? I would love to know if I was creating the template incorrectly!

**Comment by Floydtm** [comment]
It works. Contact our [support ](https://crocoblock.com/help-center/)team, they will help you with this
