### ISSUE TITLE
2 suggestions for jet smart filters plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3149]
1- Please add a feature to these filters, to show the user the number of products in each filler.
Just like the picture opposite : https://prnt.sc/12b3ebt

2- Please add a feature to the filters so that we can set the desired height for them.If the number of filters is large, the user can scroll the filters. Just like the image opposite : https://prnt.sc/12b3h9b
It would be great to be able to customize the navigation bar as well.Items such as background color, active scroll background, scrolling width, border curvature, etc.
please check.

thanks

**Comment by Floydtm** [comment]
Dear @79ho3ein before adding a new feature request, please, make sure you’ve checked:

if the feature is already added to the backlog or in work;
if the feature is missing from the products.
