### ISSUE TITLE
Please add loading mode to jet smart filters plugins.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3150]
It would be great if you add this feature to this plugin because it makes the user experience a great user interface.This feature can be used to activate filters or use the pagination of this plugin.
I will show you this suggestion in the form of an image : https://prnt.sc/12b3wmg
Now, when the filter is loaded, the screen fades a bit, which does not have an interesting user interface. please check

thanks

**Comment by DevDietheR** [comment]
+1

**Comment by Floydtm** [comment]
You can do this right now with the jetengine + jetsmartfilters plugin
