### ISSUE TITLE
Please add the ability to add the desired label to the product grid widget of the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3151]
This feature will be very useful. And greatly increases the conversion rate.
I will show you this request in the form of an image : https://prnt.sc/12b4o8e - https://prnt.sc/12b51w2
please check.

thanks

**Comment by UraraReika** [comment]
I merged this issue with #2680, which is on the same subject so we could deal with it more efficiently.
