### ISSUE TITLE
A unique offer for the jet woobuilder plugin.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3153]
It would be great if we could show the number of views of each product to the users.This feature can be added to the product grid widget so that the user can see the products as a slider.This feature can greatly increase the conversion rate.
I have not seen a similar example anywhere (for products, of course), I hope jet woobuilder is the first plugin to use this feature.
I simulated this feature with elementor to show you : https://prnt.sc/12bi42e
In my opinion, the best place to show this feature is in front of the price I have shown in the figure.
Please check.

Thank you

**Comment by UraraReika** [comment]
I merged this issue with #3110, which is on the same subject so we could deal with it more efficiently.
