### ISSUE TITLE
🔥[Jetengine forms] improve the use of featured images and declare war against duplications 

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3154]
Hello ,
a little attention please this is a problem that concerns everyone and we must have this small improvement at least in [DevTools ](https://crocoblock.com/freemium/tools/) and then integrate it to jetengine core because it will be difficult to do otherwise. 
we will see how this functionality will become vital today. and the people will claim it day and night.

not to mention the savings in storage space and performance and time for all users without exception.

First thing to note, there are two types of uses for featured image

Type 1 :
blogs and all the sites where you need a different thumbnail image.

quick example:

![blog thum@2x](https://user-images.githubusercontent.com/82481592/116785064-7e3e7600-aa8f-11eb-919a-d027ef01db2f.jpg)

Type 2 : 
dynamic sites where you need to choose an image for thumbnail among the uploaded images. it is our case which was not taken into account and which poses a problem today.

quick example:

![dynamic thum@2x](https://user-images.githubusercontent.com/82481592/116785072-87c7de00-aa8f-11eb-965a-63316ed72374.jpg)

The solution : 

![solution thum@2x](https://user-images.githubusercontent.com/82481592/116785079-90b8af80-aa8f-11eb-94bb-97613bd2a47c.jpg)

note about the delete button, it may be preferable to display a confirmation message before directly deleting the image because it often happens that we click on delete without wanting it, especially when we want to reorganize the order . 
it comes into the fight against duplications, having to re-upload an already uploaded image. 

Final word :)

When it comes to working efficiently with hundreds of posts and especially opening uploads to users. 
featured image in its current form... left to the **mercy of users** is no longer an option as it will generate more duplicates and problems than solutions.

 where I get my references :

[Realhomes](https://themeforest.net/item/real-homes-wordpress-real-estate-theme/5373914)

![realhomes](https://user-images.githubusercontent.com/82481592/116820079-08a7d800-ab6b-11eb-9178-cdd9163c2c45.jpg)

[Wpresidence](https://themeforest.net/item/wp-residence-real-estate-wordpress-theme/7896392)

![wpresidence](https://user-images.githubusercontent.com/82481592/116820083-0b0a3200-ab6b-11eb-9934-ef5cb0622ffc.jpg)

[Houzez](https://themeforest.net/item/houzez-real-estate-wordpress-theme/15752549)

these 3 big themes have a huge user base and feedback their submit forms are very mature and watch carefully (demos or buy them for the sience) they have concluded the same structure for uploads. it is not a coincidence it is a fact that must not be neglected at crocoblock to create better sites  and of course in order to align with the standards of our days .

**Contribution for the implementation**
Depending on the case 
the easiest way I have found this could be a checkbox in field media to enable the super uploader. and delete _thumb for example. 

![modern](https://user-images.githubusercontent.com/82481592/116821185-c1244a80-ab70-11eb-80b5-be18774cf06a.jpg)

I Show you how I was doing before jetengine 
in an old site, before migrating to jetengine I was using acf and I had this little magic code which precisely ensures that the first photo of the gallery is the featured image that could help developers a lot to understand

```
/**[ACF] [PHP] First Image Gallery To featured Image**/

add_filter('acf/save_post', 'gallery_to_thumbnail');
function gallery_to_thumbnail($post_id) {
	$gallery = get_field('property_photos', $post_id, false);
	if (!empty($gallery)) {
		$image_id = $gallery[0];
		set_post_thumbnail($post_id, $image_id);
	}
}

```

if this method is also added, users will only have to arrange the photos according to their preferences 

![explain](https://user-images.githubusercontent.com/82481592/116837365-0e7cd800-abc2-11eb-9859-78e7f63c3fdb.gif)

**Comment by kaskad88** [comment]
Hi @nreljed 
The following code makes the first photo in the gallery the featured image of the post. 

```
add_action( 'save_post', function ( $post_id ) {

	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
		return;
	}

	$gallery_key = 'property_photos';

	$gallery = get_post_meta( $post_id, $gallery_key, true );

	if ( empty( $gallery ) ) {
		return;
	}

	$gallery = explode( ',', $gallery );

	$image_id = $gallery[0];
	set_post_thumbnail( $post_id, $image_id );

}, 99 );
```

**Comment by elhobe** [comment]
thanks for this! works really good 🎉

**Comment by lifeact** [comment]
follow

**Comment by galaxyp100** [comment]
Hi, is it possible to avoid the Featured Image being duplicated in the Gallery? At the moment if you open the featured image in a lightbox and press the next arrow for the next image it is the Featured Image repeated again? Thanks :)

**Comment by tunacan34** [comment]
Also need big button to change images order
