### ISSUE TITLE
Please add the random archive feature to the product grid widget of the jet woobuilder plugin.Of course when the current quary is active.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3155]
Please add this feature so that we can display the products randomly. Of course when Current Query
 is active.
Now when Current QueryActive, we can not display products randomly. https://prnt.sc/12d7g50

thanks

**Comment by UraraReika** [comment]
When you enable Current Query option query for product grid taken from customizer settings https://prnt.sc/12gneyv. You can although extend this option with WooCommerce hooks like this https://rudrastyh.com/woocommerce/change-defaut-product-sorting.html.
