### ISSUE TITLE
Report an important bug in the jet woobuilder plugin. please check it

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3156]
When we make a number of product carousels with the product grid widget,for example 6 for desktop and 6 for mobile and tablet ...
If the navigation point of this widget is active, it should be active for everyone. Otherwise, it will bug. : https://prnt.sc/12dfjfs
For example, I wanted up to 6 product carousels on the desktop to have no navigation point.
But have a mobile phone and tablet.
But when I disabled the navigation points on the desktop, all the navigation points got into trouble. **Even the navigation points of the slider widget in the elementor pro plugin** (https://prnt.sc/12dfz8m).It would be great if we could disable the navigation points for some things, but without any problems.
I tested this problem on various sites and it existed.
I hope this problem is solved soon.

thanks

**Comment by UraraReika** [comment]
You dont need to disable pagination.
For example i want to display 6 products on my homepage i put options like this https://i.gyazo.com/5751afcd9873c9a587ea01a1d394ed3f.png on desktop https://i.gyazo.com/2cbe40c091a592af71b14176149467fa.png - tablet https://i.gyazo.com/a9b139e845caf8e40c670ced6c52e0b9.png - mobile. And such carousel options https://i.gyazo.com/1ede7f7c26fb9be0a733fba5a55dceb8.png. All works grate.
