### ISSUE TITLE
A suggestion to improve the widgets on the single page of the jet woobuilder plugin product.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3157]
Please add this feature so we can edit the profile section. This section is very important for users, but unfortunately at the moment it does not have a good user interface and we can not edit it. https://prnt.sc/12e5ghm
please check

thanks

**Comment by UraraReika** [comment]
For achieve this you can use Table Widget from JetElements plugin, and with the help of Elementor Pro dynamic terms output needed information https://prnt.sc/12m4xmf. Then put this template in jet tab and style it whatever you want. If you have difficulties with this please contact our support team.
