### ISSUE TITLE
Re-request for the single page of the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3158]
hello
A very important feature that jet woobuilder lacks is displaying product colors on the product page.
It is unbelievable that such a large plugin lacks this feature.I make this request again with the proposal...
As you can see in the image below, the product colors are displayed to the user.And whatever color the user hovers, the name of that color is also displayed : https://prnt.sc/12e5rgd
This feature is extremely important to add to this plugin. This is a request of many users of this great plugin.
I hope the crocoblock team pays attention to my request, which is requested by many users.

thanks

**Comment by DevDietheR** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with #361, which is on the same subject so we could deal with it more efficiently.
