### ISSUE TITLE
JetBlog

### ISSUE THREAD

**Issue by JDoukaga** [CrocoBlock/suggestions#3159]
It would be nice if we could have the number of views of each item on the grid (Much like on airpano.com or kuula.co/explore) and a badge for the categories or tags.
Thank you !

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
