### ISSUE TITLE
An important request for the jet woobuilder plugin.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3160]
Please add a feature to this plugin (especially the product grid widget) so that we can display the colors of the products in the archive to users. This feature is very practical and modern.
There is a similar item in this image : https://prnt.sc/12eep7w
Please check these features. Because the most up-to-date and professional sites use these facilities.
I hope to see this feature in jet woobuilder as soon as possible.

Thanks to the powerful crocoblock team.

**Comment by UraraReika** [comment]
https://crocoblock.com/troubleshooting/articles/how-to-add-attractive-variation-swatches-to-woocommerce-archive-page/
