### ISSUE TITLE
Result Counts should work on Filtering 

### ISSUE THREAD

**Issue by DevDietheR** [CrocoBlock/suggestions#3161]
Hi I'm gonna open this issue again, It's been a longtime but still this is not still added or prioritized. This one is pretty easy function.
Currently the result counts only works on a search result but in filtering it doesn't
![image](https://user-images.githubusercontent.com/42364592/116844806-c045f400-ac16-11eb-9cef-387d90b1e188.png)
![image](https://user-images.githubusercontent.com/42364592/116844793-b6bc8c00-ac16-11eb-988a-31744cc3112f.png)

Sample: https://demos.wpgridbuilder.com/?_product_brand=my-accessories

**Comment by Medienor** [comment]
+1 This should be a basic function with a filter widget!

**Comment by 79ho3ein** [comment]
Hello
Do you mean this part? https://prnt.sc/12fe72c

**Comment by UraraReika** [comment]
I merged this issue with #2592, which is on the same subject so we could deal with it more efficiently.
