### ISSUE TITLE
🔥Using the wp-rocket plugin, an important bug is created in the jet woouilder plugin.please check🔥

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3163]
I wanted to show the last visited products to users using the product grid widget (Using the query in product grid widget widget)
But when I entered the site as a guest user and saw a product, instead of one product, two products were added to the list, while I had only visited one product. This problem was repeated in other visits. I checked and found that if wp-rocket is enabled, this problem will occur.
Rocket plugin is used in many sites and can cause problems for users of the jet woobuilder plugin.
Please, please check this item and fix it.

**Comment by UraraReika** [comment]
If you query by Recently viewed in this case we use `woocommerce_recently_viewed` cookie that is default for WooCommerce. So this is not JetWooBuilder problem. Every widget or product loop that use this cookie will struggle. In this case you need to configure wp-rocket. Just exclude this cookie from wp-rocket.
