### ISSUE TITLE
Report a bug in the buttons of the jet smart filter plugin.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3164]
Buttons such as the Price Range Widget and Search Widget have a focus mode by default. That is, when the user clicks on the button, it gets colored and this problem can be solved only with the code.
You can see this problem in the image opposite : https://prnt.sc/12f78ac
Please investigate this issue. thanks

**Comment by Floydtm** [comment]
We do not quite understand what the problem is. describe your request in more detail. also you can remove the hover in the widget settings

**Comment by 79ho3ein** [comment]
@Floydtm 
When the Price Range button or the Search button is clicked, the background of these two buttons is colored.
Checking with Inspect, it turned out that these two buttons now have a focus that changes color by default after clicking.

**Comment by Floydtm** [comment]
We checked everything and did not find this problem, but you can contact our support team, the guys will study it on your side. Thank you!

**Comment by Floydtm** [comment]
https://crocoblock.com/help-center/
