### ISSUE TITLE
Hello Theme - Must be able to set all Jetwoobuilder Templates to Full Width

### ISSUE THREAD

**Issue by DevDietheR** [CrocoBlock/suggestions#3165]
Hi This is a very important features need to implement, Hello theme is the most used theme in Wordpress. Currenlty it doesn't have a function to set a full width to Single Product Page. In Jetwoobuilder to set a single product page to full width you must do this every time.
![image](https://user-images.githubusercontent.com/42364592/116874526-0c5f5b80-ac4c-11eb-96b3-c3b4f59ab9b4.png)
Template Type > Set to Full Width, this is not a good way. We must implement a way to set this globally.

**Comment by P-happiness** [comment]
+1
I've got the same problem!

**Comment by 79ho3ein** [comment]
+1
Yes, it's really difficult to repeat this every time.

**Comment by UraraReika** [comment]
https://crocoblock.com/troubleshooting/articles/how-to-make-shop-template-full-width/.
 This guide although works for single product pages.

**Comment by DevDietheR** [comment]
@UraraReika Don't just close the issue lol, This issue wouldn't be here in the first place if your guide have that.
