### ISSUE TITLE
Forms - Ability to add images into the JetForms WYSIWYG area

### ISSUE THREAD

**Issue by jojopa** [CrocoBlock/suggestions#3168]
Hi, for JetForms it would be Extremely useful to be able to add pics into the post like the traditional Wordpress backend wysiwyg offers. 

An example of why it would be useful is if someone is explaining how they did something - explaining a little and showing pics under the explanation. (like what is possible using Tumblr) 

I haven't yet found any alternatives, besides traditional Wordpress _backend_ posts. But from the _frontend_ with Jetforms, and most forms, it's not possible. 

Thank you

**Comment by Floydtm** [comment]
For security reasons, we cannot fulfill your request. Thank you for understanding!

**Comment by ATSFNL** [comment]
> Hi, for JetForms it would be Extremely useful to be able to add pics into the post like the traditional Wordpress backend wysiwyg offers.
> 
> An example of why it would be useful is if someone is explaining how they did something - explaining a little and showing pics under the explanation. (like what is possible using Tumblr)
> 
> I haven't yet found any alternatives, besides traditional Wordpress _backend_ posts. But from the _frontend_ with Jetforms, and most forms, it's not possible.
> 
> Thank you

### Need this option also, 
WP USER FRONTEND pugin has this option. I switched to Crocoblock and then find out that this option is missing!
See other posts with same issue: https://github.com/Crocoblock/suggestions/issues/2586#issuecomment-879796065

**Comment by neylwalecki** [comment]
+1
