### ISSUE TITLE
Jet Engine: Enable Post Categories & Tags on Custom Post Types

### ISSUE THREAD

**Issue by greenstreetdesign** [CrocoBlock/suggestions#3169]
My wordpress posts have the following categories: Aviation; Hospitality; Technology

If I make a new Jet Engine Custom Post Type I cannot use those taxonomies! Why? I cannot understand why this isn't possible. Do I have to create all new custom taxonomies for new custom post types?  Am I missing something?

It is a simple thing to enable Categories and Tags in CPT and ACF. Please add this basic functionality!

**Comment by iamalsoandy** [comment]
Does "pending" mean that this is going to happen? 

I would like to be able to do this, without having create custom taxonomies.

**Comment by kaskad88** [comment]
This feature is already available.

1 - Go to JetEngine/Taxonomies page https://tppr.me/SpdRy
2 - Click to JetEngine/Build-in switcher https://tppr.me/BIycl
3 - Click the Edit button for Categories taxonomy https://tppr.me/lpE5i 
4 - Add CPT for Taxonomy https://tppr.me/1l3ba
