### ISSUE TITLE
Reload listing grid on success not working

### ISSUE THREAD

**Issue by sbc640964** [CrocoBlock/suggestions#3170]
**Describe the bug**
Reload listing grid on success not working, thet reload section to empty list

**To Reproduce**
1. create new data store (I did this on a meta user)
2. create listing item and use dynamic widget to add to store and check the reload listing grid
3. compare the listing grid id
4. try click on add to store.

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
