### ISSUE TITLE
Jet Product Gallery Slider - Thumbnails often not clickable 

### ISSUE THREAD

**Issue by technicompak** [CrocoBlock/suggestions#3172]
When clicking through the thumbnails quickly, not every click triggers a reaction. It seems like often a click is mistaken for a swipe and this leads to the feeling that the whole plugin is kind of unresponsive.

**Comment by UraraReika** [comment]
Hello @technicompak !

Please describe in more details or record video how to reproduce the issues.

**Comment by technicompak** [comment]
I tried to capture what I mean - the mouse movement is a bit overdone.


https://user-images.githubusercontent.com/4681129/117269697-ce835280-ae58-11eb-8f55-752cffb36d60.mov

**Comment by UraraReika** [comment]
We use Swiper Slider for our carousel gallery widget and by default this library use true for allowTouchMove. This option gives ability move slider by grabbing it with mouse or by touching it with finger (on touch screens). And this option triggers your issue. You can disable it by using this `filter jet-woo-product-gallery/slider/thumb-options` heres example 

```
add_filter( 'jet-woo-product-gallery/slider/thumb-options', '__your_theme_prefix_thumbnail_gallery_settings' );

function __your_theme_prefix_thumbnail_gallery_settings( $options ) {
	$options['allowTouchMove'] = false;

	return $options;
}
```
