### ISSUE TITLE
Ability to edit the tab widget description in the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3175]
Is it possible to add a feature so we can edit this section with jet woobuilder? https://prnt.sc/12gzhn5

thanks

**Comment by UraraReika** [comment]
Go to Elementor > Settings > General and enable Products Post type for editing https://prnt.sc/12h8l22. Press Edit with Elementro button https://prnt.sc/12h8nr9. In elementor editor style what you what and how you want https://prnt.sc/12h8qjw. Then this template will display in description tab https://prnt.sc/12h8s3t. Have fun.
