### ISSUE TITLE
A unique offer for the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3176]
It would be great if we could show the number of users who are visiting the product on the product page.
Just like the image I tried to simulate : https://prnt.sc/12h0tq2
This feature would be great

**Comment by UraraReika** [comment]
@79ho3ein, You mean real time viewers?

**Comment by 79ho3ein** [comment]
Yes, the number of users viewing the product at the same time as me.Depends on the number of online users.
I hope I have conveyed my point well.This feature will be very special and excellent and practical.
Thank you for your attention

**Comment by UraraReika** [comment]
Sorry, but we will not implement this functionality to our plugin.
