### ISSUE TITLE
 [JetSearch] hide 'out-of-stock' products from search results.

### ISSUE THREAD

**Issue by mymottow** [CrocoBlock/suggestions#3177]
Products which are out of stock show up in the JetSearch search results. Even when I activate the option "hide out  of stock products" in the woocommerce settings. Is there a way to hide the out of stock products in the JetSearch results?

otto

**Comment by P-happiness** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with #842, which is on the same subject so we could deal with it more efficiently.
