### ISSUE TITLE
Limit in meta custom input field

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#318]
Is there any options of limiting characters in meta custom input fields, for example, the Text Area field? So, for example, I would add a custom text area field but only wanted a maximum of 150 characters to be entered in the backend

**Comment by Floydtm** [comment]
@WildHund, Hi. Our team decided that not every user needs this option. But we give you the code for your request. Paste the following code into your theme. 

add_action( 'admin_print_footer_scripts', '__your_prefix_add_maxlength_attr_to_textarea' );
function __your_prefix_add_maxlength_attr_to_textarea(){
	?>
	<script type="text/javascript">
		jQuery( document ).ready( function( $ ) {

			$( '#_custom_html.cx-ui-textarea' ).attr( 'maxlength', 150 );

		} );
	</script>
	<?php
}


where _custom_html is the id of the meta field
