### ISSUE TITLE
Jet elements- Animated box peel feature

### ISSUE THREAD

**Issue by ArielaSel** [CrocoBlock/suggestions#3181]
In Jet Elements there is a widget called Animated box there are a few  "switch types" in content like peel, scratch, click etc.
In most switch types there is an option of direction- which is very important as a user. Unfortunately the feature "peel" has no such option which stopes me from  going wild with this amazing widget.
I would appreciate if this widget was updated!
![image](https://user-images.githubusercontent.com/83653705/117015653-9b2ab180-acfa-11eb-8f9f-f5733dd38487.png)

**Comment by Gawuww** [comment]
Added in JetElements v2.6.6
