### ISSUE TITLE
Staging and Dev environment support

### ISSUE THREAD

**Issue by Dah19** [CrocoBlock/suggestions#3182]
Elementor recently added support for Dev and staging environments based on domain. See link below. Please consider adding this feature. Otherwise required to purchase multi-domain subscription for use with one domain.  Not Practical to turn on and off production which is your current policy.  https://elementor.com/blog/elementor-expands-license-to-include-staging-sites/

**Comment by shinTM** [comment]
Done
please use URLs that matches one of these:

localhost
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
*.dev
.*local
dev.*
staging.*

**Comment by diogui** [comment]
I´m trying to update my plugins on local dev (url .local) and get the following error "Ocorreu um erro ao actualizar JetCompareWishlist For Elementor: Não foi possível instalar o pacote. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature"

**Comment by liiakerosene** [comment]
> 

https://crocoblock.com/troubleshooting/articles/cannot-update-crocoblock-plugins-license-error/

**Comment by JorensM** [comment]
@shinTM Will the plugins work off the bat on localhost or do I have to do some additional steps?

**Comment by aayla-secura** [comment]
SiteGround adds a digit after the "staging" subdomain of staging copies, e.g. staging5.mydomain.example. There's no way as far as I know to disable that or choose a custom subdomain for the staging copy. Might you consider expanding the ruleset that determines if the domain is staging to also allow any digits after "staging"?

**Comment by Gio76** [comment]
Can we please also add Rocket.net. Their naming for staging sites are:

https://NAME-staging.onrocket.site/

If we could add .onrocket.site that would be great!
