### ISSUE TITLE
Link for Date and Time (Information) on Edit Dynamic Field goes to old link...

### ISSUE THREAD

**Issue by KnoxVegas** [CrocoBlock/suggestions#3183]
I noticed a broken link and wanted to help report it, I know you can simply click on the link but its nice to go to something and get the info right away. I'm working on the "Edit Dynamic Field" block and the callback is set to "Format Date" the link below is broken when trying to get more information on the "Documentation on date and time formatting". Should re-direct to the following working link here - https://wordpress.org/support/article/formatting-date-and-time/.

**Comment by kaskad88** [comment]
Fix for the next version (2.10.3). Thanks for your report!
