### ISSUE TITLE
Add dynamic redirect for login widget

### ISSUE THREAD

**Issue by knireis** [Crocoblock/suggestions#319]
I would like to redirect my users to a user dedicated page. So each user to a specific page. As an example: user 'jasper' will (after login) be redirected to https://domain.com/jasper and user 'mike' to https://domain.com/mike.

There is a plugin (https://nl.wordpress.org/plugins/peters-login-redirect/) with this functions but it does not work together with jet login form.

**Comment by knireis** [comment]
Some extra info.
A dynamic link field in elementor has the option for a shortcode. It is easy to create a shortcode which supplies the desired link. 
So for me just adding dynamic options to the link would be great.

**Comment by kaskad88** [comment]
Added in JetBlocks v1.2.6
