### ISSUE TITLE
Implement Product's Loop functionality into Product's grid

### ISSUE THREAD

**Issue by Rok-fullstack** [CrocoBlock/suggestions#3191]
I have one request for you to fullfill if it's possible.

It would be great if you could add the functionality to **Select Archive item template** of **Products Loop** to **Products Grid** also.

Because the problem I am facing right now, is that I can't put custom field into Product's grid and can't make the same visual on Product's grid as it's on the Shop page.

And If I could make the single template for Product's grid and select this template to use, I would have the same visual as it's on the Shop page.

If you could make it happen it would be great, you would save me a lot of time :).

Regards, Rok

**Comment by UraraReika** [comment]
Hello @Rok-fullstack!

If you want to use custom fields in Product greed than look forward this issues #2932. Although you can use standard WooCommerce shortcode functionality to output products with Archive Card template elsewhere besides shop page https://docs.woocommerce.com/document/woocommerce-shortcodes/ with the help of this option https://prnt.sc/12j066h.

**Comment by Rok-fullstack** [comment]
Hello! I have just one question left, is there a way to get a shortcode for Product's grid slider/ carousel? 

Because let's say I use woocommerce shortcode -> `[products limit="4" columns="4" on_sale="true" ]`, there is no bonus settings that could enable product slider.  

Regards, Rok

**Comment by UraraReika** [comment]
In this case you can combine JetEngine and JetWooBuilder. Create listing item in which you can use JetWooBuilder Archive Item widgets. Them output it with the help of Listing Grid widget where carousel settings exist.

**Comment by Rok-fullstack** [comment]
Aha that's great to hear. Is there any tutorial out there?

Thanks for your time and help!

Regards, Rok

**Comment by UraraReika** [comment]
Right now we don't have tutorial but it like build normal listing items. And now if JetWooBuilder is active you will see it's widget in editors widgets panel.

**Comment by Rok-fullstack** [comment]
Could you be a little bit more specific?

Because I have created a listing grid, and displayed a listing grid for
products slider on the product page, but the problem is that the products
aren't clickable or buyable, so users can't actually click on the product
or add it into the cart.

Is there any additional option/ setting that can enable the products slider
to somehow connect with real woocommerce products?

Thanks for your help and time!

Regards, Rok

**Comment by UraraReika** [comment]
Please contact our support team they will help you.
