### ISSUE TITLE
Please remove the extra space between the button and the variable product.jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3193]
On the single page of this plugin, there is a large gap between these two parts. Please correct it if possible. https://prnt.sc/12j05yk

thanks

**Comment by UraraReika** [comment]
You can achieve needed result by reset margin here https://prnt.sc/12j13qk and here https://prnt.sc/12j12in.

**Comment by UraraReika** [comment]
Please contact our support team with this type of issues.
