### ISSUE TITLE
A suggestion for the jet woobilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3196]
I apologize for suggesting this again...
But it would be very useful if instead of the price of products that are not in stock, the desired word is written. For example, non-existent.
There is currently such a feature in jet woobuilder, but I do not think it has a good user interface.Because its text is not displayed in the right place. In my opinion, if this feature is added, the previous feature will no longer be needed. Of course, if this feature is added.**I think both capabilities can exist at the same time.In this case, anyone can work with any option they like.**
I am confident that this feature will be better than the current situation.
Of course, I simulated this request for you to better understand it...
For example, if the middle product is not in stock : https://prnt.sc/12jed9t

Please check this feature if possible. I have seen examples of it in department stores. Please add this feature if possible.

thanks ...

**Comment by 79ho3ein** [comment]
Thanks

**Comment by UraraReika** [comment]
You can rewrite widget template to achieve this result.
