### ISSUE TITLE
AJAX Search is including some of the pages in the result. 

### ISSUE THREAD

**Issue by DevDietheR** [CrocoBlock/suggestions#3197]
### Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

### Description
When you use the "Search by the current query" of the AJAX Search widget and search your products, some of your pages will show in the results area which should be product only. I used the "Search by the current query" to be able to customize my search results via elementor template.

### Steps to reproduce

- [x]  Use Elementor and Elementor Pro Latest Version
- [x]  Use Woocommerce and Add Sample Products
- [x]  Use Jetsearch and AJAX Search Widget
- [x]  Activate the Search by the current query

**Expected behavior**
When Ajax search Search by the current query is activated, product's only is the searchable and the results is only product.

**Screenshots**
![image](https://user-images.githubusercontent.com/42364592/117220183-4ccffc80-ae39-11eb-834e-777e0002873b.png)

I hope you guys can solved this problem as soon as possible.

**Comment by Floydtm** [comment]
We have checked your request and it looks like everything is working correctly. However, I want to clarify that this option only works on archived pages. https://prnt.sc/12keq5b On a static page, this may not work correctly. Thank you!

**Comment by DevDietheR** [comment]
Hi @Floydtm , I don't think so, there's a bug on this ajax search widget, As you can see that's a freshly installed plugin. Please Check 
![image](https://user-images.githubusercontent.com/42364592/118058770-8cf72800-b3c1-11eb-96ab-21206fa29ce8.png)

As for your clarification Why is that? then how are you going to achieve this ( Custom Search Results Page using Elementor theme builder ) If your widget can can detect the pages on search results too? please humor me.

**Comment by Floydtm** [comment]
I understand you. However, I will repeat that we have checked everything and the plugin is working correctly. But I cannot guarantee that there is no mistake on your side. Contact our support team so we can study this in more detail. Thank you!
