### ISSUE TITLE
***CRITICAL ISSUE***   JetEngine Version 2.7.8 - Error 500

### ISSUE THREAD

**Issue by stavroscha** [CrocoBlock/suggestions#3199]
I am getting the specific error message as below when i am trying to update a page/post while having installed JetEngine Version 2.8.0-beta1. I have installed the bet version so i can have access to the new query functionality you released recently. Here is the picture of the 500 error i am getting.

![image](https://user-images.githubusercontent.com/11261921/117264030-81ed4680-ae5b-11eb-9a5e-286512559c13.png)

**Comment by stavroscha** [comment]
The specific issue is happening also on the latest released version of JetEngine. I have installed Elementor and Elementor Pro plugin without having any extra plugins installed except fro JetEngine and still getting Error 500 while trying to access the website frontend or backend. I am pretty sure this is a serious issue since this is happening on LIVE ENVIRONMENTS.

**Comment by Floydtm** [comment]
We have checked your request and cannot receive such an error. Please contact our support team to resolve this issue. Thank you!
