### ISSUE TITLE
JetWooBuilder Widget: Add an option 'link > nofollow' to the 'Add to Basket' widget

### ISSUE THREAD

**Issue by shenom-x** [Crocoblock/suggestions#320]
Just enhance these widgets (single and archive) - so that we can choose a link -> nofollow option - as it is possible in the Elementor links sections as well.

We´re using a heavy count of affiliate product links. So this would be very welcome.

**Comment by Floydtm** [comment]
@shenom-x, Hi! At the moment, the button on the archive page has this attribute https://prnt.sc/q3tkls As for the single product, we can’t implement it in any way. This needs to be done on the side of the woocommerce plugin.
