### ISSUE TITLE
Sales badges on variable products show xx% - 0% if not all variants on sale

### ISSUE THREAD

**Issue by Magn2871** [CrocoBlock/suggestions#3202]
Hi

i have a problem with the sale badges. When i have it on a variable product, then i shows a 0% if it has 1 variant, which is not on sale. This look quite shit in my opnion...
1. Go to www.guldbech.dk/shop/ringe/

**Comment by UraraReika** [comment]
Hello @Magn2871 !

Please use this as example and write your own macros https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce.
