### ISSUE TITLE
🐛[Jetengine Bug] fallback refuses to work on empty format number 

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3204]
ah again this little bug 🐛, 
yes I intend to follow this one :)  it has remained unnoticed for too long. 
I think our dear fallback doesn't like numbers, he can't figure out what to do if there is an empty he displays 0 zero 

![fallback](https://user-images.githubusercontent.com/82481592/117314487-b9b9b580-ae7e-11eb-97d8-d6d0080d9e8c.jpg)

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
