### ISSUE TITLE
A suggestion for the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3207]
Hello, thank you for your efforts...
I mentioned this earlier in issue # 3157, but now I want to complete it and show you a complete example.
I am talking about the product specifications section on the single product page...
I think this section is very important for users, because in this section they decide whether to buy the product or not.
But as I said, unfortunately this part does not have a good user interface in jet woobuilder and can not be customized for us.
I will show you a suggested example, it would be great if we could design something like this with this plugin.jet woobuilder desperately needs this feature.
Suggested sample : https://prnt.sc/12l14y2

Please check this feature and please add it to the plugin sooner.
thank you.

**Comment by UraraReika** [comment]
For achieve this you can use Table Widget from JetElements plugin, and with the help of Elementor Pro dynamic terms output needed information https://prnt.sc/12m4xmf.

Back to issue #3157 here you can use JetTabs plugin in which paste elementor template with single products widgets and have more flexible area. For more details how to replace Single Tabs widget with JetTabs plugin Tabs widget contact our support team.
