### ISSUE TITLE
Open the product page, as a new tab, in the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3208]
Please add a feature to the product grid widget, so that when the user opens the product, that product will open in a new page.
This feature is very useful.This feature has also been added in the new version of the jet search plugin. I hope you add it too.
Settings for this feature in the jet search plugin :  https://prnt.sc/12l1pix

please check. thanks.

**Comment by UraraReika** [comment]
I merged this issue with #2837, which is on the same subject so we could deal with it more efficiently.
