### ISSUE TITLE
Excerpt on Listing not Working

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#3212]
**Describe the bug**
When you create a listing for any post. The excerpt is not working. The limitation of the amount of "words" is not working. Like, instead of showing 5 words for example, it shows the full excerpt.

**To Reproduce**
1. Go to Listings, create a listing of a post.
2. Select except widget OR use Dynamic Field.
3. Limit the amount of "words" to show.

**Expected behavior**
Show the same amount of words you are introducing in the Widget.

![image](https://user-images.githubusercontent.com/68023943/117383564-729be680-aeb7-11eb-821c-cd42a641cf76.png)
![image](https://user-images.githubusercontent.com/68023943/117383584-7af42180-aeb7-11eb-86c0-4458c9f84645.png)

**Comment by Floydtm** [comment]
Hi! These options work when you generate a short description from the main description https://prnt.sc/12r8o0f only
