### ISSUE TITLE
Fluent Forms Integration Incompatibility

### ISSUE THREAD

**Issue by euguk007** [CrocoBlock/suggestions#3213]
**Describe the bug**
I use Fluent Forms for my User registration due to its fluent compatibility with Fluent CRM.
Using your Profile Builder makes it impossible to incorporate multiple select option for checkboxes and country list, which (in my view) is a bug.

**Checkboxes Bug**
is due to the DB storage of submitted values as a complex array as apposed to a simple comma separated array like:
one,two,three

**Possible Solution**
to add an option for Indexed Array

**Country List Bug**
is due to the front-end display of the value as opposed to the label, which makes United Kingdom displayed as GB

**Possible Solution**
to add an option for displaying as label

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
