### ISSUE TITLE
A small but great suggestion for the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3218]
In the payment slip, when the user selects their city, the shopping list is loaded in Ajax.
Like the image opposite, this plugin has a loading mode that does not make the user feel comfortable. https://prnt.sc/12mzwcx
It will be great if you change the look of this loading.I will show you a suggested example that ultimately your choice of which loading is better.Of course any loading other than the current loading.
suggested model : https://prnt.sc/12n02w6
Please review this offer. It is a small case. But it has a very good user interface.

thanks.

**Comment by UraraReika** [comment]
Use this solution https://gist.github.com/eversionsystems/9c1845cc3a18209d4a6eb8ed5d5221a5
