### ISSUE TITLE
JetEngine: Custom Post Type (CCT): Dynamic Visibility: Extend functions to include Post Author / Not Post Author etc

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#3219]
When using a Custom Content Type (CCT) the Dynamic Visibility functionality can hide based on Custom Field Types but does not function with Post Authors (cct_author_id). I chatted with Ana from Croco support who confirmed this is currently not possible. 

This request is to extend (or create new) functionality to cover these scenarios:

-  Current User ID = Post CCT Author
- Not Current User ID = Not CCT Author
- Post Author ID = Value
- Not Post Author ID = Not Value

### Files

- \jet-engine\includes\modules\dynamic-visibility\inc\conditions\post-author.php
- \jet-engine\includes\modules\dynamic-visibility\inc\conditions\post-author-not.php
- \jet-engine\includes\modules\dynamic-visibility\inc\conditions\user-id-not.php
- \jet-engine\includes\modules\dynamic-visibility\inc\conditions\user-id-not.php

**Please, describe the feature request, making it clear to understand.**

Allow Dynamic Visibility to filter Custom Content Types (CCT) by Post Author / User ID conditions.

**Comment by kaskad88** [comment]
Hi @jamsheehan. This functionality is already available.

What needs to be done:
1 - select `Equal` or `Not Equal` condition https://tppr.me/KEjkZ
2 - in the `Field` setting, select the `Custom Content Type Field` dynamic tag and select the `Item Author` field https://tppr.me/Ev5Yn
3 - in the `Value` setting, you can manually set an id of author or select the `Macros` dynamic tag and select the `Current User ID` macro https://tppr.me/WfYbd
