### ISSUE TITLE
A suggestion for the "Add to Cart" widget in the jet woobuilder plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3221]
It would be great if you could add custom icons (like svg) to this widget.
In addition, the ability to edit the text of the Add to Cart button can be great.
thanks.

**Comment by UraraReika** [comment]
Hello @79ho3ein !

You can use this solution https://github.com/UraraReika/jet-woo-builder-custom-add-to-cart-icon whitch in closest time will be added to [Crocoblock DevTools](https://crocoblock.com/freemium/tools/) .
