### ISSUE TITLE
A very important suggestion for the single page of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3222]
I think it is **better to separate the variable selection section from the Add to Cart widget button**.**And develop it as a separate widget**.
The variables section is a very important section that, if added, could be developed more professionally in jet woobuilder.
Another advantage that this feature provides is that we can move the selection of variables to the desired location.In the current situation, the selection of variables is always accompanied by a button.
I think it would be great if the variable selection section was separated from the Add to Cart button.
Please review this offer. Thank you

**Comment by UraraReika** [comment]
Sorry but we will not add this functionality.
