### ISSUE TITLE
Please add the ability to delete the price range of variable products to the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3224]
If our products are variable, 2 prices are displayed for the products. Just like this image : https://prnt.sc/12o9zeb
Please add a feature to this plugin (especially the product grid widget) so that we can remove this price range.That is, only one price is displayed to the user.
This price, of course, can be adjusted to display the lowest product price, or the highest product price.
For example, if the price range is omitted, I want the lowest price of that product to be displayed. The other user of this plugin may want to show the highest price of that product to their user.
Please review this very important feature. 
thank you.

**Comment by UraraReika** [comment]
https://gist.github.com/UraraReika/d0cc860469df4d21b10b90de6b803395 use this code to display needed price.
In this place https://prnt.sc/12r46f0 you can use this parameters: $prices['regular_min'], $prices['regular_max'], $prices['sale_min'], $prices['sale_max'] to achieve result you need.
