### ISSUE TITLE
Error with JetEngine 2.8.0-beta1 and repeater field

### ISSUE THREAD

**Issue by naturalweb-business** [CrocoBlock/suggestions#3226]
Hi !!

I activated the Beta and occur this error :

Se ha producido un error del tipo E_PARSE en la línea 64 del archivo /www/comunidadmednaturalis_810/public/wp-content/plugins/jet-engine/includes/components/listings/render/dynamic-repeater.php. Mensaje de error: syntax error, unexpected '$items_before' (T_VARIABLE)

The page affected was broke in front and backend

Thanks !!!

**Comment by Floydtm** [comment]
Hi! Please contact our support team to resolve this issue. Thank you!
