### ISSUE TITLE
Jet Section Parallax Multiple Background

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#3227]
Hello, it would be nice in Jet Section Parallax https://prnt.sc/12pq47u to be able to control the position of the background, resize depending on the device similar to the standard Elementor capabilities https://prnt.sc/12pq7ph

Purpose: Use the Jet Section Parallax functionality to overlay two or more backgrounds in one section while being able to manage this background in the same way as here https://prnt.sc/12pq7ph.
Let me remind you that the standard functionality of Elementor allows you to set no more than two backgrounds for one section, which is often not enough.

/*Оригинал*/
Здравствуйте, было бы неплохо в Jet Section Parallax https://prnt.sc/12pq47u иметь возможность управлять положением фона, изменения размера в зависимости от устройства аналогично стандартным возможностям Elementor https://prnt.sc/12pq7ph 

Цель: Использовать функционал Jet Section Parallax для наложения двух и более фонов в одной секции при этом иметь возможность управлять этим фоном так же как тут https://prnt.sc/12pq7ph.
Напомню, стандартный функционал Elementor позволяет задать одной секции не более двух фонов, что часто бывает недостаточно.

**Comment by Gawuww** [comment]
Added in 2.6.0
