### ISSUE TITLE
Add feature to add rel="noopener noreferrer" to external links

### ISSUE THREAD

**Issue by alriksson** [Crocoblock/suggestions#323]
Missing a core feature for external links. We should have 2 more tick boxes for noopener and noreferrer for all elements/widgets that have a link option.

- Add it to all link elements
- Priority on button

**Comment by kaskad88** [comment]
In Elementor v2.9 was added Custom Link Attributes to Link Options to allow adding custom attributes. And we added compatibility with this feature
