### ISSUE TITLE
Report a problem with the jet woobuilder plugin. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3230]
When we offer discounts for variable products, this discount is displayed as a range and this is not good at all.https://prnt.sc/12rcas0
Please add a feature to show users only one value when enabled. Show 2% discount does not have an interesting user interface. Thank you

**Comment by UraraReika** [comment]
https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce use this code snippets
