### ISSUE TITLE
Please add the ability to display thumbnails below the original image to the jet product gallery plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3231]
I used this plugin but it was not possible to display the product thumbnails below the original image. Please add this feature. Thank. https://prnt.sc/12rcjzx

**Comment by UraraReika** [comment]
@79ho3ein you use Single Image widget or Gallery slider from JetProductGallery plugin?

**Comment by 79ho3ein** [comment]
Yes, but it was not possible to display thumbnail images below the original image.
https://woodmart.xtemos.com/shop/furniture/wooden-single-drawer/

thanks

**Comment by Floydtm** [comment]
Сontact our support team, they will help you or check the [documentation ](https://crocoblock.com/knowledge-base/article-category/jetproductgallery/)
