### ISSUE TITLE
Compatible with Blocksy Theme

### ISSUE THREAD

**Issue by andrii2meter** [CrocoBlock/suggestions#3238]
I will be glad if you can make it compatible with Dynamic Demo Template Import with Blocksy Theme? This is a very lightweight and the first choice by our Client's inquiry.
https://creativethemes.com/blocksy/ free version available. If you need a pro companion Plugin feature, please let me know.
(#ticket32097)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
