### ISSUE TITLE
Random query for Category Grid

### ISSUE THREAD

**Issue by flyartcom** [CrocoBlock/suggestions#3239]
Hello
I think adding a random query function to the category grid would be a great addition to the category grid.
While the Taxonomy Tile Widget allows random queries it's limited in the amount of categories to display and while the Category Grid Widget allows unlimited categories display, random queries are not supported ...

So please add random query to Category Grid Widget or allow unlimited category display in the Taxonomy Tile Widget.

Thanks you, can't wait ;)

**Comment by UraraReika** [comment]
Hello @flyartcom !

In the next release we will add this hook `jet-woo-builder/shortcodes/jet-woo-categories/categories-list` so you can use it to display random categories like this:

```
add_filter( 'jet-woo-builder/shortcodes/jet-woo-categories/categories-list', '__your_theme_prefix_get_random_categories' );

function __your_theme_prefix_get_random_categories( $categories ) {
	shuffle( $categories );

	return $categories;
}
```

**Comment by flyartcom** [comment]
Hello Oleksandr

Thanks for the good news! 
Will I have to use a php snippet like shown below or will this be integrated in the query section of the category grid?

Thanks, 
Pascal

**Comment by UraraReika** [comment]
You will have to use this snippet.
