### ISSUE TITLE
Suggestion for shopping cart button widget in jet woobuilder plugin (single product page)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3245]
As you can see in the image, the unit price of the Add to Cart button is not editable. That means we can't make the price unit a little smaller.https://prnt.sc/12ugxa9
Please add this feature if possible.
thanks.

**Comment by UraraReika** [comment]
I merged this issue with #3173, which is on the same subject so we could deal with it more efficiently.
