### ISSUE TITLE
JetProductGallery - Vimeo integration doesn't support 2:3 or 9:16 ratio video

### ISSUE THREAD

**Issue by yapofire** [CrocoBlock/suggestions#3255]
At the moment video with ratios like 2:3 or 9:16 are not supported in JetProductGallery with Vimeo (they only work for self hosted video)

Most photos are 2:3 so making the video the same ratio is what most people would want to do

See Crocoblocks Youtube clip here: https://www.youtube.com/watch?v=13nza5_IzQU

At 08:30

If you use a self hosted video that is 2:3 (like the Crocoblocks example) you can set the plugin to 1:1 in Elementor and it works fine.

The problem is that most shared hosting does not support self hosted video, making Vimeo the only option for users wanting to use clean video in the ProductGallery widget

Vimeo supports 2:3 ratio and any other ratio, so hopefully this would be an easy thing to sort out.

It would make a huge difference to users as the video functionality of JetProductGallery is a great feature, if only we could all use it :-)

Thanks

**Comment by yapofire** [comment]
Hi there, is there any news on this?

**Comment by UraraReika** [comment]
Hi @yapofire ! Work in progress.

**Comment by yapofire** [comment]
@UraraReika Great, thanks!
