### ISSUE TITLE
Does crocoblock have a plan to produce a user panel plugin?

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3256]
I design shop templates using elementor and jet plugins and I am very satisfied with this. But there is a severe shortage in the user panel.
I think crocoblock can work very professionally in the production of this plugin so that we can edit our user panel with elememntor.
(In any case, I believe there is no better and more professional plugin than jet woobuilder. Of course in the WooCommerce page editing section)
But in any case, I hope crocoblock releases this plugin soon. I do not know if it is currently producing this plugin.
I personally have many ideas for this plugin. I hope this plugin is released to share them with you.

Good luck.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
