### ISSUE TITLE
JetSearch - Seperation of responsive Product Count & Thumbnail Sizes

### ISSUE THREAD

**Issue by shenom-x** [Crocoblock/suggestions#326]
Hi again.

To make this beauty more sexy - is it possible to make the settings for 'tumbnail size' and the 'listed products per page' responsive?

If You take a mobile look at the search on our page - it would be way more handy to let the user scroll down more & more products. Instead of clicking every 3rd product to the next page.

https://www.faunt.de

**Comment by kaskad88** [comment]
Responsive Product Count - added for JetSearch 2.0.0

**Comment by kaskad88** [comment]
You can change a thumbnail size with the Thumbnails Size control http://prntscr.com/on0oba

**Comment by kaskad88** [comment]
Thanks for your report!

**Comment by shenom-x** [comment]
Just tested it... Work´s pretty nice - Thx alot!
