### ISSUE TITLE
Please add the ability to design a blank page of the wishlist and comparison to the jet compare & wishlist plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3260]
Please add blank page design feature to this plugin.
Both blank page design for comparison list and blank page design for favorites list.
Currently, only the text "Product not selected" is displayed when no product is added to the favorites or comparison list.Which does not have a proper user interface.
It would be great if you could add a feature so we could design blank pages for this plugin.
Just like this picture : https://prnt.sc/12w13os & https://prnt.sc/12w1ghd
I hope this feature will be added soon.

thanks.

**Comment by UraraReika** [comment]
Hello @79ho3ein !

You can use JetEngine dynamic conditions to achieve needed results. First of all you need JetEngine then active this module https://prnt.sc/12x7otu and install this small plugin https://github.com/UraraReika/jet-engine-custom-visibility-conditions in which we add specific conditions for JetCompareWishlist. After it go to Elementor editor and you will see this tab https://prnt.sc/12x7qyr.  Configure it like this https://prnt.sc/12x7t0z same condition presents for compare.
