### ISSUE TITLE
JetEngine: Forms: Allow website admins custom error validation message handling per field

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#3264]
Right now the error messages for forms are quite generic and does not allow for much administrator customisation. This can be quite frustrating for end users who can not understand why the form has not submitted. This is especially true for multi step forms where users may have forgotten to enter something a few pages back. 

By having custom validation errors for each field this will assist with user experience and accessibility making JetEngine forms a must have plugin. 

This request is to add another form to each field type to handle custom error messaging for each field similar to the conditional rules functionality. See below:  

![image](https://user-images.githubusercontent.com/223342/118196025-27c32700-b401-11eb-880a-b1793621b830.png)

![image](https://user-images.githubusercontent.com/223342/118196034-2b56ae00-b401-11eb-9f10-bf0954459235.png)

### Requirements

- Create a new form for each field on the Form fields which is accessed through a new button "Field Error Messages" similar to Conditional Rules functionality.  
- When a user clicks on this button the new form appears Field Error messages or Validation messages
- Within the form the user will be presented with the following:
-- New Rule Button
--- Clicking on this button will generate a form where the user will specify the error rules
-- Form Fields will include
-- Display rule if field value: **See below for operators**
-- Value to compare: 
--- This should be a dropdown of generic messages (Message Settings for the form)
--- Free text input value
-- Message to display
--- Free text which also includes %s functionality to output error messages e.g. "Your email jonatsmith.com is invalid because there is no @ symbol".
-- Users should be able to delete rules
- The messages specified in these rules should be output in the same field container as the offending field in a list format
-- Validation messages should include an anchor for that field which can also be visited from a summary if the user has a long form or a multi step form. 
- The Elementor JetEngine Form widget should have styling options for the validation rule messages. 
-- Typography
-- Font Size
-- Color
-- Margin
-- Alignment
- Optional value to display the validation messages in a summary at the form messages field on submit. 
-- These errors will use typography as other generic field settings messages.
-- When this is selected All error messages in the form will be displayed in the form validation message bar. 
- In the summary field this is a hyperlink to the field error message itself which is great for user UX. 
- When there are no validation messages for this field the symbol will match the Wordpress theme colour
- When there is an active validation message for the field the symbol will be displayed in colour (yellow?). 
-- This could also be an empty alert icon for no rules or a filled in icon when there are rules. 

**Display Rules operators:** 

- Equal
- Not Equal
- Greater than
- Less than
- Between
- In the List
- Minimum Length
- Maximum Length
- Contains Text
- Does not Contain Text

#### Defaults to choose from

**Field Type**
**Email:** ([See Wikipedia for examples](https://en.wikipedia.org/wiki/Email_address#Examples))

- Missing @ symbol
- Two or more @ symbols in your field
- Email address must not contain spaces
- Invalid characters within this field
- Two .. appearing together
- Email must not start with .

**Telephone:** 

- Field must only contain numbers 
- Phone number is not valid
- Phone number does not contain 

**Password** 

- Password must be at least %s characters long
- Password must be a combination of upper- and lower-case characters(*)
- Password must contain one or more digits(*)
- Password must not be empty
- Password does not match

### Resources and additional reading material

[Zuko Error mesasges](https://www.zuko.io/blog/a-guide-to-error-messages-in-online-forms)
[Accessuse Form Handling](https://accessuse.eu/en/forms-error-handling.html)
[W3 accessibility](https://www.w3.org/WAI/tutorials/forms/)

I accidently deleted my first draft of this, so here goes for round 2 (apologies this isn't as comprehensive as what I originally wrote)

**Comment by adelapuentep** [comment]
+1

**Comment by Rotg20** [comment]
That would be perfect!

**Comment by vogelmy** [comment]
+1

**Comment by girafffee** [comment]
This issue is resolved with JetFormBuilder 3.0-beta

more details here
https://github.com/Crocoblock/suggestions/issues/6408
