### ISSUE TITLE
*** Bug on JetWoobuilder Product Pagination using  Custom Taxonomy Template ***

### ISSUE THREAD

**Issue by P-happiness** [CrocoBlock/suggestions#3267]
Hi there,
I want to report an important bug using Product Pagination on a Custom Taxonomy Template.
In my case I use the Shop Template for a Tag (New Arrivals)

The Product Pagination doesn't work.  
It repeats the same products over and over (pag 2- pag 3- pag 4 ecc...)

You can check yourself...

Pag 1 - https://prnt.sc/12xhlig
Pag 2 - https://prnt.sc/12xholi
And so on...

I faced this problem when I was trying to implement BeRocket plugin (Load More Button).
I thought it was a compatibility issue between the plugin itself and JetWoo Custom Template.
Instead I realized that the Product Pagination doesn't work at all on Custom Taxonomy Template.

Please check this out.
Thanks.

**Comment by UraraReika** [comment]
Hello @P-happiness .

Which widget did you use?

**Comment by P-happiness** [comment]
> Hello @P-happiness .
> 
> Which widget did you use?

Hello,
I used Products Grid and Query for Tag > New  
Here's the screenshot: https://prnt.sc/13158a4

Under the Products Grid I put Products Pagination like in the previous post...

Then I've assigned this custom template to the Tag "New" that I created before.

Did I do something wrong?
Thanks

**Comment by UraraReika** [comment]
Products Pagination widget has this notice: https://gyazo.com/42d770929383fc537788414b5d8a1e34. So you need to use this option in Products Grid widget https://gyazo.com/eb934194ee6429b842b5fd9de0de650f to make pagination work or use Pagination widget from JetSmartFilters.
