### ISSUE TITLE
Improved previous price corrosion mode in jet woobuilder plugin.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3268]
There is a small problem in the products whose previous price has been crossed out, which I will explain to you and I hope it will be solved in future updates.
The problem is that the price line is separate from the unit price line.And when the unit price is smaller than the price, this problem occurs. Just like the picture opposite : https://prnt.sc/12xlr7m
I think if you can continue the price corrosion on the price unit, and remove the price unit corrosion, this problem will be solved.
This is a very small problem, but it attracts attention. **Especially on a mobile phone is clearly visible**.

Please check. Thank you.

**Comment by UraraReika** [comment]
This is the way how CSS apply text-decoration property.
