### ISSUE TITLE
!!! Update to Core Features of Jet Engine !!! (Related Posts Select Enchancement, Visibility options, Custom classes, Automatically save custom fields to custom database table))

### ISSUE THREAD

**Issue by smatzis** [CrocoBlock/suggestions#3269]
Hello and thank you for your continuous and hard work in JetEngine. I understand that it has gone too far since the beginning. However I think there are some core features missing that would improve all of its functionallity by a lot. I would also like to show some examples from other custom post types - custom fields plugins. :)

### 1. Related Posts Select Enchancement
Please add options to enhance single or multi select related posts, terms etc and if possible allow reciprocal relationships (posts-posts, users-users, etc...)

![single-select](https://user-images.githubusercontent.com/6583607/118316679-cb92fc80-b4ff-11eb-94fc-22eec70e52d1.png)
![multi-select](https://user-images.githubusercontent.com/6583607/118316697-d057b080-b4ff-11eb-84ce-179ecaa6070b.png)

### 2. Visibility options - Custom classes
Please add visibility options and allow to define custom classes for each field.

![Visibility options - Custom classes](https://user-images.githubusercontent.com/6583607/118317239-74415c00-b500-11eb-8cbd-b8ed1257a7ba.png)

### 3. Automatically save custom fields to custom database table

Please add option to save post type custom fields to a different custom database table to enhance performance. An option to define the custom table inside each custom post type would be wonderfull. It would also be perfect to automatically create the custom table if it does not already exist...

![custom table](https://user-images.githubusercontent.com/6583607/118317959-64764780-b501-11eb-9228-b610e42221bc.png)

Please consider these enhancements which i think could greatly improve the whole experience!
Thank you in advance!

**Comment by MjHead** [comment]
most of this was implemented in last updates

**Comment by smatzis** [comment]
Thank you very much!
