### ISSUE TITLE
A suggestion for a single page of the jet woobuilder plugin. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3270]
Please add the ability to change the text of the "single point" widget to this plugin. https://prnt.sc/12xsrbz
It would be great if you could add a feature so we can change the text of this widget and write our own text.
Please add this feature.
Also, this widget has a lot of free space at the bottom by default, which is unreasonable. Please check it out.https://prnt.sc/12xszst

Thank you

**Comment by UraraReika** [comment]
We will not implement controls for link text changing because of function we use for single and multiple rating. But if you want to change it you can rewrite template.
