### ISSUE TITLE
A suggestion to complete the new update of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3274]
Thanks for the great update you released ...
But I will offer a case to complete the free mode of your service.
In the new update, the old navigation points are obsolete. And its use interferes with the free mode feature.
It is better to use the bar navigation for free mode, which I suggest you to do the same.
Old navigation point : https://prnt.sc/12z3w4n
Suggested navigation bar for future updates : https://prnt.sc/12z3ymw
You can see a similar example on this website: digikala.com
It would be great if this preview bar had personalizations such as: color, thickness, border-radious, and so on.

Thanks to the crocoblock team

**Comment by UraraReika** [comment]
We provide this hook apply_filters( 'jet-woo-builder/tools/carousel/options', $options, $settings ) so you can add whatever you want slider feature.

```
add_filter( 'jet-woo-builder/tools/carousel/options', 'set_progressbar' );

function set_progressbar( $options ) {

	$options['pagination'] = [
		'el'   => '.swiper-pagination',
		'type' => 'progressbar',
	];
	var_dump( $options );

	return $options;
}
```
