### ISSUE TITLE
Please add Vertical alignment mode to the product grid flash widget.please check.(jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3275]
In the carousel of this plugin, the navigation flash may be longer or shorter.
For example, if a product has great sales, its carousel flash is higher than others that do not have great sales.
For example, in the image opposite, I placed the carousel arrow in the middle of the product box : https://prnt.sc/12z4g80
But in this image, we see that the carousel arrow, unlike the image above, is not in the center And a little lower: https://prnt.sc/12z4jfg
The reason is that in the first image, the product had 2 prices. And this causes the carousel flash level to be distorted and does not have a proper user interface.
It would be great if you add a feature, whether the product has 1 price or 2 prices, the carousel flash is exactly in the center.
In general, I mean vertical alignment capability for carousel flash products.
I hope I have conveyed my point well

thanks.

**Comment by UraraReika** [comment]
Use `Equal Columns Height` option to prevent this behaviour .

**Comment by 79ho3ein** [comment]
Sorry, I did not understand what you mean. That is, it will be added in
future updates?
thanks

‫‪Oleksandr Rudyi‬‏ ***@***.***‬‏> در تاریخ دوشنبه ۱۷ مهٔ
۲۰۲۱ ساعت ۱۳:۲۳ نوشت:‬
