### ISSUE TITLE
Please add the ability to adjust the degree of difficulty to free mode. (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3276]
It would be great if you could add a feature so that we can make the free motion smoother or harder.
This feature is very important. Please check. thanks

**Comment by UraraReika** [comment]
We provide this hook `apply_filters( 'jet-woo-builder/tools/carousel/options', $options, $settings )` so you can add whatever you want slider feature.
