### ISSUE TITLE
A few small suggestions for improving the jet woobuilder plugin.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3277]
1- In the single product image widget, there is no ability to apply padding to the thumbnail. Please add this feature.
https://prnt.sc/12z4zya
2- Please add a feature so that we can expand the continue payment button in the cart.(Full width)
https://prnt.sc/12z55ow
3- Please add the ability to apply height to the carousel flash box to this plugin. https://prnt.sc/12z57qh
4- Please add the ability to move left or right to the cart update button. https://prnt.sc/12z5bdz
5- Please add the ability to disable the zoom button to the single image widget of the product. https://prnt.sc/12z5eit
6- please check  #3268

please check. thanks

**Comment by UraraReika** [comment]
All this thing you already spread through our git in separate issues.
