### ISSUE TITLE
An offer for the car woobuilder plug-in product carousel.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3280]
When we give the product box the distance between the columns, this distance is the same around the box. But between the two boxes, this distance is twice as large.This is because the distance between two boxes on top of each other doubles the distance.
In this image is specified : https://prnt.sc/12zo7xj
While this is not a problem, it does not provide a good user interface.
I think it would be great if you add a feature that, if enabled, would halve the space between product boxes : https://prnt.sc/12zofrr
In this case, the distance between the product box and its surroundings is equal. And that would be great.
I hope I have conveyed my point well.

Thanks to the crocoblock team.

**Comment by DevDietheR** [comment]
Hi, @79ho3ein you can fix this with proper settings in the product grid widget.

**Comment by 79ho3ein** [comment]
That is, can the distance between the two product boxes be halved?
How?  Can you explain?

**Comment by 79ho3ein** [comment]
@DevDietheR  I checked, but there was no such possibility. I hope jet woobuilder releases it in future updates.

**Comment by DevDietheR** [comment]
Hi @79ho3ein you can adjust it on column padding before the product item style

**Comment by 79ho3ein** [comment]
This is possible. But padding causes a margin to appear when scrolling products, which corrupts the user interface.

**Comment by UraraReika** [comment]
@79ho3ein you wrote distance but in controls area clearly written 'Column Padding'. And thats how paddings works. For preventing double padding use it like this https://i.gyazo.com/5372130c6ffb816026de87eabec1be82.png or this https://i.gyazo.com/9ae7974580465b0b211d7fbc6044019b.png
