### ISSUE TITLE
Please add the previous and next mode to the back strap images of the single product image widget of the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3281]
It would be great if we could display individual images as sliders.
Now, if the number of images is large, they are placed below each other, which creates a very bad user interface.
If this feature is added to this great plugin, our needs will be largely met and there will be no need to install the jet product gallery plugin.Because the less the plugin is installed, the better.
I will give you a similar image of this feature, I hope it will be added in future updates. https://prnt.sc/12zy8d6

please check. thanks

**Comment by UraraReika** [comment]
We will not ad this feature in the future. Use JetProductGallery plugin or theme that from the box has this functionality for example JupiterX
