### ISSUE TITLE
Hot spot widget html code

### ISSUE THREAD

**Issue by fabxo** [CrocoBlock/suggestions#3282]
**Describe the bug**
Hotspot widget Element that uses html inside the tooltip dies not work after latest update. IT shows the Tags as Plain text

**To Reproduce**
Use bold tag inside tooltip 

**Expected behavior**
Html Formating

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaskad88** [comment]
Added in the JetTricks 1.3.8
