### ISSUE TITLE
Honeypot on JetForms

### ISSUE THREAD

**Issue by WomboIT** [CrocoBlock/suggestions#3283]
Hi!
Is it possible to include also an honeypot field in the jetform? I know there is the recapatcha integration, but I prefer to use less 3d parties services as possible and not be dependent on them.
Thanks!

**Comment by samuelbauer-io** [comment]
+1 super basic requirement

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
