### ISSUE TITLE
Show sale price time limit to users in jet woobuilder plugin..please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3284]
It would be great if we could define a time limit for great selling prices and show it to the user using the jet woobuilder plugin.
I will suggest you how to implement it in the following. I hope it can help you.
Please add a field in the products section so that we can apply a time limit for the sale price. For example, 2 days
Description of this feature : https://prnt.sc/13167cu
Then, by activating the option to display the sales time limit in the product grid widget, we will be able to easily show the end time of the discount to the users. https://prnt.sc/1316ekb
This feature is much needed and will increase sales.

thanks

**Comment by UraraReika** [comment]
Sorry but we build the WC and not implement such custom functionality.
