### ISSUE TITLE
A suggestion to improve the appearance of the variables selection section in the jet woobuilder plugin.plrase check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3286]
Unfortunately, at the moment the variable selection section in jet woobuilder does not have a good user interface at all.
And its appearance is very old. https://prnt.sc/131mwtt
I give you a suggestion to improve it and I hope you will add it in future updates.

suggested model : https://prnt.sc/131msb1
The image above is excellent and up to date.If you add this feature to this plugin, it will be a very big move
There are more details about this feature that I will explain if this offer is approved.

thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
