### ISSUE TITLE
Listing Grid: Sort by popularity / views

### ISSUE THREAD

**Issue by nisimpaniri** [CrocoBlock/suggestions#3287]
Greetings.
While working on your wonderful JetEngine plugin, I came across an option that I really missed.
As is well known in many sites and in many extensions, it is possible to sort listings by: name, date, and popularity, or a number of views.
This means that if, for example, I create a posting of posts from my site, I want to create a specific area where users can see the most viewed or popular posts from my site.
When using the "Listing Grid" widget, under the "posts query" setting there is an option to sort "order & offset". It would not have hurt if in the "order by" field there was another option of "views" or "popularity".
That way I could show the site users posts that interested other users.
Thank you!
<img width="222" alt="צילום מסך 2021-05-18 034813" src="https://user-images.githubusercontent.com/25092916/118573802-e9749180-b78b-11eb-9852-44397b1d14dc.png">

**Comment by Floydtm** [comment]
At the moment there is no way to implement this since this is not the case for the jetengine plugin. You need to collect information about views using third-party plugins and record this in the meta fields. Then you can query the listing grid for this field.
