### ISSUE TITLE
Jetbooking - Setup a limit of min nights

### ISSUE THREAD

**Issue by Maxime40990** [CrocoBlock/suggestions#3289]
Hello there. 

I'm building a Booking system on a Wordpress website. 

My client would like to allow bookings for min 2 nights. 

Not possible actually

**Comment by Lonsdale201** [comment]
+1 Usefull feature :)

**Comment by Hammer-ger** [comment]
You can do this with conditional logic. 
You can choose, that the submit Button is only shown, if travel-date-field is bigger than 2.

So if i want to book only 1 night, i can not submit the Form, because there is no submitbutton 😉

**Comment by Maxime40990** [comment]
Hey @Hammer-ger , I'm use to find solutions, but never think about this one ! 

And it's work, thanks a lot !!

**Comment by Hammer-ger** [comment]
you welcome.

maybe you could help me with an issue?
https://github.com/Crocoblock/suggestions/issues/3320#issue-898157507

**Comment by breakused** [comment]
> You can do this with conditional logic.
> You can choose, that the submit Button is only shown, if travel-date-field is bigger than 2.
> 
> So if i want to book only 1 night, i can not submit the Form, because there is no submitbutton 😉

That does not work for me. Any ideas why?

<img width="935" alt="1" src="https://user-images.githubusercontent.com/37920259/124752044-a29f4e80-df27-11eb-8c26-17626e31422a.png">

**Comment by UraraReika** [comment]
I merged this issue with [#3122](https://github.com/Crocoblock/suggestions/issues/3122), which is on the same subject so we could deal with it more efficiently.
