### ISSUE TITLE
Jet engine - listing grid slider animation

### ISSUE THREAD

**Issue by LukasSleboda** [CrocoBlock/suggestions#3292]
Hi,

Is it possible to add a possibility to make any animation in listings? I mean, if I make a slider (1 slide to show, 1 slide to scroll) using listing grid, I miss the possibility to add any animations of words etc. If I ann an entrance animation, it works onle on the 1 slide, other slides are showing without animations.

Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
