### ISSUE TITLE
Some important suggestions for improving the Single Attributes widget In the jet woobuilder plugin. Please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3297]
The product specifications section is one of the most important sections that a user pays attention to.
This widget can be customized to some extent, but it is not satisfactory. https://prnt.sc/134bql6

Some suggestions for improving this widget :
1- This line exists by default. Which is not interesting. Please correct it : https://prnt.sc/134brzu
2-  I do not know why, but a feature has a link and it is not possible to change its color.I think this problem is only in Couple rows.Please correct it : https://prnt.sc/134bvmt
3- Apparently the features section is italic. The text is slightly skewed. Please check : https://prnt.sc/134c222
4- Please add a feature so that we can space between columns and rows. This feature is very important, and currently not possible. For example, we can make something like this : https://prnt.sc/1342bre
5- Please add a feature so that we can give the rows an even and odd background color. For example, we can design something like this : https://prnt.sc/134cbul
6- If padding is applied, the vertical alignment of the text in the row will be damaged.It would be great if you could also add vertical text alignment settings to this table. In this case, changing the padding does not cause a problem. : https://prnt.sc/134chpz

Please check these items and add to this plugin soon. is very important. Thank you for your attention

**Comment by DevDietheR** [comment]
+1

Basically, they need to fix how styling works on the Single Attributes widget, During my use of this widget also encountered things you've mentioned, as of now you can fix these things via CSS.

**Comment by 79ho3ein** [comment]
Yes,I hope jet woobuilder makes this widget more professional.  And add it as soon as possible.
Thanks for your comment.
Please have any ideas for improving this widget here. 

Thanks

**Comment by 79ho3ein** [comment]
@UraraReika 
Thank you for your efforts
