### ISSUE TITLE
Show suggested products as carousel in jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3298]
It would be great if we could display the proposed products as a carousel, using the product grid widget.
https://prnt.sc/134ifsc
Please add the query of the suggested products to the product grid widget.
Of course, this feature is only required on the shopping cart page.
Please check this. Jet woobuilder desperately needs it.

thanks

**Comment by UraraReika** [comment]
Soon in Query builder from JetEngine will be able WC_Products_Query which gives you this query opportunity
