### ISSUE TITLE
JetSmartFilters radio button define default checked option

### ISSUE THREAD

**Issue by javiercriado** [Crocoblock/suggestions#330]
When working with radio buttons it's necessary to have the ability to define which of the options will be the default checked.

Currently this plugin has no option for that.

**Comment by Floydtm** [comment]
@javiercriado Hi. You can create custom query filters. Like this http://prntscr.com/o3y56g And with the help of a custom link add it to the menu. When you go to the menu item filter will be selected. It is advisable to configure the filters to work on the reloading page.
