### ISSUE TITLE
Report a common bug between the jet woobuilder plugin and jet smart filters. Please check. Very important.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3301]
I am using the product grid widget of the jet woobuilder plugin for archiving products.
The jet smart filters plugin from version 2.2.2 had a bug. Which I will explain to you in the following.
I reported these bugs twice but it was ignored.Even these bugs were not fixed in version 2.2.3 of the jet smart filters plugin.

1- When you enter the product archive page, the delete active filters button is enabled by default.While in version 2.2.1 of the jet smart filters plugin, the button to delete active filters is displayed after the filter is active

2-  In the price range filter, if the right button is dragged to the left, or vice versa, we can no longer pull that button to its previous position, because another button comes with it. https://prnt.sc/12yidjk

Please investigate and resolve these issues. I checked these problems on several similar sites and there were.
**Please check number 3272**

With thanks for your attention

**Comment by 79ho3ein** [comment]
Thanks, please fix this bug soon.  It is very necessary.

**Comment by UraraReika** [comment]
follow this template https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md and describe you r bugs in more details.
