### ISSUE TITLE
PHP code to get values from repeater field

### ISSUE THREAD

**Issue by laurentgarin** [CrocoBlock/suggestions#3303]
Hi,

For a specific reazon, i need to use PHP to display value from a repeater field create with jetengine.

I see that this field is in an array  :
`["my-repeater-field"]=>
  array(1) {
    [0]=>
    string(250) "a:3:{s:6:"item-0";a:2:{s:5:"sub-field-1";s:8:"00:10:10";s:13:"sub-field-2";s:7:"Lien  1";}s:6:"item-1";a:2:{s:5:"sub-field-1";s:8:"00:50:10";s:13:"sub-field-2";s:6:"Lien 2";}s:6:"item-2";a:2:{s:5:"sub-field-1";s:8:"01:30:00";s:13:"sub-field-2";s:9:"sfgdggdfg";}}"
  }`

But i don't know how get value from that string ?

Thanks.

**Comment by nreljed** [comment]
#3514

**Comment by kaskad88** [comment]
Solution: https://gist.github.com/MjHead/49ebe7ecc20bff9aaf8516417ed27c38
