### ISSUE TITLE
In the jet woobuilder plugin, there is a lot of extra space between the Add to Cart button and the variable selection.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3304]
I apologize for making this request again.Unfortunately, this distance is too large and severely damages the user interface.
I checked the Add to Cart widget button settings, but it was not possible to reduce this gap. https://prnt.sc/13635cv
Please investigate this issue. is very important.

thanks.

**Comment by UraraReika** [comment]
In previous issue i show you how to decrease this gap contact our support team.
