### ISSUE TITLE
Problem displaying discount percentage on the single page of the jet woobuilder plugin for products that do not have a discount.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3305]
When we use this widget (https://prnt.sc/1363q97) to display the discount percentage, if the product does not have a discount, the widget will remain empty. https://prnt.sc/1363mf2

Please correct this distance. Thanks

**Comment by 79ho3ein** [comment]
There is also this blank space at the bottom of the single image. https://prnt.sc/1366ag9

**Comment by 79ho3ein** [comment]
The extra space at the bottom of the image is shown here : https://prnt.sc/139hxw4

**Comment by UraraReika** [comment]
It's the way ho elementor render widgets. Please contact our support team so we can help you to solve this issues.
