### ISSUE TITLE
Please add a feature to the jet woobuilder plugin so that we can display the number of product sales to the user on a single product page.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3306]
It would be great if we could show them the number of sales of products that the user visits.
For example, the user runs the iPhone 12 and enters its screen. In this section you can see how many other products other users have bought. https://prnt.sc/1364f41
This feature greatly increases the conversion rate.There is currently a plugin for this, but it is not optimized. And it is not possible to personalize.
I hope to see this feature in jet woobuilder soon.

Thanks to the crocoblock team.

**Comment by UraraReika** [comment]
This is custom functionality and you can achieve this by rewrite widget template.
