### ISSUE TITLE
jetEngine form repeater is not saving more than 10 items

### ISSUE THREAD

**Issue by gpolitog** [CrocoBlock/suggestions#3310]
This issue occurs at least since version jetEngine version 2.4.11, also 2.7.3, and even 2.8.0

I have the Repeatable Fields Group Start configured with Manage repeater items count: Dynamically (get count from form field).

If I put more than 10 repeatable fields (for example more than 10 names of people), the form is submitted apparently ok.
But if I check the cpt in the backend, only 10 repeatable fields (names) were saved.

If using the backend I put, say, 12 repeatable fields in the cpt, it is saved ok.
Next time I open the form, it will show ok (filled) the 12 repeatable fields, but as soon as I submit again, in the backend only 10 repeatable fields will exist.

If after submitting the form, I reload the page, then the form accurately shows that repeatable field number 11 (name of 11th person) is empty.
Even if I fill the name again and submit the form, in the backend only 10 names are saved.

Regards.

**Comment by kaskad88** [comment]
Fixed for the next version. Thanks for your report!
