### ISSUE TITLE
send a mail to all registered users from form frontend

### ISSUE THREAD

**Issue by Jserraho** [CrocoBlock/suggestions#3315]
A form functionality send mail that when the admin or editor user add a new post type, for exemple "Properties" from form frontend, send a mail to all registered users

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
