### ISSUE TITLE
** Question: Jet Smart Filters Load More Button will ever be combined with JetWooBuilder? **

### ISSUE THREAD

**Issue by P-happiness** [CrocoBlock/suggestions#3316]
In 1.7.5 version of JetWooBuilder we added compatibility between Archive & Categories items widget and JetEngine Listing. So right now you can build product card with the help of JetEngine listing and output it with listing grid widget which has load more option.

_Originally posted by @UraraReika in https://github.com/Crocoblock/suggestions/issues/2683#issuecomment-818480796_

I'm sorry to open a new topic about this, so please forgive me!
I want to start with this replay from another topic (about Load More Button in Products Grid for Products Pagination), to understand what I'm supposed to do in order to let Jet Smart Filters Load More Button works on my WooCommerce Shop. 

What I get from this answer is that:  If we ever want Load More Button on Jet Smart Filters, we should build our Shop Templates with Elementor Archive Template and using Listing Grid (Jet Engine)  instead of Products Grid (JetWooBuilder)
Am I wrong?

If I'm right, I don't understand the use of JetWooBuilder for building a WooCommerce Shop (like in all your tutorial video)  if we cannot have all the benefit from Jet Smart Filters...

I mean, Filters are an essential part of a WooCommerce Shop, and if we cannot expand the pagination functionalities , it's kind of weird for a plugin that claims to be the WooCommerce Builder... (IMHO)

For those like me, that do not have JetEngine yet, it's quite difficult to understand how to build a WooCommerce Shop using Listing Grid instead of Products Grid.
There are no articles or video about that.
It is also frustrating to accept the fact that for a single functionality (Load More Button) I should get rid of JetWooBuilder and use JetEngine.

I came to this point because I just realized that we cannot integrate Jet Smart Filters also with other Load More Button plugins (like  BeRocket) because of the lack of the link to the next page.
Check this: https://wordpress.org/support/topic/repeated-items/ 

Since know I've been able to replace the Products Pagination (Jet WooBuilder) with their plugin, and it works. But, if want to apply Jet Smart Filters Pagination, the plugin doesn't work.

Please, before closing this request, consider this: I'm not a developer, I just want to understand better this point.

Let me say thank you in advance to those that have enough patience to explain this to me.
Thank you guys.

**Comment by 79ho3ein** [comment]
You mean the paging widget of the jet smart filters plugin does not work with jet woobuilder?
If yes, no problem because I am currently using the product grid widget and jet smart filters paging and no problem.

But if you mean that the smart jet filter plugin with jet woobuilder does not have a button to load more products, that's right. I also think this widget is very much needed for smart jet filters.

**Comment by P-happiness** [comment]
> 
> But if you mean that the smart jet filter plugin with jet woobuilder does not have a button to load more products, that's right. I also think this widget is very much needed for smart jet filters.

Yes. This one.
I would like to know if they are planning to add this integration in jet smart filters, in order to work with products grids... 

I would like to know more about their plans, and not that we can just use JetEngine to do that.

Like I said, I tried also a plugin called WooCommerce Load More Products  (BeRocket) but there's no way to work with Jet Smart Filters. They say that Jet Smart Filters Pagination is not compatible with them.

**Comment by 79ho3ein** [comment]
@P-happiness 
Yes, this widget is very necessary for jet smart filters plugin. Hope to add it to the plugin soon.
+1

**Comment by coversil** [comment]
> > But if you mean that the smart jet filter plugin with jet woobuilder does not have a button to load more products, that's right. I also think this widget is very much needed for smart jet filters.
> 
> Yes. This one.
> I would like to know if they are planning to add this integration in jet smart filters, in order to work with products grids...
> 
> I would like to know more about their plans, and not that we can just use JetEngine to do that.
> 
> Like I said, I tried also a plugin called WooCommerce Load More Products (BeRocket) but there's no way to work with Jet Smart Filters. They say that Jet Smart Filters Pagination is not compatible with them.

I would love to know if you have found a solution ..
Were you able to work with jet filter or any other ajax filter?
When I use the filter and then scroll down it reloads all the products :(

**Comment by P-happiness** [comment]
> > > But if you mean that the smart jet filter plugin with jet woobuilder does not have a button to load more products, that's right. I also think this widget is very much needed for smart jet filters.
> > 
> > 
> > Yes. This one.
> > I would like to know if they are planning to add this integration in jet smart filters, in order to work with products grids...
> > I would like to know more about their plans, and not that we can just use JetEngine to do that.
> > Like I said, I tried also a plugin called WooCommerce Load More Products (BeRocket) but there's no way to work with Jet Smart Filters. They say that Jet Smart Filters Pagination is not compatible with them.
> 
> I would love to know if you have found a solution ..
> Were you able to work with jet filter or any other ajax filter?
> When I use the filter and then scroll down it reloads all the products :(

Hi, unfortunately nope!
I have the same problem, and I'm still waiting for an update...
For now I removed filters in my shop pages rather than use classic pagination, witch really sucks to me...
I'm no happy with that (so to speak!!!)
They added this topic to Milestone but It seems there's no roadmap for this feature yet...

**Comment by 79ho3ein** [comment]
I do not think we will see this possibility soon in the jet smart filters plugin. But apparently the developers of jet woobuilder plugin are trying to add this feature to their plugin. See in this issue. 3436

**Comment by Theo789595** [comment]
I have the same issue boys, 

I just need a load more button to work with jetsmartfilters/jetwoobuilder.

Berocket is not compatible with jetsmartfilters. When i filter items they reaload and the BeRocket load more button stops showing.

**Comment by coversil** [comment]
> I have the same issue boys,
> 
> I just need a load more button to work with jetsmartfilters/jetwoobuilder.
> 
> Berocket is not compatible with jetsmartfilters. When i filter items they reaload and the BeRocket load more button stops showing.

After some getting involved and burning for hours trying to solve this I decided to purchase from berocket their filters as well.  I had to use a lot of css to get to the design I did in jetfilter but the main thing is that everything works now.

**Comment by 79ho3ein** [comment]
hello everyone
Please follow this request here (#2683). This feature is more likely to be added to the jet woobuilder. The developers of jet woobuilder pay attention to the suggestions of users. Unlike Jet smart ...

thank you

**Comment by UraraReika** [comment]
This functionality was presented in 3.1.1 version of JetSmartFilters plugin. You can fell free to check it out.
