### ISSUE TITLE
Cart empty on checkout process

### ISSUE THREAD

**Issue by pgirzalsky** [CrocoBlock/suggestions#3318]
Using your plugins to create a custom WooCommerce shop, I experience a behavior that makes for a bad user experience:

Whenever the shopping cart is opened on a page that is part of the checkout process, the cart appears empty.
Here is a video showing that behavior:
https://streamable.com/ghqi6f

Your support told me that this is intended as there is no need to display the products inside the cart side menu when the user is in the checkout process. I disagree and would argue that it can confuse the user to think his cart is empty all of a sudden.
It would be nice if you could add a feature like a checkbox in the widget's options to display the products in the checkout process as well!

**Comment by Floydtm** [comment]
Hi, I understand that this is important for you, but the widget is working correctly. You can hide the cart item with dynamic visibility or create a separate header

**Comment by pgirzalsky** [comment]
> Hi, I understand that this is important for you, but the widget is working correctly. You can hide the cart item with dynamic visibility or create a separate header

I know that it is working as intended. But this issue is supposed to be a feature request. So don't close it, please!
