### ISSUE TITLE
Listing Grid Numbering

### ISSUE THREAD

**Issue by Olegggggggg** [CrocoBlock/suggestions#3319]
Hello.
It would be nice to be able to do the numbering in the Listing Grid widget, let's say if I create a "Most Popular Products" record using the Listing Grid I would like to be able to number before the name of the product, for example:
1. First product
2. Second product
3. Third product
etc. Yes, I know that now it can be done using CSS, but it's not very convenient.
Thanks in advance.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
