### ISSUE TITLE
A great suggestion for the single image widget of the jet woobuilder plugin. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3322]
It will be great if a frame is displayed to the user when zooming in on a single product image to determine which part of the image she is focusing on.
This feature is required for this widget. And it improves its user interface. Please add this great feature.
See this feature in the image opposite : https://prnt.sc/138dtp8
With the addition of this feature, the user is able to see the area he is focusing on. And have more focus on it.
Please check out this great feature and add it if possible.

thanks.

**Comment by UraraReika** [comment]
We will not implement this functionality to our products but you can use for example this plugin https://ru.wordpress.org/plugins/wp-image-zoooom/
