### ISSUE TITLE
Please add the ability to display best-selling products to the product grid widget.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3324]
This feature is very important to be able to show best-selling products to users. Currently, we can only show bestsellers to users on a single product page. Which is useless. Because it is better to show best-selling products to users on the main page.
Please add the ability to display best-selling products to the product grid widget. This feature is very important.
Before you add this feature, I had a suggestion ...
It would be great if we could determine, if the number of product sales was more than 5 or the desired number, to be displayed as best-selling products.
For example, if the number of product sales was more than 5, I want it to be displayed as a best-selling product. Or if the number of sales is more than 2, be displayed as best-selling products. 
I hope I have conveyed my point.
Please add this feature. For store managers, it is essential to showcase their best-selling products to users.

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein please stop creating same issues.
I merged this issue with #3058, which is on the same subject so we could deal with it more efficiently.
