### ISSUE TITLE
A great suggestion for the jet woobuilder plugin.please chek .

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3325]
It would be great if you could add a query to the product grid widget, so that we can show users the suggested products on a single product page. https://prnt.sc/139gi10
For example, the user is viewing a product ...
Using this query, We offer products to the user, which complement the products they are viewing.
Recommended products Each product is taken from this WooCommerce section : https://prnt.sc/134ifsc
This feature is extremely useful.And increases user interaction with the store.

I made a similar suggestion in # 3298. But I think this proposal is much more complete than that. Because in this case, the user sees the complementary products immediately after viewing the product. And this definitely increases the conversion rate drastically.
In this case, there is no need for the user to add the product to the cart, enter the cart tab to be able to see the complementary products. Rather, by observing each product, it simultaneously sees its complementary products, and this is unique.
I hope I have conveyed my point.
Please add this query as soon as possible. I'm sure it will be wonderful. 
Preview of this feature On a single product page : https://prnt.sc/139h2zc

I hope you add this feature soon.
If you agree with this offer, please reject # 3298. thanks

**Comment by UraraReika** [comment]
If you use Products Grid or List widgets in single product template then some addition queries appears https://i.gyazo.com/5dee6028476dea4d70b0b502b01c3a8d.png. 

Although soon in Query builder from JetEngine will be able WC_Products_Query which gives you this query opportunity
