### ISSUE TITLE
Please improve the focus mode of the product image in the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3332]
The single-image widget focus mode of the product, in the jetwoobuilder plugin, does not work well on mobile phones and tablets.
This means that the user must click on different parts of the image to be able to move, and this is not good at all.
My suggestion is to add a feature, so that the user can easily focus on different parts of the image by moving her finger on a single product image.
Just like a desktop, the focus changes when the user moves the mouse.

thanks.

**Comment by UraraReika** [comment]
https://github.com/Crocoblock/suggestions/tree/master/.github/ISSUE_TEMPLATE follow one of this template
