### ISSUE TITLE
[BUG] JetEngine 2.8 - String to timestamp macro not working correctly

### ISSUE THREAD

**Issue by lensoft-softwares** [CrocoBlock/suggestions#3336]
Hey!
It looks like that the **String to timestamp** macro is not working properly. If I add anything else than "now", it is just not working. The condition is benig skipped.

My meta field, which I'm using is this particular condition is a datetime field (saved as timestamp, UNIX), therefore I used "Numeric" as the (data) type. (Anyways, If I use Date or Datetime instead of Numeric, the query returns a null array.)

Values I tried in the macro:

- now
- +3 hour
- +3 hours
- +2 week
- +2 weeks

It seems like that only the "now" string worked.
![jetnegine2 8-macro](https://user-images.githubusercontent.com/46899203/119357353-be1c0600-bca7-11eb-87b4-5fcb67e0af2a.jpg)

Anything, which can help me?

PS.: I'm in the UTC+3 timezone (CEST), therefore I need to always put "+3 hours" into a datetime condition, but this time, it is jut not working.

Many thanks!

**Comment by MjHead** [comment]
@LenSoft-Softwares thanks for reporting we'l release the fix with next JetEngine update

**Comment by lensoft-softwares** [comment]
@MjHead Thanks a lot! I'll look forward to the update.

**Comment by LevelUpGit** [comment]
Hi, we are still experiencing this issue in latest version, it simply doesn't work.
In listing grid this works "tomorrow, tomorrow + 1 day" in query editor it doesn't. 
Or 2 days ...

**Comment by ofmarconi** [comment]
First time I'm using this
I may be configuring it wrong, but after reading the @LevelUpGit report I think it's a bug.

It didn't work for me either.

**Comment by LevelUpGit** [comment]
Hi @ofmarconi , I made support ticket, thing is String to timestamp can parse only one thing at the time, so if you have "tomorrow, tomorrow + 1 day" like in my example you need to create one for "tomorrow" then another with "tomorrow + 1 day" using AND condition. This way it works. Hope this helps you.

**Comment by ofmarconi** [comment]
@LevelUpGit Amazing! Thx!
