### ISSUE TITLE
Audio JetElements Dynamic Data Addon

### ISSUE THREAD

**Issue by timolukayode** [Crocoblock/suggestions#334]
I want to create a custom audio file upload at the backend. I will use the jet download button to allow users to click and download the audio file at the frontend. Any plans to add more? Especially the Audio File that can integrate with the download button in such a way that if I add an audio file via a custom post field I created and integrated the jet download button to dynamically integrate to the audio file. Users will be able to click the button and download it.

Hope you get my point.

**Comment by Floydtm** [comment]
@timolukayode, hi! You can implement your request using the [jetengine](https://jetengine.zemez.io/) plugin. Add "media" type meta fields to your posts. Then you can use the download button widget and use the dynamics to select the file you need. More information you can find [here](https://documentation.zemez.io/wordpress/index.php?project=jetengine).
