### ISSUE TITLE
JetSmartFilters - Woocommerce Tag Widget

### ISSUE THREAD

**Issue by DrewS138** [CrocoBlock/suggestions#3344]
This would be a good feature to integrate. 

![image](https://user-images.githubusercontent.com/74819605/119430679-8ae38080-bd54-11eb-9e67-04579ff02c01.png)

WooCommerce after search, show relevant tags (taken from the most used tags) 

User clicks on tag and it populates with that result.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. However, right now you can filter by tags and display it on the search results page
