### ISSUE TITLE
Back-en bookings and closure business in booking plugin

### ISSUE THREAD

**Issue by ward-reekmans** [CrocoBlock/suggestions#3345]
There is a gigantic miss with the booking plugin!!!

1) you cannot add any holidays when you are closed!!! e.g. hotel closed during a specific time but you cannot add this.
2) you cannot add any bookings back-end. If somebody makes a phone call (or other contact) you cannot add a booking for this customer.

This is a gigantic miss!!! in this plugin.

**Comment by TIBINTCO** [comment]
Business hours is a huge missing feature in the plugin. Take a look at how WooCommerce Bookings does this and please add it to your plugin. [WooBooking Backend Setup](https://paste.pics/ebb2cf5d6491fdeaee4d212e3e5c9b33)

Range Type, Range, Bookable, and Priority.
They allow you to set: 
- Max Bookings per block, 
- Min block bookable, 
- max block bookable,
- Required buffer period in between bookings, 
- set all other times (closed office) as available or not available
- First block start time

Time should be incorporated in the Bookings plugin as it is important for almost everyone. If a customer wants to check-in at 9am and check out at 11am it should be reflected on the bookings side to allow another customer to book the same product after they are done. 

Each booking is set to 24 hours, right? So if a customer decides to use the product for 32 hours, they should be charged for 2 days, not 1.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.5.0 version. You can fell free to check it out.

Thank you!
