### ISSUE TITLE
Product Result Count Widget Not Alighned With JetSmartFilters Results

### ISSUE THREAD

**Issue by mothunyane** [CrocoBlock/suggestions#3347]
The Product Result Count widget is not aligned with jetSmartFilter in that when the applied filter results number changes, the product count widget does not display the appropriate number based on the number of results after applying the filter. 

My suggestion is that this widget should work like the Product Pagination widget in which you have the option to select what you are applying pagination for from the content area of the widget.

**Comment by Floydtm** [comment]
We are working on this, stay tuned. Thank you!
