### ISSUE TITLE
Добавить якоря к листинг айтемам

### ISSUE THREAD

**Issue by cultweba** [CrocoBlock/suggestions#3349]
Здравствуйте. Столкнулся уже второй раз с необходимостью добавить акоря к листинг айтемам. Когда впервые столкнулся даже не думал, что этой возможности нету. Но не нашел все-таки и пришлось реализовать в тот раз по другому. Сейчас снова столкнулся с тем, что нужно иметь возможность перехода на конкретную новость из новостей, что вывел через листинг грид. Но чтобы это был не переход на сингл пост а именно в списке всех новостей был переход на конкретную. 

Скажите, можно ли реализовать такую возможность? Была бы очень кстати (уверен не только для меня)

**Comment by Floydtm** [comment]
Please, note, that the feature requests can be accepted and processed only if they’re written in English.
