### ISSUE TITLE
JetElements Testimonials widget's responsiveness 

### ISSUE THREAD

**Issue by blueberry11** [CrocoBlock/suggestions#335]
В виджете Testimonials (с каруселью) нет возможности 
в Item изменять margin для мобильных устройств. 
Этого здесь явно не хватает. 

In the Testimonials widget, there isn't any opportunity to change the margin on mobile view. 
it's really necessary. 
http://prntscr.com/o579s0

**Comment by kaskad88** [comment]
Added for next version (1.15.15).
