### ISSUE TITLE
Can I add the "HTML Tag" function to the "items" of the "JetTabs"?

### ISSUE THREAD

**Issue by s863323** [CrocoBlock/suggestions#3351]
Can I add the "HTML Tag" function to the "items" of the "JetTabs"?

I think "JetTabs" is a very useful plug-in, which is better than the built-in "Accordion"、"Tabs" of Elementor.

But considering the structural requirements of page articles,

I think "items" should be added with "HTML Tag" function?(H1, H2, H3...)

![01](https://user-images.githubusercontent.com/84800282/119534783-e136da80-bdb9-11eb-8814-09af6adfcb01.jpg)
![02](https://user-images.githubusercontent.com/84800282/119534790-e2680780-bdb9-11eb-91c1-0598669ccc24.jpg)

**Comment by Gawuww** [comment]
Added in 2.1.14
