### ISSUE TITLE
Report two bugs in free mode widget product grid.please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3354]
1- When the product carousel is in this state ( https://prnt.sc/13etee9 ) ، In this case, if the user clicks on the product, the carousel mode will look like this ( https://prnt.sc/13etj4u ) That is, its free state is lost by clicking on the product image.It would be great if the carousel did not move when the product was clicked.

2- When the carousel of the product is in this state ( https://prnt.sc/13etee9 ) ، In this case, if we scroll up or down the page, when we return to the first carousel ( https://prnt.sc/13etee9 ), the carousel moves automatically. And its state has changed ( https://prnt.sc/13etj4u ) . It would be great if the free mode did not change with scrolling.

**Comment by 79ho3ein** [comment]
Thank you for your attention
I hope it will be fixed in the next updates.
To further develop the free mode feature, check out the product carousel on this site. This is a complete example.
free mode in jet woobuilder has a lot of room for improvement.
(Please see with mobile phone)

thanks

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
@UraraReika
I tested these bugs on various sites and there were.
I certainly did not convey my words well.
In any case, thank you
