### ISSUE TITLE
Show cart items inside the cart side menu on checkout process

### ISSUE THREAD

**Issue by pgirzalsky** [CrocoBlock/suggestions#3356]
Using your plugins to create a custom WooCommerce shop, I experience a behavior that makes for a bad user experience:

Whenever the shopping cart is opened on a page that is part of the checkout process, the cart appears empty.
Here is a video showing that behavior:
https://streamable.com/ghqi6f

It would be nice if you could add a feature like a checkbox in the widget's options to display the products in the checkout process as well!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks. I wrote about it in the last request from you.
