### ISSUE TITLE
JetEngine: Prevent accidental deletion of Custom Content Type (CCT) instances

### ISSUE THREAD

**Issue by TomBarker123** [CrocoBlock/suggestions#3358]
Once you have created a Custom Content Type (CCT), for example 'Businesses' and then you create instances of this CCT, e.g. 'Google', 'GitHub' etc, the items will be listed in the table under the 'Businesses' CCT in the WordPress menu.

Currently each instance has three options next to it on the right hand side: Edit, Clone, Delete.

If you click 'Delete', the entry gets instantly deleted and there is no deletion confirmation.

Please can you AT LEAST add a deletion confirmation popup?

IDEALLY you can add a 'Bin', of deleted items such that they can quickly be brought back in case of accidental deletion.

**Comment by TomBarker123** [comment]
Hi @Floydtm @kaskad88 any update on this? Thanks

**Comment by kaskad88** [comment]
Added for the next version. Thanks for your report!
