### ISSUE TITLE
A suggestion to improve the ability to fully edit the payment field of the jet woobuilder plugin that will be added in future updates ...

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3359]
There is no interesting scroll bar in the list city or province field. Great if you also add the ability to edit the scroll bar.
https://prnt.sc/13fuhff
Personalizations including: bar width, color, radious bordper are sufficient. 
This feature greatly improves the user interface. Because it does not have an interesting scroll bar at the moment.

Please review the offer.Thanks to the crocoblock team

**Comment by UraraReika** [comment]
I merged this issue with #3108, which is on the same subject so we could deal with it more efficiently.
