### ISSUE TITLE
JetSearch to search for custom fields in product variations

### ISSUE THREAD

**Issue by wittrup** [CrocoBlock/suggestions#3361]
Feature request

Hello

I would very much like if JetSearch searched through custom fields in product variations and returned product based on this.
This i related to, but not limited to:

1. [sku-search-for-product-variations #2231](https://github.com/Crocoblock/suggestions/issues/2231)
2. [JetSearch doesn't search through the variations SKU #1961](https://github.com/Crocoblock/suggestions/issues/1961)

There is also a ticket that is elaborating about the issue:
https://support.crocoblock.com/support/tickets/32912

When Search in custom fields are added to the widget it only returns main/simple product having such custom fields.
It is desirable that the search field also searches for custom fields in product variations.

A workaround could be to add  custom fields for the variation parent, however this would require a lot of rework for all (sub-)products.  Assisting with a SQL query that UPSERT all variation parents would be most helpful as a temporarily workaround.

Thanks in advance!

**Comment by Floydtm** [comment]
#2231 #1961 #1202 #1556

**Comment by mikibas** [comment]
Solution in the following link
https://github.com/Crocoblock/suggestions/issues/1556
