### ISSUE TITLE
Please add scrolling to the visual filter (color) of the jet smart filters plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3364]
Currently, scrolling is available for checkbox filters. But not for visual filters (color-based filters). Please add this scrolling feature to the visual filter. is very important. https://prnt.sc/13gfmj3
Thanks

**Comment by Floydtm** [comment]
This will be implemented soon. Keep for updates. I think you already wrote about this earlier. You should not create similar requests, otherwise we will simply close them. Thank you!

**Comment by 79ho3ein** [comment]
You are truly unique.
I apologize for repeating sometimes. I translate with Google Tetranslite and this sometimes confuses me.
In any case, thank you.
