### ISSUE TITLE
Consider extending JetEngine Dynamic Repeater for supporting all Media not only images (see code in attachemnt)

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#337]
Hello, I'm using JetEngine on a WordPress website and more particulary the Dynamic Repeater widget. I found an easy way to extend the repeater so that when working with the Media field type, you can also use uploaded files, not only images. I would like to share my code with you. Basically it's only a matter of adding a few lines to an existing code block and then adding one extra callback function. A good use case for this is when you want to use JetEngine Dynamic Repeater to make a list of downloads like PDF's. Handy for websites that need to list downloadables like reports or product manuals.

`/* Add a filter : file_url_by_id
------------------------------------------------------- */

public function get_all() {
	return apply_filters( 'jet-engine/listings/filters-list', array(
		'img_url_by_id'  => array(
			'cb'   => array( $this, 'get_img_url' ),
			'args' => 'full',
		),
		'file_url_by_id'  => array(
			'cb'   => array( $this, 'get_file_url' ),
			'args' => false,
		),
		'post_url_by_id' => array(
			'cb'   => array( $this, 'get_post_url' ),
			'args' => false,
		),
		'img_gallery_grid' => array(
			'cb'   => array( $this, 'img_gallery_grid' ),
			'args' => 'full',
		),
	) );
}

/* Add a function : get_file_url
------------------------------------------------------- */

public function get_file_url( $file_id ) {
	return wp_get_attachment_url( $file_id );
}`

**Comment by studi778** [comment]
I really need this exact solution... To allow visitors to download pdfs that have been added by JetEngine repeater fields...pls advise how I can do this from the above many thanks!

**Comment by studi778** [comment]
Floyd in order to make your solution work please let me know where I place your code...really appreciated thanks!

**Comment by Poklos** [comment]
@studi778 or @Floydtm  do you know where to put this code? :)
