### ISSUE TITLE
Copy to Clipboard Widget

### ISSUE THREAD

**Issue by sahinoz** [CrocoBlock/suggestions#3378]
Hello,

I suggest that you develop a widget called add copy to clipboard. 
Just like the button you use in your homepage (Crocoblocks) Copy discount code: crocoturns3.
When we click on the discount code, it copies and gives us a checkmark, letting us know it has been copied. 

I would love to buy such a widget because I do not want my customers to scan my email adress and paste it to email me. They can easily click on my email adress like a link or button and simply copy it to clipboard.

**Comment by Floydtm** [comment]
Right now, you can find a solution [here](https://wordpress.org/plugins/search/Copy+to+Clipboard/). We do not plan to do this yet. Thank you!
