### ISSUE TITLE
Widget Transform

### ISSUE THREAD

**Issue by gsuez** [CrocoBlock/suggestions#3381]
I would like a transform feature for element with hover action. Set translate (Horizontally and Vertically) and Rotate (In the axis of Rotate X, Y, and Z).

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by gsuez** [comment]
Thanks, @Floydtm ,currently I do it with css, it's simple. But easier would be a click :D
