### ISSUE TITLE
A very important request for the jet smart filters plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3382]
When scrolling mode is enabled for checkbox filters, the user will not notice that these filters are scrollable.As a result, the filters may seem incomplete to the user. Of course, this problem only exists in mobile phones and tablets.
I show you this problem in an image ...

This filter has a scroll. Would you notice it if I did not mark it? https://prnt.sc/13j3sga
what's the solution?
My suggestion is to always keep the scroll bar of the filters visible. Just like the picture opposite : https://prnt.sc/13j3xtc
In this case, the user can easily detect scrolling filters.

Please add this feature if approved. Thank you for your attention.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
