### ISSUE TITLE
Please add the display conditions feature to the jet smart filters plugin ...

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3387]
hi
It would be great if we could specify for which category each filter is displayed.
For example, I sell laptops and flash on my site. For laptops, I have put filters based on screen size, RAM, graphics, etc. But if the user enters the flash category, he will also see these laptop filters,Which do not work for Flash and mislead users.
Of course, it is now possible that if there is no filter for the product, that filter will be hidden, but this is not complete and in some cases has limitations.
Adding display conditions makes this plugin much more powerful than ever.

**But I have a suggestion to implement this feature, which I hope will help you dear developers...**

Please add such a section to all filter widgets in this plugin : https://prnt.sc/13lzjbv
Exactly such a part : https://prnt.sc/13lznzj
In this case, we can specify in which product category this filter will be displayed.
For example, I want the screen size filter, graphics, RAM, etc., to be displayed only for the category of the laptop.

Please review this offer. I think it is needed more than any other feature. Please share your opinion.
With thanks for your attention.

**Comment by 79ho3ein** [comment]
@SargasTM please check. thanks

**Comment by Floydtm** [comment]
Right now you can customize the visibility of filters using the jet engine plugin. Use this module https://prnt.sc/166iffk
