### ISSUE TITLE
Query update

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#34]
"The Post Type is a users details and holds the users personal details
The user is already logged in and the author of the post -

Adding a link as you suggest is a manual process and is not something i would look to do for over 30,000 users

The code: // get users data
$user_data = wp_get_current_user();

// Query arguments
$queryArgs = array(
‘author' => $user->ID,
‘post_type’ => ‘host_family’,
‘post_status’ => ‘any'
);

would call the current user and would call the post type and the users id, so why can this not be used i.e your own wp query generator doesnt even show this as an option"

**Comment by jurdekker** [comment]
Any update? On the generator website is the auth function https://crocoblock.com/freemium/tools/wp-query-generator/. When not inside de query?

**Comment by MjHead** [comment]
Hi! Now you can use Query Builder to do this
