### ISSUE TITLE
Entrance animations for the listing grid slider widget

### ISSUE THREAD

**Issue by Gitmarcc** [CrocoBlock/suggestions#3400]
It would be great if the listing grid slider widget shows the entrance animation you set on the listing item.
I set entrance animation to some elements in the listing item I designed, hoping for them to show on the listing grid slider.
Unfortunately it only works for the first slide, not so with the others.

It would be great if you consider this functionality for a future update. I think it would make it even cooler.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
