### ISSUE TITLE
Please add new spinners to the jet search plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3401]
Currently, there is only one spinner for this plugin that is outdated and monotonous. https://prnt.sc/13nae4v
Please add more spinners to this plugin if possible.
It would be great if we could add custom spinners to this plugin using the lottie animation widget in elementor.

thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
