### ISSUE TITLE
Please add the "Semi Mode" feature to the product carousel of the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3404]
Picture of semi mode : https://prnt.sc/13nyzpb
This feature will be great along with the free mode feature. Because it greatly improves the user interface and increases the level of user interaction.
As you can see in the image above, the product carousel has two full boxes, and one half box. That half box is added when the semi mode feature is activated. Of course, this feature is only used on mobile phones and tablets.
Please check this feature and add it to the plugin if possible.

thanks

**Comment by 79ho3ein** [comment]
thanks🌹

**Comment by UraraReika** [comment]
Use Center Mode option in carousel settings

**Comment by 79ho3ein** [comment]
Dear @UraraReika
The semi mode feature is different from center mode. Please compare the images below :

**center mode** : https://prnt.sc/13pydgq  Which causes the user interface to drop drastically. Because as you can see in the picture, the right side of the product box is empty. I have not seen a website that has this feature used.

**semi mode** : https://prnt.sc/13pym2p But in the semi mode, there is no empty space. And the interface is incredibly attractive.

In general, center mode removes half of the product box. But in semi mode, half the box is added.

In any case, I respect your decision.But please refrain from closing this request if possible. I'm sure this feature will be much better than center mode.

thanks
