### ISSUE TITLE
JetPopup 1.5.2 - Going From One Popup (#1) To Another (#2) By Clicking On Button

### ISSUE THREAD

**Issue by DrewS138** [CrocoBlock/suggestions#3405]
**Describe the bug**
JetPopup appears to not support going from one popup to the other popup via button click after applying it to open another popup.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create popup #1. 
2. Create Popup #2. 
3. Connect button/element inside the Popup #1 via the Elementor > Advanced > JetPopup and selecting Popup #2. 
4. When the user clicks on the button it does not open Popup #2. 

**Expected behavior**
When you select the Popup #2 to open via the click of the button inside Popup #1 it should open Popup #2 - instead it does nothing. 

- It should either open the popup or replace the popup. (as in hide the Popup #1 and replace with Popup #2.)

![image](https://user-images.githubusercontent.com/74819605/120330482-35007100-c330-11eb-8cc7-b401ad26fa18.png)

**Comment by Floydtm** [comment]
This should work right now. Contact our support team, they will help you with this. Thank you!
