### ISSUE TITLE
Conditional Logic Rules Not Working with Glosary

### ISSUE THREAD

**Issue by IFTTD** [CrocoBlock/suggestions#3406]
**Describe the bug**
If Field is a Select and uses Glossary and you go to add a conditional rule using that field. It will not automatically populate the values list to select from. Entering in the values manually separated by commas also doesn't work.

**To Reproduce**
1. Create a Meta Field (Room-ID) as Select and choose a Glossary you have created.
2. Create another Meta Field as WYSIWYG and enable conditional logic
3. Add New Rule
4. Select Field to be Room-ID
5. Select Operator to be In The List
6. Value isn't automatically populated with the options.

**Expected behavior**
Should allow to select populated list from glossary.

**Comment by its4youb** [comment]
Need it too +1

**Comment by kaskad88** [comment]
Fix for the next version (2.9.3). Thanks for your report!
