### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by fotografica** [CrocoBlock/suggestions#3407]
I'm a brand-new user of Jet plug-ins set. Then, I'd like to add a new feature on Filter Setting section. 

I saw that with Filter Type = Checkboxes list I have the Intersection option under Relation Operation field (AND instead of OR), while it is not available on Visual type.

Is there any way to add the Intersection functionality under the Visual filter type?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
