### ISSUE TITLE
Jetengine: Uncaught error due tabs after update to 2.8.1

### ISSUE THREAD

**Issue by koonda** [CrocoBlock/suggestions#3408]
Hello, 

update to 2.8.1 screwed up my website:

Fatal error: Uncaught TypeError: Return value of Jet_Engine\Dashboard\Tab_Manager::register_manager_js() must be an instance of Jet_Engine\Dashboard\void, none returned in /data/web/virtuals/189417/virtual/www/domains/euro2021.minifootball.eu/wp-content/plugins/jet-engine/includes/dashboard/tab-manager.php:55 Stack trace: #0 /data/web/virtuals/189417/virtual/www/domains/euro2021.minifootball.eu/wp-content/plugins/jet-engine/includes/dashboard/tab-manager.php(22): Jet_Engine\Dashboard\Tab_Manager->register_manager_js() #1 /data/web/virtuals/189417/virtual/www/domains/euro2021.minifootball.eu/wp-content/plugins/jet-engine/includes/dashboard/tab-manager.php(14): Jet_Engine\Dashboard\Tab_Manager->__construct() #2 /data/web/virtuals/189417/virtual/www/domains/euro2021.minifootball.eu/wp-content/plugins/jet-engine/includes/dashboard/manager.php(71): Jet_Engine\Dashboard\Tab_Manager::instance() #3 /data/web/virtuals/189417/virtual/www/domains/euro2021.minifootball.eu/wp-includes/class-wp-hook.php(292): Jet_Engine_Dashboard->init in /data/web/virtuals/189417/virtual/www/domains/euro2021.minifootball.eu/wp-content/plugins/jet-engine/includes/dashboard/tab-manager.php on line 55

Can I do a rollback to 2.8.0? Is there installation package somewhere?

**Comment by kaskad88** [comment]
Fixed in JetEngine 2.8.2
