### ISSUE TITLE
JetEngine: add bulk upload of CCT instances

### ISSUE THREAD

**Issue by TomBarker123** [CrocoBlock/suggestions#3409]
Would it be possible for you to add a bulk upload feature for the JetEngine CCT? (i.e. the opposite of the bulk extract that currently exists).

I have created a business directory website and could potentially have hundreds of members. If something went wrong with the site, I would have to manually upload all member details, which would take forever.

Please can you consider adding a way to upload some sort of CSV or XML file etc containing all of member details? I understand that this file would have to take the same structure as the columns defined in the CCT.

**Comment by Floydtm** [comment]
We will work in this direction later. Maybe [this ](https://www.youtube.com/watch?v=XyoFwW06SOA)will help you now. Thank you!
