### ISSUE TITLE
JetMenu: hide dropdown icon 

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#341]
Need to add the setting to show/hide dropdown icon: http://prntscr.com/o6zw94

**Comment by jasonb4u** [comment]
Hi, I think this would be goods as per single menus.  Can probably add in GLOBAL, but also needs to be activated as per each menu used.  If I have several Menus on ONE page and only want the MANI menu with no drop-down BUT the others can be altered at any time.  This setting would be in the Elementor Widget.

**Comment by shinTM** [comment]
you can use custom css 
.jet-dropdown-arrow{
display: none;
}

**Comment by ColinHiom** [comment]
hi guys, I just stumbled on this. I've spent over half an hour trying to find a setting for that. Surely there be a setting by now to change the style of the dropdown arrow too and to have a 'user dropdown arrow ? yes/no'. I'm sure it must be there somewhere but where? Am I blind?
