### ISSUE TITLE
A request for the "range" filter of the jet smart filters plugin. please check it

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3412]
It will be great if you add a feature so that we can style the price prefix or suffix separately from the price. https://prnt.sc/13ovnog
In the current situation, prices, prefixes and suffixes are styled the same, which is not interesting at all.
Please review this request

thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
