### ISSUE TITLE
👎 Huge problem "Make sure only CCT element author can edit CCT element with front end form"

### ISSUE THREAD

**Issue by pegujurado** [CrocoBlock/suggestions#3414]
I am building a huge project. With the last update I cannot edit CCT with the other authorized form. Are you sure this is the way? Think of all the problems that this measure can cause. There is no possibility to deactivate this option? I am really dissatisfied and my project has stopped. Please think of all the possibilities and not just basic clients and fix this. It was not a great idea. I had to stay on the 2.8.0 jet engine.

**Comment by hum-bug** [comment]
I have exactly the same issue - for me I'm using CCTs as tasks that need to be managed by multiple users so this also breaks my website. I could manage securely already by controlling access to the page hosting the form and also used the form webhook option to check user access when submitting. 

This should have been introduced as an option so as not to break existing functionality!!! Please fix urgently!!!!!!!

**Comment by Jackal-un** [comment]
I have also the same problem. Complete disaster for my project...Hope to get some option to give other users (then CCT author) the access to edit CCT

**Comment by Jackal-un** [comment]
The only way to fix this now is to change the notification file in modules>CCT>forms. Change that file with a file from an older version 2.8.0. for example.

**Comment by ihslimn** [comment]
This behavior is not a bug, but a bugfix.
Prior to the update anyone - for example - could edit CCT items through the form with pre-set from the query variable.
This was reported and fixed, as this was a security issue.

You may contact support and explain in more details why is there a need to let users edit others' CCT items.
Maybe there is some workaround, or it is possible to change the way you build your site.

Also, you may edit the plugin, as **Jackal-un** suggested.

We are really sorry for the inconvenience, but there was a reason behind the fix,
and this is not something that will be changed back.
