### ISSUE TITLE
Offer to display the discount percentage of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3419]
Please, if possible, add a feature to the product grid widget, so that we can put the discount percentage before the special sale price. Just like the picture opposite : https://prnt.sc/13q19e3
I do not know why, but this feature has been requested by many of our customers.
Of course, I think it is an excellent feature and improves the user interface.
Please add this feature to the plugin if possible.

Thank you.

**Comment by UraraReika** [comment]
For this you can rewrite widget template. Please contact our support team.

**Comment by 79ho3ein** [comment]
thanks
