### ISSUE TITLE
🔥 [JetBlocks] Raise login widget to the next level

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3420]
[https://wpresidence.net/](https://wpresidence.net/)
![wpresidence login](https://user-images.githubusercontent.com/82481592/120509636-f9fe4c00-c3c8-11eb-9a89-6b524dd85c46.gif)

[https://modern.realhomes.io/](https://modern.realhomes.io/)
![realhome login](https://user-images.githubusercontent.com/82481592/120509663-01255a00-c3c9-11eb-865e-235285ad41be.gif)

I realize that this kind of natural and user friendly popup register/login is a nightmare to do even today in 2021.

At elementor github my requests to improve their login widget with popup weren't taken seriously ..

by chance I discovered that at crocoblock someone has integrated the notion of **Error validation** in the Login Widget JetBlocks !

![Capture d’écran 2021-06-03 010334](https://user-images.githubusercontent.com/82481592/120566701-140f4d00-c410-11eb-8c3c-2903c1aa815b.png)

So I started dreaming of being able to do like the two examples above

I created a login popup elementor with jetblock login widget

![my login](https://user-images.githubusercontent.com/82481592/120510442-b8ba6c00-c3c9-11eb-9528-96ccd67ddf42.png)

and another registration with jetengine forms

![registration](https://user-images.githubusercontent.com/82481592/120511059-4eee9200-c3ca-11eb-9551-50597aa9cd22.png)

Unfortunately, it is not perfect. if a bad login is entered the page reload.. so the popup disappears. 

if you activate "Lost your password?" if you clic the link redirect you to 
/wp-login.php?action=lostpassword

![lost pass](https://user-images.githubusercontent.com/82481592/120511083-5615a000-c3ca-11eb-9580-ceddb26dd2ca.png)

and leaves you at the mercy of wordpress with the **log in** link visible..
which if unfortunately the user connects with ... he finds himself in the backend .. misery and despair!

it will be necessary to think how deactivate ALL wordpress logins ways and replace it by JetBlocks rules.

![Capture d’écran 2021-06-03 011125](https://user-images.githubusercontent.com/82481592/120567150-55ecc300-c411-11eb-85d3-26855f7db122.png)

Another important point are logins by social media
This will be **the game changer**  function with only one plugin to govern them all .

I have great hope that soon someone at crocoblock will understand the need to create a real functional & flexible popup register/login 
to strengthen the ecosytem of crocoblock plugins.

**Comment by Medienor** [comment]
Amen! +1 | We all need this. @Crocoblock

**Comment by Medienor** [comment]
@shinTM  | Express this | We will pay for your hourly fee.
Send us a message to josef@medienor.no regarding payment

**Comment by MathiasVignes** [comment]
+1!

**Comment by nreljed** [comment]
little test with a [plugin ](https://ultimateelementor.com/widgets/login-form/)which seems to succeed in not closing the popup or reload the page.
![test](https://user-images.githubusercontent.com/82481592/120592080-86e2ed00-c43d-11eb-89f4-2bc5cb34871e.gif)

but they failed the login/register switch and the ultimate test "Lost your password?" which brings you right back to the screen of death wordpress login .. :( 
we are far from equaling the two examples shown at the beginning of the post... :( 

but at least we know it's not impossible !
I hope with that we have enough information to do better or equal to my examples

![test2](https://user-images.githubusercontent.com/82481592/120592125-9eba7100-c43d-11eb-8fbb-9f861f2056dc.gif)

**Comment by DevDietheR** [comment]
+1

**Comment by Lonsdale201** [comment]
+1 :)

**Comment by SMolodoy** [comment]
+1 ))

**Comment by yerhgogh** [comment]
+1

**Comment by lifeact** [comment]
+1  and need  antispam  capcha

**Comment by zonerap** [comment]
+1

**Comment by Hans-101** [comment]
+10 @Crocoblock

**Comment by Hans-101** [comment]
> little test with a [plugin ](https://ultimateelementor.com/widgets/login-form/)which seems to succeed in not closing the popup or reload the page.
> ![test](https://user-images.githubusercontent.com/82481592/120592080-86e2ed00-c43d-11eb-89f4-2bc5cb34871e.gif)
> 
> but they failed the login/register switch and the ultimate test "Lost your password?" which brings you right back to the screen of death wordpress login .. :(
> we are far from equaling the two examples shown at the beginning of the post... :(
> 
> but at least we know it's not impossible !
> I hope with that we have enough information to do better or equal to my examples
> 
> ![test2](https://user-images.githubusercontent.com/82481592/120592125-9eba7100-c43d-11eb-8fbb-9f861f2056dc.gif)

The issue with Ultimate Addons for Elementor is that they have a bunch of PHP errors, warnings and depreciations, they cause conflicts with Elementor, but they are very hard to pinpoint, as all errors seem to come from Elementor. Once UAE is disabled, the errors disappear, but, also UAE's plugin. Kind of sucks. I'd prefer someone more backend responsible (@Crocoblock ) to add this functionality. Social login/one-click login is basic in Social Media times, like for the last decade.

**Comment by ernsyn** [comment]
+1

**Comment by arekuki** [comment]
+1

See #1677

**Comment by mrgithub** [comment]
+1

**Comment by JakJakson** [comment]
+100 :)

**Comment by mrgithub** [comment]
I assumed social logins were automatically included - surprised to see its not!

**Comment by Zaanone** [comment]
+1

**Comment by kuni13** [comment]
+1

**Comment by vladvaleanu** [comment]
+1

**Comment by MjHead** [comment]
Similar functionality planned for the next JetFormBuilder. As for social login - you already can use it in combine with any free 3rd party plugin for social login, which includes shortcode or block for login buttons. Just paste this block directly into the JetForBuilder form layot in any place you want.
