### ISSUE TITLE
🥰 [JetSmartFilters] - Add a loading spinner when you switch filters [Please Important!] 🥰

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#3421]
Hello, i asked about this function 7 months ago.
It's been ignored over and over again.

When you switch filters in the JetSmartFilters you want to see that the list is changing. Right now its no animations or anything. This is strange for a big brand like Crocoblock not to have this installed?

I know there are MANY customers who are looking for this function. Can we please expedite this?

<img src="https://i.ibb.co/31wtTWz/Crocoblock-I-Love-You-Please-Add-This-Function.jpg" alt="Girl in a jacket">

**Comment by 79ho3ein** [comment]
+1
yes I agree.This is a great requirement.
I hope they approve this request.

**Comment by Lonsdale201** [comment]
+1

**Comment by stasonua0** [comment]
+1

**Comment by yerhgogh** [comment]
+1

**Comment by jamsheehan** [comment]
Would be amazing if we could upload our own spinners

**Comment by 79ho3ein** [comment]
> Would be amazing if we could upload our own spinners

Exactly, for example, using the animation lottie widget elementor plugin.

**Comment by lifeact** [comment]
+1

**Comment by DevDietheR** [comment]
+1

**Comment by 79ho3ein** [comment]
I think this spinner should be similar to the spinner of the jet search plugin.
Because two different spinners do not look interesting on one site. Of course, I do not know if you also use the jet search plugin or not.
I have already submitted a request to change the jet search plugin spinner. They replied that we have no plans for that at the moment.

**Comment by Medienor** [comment]
@SargasTM Has been assigned everybody! Let's celebrate!

**Comment by DevDietheR** [comment]
+1

**Comment by WebsiteWerk** [comment]
+1

**Comment by Michaelgimii** [comment]
+1
Is there any news about this feature?

**Comment by ThomasCommpagnie** [comment]
+1 
Hope this feature will come live one day, it is a detail but a big improvement for user experience

**Comment by stasonua0** [comment]
+1

**Comment by 79ho3ein** [comment]
hi @Floydtm

I had a suggestion for this. It will definitely be difficult and even difficult to implement a spinner to load the products. But there is a much easier and even more beautiful way. I think it is better to use [shimmer](https://prnt.sc/LDb0B2F4RNMD) to load products after selecting filters. Please watch the video below :

https://user-images.githubusercontent.com/77163248/159258387-97a2f47c-eba0-4a2a-8273-d462457b269a.mp4

Currently, this feature is implemented in the load mode (jet woobuilder) plugin.
This link may also be useful : https://codepen.io/arsh-shaikh/pen/JjEQYmW

thank you

**Comment by MjHead** [comment]
Will be released in 3.3.0 in a few days
