### ISSUE TITLE
Bug when updating values in option page using jet-engine form

### ISSUE THREAD

**Issue by rousarp** [CrocoBlock/suggestions#3423]
When the field value in the form is zero ("0"), the item is not saved in the option page field.

I have created an option page and in it 4 items of type number.  I made a form to update these fields using jet engine form. The values are only saved when one of the items is not zero, but the form always will return a status of successfully saved form.
Storing values of 0 in the back end works fine.

**Comment by nreljed** [comment]
#3068

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
