### ISSUE TITLE
Jetwoo builder - additional fields population 

### ISSUE THREAD

**Issue by paulpsky** [CrocoBlock/suggestions#3429]
Allow for additional fields to be populated into emails and back end orders. 

Currently even the woocommerce default "additional fields" when filled in after payment does not show any record of information inputted within 1) the back end and 2) jet woo styled templates

**Comment by UraraReika** [comment]
Thanks for the feedback, Please follow [guidelines](https://github.com/Crocoblock/suggestions/tree/master/.github/ISSUE_TEMPLATE) for opening a new feature request, so we can help you better.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
