### ISSUE TITLE
Room allocationc

### ISSUE THREAD

**Issue by YorickChartrain** [CrocoBlock/suggestions#3430]
Hi,

Jet Booking system doesn't necessarily allocate rooms in the best way. Sometimes it's not possible to book a room whereas itshould be possible by dispatching room in another way.

An exemple : 
Room 25 taken between 5th august and 25th august
Room 26 taken between 3rd july and 26th july
Room 27 taken between 8th july and 26 july

It's however possible to affect differently the rooms to allow to reserve a room between 24th july and 7th august (put that of the room 27 in room 25 for exemple).

It's not also possible to do it manually. I try to change the number of a room on an existing booking but it causes bugs.
The reservation have disappeared on Booking and on Upcoming Bookings in the room article.
In woocommerce order, Booking details have disappeared and statut have changed to "Waiting".

It would be very useful to be able to manage the rooms allocation manually.

Best regards,

YC

**Comment by UraraReika** [comment]
Hello @YorickChartrain. Thanks for the feedback.

Unfortunately this kind of logic can't be implemented. In release of JetBooking plugin version 2.5.0 we added possibility to create new bookings from the admin area so now you can manually handle this by yourself. In future releases we will add feature to connect manually created bookings with WooCommerce orders.

Thank you for your understanding.
