### ISSUE TITLE
A small request for the jet woobuilder plugin. Please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3432]
In the product grid widget, there is no space between numbers and percentages : https://prnt.sc/13w9yv2
It will be great if you add a feature so that we can apply the desired distance between the number and the percentage.
This is a very small and insignificant request. But it has an important effect on the user interface.

thanks

**Comment by UraraReika** [comment]
You can use this as an example https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce to write your own macros with your rules.
