### ISSUE TITLE
jetBooking bug: not possible to book bevore another booking

### ISSUE THREAD

**Issue by Hammer-ger** [CrocoBlock/suggestions#3434]
i have got a bug in booking.
setting is booking per nights.
after i book e.g. 08.09. to 10.09. it is possible to book 10.09. to 11.09. but it is not possible to book 07.09. to 08.09.
![grafik](https://user-images.githubusercontent.com/66528657/120713355-0fa36c80-c4c2-11eb-8fe9-26b3cc98b4ec.png)

i can choose the 07.09. for checkin, but can not klick on the 08.09. for checkout.
![grafik](https://user-images.githubusercontent.com/66528657/120713398-20ec7900-c4c2-11eb-9a78-ba05c8a2b113.png)

i set settings to book per night the last day is not included, so why can i not book (in this case) from 07.09. until 08.09.?

Thank you for your help,

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.5.1 version. You can fell free to check it out.

Thank you!
