### ISSUE TITLE
Add load more functionallity on Product's loop

### ISSUE THREAD

**Issue by Rok-fullstack** [CrocoBlock/suggestions#3436]
Hi there!

The feature I'm requesting is you to add Load more button functionallity on Product's loop. 

I've seen that's possible on the JetEngin plugin if I create listing item and then display it on the product's grid, but product's grid is not working the same as product's loop.

If you could add this feature in the future it will be really helpful!

Thanks for your time and help!

RP

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with #2683, which is on the same subject so we could deal with it more efficiently.
