### ISSUE TITLE
Display the desired image before fully loading the product images. (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3439]
hello
I do not know if I should request this feature from jet woobuilder or woocommerce or even WordPress.
Anyway, I make my request, I hope if possible, jet woobuilder add this feature.

It would be great if we could select an image to be displayed to the user before the product image is fully loaded.This feature makes the user not tired of waiting for the full image of the product to load.
Of course, the image we choose to display before uploading is only displayed to users when the site loads late for any reason and the product image is slowly loaded.
But under normal circumstances, the user will never see this image.

To better understand this request, I will show you the image of this feature :
Currently, if the site loads late, product images will not be displayed and this is not good at all : https://prnt.sc/148mq03
But if this feature is added, from now on, if the site loads late, the images will be displayed like this : https://prnt.sc/148ne20

There are more details about this plugin that I will provide your service if this request is approved

With thanks for your attention

**Comment by DevDietheR** [comment]
Basically fallback image :), Good request  +1
but much better if they put a loading bar on their ajax loading

**Comment by UraraReika** [comment]
Fore sure your images is lazy loaded in this case plugin that you use should give you an opportunity to handle this issue. For example if you use Smush – Lazy Load Images, Optimize & Compress Images than you can do this https://monosnap.com/file/r5lFLAUdc0kJHirX7aSDkChpvGoDxp.
