### ISSUE TITLE
Why loading jquery tablesorter when not used

### ISSUE THREAD

**Issue by alriksson** [CrocoBlock/suggestions#344]
**Please, describe the feature request, making it clear to understand.**
Far from all users will use the function tablesorter. When this feature is disabled this function should not execute on the frontend. it's a very heavy script that has a big impact on performance.

You should no execute this if not used. I've disabled it on my side but per default, in the plugin it should only be executed when used. As per my other ticket regarding performance.
/jet-elements/assets/js/lib/tablesorter/jquery.tablesorter.min.js?ver=2.30.7

**Comment by kaskad88** [comment]
Fix for next version (1.15.15).
Thanks for your report!

**Comment by alriksson** [comment]
@kaskad88 thanks!
