### ISSUE TITLE
A request to improve the free mode feature.(jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3440]
If I am not mistaken, I have made this request once before. But I repeat this request to remind you again.
With the addition of the free mode feature, the old navigation points are obsolete. This means that if we use the old navigation points for free mode, it will not be interesting at all. And also the method is not up to date. https://prnt.sc/14a7hi7
I have reviewed many sites that use free mede mode. But none of them used the old navigation, ie point (Image above).

But a new navigation feature for free mode ...
On all sites that used the free mode feature, the product preview was displayed in this way. As the product grid moved, the line marked in the opposite image moved. https://prnt.sc/14a8mnw
Great if you add this feature to jet woobuilder. Of course, I think it is absolutely necessary to add it. But in the end the decision is with you dear developers.

thank you for your attention...

**Comment by UraraReika** [comment]
We provide this hook apply_filters( 'jet-woo-builder/tools/carousel/options', $options, $settings ) so you can add whatever you want slider feature. And here is carousel API https://swiperjs.com/swiper-api

**Comment by 79ho3ein** [comment]
@UraraReika 
That is, it will be added in future updates?

**Comment by UraraReika** [comment]
You can use it already
