### ISSUE TITLE
🔥[Jetengine] Listing grid exclude by author

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3443]
![Plan de travail – 1](https://user-images.githubusercontent.com/82481592/120942117-036c1900-c727-11eb-8366-dfdd5563b754.png)

for specific reasons i have a need to create a listing and exclude current user posts and see all other users' posts.
**macros> exlude current user ID.**
as listing grid does not have this option (yet?) 
so I said let's use the new query builder...
great idea ? no ! very bad idea. :( 

I realized after having successfully completed this task .. (with query builder) that jetsmarfilters conflicts and clashe listing grid with my custom query listing and refuses to work correctly **(specifically on indexer options> if items empty> hide)** my filters remain hidden, 
they refuse to work until **I deactivate the query builder**. and ..everyone becomes friends again!
no matter what id you put it will not work like that.

Good luck if you find me a solution
while waiting for an admin to give us good news
it will be so simple and productive to add the exclusion of authors. directly in listing grid.

**Comment by nreljed** [comment]
after further investigation, apart the missing option to exclude authors in listing grid.
jetsmartfilters does not support the new query builder, he refuses to filter as long as there is a custom query.

**Comment by kaskad88** [comment]
Hi @nreljed. Use the Query Builder for your case. Also update JetEngine to the latest version with the latest updates and fixes.
