### ISSUE TITLE
Please add a query to the product carousel widget, so that we can show WooCommerce products offered to users.jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3446]
hello
This is a very important offer in the WooCommerce framework.That jet woobuilder is severely lacking.
Offer Description :
When inserting a product, WooCommerce has a section where we can select products as the suggested products of the product we insert.https://prnt.sc/14ibe47
For example, when a user enters the iphone 12 single product page, they see that we have provided frames, airpods and other accessories as an offer for the iPhone 12.And this is wonderful.
Unfortunately, this feature is not currently available in jet woobuilder. And it really needs it.
Please add this important feature to jet woobuilder.
If you need further explanation, I am at your service.
thanks

**Comment by UraraReika** [comment]
If you use Product Grid widget on single product template some additional options appears https://i.gyazo.com/7b36648c0be2243652d2d83eb0c7dbb5.png

**Comment by 79ho3ein** [comment]
@UraraReika 
This is exactly what I wanted.
You are truly unique. thank you.🌹🌹🌹🌹🌹
