### ISSUE TITLE
A suggestion for the carousel flash box product of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3447]
https://prnt.sc/14j9jt9
Great if you remove the padding, And changing the amount of padding makes the flash box only square, and that's not interesting.
My suggestion is to remove the padding, and add the width and height values ​​instead.
Please review this request.

Thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein !

I already describe how to achieve desirable results with next release here https://github.com/Crocoblock/suggestions/issues/3102 so please be patient

**Comment by 79ho3ein** [comment]
@UraraReika 
Sorry, I did not see # 3102.
thank you
