### ISSUE TITLE
Please add the z-index feature for the jet woobuilder plugin discount medal.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3448]
The z-index feature is very important for the discount medal.Because in the current situation, this medal can not be placed in the desired position.
For example, we can not display the medal in this section : https://prnt.sc/14jbbd5
Because as you can see in the picture, if we bring it down, it goes under the title and price and can no longer be displayed : https://prnt.sc/14jbq2i
With the addition of z-index this problem is easily solved.

Please review this request. Thanks

**Comment by UraraReika** [comment]
There is no need in z-index. Discount badge render in item-thumb template of Products Grid so that is why it looks like this. You can solve it by rewriting templates and put this badge whatever you want.

**Comment by 79ho3ein** [comment]
rewriting templates?
I mean do I have to code?

**Comment by UraraReika** [comment]
Not much but yes. You can contact our support team so them can help you.

**Comment by 79ho3ein** [comment]
Okay,thank you

**Comment by 79ho3ein** [comment]
Excuse me, I had a question for you dear developer, about the jet woobuilder plugin ...
I already had some important requests from you to improve this plugin, such as displaying the remaining time of the special sale : https://prnt.sc/14l2v7 And you said that : https://prnt.sc/14l3vfj
I wanted to ask you if this limitation exists forever, or if we can soon see such capabilities in jet woobuilder?
Thank you for your efforts🌹
