### ISSUE TITLE
JetBlog Not supporting RTL

### ISSUE THREAD

**Issue by pintolog** [CrocoBlock/suggestions#345]
Hi,
I'm using Smart Post Tiles Element from JetBlog for my blog post, but as i see it's not support RTL language like Hebrew.

The "?" mark should be on the left and not on the right as it is right now. 

Can it support RTL languages ?

![image](https://user-images.githubusercontent.com/7497319/60387261-037a2d80-9aa9-11e9-9504-8a807921e8a5.png)

**Comment by Floydtm** [comment]
@pintolog, hi. We checked RTL and could not reproduce the bug https://prnt.sc/o8w43e. Perhaps the bug is associated with the symbol "?". Check it please
