### ISSUE TITLE
Update cart after quantity changes JetWooBuilder

### ISSUE THREAD

**Issue by xC4M** [CrocoBlock/suggestions#3451]
Hi there.

Please add in a next release the possibility to update the cart after quantity change. While designing the Cart Page using JetWooBuilder it has a toggle to hide the "update cart button" but it's missing the automatic update cart after a quantity change. If you give me the ability to hide it, then you could also give us the ability after hiding it, the cart's total could change after a product's quantity change.

Think on it.

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Sorry but we will not implement this functionality but you can use this article https://rudrastyh.com/woocommerce/remove-update-cart-button.html to handle your needs

**Comment by xC4M** [comment]
> 
> 
> Sorry but we will not implement this functionality but you can use this article https://rudrastyh.com/woocommerce/remove-update-cart-button.html to handle your needs

Thanks for the article. It works... but only when the "Update cart" button is visible. When you hide it using CSS or the option to hide it which is integrated in the Cart Widget (JetWooBuilder), it doesn't work... :(

You should re-think to add this function.

**Comment by UraraReika** [comment]
Please contact our support team.
