### ISSUE TITLE
Please remove the extra price from the single page product of the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3452]
In variable products, after the user selects the variable, another price is displayed to the user, which does not have a suitable user interface at all.
My suggestion is to please delete the price that is displayed after selecting the variable. https://prnt.sc/14nm767
It would be great if the previous price was updated after selecting the variable product. https://prnt.sc/14nmnwi
This will be excellent and more efficient.
Please check.

Thanks

**Comment by UraraReika** [comment]
Once again we will not implement this optionally but you can use this snippet:

```
add_action( 'woocommerce_before_add_to_cart_form', '__your_theme_prefix_selected_variation_price_replace_variable_price_range' );

function selected_variation_price_replace_variable_price_range() {
	global $product;

	if ( $product->is_type( 'variable' ) ): ?>
		<style>
			.woocommerce-variation-price {
				display: none;
			}
		</style>

		<script>
			jQuery( function( $ ) {
				var p = 'p.price'

				q = $( p ).html();

				$( 'form.cart' ).on( 'show_variation', function( event, data ) {
					if ( data.price_html ) {
						$( p ).html( data.price_html );
					}
				} ).on( 'hide_variation', function() {
					$( p ).html( q );
				} );
			} );
		</script>
	<?php endif;
} 
```

If you have some difficulties then contact our support team.
