### ISSUE TITLE
JetBooking - Implementing seasonal price changes

### ISSUE THREAD

**Issue by laura-brrth** [CrocoBlock/suggestions#3455]
When renting a property, the price of the property to rent often changes with seasons. (In summer the price for a holiday home might be higher as in winter)
It would be really helpful if we would be able to implement those price changes directly into the price calculation, in the same way as it is already possible to change the price if a person books an determined beforehand amount of days.

**Comment by CaseFixedWebdesign** [comment]
+1

**Comment by tavolucas** [comment]
@Crocoblock  has not done anything and to solve this and it seems that they are not going to do it, I have been waiting for months ...

**Comment by JackobStuard** [comment]
Hi devs, @Crocoblock @MakhonkoDenis 

Is there any update for this feature?
I hope that will be implemented soon, I think that all users want this feature to have on JetBooking :)

Thanks!

**Comment by ghost** [comment]
I implemented a custom solution with seasonal coefficients and custom periods, with the check done day per day and not just on start date. If someone interested he can contact me

**Comment by UraraReika** [comment]
This functionality already released. You can fell free to check it out.
