### ISSUE TITLE
JetEngine Listing Grid "load more" and "infinite scroll" not working with WPML

### ISSUE THREAD

**Issue by esalonico** [CrocoBlock/suggestions#3456]
**Describe the bug**
As you can see on the page https://italianwatchspotter.com/tutti-gli-articoli/, when scrolling down the page and therefore triggering the Listing Grid infinite scroll, the articles that show up are both in Italian and English (website built with WPML).

**To Reproduce**
See internal ticket https://support.crocoblock.com/support/tickets/33514

**Expected behavior**
The articles that should show up should be only in the current language.

**Screenshots**
See internal ticket.

**Desktop (please complete the following information):**
Happens on all devices.

**Smartphone (please complete the following information):**
Happens on all devices.

**Comment by kaskad88** [comment]
Hi @esalonico. Please check if the following option https://prnt.sc/14p4rfv is enabled in the WPML settings

**Comment by esalonico** [comment]
Yes, the option was enabled. I tried to disable it and enable it again but the problem is still there

**Comment by esalonico** [comment]
@kaskad88 please wait, I am in contact with the editor of the website and they are telling me that they changes some settings in the WMPL config and in the single articles, I will let you know if tweaking them back solves the issue.

**Comment by esalonico** [comment]
Nevermind, the problem is still there. @kaskad88 please let me know if I can help you troubleshoot it in any way. Thanks

**Comment by kaskad88** [comment]
Hi, @esalonico. You can see the solution in in https://support.crocoblock.com/support/tickets/33514
