### ISSUE TITLE
CPT inherit default WordPress taxonomies (categories and tags)

### ISSUE THREAD

**Issue by WPElementalist** [Crocoblock/suggestions#346]
By default if a custom post type (CPT) is created with jet engine the cpt is set to publicly queryable and should be able to be categorized and tagged with the default taxonomies in WordPress, however, they do not currently inherit the default taxonomies. 

This becomes a real problem if you wanted to create a category that will “glue” relationships between cpt and the default posts in WordPress, which is a powerful relationship as any and all plugins or services work with the default WordPress taxonomies by default. Now you have to make a custom taxonomy which sometimes isn’t supported in some widgets and plugins. 

Overall it would make design work easier and simpler for designers but also create extremely powerful interactions whenit comes to using archive templates and related posts widget with Elementor Pro as you can easily show multiple post types with a single, supported category instead of creating differentiating archive templates (or listings) for each Cpt, making design work harder later when you want to make a simple change you have to make it on each template for each cpt which can be a hassle.

Thanks for your time and the fantastic apps by crocoblock.

**Comment by realstephenzhao** [comment]
I know free Pods plugin can do this, but I don't want install another plugin.

Jetengine now can edit built-in post types(from version 2.0?), but it can't edit built-in taxonomies at this time. That's the problem.

Hope the developers from Crocoblock can provide this feature soon.

**Comment by zonerap** [comment]
+1

**Comment by lidocaine** [comment]
+1

**Comment by jamieburchell** [comment]
+1. How is this not a thing? I moved from PODS and am surprised this isn't part of JetEngine.

**Comment by kskonovalov** [comment]
+1 must-have feature, don't want to add CPT UI only for THIS

**Comment by datatime-sk** [comment]
+1. Please :)

**Comment by brentcopeland** [comment]
+1. Wow, just spent an hour trying to figure out how to get them to show up and found this.  This is such an obvious need that it kinda worries me that it's not already in the plugin. Especially when people have been asking for it for almost 3 years now.

**Comment by MjHead** [comment]
Added with 3.0.0 update
