### ISSUE TITLE
Jet Woo Builder - Add ability to edit FORMS on checkout page. Hide / delete, reorder, rename fields

### ISSUE THREAD

**Issue by DmitryBychenko** [CrocoBlock/suggestions#3462]
There was an issue on my website, and one of your specialists (ticket #34486) told me there is no compatibility with Crocoblock and Checkout Field Editor for WooCommerce (by ThemeHigh).

Im sure you know this is highly used feature.

Please add compatibility with this or similar plugins, or better add this feature into Jet Woo Builder.

**Comment by UraraReika** [comment]
I merged this issue with #2974, which is on the same subject so we could deal with it more efficiently.
