### ISSUE TITLE
CPT and Conditional Logic

### ISSUE THREAD

**Issue by marcoscioni** [CrocoBlock/suggestions#3464]
It would be interesting to implement the logical functions of visualization of the meta fields by extending the possibility to hide the tabs as well, just as it is possible to do in the ACF plugin.
In this way you can significantly shorten the entries on Post Type with variables such as the number of Stages of a Bike Tour
Regards, Marco

**Comment by Floydtm** [comment]
Could you describe your request in more detail. I also want to say that we have the logic of conditions for the meta fields https://prnt.sc/15lelkm and so there is a dynamic visibility module https://prnt.sc/15leopg

**Comment by marcoscioni** [comment]
Hello, the matter is very simple.The logical condition of ACF allows me to hide the tabs:  the logical condition of Jetengine does not allow me to hide the tabs  This means that in the management of the post the interface is not very manageable by the website manager as shown in the comparison images ACF (Compact view)  Jet Engine(Extended view)   so if you could hide the tabs like in ACF the problem would be solved.Regards, Marco      Inviato da Posta per Windows 10 Da: FloydInviato: mercoledì 16 giugno 2021 11:43A: Crocoblock/suggestionsCc: marcoscioni; AuthorOggetto: Re: [Crocoblock/suggestions] CPT and Conditional Logic (#3464) Could you describe your request in more detail. I also want to say that we have the logic of conditions for the meta fields https://prnt.sc/15lelkm and so there is a dynamic visibility module https://prnt.sc/15leopg—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kaskad88** [comment]
It was implemented in JetEngine 3.2.0
