### ISSUE TITLE
Add 'Buy Now' button and 'Swatches' option to variable products

### ISSUE THREAD

**Issue by zaheen** [CrocoBlock/suggestions#3468]
**Add 'Buy Now' button and 'Swatches' option to variable products.**

If you already don't have "BUY NOW" feature and "Color Swatches" for variable products, I think it will be a good feature to add to your WooBuilder plugin.

**Comment by 79ho3ein** [comment]
+1
Yes, exactly. They are very important, especially the Swatches feature.
I do not understand what you mean to buy now. Can you explain more?

**Comment by TODO4EVER** [comment]
I don't think they will be providing swatches anytime soon because they already have a guide advertising another plugin for swatches... I hope they include it, I really do, but I don't have much hope for it.

**Comment by UraraReika** [comment]
Hello @zaheen !

We will not implement 'Buy Now' button functionality. There are a lot of plugins in org that can be used. For example this https://wordpress.org/plugins/buy-now-button-for-woocommerce/. Make sure you disable this option https://i.gyazo.com/ba3e174976fdff663cc8b55fac0895f0.png. 

As for Swatches than watch this issue #361, which is on the same subject so we could deal with it more efficiently.
