### ISSUE TITLE
🔥[Jetengine] ability to export glossaries and query builder and forms

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3470]
![Groupe 4155](https://user-images.githubusercontent.com/82481592/121561833-26dddf00-ca19-11eb-8af3-f3d5dafff8a9.jpg)

for the moment I don't have a lot of glossaries and query builder but it will be very very delicate and complicated soon not to be able to export them to my fresh install

Additional informations

to avoid creating another post I also just noticed that the export of forms is very delicate
we can export / Import them only one by one 
and
working like that may be very delicate if we have a lot  of forms and even forget some...

I also noticed that I had created two deplicates to move faster and not redo the same steps over and over.

![Image 171](https://user-images.githubusercontent.com/82481592/122286430-213c3980-cef0-11eb-8e43-c907092f53de.png)

so my exports confused me (edit-user-copy? edit-user-copy2?) but I understood what happened

so I tried to update my slugs .. and ? surprise no slugs :)

![Plan de travail – 2](https://user-images.githubusercontent.com/82481592/122286667-66606b80-cef0-11eb-9f9c-a49f52a26fd8.png)

what is missing
- forms slug edit
- export forms

the ideal is to include the forms also in skin export, so we export all our work safely on a clean install

![Groupe 3076](https://user-images.githubusercontent.com/82481592/122286910-aa537080-cef0-11eb-8ce2-abdcb6f60234.png)

**Comment by xtofr** [comment]
Plus + 1 
very interested in adding the possibility to export/import glossaries. 
2 aspects : 
between dev & live site
I'm declining the same scheme of site in several fiels of  a university, so it is of particular interest to re-use glossaries
Thanks and congrats :)

**Comment by salbatyku** [comment]
+1 please for glossaries and query builder so we can export them easily.
