### ISSUE TITLE
Script Loading Map Listing and GDPR

### ISSUE THREAD

**Issue by sciam-digitalmedien** [CrocoBlock/suggestions#3471]
**Describe the bug**
To be precise: The issue is somhow between a bug and and improvement of service due to GDPR regulations

**To Reproduce**
1. To comply with GDPR we have to block all third party requests prior to user consent.
2. We therefore use Borlabs Cookies on all our clients' sites where content or scripts have to be blocked and consent to the loading has to be given.
3. When we enable borlabs and establish the script blocking, all 4 scripts (ressources)
	fonts.googleapis.com
	fonts.gstatic.com
	maps.gstatic.com
	maps.googleapis.com
 are successfully blocked.
4. After user has given consent, only maps.googleapis.com is sucessfully loaded, the others are not which means, that the map-widget is not working

**Expected behavior**
From other plugins and tools (and even your map-widget) this consent-related loading of blockes scripts works perfectly well

**Screenshots**

**Desktop (please complete the following information):**
all browsers

**Smartphone (please complete the following information):**
all devices

**Additional context**
We analyzed the issue with borlabs and they explained to us, that their tool only restarts the script loading, but that due to the architecure of some scripst this "lazyloading" does not work. So we hope, that you can resolve this issue, because as it is, we cannot use your wonderful tool.

Thank you very much for your help,

Martin

**Comment by About2git** [comment]
I experienced the very same problem…

I think Team Croco can also reach out to https://borlabs.io/borlabs-cookie/ https://borlabs.io/contact/ and they are willing to help / point you in the right direction.

**For the Script Blocker I used this:** 

jet-engine-frontend, jet-engine-google-maps-api, jet-maps-listings, jet-markerclustererplus, jet-search, jet-smart-filters 

+ the urls you send above.

@Crocoblock I even can send you the Borlabs Plugin with a License for testing debugging, from my agency license.

THIS IS REALLY NEEDED FOR GDPR / DSGVO Compliance.

**Comment by Floydtm** [comment]
Guys, please contact our support team to resolve this issue. Thank you!

**Comment by About2git** [comment]
Nice to have it open again. I also answered more details in the Support Ticket.

But here is some working examples:

These 2 Google Maps Plugins are compatible as described here [https://borlabs.io/kb/wp-google-maps-wp-google-maps-pro/](https://borlabs.io/kb/wp-google-maps-wp-google-maps-pro/)

Here is an Example Page, where it does work : [https://bestcarwash.de/](https://bestcarwash.de/). This is the Plugin used there: [https://wordpress.org/plugins/wp-google-map-plugin/](https://wordpress.org/plugins/wp-google-map-plugin/)


Also, the default Elementor Maps Widget is working perfectly -- out of the box: See example here: [https://ennepe-ruhr-entdecken.de/poi/shona-art-galerie-skulpturenpark/](https://ennepe-ruhr-entdecken.de/poi/shona-art-galerie-skulpturenpark/)

Thanks in advance.

**Comment by sciam-digitalmedien** [comment]
> 
> 
> Guys, please contact our support team to resolve this issue. Thank you!

Well the only reason I posted this issue here is the support team: I tried to explain the issue twice and both times they asked me to post it here ....

**Comment by sciam-digitalmedien** [comment]
> 
> 
> Nice to have it open again. I also answered more details in the Support Ticket.
> 
> But here is some working examples:
> 
> These 2 Google Maps Plugins are compatible as described here https://borlabs.io/kb/wp-google-maps-wp-google-maps-pro/
> 
> Here is an Example Page, where it does work : https://bestcarwash.de/. This is the Plugin used there: https://wordpress.org/plugins/wp-google-map-plugin/
> 
> Also, the default Elementor Maps Widget is working perfectly -- out of the box: See example here: https://ennepe-ruhr-entdecken.de/poi/shona-art-galerie-skulpturenpark/
> 
> Thanks in advance.

Thank you Marius for your input. Well as far as I understand/checked the bestcarwash.de might not be the best example, because resources from google are loaded even before I pressed the accept-button in borlabs. The map was blocked (with the boralbs overlay) but - at least in my tests - google showed up in the chrome developer tools as a ressource. 

Nevertheless the wp-google-map-plugin might be an appropriate "workaround" since it is able to show multiple adresses in one map. 

Yes, the elementor Maps widget is fine, but adresses have to be added manually - or did I oversee something? The solution we wanted to estblish is as follows:

-- We have a custom post type for real estates
-- Adresses are importet automatically from the agents CRM
-- Jet engine could dynamically detect the adresses and show them in the map (as map listing)

Do you think this will work with the elementor wiget as well? So far I have not found any possibility to achieve this result.

Kind regards, Martin

**Comment by About2git** [comment]
> > Nice to have it open again. I also answered more details in the Support Ticket.
> > But here is some working examples:
> > These 2 Google Maps Plugins are compatible as described here https://borlabs.io/kb/wp-google-maps-wp-google-maps-pro/
> > Here is an Example Page, where it does work : https://bestcarwash.de/. This is the Plugin used there: https://wordpress.org/plugins/wp-google-map-plugin/
> > Also, the default Elementor Maps Widget is working perfectly -- out of the box: See example here: https://ennepe-ruhr-entdecken.de/poi/shona-art-galerie-skulpturenpark/
> > Thanks in advance.
> 
> Thank you Marius for your input. Well as far as I understand/checked the bestcarwash.de might not be the best example, because resources from google are loaded even before I pressed the accept-button in borlabs. The map was blocked (with the boralbs overlay) but - at least in my tests - google showed up in the chrome developer tools as a ressource.
> 
> Nevertheless the wp-google-map-plugin might be an appropriate "workaround" since it is able to show multiple adresses in one map.
> 
> Yes, the elementor Maps widget is fine, but adresses have to be added manually - or did I oversee something? The solution we wanted to estblish is as follows:
> 
> -- We have a custom post type for real estates
> -- Adresses are importet automatically from the agents CRM
> -- Jet engine could dynamically detect the adresses and show them in the map (as map listing)
> 
> Do you think this will work with the elementor wiget as well? So far I have not found any possibility to achieve this result.
> 
> Kind regards, Martin

Yes, the bestcarwash and Elementor are only examples for the developer, where Blocking and Loading is working.

@kaskad88 maybe this is helpful as a resource  (Documentation in english): [https://borlabs.io/kbtopic/borlabs-cookie/](https://borlabs.io/kbtopic/borlabs-cookie/)

**Comment by About2git** [comment]
Hi Martin,

the Elementor Maps Widget has a Dynamic Option. This should work as long as you get the whole address in one field from your CRM.
see here: [https://imgur.com/a/j4TdQZ5](https://imgur.com/a/j4TdQZ5)

BUT I still need this to work. Ben from Borlabs Cookie said it should work:

> Basically, JavaScript code must be blocked, this can be done with the script blocker from our plugin. Since the JavaScript often waits for the DOMContentLoaded event in order to initialize the code, the name of the function is simply required, which must be called afterwards in order to initialize all JavaScript.

Ben from Borlabs Cookies (wrote to me).

------

> 
> -- We have a custom post type for real estates
> -- Adresses are importet automatically from the agents CRM
> -- Jet engine could dynamically detect the adresses and show them in the map (as map listing)
> 
> Do you think this will work with the elementor wiget as well? So far I have not found any possibility to achieve this result.
> 
> Kind regards, Martin

**Comment by chronoB** [comment]
If got the same problem I guess. Is there any update on the compatibility with Borlabs and the GDPR?

**Comment by About2git** [comment]
My latest on this is we need another inject method to load the map and the developers will work on it if they have time: This is what the support wrote 10 days ago:

> There can be no alternative call to reinitialize the map. This issue is still in the list of the issues to be implemented by the developers though :)
> Please, kindly understand we have hot fixes and fixes to implement, then the roadmap and then the suggestions and the third-party compatibilities.
> Please, kindly await the version release with the needed fix :)

**Comment by kaskad88** [comment]
Added compatibility for the next version ( v2.11.5 )

**Comment by About2git** [comment]
Woohooo!  It is working! And that in these hard times for your guys… 

Thank you very much!

Stay safe.
