### ISSUE TITLE
Please add the ability to transfer unavailable products at the bottom of the list in jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3472]
It would be great if you could add a feature to the jet woobuilder plugin, especially the product grid widget, so that we can move out of  products to the bottom of the list.This feature is extremely important.
Of course, this feature will be useful when we have used the product grid widget to display the product archive. 
If you are careful, all major online stores used this feature.
This feature in the product grid widget can be enabled or disabled as a button.Such as the ability to open a new window, which will be released in a future update.
Please review this request and add it to the plugin if possible.

Thank you for your efforts

**Comment by UraraReika** [comment]
I am not sure if  I understand your request right so please describe on more details.

**Comment by 79ho3ein** [comment]
@UraraReika 
Yes, Sure...
I saw this feature in several large store sites, which was very interesting and useful.
On these websites, products with inventory of 0 were at the bottom of the product archive.
For example, suppose the stock of 3 products in our store is exhausted. If we use this feature, these 3 products will automatically be at the bottom of the product archive. They are located exactly in the position indicated in this image. The end of the archive : http://i.prntscr.com/2HiwSPK8QgCxjvYhxX9sjA.png
In general, products with an inventory of 0 are at the bottom of the list. As such, the priority of the show is with the products available.
To better understand this request, I will show you the code of this feature : 

add_filter( 'woocommerce_get_catalog_ordering_args', 'mihanwp_sort_by_stock', 9999 );
function mihanwp_sort_by_stock( $args ) {
   $args['orderby'] = 'meta_value';
   $args['order'] = 'ASC';
   $args['meta_key'] = '_stock_status';
   return $args;
}

**The reason I prefer this feature to be added to jet woobuilder so that we do not use code, is the fact that these codes over time cause errors on the site.In addition, by updating the  website template, these codes are removed and cause trouble.
But if this feature is added to the jet woobuilder, there will be no problem.**
Great if you add this feature to jet woobuilder. Especially to the product grid widget.
Using this feature can be optional. Just like other features that are optional in the product grid widget. Like this : http://i.prntscr.com/npJQWgkUQEuuLuuZyU0KDw.png

This feature will be extremely useful. Please add it to jet woobuilder if possible.
I hope I conveyed my words well.

thanks
