### ISSUE TITLE
Sorting taxonomies on Form

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#3473]
This is a request when creating a Form using JetEngine's Form Widget. If you specify Filed Type as select or CheckBox or Radio in Form field, specify Fill options Form as terms, and then create a Form, you cannot order or sort the terms. When the user selects the corresponding item in the Form, the order in which they are displayed is random and very difficult to find. It would be very helpful to be able to rearrange the order of terms. At the same time, it is even more convenient to have Group terms by parents, like the features that exist in Smart Filters. Hierarchical terms are also displayed in an easy-to-understand manner, and you should be able to create a Form that is easy for users to see.

**Comment by lukepatrickillustrations** [comment]
Yes I agree, this doesn't seem like a feature request but more of a missing feature that a user would expect. You should be able to reorder taxonomies as you can with Woocommerce Product categories. They have 3 bars on the right side that allow you to reorder them quickly and the filters would reflect that order. A very important feature that would save people a lot of frustration.

**Comment by dmvega81** [comment]
+1

**Comment by Floydtm** [comment]
So far, we cannot fully implement this in our plugins. Please use this [plugin](https://wordpress.org/plugins/intuitive-custom-post-order/) to resolve your issue. Thank you!
