### ISSUE TITLE
Please add a feature to the jet woobuilder plugin so that I can show users the number of sales of each product.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3475]
I saw one of the store websites created with WooCommerce, which shows the number of sales of each product to users.
This image shows : http://i.prntscr.com/m3Ac_po5ToCI98ASje-MTg.png
This feature caught my attention a lot.Because it is extremely practical and greatly increases the conversion rate.
It would be great if you could add this feature to the Jet woobuilder plugin. This is not a request outside of WooCommerce.
Of course, I found a plugin for this feature, but I and many users prefer to use the Jet woobuilder plugin for these features rather than other malicious plugins.
This great feature will be useful for the product grid widget. Of course, it is better to use it optionally. Such as the title tooltip feature and other features that are optional in the product grid widget.
Please check this feature and add it to jet woobuilder if possible. This feature will be extremely useful.

Thanks to crocoblock🌹

**Comment by 79ho3ein** [comment]
@UraraReika
Thank you
Please add this feature to the plugin if possible.
It will be extremely practical and excellent.

**Comment by DevDietheR** [comment]
+1

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Sorry but we will not implement this feature to our core! There a lot of plugin with that kind of functionality and you can easelly use it and put whatever you want by rewritten one of products grid templates.
