### ISSUE TITLE
Relationship fields & relationship table

### ISSUE THREAD

**Issue by ArekZw** [CrocoBlock/suggestions#3476]
1. Relationship fields
It's handy feature to record save meta information about a relationship. 

For example:
People <--- many to many ---> Teams
Meta info:
- Role 
- Permissions (multiselect)
- Date of joining

2. Separate relationship table 
This has obvious performance benefits compared to post_meta searches and allows you to easily add relationship fields. 

1&2 Also allows for more advanced and fast searches, e.g. "find all people who have leadership roles in at least one team" or "Find a team without a leader" or "find all people on team X that have permission to add new members" or "find all members of team X who joined in last year". This is a very simple example to show the possibilities.

-----
This is already in toolset:
https://toolset.com/course-lesson/many-to-many-post-relationships/ (ctrl+f: Adding relationship fields)

I'm not sure, but I think the Pods also have this feature

**Comment by MjHead** [comment]
Added with 2.11.0
