### ISSUE TITLE
dynamic visibility and listing does not work together

### ISSUE THREAD

**Issue by yaron86** [CrocoBlock/suggestions#3477]
i want to add inside a listing a dynamic visibility image that will show only on specific category, so i made:

1. show element if condition is met
2. contains - post terms with the slug value

but the issue is in the post terms when clicking the wrench icon, there is no option to choose the cpu because this dynamic visibility is being used under the listing.  when i try doing this on a regular archive page i can choose the cpt and it works fine.
any suggestions?

![image](https://user-images.githubusercontent.com/3582979/121800362-f88b1a00-cc39-11eb-867a-9c297a273e42.png)

**Comment by yaron86** [comment]
seems that a small refresh fix this issue.

**Comment by kaskad88** [comment]
Upgrade to JettEngine 2.10.1 and use the `Post Has Terms` condition.
