### ISSUE TITLE
Hide/Remove Out of Stock Products in Products Grid Widget (Carousel)

### ISSUE THREAD

**Issue by shashikant-rohit** [CrocoBlock/suggestions#3478]
Hi Team,

I had a chat with your support executive & asked them about removing out of stock products in the carousel of products grid widget. But unfortunately I have got a revert that this option is not available currently.

Request you to kindly consider this as a feature request & develop the same in the upcoming releases.

Currently when we add products in the Products Grid widget & convert them to carousels we have NO option of removing out of stock products.

Example: If we want to show recently added or recently listed products on the front (home) page, it gives a bad impression to customers if we show them out of stock products. (We list out of stock products wantedly - wait for the physical stock to come but wanted to make sure that customers are aware of the availability of the product on our website)

Hence removing out of stock products on the Home page is a very basic requirement.

Kindly consider the same & help us add this feature so that developers like us can promote & use your paid plugins on more number of woocommerce website for our clients.

Thanks & Regards,
Shashikant

**Comment by UraraReika** [comment]
Hello @shashikant-rohit !

Right now you can use this option https://i.gyazo.com/bba13c8f1f5c7a5245c9128ed8db3301.png in Woocommerce -> Settings -> Products -> Inventory. We will consider about your issue and add as separate control for product widgets.

**Comment by shashikant-rohit** [comment]
Hi,

Please read the requirement carefully.

You are suggesting me to hide the products on overall website. But I wanted
to only hide it on front page.

That option is already known since long.

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
https://i.gyazo.com/f38ed71942702e9ae69b861458231287.png this option https://i.gyazo.com/9bbf9fe815d705931944ed5e41cd2a06.png. Then 

```
add_action( 'jet-woo-builder/query/hide_out_of_stock', '__your_theme_prefix_hide_out_of_stock_products' );

function __your_theme_prefix_hide_out_of_stock_products( $query ) {
	$query->query_vars['meta_query'][] = [
		'key'     => '_stock_status',
		'value'   => 'outofstock',
		'compare' => 'NOT LIKE',
	];
}
```

**Comment by Irinel123** [comment]
> https://i.gyazo.com/f38ed71942702e9ae69b861458231287.png această opțiune https://i.gyazo.com/9bbf9fe815d705931944ed5e41cd2a06.png . Apoi
> 
> ```
> add_action( 'jet-woo-builder/query/hide_out_of_stock', '__your_theme_prefix_hide_out_of_stock_products' );
> 
> function __your_theme_prefix_hide_out_of_stock_products( $query ) {
> 	$query->query_vars['meta_query'][] = [
> 		'key'     => '_stock_status',
> 		'value'   => 'outofstock',
> 		'compare' => 'NOT LIKE',
> 	];
> }
> ```
Unfortunately for me it doesn't work on the grid listing in jet
