### ISSUE TITLE
Add a title of the repeater group when is folded

### ISSUE THREAD

**Issue by RumenGeorgieff** [CrocoBlock/suggestions#3479]
It would be very nice if you make first field of a repeater group to be the title for the group when it's folded. For example: I want to create group of repeater fields for members, that include fields like: name, position, picture, description and etc. When I add 10-20 members, the page is getting pretty long because the group of every member is open. The problem is that if I folded the groups of already added members, there is no indicator which group for which member is. It looks like this: https://prnt.sc/15dw82v .. no title, no name .. no nothing. Image if I have 50 members? What about 100? It would be great if there is a way the field groups to have a title or name when they are folded, something like this: https://prnt.sc/15dwegp . Maybe the value of the title could be pulled from the first field or I don't know .. 

Thank you :)

**Comment by RumenGeorgieff** [comment]
Here is a live example: I'm creating a website for a hospital which have several clinics and every clinic have different team of medics. I'm using repeater to add the medics. Everyone of them have name and description. This clinic have team of 34 medics. Look the page length when all repeater groups are unfolded (whic is the default state). Now check when they are folded. It's better but then if I have to edit someone of the medics, I have to check manually everyone of the group, because they don't have any indication (name) of the fields they contain. 

![unfolded](https://user-images.githubusercontent.com/2687942/121897759-5fd4c700-cd2b-11eb-8f26-5c714ed2947d.png)
![folded](https://user-images.githubusercontent.com/2687942/121897752-5ea39a00-cd2b-11eb-80d6-ce0598b73198.png)

**Comment by Lonsdale201** [comment]
Yes +1 :)

**Comment by nreljed** [comment]
#3514

**Comment by kaskad88** [comment]
Added in JetEngine 2.10.2 https://prnt.sc/20xamn3
