### ISSUE TITLE
Difficulty displaying discount percentages on variable products. (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3480]
Hello
If I am not mistaken, I have already submitted a request in this regard. But this time I will state my intention more clearly.I hope I can convince you dear developers to solve this problem.
If we give a special sale price for products that are variable, the product discount percentage is displayed as a range, which is not interesting at all. https://prnt.sc/15ex4zr
For example, if we have a product in 5 colors with different prices, and we put a special sale price for each color, this problem arises.
This problem is generally present in jet woobuilder. Of course I use the product grid widget ...

Suggestion to solve this problem : 
Please, if possible, add settings at the bottom of the section where we select the type of discount display, so that we can choose which displays the lowest discount, or the highest discount. this part : https://prnt.sc/15evt30
If you add this feature, if we choose to display the lowest percentage discount, the problem will change from this ( https://prnt.sc/15ex4zr ) mode to this ( https://prnt.sc/15exs1y ) mode. Because we chose to show the lowest percentage of product discount.
Please fix this problem if possible.It is very troublesome on sites that have variable products.

thanks

**Comment by UraraReika** [comment]
Hello @79ho3ein !

If you already wrote about it then we answered. Use this code snippet https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce which add more macros to sale badge functionality and you can display min or max discount percentage. If you feel difficult with this please contact our support team.

**Comment by 79ho3ein** [comment]
dear @UraraReika  
I used this code but this problem still exists. https://prnt.sc/15hxhh9

**Comment by UraraReika** [comment]
So you did something wrong. If you feel difficult with this please contact our support team.
