### ISSUE TITLE
Duplicate post from front end

### ISSUE THREAD

**Issue by hakerdesign** [CrocoBlock/suggestions#3484]
please add a feature  where memeber will be Abel to duplicate their post form front end In membeer area post list.
 Right now they can edit their post and delete it but there is no way to duplicate iy
thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
