### ISSUE TITLE
Change url structure of the pagination widget

### ISSUE THREAD

**Issue by pgirzalsky** [CrocoBlock/suggestions#3485]
I want to be able change the url structure set by the pagination widget.
For example 
https://lendis.io/magazin/kategorie/office-life/?jsf=jet-engine:current_category&pagenum=2 
should simply be
https://lendis.io/magazin/kategorie/office-life/page/2
like it does with Elementor's native post widget if you enable pagination there.

An example with Elementor's native widget can be found here:
https://lendis.io/magazine/alle/page/2/

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
