### ISSUE TITLE
There are two important bugs in the jet smart filters plugin. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3486]
hello @Floydtm
Thank you for your attention to our reports and suggestions...
There are some small bugs in the jet smart filter plugin update, please fix it. Because it has severely affected the user interface.

1- In all filters, the options are almost stuck together and we can not put a space between them : https://prnt.sc/15hnkfc
As you can see in the image, the distance between the color, the text and the number of filters is zero.
**This problem also exists in the filters of checkboxes, radios, etc.**
Please add a feature to all filters so that we can create space between the elements of each filter.

2- The display of the number of available filters is not aligned with the filter text. And is slightly above the text.
https://prnt.sc/15hocr1 .This bug is very noticeable on tablets and mobile phones : https://prnt.sc/15hoi6g
**This bug only exists in the visual filter.**

Please consider these two important issues. Thank you

**Comment by Medienor** [comment]
Have you tried to use custom CSS? I believe this can be fixed with CSS.

**Comment by 79ho3ein** [comment]
@Medienor 
Yes it can be solved. But it is better to have these items in the plugin. Because not all css users know.
Similar items are observed in this plugin. Apparently, the developers were unaware of this.
In any case, I hope the dear developers will solve these problems in the next version.

Thank you for your attention.

**Comment by 79ho3ein** [comment]
@Floydtm
There is another bug in this version ...
If we put space between the pagination boxes, on the mobile, there will be a responsive problem. https://prnt.sc/15l7yzu
This problem did not exist before.Please check

thanks

**Comment by 79ho3ein** [comment]
If the number of products to display is small, the paging widget space will remain blank. https://prnt.sc/15l8guo
Please check for these bugs. Unfortunately, the jet smart filters plugin adds a lot of bugs in every update.

**Comment by 79ho3ein** [comment]
@SargasTM please check. thanks
