### ISSUE TITLE
Option to remove whole element/multiple css classes when products are not found within a product grid. [JetWooBuilder]

### ISSUE THREAD

**Issue by danekoenders** [CrocoBlock/suggestions#3487]
When you pick a product grid element from JetWooBuilder and you use the option "Recently viewed" in the query. It gives you the option to pick a message that will be shown when the customer hasn't viewed any recently products yet. This can be quite annoying since you don't want to show that on your store's front page is it doesn't recommend any products. So It would be cool to get a feature to remove the whole element and/or certain css classes when the products grid doesn't recommend any products. If you use a caching plugin and your divs will be cached, it can be a pain because it will not show the recently viewed products immediately after you've visited a product. This can take up to as long as the cache is renewed. So it would be nice if it can be hidden until then. Kind regards, Dane

**Comment by 79ho3ein** [comment]
@DutchDane 
Yes, unfortunately this problem exists for me as well. Therefore, I can not show recently visited products to users.
This is not a problem with jet woobuilder. But also the problem of cache plugins.

**Comment by DevDietheR** [comment]
+1

**Comment by UraraReika** [comment]
Hello @DutchDane !

We will not implement this functionality. You can easelly manipulate optional and style controls to achieve clean output, as for caching plugin it can be setup to ignore certain parts of your site. If you feel problems the you can contact our support team.
