### ISSUE TITLE
Automatic indexer capability in jet smart filters plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3488]
Great if you add a feature, so the indexer works automatically.
This feature will be extremely useful. Because when the customer enters the products on the site, he does not remember to do the indexing manually. Therefore, we (the site designer) have to do this for them every time, and this is very problematic.
If you add this feature, it will be automatically indexed after each time the product is posted on the site, and that would be great.

Thank you dear developers.

**Comment by nreljed** [comment]
#3465

**Comment by 79ho3ein** [comment]
@SargasTM please check. thanks
