### ISSUE TITLE
Crocoblock: Consider adding breadcrumbs to admin screens for Jet Products

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#3493]
Navigating around Crocoblocks extensive product list can take quite some time, especially if you're navigating between multiple screens, e.g. going to different CCT's or Forms and Query Builder. One quick way to help alleviate some of the hassle of getting around would be to try and implement some sort of breadcrumb functionality. I realise that Wordpress way of admin pages is quite bad, but it can be just a little better. 

Ideally the breadcrumbs will have a dropdown that all possible paths out of the page you're in, e.g. Custom Post Types the dropdown would have Add New > Edit ... <retrieve a list of your existing CPT>.. 

I haven't found a good way of retrieving the page by query to populate a Breadcrumb but I'm pretty sure there's some funky Javascript out there that can construct it: 

https://badwordpresssite.sigh/admin.php?page=jet-engine-cpt&cpt_action=edit&id=11
https://badwordpresssite.sigh/admin.php?page=jet-engine-cct&cct_action=edit&id=4

This would vastly help improve navigating around the product

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
