### ISSUE TITLE
Date format for Custom Meta Box Field

### ISSUE THREAD

**Issue by JennyPower** [CrocoBlock/suggestions#3494]
The date custom meta box field should default to the date format in the WordPress settings. Whilst you can format the date on the frontend, the metabox in the editor is fixed at United States date format.

Alternatively, add a setting to the meta box field to set the date format for both the front end and the editor.

Further to this, if you put in the date in the format d/m/y it excepts the date without any notification but doesn't save it - this is a bug

**Comment by vinnyCalixto** [comment]
Any news?

**Comment by jh4tz** [comment]
Same issue here - datetime field also shows default as 2021-12-14T12:12 on front end and back end and no setting available to change in meta box settings or in the editor.

**Comment by kaskad88** [comment]
Add for the next version( 2.10.3 ). Thanks for your report!
