### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by sonnesworld** [CrocoBlock/suggestions#3495]
I really like the JetSmartFilter plugin but missing a filter for products in stock so users can filter and show just products which are in stock like here: https://us.louisvuitton.com/eng-us/women/handbags/iconic-monogram-bags/_/N-1b916w8
![image](https://user-images.githubusercontent.com/57396134/122180881-20bc8800-ce89-11eb-9d99-4f9833ae4252.png)

**Comment by 79ho3ein** [comment]
+1
Excellent offer

**Comment by Floydtm** [comment]
You can do it right now https://prnt.sc/166a04o https://prnt.sc/166a3l2
