### ISSUE TITLE
If the current query option is enabled, it is not possible to display products randomly. (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3498]
hello
I use the product grid widget to display the product archive.But one problem is that when we enable the current query option in this widget, it is not possible to display products randomly.
Because of this, many products with similar names are put together that do not create an interesting user interface. In this image you can see two examples : https://prnt.sc/15lmmnz
Great if you add a feature, so that if the current query option is enabled, we can display products randomly.
Unfortunately, by activating the current query option, the possibility of displaying products randomly is eliminated.
please check

Thanks to crocoblock

**Comment by UraraReika** [comment]
If you enable this option then widget takes query from this settings https://i.gyazo.com/23618009da5255189665562d8afc9768.png. You can easelly add needed parameter with woocommerce hook. Or you can use theme with predefined more parameters.
