### ISSUE TITLE
Bug: page breaks in JetEngine forms result in error

### ISSUE THREAD

**Issue by simonvanoordt** [CrocoBlock/suggestions#3500]
**Describe the bug**
Adding a page break to a user registration forms results in error: "One or more fields have an error. Please check and try again"

**To Reproduce**
1. Add user registration form
2. Insert page break
3. Try to register a user
5. Copy form
6. remove page break
7. test form
8. no error

**Tested on Desktop (please complete the following information):**
 - Windows
 - Chrome , edge
- JetEngine 2.8.5

**extra information**
I haven't tested other type of forms (e.g. create post)...

**Comment by Floydtm** [comment]
To resolve your request, you need to contact our support team. Guys will help you quickly resolve this request
