### ISSUE TITLE
Two important bugs in the new version of the jet woobuilder plugin. Please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3502]
Hi @UraraReika 
There were two important bugs in the new update, which made me refrain from updating this plugin. Especially case number 1.
I will explain these two problems below...

1- The coupon section on the payment page is completely inverted. So that it can not be used at all.That's why I decided to stay in the previous version. See these changes(bug) in the image :
Before the update : https://prnt.sc/15n6b86
After the update : https://prnt.sc/15n6ecj
The form field has been moved to the left of the button, while it was on the right side of the button before the update

2- The "Make Product Product Clickable" option has many bugs. Most importantly, when we enable it, the product box hover mode no longer works. That means we can no longer specify that if the mouse hovers over the product box, it will be shaded around it.

Again, the "Make Product Product Clickable" feature does not work properly. Because when we activate it, all parts of the product carousel have links.
While only the area specified in the image should have a link. That is, the product box : https://prnt.sc/15n8lx2
In the current situation, when we enable the "Make Product Product Clickable" option, all the specified parts have links.
All episodes :https://prnt.sc/15n9371
For the "Make Product Product Clickable" option to be complete and work properly, the red areas should not have links and only the white sides should have links : https://prnt.sc/15namu7
Finally, there is a simple but very important point that has been observed in other sites. I say, please consider it. If the "Make Product Product Clickable" option is enabled, even the border around the product box should not have a link. 
The link will only exist before the border. And the border itself does not contain a link : https://prnt.sc/15nbfgz

**Please fix these bugs soon. One month is too long for the next version.😔**

Thank you very much for your attention to our requests.

**Comment by UraraReika** [comment]
We check our widget in rtl and it works proper. As for clickable items you should be more specific when you lease the reply. In thats chase contact our support team with this request they will help you to achieve needed results.

**Comment by 79ho3ein** [comment]
hi @UraraReika Thank you for your attention.
I checked the first case or the payment coupon and found that this rtl problem only exists in the editor. But on the website it is true.
Please fix this problem in the editor if possible.

Regarding the second case, will there be no changes in the next version?
Because I checked the said bugs in some of my sites and there were.

In any case, we sincerely appreciate your efforts.
