### ISSUE TITLE
JetWooBuilder: Customizable time  period for Best Sales product ordering in Products Grid

### ISSUE THREAD

**Issue by makovane** [CrocoBlock/suggestions#3507]
The 'top sellers' have clear marketing value for the store. But if only all time top sellers are listed,  the listing changes very rarely.

Therefore the best sellers' period of examination should be customizable on a basis of days, weeks or months.

**Comment by UraraReika** [comment]
Use Query ID option https://i.gyazo.com/c63d9da5d756a893a2e4caeb1202f673.png. And code below as example to achieve needed result. (You can put to Query ID option whatever you want name but then put it here 'jet-woo-builder/query/{your-name}') 

```
add_action( 'jet-woo-builder/query/best-sellers', '__your_theme_prefix_get_bestsellers_products' );

function __your_theme_prefix_get_bestsellers_products( $query ) {
	$query->query_vars['meta_query'][] = [
		'key' => 'total_sales',
		'value' => 0,
		'compare' => '>'
	];
}
```
