### ISSUE TITLE
JetBlog: exclude the current post

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#351]
Using Smart Posts Lists with a Custom Query, is there a way to exclude the current post from showing up on the list without refering to the actual ID of the Post? This is because I'm doing it on a template. I want it to apply to all of my posts and to automatically detect the Post ID. I've tried using "post__not_in":["%current_id%"] but haven't been sucessfull.

I'd also like to do the same thing for Tags detection. Instead of using "tag":"comedy", I want it to automatically detect the tag of the post. Used "tag":"%current_tags%" but nothing as well.

**Comment by kaskad88** [comment]
Added for the next version

**Comment by yyc-food-blog** [comment]
Did you figure this out?  "post__not_in":["%current_id%"]  is not working for me.
