### ISSUE TITLE
Request to improve the navigation point performance of "Product Carousel" jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3510]
Hello
Currently, we can only increase or decrease the size of the navigation points. But for example, we can not take its shape out of the square,And change its appearance to your liking.
This means that we can not currently design navigation points in this way : https://prnt.sc/15srpy9
Instead, we can only make it smaller or larger : https://prnt.sc/15srufg
It would be great if you could add a feature that allows you to specify the size of the navigation points in width and height.
In this case, we can customize the navigation points.
Please consider this request. It will be very useful.

Thank you for your efforts

**Comment by UraraReika** [comment]
You can do same thing like this https://github.com/Crocoblock/suggestions/issues/3102
