### ISSUE TITLE
🔥[Jetengine] one repeater is enough

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3514]
Hi Friends, 

I hope this request will finally be heard and understood 
this issue has been around for a long time.
because you have no idea how much confusion it generates ... even I am very confused sometimes I get lost.

I'm talking of course about jetengine repeater,
we can't see what's going on without opening them
you imagine yourself playing with 20 white repeater and especially trying to guess what's inside ... and organize them in order?
yes ? go try it is very fun :)

demo of actual situation I'm trying to organize my 3 repeaters..
![backend](https://user-images.githubusercontent.com/82481592/122597066-c1b26b00-d062-11eb-823d-6272966973bd.gif)

## Solution 

the solution is in front of our eyes :)

if my eyes see well we have 3 types of repeater

one  for fields (backend)
one  for the jetengine menus (glossaries) etc..  (backend)
one  for forms. (frontend)

It's a lot of repeaters and code isn't it? 

oddly, in jetengine menus you have a super functional, efficient and fluid repeater with already include a 
duplicate and delete actions buttons 
it's super easy, fast and mobile friendly already ! 

![gloosary](https://user-images.githubusercontent.com/82481592/122597228-00482580-d063-11eb-976e-a5f2530889ab.gif)

## your idea please 

so my idea is so simple .. 
why not use this super handy repeater globally in backend and frontend (forms) ? 

make it a little customizable and voila !

visualize the result

![Groupe 4232](https://user-images.githubusercontent.com/82481592/122595013-b3168480-d05f-11eb-8faa-438b42d8173f.png)

![Groupe 4238](https://user-images.githubusercontent.com/82481592/122599408-3cc95080-d066-11eb-8df9-d807ead900c2.png)

![Groupe 4234](https://user-images.githubusercontent.com/82481592/122594997-ad20a380-d05f-11eb-9280-875530392336.png)

demo form updated repeater 
![new repeater form](https://user-images.githubusercontent.com/82481592/122597834-dd6a4100-d063-11eb-83c0-270947a5938e.gif)

benefits :

we will finally be able to see our repeater!
we can finally reorganize the order of our repeater frontend and backend.
we can finally duplicate and delete easily
we can finally offer a consistent global solution for the frontend and backend
customization colors and font button
bye bye the frustrating customization of close button (repeater forms) try it to see what I'm talking about :)
[developers] less code so less problems
[developers] target problems more easily with just one repeater to fix

**Comment by Lonsdale201** [comment]
+1

**Comment by DevDietheR** [comment]
+1

**Comment by ayhanmalkoc** [comment]
+1

**Comment by simplicity17** [comment]
+100 This is a MUST

**Comment by kaskad88** [comment]
Added in JetEngine 2.10.2 https://prnt.sc/20xamn3
