### ISSUE TITLE
Outline problem of all crocoblock plugins in hello elementor theme.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3515]
Unfortunately, this problem is present in all crocobloc plugins. The problem is that all the text and buttons that have a link are "outline" after clicking. Please pay attention to the images below which are in the jet woobuilder plugin :
Before clicking : https://prnt.sc/15ubgez That is not a problem
After clicking : https://prnt.sc/15ubjv8 After clicking, a black border appears.

This problem with the code: outline: none; Is solved, but The number of these cases is so large that it is very time consuming to code for each of them.
This problem is very common in jet search plugins, jet smart filters and jet wooobuilder. Please think about fixing them. Every time I code, their number decreases, but they still exist. This problem also exists on the websites of colleagues who use these plugins.
Finally, it is better to remind that apparently this problem only occurs with the hello elementor theme. Please fix this problem once and for all from your plugins.

Thanks to the crocoblock team.

**Comment by kamyabnazari** [comment]
I have also the same problem with the hello elementor theme, have you found a solution for this?
