### ISSUE TITLE
Report bug in open product feature in new window (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3518]
hi @UraraReika
I noticed a bug in this feature and wanted to report it to you. Please investigate this issue. https://prnt.sc/15yutee
I display my product archive with the product grid widget. And to paginate it, I use the paging widget of the jet smart filters plugin.
The problem I noticed is that the "Open Products in new window" feature Works only on the first page of the product archive.And when we enter the second page of the product archive, the products do not open in a new window.
This problem occurs when you enable the Ajax feature in the jet smart filters plugin widget.
I checked this bug on several of my sites and it existed.

Thank you for your attention.

**Comment by UraraReika** [comment]
I check your issue and everything works proper. Please contact our support so we can check it on your side.

**Comment by 79ho3ein** [comment]
Thank you @UraraReika
Was the Ajax paging widget enabled when you tested this problem? https://prnt.sc/166nvjj

Did you pay attention to this point? > **There is no problem on the first page and the products open on the new page. But on the second, third, etc. page, other products will not open on the new page.**
May you review this bug again? Because I saw this problem on several sites.
Please check this site to better understand this problem. https://avangwebsite.ir/product-category/mobile/
You will see that on the second page, the products will not open on the new page. 

Thanks🌹

**Comment by UraraReika** [comment]
Please contact our support team.

**Comment by 79ho3ein** [comment]
ok,thank you
