### ISSUE TITLE
JetSearch - SKU search

### ISSUE THREAD

**Issue by Steriotis** [CrocoBlock/suggestions#352]
Please add the feature to search product by SKU.

**Comment by kaskad88** [comment]
This feature will be available in v2.0.0

**Comment by Steriotis** [comment]
> This feature will be available in v2.0.0

Nice to see this but when v2.0.0 will be available for download ?

**Comment by ghost** [comment]
Its 2023, Still not available

**Comment by kaskad88** [comment]
@911-shohan its available since 2019 https://tppr.me/YBUHh
