### ISSUE TITLE
Make JetCompareWishlist compatible with listings / post types

### ISSUE THREAD

**Issue by drwillems** [CrocoBlock/suggestions#3520]
So far JetCompareWishlist is only compatible with Woocommerce products. I was wondering whether it would be possible to make it compatible with listings / post types. This is especially useful for website that have listings. Example of those would be Realtor website, Hotel booking, Service booking, etc.
In the end it will come down to the compatibility with the listings / post types created within JetEngine.

A similar solution is provided by GeoDirectory - https://wpgeodirectory.com/ .
They have an addon that makes it possible to compare listings called - https://wpgeodirectory.com/downloads/compare-listings/

I would be amazing for users of a listing website to compare them against each other and also a great assets within the Crocoblock toolkit. Also a new use case for the JetCompareWishlist plugin.

**Comment by UraraReika** [comment]
You can use Data Stores module build in JetEngine https://crocoblock.com/knowledge-base/articles/jetengine-data-stores-module-overview/

**Comment by UraraReika** [comment]
We’ve not heard back from you in a while, so I’m marking this thread as resolved. Hopefully, you were able to find a solution to your problem! If you have further questions, please feel free to open a new topic.
