### ISSUE TITLE
In the jet compare & wishlist plugin, if the user is not registered on the site, please redirect it to the login page.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3521]
hello
In the jet compare & wishlist plugin, products are not added to the wishlist properly when the user is not logged in. For example, if it adds one product, it sees that 3 products have been added. In this case, the user thinks the site has a problem.
But if the user logs in, the product is added to the list properly and everything works great.
I suggest adding a feature so that the user will not be able to see their wish list when they are not logged in.
In this case, if the user who is not logged in wants to see his favorites list, he will be redirected to the login and registration page, to register first, then he can see his  favorites list.

thanks

**Comment by UraraReika** [comment]
I merged this issue with #3009, which is on the same subject so we could deal with it more efficiently.

We asked you already. Stop duplicating issues.

**Comment by 79ho3ein** [comment]
That's right, I forgot. I'm sorry.
