### ISSUE TITLE
JetEngine: Dynamic Visibility, Options for Parent and Child Pages

### ISSUE THREAD

**Issue by schndr-cdn** [CrocoBlock/suggestions#3522]
Please add these Options:

**_Show if / Hide if..._**
1. If Page is a Parent-Page
2. If Page is a Child-Page
3. Child-Page of Post-ID

These Options can keep us away from adding hundres of Post-IDs.

Examples you can find in Plugin: "Dynamic Visibility for Elementor"

**Comment by datatime-sk** [comment]
+ 1

**Comment by pgirzalsky** [comment]
+1 definitely needed!

**Comment by Asored-D** [comment]
+1

**Comment by mindingear** [comment]
+1

**Comment by Jtmichel** [comment]
Have you guys found a solution to this? I set up a custom query that calculates this based on the current post object but it would be nice as a built-in feature!

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.3
