### ISSUE TITLE
BUG/A few small bugs in the new Jet woobuilder plugin last update.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3523]
hello
In the new update of the jet woobuilder plugin, there are some bugs that I will explain. Please check.

1-In RTL, the coupon form in the editor is LTR. This bug has been created in a new update.
On the website : https://prnt.sc/15pu4la
When editing : https://prnt.sc/15pugvm
True on the website, but when editing LTR.

2- In the single attributes widget that was updated in this update, there is a dotted dot at the top of the table by default, which makes the design difficult : https://prnt.sc/15pvmb4

3- Again in the single attributes widget, there is a margin at the bottom of the table by default. https://prnt.sc/15pw8j9
If we put this code in the specified field, this space will be deleted. https://prnt.sc/15pvzoo
margin: 0px;

4- 6- Again in the single attributes widget, The features section is italic by default. In this image, the italic code that is available by default is specified. https://prnt.sc/15q4ffx
Please correct

Thank you for your efforts

**Comment by UraraReika** [comment]
1 - fixed;
2 -3 solved by styler controls. If you feel difficult please contact our support team.

**Comment by 79ho3ein** [comment]
> 2 -3 solved by styler controls. If you feel difficult please contact our support team.

Yes, I solved this problem with code.
But many users of this plugin who do not know how to code, objected to this issue, I wanted to tell you.
It would be great if you could solve these issues in public. Because not all users have coding knowledge.

Thank you for your answer🌹

**Comment by 79ho3ein** [comment]
Thank you🌹🌹🌹
