### ISSUE TITLE
Request for a widely used feature in the Jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3524]
hello
I apologize for making this request again. But I think one of the biggest drawbacks that jet woobuilder has over other competitors is that we can't show the up selling products to users on the home page.
Unfortunately, we can only show up selling products to users on a single product page. https://prnt.sc/16aq8tc
I have not seen any store site that shows its up selling products to users on a single product page. Rather, they expose the best-selling products on the home page of their users.
Dear developer, please put the query of up selling products in public in the product grid widget. In this case, we can show our up selling products to users on the home page. This feature is available in any store website.

Thank you for your efforts🌹

**Comment by UraraReika** [comment]
You should know that upsalles and cross sales product functionality connected to single product https://i.gyazo.com/7294b160b79fb6c5a8461c0edb8a1892.png. So please describe how you suppose to use this type of Query and  witch product upsales product should be display at home page?

**Comment by 79ho3ein** [comment]
@UraraReika 
I am sorry. I mistranslated my words.
I mean, please add the best sellers product query to the product grid widget.
If this feature is added, we can show the best-sellers products in each product category to users.
Like this picture, which shows the best-sellers products in the toy category : https://prnt.sc/16bi3l8
This feature is extremely useful and required.
Again, I apologize for my mistake🌹

**Comment by UraraReika** [comment]
Watch this https://github.com/Crocoblock/suggestions/issues/3058

**Comment by 79ho3ein** [comment]
I tried but failed.  Surprisingly, there is no such important feature in this great plugin.
In any case, thank you
