### ISSUE TITLE
JetWooBuilder - ajax add to cart inside single product

### ISSUE THREAD

**Issue by Steriotis** [Crocoblock/suggestions#353]
Please add the option to choose "Ajax add to cart" feature inside the single product builder -> "single add to cart".

**Comment by Floydtm** [comment]
@Steriotis, hi! We cannot implement this functionality as this is the territory of the woocommerce plugin

**Comment by Steriotis** [comment]
hi! There are some plugins that do this and they are not from WooCommerce such as [this](https://wordpress.org/plugins/woo-ajax-add-to-cart/).

**Comment by Floydtm** [comment]
this is great, you can use it on your site. Sorry, but now we can’t realize it.
