### ISSUE TITLE
Please, if possible, add this feature so that we can place the coupon widget in the desired location.(jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3530]
hello
As you know, the payment page of this plugin consists of two parts. One is the top section, and the other is the bottom section where the payment fields are located.
But there is a problem here. That we can not use the coupon widget at the bottom of the payment. And if we use it at the bottom of the payment page, it will bug.
For example, I wanted to put coupon widget at the top of the payment form. (Part marked in the picture) https://prnt.sc/16g3ylj
But this is not possible now. And if we put it there, it creates problems. (The problem is that the coupon can no longer be opened and closed and is always open).
Please remove this restriction if possible. In this case, we can display the coupon widget in any part of the payment page.

Thank you for your efforts

**Comment by UraraReika** [comment]
This happens because Coupon widget form is form, and checkout page body is although form. Form can't work proper inside another form. So if you want to put it in the bottom of the page you can create footer for specific  page and paste widget in this footer.

**Comment by 79ho3ein** [comment]
thanks for your response.
But for now we can not put the coupon widget in a footnote. And if we put it in a footnote, it becomes problematic. Apparently this part has a bug.
As I said above, if we put the coupon widget in a footnote, it will no longer be able to open and close and is always open. 
Please check these bugs if possible. If this is my only problem, I will contact the support team.
Thank you for your efforts🌹
