### ISSUE TITLE
Ability to edit mini Cart in Jet WooBuilder

### ISSUE THREAD

**Issue by fysioski** [CrocoBlock/suggestions#3531]
Please make the option to be able to edit the mini cart. Now only some basic styles are editable. It would be nice if it is possible to edit the delete product icon(x), title of product styles and price. Now those are only styleable by putting in custom CSS. But that is not why we have Jet WooBuilder.

**Comment by UraraReika** [comment]
Hello @fysioski !

We have WooCommerce mini cart widget in JetBlocks plugin https://crocoblock.com/widgets/shopping-cart/. Did you try to use it?

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
