### ISSUE TITLE
[JetBooking] - unique units system

### ISSUE THREAD

**Issue by sitechfromgeorgia** [CrocoBlock/suggestions#3532]
Hello in support page you ask me to write here.
in last week in my work someone ask me create site with booking form but not typical, because of fields and dates. have a look.

 i need create booking for work but i don't know hot to create hard system because of not typical booking system.

i have this type of rooms:
Standart
Superior
Bussines
Junior

but i have in different days different Quantity of rooms.
for example:
20.06.2021 i have:
Standart 4 room
Superior 2  room
Bussines 5  room
Junior 2  room

21.06.2021:
Standart 45
Superior 1
Bussines 23
Junior 24

and like this all time, if everyday i have just same rooms quantity i know about units but when i have in different date different quantity of rooms how to organize this booking system?

**Comment by UraraReika** [comment]
Hello @sitechfromgeorgia. Thanks for the feedback.

We've checked your request. Such a goal can be reached using a custom solution only witch we do not plan to introduce into our plugin. I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/  

Thank you for your understanding.
