### ISSUE TITLE
Fold/Unfold Gradient Bug JetTricks

### ISSUE THREAD

**Issue by sonnesworld** [CrocoBlock/suggestions#3537]
Please visit this page: https://work.richikuettel.ch/projekte/ or https://www.bachsermaert.ch/en/product/kinderkochbuch-misch-masch/. On both pages I use fold/unfold function. When users unfold the text the gradient is still visible, just after fold and unfold again it shows correct (without gradient when full text/content visible). The gradient should be hidden when unfold, right? Makes no sense when gradients are visible because the content is not fully visible.

**Comment by petranca** [comment]
+1

**Comment by Floydtm** [comment]
We will fix this in the next release. Thank you!
