### ISSUE TITLE
Recurring Events For Calendar

### ISSUE THREAD

**Issue by ghostdragon546** [CrocoBlock/suggestions#3540]
Can we please get recurring events set up on the calendar feature?
All of the event calendar plugins have an option for events to happy once every day, week, month, or year. That feature would be a huge help, because none of the other calendar options I've found work very well with elementor.

**Comment by NobleLarry** [comment]
+1 for this

**Comment by loiceoka** [comment]
I would love this too. The whole suite is complete but this part is a must for many projects!

**Comment by loucasl** [comment]
+1

**Comment by doodledude** [comment]
+1

**Comment by m-dejong** [comment]
This is needed very much.

**Comment by doodledude** [comment]
+1

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
