### ISSUE TITLE
JetForms PDF Generator

### ISSUE THREAD

**Issue by anderoav** [CrocoBlock/suggestions#3545]
It was quite a useful function with CF7, as they had so many third-party plugins built( especially PDF generators).
And I really miss that functionality, is there any possibility that you might add it in the near future?
As we are currently building a site for client and they need PDF automatically generated from the form.

https://github.com/Florent73/send-pdf-for-contact-form-7

**Comment by pixelika** [comment]
I would like that feature too.

**Comment by gguzzman** [comment]
Please!!!!!!!!!!!!!! I would like that feature too.

**Comment by fulanodigital** [comment]
I need this too!

**Comment by BatcomAus** [comment]
Lots of people want this feature yet you've closed this and linked it to another case that's the same, which is also closed and linked back to this case. There are even older cases requesting this feature which haven't been closed or commented on. If you're not going to add the feature then please say so because this has been requested for over 18 months. If it is being worked on then please let us know and point to the correct Suggestion so we can monitor it.

**Comment by nextab** [comment]
We could need this too for a project.

**Comment by accumanangel** [comment]
We sincerely request the ability to create a PDF file on form submit using the form **inputs**. This would allow users to generate customized PDF documents based on the data they enter in the form, such as invoices, receipts, contracts, etc.

Jetformbuilder already has some post submit actions that can be used to send emails, insert/update posts, or create user accounts.

I wonder if it would be possible to add a new **post submit action** that can create a **PDF** file from the form inputs and attach it to an email or save it to a folder.

**Comment by kwsim539** [comment]
+1 for this

**Comment by LordSnipeBG** [comment]
+1 for this! PDF generator is a need for nowadays. Almost every project is related to a certificate, customized card etc.

**Comment by Kraterspalter** [comment]
+1 for this -  very, very important!

**Comment by nishidshajib** [comment]
We urgently need a PDF generator for form submissions on JetformBuilder.

**Comment by Crocoblock** [comment]
Hello! I am glad to inform you that we have just released the PDF Attachment Addon. Feel free to [check it out](https://jetformbuilder.com/addons/pdf-attachment)
