### ISSUE TITLE
Support for Optgroup in JetFormBuilder

### ISSUE THREAD

**Issue by sanjeevz** [CrocoBlock/suggestions#3546]
It would be very useful to have support for the Optgroup tag/ label for the select dropdown menus. 

Or any other way to create groups within a select dropdown menu.

Example: https://www.w3schools.com/tags/att_optgroup_label.asp

**Comment by Crocoblock** [comment]
Hi, thank you for feedback
I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7491)
