### ISSUE TITLE
Offset dates on Availability Calendar to prevent bookings at too short notice (eg Offset 3 days)

### ISSUE THREAD

**Issue by GinaHTC** [CrocoBlock/suggestions#3547]
The Availability Calendar in JetBooking shows days available from today onwards. This is not always convenient/appropriate if there are processes, verifications, payments etc required before the booking is taken up. It would be great to have a feature where we can make the earliest date available for booking on the online form a number of days in the future. We can always offer a phone number/email to enquire about short notice availability.

**Comment by WebStudioNW** [comment]
Definitely a much needed option, also should be simple to implement too on the date selector

**Comment by UraraReika** [comment]
I merged this issue with [#717](https://github.com/Crocoblock/suggestions/issues/717), which is on the same subject so we could deal with it more efficiently.
