### ISSUE TITLE
Passing SmartFilter array to a new page

### ISSUE THREAD

**Issue by JamesDandy** [Crocoblock/suggestions#355]
When using SmartFilter on a page, I would like the ability to pass the array that is created to another page. This is so that I can display one page of many items with a limited amount of information and then present these selected items on a new page with more/additional information and in a different format. 

This image is a filtered set that I would like to pass to another page.
![image](https://user-images.githubusercontent.com/40547617/60901232-96e6f780-a23b-11e9-9fc4-77e95b9fd383.png)

This is the second page where I'd like _only_ the filtered items to appear in this new format.
![image](https://user-images.githubusercontent.com/40547617/60901335-c138b500-a23b-11e9-9618-457a0785b45e.png)

**Comment by JamesDandy** [comment]
Is there any more information I can provide to help define the problem?

**Comment by JamesDandy** [comment]
This is an important need for your filter. If you've created a filtered selection, why not allow that selection to be used on another page. It's great to filter the original page and display filtered data in the exact same format but being able to filter data displayed in one way to make it easy to show all the options, but then to allow the display of that filtered data in a more comprehensive way is critical. 

I think you can see that on the first image above I'm only displaying a small amount of data but in the filtered list I'd like to be able to display a lot more. Can you please consider how to improve your filter to allow the display page (or grid) to be different than the source page (or grid).

**Comment by Floydtm** [comment]
@JamesDandy, you can use filter [redirect](https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-set-up-a-redirect-path-to-filter-results-page/)
