### ISSUE TITLE
Is there any way to create a listing grid for woocommerce shop orders?

### ISSUE THREAD

**Issue by aliazarmi** [CrocoBlock/suggestions#3550]
Hi there
I Appreciate your team hard word and your amaziiiiiing products,
I want to ask is there any way to create a listing grid for Woocommerce shop orders?
if yes, How? because I cant see Order Shop post type in new listing items
if No, is it in your team plan to add this feature?
in my opinion it very very "Launcher work" !

Thanks in advanced

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
