### ISSUE TITLE
When the Jet engine plugin is activated, the crocoblock dashboard as well as the plugins open very slowly.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3551]
hello
When we activate the jet engine plugin, the speed of the crocoblock dashboard as well as the plugins section drops sharply.
It even takes up to 2 minutes to load. I followed up on this problem, and realized that this problem also exists in some users.
Please investigate the problem if possible.

thank you

**Comment by mehdimoradi1500** [comment]
Yes i faced this problem too, when i activate jet engine, these following parts run into problems: Plugins section, elementor loadigs and crocoblock dash run so slowly up to 1-2 minutes

**Comment by Floydtm** [comment]
We've checked your request and everything seems to be working well. If you still have a problem, we recommend that you go to our support team to solve it

**Comment by 79ho3ein** [comment]
Thank you
