### ISSUE TITLE
jet woo builder or jet engine: product add-on (Custom input fields) 

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#3552]
Hi 
I suggest to provide a Custom input fields in products single page
Custom input fields (also called product add-ons) like text fields, select fields, checkboxes, and so on that allow the user to enter additional, personalised information about a product, and these datas will be shown in the purchase basket and so on
Thank you so much

**Comment by Floydtm** [comment]
Right now you can add custom meta boxes for products using the jetengine plugin. Thank you!

**Comment by mehdimoradi1500** [comment]
Hi
Unfortunately, there is no option to achieve it. i want to add a field
(meta box) in front end of single product page
I attached the picture,
It will be so good if u add this option to jetwoo or jet engine
