### ISSUE TITLE
🐞 JetEngine - REST API Post Number Doesn't Work

### ISSUE THREAD

**Issue by perks98** [CrocoBlock/suggestions#3556]
**Describe the bug**
When creating a JSON feed from a feed provided from a product supplier it seems to work but using the Listing Grid widget the 'Posts number' doesn't work, e.g. when it is left to default or any number like 4 it still loads and displays all 80. This also doesn't work with the Pagination widget from JetSmartFilters. Please can you look into this as it is almost perfect for my customers.

**To Reproduce**
1. Enable Rest API Listings module.
2. Create Rest API Endpoint e.g. [Name: Trader Json Feed] [Endpoint URL: https://3rdParty.guntrader.uk/LivensGunshop/jsonGuns?filter=SG] [Items path: /Guns] ~ send request should work then save.
3. Create an Elementor Listing picking model and price fields only from the Rest API.
4. Create a page and edit with Elementor and add Listing Grid widget to page.
5. Pick the new listing instance you just created which has the model and price.
6. Try and limit by post number by 4.

**Expected behavior**
Should display 4 posts only then if desired display more on load, but instead displays all (more than 4).

**Comment by Floydtm** [comment]
You need to set up a rest api query https://prnt.sc/17ak1z0 Also check out this tutorial https://crocoblock.com/knowledge-base/articles/jetengine-how-to-display-custom-content-type-items-using-rest-api/ https://prnt.sc/17ak9f4

**Comment by perks98** [comment]
Hi @Floydtm,
Unfortunately that doesn't work, the JSON feed mentioned isn't created with your CCP, it is a supplier JSON feed. I guess your plugin can't work with it... I was hoping to create a feed without having to import data.

**Comment by Floydtm** [comment]
Now I understand you, unfortunately we cannot guarantee that this will work. Alternatively, you can contact our support team to send your request to the developers. However, I cannot guarantee that this will work. Thank you!

**Comment by perks98** [comment]
No problem, thanks for looking at the request anyways. Maybe as a feature request if your plugin could accept external feeds like REST API, JSON, XML, CSV from URL/HTTP request and FTP file access that would be superb for some of my advanced customer basis.

Thanks 👍.
