### ISSUE TITLE
Ability to introduce price start in jet samrt filetrs plugin ( Price range filter )

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3557]
hello
Currently, it is not possible to tell the user in the price range filter that the price is from X to Y dollars.
It would be great if you could add a feature so that we can put a prefix for the lowest price and highest price.
If you add this feature, we can introduce something like this in the price range filter to users : **From $ 200 to $ 3000**

Please check. Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by 79ho3ein** [comment]
thank you
