### ISSUE TITLE
Report an interference in the jet woobuilder plugin title widget.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3558]
hello @UraraReika 
This interference I'm talking about has occurred in the last 6 updates to the plugin. **The problem is that the product title widget is displayed in the editor, but is hidden on the site.**
I inquired about the reason for this problem and found that this problem also exists on two other sites. Please see the red box in the image below:
![Untitled](https://user-images.githubusercontent.com/77163248/123525772-72b2a880-d6e8-11eb-8598-4defaec8cbbf.png)
This code is taken from another part that is public. from here : https://prnt.sc/16yuc56
If we hide the tab title by elementor in the tab settings, the product title widget will also be hidden.
Please fix this interference if possible.

thank you

**Comment by UraraReika** [comment]
https://i.gyazo.com/67018de48d8a78991ff07158ff791378.png.
To prevent this behaviour you can rewrite single title widget template and remove entry-title class
