### ISSUE TITLE
Ability to "Show more" in the single attributes widget.(jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3559]
hello
Usually on store websites, the number of product attributes is high,and This increases the scrolling length on a single product page.
It would be great if you could add a "show more" feature to the single attributes widget.
If this feature is added, only x items of product attributes will be displayed to users. And if the user wants to see all the product attributes, she clicks on the display more option. This feature will be extremely useful
I will show you an example of this important feature, dear developer : https://prnt.sc/176752k
In this example, if the user clicks on the show more option, all product attributes are displayed.

If you decide to add this feature, please consider the following suggestions.
1- Ability to edit the Show more option text to the desired text.
2- Ability to load custom icons such as SVG https://prnt.sc/17682dr
3- Ability to close the show more option again. In this case, the text and the icon change (up arrow) https://prnt.sc/1768lf7
4- Ability to specify the number of product attributes previews. For example, display 3 feature items and display the rest after clicking show more. It would be great if the number 3 could be changed by us.

Please review this request. Thank you🌹

**Comment by 79ho3ein** [comment]
Thank you🙏🏻🌹
The product features section (except for the title) has italic code by default. https://prnt.sc/15q4ffx
Please fix this problem if possible.
Thanks

**Comment by UraraReika** [comment]
You can combine this widget with JetTabs or just use Single Tab Widget where attributes can be hide. The italic default styles can be changed with style controls.
