### ISSUE TITLE
Collapse Meta Fields when editing Post Types

### ISSUE THREAD

**Issue by JamesDandy** [Crocoblock/suggestions#356]
I have a couple dozen fields in my Post Types and I'm constantly having to edit and add fields due to developing new services and with so many fields it's hard to create a new field and drag it into place without first having to collapse each and every field in advance first. 

The design of the Post Types editing page is also hampered in this case by the fact that the button to collapse and expand each field is so small that the Move Field cross-headed arrow constantly pops up if you're not directly over the small arrow needed to collapse or expand that field.

It would assist me greatly, and likely many others, if either the default was that all fields are collapsed or that there was an option to collapse or expand all fields.

**Comment by JamesDandy** [comment]
Glad to see this marked as done however after updating the plugin I still don't see an option to collapse all meta fields. Am I just not looking in the right place?

**Comment by Floydtm** [comment]
@JamesDandy, Hi! This will be available in update 2.0.0

**Comment by JamesDandy** [comment]
Ok, great...Thank you!

**Comment by JamesDandy** [comment]
Thank you, the implementation of collapse along with keeping the update post button on screen are both great changes.
