### ISSUE TITLE
Create new widget or option for slider (support dynamic template for slides)

### ISSUE THREAD

**Issue by promocot** [CrocoBlock/suggestions#3561]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

Hello, what I mean? For example, I need to create on website block with before and after, if I add many widgets before and after, I will make the site inconvenient to use and too large, however, if I create several templates for output and then load them into the slider, it will simplify the site and allow you to show more results before and after. You can also find endless use for such a widget (you are limited only by your imagination) at the moment I have to resort to сss to make custom sliders, and this takes time + harms optimizations since I need to create a new section for this and this is an extra 26 lines of code. 

P.S. the fact is that I use flex properties for the site and in my work, I manage one section and a dozen columns with different fill sizes, and this gives me perfect optimization against the background of your innovations

**Comment by Floydtm** [comment]
You can use it right now https://prnt.sc/17fo1jh
