### ISSUE TITLE
 JetWooBuilder - Add to cart floating sticky

### ISSUE THREAD

**Issue by mrhossein** [CrocoBlock/suggestions#3564]
Hello.
A great feature for creating product pages is the Add to Cart button that sticks to the bottom or top edge of the product page all the time while scrolling the page, and whenever the user is satisfied with the description, he can click on the Add to Cart button.

**Comment by tizum** [comment]
Very good this suggestion, it will be a great resource.

**Comment by UraraReika** [comment]
You can already achieve this by using add to cart widget is separate section in combination with motion effects by Elementor.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
