### ISSUE TITLE
Adding pictures of the Author in Jetblog listing

### ISSUE THREAD

**Issue by 4elementsme** [CrocoBlock/suggestions#3566]
Hi there,

In the regular blog listing of elementor, we can add the picture of the author of any post in the blog listing.

Right now in Jetblog, we can only see the name and a generic user icon.

I'd really like the option to add the picture of the author for blogs with lots of collaborators.

example: https://snipboard.io/tUFgQ9.jpg

Thank you

**Comment by Crocoblock** [comment]
was added in JetBlog 2.3.8 https://i.imgur.com/WerOL6F.png
