### ISSUE TITLE
Add content source for countdown timer

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#357]
Can the JetElements Countdown Timer work in conjunction with a custom field (date).

Example use case: If I create a custom post type for events, it would be great that if a countdown timer widget is in place that it can pull the timer data from a custom field so not having to manually set it?

**Comment by kaskad88** [comment]
Added for next version(2.1.0). Thanks for your report!

**Comment by iamdanbarrett** [comment]
Oh wow my contribution was considered and ready for release! 👍
