### ISSUE TITLE
Ability to "Show more" in the single content & Single Excerpt widget.(jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3576]
hello
I once had this request in # 3559 for another widget. But I forgot to request this for the single content & Single Excerpt
 widget there as well.

Similar example:
before clicking : https://prnt.sc/17jcoid
After clicking : https://prnt.sc/17jcvum
Single Excerpt : https://prnt.sc/17mw4a0
In the images above, users are set to see only 7 lines of content as a preview. If they want to read more, click on the show more option to see more. Also, after a complete study, they can close it again.
If possible, please add the show more feature to the single content widget. This feature will be very useful on the product page.

thank you

**Comment by UraraReika** [comment]
Use this widget https://crocoblock.com/widgets/unfold/ in combination with dynamic tags functionality.

**Comment by 79ho3ein** [comment]
thank you dear @UraraReika 
excuse me... I have already made two suggestions for improving the jet woobuilder plugin, these requests are still open.
#3077 & #3078
May you review it again? Will you add them to jet woobuilder in the future?

thank you 🌹
