### ISSUE TITLE
Request to increase the performance of single meta widget.(jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3577]
hello
The single meta widget is one of the most important widgets on the product page.I have two suggestions for improving this widget. Please add it to the plugin if you wish.

1- Ability to edit meta title text : This feature is very important. The feature is now available in the Meta WooCommerce widget. Great if you add it to the plugin : https://prnt.sc/17jfxnj

2- It will be great if you add a feature so that we can put the desired icon for this widget. in this part : https://prnt.sc/17jguqk

please check. thank you

**Comment by UraraReika** [comment]
1 - It can be style separately
2 We will not add this feature.

In nearest update with the help of JetEngine and dynamic tags functionality you will be to achieve needed results.

**Comment by 79ho3ein** [comment]
thank you
