### ISSUE TITLE
Support for Brizy Page Builder - Trying to use JetAppointment Form through the provided shortcode

### ISSUE THREAD

**Issue by DrPine** [CrocoBlock/suggestions#3579]
I really want to be using Brizy as my page editor.  I do like it a bit more than Elementor, I know Elementor can do more I just don't need everything Elementor has to offer and I already have a lifetime license for Brizy.

The main functionality that I'm currently missing is with JetForms.  I used the JetAppointment plugin and it created a template form for me.  I went to use the shortcode within Brizy and the next button is not working.  Works fine if I create a blank Elementor page but I do not want to use Elementor if possible.

Not sure if this is something Brizy is going to need to add to their product so full functionality can be achieved with these amazing forms or if it's something that can be fixed on Crocoblock's end.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
