### ISSUE TITLE
Jetengine - Dynamic Color on Checkbox Smart Filter

### ISSUE THREAD

**Issue by pixallusdev** [CrocoBlock/suggestions#3581]
I’ve created taxonomy, added color picker meta field to it, assigned some colors to categories, created checkbox filter, and tried to assign dynamic color to the filter but it seems it doesn’t work. 

I was able to set dynamic color on the listing item titles and custom fields. But it’s not working on smart filter. 
Here’s a short video
https://www.berrycast.com/conversations/25837b58-0878-5bfa-a02b-8685aafdf6ae 

I've currently implemented colors on checkbox filter with jquery and css.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
