### ISSUE TITLE
JetBlocks: Add custom url option to Cart widget

### ISSUE THREAD

**Issue by IgorDark** [CrocoBlock/suggestions#3585]
Currently there are only 2 options.

- show slide in offcanvas cart
- dropdown list

Can you add simple option to insert any custom url. When user clicks on cart icon he will be redirected to specific page you've inserted.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
