### ISSUE TITLE
Sort option in JetSmartFilters

### ISSUE THREAD

**Issue by Medeon-68** [CrocoBlock/suggestions#3588]
It is definitely necessary to add a sorting option in the appropriate JetSmartFilters filters, by name, number, ascending and descending ... I don't think it would be a problem to add it to one of the new versions of the plugin.

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-sort-posts-and-products-with-sorting-filter-widget/

**Comment by Medeon-68** [comment]
You just didn't read my text carefully ... The link you sent has absolutely nothing to do with the question asked.
