### ISSUE TITLE
JerSmartFilters - Sorting filter - Sort list

### ISSUE THREAD

**Issue by Medeon-68** [CrocoBlock/suggestions#3589]
By default, the Sorting Filter sorts the Listing grid by name. It would be a good idea to allow one of the options we add to the Sorting list to be selected for the default sort. Just a simple check box, quite enough.

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-sort-posts-and-products-with-sorting-filter-widget/

**Comment by Medeon-68** [comment]
You just didn't read my text carefully ... The link you sent has absolutely nothing to do with the question asked. I just suggested that the assigned sort can be determined by one which would be the default. This way the first sort is always based on the name.
