### ISSUE TITLE
More Shop, Product and Product Archive Templates

### ISSUE THREAD

**Issue by NEILBATCHELOR** [Crocoblock/suggestions#359]
I would like to see a greater range of product designs and templates incorporating jets woo product gallery plugin.

You have a good range of designs and sections for use on third party themes but you are lacking when it goes to:

Single Product page designs
Product Archives
Shop pages - front shop pages and catalog

specially we need ones that incorporate cool designs, smart filters and smart product search.

**Comment by Floydtm** [comment]
Now we have an emphasis on plug-in development. Maybe soon we will add more design templates
