### ISSUE TITLE
JetSmartFilters - Pagination widget 

### ISSUE THREAD

**Issue by AlfaBlue** [Crocoblock/suggestions#360]
Hello,

I think it would be a good idea to provide a feature/function in the  **JetSmartFilters - Pagination widget** to enable the number of pages shown on the frontend. 

**Example**
A website uses JetEngine to make a listing and shows that listing with the listing grid. A total of 10 items are shown per page. The listing is sorted by date, the latest date is shown first. 100 items would make 10 pages in the frontend of the site. The pagination widget shows 10 pages on the frontend.

**Problem**  
A client wants to show a maximum of 3 pages only with the latest entries.

**Question**
Would it be possible to add a function to the JetSmartFilters - Pagination widget to set a maximum of pages?

**Comment by Floydtm** [comment]
@AlfaBlue, hi! 
Please check these [options](http://prntscr.com/og5gb4). They will help you adjust the number of pages on the front end.
