### ISSUE TITLE
JetWooBuilder: Stock Status for  Single Product

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#3602]
В блоке с кнопкой корзины надо сделать возможность отключения элемента Stock Status. В этом блоке/виджете идут вместе очень много элементов. Было бы неплохо их разделить на отдельные виджеты для более гибкой настройки макета карточки товара.

В стандартном шаблоне WC элемент Stock Status выводится немного странным образом. Через хук его не отключишь - можно только закомментировать, хотя, может я чего-то не знаю. Это просто для информации вам пишу.
http://prntscr.com/18pi0hw
http://prntscr.com/18pi3bl

**Comment by UraraReika** [comment]
This template has description 'This template can be overridden by copying it to yourtheme/woocommerce/single-product/add-to-cart/simple.php'. So just do it and comment or remove unnecessary code.
