### ISSUE TITLE
Verifying code for phone number/ email login and registration 

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#3603]
Hi crocoblock team, 

I want to design a login/register form for my website and use OTP verifying code by entering phone number or email. 
But unfortunately i did not see such a functionality in jet form builder or other Jet Plugins 
It will be so great to add this  option yo jet form builder? Yes?

**Comment by Floydtm** [comment]
We're not going to add this right now, but you can find a solution [here](https://wordpress.org/plugins/search/otp/).
