### ISSUE TITLE
Jetformbuilder and paypal

### ISSUE THREAD

**Issue by ombres-et-lumieres** [CrocoBlock/suggestions#3605]
Yesterday, i saw a YouTube demo by wptuts about the new possibility: the connection with paypal.
To do that, he uses as example a membership payment. But, the new option allows just single payments and not recurring payments, as it should be on a membership site.

The actual option is useful if I have a few things to sell, but most of the time people will use woocommerce, as it is free.

I think adding the recurring payment with paypal would be a real help for many people.

**Comment by razkoko1** [comment]
Hey!
Same need here... Its awesome option, but when combined with the option to make recurring payments its open new world of opportunities!!

**Comment by GCG82** [comment]
+1 for PayPal and Stripe addon

**Comment by girafffee** [comment]
An addon has been released
https://jetformbuilder.com/addons/paypal-recurring-payments/
