### ISSUE TITLE
New product grid preset (Jet Woo Builder)

### ISSUE THREAD

**Issue by osamaaminaziz** [CrocoBlock/suggestions#3606]
hello,

I need to request new product grid preset that use the wishlist & compare with the product content
https://share.getcloudapp.com/7KuoWYbZ
& adding the order feature to it so I can order it like the title and button.. etc
https://share.getcloudapp.com/eDuyENjQ
this will help us making other designs like this
https://share.getcloudapp.com/nOuPLqoq

Thanks

**Comment by UraraReika** [comment]
Hello @devosamaamin !

You can create your own preset by rewriting one of existing. If you have difficulties with this please contact our support team.

**Comment by osamaaminaziz** [comment]
Hello @UraraReika, thanks for your reply.
is there any documentation for this?

**Comment by UraraReika** [comment]
Template can be overridden by copying it to yourtheme/jet-woo-builder/jet-woo-products/global/presets/archive-product.php. There isn't documentation on our knowledge base it's just wp basics. More info gives our support
