### ISSUE TITLE
Jet woobuilder compatibility with elementor tab widget.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3608]
hello
Great if you make the Jet woobuilder plugin compatible with the elementor tab widget. If you add this feature, we can design a much more attractive single page with jet woobuilder. In this case, we can display single page content, such as comments, features and product descriptions in the tabs(Then we can have a much better personalization.), and this would be great. Like this picture : https://prnt.sc/18uaq7g
We can not even use product content, features and comments in the jet tabs plugin.
The jet woobuilder now has a tabs widget (https://prnt.sc/18ubhz0). But it does not have proper personalization and we can not edit its content.
If you decide to add this feature, you only need a few widgets to make them compatible : https://prnt.sc/18ucrsm

Please review this offer. Extraordinary required. **If you need more explanations and ideas, I am at your service.**

thank you🌹

**Comment by UraraReika** [comment]
We have JetTabs widget than can contains templates. And you can use it with JetWooBuilder if you have some problems please contact our support team.

**Comment by 79ho3ein** [comment]
thanks
