### ISSUE TITLE
Jet Engine Form - ability to get the IP address

### ISSUE THREAD

**Issue by its4youb** [CrocoBlock/suggestions#3609]
Hello Crocoblock team.
My suggestion is to create a new field option in the forms to get the IP address from those who are filling out the form, or even create a new field in the forms to be possible a HTML command.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
