### ISSUE TITLE
Add feature to add dynamic icon or svg file in all dynamic fields

### ISSUE THREAD

**Issue by Kimantu** [CrocoBlock/suggestions#3610]
Add a feature to add a dynamic icon or SVG file in all dynamic fields.

![Untitled](https://user-images.githubusercontent.com/22232346/124556153-92b73a00-de55-11eb-9710-0617a54f9649.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
