### ISSUE TITLE
Ability to preload all WooCommerce images in the jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3611]
Please add a feature to jet woobuilder so we can preload all WooCommerce images. This great feature has a positive effect on the performance of the website. I tested it using a plugin and it worked extremely well.
This will be a very important feature for sites where all WooCommerce pages are built with Jet woobuilder.
If this feature is added to the woobuilder jet, it would be great. If it needs more explanation, I am at your service.

thank you

**Comment by UraraReika** [comment]
Just use plugin that you tested.
