### ISSUE TITLE
Jet Engine (listing) - Jet Booking seasonal prices + half days

### ISSUE THREAD

**Issue by NicolNekesa** [CrocoBlock/suggestions#3612]
It would be more than great to have the option of seasonal prices at Jet Booking/ Jet Engine (listing). A basic and key feature for accommodation or car rentals + the possibility of booking not a whole day but a half-day (for example booking from Friday noon a Wednesday noon).

Thank you.

**Comment by WebStudioNW** [comment]
This is a basic feature that is required for any booking system, some dates are more expensive that others, in the UK we have Bank Holidays and weekends which are always more expensive than regular mid week bookings

**Comment by NicolNekesa** [comment]
> This is a basic feature that is required for any booking system, some dates are more expensive that others, in the UK we have Bank Holidays and weekends which are always more expensive than regular mid week bookings

You are right. I just received an email, that this feature is not possible with Jet Engine/Booking so I made this post. Hopefully, they will work on it. Because otherwise, it is one of the best features (Jet plugins) for Elementor.

**Comment by benjamieson** [comment]
This is the same as #3656 

Gets a +5 from me - it's essential.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.4.0 version. You can fell free to check it out. 

Thank you!
