### ISSUE TITLE
Meta Boxes missing from Meta Box List

### ISSUE THREAD

**Issue by wbrobston** [CrocoBlock/suggestions#3613]
**Describe the bug**
I have 5 meta boxes configured and have been tinkering with them over the last few months. In the past week they are not longer listed in the Meta Box List for editing. I am running WP 5.7.2 and JetEngine 2.8.5.

How can I get them listed back here for editing?

**Screenshots**
<img width="1280" alt="Screen Shot 2021-07-06 at 8 55 03 AM" src="https://user-images.githubusercontent.com/76851026/124604008-7f49a600-de38-11eb-8f72-4ab850ae003f.png">

**Comment by Floydtm** [comment]
We have checked everything and do not experience such a problem on our side. Please contact our support team. Thank you!
