### ISSUE TITLE
Issuance of purchase invoice, in Jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3614]
hello
Invoice issuance is one of the most important services of a website. If it is added to the jet woobuilder, it will be extremely great and practical.
There are several plugins for Issuance of purchase invoice. But due to the increasing development of elementor and jet woobuilder, many sites use elementor. If jet woobuilder adds this feature, it will easily beat all competitors.
Example of WooCommerce Purchase Invoice : https://prnt.sc/1942z8j
This feature can be added to the Thanks you page.
After completing the order, a button will be displayed when the user enters the thank you tab. If he clicks on it, he can see his purchase invoice. (As a suggestion)
I have many ideas to complete this feature, and if approved, I will write them in this issue. **Please share your opinion**

thank you

**Comment by UraraReika** [comment]
This feature has nothing to do with page building so in this case we will not implement it. There are a lot of plugins in org so you can use one of them and then display it in the template. Although you can watch this issue https://github.com/Crocoblock/suggestions/issues/476

**Comment by 79ho3ein** [comment]
thank you @UraraReika 
Yes, #476 is exactly that. Will it be #476 added to jet woobuilder?
