### ISSUE TITLE
Time Slots for JetBooking and Jet Appointment

### ISSUE THREAD

**Issue by stavroscha** [CrocoBlock/suggestions#3616]
Have the ability to choose either choose the starting time of the booking and the duration of the booking or have a starting and ending time of each booking.

As a scenario to explain this better, for example when there is a service that runs every day in three slots (10:00-13:00, 14:00-17:00 and 17:00-20:00). Customers can choose the specific timeslot they want to book and when the maximum amount of people book for each timeslot, then that specific time slot should become unavailable.

To be fair this is one of the most common scenarios so not sure why is not implemented yet. If it is not possible and you will never bother doing anything about it at least let us know so i can just look anywhere else.

I have added already another request and it has been deleted so i am hoping that this will not.

**Comment by Floydtm** [comment]
Anything you ask for can be implemented right now. Explore the documentation or contact our support team https://prnt.sc/1astpzh Thank you!
