### ISSUE TITLE
Number of Adults/Children Option for JetBooking/JetAppointment

### ISSUE THREAD

**Issue by stavroscha** [CrocoBlock/suggestions#3617]
Have the option to allow users to be able to have the option to have a number of adults and a number of children who are going to be attending the booking/appointment.

An example scenario, when you are going to attend an event and you want to provide tickets and have different prices for adults and different prices for children. Also, that will require for you to be able to choose the number of adults and the number of children and based on your choice the price will be calculated.

That is also another really important functionality that needs to be added and that many people are asking for.

**Comment by Floydtm** [comment]
https://prnt.sc/1at1q67 https://prnt.sc/1at1uuw You can set it up right now, you just need a little trick. If you have any problems with this, please contact our support team. Thank you!

**Comment by stavroscha** [comment]
I have posted a ticket for the specific functionality but i got a reply that it cannot be achieved at the specific time. I believe there is a big misunderstanding between the queries sent to the support and the actual replies that are sent over since i have mentioned this specific functionality several times and the answer i got back was that is not possible at the moment....and I will try and implement it without having any instructions on how to achieve it.

**Comment by stavroscha** [comment]
@Floydtm if you have a solution for it you can mention it here because the support mentions that this is not possible. I have created more than one ticket for the same reason and spend way too many days on this. I had enough. If you are willing to mention the solution that will be great, but your answer above does not really help. Here is the answer from the staff member about the specific functionality in case you do not believe it.

![image](https://user-images.githubusercontent.com/11261921/127163367-eac16305-89f0-45b9-8bd7-9f81eda0af9b.png)
