### ISSUE TITLE
Product label compatibilities from other plugins

### ISSUE THREAD

**Issue by Matan3838** [CrocoBlock/suggestions#3619]
Hey,
Product Item archive with Woobuilder can't add Label with Product Label Plugins, it's doesn't show up on the product, 
 This product item doesn't compatibilities with any plugins, that give the ability to add Label/Sticker to the product

The only badge that can possible to add is the Sale Badge.

Example plugin that I am using is: advanced-woo-labels

**Comment by UraraReika** [comment]
Please follow guidelines for opening a new [feature request,](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.

**Comment by Matan3838** [comment]
Hey,
 
Screenshot with example is attached:

The product looks like when using on the regular **products** widget, same for the appearance in the categories,
![With](https://user-images.githubusercontent.com/87079922/124939414-c048e280-e011-11eb-8cc4-338e656d2631.JPG)

Here you can see the plugins works when we are using in the **product grid** widget
![Without](https://user-images.githubusercontent.com/87079922/124939572-e4a4bf00-e011-11eb-89df-a671d3d1c2f1.JPG)

You can see when I disable the template to the archive page item:
![Disabled](https://user-images.githubusercontent.com/87079922/124939901-2d5c7800-e012-11eb-8e50-e666aa25fb79.JPG)

The widget itself works:
![Works](https://user-images.githubusercontent.com/87079922/124939955-38afa380-e012-11eb-85ce-5e7c84be0ad3.JPG)

**Comment by 79ho3ein** [comment]
@Matan3838 
If I am not mistaken, this offer has already been made. # 2680

**Comment by UraraReika** [comment]
@Matan3838, in our widgets we use custom function to handle products images so there can be some issues with thirs party plugins. Plugin that you use can have shortcode or function to display badge. So in first case (shortcode) you can with the help of Shortcode widget output it in the product item card. Second case - hook the filter.

**Comment by 79ho3ein** [comment]
@UraraReika 
Will the possibility of inserting a custom label for the product grid widget be added in the future?

**Comment by UraraReika** [comment]
Follow this issue https://github.com/Crocoblock/suggestions/issues/2680.

**Comment by Matan3838** [comment]
I tried to hook this, but still because it's not with the same structure i can't to hook this.
