### ISSUE TITLE
Testimonials Widget Features

### ISSUE THREAD

**Issue by Carroyo26** [Crocoblock/suggestions#362]
Hi,

The Testimonial Widget should have the possibility to link the image with a webpage. For example i have a review for one of my clients, and i want all the people that visit my webpage to be able to click on the image and go to the webpage from my client in order the be sure that this is a testimonial form a real company, and not some invented name.

**Comment by kaskad88** [comment]
Added for next version ( 2.0.1 )

**Comment by kaskad88** [comment]
Thanks for your report!
