### ISSUE TITLE
Woo pagination for complex listing layouts with multiple widgets

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#3621]
Hi, since your plugins do almost everything, I have a new suggestion concerning the woo templates and the pagination. 
Pagination at the moment, works only with one listing widget. So, we are stuck with one design layout for shop or product archives. If we create different listings with different design and use the offset to create a more complex layout with multiple widgets on the same page, it would be great if when moving to page 2 with pagination widget, the complex layout will stay the same and products will roll to the next set while keeoing the exisitng offsets on every widget. In the attachement I have created some complex layouts with multiple widgets to make my suggestion more clear.
![productsLayout](https://user-images.githubusercontent.com/36569170/124915113-d8ad0300-dff9-11eb-9a0c-84f8e4b41bbe.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
