### ISSUE TITLE
Report a bug in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3622]
hello
If we put the product grid widget in the section and give the background color to the column, a bug will be created if we activate the carousel for the product grid widget. The problem is that the product grid widget moves slightly to the left, causing the horizontal scrolling to.
Please pay attention to these pictures : https://prnt.sc/19hmtal
In the image above, everything is working properly (please see the section mentioned in the image above, to see the problem in the next image) 

Now I have activated Carousel. Please see this picture : https://prnt.sc/19hnr5j
Did you notice the widget move to the left? If you look left and right marked with an arrow, the movement is quite clear.
In addition, a preview bar appears at the bottom confirming this move (green arrow)
**If I want to briefly explain this bug, it is that if we enable the product carousel, the product grid widget creates a responsive problem.**
In this video, the problem is easily visible : https://drive.google.com/file/d/1MBy6z3TuIlMYM7BAq8wZXUR1BXf1CrjF/view?usp=sharing

thank you

**Comment by 79ho3ein** [comment]
thank you @UraraReika ,I hope I have conveyed the problem well.

**Comment by UraraReika** [comment]
The problem can be caused with settings in the widget. Please try to recreate this problem from scratch.

**Comment by 79ho3ein** [comment]
No special settings have been created. 
Number of products to display : 4
The slider can be scrolled.
Total number of products to display: 10

I tested everything. This problem occurs when the carousel is active.
Resolving this bug means that most designers do not need to use the interior. And this helps to optimize the website. thank you

**Comment by 79ho3ein** [comment]
may you tell me when the next update will be released? If I have time, I will investigate the problem further.

**Comment by 79ho3ein** [comment]
hi @UraraReika 
I tested the problem by all means. Just like video, it creates a problem.

**Comment by UraraReika** [comment]
Hello @79ho3ein ! 

We deeply tested this issue and came to the next conclusion. This is not a problem of our widget but its here. This behaviour is caused by Swiper slider library and the way how sliders works and render themselves. We although recreate this issue with other not only our widgets. You can avoid this by using paddings on columns or margins directly on widget.

**Comment by 79ho3ein** [comment]
Thank you very much @UraraReika
