### ISSUE TITLE
In the new update of Jet woobuilder plugin, it is not possible to edit a single product page.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3628]
hello @UraraReika 
In the new update, when we try to edit single product page, the following error is displayed :

![images](https://user-images.githubusercontent.com/77163248/125065692-60147800-e0c7-11eb-86f4-af2e496c56c7.jpg)

This problem only occurs when editing a single product page. There is no problem for the payment page, shopping cart, etc. Single product page only.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

We test different scenario of this case but everything seems to work. Please contact our support team so we can check your sire.

**Comment by 79ho3ein** [comment]
thank you @UraraReika 
But it's really weird. This problem only exists on a single product page and cannot be edited.
In any case, thank you. I hope it is solved.

**Comment by 79ho3ein** [comment]
But there is definitely a problem. Because when I go back to the previous version, the problem is solved.

**Comment by UraraReika** [comment]
Ones again we check and all works proper. Contact our support team or use this [template](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to give us more information

**Comment by 79ho3ein** [comment]
thank you

**Comment by 79ho3ein** [comment]
Hi again @UraraReika 
I realized exactly where the problem was. Of course, I also called support, but due to the end of working hours, the conversation remained unfinished. So I decided to explain the problem in more detail here.

The problem is: when using the product grid widget on a single product page, everything is fine...
**But when we set the product grid widget query to "related" or "cross sell", we will receive an error of 500 when saving.**

You can see how this problem occurs in this video : https://drive.google.com/file/d/1Ec84Hu1bgzPlz6694nm4-4vLwzt1AL8B/view?usp=sharing

thank you again

**Comment by 79ho3ein** [comment]
It should be noted that I am using the latest hello theme update.
