### ISSUE TITLE
Webhooks for JetFormBuilder

### ISSUE THREAD

**Issue by amororov** [CrocoBlock/suggestions#3629]
Please add the ability to send form data via webhooks.
I am currently using this plugin — https://wordpress.org/plugins/forms-to-zapier/
It allows you to send form data (in my case, CF7) to one of the automation services and then link it to any CRM, google spreadsheets and anything else. 
Unfortunately, without this I will not be able to use this plugin 90% of the time. Because it cannot be linked to any of my clients' CRMs.

**Comment by ofmarconi** [comment]
+1

**Comment by Floydtm** [comment]
@amororov, hi! Please check Post Submit Actions in form https://prnt.sc/1xax4fc https://prnt.sc/1xax5kz

**Comment by amororov** [comment]
Thanks guys.
