### ISSUE TITLE
Make Column Clickable Elementor

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#363]
Hello, I ask you to introduce the possibility to put a link to a column in Jet Elements plugin.
There is a free plug-in for this - Make Column Clickable Elementor, but I would like this functionality to be in the Crockoblock set. Thank.

/*Оригинал*/
Здравствуйте, прошу внедрить в плагин Jet Elements возможность ставить ссылку на колонку.
Есть бесплатный плагин для этого - Make Column Clickable Elementor, но хотелось что бы этот функционал был в наборе Crockoblock. Спасибо.

**Comment by stasonua0** [comment]
Можно закрывать, этот функционал уже есть в Jet Engine и этого достаточно

**Comment by philmatt** [comment]
+1 for advanced link settings

**Comment by petranca** [comment]
+1
Yes please, add this feature for columns and sections

**Comment by stasonua0** [comment]
+1

**Comment by raroDev** [comment]
+1

**Comment by heavestudio** [comment]
+1000

**Comment by joseehilton147** [comment]
why close this??? elementor dont want to add this to core and i need to use another plugin to get this... why not integrate with jet engine and make the plugin better and more complete
