### ISSUE TITLE
Dynamically Hide Empty Filters & Labels - JetSmart Filters

### ISSUE THREAD

**Issue by hitsgee** [CrocoBlock/suggestions#3630]
Not sure if this is a bug or a feature request either way it would be great to see.

Currently, if you have a Jet Smart filter with a label but no options match that filter just the label is shown. Could we not have the option that if the filter is empty (no options/values) this completely hides the filter rather than just showing a random label.

This would be great for Ecommerce where a category does not have products with filters that apply to it.

**Comment by 79ho3ein** [comment]
You mentioned a very good case. Yes, this is definitely a bug in the jet smart filters plugin.
I have already submitted a request in this regard (#3366). I hope this problem will be resolved

**Comment by AndyMorley** [comment]
I have just asked on live chat for this exact thing, he pointed me towards their "indexer" feature, the Indexer featuer isnt right for this, it doesn't hide the filter entirely including the filter label.

I've been trying to find ways to do this but no luck.

It seems like such an obvious thing to include i'm surprised their dev team didn't implement it already.

**Comment by welcodario** [comment]
Hello! Has anyone solved this issue?

It's two entire days I am working without success...quite e long time for such a small issue...

Dario

**Comment by taidang26** [comment]
Hello I am also stuck here, sadly someone has reported since 2021 and there is no update.

Does anyone have a solution to this problem that can ping me?

**Comment by akW-matt** [comment]
Exactly the same functionality needed. Do we have a solution for that?

**Comment by welcodario** [comment]
@taidang26 and @akW-matt,

some days ago I managed to find a temporary solution, it's quite poor but it's the only one that's working.

I added a custom function in the functions.php wordpress file, the key was to put a small timeout so the page is FULLY loaded. It doesn't sound good but at this time it is working very well and it solved the problem for me. hHope this helps:


function ti_custom_javascript() {
    ?>
        <script>
document.addEventListener('DOMContentLoaded', function()
{
    setTimeout(function() {
    const elementi = document.querySelectorAll('.elementor-widget-jet-smart-filters-checkboxes');
    elementi.forEach((elemento) =>
    { 
        secondoDiv = elemento.children[0].children[0];
    disp = secondoDiv.style.display;
    if (disp == 'none')
    elemento.style.display = 'none';
      });
    }, 300); 
});
        </script>
    <?php
}
add_action('wp_head', 'ti_custom_javascript');

**Comment by akW-matt** [comment]
@welcodario does this code still work for you? I tried it, but it doesn't hide the labels.

**Comment by welcodario** [comment]
Yes it works!

You can inspect the HTML source ti check for the dom elements.

Dario

Il Ven 7 Giu 2024, 15:01 akW-matt ***@***.***> ha scritto:

**Comment by midsun93** [comment]
Hello, I made simple css fix:

.elementor-widget-jet-smart-filters-checkboxes:not(:has(.jet-checkboxes-list)) {
  display: none;
}

**Comment by martiniboy** [comment]
Thanks @midsun93 I had to tweak it to

```
.jet-smart-filters-checkboxes:not(:has(.jet-checkboxes-list)) {
display: none;
}
```
