### ISSUE TITLE
Color swatches and images based selection for colors (jet woobuilder) 

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#3632]
Hi crocoblock team
Is there any plan to add a great option to jet woo builder in which, we can add a "colors pallet" to the single product page? 
And even add a brilliant feature; to use product's images as the colors of the product, So customers can choose the images as the colors 

First option:
![IMG_20210711_022349_522](https://user-images.githubusercontent.com/86493591/125177225-3bb3bb00-e1ef-11eb-9b96-bad670cfd79e.jpg)

Second option:
![Screenshot_20210711-013345_Chrome](https://user-images.githubusercontent.com/86493591/125176395-4b7bd100-e1e8-11eb-87eb-e4f1b865bc3f.jpg)

I suggest to add these two wonderful features, in one widget in jet woo builder! 

It will be so great and we love u more than ever ✌️😊 you make life easier too 🙏
Thank you

**Comment by UraraReika** [comment]
I merged this issue with #361, which is on the same subject so we could deal with it more efficiently.
