### ISSUE TITLE
Request to add "Incomplete mode" feature to the jet woobuilder plugin carousel widget.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3633]
hello
I have made this proposal before. But because the request was not made clear, it was rejected. I hope I can make my request clear to you. And also hope you add this feature.😃

**Request Description :** 
It would be great if you could add a feature so that we can display product sliders in a more up-to-date way. (In addition to free mode and normal mode)
This feature, which I will describe, is called **Incomplete mode**. This feature is used on many sites. Let's see a picture of this feature for now to explain it further : 
![Screenshot_20210711-031957_Chrome](https://user-images.githubusercontent.com/77163248/125178202-cb5d6780-e1f7-11eb-8a20-1a602f452e92.jpg)

**Please do not confuse this feature with the center mode that is currently in the plugin.**
As you can see in the image above, there are two complete product boxes, and one incomplete product box. This feature is such that, for example, if we set to display 2 product boxes on each slide, two complete boxes and an incomplete one will be displayed. Or, for example, if we specify that 4 boxes of products are displayed on each slide, it will show 4 complete boxes and an incomplete one. For this reason, this feature is called **Incomplete mode**.
To understand more about this fascinating feature, please watch this video ( Please note the half box on the left )
https://drive.google.com/file/d/1xD4Ir_OBuvWhjYHPIrABPEa5dciC0BgS/view?usp=sharing
After the scroll is completed, the half mode is shifted to the right. Like the image below : 
![Screenshot_20210711-030814_Chrome](https://user-images.githubusercontent.com/77163248/125178103-cf3cba00-e1f6-11eb-9004-36e4ac7bacb4.jpg)

In this website, you can see this feature and examine its function carefully : https://www.banimode.com/
**Of course, it should be noted that this feature is only used in mobile phones and tablets.**
Finally, I emphasize that please do not confuse this feature with the center mode. They are very different.

I apologize for the lengthy explanation. thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

In our carousel we use [Swiper Slider](https://swiperjs.com/swiper-api) and with it you cant make this functionality.
