### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by alexgauvin** [CrocoBlock/suggestions#3636]
Hi,

I'm trying to work out a specific operation that involves WooCommerce, JetEngine, and Extra Product Option for WC (EPO) from ThemeHigh.

The results expected is to impact the price of a product by multiplying a JetEngine custom field value by a fixed price from EPO from inside

Please have a look at : https://www.loom.com/share/5986ccf27a3949b6bf75662f4eb864e9 for visual info about my request.

And here is custom snippet provided by ThemeHigh devs

```
add_filter('thwepo_product_field_extra_cost','adjust_product_field_extra_cost',9999,4);
function adjust_product_field_extra_cost($fprice, $name, $price_info, $product_info) {

    // you can use below data if needed.
    $price_type = isset($price_info['price_type']) ? $price_info['price_type'] : 'normal';
    $value = isset($price_info['value']) ? $price_info['value'] : 0;


    if ($name == 'wepo_custom_field_name') {
        // you can integrate jet engine field value with your developer
        $JetEngine_field_value == "jetengine field value";
        $fprice = $fprice*$JetEngine_field_value;
    }

    return $fprice;
}
```

Thanks for your support

**Comment by Floydtm** [comment]
Your link is not working. Re-create the request
