### ISSUE TITLE
Lottie widget: allow number of times to loop to be specified

### ISSUE THREAD

**Issue by lcgitrdone** [CrocoBlock/suggestions#3639]
I like the Crocoblock Lottie widget better than the Elementor widget.  But, sometimes I have to use the Elementor version because it allows me to specify a set number of times to loop.  Some Lotties becomes annoying if they play infinitely.  See screenshot.  Thank you!

<img width="555" alt="Screenshot 2021-07-12 at 14-04-42 JetElements Lottie Widget Full Overview Crocoblock" src="https://user-images.githubusercontent.com/25237949/125335683-d52bbb80-e31a-11eb-86eb-b76e4b1bf914.png">

**Comment by kaskad88** [comment]
Added to JetElements 2.5.9
