### ISSUE TITLE
JetSmartFilters - Change date format

### ISSUE THREAD

**Issue by SirLouen** [Crocoblock/suggestions#364]
**Please, describe the feature request, making it clear to understand.**

This is simple: I only need to change the JetSmartFilter Date Ranger filter format from 
MM/DD/YYYY to DD/MM/YYYY

**Add an example of where this feature is already implemented. **

https://theworldmarch.org/adhesiones/

Instead of 
07/05/2019 meaning 5th July 2019, US format
05/07/2019, meaning 5th July 2019, European format

**Comment by createque** [comment]
Is this solved? I have the same problem and don`t see possibility to change this date format

**Comment by createque** [comment]
Please solve this issue. 
Invalid date format looks very unprofessional on our websites.

**Comment by Floydtm** [comment]
Available in version 2.0.1
