### ISSUE TITLE
** Bug on Products Grid Widget if Query by "Custom Taxonomy" created with the plugin "Perfect Brands for WooCommerce" **

### ISSUE THREAD

**Issue by P-happiness** [CrocoBlock/suggestions#3642]
**Describe the bug**
Hi there,
I want to report a Bug on Products Grid Widget (JetWooBuilder).
It seems that the option Query by "Custom Taxonomy" doesn't work for Taxonomy created with the help of the Plugin: Perfect Brands for WooCommerce.
I'm trying to create a carousel on my Homepage and I want to Query for Brands created with this plugin, but I keep getting "Products not found" message.

1) Here is one of the terms (brands) created with the Plugin "Perfect Brands for WooCommerce. 
Name: Dr Martens
Slug: dr-martens
https://prnt.sc/1ar0u0m

2) Here is the "Products not found" message. 
Query by "Custom Taxonomy"
Slug: dr-martens
https://prnt.sc/1ar1vi2

Could you help me please?
Thanks for your support!

**Comment by UraraReika** [comment]
Hello @P-happiness !

You need to fill all fields correct https://i.gyazo.com/851e12f0d01132238ef420c531133d8f.png.
Tax slug taken here https://i.gyazo.com/f446082022c29e3bbe96c186a9dcb495.png URL line.
Id from tax https://i.gyazo.com/f872055ac9c9e9542bb9f63ac1b6cbf7.png.

result https://i.gyazo.com/833b655367c70039fc06a9a5f8e49343.png
