### ISSUE TITLE
pie chart legend vertical align

### ISSUE THREAD

**Issue by delas-soap** [CrocoBlock/suggestions#3646]
This should be a pretty obvious function for the pie chart. However, I don't think anyone thought about it.

![image](https://user-images.githubusercontent.com/57832551/125551864-00a78aa2-7fff-4115-a9d0-4a2984b0c265.png)
![image](https://user-images.githubusercontent.com/57832551/125551898-45f50d2b-c3d3-414a-ab6a-e288051bd04c.png)

**Comment by Gawuww** [comment]
Added in JetElements 2.6.2
