### ISSUE TITLE
Font problem in Jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3647]
I have customized my website font using elementor custom fonts. But today I noticed that in the jet woobuilder plugin, the values ​​of 100 and 400 fonts are not displayed.
I checked the problem in elementor widgets but there was no problem and they were displayed. I do not know if this problem exists for you or not.
![Screenshot (75)](https://user-images.githubusercontent.com/77163248/125603130-0274acdc-9730-4e25-809c-2fe7dd77d640.png)

thank you

**Comment by UraraReika** [comment]
We didnt face this problem so please contact our support team.
