### ISSUE TITLE
JetFormBuilder - A Form Entries Module aka Database to Save Submitted Forms

### ISSUE THREAD

**Issue by realstephenzhao** [CrocoBlock/suggestions#3651]
Please implement a form entries module (sometimes called database plugin) to save form submissions.

Even Elementor had released such an feature, but I will ditch Elementor and fully switch to Gutenberg after WP5.9.

**Comment by baf139** [comment]
yes, this would help greatly!

**Comment by git-temak** [comment]
This feature is highly required. An option to enable forms to save submissions in the backend would be nice. An example for CF7 is here - https://en-gb.wordpress.org/plugins/contact-form-submissions/

**Comment by girafffee** [comment]
This functionality has been added since version 2.0

https://jetformbuilder.com/features/wordpress-custom-form-records-page/

**Comment by git-temak** [comment]
@girafffee how about for Jet Forms itself, the module that comes with JetEngine, does that have this functionality? Only the JetFormBuilder seems to have it, or is JetEngine Forms going to be retired?

**Comment by girafffee** [comment]
@git-temak JetEngine forms are legacy now. We add all changes and improvements to the JetFormBuilder so it has many more functionalities than the JetEngine.
You can use the converter to transfer the form from the JetEngine to the JetFormBuilder. https://github.com/Crocoblock/jet-form-builder-converter
