### ISSUE TITLE
PLEASE! JetBooking/JetEngine - Ability to change price based on dates

### ISSUE THREAD

**Issue by jpcayman** [CrocoBlock/suggestions#3656]
As plugins that were built with accommodations in mind, I don't understand why seasonal rates aren't an option using JetBooking/JetEngine. The ability to change the price for specific nights/dates/seasons is very important in the accommodations/hospitality industry. There are high and low seasons and rates change within these times so JetBookings/JetEngine are quite useless for this industry. I'd love to move my clients away from their current PMS (Property Management System) if this becomes an option.

A dashboard (if not already available) to view data such as # of bookings, revenue made, booked/blocked dates would also be amazing for both the developer and client!

**Comment by CaseFixedWebdesign** [comment]
+1

**Comment by tfrank7** [comment]
+1 I really need this function.

**Comment by benjamieson** [comment]
+1 - Essential!

**Comment by WebStudioNW** [comment]
It's a bank holiday this weekend in the UK, I have setup a simple selector as a work around, but it's far from ideal.  It is a much needed feature to any booking system to be able to alter prices based on day or date.

[Touring Caravan Park North Wales Booking Form](https://penisarmynydd.co.uk/pitches/caravan-standard-pitch/)

It pains me to have to go on about it, the more I use Crocoblock the more I like their stuff and appreciate the quality of the plugins, but this is a big issue.......please resolve so I can love you guys more:)

**Comment by ghost** [comment]
I implemented a custom solution with seasonal coefficients and custom periods, with the check done day per day and not just on start date. If someone interested he can contact me

**Comment by WebStudioNW** [comment]
> I implemented a custom solution with seasonal coefficients and custom periods, with the check done day per day and not just on start date. If someone interested he can contact me

Very interested in this, we need to change some days in the calendar (uk bank holiday weekends) and an increase in price over the summer season.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.4.0 version. You can fell free to check it out.

Thank you!
