### ISSUE TITLE
'Portfolio' widget hover images + 'Inline SVG' widget images (JetElements) translatable into other languages

### ISSUE THREAD

**Issue by AliceNatali259** [CrocoBlock/suggestions#3657]
I am writing this suggestion as instructed by Crocoblock support. 

Currently, the HOVER IMAGES (either SVG or other, such as PNG or JPEG) of the JetElements 'Portfolio' widget are not recognised by translation plug-ins, such as Translate Press, so they cannot be replaced in the case of a translation into another language. Translate Press allows you to select only the image, but NOT the hover image (as you can seen in the third screenshot, the site with the pink background).
Here is a practical example: I have an image in a 'Portfolio' widget; if I click on this image, it takes me to the page of a specific project; if I hover over the image, I would like a hover image to appear with the title of the specific project. My site (under construction) is in two languages, Italian and English, so the hover image with the title in Italian must be selectable with the translation plug-in and replaceable with other one with the title in English. The 'Filtrable Gallery' widget in the Essential Addons for Elementor plug-in allows this to be done without any problems (as you can see in the first and second screenshot, the site with the black background that I created using this plug-in: the balloon is a SVG hover image with a text on it). 

I found the same problem with the 'Inline SVG' widget, also from JetElements: Translate Press does not recognise the SVG IMAGE, it is not selectable and therefore cannot be replaced. In the latter case, I got around the problem by using the classic Elementor 'Image' widget instead, that Translate Press recognises correctly, but I still think the problem should be solved. 

![Example of Translate Press and hover images of EA 'Filtrable Gallery' widget (1)](https://user-images.githubusercontent.com/87484316/125803483-9738a864-790f-4208-addf-03edd8257a70.jpg)
![Example of Translate Press and hover images of EA 'Filtrable Gallery' widget (2)](https://user-images.githubusercontent.com/87484316/125803488-a4609d47-a073-43ce-b621-7ddf4cc19b6f.jpg)
![Example of Translate Press that recognises only the image of JetElements 'Portfolio' widget](https://user-images.githubusercontent.com/87484316/125804278-d75bdef2-3f63-45db-91c8-5f60a6e250a8.jpg)

**Comment by Gawuww** [comment]
Added in JetElements 2.6.2
