### ISSUE TITLE
Add Custom Post Type selection when using Advanced Map in a Popup

### ISSUE THREAD

**Issue by JamesDandy** [Crocoblock/suggestions#366]
I'm trying to add the Advanced Map widget from the JetElements group to a JetPopup but I cannot access the underlying Post Type from the page the popup is executed from. 

There are no options in the Popup settings to select a Post Type to work with the popup and therefore there are no fields to choose from under the Dynamic Map Center settings.

![image](https://user-images.githubusercontent.com/40547617/61404949-9fc47280-a8a6-11e9-95c1-a1f182e1e326.png)

**Comment by Floydtm** [comment]
Hi! Now all options of custom fields will be available in the select. But you must understand that your case works if a connection is established with a popup and a custom field. Simply put, this will work if the popup and labeling the field with the value are on the same page.
