### ISSUE TITLE
Auto Delete Post at Indicated Time Frame.

### ISSUE THREAD

**Issue by FknBestBrain** [CrocoBlock/suggestions#3666]
Hopefully you add the "Paid Listings" request, and if you do or don't, I would like to be able to have the listing expire on a certain date. I do not want to have posts siting on my server forever, it would be easier to have them autodelete or go into a folder for deletion, or go back into a draft state if it cannot be deleted that admin only has access to to request whether user wants to update post again for a "price". Would like Stripe capability, woo commerce, something other than PayPal, but PayPal for those who use this as well. We all in this together you guys/girls!

**Comment by Floydtm** [comment]
It looks like we have one [solution](https://crocoblock.com/freemium/tools/) https://prnt.sc/1h4b63n. As for your other ones, we can easily consider them and establish their status. Stay tuned!

**Comment by FknBestBrain** [comment]
Thanks. What were the "others"? I'd like to keep track in one email
response. Please provide the "other" suggestions to stay tuned for.

**Comment by Floydtm** [comment]
At the moment there is only one solution for your request
