### ISSUE TITLE
Fatal Error on Single Product Template (JetWooBuilder)

### ISSUE THREAD

**Issue by P-happiness** [CrocoBlock/suggestions#3667]
Hi there,
I'm getting a Fatal Error on Single Product Template.
I can't edit it.

https://prnt.sc/1c9mu1x
https://prnt.sc/1c9nbs4

Since I updated to the latest version of JetProductGallery I started noticing problems on the frontend.

https://prnt.sc/1c9p3ep

The Gallery is gone. I keep getting Gallery not found message.

Could you helpe me please?

**Comment by 79ho3ein** [comment]
hi @P-happiness
This problem only exists for a single product page, right? checkout page, shopping cart, etc. work properly?
This problem has also occurred to me in a recent update. (1.9.0 version)
I reported it to the developers. And I explained the problem.(In #3628)
That's why I'm still in version 1.8.2 ...
I hope the problem is solved in the new version.

**Comment by P-happiness** [comment]
> hi @P-happiness
> This problem only exists for a single product page, right? checkout page, shopping cart, etc. work properly?
> This problem has also occurred to me in a recent update. (1.9.0 version)
> I reported it to the developers. And I explained the problem.(In #3628)
> That's why I'm still in version 1.8.2 ...
> I hope the problem is solved in the new version.

Hi @79ho3ein,
yes this problem only exists for single product page...

On Query Monitor I get a PHP Error to JetWooBuilder plugin.

`wp-content/plugins/jet-woo-builder/includes/shortcodes/jet-woo-products-shortcode.php:534
Jet_Woo_Products_Shortcode->query()
wp-content/plugins/jet-woo-builder/includes/shortcodes/jet-woo-products-shortcode.php:813
Jet_Woo_Products_Shortcode->_shortcode()
wp-content/plugins/jet-woo-builder/includes/base/class-jet-woo-builder-shortcode-base.php:187
Jet_Woo_Builder_Shortcode_Base->do_shortcode()
wp-content/plugins/jet-woo-builder/includes/widgets/global/jet-woo-products.php:631
Elementor\Jet_Woo_Products->render()
wp-content/plugins/elementor/includes/base/controls-stack.php:1892
Elementor\Controls_Stack->render_by_mode()
wp-content/plugins/elementor/includes/base/widget-base.php:549
Elementor\Widget_Base->render_content()
wp-content/plugins/elementor/includes/base/widget-base.php:679
Elementor\Widget_Base->print_content()
wp-content/plugins/elementor/includes/base/element-base.php:650
Elementor\Element_Base->print_element()
wp-content/plugins/elementor/includes/base/element-base.php:911
Elementor\Element_Base->print_content()
wp-content/plugins/elementor/includes/base/element-base.php:650
Elementor\Element_Base->print_element()
wp-content/plugins/elementor/includes/base/element-base.php:911
Elementor\Element_Base->print_content()
wp-content/plugins/elementor/includes/base/element-base.php:650
Elementor\Element_Base->print_element()
wp-content/plugins/elementor/core/base/document.php:1420
Elementor\C\B\Document->print_elements()
wp-content/plugins/elementor/core/base/document.php:943
Elementor\C\B\Document->print_elements_with_wrapper()
wp-content/plugins/elementor/includes/frontend.php:1010
Elementor\Frontend->get_builder_content()
wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-template-functions.php:510
Jet_Woo_Builder_Template_Functions->get_woo_builder_content()
wp-content/plugins/jet-woo-builder/templates/woocommerce/content-single-product.php:39
load_template('wp-content/plugins/jet-woo-builder/templates/woocommerce/content-single-product.php')
wp-content/plugins/woocommerce/includes/wc-core-functions.php:284
wc_get_template_part()
wp-content/plugins/woocommerce/templates/single-product.php:37`

I'm still on the latest version of JetWooBuilder and I can tell you that the problem is not solved.
In my case the huge problem is related to JetProductGallery plugin on the frontend.
The gallery didn't show up.
I had to come back to version 1.3.1 to let it work again, but I keep getting this fatal error on the backend.
I hope they solve this problem.

**Comment by 79ho3ein** [comment]
@P-happiness 
The problem is definitely with the jet woobuilder plugin. **To test, please do what I say below and let me know the result**

You have used the product grid widget on a single product page. Please change all queries to "all" in the product grid widget.
For example, if the product grid query was on related products, cross sell, etc., set them to "all". And then save the settings.
Has the problem been resolved?

**Comment by UraraReika** [comment]
@P-happiness The problem with fatal error is solved, release soon. After product gallery update please select gallery source

**Comment by UraraReika** [comment]
@P-happiness you can contact our support team to solve this issue
