### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by CommerceMax** [CrocoBlock/suggestions#3672]
Meta fields for product variations in Woocommerce are currently not supported, though I can select variations while creating a meta field. The field will not show up on the product variation. Simple feature, that your users will love. It will give you an advantage over your competitors and save us messing around with crooked code snippets and additional plugins.

**Comment by UraraReika** [comment]
Thanks for the feedback.
 Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.

**Comment by CommerceMax** [comment]
> Thanks for the feedback.
>  Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.

Reopend here https://github.com/Crocoblock/suggestions/issues/3674#issue-947553716
