### ISSUE TITLE
Meta fields (Custom Fields) for product variations in Woocommerce with Jet Engine 

### ISSUE THREAD

**Issue by CommerceMax** [CrocoBlock/suggestions#3674]
I would like to see support for Jet Engine Custom Meta Fields for Woocommerce Product Variations. 

After contacting support this feature is currently not supported.

While configuring Custom Meta Fields under the current options, i'm able to select "Variations" under the "Enable For Post Types" option. In the image below you can see the Meta Field "Info" is set to display on "product_variations", which i was able to select from the dropdown menu. 

<img width="1500" alt="Schermafbeelding 2021-07-19 om 12 50 16" src="https://user-images.githubusercontent.com/87635598/126149687-eedfedad-903d-4d1f-a9bc-e5013a129482.png">

This field doesn't show up in the backend on the product variation panel. If i select product the custom field shows up fine on the single product.

Why would you incorporate such a feature?

Custom fields on products are nothing new, though there isn't a solution that comes out of the box for product variations. I can imagine multiple scenarios where this feature will come in handy. In the link below there is a code snippet available as work around for the same problem. 

- I don't want to install any additional plugins or code to work my way around. 
- There are a lot of topics with people that are having similar problems. 
- It would give you an advantage over competitors who provide custom fields solutions.
- Would make your product more less buggy experience because i'm already able to select product variations from the dropdown list, but this doens't work.
- Low effort, high effect

[Example](https://www.businessbloomer.com/woocommerce-add-custom-field-product-variation/)

**Comment by UraraReika** [comment]
Released in JetEngine 3.2.0 verison.
