### ISSUE TITLE
Search Functionality to include Comments to the search

### ISSUE THREAD

**Issue by leppisretep** [CrocoBlock/suggestions#3675]
Hi.
The JetEngine search functionality (like Ajax Search) is currently not searching in the comments. I want site members to discuss the posts and this text or information should be included in the search results.
Thanks.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
