### ISSUE TITLE
Improve JetTabs functionality - it has great potential

### ISSUE THREAD

**Issue by ConsultMePL** [CrocoBlock/suggestions#3677]
Hi,

I have used JetTabs along with JetEngine and found it extremely useful to build restaurant menus, galleries, and now even woocommerce shop page. But there are way more used cases, but in order to fully utilize JetTabs potential, I'd love to certain improvements:

- ability to "enable slider" so it could be mobile friendly (for now I have to use custom css)
- ability to query elements directly in the tabs instead of template, so you only have one template instead of 10 (in a similar matter you can query elements inside of listing grid - it wouldn't have to be enabled by default, you could enable it from JetTabs settings like you can do with JetEngine modules)
- dynamic creation of Tabs - if Tab is a category/taxonomy and you have a CPT/Taxonomy, once you add them in wp-admin, Tabs and items are automatically added to the Tabs structure
- fetching/deffering load of all but first Tab in order to improve performance

Implement those functions and it could become amazing tool. I guess enabling slider, query elements or deffer load (not ajax load - it makes it worse) shouldn't be that difficult, some options are already there, just not available for JetTabs

Thanks,
Dominik

**Comment by IrynaBerezhnaya** [comment]
Added slider for the Tabs widget, the rest is already done.

**Comment by Crocoblock** [comment]
released in JetTabs 2.2.5
