### ISSUE TITLE
Title option is not working on breadcrumbs.

### ISSUE THREAD

**Issue by MakhonkoDenis** [CrocoBlock/suggestions#368]
When you edit a page through the elementor editor, the page title disappears.

The problem is in the line: https://github.com/Cherry-X-framework/cherry-x-breadcrumbs/blob/master/cherry-x-breadcrumbs.php#L715

Decision: ```$post_title = have_posts() ? single_post_title( '', false ) : get_the_title() ;```

**Comment by kaskad88** [comment]
Fix for next version.Thanks for your report!
