### ISSUE TITLE
jetwoo is untested and incompatable with elementor pro 

### ISSUE THREAD

**Issue by cadentic** [CrocoBlock/suggestions#3680]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

get woo builders is not updated for last 5 months and showing incompatible with elementor pro 
elementor -> systeminfo

**Comment by UraraReika** [comment]
Hello @cadentic !

Latest JetWooBuilder version has this compatibility tags:
 * Elementor tested up to: 3.2
 * Elementor Pro tested up to: 3.3

There wastn any release after Elementors updates. Next release will be soon and already tested with latest versions of Elementor and Pro version.
