### ISSUE TITLE
JetEngine: Option to Export & Import JetEngine CPT & CCT Meta Fields 

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#3683]
Right now if you have 2 websites that are basically using the same details there's no quick method to export / import meta fields for the various data types. 

It would be phenomenal to have the option to export the Meta Fields for the Custom Post Type and Custom Content Types but could also be extended to some of the others: 

- jet-engine-meta
- jet-engine-cpt-tax
- jet-engine-options-pages

This would allow the site admin to export one set of meta field data and import it into another site speeding up multi site development.

**Comment by Floydtm** [comment]
You can do it all right now. Have a look at the jetengine plugin options https://prnt.sc/1iootcd

**Comment by newtonata** [comment]
Skin Manager doesn't include CCT Export/Import. i think that issue should be reopened.
