### ISSUE TITLE
Problem with Single Sale Badge Widget (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3685]
hello
in Single Sale Badge Widget, The field is not in the right place and is not in a good position. https://prnt.sc/1alenp4
As you can see in the image above, the highlighted field is out of the box by default. And this makes it difficult to align with other widgets. Now, I'm aligning this part using the margin. Please fix this problem if possible.

thank you

**Comment by UraraReika** [comment]
Please contact our support team with this request
