### ISSUE TITLE
Visual cue of unused widgets in all JetPlugins settings for deactivation

### ISSUE THREAD

**Issue by alexgauvin** [CrocoBlock/suggestions#3687]
My suggestion would be to have a visual cue on each Widgets & Extensions page settings for every JetPlugins installed that indicates which widgets and/or extensions are in use (or not) on the website. 

This to be able to deactivate them when dev project is done, for efficiency and speed purposes.

A short clip to be more precise : https://www.loom.com/share/d5dad5e85aa54c48bb967d7871797cd1

**Comment by Floydtm** [comment]
merge with #3607
