### ISSUE TITLE
Sales Funnel Builder for Wordpress 

### ISSUE THREAD

**Issue by onakan1** [CrocoBlock/suggestions#369]
Sales Funnel Builder for Wordpress

**Comment by qwik3r** [comment]
Cartflows isn't over priced first of all. Secondly it's a major system that I highly doubt CrocoBlock is going to bother creating or competing against. Kind of a dumb request to be asking here.

**Comment by onakan1** [comment]
I understand. Currently working on a Carflow alternative. Should be out soon. See how it stacks up against CartFlows.

**Comment by qwik3r** [comment]
Please post your alternative here when you do!

**Comment by onakan1** [comment]
Adams please do you realise this is GitHub? Why take things personal?
