### ISSUE TITLE
Adding a map to forms to provide a location #JetEngine

### ISSUE THREAD

**Issue by frankwarwick** [CrocoBlock/suggestions#3690]
Adding a map to forms to provide a location using drag n drop pin location that also shows the address in adjacent input fields.

As an event manager I want to provide the country, State, city/town and post code/Zip 
As a rental agent I want to show the country, State, city/town and post code/Zip
I live in a location that has not street name or property numbers

**Comment by Lonsdale201** [comment]
May this help https://jetformbuilder.com/addons/address-autocomplete/? :)

**Comment by frankwarwick** [comment]
Thanks @Lonsdale201, that exactly what I am looking for
