### ISSUE TITLE
JetWooBuilder releated products 500 internal server error crash

### ISSUE THREAD

**Issue by hNilsen90s** [CrocoBlock/suggestions#3693]
**JetWooBuilder 500 error crash**
If you create a single product page template, and add a product grid listing and set query to "related" products on a single products page/template you will ruin/break your template. You are not able to revert this, you'll keep getting an error 500 until you create a new single product template.

**Reproduce crash**
1. Setup a single product page
2. Add product grid listing
3. Publish and save the changes to get access to related products query.
4. Select "related" in query by in the listing grid.
5. Save and publish the page again.
6. Try do any changes to the page yet again, and you will keep getting 500 errors.

**Screenshots**
http://prntscr.com/1ea5adz

**Desktop (please complete the following information):**
 - Browser: All (Tested Safari, Chrome, Firefox)
 - Version: Tested with latest plugin version

**Extra**
All plugins are updated, only running Crocoblock and Elementor. The memory limit is set to 1GB. The error only occurs on the single product page.

**Solution**
Last working version is JetWooBuilder 1.8.2 (Version 1.9 and above are broken)

**Comment by 79ho3ein** [comment]
hello @UraraReika 
When will this update be released? may you tell?

**Comment by UraraReika** [comment]
This week

**Comment by 79ho3ein** [comment]
thank you

**Comment by hNilsen90s** [comment]
@UraraReika was this issue fixed in the JetWooBuilder 1.9.2 release? Found nothing releated to the bug in the changelog.
