### ISSUE TITLE
JetWooBuilder settings - Use AJAX remove from cart instead of reload page

### ISSUE THREAD

**Issue by 93petter93** [CrocoBlock/suggestions#3708]
Hi! Could you add functionality to use AJAX to remove products from cart instead of reload page? 

This could be a checkbox inside JetWooBuilder settings next to "Force use AJAX add to cart instead of page reload on the singe products page".

**Comment by UraraReika** [comment]
Hello @93petter93 !

If you enable this option https://i.gyazo.com/25917457f8acf59497e5eeec3e9d5b4a.png then you can remove products from the cart (JetBlocks - WooCommerce Shopping Cart, and module in kava theme header) via ajax.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
