### ISSUE TITLE
JetSmartFilters - Filter product categories descending by index count

### ISSUE THREAD

**Issue by 93petter93** [CrocoBlock/suggestions#3709]
Hi! Could you add a way to filter product categories descending by index count?

Example:
![image](https://user-images.githubusercontent.com/58670859/126747572-fa12ac94-0cde-40c8-ac48-4874082ac5ea.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
