### ISSUE TITLE
Product Grid Use Current Query must be able to set Order by and Order in Jetwoobuilder

### ISSUE THREAD

**Issue by DevDietheR** [CrocoBlock/suggestions#3710]
Hi, Recently my client asked me if they can set the product grid order, I said yes but the problem is if it is a category page, the product grid must be set to "Use Current Query" in order to display the products for the current categories/tags, the problem is when this is activated the Order by and Order option dissapears. 
This is very important to have, not just a-z order 

![image](https://user-images.githubusercontent.com/42364592/126748653-afc58c29-4f22-4f5f-a255-944a446406da.png)

![image](https://user-images.githubusercontent.com/42364592/126748700-3141b7fb-bc09-4988-a220-e346b03f7f10.png)

**Comment by UraraReika** [comment]
Hello @DevDietheR !

Appearance > Customizer > WooCommerce > Product Catalog > https://i.gyazo.com/276104d73334805673a508c3ae879cc6.png. You cant although expand this list with hooks.
