### ISSUE TITLE
Jetpopup - CSS error (It is not displayed in the front-end of the elementor (editor) and also in the preview of the page)

### ISSUE THREAD

**Issue by prodrigocostavieira** [CrocoBlock/suggestions#3719]
I have a problem with Jetpopup.

When I create a new popup, when I make any changes to the style settings, inside the elementor editor, nothing changes. The same problem occurs in the page preview, the css is broken all over and no style settings are displayed.

I've tried absolutely EVERYTHING!

Update plugins, disable all plugins and leave only jetpopup and elementor, change theme, reload css style in elementor tool, use old version of jetpopup, use old version of elementor, but problem persists.

I'm using the "quick view" option for dynamic loading of a custom post type, and the css is all broken.

Is there any solution for this?

Thank you!

<a href="https://ibb.co/K2VKm4v"><img src="https://i.ibb.co/fkrDQ6w/Captura-de-tela-2021-07-23-130753.jpg" alt="Captura-de-tela-2021-07-23-130753" border="0"></a>

**Comment by Floydtm** [comment]
To quickly resolve your request, you need to contact our support team
