### ISSUE TITLE
Ability to display product images in 3D in the jet product gallery.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3721]
hello
Recently, I saw the feature of displaying products in 3D, which was very interesting to me. A similar example is implemented in the Woodmart format, but it is not complete and can only be moved left and right. https://woodmart.xtemos.com/shop/furniture/eames-plastic-side-chair/
**In principle, this feature is such that the products can be moved in all directions and all parts can be seen.**

I wanted to share this feature with you. I hope it is useful. thank you

**Comment by 79ho3ein** [comment]
We see the full example of this feature in this video :
https://user-images.githubusercontent.com/77163248/126994480-d17c7791-e43c-45a4-afd1-bfc142fea25a.mp4

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
