### ISSUE TITLE
Cannot reset JetAppointments settings

### ISSUE THREAD

**Issue by stavroscha** [CrocoBlock/suggestions#3724]
After updating the plugins to the latest versions i was not able to reset the setup of the JetAppointments by going to Set Up menu and pressing the Reset button.

I was getting an error about vue.js file.

**Comment by Floydtm** [comment]
Hi. We checked it out and everything seems to be working correctly. Tell me if you are still experiencing the problem. If so, then you better contact our support team. Thank you!

**Comment by stavroscha** [comment]
Issue has been resolved
