### ISSUE TITLE
Mobile - Horizontal scrolling for products

### ISSUE THREAD

**Issue by 93petter93** [CrocoBlock/suggestions#3726]
Hi! I would love to see a way to display products on mobile with horizontal scrolling. It looks so clean and makes a great UX. 

Examples:
![image](https://user-images.githubusercontent.com/58670859/126931646-760be397-94fe-41cf-8a4b-408967d4a513.png)
![image](https://user-images.githubusercontent.com/58670859/126931656-ea38110b-beb1-472d-958f-6b7aa60042a2.png)
![1](https://user-images.githubusercontent.com/58670859/126931709-8f53ee1a-fe64-4710-bb38-7e9ee17765d9.gif)

**Comment by 79ho3ein** [comment]
hello @UraraReika 
This is exactly what I wrote about in issue #3633 ....

But there is one point about this great feature. That this feature can be both free mode and normal. For example, in the video above that @93petter93  showed, it was displayed in free mode. 
This feature is excellent. I hope it will be added to the plugin soon.

thank you

**Comment by UraraReika** [comment]
Hello @93petter93 ! 

Our widget has Center Mode controls which is pretty mush the same. With some small difference. You may although use this lines of code to achieve your results.

```
.swiper-container {
    overflow: visible;
}
```
