### ISSUE TITLE
Jet Woo Builder "Products Grid"  include option to add "More Info" button

### ISSUE THREAD

**Issue by andybarn** [Crocoblock/suggestions#373]
When using Jet Woo Builder to add a "Products Grid" to a page this works fine

This comes with an option to either show or hide the "Add To Cart" button. 

It would be good to add a feature to show or hide a "More Info" button and this is to link to the Product Page just the same as if you clicked the Product Image or Title

Thanks
Andy Barnish

**Comment by Floydtm** [comment]
Hi! We cannot do this because it is the same button. She changes the text depending on the product
