### ISSUE TITLE
Show meta field only if a term taxonomy is choosen like ACF

### ISSUE THREAD

**Issue by enricgomez** [CrocoBlock/suggestions#3730]
I'm creating a meta field with JetEngine.
I want that meta field to show only if a specific category is choosen.
I don't see that conditional.
ACF has it.

**Comment by dotrahat** [comment]
+1

**Comment by kaskad88** [comment]
@enricgomez @dotrahat 
This feature is available now from JetEngine v3.2.0
Steps to settings:
1- Go to Meta Box settings
2- Click to the `New Condition` button https://tppr.me/e6bse in the Visibility section
3- Select the `Post Has Taxonomy Terms` option
4- And choose the necessary taxonomy and terms https://tppr.me/hMDNa
