### ISSUE TITLE
Jet form few fields for one post meta not working

### ISSUE THREAD

**Issue by Mindaugasmitras** [CrocoBlock/suggestions#3731]
**Form fields don't shows up after post published.**
I have few form fields for one post meta field, only one field can by chosen but anyway nothing shows in published post. Can you please fix this.
 in form I made like this:

_model_acura               Post Meta    model
_model_alfa_romeo      Post Meta   model
_model_audi                 Post Meta   model

**Comment by Floydtm** [comment]
Hi. This will not work at the moment. You can write data from one form field to one meta field. I understand that this is important to you, but we cannot add it to the plugin yet. Thank you!
