### ISSUE TITLE
Problem displaying single product page in Safari browser (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3732]
The variable product selection section, as well as the number of products, is displayed in a very bad way in Safari browser and has a very inappropriate user interface. While in Android browsers it is completely different.
![IMG_20210725_210327_695](https://user-images.githubusercontent.com/77163248/126994226-da1a9ba9-3023-41fb-9731-e66618954c66.jpg)

Please check. Thank you

**Comment by UraraReika** [comment]
Select - fixed.
Input We have checked your request in latest Safari and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
thank you @UraraReika 
I use the hello elementor theme. All the bugs I report are about this theme. Most users of jet extensions use the hello elementor theme، I do not know if you are testing bugs in this theme or other theme. Please test the bugs in this theme. This is the formal element pattern.
In any case, thank you very much for your efforts🌹

**Comment by UraraReika** [comment]
Still no any errors and you should notice it at the beginning.

**Comment by 79ho3ein** [comment]
ok, thank you
