### ISSUE TITLE
Jet Appointments - select multiple people/options per service

### ISSUE THREAD

**Issue by michaelsburgess** [CrocoBlock/suggestions#3735]
It would be extremely useful if an appointment could be set for more than one person per time slot. Currently appointments can be set for one person per time slot per booking.  It would be far more versatile and for a broader range of applications if user was presented with a drop down to select number of people per time slot - or system allows for multiple options on one service post page. 

In our application we can accommodate multiple people in a single time slot as a group activity. Currently the group would need to each book individually for the same time slot 10 times or we would need to create individual services for each quantity Service 1, Service 2,3..... 10, which is impractical. 

In addition:

- This would also need ability to calculate the total price for each person added.

or

- It would be useful to expand the Price field in the services post page from a single field to a table of sorts that allows for multiple variations for each service type. i.e. one person = $10 and two people = $16 as special price package instead of simply multiplying $10 X 2 = $20 for two people as in first option.  

I hope this is clear.
 
Many thanks.

**Comment by Floydtm** [comment]
Hi. Almost everything you need can be done right now. If you have a problem with this, please contact our support team. Thank you! 
[bandicam 2021-08-23 14-43-45-780.zip](https://github.com/Crocoblock/suggestions/files/7031555/bandicam.2021-08-23.14-43-45-780.zip)
