### ISSUE TITLE
Add widgets Jet Tabs for repeater fields

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#374]
Please add Jet Tabs widgets for the ability to add content via Repeater Fields

Speech about this feature add-on JetElements Dynamic Data Addon
https://crocoblock.com/2018/09/26/jetelements-dynamic-data-addon-the-key-to-adding-dynamic-content-to-jetelements-widgets/

http://prntscr.com/oha4yk

In almost every project in the service templates, I have a FAQ section which is displayed by a widget from Jet Tabs and I have to make a fixed number of arbitrary fields.

**Comment by stasonua0** [comment]
Hello, this functionality is very necessary in 90% of projects. Please give this development a higher priority. Thank you!

**Comment by kaskad88** [comment]
Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )
