### ISSUE TITLE
There are no bestsellers in the product grid widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#3740]
jet woobuilder...
In the product grid widget, there is no query to display best sellers products. And this is disappointing
![Screenshot (95)](https://user-images.githubusercontent.com/88034902/127145719-8e0e1fa7-b344-4687-90e4-ca933d241b89.png)
In this plugin we can display the products that the user has recently visited, but we can not display the best sellers products.
Many customers ask us to display best-selling products as carousels. But we can not ... 
Please add it to the plugin. It is very useful and necessary. 
In all theme and store sites, there is the ability to display best-sellers products. It is strange how the jet woobuilder was indifferent to it.

**Comment by UraraReika** [comment]
Same subject here #3058.

**Comment by Michaelgimii** [comment]
thank you
After inserting the code, what should I put the product grid query widget on? all?
