### ISSUE TITLE
Link "JetEngine forms" to woocommerce (gateway payment) 

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#3742]
Hi

I have searched a lot about how to link JetEngine's forms or jetformbuilder to woocommerce for making a payment, Because payment's systems are not all the same in different countries (PayPal is not supported in my country)! but there are some Plugins for woocommerce so we can make a payment. 

![Screenshot_20210728-015957_Chrome](https://user-images.githubusercontent.com/86493591/127231069-39c17aaf-3a03-4303-b08b-9e894967004a.jpg)

Assume that i want to make a form for my services and then make a payment at the end! There are two ways to make the payment: first design a custom payment setting that each gateway can connect to it, second one is to link the form to woocommerce and make the payment. 

Please consider this important issue 
Best regards. 

@UraraReika

**Comment by 79ho3ein** [comment]
+1

**Comment by mehdimoradi1500** [comment]
Hi @UraraReika 
will u please check this feature
I have just watched YouTube tuts for JetEngine forms and jet form builder
So many users have the same problem

**Comment by razkoko1** [comment]
+1

**Comment by Lucky5111** [comment]
+1

**Comment by Lucky5111** [comment]
I am planning to use WSForms.

**Comment by mehdimoradi1500** [comment]
Im in love with JetEngine 😂

**Comment by Lucky5111** [comment]
Yeah, but their form builder are kind of lackluster compared to WSforms. You are able to do woocommerce integration if you use WSforms. PS. I am able to get you some crocoblock licenses keys!

**Comment by neoset** [comment]
I join the request for integration with woocommerce, I see it essential and it is not in Jet Engine forms.

**Comment by MjHead** [comment]
Implemented as addon for JetFormBuilder (which is replacement for JetEngine forms) - https://jetformbuilder.com/addons/woocommerce-cart-checkout-action/
