### ISSUE TITLE
RECURRING EVENTS - FOR JET ENGINE CPT/META FIELDS/DATE PICKER

### ISSUE THREAD

**Issue by xBromsson** [CrocoBlock/suggestions#3745]
Description:

Add the ability to set a recurring event within jet engine meta field/ field type/date picker. This will allow our users to set up an event that displays on the front end that will populate on the dynamic calendar (daily, weekly, monthly, or yearly as needed) without the user needing to manually input the same event over and over since it is a recurring event. 

Why:

Adding this will decrease the end users workflow time when dealing with event management (a common need). Which will increase time they can devote to other tasks. Which will save them money. Which will increase value down the line all the way to Crocoblock.

**Comment by doodledude** [comment]
+1

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
