### ISSUE TITLE
JetEngine BUG - Woocommerce Meta Data Not Working With Gutenburg Listing

### ISSUE THREAD

**Issue by perks98** [CrocoBlock/suggestions#3748]
Hi, When creating a listing grid item and you add a dynamic field widget and try to use any woocommerce field, it doesn't work, which with Elementor it does.

Gutenburg View: 
![Screenshot_2](https://user-images.githubusercontent.com/55829113/127470286-93fb9918-e817-42ae-8bab-769d7d06dd17.png)

Product Category Page View: 
![Screenshot_3](https://user-images.githubusercontent.com/55829113/127470363-775d1276-b4a5-4baf-824e-1c106acbed6a.png)

Product Page (showing it has a price): 
![Screenshot_4](https://user-images.githubusercontent.com/55829113/127470420-0dab4ea1-d37d-4b37-ab00-dad4bf471f8d.png)

**Comment by UraraReika** [comment]
Hello @perks98 !

This options works when you use WC Product Query only.

**Comment by perks98** [comment]
Hi @UraraReika,

It's an odd one, it works with Elementor without needing WC Produc Query, just Gutenburg for the same field it is needed like you said. I've found a way around it without the query builder. That is by using '_price' with Source: Meta Data then use the Custom Meta field. Just thought I would flag it for review.
