### ISSUE TITLE
Show captions under image gallery grid view

### ISSUE THREAD

**Issue by qwik3r** [Crocoblock/suggestions#375]
**Please, describe the feature request, making it clear to understand.**

JetElements currently has an Image Layout Widget. In this widget is a grid view, which would be great if could show captions straight away underneath an image instead of on hover.

**Add an example of where this feature is already implemented. **

https://cl.ly/5a021337d5d9

**Comment by Floydtm** [comment]
Hi! You can use the portfolio widget to display a description below the image. http://prntscr.com/oibc0j

**Comment by qwik3r** [comment]
There's actually a problem with this widget. If you drag it in a section whatever is below it sits on top. I'm going to submit a support ticket.

**Comment by Floydtm** [comment]
@qwik3r Hi! You can describe your problem in more detail here. Our team will check everything and fix the bug. Thanks you!

**Comment by qwik3r** [comment]
When you add it in the backend it sits below the section below it: https://cl.ly/04711652cca6

**Comment by kaskad88** [comment]
@qwik3r Please tell me which WordPress theme are you using?

**Comment by qwik3r** [comment]
Astra

**Comment by kaskad88** [comment]
@qwik3r 
Thanks for your feedback.

We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support at support https://crocoblock.com/help-center/ for guidance in resolving this issue.

Thanks.
