### ISSUE TITLE
Add ability to display CCT Repeater Fields

### ISSUE THREAD

**Issue by IFTTD** [CrocoBlock/suggestions#3751]
Currently I have not found a way to use repeater fields in Custom Content Types. One can add the repeater fields as usual but when it comes to displaying them. There is no functionality to do so both in the Dynamic Repeater Widget or in creating a Listing where only Post is an option.

**Comment by drewbclark** [comment]
I also have same issue! I find the repeater field to be useless without this. Please please add CCT Repeater Field Listing Support!

**Comment by madmaxpowermx** [comment]
Joining to this petition too. Hope CCT will get an important update, it feels like an abandoned feature

**Comment by kaskad88** [comment]
Added in JetEngine v2.11.8
