### ISSUE TITLE
Ability to apply shadows to any carousel flash box product of Jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3753]
hello
It would be great if you could add a feature, so that we can shade each product carousel flash box separately. There is a reason for this feature, which I will explain below :
![Screenshot (99)](https://user-images.githubusercontent.com/77163248/127545530-b91f3362-56d7-40f6-8db8-0093668a176d.png)
As you can see in the figure above, the shadows are more in the red areas than in the green areas. This is because the shadow of each box has moved horizontally in the opposite direction.
At the moment we can not design such a thing in jet woobuilder, because the shadow is applied on two boxes.(Each shadow we apply is applied to two carousel arrow boxes.)

In fact, we need to add shadow settings to these parts : (next arrow & prev arrow)
![Screenshot (101)](https://user-images.githubusercontent.com/77163248/127582387-acfff158-6a52-4ae0-b0b0-2ad4b8f9ef49.png)

**Please add this feature, so that we can apply a shadow to each of the carousel flash boxes separately.** I really need it.
thank you

**Comment by UraraReika** [comment]
https://gyazo.com/29922cd97423322a6c68dcf89b206440 and https://i.gyazo.com/0edc5a5129ef4d96a033f99debd7f02e.png

**Comment by 79ho3ein** [comment]
thank you @UraraReika 
But I did not mean the movement of the carousel flash box. Rather, the shadow movement of the carousel box was the product:
http://i.prntscr.com/3DFykFB7SXesNZhwPvvWTg.png
Currently, we can only apply border type and border radious. (For netx & prev box). 
It would be great if you could add shadows as well. I meant exactly the shadow. this part : http://i.prntscr.com/JnEhZnqUSHKZpsThMjePqw.png
**In general, please add the box shadow feature to the next arrow and prev arrow if possible.**

thank you
