### ISSUE TITLE
JetEngine: 2.8.7 - Unable to create new or edit existing Forms

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#3754]
**Describe the bug**

One of my sites has this issue when attempting to create a new form

jet-engine-booking/{{ currentItem.hook_name }} - WP action. Perform a hook without an ability to validate form,
jet-engine-booking/filter/{{ currentItem.hook_name }} - WP filter. Perform a hook with an ability to validate form. Allows to return error message.

The site is a multisite. I haven't been able to do a deep diagnosis, there's no error in the PHP logs but I am getting a 500 error for the following: notifications_builder

- jet-engine/templates/forms/admin/notifications.php

**To Reproduce**
1. Go to JetEngine > Forms > Add New
2. Should see the error

**Expected behaviour**

**Screenshots**

https://tinyurl.com/ygl8ppr8

**Additional context**
Downgraded to 2.8.6 and was able to create forms again. I can also import. So not a major blocker.

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
