### ISSUE TITLE
Jetbooking problem on checkout dates

### ISSUE THREAD

**Issue by dariogalleno** [CrocoBlock/suggestions#3755]
Good day, I'm experiencing a problem on bookings where the check out date of booking A is the same of the checking date of booking B .
the problem I have consist in the available booking dates. In my case I booked a room for 1 night. Checkin aug5 check out aug 6. As the booking setting is per night is is correct that the 5th is marked as not available. The room still be available in4th out 5th I should be able to book it.. I can not book it as the 5th results already booked..how can configure the nightstay?
I suppose this is a basic and fundamental function for a booking plugin. In this moment my potential guests can not book a room if the checkout date is the same of the checkin date for another reservation already booked...and potentially i will not sell a room...
Hope everything is clear,
Waiting for yours 
Tks
Dario

**Comment by tfrank7** [comment]
Hi Dario,
I think you looking for this setting:
Bookings > Settings > General tab
https://tinyurl.com/yk4bgjtv

**Comment by dariogalleno** [comment]
Hi tfrank77, 
tks for your reply. I already setted "per night" option, and it works fine for the price calculation. 
the problem is that the check-in date results already booked trying to book the day before. I try to explain better sendig the availability calendar screenshot.

![image](https://user-images.githubusercontent.com/87863573/128887490-14aa1f2c-c702-4830-970b-cc2c72560b27.png)

for ex.: the room/night check in 21 check out 22 is already booked and confirmed. 
the room/night check in 20 check out 21 is available... but it's not bookable as the 21 results full..

I think that the "per night" option should consider only the day after the check in.. in my case the 22 ... 

hope I've expleinde well...
tks in advance
Dario

**Comment by tfrank7** [comment]
I see what you means.
Unfortunately i have the same problem.
So, the Guest 1's checkout's date can't be on the same day as the freshly arrived Guest 2's.
Normally I saw this solution on every booking site (half leaving/arriving days):
![booking-cal](https://user-images.githubusercontent.com/28020154/136802931-8b83fa16-67b7-41e6-af11-e373f64d2f12.png)
It can be a solution for JetBooking too.
Or, if anyone has any idea to solve this, I'm listening. :)

**Comment by jannelundin** [comment]
I have the same problem I have a small vacation appartment
Website and it is not possible to use jetbooking because of
This issue.

**Comment by trofimartya** [comment]
Facing the same issue. Can't book dates even if they are available.

**Comment by UraraReika** [comment]
Hello everyone!

In the latest release 2.5.1 we introduced new option called Allow checkout only days. If this option is checked, first day of already booked period will be available for checkout only.

If the Booking Period is Per Night, the option Allow checkout only days is added - if the option is enabled, the new logic is applied, if it is disabled, the old one https://tppr.me/zZA7Z. A label for Checkout only days has been added to the label settings https://tppr.me/BOcYD.

Example:
We have a booking from the 25th to the 26th, the 25th is off the calendar, the 26th is available - https://i.imgur.com/uyFqN0F.png. 25 is marked as Only checkout - https://i.imgur.com/6S60wkY.png (the label is controlled in the settings), while the rest of the booked days are marked as before - sold out, etc. If we start selecting the available date range BEFORE the 25th, it becomes available, the date blocking starts from the 26th - https://i.imgur.com/J4psOfd.png.  When more than one day in a row is excluded, the situation is simpler - the first day of the booked range becomes available - https://i.imgur.com/WCuk7OE.png, https://i.imgur.com/z5SVxv5.png.

**Comment by Clicktoweb** [comment]
Hi @UraraReika .. thanks for the update. I tried the new functionality but it works only for the departure day : I've made a booking for 1 week (20 to 27 of august). Other people can make a booking from the 27/08 (it works fine) but they can't make a booking from today to 20/08 (20 is unavailable, booked in my bookingtest but the check-in are in the afternoon and check-out in the morning so that no nights are lost. Is it possible to fix it? Thanks a lot


<img width="462" alt="Capture d’écran 2022-08-16 à 10 04 39" src="https://user-images.githubusercontent.com/101868369/184829653-583e35d6-691c-4bdb-8856-a1f00e416786.png">

**Comment by UraraReika** [comment]
Hello @Clicktoweb !

I have this setting enabled https://tppr.me/hIFJk. Then i made a booking like this https://tppr.me/dkwwf. Now i want to make a new booking and see this. I can start my booking from 9th of September but 5th of September still unavailable. If you select date before 5th then 5th become enable https://tppr.me/5LToy and you can select it for booking https://tppr.me/z3Gei. Perhaps this is related to your site. Please contact our support team.

Thank you!

**Comment by Clicktoweb** [comment]
@UraraReika Ah ok I understant.. You're wright, the 20/08 is available only if you choose a date before. At first sight.  it seems to be unavailable. Wouldn't it be clearer for the customer who has to book to see that on 20/09 the room is free by leaving the last date in black and not grey?
<img width="461" alt="Capture d’écran 2022-08-16 à 13 46 33" src="https://user-images.githubusercontent.com/101868369/184872840-5d8186e3-3166-43a2-add5-0ccfb733f869.png">
<img width="464" alt="Capture d’écran 2022-08-16 à 13 46 42" src="https://user-images.githubusercontent.com/101868369/184872847-a9bd42b0-b0fc-45b9-9904-f1debf80e8d8.png">

**Comment by UraraReika** [comment]
For this purpose you have label option.
