### ISSUE TITLE
Display product's variation options after click on "Select options" button at Shop Page - JetWooBuilder / JetPopup

### ISSUE THREAD

**Issue by xC4M** [CrocoBlock/suggestions#3756]
Popup allows giving customers a great experience while they are visiting our website; they can do things in less steps.
So, It'd be awesome if you please add the feature to display in a popup the product's options or variations to select.

Example in the next link: 

https://gifyu.com/image/O8Nh

**Comment by UraraReika** [comment]
This is basic quick view functionality. Please contact our support team they will help you.
