### ISSUE TITLE
UX Listing grid load more infinite scroll feedback

### ISSUE THREAD

**Issue by hNilsen90s** [CrocoBlock/suggestions#3759]
**Please, describe the feature request, making it clear to understand.**

Load more with infinite scroll needs better feedback to the visitor/customer of the site. When you are loading more content, nothing is displayed until the items are fully loaded. The grid from the Listing grid goes into a gray color, and suddenly there are more items loaded.

There should be feedback with text or icons letting the visitor know that more content is loading. This is a very important step for people who has slow internet, or if the server is located far away from the visitor.

I've already seen a huge drop in visitors buying products because they think all products are loaded.

**Comment by petranca** [comment]
https://github.com/Crocoblock/suggestions/issues/2126

**Comment by Gidsa** [comment]
I would also strongly recommend adding this feature as the UX suffers greatly without it. Users need to be aware that more posts are being loaded. The faded out posts indicator is not enough.

**Comment by tealou** [comment]
Following up on progress with this -- ability to choose the same icons/animations as Elementor page transitions would be better (too much replication as it is), but as a minimum, the ability to upload a GIF or SVG (or even Lottie) file for that feedback would be good on all Listings with Infinite Scroll.

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
