### ISSUE TITLE
Add the option to hide empty rows in JetElements Table

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#3760]
In the JetElements Table with dynamic content, add an option to hide rows with empty cells. If we don't add the dynamic content to any of the cells of the row, the row should not be shown on the front-end.
<img width="1440" alt="Screenshot 2021-07-30 at 9 05 55 PM" src="https://user-images.githubusercontent.com/88202146/127677129-c2831553-ec73-4843-99d5-2e02f8a24119.png">

The table in the above template has two empty rows with no dynamic content in them. Adding an option to hide empty rows would be a nice decision.

**Comment by Gawuww** [comment]
Added in JetElements 2.6.2
