### ISSUE TITLE
Bug in flash product navigation widget product grid (jet woobuilder)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3765]
hello
In the product grid widget, if we put the product carousel arrows in **svg** format, it is not possible to change their color. Both normal and inactive.
https://prnt.sc/1i3rnn0

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!
