### ISSUE TITLE
Thanks page in elementor canvas mode (no header or footer) jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3768]
hello
If we set the thanks page mode to elementor canvas, there is a header and footer in the editor, but it is correct on the site.
Please correct it if possible.
It should be such that if we select the canvas mode, there is no header and footer in the editor.

thank you

**Comment by 79ho3ein** [comment]
**There is also no style tab for this tab (to apply background color)**

To better understand the request, I compare the jet woobuilder thank you sheet with the 404 elementor plugin sheet ...

Thank you page in jet woobuilder :
![Screenshot (105)](https://user-images.githubusercontent.com/77163248/127854526-2be1e719-fa95-4302-9cb3-f781a620b700.png)

page 404 in elementor :
![Screenshot (106)](https://user-images.githubusercontent.com/77163248/127854887-33b686cc-ebad-400c-a047-63e9db44757c.png)

In the Style tab, no special items are required. Just changing the background color of the whole thank you sheet is enough.
Please check these items. Highly needed. 

thank you🌹

**Comment by 79ho3ein** [comment]
Thank you very much @UraraReika 🌹

**Comment by 79ho3ein** [comment]
hello dear @UraraReika, Is it possible to publish this in the next update? Please

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Templates layout now applied in Elementor editor. We will not implement style tab to our template in case we insert template to page this in not actually a page. As for the preview option the content shows correct data i don't understand needed of this option in such kind of option.

**Comment by 79ho3ein** [comment]
thank you @UraraReika🌹
Unfortunately, I did not understand exactly what you meant...
From now on, can we change the background color of the thanks page? At the moment this is not possible and we can only change the background color of the elementor section! This was a very big limitation
