### ISSUE TITLE
Image Layout height on mobile

### ISSUE THREAD

**Issue by qwik3r** [CrocoBlock/suggestions#377]
**Please, describe the feature request, making it clear to understand.**

On mobile and tablet there should be an option to adjust the image height to 100vh or percentages instead of just pixels. For example: https://cl.ly/6afea0a5baf1 the image is cut off on tablet. I can adjust the image height with the slider but not sure how that will work in all instances. It would be better to have VH as an option as well. 

**Add an example of where this feature is already implemented. **

https://cl.ly/6afea0a5baf1

**Comment by kaskad88** [comment]
Added for next version. Thanks for your report!

**Comment by qwik3r** [comment]
You rock, thank you!
