### ISSUE TITLE
⏰[Jet Engine - Forms] Stripe payment gateway and Paypal payment gateway and Woocommerce integration

### ISSUE THREAD

**Issue by neoset** [CrocoBlock/suggestions#3770]
Although I have not tested it, I know that there is a Paypal payment gateway hidden in the Jet engine forms code and it has been there for months but for some reason it has not been released.
When will we have Integration with Woocommerce, Stripe and Paypal payment gateway in the Jet Engine forms?
This would open the doors to the creation of membership sites.

Thanks for your great work.

**Comment by julianderyk** [comment]
Its not right that paypal payment haven't been released

Here are only two example
 https://crocoblock.com/blog/best-ways-to-set-up-the-payment-gateway-system/

https://crocoblock.com/blog/building-membership-site-with-jetengine/

**Comment by Lucky5111** [comment]
Seriously they need to add this. This is the thing stopping most people from buying jet engine.

**Comment by neoset** [comment]
They should put the integration with Woocommerce in the forms of Jet engine, it is something really necessary.

**Comment by mehdimoradi1500** [comment]
I suggest this feature in #3742 but unfortunately no one pay attention 😢, its so important to integrate JetEngine's form with woocommerce 
Please consider this issue 
@UraraReika

**Comment by khandiz** [comment]
We also need Stripe integration for Crocoblocs. Both for WooCommerce and for membership

**Comment by MjHead** [comment]
Implemented as addons for JetFormBuilder (which is replacement for JetEngine forms) - https://jetformbuilder.com/addons/woocommerce-cart-checkout-action/, https://jetformbuilder.com/addons/stripe-payments/
