### ISSUE TITLE
Load More / Infinite Scrolling for products in JetWooBuilder

### ISSUE THREAD

**Issue by Theo789595** [CrocoBlock/suggestions#3771]
**Ajax Load More** and **Infinite Scrolling** functions are a must for modern ecommerce sites.

After trying plugins and code customization for weeks i still **haven't found a way to make the function work** properly with or without jetwoobuilder/crocoblock. 

The only decent plugin available for this kind of option is **BeRocket Load More** and only works if you display your products without the use of page builders & of course Crocoblock or if you display products using woocommerce shortcode (working with issues too). Also **the plugin doesn't work** with any kind of filtering, when you use filters to show products the plugin just doesn't work and after being asked they stated in their support that they won't do anything about it.

So, why would this simple function which is so **useful** not be **available "working properly" anywhere in wordpress**!

**It is kind of simple:**
**1.** Have an option between load more button & infinite scrolling.
**2.** Make the function compatible with filtering and sorting changes (jetsmartfilters or generally).

Of course most people would want this compatible with both jetwoobuilder product widgets and  woocommerce shortcode.

What do you think guys? Do you think this is a usefull function? Any suggestions?

**Comment by 79ho3ein** [comment]
hello @Theo789595
Yes, "Load more" is a very important feature of the product grid widget. This request was previously registered in #2683.
This is definitely on the developers' roadmap. I hope this feature will be added to the plugin soon, Many users are looking for this feature.

**Comment by UraraReika** [comment]
I merged this issue with #2683, which is on the same subject so we could deal with it more efficiently.
