### ISSUE TITLE
Report a bug and a suggestion for the jet woobuilder plugin. please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3774]
hello
First I report a bug that occurs after applying the discount code to the cart. **The problem is that when we activate the discount code in the shopping cart, the price units are transferred to the right of the price.**
To better understand the problem, please watch the video below :
https://drive.google.com/file/d/132iq3NaXfMDmkkou7A7bloGdOqp9TCK0/view?usp=sharing
I do not know if this problem is only in RTL or not ...

**And one suggestion ...**

In the shopping cart and checkout page of the jet woobuilder plugin, after applying the coupon, a button will appear to delete the discount code, and unfortunately it is not possible to personalize it.
**Please add this feature so we can edit this option. Of course, editing is enough to change the color (normal and hover).**
https://prnt.sc/1in8f5e
**Finally, I emphasize that this item is in both the shopping cart and the checkout page.**

thank  you

**Comment by UraraReika** [comment]
First this isn't problem of our widget, tested on default template with default theme.
Added some additional link color controls.

**Comment by 79ho3ein** [comment]
thank you @UraraReika 
The bug I reported in this issue is in hello elementor theme.
