### ISSUE TITLE
JetEngine: More URL/slug options

### ISSUE THREAD

**Issue by Crownedpride** [CrocoBlock/suggestions#3775]
I'd like to suggest a feature for custom post-type URLs.

Currently, when you've created a custom post type and added content to that post type, then the URL will look like this:
https://domain.com/custom-post-type/single-post/

However, what if we add some taxonomies with a hierarchy? The URL then remains the same, even though when you add breadcrumbs on that single post, it'll show the custom post type and the taxonomy hierarchy. 

So let's keep https://domain.com/ as our example domain.
Custom post type name: Companies.
Taxonomy name: Category.
Main category: Tech.
Subcategory: Phones.
How I imagine the URL would be: https://domain.com/companies/tech/phones/single-post/.

It's already possible with JetBlocks as it asks what path to follow for the breadcrumbs which is why I was surprised to see the limitations of custom post-type URLs.

Hopefully, I was able to explain it clear enough, if not then feel free to ask!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
Now you can look for a custom solution for customizing [permalinks](https://wordpress.org/plugins/search/permalink/). Thanks!

**Comment by kochhase** [comment]
Hi Floyd,
do you have contact with 
https://permalinkmanager.pro/docs/#faq
because, we are using WPML as well. And there is no solution right now.
thanks
