### ISSUE TITLE
Display the number of available results

### ISSUE THREAD

**Issue by Topicimes** [CrocoBlock/suggestions#3783]
Hello to all,

I am currently developing a website such as Cardealer, for activities. I would like to display a text on the catalog page (eg: https://demo.crocoblock.com/cardealer/catalog/) like this for example: 23 results available according to your filters.

Thank you in advance for your feedback and good luck.

**Comment by Crownedpride** [comment]
Go to your JetFilter settings, go to "Indexer Settings" and enable the post types you are trying to filter. Next, you go to your filter widget, underneath "Content" there's now a new tab called "Indexer Options" where you can apply the indexer and show a counter.  https://prnt.sc/1j1x0id.

**Comment by Topicimes** [comment]
> Go to your JetFilter settings, go to "Indexer Settings" and enable the post types you are trying to filter. Next, you go to your filter widget, underneath "Content" there's now a new tab called "Indexer Options" where you can apply the indexer and show a counter.

Hello,

We have misunderstood each other. I have indeed already applied indexing to my filters. I am talking about a global message, which does not concern any specific filter, but only according to all the selected filters, the number of list still available.

Is it clearer for you?

**Comment by MjHead** [comment]
@Louisjdv Hi! If you build query for cars listing with new Query Builder, you can use `Query Results Count` dynamic tag

**Comment by jamsheehan** [comment]
Here is how you achieve this: 

https://crocoblock.com/knowledge-base/articles/jetengine-query-builder-sql-query-type/

Once you build your query, you can then select it (note I'm using a button here, but any element that supports dynamic text can utilise this): 

![image](https://user-images.githubusercontent.com/223342/128248951-c62f409b-da7b-4398-9701-6532c4d9485f.png)
![image](https://user-images.githubusercontent.com/223342/128249131-50f57e8a-2841-4fd8-94dd-68c0a9d1ec01.png)

You can use the advanced field then in the before and after to add whatever text you want.

**Comment by Topicimes** [comment]
> Here is how you achieve this:
> 
> https://crocoblock.com/knowledge-base/articles/jetengine-query-builder-sql-query-type/
> 
> Once you build your query, you can then select it (note I'm using a button here, but any element that supports dynamic text can utilise this):
> 
> ![image](https://user-images.githubusercontent.com/223342/128248951-c62f409b-da7b-4398-9701-6532c4d9485f.png)
> ![image](https://user-images.githubusercontent.com/223342/128249131-50f57e8a-2841-4fd8-94dd-68c0a9d1ec01.png)
> 
> You can use the advanced field then in the before and after to add whatever text you want.

Thank you very much for all these precisions. So I tried to build my Query but I have a lot of trouble.

Could you provide me with screenshots of your back end, especially to know which table to select, etc.?

**Comment by Topicimes** [comment]
With the help of one of their agents, I finally succeeded. Thank you very much for your answers.

Have a good day, and above all, take care of yourself
