### ISSUE TITLE
Jet engine/Jet formbuilder + woocommerce

### ISSUE THREAD

**Issue by Lucky5111** [CrocoBlock/suggestions#3784]
This will be a godsend for directory sites with the post-expiration plugin from crocoblock dev.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.
