### ISSUE TITLE
JetElements Table for JetEngine CustomContentType

### ISSUE THREAD

**Issue by dayoherrera** [CrocoBlock/suggestions#3789]
Hello, I am using the JetElements “Table” widget to show JetEngine “custom-content-type” DATA, but I cannot get the table body to take dynamic data even when I choose the Custom Content Type Field.

If I write text, it works. Also, it worked when I added the Table element in a Listing, but it repeats the header for each record. 

![Screen Shot 2021-08-05 at 3 09 56 PM](https://user-images.githubusercontent.com/33962205/128421707-5523205d-e197-4be5-be0a-aa29be53f3a6.png)

What am I doing wrong? I want to show the CCT in the JetElements Table. 

![image_2021-08-05_17-29-19 (1)](https://user-images.githubusercontent.com/33962205/128423784-2e502822-22b8-4883-bd46-05cbc82ea3a4.png)

Is this an error or a new feature request?

Thanks

**Comment by MjHead** [comment]
@dayoherrera Hi! This feature will be added as separate module with JetEngine 2.9.0. More details here - https://github.com/Crocoblock/suggestions/issues/3803
