### ISSUE TITLE
Add 'Filter field output' in Map Listing widget - JetEngine

### ISSUE THREAD

**Issue by vmavrikios** [CrocoBlock/suggestions#3790]
In short ..there is no option in Map Listing widget to display eg. the price of a real estate property in the following format dynamically:
100,000€
The best you get is this format:
100,000.00€ ..but these 2 zeros at the end are not needed and never used in big numbers, so they just take up more space in a marker that displays the price.

In the contrary ..in Dynamic Field widget there is such an option, by enabling the 'Filter field output' and in the number callback you can set decimal and thousands separator and decimal points.
Like here:
https://gyazo.com/28416402a01f6451f26d6ea02245c815
Which you cannot do in Map Listing widget for some reason.

The problem with this is when designing a custom website with tools that are meant for this reason, you need to have consistency - in my case to display the same price format throughout the website, using multiple Crocoblock widgets. 

In the following example the properties listing on the left has the required price format (using the Dynamic Field widget).
But the map listing (using the Map Listing widget) on the right shows 2 decimal zeros at the end of the price that cannot be removed if a callback is used.
If the callback 'format number' is not used, then the thousands separator is also omitted.
https://gyazo.com/265d0dff497f98c3d0262b7365fb5f41

The conclusion is that the Map Listing widget does not provide the option to customise the price format like other JetEngine widgets/modules.
If the purpose of the widget is to be used in combination with other JetEngine modules to create complex websites (like directories with map listings) then Price format is an essential detail to display consistently in the same format. 

The website example with map listing trying to achieve this:
https://home-is-crete.com/residential/

I hope the above are clearly described and this issue is addressed and fixed soon.

Kind thanks to the dev team

**Comment by kaskad88** [comment]
Added for the next version( 2.8.9 ). Thanks for your report!
