### ISSUE TITLE
Error ajax jetfilter with yith request.

### ISSUE THREAD

**Issue by IngerGarrido** [CrocoBlock/suggestions#3794]
I have a site where I use jetsmart filter ajax and yith request, when loading the page everything perfect (image 1), but when selecting the ajax filter button yith request broken, it remains as text (image 2).

imagen 1
![image 1](https://user-images.githubusercontent.com/17303550/128581644-6b84c7c0-662f-4959-bcd9-29dc7fc639b1.jpg)

imagen 2
![image 2](https://user-images.githubusercontent.com/17303550/128581645-d8050917-a0da-4288-ba88-60d6491bc6f9.jpg)

The same thing happened to me once with yith compare, and you guys released an update and it was fixed.

**Comment by UraraReika** [comment]
Hello @IngerGarrido !

This yith request and yith compare probably rendered with the help of js, so in this case you need to trigger it one again after ajax filtering using this document trigger `jet-filter-content-rendered` from JetSmartFilters.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
