### ISSUE TITLE
JetEngine: do_shortcode for the dynamic repeater widget

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#3795]
Hello)

I output some data using the repeater field and the dynamic repeater widget. This data may contain shortcodes added by me. However, this widget does not handle them. The Dynamic Field widget has a do_shortcode, but what about here? Maybe there is some kind of hook, like `add_filter('dynamic_repeater_widget', 'do_shortcode');` ? I didn't find it on the web(

**Comment by MjHead** [comment]
Hi! We'll add some more advanced solution with one of the next updates. As for now you can try to do it in this way:

```
add_filter( 'jet-engine/listings/dynamic-repeater/pre-get-saved', function( $result, $settings ) {

	$source         = isset( $settings['dynamic_field_source'] ) ? $settings['dynamic_field_source'] : false;
	$object_context = isset( $settings['object_context'] ) ? $settings['object_context'] : false;

	/**
	 * Replace my_field with your actual Repeater meta field key
	 */
	if ( 'my_field' !== $source ) {
		return $result;
	}

	$result = jet_engine()->listings->data->get_meta(
		$source,
		jet_engine()->listings->data->get_object_by_context( $object_context )
	);

	if ( ! empty( $result ) ) {

		$applied = array();

		foreach ( $result as $item ) {
			/**
			 * Replace child_field with your actual repeater child field key
			 */
			$item['child_field'] = do_shortcode( $item['child_field'] );
			$applied[] = $item;
		}

		$result = $applied;

	}

	return $result;

}, 10, 2 );
```

Please note, this code sample is only example to demonstrate how it could be implemented, so please try it in the dev environment before go live.

**Comment by serg-pervushin** [comment]
Thanks!

**Comment by DamascinoPS** [comment]
Hi 
did you add some more advanced solution yet

**Comment by pauserratgutierrez** [comment]
> Hi! We'll add some more advanced solution with one of the next updates. As for now you can try to do it in this way:
> 
> ```
> add_filter( 'jet-engine/listings/dynamic-repeater/pre-get-saved', function( $result, $settings ) {
> 
> 	$source         = isset( $settings['dynamic_field_source'] ) ? $settings['dynamic_field_source'] : false;
> 	$object_context = isset( $settings['object_context'] ) ? $settings['object_context'] : false;
> 
> 	/**
> 	 * Replace my_field with your actual Repeater meta field key
> 	 */
> 	if ( 'my_field' !== $source ) {
> 		return $result;
> 	}
> 
> 	$result = jet_engine()->listings->data->get_meta(
> 		$source,
> 		jet_engine()->listings->data->get_object_by_context( $object_context )
> 	);
> 
> 	if ( ! empty( $result ) ) {
> 
> 		$applied = array();
> 
> 		foreach ( $result as $item ) {
> 			/**
> 			 * Replace child_field with your actual repeater child field key
> 			 */
> 			$item['child_field'] = do_shortcode( $item['child_field'] );
> 			$applied[] = $item;
> 		}
> 
> 		$result = $applied;
> 
> 	}
> 
> 	return $result;
> 
> }, 10, 2 );
> ```
> 
> Please note, this code sample is only example to demonstrate how it could be implemented, so please try it in the dev environment before go live.

Is this added? I can't use dynamic visibility with checkbox inside repeaters
