### ISSUE TITLE
infinite scroll for infinite scroll

### ISSUE THREAD

**Issue by zivit-drori** [CrocoBlock/suggestions#3797]
Hi,
I'm using JetWooBuilder with JetSmartFilters
and I'm trying to use the code that is in the attached file for infinite scroll
with no success
It's most important for my project to have this option
[for-elementor.txt](https://github.com/Crocoblock/suggestions/files/6949402/for-elementor.txt)

https://samplive.co.il/product-category/single-samples/

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
