### ISSUE TITLE
Table: Allow adjusting of cell data by column or individual cell

### ISSUE THREAD

**Issue by JamesDandy** [Crocoblock/suggestions#380]
In the JetElements Table widget, there is no ability to allow for the columns in the table body to be aligned individually. The Alignment in the Style section affects all table columns and thus prevents proper formatting of row labels (typically left justified) and the other data in the rows (typically mixed between left, right and center). 

A normal example is that the first column has row labels which would be left justified and rows containing numbers to the right of the first column would be right justified. As it works now, the only justification option affects all rows.

Even trying to use html in the table body contents text field doesn't work with alignment....html for colors does work so I can't understand why it's important to block or to not account for alignment.

Alignment does not work
<p align="right">This is some text in a paragraph</p>

Color does work
<p style="color: green">This is some text in a paragraph</p>

**Comment by Floydtm** [comment]
Hi. Unfortunately, we cannot embed this in a table widget. For all this time there were no calls with a stack request. You can do this with custom CSS.
