### ISSUE TITLE
Allow to open a Popup window using Advanced carousel plugin

### ISSUE THREAD

**Issue by nbarlevav** [CrocoBlock/suggestions#3801]
When pressing a button on a slide it will be great to allow to open the destination URL in a popup, rather then in a full window...
Thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
