### ISSUE TITLE
Dynamic Field Widget: Please add "Last updated / modified" date

### ISSUE THREAD

**Issue by jarahner** [CrocoBlock/suggestions#3804]
Currently it's only possible to display the date created in a dynamic field widget. Please also add the last updated / last modified date as well. 

I guess it's already implemented in the post info widget but I need to display the human readable time difference between now and the last updated date which is only possible in the Dynamic Field widget

**Comment by kaskad88** [comment]
Added for the next version. Thanks for your report!
