### ISSUE TITLE
Enable Add More Custom Post Type in JetAppointment

### ISSUE THREAD

**Issue by Dinorexasia** [CrocoBlock/suggestions#3808]
Hi, I would like to request the features on Jetappointment to allow add more custom post types. The Current setting only allows us to add services & providers only (Limited to 2 only)

If it is possible to allow us to add more custom post types it would be better & more flexible. 
Example to add services, providers & branches, etc. 

![image](https://user-images.githubusercontent.com/88306192/128803338-8d514f6e-3eca-4157-ba7e-2656e086cdcb.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
