### ISSUE TITLE
Enable to add dynamic email in the "mail to" session in post action of JetAppointment  

### ISSUE THREAD

**Issue by Dinorexasia** [CrocoBlock/suggestions#3809]
Hi I would like to request to enable us to add dynamic email in the "mail to" session in post-action of JetAppointment form. 

For example, we can put a dynamic email in the column mail to: "provider_email" instead of a specific email address. This can allow us to send the appointment email notification to the respective provider. 

![image](https://user-images.githubusercontent.com/88306192/128803883-4e0c93e6-f9f0-41c5-9229-7f270dc2981c.png)

**Comment by Floydtm** [comment]
Hi! Add a meta field for the single provider https://prnt.sc/1rloxsa Write your desired email address in this meta field https://prnt.sc/1rlp04g In the form, add a hidden field that will receive this email https://prnt.sc/1rlp5ux  Specify the form field in the notification https://prnt.sc/1rlp8i7
