### ISSUE TITLE
Tablepress Shortcodes do not work in a JetPopup window

### ISSUE THREAD

**Issue by JamesDandy** [CrocoBlock/suggestions#381]
When using the Shortcode widget on a JetPopup window and entering the shortcode to a TablePress table, the table does not display. The shortcode is displayed instead, but not the table associated with it.

I placed the shortcode to my footer in the popup and that works but not a TablePress shortcode. I've even used a complete Elementor page's shortcode and that works, but none of the TablePress shortcodes work even though these TablePress shortcodes work on other parts of the site.

**Comment by JamesDandy** [comment]
Here is an example: 
![image](https://user-images.githubusercontent.com/40547617/61666248-02ea4680-aca5-11e9-9192-67c835341277.png)

**Comment by Floydtm** [comment]
@JamesDandy Hi! For the shortcode to work correctly, you must disable the [Loading content with Ajax](http://prntscr.com/oismq0) option.
