### ISSUE TITLE
Map distance

### ISSUE THREAD

**Issue by DesignByFloor** [CrocoBlock/suggestions#3810]
Is it possible to filter the map listing of crocoblock by distance?
Visitors must be able to enter an address and then indicate the number of km via a range filter.

**Comment by stasonua0** [comment]
+1

**Comment by adelapuentep** [comment]
+1
Not only by entering an address but by the widget asking for permission to allow to access to location so it grabs it automatically.

**Comment by belikebrahma** [comment]
+1

**Comment by belikebrahma** [comment]
Fetch Live location, is a must-have feature for a map listing plugin.

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
