### ISSUE TITLE
JetEngine dynamic gallery slider hover icon not displaying

### ISSUE THREAD

**Issue by GDUpson** [CrocoBlock/suggestions#3812]
The image hover icon on the JetEngine gallery slider is not showing.

**Comment by kaskad88** [comment]
Hi @GDUpson. Try enable this option https://prnt.sc/1mq9ghg

**Comment by GDUpson** [comment]
> Hi @GDUpson. Try enable this option https://prnt.sc/1mq9ghg

@kaskad88 Unfortunately this didn't work :(

**Comment by kaskad88** [comment]
@GDUpson Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue.
Thanks.
