### ISSUE TITLE
Query Builder Enabled Distinct or Group By in Module Builder

### ISSUE THREAD

**Issue by angelitodiaz1** [CrocoBlock/suggestions#3814]
Hello, I need to integrate in a query made with Query Builder the ability to make a Distinct or a Group By Id. I made a query and it brings me duplicate data. I am taking the taxonomies of some Posts to show this data in a list. I did the whole walk building the query and I can't do the Distinct or Group By. Is there any solution?

For example replicate this query:

SELECT DISTINCT(B.meta_key) 
FROM `wp_posts` A
INNER JOIN `wp_postmeta` B
ON A.ID = B.post_id
WHERE A.post_type = 'profesiones' 
AND B.meta_key = 'urgencias'
AND B.meta_value = 'Si'

![Screenshot_2](https://user-images.githubusercontent.com/6534435/128964328-0484de10-a664-4adf-a62f-336e34455ccc.jpg)

**Comment by MjHead** [comment]
Hi! This feature will be added with JetEngine 2.9.0, more details here - https://github.com/Crocoblock/suggestions/issues/3803. Also with 2.9.0 will be added one more tiny feature which will can help you. Is `Advanced mode` for SQL query, in this mode you'll be able paste SQL query manually. You can test this functionality in 2.9.0 beta version (available for download in your account). If you'll have any notes about this functionality, you can left it with comments in this issue - https://github.com/Crocoblock/suggestions/issues/3803

**Comment by angelitodiaz1** [comment]
Thx. I don´t understand how to make SQL Queryin Mode Advance. Not Working.

My example:

SELECT DISTINCT(E.name)
FROM posts as A
INNER JOIN postmeta as B
ON A.ID = B.post_id
INNER JOIN term_relationships as C
ON C.object_id = A.ID
INNER JOIN term_taxonomy as D
ON D.term_taxonomy_id = C.term_taxonomy_id
INNER JOIN terms as E
ON D.term_id = E.term_id
WHERE A.post_type = 'profesionales' 
AND B.meta_key = 'urgencias_24_cpt'
AND B.meta_value = 'a:1:{i:0;s:2:"Si";}'
GROUP BY A.ID


![Screenshot_2](https://user-images.githubusercontent.com/6534435/129078278-455e35d1-bca6-4c19-9be5-64a3e3c50e33.png)

Thx helpme.

**Comment by MjHead** [comment]
@angelitodiaz1 Tables in WP database goes with unique prefix (by default its wp_, but may be any other string) - http://prntscr.com/1nb0qil You need to put tables into query with this unique prefix, for example 
`
SELECT DISTINCT(E.name)
FROM wp_posts as A
...
`

**Comment by angelitodiaz1** [comment]
Hi MjHead.

Uhmm. But not working.  I set my script query normally, and not working. See:

My Script:

SELECT DISTINCT(DDG4rge_terms.name)
FROM DDG4rge_posts
INNER JOIN DDG4rge_postmeta
ON DDG4rge_posts.ID = DDG4rge_postmeta.post_id
INNER JOIN DDG4rge_term_relationships
ON DDG4rge_term_relationships.object_id = DDG4rge_posts.ID
INNER JOIN DDG4rge_term_taxonomy
ON DDG4rge_term_taxonomy.term_taxonomy_id = DDG4rge_term_relationships.term_taxonomy_id
INNER JOIN DDG4rge_terms
ON DDG4rge_term_taxonomy.term_id = DDG4rge_terms.term_id
WHERE DDG4rge_posts.post_type = 'profesionales' 
AND DDG4rge_postmeta.meta_key = 'urgencias_24_cpt'
AND DDG4rge_postmeta.meta_value = 'a:1:{i:0;s:2:"Si";}'
GROUP BY DDG4rge_posts.ID


And here the screens:

![1](https://user-images.githubusercontent.com/6534435/129211046-e2368efc-d883-431f-b18c-453dc7585859.png)
![2](https://user-images.githubusercontent.com/6534435/129211051-1435af40-0020-49d7-ad79-7c9b74075b51.png)
![3](https://user-images.githubusercontent.com/6534435/129211059-9a9128e6-3e64-467a-9fc2-913b7d747f3a.png)
![4](https://user-images.githubusercontent.com/6534435/129211162-90cbc102-6964-4ec5-9524-804a2f3f7bdb.png)


What's wrong?

**Comment by MjHead** [comment]
I tested your query on my installation, just changed these values according my data:
![image](https://user-images.githubusercontent.com/4987981/129218733-9a8ceb5f-4a41-415e-a911-6e00b71ddcdc.png)
And all works fine for me:
![image](https://user-images.githubusercontent.com/4987981/129219113-0a3b2916-0bda-415b-a777-6889db40b921.png)
So please try to check your conditions, maybe use something simpler to test whole query

**Comment by angelitodiaz1** [comment]
Thx.

I check again but is not working.

I detect that the issue is when  I use clause with data type LONGTEXT  in the column´s database.  Without this line, all work well:  

 AND DDG4rge_postmeta.meta_value LIKE '%a:1:{i:0;s:2:"Si";}%'.

Here my code:

SELECT DISTINCT(
    DDG4rge_terms.name
)
FROM DDG4rge_posts
INNER JOIN DDG4rge_postmeta ON DDG4rge_posts.ID = DDG4rge_postmeta.post_id
INNER JOIN DDG4rge_term_relationships ON DDG4rge_term_relationships.object_id = DDG4rge_posts.ID
INNER JOIN DDG4rge_term_taxonomy ON DDG4rge_term_taxonomy.term_taxonomy_id = DDG4rge_term_relationships.term_taxonomy_id
INNER JOIN DDG4rge_terms ON DDG4rge_term_taxonomy.term_id = DDG4rge_terms.term_id
WHERE DDG4rge_posts.post_type = 'profesionales' 
AND DDG4rge_postmeta.meta_key = 'urgencias_24_cpt'
AND DDG4rge_postmeta.meta_value LIKE '%a:1:{i:0;s:2:"Si";}%'
GROUP BY DDG4rge_posts.ID

I tested that script in PHPMYADMIN and work success.

![Screenshot_1](https://user-images.githubusercontent.com/6534435/129291341-6ad27707-a3b5-4d21-9f15-5887ddbfdae2.png)
![Screenshot_2](https://user-images.githubusercontent.com/6534435/129291345-00266858-d1b4-4d52-8568-01d990f2a220.png)

![Screenshot_3](https://user-images.githubusercontent.com/6534435/129291601-0d9d0e0d-724b-4d0b-950f-c45d4af88631.png)

I don´t know what do to fix.

**Comment by MjHead** [comment]
@angelitodiaz1 Thanks for the detailed info, looks like I found the problem. Could you please download new beta version from your Crocoblock account, reinstall and try with it?

**Comment by angelitodiaz1** [comment]
Hi.

I download Beta3 and reinstall.  But, I check again and not working.

My tests:

Test A:
+++++
SELECT DISTINCT(
    DDG4rge_terms.name
)
FROM DDG4rge_posts
INNER JOIN DDG4rge_postmeta ON DDG4rge_posts.ID = DDG4rge_postmeta.post_id
INNER JOIN DDG4rge_term_relationships ON DDG4rge_term_relationships.object_id = DDG4rge_posts.ID
INNER JOIN DDG4rge_term_taxonomy ON DDG4rge_term_taxonomy.term_taxonomy_id = DDG4rge_term_relationships.term_taxonomy_id
INNER JOIN DDG4rge_terms ON DDG4rge_term_taxonomy.term_id = DDG4rge_terms.term_id
WHERE DDG4rge_posts.post_type = 'profesionales' 
AND DDG4rge_postmeta.meta_key = 'urgencias_24_cpt'
AND DDG4rge_postmeta.meta_value = 'a:1:{i:0;s:2:"Si";}'
GROUP BY DDG4rge_posts.ID


Test B ( using {prefix} )
+++++++++++++++

SELECT DISTINCT(
    {prefix}terms.name
)
FROM {prefix}posts
INNER JOIN {prefix}postmeta ON {prefix}posts.ID = {prefix}postmeta.post_id
INNER JOIN {prefix}term_relationships ON {prefix}term_relationships.object_id = {prefix}posts.ID
INNER JOIN {prefix}term_taxonomy ON {prefix}term_taxonomy.term_taxonomy_id = {prefix}term_relationships.term_taxonomy_id
INNER JOIN {prefix}terms ON {prefix}term_taxonomy.term_id = {prefix}terms.term_id
WHERE {prefix}posts.post_type = 'profesionales' 
AND {prefix}postmeta.meta_key = 'urgencias_24_cpt'
AND {prefix}postmeta.meta_value = 'a:1:{i:0;s:2:"Si";}'
GROUP BY {prefix}posts.ID

Test C
++++
SELECT *
FROM {prefix}posts


In all tests show the issue  "La respuesta no es una respuesta JSON valida": 

![Screenshot_4](https://user-images.githubusercontent.com/6534435/129392122-84f3bcfa-e9fd-4c8f-9d68-dd553099ff25.png)
![Screenshot_5](https://user-images.githubusercontent.com/6534435/129392128-d3b6e64e-8c38-4711-8e53-a0fccccbd607.png)

Thx.

**Comment by MjHead** [comment]
Sorry for the delay, I'll check it one more time

**Comment by MjHead** [comment]
It was a small bug. Sorry for the inconvenience, could you please try to download and re-install beta 3 from your account

**Comment by angelitodiaz1** [comment]
Thx. I did already it, and working but only in side Query builder form. When I try to catch values in the front fail or I don´t know how to show it.

Here my screen.

![Screenshot_1](https://user-images.githubusercontent.com/6534435/129588491-2c45b3ea-dabc-43a8-ae21-dbba3e05bb76.jpg)

![Screenshot_4](https://user-images.githubusercontent.com/6534435/129588524-a87b9a93-d795-4bf0-af5e-82bffc184539.jpg)

I don´t understand what is failed.

thx.

**Comment by angelitodiaz1** [comment]
Sorry, I already it resolve.  Only change widget by Dynamic Field and I did use it option Post/Term with output Term Name.

Thanks.

+++++

By the way I detect that Module Query Builder in the backend form not support JOIN by other tables of database, working only with Current Table.  That feature is really important.  Please can you incorporated?... Jajaja. thansk so much.

![Screenshot_6](https://user-images.githubusercontent.com/6534435/129590716-2ca3c6b7-2363-49f5-a1d9-bfcbcc9ed361.jpg)

**Comment by moragon87** [comment]
I tried work with different databases too and I can't do it. Please will be fantastic to do it. Thank you!!!
