### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by ofmarconi** [CrocoBlock/suggestions#3815]
Hello
Is it possible for the Rating to be the category and not of the product?
I work with unique products, each product is a piece (crystals).

But they are within categories, I would like the evaluations to be shared with all the products of that category.
thank you!

My site: https://itacrystals.com/product-category/crystals/faceted-gems/

**Comment by UraraReika** [comment]
Thanks for the feedback.
 Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
