### ISSUE TITLE
Bug Query Builder - Custom SQL Query

### ISSUE THREAD

**Issue by angelitodiaz1** [CrocoBlock/suggestions#3818]
I don´t understand how to make SQL Query in Mode Advance. Not Working.

My example:

SELECT DISTINCT(E.name)
FROM posts as A
INNER JOIN postmeta as B
ON A.ID = B.post_id
INNER JOIN term_relationships as C
ON C.object_id = A.ID
INNER JOIN term_taxonomy as D
ON D.term_taxonomy_id = C.term_taxonomy_id
INNER JOIN terms as E
ON D.term_id = E.term_id
WHERE A.post_type = 'profesionales'
AND B.meta_key = 'urgencias_24_cpt'
AND B.meta_value = 'a:1:{i:0;s:2:"Si";}'
GROUP BY A.ID

![Screenshot_2](https://user-images.githubusercontent.com/6534435/129093215-72cdfe72-70ea-4ff5-b5e2-831f7ef31594.png)

Please, helpme.

**Comment by MjHead** [comment]
Replied here - https://github.com/Crocoblock/suggestions/issues/3814
