### ISSUE TITLE
Typo in Jet-Theme

### ISSUE THREAD

**Issue by mustafamohsen** [CrocoBlock/suggestions#382]
**Describe the bug**
A simple typo in Jet-Theme. The word automatic**c**ally has an extra **c**

**To Reproduce**

1. Go to Jet-Theme
2. Click **Themes** tab
3. Scroll down to **Enable automatic backup** section where you'll fine the word in the description

**Expected behavior**
Correctly display the word as **automatically**

**Screenshots**
![image](https://user-images.githubusercontent.com/29289923/61733192-837d7580-ad7f-11e9-929c-61eef9121c2f.png)

**Version**
JetTheme 1.1.11

**Comment by kaskad88** [comment]
Fixed for next version ( 1.1.12 ). 
Thanks for your report!
