### ISSUE TITLE
Custom JS

### ISSUE THREAD

**Issue by lipob** [CrocoBlock/suggestions#3820]
Hi.

I need to add some custom js code to limit the number of images shown in a gallery placed into a Listing. That listing is shown in a lightbox of the Map Listings.

I tried by adding the code into a custom js file, and also using an HTML widget inside the listing, but it's no making effect.

How can I achieve that? Is there a feature to do that?

Thanks and regards.

Leopoldo

**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by lipob** [comment]
Hi Floyd. Thanks for your answer. 
Fortunately I could resolve it with custom JS. 
Crocoblock plugins are great! Thank you.
