### ISSUE TITLE
Using ACF or Custom Metafield from JetEngine for JetWooBuilder

### ISSUE THREAD

**Issue by andeeshmehdi** [CrocoBlock/suggestions#3821]
It is currently not possible to use a dynamic field from ACF or JetEngine in a JetWooBuilder template. I want to display some custom fields (product info) from my products on Product Archive / Shop / Single Product pages but it is currently not possible to do so. Elementor Pro supports dynamic content within it's WooCommerce pages but JetWoo doesn't.

**Comment by UraraReika** [comment]
Hello @andeeshmehdi !

JetWooBuilder templates support dynamic content functionality. If you have some difficulties please contact our support  team.
