### ISSUE TITLE
Apostrophes in Glossaries section cause a \ to be generated in Field Names

### ISSUE THREAD

**Issue by zalahmar** [CrocoBlock/suggestions#3822]
**Describe the bug**
If you create a new field in a glossary that contains an apostrophe ' the field will get renamed after you save to include a \ before the '. Furthermore, if you make any changes to any field in a glossary that has a field entry that contains a ', additional \\\\\ will be added prior to the ' even though you are not editing the field with the apostrophe.

**To Reproduce**
1. Go to Glossaries
2. Create a new field in an existing glossary or create a new glossary and add a new field.
3. In the field name add something with an apostrophe, for example, Marvel's Spider-Man. Save the field and refresh.
4. Upon refreshing you will see the field is now renamed to Marvel\'s Spider-Man.
5. Make a change to the glossary by adding a new field. Go back and check the Marvel\'s Spider-Man entry and you'll notice it has added additional \\\\ before the apostrophe. 

**Expected behavior**
This should not happen. It's clearly a bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/88862118/129281900-98636ee4-1324-4015-87a9-52ac3b559ba4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 92.0.4515.131

This causes a serious issue as creating a field with an apostrophe is impossible and any new field added just makes the problem worse by adding new \\\\\ to the field name.

**Comment by MjHead** [comment]
Fixed with 2.8.9 update
