### ISSUE TITLE
Make listing item clickable - Jet Engine

### ISSUE THREAD

**Issue by DIntriglia** [CrocoBlock/suggestions#3823]
**Describe the bug**
There is no way to select a ACF field to use when trying to Make listing item clickable via the Listing settings panel. You can select ACF, but can not select a specific ACF field.

**To Reproduce**
1. Go to a listing
2. Click on setting in bottom left
3. Turn on Make listing item clickable
4. Select ACF
5. Observer there is no way to select an ACF URL/Attachment field.

**Expected behavior**
Similar to the dynamic content buttons, I should be able to click ACF field, and then click the wrench to configure which field.

**Screenshots**
![image](https://user-images.githubusercontent.com/1638530/129415161-c1d95f2d-85ff-4e40-bd28-62819d609164.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser: Chrome
 - Version: 92

**Comment by kaskad88** [comment]
Fixed in JetEngine 2.9.0. Feel free to update!

**Comment by DIntriglia** [comment]
Confirmed this issue is now fixed. Thank you!
