### ISSUE TITLE
[JETENGINE] add the possibility to insert templates when no content exists/found

### ISSUE THREAD

**Issue by saltkinmedia** [CrocoBlock/suggestions#3825]
add the possibility to insert templates when no content exists/found.

For example:
On the listings grid, when there's no content found or isn't exist. It could have the possibility of adding a template instead of only show a message.
![Captura de ecrã 2021-08-14 182339](https://user-images.githubusercontent.com/67977248/129455409-8c1d8999-6f87-4dd0-96fb-22a89b10bd0c.png)

**Comment by julianderyk** [comment]
Use this free extension fir your purpose
https://e-addons.com/elementor/dynamic-tag-template/

**Comment by nreljed** [comment]
no need for a plugin 
I tested the possibility of pasting the elementor template shortcode and
that works
now all that remains is to test and document this manipulation by crocoblock

![Capture d’écran 2021-08-17 150709](https://user-images.githubusercontent.com/82481592/129741829-20c18ae1-7671-4359-b803-404b49180db4.png)

**Comment by saltkinmedia** [comment]
thanks @nreljed 

Elementor shortcodes work fine!
