### ISSUE TITLE
Adding additional page builder compatibility such as Brizy and Beaver Builder

### ISSUE THREAD

**Issue by manuelgraph** [CrocoBlock/suggestions#3826]
Elementor is well known by a lot of people. However, not everybody design and develop websites with Elementor in mind. Can Brizy and Beaver be added to the compatibility of Jet Plugins? Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by manuelgraph** [comment]
I guess it is about popularity because Brickbuilder was added to work with jetengine. There is nothing wrong with that but clarity is key here
