### ISSUE TITLE
JetEngine: Listing Grid Columns do not support new responsive options in Elementor 3.4+ 

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#3831]
**Describe the bug**
Elementor 3.4+ has added several new Responsive options

- Widescreen
- Laptop
- Tablet Extra
- Mobile Extra

JetEngine columns default to the standard (old) versions General (desktop), Tablet and Mobile. 

**To Reproduce**

This is most easily reproducible with the Listing Grids 

**Prerequisites**: You should have a listing grid prepped with multiple items. 

1. Download and Install Elementor 3.4
2. Go to Elementor > Settings > Additional Custom Breakpoints and set to active
3. Load a page in Elementor
4. Go to Elementor Site Settings (Hamburger Menu > Site Settings > Layout > Breakpoints) (see below for screenshot)
5. Activate the additional breakpoints and click on update
6. Refresh the page to activate the new breakpoints
7. Find and locate the Listing Grid and drop in the listing grid > select your listing items
8. Select one of the new Display Options
9. Change the columns to anything like 10
10. Update the page and view (you can also see the issue in preview)

**Actual Result**
The column listings do not update. 

**Expected behavior**
All responsive types should be supported by JetEngine Columns. 

**Screenshots**
![image](https://user-images.githubusercontent.com/223342/129601686-18e24c00-395b-48fa-9629-dde4142099a1.png)
![image](https://user-images.githubusercontent.com/223342/129602025-361ec78b-05c0-47dd-9601-5275e8a2b1ed.png)

**Additional context**

From what I could determine settings located in: 

\jet-engine\jet-engine\assets\js\admin\blocks-views\src\blocks\listing-grid\index.js

**Comment by kaskad88** [comment]
The compatibility added to the next version ( 2.8.9 )
