### ISSUE TITLE
Tags in Jet Forms

### ISSUE THREAD

**Issue by rubyviocom** [CrocoBlock/suggestions#3833]
Hello, 
it would be nice if customers and user could have posibility to add tags via form, when they creating theyre own contant on our sites. It would be very welcome future for many similar projects i believe.

Currently we need to add hashtags manualy when we arpoving content, and you can imagine that that is veryy time consuming.

:-) Thanks, Joe @rubyvio

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
