### ISSUE TITLE
JetEngine: Add text color option in wysiwyg text field

### ISSUE THREAD

**Issue by keet789** [CrocoBlock/suggestions#3835]
Hi, could you please add an option in the front-end Wysiwyg test editor letting users choose text color?
It's an essential feature demanded by my users. Thank you.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
