### ISSUE TITLE
Build a real booking functionality

### ISSUE THREAD

**Issue by Hammer-ger** [CrocoBlock/suggestions#3836]
Please change JetBooking to a real booking System.

As every booking System you need to have 3 types of days (not 2):

Free days 
Booked days
Arrive/leave days (1/2 day)

Your developers are realy good so i think this is not to difficult for you.

And you will get a very powerful tool. In a now growing again marked.

Best regards,

Maximilian

**Comment by UraraReika** [comment]
All the functionalities you mentioned already added to our plugin so feel free to test them. If you have some questions please contact our support team - https://crocoblock.com/customs/  .
