### ISSUE TITLE
[JetBlog] Incoporate RSS feeds in widgets

### ISSUE THREAD

**Issue by TRADEREXDE** [CrocoBlock/suggestions#3839]
Hello

it would be a total game changer if you would incorporate the ability to display RSS feeds in the jetblog widgets.

E.G. the news ticker could fetch dynamic rss data from CNN, CNBC, or whatever news source. 

Additionally, it would make sense to create an RSS widget which lets us display the available content of the rss feed in the way we want (amount of words, headline yes/no, image yes/no)

Thanks

**Comment by IrynaBerezhnaya** [comment]
Added the ability to display RSS feeds in the Text Ticker widget.

**Comment by Crocoblock** [comment]
was added in JetBlog 2.4.0
