### ISSUE TITLE
JetEngine: CCT Dynamic Repeater Widget

### ISSUE THREAD

**Issue by iamdanbarrett** [CrocoBlock/suggestions#3841]
Can you please allow for the dynamic repeater field widget to work with the Custom Content Type metadata, please? It seems redundant to have the option to create this type of data within the CCT if it cant be output on the front end. I had to create an entire directory into a CPT discover that this wasn't possible with a CCT.

**Comment by gmverdon** [comment]
Any progress on this issue?

**Comment by mohizahmad** [comment]
Highly recommended. I planned entire project using CCT and can't implement it

**Comment by kaskad88** [comment]
Added in JetEngine v2.11.8
