### ISSUE TITLE
Listing in Slider Not Work properly in new update 2.8.9

### ISSUE THREAD

**Issue by P258tiwari** [CrocoBlock/suggestions#3842]
**Describe the bug**
Listing Slider have more gap in new update please check I share 2 Screen shot before and after updates

![Web capture_18-8-2021_25044_ampwakelibrary com](https://user-images.githubusercontent.com/64008801/129802479-5017db40-a059-464e-8a15-ae88247c63e4.jpeg)
Before Update (2.8.8)

![Web capture_18-8-2021_25030_ampwakelibrary com](https://user-images.githubusercontent.com/64008801/129802519-b52adfdb-4567-4937-a023-f423c2bb9752.jpeg)
After Update (2.8.9)

Please Check

**Comment by kaskad88** [comment]
Thanks for your feedback.

We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.

**Comment by P258tiwari** [comment]
ok
