### ISSUE TITLE
JetEngine: Query Builder WC Product Sale Variation

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#3844]
Until now it is still not possible to display product variations that are on sale in the listing grid. Only single products on sale are displayed. 

It would be good to have the option in the query builder under "WC Product Query" to display all sales, including those of the variations. 

Or at least that you could select a listing grid in the "WooCommerce Sale Products" widget.

**Comment by UraraReika** [comment]
Hello @petranca !

Use this code https://gist.github.com/UraraReika/0944fd7706619f2876385422ec4d23f4 to add custom macros https://i.gyazo.com/68febb51ac3d27dd97bc9a0b1844bb82.png. And then use it here https://i.gyazo.com/932b38f960edcf166f59f4180226ecea.png.

**Comment by petranca** [comment]
Hi @UraraReika and thank you, but is not really working. It does fetch the products with variation on sale, but all other widgets in the listing grid do not recognize the ID. Image, Wishilist, Title, Description...
https://prnt.sc/1qbn357
