### ISSUE TITLE
JetBooking: show booking status on the frontend

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#3846]
For example, in the Cars Listing, need to show booking status (free, on hold, will be free at...) http://prntscr.com/1qbtnwv

К примеру в листинге авто, в карточке надпись (занято, свободно или когда освободится)
Пример такой реализации на сайте - https://autoprokat24.ru/

**Comment by MjHead** [comment]
Added in 3.4.0
