### ISSUE TITLE
JetSmart filter dropdown (filled from taxonomy) custom order

### ISSUE THREAD

**Issue by lucasblendimc** [Crocoblock/suggestions#385]
Request for custom select/dropdown filter ordering when pulling the data from a taxonomy for JetSmart Filters.

On a website I have a taxonomy for day of the week. I am allowing users to filter by day of the week as the data for the dropdown is pulled from the taxonomy.

This dropdown on our site is pulling days of the week from existing tags in the taxonomy, I would like to customize the order of the dropdown so that it is not alphabetically sorted (default).

![image](https://user-images.githubusercontent.com/50926427/61798883-b5c6bb80-adef-11e9-8393-6d6d906d4a90.png)

**Comment by RodSuper** [comment]
@lucasblendimc There's a way to sort the filter options using a plugin like 'Simple Custom Post Order'.

After activating the plugin, make sure to give permission to edit the category of your choosing in the settings of the plugin. (You find it here: Settings => SCPOrder)

Once it's selected, go to the categories in the backend and drag them in the order you wish.

Hope this helps, let me know if it's working for you :)

Rod

**Comment by Floydtm** [comment]
Guys, I think this is a good solution because we would not want to come up with a new select, but we use what the elementor provides
