### ISSUE TITLE
Email subscription - integration with drip.com

### ISSUE THREAD

**Issue by TimeaRich** [CrocoBlock/suggestions#3850]
Good afternoon,

I see that you have an integration with Mailchimp, but would it be possible to integrate with drip.com as well? Drip provides better marketing analytics than MailChimp.

Have a great day!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
