### ISSUE TITLE
Post slug with jet engine forms

### ISSUE THREAD

**Issue by jabaco** [CrocoBlock/suggestions#3851]
The post slug is automatically created with post title but it would be much better if the user has the power to choose his own post slug so he can better customize his post... This is very useful for ad, classified and similar sites...

Please add this in Jet Engine forms!

Thanks 
Javier

**Comment by anybany** [comment]
+1
and additionally a auto-update function for the slug if the title changes ;)

**Comment by alican532** [comment]
+1

**Comment by Pooriya369** [comment]
+1

**Comment by kaskad88** [comment]
It`s possible https://prnt.sc/sCim-ZyaezWw
