### ISSUE TITLE
Searching for Custom Content Types within the CCT listing is broken. No results yeilded.

### ISSUE THREAD

**Issue by zalahmar** [CrocoBlock/suggestions#3852]
**Describe the bug**
If you add Custom Content-Type fields to the Admin Column and try to search terms for anything displayed in the Admin Columns, the search results always come back as nothing found. 

**To Reproduce**
1. Create a Custom Content Type, create a couple of fields and select "Show in the admin columns" checkmark
2. Populate a few entries for the Custom Content Type.
3. Try to search for anything that is displayed in the Admin Column for the CCT.
4. You will get a result of "No Items Found"

**Expected behavior**
I expect the search to show the results. This would make finding records impossible in very large database entries as you would need to manually click through pages to find the entry.

**Screenshots**

![image](https://user-images.githubusercontent.com/88862118/130146242-76417342-962a-4196-881e-22612fd47b94.png)

![image](https://user-images.githubusercontent.com/88862118/130146131-c84f0635-d3ed-4e6d-a944-00ebd38bcb1a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 92.0.4515.159

**Additional context**

**Comment by kaskad88** [comment]
Fix for the next version (2.9.4). Thanks for your report!

**Comment by Lonsdale201** [comment]
> Fix for the next version (2.9.4). Thanks for your report!

you mean 2.9.3? :P
