### ISSUE TITLE
Geo proximity/distance filter and search for WooCommerce or custom post types

### ISSUE THREAD

**Issue by upsited** [CrocoBlock/suggestions#3855]
Would it be possible to add a proximity/distance to the JetSearch plugin? Example: You could search by entering your zip code and choose from dropdown the range in miles/kilometers. Just like the categories dropdown is an option this could be another option in the search field.

This would also be great for the JetSmartFilters to allow to filter woocommerce/products by distance from your location. Using geocoding to pull in users location automatically and filter the products by a chosen distance.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
