### ISSUE TITLE
JetTabs: Allow to set a custom ID to tabs. 

### ISSUE THREAD

**Issue by adelapuentep** [CrocoBlock/suggestions#3856]
Problem:
When you want to link to a specific tab, you need to inspect the code, find the dynamic tab ID (#jet-tabs-control-1234) and add it to the URL. This gives you a final URL such as (https://www.example.com/#jet-tabs-control-1234). This isn't user nor SEO friendly. 

Solution:
Allow to set a custom ID to each tab so that the url is SEO and user friendly.

**Comment by UraraReika** [comment]
Hello @adelapuentep !

This functionality already exist https://i.gyazo.com/bd6dff0f7eeb6eee9bcb520dabe0d940.png. Control CSS ID.
