### ISSUE TITLE
After update, profile builder feature is broken.

### ISSUE THREAD

**Issue by erturkuner** [CrocoBlock/suggestions#3859]
**Describe the bug**
After 2.8.9 and 2.8.10 update, profile builder feature is broken. When I want to update or add new custom post item, account page is deleting. Normal url is /mysite.com/account but after the update or add process it's returning to /mysite.com/properties/account and it's showing me the last property that I edit or add.

**Screenshots**
--> Before the update or add process
Account Page Content -->![Screenshot_3](https://user-images.githubusercontent.com/25878956/130222565-cf2f39c1-483d-410e-bacc-6df1d1004880.png)

URL--> ![Screenshot_1](https://user-images.githubusercontent.com/25878956/130222566-3af994e7-364d-4462-a678-2247ab3bd46f.png)

Profile Builder Screen --> ![Screenshot_2](https://user-images.githubusercontent.com/25878956/130222567-a36f47cd-91cd-435a-86b4-3e6680a025b8.png)
--> After the process

URL--> ![Screenshot_4](https://user-images.githubusercontent.com/25878956/130222891-8e2b36f2-951c-454c-83cc-d7a53938b2f2.png)

Account Page Content --> ![Screenshot_5](https://user-images.githubusercontent.com/25878956/130222893-e2d8d21f-cf4a-4971-bb62-1ee07a66b9d8.png)

Profile Builder Screen--> ![Screenshot_6](https://user-images.githubusercontent.com/25878956/130222896-d700fe6b-7794-4207-84d4-b5f5be66986d.png)

**Comment by johannbt** [comment]
also got this bug, it is very annoying

**Comment by johannbt** [comment]
Hi Kemal,

I have tested it with the beta version 2.9 and so far it works, that means that the version 2.8.10 has errors

Regards
Johann

**Comment by johannbt** [comment]
Hi Kemal,

Julia Kiselyova from Crocoblock helped me and now everything works.
Can you write to her and say that you have the same problem as Johann and she will help you.

Many thanks to Julia Kiselyova, a very good support

**Comment by erturkuner** [comment]
@johannbt Thanks your feedback. I think it's about elementor new version combability. I'm using older versions for now and if a solid comes out for this then I'll try to solve it.

**Comment by johannbt** [comment]
Hi Kemal,

it has nothing to do with Elementor, it is only about the update of JetEngine to version 2.8.10, this is somehow buggy, because version 2.9 works fine.

In spite of this, you should also use the following settings for version 2.9 and I have these screenshots from Julia from Crocoblock:

Wrong: https://prnt.sc/1qhsrgi
Correct: https://prnt.sc/1qhss2f

if you have a form to create a post, you don't need that: https://prnt.sc/1qhstl3

always ask the people at Crocoblock, they are really very knowledgeable

Regards
Johann

**Comment by erturkuner** [comment]
Hi Johannbt,

Thanks for the information. Can you tell me the version of elementor plugin that currently working with jet engine 2.9. Elementor and Elementor pro plugin of course.

Thanks

**Comment by johannbt** [comment]
Hi Kemal,

it actually has nothing to do with Elementor, just update the Elementor and Elementor Pro to the latest version and everything will work with version 2.9.

If you have any questions, write to the support at Crocoblock, the people there are really very friendly, fast and competent.

Best regards
Johann

**Comment by AhYazid** [comment]
> Hi Kemal,
> 
> it has nothing to do with Elementor, it is only about the update of JetEngine to version 2.8.10, this is somehow buggy, because version 2.9 works fine.
> 
> In spite of this, you should also use the following settings for version 2.9 and I have these screenshots from Julia from Crocoblock:
> 
> Wrong: https://prnt.sc/1qhsrgi Correct: https://prnt.sc/1qhss2f
> 
> if you have a form to create a post, you don't need that: https://prnt.sc/1qhstl3
> 
> always ask the people at Crocoblock, they are really very knowledgeable
> 
> Regards Johann

I also had a problem with that, when adding or editing a post suddenly the account page for the user disappeared permanently. by using this method everything works normally again. Thanks very much
