### ISSUE TITLE
Add CrossSell, Upsell and Related Queries [Products Widget] on Cart Page JetWooBuilder

### ISSUE THREAD

**Issue by xC4M** [CrocoBlock/suggestions#3862]
Hi, while editing my Single Product Page I saw that I had Cross-sell, Upsell and Related queries' available to use inthere. But I'd like to use, for example, the Cross-sell query in the Cart Page using Product Widget, but it's not available. So, please add them to be use it in the Cart Page or even globally using the Product Widget in JetWooBuilder.

Cross-sell, Upsell and Related Queries appears on Products Widget while I'm editing the Single Product Page ( https://prnt.sc/1qdtq67 / https://prnt.sc/1qdtqqx ) 

...and it doesn't while editing the Cart Page https://prnt.sc/1qdua1s

**Comment by xC4M** [comment]
@UraraReika  Thanks for take my feature request.

After JetWooBuilder update, there's an error at the bottom of the Cart Page. https://prnt.sc/1qhwuzi
and also, there was a change in the quantity input field, the minus and plus buttons disappeared.

All those happened after updated.

**Comment by UraraReika** [comment]
Fixed, release soon

**Comment by 79ho3ein** [comment]
hello
Cross sales and ... has been added to the cart?
I updated but did not see the Upsell & CrossSell...

**Comment by xC4M** [comment]
@79ho3ein  Yes, Cross-sell query was added into the Product Grid Widget in the Cart Page, but it doesn't really work. It doesn't display products even it has.

Also, quantity change buttons (plus and minus) disappeared after lastest update.

**Comment by 79ho3ein** [comment]
> @79ho3ein Yes, Cross-sell query was added into the Product Grid Widget in the Cart Page, but it doesn't really work. It doesn't display products even it has.
> 
Such a thing has not been added at all.

> Also, quantity change buttons (plus and minus) disappeared after lastest update.

quantity change buttons (plus and minus) ؟ What is your theme? The woobuilder has not added this feature yet ... I use the hello elementor template.

**Comment by xC4M** [comment]
@79ho3ein When I talk about quantity plus and minus buttons, it's jus in my case. After I upgrade JetWooBuilder, plus and minus buttons disappeared in the Cart Page; that's what I tried to explain you. I'm using ASTRA PRO as a Theme.

**Comment by UraraReika** [comment]
Only cross-sell query was added to cart page template. Other not supported directly by cart object but if you really want in you can code your own custom query. If you have some difficulties with this please contact our support team. As for plus minus buttons i cant tell you sure what happens but nothing really changes at that point.

**Comment by xC4M** [comment]
@UraraReika 
This is my case...

plus/minus buttons on version 1.10.0 which was BEFORE the update's 1.10.1 (also 1.10.2 version didn't solve the issue) https://prnt.sc/1qm1c64
At the bottom of the Cart Page BEFORE update to 1.10.1 version https://prnt.sc/1qm1hjv , all was good.

So, I updated JetWooBuilder to 1.10.1 and 1.10.2 version but still appearing the same issue on both version and Error started to appear AFTER update to 1.10.1 version and still appearing on 1.10.2 version 
1.10.1 version: https://prnt.sc/1qm2ou8 - plus/minus https://prnt.sc/1qm2qir - Cart Page Error https://prnt.sc/1qm2wv4 
1.10.2 version: https://prnt.sc/1qm23mv - plus/minus https://prnt.sc/1qm29c2 - Cart Page Error https://prnt.sc/1qm2kjv)

I had to downgrade from 1.10.2 version to 1.10.0 version because it was the last time everything was working good https://prnt.sc/1qm1ude

That's why I assume that could be due to the changes on 1.10.1 version...

**Comment by UraraReika** [comment]
Hello @xC4M !

Perhaps this is related to your site. Please contact our support team. Thank you!
