### ISSUE TITLE
Slider Preview not working in new update and listing show in center 

### ISSUE THREAD

**Issue by P258tiwari** [CrocoBlock/suggestions#3864]
**Describe the bug**
When I update new version slider listing notworking properly for me 
1. Equal Height function not work with slider and listing break  
2. Slider on preview only show single image 
3. Item in center in front view

I solve center item with adding custom CSS please check

MY CSS FOR CENTER LISTING IS 

.jet-listing-grid .slick-track{
    margin: 0px;
}

I select 3 Item in a slider but preview only show one
![Web capture_22-8-2021_495_new popsiclesclothing com](https://user-images.githubusercontent.com/64008801/130336605-ca2ead53-65fc-4a69-829d-ba8aa177b7fd.jpeg)

OFF Slider 
![Web capture_22-8-2021_4938_new popsiclesclothing com](https://user-images.githubusercontent.com/64008801/130336615-e0b707fa-4391-4dc5-85aa-0000aa63b85b.jpeg)

ON Slider
![Web capture_22-8-2021_4952_new popsiclesclothing com](https://user-images.githubusercontent.com/64008801/130336619-9e2223c9-0af8-4d48-91f5-fa670b3fff85.jpeg)

**Comment by kaskad88** [comment]
@P258tiwari, Please update the JetEngine to version 2.8.10 and regenerate the CSS and data ( Elementor->Tools->Regenerate CSS & Data ).

**Comment by P258tiwari** [comment]
@kaskad88 OK Let me check

**Comment by wordpressman** [comment]
Updated Jet Engine to 2.9.0 and regenerated CSS & Data, but I still see exactly that problem, just like @kaskad88 (same number of column, no dots....etc)

I notice also that if you choose 4 column, you get 3, if you choose 5, you get 4 and so on.

**Comment by P258tiwari** [comment]
Crocoblock team help me to solve this issue  just off equal column option if you on it will help to resolve this problem

**Comment by kaskad88** [comment]
@P258tiwari We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
Thanks.

**Comment by P258tiwari** [comment]
I figure it out due to new elementor Accessibility Improvements and Improved CSS Loading cause this issue when I turn off it work perfectly for me.

Please check this way too

**Comment by kaskad88** [comment]
Hi @P258tiwari We tried to reproduce your issue based on the **new** information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
Thanks.
