### ISSUE TITLE
🐛[Jetsmartfilters] Filters on popups (elementor pro)

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#3865]
![pop2](https://user-images.githubusercontent.com/82481592/130337613-08ce791d-32db-4d50-a001-89e9884644ab.png)

by accident..
I just realized that the use of filters on popups (elementor pro) is not possible with jetsmartfilters
[you have to go through jetpopup](https://crocoblock.com/troubleshooting/articles/cannot-display-smart-filters-in-popup/)

**This may seem normal** if I did not have another plugin ... precisely [gridbuild ](https://wpgridbuilder.com/) on which I dared by excess of imagination to cross this limitation without difficulty 
Created one popup > add my filters widget and voila..

I have verified that everything is working correctly...

In doubt I installed jetpopup to make my jetsmart filters work in popup..

but now it's not normal ..
because if I have elementor pro and popups, I don't need to install another plugin for popups .. it doesn't make sense..

I don't know what to say about this strange technique.
but it doesn't seem natural anymore after doing it with the other solution naturally.
it's a matter of logic and common sense

we will just say that it is a 🐛 bug or a limitation that has not been removed or need to be fixed :) 

let's imagine that this is the only way ...

for those who only have elementor free..  it can be understood..
that's a valid reason to install jetpopup to enable popups 

but... 

with elementor pro?

and how to explain the other plugin does it so quietly and naturally? do they have ninja techniques?

in my opinion this limitation must be removed by default
I believe it is from another era before popups in elementor

**Comment by 79ho3ein** [comment]
hi @nreljed 
I have requested this feature before in #3146. They add this feature, but it is not clear when!

**Comment by 79ho3ein** [comment]
fixed in 2.3.10
