### ISSUE TITLE
🔥[Jet Booking] Hours for collection and delivery in calendar and work and rest hours

### ISSUE THREAD

**Issue by neoset** [CrocoBlock/suggestions#3866]
Hello, Jet Booking in addition to the range of eligible days, you necessarily need the pick-up and delivery times in the calendar in the case of car reservations, the same as on the sixt.com website.
You also need the same system of work and rest schedules as jet appointment, a greeting.

<img src="https://i.ibb.co/zhXk9Y8/Sin-t-tulo.png" alt="Sin-t-tulo" border="0">
<img src="https://i.ibb.co/x27FdjS/Sin-t-tulo2.png" alt="Sin-t-tulo2" border="0">

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1597, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
