### ISSUE TITLE
Jet Listings Post Sort dropdown

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#387]
After speaking with your pre-sales team I was wondering if there is a way to create a feature for the Jet Listings and create a widget for sorting posts by A-Z, Z-A, date etc etc. This is a basic WP expectation and not even really a major feature.

**Comment by realstephenzhao** [comment]
I always need this sorting option on frontend page. It will be better if we can toggle grid view and list view.

**Comment by Floydtm** [comment]
Guys, this can be implemented using the sorting widget http://prntscr.com/ri8duf which is available in the jetsmartfilters plugin
