### ISSUE TITLE
Wishlist Functionality Enabled creates Active PHP session Warning

### ISSUE THREAD

**Issue by kamyabnazari** [CrocoBlock/suggestions#3870]
**Describe the bug**
After activating the Wishlist functionality in the Crocoblock dashboard, i get in site health page the critical warning that an active php session was detected. and get the rest Api warning to.

**To Reproduce**
1. Go to 'Crocoblock -> JetPlugins settings -> JetCompareWishlist -> Wishlist Settings'
2. Click on 'Enable Wishlist'
3. Scroll down to 'Tools -> Site health'
4. See error (Warning) :  An active php session and Rest API timeout

**Expected behavior**
No warning and errors.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home (10.0.19043 Build 19043)
 - Browser Firefox
 - Version 91.0.1 (64-bit)

**Smartphone (please complete the following information):**
 - Device: none
 - OS: none
 - Browser none
 - Version none

**Additional context**
I have fixed the issue by changing the session_start() code inside of "class-jet-cw-wishlist-data.php" file.

from:
`if ( !session_id() ) {
    session_start();
}`

to:
`if ( !session_id() ) {
    session_start( [
        'read_and_close' => true,
    ] );
}`

**Comment by UraraReika** [comment]
Hello @Kamyabnz!

This solution can fix the issue but after it you will not be able to add products to list.

**Comment by kamyabnazari** [comment]
Hello @UraraReika,

what could be the alternative solution ?

**Comment by UraraReika** [comment]
In latest update of the plugin you can switch between sessions and cookies. So just use cookies.
