### ISSUE TITLE
In the context of a marketplace, I would like to configure the ability to receive internal messages/LiveChat communication from a customer to a seller. The seller can see the messages from a customer when he is logged into his account ? Thank you. An example that come close to this feature is described here: https://docs.wclovers.com/live-chat/

### ISSUE THREAD

**Issue by kirisutoweb** [CrocoBlock/suggestions#3872]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
