### ISSUE TITLE
JetSmartFilters Sorting Filter - usable for JetWooBuilder Products Loop?

### ISSUE THREAD

**Issue by computerfreak84** [CrocoBlock/suggestions#3874]
Any chance the Sorting Filter widget from JetSmartFilters can be used with the Products Loop widget from JetWooBuilder?

The help article only talks about JetWooBuilder Products List and Products Grid...
https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-sort-posts-and-products-with-sorting-filter-widget/

Thank you and best regards

**Comment by Floydtm** [comment]
You can use this right now. Thank you!
