### ISSUE TITLE
Please, make JetCompareWishlist plugin working with cookies to solve the caching issues.

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#3876]
Please, make JetCompareWishlist plugin working with cookies to solve the caching issues.

**Comment by DeBelserArne** [comment]
@UraraReika You closed this and put "Ready for release" label onto the ticket, is this something that's gonna come out soon?

**Comment by Floydtm** [comment]
This is already in the release version https://prnt.sc/1ywsts9
