### ISSUE TITLE
JetSmartFilter: Select filter positing line | column options not working

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#3877]
I use hierarchical filter with Select filter type. When I choose to show on the same line it doesn't work. Defaults are columns and cannot be changed.
I have tried again with checkbox filter and it works fine. I think this is a bug I hope you guys can fix it soon.
![line - column](https://user-images.githubusercontent.com/89138954/130589128-adbc0d4c-65e1-476c-92ee-4c3929afc95e.jpg)

**Comment by Floydtm** [comment]
I see that you have a group of filters, the desired setting is in a different control below. https://prnt.sc/1rpb0cv Thank you!
