### ISSUE TITLE
JetTabs - Active/Inactive tab styling and Close tab button

### ISSUE THREAD

**Issue by Rubendj1** [CrocoBlock/suggestions#3878]
Hi, 

I would love to see the functionality added to style active and inactive tabs separately. 
And I would like to be able to add a button that closes the active tab.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
