### ISSUE TITLE
Integrate MyCred with JetReviews

### ISSUE THREAD

**Issue by RealtorNathan** [CrocoBlock/suggestions#3881]
Integrate MyCred with JetReviews. There are a few review plugins that already integrate with MyCred, but I can't display the rating on a listing.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
