### ISSUE TITLE
Support for Product Results Count + JetSmartFilters 

### ISSUE THREAD

**Issue by simonkrogh10** [CrocoBlock/suggestions#3882]
Make Product Results Count Widget work with JetSmartFiltering so that the Results Count can change based on AJAX instead of page reload only.

**Comment by Floydtm** [comment]
Could you describe your problem in more detail? Attach screenshots if possible. Thank you!

**Comment by Dhaump** [comment]
I think it refers to this ... that the total products counter will change according to the selection you make in the filter. I was also going to request this upgrade, it seems essential ...

![1](https://user-images.githubusercontent.com/90693991/133299592-407c7312-3592-4a48-982f-c10053727629.JPG)

**Comment by Floydtm** [comment]
Unfortunately, we will not be able to implement this, since it depends not only on us, but also on the woocommerce. From our side, you can implement all this with the jetengine plugin. You can contact our support team, the guys will help you. Thank you!
