### ISSUE TITLE
Duplicating templates in Jet Woo Builder.

### ISSUE THREAD

**Issue by MB88621** [CrocoBlock/suggestions#3883]
I'm writing an idea for a feature for Woo Builder after talking to your support and realizing this feature doesn't exist in Jet Woo Builder.

When building a website with Elementor duplicating templates is a part of the job and it gets the work done faster.

I'm building a woo commerce website where I would need to build lots of templates for a "Single Product Page" - I have several artists and each has different artworks with different info to show - so I needed to be able to duplicate the "Single Product Page Template" instead of building a new template for each artist.

I even tried saving it as a template in the Elemntor Editor, but then Jet Woo Builder doesn't recognize Elementor templates as woo-commerce templates so this didn't work.

The only solution I found is to copy-paste sections from a "Single Product Page Template" I've already built, which is not the best workflow.

Please consider adding this feature to Woo Builder.

Thanks,
Mcihal

**Comment by UraraReika** [comment]
Hello @MB88621 !

You can save it as a template. Like this https://gyazo.com/5ce0d6e4f9034016321eeb6334a96a32. Then in new template just find it in the list https://gyazo.com/ed96e2d8b8f53343b85484b650bbdfb4.

Or you can create one template and with the help of dynamic data output different info.

**Comment by MB88621** [comment]
Your support could have explained this to me. I was told this functionality
doesn't exist.
