### ISSUE TITLE
[JetBooking] Insert booking in WP-admin

### ISSUE THREAD

**Issue by Micheldebo** [CrocoBlock/suggestions#3889]
Hey guys,

A customer of mine runs a camping website. We created the Booking system with JetBooking plugin. 

Some customers call them for a booking instead of through the website. Therefore, they would like to insert a booking into the Wordpress system themselves. 

Would it be possible to do this somewhere in WP-admin?  I can't find such feature. Would be great!

**Comment by benjamieson** [comment]
I second this request.

It's pretty much essential for any company using bookings - they need to be able to add bookings from the back end.

**Comment by UraraReika** [comment]
This functionality was released in 2.5.0 version of the plugin.
