### ISSUE TITLE
JetEngine - Random posts for listing grid

### ISSUE THREAD

**Issue by fissunix** [Crocoblock/suggestions#389]
A way to have X random posts in the listing grid for any custom post type or taxonomy.

Example : 
on the homepage of a website, adding a listing grid in slider mode that shows X random posts of any custom post type or taxonomy. Thus, anytime we come back to the homepage (or just a new session), we have a different content on the homepage (so not just a random "order by"). 

Thank you.

**Comment by slamdive** [comment]
Just came here looking for this.
Any updates?

Thanks.

**Comment by justinpatrickkeller** [comment]
Here too... I just spend an hour fumbling around trying to do this. Finally realized it's a missing (very needed) feature.

**Comment by mcj777** [comment]
+1

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0

**Comment by RyanWKramer** [comment]
I thought the original request was for random POSTS, not random NUMBER of posts.

**Comment by justinpatrickkeller** [comment]
Yeah, this should be the ability to display a random assortment of X number of posts, where X is defined and the posts that show up are random... for example we have a post type of contributor. We have 237 contributors. On our homepage we want to display 10 contributors, chosen at random. So that each time the page gets loaded there is a different 10 contributors featured.

**Comment by Floydtm** [comment]
Use  this options https://prnt.sc/1000bu9

**Comment by ALPSIT** [comment]
> Use this options https://prnt.sc/1000bu9

This doesn't work for Custom Content Types. Only for Posts.

Why can't an option be put in place to randomise the order of Custom Content Types? Much needed when there are 10s-100s of items that we'd like to display at random.

Please implement!

**Comment by iAbhinavJain** [comment]
> > Use this options https://prnt.sc/1000bu9
> 
> This doesn't work for Custom Content Types. Only for Posts.
> 
> Why can't an option be put in place to randomise the order of Custom Content Types? Much needed when there are 10s-100s of items that we'd like to display at random.
> 
> Please implement!

Really need this. Simple yet essential

**Comment by thoknuts** [comment]
kaskad88 - How is it possible to interpret this essential request of random POSTS into random Numbers of posts?? 
TS does not mention random numbers at all. ( And I can't think of a single use case where random post numbers has any use.)

Really need to display Random posts ( As Elementor Pro  has) 

PLEASE OPEN THIS THREAD AGAIN - AND DO IMPLEMENT THIS

**Comment by kaskad88** [comment]
@thoknuts to display random posts use this options https://prnt.sc/1000bu9 as mentioned above in the comment

**Comment by kaskad88** [comment]
@ALPSIT to display random CCT items use this options https://prnt.sc/1sthlg7

**Comment by atiroop** [comment]
> @ALPSIT to display random CCT items use this options https://prnt.sc/1sthlg7

Hey! I logged in just to say **Thank You** to you. I've searching all over the places, Finally I found the answer. :D

**Comment by zahnd** [comment]
> @ALPSIT to display random CCT items use this options https://prnt.sc/1sthlg7

Hi. This doesn't seem to work for me. My query is https://monosnap.com/file/HMrTfgP16F7GyxNUalPtOsJu6OxvWx but it always shows the same items. Same when no query is set. Any hint is much appreciated :). Thank you

**Comment by camfil26** [comment]
Go to Posts Query > choose the Order & Offset option > Order by: RANDOM.
It works for Custom Posts as well.

**Comment by SiavashBavandpour** [comment]
@kaskad88 Hi there, 

Background: I use cloudways for my wordpress and their package comes with Object Cache Pro.
I am using the Query builder, the posts are listed randomly and everything works fine, however when the cache is active, it also caches the query and the listing order stays the same.  I think Crocoblock needs to add "'**cache_results'  => false,**" into the array when "Order By" is "Random Order".

**Comment by studio-utd** [comment]
Hi. I am using a query builder for terms to display random terms but I don't see Random order option in Query Builder > Order by.

**Comment by kaskad88** [comment]
> Hi. I am using a query builder for terms to display random terms but I don't see Random order option in Query Builder > Order by.

Hello @studio-utd. WordPress does not support random order for the Terms Query https://tppr.me/M01eF https://developer.wordpress.org/reference/classes/wp_term_query/__construct/#parameters

**Comment by zahnd** [comment]
I'm adding my name of the persons who are facing issues with Oject Cache Pro like @SiavashBavandpour

**Comment by rentaterry** [comment]
It does not work with CCT.

**Comment by lokosjoe** [comment]
@rentaterry Did you get to work the random query with CCT?

**Comment by esamzenhom** [comment]
have any one tried to use query builder !, i guess it worked for me

**Comment by dis-mal-skull** [comment]
In 2025 need first **activate** the legacy mode, reload the page and then use this configuration, because the Post Query Tab is not visible in start.

![Image](https://github.com/user-attachments/assets/cccc34a9-784a-4f85-8f8c-6e05b3f6f158)
