### ISSUE TITLE
woobuilder add dimensions

### ISSUE THREAD

**Issue by hakankarar** [CrocoBlock/suggestions#3896]
it would be nice to see products dimensions on shop page

**Comment by UraraReika** [comment]
Hello @hakankarar !

You can use Query Builder ( WC Product Query ) from JetEngine with this settings https://i.gyazo.com/3e2e6b68f6162af2845ae3a76319dc19.png. Then create listing and with the help of Dynamic Field widget output dimensions. The last step in use Listing Grid widget on single product template with Custom Query option where you choose query you created before.
