### ISSUE TITLE
New options for timeline

### ISSUE THREAD

**Issue by Floydtm** [CrocoBlock/suggestions#39]
- Why you don't let the user the choice for px vs em for the size of connector circles? It's smarter to use em as unit since it can scale for tablet and mobile, at least give the option (i think it's very simple for elementor to add support for both units on a field).

- Why you don't let user override the style for each single element so that I can have a line/circle red when in focus, then the next one yellow, the next one green, or contenets with different backgrounds, etc. You would just need to add a switch "ovverride style" like UAEL does.

**Comment by kaskad88** [comment]
1 - Done
2 - No need to do

**Comment by kaskad88** [comment]
Done. Available in JetElements 1.15.13
