### ISSUE TITLE
JetEngine - Custom Post Type - Admin Colunmn: Add a render image from media gallery

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#3903]
I noticed the admin column section has the feature to get the image from the Gallery meta field to display on the admin column. But it only takes 1 image. Show from meta value then it only shows image ID.
To make it more convenient to display, I think it should appear all images in the meta field gallery or limit the number of images.

![image](https://user-images.githubusercontent.com/89138954/131204903-b4dda89f-dd9f-4276-bdd0-c176789df106.png)
![image](https://user-images.githubusercontent.com/89138954/131204920-6f668710-0da4-443c-b41f-2532d9141062.png)
![image](https://user-images.githubusercontent.com/89138954/131205037-3eca3576-11bc-45f2-96fc-dd6aa7c2d4ef.png)

**Comment by kaskad88** [comment]
Added for the next version. Thanks for your report!
