### ISSUE TITLE
Absolute Height and width for the product grid widget flash box (jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3905]
hello
It would be great if you add settings to the flash box of this widget, so that we can give it absolute height and width. https://prnt.sc/1qp78yl
Unfortunately for now, we can only change the overall size of the box and this makes the box  always square.
**In fact, it would be great if we could determine the size of the box like this :** https://prnt.sc/1qp7whi

please check. thank you🌹

**Comment by UraraReika** [comment]
I merged this issue with #3102, which is on the same subject so we could deal with it more efficiently.

**Comment by 79ho3ein** [comment]
thank you, But number 3102 is closed !

**Comment by UraraReika** [comment]
Solution is there
