### ISSUE TITLE
JetFormbuilder - Conditional Logic - disable loading hidden content

### ISSUE THREAD

**Issue by WaBaX** [CrocoBlock/suggestions#3907]
Hi, 

i created a huge form for my frontend user to create new advertisements on my marketplace. 
The marketplace compare between privat and business users. 
Business users can choose the branche of their business.
That means i have many different user roles which the marketplace has to handle with. 

While creating the new advertisement i have to show / hide content by the user role of the customer which is creating the advertisement.

Example: 
Business customer is allowed to add 3 Contact persons to the advertisement.
Privat customer is not allowed to add additional contact persons to the advertisement.

Business customer can not choose which contact details should be hidden. 
Privat customer can choose which privat contact details should be hidden on frontend.

The issue i face while creating the form is the following.
The conditional logic to show / hide content is using the css code "display: none;".

--> If my customer is knowing css a bit he can easily display the hidden content. 

For the function to create new advertisements it is not that much critical because the content isn´t confidational 
but if you work with more critical content it should be really hidden. 

Maybe you can find a different way to hide the content.

Thanks

**Comment by girafffee** [comment]
Already available in beta 3.0

![image](https://user-images.githubusercontent.com/46720998/213578502-fb97dae6-4bd0-40c3-a9e4-d5758fcbfc91.png)

https://github.com/Crocoblock/suggestions/issues/6408
