### ISSUE TITLE
Jet Smartfilter: Add 'show all' option for displaying portolio items and more

### ISSUE THREAD

**Issue by RodSuper** [CrocoBlock/suggestions#391]
Hi,

I'm using Jetengine combined with Smartfilter to display portfolios, blogs and teamcards. The filters can be nicely used to filter by blogcategory, type project and much more. However it's not really created for this purpose, but I believe a 'small' add-on can open up new possibilities.

I currently use radio buttons, but have to add a seperate 'show all' category in order to show all items in the listing grid.

I wish there could be an option to add a 'show all' option to the filter that is set to active when you load the page. That way we can also use this filter in a modern style portfolio.

![IMG_20190725_212433](https://user-images.githubusercontent.com/47865142/61902644-d5aacc00-af22-11e9-937d-6cec25568b35.jpg)

Hope you get the idea.

Thanks in advance,
Rod

**Comment by Floydtm** [comment]
@RodSuper, Hi! Soon we plan to release a plugin release. A new module "clear all filters" will be available. This will help solve your case. Thanks for the feedback!

**Comment by RodSuper** [comment]
@Floydtm Great, look forward to it :) Thank you
