### ISSUE TITLE
Listing grid item be clickable itself when Map listing popup is enabled

### ISSUE THREAD

**Issue by Sheena-Dhingra** [CrocoBlock/suggestions#3911]
Hi, I have created a map listing using JetEngine Map listing. Link to the page: https://orioninnovationhomes.com.au/properties/. On my page, there are two listings (Map Listing on left and simple listing grid on right) And have used the functionality, when we hover over the listing item (on right), it pop-up in the map(on left). This is working but the listing itself has a link (A Dynamic link linked to the detail page) that link is not getting clicked. "Make listing item clickable" interrupts the dynamic link widget. I want links in the listing to be clicked as well. Without this feature, I believe the Map listing has no benefits. 

Link to the page: https://orioninnovationhomes.com.au/properties/
Also have attached a screenshot to quickly show you the dynamic link part. Please see if we can come up with a solution. Thank you in advance.

![image](https://user-images.githubusercontent.com/89901379/131630930-a8871bc8-794a-4c72-85b7-52b6db1cc96b.png)

**Comment by kaskad88** [comment]
Fix for the next version. Thanks for your report!
