### ISSUE TITLE
crocoblock for easy digital download

### ISSUE THREAD

**Issue by zuhdi-in** [Crocoblock/suggestions#3912]
Hello
I was expecting crocoblock to also make plugins like "JetWooBuilder", but this time not for WooCommerce but for Easy Digital Download

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
