### ISSUE TITLE
[JetWooBuilder] Ability to apply a single product template to all single items within a product category

### ISSUE THREAD

**Issue by StevenVanWingerden** [CrocoBlock/suggestions#3913]
Hi,

It would be great if we can apply single product templates to all products within a product category, instead of having to manually select the template within each product.

Kind regards,
Steven

**Comment by UraraReika** [comment]
I merged this issue with #2540, which is on the same subject so we could deal with it more efficiently.

**Comment by rtpHarry** [comment]
I've implemented a version of this, as a plugin, which lets you assign product single templates based on the product category:

https://github.com/rtpHarry/jet-woo-builder-category-custom-product-template

It adds configuration options into the WooCommerce Product Category taxonomy to let you select the "product single" template to apply to all products with that category.
