### ISSUE TITLE
JetEngine - Listing "make listing clickable" pointer is missing

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#3915]
In the latest JE update, the Listing option **"make listing clickable"** dont show the pointer cursor in the listing grid. (btw the content clickable).

**Comment by kaskad88** [comment]
Hi @Lonsdale201. We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.

**Comment by Lonsdale201** [comment]
> Hi @Lonsdale201. We tried to reproduce your issue based on the information you provided, but without success.
> Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
> 
> Thanks.

Ahh really, the problem cause my code. Sorry, i resolved :)
