### ISSUE TITLE
Notify Me When Back in Stock for WooCommerce Products

### ISSUE THREAD

**Issue by hempaware** [CrocoBlock/suggestions#3916]
It would be great to have a feature where we can have a button/field that says NOTIFY ME WHEN BACK IN STOCK, for any products that are out of stock. And the person just enters in their email address and get's an automatic email once the product is back in stock. There are obviously other plugins that do this, but having more features in one place is always better as you know! Thank You!🙏👍

**Comment by UraraReika** [comment]
Hello @hempaware !

Unfortunately we do not plan to introduce such functionality into our plugin. But you can use one of third party plugin solution like [this](https://wordpress.org/plugins/back-in-stock-notifier-for-woocommerce/). Or from official site like [this](https://woocommerce.com/document/back-in-stock-notifications/). Our plugin has all the compatibility functionalities and everything should be okey. 

Feel free to [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
