### ISSUE TITLE
Compatibility of Fields manager feature for Checkout Billing & Shipping forms with hello elementor theme / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3918]
Hello @UraraReika  good time👋

The feature of managing payment fields is great, but unfortunately it is not compatible with the hello elementor format. This means that we have to write css in order to have list fields, such as city or province. While many users do not have the ability to write css.
https://prnt.sc/1r0m0pr
Most jet woobuilder users use the hello elementor template. Not being able to have a proper list field is a big hassle. **Currently, we can only style text fields such as name, contact number, company name, etc., but there is no option to edit the list fields.**

Please add settings so that we can style the list fields separately. Settings such as: padding, border, background, border radious.
These are very important. Please review them if possible.
I have written about this before. This time I tried to explain the request more clearly. I hope you approve.

thank you🌹

**Comment by UraraReika** [comment]
I merged this issue with #3793, which is on the same subject so we could deal with it more efficiently.

**Comment by 79ho3ein** [comment]
Thank you
