### ISSUE TITLE
Add Strong Passord Creation In Password Recovery, Registration and Change Password

### ISSUE THREAD

**Issue by CZEG-FIR** [CrocoBlock/suggestions#3921]
JetBlock - It surprised me that this option is not available in the Login, Password Recovery and Register.

Put the functionality in to ensure a user uses strong passwords. Such as Number Of Characters, Upper Case, Lower Case, Numbers and &%#* etc. This should be selectable as part of the widget by the form creator. The user should be informed as to what is required and when the password is not strong and therefore the password is not acceptable, and the user is forced to reenter the password until such time as the password is"strong".

**Comment by nreljed** [comment]
I observed this difficulty while trying to [recreate](https://github.com/Crocoblock/suggestions/issues/3080)
Add new user form wordpress with
the jetengine forms.

the idea is also to allow a predefined role
to access this special form and to be able to create users without going through wordpres backend. it just lacks the possibility of a select> choose roles.

as users are never careful with their password it creates security problems

for the password field, it's a simple js to integrate

now you have to know which one is the best

[Password Strength Validator UI](https://codepen.io/nat-davydova/pen/yLyXogO)

[jQuery Password Requirements](https://www.jqueryscript.net/demo/validate-password-requirements/)

[Passtrength.js](https://adri-sorribas.github.io/passtrength/)

**Comment by StevenVanWingerden** [comment]
+1

**Comment by MolyMalon** [comment]
I am super interested in this functionality and also in giving the possibility to the user to choose their own user role as well....

**Comment by RibeiroM4E** [comment]
JetEngine Forms and JetFormBuilder need to have this functionality. I don´t know why they didn´t add it since the beginning, as Wordpress has it, so maybe it would be a matter of linking it to the forms when you choose a "Text : Password" field type.

https://code.tutsplus.com/articles/using-the-included-password-strength-meter-script-in-wordpress--wp-34736

https://www.thecodehubs.com/how-to-add-password-strength-meter-in-wordpress-or-woocommerce-registration-form/

![Screen Shot 01-17-22 at 11 10 PM](https://user-images.githubusercontent.com/68911365/149859656-22fc0644-0d80-46b0-840e-b84a933ee439.PNG)

**Comment by RibeiroM4E** [comment]
This could be added to JetFormBuilder and JetEngine Forms as well.

**Comment by kaskad88** [comment]
Add in JetBlocks v1.3.3

**Comment by rlb222** [comment]
> This could be added to JetFormBuilder and JetEngine Forms as well.

Yes please, because I use JetFormBuilder to register. I use JetBlocks to reset password.

I don't think this item should be closed as only JetBlocks has been changed for this.

**Comment by jzelle** [comment]
@RibeiroM4E thank you for the suggestions. I was able to make this work for JetFormBuilder!
@rlb222 , @MolyMalon : perhaps you can use this if you still need a solution :) .

My code has been published here: https://github.com/jzelle/crocoblocks-jetformbuilder-passwordstrength
