### ISSUE TITLE
#JetSmartFilters: Add support to filter #JetEngine REST-API Listings

### ISSUE THREAD

**Issue by oceandiveloper** [CrocoBlock/suggestions#3922]
I use REST API Listings to display content managed on website 1 to be displayed on website 2. On the original website I was able to use the JetSmartFilters plugin to filter the CCT listings in the front-end.

On the second website though I cannot filter the REST-API listings. It would be a great addition for the user-friendliness if we could filter the REST-API listings in the front-end via JetSmartFilters! I already asked on the Facebook group and was told that this is impossible. Please add this feature.

**Comment by BaronVonDerpsalot** [comment]
+1

**Comment by borispoehland** [comment]
+1 please include this if possible

**Comment by Lucky5111** [comment]
+1

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by ssoronid** [comment]
+1

**Comment by Moncho73** [comment]
+1

**Comment by rafaelsiek** [comment]
+1
