### ISSUE TITLE
Deactivate "Custom-PostType-Link" in Breadcrumb

### ISSUE THREAD

**Issue by Ca-Ty** [CrocoBlock/suggestions#3923]
Hi there at Crocoblock,
I wondered how to deactivate the "Custom-Post-Type-Link" in the Breadcrumbs: As "Default", the bradcrumb-Element diplays the Name of the CustomPost-Type. 

I learned from the crockoblock-Support that this is impossible. 

As you know, Breadcrumbs are both - an important component for navigation on page - and a really relevant part for onpage- SEO-optimization. 

There is no reason why the user / visitor should have the acces to this at least technical workspace & background area. And as the user has this access, we should have to build a kind of page for this at least - which we won-t, because it makes no sense. Effectively, this means we can not activate the Breadcrumbs.  It coud mislead and confuse the Visitor. As so, it affects the user experience and the search-engine-performance - and as such the success of the page. 

I hope, this shows you the importance of this issue - and how important this is to be fixed soon. 

Thanx

**Comment by Gawuww** [comment]
Added in JetBlocks v1.3.2
