### ISSUE TITLE
The Center Mode function in the Listing grid

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#3925]
Add the Center Mode function to the listinggrid for the carousel
This function is available in the Products Grid widget
It does what it adds half-formed pictures at the edges..
![222](https://user-images.githubusercontent.com/47380983/132021258-2034aa0d-b35c-4d65-b856-976187d0d11e.png)

**Comment by kaskad88** [comment]
Add for the next version ( 2.9.3 ). Thanks for your report!
