### ISSUE TITLE
JetForm Builder - OR operator for Conditional Logic

### ISSUE THREAD

**Issue by GinaHTC** [CrocoBlock/suggestions#3929]
Form field conditions are incredibly hard to deal with. We really need the option to use an OR operator. Is there any chance this will be added (soon preferably).

**Comment by davispe** [comment]
Are we ever going to see OR statements for conditional logic?

**Comment by girafffee** [comment]
Already available in beta 3.0
https://github.com/Crocoblock/suggestions/issues/6408
