### ISSUE TITLE
[JetBooking] -  hourly basis rent

### ISSUE THREAD

**Issue by mrroy119** [CrocoBlock/suggestions#3935]
**This is one of the biggest problems in rentgo, jet booking plugin** 
that there is no feature to calculate the car rent on an hourly basis 

and I don't know why this thing is still not in the booking plugin?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1597, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
