### ISSUE TITLE
Add Support for the Divi Theme Builder

### ISSUE THREAD

**Issue by CptSugarFree** [CrocoBlock/suggestions#3937]
Divi and Elementor are definitely in the top when it comes to theme builders and I know if your plugins were made available to the Divi market pretty much everyone would start using them. When it comes to divi plugins it's a bit of a scattered mess for things like bookings, events, etc. The power of your core Jet plugins mixed with appointments, bookings, reviews, woocommerce, etc. would be a massive unification for many companies and freelancers that would help save a ton of time and provide an easier method of building websites.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
