### ISSUE TITLE
Ability to transform the product item in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3939]
hello

It would be great if you could add the transform (x-y) feature in the hover mode to the product item (product grid widget).
![Screenshot (141)](https://user-images.githubusercontent.com/77163248/132321827-ce7ff6f7-8ec8-4fe1-a484-0420d4b9f3b7.png)

Using this feature, we can determine how much it moves up or down when the product item is **hovering**. (transform x-y)
Another thing that is important in this feature is the ability to determine the **speed of the transform.**
Please see an example of this feature in the video below :
https://drive.google.com/file/d/1GnKMp-y4nxngTy5x2XYc_jhZvR9Gk_yH/view?usp=sharing

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Sorry but this type of style controls will not be added.

**Comment by 79ho3ein** [comment]
thank you🌹
