### ISSUE TITLE
JetProductGallery - support gallery custom field for CPT

### ISSUE THREAD

**Issue by realstephenzhao** [CrocoBlock/suggestions#394]
JetProductGallery is much better than normal image slider widget.

If it can support gallery custom field(not just WooCommerce), that would be great.

I am using ACF pro to add gallery metabox to side position of editor of a custom post type such as _products_, hope there would be one day JetProductGallery can support it.

**Comment by Floydtm** [comment]
@realstephenzhao, Hi! At the moment there is no such functional. While we do not plan to do it. To output the dynamics, use the dynamic field widget in the plugin [jetengine](https://jetengine.zemez.io) and configure the [callback](https://documentation.zemez.io/wordpress/index.php?project=jetengine&lang=en&section=jetengine-dynamic-widgets#) you need
