### ISSUE TITLE
Image Size Setting on JetImageAccordion

### ISSUE THREAD

**Issue by Marc-Paul** [CrocoBlock/suggestions#3941]
Using the JetImageAccordion currently only allows for default sized images. The same image sizing option, that is available for other widgets using images, e.g. the default image widget, should be accessible to ensure persistent and optimized Image Sizing. 

Additionally using Imagify doesnt work with the JetImageAccordion, as the Images dont have a size class, they arent visible at all. 

Looks more like it was forgotten than excluded for a reason, as other Crocoblock Image Widgets feature this setting persistently.

**Comment by Gawuww** [comment]
Added in JetTabs v2.1.17
