### ISSUE TITLE
Show categories and subcategories

### ISSUE THREAD

**Issue by medusamarketing** [CrocoBlock/suggestions#3942]
We want to make a page and in the page we want to have the parent categories, when you click in one category we want to display the subcategories that belong to the parent category, and then when you click in the subcategory, we want to display the posts.

Best regards,

MEDUSA TEAM.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
