### ISSUE TITLE
Set an item booked for a certain date range in the admin panel (JetBooking)

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#3943]
Hi, We're a car rental companty using JetBooking.

We've necessity to allow also booking form external sources (e.g. phone call)

So we're looking for an easy way to mark some dates unavailables form the JetBooking backend.

**Comment by ghost** [comment]
We solved with a custom ajax snippet, i can share it with those interested but it's very rudimental and in testing phase

**Comment by peterloran** [comment]
Would be nice to have certain date ranged packages for certain rooms/products.

**Comment by UraraReika** [comment]
This issue was solved with 2.5.0 release.
