### ISSUE TITLE
Jet Woo builder needs to be more mobile friendly

### ISSUE THREAD

**Issue by Fjashaw** [CrocoBlock/suggestions#3945]
Jet woo builder should have a lot more style options when we are making our website responsive on mobile and tablet. With a massive percentage of the population shopping on mobile, it is important that we make their shopping experience as seamless as possible. Currently, I am not able to do this with the styling limits of the Jet Woo Builder. 

I am running into most of these limitations when building my cart and checkout templates. 

For example, the Cart Table Widget on desktop is in columns then on tablet and mobile it going straight to a stacked view which I have no control over and for some reason when viewing on tablet the thumbnail doesn't show but it shows again on mobile.

**Comment by 79ho3ein** [comment]
+1
It is true. The user interface of the shopping cart page is very disappointing in mobile size. One of its biggest drawbacks is that the product image is not displayed in the cart. (On mobile and tablet)
**This is a good example of shopping cart development in this plugin :** https://prnt.sc/1rlqtou
Please check these items. The plugin of this plugin needs to be expanded.

thank you
