### ISSUE TITLE
Jet Popup - Action to open Jetpop with dynamic tag

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#3949]
I would like to suggest an option to attach popup's as a link when made with jet popup, so you don't need to use it by the elementor pro, in case I'm using a hotspot widget and would like to attach a popup to each item to make the design more attractive.

Thank you guys

![image](https://user-images.githubusercontent.com/6773491/132789522-e57882e7-3c56-481a-b6d5-7bb45df2ce17.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
