### ISSUE TITLE
JetStyleManager breaking Gutenberg editor

### ISSUE THREAD

**Issue by oceandiveloper** [CrocoBlock/suggestions#3954]
I've just installed JetStyleManager to style me Gutenberg listings in JetEngine. First of all installing from Crocoblock Dashboard installs an old version 1.2.0 by default. I directly have to update to 1.3.0. Minor Issue but should be looked at.
Bigger issues: as soon as I activate the plugin and open the Gutenberg editor I get a criticial error. Only disabling the plugin helps to remedy the problem.
This is already the second website where this happened to me. Could we get that fixed please? JetEngine Gutenberg listings are super ugly by default and I don't want to use CSS for every minor tweak.
![CleanShot 2021-09-11 at 14 41 36@2x](https://user-images.githubusercontent.com/43462095/132939175-f7b874bd-26fa-4a36-9798-8ed61350793d.jpg)

**Comment by Floydtm** [comment]
Hi, check for an update for the plugin. The problem should go away. Thank you!
