### ISSUE TITLE
Link an specific Listing Grid Item to an Anchor?

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#3956]
Hi there,

Can you add the functionality to Link an Specific Listing Grid Slide to a Button for example? for example if you set the slider to have 10 results. Add a # to a button like #jet-listing-gird-slide-2 so when you click this button the referenced slide change to that specific slide?

This will be very practical for example having 

1 listing grid with categories
1 listing grid with categorias description on the right (with slider option enabled)

when you click 1 categories, the slider on the RIGHT changes to that specific result so we can design more advanced designs.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by maurocarreraok** [comment]
Hey Floyd

This can be doable with 
```

<script type="text/javascript">
(function($) {
  $('.jet-listing-grid--182').find('.jet-listing-grid__item').each(function (item) {
    var $selector = $(this);
    $selector.click(function() {
      $('.jet-listing-grid--415').slick('slickGoTo', (item));
    });
  });
})(jQuery);
</script>
```

Bringing up the code so this can be implemented.
