### ISSUE TITLE
JetEngine: CCT checkbox field >Add custom + Save Custom

### ISSUE THREAD

**Issue by lolirado** [CrocoBlock/suggestions#3964]
In CCT we don't have the option to Add custom and Save Custom checkbox value just jet.
Please add this to the features. Otherwise It's a no no for the lower user role.
![image](https://user-images.githubusercontent.com/25382055/133068557-5a52b90a-c203-42f2-bf05-56417db5ca26.png)

**Comment by kaskad88** [comment]
https://github.com/ZemezLab/jet-engine/tree/dev/cct-check-radio-custom-values

**Comment by lolirado** [comment]
**We had it ?**

**Comment by Floydtm** [comment]
Will be added in the next updates
