### ISSUE TITLE
Support wysiwyg field inside repeater

### ISSUE THREAD

**Issue by crypto-vault** [Crocoblock/suggestions#397]
Currently you can’t add a wysiwyg field inside a repeater like ACF Pro does. Ironically Jetengine supports displaying ACF wysiwyg fields which  are inside repeaters, with the dynamic fields widget, so why not support creating it too?

**Comment by chriswecreate** [comment]
+1 for this

**Comment by norbertfogarasi** [comment]
+1

**Comment by yratof** [comment]
still no???

**Comment by kaskad88** [comment]
@yratof this feature was added a long time ago https://tppr.me/4VGKW https://tppr.me/GyjRZ
