### ISSUE TITLE
Simultaneous use of color and image in the visual filter of the jet smart filters plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3970]
hello
It would be great if we could use color and image for visual filtering at the same time. At the moment, we can only use one of these two, which puts limitations on us.
For example, I was importing a color filter for store watch straps. Some of the straps were in seven colors. But it was not possible to apply the image of seven colors next to the color. And that was a big limitation.
Of course, there are many examples to describe this limitation, but this one was enough to convey my point.
I think it would be great if you could combine color and image loading in the visual filter. In this case, there will be no restrictions on the application of the filter.

Thank you for your attention.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
