### ISSUE TITLE
autoplay to the product gallery

### ISSUE THREAD

**Issue by Dhaump** [CrocoBlock/suggestions#3971]
It would be great if you added an autoplay to the product gallery/gallery slider (for single product templates) so that the images move by themselves within the product itself

**Comment by UraraReika** [comment]
Hello @Dhaump !

For additional options like slider autoplay we provide filter hook `jet-woo-product-gallery/slider/options` so you can add any option you want according to [official documentation](https://swiperjs.com/swiper-api) .

Here is example:

```
add_filter( 'jet-woo-product-gallery/slider/options', '__your_theme_prefix_add_autoplay_to_gallery_slider' );

function __your_theme_prefix_add_autoplay_to_gallery_slider( $options ) {

	$options['autoplay'] = [
		'delay' => 500,
	];

	return $options;

}
```
