### ISSUE TITLE
colors of terms and conditions in the checkout

### ISSUE THREAD

**Issue by Dhaump** [CrocoBlock/suggestions#3972]
It would be great if you could change the colors of terms and conditions that appear in the checkout

**Comment by UraraReika** [comment]
Thanks for the feedback.
 Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/tree/master/.github/ISSUE_TEMPLATE), so we can help you better. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
