### ISSUE TITLE
custom fields in the single product / cart page template

### ISSUE THREAD

**Issue by Dhaump** [CrocoBlock/suggestions#3973]
It would be great if you could add the option to create custom fields in the single product / cart page template.

- For example: imagine a personalized article, which needs to write something to specify it in the variant, for example a word that is going to be engraved, on a shirt or a jewel as is my case. Ideally, a field will appear that is "comments or write your personalization here" and the client can write this in a field or in the single product template before adding to add to cart, or in the cart, a new box where specify what they want (in each product) not a common box at the end (which I know exists)

- Another thing that would be great would be to add the option to create a custom field of checkbox or radio filter or something like that, for example, imagine you have a shirt with variants (the attributes are type of fabric and color), you as a customer select the color and the type of fabric, but there is one more piece of information to add but it is not a common attribute for all clients, so do you create a yes / no box or with three options, for example, do you want customization? (yes / no), if you say yes, you will see the box that I said before writing your personalization here

-Also a field to choose an image that you upload as an attachment (it seems essential to me)

**Comment by Floydtm** [comment]
Hi! I understand that this is very important for you, but we cannot implement this because it depends not only on us. Right now you can add custom fields for a single product. But we will not be able to display it on the woocommerce templates.
