### ISSUE TITLE
custom fields to my account

### ISSUE THREAD

**Issue by Dhaump** [CrocoBlock/suggestions#3974]
It would be great if they could add custom fields to my account, for example:

Field of tracking numbers that are filled in by the store where each client in my account> my orders can see their order with one more column where they see the tracking number of their order and then they can copy or click on it, or a button and go to track your order to see where it is at all times

**Comment by Floydtm** [comment]
Hi! I understand that this is very important for you, but we cannot implement this because it depends not only on us
