### ISSUE TITLE
Conditional logic and comparison for booking forms

### ISSUE THREAD

**Issue by olyaastep** [CrocoBlock/suggestions#3975]
Hello!
It would be nice to add a feature for crocoblock Jet engine and booking plugins
when creating booking a booking form for the post type, add a feature to set amount of days available for booking. As there are different travel companies that offer packages for booking like (7, 10, 21 days options available)
for example, a user (client) can choose the duration of stay in a select field (options added by partner), and then only this period is available to choose in the calendar.
What's more the ability to set available days for check-in/check-out days would also come up in handy for this type of company (like camps, retreats and etc).
Another option to solve this issue may be the ability to create a field with the message "please choose the available duration" appear if a client didn't choose the previously set amount of days.
Thank you in advance, 
Best regards, 
Olya

**Comment by UraraReika** [comment]
I merged this issue with #1833, which is on the same subject so we could deal with it more efficiently.
