### ISSUE TITLE
Dynamic pricing option when selecting more than one product

### ISSUE THREAD

**Issue by Dhaump** [CrocoBlock/suggestions#3978]
*It would be nice if they added the dynamic pricing option when selecting more than one product in the single product template.
For example, there is a product that costs $ 18. You select 2 units in the counter and the total price of the two shirts appears before adding to the cart (2 x $ 18 = $ 36)

**Comment by Floydtm** [comment]
Hi! I understand that this is very important for you, but we cannot implement this because it depends not only on us.
