### ISSUE TITLE
Problem displaying Product title in Chrome browser / jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3981]
hello
A strange problem occurred on some of the sites I checked, which is as follows ...
When the site is fully loaded, the product title in the carousel is displayed incompletely. Of course, this problem does not occur for all products. Rather, the products on the right side of the carousel have this problem. **As soon as the mouse hovers over that product, the hidden part of the product title is displayed.**
I did a lot of research, but I did not find the problem.(For plug-in interference)
Strange, but this problem only exists in the Chrome browser (desktop). Displays properly in other browsers and even mobile.
To better understand the problem, please see the pictures below.

**After the website is fully loaded :**
![20210915_114853](https://user-images.githubusercontent.com/77163248/133425727-e9221d10-64f5-49b0-a558-ae505f87f6bb.jpg)

**After moving the mouse over that product, the title content returns to normal :**
![20210915_114906](https://user-images.githubusercontent.com/77163248/133425932-26ab3e19-705c-45ee-a279-1a33a2e8e087.jpg)

thanks for your attention🌹

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
Thank you
