### ISSUE TITLE
Jetmenu breadcrumbs

### ISSUE THREAD

**Issue by Enter-GWD** [CrocoBlock/suggestions#3982]
Is it possible to make Breadcrumbs clickable.

![image](https://user-images.githubusercontent.com/23224703/133452719-b2beec1c-d09a-47c1-8a45-95238b6f8805.png)

Thanks a lot

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
