### ISSUE TITLE
Listing Grid with several types of Listings

### ISSUE THREAD

**Issue by kugcmadushan** [CrocoBlock/suggestions#3986]
I would like to suggest the options to show several types of Listings in one Listing Grid. 

As an example, in some real Estate websites lands are also considered as properties. Though we can showcase Houses and Apartments in a single listing template with Number of Bedrooms and Bathrooms, the same listing template cannot be used for lands where it has different meta fields. 

If somebody wants to showcase all listings under one listing grid, enabling required filters to filter out as necessary, there is no such option as I got to know.

**Comment by TheBigBanik** [comment]
Hi my friend. Actually this is very easy to accomplish by using the dynamic visibility feature. I use it all the time. As a simple workaround do the followings (I will give you a real estate example). In your listing template add the appropriate widgets to display the bedrooms, bathrooms, floors etc. Then, in the advanced tab you will have to enable the dynamic visibility and set the conditions to show those elements if the post is not assigned to the Land taxonomy. A simple demonstration would be like that:
CPT=Properties
Meta fields= Area / Bedrooms / Bathrooms / Floors / 
Taxonomies= Appartment / Villa / Office / Land
If you exclude the Bedrooms / Bathrooms / Floors meta fields visibility from Land, then in your listing grid you will have all properties with their desired visible meta fields.
I hope that helps.

**Comment by Floydtm** [comment]
Check out these tutorials, hope it helps you https://crocoblock.com/knowledge-base/articles/jetengine-dynamic-visibility-module-options-overview/ https://crocoblock.com/knowledge-base/articles/how-to-use-the-alternative-listing-template-functionality-in-listing-grid/
