### ISSUE TITLE
JetSmart Filter pagination additional provider option.

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#3990]
In a future possible to add the additional provider option for the pagination widget? 
If you use the jettabs for make variations listing option, every filter can work together, thanks to additional provider option, but with the pagination can't combination.  

![image](https://user-images.githubusercontent.com/23199033/133512012-4db841f5-4d3d-4dec-a394-830c420b7c97.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by Lonsdale201** [comment]
> At the moment, we do not plan to introduce such functionality into our plugin.
> Now our team is working on more priority tasks.
> But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

I completely understand.  And thank you if you will come back to this question later. ^^
