### ISSUE TITLE
jetwoobuilder compatible with individual elementor product

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#3995]
### jetwoobuilder
When you create an individual product template in elementor, the jetwoobuilder widgets don't appear. They only show up if you create it with woo page builder. It would be nice if they added the possibility of working in individual product with elementor.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
