### ISSUE TITLE
woo page builder, cart template

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#3996]
In the woo page builder cart template. In the cart table widget, in the style of table cells. The update cart button is aligned with the content of the cells, if you change any alignment.
![Captura de pantalla 2021-09-16 a las 12 45 26](https://user-images.githubusercontent.com/90837626/133599478-4afa88d1-6e3a-459a-a64c-d25498ee1c6c.png)

**Comment by 79ho3ein** [comment]
+1
