### ISSUE TITLE
widgets jetwoobuilder, elementor template single product

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#3998]
### jetwoobuilder
It would be nice if the individual product jetwoobuilder widgets could be used in the elementor product template. I see that they can only be used on the individual page of woo page builder.

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello @JuanCar29 !

JetWooBuilder sets of widgets will be only available on JetWooBuilder templates or compatible Jet plugins widget. If you want to use Elementors template then in this case they have their own sets of widgets.
