### ISSUE TITLE
Loading capability in the Add to Cart button / jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4002]
It would be great if you add the loading feature to the shopping cart button. This feature greatly enhances the user interface.
![20210917_022930](https://user-images.githubusercontent.com/77163248/133691898-8c59ee85-cdfd-4334-a79f-5da3d6c1efda.jpg)
Currently, when the user clicks on the Add to Cart button, he does not see a response to understand that his request is in progress.
This case is well implemented in Woodmart format. I hope it will be added to jet woobuilder as well.
**To better understand the request, please watch the video below. Loading works beautifully.**
https://user-images.githubusercontent.com/77163248/133692121-f871de6b-8fea-43b2-99ed-dd4ed03c4a95.mp4

Thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

If you enable this option https://i.gyazo.com/352567c89b4a8392817df9c063c3ba07.png then default woocommerce loading will be added.

**Comment by 79ho3ein** [comment]
thank you @UraraReika
