### ISSUE TITLE
JetFormBuilder - DOI double opt-in feature

### ISSUE THREAD

**Issue by xitromedia** [CrocoBlock/suggestions#4008]
The JetFormBuilder plugin should have a double opt-in feature for registering and updating users, and maybe for other post submit actions too. To do a double opt-in check for some user actions with privacy related data is mandatory in many countries. Especially in germany the law concerning that is very strict. 

Maybe it would be helpful to have this feature also for other post submit actions, to ensure it is an authorized and wanted action or input of data.

I wanted to substitute Gravity Forms with JetFormBuilder. Currently i use a custom double opt-in implementation in my theme for GF and DOI. Without this essential feature in JetFormBuilder i cannot do that substitution, and i think many other users wanting to change over need this feature urgently too.

**Comment by Lonsdale201** [comment]
+1

**Comment by alexanderpankart** [comment]
#2473

**Comment by girafffee** [comment]
Follow this issue https://github.com/Crocoblock/suggestions/issues/2473
