### ISSUE TITLE
Complete forms suite for comment , posts , users ..etc

### ISSUE THREAD

**Issue by UniSoftTeam** [Crocoblock/suggestions#401]
🔥🔥 Make custom posts layout as blog as in jetblog so I can display about 5 posts as blog magazine 
This feature available in jetblog so make an integration between both or add a separate feature in jetengine

🔥🔥 Posts , User , Comment Forms !!!
I think this make JetEngine eats all wp plugins on the the planet if u add abilty for frontend post publishing , user registering or editing posts or profiles Using custom built forms as user neads ♥️

🔥🔥 Comment forms and comments loop layouts .. if also you add a rating fiels to comment form with average shortcode + inegration with social login make this impressive

**Comment by MjHead** [comment]
All of these could be completed with JetEngine & JetFormBuilder plugins
