### ISSUE TITLE
Set Jalali Calender On booking form

### ISSUE THREAD

**Issue by zir4k** [CrocoBlock/suggestions#4013]
hi every body,
in a project we want to use jalali calendar on booking form setup by jet plugins ,we trying to install & use many persian date plugins for translate date but that's not work & and just published date on posts & front has been changed to persian date not datepicker on form , please give us help for resolve this problem ❤

**Comment by 79ho3ein** [comment]
+1

**Comment by web-elite** [comment]
I have the same problem ...

**Comment by mojtababouraghi** [comment]
Hi

Yes that's right

I have the same problem

Please add this feature.

Thanks.

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello everyone.

So for datepicker in our plugin we use this library https://github.com/longbill/jquery-date-range-picker. And this library doesn't support jalal calendar as it if. The only thing we can do in this situation is implement translation. Wiil you be okay with that?

Thank you for your understanding.

**Comment by 79ho3ein** [comment]
Hi @UraraReika , What is meant by implement translation?

**Comment by UraraReika** [comment]
> Hi @UraraReika , What is meant by implement translation?

I mean auto translate for this labels https://tppr.me/UOvOe

**Comment by 79ho3ein** [comment]
> > Hi @UraraReika , What is meant by implement translation?
> 
> I mean auto translate for this labels https://tppr.me/UOvOe

can be useful. Thank you

**Comment by UraraReika** [comment]
> Hello everyone.
> 
> So for datepicker in our plugin we use this library https://github.com/longbill/jquery-date-range-picker. And this library doesn't support jalal calendar as it if. The only thing we can do in this situation is implement translation. Wiil you be okay with that?
> 
> Thank you for your understanding.

As was said in this message datepicker library doesn't support jalal and unfortunately our team deside not to add auto translate because you just can simply use custom labels for this action.

Thank you for your understanding.
