### ISSUE TITLE
Display discount percentage on variable products / jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4014]
hello dear @UraraReika, good time.
I apologize for making this request again.As you know, the discount percentage on variable products is displayed as a range.For example (10% - 3%). I called the support team and they said there is no way to solve this problem right now. 
I saw a site whose variable products did not have this problem.
In this way, in the carousel of products, the lowest percentage of discount was displayed. (The image below)
![Screenshot (152)](https://user-images.githubusercontent.com/77163248/133909443-7b48286d-98a0-4c85-ac1b-7504ade1a2fd.png)
**But on the page of the same product, when we choose another color, by changing the color, the discount percentage of that product also changed.** In this case, the discount percentage is no longer displayed as a range.
To better understand the subject, please watch the video below :

https://user-images.githubusercontent.com/77163248/133909870-55aebc51-8fa4-4f51-abc4-5a57294e3fc1.mp4

As you can see in the video above, the product came in 6 different colors, but only one product had a 7% discount. **Currently, if we have these conditions in jet woobuilder, the discount percentage is displayed as follows : (0% -7%)**
**Excellent if the conditions are such that, by default, the lowest percentage of discount is displayed (in variable products). When the user enters the product page, with a change of variables, the discount percentage of each variable changes as Ajax.**
In this case, the discount percentage of variable products is no longer displayed as a range.
I hope I conveyed my meaning well. Unfortunately, at present, if we have variable products on the website, we can not show the discount percentage to users. Instead, we should use texts such as sales Which is not user friendly.
I hope this problem is solved once and for all in this plugin.

thank you for your attention🌹

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Use this snippet https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce.
