### ISSUE TITLE
JetWooBuilder - Ability to hide JetWooBuilder widgets if there is no value

### ISSUE THREAD

**Issue by azkalex** [CrocoBlock/suggestions#4017]
Please add an option to hide the widgets used on Single product pages like the Dynamic Fields in JetEngine.

![image](https://user-images.githubusercontent.com/60075863/133942322-d4984474-0cb8-4f1a-b128-43c783131cec.png)

This would allow for more complex layouts where the widgets get displayed only if the user inputs values in the product details.

![image](https://user-images.githubusercontent.com/60075863/133942186-b46469ea-44ff-4970-9f11-19193e59148e.png)

**Comment by UraraReika** [comment]
Hello @azkalex !

For this purpose use this [plugin](https://github.com/UraraReika/jet-engine-single-products-widget-custom-visibility-conditions).

You need JetEngine installed and this [option](https://i.gyazo.com/4d1ebde2ebadf7224648a1d777704d9f.png) enabled . Then in elementor editor under tab Advanced you will be able to see this [tab](https://i.gyazo.com/cfd8b3af34883d87cca19c6348775243.png). Just choose whatever condition you need.

**Comment by azkalex** [comment]
But why can't this be straightforward and be implemented the way it's in JetEngine since it's also your work?
