### ISSUE TITLE
JetEngine Post Expiration

### ISSUE THREAD

**Issue by kugcmadushan** [CrocoBlock/suggestions#4021]
Appreciate anyone could assist on this !

JetEngine is an awesome plugin for listings. I am a non - developer and thanks to this awesome plugin I am creating listing websites so easily. Something I could not figure out is a way for post expirations. 

There is a tool under Dev tool and I have no idea hot it should be setup. Unfortunately not a single video on this available. Further, I posted the issue on several FB groups and nobody was able to answer. 

Any kind soul help me to get this done please. As mentioned earlier I am a non developer and zero experience in coding.

**Comment by JuliaKiselyova** [comment]
The option will work for the newly-created posts. The old ones that were added before you uploaded the new version of the addon won't work. Example:
In the ADD new Post Form, you will have a new option https://prnt.sc/1syhko2. Here you can decide whether to move this post to trash or to draft.
So all you need to do is to create an Add Post form and check this option there:) 

Let me know if you have any questions:)
