### ISSUE TITLE
JetBooking - Units Available or book 2 or more units at the same time

### ISSUE THREAD

**Issue by daniele77ba** [CrocoBlock/suggestions#4022]
Hi,
I'm working on a bike rental site, one of the JetBooking limits is that I can't rent 2 or more bike at the same time, so if a couple would like to have a tour they must use the form twice with the risk that the second one isn't available!

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5948, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
