### ISSUE TITLE
Normal , hover and disable mode, in the product grid widget / jet woobuilder plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4026]
hello, Thank you for the new update.

Prev Arrow Position and Next Arrow Position are now excellent. **But it would be great if you add Normal , hover and disable mode to these two sections.**
![Screenshot (153)](https://user-images.githubusercontent.com/77163248/134038900-2cb79c1a-a5d8-4b8f-b5fa-ba32b8badc56.png)
Currently, if we use Prev Arrow Position and Next Arrow Position, we have no control over Normal , hover and disable mode.
![Screenshot (154)](https://user-images.githubusercontent.com/77163248/134039043-e5698c7f-52eb-465b-ac4f-a0c5ead44dab.png)

thank you very much🌹

**Comment by UraraReika** [comment]
Hello @79ho3ein !

This types of controls will not be added.

**Comment by 79ho3ein** [comment]
thank you
