### ISSUE TITLE
JetWooBuilder - JetTabs - Pagination issue

### ISSUE THREAD

**Issue by azkalex** [CrocoBlock/suggestions#4028]
Hello, the pagination widget inside the JetTabs widget as a template doesn't work.

1. Create a page
2. Add the JetTabs Tabs widget
3. Create an Elementor template
4. Add the JetWooBuilder Product Grid widget
5. Add the Pagination widget below selecting the pagination for JetWooBuilder Product Grid and save it
6. Go back to the page where the tabs are, for one of the tabs select the newly created template
7. Do this 2 or 3 times to have 2 or 3 templates in the tabs widget, each template displaying a specific category as an example

Opening the page where the tabs are, you'll see that there's no pagination for the products in the tabs, BUT by opening each template you created, you'll see that the pagination shows up, it just doesn't show when it's inside the JetTabs Tabs widget on the page where it is. I tried having a unique query ID for the Products Grid and Pagination widgets on each template, yet it still doesn't show inside the Tabs.

I expect to see the pagination inside the tabs and be able to navigate through them.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by azkalex** [comment]
![image](https://user-images.githubusercontent.com/60075863/134174971-9e173922-a67f-4f93-a425-2a086deaae1e.png)

![image](https://user-images.githubusercontent.com/60075863/134175087-26713437-e6bd-4a4f-903f-5cfb382405d6.png)

Adding a query ID to widgets results in no pagination shown at all anywhere, not even in the ones that are not in tabs. Can you attach your working template?
