### ISSUE TITLE
Add Jet Woo Templates to Theme Parts

### ISSUE THREAD

**Issue by crypto-vault** [Crocoblock/suggestions#403]
If Crocoblock main plugin detects JetWooBuilder plugin is installed, it should add Jet Woo Templates inside a new tab called "Product" in "Theme Parts" in "Crocoblock -> My Library" so that all templates can be accessed in a single place.

**Comment by Floydtm** [comment]
@crypto-vault, Hi! At this moment, we cannot do this. There are clients who use the plugin without theme core and who do not have the template part library. Additional code will overload the jetwoobuilder plugin
