### ISSUE TITLE
Checkout billing form, jet woobuilder

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#4030]
After installing the WC - APG plugin NIF / CIF / NIE field that adds a field to the checkout.
It only shows it if I deactivate the modify fields of the checkout billing form widget. If I activate it, I can't add it. I command the captures.
![Captura de pantalla 2021-09-21 a las 11 59 36](https://user-images.githubusercontent.com/90837626/134152649-6708330e-ae68-47d1-a96a-98d44f03737b.png)
![Captura de pantalla 2021-09-21 a las 12 00 04](https://user-images.githubusercontent.com/90837626/134152651-eea9e3af-4ee3-4949-8a8d-ce260f96ad18.png)

**Comment by UraraReika** [comment]
Please follow guidelines for opening a new [bug report request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
