### ISSUE TITLE
Connected users to be able to register other users from a front-end form

### ISSUE THREAD

**Issue by AliSMT** [CrocoBlock/suggestions#4031]
Hi,
I would like connected users to be able to register other users from a front-end form (accessible from my account space for example). I created a form and I configured the notification "Register new user" however it does not work when a user is connected, after several tests, it only works when no user is connected.

This is not possible because by default WordPress doesn’t allow registration for already registered user.

Here is a sample application :
I have a community. And a user group A has the right to create users. Workflow: user contacts user group A, with the request to create an account for it. Users of user group A then register the user completely new in the system from their member account.

**Comment by nreljed** [comment]
[#3080](https://github.com/Crocoblock/suggestions/issues/3080)

**Comment by Floydtm** [comment]
It's available right now https://prnt.sc/1t7j7rz
