### ISSUE TITLE
JetEngine/JetSmart Filters - Add Availability Calendar and Search By Start/End Dates

### ISSUE THREAD

**Issue by darylbowers** [Crocoblock/suggestions#404]
Add a searchable/filterable Availability Calendar for accommodation listings website (holiday rentals) with multiple properties. Each property (CPT Post) requires its own calendar.

Need the ability to update the booking status of dates in calendar for each property without taking a booking through the website, as customers use multiple listings platforms and may take bookings on other platforms or by phone and need to update the calendar.

Add JetSmart Filter to list only properties that are available between the selected dates.

See: https://www.phpjabbers.com/availability-calendar/ for a calendar example - I use this through Brolmo, but I would love the ability to have it built in to wordpress/jetengine and to filter based on availability.

Thank you!

**Comment by darylbowers** [comment]
Here's my current JetEngine-driven page that I'd like to add a date filter to:

https://wellsguide.com/where-to-stay-in-wells-next-the-sea/holiday-cottages/

And here's an individual property showing an availability calendar:

https://wellsguide.com/holiday-cottages-wells-next-the-sea/apartment-one/

Thanks

**Comment by ilyakar** [comment]
@darylbowers I see you got it to work. How did you manage this?

**Comment by darylbowers** [comment]
I didn't!

I used a third party availability calendar from PHPJabbers and wrote my own
plugin/application in PHP/javascript.

**Comment by MjHead** [comment]
Can be done with JetBooking plugin
