### ISSUE TITLE
Slider Widget: Add Color option for both navigation, padding option instead of box-sizing and also provide some more effect

### ISSUE THREAD

**Issue by syed-majid-akhtar** [CrocoBlock/suggestions#4042]
Hi, Crocoblock

Kindly,
1. add a Color option for both navigation so we can easily apply different colors for both navigations.
2. add padding option instead of box-sizing so we can easily manage the different sizing of the navigations.
3. provide some more effects rather than fade and slide.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
