### ISSUE TITLE
Ability to create a template for single WooCommerce orders endpoint

### ISSUE THREAD

**Issue by StevenVanWingerden** [CrocoBlock/suggestions#4046]
Hi,

![image](https://user-images.githubusercontent.com/39831934/134650530-889ec3bb-9482-4c97-baa5-15b8c50b5cbc.png)

I think it's great that we can create templates for Woocommerce endpoints, but I would find it really great if we can also create templates for Single Woocommerce Orders endpoint. So that if a user clicks to view an order, we can create a template for that instead of the default Woocommerce template.

Kind regards

**Comment by UraraReika** [comment]
I merged this issue with #2721, which is on the same subject so we could deal with it more efficiently.
