### ISSUE TITLE
JetWooBuilder - Categories grid conflict with Epro Imporeved asset loading

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#4048]
**Describe the bug**
Elementor experimental features: Improved asset loading cause issue with the JetWooBuilder Categories grid widget.

Results without **Improved asset loading** :
https://prnt.sc/1tgt6u3

Results if Improved asset loading active:
https://prnt.sc/1tgtfoa

**To Reproduce**
1, Place a JetWooBuilder Categories grid widget
2, Activate the Improved asset loading feature
3, Categories grid carausel mode enabled /+/ Free and Infinite loop also

**Config: **
Theme: Kava
Elementor pro v 3.4.1
Elementor v 3.4.4
JetWooBuilder v 1.10.3

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!
