### ISSUE TITLE
Problem displaying border tables in the shopping cart tab / jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4051]
hello
I previously reported this problem on the payment slip (#3904), which was fixed in the latest version.
But there is also this problem in the shopping cart tab.Both on the desktop and on mobile. The image below clearly shows that the marked part is not equal to the other parts.
![Screenshot (155)](https://user-images.githubusercontent.com/77163248/134723281-ab2fdeb3-a1b2-4122-9265-dcf2cd117a3a.png)
Please test the shopping cart on mobile as well. This problem also exists in mobile. 

Thank you very much

**Comment by UraraReika** [comment]
Fixed on desktop. But if we talking about mobile view in this case you need change border styles in mobile breakpoint to achieve needed results. Desk - https://i.gyazo.com/06b8a54101a0a217a67a2331676db696.png, mob - https://i.gyazo.com/e5df145aafa08a60c3e355a8ae69948d.png.

**Comment by 79ho3ein** [comment]
thank you.
I thought it would inherit the amount of margins from the desktop.
