### ISSUE TITLE
Ability to query WooCommerce cart contents 

### ISSUE THREAD

**Issue by Rubendj1** [CrocoBlock/suggestions#4052]
I would like to be able to query the WooCommerce cart contents so that you can build a custom cart grid.

**Comment by UraraReika** [comment]
Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
