### ISSUE TITLE
 In the WOOCOMMERCE BESTSELLER widget,  put a specific ARCHIVE to show the results

### ISSUE THREAD

**Issue by Dhaump** [CrocoBlock/suggestions#4056]
I would like to have the possibility to customize the appearance of the WOOCOMMERCE BESTSELLER widget to put an ARCHIVE that shows the results. I have spoken with the technical support and they have told me that there is no possibility and that I would propose it as a feature in github. https://prnt.sc/1tgq1gz

**Comment by UraraReika** [comment]
Hello @Dhaump !

You can create Archive Products template with the help of JetWooBuilder and set it like this https://i.gyazo.com/0accb50b64d6cc503c57c809ef3f1472.png.

**Comment by Dhaump** [comment]
@UraraReika but how do I put that shortcode template to appear in the bestseller woocommerce widget? Should I put some shortcode inside the widget?
