### ISSUE TITLE
Email notifications not working

### ISSUE THREAD

**Issue by OmarElFakih** [CrocoBlock/suggestions#4058]
**Describe the bug**
I am making a booking website (https://datobienestar.com/studenpatrova/) and I added a send email notification to the booking form, while the form is succesfully storing the booking information in the data base it is not sending the notification email that I added

**To Reproduce**
1. Go to https://datobienestar.com/studenpatrova/
2. Book any room from any of the 2 houses available (no payment is required for this step)
3. recive no email notificatoin about your booking

**Expected behavior**
Recive an email notification describing the booking you just did

**Screenshots**
![bookingForm2](https://user-images.githubusercontent.com/49835178/134784209-5051c009-ba18-4862-a0f5-6e89c0afd3ba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
I've already watched various tutorials but I can't seem to replicate their effects

**Comment by Floydtm** [comment]
Hey! We've checked everything and everything seems to be working correctly. However, our sites can be customized in different ways. To resolve your request, please contact our support team. Thank you!
