### ISSUE TITLE
JetSmartFilters and Products Loop

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#4063]
Hello.

It looks like Jet Smart Filters does not work with the Products Loop widget from JetWooBuilder, or am I wrong?

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by serg-pervushin** [comment]
Unfortunately, I can't contact support, the plugin was activated by a friend.

This is strange, because filtering works for all widgets (JetEngine Listing, Product List, etc.), except for Products Loop. To be honest, I don't even see a filter for this widget.

![2021-09-27_09-53-43](https://user-images.githubusercontent.com/37971764/134859229-1b10c1f2-6a7d-4dc4-9455-6f53bef0553c.png)

**Comment by UraraReika** [comment]
WooCommerce Archive (by JetWooBuilder)

**Comment by serg-pervushin** [comment]
I'm an idiot. It works. Thanks)
