### ISSUE TITLE
Ability to call for price in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4064]
Hello
It will be great, if you add a feature to this plugin, so that if we do not set a price for the product (the price blank), the desired text will be displayed instead of the product price. For example, call.
This feature will be extremely useful. Especially for product grid widget
By adding this great feature, custom text (call for price) will replace the empty product price. The only thing needed to customize this text (call for price) are typographic settings, and text color.
Please review this request.

Thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

For such functionality you can use filter hooks. Like this for price `jet-woo-builder/template-functions/product-price` which take price_html.

**Comment by 79ho3ein** [comment]
Thank you
