### ISSUE TITLE
Jet woobuilder plugin interferes with wp-rocket (If use the Recently Viewed feature)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4067]
hello @UraraReika, good time!
The Recently Viewed feature in the product grid widget interferes with the wp-rocket plugin. In a way that can not be used at all.
I contacted wp-rocket support, they asked me to see where the problem is, so that they can fix it (in their own plugin)
How can I see exactly where the problem is?
This interference is such that if we see one product, 3 products will be added to the list. Or not added at all ...

thank you

**Comment by UraraReika** [comment]
We use `woocommerce_recently_viewed` cookie to get recently viewed products.

**Comment by 79ho3ein** [comment]
thank you very much🌹
