### ISSUE TITLE
JetWooBuilder - Product Grid and List additional feature request

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#4068]
in the future, it would not be a bad idea to include the following additions in the Product grid, and List widget

1, Rating - Show if empty
2, Rating - If over the mouse show a count in simple tooltip ( https://prnt.sc/1tth0oq )

Thanks in advance :)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
