### ISSUE TITLE
Ability to design the "Product not found" page for the product grid widget in the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4071]
hello
It would be great if you add a "Product not found" page design to the product grid widget. Just like the ability to design an empty shopping cart page, which already exists in this plugin.
The image below is a product carousel designed with a product grid widget :
![Screenshot (160)](https://user-images.githubusercontent.com/77163248/134972138-4850c04d-a1d1-4f39-859f-7964092e81c4.png)
Currently, if the product is not displayed, only the text Product not found is displayed. Which severely damages the user interface  :
![Screenshot (159)](https://user-images.githubusercontent.com/77163248/134972574-20117d95-f0f4-455f-a464-d0b20607921d.png)

But if you add this great feature, we can design an attractive "Product not found" page. (Like the picture below) and this is fantastic.
![Screenshot (161)](https://user-images.githubusercontent.com/77163248/134972768-0d053896-8c65-4b4f-9d7f-fdb6a4f1a886.png)

Please check this. Thank you🌹

**Comment by UraraReika** [comment]
We update output of not found message in Products Grid and Products List widgets so now you can use filter hook to print needed template.

Create your template with the help of Elementor Page Builder. Then go to templates and copy template shortcode https://i.gyazo.com/ba1026d868588b5d5c6a8f9c102213b2.png and put it in widget Nit found message input like this https://i.gyazo.com/9006a1575356bd12f482d91a4447b6a2.png. Although use this code snippet:

```
add_filter( 'jet-woo-builder/shortcodes/jet-woo-products/not-found-message', function( $message ) {
	
	$message = str_replace( '&quot;', '"', $message );
	
	return do_shortcode( $message );
	
} );
```

P.S. Next release.
