### ISSUE TITLE
Multivendor Marketplace Woo commerce 

### ISSUE THREAD

**Issue by Eire1181** [CrocoBlock/suggestions#4073]
Would love to see Users/vendors be able to input their own woocommerce products for their pages.

**Comment by UraraReika** [comment]
Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
