### ISSUE TITLE
Enable repeater field data connection for JetTabs and allow dynamic population

### ISSUE THREAD

**Issue by remygfx** [CrocoBlock/suggestions#4074]
**Please, describe the feature request, making it clear to understand.**
The ability to populate accordion widgets  in the faq style is already available for ACF Pro users though none of the available products support JetEngine to date

**Add an example of where this feature is already implemented. **
https://youtu.be/Mq_C0-cYf-M
and here:
https://www.elementoraddons.com/tutorial/using-acf-repeater-fields-for-creating-dynamic-accordion-in-elementor/

An FAQ page is a becoming a consistent requirement with my web dev clients. The current solutions such as Helpie FAQ are not very robust. I am trying to determine if another developer who appears to support JetEngine has a workable solution as Crocoblock has yet to provide such functionality (see https://pafe.piotnet.com/ ). Being able to connect accordion tab titles and text content in the tab area to repeater field data is a major requirement as something like FAQ sections have a non-specific number of items and are constantly growing.

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/jetelements-dynamic-data-addon-how-to-use-dynamic-values-in-the-jetelements-widgets/ this plugin is tabs compatible
