### ISSUE TITLE
Listing item popup can't be closed in map listing - JetEngine

### ISSUE THREAD

**Issue by edgaraccount** [CrocoBlock/suggestions#4077]
hello Crocoblock team, i found a little bug. I noticed that the listing popup for the map listing in JetEngine cannot be closed. the x-icon is not working for some reason. Incidentally, it does not matter whether the setting of the listing is whether the item should open in a new tab or not, or whether it is clickable at all. the popup close button therefore generally does not work for listing popups in jet engine maps. Here is a short video about it:

https://user-images.githubusercontent.com/86965458/135106649-5d0b2485-a71b-4438-863a-dd9491cdbbac.mp4

**Comment by edgaraccount** [comment]
> hello Crocoblock team, i found a little bug. I noticed that the listing popup for the map listing in JetEngine cannot be closed. the x-icon is not working for some reason. Incidentally, it does not matter whether the setting of the listing is whether the item should open in a new tab or not, or whether it is clickable at all. the popup close button therefore generally does not work for listing popups in jet engine maps. Here is a short video about it:
> 
>  bug-map-listing-popup-close-function.mp4

**Comment by Floydtm** [comment]
Hi! We have checked everything and everything is working fine. Could you please contact our support team to resolve this issue. Thank you!
