### ISSUE TITLE
Border problem in cart total widget / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4078]
hello
I apologize for reporting this problem again. But this time I want to explain the problem in the form of a video. To be better revealed. **Please watch the video below :**

https://user-images.githubusercontent.com/77163248/135172055-2635b6e6-ac8e-4927-9e34-81fd716307be.mp4

As you can see in the video above, the cart total widget on the tablet and mobile was set to 1 pixel, but it was actually much wider. Up to 2 pixels. Even when I set it to zero, there was still some border. 
In fact, Border values ​​in the cart total widget have a problem. So that if we give it a border of 1 pixel, its thickness will be like 2 pixels.

**In the image below, both areas have a 1 pixel border. But do you feel the difference in border thickness in the cart total widget? **
![Screenshot (162)](https://user-images.githubusercontent.com/77163248/135172924-c90cb9fa-c8a8-4d59-b958-7a50942977b7.png)

I apologize again for repeating this issue

thank you

**Comment by UraraReika** [comment]
Complete with latest release.
