### ISSUE TITLE
Availity to select number of rooms (room quantity) in jet booking 

### ISSUE THREAD

**Issue by Techuapp** [CrocoBlock/suggestions#4080]
One basic feature missing, the Number of rooms (Room quantity) not available in Jet Booking. A user only book a single room at one time which is not good because if any user wants 2 or 3 rooms in the same hotel then what does he/she do? will he/she create a new booking for another room in the same hotel?

**Comment by Floydtm** [comment]
I understand that this is important to you, but we cannot implement it right now. However, you can create multiple units and book them for the same date. https://crocoblock.com/knowledge-base/articles/how-to-manage-units-via-the-wp-dashboard/
