### ISSUE TITLE
Crocoblock independence - Stop relying only on Elementor

### ISSUE THREAD

**Issue by Theo789595** [CrocoBlock/suggestions#4081]
I know this is hard as it needs a lot of work to be done but independence is a must as crocoblock evolves. 

Solely relying on elementor is just holding the plugins back. Crocoblock only refers to people wishing to build with elementor making it completely unavailable to developers that don't use the page builder (for good reasons).

Of course, you can't do this to all plugins as some are meant to work with dependecy to page builder. Start updating plugins that would work pretty well standalone like jetsmartfilters. There is no reason for that plugin to only work with page builders...Make it available to entire wordpress (use with shortcode to place filters anywhere).

The need to use crocoblock further without dependency on page builders is important to many people already using crocoblock plus you can bring a lot more people in crocoblock.

**Comment by Floydtm** [comment]
At the moment, the filters are compatible with both Elementor and Gutenberg https://prnt.sc/1u3klqk This gives the user a choice. As for the other builders, we have no plans to make compatibility with them. Thank you!
