### ISSUE TITLE
Jet Engine: Option on custom post types to hide the "Name: " string that shows up by all the labels/descriptions

### ISSUE THREAD

**Issue by Ssendam0101** [CrocoBlock/suggestions#4084]
For an end user filling in a custom post type, seeing "Name: " is not really necessary. It would be great if there was a way to hide this so that the users didn't see it.

**Comment by Floydtm** [comment]
Could you add screenshots or videos to your request. Thank you! You may have overlooked these settings when creating a custom post. https://prnt.sc/1u3me6a

**Comment by Ssendam0101** [comment]
Hello - that link didn't seem to work for me when I tried viewing it. This is what I was trying to hide though:

![image](https://user-images.githubusercontent.com/71953159/135546680-ba3d1293-5b90-4ce0-b4c4-be7d6d43c582.png)

**Comment by kaskad88** [comment]
I merged this issue with [#5625](https://github.com/CrocoBlock/suggestions/issues/5625), which is on the same subject so we could deal with it more efficiently.
