### ISSUE TITLE
JetEngine Dynamic Field: Title Trimmed for dynamic field

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#4090]
I want to control the length of the post title. I see it appearing in the post widget but in the Dynamic Fields section I can't find it.
![image](https://user-images.githubusercontent.com/89138954/135374986-7f665900-7db1-4622-a216-0e42d4c69d01.png)
![image](https://user-images.githubusercontent.com/89138954/135375027-4df6f4dd-3101-43a1-86c5-9f429ff24ae8.png)

**Comment by ZemezLab** [comment]
Hi @taidang26. Enable the Trim string callback module https://prnt.sc/1u6wa2g, then go to Dynamic Field widget and find Trim string by chars in the Callback option and set chars number you want to display into * String length * option.

**Comment by kaskad88** [comment]
Hi @taidang26. Enable the Trim string callback module https://prnt.sc/1u6wa2g, then go to Dynamic Field widget and find Trim string by chars in the Callback option and set chars number you want to display into * String length * option.

**Comment by SiavashBavandpour** [comment]
@kaskad88 please add the option to trim the string by **words** instead of chars. I am using this option to trim the excerpt, and triming by chars always cuts off the word. (your help is appreci....)

**Comment by kaskad88** [comment]
> @kaskad88 please add the option to trim the string by **words** instead of chars. I am using this option to trim the excerpt, and triming by chars always cuts off the word. (your help is appreci....)

@SiavashBavandpour Added an ability to trim by words in  https://github.com/Crocoblock/jet-engine-trim-callback
