### ISSUE TITLE
JetEngine Tables Builder: Adding Column total

### ISSUE THREAD

**Issue by opwolken** [CrocoBlock/suggestions#4091]
Hi!

Great work on te Tables builder. IMO this has the potential to outgrow competition like wpdatatables! Keep up the good work :)

I have a feature request to have the option to add a calculated column total (Sum, Count, Avg, etc) to the footer of the table. This total needs to change once you filter the table of course.

Love to see where this plugin is going!

**Comment by opwolken** [comment]
Hi bump :)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
