### ISSUE TITLE
Minimum and maximum stay for Jet Bookings

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#4095]
Hi, since you have developed the Jet Bookings plugin we were very exited to use it but there are some limitations that makes it not very useful. So, my feature request is that we should be able to set minimum and maximum days of stay and not only daily or weekly because many hotels or villas or other accommodations have those restrictions to their policy. I am aware of hotels that you cannot stay less than 3 days in a row, some others have 5 days minimum restriction so as you can realize we are limited to less business and in case some hotel sdeside to change their policy we willbe in reall trouble if we cannot make it work according their needs.

Thats all. Thanks.

**Comment by Hammer-ger** [comment]
Hey,

you can do this via logical conditions in the bokking form.

Add a calculated field and calculate: %FIELD::travel_date%+%FIELD::travel_date%
the result depends on the number of days that where selectet.

now use conditional locig to hide the submit button if calculated field is outside your needs (range).


but be careful. JetBooking ist not working for Hotels at the moment. the ideas are great but it is absolutly not working in the real world. 
a real world bookingsolution has always 3types of days:
- fee days
- coming/leaving days
- booked days.

jet booking only knows booked nights and not-bookes nights. 

also it is easy to book a room, that is already booked.
your clients will hate you for that.

when jetbooking is at 100% it will be one of the most powerful wordpress-booking-solutions. but at 80% it is not usable.

**Comment by UraraReika** [comment]
I merged this issue with [#3122](https://github.com/Crocoblock/suggestions/issues/3122), which is on the same subject so we could deal with it more efficiently.
