### ISSUE TITLE
JetEngine - CPT Conditional Logic BUG in Operator: In the list 

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#4101]
Hey guys,
I updated my plugin to the latest version 2.9.3 found a problem when I needed to add a new conditional logic, I went back to version 2.9.0 and it works normally again.

V 2.9.3 - BUG
![image](https://user-images.githubusercontent.com/6773491/135657357-b4ffc2fc-eed2-42f9-a534-db13fc6e4ef0.png)

V 2.9.0
![image](https://user-images.githubusercontent.com/6773491/135657430-bb1556ef-a064-4578-aa99-6580db0a1e25.png)

**Comment by kaskad88** [comment]
We tried to reproduce your issue based on the information you provided, but without success.

Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
