### ISSUE TITLE
Ordering easily dragging posts in backend our frontend

### ISSUE THREAD

**Issue by ofmarconi** [CrocoBlock/suggestions#4102]
Hi!

Can I manually organize the order of how a CPT listed...

I want my client to decide the position of each post as if it were something like drag and loose, it seems like this plugin does this: https://wordpress.org/plugins/post-types-order/

It would be incredible if I had this in JetEngine.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
