### ISSUE TITLE
JetEngine Query Builder - %related_children_from|post-type-slug%

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#4104]
Hello.

Please tell me where in Query Builder I can use an analog of the query %related_children_from|post-type-slug%. Now, directly in the listing, I specify this macro with my record type and everything works correctly, but I would like to understand where I can do this in Query Builder.

And can I use this macro together with filtering by category. i.e. get all the posts of the current category, and then get %related_children_from|post-type-slug% from them.

Thanks.

**Comment by kaskad88** [comment]
You can use the Related children dynamic macros https://prnt.sc/1upzb33 https://prnt.sc/1upzc6s In Query Builder.

**Comment by kaskad88** [comment]
And you can use this macro with filtering by category.
