### ISSUE TITLE
Jet Woo Builder - Display Variations

### ISSUE THREAD

**Issue by osamaaminaziz** [CrocoBlock/suggestions#4105]
Hello,

I'm using this plugin to display the variations inside the product grid 
https://getwooplugins.com/plugins/woocommerce-variation-swatches/
but it's not compatible with the jet woo builder.

It will be very useful if we can show product variations and "Add to Cart" on the shop page instead of this (Options) button.
so I need to request this feature to be displayed with the jet woo builder product grid.

thank you.

**Comment by Michaelgimii** [comment]
+1
The color swatches is very much needed for this plugin. It is strange that this very important feature does not exist in this plugin.
Does crocoblock have a plan to add this feature to jet woobuilder?

**Comment by UraraReika** [comment]
https://crocoblock.com/troubleshooting/articles/fail-to-add-attractive-variation-swatches-to-woocommerce-archive-page/

**Comment by 79ho3ein** [comment]
hello @UraraReika
excuse me... Do you have a plan to add color swaches to jet swatches? (specially product grid widget)
