### ISSUE TITLE
Add Query Arguments/URL Prefix options to other widgets that accept Links

### ISSUE THREAD

**Issue by Ssendam0101** [CrocoBlock/suggestions#4106]
The dynamic link widget is very powerful. However, there is some simple functionality included with it that would be nice to have for other widgets that take Links, like the Button Widget.

It would be really helpful if the Button widget (and others that took links) would let the user specify query parameters and url prefixes. Because of the current limitation, I cannot make button use a dynamic link in the way I need.

![image](https://user-images.githubusercontent.com/71953159/135738934-a7d0387b-e069-4e2d-979a-33bc386aeb97.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
