### ISSUE TITLE
JetMenu Error

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#4107]
<html>
<body>

Level | Message | Count | Location | Component
-- | -- | -- | -- | --
Warning | Attempt to read property "display_name" on bool | 3 | -wp-content/plugins/elementor/includes/template-library/sources/local.php:603<br />Elementor\T\Source_Local->get_item()<br />wp-content/plugins/elementor/includes/template-library/sources/local.php:443<br />Elementor\T\Source_Local->get_items()<br />wp-content/plugins/jet-menu/includes/tools.php:409<br />Jet_Menu_Tools->get_elementor_templates_select_options()<br />wp-content/plugins/jet-menu/includes/settings/options-modules/mobile-menu-options.php:91<br />Jet_Menu\O\Mobile_Menu_Options->init_options()<br />wp-includes/class-wp-hook.php:303<br />do_action('init')<br />wp-settings.php:578<br /> | Plugin: elementor

</body>
</html>

**If i disable JetMenu the error disappears**

**Comment by Floydtm** [comment]
Hi! For a quick solution, please contact our support team. Provide access to your site. Thank you!
