### ISSUE TITLE
Slider in two rows

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4108]
If the opportunity arises
Please implement the function of creating a slider in two rows!
i.e. now all sliders go in one row.
It would be great if you could specify the number of rows.
I would like to see such an opportunity in the widgets: Listing Grid and Slider
![Без-имени-2](https://user-images.githubusercontent.com/47380983/135761764-e4a2a8a6-112a-4180-927a-6697120bc32a.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.  However, right now you can use templates as content

**Comment by klecka** [comment]
Since this is an out of the box feature of slick slider, which you're using under the hood, it shouldn't be to hard to add more slick options to your slider feature?
