### ISSUE TITLE
JetSmartFilters - prepopulated 

### ISSUE THREAD

**Issue by bislamovic** [Crocoblock/suggestions#411]
I have woo commerce shop and JetSmartFilters in it. As you can navigate through shop by categories -  you can easily filter products by clicking link with category name.

For example, category: "boat tours" can be accessed by clicking:
/product-category/boat-tours/

and all products in that category will be shown.

Problem is that in JetSmartFilters, if you have filtering by Categories, selected category "boat transfers" is not ticked. 

So if client filter any other categories shop will not show products because JEtSmartFilter filtering only products in category "boat tours". 

If JetSmartFilters can be populated with selected category (by link) than customer will see that boat transfer category is ticked and if he un-tick it he will get all products and then can search by other category.

**Comment by Floydtm** [comment]
Hi. You can create custom query filters. Like this http://prntscr.com/o3y56g And with the help of a custom link add it to the menu. When you go to the menu item filter will be selected. It is advisable to configure the filters to work on the reloading page.
