### ISSUE TITLE
Animated Hamburger Menu

### ISSUE THREAD

**Issue by durnovtsev** [CrocoBlock/suggestions#4116]
Good afternoon, interested in the possibility of animation when calling Japopup.

1. Unlimited Elements has a free awesome Animated Hamburger widget
https://unlimited-elements.com/animated-hamburger-ico..
Unfortunately, it only works with Popup in Elementor PRO. I would like to implement with your JetPopup.
Unlimited Elements has javascript, as can be seen from the screenshot "refers to Popup in Element or PRO"
Is it possible to make it refer to yours?
![Unlimeted Code popu Elementor PRO](https://user-images.githubusercontent.com/32779191/135887779-faeece76-3070-4499-80af-d5bff641da66.jpg)

2. You can also implement it via Lottie at Elementar https://www.youtube.com/watch?v=mLZ8OhqlRrY
Unfortunately your widget only has animation without Toggle

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
