### ISSUE TITLE
JetElements | Floating Image Box

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#4118]
Please, add something like this on the Advance Image Box

Icon "Over" the Box itself. Like floating

![image](https://user-images.githubusercontent.com/68023943/135894380-81c8e7c8-80a0-4334-bcd5-8e7b7c7865bd.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
