### ISSUE TITLE
2 bugs in the new update of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4122]
hello
Thank you very much for the new update...

But the new version has 2 serious bugs on the shopping cart page. These two bugs are present in Cart Totals & Table widgets.
Both of these widgets are of uncontrollable width. Please see the image below :
![Screenshot (175)](https://user-images.githubusercontent.com/77163248/136189038-dacaf9ab-19fc-4adf-acdd-0093b0064045.png)

**Also in the image above, it is clear that the payment button is stuck up**. This was not the case in the previous version.
The Cart Totals widget is completely out of control in controlling the width of tables and columns.
As you can see in the image above, the Cart Totals widget table is shorter than the button. While both its width and the width of the button are set to 100%.

I hope I have described the problems well.  thank you

**Comment by UraraReika** [comment]
Fixed. wait for next release. for now you can use temporary solution as styles for table `table-layout: auto;`

**Comment by 79ho3ein** [comment]
thank you
