### ISSUE TITLE
Report an item in the empty cart page / jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4136]
hello
In the emty cart page, if we do not use the Cart Empty Message widget, the empty cart page will not be called if we remove the product from the cart. The ui design of some websites, including my website, is such that this widget is not required.

Please add this feature if possible, so that if you do not use the Cart Empty Message widget, there is no problem calling it.

thank you

**Comment by UraraReika** [comment]
The cart empty message requires to have the class `cart-empty` to show the updated information without reloading the page. But you can add this widget to the template and [hide](https://i.gyazo.com/b2fdcb12d5b2687fa1f0a1370b3d7e25.png) it with the help of default Elementor instruments.

**Comment by 79ho3ein** [comment]
thank you
