### ISSUE TITLE
Feature Request: Custom Icon on Home Button

### ISSUE THREAD

**Issue by RoldanAncajas** [Crocoblock/suggestions#414]
This is a feature request. 

It would be great if you can add an option of putting a Custom Logo on the Home button of your JetMenu Product, instead of just the Fontawsome premade icons.

As observed, most websites have their logo on the upper left hand corner of Nav Bar then fallowed by the Menu Items.

Thank you!

**Comment by shinTM** [comment]
available since v2.0.4
