### ISSUE TITLE
User Role Expiration Period (example: from Gold to Guest)

### ISSUE THREAD

**Issue by Ioannis981** [CrocoBlock/suggestions#4147]
Hello all! 
I could not find the following feature in JetformBuilder so it would be highly appreciated if you will have it under consideration.
Details:
There is a expiration period in terms of published post period but I could not find an expiration period in terms of user role validity period. 

There could be the following 3 option fields in a payment jetformbuilder form where: 
1) The user role will expire after: x days 
2) Select what will be the user role validity period after payment form submission (ex: Gold, where in Gold role the user will be able to publish x number posts-listings). The feature of allowable number of post-listings per user role can already be set  in JetEngine.
3) Select what will be the user role after the expiration of the user role validity period? (ex: Guest, where when Gold Membership end the user goes to Guest role and will not be able to publish any posts-listings)

Thank you for all great features already provided to Crocoblock users.

Ioannis

**Comment by Ioannis981** [comment]
I have just seen that this issue-suggestion is already added from another user.

**Comment by MolyMalon** [comment]
Can you pass link where you saw it?

**Comment by Ioannis981** [comment]
Hello Team,

Apologies for my late response.

I saw this post and thought that it will lead to suggestion  :
https://github.com/Crocoblock/suggestions/issues/3898 .

But it seems that it is not added in the pipeline for improvements yet
right?

Kind regards,

Ioannis
