### ISSUE TITLE
JetMenu: Enable Toggle Option for Sidebar Menu in Mobile Mode

### ISSUE THREAD

**Issue by RoldanAncajas** [Crocoblock/suggestions#415]
Hi Crocoblock,

I noticed the Sidebar Menu of your JetMenu is not responding to Mobile Mode. It would be a great addition if you can add an option for SIDEBAR MENU to toggle in Mobile Mode.

Since, what if Side bar menu is far to long for the mobile mode, the most sensible thing to do is to toggle it to save up space.

Thank you!

Roldan Ancajas
www.adamsproject.ph

**Comment by Floydtm** [comment]
@RoldanAncajas, we redid the mobile menu. A beta version of the jetmenu plugin is now available in your account

**Comment by RoldanAncajas** [comment]
@Floydtm You have one of the best Plug-ins ever.

Thank you for the improvements.

Crocoblock fan here!

**Comment by RoldanAncajas** [comment]
Hi Floyd,

Thank you for this improvements.

You have the best plug-ins ever.

Crocoblock fans here.

Best Regards,
Roldan
