### ISSUE TITLE
User's full name as preset in Jet Form Builder

### ISSUE THREAD

**Issue by simkoG** [CrocoBlock/suggestions#4151]
Is it possible to get the user's full name as default value for an input in Jet Form Builder?

I hane a **name** field which contains the first name and last name. But I could load only the user's `First Name` **OR** `Last Name` into an input field.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
