### ISSUE TITLE
JetCompareWishlist statistic

### ISSUE THREAD

**Issue by martinjakse** [CrocoBlock/suggestions#4156]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

As a store admin I am interested in how to get information about what people are adding to the wishlist. I am using Wishlist Widget and this is very important for my store because this would help me to increase sales with specific promotions. 

**I want every product to have some field with a special number that will show how many times a product was added to wishlist.**

**Comment by UraraReika** [comment]
Unfortunately we do not plan to introduce such functionality into the core our plugin. Now our team is working on more priority tasks. But I recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/

Thank you for your understanding.
