### ISSUE TITLE
JetProductGallery - Lightbox behaviour

### ISSUE THREAD

**Issue by knireis** [CrocoBlock/suggestions#4157]
I notice some behavior in the gallery slider which can be done more user friendly for visitors.
Clicking an image only shows the current image in the lightbox. You have to click the 'gallery icon' in the topright corner of the image to show the all the images in the lightbox. 
Usually visitors will just click the image which means they have to click every image separately to get them in the lightbox.

Second, when i enable to video option, the video is not included in the lightbox. Is it possible to change this behavior?
Regards, Jasper

**Comment by UraraReika** [comment]
@knireis ! In future update photoswipe gallery will trigger with button on image. But video will not be included in it.
