### ISSUE TITLE
Shortcodes for JetEngine Custom Fields

### ISSUE THREAD

**Issue by MikeJoe2602** [Crocoblock/suggestions#416]
Is it possible to enter multiple custom fields inside of ie a textbox? I don't want to use multiple widgets to display entries if possible? Currently using Jet Engine. So like shortcodes: This is [my-custom-field] and the text goes on and has [another-custom-field] in it?

**Comment by Floydtm** [comment]
This is available in the latest version of the plugin http://prntscr.com/riuudj

**Comment by yas1nshah** [comment]
i have the same issue whats the solution fot this?? @MikeJoe2602 
the link isnt opening btw @Floydtm

**Comment by alecasgari** [comment]
> This is available in the latest version of the plugin http://prntscr.com/riuudj

Yes thanks. My long-term issue is now solved. 
Here is the screenshot
![image](https://github.com/Crocoblock/suggestions/assets/161822574/0c3fddd5-2c40-4936-bc62-4453ef68cfa5)
