### ISSUE TITLE
Add icon to widget name in backend

### ISSUE THREAD

**Issue by ofmarconi** [CrocoBlock/suggestions#4162]
Simple suggestion to add an image to the widget description, the icon will make it much easier for me to know which one to disable after building the site:

![image](https://user-images.githubusercontent.com/6594795/137501423-bc51a437-d284-4ef6-a55f-3d185530e16a.png)

**Thx!**

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
