### ISSUE TITLE
Bug in jet-dashboard

### ISSUE THREAD

**Issue by ZENwww** [CrocoBlock/suggestions#4166]
**Describe the bug**
In console are bug:
Uncaught TypeError: Cannot read properties of undefined (reading 'page')
    at jet-dashboard.js:547
    at jet-dashboard.js:552
(anonymous) @ jet-dashboard.js:547
(anonymous) @ jet-dashboard.js:552

Nothing is displayed in the panel

**To Reproduce**
1. Go to Crocoblock
2. Click on JetPlugins Settings
3. Open developer tools

**Expected behavior**

**Desktop (please complete the following information):**
 - Device: iMac
 - OS: macOS 11.6
 - Browser Chrome
 - Version 94

**Comment by Floydtm** [comment]
Hello, please contact our support team for a quick solution to your request. Thanks!
