### ISSUE TITLE
JetSmart Filter search results sort widget

### ISSUE THREAD

**Issue by Olegggggggg** [Crocoblock/suggestions#417]
Hello.I think that is not enough widget sort search results with which you can choose in what order will be ordered listings. Rating, price ascending, price descending, number of reviews or alphabetically.
![2019-08-05_14-14-46](https://user-images.githubusercontent.com/53747082/62453627-27a5ea00-b78c-11e9-98c8-2a8b3a594cf1.png)

**Comment by Floydtm** [comment]
This is available in the latest version of the plugin
