### ISSUE TITLE
[BUG] Ajax Request after back page

### ISSUE THREAD

**Issue by edupaludoo** [CrocoBlock/suggestions#4172]
I created a product CPT using Jetengine and made a listing grid to bring the products, so far so good.
When I access a product from the list, I go back to the product list page, it no longer displays any filter products. From what I understand, the ajax query gets lost, it's like duplicating the query.

![image](https://user-images.githubusercontent.com/92687133/137638123-0d776b34-4441-4708-a28f-b5efffd1ad54.png)

Here is the site if you want to test: https://arieltek.net.br/lista-produtos/nautica/

**Comment by Floydtm** [comment]
Hello, please contact our support team for a quick solution to your request. Thanks!
