### ISSUE TITLE
JetWooBuilder - Carty Empty message widget

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#4173]
Hi.

In a future possible to use Html codes- inside the custom messages field in the widget itself?
image: https://prnt.sc/1wl5mzq

**Comment by UraraReika** [comment]
Hello @Lonsdale201 !

Sorry but this feature will not be added due to method that we use to override the message.

**Comment by Lonsdale201** [comment]
> Hello @Lonsdale201 !
> 
> Sorry but this feature will not be added due to method that we use to override the message.

No problem, thank you :)
