### ISSUE TITLE
Jet Woobuilder product grid widget new Queries

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4177]
In all store websites, there are two very important sections. The first is the display of bestsellers products.And the second case is the display of popular products. (Products that most users see. That is, they enter the single page of that product.)
This is really frustrating. Why shouldn't such a great plugin have such capabilities?
I already saw that you suggested users to use the code. But did you know that most users of this plugin have no knowledge of coding?
This is not really a feature outside of WooCommerce. Even the weakest theme can display best sellers products.
This is a major concern for many users of this plugin.
Please think about these two features. These are very important in e-commerce. Especially the feature of displaying bestsellers products

In fact, to solve this problem, we need two new queries in the product grid widget.
1- The best-selling products
2- The most visited products
The first is very vital.

Please add this. Please

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

You can use Custom Query functionality from JetEngine in combination with JetWooBuilder Products Grid to solve your problem.

Use [Query Builder](https://i.gyazo.com/887da3c88ee9bc665bc0182b41facc32.png) with Query Type WC Product Query and setup you specific query. Then use it in the widget [here](https://i.gyazo.com/361239622c033438becd9457a21e8ee8.png).
