### ISSUE TITLE
An anonymous bug in jet woobuilder (product grid widget)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4182]
hello @UraraReika 
I am in 1.10.3 version. There is a bug in the product carousel, but I do not know exactly what the problem is. But I tested this bug on all my websites and it existed ...
**Please watch the video below :**

https://user-images.githubusercontent.com/77163248/137916591-b7ff75c2-3d66-418e-963a-aa4b5668c195.mp4

As you can see in the video above, in tablet size, I displayed the products in 3 columns and activated the carousel. But after saving and reloading the editor, the products were displayed in grid. While the carousel was active!
**This bug is only available in tablet size**

Please put the product grid widget in the following conditions in case of troubleshooting : 
1- Add the product grid widget
2- Enable tablet mode         https://prnt.sc/1wq7m5h
2- Columns : 3        https://prnt.sc/1wq770u
3- Products Number : 4         https://prnt.sc/1wq74eg
3- Activate the carousel
4- Save changes and reload the editor
5- After reloading, enter tablet mode again

Then you will see that the products are not carousel. While the carousel is active.

thank you

**Comment by 79ho3ein** [comment]
I forgot to say one thing ...
This problem is not limited to the editor. If you view the website with a tablet, it looks exactly like an editor and is displayed as a grid (I saw this with chrome inspact.)

thanks

**Comment by 79ho3ein** [comment]
hello @UraraReika, good time!
This bug has been fixed in the new version. But there is still a problem. Just like the video above, after reloading the page, this time the arrows and navigation points are hidden.
**If you need video, please let me know**

thank you very much

**Comment by UraraReika** [comment]
Hello @79ho3ein !
Thank you, we don't need video, we can see this at our side. But this isn't an actual issue. The reason why this isn't an issue hide behind how the scripts works. We check if items count more than cols count and if it is we trigger carousel in other cases we just print products grid. In the editor this script works as well and when you change to tablet view page or widget doesn't reload to trigger this script again that is why you don't see the controls parts. This behavior was in previous version of the plugin as well.

**Comment by 79ho3ein** [comment]
thank you
