### ISSUE TITLE
Jet Engine Except

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#419]
Hello, I noticed that the Jet Engine in the listing does not automatically generate a recording excerpt, although they say in the WP documentation that it should. All plugins of posts that I know for Elementor form an excerpt automatically. I ask to make this revision, so I do not really want to do manually what WP can do from the box.

/*Оригинал на русском*/
Здравствуйте, заметил что Jet Engine в листинге не формирует автоматом отрывок записи, хотя в документации WP говорят что должен. Все плагины постов которые знаю для Elementor формируют отрывок записи автоматически. Прошу внести эту доработку, так делать вручную то, что WP умеет с коробки, не очень хочется.

**Comment by Floydtm** [comment]
@stasonua0 Hi! Soon we will release update 2.0 in this functionality will be available. Thanks you!
