### ISSUE TITLE
JET Engine - How to organize taxonomy by meta field (Feature Request)

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#4191]
Hello, I need to organize a taxonomy by company hierarchy as the customer requested, to organize I create a meta field: "Custom Order" but when I add the listing grid I can't filter by the meta field

![image](https://user-images.githubusercontent.com/6773491/138143322-4da8400b-fd06-449c-82a8-8eb10c020744.png)

Listing Grid Terms Query order by options
![image](https://user-images.githubusercontent.com/6773491/138145824-f9c3cb95-360e-47d3-a45e-25b24f22beb0.png)

I believe it would be important to have an option to sort the listing grid by meta field here, as we have how to add these targets to any taxonomy created with JetEngine. 

Query Builder
![image](https://user-images.githubusercontent.com/6773491/138144108-d334dc0d-27e9-4d0c-b46c-3d09fd1e2fd0.png)

Query Builder Meta Clause
![image](https://user-images.githubusercontent.com/6773491/138145393-0633da1d-91b1-49b4-8e46-b00f6a819499.png)

**Comment by dyonatandias** [comment]
I was in the same situation a little while ago, in my case the meta field in the taxonomy was about a value, I ended up leaving it randomly because I couldn't organize it from the smallest to the largest.

**Comment by tizum** [comment]
Guys, I need solve this problem :(

**Comment by kaskad88** [comment]
Hello.

For ordering taxonomy by meta field you must make follow:
1. Create Terms Query in JetEngine Query Builder
2. Add Meta Query Clauses in Meta Query tab as on screenshot https://prnt.sc/1xpp1jd
3. In General tab select Order by meta clauses and select Meta Clause https://prnt.sc/1xpp72b

**Comment by tizum** [comment]
Guys, it still doesn't work here.

![image](https://user-images.githubusercontent.com/6773491/139998600-3f5dadc2-1dda-4f3d-9ca8-737270721cce.png)

Price does not appear in this array
![image](https://user-images.githubusercontent.com/6773491/139999058-14a251f3-dd38-4ebd-b51b-5ea67b87a370.png)

![image](https://user-images.githubusercontent.com/6773491/139999148-9cb24332-da6d-4d3f-8640-310850eea9dc.png)

![image](https://user-images.githubusercontent.com/6773491/139999546-51a0ecd3-a3f1-4054-a2ac-dd3091186300.png)

![image](https://user-images.githubusercontent.com/6773491/139999615-f5ca5079-3ca7-4606-af96-9226533ba2b5.png)

I don't know what it could be, these are just some prints, but I spent a few hours trying to solve it in different ways.

Obs: The previous project I decided to put the order in the description, so I went back to the one that is most important, as it is a site for an authorized Nissan dealership.

@kaskad88 Plss Check
