### ISSUE TITLE
JetWoo Checkout endpoints is missing style options

### ISSUE THREAD

**Issue by mdesignweb** [CrocoBlock/suggestions#4193]
**Describe the bug**
My account template doesn't support this functionality https://docs.woocommerce.com/document/managing-orders/#paying-for-an-order.  It looks like this  (https://user-images.githubusercontent.com/92887019/138158011-7f352525-9ba9-45d8-a618-778bb5c78b87.png), while My custom account template is displaying properly when you visit /my-account/ page

**To Reproduce**
Please refer to this link https://docs.woocommerce.com/document/managing-orders/#paying-for-an-order

**Expected behavior**
I'm not sure of expected behavior, but for sure is a lack of JetWoo functionality or maybe style should be like a custom checkout template if that template is set up. 
Another solution is an additional setting for this template to be made custom. From my test, it just loads with the theme(Astra) colors and style. 

**Screenshots**
 (https://user-images.githubusercontent.com/92887019/138158011-7f352525-9ba9-45d8-a618-778bb5c78b87.png)

**Comment by UraraReika** [comment]
I merged this issue with #2721, which is on the same subject so we could deal with it more efficiently.
