### ISSUE TITLE
Adding a Taxonomy Filter to Admin List for a Custom Post Type

### ISSUE THREAD

**Issue by serg-pervushin** [CrocoBlock/suggestions#4194]
Maybe it is, but I haven't found(. Added a new type of post, added a taxonomy and I would like to filter this type post by taxonomies. Tried solutions on the net - does not work for me(

![XBYZX](https://user-images.githubusercontent.com/37971764/138220958-ab8be9b9-4d64-4134-8451-b34f616f37e1.png)

**Comment by Floydtm** [comment]
We are working on this, stay tuned. https://prnt.sc/1r3pt6w https://prnt.sc/1r3pmfx Thank you!
