### ISSUE TITLE
Add a CUSTOM LAYER on "advanced carousel"

### ISSUE THREAD

**Issue by webavalanche** [CrocoBlock/suggestions#4199]
The main goal is to improved the "Advanced carousel" features. First of all, you should copy the Elementor Pro Features called "Media Carrousel" because you can add a big video on top + all the following video are under in the carrousel. The presentation is great like this -> see the example here : https://thibow.com/improve-advanced-carousel-features-crocoblock/

Starting from this you can improve the features by adding the possibility to have an overlay.  

UX: When the user will put is mouse on the carrousel slide an overlay will appear with background color + title + text + button + icon => in this way you will be able to increase interaction with the visitors.

Other available options would be the same video carrousel but with the overlay informations so title + text + button + icon always visible.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
