### ISSUE TITLE
New options for slider thumbnail

### ISSUE THREAD

**Issue by Floydtm** [CrocoBlock/suggestions#42]
Want the thumbnails bar to be a slider and have choises for "Slides Per View", "Ratio", and "Centered Slides" like Media Carousel http://prntscr.com/mer7cy http://prntscr.com/mer7gi

**Comment by kaskad88** [comment]
The js script of slider does not allow do this

**Comment by kaskad88** [comment]
Added responsive controls to `Thumbnail width` and `Thumbnail height` options
