### ISSUE TITLE
3 requests to improve the cart page / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4201]
hello
There are 2 very simple but important items on the shopping cart page. I will describe them, please review them if possible.

1- In the Cart Table widget, the shopping cart update button is attached to the Coupons section (Of course on the desktop).
Now, I've moved it to the left using css (float: left;)
![Screenshot (194)](https://user-images.githubusercontent.com/77163248/138441037-393bd589-e184-49c7-b813-dd4dbe1ad706.png)

**Please, if possible, add a feature so that we can move the cart button to the left or right. There are currently no settings for this.**

2- In the "Cart Table" widget, the payment button is attached to the table. At this time, it is not possible to move it from the top.
![Screenshot (196)](https://user-images.githubusercontent.com/77163248/138441673-1cf960f8-4d75-48db-9001-e2ae664c9943.png)
Please add a feature to the button so we can move it away from the top.
**I re-examined this case. It looks like this in the editor. But in the output is correct. In any case, the option of distance from the top is very important.**

3- **In the Cart Table widget, please add the ability to move the image left or right. This is much needed.**

thank you very much

**Comment by UraraReika** [comment]
> In the Cart Table widget, please add the ability to move the image left or right. This is much needed.

Please describe in more details

**Comment by 79ho3ein** [comment]
1- now,in Cart Table widget we cannot move the cart update button to the right or left. By default, it is only on the left.

2- In connection with the Cart Totals button, please add an adjustment if possible so that we can move the button from the top. (margin top)
In this image https://prnt.sc/1z0h8wb, the Cart Totals widget button is stuck up. This problem is only in the editor. But on the website it is true. Please check the editor.

thank you
