### ISSUE TITLE
PHP Notice:  Undefined index: HTTP_USER_AGENT - JET MENU

### ISSUE THREAD

**Issue by loorlab** [CrocoBlock/suggestions#4207]
**Describe the bug**
[24-Oct-2021 04:47:10 UTC] PHP Notice:  Undefined index: HTTP_USER_AGENT in /path/wp-content/plugins/jet-menu/includes/assets.php on line 158

**To Reproduce**
Load the site

**Expected behavior**
No PHP Notice

**Additional context**
WP DEBUG ON

Possible Solution:

`            $sh = isset( $_SERVER['HTTP_USER_AGENT'] );
			if ( false !== strpos( $sh , 'Trident/7.0; rv:11.0') ) {
				$public_script_depend[] = 'jet-menu-polyfills';
			}`

Please check. 

Regards

**Comment by Floydtm** [comment]
Done! Keep for updates.
