### ISSUE TITLE
JetAppointment -  Group Capacity Service allows same customer to book same appointment

### ISSUE THREAD

**Issue by ALPSIT** [CrocoBlock/suggestions#4209]
A user which has booked in for a Group Capacity Service is able to book in for the same appointment which they have already booked.

There should be a check to see if current user already has this appointment scheduled to not allow the same booking again as they have already booked for it.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
