### ISSUE TITLE
BUG / The new version of the jet menu plugin has a problem with elementor / Very important, please check.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4219]
hello
When the new version of the jet menu is enabled, Page Layout in Builder Theme> page is disabled. **To Rebuilding the problem, please follow the steps below :**

1- Make sure the latest version of the jet menu plugin is installed and enabled.
2- Create a page using elementor theme builder. https://prnt.sc/1xdxjp1
3- After creating the page, place the Page Layout on the elementor canvas. https://prnt.sc/1xdy002
4- Then tap Publish, and reload the page.
5- After reloading, go to the Page Layout section again. You will see that it is completely lost. https://prnt.sc/1xdye5j

Next, if you disable the jet menu, the problem will be solved.
If you do not experience the problem, let me know so I can send you the video.

thank you

**Comment by Michaelgimii** [comment]
I also experience a problem. @Floydtm may you check this please?

**Comment by 79ho3ein** [comment]
This bug was fixed in the new version. thank you @Floydtm.
