### ISSUE TITLE
JetSmartFilters: stylable labels in Visual Filter

### ISSUE THREAD

**Issue by arnohesse** [Crocoblock/suggestions#422]
Desirable feature for Visual Filters in JetSmartFilters: 

1. Make the Item Labels styleable, with _background_, possibly _borders_.
Advantage: it would make the item labels look like clickable _badges_, a popular filtering UI, especially in the horizontal arrangement.

2. Different Item Label styles for normal vs. checked.
Advantage: it would be great if the _background_ of the Item Label would indicate which filter is currently active.

**Comment by Floydtm** [comment]
This is available in the latest version of the plugin http://prntscr.com/riuqr0
