### ISSUE TITLE
Major Problem: Can't use Elementor after updating to new JetEngine

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#4223]
We jumped from JetEnginge 2.8.0 to newest version,

Now see this error in some of our list builders:
https://prnt.sc/1xiwa02

We cannot access Elementor on this pages either,
We need help ASAP to fix this.

Please

**Comment by Medienor** [comment]
When we try to access a website with this error code it breaks the site,
We cant even close the tab.

Please Crocoblock,
Any suggestions?

**Comment by Medienor** [comment]
Every website that cointains JetFilters + JetEnginge Listings is crashing = https://prnt.sc/1xiwyzy

**Comment by Medienor** [comment]
We rolled back to 2.8.4 .. Safe for now.

**Comment by kaskad88** [comment]
@Medienor Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
