### ISSUE TITLE
JetFilter permalink

### ISSUE THREAD

**Issue by fabio323ti** [CrocoBlock/suggestions#4224]
im using jetwoobuilder and elementor pro, in shop page have a template with grid products and smart filter for category that works fine.
When i open single product page, if i click on category link, site come back to product main page with different permalink and jetsmart filter doesn't do exactly the job.

for example... 
i have main product page on /shop 
the single product category is /t-shirt, when i click on it page site change to /shop/product-category/t-shirt/

in my case, i see again shop template and checkbox filter already selected , that's its cool.
But if i change filter checkbox selection.. the ajax or query start from new permalink, for ex. /shop/product-category/t-shity/?...ect ect and filter fail because main shop is on /shop/

hope it clear..
someone please can help me? i don't want to create a single template for each category product..

just back to main shop page with filter working is more than enough.

thanks

**Comment by nreljed** [comment]
hello, there is no solution at the moment.
maybe in the near future.
otherwise use my snippet code solution to redirect the terms in filters to /shop/ and be able to use the filters without limits
#3376

**Comment by fabio323ti** [comment]
Solved with #3376, many many thanks.
