### ISSUE TITLE
Possibility to add JetForm inside listing

### ISSUE THREAD

**Issue by ofmarconi** [CrocoBlock/suggestions#4225]
JetForm has incredible potential!

I see it becoming something far beyond what a form, can be a great multi-task automation with your "post submission actions".

But it would also be interesting to have only the send button and with the post submission actions, that would be incredible!

And that they worked inside the listing, today occurs error if we enter jetform within the listings ...

Please if possible allow jetform within the listing without the need for popup (an alternative to work)

> A practical and incredible example is this magic plugin button Uncanny Automate:
> https://automatorplugin.com/knowledge-base/magic-button/

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
