### ISSUE TITLE
Jet Elements: dynamic input for numeric value in Progress Bar 

### ISSUE THREAD

**Issue by arnohesse** [Crocoblock/suggestions#423]
Wouldn't be nice if the _numeric value_ in the **progress bar** could be _dynamically_ tied to numeric fields in posts? Instead of it being a fixed manual input? 

There are many relevant applications for this feature, e.g. in e-commerce: inventory left, funding goal achieved, sell-out level for events.

**Comment by andrewkirkcaldy** [comment]
This would be a great feature to have. It appears quite a few other elementor addons don't offer this either.

**Comment by kaskad88** [comment]
Added for next version ( 2.1.0 )
