### ISSUE TITLE
Zoom integration within Jet Appointment plugin

### ISSUE THREAD

**Issue by Daniel0989** [CrocoBlock/suggestions#4230]
Firstly apologies if this has come up in the past. 

I would like to suggest for the integration of Zoom or some other video conference tool to be used in the Jet Appointments plug in. I have multiple clients that need this function but I am forced to use an alternative plugin for this feature. I would love to be able to use Crocoblocks for this. 

Thank you.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
