### ISSUE TITLE
JetWooBuilder - possibility to customize WooCommerce "messages" and e.g. "lost password"

### ISSUE THREAD

**Issue by Charlottilottan** [CrocoBlock/suggestions#4233]
I love JetWooBuilder as I needed to customize the check-out process to a certain brand's colours and fonts. 
However

1. - when a user makes someting wrong - an error message occurs (as it should). However, after chatting with support I understand there is today no Widget for customizing the errror messages.
![woo mesages](https://user-images.githubusercontent.com/83376778/139431541-ba80b07a-fc0c-4d3a-8453-aca9b5a2de11.JPG)

2. - when any other "notice" shows (like..product A is added)

3. When a user has lost password, suddenly the form is WooCommerce Standard

The whole idea of aligning the check-out process - design, with a certain Brand - falls flat....

**Comment by Michaelgimii** [comment]
Isn't that really the case? #2249
Won't WooCommerce notifications pop up in the jet woobuilder plugin? In fact, pop-ups will be the best and most up-to-date option for this feature

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently.
