### ISSUE TITLE
In the new jet woobuilder update, there is a problem in the cart page widget.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4239]
The cart totals widget has a problem with its width. I set its width to 100% but it does not become full width. This problem also exists in tablets and mobile phones
Please fix it

theme : hello elementor
jet woobuilder : new version
elementor : new version
elementor pro : new version
wordpress : 5.8.1

**Comment by 79ho3ein** [comment]
This BUG has been added to the plugin since the previous two versions. I have explained it in this issue : #4200
I'm still in previous versions ...

**Comment by UraraReika** [comment]
I merged this issue with #4200, which is on the same subject so we could deal with it more efficiently.
