### ISSUE TITLE
Enhancement: wooCommerce Subscriptions CSS customization

### ISSUE THREAD

**Issue by dlinstedt** [CrocoBlock/suggestions#4241]
Would love a new feature:  The ability to style woo Subscriptions, the same way woo Orders is styled on the My Account template overrides.

The specific woo Product we use is:
https://woocommerce.com/products/woocommerce-subscriptions/

**Comment by UraraReika** [comment]
Hello @dlinstedt !

Our product spesific for default WooCommerce functionality. We althoug add some smal compatibilities with third party plugins.
