### ISSUE TITLE
wooCommerce CSS Customizer for Downloads endpoint

### ISSUE THREAD

**Issue by dlinstedt** [CrocoBlock/suggestions#4242]
Feature Request:  would really love an ELEMENTOR CSS customizer widget for wooCommerce Downloads list

**Comment by UraraReika** [comment]
Hello @dlinstedt !
Some additional style controls for not rewriten templates located in My Account Content widget.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
