### ISSUE TITLE
Button width on the payment page of the jet wobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4243]
hello
On the payment page, if we set the button width to 100%, its width will be less than 100%. https://prnt.sc/1xv366t
If you look closely at the blue arrows in the image above, it is clear that the button is not full width. This problem is very evident in mobile. please check if possible

**Comment by UraraReika** [comment]
Hello @79ho3ein !

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team or describe in more details how to reproduce this bug. 

Thank you!

**Comment by 79ho3ein** [comment]
hello @UraraReika 
I forgot to say that I use the hello elementor theme. This problem is definitely related to this theme.

thank you

**Comment by UraraReika** [comment]
We use Hello Elementor theme to check this issue, here's what we [got](https://i.gyazo.com/0eaad7980bb81de20e63860d8c5ecffb.png).

**Comment by 79ho3ein** [comment]
Could it be because of the deletion of the privacy policy section? I have removed this section (from the WooCommerce Customization section in the WordPress Dashboard)

**Comment by UraraReika** [comment]
Remove pp section but result still [good](https://i.gyazo.com/f6b1c749306543b5046b1218b3be1f81.png)

**Comment by 79ho3ein** [comment]
hello @UraraReika
There must be a problem. I will investigate this further and let you know. thank you for your attention

**Comment by 79ho3ein** [comment]
I found the problem. I deleted this line using the code : https://prnt.sc/1z9zk13
If this line is deleted, the button will be smaller. Is there a way to remove this line more easily? If privacy policy is not needed.
Is it possible to completely disable and delete the privacy policy section in jet woobuilder? As a new feature

thank you

**Comment by UraraReika** [comment]
This line is just a border-bottom on `payment_methods` section so what did you mean by deleting it. If we remove this style only border disappear the layout and button width stay the same.

**Comment by 79ho3ein** [comment]
I must have mistyped the code. may you add a feature to disable the privacy policy? If possible, is it possible to add a feature to disable the privacy policy? If you disable it, the privacy policy section will be completely disabled and hidden. 
Anyway, thank you for your time🌹.

**Comment by UraraReika** [comment]
This feature exist in global WooCommerce settings in customizer so we will not add it to our functionality. If you disabled it in customizer it will be completely disabled and hidden on frontend.

**Comment by 79ho3ein** [comment]
It is true.Thank you very much dear @UraraReika .
