### ISSUE TITLE
JetEngine: Data Stores: Allow to query by *NOT* in data store

### ISSUE THREAD

**Issue by oguruma1218** [CrocoBlock/suggestions#4244]
I would like to see a feature in which you can use JetEngine to do queries by items that are NOT in a data store.

For example: I have a data store called "recently visited" which includes posts that the visitor has  visited. I would like to be able to query posts that are NOT in the data store, so that would mean posts that the user has not visted before.

**Comment by MjHead** [comment]
Hi @oguruma1218 You can do this by using Posts Not In option in Query Builder and macros Get Store
