### ISSUE TITLE
BUG / Show "Product Added to Cart" / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4257]
hello
If you enable the ajax add to cart option from the jet woobuilder settings and then add the product to the cart, the "Product added to cart" notification will not be displayed. **But after we enter the cart page, it will be displayed!**
This was reported by many website users as a bug.
Displaying WooCommerce notifications is a big hassle. Of course, this problem will be solved by adding the ability to display WooCommerce notifications as a pop-up. Please add this feature if possible.
please check this bug.

Thank you

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently. Or contact our support team so they can help you to solve this issue.
