### ISSUE TITLE
Notify wishlist customer when price drops

### ISSUE THREAD

**Issue by electrodm** [CrocoBlock/suggestions#4259]
It would be great if the Wishlist plugin could have the option to email customers when the price of a product drops.

**Comment by UraraReika** [comment]
Unfortunately we do not plan to introduce such functionality into the core our plugin. Now our team is working on more priority tasks and this task does not correspond to the functionality of our plugin But I recommend you to check our custom service - we take such cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/

Thank you for your understanding.
