### ISSUE TITLE
Add option to Duplicate\Clone Post Type

### ISSUE THREAD

**Issue by pintolog** [Crocoblock/suggestions#426]
Please Add the Action\Option to duplicate a PostType in JetEngine without the need to export it, import it & then have a mass to figure out what is what.

**Illustration of this Feature:**
![image](https://user-images.githubusercontent.com/7497319/62680804-cf0b6280-b9c0-11e9-8d02-c39c6b2dbf7b.png)

**Comment by bluehavoc** [comment]
This would be an awesome time-saver.

**Comment by neylwalecki** [comment]
+1

**Comment by neylwalecki** [comment]
And the option to duplicate any post as well.

**Comment by ayhanmalkoc** [comment]
+1

**Comment by donnakat1** [comment]
+1

**Comment by smithbenites** [comment]
+1

**Comment by Spacefunls** [comment]
+1

**Comment by maljassem** [comment]
We Really need this feature.....

**Comment by AzerTrex** [comment]
+1 - It's a feature for CCTs, it should be available for CPTs as well!

**Comment by slaakk** [comment]
+1 - Would save hours

**Comment by JamesT388** [comment]
+1

**Comment by creativetoria** [comment]
+1

**Comment by affiqfadzil** [comment]
+1
Yes, really need this.

**Comment by lightweb2** [comment]
+1

**Comment by enricgomez** [comment]
+1

**Comment by kaskad88** [comment]
Added for the next version (2.11.5)

**Comment by Nicolas-Lefebvre** [comment]
To duplicate post from CPTs :
- Install the plugin Yoast DUplicate Content
- go to the plugin's settings
- Second tab will let you chose whi post types you'd like to duplicate

Saves hella time 👍
