### ISSUE TITLE
Ability to scroll vertically in the search results section / jet search plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4260]
**Please, describe the feature request, making it clear to understand.**

hello
It would be great if you could add scrolling to the search results section.

![Screenshot (205)](https://user-images.githubusercontent.com/77163248/139875930-b5fd7472-5cbf-4383-92a4-ac6235070c71.png)

Currently only pagination is possible. This will be great and more practical.

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
