### ISSUE TITLE
Ability to display the number of products found, for the product grid widget / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4262]
hello
If we design the product archive using elementor theme builder and product grid widget, we can not display a series of important information to users.
For example, when a user browses a mobile product category, he or she does not know how many products are on the list.

Please see this image : https://prnt.sc/1y6fapy
As shown above, Suppose the user logs in to the store page. Using this feature, the user sees at a glance that 35 products are available in the store. Now if the user activates a filter, the number of products will decrease. Thus, the number of 35 products changes and displays the number of products that the user has filtered. Next, if the user disables the filter, the number of re-products returns to the first state (35).
In general, this feature shows users the number of products in each archive. Whether it's a store page, a specific category, or how many products before and after activating the product filter. This feature is extremely useful. Also very essential.

**I also had a suggestion to add this feature ...**
I suggest adding the dynamic tags section to the jet woobuilder. This is much needed and will be very useful even in the future.
**For example, to display the number of products I mentioned above, just add the title widget or even the elementor icon list, and in the dynamic jet woobuilder tags section, select the number of products option.** Using this method, we can easily display the number of products to users. Dynamic jet woobuilder tags will be very useful in the future.
Please check these items.

thank you

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Right now you can achieve this result with the help of JetEngine Query builder - https://tppr.me/cNt7W3 and JetEngine Query Result Count dynamic tag - https://tppr.me/G6c5eh. All this perfectly working with JetSmart Filters.

Thank you for your understanding.
