### ISSUE TITLE
Closing Tabs (Classic Accordion)

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4270]
There is a Classic Accordion widget (Figure 1) please tell me, can you do that when the parameter is enabled (Close when clicking on another element?) they also closed already open tabs.
If the function is disabled, the open tabs are closed, but unfortunately when you click on another element, the tabs are not closed, and if the function is enabled, then when you click again, the current tab is not closed.
In general ) Please
make sure that when you click on another element , the tabs are closed and when you click on the current element , the tab is also closed
![444](https://user-images.githubusercontent.com/47380983/140078474-81d4aa43-2e79-48f6-a3fa-3e2413db4bf0.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
