### ISSUE TITLE
Crocoblock Jet Woo Builder: My Account Content Widget/Mega Menu Issue 

### ISSUE THREAD

**Issue by Hurcann** [CrocoBlock/suggestions#4273]
Hello,

I'm having similar type issues that I've now been working on for weeks (I'm embarrassed to say).

I have a long dialogue open with Crocoblock support but at this point they're just copy/pasting the same response over and over. I'm hoping someone might be able to help here.

I followed the new crocoblock tutorial for making endpoint templates in jet woo builder and assigning them in woocommerce settings.

I then created a new menu with the endpoint templates.

I created a seperate jet woo page for "My Account" --> I inserted the vertical mega menu in one column and the "My account content" widget in the other column (just like in the tutorial).

The issue I cannot solve is --> there is no automatic connection between the menu I created and inserted and the my account content widget. The only thing that loads (automatically, not connected to the actual menu button) in my account content widget is the dashboard. Please see the attached photo for how it looks.

The menu items do not display the endpoint templates I created.

I did have some slug/permalink issues that I thought would solve the problem but did not. All my slugs match through woocommerce and the endpoint template.

I'm hoping someone can at least lead me in a direction to try something new to fix it because I'm ready to pull my eyeballs out over this problem :)

Thank you.
<img width="1143" alt="Screen Shot 2021-11-03 at 1 18 58 PM" src="https://user-images.githubusercontent.com/93670341/140157173-dbd2eeed-9933-4825-bff4-5c9ed671d4dc.png">

**Comment by UraraReika** [comment]
Hello @Hurcann !

Tell me please your ticket number.

**Comment by Hurcann** [comment]
hello, this problem was solved. 

The endpoint templates do not update on the back end unless the preview window is open and refreshed as updates are made. 

Thank you
