### ISSUE TITLE
JetSmartFilters - filter bar with links, no radio, no checkboxes etc. 

### ISSUE THREAD

**Issue by luxpatrick** [Crocoblock/suggestions#428]
Add the possibility to add a filter bar with only links, no radios, no checkboxes, just the simplest way it could be. Not everybody is using it for Woocommerce. 

Elements portfolio widget has this ability.

**Comment by Floydtm** [comment]
@luxpatrick Hi! In the styles tab, you can configure the filter so that only text is displayed in it. http://prntscr.com/orkeog

**Comment by luxpatrick** [comment]
Support said not possible...

**Comment by luxpatrick** [comment]
your solutions doesn't work. Setting the size to zero results in a point in my case. And the labels don't seem to be links . So no filter any more. 
<img width="298" alt="Screenshot 2019-08-18 at 10 52 42 PM" src="https://user-images.githubusercontent.com/48523191/63230319-446e0300-c20b-11e9-8848-7e1a72264bc7.png">

**Comment by Floydtm** [comment]
@luxpatrick, at the moment, you can set a transparent color for these elements. We will try to add options in the following updates to the plugin. Keep for updates.

**Comment by luxpatrick** [comment]
Transparent makes them disappear. Where should people click?

**Comment by Floydtm** [comment]
@luxpatrick,  thus we made the icons of the checkbox transparent. this does not apply to labels. look at the answer in the request #451

**Comment by realstephenzhao** [comment]
> 
> 
> @luxpatrick Hi! In the styles tab, you can configure the filter so that only text is displayed in it. http://prntscr.com/orkeog

Hi, I can make it work and style it using css(hide elements, change hover state and active state). But where is "Select All" option in Radio Filter widget? I need to put a "Select All / Reset / Remove" option left beside the first item of radio filter just like your Select Filter widget.

Any update to release a real fiter bar widget?

**Comment by Floydtm** [comment]
@luxpatrick, in version 1,7,0 we added additional style settings
@realstephenzhao, by logic, a radio filter cannot select all values. You confuse this with a check box filter. I think soon we will add it
