### ISSUE TITLE
Dynamic tags for my account page / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4281]
Hello
As I explained in # 4262, dynamic tags will be very useful and efficient for jet woobuilder in the future.
Here are some important suggestions on my account page, which I think are very useful and helpful.
It would be great if we could show a series of information to users' accounts.
Therefore, after registration, users can view a series of important information on their user page.

This information includes :
1- The number of days the user has registered on the website
2- Number of orders registered by the user on the website
3- Number of comments the user has submitted for products
4- Total orders amount (from the beginning of registration until now)
5- Number of tickets registered by the user (if the ticket plugin is installed)
https://prnt.sc/1yfwug7
All of the above requires dynamic tags in the jet woobuilder. This feature is great. These 5 items I mentioned above are in user panel plugins. It would be great if it was added to Jet Woo Builder.

Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
