### ISSUE TITLE
Ability to insert user profile picture / Jet Woo Builder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4283]
Please add a feature to my account page so we can allow users to add photos to their account profile.
Currently, 50% of this can be done. We can make the elementor image widget dynamic(Dynamic to account image).
But the user can not change her account photo!
Please add a feature to my Account page> Account details, so that the user can change or delete their account photo completely.this is fabulous.

Finally, 2 more features are required for the male user profile :

1- Ability to set the limit for uploading an account image.For example 1 MB. Therefore, the user can not upload a larger image to his account.

2- Ability to specify the default user image. If the user does not upload the photo to their account, this image will be displayed by default.

Finally, I emphasize that for now, we can display the user account image using the image widget, but the user can not change or delete their image.
In fact, we need jet woobuilder to add a section to the account details, so that the user can change or delete their profile.

Thank you

**Comment by Floydtm** [comment]
Hi, this request cannot be implemented in the jetwoobuilder plugin. Right now you can implement with jetengine -> profile builder https://crocoblock.com/knowledge-base/articles/jetengine-user-profile-builder-overview/
