### ISSUE TITLE
Product page URL more friendly

### ISSUE THREAD

**Issue by ElAlceWeb** [CrocoBlock/suggestions#4287]
I want you to help me solve this!
When I add pagination to a category product, for example when I clicked in 2 page, the url is not too nice.

for example a real case: **https://www.poemasenmadera.com/casitas-de-pajaros/?jsf=jet-woo-products-grid&pagenum=2**
maybe it would be alright the user could see **https://www.poemasenmadera.com/casitas-de-pajaros/2/**

:D

**Comment by Floydtm** [comment]
Hi! I understand that this is important to you, but I must tell you that now it is not possible to do it. Thank you!
