### ISSUE TITLE
[JetEngine] Possibility to customize your own AJAX loading animation

### ISSUE THREAD

**Issue by edgarBllw** [CrocoBlock/suggestions#4288]
hello,

it would be cool if you could adapt this animation somehow. because by default only the background is grayed out until the content has been loaded

like on booking.com :)

https://user-images.githubusercontent.com/92536649/140611701-e4b94f6f-7c84-46de-a4d4-8e33c5432b0f.mp4

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
