### ISSUE TITLE
[JetEngine] Option for a popup after successfully submitting a form

### ISSUE THREAD

**Issue by edgarBllw** [CrocoBlock/suggestions#4289]
this possibility already exists in elementor. unfortunately it is still missing in the jet engine forms

https://user-images.githubusercontent.com/92536649/140611801-5b4438a0-8d73-4abe-afb2-f2a00915db40.mov

**Comment by Floydtm** [comment]
Hi! Use this addon https://crocoblock.com/freemium/tools/ https://prnt.sc/1ystvnz

**Comment by de-er-kid** [comment]
> Hi! Use this addon https://crocoblock.com/freemium/tools/ https://prnt.sc/1ystvnz

This doesn't works anymore, is there any other to toggle/open a popup after form submission?

**Comment by TecnoTriks** [comment]
Esse código me resolveu.
This code solved it for me.
![Captura de tela 2024-05-29 190859](https://github.com/Crocoblock/suggestions/assets/20442409/b63e55dd-04b9-492a-acad-7ab586c2d022)
Code:
`<script type="text/javascript">
jQuery(document).ready(function($) {
    // Intercepta o envio do formulário ao clicar no botão "Atualizar"
    $('.jet-form-builder__action-button').on('click', function(e) {
        var $this = $(this);
        // Aguarda 2 segundos após o clique no botão de enviar do formulário
        setTimeout(function() {
            // Simula o clique no botão de fechar o pop-up
            $('.jet-popup-action-button a').trigger('click');
            // Se você deseja enviar o formulário após clicar no botão "Atualizar", remova o comentário da linha abaixo
            // $this.closest('form').submit();
        }, 2000); // Tempo em milissegundos (2 segundos)
    });
});
</script>
`
