### ISSUE TITLE
JetSmartFilters - add support for elementor portfolio widget

### ISSUE THREAD

**Issue by luxpatrick** [Crocoblock/suggestions#429]
JetSmartFilters - add support for elementor portfolio widget. no more to say. 
<img width="417" alt="Bildschirmfoto 2019-08-08 um 23 30 44" src="https://user-images.githubusercontent.com/48523191/62739303-c5bbdd80-ba34-11e9-9313-264f8e6d2514.png">

**Comment by Floydtm** [comment]
Available in the plugin starting from version 1.7.0
