### ISSUE TITLE
WooCommerce pop-up notifications

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4299]
In the current situation, we lose the main WooCommerce notifications. This situation is very uncomfortable for users. They are complaining to us about this. Obviously you decide to extend this feature to jet woobuilder. But is there a deadline for its release?
Please let us know

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

Please describe your request i more details.

**Comment by Michaelgimii** [comment]
thanks @UraraReika
After adding a product to the cart, the product message added to the cart will not be displayed. This message will be displayed if we enter the shopping cart after that. This problem is really painful.
This problem will definitely be solved by adding the feature of displaying WooCommerce notifications as pop-up .
Please add this feature sooner. In this case, this problem will be solved forever. I'm really worried about this.
Is it clear when you publish this feature? Answer if possible. Will it be added in 2021?

**Comment by UraraReika** [comment]
I merged this issue with #2249, which is on the same subject so we could deal with it more efficiently.
