### ISSUE TITLE
API rest for CPT

### ISSUE THREAD

**Issue by Topicimes** [CrocoBlock/suggestions#4302]
Hello to all,
The whole of my suggestion is in the title. Allow DTCs to have access to the API in order to link them to other websites, or to create associated mobile applications.

Thanks in advance for your feedback.

**Comment by MjHead** [comment]
i! CPTs available in the API from WordPress core. Just make sure this option in Advanced Settings of required CPT is enabled - https://gyazo.com/eaaa9340b4b2ef19be4a92ffef8b328a, than your posts will be available by this path - {your webiste URL}/wp-json/wp/v2/{CPT slug}
