### ISSUE TITLE
Jetwoobuilder : Single Reviews Form needs Customization 

### ISSUE THREAD

**Issue by dazdazslk** [CrocoBlock/suggestions#4306]
Hi Team.

I'm using **Single Reviews Form** widget on a **Jetwoobuilder** template.
It seems that we can't modify the style of this widget.
I managed to add custom CSS to style it for the Desktop version on my website.
But for the mobile version it might require CSS skills that I'm very far to get.

Would it be possible for the Crocoblock Team to implement the possibilty to style this widget ?
The feature that would be very usefull to have is to be able to place the submit review section under or above the reviews bloc.
(This is what i'm trying to do with CSS but with no success.. :/ )

Thank you Crocoteam !

Daz from Paris.

Edit : Still waiting for update.
We need to be able to have some possibilities to customize those fields..
Thx team

**Comment by Lonsdale201** [comment]
If you want to make separate, to one field with only submit, and the prodzcts tab only list all of review like in my example:

![image](https://user-images.githubusercontent.com/23199033/141146508-cfe24dba-953b-4385-9e6c-53b79c1da08f.png)

You can use the following css code:

Code for the **single reviews form widget:**
(recommended to add a specific unique class for your widget in here: https://prnt.sc/1z1eub1 ), or overwrite every .mysingle--rew to: selector 

```
.mysingle--rew .commentlist {
    display: none;
    height: 0;
}

.mysingle--rew .woocommerce-Reviews-title  {
    display: none;
}
.comment-form-rating p:nth-last-child(2n) {
    display: none;
}

.mysingle--rew  .comment-reply-title {
    font-size: 16px;
}

.mysingle--rew  .woocommerce-noreviews {
    display: none;
}
```
This code will hide everything, and only show the submit review option.

Next code a  "reverse" for this technique, for the "Single tabs" widget.

```
 .woocommerce-Tabs-panel--reviews  #review_form_wrapper
{
    display: none!important;
}

```

**Comment by dazdazslk** [comment]
Thank you so much Lonsdale for this suggestion !
I'll try what you've explained when I can and give you feed back.
It takes my a bit of time since i'm new on github and noob at cooding.

Thank's again man ! Means a lot

**Comment by UraraReika** [comment]
Hello @dazdazslk !

Did you try to use JetReviews plugin? This can be the thing you need. You will have full control on your review system and a lot of styles possibilities.

[Here](https://crocoblock.com/knowledge-base/article-category/jetreviews/) you can find some knowledge about it.
[Here](https://crocoblock.com/knowledge-base/articles/jetreviews-how-to-add-reviews-to-the-post/) specific one.

Look closer on our [demo](https://crocoblock.com/plugins/jetreviews/) site.

The other thing that this widget doesn't have any styles is that the style and view of this widget is often affected by your theme and plugins.
