### ISSUE TITLE
Hide empty values in the Price list widget

### ISSUE THREAD

**Issue by Olegggggggg** [Crocoblock/suggestions#431]
Add the ability to "Hide if value is missing" to the Price list widget
![2019-08-09_20-14-10](https://user-images.githubusercontent.com/53747082/62789449-5d2b3a00-bae2-11e9-968f-9324e5467fe3.png)

**Comment by Floydtm** [comment]
@Olegggggggg Hi! 
Could you describe your request in more detail? if possible, add screenshots or videos

**Comment by Olegggggggg** [comment]
The function "Hide if the value is missing" is now in the Dynamic Field widget (first screenshot). In the event that I output meta data but this value is absent in the record, the field is not displayed at all. It is very convenient.
It would be nice to do the same in the Price List widget. Now, if I output meta data through the price list and the meta fields are empty, an empty price list template will be displayed, as in the second screenshot.
![2019-08-13_14-30-56](https://user-images.githubusercontent.com/53747082/62932103-f30fdf00-bdd8-11e9-829e-2b16f2d681dc.png)
![2019-08-13_14-45-22](https://user-images.githubusercontent.com/53747082/62932160-1175da80-bdd9-11e9-8e7e-96d2a153b170.png)

**Comment by kaskad88** [comment]
Added for next version ( 2.1.0 )
