### ISSUE TITLE
JetTricks : The Unfold widget not compatible with the Additionnal Breakpoints feature (beta) of Elementor

### ISSUE THREAD

**Issue by dazdazslk** [CrocoBlock/suggestions#4311]
Hi Team.

Unfold widget by **JetTricks** is very usefull for mobile.
It worked like a charm before activating this experiment of Elementor : _Additionnal Breakpoints._
Unfortunately, when activated, the widget starts to bug.

Description : 

- I edit a new page with Elementor using Unfold widget by JetTricks
- I check the result : it works
- I refresh the same page : it breaks. The button allowing to unfold disapears and the layer bugs.
- Checking the console the error is this type : Uncaught TypeError: Cannot read properties of null (reading 'size')
    at widgetUnfold (jet-tricks-frontend.js?ver=1.3.8:168) etc..
    
    I understand that this feature is Beta and brought to us by Elementor so may be my post here for the CrocoTeam is irrelevant. 
    But if you can do something about this in the next JetTricks update it would be awesome !
    This Additionnal Breakpoints feature is a game changer for people like me with no coding skills using this entire ecosystem 🙏
    
    Thanks for reading !
    
    Daz

**Comment by dazdazslk** [comment]
Hope we will have this issue fixed soon !
In the meantime if you have any solution to propose me to make the Unfold widget work with the Additionnal breakpoints activated it would be very, VERY helpfull for me : pray : 

Thank you for any tips !

**Comment by dazdazslk** [comment]
I was forced to buy Premium Addons.. Unfold widget works perfectly with the " experiment breakpoints " ...

**Comment by Floydtm** [comment]
Compatibility was added in version 1.3.9
