### ISSUE TITLE
Календарь событий из разных произвольных записей

### ISSUE THREAD

**Issue by EvgenKlb** [CrocoBlock/suggestions#4312]
Необходим Календарь событий, отображающий записи разных типов. 
В настоящее время виджет Календарь возможно применить только для одного типа записи. В то же время, думаю, что нередко, на сайте могут быть разные типы записей для различных видов событий. 
Очень удобно было бы использовать один календарь для всех событий на сайте, а не делать несколько календарей под каждые типы событий.
Спасибо!

**Comment by Floydtm** [comment]
Please, note, that the feature requests can be accepted and processed only if they’re written in English.
