### ISSUE TITLE
Show photo captions in the gallery of repeater fields

### ISSUE THREAD

**Issue by REMWEB** [CrocoBlock/suggestions#4313]
Though there is a macro for presenting the image url of each image (% gallery-name | img_url_by_id%), there is not one for showing each photo's caption (or description), as it it is stored in WordPress "media".

I think, that presenting the caption for the photos of the the gallery of repeater fields would be very useful.

Thanks
Marialena

**Comment by NulledStation777** [comment]
We need it!

**Comment by morosmo** [comment]
+1

**Comment by karmelp** [comment]
+1

**Comment by MjHead** [comment]
added in 3.5.0 update
