### ISSUE TITLE
jet woobuilder plugin

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4314]
hello jet woobuilder developers

In such a large plugin, why not display the bestsellers products in your queries section? (product grid widget)
This is really weird. But we can show the recently viewed, but not the bestsellers products! This is really frustrating.
It is possible to display bestsellers products on all store websites. Why should we not have? Customers ask us to display their bestsellers products on the website. But we can not. Please add this feature. Please
For example, we can not display the bestsellers products of category x. Isn't this really needed?
Showcasing bestsellers is the most important feature of WooCommerce. But why should a jet woobuilder lack it?
Please add the query of bestsellers to the product grid widget. This is my only wish ...

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

You want to display only products that has sales of first of all products with sales than everything else?

**Comment by Michaelgimii** [comment]
hello @UraraReika
**Products that have sold more than other products (Best Selling).** This feature is available in the jet elements plugin, but it is really needed for jet woobuilder. Please add this query to the product grid widget. please please
This is what many customers want from us, but we can not implement it. Please do not reject this request. This query is essential for this plugin.
This is on most online store websites.

**Comment by Michaelgimii** [comment]
hello @UraraReika , Will this feature be added? please

**Comment by UraraReika** [comment]
Release this week.

**Comment by Michaelgimii** [comment]
thank you thank you

**Comment by Michaelgimii** [comment]
hi @UraraReika.
How exactly does this query work?
Several products were displayed when I put the query on the "bestsellers". The website, on the other hand, had no sales.
Can you explain how this query works?

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

We use `total_sales` meta key to handle this query.
