### ISSUE TITLE
Hamburger menu to push content right or left while its slide out

### ISSUE THREAD

**Issue by 3nines** [CrocoBlock/suggestions#4322]
We need an option in the “**Hamburger menu**” to push the content left/right while it's sliding out or in.

There are only three options available right now: **Slide out / Dropdown / Push**. And these options are wrong for the content, for example when you choose “**Push**” in “HAM-MENU” it pushes the content down? Instead of pushing the side you have chosen to slide come out from. 

https://imgur.com/kblM9PF

Look in here, something like this ; https://codepen.io/ncerminara/pen/KJjiD. This is mush easier to understand and also more standard feature to must have. 

I can easily go around this with that CSS-CODE above, but I think it's much easier and better for the client and future designer to just have these options to choose from via layout menu.

**Comment by Lonsdale201** [comment]
+1

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
