### ISSUE TITLE
Ability to assign a query to a specific category in / Jet wobbuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4324]
hello
Now, if we set the query to "sale", it will show all the sale products. It would be great if we could assign a sale to a specific category.
https://prnt.sc/1zbox40
For example, we have a landing page that is only for mobile phones and we want sale to show only mobile phone products. No other categories. That's great. I hope I have conveyed my point well.

thank you

**Comment by UraraReika** [comment]
You can do this like so:
https://gyazo.com/d233907c34cb50fffb87ca3c5ebed75d then add additional query https://gyazo.com/9cd2c5a0ffc8b3c4b77708137d7ab1e0

**Comment by 79ho3ein** [comment]
thank you
