### ISSUE TITLE
Cross sells query in the cart page / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4329]
hello
Currently, we can not display cross sells products in the cart as a carousel (in product grid widget). There is only one cross sells widget which is very simple.
If possible, please add a cross sell query to the product grid widget in the cart page. https://prnt.sc/1zf2olt
This is excellent and required.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Products Grid widget can display cross sell items in cart page.

Open your Cart Template. Place Products Grid widget. Save Template. Reload editor page. Then in Query by control you will be able to see Cross Sell option in the end.

**Comment by 79ho3ein** [comment]
thank you dear @UraraReika
