### ISSUE TITLE
JetEngine: Is it possible to redirect users to page with filters already set? (Forms)

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#4332]
We have a form on our website where users can fill out details like:

- How many people in house (**Example 2**)
- How many kilowatts do they use each month (**Example 3000 kwt**)
- And what kind of contract they want (**Example Spotprice**)

When the user clicks "Search" - Is it possible to redirect them to a page that contains a list with the jet smart filters already set and activated?

So when user clicks search on the form - they will be redirected to a new page -
With filters already activate: 2 in house - 3000 kwt & spotprice.

Thank you!

**Comment by MjHead** [comment]
Hi! Yes, you can do this:
1. Add required filters to the initial page. 
2. Set for all filters provider in the usual way, like with listing on the page and apply type - Click on apply button
3. Add separate Apply button widget on the page and select required page to redirect:
![image](https://user-images.githubusercontent.com/4987981/145606767-cfba2d04-4e79-40f8-bcc7-94b74089956e.png)
Here you can see this in action - https://demo.crocoblock.com/findero/
