### ISSUE TITLE
Autoplay feature and linking option for the audio player.

### ISSUE THREAD

**Issue by josiase95** [CrocoBlock/suggestions#4334]
Hello CB,

lets say someone is making a podcast website, music store or any kind of music service. Maybe the person has a CPT with a listing grid of songs (like Itunes, Tidal, Spotify etc.). It looks very bad having the audio player displayed right in a listing grid, so the optimal solution, which is also used by the companies listed above, is to have a play icon on the listing grid, triggering a popup with the audio player in. So if you could update the audio player to make it possible to use it in a popup / have an autoplay function, that would be amazing, Also if you could link the play button so if you use it like explained above, the play button in the grid will activate the popup + it will sync with the audio player in the popup. :-)

**Comment by MiffedLyric559** [comment]
Add: Autoplay should definitely be added as a feature. PLUS

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
