### ISSUE TITLE
JetEngine: Switch to use Field in Repeater as Repeater Field Title

### ISSUE THREAD

**Issue by marlokessler** [CrocoBlock/suggestions#4335]
It would be awesome if you could implement a switch for a field in a repeater field to allow that field (e.g. a text field) to be the title of the repeater field, so that multiple repeater fields can be differentiated and reorganised more easily by users if collapsed. E.g.:

In a "Recipe" post type on a food blog there is a repeater section for the ingredients. Each ingredient repeater field consists of the fields "amount", "unit" and "ingredient". There is a switch at the bottom of each field which can be switched if it should be also used as the title of the repeater field. For the "ingredient" field it is turned on:
<img width="1257" alt="Screenshot 2021-11-13 at 23 10 06" src="https://user-images.githubusercontent.com/48910761/141660777-80a89c10-c10b-4b3b-a93e-85658878b77c.png">

So when a user now creates a recipe and enters the ingredient, the repeater field title changes dynamically when the user enters the ingredient into the "ingredient" field:
<img width="1257" alt="Screenshot 2021-11-13 at 23 06 45" src="https://user-images.githubusercontent.com/48910761/141660810-5e8d8f9d-0251-4e5e-93b6-c3ab2dcd19e5.png">

With this he/she can easily differentiate between multiple repeater field, when collapsed (e.g. collapsed to reorganise them):
<img width="1257" alt="Screenshot 2021-11-13 at 23 17 40" src="https://user-images.githubusercontent.com/48910761/141660829-105d7fe6-a114-4143-a225-621d4579859e.png">

**Comment by kaskad88** [comment]
Added in JetEngine 2.10.2 https://prnt.sc/20xamn3

**Comment by marlokessler** [comment]
Thank you a lot, that is a really helpful feature!
