### ISSUE TITLE
JetProductGallery does not support Woocommerce Additional Variation Images, but JetWooBuilder does.

### ISSUE THREAD

**Issue by campiotto** [CrocoBlock/suggestions#4338]
Hey guys,

I am working at a Fitness clothing store and we would like to have a complete individual gallery for each color.

I followed this guide:
https://crocoblock.com/troubleshooting/articles/fail-to-add-attractive-variation-swatches-to-woocommerce-archive-page/?fbclid=IwAR10HLY3uRdbGrhqLWEfxKJDV41zDXsqGF1X_Dna56prNdOQu41rnai

I managed to do this, but there's something really weird.

When changing the color of the variation, jetproductgallery doesn't change all the images, only the first one on the cover.

I installed this plugin: Woocommerce Additional Variation Images, it works perfectly with JetWooBuilder and Woocommerce Additional Variation Images, but it doesn't work with JetProductGallery.

Could you guys add compatibility?

I am a fan of jetengine with a lifetime license that I have a lot of honor.

**Comment by UraraReika** [comment]
I merged this issue with #2619, which is on the same subject so we could deal with it more efficiently.
