### ISSUE TITLE
Bug in Scroll Navigation when sticky

### ISSUE THREAD

**Issue by ctrotzky** [Crocoblock/suggestions#434]
On a page I have multiple sections which all are made sticky using Elementor Pro's feature. As soon as I activate the sticky section from Elementor, the ScrollNavigationElement gets confused when reloading the page with an anchor in the URL. It's not possible to navigate through the sections and it is not updated correctly when scrolling the page.

To reproduce:

- Create a page with 3 sections in Elementor- Make all sections "Sticky" using "Top" setting
- Add an ScrollNavigationElement to the top and configure it to use the 3 sections (CSS IDs ...)
- Open the page and scroll around: Still looks okay
- Reload the page (which will use the anchor as inserted to the URL while scrolling)

Result: The page loads at a strange position and the scroll indicators are not working correctly anymore.

**Comment by Floydtm** [comment]
@ctrotzky Hi!Could you provide an example where this works as you please. Thanks you!
