### ISSUE TITLE
bug in jet compare&wishlist

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4346]
hello
To reproduce this bug, please follow these steps :

1- Make sure you are not logged in to the website. (guest user)
2- Add products to your wishlist
3- Open your favorites list. You will see that the product is in the list.
4- Return to the main page. Now if you look at your favorites list, the number of products on the list is 0. while you did not remove that product from the list.

thank you

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
Thank you
