### ISSUE TITLE
Scrollable tabs

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#4349]
I went through popular elementor addon collections of different themes but couldn't find any scrollable tabs. Scrollable tabs are mostly handy on mobile screens to slide. 
One example is here https://amuli.axiomthemes.com/   on an Apartments Plans section, It is really amazing. Would be better if you added such feature 😉

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
