### ISSUE TITLE
JetWishlist apply_filter woocommerce_product_add_to_cart_text

### ISSUE THREAD

**Issue by odedta** [Crocoblock/suggestions#435]
Hello,

I would like to have an icon-only button for add to cart both on archive pages and on the Wishlist page.
I'm using this code to accomplish that:
**functions.php**
```
function delab_woocommerce_product_add_to_cart_text() {
	return __( '<i class="fa fa-cart-plus" aria-hidden="true"></i>', 'woocommerce' );
}
add_filter( 'woocommerce_product_add_to_cart_text', 'delab_woocommerce_product_add_to_cart_text' );
```

**CHILD_THEME/woocommerce/loop/add-to-cart.php**
```
echo apply_filters( 'woocommerce_loop_add_to_cart_link', // WPCS: XSS ok.
	sprintf( '<a href="%s" data-quantity="%s" class="%s" %s>%s</a>',
		esc_url( $product->add_to_cart_url() ),
		esc_attr( isset( $args['quantity'] ) ? $args['quantity'] : 1 ),
		esc_attr( isset( $args['class'] ) ? $args['class'] : 'button' ),
		isset( $args['attributes'] ) ? wc_implode_html_attributes( $args['attributes'] ) : '',
		$product->add_to_cart_text()
	),
$product, $args );
```
*Notice that the function _esc_html()_ was remove from _$product->add_to_cart_text()_

Product Archive look: [https://imgur.com/a/l3CrmAa](https://imgur.com/a/l3CrmAa)
Wishlist look: [https://imgur.com/a/F5fl6bX](https://imgur.com/a/F5fl6bX)

The archive product pages show an icon where the Wishlist page shows the `<i>` tags code.
Please allow the esc_html() for the content.
Would love to know if there's another solution for this, thanks!

**Comment by Floydtm** [comment]
@odedta Hi! Please, create a ticket here https://support.crocoblock.com and our development team will help you.
