### ISSUE TITLE
Put the out-of-stock products to the end of the query in the Products Grid widget

### ISSUE THREAD

**Issue by marcofrasson** [CrocoBlock/suggestions#4356]
I would like to put the out-of-stock products to the end of the query in the Products Grid widget, how do I do it?

For the default WooCommerce querty this is https://stackoverflow.com/questions/25113581/show-out-of-stock-products-at-the-end-in-woocommerce

**Comment by UraraReika** [comment]
Hello @marcofrasson !

You can achieve this setup your widget like [this](https://i.gyazo.com/182fc139579a57be94748b3ae36e02fc.png).

**Comment by marcofrasson** [comment]
@UraraReika I'm using the current query for category pages and it doesn't have this option.

And out-of-stock products mix with out-of-stock products, causing confusion for customers.

If I use the element's default listing, I can filter the query according to the link I passed, but I need to use JetWooBuilder's Products Grid. https://ibb.co/1GmJNw4

**Comment by UraraReika** [comment]
If you use this option then widget take global query for products. You have some controls for query [here]( https://i.gyazo.com/0f7a2efdc865bb57e225f0a49b16bec8.png). You although can add additional [sorting option](https://i.gyazo.com/e87a4ff19570f17d26b919e9d57b4827.png) to achieve your goal.

```
add_filter( 'woocommerce_default_catalog_orderby_options', '__ypur_theme_prefix_custom_wc_catalog_orderby' );
add_filter( 'woocommerce_catalog_orderby', '__ypur_theme_prefix_custom_wc_catalog_orderby' );

function __ypur_theme_prefix_custom_wc_catalog_orderby( $sortby ) {

	$sortby['stock-status'] = 'Sort by Stock Status (asc)';

	return $sortby;

}

add_filter( 'woocommerce_get_catalog_ordering_args', '__ypur_theme_prefix_alphabetical_shop_ordering' );

function __ypur_theme_prefix_alphabetical_shop_ordering( $sort_args ) {

	$orderby_value = isset( $_GET['orderby'] ) ? wc_clean( $_GET['orderby'] ) : apply_filters( 'woocommerce_default_catalog_orderby', get_option( 'woocommerce_default_catalog_orderby' ) );

	if ( 'stock-status' == $orderby_value ) {
		$sort_args['orderby'] = 'meta_value';
		$sort_args['order'] = 'ASC';
		$sort_args['meta_key'] = '_stock_status';
	}

	return $sort_args;
}
```
