### ISSUE TITLE
Add Dynamic settings to the Horizontal timeline

### ISSUE THREAD

**Issue by SjansenDesign** [Crocoblock/suggestions#436]
There is support for Dynamic settings in the Vertical-timeline but not in the Horizontal time-line. Very strange that this is not implemented. I think this is a quick fix.

See the screendumps.

<img width="301" alt="Vertical timeline with dynamic settings" src="https://user-images.githubusercontent.com/53438156/62849086-7d274d00-bcde-11e9-9e4d-fed84cb835a3.png">
<img width="300" alt="Horizontal-timeline-NODynamic settings" src="https://user-images.githubusercontent.com/53438156/62849087-7d274d00-bcde-11e9-9f1d-fd2fd569a5f7.png">

**Comment by kaskad88** [comment]
Added in JetElements Dynamic Data Addon v.1.1.1
