### ISSUE TITLE
JetTricks - Alignment for Read More Widget

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#4361]
I see the current readmore button widget is missing the Alignment feature. 
![image](https://user-images.githubusercontent.com/89138954/142347313-72a1f0bd-f4a3-4682-8a2c-95b9cbb643c4.png)
Align left, right, center, align both sides. 
Hoping to add more in the future
![image](https://user-images.githubusercontent.com/89138954/142347280-57d33c82-43e3-40cb-929a-4f2928131262.png)

**Comment by BrockwayProd** [comment]
Thanks for fixing this, this was so stupid/mindblowing that the button doesnt had at least the same available options than a default Elementor button.
