### ISSUE TITLE
After selecting the visual filter, the selected filter is not easily recognizable. / jet smart filters

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4362]
hello
If the user selects the visual filter, for now, only the margin of the active filter will be colored : https://prnt.sc/200q944 (green border)

**Desired solution :**
I suggest adding a feature instead of the current one, so that after selecting, the visual filters will be checked like the checkbox filters.
https://prnt.sc/200qk1j

This is much better and users can easily find active filters in the visual filter. Please check this item.

Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
