### ISSUE TITLE
Custom endpoint for user panel / jet woobuiler

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4364]
hello
It would be great if we could have custom endpoints. Currently, we are limited to just a few endpoints. For example, if we want to add a page to send user tickets in the user panel, this is not possible.
Please add this feature if possible so that we can create as many custom endpoints as we want. For a professional user panel, this is much needed.

thank you

**Comment by UraraReika** [comment]
I merged this issue with #2721, which is on the same subject so we could deal with it more efficiently.
