### ISSUE TITLE
JetWooBuilder | Sorting List Widget Bug

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#4367]
**Describe the bug**
JetWooBuilder | Sorting List Widget - JetWooBuilder Product Grid option selected | not working if in Product Grid widget "Use Current Query" checkbox is selected. It causes to all Products dissapears.

**Expected behavior**
Sorting List Widget must work with Product Grid Widget if "Use Current Query" is set.

**Comment by UraraReika** [comment]
Hello @s5t5n !
By "Sorting List Widget" you mean this [one](https://i.gyazo.com/537f333e79498c2dff6c3c9839a6e7ec.png)? Or maybe [this](https://i.gyazo.com/82f3c36d5a74098a119a54cab4d620bc.png)?

**Comment by petrovui** [comment]
> Hello @s5t5n ! By "Sorting List Widget" you mean this [one](https://i.gyazo.com/537f333e79498c2dff6c3c9839a6e7ec.png)? Or maybe [this](https://i.gyazo.com/82f3c36d5a74098a119a54cab4d620bc.png)?

I'm talking about your FIRST Screenshot. "Sorting Filter".

P.S. Your second screenshot contains widget called "Products Ordering". As u know Elementor Pro 3.5+ got his own Shop Template / Archive Template (i'm using it already). This wiget only appears at SHOP TEMPLATE by JetWooBuilder Template Builder, but anythere else. In default Elementor Pro 3.5+ Shop / Archive pages this widget not appearing in Elementor Builder Panel.

**Comment by UraraReika** [comment]
We have tested both variant and everything works fine. Maybe you miss connection between filter and widget. In filter enter [Query Id](https://i.gyazo.com/06a1890163bce76a2aa28bbbd07be7f5.png). In Products Grid widget enter [CSS ID](https://i.gyazo.com/9c12862b787db0f0da92d87c39fd58b9.png).
