### ISSUE TITLE
Display order information on my account page / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4368]
Hello
It would be great if you could add a feature that allows us to display the number of orders and the total price of orders in my tab account.
With this feature, the user can easily view the number of registered orders in his panel. You can also see the total price of your orders. For example, $ 1,000
This feature is extremely useful and is present in almost all professional user panels. Please check this.

Thank you

**Comment by Michaelgimii** [comment]
+1

**Comment by rodolphebertozzo** [comment]
+1000

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

But I've checked your request and such a goal can be reached using JetEngine in combination with JetWooBuilder and  a bit of custom code. I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such complex cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.
