### ISSUE TITLE
[Jetengine] Reorder options list in forms, select > manual input mode

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#4370]
it is while inserting the values that I realized that I cannot rearrange them .. which is very annoying and disrupts the work in progress and the flow of ideas.

![test](https://user-images.githubusercontent.com/82481592/142642493-c13a1a93-7357-469c-818b-969fd8b8d0d2.jpg)

it is these kinds of details that improve the quality of life and work with jetengine 😊

**Comment by MjHead** [comment]
Hi! This feature is available in JetFormBuilder - https://wordpress.org/plugins/jetformbuilder/ You can use it as replacement for the JetEngine forms. JetEngine forms are only maintained at the moment.

**Comment by kochhase** [comment]
yes but how to use https://wordpress.org/plugins/jetformbuilder/ without using Gutenberg??
