### ISSUE TITLE
The picture does not change in (JetCompareWishlist For)

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4374]
Created a bookmarks page!
In the listing grid, I created the output of posts and installed a bookmark widget there so that when you click on the widget, posts go to bookmarks!

In the JetWooBuilder plugin , the output of the selected listing has been set .

Everything works like clockwork ! but only I have the effect of replacing the picture, i.e. when hovering over the photo (the main photo changes to the second photo), the whole problem is that this function does not work in bookmarks (
i.e. if you use a widget (Wish list) that displays bookmarks and hover over the picture, then the picture will not be replaced (

Can you fix this problem ?

**Comment by UraraReika** [comment]
Hello @GOHA81177!

Please follow guidelines for opening a new [bug request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.

**Comment by GOHA81177** [comment]
Created a new ticket #4417
