### ISSUE TITLE
Custom fields using glossaries not showing

### ISSUE THREAD

**Issue by zabdala** [CrocoBlock/suggestions#4376]
I have a custom post type that has custom fields that link to glossaries. When testing the post and filling out the fields, the glossaries are not appearing after clicking on the "select" drop down option. 

An example of one of these custom fields is "Final Make Stage", seen below:
![image](https://user-images.githubusercontent.com/93880118/142703799-5d5fee92-6e47-43b5-ab02-7d228058c6f8.png)

In this example, I had already clicked on the field. Nothing appears except for a very short box (around 1-2px) that looks like it's trying to access the information, but is unsuccessful.

**Comment by kaskad88** [comment]
Hello. We tried to reproduce your issue based on the information you provided, but without success.

Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
thanks.
