### ISSUE TITLE
Add compatibility with bricks builder for Jet engine

### ISSUE THREAD

**Issue by promocot** [CrocoBlock/suggestions#4379]
Hello, today jet engine works with elementor and gutenberg, but this plugin works with oxygen. Please add compatibility with bricks builder. Link to documentation for developers: https://academy.bricksbuilder.io

bricks are a new progressive solution that combines the capabilities of oxygen and elemental. Just as before, the elementor did not have widgets for wokomers or modals with dynamic content and your solutions were the perfect solution, so bricks can be an opportunity for you to earn the same, every day the community of bricks is growing and many are switching from Elementor and oxygen (this I read in the group and on their website)

**Comment by Floydtm** [comment]
Sorry, guys, but we are not planning to integrate with Oxygen as well as Bricks, Divi, Brizy, Beaver, or other website [builders](https://www.facebook.com/groups/CrocoblockCommunity/posts/4533744080050311/).
