### ISSUE TITLE
[Request] Dynamic Gallery Enhancement: Masonry Layout, Text Overlay, and Lazy Loading

### ISSUE THREAD

**Issue by dennylai1990** [CrocoBlock/suggestions#4383]
For dynamic galleries, the current way to do it is by enabling Grid/Slider gallery in the Jetengine, and using the dynamic field widget to dynamically "pull" the gallery. However, its quite limiting in functionality, especially when masonry layouts are not available. Here are my suggestions:

1) Add the option for Masonry Layouts for dynamic gallery.
2) Combine Grid, Slider and **Masonry** layout in one option.
3) Grid, gallery or masonry should be device independent. Modern layouts often have a grid layout for desktop devices, and a slider layout for mobile devices. (This idea can also be done for listing grids)
4) Like the current elementor gallery widget, there should be an option to have title and description text overlays pulled dynamically.
5) Have an option for lazy loading like the current elementor gallery widget. However, as I'm using gallery in a repeater, I'm not sure how this will work out.

**Comment by mariodev114** [comment]
+ 1

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by dennylai1990** [comment]
How about the basic dynamic field widget for gallery? It is without masonry and text overlays. I could make do with the elementor pro gallery widget, which has all the functions I need. However, the elementor pro gallery widget wouldnt work if I work with repeaters.
