### ISSUE TITLE
Country and city selection field customization settings in jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4384]
There is a big limit in the checkout fields of this plugin. We can not customize fields like country.
![Screenshot (237)](https://user-images.githubusercontent.com/88034902/142777058-465ea07a-9867-49f3-a46c-7692378e30ce.png)
The image above is an example of this feature that does not exist in this plugin. Add settings for customizing country fields and the like. This is really needed.
For example, in the image above, all areas are well customized. Customize the city search box, the hover mode for city names, and the active mode, which were red and gray in the image above. Also customization settings for borders and typography for texts and even padding for any city or country name box. These are extremely necessary
In fact, the current situation is incomplete...

**Comment by UraraReika** [comment]
I merged this issue with #3793, which is on the same subject so we could deal with it more efficiently.
