### ISSUE TITLE
New mode for product grid carousel widget / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4385]
hello
Great if you add a new mode to the jet woobuilder carousel. I do not know exactly what its name is. But it is very good and is used in many sites today. Our customers also demand it a lot. The image below is a preview of this feature that I designed for a better description : 
![jet-woobuilder](https://user-images.githubusercontent.com/77163248/142781425-4fd639ac-a470-4fe5-9373-2a351cdb066e.jpg)
You are definitely familiar with this type of carousel.
Please add this new mode to jet woobuilder if possible. The place is very empty.

thank you

**Comment by Rubendj1** [comment]
This would be awesome! I've been looking for this.
