### ISSUE TITLE
Product not found message / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4386]
hello dear @UraraReika, good time!

The new Product not found feature was added in the previous update and was great.
But is it possible to put the code you introduced for this feature in the plugin code by default? Please Because in this case, we no longer need to re-insert the code in the template after each template update. Other users who do not know how to embed code can also use this feature. So if this code is available in the plugin it would be great. Please include this in the new update if possible

thank you very much🌹

add_filter( 'jet-woo-builder/shortcodes/jet-woo-products/not-found-message', function( $message ) {
	$message = str_replace( '&quot;', '"', $message );
	return do_shortcode( $message );
} );

**Comment by 79ho3ein** [comment]
Thank you very much🙏🏻

**Comment by Michaelgimii** [comment]
excellent. Is it possible to publish this in the new version? please🙏
