### ISSUE TITLE
[REQUEST] Use Repeater data with Dinamyc Charts and tables

### ISSUE THREAD

**Issue by gponga** [CrocoBlock/suggestions#4387]
Currently data can be collected via MetaFields, WP metas and other options via Query Builder. However, it is not possible to extract the data within a repeater to display it in a dynamic chart or a dynamic table.

It would be great to be able to use it to track checkpoints within a user profile, and have the client add it with a repeater.

Thanks a lot.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
