### ISSUE TITLE
Filter price range The price range is not coordinated with other filters / jet smart filters

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4388]
hello @Floydtm.
If we use several filters, such as a checkbox, as well as a **price range filter**, there is no coordination between the filters and the **price range filter**.

**But what does this lack of coordination mean?**
In the product archive, we have products between $ 15 and $ 200. Thus, the price range filter shows the $ 15-200 range. Now we filter the products using the checkbox filter. Now, the price of filtered products is between $ 30 and $ 100. **But the price range filter still shows the $ 15-200 range.** While it should show $ 30-100.

Please check this item. it's too important.

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
