### ISSUE TITLE
We need to be able to change the slug for JetEngine Custom Post Types without losing all its posts, taxonomies, filters, etc. 

### ISSUE THREAD

**Issue by stefan57** [Crocoblock/suggestions#439]
**If we change the Slug of a JetEngine Post Type we will lose all its posts, taxonomies, filters, etc.** 

As a work-around, I can get the slug changed if I use the Rewrite Slug field to change the slug. The URL will be changed, but it brings another issue: _The old slug will still show up in the search results URL._

My old Rewrite Slug field: all_templates
My new Rewrite Slug field: all_themes

This is how the search result URL looks now:
https://domain.com/?s=jetEngine&post_type=all_templates

This is how I expected the search result URL to look:
https://domain.com/?s=jetEngine&post_type=all_themes

**Losing all posts, taxes etc when changing the JetEngine Custom Post Types slug is really bad and should be fixed quickly.**

**Even I changed the slug in Rewrite slug field it still shows the old slug in search results URLs and that looks really bad, should also be fixed quickly.**

This is confirmed by Victoria Bormotova in your FB group, and she told me to post this issue here.

---

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

See above

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by andrei-nistor** [comment]
Has this been solved yet? Can we change the slug of our CPTs without losing any data? Crocoblock knowledge base doesn't explain much about how 'Rewrite slug' works. And I don't understand why the 'Slug' field is kept editable after the first use anyhow, since changing it messes the CPT posts?

**Comment by bergjs** [comment]
I think I ran into the same issue. I changed the post type slug and now my custom post pages cannot be found anymore. No idea how to fix this.

**Comment by Floydtm** [comment]
@bergjs, hi! Change the slug of your posts to the old slug. This should help. Or contact our [support](https://support.crocoblock.com)

**Comment by Floydtm** [comment]
In the version of the jet-engine 2.0.0 plugin, this option appeared http://prntscr.com/ql75l6, it solves the problem with rewriting the slug. You also need to check this option http://prntscr.com/ql76q2 which customizes permalinks. After all this, you need to update permalinks

**Comment by bergjs** [comment]
@Floydtm  it somehow fixed itself, not sure anymore what I did but thanks for the support!

**Comment by fafchook** [comment]
Issue still not fixed. having the same problem
