### ISSUE TITLE
Ability to redirect users who have not registered to the login / registration page (jet woobuilder)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4393]
hello
Most user panel plugins have the feature of redirecting users who have not registered to the registration page. Of course, this redirect happens when guest users enter the checkout page. This can be great.
Of course, WooCommerce has some settings in this area, but it lacks this. And it is not enough.

If possible, please add an option to WooCommerce Configuration> jet woobuilder tab, which will enable this feature (Redirect guest users to the login / registration page). 
By activating this option, users who are not logged in will not be able to view the Checkout page. Therefore, they will be redirected to the login / registration page. this is fabulous. Please check this item. is very important.

Thank you

**Comment by Michaelgimii** [comment]
+1
This is really great. Hope to be added to jet woobuilder.

**Comment by mehdimoradi1500** [comment]
Yes i have the same problem
Its necessary to redirect guest users to login/register template (login template: woocommerce configuration>jet woo builder tab) or page
 Important notice: After the users logged in or registered then they have to be redirected to checkout page
@UraraReika 

![IMG_20211123_181235_563](https://user-images.githubusercontent.com/86493591/143136840-10d50699-3e46-4c6c-a29b-073cbe257ae6.jpg)

**Comment by 79ho3ein** [comment]
> notice: After the users logged in or registered then they have to be redirected to checkout page @UraraReika

hi @mehdimoradi1500, This idea was great.

**Comment by UraraReika** [comment]
This functionality will not be added to our plugin. WooCommerce itself has some kind of this  and our product work with this default functionality and gives to it some customization. You can check it [here](https://tppr.me/xVi09). 

But you can use this solution:

```
add_action( 'template_redirect', '__your_theme_prefix_user_redirect' );

function __your_theme_prefix_user_redirect() {
    if ( ! is_user_logged_in() && is_checkout() ) {
        // feel free to customize the following line to suit your needs
        wp_redirect(wp_login_url());
        exit;
    }
}
```

Put this code into your theme `functions.php` and it will work. On the login or registration page you can use JetBlocks widgets in which you can use redirect options so users after can get back to checkout page.
