### ISSUE TITLE
JetWooBuilder : Single review form : How to display stars instead of form for evaluations/ratings ? 

### ISSUE THREAD

**Issue by dazdazslk** [CrocoBlock/suggestions#4395]
Hello Croco Community !

I submitted I ticket 15 days ago to ask for the possibility to customize the Single Review Form.
But in the meantime does anyone knows how to display "stars" instead of small form for evaluation ?
![image](https://user-images.githubusercontent.com/94035165/143212202-d27600a8-757d-4506-b493-089a8751dc00.png)

If someone knows any CSS or HTML to switch from "form style" to "stars style" thank you so much for your help !

Daz

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!
