### ISSUE TITLE
Bug in the new update of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4396]
hello
In the new update, the sale price is not displayed : https://prnt.sc/20ryvx1
Also on the shopping cart page, some styles have been changed to default : https://prnt.sc/20rzgk6
In the product grid widget, the sale price style is also lost : https://prnt.sc/20rzvot

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Sale price display as [should](https://i.gyazo.com/3306afaed977d94176c73de615b5990d.jpg).
Please specify in more details which style lost? The last update did not affect styling and price controls in any way.

On the cart page none of the styles were changed to default. But now in the editor  we add WooCommerce classes so the widget can look the same both in the editor and on the frontend.

**Comment by 79ho3ein** [comment]
thank you @UraraReika. that is weird. But on all my websites, after the update, the sale price is not displayed. I do not know exactly what the problem is. But I have to look for the problem more. I will inform you of the result.

Thank you

**Comment by UraraReika** [comment]
Please contact our support team next time. Thank you!
