### ISSUE TITLE
Jet product gallery: option to let customers add images and videos to product

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#4397]
Hi
It would be great if a feature could be added to the product page so that users who have purchased the product can add photos and videos of the product to the gallery.

This option causes more interaction of users with the site and products

Tip 1: Users must first registered or logged in to upload photos and videos, in addition only users who have purchased the product can upload files

Tip 2: the uploaded photos and videos, will be published or rejected after the approval of the site admin

Tip 3: the admin of the site be able to change the following options: File format (image or video), number and size of files to upload
@UraraReika

![IMG_20211124_163148_128](https://user-images.githubusercontent.com/86493591/143243330-8b8d67f8-a83e-4922-a9da-e988b017a2f6.jpg)

**Comment by Michaelgimii** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Such functionality will not be added to the JetProductGallery plugin. But it can be some kind done with the help of JetEngine. So you are welcome to try it.
