### ISSUE TITLE
Make a source listing (Shopping Cart)

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4398]
Hello

Could you make a record source (Basket) in the Listing Grid?

The fact is that on the checkout page I would also like to display those products that have already been added to the cart so that users understand and clearly see what they are buying !
![baсket](https://user-images.githubusercontent.com/47380983/143256177-fe8f2708-009d-4af3-aabc-2d056303343a.png)
![Checkout](https://user-images.githubusercontent.com/47380983/143256727-db82e94b-c8bf-41d2-a662-e2c6d05684ba.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
