### ISSUE TITLE
Problems with checkout field editor and jet woobuilder

### ISSUE THREAD

**Issue by jaimenurbina** [CrocoBlock/suggestions#4401]
I have created a field with the checkout fields editor that makes a surcharge in the total for packaging expenses, with the default woocommerce template it works perfect but in the template that I have designed with the jetwoobuilder the field data does not appear and does not add the value configured in the checkout fields editor, what could I do to make it work?

**Comment by UraraReika** [comment]
Please contact our support team or use this template for [bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
