### ISSUE TITLE
Bugs in the new version of the jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4402]
1- In the cart page, the color of the delete Custom icon does not change. Also, when hovering, its appearance deteriorates. https://prnt.sc/20sqj7h

2- On the single product page, the Add to Cart button has been moved to the other side. (RTL) https://prnt.sc/20sqkfh

3- The cart totals widget border is still heavier on tablets and mobiles. But great on the desktop.
On the desktop : https://prnt.sc/20sqm77         **without problem**
On mobile : https://prnt.sc/20sqn4u         **The mentioned parts (red arrow) are fatter than the green part.**

thank you

**Comment by 79ho3ein** [comment]
hello @UraraReika. thank you for your attention.
There is another item in the cart totals widget ... 
By default, the width of the cart totals table is not 100%. It is almost 70%. We must set the width to 100 to be the full width.
The problem is in the default width, which is not 100%. **Of course, this problem only exists in the size of tablet and mobile phones.**
Please check this item.

thank you🌹

**Comment by UraraReika** [comment]
Use responsive width control for table cells

**Comment by 79ho3ein** [comment]
Yes. I do the same. But it is not 100% by default. This problem occurred in the last two updates.

**Comment by 79ho3ein** [comment]
hello @UraraReika. Thank you very much for your efforts. Many improvements were made in the new version. But there are some very small bugs.
1- The product removal icon in the cart does not support global color. https://prnt.sc/20xdyll
2- In the cart totals widget, the left and right borders have been removed. **Of course only on tablets and mobiles**
https://prnt.sc/20xdydz 
**also cart table widget**

3- And the third case, in the responsive section, there are coupons in the shopping cart. If we "inline" the coupon section on the desktop, it will be the same on tablets and mobiles. In fact, this feature requires a responsive mode. For example, it should be "inline" on the desktop, but "block" on tablets and mobile phones. https://prnt.sc/20xe079

4- In the shopping cart table, if we put a title for the product image, that title will not be displayed on the tablet and mobile.https://prnt.sc/20xe3qu

5- There seems to be a problem with the width of these two marked sections : https://prnt.sc/20xe10l
I increase the width of the field (green box), but the width of the button also changes with the field.

Please let me know if I need to open a new issue for these items.

thank you
