### ISSUE TITLE
Improved ui in the shopping cart of the woobuilder jet plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4403]
hello
The ability to insert icons in the new update was excellent. But the ui is still weak on tablets and mobiles. 

Currently, there is a lot of empty space in the tablet and mobile shopping cart. Which has greatly destroyed the Ui. https://prnt.sc/20sqtuq
There is also an extra line on the tablet and mobile above the delete button, which is not interesting at all : https://prnt.sc/20squ7v

**proposed solution :**

Great if you move the delete button to the front of the product image. Therefore, the previous location of the delete button (green area) will be completely deleted : https://prnt.sc/20squw0

thank you

**Comment by UraraReika** [comment]
1 - Can be solved with image size and width controls. In future width control become responsive.
2 - We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
Thank you
