### ISSUE TITLE
Cleverly display the prices of variable products / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4409]
hello
In connection with yesterday's report that the sale price is hidden ...
If products are variable, the sale price will no longer be displayed. In this case, the price of the products is displayed as a range. For example, $10 -$120
Showing price by range is not really interesting. If this can be solved, it would be great.
I checked a few reputable sites, they did not show the price by range. Among the variables in a product, they display the product with the lowest price as the default. Therefore, they did not lose the sale price in displaying their products.

**proposed solution :**
If possible, please add an option to WooCommerce Configuration> jet woobuilder tab. This setting has 3 options. **Default** - **lowest price** - **highest price**

If we select the default option, the current situation continues and in variable products, prices are displayed as range. Also "sale price" is not displayed.If we select the default option, in variable products, prices are displayed in intervals. Also "Sale price" is not displayed. (This is how it is now)

**But what happens if we choose "lowest price"?**
By selecting this option and the "highest price" option, prices in variable products are no longer displayed as intervals. Instead, the variable with the lowest price is displayed as the default price. Therefore, the sale price will also be displayed. this is great.

**To better understand, I will illustrate this wonderful feature with an example :**

Suppose we have a product, with 3 different prices(Variable product). All 3 prices have a sale price.
![jet-woobuilder](https://user-images.githubusercontent.com/77163248/143443574-8ce4522e-2dcf-4e79-a326-11885af3f5cb.jpg)

If we select the default mode through the jet woobuilder settings (new feature), the price display status will be the same as now. As a result, product prices on the jet woobuilder (product grid) will be displayed as a range.

**But what happens if we choose the lowest price?** In the image above, the lowest price among the variables was $ 1100. Therefore, this price is displayed as the default price. Because we have chosen the lowest price.
![jet](https://user-images.githubusercontent.com/77163248/143445204-433fd6db-2dc7-4d77-b31a-9138abf9009a.jpg)

If we select "highest price" In this case, the $ 1400 variable will be selected by default. Because among the 3 variables, it is the highest price.:
![jet-2](https://user-images.githubusercontent.com/77163248/143445794-84338d2e-9d25-455d-8f50-bd3e1bfc2686.jpg)

This feature is very useful. Using this feature, users can display the price of variable products as desired. (As a range or selectively)

I apologize for the lengthy explanation. It needed a lot of explanation.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

In your previous report you mentioned that our last update hide sale price but it's not true. We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. And you can contact our support team. 

As for your feature request it will not be implemented due to its specificity. For this purpose we provide `jet-woo-builder/template-functions/product-price` hook so you can do whatever you want.

Thank you!

**Comment by 79ho3ein** [comment]
Hello @UraraReika.
In connection with the previous report, yes. There was no problem with the plugin. Of course it was solved.
Your work is always great.
