### ISSUE TITLE
[JetFormbuilder] Add support for Mollie payments

### ISSUE THREAD

**Issue by antoinelbch** [CrocoBlock/suggestions#4411]
Currently JetFormbuilder only supports Stripe. Please add support for payments through [Mollie](https://www.mollie.com/en), as this is a major payment provider, specially in Europe.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
