### ISSUE TITLE
How to work better with CCT

### ISSUE THREAD

**Issue by xypnotic** [CrocoBlock/suggestions#4414]
Hi to everyone, I want to thank you for this excellent plugin. 

Im trying to create a big directory listing website. 

My issue or question is:

I created a CCT with 53 different fields. I started with CPT but after reading a lot more about the best practices i discovered that if i keep doing CPT with so many fields then i will be affecting the speed of the data base and website in general. 

The only thing is that I want to relate CPT between them and use some taxonomies and using CCT i cant do that yet... 

I dont know if i have chosen the best option. My idea is to create more than 3,000 url using this CCT, so Im not sure if this is the best option or I should continue using CPT to make it easier for me while designing the single templates?

Greetings and thanks in advance.

**Comment by MjHead** [comment]
Hi! At the moment, if you need taxonomies and some custom URLs, is better to use CPT, because CCTs a bit limited in this case.
