### ISSUE TITLE
Separate delivery widget

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4416]
Please make a separate delivery widget.
Currently, delivery is displayed only through the widget (Checkout Order Review).
It would be great to display the delivery separately as shown in the photo

![4](https://user-images.githubusercontent.com/47380983/143577086-8a32ee09-a490-44fd-afaa-e86df9a6ae69.png)

**Comment by UraraReika** [comment]
Hello @GOHA81177 !

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. 

Thank you!
