### ISSUE TITLE
The pictures in the bookmarks do not change (JetCompareWishlist For)

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4417]
Created a bookmarks page!
In the listing grid, I created the output of posts and installed a bookmark widget there so that when you click on the widget, posts go to bookmarks!

In the JetWooBuilder plugin , the output of the selected listing has been set .

Everything works like clockwork ! but only I have the effect of replacing the picture, i.e. when hovering over the photo
https://elegatto.store/product-category/vse-braslety/
 (the main photo changes to the second photo), the whole problem is that this function does not work in bookmarks 
https://elegatto.store/zakladki/
(i.e. if you use a widget (Wish list) that displays bookmarks and hover over the picture, then the picture will not be replaced (

Can you fix this problem ?

**Comment by UraraReika** [comment]
I merged this issue with #4374, which is on the same subject so we could deal with it more efficiently.
