### ISSUE TITLE
Ability to redirect users, after logging in and registering In jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4423]
hi
The ability to redirect users after "Login and Register" as well as "Logout" is great. For example, I want users to be redirected directly to their user panel after logging in or registering. Or I may want them to be redirected to the main page of the site after logging in and registering.
**It is also excellent to be able to redirect after "Logout"**. After logging out, users will be redirected to the main page, or to the login and registration tab. This is completely optional.

**Comment by UraraReika** [comment]
You can use JetBlocks widgets inside your JetWooBuilder templates to achieve this results.
