### ISSUE TITLE
JetWooBuilder BUG

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#4425]
With the template switcher (Product loop widget), when i switch the layout, the jetproduct gallery widget does not work in the layout. The paginations cant switch the images. If i refresh the page, and not using the layout switcher, works until I use it again the switcher.

Latest epro
Latest jetwoo( 1.11.2)
Latest JetProductgallery(2.0.4)

**Comment by UraraReika** [comment]
We have checked your request with latest plugins versions and everything seems to be working correctly. If you still face this problem then perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by Lonsdale201** [comment]
> We have checked your request with latest plugins versions and everything seems to be working correctly. If you still face this problem then perhaps this is related to your site. Please contact our support team. Thank you!

Yes, because you have since fixed it. :)
