### ISSUE TITLE
Ability to change the text in a single meta widget / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4426]
hello
Please add the ability to rename the title to this widget if possible. https://prnt.sc/20xqq38
This is a simple but practical feature. For example, in our language, this part is not translated correctly. So for now, we can not change the text. If you add this feature, this problem will be solved. Of course, this feature can be used in all languages. This feature increases the possibility of customization.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Unfortunately this is not possible in this situation.  In our widgets we try to keep default WooCommerce structure for better compatibility. But you can achieve this by rewriting WooCommerce template and change the text manually. You need to find this file `wp-content/plugins/woocommerce/templates/single-product/meta.php` and using instructions in the header of this file or use official [documentation](https://woocommerce.com/document/template-structure/) to rewrite it in your child theme.
