### ISSUE TITLE
Change icons in checkout fields in jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4429]
The payment field icon is very ugly. Great if you can add custom icons to the payment fields.
In fact, we need icons before and after the list opens.

before opening (Icon down)
![Screenshot (247)](https://user-images.githubusercontent.com/88034902/143772472-20fffb17-aa3e-49dc-91e0-5077c44afb74.png)

The icon changes after the list opens. (Icon up)
![Screenshot (248)](https://user-images.githubusercontent.com/88034902/143772537-f978cdd2-39cd-4aba-87a9-740e5dd5c918.png)

This is really great

**Comment by UraraReika** [comment]
I merged this issue with #3793, which is on the same subject so we could deal with it more efficiently.
