### ISSUE TITLE
Flux Store Intergration 

### ISSUE THREAD

**Issue by davidwatkins2** [CrocoBlock/suggestions#4431]
Integration with  Flux Store since Croco Block doesn't offer native app services. 
https://fluxstore.app

This will allow users to turn their Crocoblock build websites into iPhone/Android Apps

**Comment by johnfc2021** [comment]
Crocoblock is not a stand alone product, it is a set of plugins for WordPress, if fluxstore want to add native app services, then they need submit their plugin to the WordPress repository. 

There are native app plugins in the WordPress repository along with PWA plugins, so if anyone wants to make their site into an app, they can just install a suitable plugin.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
