### ISSUE TITLE
Add additional Item or Price System for Single booking Form & Single Product Page

### ISSUE THREAD

**Issue by SjPavel** [CrocoBlock/suggestions#4432]
Hi,
User can add additional item like extra item and will be show the extra price for extra item. See the screenshot - ![download](https://user-images.githubusercontent.com/39057848/143824543-9aeb76dc-edb9-4ccf-ac20-0627f3dfafd6.png)And this option will be in booking form or system and single product page.
Is it possible by crocoblock? Can you add this feature? 

Thank you.

**Comment by Floydtm** [comment]
You can do this with forms right [now](https://demo.crocoblock.com/travengo-new/tour/wonderful-usa/#)
