### ISSUE TITLE
JetAppointment - Move appointments to CCT and CPT

### ISSUE THREAD

**Issue by johnfc2021** [CrocoBlock/suggestions#4433]
Hi,

Currently all the appointments are stored in their own table in the WordPress database, but moving the appointments to it's own custom post and content type, like you would for the providers and services would make the data more dynamic. The ability to have a repeater for blocking days on a range would be useful as well as a repeater, because if we don't work Christmas day, we don't want to have to add Christmas day for every year we will be working, as the current days off only apply to that calendar year. 

This means that you can use the REST API to access the appointments, and sync them with Google Calendar via a 3rd party automation tool and even have them go into your CRM or online accounting system.

**Comment by paeschr007** [comment]
Yes, this is a good idea.

**Comment by Zszywaczyk** [comment]
+1

**Comment by davidwatkins2** [comment]
Yes +1

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by jbaudracco** [comment]
+1
