### ISSUE TITLE
JetSearch количество товара в расширенной вкладке

### ISSUE THREAD

**Issue by pasha-ags** [CrocoBlock/suggestions#4434]
Здравствуйте. Сделайте пожалуйста возможность отображения количества товара во вкладке
[https://yadi.sk/d/MWs-3aiYDCId-w](url)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
