### ISSUE TITLE
Filters Disappear if Customer Selects Options too Quickly

### ISSUE THREAD

**Issue by elliotaccount** [CrocoBlock/suggestions#4435]
Hi there,

I am using your JetSmart Filter plugin. However, I would like to request a feature add on. First I will explain the issue:

When on one of my pages: https://www.gutterwarehouse.co.uk/corrugated-roofing    , if you select the filter options which don't have products in them too quickly, all of the options disappear. The only way to get them back is to refresh the page.  You can see an example of this issue [here](https://streamable.com/ki5x4d).

It would be great if there was a way to prevent the other filters from being selected too quickly. So once you've chosen an option on the first filter, there is a slight pause to allow the indexing, and then allow further filtering?

Kind regards,

Elliot

**Comment by elliotaccount** [comment]
You can see an example of the issue on [this link here](https://streamable.com/ki5x4d)

**Comment by elliotaccount** [comment]
Anyone update?

**Comment by Floydtm** [comment]
This is not a bug. You can adjust the filters differently or use the reset button. Thank you!

**Comment by elliotaccount** [comment]
Sorry Floyd that doesn't solve it actually. You can;t readjust the filters
differently because they all disappear if they are selected too quickly and
there are no products matching that selection. The only way to reselect is
to refresh the page which isn't great user experience.
