### ISSUE TITLE
JetBlog: Query multiply post types not possible

### ISSUE THREAD

**Issue by tommy83** [CrocoBlock/suggestions#4436]
Having an query for multiply post type is an very basic need.
So i was very surprised that this function is still missing in paid solution JetBlog. Because most of all free elementor addons can do that. The paid JetBlog solution cant do that?

So i try to give them a second try and open the dedicated Query Generator: https://crocoblock.com/freemium/tools/wp-query-generator/

In the first moment you can enter diffrent post type names, thats looks like an solution:

![Uploading Screenshot 2021-11-30 at 10-04-18 WP Query Generator - create custom WordPress queries.png…]()

But its not. Yes, this field allow multiply values, but it will not work for JetBlog. Thats very frustrating situation. Query multiply posttypes is very basic and i hope you plan to add that basic option into JetBlog functions.

**Comment by Crocoblock** [comment]
was added in JetBlog 2.3.8
