### ISSUE TITLE
Specific filters depending on the Checkboxes Filter category

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4437]
I use the Checkboxes Filter widget in photo 1 it can be seen that I display product categories.
Question:
Can you implement the functionality to output a certain filter depending on the category ?

For example... I select a group of categories and when clicking on this group, some filters are displayed.... I select another group of filters and other filters are displayed.

Is it possible to do this ?

![fil](https://user-images.githubusercontent.com/47380983/144062428-e201cdab-8fc7-4010-9a2a-e250f215a6b7.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
