### ISSUE TITLE
Display the coupon widget on the Checkout Template page

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4438]
You need to display the coupon on the Checkout Template page, but it does not work there... this widget only works on the Checkout Top Template page.

Please make the Coupon widget also work in the Checkout Template

**Comment by 79ho3ein** [comment]
+1
This is really needed. In fact, the current situation limits the design.

**Comment by UraraReika** [comment]
In the official W3C specification the section on the [FORMS](https://www.w3.org/MarkUp/html3/forms.html) element states that:

> Every form must be enclosed within a FORM element. There can be several forms in a single document, but the FORM element can't be nested.

There are workarounds using JavaScript without needing to nest form tags. But we use as much as we can standard WooCommerce functionality to avoid compatibility issues.
