### ISSUE TITLE
Show the title of a Active Filter on the top of the Listing Grid

### ISSUE THREAD

**Issue by bombarda-rpd** [CrocoBlock/suggestions#4439]
When a filter option is selected, I think it will be interesent to see a title above the filtered listingrid.

Filters:
Monday, Tuesday, etc
Selected Monday....

Filting Grid Title:
Events on Monday.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
