### ISSUE TITLE
Adding Open StreetMap for Map Listings

### ISSUE THREAD

**Issue by torsten3d** [CrocoBlock/suggestions#4440]
Would be nice to have also Open StreetMap as Source for Map Listings.
No Deal with ApiKeys and also better for DSGVO concerns.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
