### ISSUE TITLE
Calendar widget should output range of months

### ISSUE THREAD

**Issue by wsnine** [CrocoBlock/suggestions#4445]
Currently if you use the calendar widget and perform a search you can only display one month.  I'm looking to display search results across a 3 -4  month range on "mini calendars".  Clicking each date box would link to a details page pertaining to that day. I think this can be useful for many purposes including booking calendars where you can quickly see what months are booked up.  I'm currently attempting to dynamically show stock market green and red days across several months and can't find a way to achieve that in Jetengine. 

An example image is below.

![multiple -calendars](https://user-images.githubusercontent.com/43257254/144304138-b998ada1-5e64-44b5-b6ae-08752e5b397c.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
