### ISSUE TITLE
листинг ссылка

### ISSUE THREAD

**Issue by loki99928** [Crocoblock/suggestions#445]
Add the ability to make the entire listing a link to the record, now to open the record you need to click on a specific element of the listing, it is not very convenient

**Comment by Floydtm** [comment]
@loki99928, Hi! Please, note, that the feature requests can be accepted and processed only if they’re written in English. 
Please edit your request.

**Comment by Olegggggggg** [comment]
+1 Add the ability to make the entire listing a link to the record, now to open the record you need to click on a specific element of the listing, it is not very convenient
