### ISSUE TITLE
jet woobuilder Select a template.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4450]
hello
Unfortunately, for now, if we publish a product, we must specify the format of the individual product as well as the width of the individual page : https://prnt.sc/21dtrbv
Therefore, we have to do this for each product. This does not really make sense. I dare say this is the only and biggest weakness of jet woobuilder.
Great if you can fix this problem forever. This is needed more than any other feature. To solve this problem, I have a suggestion, I hope it will be useful.

I think it's better to add a section like this (https://prnt.sc/21due1u) to WooCommerce Configuration> jet woobuilder tab. 
Using this section, we can select the template as well as the default width for all products. Therefore, we no longer need to do this every time we insert a product.
If for any reason we want to change the format of a product, as before, we go to the product insertion section and change the format of that product. This is really great. **Please fix this problem**

thank you

**Comment by mehdimoradi1500** [comment]
yes I have the same problem, its so annoying!! every time for each product i have to choose a template!
fix this problem, dear @UraraReika

**Comment by mehdimoradi1500** [comment]
Hi @UraraReika will u please fix this issue? I have to upload 20 products each day and its difficult to select the single template for each product
🌷

**Comment by UraraReika** [comment]
This issue in progress and will be available in a few updates.

**Comment by mehdimoradi1500** [comment]
Thank you 😍

**Comment by petrovui** [comment]
Can it be solved with temporary changes in child theme?

**Comment by UraraReika** [comment]
This issue already solved, release will be soon.

**Comment by Michaelgimii** [comment]
Great, thank you very much @UraraReika . When will the update be released?

**Comment by Michaelgimii** [comment]
hi @UraraReika , How can this feature be used in the new version? It works for me like before

**Comment by UraraReika** [comment]
> hi @UraraReika , How can this feature be used in the new version? It works for me like before

When you edit single product template made with JetWooBuilder you can notice this new settings https://tppr.me/mpqcd.

**Comment by 79ho3ein** [comment]
Thanks for this great feature @UraraReika
