### ISSUE TITLE
Query builder refresh

### ISSUE THREAD

**Issue by Tibi5** [CrocoBlock/suggestions#4455]
Hello!

I have made a custom query with the query builder. The query sorts and filters CPTs. I have used it in a listing and everything works fine until I delete all the posts and create others. When I do that, the listing still keeps the deleted posts even though when I click them to access the single page, they don't exist and the new ones don't appear.

That's it. Thanks!

**Comment by Floydtm** [comment]
Please check this option https://prnt.sc/25zh1qs If you have any problems with this, please contact our support team. Thank you!
