### ISSUE TITLE
Jet Appointment - Reminder e-mail notification

### ISSUE THREAD

**Issue by jb2021Github** [CrocoBlock/suggestions#4457]
It would be fantastic if a reminder e-mail notification could be automatically sent to the customer 24 hours (and possibly also 2 hours) before the appointment begins. Could  you **please** implement this in Jet Appointment?

**Comment by nicedood** [comment]
+1

**Comment by molnarbalazs950817** [comment]
+1

**Comment by MjHead** [comment]
Could be implemented with Workflows functionality

**Comment by rinibak** [comment]
Yes, please do create this functionality, it would be great, and better than having to pay for an sms reminder service number with Twilio!

**Comment by shohanmiah** [comment]
Its very important for me to set reminder notification before 30 minute of appointment time
