### ISSUE TITLE
Multiple CPTs into one archive page

### ISSUE THREAD

**Issue by cosetos** [CrocoBlock/suggestions#4458]
Hi there;

Is it possible to merge multiple CPTs into one archive? Specifically, I have 3 CPTs (Internships, Services, Participants) and I would like to merge those 3 under one archive page (named Student Department) so that every my slug structure would be 

www.mysite.com/student-department/internships
www.mysite.com/student-department/services
www.mysite.com/student-department/participants

and that all CPTs would direct to one archive page ("Student Department").

Is this possible via JetEngine CPTs or through relations? Is there a way to go about this?
If not, it would be great to have it as feature in later updates. 

Many thanks,
C.

**Comment by Floydtm** [comment]
I understand that this is very important to you. However, this is not possible at the moment. Thank you!
