### ISSUE TITLE
Gallery slider image settings.

### ISSUE THREAD

**Issue by tekonemedia** [CrocoBlock/suggestions#4460]
Would be great to have image width, height, and object fit & position adjustment setting for the gallery slider widget. Also would be nice to set vh height for vertical layout and % width for horizontal on the thumbnail section, and align align options as well so you could match it to the main image size. Also main image sticky within widget would be great for really large gallery's. Would be nice to have something like this https://www.mccleandesign.com/en/projects

We found ourselves tinkering with this widget for hours trying to customize it and use custom css but to no prevail. In the end we just straight up couldn't get it to fit our layout.

**Comment by UraraReika** [comment]
Hello @tekonemedia. Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. This plugins and widgets was developed for another kind of usage. You can take a look at another slider which can fill your needs https://crocoblock.com/widgets/slider/.

Thank you for your understanding.
