### ISSUE TITLE
Ability to set AND and OR together in Dynamic Visibility [JetEngine]

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4462]
Hello,

Currently, we can only choose either AND or OR as the Relation for the Dynamic Visibility:
https://ibb.co/pZGbZd3

But it happens a lot (actually very often) that we need to set both conditions (for example, let's say I want to display a notice IF user's country is Canada AND the product is in x category, OR, the user's country is Canada AND the product is in y category, OR... => you got the point!)

Adding a feature to let us add a new set of conditions with specific condition relations would solve this issue. Like:
https://ibb.co/T1dNQYm

Once clicked, it will let us make a condition like this:
https://ibb.co/qCjV62f

Without this feature, currently, we have to duplicate the elements for every OR, and in cases in which there are many elements/widgets in 4 different scenarios/ORs, we end up having hundreds of duplicated widgets just to set a few conditions (this not only affects the performance but also makes it hard, if not almost impossible, to easily maintain the design)

I hope to get this critical feature soon.

Thanks

**Comment by MjHead** [comment]
Unfortunately at the moment this in not possible due to UI limitations. For your case the best way will be to register custom condition and check all required data inside this condition. Here is example how to register custom condition - https://github.com/MjHead/jet-engine-custom-visibility-conditions/

**Comment by kochhase** [comment]
Hi Andrew, you said:
For your case the best way will be to register custom condition and check all required data inside this condition. Here is example how to register custom condition. But there is no example how to do some conditions with AND or OR. This https://crocoblock.com/knowledge-base/articles/jetengine-devtools-custom-visibility-conditions-add-on/ will not help us as well. Is there something ready at Jetengine 3.0?
