### ISSUE TITLE
More User Fields options for Dynamic Visibility [JetEngine]

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4463]
Hello,

When setting the Dynamic Visibility for widgets, after choosing "User Meta is" for the condition, we have a limited number of options for the "Field":
https://ibb.co/sQD999H

This limited dropdown doesn't let us do pretty much anything complex. (for example, if we decide to show/hide a notice based on the user's shipping or billing country, city, or any other metadata that is not already in the limited number of fields in that dropdown, we can't do it)

Please complete that list, and especially add a "Custom" option to the list to let us enter/search "any" meta field.

Currently, we are using a custom plugin for that:
https://ibb.co/j40fWp7
https://ibb.co/J3M7hKH

But I don't want to keep adding new plugins for every single lack of feature (for 2 reasons: 1. those plugins come with many other features that we don't need but it adds to the site's load time 2. the project I'm working on is very large and highly customized store with already many plugins and the more we keep adding plugins the harder it gets to keep it fast)

Thanks

**Comment by MjHead** [comment]
Hi! If I understand you correctly, you can do this by installing **Custom visibility conditions** module and using **User meta is** condition from this module:
![image](https://user-images.githubusercontent.com/4987981/145602719-75b1fa42-d45f-4863-9d6d-7008a1d30d56.png)
![image](https://user-images.githubusercontent.com/4987981/145602787-27944c70-b7fb-4c55-8de5-27fdd829e8c8.png)
