### ISSUE TITLE
Bar Chart (JetElements) widget should allow legend to be left-justified

### ISSUE THREAD

**Issue by lcgitrdone** [CrocoBlock/suggestions#4465]
Hi,

Unless I am missing something, the Bar Chart widget's legend is always centered.  Centering on the Web is often not a best practice, and it's definitely not a best practice for a legend sitting on top of a left-justified horizontal bar chart.  It's acceptable if it has to be on desktop, but it's absolutely horrible on mobile.  Pics of both attached.  

IMO, there should be a justification control added to widget for legend positioning.  

Thank you!

![desktop bar chart legend centered](https://user-images.githubusercontent.com/25237949/144720791-817d11d4-d68e-47b0-bae8-95d9cdb48a5e.jpg)

![mobile bar chart legend centered](https://user-images.githubusercontent.com/25237949/144720792-46bc2946-c203-44d3-a143-a5ffccf4b4b4.jpg)

**Comment by Gawuww** [comment]
Added in JetElements 2.6.2

**Comment by lcgitrdone** [comment]
Works great -- thank you!
