### ISSUE TITLE
Allow product image to be available at all times in table view

### ISSUE THREAD

**Issue by desupero** [CrocoBlock/suggestions#4467]
**Please, describe the feature request, making it clear to understand.**

At this link here, on my pc the columns have to be scrolled using a scroll bar at the bottom of the items. So, the image and item description go out of view! The item column should remain in view at all times to enable the view to match the info across the screen with the relevant image.

https://demo.crocoblock.com/jetengine-addons/tables-and-charts-demo/

This feature is not currently implemented

The image column should remain fixed and the remainder of the columns horizontally scrollable 

![image](https://user-images.githubusercontent.com/6705332/144752938-6e89c95a-2e7e-487b-a5a8-aeae659c2498.png)

![image](https://user-images.githubusercontent.com/6705332/144752950-a685b1f6-6f67-4c3c-b788-934d492dbd6f.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
