### ISSUE TITLE
Jet Booking Partial payment option

### ISSUE THREAD

**Issue by FrankSchoen** [CrocoBlock/suggestions#4468]
Most hotels allow customers to do a partial payment of a booked room, the remainder of the total cost is payed at the end of the stay while checking out. Would it be possible to implement this in Jet Booking?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
