### ISSUE TITLE
jet woobuilder "bestsellers" query

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4473]
hello dear @UraraReika.
In the new version of the plugin, you have added the **bestsellers** product query. But this query does not seem to work at all. Because in the status section of WooCommerce (https://prnt.sc/224r8s2), it shows the product as a bestseller that is completely correct and has been sold many times.
But when I use jet woobuilder query, it shows products that did not sell at all. 

**Actually :**  https://prnt.sc/224qpet = https://prnt.sc/224qume

Whether the query is empty or on bestsellers, it displays a product.

Please check this if possible. This query is very practical and customers want it from us a lot.

thank you

**Comment by UraraReika** [comment]
This query was added to display only product that has been selled. And in this case we use `total_sales` product meta and compare if it more than 0. Try to clean up your Products Sale Report section and [Products meta](https://tppr.me/SDk3d) for `total_sales`. Then everything should synchronize and show you correct results.
