### ISSUE TITLE
Adding a static image to a form

### ISSUE THREAD

**Issue by Avram-Baskin** [CrocoBlock/suggestions#4478]
It would be useful to be able to include a static image on a form.  Users have not been able to understand the purpose of a particular form field.  It would be helpful to users to include a static image to show users where on the front end of the website the information in the field will be displayed.

**Comment by MjHead** [comment]
Hi! You can use JetFormBuilder for this purpose - https://wordpress.org/plugins/jetformbuilder/ Actually JetFormBuilder is a replacement for JetEngine forms - its actively developed, JetEngine forms are only maintained at the moment

**Comment by Avram-Baskin** [comment]
Sorry to bother you again.  Will JetForm Builder update the forms I created in JetEngine forms?  Or will I have to recreate them?

**Comment by kochhase** [comment]
Yes you have to create all new. Import is not working. And you have to enable the Gutenberg editor. But I don´t want to use them for my clients. So Mjhead how to do? Maybe you can do it like other plugins. only to active the  Gutenberg editor for you plugin, not for all plugins
