### ISSUE TITLE
Adding grandparent - grandchild relation between related CPTs in JetEngine

### ISSUE THREAD

**Issue by strale73** [Crocoblock/suggestions#448]
Hello,
it will be a cool and helpful feature to add grandparent-grandchild relation between related CPTs in JetEngine. I know the feature to show related posts between parent and child CPT already existed in JetEngine but this feature can be expanded with grandparent-grandchild relation.

Currently, I am working on a project building tourists attraction directory for a client and I am using Elementor Pro and Toolset for development. But, it is very hard and painful to achieve some of the features with Toolset, lots of hardcoding with PHP and CSS. And, this is NOT what Elementor developers and clients like to see (clients don't want to be limited hiring PHP developer again - too expensive).

I made 5 CPTs (Continent, Country, Region, Destination, Attraction), and there are in relationships one-to-many (one continent have many countries but one country is on only one continent, etc.). I made 5 different templates for any of the CPT (with Elementor) when it comes to displaying related child post on parent posts - it is ok and easy. BUT, if you like to display, for instance, Attractions on Regions page, this is so complicated and annoying. 

Example: When I choose France (destination) I want to display only Attractions (Eifel Tower, Arc the Triomphe, etc) who is related to France (don't want to display Northern France (or any other Region) or Paris (or any other Destination).

Toolset using Views to display the related post, in this case, they using Views inside the Views (in the first View they listed related post from Country-Region relationship, then, in the second View listed Region-Destination relationship and put inside the first one, and in the end, in the 3rd View listed Destination-Attraction posts relationship, put it in the 2nd View). Very hard, frustrated and time-consuming operations.

Adding to this, Toolset is moving away from Elementor, and Elementor advanced users need another capable and simple-to-work plugin to work with. JetEngine is the right fit for this, you can attract many disappointed Elementor developers to buy and use JetEngine and other CrocoBlock plugins. This is just the right opportunity.

I hope this is not so complicated to achieve.

Thanks,
Strahinja

**Comment by MjHead** [comment]
Thanks for your suggestion! Just to make sure I understand you correctly - you want make related all this chain, for example also show related attractions for Country and Continent?

**Comment by strale73** [comment]
Yes, that's correct. It will be cool if you can expand the drop-down option in JetEngine where you choose parent or child custom post types.
Screenshot: https://prnt.sc/ou6emt

In this example there are 5 levels, the first is Continent and the last is Attraction. In some cases, you can display related Attraction (level 5) on a Continent (level 1) or Level 5 on Level 2 ... etc. All combinations applied, it will be great flexibility for the users.

Thanks
