### ISSUE TITLE
Jet style manager as a builder

### ISSUE THREAD

**Issue by moragon87** [CrocoBlock/suggestions#4480]
I have been proving cwicly, is a builder for Gutenberg and it is awesome.

I think that jet style manager could be a builder too if you add some widgets (heading, text, image, etc) and a theme builder for Gutenberg.

It is an idea for create your own builder based in Gutenberg.

Regards

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
