### ISSUE TITLE
Manageable availability - not depending on bookings

### ISSUE THREAD

**Issue by Queen-Eef** [CrocoBlock/suggestions#4484]
I think it would be great for CrocoBlock if there was an easier way to manage the availability of the product/service.
For example, 
We are creating a website for a car rental and he has a lot of cars (!!) but he doesn't want them all specifically on his website. He has 6 categories, so 6 cars are available on his website. It should be possible to book every car (category) multiple times in the same period.
If he has more bookings of 1 category in the same period than he has cars, he offers the customer an upgrade. So he will manage the bookings himself and not his booking system. 
I fixed this now by adding al lot of units to each car, and I will delete all bookings regularly to prevent a car not being available. But this is not really handy (or professional). 
I also thought of the solution not to use the Booking plugin, so 1 car would still be available after a booking. That could be a solution to this issue.
But I can't do this because of my next 'thingy' with the availability options;

This rental company also has another website (more expensive) to rent his cars from. And in the period of Christmas, a really fully booked period, he wants all of his cars to be booked by the more expensive website. So the cars on this website should never be available in the Christmas period.
To manage this, I have to book them all for that period in advance, for the upcoming years. But I just added extra units to make sure they are always available (the first issue), so this is a very time consuming task.

So it would be great if the availability was manageable from the backend. For example, this product/service stays available in the same period after a booking. And this product/service is this-year-not/never available in this period.

Hope it's clear what I'm trying to say...
Curious about your thoughts!

**Comment by UraraReika** [comment]
Hello @Queen-Eef, thanks for the feedback.

About blocking bookings for some period of time, in 2.5.0 release of the plugin disabled days and weekend days functionality was added. So you can manage this option globaly and for each separate booking item.

> I fixed this now by adding al lot of units to each car, and I will delete all bookings regularly to prevent a car not being available. But this is not really handy (or professional).

I dont really understand why are you doing this because in your case cars availability depends on units count and selected date range. So please descrube this moment in more detais.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. If you still need help with this issue or have any other questions about our product, please start a new thread.
