### ISSUE TITLE
Two-color mode for jet smart filters plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4485]
hello
Currently, we can only introduce one color in visual filters. It would be great if you could add a feature so that we could also introduce a mixed color in the visual filter. Like this picture : https://prnt.sc/22cfjk6
Because sometimes, products have two colors. With this feature added, this restriction will no longer exist. Therefore, we can apply single and two-color colors in the visual filter.

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
