### ISSUE TITLE
Dynamic Tag for Background Slider

### ISSUE THREAD

**Issue by JurIvk** [CrocoBlock/suggestions#4493]
The idea is to create the possibility to add a dynamic tag to Elementor's background slider or build a better version than Elementor's existing one. Currently there is the option to choose between different images, but it would be even better if you could load in featured images from custom post types or from normal posts as background images of the section. 
Bain&Company consulting firm has this feature on their website.

[Link:] https://www.bain.com/de/# (https://www.bain.com/de/#)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
