### ISSUE TITLE
JetForms: Saving User Submissions into Database

### ISSUE THREAD

**Issue by rindoshingen** [CrocoBlock/suggestions#4495]
Hey folks,

I have been playing around with your Jetforms plugin and love it thus far. However, the one feature that I feel is lacking is the **'saved submissions'** option. 

It would be nice to have a place where the admin could look at all the submissions via the dashboard. This way they have a central location for those submissions, but also a backup of them [so not just an email].

Many thanks for your great efforts! =)

**Comment by Lonsdale201** [comment]
You can do this. Jetengine custom content type function. :)

**Comment by rindoshingen** [comment]
> You can do this. Jetengine custom content type function. :)

Thanks, let me have a look and see. =)

**Comment by MjHead** [comment]
Can be done with CCT in combination with forms

**Comment by rindoshingen** [comment]
> 

Perfect, thank you. =)
