### ISSUE TITLE
JetEngine Forms Add hCaptcha compatibility to comply with GDPR

### ISSUE THREAD

**Issue by IFTTD** [CrocoBlock/suggestions#4497]
Add ability to use hCAPTCHA such as in this plugin https://wordpress.org/plugins/hcaptcha-for-forms-and-more/
or simply add Honeypot ability

**Comment by mbhzpi** [comment]
I also need a feature to integrate hCaptcha in a JetEngine Form!

**Comment by girafffee** [comment]
Merge with https://github.com/Crocoblock/suggestions/issues/2792
