### ISSUE TITLE
Не корректно отображаются кастомные иконки в виджете Cart Table

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4505]
Загрузил иконку в виджет Cart Table и он совсем не так отображается рисунок 1 и загрузил туже самую иконку но только через виджет иконки (рисунок 2) еще попробовал через виджет крокоблока Button и там тоже все отлично !

Я так понимаю проблема именно в виджете Cart Table ... что сделать чтобы иконка нормально отображалась ?
![1](https://user-images.githubusercontent.com/47380983/145712375-ce8985c3-46bf-4214-84c4-fd0631fd07b0.jpg)
![2](https://user-images.githubusercontent.com/47380983/145712380-6ea46df1-c0b7-4fd1-88ae-31ac5dcdb8ec.jpg)
![3](https://user-images.githubusercontent.com/47380983/145712384-e8bead36-1d32-4c03-846e-20ec31692821.jpg)

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!
