### ISSUE TITLE
The "View All" section in the product grid widget / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4506]
hello

It would be great if you add a "View All" section to the product grid widget. This feature greatly improves UX.

**Feature description**
If we enable this feature in the product grid widget, a new section will be added to the end of the carousel. When the user reaches the end of the carousel, she will see the "View All" section and can be redirected to the carousel archive.
Please see this image : https://prnt.sc/22rt76l

As you can see in the image above, we were at the end of the carousel. At the end of the carousel was the "View All" box. 
Activation of this section can be completely optional. Customizations that this section needs :

1- Ability to insert custom icons : https://prnt.sc/22rtab0
2- Custom text ( view all) And related customizations : https://prnt.sc/22rtara
3- background color for view all box : background color : https://prnt.sc/22rtbos
4- Spacing between text and icon (Margin) 

Two important points about this feature :

1- This section is completely clickable. (Custom link) https://prnt.sc/22rt91y
2- The link is custom. At Carousel, for example, we display laptop category products. Therefore, we apply the laptop category link.

Video of this feature :

https://user-images.githubusercontent.com/77163248/145732384-e1c8dd84-b2c5-43c6-b8a8-4971788178be.mp4

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein. Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But we've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.
