### ISSUE TITLE
JetSmartFilters - filter bar with links, no radio, no checkboxes etc.

### ISSUE THREAD

**Issue by luxpatrick** [Crocoblock/suggestions#451]
I'm posting this again as the original thread was closed with a non working solution: 
Add the possibility to add a filter bar with only links, no radios, no checkboxes, just the simplest way it could be. Not everybody is using it for Woocommerce.
Setting the icon size to zero results in a point in my case. And the labels don't seem to be links . So nothing to click to filter any more.

Elements portfolio widget has this ability.

**Comment by Floydtm** [comment]
@luxpatrick, in fact, your case can be completed using the widget’s stylistic settings. http://prntscr.com/ov3y93 http://prntscr.com/ov3znc We will try to add the options you request in the following plugin updates. Thanks you!

**Comment by Floydtm** [comment]
I merged this issue with #428, which is on the same subject so we could deal with it more efficiently.
