### ISSUE TITLE
JetWooBuilder takes 2 seconds to render a page

### ISSUE THREAD

**Issue by diogui** [CrocoBlock/suggestions#4511]
**Describe the bug**
Whenever you request a page that it's content is rendered by JetWooBuilder it takes around 2 seconds to be generated. An Archive Page or a Single page, it takes too long to be generated. It doesn't matter how much cache do you use because this pages in the headers request to no-cache, so the pages are not cached and it takes a ages and of course a very painful result on google speed metrics (around 13 on mobile.) . I thought the problem was mine but when you go to the crocoblock product grid jetwoobuilder demo page the long server initial response time is there also https://demo.crocoblock.com/zolden/shop/ .

This is a huge problem as navigating through the page on mobile (using 4G, which is 80% of actual traffic this days) is very slow.

**To Reproduce**
1. Go to ['crocoblock demo page'](https://demo.crocoblock.com/zolden/shop/)
2. Click on 'open network tab and select HTML and see the server initial response time'
3. 2713 ms to load an archive page, 3585 ms to load a single product page (almost 4 seconds !!)

**Expected behavior**
One would say that the page generated should be faster but if not, crocoblock should cache this queries, when selected, so this pages would be served static. Whenever the customer adds a new product, the cache would be purged and new static pages generated

**Screenshots**
- 2 screenshot. One of archive page and another one for single product page

**Desktop (please complete the following information):**
 - Firefox

**Smartphone (please complete the following information):**
 - Safari

**Additional context**
<img width="1702" alt="Screenshot 2021-12-13 at 14 40 57" src="https://user-images.githubusercontent.com/875776/145832328-17ade567-9317-4fc2-966c-9ce90fe58b51.png">
<img width="1716" alt="Screenshot 2021-12-13 at 14 41 49" src="https://user-images.githubusercontent.com/875776/145832412-5d419a4b-ecdf-4b83-be38-e6b0e5f65449.png">

**Comment by UraraReika** [comment]
I merged this issue with [#2282](https://github.com/Crocoblock/suggestions/issues/2282), which is on the same subject so we could deal with it more efficiently.
