### ISSUE TITLE
Image URL Suffix for Dynamic Image widget [JetEngine]

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4515]
This feature can save hours and hours of maintenance and development, and also is a huge performance boost in the end.

One of the options for the "Dynamic Image" widget in JetEngine, is the "Image URL Prefix":
https://ibb.co/f1pMJkw

This is very useful. But it would be amazing if we also had another option below it as "Image URL Suffix". Like this:
https://ibb.co/dQPcnfH

This helps us have much more dynamic and optimized pages. Let me explain a real example to make things clear:

We have a Glossary in JetEngine that contains 242 countries, each country has the country code as their Key/Value to both follow the Woocommerce's country database's standard and also make further development easier. As you know, in Glossay we can only have simple options that later will be used in Checkbox field type. We can't have complex structures like Repeater and ... within a Glossary itself (and we use that in a Custom Post Type to create a shipping restriction). 

In product page, based on the user's shipping country, we show a notification. We are totally fine creating dynamic sections and showing the user's country name and even state name, and the notice's main message, but it gets impossible when we want to show the country flag. As the Icon or Image widgets are so limited, there is no way using them to dynamically pull the country flag based on the user's country or notice's related country. (so, we have to define 242 different notices, with different flags, and CONDITIONALLY show them)

But, what if the Dynamic Image widget would have "Image URL Suffix" as well? In that case, we could use that widget, set the Country Checkbox's Key as "Custom meta field/repeater key", set the location where 242 flags are uploaded as "Image URL Prefix", and set .jpg or .png or whatever format we want as the "Image URL Suffix". (as the flags files are also named based on country code, this would perfectly find the right image and show it as the notice's flag. So, instead of 242 elements, we would only have 1 element on the page. And you know how weird the Elementor is creating dozens of nested divs and hundreds of lines of CSS code, for the simplest element. So avoiding 241 unnecessary notices would save a lot of page load time and future maintenance.)

**Comment by Floydtm** [comment]
I understand that this is important to you, but we have analyzed your request and it seems that it concerns only you. At the moment, we do not plan to introduce such functionality into our plugin. Thank you!

**Comment by SINFOUND** [comment]
We need this as well. Please implement this.
