### ISSUE TITLE
Bug in variable selection (In Safari browser)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4525]
hello
In the section selecting a single product page variable, The variable selection arrow is not displayed. **This problem only exists in Safari browser.** https://prnt.sc/235dznt

thank you

**Comment by 79ho3ein** [comment]
Hello @UraraReika !
may check this bug for the new version?

Thanks

**Comment by UraraReika** [comment]
This isn't a bug. This is the way how the appearance works in Safari browser. If you disable `-webkit-appearance: none;` style you will see default Safari browser selects with arrows and inside spiners but Elementor styles will not apply on them.

**Comment by 79ho3ein** [comment]
thank you @UraraReika. But in the last 2 updates, this was not the case and the arrows were displayed!
