### ISSUE TITLE
🐛[Jetsmartfilters] Active tags has lost its label setting 🔧

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#4526]
in jetsmartfilters active tags lost the label option or it was forgotten

**comparison between active filters and active tags widgets**
![label not available ](https://user-images.githubusercontent.com/82481592/146254513-9f2b91a3-04fe-4385-9d2b-0cfc8f814392.gif)

while waiting the fix
I switch to manual mode

```
selector .jet-active-tag__label {
   font-size: 12px;
   margin-right: 3px;
   color:#858B94;
}
```

**Comment by 79ho3ein** [comment]
hi @nreljed. You mean the label on this filter does not have typographic settings, right?

**Comment by nreljed** [comment]
> hi @nreljed. You mean the label on this filter does not have typographic settings, right?

yes , we can't customize label 
also with typography if we set zero to size 
the label disappear, so no need to target it with css and set display:none;

**Comment by 79ho3ein** [comment]
I have reported this many times, but unfortunately no one pays attention. This plugin, with all its power, has many drawbacks.

**Comment by SargasTM** [comment]
done, will appear in the next version
