### ISSUE TITLE
Dynamic Tables Builder - Option to stack table cells when viewed on mobile

### ISSUE THREAD

**Issue by deanloh** [CrocoBlock/suggestions#4528]
At the moment, when viewing dynamic table on mobile, user has to swipe left/right on the table to view other columns. Some users may not be aware of that and thought their view is limited only to first few columns.

Would be nice if there is an option to stack the table cells so data can be view without swiping sideways.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
