### ISSUE TITLE
Adding calculated field in JetElements that can display distance calculation

### ISSUE THREAD

**Issue by Comleon** [CrocoBlock/suggestions#4531]
Hello,

I would like Crocoblock to add an option to calculate distances based on Google Maps integration between 2 adresses filled in as CPT fields (2 different CPT).

Example:
CPT #1 is Clients, with Name, Address, Type of services, image, etc. fields
CPT #2 is Technical Representative, with Name, Address, Technical expertise, etc. fields

The option would allow to calculate the distance between the Client and the Technical Representative (remote worker) to establish the cost of travel, i.e. distance * rate/km

Thank you.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
