### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by kobus92** [CrocoBlock/suggestions#4535]
**#50900 Relational operator (Union & Intersection) for meta fields (checkbox filters)**![Screenshot 2021-12-09 at 09 11 41](https://user-images.githubusercontent.com/78893676/146513059-a7eb9d49-598c-4e2f-9ec9-97d5c25f0cb8.png)

Hi Guys, 

Adding this feature would be an AMAZING tool to add some serious power to filtering capabilities for all listing types. Having an option to set meta data checkbox filter relational operator as "Intersection" as one does for Taxonomies as data source is something I though would be a given. This feature is used on most accommodation listing sites, for example Booking.com

Please please please can this be added in the next update?

Kind regards,
Kobus

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7592)
