### ISSUE TITLE
JetBookings - Booking of two separate CPTs

### ISSUE THREAD

**Issue by Tommentron** [CrocoBlock/suggestions#4537]
Hello everyone,

I'd like to suggest an improvement for JetBookings. I think it would be great if there was an option to make a booking of two (or more) different CPTs. I am currently struggling with this as I need to somehow implement it but don't know how (maybe a different plugin or another one?). If anyone had an idea, please, let me know.

What would it be good for? For example, I'm developing a website where users can book locations (properties/rooms) as well as filming equipment (cameras, etc.). So it would be extremely beneficial to me. 

Thank you and if anyone had any advice, please, get in touch! :)

**Comment by UraraReika** [comment]
I merged this issue with #2573, which is on the same subject so we could deal with it more efficiently.
