### ISSUE TITLE
Bar Chart Showing Profile/Page Views for Members Account

### ISSUE THREAD

**Issue by deanray2809** [CrocoBlock/suggestions#4538]
I am wanting to place a Bar Chart in each of my member's Account Dashboards so they can see how many profile/page views they receive per hour, per day, per week, and per month.
When you replied to my question regarding this I was really surprised to see that this feature was not available.
Something as straightforward as being able to see how many visitors viewed your profile should be available.
Can you please put this in your to-do list.
Thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
