### ISSUE TITLE
Jetappointment, provider post type select user

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#4549]
I have a property cpt and I would like to install the jetappointment plugin so that visitors can choose a time to visit the property. Jetappointment does not allow the authors of the post to be selected as a provider. I have several wordpress users who are the authors of the cpt. It would be nice if you could include it in future updates.
![Captura de pantalla 2021-12-20 a las 17 22 13](https://user-images.githubusercontent.com/90837626/146799428-e4b16204-177c-4e57-9719-59ec9f5be2e9.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
