### ISSUE TITLE
JetSmartFilters

### ISSUE THREAD

**Issue by Olegggggggg** [Crocoblock/suggestions#455]
Hello. Now if I make a filter Check box and make three categories in it: A, B, C, when two categories are selected at the same time: A and B, I will see listings that contain separately category A and separately category B. Please add a filter setting which in this case will give the opportunity to show only those listings that simultaneously include category A + B together.
It is very necessary)

**Comment by javiercriado** [comment]
experiencing same issue. please add to core!
