### ISSUE TITLE
 Popups inside Listing grid don't work when using Lazyload.

### ISSUE THREAD

**Issue by pegujurado** [CrocoBlock/suggestions#4550]
Popups inside Listing grid don't work when using Lazyload. This problem has been going on for months.

**Comment by kaskad88** [comment]
Hello @pegujurado. Try to set the display conditions https://prnt.sc/24bbxw8 for the popup and add the page to the condition where use the Listing Grid https://prnt.sc/24bc07q.

if issue is still here, could you also please create a ticket at our support portal - https://support.crocoblock.com/support/tickets with access details to your website (and mention that you were directed by me and reference this issue.)

**Comment by pegujurado** [comment]
Thank you very much for the reply. First of all the screenshots are not displayed. Second, I don't think he understood me. When I use within a listing grid with LazyLoad and CCT activating Ajax and Force loading, it doesn't work, it doesn't launch the popup, it doesn't do anything. This has been going on forever. @kaskad88

**Comment by kaskad88** [comment]
@pegujurado Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

**Comment by pegujurado** [comment]
@kaskad88 First of all the screenshots are not displayed
