### ISSUE TITLE
Live/Ajax check for JetEngine's Forms

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4554]
We are using JetEngine's Forms for many parts of our website, and in most cases, the forms are long and have many fields.

Some of the fields' data can be checked before the form is submitted, which is great (like when you set the min or max characters, or when you set Filed Type. the user can't submit a form that breaches these rules. Or even Input Masks are handy in some cases)

But in many other cases, the form doesn't check the entered data before the form is submitted, and as a result, there is a reload after the Submit button is clicked, and then the form is empty and there are errors below the form. This really is not optimal at all. Reasons why:

- The fields get empty after the reload. user should refill the long form all over again (many just give up and leave)
- The error is below the form. (many users don't see and don't notice it. there is no other indication)
- When the page reloads, it doesn't scroll down to the form. The page loads at the top of the page. (the user gets confused and they don't know what just happened. They have to scroll down, go see the errors below the form and then they notice their registration wasn't successful for example)

There are 2 solutions that come to my mind:

1. Either check the fields data live/ajax (this is the best solution. it keeps updating the user as they fill a field. this way they know if everything is right or they have to fix a field's data)
2. OR, when the form is submitted with errors, then after the reload, keep the form's data, and also scroll down to the form, and also add some sort of indications on fields with error, and make the error messages as popup (or any other easily visible solution. popup was the best type of notice that just came to my mind. you may have better solutions)

Thanks

**Comment by jamsheehan** [comment]
This would be great in addition to [3264](https://github.com/Crocoblock/suggestions/issues/3264 )

**Comment by girafffee** [comment]
This issue is resolved with JetFormBuilder 3.0-beta

more details here
https://github.com/Crocoblock/suggestions/issues/6408
