### ISSUE TITLE
Integration with Zion Builder

### ISSUE THREAD

**Issue by 08ryanpietrzak** [CrocoBlock/suggestions#4559]
I am requesting that you provide integration with Zion Builder.

It is basically Elementor but without all of the BLOAT that elementor has in its code. 

You can review more information on their website.
https://zionbuilder.io/

They are growing EXTREMELY fast and I believe will be the new standard for block type page builders (without slowing down websites)

**Comment by Floydtm** [comment]
https://www.facebook.com/groups/CrocoblockCommunity/posts/4533744080050311/
