### ISSUE TITLE
Bug in jet woobuilder plugin / product grid Carousel.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4561]
hello

**(This bug is not related to the new version )**

The problem is that if I click on the product corners in the carousel, the carousel moves. The bug is strange, in the carousel, the products are in 4 rows. There is no problem when I click on the box of two products on the right. But the two products on the left have this problem. If I click on the box 2 of the product on the left, the carousel will move. **Without clicking on the left and right arrows.**
In short, by clicking on these areas (red), the carousel moves. But this does not happen in the green zone : https://prnt.sc/23x0o4d
**For a better understanding, please watch the video below. (Note the click location)**

https://user-images.githubusercontent.com/77163248/146999800-34192b69-34a8-45fa-961c-fc268dbcd43e.mp4

**some notes :**

1- My website is RTL. I'm not sure you have this problem in the red. Maybe in LTR this problem is in the green areas.
2- I do not know if this bug is in the new version or not. I have not tested yet. This is the previous version.
3- I tested this bug on several websites and it was there.

I'm sorry for the lengthy explanation

thank you

**Comment by 79ho3ein** [comment]
thank you dear @UraraReika❤

**Comment by schregsimone** [comment]
I'm still having this issue on mobile and tablet. When I click on a product (mainly a product on the right side) the carousel moves instead of opening the product. Could you please check?

**Comment by 79ho3ein** [comment]
@schregsimone , This bug has been fixed in the new version.
