### ISSUE TITLE
checkout coupon icon in Jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4562]
On the payment page, there is a coupon form. Please add the ability to change the icon of this form. It's excellent. This feature is available in the PowerPack plugin. jet woobuilder needs it too. https://prnt.sc/23xkswm

**Comment by UraraReika** [comment]
Thanks for the feedback.

We've checked your request and unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks.

But such a goal can be reached using a custom solution only.
I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.
