### ISSUE TITLE
Be able to Query Related Products and Upsell Products with the Product Grid Widget

### ISSUE THREAD

**Issue by shopakr** [CrocoBlock/suggestions#4563]
**Before adding a new feature request, please, make sure you’ve checked:**

It would be great if in the Query options for the Product Grid Widget you can ad Related Products or Upsell Products. This way there is an easy tool to add a Related/Upsell Product Carousel to a Product Page in JetWooBuilder.

**Comment by UraraReika** [comment]
Hello @shopakr !

This functionality exist in our widget. Please contact our support team. Thank you!
