### ISSUE TITLE
Template EMAIL with Elementor for JetFormBuilder

### ISSUE THREAD

**Issue by Topicimes** [CrocoBlock/suggestions#4567]
Hello,

Could you propose in the future a system allowing to send emails in HTML or even emails designed on Elementor, as it is the case of this plugin, it could be great : https://elemailer.com/?ref=Psmeg&campaign=general

Thanks in advance for your feedback.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
