### ISSUE TITLE
CSS Filters feature for product image / product grid widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4569]
Hi again

If possible, please add the "CSS Filters" option to the product grid widget. This feature is also included in the image widget. https://prnt.sc/242sqfx

**What is the reason for using "CSS Filters" in the product grid widget?**
Using this option, we can change the product image mode in this widget after Hover. For example, after the product  hovering, the image of the product becomes a little brighter, or a little blurry. this is fabulous.
In fact, as you know, this part needs this feature : https://prnt.sc/242tsm4           **Both normal and hover**

thank you

**Comment by Crocoblock** [comment]
The option has been added to three global widgets - https://tppr.me/qgMy1L . Both in the normal state - https://tppr.me/p9qReJ and when indicated - https://tppr.me/kCY9dp. Moreover, for pointing to work, you need to point to the widget card, not necessarily point to the picture itself.

was added in JetWooBuilder 2.1.14
