### ISSUE TITLE
Woocoomerce choose quantity in the product card

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#457]
Hello, could you add the Add to Cart button to the Jet Woo Builder widget that would include the selection of quantities directly from the product card?
Here is an example - https://prnt.sc/ovgwct

This function is needed in 90% of online stores, and food delivery sites without this function do not make sense at all.

Here is a sample code - https://wpincode.com/dobavlyaem-pole-kolichestva-na-stranicu-tovarnoj-kategorii-v-woocommerce/

But it is precisely in product cards built on Jet Woo that this code cannot be applied.

**Comment by stasonua0** [comment]
Guys, is there a chance that this will be realized?

**Comment by morkibut** [comment]
+1
