### ISSUE TITLE
Replace the URL in the Crocoblock templates with Site URL

### ISSUE THREAD

**Issue by johnfc2021** [CrocoBlock/suggestions#4573]
I recently installed the Zolden Store template using the Wizard and noticed the links in the home page and some other places point to demo.crocoblock.com/zolden instead of the site I just installed.

Can this be replaced with the Site URL when the Wizard has installed the content? I know WordPress provide site_url() to return the site URL.

**Comment by Floydtm** [comment]
I understand that this is important for you, but the installation wizard cannot replace links in some places. To do this, use the tool in the Elementor https://prnt.sc/26a45fe Thank you!
