### ISSUE TITLE
Jet Appointment - Send the booking to the calendar

### ISSUE THREAD

**Issue by eliquame** [CrocoBlock/suggestions#4575]
Hi Croco Team!

We cant find a very important feature.
We would like to an option to send Google and Apple calendar the booking. For the provider e-mail and for the customer who has booked the time too,
![screenshot-2021 12 23-16_25_54](https://user-images.githubusercontent.com/44946426/147261075-620707c8-3ccd-48ec-98ab-75bf3de0ee06.png)
.

**Comment by Floydtm** [comment]
I understand that this is important for you, but now there is no such option in the plugin. But you can use Call a WebHook Send notification for your case right now https://prnt.sc/26a4vi0 Check out the [documentation](https://crocoblock.com/knowledge-base/articles/jetengine-how-to-synchronize-form-with-3rd-party-services/) on our website. Thank you!
