### ISSUE TITLE
JetSmartFilters with Elementor posts widget bug

### ISSUE THREAD

**Issue by msmatis** [Crocoblock/suggestions#458]
hello,
I have created custom taxonomy by pods, on my web site I have Elementor posts widget which have query set to include term from taxonomy A and exclude another term from taxonomy A (image 03 and 04). On same page I have set filter which is filtering results base on taxonomy B.
Problem is that on some options from filter, displayed results are from excluded taxonomy A (image 02). 

![01](https://user-images.githubusercontent.com/26801957/63425884-d6dff380-c411-11e9-9deb-1eed35d7578f.jpg)
![02](https://user-images.githubusercontent.com/26801957/63425885-d6dff380-c411-11e9-97a5-8c169e6b658d.jpg)
![03](https://user-images.githubusercontent.com/26801957/63425886-d7788a00-c411-11e9-8251-b220a4a911eb.jpg)
![04](https://user-images.githubusercontent.com/26801957/63425888-d7788a00-c411-11e9-81c1-db6c392280f8.jpg)

**Comment by Floydtm** [comment]
Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help you
