### ISSUE TITLE
Option "Mobile Hover on Touch" does not support the Hover effect of thumbnail images of products attribute / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4582]
hello
I'm not sure if this is a bug or not, but I think it needs to support this feature. Because in the product grid widget, the only way to change the images is to hover it.
If we click on the product on mobile and tablet, the image will change, but it will enter the product page immediately.

thank you

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!

**Comment by 79ho3ein** [comment]
I will investigate more at the appropriate time. Thank you
