### ISSUE TITLE
Add "Has Archive" to Meta Fields [JetEngine]

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4583]
As you know, Woocommerce's Attributes has a checkbox called "Has Archive", which if checked, that attribute will have an archive page in the front-end. (this is very useful as users can access each attribute's page to see the list of related products)

But for many reasons, we decided NOT to use WC's built-in attributes system, and instead, we are using JetEngine's Meta Box (Meta Fields)

The only thing missing here is the "Has Archive" functionality for Meta Fields. (it kinda makes sense not to have it if the meta fields are being used as is, but as you know, JetEngine is all about creativity, and when you talk about creativity, you use features for many different purposes that may not be the actual purpose of that feature initially)

I think, if you add a checkbox to the Meta Field to let us set that field to have archive, would open many doors to creativity (at this point, we have to create pages manually and add Grid Listing to each page to show specific filter, but the "Has Archive" system would automate this, which is a big time-saver, especially when there are hundreds of meta-fields/attributes)

Thanks

**Comment by Floydtm** [comment]
I understand that this is important to you. However, you should understand that attributes are taxonomies. Meta fields cannot be taxonomies and cannot have archived pages. For this you need to use custom taxonomy. Thank you!
