### ISSUE TITLE
After payment, the product remains in the cart / jet woobuilder bug

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4588]
hello @UraraReika
If we activate the **Thanks You page** and use it on the website, there will be a problem ...
After the user makes her payment through the bank portal, and returns to the site, she will be faced with thank you page. But the problem here is that the product that the user has already added to the cart and paid for it (through the banking gateway) **still remains in the user's cart.**
I have tested this problem many times but the product still remains in the cart after payment. But when I disabled the jet woobuilder **thank you page**, the problem was fixed and after payment, the product no longer remains in the cart.
Please consider this, it is very important.
There is definitely a problem in this area, because disabling the thank you tab will solve the problem.
**details**
1- thank you page is in canvas mode.

thank you for your attention🙏

**Comment by UraraReika** [comment]
Please contact our support team so we can test it. Thank you!
