### ISSUE TITLE
Bug in free mode / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4589]
hello
There is a small bug in the free mode feature which is as follows :
If we scroll through the carousel and then go to the bottom of the website and return to that carousel again, the carousel status will be reset. While its state should not change.

1- After scrolling, the carousel looks like this , This is normal and there is no problem : https://prnt.sc/24un8jp
2- But after we leave the carousel and go to the bottom of the website and go back to that carousel, the carousel mode is reset : https://prnt.sc/24unh16

Please correct this problem if possible, so that free mode is not reset under any circumstances. (Except with page reload)

I hope I conveyed my words well. Otherwise, please watch this video. The problem is quite clear.

https://user-images.githubusercontent.com/77163248/147508710-6bf4e973-b769-4ce7-beca-8ff9fe899cec.mp4

Please note that I experience this problem in the **Android** version of **Chrome browser**. I did not test other browsers and IOS.

thank you

**Comment by 79ho3ein** [comment]
hi @UraraReika , good time!
I had a question about free mode ...

Do you use the elementor swiper library for free mode?
Because freemode is not working properly at the moment and does not work well on various devices and browsers. Of course, I had already explained about it. So I wanted to ask if you are using swiper library for free mode, if the elementor updates this library, will the current problems be solved?

**Comment by UraraReika** [comment]
Yes we use Swiper library from Elementor. May be after they update this library to some newest versions some problems will gone.
