### ISSUE TITLE
не меняются настройки попап (нужно фиксить)

### ISSUE THREAD

**Issue by zimmiel** [Crocoblock/suggestions#459]
Задал вопрос в тикет
- не меняются настройки попап (изменил close button, убрал фон в настройках, но на сайте он остался)

получил ответ
- И касательно того, что стили в попапе не меняются на фронте - с последними обновлениями Элементора некоторые стили поменялись. Это нужно фиксить глобально. Можете пожалуйста сообщить обэтой проблеме нашей команде на гите

Сообщаю команде на гиге:
В настройках меяю стили попапа - а на фонте ничего не меняется. Так же с масштабированием

![popup-size](https://user-images.githubusercontent.com/42843497/63428035-3d1f4300-c41f-11e9-9f7b-bd8718fadc48.png)
![popup-size-2](https://user-images.githubusercontent.com/42843497/63428036-3d1f4300-c41f-11e9-8116-476ded405e7a.png)
![popup-x](https://user-images.githubusercontent.com/42843497/63428038-3d1f4300-c41f-11e9-90af-c78a8f87c040.png)
![popup-x-2](https://user-images.githubusercontent.com/42843497/63428039-3d1f4300-c41f-11e9-8ebf-d6db02113d2b.png)

**Comment by Floydtm** [comment]
@zimmiel, Please, note, that the feature requests can be accepted and processed only if they’re written in English. We will fix this bug in the next plugin update. Stay tuned

**Comment by zimmiel** [comment]
okey)

ср, 21 авг. 2019 г. в 17:40, Floyd <notifications@github.com>:
