### ISSUE TITLE
Add Carousel/Slider Feature to your Single Related Products Widget and the Singe Upsells Widget

### ISSUE THREAD

**Issue by shopakr** [CrocoBlock/suggestions#4591]
It is very popular to list your Related Products and Upsell Products in a Carousel format to save space on the page and make it more user friendly to scroll through the products. Almost every large store I shop on uses this display type for related and upsell. 

You offer a Single Related Products Widget and a Singe Upsell Widget. But neither of these have a Carousel feature. I also tried adding this using your Product Grid Widget since this has a Carousel Feature, but it does not have Queries for Related or Upsell. So then you can create an Upsell Custom Query using JetEngine, but not a Related Query. But this threw a server error. And why go through all of these steps, of trying to create custom queries when you already have the Widgets for Related and Upsell. You just need to add the Carousel Option to them.
Believe me, it will be a very desired feature.

**Comment by UraraReika** [comment]
Hello @shopakr !

You can use Products Grid widget for this purpose. Add Products Grid widget to Single Product template. Save template and reload it. After reload related and upsells queries will appear.
