### ISSUE TITLE
Elementor Button Widget Extra spacing

### ISSUE THREAD

**Issue by morosmo** [CrocoBlock/suggestions#4593]
Hi Elementor Devs,
From last three  updates I am facing issue regarding about elemenotr Button Widget.
The issue is:
When we drag elementor button widget by default they are adding margin on top of the button and padding bellow text inside button.

![Screenshot](https://user-images.githubusercontent.com/87468744/147636754-a5db0f4a-fb42-4a64-ba69-d4de967b7f4e.png)

You cna see the screenshot for more refference.
Thansk

**Comment by Floydtm** [comment]
Hi! Leave your request [here](https://github.com/elementor/elementor/issues)
