### ISSUE TITLE
Suggestion: JetWooBuilder for Gutenberg

### ISSUE THREAD

**Issue by flyingcompass** [CrocoBlock/suggestions#4597]
If you're not already doing or planning this, would like to request you create JetWooBuilder blocks as you have done with JetEngine, JetSmartFilters, etc. 

A set of blocks to customize WooCommerce using Gutenberg would be a great addition.

**Comment by davidwatkins2** [comment]
I agree

**Comment by UraraReika** [comment]
I merged this issue with #3782, which is on the same subject so we could deal with it more efficiently.
