### ISSUE TITLE
Add conditions to hide whole Elementor section/column if all meta fields are empty

### ISSUE THREAD

**Issue by kiudex** [Crocoblock/suggestions#460]
Hi Crocoblock team,

I know that with JetEngine for dynamic fields I can set the fields to be hidden if they are empty (no value). That's basic functionality with custom fields and for the most part I'm happy with it. Just sometimes hiding one field is not enough based on the layout.

For example: In a current project users can add image galleries and optionally add information about the gallery only if they want to. I added a listing with a section containing all the meta fields to show all the information. 

<img width="1246" alt="Screen Shot 2019-08-22 at 11 59 26" src="https://user-images.githubusercontent.com/14236672/63485013-59c98280-c4d4-11e9-962f-3f1e1b2504f9.png">

BUT if no information is added by the user then there is an empty section with titles. If users don't want to add any information the whole section containing this information within the listing element is just empty and should be hidden completely. Right now I can only hide the fields but not the whole section that contains the fields. The result is pretty ugly.

<img width="1246" alt="Screen Shot 2019-08-22 at 11 45 48" src="https://user-images.githubusercontent.com/14236672/63485097-b0cf5780-c4d4-11e9-959a-8e36c67abc5d.png">

Could you add conditional logic to Elementor sections/columns etc. to be hidden if meta fields have a certain value (e.g. text field "Do you want to add information?" - Answer "NO") or if all specified fields are empty?

I'd be okay to add a meta field that explicitly asks if the section should be visible or not. If that's too difficult within Elementor I would also be happy if I can add some custom code that allows me to achieve that.

I opened a support ticket with the same question and was asked to add this suggestion here.

Best regards,

Kevin

**Comment by Floydtm** [comment]
@kiudex, hi! Thank you for contacting us. We will be able to review your request when we finish working with main tasks. Now you can use this [plugin ](https://wordpress.org/plugins/dynamicconditions/)

**Comment by kaskad88** [comment]
I merged this issue with #755, which is on the same subject so we could deal with it more efficiently.
