### ISSUE TITLE
Widget "Compare" with glosseries and comma settings like the widget "Dynamic Field" has...

### ISSUE THREAD

**Issue by L6ZB3W9** [CrocoBlock/suggestions#4601]
Hello developer of Crocoblock!

In the widget "Dynamic Field" it is possible to set the display of a value. So you can show
a) Glosseries
b) Numerical values with a comma instead of a period (standard from the database)

Unfortunately, this is not possible by default with the “Compare” widget.

The glosseries can be displayed awkwardly using a filter. Numerical values with commas do not work. 

Please integrate this function in the "Compare" widget.

Thanks in advance… 

Best regards

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
