### ISSUE TITLE
Improve ux in product grid widget / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4603]
hello, happy New Year👋

I had a suggestion for this feature, it would be great if you add it to this widget. With this feature, users will feel great when hovering over products. Now I use this feature using css half line, but it would be great if you could add this to the plugin for other users to use as well.
With this code, if users hover over products, the product box will move up slightly. Please watch this video :

https://user-images.githubusercontent.com/77163248/147821800-1d10dde9-4a9a-42d9-aa69-1713b973f444.mp4

I use this code :

.jetwoo_sale .jet-woo-products__inner-box:hover {
    transform: translateY(-2px);
    transition: transform 0.5s ease;
}

In fact, this feature is required in this section : [ ](https://prnt.sc/25elrlg)    **Only in Hover mode.**

Please check this. It would be great.

thank you for your attention🌹

**Comment by Michaelgimii** [comment]
Great idea. We now have this functionality in elementor and can use it in jet woobuilder. https://prnt.sc/t40d74YQW7Yp
@UraraReika , Please consider this. thanks

**Comment by UraraReika** [comment]
This feature is quite complex @Michaelgimii present screenshot https://prnt.sc/t40d74YQW7Yp but most part of this functionality is hidden behind tooltip. Here you can see the full picture https://tppr.me/b3bjR. There is no way we will ad this functionality to our widgets, and in this case you just need one simple option. 

But in the future we do not exclude the possibility of adding this functionality. Like separate module for example. 

For now you can even simplify you pease of code if you use Elementor PRO like this:

```
selector .jet-woo-products__inner-box:hover {
    transform: translateY(-2px); // you don't need transition because it already exist
}
```

**Comment by 79ho3ein** [comment]
thank you @UraraReika
