### ISSUE TITLE
Jet Booking, bookings/nigth

### ISSUE THREAD

**Issue by jannelundin** [CrocoBlock/suggestions#4605]
If you reserve one appartment ot room for 2 or 3 nigths the checkout day is OK for booking but
the checkin day is not bookable any moore. 
 It needs to be checkin before noon and checkout after noon should be free, otherwise you lose 1 bookable nigth.
and then there is this issue with seasonal prices that is absolutely nessecary for a appartment or room
booking plugin without these features the plugin is useless.

**Comment by Hammer-ger** [comment]
because of that you can not use jetBooking for a real world situation.
be carefull: if you use the daterange finder, a coustomer can book an alredy booked appartment and wil get the  conformation e-mail. so you have two guest at the same time and the same room ;-) could be interesting.

**Comment by jannelundin** [comment]
It should be checken in afternoon and checkout before noon
I wrote the wrong way. It is normal That you have to
Checkout like 10-11, and check in around 13-14.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was added in 2.5.1 release called  Checkout only days option. Feel free to contact our support team for instructions.
