### ISSUE TITLE
JetBooking Availability widget not working on translated pages

### ISSUE THREAD

**Issue by zigy1981** [CrocoBlock/suggestions#4606]
Hi, when translating a page with availability widget to other than original language, the availability is not shown correctly as it is not pulling the info from correct custom_post_id. The widget should have the possibility to select from which post_it should it pull availability. This is a must, otherwise the availability widget is not useful on multilanguage pages. In Motorpress, it is a basic functionality.
Example:
![image](https://user-images.githubusercontent.com/96580649/147978644-3781f77d-35f6-4041-95cb-a11cb678e41b.png)

Example of Motopress plugin solution for translated pages - just use the original post id:
![image](https://user-images.githubusercontent.com/96580649/147979528-97592f3f-4b07-4a59-92c9-193db8cbe636.png)

**Comment by UraraReika** [comment]
This was fixed in one of the latest release when we added compatibility with different types of translate plugins.
