### ISSUE TITLE
Display sale product in variable products / jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4607]
hello
I'm not sure if this is a bug or not, but there is a problem anyway...

If in a variable product that contains two variables, only one of its variables has a sale price, this product is not known as a sale product (https://prnt.sc/25tcmi1) !

For example, we have a product carousel on the website, which displays sale products. (product grid widget)
On the other hand, for example, we have the iPhone 13, which has two variables. IPhone 13 with 4 GB of RAM and iPhone 13 with 6 GB of RAM. If we only put the iPhone 13 with 4 GB of RAM in the sale price, this product will not be known as the sale price.
in prooduct grid widjet, **Sale query does not display this product**. Therefore, users will never know that one of the iphone 13 variables has a special sale! And this is a big musk. 

**Suggestions to fix this problem**
I think it is great if the products are displayed in such a way that sale products are a priority. That is, if, like the conditions above (iPhone 13), there was only one variable of a product in the sale price, that product would be displayed as an index, which has a sale price.

I hope I conveyed my point well.

thank you

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
thank you
