### ISSUE TITLE
The "recently viewed" query does not work properly.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4609]
hello
If you remember, I had previously reported on this problem. The problem was that if the wp-rocket plugin was enabled, the recently viewed query would fail !
I reported this problem to wp-rocket, they said **recently viewed query does not support cache.**
In order to test, while the wp-rocket plugin was active on the website, I used the code to disable the website cache and the problem was solved.
Please check this if possible.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !
Recently viewed query use cookies. WP Rocket should have some settings for it. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
hello dear @UraraReika.
I checked this problem and found that this query (recently visited) has a problem with cache. I disabled the cache of the home page in which I used this query and the problem was solved! But it does not make sense to disable the entire cache of a page and causes a slowdown.
In fact, in this query, the cache must be disabled for it to work properly. Please add this in the new version if possible. It is very, very important.

thank you🌹
