### ISSUE TITLE
Jet Menu. Add the ability to download mega menus using Ajax

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#461]
Jet Menu. Add the ability to download mega menus using Ajax

**Comment by ScottKemp** [comment]
110% agree.  There is really no one else doing this with WordPress.  It would be a great feather in JetMenu's cap.  The mega menu clogs every page on my site with DOM elements, CSS and JS when most of it is never used.

**Comment by shinTM** [comment]
done v 2.0.0
