### ISSUE TITLE
ola, nao consigo atualizar o plugins JetBlocks para a versão 1.3.9. quando tento atulizar pelo wodpress da erro. 

### ISSUE THREAD

**Issue by meloczr** [CrocoBlock/suggestions#4610]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UraraReika** [comment]
Please contact our support team. Thank you!
