### ISSUE TITLE
MegaMenu Tablet menu selection 

### ISSUE THREAD

**Issue by PaulCGR** [CrocoBlock/suggestions#4612]
Could we add possibility to select Mobile menu to tablet, please? 

**Default is : Desktop and mobile view**
Desktop: Desktop
Tablet: Desktop
Mobile: Mobile

**So what i would like to be able to select is:** 

Desktop: Desktop
Tablet: Mobile
Mobile: Mobile

Trouble is, while you duplicate element to achive that , it react funny while on JetSticky and scrolling on Ipad.

Many thanks! 
PK

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
