### ISSUE TITLE
Vertical alignment in the arrow box of the product grid widget.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4614]
Very small things also affect UI design. There is a problem in the product grid widget that I always face. Manually, I positioned the arrow box in the middle (vertically). But if the carousel has a sale product, the arrow box will no longer be in the middle. Because with the addition of the previous price, the height of the carousel will increase slightly. So it will be a little lower and this will hit the UI hard.
My suggestion is to add the Vertical alignment option to the arrow box so we can control it. For example, if we place the Vertical alignment in the middle, the arrow box will automatically be in the center. Therefore, by changing the height of the carousel, the arrow box will always be in the center.
Adding this feature is not difficult. But it is needed. I hope it will be added to the new version. thanks

**Comment by UraraReika** [comment]
Please to add any videos, links, screenshots to illustrate the requested feature.

**Comment by Michaelgimii** [comment]
hello @UraraReika 
Under normal circumstances, there is no problem if we place the arrowS boxe in the center (vertical) : https://prnt.sc/2604fl3
But if a product has a sale price, the arrow box will go out of balance. Because with the addition of the sale price the height of the carousel has increased : https://prnt.sc/2605iyk

In the second image, due to the change in the height of the carousel, the arrow box moves slightly upwards and is not in the middle.
**By adding the Vertical alignment feature to the arrow box, this box is automatically centered in any situation.** Therefore, we no longer need to manually set its height in the center (vertical). Will be centered automatically (vertically).
This is a very necessary case.

**Comment by UraraReika** [comment]
What units you use to center arrows (%, px, em)? Why don't you display price inline to avoid this issue?

**Comment by Michaelgimii** [comment]
I used the value%, it was solved. thanks
