### ISSUE TITLE
Custom position of badges in product grid widget / jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4618]
hello

Currently, the relocation of badges is very limited. It can only be placed on the right and left, we can also give it a margin. Worst of all, we can only move it within the specified range (green range). If it goes out of range, it goes below the price layer (red blue arrow).
https://prnt.sc/266k89q

**proposed solution**
Great if you add custom positioning to this section. Just like the custom position of the carousel arrow box : https://prnt.sc/266kad3
this is great.
**With the above feature added, we no longer need these items in the badges settings :** https://prnt.sc/266kb9z

**One more point**
Badges have padding by default : https://prnt.sc/266kbsf        If you set the padding value to 0 by default, we no longer need the padding setting option : https://prnt.sc/266kcuf    Because now, we have these settings and no padding is needed :  https://prnt.sc/266kdni & https://prnt.sc/266kduo

**The above are not necessary. But it helps to make this widget more professional, because there will be no restrictions.**

thank you for your attention❤

**Comment by UraraReika** [comment]
The position of this element will stay the same. Every preset of this widget contain this element inside thumbnail wrapper so you can't move out of it.

In new version of this plugin some new controls will be able. None of control will be removed.

**Comment by 79ho3ein** [comment]
thank you
