### ISSUE TITLE
[JetSmartFilters ] CRITICAL BUG - broken pagination when going to next page with filters enabled

### ISSUE THREAD

**Issue by hicham1989s** [CrocoBlock/suggestions#4619]
**Describe the bug**
JetSmartFilters + Elementor Archive Posts pagination does not work and shows white screen.

**To Reproduce**
1. **Go to https://wordpress-657309-2366143.cloudwaysapps.com/people/**
2. Click one of the checkbox on the right (for example Belgium)
3. Scroll down to pagination and pick next page
4. See error (white screen, links to https://wordpress-657309-2366143.cloudwaysapps.com/wp-admin/admin-ajax.php/page/2/

**Expected behavior**
Going to next page of the results within that selection

**Additional information**
- Tested on clean fresh installed Wordpress
- Only active plugins are Elementor + Elementor Pro + JetEngine + JetSmartFilters

My developer cannot fix this as he told me you are using some Vue Javascript and it would be easier for you to fix this as soon as possible.

**Checkbox filter settings**
- I have tried with all Apply type: non worked correctly.
![Screenshot 2022-01-06 165058](https://user-images.githubusercontent.com/96820586/148410631-8e955691-d4db-4b39-9973-dc3c5f2d8333.png)

**Comment by Floydtm** [comment]
I understand that this is important for you, but technically we cannot make filters compatible with element pagination. Use JetSmartFilters Pagination.  Thank you!
