### ISSUE TITLE
JetWooBuilder Back in stock notification

### ISSUE THREAD

**Issue by ihslimn** [CrocoBlock/suggestions#4620]
Will it be possible to add the functionality similar to https://woocommerce.com/products/woocommerce-waitlist/
to JetWooBuilder directly or as an addon?
It would be great to allow customers to track the product availability - to get notification by email or otherwise when the product is back into stock.

**Comment by Michaelgimii** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with #3916, which is on the same subject so we could deal with it more efficiently.
