### ISSUE TITLE
[JetAppointment) Home services

### ISSUE THREAD

**Issue by VaniaRensi** [CrocoBlock/suggestions#4627]
It would be great to have an option for home services appointments (cleaning, baby sitting, at home car washing etc.) where:

- the user insert his address
- the plugin, compares this address with the previous appointment's one, and calculate the distance
- based on that distance it applies a different preset time buffer and show the right next available time

The time buffers have to be set previously, based on distance range and knowledge of the area ex. 0-5km -> 15min, 5-10km-> 20min, and so on.

Am I dreaming? 😊

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
