### ISSUE TITLE
JetEngine Form: Add ability for One Time Passcode To Complete Submission

### ISSUE THREAD

**Issue by IFTTD** [CrocoBlock/suggestions#4628]
To help deter spam and ensure only actual active emails belonging to the submitter are used to submit the form adding OTP (One Time Passcode) before a form gets submitted would be a real help.

In todays world everyone is going with some kind of 2FA system. Implementing this ability would greatly help the JetEngine Form plugin.

How it would work:

1. User fills out form (email field required)
2. System creates and sends a OTP to the email address given. Inside the email is the randomly generated 6 digit passcode.
3. The form then asks for this OTP to complete the form submission via a new field.
4. Once correct passcode is entered. Form completes all the rest of the submission tasks.

Obviously the first submission notification in task list must be an OTP action. OTP passcodes are only valid once hence the name One Time.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by MolyMalon** [comment]
This functionality would be great! I'm interested!!

**Comment by MolyMalon** [comment]
This functionality would be great! I'm interested!!

**Comment by MolyMalon** [comment]
And give the user the possibility to choose their own user role too...
