### ISSUE TITLE
Add Ken-Burns effect to slider Image

### ISSUE THREAD

**Issue by JurIvk** [CrocoBlock/suggestions#4629]
**Please add Ken-Burns effect to slider image**

the fade transition between the slides are great but for better UX there is a need to enhence the widget with good looking effects.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
