### ISSUE TITLE
Add ability for (vendors/partners) users to accept/decline bookings

### ISSUE THREAD

**Issue by olyaastep** [CrocoBlock/suggestions#4630]
Hello!
It would be great to add a feature/widget to display orders related to users who posted them with the ability to accept/decline orders from the frontend. It is necessary for booking marketplace partners to have an opportunity to manage their bookings from their front end account. 
So when the booking is made on the website, the status order should be pending approval, then when a partner adds a notification message he can log in to their account and decline or accept the booking, this should trigger an email to a client with a checkout link or "sorry the unit is not available for booking"
 A similar solution is provided by https://wordpress.org/plugins/dokan-order-approval/
but it is not compatible with crocoblock bookings.
Hope this feature will be added as soon as possible.

**Comment by UraraReika** [comment]
I merged this issue with [#1080](https://github.com/Crocoblock/suggestions/issues/1080), which is on the same subject so we could deal with it more efficiently.
