### ISSUE TITLE
Add Relevansssi support for better search [code in description]

### ISSUE THREAD

**Issue by jacktaffa** [CrocoBlock/suggestions#4631]
@MjHead 

please, add Relevansssi support to jet search just adding this lines of code for an incredible ajax search
```
// ON jetsearch/includes/ajax-handlers.php:216
	if(function_exists('relevanssi_do_query'))
			    relevanssi_do_query( $search );
```
<img width="1386" alt="Schermata 2022-01-08 alle 18 57 50" src="https://user-images.githubusercontent.com/2649534/148654725-2b1f7676-6a20-450b-afa0-eb9ca67ce6b7.png">

**Comment by MjHead** [comment]
Added with 3.0.0 update

**Comment by alexmoreirarosa** [comment]
Seria importante ter a opção de listar mais de um select de categoria no plugin.
Eu dupliquei no formulario mas não consegui puxar o outro.

<?php echo $this->get_categories_list(mais_categoria); ?>
 <?php echo $this->get_categories_list(); ?>
