### ISSUE TITLE
New scrollbar for free mode (product grid widget)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4633]
Thanks for adding this #4461 feature to the plugin. The free mode feature is now one step away from being completed.

Horizontal scrolling is excellent for free mode. Almost all websites that use free mode enable horizontal scrolling to let users know where they are after navigating. See this image : https://prnt.sc/26bomwi       this is fabulous.

Currently, we only have navigation Dots in the product grid widget. Which is not suitable for free mode. Therefore, the current navigation Dots are used only for ordinary (Default) carousels.

**Describe your solution**

Please add a feature that, if the free mode is enabled, will automatically delete the current navigation points and add horizontal scrolling instead. Therefore, if we disable the free mode, the former navigation points will be reactivated.
**Note: Horizontal scrolling is only used for mobile phones and tablets.**

Horizontal scrolling will require very simple customization. As :
Width and height adjustment : https://prnt.sc/26bopvj
Color & hover color : https://prnt.sc/26boq2q
background color : https://prnt.sc/26boq7o
shadow for color & background color : https://prnt.sc/26boqij
border & border radious for this color & background color 

Please do not reject this offer. It is extremely important and necessary. thanks

**Comment by pgirzalsky** [comment]
+1 we definitely need a scrollbar. Same goes for the Listing Grid widget. Please update that to use Swiper as well and add a scrollbar for the slider! Also, a custom slidesPerView or "Columns" value as you named it in your settings, would be greatly appreciated! Swiper supports values like 2.3 or 3.5 as well as full numbers like 1, 2, 3. It's easily doable by changing from a SELECT Controls_Manager to a NUMBER.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce new carousel functionality in our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Despite that you can achieve this right now. First of all you need to rewrites one template in your child theme, this one jet-`woo-builder/widgets/global/products-grid/loop-end.php`. To override template use comment in file heading. Like this - https://tppr.me/we0xHe add this line to the end of the file `<div class="swiper-scrollbar"></div>` 

Second step will be to use options hook where you can add scrollbar like this:

```
add_filter( 'jet-woo-builder/tools/carousel/options', function( $options, $settings ) {
    $options['scrollbar'] = [ 'el' => '.swiper-scrollbar' ];

    return $options;
}, 10, 2 );
```

This is minimum required code, if you want to extend it please use Swiper API docs - https://swiperjs.com/swiper-api#scrollbar

Please [contact](https://support.crocoblock.com/support/home/ ) our support team if you have additional questions.

Thank you for your understanding.
