### ISSUE TITLE
Call for price / jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4634]
Call for price feature can be very useful in any store website. There are currently plugins for this feature that do not have proper coding and have a negative impact on the site.
It would be great if we could localize this feature in jet woobuilder. Therefore, we will not need to use miscellaneous and low quality plugins.

In order to implement this feature in jet woobuilder I had a suggestion that would be great if you agree with it.
Please add a new one to crocoblock > jet plugin settings > jet woobuiilder > General settings. This section will have very simple settings.
To add this great feature, we need these settings: https://prnt.sc/26boz2q

According to these settings, we activate the call for price, then enter the desired text that is displayed to users. For example, call.
After that, the price of each product that we consider in WooCommerce 0, this text will be displayed instead of the price.

a case : If you add this feature to the plugin, it needs a little customization in the product grid widget. Only in terms of typography and color.

thank you

**Comment by UraraReika** [comment]
https://github.com/Crocoblock/suggestions/issues/5222
