### ISSUE TITLE
 A few suggestions to improve cart & checkout page / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4635]
hello

There are cases that are found gradually. I report them, please check them if possible.

1- Please add the possibility of editing the text of these 3 parts in the coupon section of the settlement page. They are very important for translation : https://prnt.sc/26bqlwu
2- Please add the "Show hidden products" option to the cart table & cart totals so that if the cart is empty, we can still edit the cart. As you know, this option is currently available in the product grid widget.
3- Please make the coupon section in the cart page responsive. https://prnt.sc/26bqn1o
4- The coupon button in the shopping cart table does not have a margin setting. Please add. https://prnt.sc/26bqowc
5- cart table has no left and right border : https://prnt.sc/26bqpsw
6- Please add the ability to edit the text of the button to the Cart Totals widget.
7- Please add the ability to edit the text of the button to the Checkout Payment	 widget.
8- Please add the heading section to the cart table widget. (Like other widgets) https://prnt.sc/26bqsy3
9- Please add margin settings to the update button. (Shopping cart table widget)

10- **In the "Order notes" section of the payment page, there is no (optional) section in the text editing section. So we can not delete (optional).** https://prnt.sc/26bqw5p
11- **In the settlement form, the zip code field only supports Latin characters. Therefore, if we use Persian numbers for example, it shows an error. (Postal code is not valid)** Please add compatibility with other numbers if possible.

Thank you very much for your attention🌹

**Comment by UraraReika** [comment]
Hello @79ho3ein !
Some of this will be added in the future release, something not.

**Comment by 79ho3ein** [comment]
hello
thank you dear @UraraReika.

Is it clear when the update will be released?
