### ISSUE TITLE
Cannot use date field to calculate age for conditional

### ISSUE THREAD

**Issue by barrychapman** [CrocoBlock/suggestions#4637]
**Describe the bug**
have a date field (birthdate), but it will not work with conditionals.
The conditionals do not show the option to display by age

**To Reproduce**
create a form, add a date field, add another field, try to set conditional based on outcome of date

**Expected behavior**
to be able to display by date

**Desktop (please complete the following information):**
 - OS: win11
 - Browser all
 - Version 2.10.1

**Additional context**
Would be really nice if we could pass in a shortcode to apply logic from. Say, we pass the selected date from control field to a shortcode, which does the comparison and returns whether or not it is true

**Comment by girafffee** [comment]
The new version of JetFormBuilder 3.0-beta is now available to you.
You can check if your case is working now.

For this, in the Conditional Block, you only need to specify the date field and choose the operator Greater than, Less than or Between (that is, those that work with numbers)

More details here https://github.com/Crocoblock/suggestions/issues/6408
