### ISSUE TITLE
GEO LOCATION -> NEAR ME SEARCH > WITH POST TYPE RESULTS

### ISSUE THREAD

**Issue by developer784** [CrocoBlock/suggestions#4638]
We need GEO LOCATION SEARCH feature ASAP... there is no reason NOT to have it in 2022.  Let's go!!  :)

**Comment by Kytab** [comment]
Agree....
My customers aske me that feature all the time !

**Comment by simonclay** [comment]
Would really value this feature. I have had 2 clients ask me for it. But have had to resort to other plugins.

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
