### ISSUE TITLE
Remove time slot in Teams / Crocoblock Cloudcut Template

### ISSUE THREAD

**Issue by Loverko008** [CrocoBlock/suggestions#4640]
PLEASE HELP>

How to turn off or remove a time slot from team settings. I want to keep the opening hours settings in teams.

https://ibb.co/HX95Fqm

**Comment by Loverko008** [comment]
![screen plug](https://user-images.githubusercontent.com/97444714/148772735-425c9edd-6eb1-4a42-af4f-b6266f47c746.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
