### ISSUE TITLE
Jet WooBuilder can't use Query Builder for Product Loop widget

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#4652]
It will be a very cool feature if **Product Loop** widget can use **queries** like listings do. 

This way in shop pages we can use multiple Product Loop widgets with different queries. It's convinient for making restaurant menus for example.

**Comment by mary151** [comment]
![query](https://user-images.githubusercontent.com/56391303/149151552-6f123e4c-cef0-4dcf-87c3-aed025ac6a77.png)

**Comment by UraraReika** [comment]
Products Loop widget used only in JetWooBuilder Shop Template and use global WC query. You mentioned Listing Grid widget then just use it. Especially when you can use Archive Template widgets inside Listing Template.
