### ISSUE TITLE
Read More widget : CSS ID of section => Dynamic tags => Current Post Id | Jet Woo Builder

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#4653]
Hello,

I'm trying to implement "**Read more**" widget in Jet WooBuilder archive template. But it works only with css id of the hidden section, which must be different for every product in the loop. In dynamic tags options for css id I didn't find "Post ID", or any post related tags.

If you implement this dynamic tag option it will be usefull for many of your plugins and will make them more dynamic.

**Comment by mary151** [comment]
![readmore](https://user-images.githubusercontent.com/56391303/149159625-9e87f323-79fc-425f-93ce-389082319249.png)

![css_id](https://user-images.githubusercontent.com/56391303/149159646-35ef8302-0b89-40cb-806e-8a09a2c431a7.png)

**Comment by UraraReika** [comment]
Most users use JetEngine in combination with Elementor Pro which has default dynamic tag [Post ID](https://tppr.me/FjL4V). So it's pointless to add this to JetEngine. Please [contact](https://support.crocoblock.com/support/home/) our support team and they will help you to implement it. Thank you!
