### ISSUE TITLE
JetWooBuilder Product Grid Fallback Image

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#4656]
By default Product Grid widget shows elementor default image for products without featured images. Can we get an option to set "Fallback Image" for all products without featured images?

Elementor default fallback image is weird.

**Comment by s5t5n** [comment]
You can see how it must work here (on bitrix):
http://wpcleaner.space/catalog/travy_i_ozdorovitelnye_sbory/

**Comment by Floydtm** [comment]
Add this [filter]([url](https://gist.github.com/UraraReika/a59a0ffac70c5a2fa8fbf5fd3f4b44c9#file-jet-woo-builder-widgets-get-woo-placeholder-image-php)) to your main or child theme. Then specify the desired thumbnail id [here](https://prnt.sc/26d5ch7). Thank you!

**Comment by petrovui** [comment]
> Add this filter to your main or child theme. Then specify the desired thumbnail id [here](https://prnt.sc/26d5ch7). Thank you!

Link is dead

**Comment by Floydtm** [comment]
https://gist.github.com/UraraReika/a59a0ffac70c5a2fa8fbf5fd3f4b44c9#file-jet-woo-builder-widgets-get-woo-placeholder-image-php
