### ISSUE TITLE
JetWooBuilder Product Grid amount of products to show (responsive)

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#4657]
There is no option to set amount of products to show on tablet and mobile. On Desktop it set to 21 for 3 columns. But in tablet mode i got 2 columns and it still 21, but i need 10. So this option must be responsive.

**Comment by UraraReika** [comment]
this is not possible in this way. Just duplicate the widget for tablet set 10 products there and use [Responsive settings](https://tppr.me/S6pP8).
