### ISSUE TITLE
Row mode for Metafield radio options and checkbox (jet engine)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4659]
hello

Please add the ability to display metafield (radio and checkbox) in a row. Now, all the options are displayed on top of each other.
https://prnt.sc/26d8nq7

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
