### ISSUE TITLE
Listing query filter user location based

### ISSUE THREAD

**Issue by busymick** [CrocoBlock/suggestions#4664]
Hello,

It would be helpful if you could filter the posts by the location of the visitor. I am currently working on a project where this would be immensely helpful. My client has consultants all over the world. For the advisors, I have created a CPT. There is an archive page where all the advisors are visible. There are also article pages. For the articles I want to show in the sidebar all the advisors working in the country where the visitor is located.

So for example, if someone searches from the Netherlands, he should see all the advisors that are activated for the Netherlands via a meta checkbox.

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
