### ISSUE TITLE
Product result count in crocoblock isn't showing the correct result

### ISSUE THREAD

**Issue by suhail-ibne-habib** [CrocoBlock/suggestions#4665]
**Describe the bug**
The product result count in crocoblock is showing the total products correctly but can't update the correct page number while changing the pagination. 

**To Reproduce**
1. Go to 'product archive page'
2. Click on 'next page from the pagination'
3. See error

**Expected behavior**
when I go to next page it should show like "Showing 2–24 of 115 results" but it shows "Showing 1–12 of 115 results".

**Screenshots**
![image](https://user-images.githubusercontent.com/59106269/149614605-41eca11f-6a80-457d-b1e2-7102e1ac4b7e.png)

**Comment by UraraReika** [comment]
I merged this issue with #2592, which is on the same subject.

**Comment by Kronan** [comment]
still issue
