### ISSUE TITLE
Add possibility to search users by role in search widget

### ISSUE THREAD

**Issue by Allybie** [CrocoBlock/suggestions#4666]
Hi crocoblock,

It would be great to have the possibility to extend the search to users by role in search widget.
Ex: I've created a role called "AGENCY" for the real estate agencies subscribed to my site and i want my users to be able to find them with the search widget.

Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
