### ISSUE TITLE
"load More" feature for product grid widget (Similar to jet engine)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4668]
The jet engine plugin has more loading capability in the listing section, which is great. It's strange that the jet woobuilder has not yet paid attention to it. Even elementor added this feature in its version 3.4.
jet woobuilder is incredibly powerful. I use it for store websites. Of course, many users use this plugin.
Our customers want us to use the "load more" feature, but we can not implement such a feature for them. Because jet woobuilder lacks it.
Dear developers! jet woobuilder really needs this feature. It would be great if you could add "load more" just like a jet engine  . Because it has the following features:
A : Ability to loade more in the form of clicks and infinite.
B : Ability to apply the ID to use the button widget. (for load more)
tnx

**Comment by Lonsdale201** [comment]
https://crocoblock.com/knowledge-base/articles/jetwoobuilder-devtools-products-grid-load-more-addon/

**Comment by Michaelgimii** [comment]
> https://crocoblock.com/knowledge-base/articles/jetwoobuilder-devtools-products-grid-load-more-addon/

Thanks, but why not add this feature to a plugin? Many users subscribe to it. Please consider this

**Comment by UraraReika** [comment]
Right now use this solution. In the future there will be some unified widget.

**Comment by Michaelgimii** [comment]
thank you @UraraReika. one question...
Does this new widget have both Loade more pagination and numeric pagination (like jet smart filters)? Or does it just have load more?

**Comment by UraraReika** [comment]
> thank you @UraraReika. one question... Does this new widget have both Loade more pagination and numeric pagination (like jet smart filters)? Or does it just have load more?

Just load more. Like JetEngine Listing grid.
