### ISSUE TITLE
Sort products in the product archive (product grid widget)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4669]
hello

If we use the product grid widget to display the product archive, we must enable the "Use Current Query" option. But if we enable this option, the possibility of sorting products is eliminated. So we lose this important settings : https://prnt.sc/26envgr
Is it possible to correct this? So if we enable the "Use Current Query" option, the Order by & order settings will remain.
Please add this feature if possible.

thank you

**Comment by UraraReika** [comment]
This isn't possible. Use default WooCommerce [sorting option](https://tppr.me/z0vgF) instead.
