### ISSUE TITLE
Bug in sorting by price / jet woobuilder product grid widget.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4670]
In RTL, price sorting does not work properly and quite the opposite. For example, I set the sort by price and in ascending order, Naturally, the price of products should start from the right (RTL) and from the low price. But this is not the case and quite the opposite happens. (Such as LTR)
**This bug only exists in price sorting. Date and other things work fine.**

thank you

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
thank you
