### ISSUE TITLE
JetwooBuilder: Pre Order system 

### ISSUE THREAD

**Issue by logivity** [CrocoBlock/suggestions#4674]
Widget to allow preorder system instead of buy now button would be a very powerful feature. 

Requirements.

1. Must be able to collect the payments in future as per stripe connection.
2. Must be able to split payments.
3. Must be able to set minimum number of preorder before the preorder campaign is considered success and customers are charged.

**Comment by mehdimoradi1500** [comment]
I was looking for it too
+1

**Comment by UraraReika** [comment]
Unfortunately we do not plan to introduce such functionality into our plugin. But you can use one of third party plugin solution like [this](https://wordpress.org/plugins/pre-orders-for-woocommerce/). Or from official site like [this](https://woocommerce.com/products/woocommerce-pre-orders/) or [this](https://yithemes.com/themes/plugins/yith-woocommerce-pre-order/). Our plugin has all the compatibility functionalities and everything should be okey.

Feel free to [contact](https://support.crocoblock.com/support/home/) our support team.

Thank you!
