### ISSUE TITLE
Layout option for META boxes

### ISSUE THREAD

**Issue by SchneiderSam** [CrocoBlock/suggestions#4675]
**Please, describe the feature request, making it clear to understand.**

It would be nice to have a way to change the layout for the meta boxes. Currently they are displayed vertically, a horizontal view would be quite handy. This makes sense primarily for radio buttons and checkboxes. ACF has that and that is very helpful especially with many options. Depending on how many options you have, it takes up a lot of space.

**Add an example of where this feature is already implemented. **

https://www.advancedcustomfields.com/resources/checkbox/

Checkout the "Layout" part.

**Comment by kaskad88** [comment]
Added for the next version ( v2.11.7 ).
Thanks for your report!
