### ISSUE TITLE
If the products are not available, the color of their image will be black and white (jet woobuilder)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4676]
This feature is used in some store websites. If the product is not available, the color of the product image will change to the desired color. (Often black and white). This feature would be great for a product grid.

![20220118_124003](https://user-images.githubusercontent.com/88034902/149907903-ac0dd895-5c44-435f-9a0a-22b64f25e5a2.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
