### ISSUE TITLE
To add products per page section

### ISSUE THREAD

**Issue by isaacwillz** [CrocoBlock/suggestions#4680]
It would be awesome to add a function to choose products per page on woocommerce loop next to sort dropdown

![image](https://user-images.githubusercontent.com/28073294/150115569-c8e5b7e0-0497-4206-b07a-96ee12d3a2b3.png)

**Comment by Lonsdale201** [comment]
+1

**Comment by isaacwillz** [comment]
Hello @UraraReika, are we gonna see this feature sometime soon?

Best regards

**Comment by UraraReika** [comment]
I merged this issue with [#4218](https://github.com/Crocoblock/suggestions/issues/4218), which is on the same subject so we could deal with it more efficiently.
