### ISSUE TITLE
Query Builder:  Add "GET, URL Query Variable" for Listing Grids

### ISSUE THREAD

**Issue by ClearianDev** [CrocoBlock/suggestions#4686]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by ClearianDev** [comment]
I don't think I missed it, but adding the URL Query Variable option to Query Builder would be very helpful.

<strong>People, if you're not using Query Builder for pulling Listing Grids you MUST check it out.  It's awesome.</strong>  If you've ever been frustrated trying to configure queries for pulling listing grids, Query Builder is for you!  Best, best, best feature - after the depth of query options - is the instant query PREVIEW QUERY result.  You can see exactly what is coming back from SQL.  I can't tell you what a great tool this is.  Great job Crocofolks!

**Comment by tjwilkinson** [comment]
YES Please.  

Need to pass a URL variable

[www.test.com/t.html?a=1&b=3&c=m2-m3-m4-m5](http://www.test.com/t.html?a=1]

I would like to put an url parameter "a". The on the page I want to call a GEt request to
GET [https:/testAPI.com/api/v2/OData/{dataset_id}/{resource}?access_token={server_token}&a=1234567890]
I have set up the API and the query. But I would like to pass the "a" into the query.

would love to see "get url parameter" here

<img width="1358" alt="Screen Shot 2022-02-09 at 6 07 53 AM" src="https://user-images.githubusercontent.com/63081898/153223743-edd57a8d-fa5e-4e21-85e7-4d210bc1d649.png">


<img width="616" alt="Screen Shot 2022-02-09 at 6 08 09 AM" src="https://user-images.githubusercontent.com/63081898/153223778-9c251ea6-79e3-4d2a-84be-3a4043dd742a.png">

**Comment by ihslimn** [comment]
Query Variable macro is exactly what you need https://prnt.sc/57YeYf7GdhGd (it will try to get WP query variable before getting a GET parameter, although in your case it must work just fine, as there is no "a" WP query variable)
