### ISSUE TITLE
JetAppointment

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#4688]
Feature-request to show the available data via a dropdown.

After choosing the date, you can then choose a time slot.
example:
http://prntscr.com/26g7wdb

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
