### ISSUE TITLE
Add a "Box List" filter/option to the smartfilter options

### ISSUE THREAD

**Issue by ColinHiom** [CrocoBlock/suggestions#4689]
What I mean "Box Lists" is a restyled variation of a checkbox that runs inline and can look like small tab/buttons but in other implementations I've seen they are html checkboxes with the actual box removed for the UI.

Why is this useful?

Sometimes it's nice to have a short list of filter options shown to users as tab/buttons instead of a long vertical list checkboxes. Here's an example (or two)

![image](https://user-images.githubusercontent.com/72506215/150326569-2c07b21e-e27c-427f-afdd-50f18034d241.png)

![image](https://user-images.githubusercontent.com/72506215/150326661-bacda541-4311-4781-823f-a1afd313083f.png)

Implementation:
These could quite easily be added to the existing checkbox 'additional settings' options and would need to include:
- Show Checkbox (on/off switch) - similar to the existing 'Dropdown Enabled yes/no
- Render Inline on/off)
Or perhaps that should be a single option: 'Render as Box Lists yes/no' and combine into a single new on-off option - or perhaps this should be entirely new smartfilter type: "Box Lists" with other options specific to this idea.

This all assumes there's isn't a existing smartfilter that has this option already that I haven't seen. The idea is functionally similar to the examples you have in the current 'visual filter widget' where a 'box list' filter could do the same but without using images. So for reference the effect (and usecase scenario) would be the same as the following (but without the logotypes):

![image](https://user-images.githubusercontent.com/72506215/150327635-ef2a8155-c09e-4e61-87ec-fde043e0a183.png)

Apologies in advance if the option does exist somewhere - but I couldn't find it and nor could the support team member I just spoke to.

Many thanks.

X

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
