### ISSUE TITLE
JetWooBuilder & WooCommerce Advanced Quantity (sell by GRAMMS)

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#4691]
I got WooCommerce Advanced Quantity plugin installed (https://codecanyon.net/item/woocommerce-advanced-quantity/11861326).

So by default elementor Add-To-Cart button of "Products" element link looks like "https://your-site.com/shop/product-category/product/?add-to-cart=9999&quantity=0.05" if i want to sell some of products or whole product categories by grams.

As you can see in link, the quantity by default will be 0.05 cause the 1 = 1 kg if it set so. In Elementor Products (simple products grid) it works just like that. But in JetWooBuilder "Products Grid" element it only displays right, but if i'll hit add-to-cart button (0,05) it will add 1. And it will add to cart 0,05 if i hit up and down arrows of quantity element.

![Untitled-1](https://user-images.githubusercontent.com/29761044/150383707-f228984a-22ca-4de0-af79-fa0a9c39173e.png)

https://user-images.githubusercontent.com/29761044/150384215-43fbcb44-f1d5-4c81-9fbc-7ad44dd19c7c.mp4

So how can i edit default quantity function of add-to-cart button of JetWooBuilder Products Grid element for custom product categories which default quantity is set to 0.05 same like at video. I want add-to-cart button of this element default value 0,05 for custom category.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
