### ISSUE TITLE
Make the bookmarks icon active after adding

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4694]
There are products https://elegatto.store/product-category/vse-braslety/kozhanye-braslety / everything is displayed via the Products Grid widget
if you hover over any product, the bookmarks icon appears at the top right of the product (photo 1) if you add the product to bookmarks, everything will go normally! the product will be added to bookmarks and its background will change! (photo2)

How to make it so that after adding bookmarks... was the icon always visible ?
that is, those products that are not in bookmarks should also work (displayed on hover) and those products that are added to bookmarks (should be visible)
![10](https://user-images.githubusercontent.com/47380983/150519853-62765ea2-2774-4a85-b1c9-0afef4854aaa.jpg)
![11](https://user-images.githubusercontent.com/47380983/150519856-ed10a06f-2c68-4f7f-824a-29d4837d4a1c.jpg)

**Comment by Floydtm** [comment]
I understand that this is important to you, but right now we will not be adding this to the plugin. You can use custom CSS to resolve the request
