### ISSUE TITLE
Jet compare & wishlist compatibility with product grid widget (jet woobuilder)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4697]
Greater compatibility of these two plugins is great. So that we can display the interests as a carousel in the product grid widget.
If we enable jet compare & wishlist, a new query would be displayed in the product grid widget queries section. If we select it, the products of interest will be displayed. this is great.

**Comment by 79ho3ein** [comment]
+1

**Comment by Michaelgimii** [comment]
hi @UraraReika , I had a question about this update...
If we select the favourites query, can we use the jet smart filters pagination widget for this widget (product grid)? Will there be complete compatibility?

**Comment by UraraReika** [comment]
> hi @UraraReika , I had a question about this update... If we select the favourites query, can we use the jet smart filters pagination widget for this widget (product grid)? Will there be complete compatibility?

There will be compatibility. But in this case we cannot interact with the wishlist, only view it.

**Comment by Michaelgimii** [comment]
> > hi @UraraReika , I had a question about this update... If we select the favourites query, can we use the jet smart filters pagination widget for this widget (product grid)? Will there be complete compatibility?
> 
> There will be compatibility. But in this case we cannot interact with the wishlist, only view it.

So if we select the favorites query in the product grid widget, the jet smart filters pagination won't work for it?

**Comment by UraraReika** [comment]
It will work

**Comment by Michaelgimii** [comment]
hi @UraraReika , In the new version, I enable the favorites query, but it does not work and displays all products.
I have not added any products to the wishlist, but it displays all products.
