### ISSUE TITLE
Percentage discount in single sale badge

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#47]
It is necessary to add a withdrawal of discounts as a percentage of the initial price. Also add the option to change the text, now the default is "sale"

**Comment by stasonua0** [comment]
+1

**Comment by SashkoWooTeam** [comment]
Added %percentage_sale% and %numeric_sale% macros for sale badge text.

**Comment by arekuusa** [comment]
Another problem is due to variable item.  http://prntscr.com/t9tneo
I need one discount
I think that it is possible maximum or minimum discount
For example, %percentage_sale_max% and %percentage_sale_min%

**Comment by UraraReika** [comment]
Hello @arekuusa!
List of macros presented in our plugin is basic and satisfy most users needs. Functionality that you need is more rare, in this case we  provide filter 
```
apply_filters( 'jet-woo-builder/macros/macros-list', array(
	'percentage_sale' => array( $this, 'get_percentage_sale' ),
	'numeric_sale'    => array( $this, 'get_numeric_sale' ),
) );	
``` 
which can expand our list.
Here is example: https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce.

**Comment by AOD28** [comment]
Hi, I need to be able to show somethinkg like %percentage_sale_min% for products with variations.
To date if we apply a sale on a variation only, we have in front 2 percentages showed : - the sale% - 0%

Where do we have to insert the code [from here](https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce) , and do we have to insert 
 `apply_filters( 'jet-woo-builder/macros/macros-list', array(
	'percentage_sale' => array( $this, 'get_percentage_sale' ),
	'numeric_sale'    => array( $this, 'get_numeric_sale' ),
) );	`
and if so... in wich  file ?

PHP is really not a part of my job, but I need to find a solution to be able to use sales for our products with variations.

Thanks in advance for the help to understanding.

**Comment by UraraReika** [comment]
> Hi, I need to be able to show somethinkg like %percentage_sale_min% for products with variations. To date if we apply a sale on a variation only, we have in front 2 percentages showed : - the sale% - 0%
> 
> Where do we have to insert the code [from here](https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce) , and do we have to insert `apply_filters( 'jet-woo-builder/macros/macros-list', array( 'percentage_sale' => array( $this, 'get_percentage_sale' ), 'numeric_sale' => array( $this, 'get_numeric_sale' ), ) ); ` and if so... in wich file ?
> 
> PHP is really not a part of my job, but I need to find a solution to be able to use sales for our products with variations.
> 
> Thanks in advance for the help to understanding.

Hello @AOD28 !

Use this [snippet](https://gist.github.com/UraraReika/5e944f13d166ec9457698922272197ce).

**Comment by johnny-mne** [comment]
@UraraReika I'm using the above mentioned snippet to display sale percentage. Is there a way to use discount percent as a sorting filter?
