### ISSUE TITLE
Listing grid with odd and even templates

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#4702]
Hello to all my favorite plugin developers. I would like to request a feature that will boost the functinality of the listing grid widget.
My though is that we can create 2 different listing template (one with the photo on the left and another with the photo on the right for example) and then in the listing grid we can select these 2 templates so in the frontend we will have a more interesting layout, better than showing the listings with the exact same style. This feature is already exists in the Ele Custom Skin Pro plugin (https://dudaster.com/alternating-templates/) but WE DON'T WANT TO USE OTHER PLUGINS EXCEPT CROCOBLOCK.
Thank you for your time to read my request.

**Comment by Floydtm** [comment]
Check this tutorial https://crocoblock.com/knowledge-base/articles/how-to-use-the-alternative-listing-template-functionality-in-listing-grid/

**Comment by TheBigBanik** [comment]
Oh, it was already implemented, strange they didn't tell me that on the chat. Thank you very much. This would be awesome.
