### ISSUE TITLE
Incompatibility Variations as Single Products for WooCommerce

### ISSUE THREAD

**Issue by xC4M** [CrocoBlock/suggestions#4703]
Recently, I bought the plugin Variations as Single Products for WooCommerce to display my variations' products as a single in my shop page, but there's no way to display it while JetWooBuilder plugin is activated. Could you please try to set compatibility of those two plugins?

**Comment by UraraReika** [comment]
Please [contact](https://support.crocoblock.com/support/home/) our support team. Thank you!
