### ISSUE TITLE
Price update after price selection / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4706]
hello

On the single product page, a new price appears in addition to the existing price if we select the variables. Therefore, two prices are displayed. This is not really good and it completely destroys the user interface. Simultaneous display of prices is also confusing for users. Especially if there is a selle price. https://prnt.sc/26i3vct
It can be said that there is no website that uses this method.

**proposed solution :** 

It is better to update the first price automatically after selecting the variable. Therefore, there is no need to display the second price.
Like the website below. Everything happens great : 

https://user-images.githubusercontent.com/77163248/150688123-33751245-e138-442e-874e-b3288350955e.mp4

Please keep this in mind. it's too important.

thank you

**Comment by UraraReika** [comment]
This is default WooCommerce functionality. So if you have some suggestions then go straight to them. This functionality gives you opportunity to set separate price for variation different form basic depending on attributes. So you can check the exact price of your selection.

**Comment by 79ho3ein** [comment]
thank you @UraraReika
