### ISSUE TITLE
Speed ​​drop in jet woobuilder 

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4708]
Plates made with jet woobuilders do not have the right speed. I do not know the reason, you certainly know better. Perhaps the most important reason is the existence of old and unused code in this plugin. That's right- this is not a big deal. But it can be much more efficient than it is now.
I suggest jet woobuilder release an update just to optimize its code. No new features. Only optimization. This is very important, even elementor is constantly optimizing itself.

**Comment by UraraReika** [comment]
I merged this issue with #2282, which is on the same subject so we could deal with it more efficiently.
