### ISSUE TITLE
JetWooBuilder: Add a quickview button on product grid (jetwoobuilder) same as: wishlist, compare (jetcomparewishlist).

### ISSUE THREAD

**Issue by ki96hn** [Crocoblock/suggestions#471]

**Comment by Floydtm** [comment]
@ki96hn, Hi! This option is available in the plugin settings http://prntscr.com/oy01f0 Check for Updates

**Comment by ki96hn** [comment]
I updated Jet WooBuilder to version 1.4.1, but also has not this option! 
http://prntscr.com/oy1d1u
http://prntscr.com/oy1cmn

**Comment by Floydtm** [comment]
@ki96hn, I'm sorry. For quick viewing, you need the jet popups plugin. The option will be available when you activate this plugin. https://crocoblock.com/knowledge-base/articles/how-to-create-a-product-quick-view-with-jetwoobuilder-and-jetpopup/
