### ISSUE TITLE
JetEngine: Dynamic Visibility for menu items in the backend

### ISSUE THREAD

**Issue by 05edgarBlw** [CrocoBlock/suggestions#4711]
It would be great if we have the ability to do so, because thats the only part of the page we can't customize with croco visibility tools.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
You can use this [plugin](https://wordpress.org/plugins/if-menu/)
