### ISSUE TITLE
Synchronize calendar with Nextcloud

### ISSUE THREAD

**Issue by moritz76** [CrocoBlock/suggestions#4713]
Hello,

it would be great if the PlugIn "JetAppointment" could synchronize the time slots into the Nextcloud calendar (CalDAV).

Also then already booked slots should be synchronized into the calendar.

I know this works with the Google calendar but that is not an option for privacy reasons.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
