### ISSUE TITLE
Limit selected Checkboxes in a form

### ISSUE THREAD

**Issue by leifrosenkranz** [CrocoBlock/suggestions#4717]
It would be amazing to limit the selected checkboxes of a checkbox field in a form. For example having 20 checkboxes to choose from but your customer should only be able to choose three. This would be very helpful because people need to prioritize.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
