### ISSUE TITLE
jet compare & wishlist Plugin does not support the "Custom Not Found Message" feature. (Like Jet woobuilder)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4719]
hello

In previous versions of jet woobuilder this feature was added which was great (#4071). Now in Jet woobuilder we can fully customize Not Found Message with shortcode.
Unfortunately, this feature is not supported by the jet compare & wishlist plugin. It would be great if you could add this feature to this plugin as well. If the user does not have the product in their favorites list, they will get a custom message.

thank you

**Comment by 79ho3ein** [comment]
hello @UraraReika , thank you for your attention.

Please check this if possible. #4386

**Comment by UraraReika** [comment]
This functionality will be available with next release. You can use [this](https://gist.github.com/UraraReika/e9f09e16c678e78a6f9bfc85fc0d765a) to handle empty message output for different widgets.

**Comment by 79ho3ein** [comment]
thank you
