### ISSUE TITLE
JetMenu - Add Accordion Menu widget support

### ISSUE THREAD

**Issue by realstephenzhao** [Crocoblock/suggestions#472]
Hello, I hope Accordion Menu widget can be added in.

![See Accordion Menu effect Screenshot](https://imgur.com/erRrssi.jpg)

I don't know why there is no Accordion Menu for Elementor till now since there are already so many Nav Menu, Mega Menu and even Accordion widgets in many plugins for Elementor.

Now I show an [Accordion Menu plugin website](https://wpaccordionmenu.com/) for reference, it looks good but not made for Elementor.

Please consider this proposal, thanks.

**Comment by AlfaBlue** [comment]
I've been looking all over the internet for this feature built into a plugin working with ELementor. It doesn't exist apparently. This would be an excellent addition to the JetMenu plugin.

**Comment by shinTM** [comment]
you can make this layer with this widget https://crocoblock.com/widgets/classic-accordion/

**Comment by realstephenzhao** [comment]
> 
> 
> you can make this layer with this widget https://crocoblock.com/widgets/classic-accordion/

But unfortunately it's not the same thing, not even close.

**Comment by serg-pervushin** [comment]
I support @realstephenzhao, the current JetTabs Accordion widget has nothing to do with the menu at all. Yes, can reproduce it, but might as well abandon JetMenu altogether and display all the items with links. Please open the branch, a very necessary thing in the vertical menu.

**Comment by wearenv-digital** [comment]
Can this be made by including the jet tabs widget into the mega menu content template?

**Comment by p0loloop** [comment]
please make this a priority. we are still waiting for this for a long time now. :D
