### ISSUE TITLE
JetWooBuilder nested category layout

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#4721]
Hello,

In JetWooBuilder It would be usefull if subcategories with products could be displayed on product category pages. Look in the image below.
This can be used when we create restaurant menus for ordering food.

**Comment by mary151** [comment]
![woocommerce-nested-category-layout-after](https://user-images.githubusercontent.com/56391303/150996106-f36e7e64-19dc-4556-bf98-87a134e1ccf7.png)
![menu_example](https://user-images.githubusercontent.com/56391303/150997009-97e38bd4-7c7f-4d40-b4c6-716e09f60628.jpg)

**Comment by UraraReika** [comment]
In this case you better use separate templates for each category you need.

**Comment by mary151** [comment]
Hello, @UraraReika , 

I don't know how exactly to put **multiple subcategories with products** in one category template. Because with product loop widget is not possible. It's not possible, because I cannot select custom queries to output in one page. 
 
I don't know why you closed this issue, because it is not solved.

**Comment by UraraReika** [comment]
If you want to use Archive Product Template then you better use products shortcodes or Elementor Products widgets. Or use Products Grid or List widgets where you can specify query. Although you can use JetEngine Listing Grid.
