### ISSUE TITLE
JetWooBuilder, Listing Gird and popup with product quick view.

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#4722]
Hello,

When we use listing grid widget inside JetWooBuilder shop template or in **any other page**, product quick view cannot load data for single product. Look at the screenshot below.  If you want I can give you full acess to website backend to test it and to see my settings.

**Comment by mary151** [comment]
**The first image is with standart JetWooBuilder template with archive template inside. It loads product quick view correctly. The second is the same JetWooBuilder template, but with Listing grid inside. Popup doesn't load single product template.** 

![1screenshot-menu club35 bg-2022 01 25-15_37_25](https://user-images.githubusercontent.com/56391303/151001595-2a8f648f-2b12-4e20-a680-48a6b2aa4c7a.png)
![screenshot-menu club35 bg-2022 01 25-15_36_33](https://user-images.githubusercontent.com/56391303/151001610-0a2b4473-97a6-4583-ad92-5259ceb21e71.png)

**Comment by UraraReika** [comment]
Hello @mary151 !

Quick view popup for JetEngine Listing Grid and JetWooBuilder Widgets works different. 

In first case you need set popup like [this](https://tppr.me/HJ7Bq) and inside this popup you build your template with the help of JetEngine Dynamic widgets of with the help of dynamic tags functionality.

From the other side in JetWooBuilder you set up template like [this](https://tppr.me/U6oIK) and leave this popup empty because inside content formed by JetWooBuilder single template that you attach. 

For more info and help please contact our [support team](https://support.crocoblock.com/support/home/).

**Comment by mary151** [comment]
Hello @UraraReika ,

I know all of that, but with dynamic widgets in popup I cannot use Single Add to cart widget - it cannot be displayed in popup. I already talked with crocoblock support and they also couldn't do it. So in this way listings cannot be always used with Products content type, because there are limitations. I need to use listing grid, because there are some limitations in JetWooBuilder- like I cannot use queries to output different categories in one page.

**Comment by UraraReika** [comment]
You can use this solution:
1 - Drag and drop Dynamic field widget to your template.
2 - Set this options up like [this](https://tppr.me/VxMGC).
3 - Add this to your `function.php` in child theme.

```
add_filter( 'jet-engine/listings/allowed-callbacks', '__your_prefix_add_to_cart' );

function __your_prefix_add_to_cart( $callbacks ) {

	$callbacks['__your_prefix_add_to_cart_transform'] = __( 'Add to Cart', 'jet-engine' );

	return $callbacks;

}

function __your_prefix_add_to_cart_transform( $value ) {

	global $product;

	$product = wc_get_product( $value );

	if ( $product ) {
		$product_type = $product->get_type();

		if ( 'simple' !== $product->get_type() ) {
			return '';
		}

		$class        = implode( ' ', array_filter( [
			'product_type_' . $product_type,
			$product->is_purchasable() && $product->is_in_stock() ? 'add_to_cart_button' : '',
			$product->supports( 'ajax_add_to_cart' ) ? 'ajax_add_to_cart' : '',
		] ) );

		return sprintf(
			'<a href="%s" class="%s" data-quantity="1" data-product_id="%s" rel="nofollow"> Add to Cart </a>',
			$product->add_to_cart_url(),
			$class,
			$product->get_id()
		);
	} elseif ( current_user_can( 'manage_options' ) ) {
		return __( 'Please set a valid option', 'jet-engine' );
	}

}
```
4 - Save and refresh your template.
5 - Turn this [option](https://tppr.me/t5Zv6) on and select `Add to Cart` callback. Save your template.
