### ISSUE TITLE
jet woobuilder is not compatible with elementor flex box.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4725]
If you know, elementor will unveil its flex box soon. It is currently in the DEV version. But with the research I did, if we put the product grid widget in the container, it will have a problem. Of course, if the carousel option is active.
Not bad if you consider these problems before the official release of elementor flex box. Of course, all JET plugins need to be compatible with the new elementor feature.

**Comment by mbaierl** [comment]
According to the support they will only make it compatible when Elementor officially releases the feature. Since containers are now in Alpha this will take a while :-(
