### ISSUE TITLE
Jetsmartfilters - Dropdown option.

### ISSUE THREAD

**Issue by josiase95** [CrocoBlock/suggestions#4730]
Hi CB,

It would be really nice to able to add a dropdown to the range filter - like you can do to alot of the other filters aswell :) 

Hope you'll consider this in the next update for it. 

Best regards

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
