### ISSUE TITLE
Static Review - Single Item Average Rating

### ISSUE THREAD

**Issue by Radzio1615** [CrocoBlock/suggestions#4732]
I use JetReviews 2.2.4. How to in "Static Review" widget insert to "Field Value" a dynamic average rating value of Item? I don't see any dynamic tag for that.

![jetreviews](https://user-images.githubusercontent.com/40895581/151219662-85b35528-a6ac-48f2-85c6-9925a6bf4cf4.png)

**Comment by Medienor** [comment]
Hey - The funnt thing is that the review form is not connect to the review static form - Review Static is for manual reviews you make in the backend editor - Crocoblock should make it sync with customer reviews instead

**Comment by Medienor** [comment]
1+ btw - we need this!

**Comment by Floydtm** [comment]
We do not plan to develop this widget. In the future, we plan to develop a review listing widget
