### ISSUE TITLE
Bug in jet woobuilder with WordPress update and hello elementor theme.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4735]
hello

Yesterday I updated WordPress and hello elementor template at the same time. After the update, the products image on the cart page disappeared. Of course only on tablets and mobiles.
After that, I restored WordPress to the previous version but the problem was not solved. Most likely, there is an interference with the new version of the hello elementor theme. Please consider both.

Thank you

**Comment by UraraReika** [comment]
Please before writing here contact our support team.

**Comment by 79ho3ein** [comment]
Ok, thank you
