### ISSUE TITLE
Show glossary label in search result

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4736]
Hello,

I use JetMenu to add the Ajax Search to the site, and in Custom Fields, I'm displaying one of the custom fields that are using a Glossary.

I want to display the Label of the meta field in the search result, instead of the value/key.

In templates, we have an option to choose to show the label from the glossary, but in the JetMenu we don't have such an option and as a result, it is only showing the value/key of the field's options, which in our case is completely useless because the Labels of the options are visual like this:
★☆☆☆☆ Very poor
★★☆☆☆ poor
★★★☆☆ average
★★★★☆ good
★★★★★ excellent

but the labels/keys are just 1 to 5 numbers. and we want to show those stars in the search result area in each item, and not just a simple number.

Please make this possible, as you've done this already in JetEngine.

Thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
