### ISSUE TITLE
jet woobuilder outline

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4737]
In hello elementor theme, there is a problem displaying the outline in the buttons. This problem is often found in crocoblock plugins. For example, if we click the Add to Cart button, the border will be black.
I entered the following code in the elementor theme builder element > custom  css, this problem was fixed on all websites except 3 parts.

*{
outline: none;
}

Although I applied this code to the whole website, they did not receive the 3 parts of the code.
1- Cart Update Button.
2- apply coupon Button in the cart page.
3- apply coupon Button in the chekout page.

Only the above 3 parts did not receive the code. While after applying the code, all outlines were deleted. outline in jet smart, jet search and even jet woobuilder plugin. But in jet woobuilder, only the above 3 did not receive the code !

**Comment by UraraReika** [comment]
I merged this issue with #3057, which is on the same subject so we could deal with it more efficiently.
