### ISSUE TITLE
JetSmartFilters - JetEngine - Add GEO Search functionality - using Google Maps API

### ISSUE THREAD

**Issue by tnagdigital** [Crocoblock/suggestions#474]
I have searched through all existing feature requests and not seen any mention of the following request.

JetEngine: The ability to have an address field - connected to Google MAPS (or alternate provider) API.
Use case: Enter an address that then, via MAP API, retrieve GEO coordinates.

JetSmartFilters (or JetSearch): Ability to enter an address that is used to search a Custom Post Type by proximity  - 'x' Miles or Kilometers from Search Address and Post containing GEO fields 
(address field)

Regards,
Andrew

**Comment by adverman** [comment]
I am very interested in this functionality. It would be really **important** to me to be able to **sort** posts based on proximity to the user's current location or to a specific location.

**Comment by travelgu** [comment]
+1 on this. Hope proximity searches are coming soon

**Comment by Dennisvb** [comment]
Hope this will be implemented soon, because this would be a great feature!

**Comment by baf139** [comment]
yes this would be great. Then you could basically recreate https://wpgeodirectory.com/

**Comment by Scoots78** [comment]
+1 This is needed to make the map listings far more usable

**Comment by evolvenl** [comment]
+1, really need geolocation.

**Comment by tylertyza** [comment]
+1

**Comment by hassanaleem0** [comment]
hope there is some progress on this :P, how can you have a listing website without this in 2021

**Comment by websightsrus** [comment]
+1

**Comment by developer784** [comment]
+1, need this ASAP...

**Comment by Topicimes** [comment]
+1

**Comment by realspiner** [comment]
When is this being picked up? It’s a much needed feature to make the map listing a viable product for professional websites.

**Comment by yepyeh** [comment]
This would be amazing

**Comment by Kytab** [comment]
+1

**Comment by darah-aldridge** [comment]
+1

**Comment by blogbytes** [comment]
2023 guys. Please integrate this

**Comment by nphough** [comment]
+1
I worry about this all day every day.  We need this feature.  My website is kind of stupid without it and the hassle of switching everything to toolset to implement it is looming over my head. Crocoblock, please please please add this feature.

**Comment by EnvioMaik** [comment]
+1000 this is like the only feature that absolutely necessary for map listings, how is it not implemented yet? After almost 4 years...

**Comment by levin-roski** [comment]
+1

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
