### ISSUE TITLE
Ajax Search - Additional Results Area customization

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4740]
A good feature for the Results Area in the Ajax Search widget would be an add to cart button with the quantity input field.
Having the add-to-cart with the quantity field in the search result area next to each item can boost sales, especially in B2B stores. This not only can be used as a professional search bar but also can be used in a Quick Order page.

**Comment by 79ho3ein** [comment]
+1

**Comment by hamed-azimi** [comment]
Definitely a must, for B2B stores. Hope to see it soon.

**Comment by 79ho3ein** [comment]
This is a great feature. But it can be used when quantity input has a good user interface. Like this : https://prnt.sc/26kdsxi
Otherwise, adding it will be useless.

**Comment by Crocoblock** [comment]
was added and released in 3.4.0
