### ISSUE TITLE
Query builder and WC variable products compatibility.

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#4741]
Hi my dear developers. After chatting with your support team I get informed that the Query Builder cannot be used to filter variable products, specificly when we have variable sale prices. If we create variable products and want to filter them according to the sale price, both Listing grid and Product grid cannot find the sale price from variable products.

**Comment by UraraReika** [comment]
Hello @TheBigBanik !

You need to use WC Product Query query type like [this](https://tppr.me/o880x).

**Comment by TheBigBanik** [comment]
Hi, thank you for the reply. But this has already been tested with the Crocoblock Team and unfortunately it doesn't work. It looks like it cannot finid the variable products.

**Comment by UraraReika** [comment]
Variable products [list](https://tppr.me/JRNWd).

Create Query with default parameters, [screenshot](https://tppr.me/jFGuB). Apply this query to listing grid with [this](https://tppr.me/xPGpd) result. If we set product type [option](https://tppr.me/NxaXA) you can see product count is changed and the frontend [result](https://tppr.me/cLPic) as well.

**Comment by TheBigBanik** [comment]
Well, I think my initial request was wrong, I am really sorry for the inconvinience. I will edit the original post. The 2 issues I have is that Query builder cannot find the variable sale price, it understands only the original price. So in my case, I just wanted to filter all products (simple and variable) that have a sale price. The listing grid cannot understand that query as the product grid also. So we cannot create a query based on the sale price for variable products. As for the listing grid, the Crocoblock team told me that thae Query builder (for products) is focused on the Products grid and not the Listing grid. In that case, we are restricted to create queries that will be applied to the Products grid only.

**Comment by UraraReika** [comment]
Use this small snippet:

```
add_filter( 'jet-engine/listings/macros-list', '__your_prefix_get_wc_products_query_macros' );

function __your_prefix_get_wc_products_query_macros( $list ) {

	$list['wc_sale_products'] = [
		'label' => __( 'WC Sale Products', 'jet-engine' ),
		'cb'    => '__your_prefix_get_products_on_sale',
	];

	return $list;

}

function __your_prefix_get_products_on_sale( $field_value = null ) {
	return array_merge( [ 0 ], wc_get_product_ids_on_sale() );
}
```

After you paste it into your child theme functions.php in Query Builder you will be able to see [this macros](https://tppr.me/IddSq). Use it in [include options](https://tppr.me/qsV9t) in general tab.

**Comment by TheBigBanik** [comment]
Wow, thanks UraraReika, I will try that asap. I believe it will work. Thank you verty much, I will keep you informed.
