### ISSUE TITLE
Ability to customize the price unit in the jet search plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4746]
hello

Please add the possibility of customizing the price unit. This customization is just about resizing it. no more.
This feature is already available in the Jet woobuilder plugin. It would be great if it was added to jet search. Please let me know if you need a picture of this feature in jet woobuilder.

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
