### ISSUE TITLE
new mode for display Product rating  / jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4747]
hello

Great if you add a new mode to the customer rating section. Numerical mode : https://prnt.sc/26kehk8
Product rating is available on both the single product page and the product grid widget. The new mode can be great.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein. Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But  we've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.
