### ISSUE TITLE
Scroll Navigation Widget - Hide On Mobile

### ISSUE THREAD

**Issue by Tommentron** [CrocoBlock/suggestions#4750]
Hello everyone,

I'd like to suggest an update to the "Scroll Navigation Widget". It would be great if the widget could be "turned off" (made invisible) on the phone view. There is an option to "Hide On Mobile" but it only disables the text but not the dots. It's a great widget but when using on the phone where the screen is much smaller, it seems rather annoying/messy. I noticed there is this option available with other widgets so it would be great if it was included in this one too. Thank you :)

Best
Tommen

**Comment by Floydtm** [comment]
Use this [module](https://crocoblock.com/knowledge-base/articles/jetengine-dynamic-visibility-module-options-overview/?utm_campaign=need-help&utm_source=jetengine-modules&utm_medium=dynamic-visibility) to solve your problem
