### ISSUE TITLE
Date meta field display

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4752]
I have a feature request regarding the Date meta field display on the backend. 
I want to place it for my users to fill in their birthdate but they can't choose the year or the month. They must click month by month to find the needed year and it is absolutely not acceptable for a real UX.

Can you change the component in your library software, please?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
