### ISSUE TITLE
BUG in jet compare & wishlist

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4757]
hello

The Add to Favorites button does not display the bottom border first : https://prnt.sc/26kxy0e
But after hover is displayed.
**This bug only exists in the Chrome desktop browser.**

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Use [this](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) template for bug report. Thank you.

**Comment by 79ho3ein** [comment]
hi @UraraReika. Rewrite for this issue? Or for next time?

**Comment by UraraReika** [comment]
We have checked your request. We use  Chrome desktop browser with Hello Elementor theme on single product template. Everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
thank you @UraraReika. I forgot to say one thing ...
True in the elementor editor, but not so outside the editor. In any case, thank you
