### ISSUE TITLE
JetEngine Dynamic Visibility New Condition to check: Post Status

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#4758]
I'm developing an admin panel where I need to check the Post Status, to display the correct button in the listing grid (Publish or Pending), these buttons open JetPopup with the right form just to Click Yes or No and it works very well.

I tried to make the logical condition to show or hide the buttons using the post status condition in several ways, I did the manual configuration using "post_status" with the value "publish" or "pending" but it doesn't work, besides the listing grid does not display products correctly, it crashes when loading new items when scrolling.
![image](https://user-images.githubusercontent.com/6773491/151628975-19bda5a4-3965-427b-9312-95e13d9b281b.png)

I used the query builder to check also to check the published products, but there is no way to apply the rule to hide the Publish button if the current Status is "publish".

What I thought and I suggest after several attempts is that it could have a new condition "Post Status is" so we inform the value we would like, for example: publish, pending, draft.....
![image](https://user-images.githubusercontent.com/6773491/151629111-6fb719c8-2d56-463d-b94c-7fd16184d73d.png)

Or also having the possibility to select through a multiselect the options that we would like, as there is in the configuration of the listing grid
![image](https://user-images.githubusercontent.com/6773491/151629207-296156b5-9dc8-49af-8220-bfbf9a1b6942.png)

Thanks in advance, if you have any other solution, I'd really like to know, thanks!

**Comment by rtpHarry** [comment]
Good news! This is already available as an extra plugin by one of the Crocoblock developers:

https://github.com/MjHead/jet-engine-custom-visibility-conditions
