### ISSUE TITLE
Add PDF generator plugin for Jet woo builder

### ISSUE THREAD

**Issue by DavidWooF** [Crocoblock/suggestions#476]
In support ticket (support/tickets/1518) we came to the conclusion that we need to create a plugin for the Jet woo builder so we can add ability for our costumers to generate and download product information in PDF, generate and print PDF from the browser, generate and email PDF and maybe also share button.

A similar plugin exists but doesn't support woocommerce nor Jet plugins.
https://wordpress.org/plugins/pdf-generator-addon-for-elementor-page-builder/

Regards 

David

**Comment by UraraReika** [comment]
Hello @DavidWooF !

At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

As for the plugin you provided, with such settings https://prnt.sc/rlv32b, generation and addition of a gray page in the PDF file will occur.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.
