### ISSUE TITLE
JetEngine Form - Media field does now allow to upload zip files when application/zip is selected

### ISSUE THREAD

**Issue by dmvega81** [CrocoBlock/suggestions#4760]
**Describe the bug**
When I add a field type MEDIA and under "Allow MIME types:" I select "application/zip" to restrict only zip file to be uploaded, I receive an "File type is not allowed." in the form while trying to upload a zip file. If I clear all options under  "Allow MIME types:" I am able to upload .zip files without a problem, but I am able to upload all types of as well and I dont that to happen.

**To Reproduce**
1. Go to 'Form'
2. Add a field type "Media"
3. Select under "Allow MIME types:" the  "application/zip" option
4. Save and publish the form
5. Go to the form and try to upload a zip file, the form gives an error "File type is not allowed."

**Expected behavior**
I expected to be able to upload only .zip files, but is now working.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome
 - Version Ver 97.0.4692.99

**Additional context**
 If I clear all options under  "Allow MIME types:" I am able to upload .zip files without a problem

**Comment by giacozama** [comment]
From mobile it happens the same thing when selecting .pdf. From desktop works from mobile it says "File type is not allowed".
I didn't test it from mobile before launching my website, my bad, but now i don't know what to do, this bug is making me lose many users.

**Comment by girafffee** [comment]
Fixed in version 2.1.1
