### ISSUE TITLE
2 BUG in jet smart filters & jet woobuilder in new version of hello elementor.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4761]
**jet woobuilder :** If we update the hello lementor, in the Jet woobuilder plugin, the product image will disappear from the shopping cart page. This bug only occurs on tablets and mobile phones

**jet smart filters :** If we install the latest version of jet smart filters and the latest version of hello elementor, this error will be displayed in the Chrome browser console. https://prnt.sc/26lypy0

**Comment by UraraReika** [comment]
> jet woobuilder : If we update the hello lementor, in the Jet woobuilder plugin, the product image will disappear from the shopping cart page. This bug only occurs on tablets and mobile phones

Look for #4735, which is on the same subject so we could deal with it more efficiently.

**Comment by Michaelgimii** [comment]
thnks @UraraReika
Do you also code jet smart filters? Or just jet woobuiler

**Comment by Floydtm** [comment]
JetSmartFilters - fix added in version 2.3.10
