### ISSUE TITLE
The Ajax search button in jet smart filters has a focus mode by default.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4762]
In the search widget of this plugin, if we click on the search button, the background color of the button changes and is not under control. In other words, it has a focus mode. https://prnt.sc/26lz2vh
**This code solves the problem. But please fix it in the plugin.**

button.jet-search-filter__submit.apply-filters__button:focus {
    background-color: white ;
}

@Floydtm

**Comment by SargasTM** [comment]
Я не понимаю, почему мы должны добавляться стилизацию состояния фокус для кнопок, если даже в стандартной кнопке елементора такого нету ???
![image](https://user-images.githubusercontent.com/5094971/159916337-9022a9b5-19db-4463-a7f0-a5f3c9b05d48.png)

**Comment by Michaelgimii** [comment]
@SargasTM , I did not say add focus mode! Focus mode is now available on the Filler Search widget button and is very annoying.
I just asked you to delete it.
please See this image : https://prnt.sc/CuJJt91hdp5K
