### ISSUE TITLE
[JetEngine] - Post URL option for dynamic field widget

### ISSUE THREAD

**Issue by 05edgarBlw** [CrocoBlock/suggestions#4763]
i had a website where i wanted a popup that displayed a qr code for the current link of the single post of a custom post type. luckily there is already an option for a qr output in jetengine. however, I would like the **current post url** option to be added to a dynamic field for Post/Term/User object data.

**Comment by kaskad88** [comment]
Added in the next release ( 2.11.3 ). From v2.11.3 the `Post ID` will be convert to `Post URL` in the QR Code callback https://prnt.sc/26qjc5v
