### ISSUE TITLE
Filter on exclusion

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4764]
It would be a great possibility if we could create a filter that excludes the results from the query instead of including them. So, for example, I wish to filter my products by attributes. My attributes are: lactose and sugar. I wish to filter the products in such a way that the filtering results show products that _do not contain_ sugar if I pick "sugar" in the filter; if I pick "lactose", the results should exclude products that contain lactose from the list, 
Hope it can be implemented!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
