### ISSUE TITLE
Checking post_type_exists too early in components/meta-boxes/manager.php:233

### ISSUE THREAD

**Issue by imsadhappy** [CrocoBlock/suggestions#4767]
Discovered when using JetEngine with [Sensei LMS](https://senseilms.com)

Custom meta boxes, when registered in JetEngine and assigned to custom post type (registered by other plugin - [Sensei LMS](https://senseilms.com)) - did not appear on post type pages.

Upon investigation I've found that Sensei LMS plugin registeres its post types during init hook, but with priority 100. While JetEngine runs checks for meta boxes at priority 10 - hence, earlier. see Jet_Engine_Base_WP_Intance __construct -> Jet_Engine_Meta_Boxes -> register_instances (components/meta-boxes/manager.php:233).

Potentially any 3rd party plugin that registeres its custom post types later than init10 won't get JetEngine meta boxes. Checking post_type_exists during init is not correct and should be done later.

My solution was simply wrapping the meta box registration in additional action 'wp_loaded'. See below:

before:  components/meta-boxes/manager.php:231 -> 

```
foreach ( $post_types as $post_type ) {

    if ( ! post_type_exists( $post_type ) ) {
        continue;
    }

    $this->store_fields( $post_type, $meta_fields, 'post_type' );
    $this->find_meta_fields_with_save_custom( $object_type, $post_type, $meta_box['id'], $meta_fields );

    $meta_instance = new Jet_Engine_CPT_Meta( $post_type, $meta_fields, $title, 'normal', 'high', $args );

    if ( ! empty( $args['show_edit_link'] ) ) {
        $meta_instance->add_edit_link( add_query_arg(
            array(
                'page' => 'jet-engine-meta',
                'cpt_meta_action' => 'edit',
                'id' => $meta_box['id'],
            ),
            admin_url( 'admin.php' )
        ) );
    }

}
```

after my small fix: components/meta-boxes/manager.php:231 ->

```
foreach ( $post_types as $post_type ) {

    add_action( 'wp_loaded', function() use ($post_type, $meta_fields, $object_type, $meta_box, $title, $args) {

        if ( ! post_type_exists( $post_type ) ) {
            return;
        }

        $this->store_fields( $post_type, $meta_fields, 'post_type' );
        $this->find_meta_fields_with_save_custom( $object_type, $post_type, $meta_box['id'], $meta_fields );

        $meta_instance = new Jet_Engine_CPT_Meta( $post_type, $meta_fields, $title, 'normal', 'high', $args );

        if ( ! empty( $args['show_edit_link'] ) ) {
            $meta_instance->add_edit_link( add_query_arg(
                array(
                    'page' => 'jet-engine-meta',
                    'cpt_meta_action' => 'edit',
                    'id' => $meta_box['id'],
                ),
                admin_url( 'admin.php' )
            ) );
        }

    } );

}
```

I've  wrapped all the code inside foreach in `add_action( 'wp_loaded', function() use ($post_type, $meta_fields, $object_type, $meta_box, $title, $args) {});` and replaced `continue` with `return` inside `if ( ! post_type_exists( $post_type ) ) {}`

Please, consider adding this fix - should be a quick one.

**Comment by kaskad88** [comment]
@imsadhappy Unfortunately, we can't add your solution to the release version as it would break backward compatibility with our components and other third-party plugins.
