### ISSUE TITLE
BUG - "Add to cart" button of JET PRUDUCT GRID not working properly on iphone devices

### ISSUE THREAD

**Issue by zlaten9** [CrocoBlock/suggestions#4768]
**Describe the bug**
When you click one click on "Add to cart" on some product, nothing happen, just hover.. and if you will click twise it will add to cart the item

**To Reproduce**
1. Go to ' https://new.smartcase.co.il/ ' on iphone device
2. Click on 'הוספה לסל (add to cart)'
3. You will see that one click isn't enough to add to cart item

**Expected behavior**
I want that when i click one click on "Add to cart" it will works, instead of 2 clicks 

**Desktop (please complete the following information):**
Irrelevant, on the desktop it works great

**Smartphone (please complete the following information):**
 **- Device:** iPhone13, iPhone12, iPhone11
 **- OS:** 15
 **- Browser:** safari

**Additional context**
PLS HELP!!!!
With Samsung devices its works great,
On iphone it like doing HOVER and then on the second click it adding do cart

p. s.
sorry for my bad english :)

**Comment by UraraReika** [comment]
Hello @zlaten9. 
We have checked your request. We use  iPhone13, iPhone12, iPhone11 in Safari with latest OS and everything seems to be working correctly. Perhaps this is related to your site. Please contact our [support team](https://support.crocoblock.com/support/home/). Thank you!
