### ISSUE TITLE
WPML and the new Relations Update

### ISSUE THREAD

**Issue by serialtasted** [CrocoBlock/suggestions#4773]
**Describe the bug**
With the new Relations update I can't set the relation to be copied in different translations.
Before I would have an option on WPML settings in Custom Fields Translation to copy the Relation between translations.

**To Reproduce**
1. Create a relation and set it up
2. Go to WPML Settings in the section Custom Fields Translation
3. Should have something like before "relation_f318c5aa95eb662af91b60fb59cfe169"
4. Change to be Copied from the different options

**Additional context**
Was working before I converted to the new relations system. I now have to set the relation on all translations when they exist for that post.

**Comment by kaskad88** [comment]
Added in 3.0.4
