### ISSUE TITLE
"Product not found" customization in product grid widget.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4775]
Is it possible to add a feature to this widget so that we can customize this message? It may seem a bit impossible to implement, but it would be great if such a thing could be added.

**Comment by UraraReika** [comment]
I merged this issue with #4386, which is on the same subject so we could deal with it more efficiently.

Please next time use one of this [templates](https://github.com/Crocoblock/suggestions/tree/master/.github/ISSUE_TEMPLATE) before create new issue.

**Comment by Michaelgimii** [comment]
thanks
