### ISSUE TITLE
get a flag symbol out of a CPT field for country code, or from URL

### ISSUE THREAD

**Issue by TheaterLina** [CrocoBlock/suggestions#4777]
Hello Support Team,

I have following challenge and hope you can assist me a bit in the future with this functionality.

I'm using JetEngine Taxonomies.
I have a taxonomy there for countries. This taxonomy is shared with all my CPT.

My items are posts and defined in CPT. I have 5 CPT in total all using the same country taxonomy.

The idea is to assign each item (post) to one ore more countries.
It's the selling country of the item.

In the taxonomy I have added an extra field (custom field) to add the flag of the country. But this is a lot of work to upload all flags there! 

My goal is to have a listing (for one CPT) and I want to see the assigned country as flag there.

Is is maybe possible to create a field (not in the taxonomy) in the CPT itself with a kind of country code like "RUS" (Russia) or "BRA"(Brazil) and to get the flag loaded from the internet when using the listing?

there are some mapping tables online like this:
https://onedrive.live.com/view.aspx?resid=9D609A31C1F627C2!313146&ithint=file%2cxlsx&authkey=!APKsz3pVoSGLOIk

I think to upload each flag into wordpress media store is a pain. Better would be to only enter a country-code or a link and get the flag loaded from the internet.

Is such a way possible?

Thanks so much and Best Regards,
Lina

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
