### ISSUE TITLE
Gutenberg custom templetes single post type.

### ISSUE THREAD

**Issue by itaides** [CrocoBlock/suggestions#4779]
Hi,it will be great if we can build a custom single template for Gutenberg, like we are doing in these days with elementor.
i know that "toolset" have that feature. https://toolset.com/

elementor:
https://elementor.com/help/creating-a-single-post-template-with-elementor-pro/
pods:
https://pods.io/features/

Many thanks.

**Comment by Floydtm** [comment]
We are working in this direction. keep for updates https://prnt.sc/qvTrPRYo-TJK
