### ISSUE TITLE
 Bulk assign Woo template to products

### ISSUE THREAD

**Issue by Mramorov** [CrocoBlock/suggestions#4785]
Hello to all,

I would like to be able to assign a separate Woo template for a group of products selected according to the specified criteria. So far, the only way to assign a different template is to go into editing a specific product each time.
I think it would be most convenient to be able to set conditions in the template settings.

**Comment by UraraReika** [comment]
I merged this issue with [#2540](https://github.com/Crocoblock/suggestions/issues/2540), which is on the same subject so we could deal with it more efficiently.

**Comment by rtpHarry** [comment]
I've implemented a version of this, as a plugin, which lets you assign product single templates based on the product category:

https://github.com/rtpHarry/jet-woo-builder-category-custom-product-template

It adds configuration options into the WooCommerce Product Category taxonomy to let you select the "product single" template to apply.
