### ISSUE TITLE
Manage Jet Appointment Services and Providers through forms using the Profile Builder

### ISSUE THREAD

**Issue by deanliddle** [CrocoBlock/suggestions#4786]
Is it possible to be able to add the functionality to manage Jet Appointment Services and Providers through forms using the Profile Builder?

I have been going through the Paul C tutorial on using the profile builder to create frontend forms to allow a client to add services and providers using Jet Appointment.

Obviously, his tutorial is just about creating generic listings. Which fields will I need to add to the form to allow my client to use the Profile Builder forms to manage the Jet Appointment services and providers? I know they could use the WordPress admin to do this but it sort of defeats the object of using the profile builder to simplify things for the client.

**Comment by Floydtm** [comment]
Contact our support team, they will help you with this. Thank you!
