### ISSUE TITLE
JetAppointment : Avoiding to take appointment after a certain day

### ISSUE THREAD

**Issue by jeremynachtegaele** [CrocoBlock/suggestions#4790]
Hi,

I'm using JetAppointment plugin so visitors can take appointment for a service.
It could be really great and helpfull if you can add the possibility to avoid that users take appointment 14 days (variable) after the current day.
Examples :
The day for registering the appointment : 3rd february --> visitor could only take appointment until the 17th february
The day for registering the appointment : 4th february --> visitor could only take appointment until the 18th february
The day for registering the appointment : 5th february --> visitor could only take appointment until the 19th february
And so on...

Some of mu customers that use my websites with this plugin is asked me that.

Thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
