### ISSUE TITLE
Ability to display the wishlist using the product grid widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4792]
**Please, describe the feature request, making it clear to understand.**

It would be great if we could display the favorites list using the product grid widget. This will happen when we have the jet woobuilder, jet wishlist plugin installed at the same time.
I think it would be great if we could install these two plugins at the same time, adding a new option as "wishlist" to the product grid query widget. This has many advantages. First, product grid widget customization is much more powerful than the current wishlist. Secondly, we can even display the user's wishlist as a carousel. this is great.

thank you

**Comment by UraraReika** [comment]
I merged this issue with [#4697](https://github.com/Crocoblock/suggestions/issues/4697), which is on the same subject so we could deal with it more efficiently.
