### ISSUE TITLE
JetReviews - Review Property Dynamic Tag

### ISSUE THREAD

**Issue by Radzio1615** [CrocoBlock/suggestions#4797]
Can you add more types to choose from in Review Property Dynamic Tag?
I really need more reviewed object related options:
- Reviewed Object Title
- Reviewed Object URL
- Reviewed Object Featured Image

I want to create a list of added reviews in user profiles. At now I can't add reviewed post title, url or thumbnail.

![image](https://user-images.githubusercontent.com/40895581/152589184-4c078905-6584-4d03-bfe9-6aeb7857122f.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
