### ISSUE TITLE
Set advanced/seasonal price settings from the front end form (Jet Booking/Jet Engine Forms)

### ISSUE THREAD

**Issue by olyaastep** [CrocoBlock/suggestions#4799]
Hello!
Crocoblock Jet Booking plugin now gives the perfect ability to set advanced price rates based on seasons.
For multihost websites, it is important to give an ability to add pricing settings through the front-end form.

Please consider it in the next update. 
Create a form field for advanced seasonal price settings with the ability to insert/update all of the data to the post. 

1) add a new field type to the Jet Forms (a copy of the Pricing settings which already exists on the back-end)
2) give an ability to connect it with advanced price settings
<img width="993" alt="Screenshot 2022-02-05 at 19 03 47" src="https://user-images.githubusercontent.com/90695766/152649189-f766b938-413f-4e49-ab5c-9621f23ca00b.png">

It would be great to find a developer who can create an addon (jet forms addons) for that feature!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
