### ISSUE TITLE
WooCommerce Product Countdown

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#48]
Integrate the countdowntimer into jetwoobuilder, so I can add a countdowntimer to the productslayout and the categorygrid. somehting like this: https://yithemes.com/themes/plugins/yith-woocommerce-product-countdown/

**Comment by UraraReika** [comment]
This issue can be solved with the help of simple date meta field, and Countdown Timer widget with dynamic options. Simply add widget to Product Archive Template and set this parameters https://prnt.sc/q36myz, where "Sale Start Date " date meta field. Also set https://prnt.sc/q36nuo this option to hide your timer when time expires.

**Comment by Michaelgimii** [comment]
> This issue can be solved with the help of simple date meta field, and Countdown Timer widget with dynamic options. Simply add widget to Product Archive Template and set this parameters https://prnt.sc/q36myz, where "Sale Start Date " date meta field. Also set https://prnt.sc/q36nuo this option to hide your timer when time expires.

Hi @UraraReika, Screenshots are not loading. Could you update it again?
