### ISSUE TITLE
Appointment - automatically approved user bookings

### ISSUE THREAD

**Issue by BrynWithin** [Crocoblock/suggestions#480]
Greetings. I am entering a feature request here after seeing your Facebook competition post.

=============

Something that I have never seen done very well in any appointment booking plugin is support for the management of premises or resources.

Put simply: allowing authorised users to claim/unclaim a slot in a daily booking form, with customisation afforded both to users and admin.

Example:
A sports club has a gym and several tennis courts. The club would like its website to have a members-only section that allows anyone to claim a maximum of one court session per day. All available court sessions not needed for coaching are shown in a calendar-type view. Each day has its own available times and courts. Up to 4 names can be submitted for each session, either by a single user (who will play with a specific group and is putting all the names down) or by different users (individuals just putting their name down for a match with anyone else who would like to play them). The first user to enter their name in a session has some options they can define, such as casual or ranked and singles or doubles. Some choices may impact the ability of other users to put their name down, if for example user types exist for casual and ranked players or if a session has been declared a singles match and therefore takes two names only. The club has no interest in manually approving any bookings - the system exists simply to manage the tennis courts in an efficient manner and avoid conflict between members. To avoid abuse, the system can also limit each user to a set quantity of active bookings and prevent anyone from booking courts more than a set period of time in advance. It is also possible for certain sessions to be ranked or casual only, where only those user types can enter their name.

The above example can be applied to countless other scenarios that appointment plugins almost always struggle with. Any other sports club, extramural activities in schools and universities, library resources, managing a free public venue, managing study rooms, a public swimming pool etc. etc. Basically the missing piece of the puzzle, where it is recognised that appointments aren't only between people but between people and a particular shared resource.

=============

I think a great many people would be over the moon if a reliable outfit like Crocoblock produced a quality plugin that can manage the above scenarios with ease.

That's it. Thanks for reading. Regards, Bryn.

**Comment by Floydtm** [comment]
We recently made a new jetappointment plugin. I think it should partially cover your request. Let us know if this suits you.
