### ISSUE TITLE
Recently viewed query on jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4800]
**Describe the bug**

hello

If you remember, I previously posted a report that this query interferes with the wp-rocket plugin. I even discussed this with the wp-rocket writers and they said it was not our problem and we could not help it. 
They were right. The problem is that the "Recently viewed" query supports cache. Because of this, this query never worked properly.
Cache support by this query causes it to add products to the list by mistake. In general, the cache corrupts this query.
Please correct this. So that this query is automatically removed from the cache. In this case, it will no longer be a problem.
(I disabled the cache on the page I was using this query and found that the problem was with the cache)

It would be great if you could fix this in the next version. Finally we can use it.

**To Reproduce**

1- Install the jet woobuilder and wp-rocket plugins at the same time.
2- On a page (for example, the main page), add the product grid widget and set its query to Recently viewed.
3- To test, visit different products and finally see the list of products you have seen before. **It does not work properly.**
4- Now edit the page (home page) and disable its cache. https://prnt.sc/26pd5qz
5- Visit different products again and see the list of recently visited products again. It will work properly.

thank you

**Comment by UraraReika** [comment]
For displaying recently viewed products we use default WooCommerce cookie `woocommerce_recently_viewed`. So please set up your wp rocket settings where you exclude this cookie.
