### ISSUE TITLE
Add More Conditional Options in JetFormBuilder

### ISSUE THREAD

**Issue by loucasl** [CrocoBlock/suggestions#4801]
JetFormBuilder is a great plugin, but I’ve found the conditional block a little bit limited compared to what JetEngine can do.

For example, with JetEngine Dynamic Visibility conditions, you can choose AND or OR with multiple conditions, something you can’t do in JetFormBuilder and that should be added in a future update.

![C903A64A-3460-4409-9A5F-19982824C7A2](https://user-images.githubusercontent.com/35241778/152667673-5d0ac8f3-594f-43f2-a737-6532afbda6b8.jpeg)

**Comment by Rubendj1** [comment]
True! A few more operators to choose from would be handy too! for example "not equal to".

**Comment by Lonsdale201** [comment]
+1

**Comment by girafffee** [comment]
Already available in beta 3.0
https://github.com/Crocoblock/suggestions/issues/6408
