### ISSUE TITLE
Jet Woo single product template options

### ISSUE THREAD

**Issue by mdesignweb** [CrocoBlock/suggestions#4803]
A shop page template has an option for template layout and title directly on the template. 
![shop template](https://user-images.githubusercontent.com/92887019/152673220-53f1fd08-f463-484c-8f6f-eff5ca873c76.png)

However, that option for a Single product is present but in the wrong place. Now, we have to go to edit every product and change the template layout. 
![product](https://user-images.githubusercontent.com/92887019/152673318-193b4f7b-25a0-41a8-afa5-06ef67cebd7a.png)
That is ok if we have a few products, but if we have 100 or more? This option is important because if not set to "elementor full-width" or "canvas", on Astra theme template will have Astra CSS and especially padding on mobile. And the page is not rendered as a Shop page for example. 
![single](https://user-images.githubusercontent.com/92887019/152673416-d522a967-9c01-47fe-8c3c-2b3682daaa34.png)

So it will be two situations where we can use this:
1. One product page template for all products - Layout setting setup to elementor full-width for the template to work properly.
2. Every product have their own product page. We used to call this "Sales page. "

If you need an extra explanation, please let me know

**Comment by UraraReika** [comment]
I merged this issue with [#4450](https://github.com/Crocoblock/suggestions/issues/2680), which is on the same subject so we could deal with it more efficiently.
