### ISSUE TITLE
Magazine Slider Widget

### ISSUE THREAD

**Issue by ChanukaWijesundara** [CrocoBlock/suggestions#4805]
Can we create Magazine Slider Widget using Croco block like this ?https://powerpackelements.com/elementor-widgets/magazine-slider/
please can you add this king of wiget for JetElement?

**Comment by UraraReika** [comment]
Hello @ChanukaWijesundara !

We have such functionality in JetBlog,  [here](https://crocoblock.com/widgets/smart-posts-tiles/).
