### ISSUE TITLE
JetTabs - JetWoobuilder templates

### ISSUE THREAD

**Issue by fababsolute** [CrocoBlock/suggestions#4806]
Hi there,
It would be great if there was an option to add Jetwoobuilder templates in addition to elementor templates
Thank you so much

**Comment by UraraReika** [comment]
Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
