### ISSUE TITLE
JetEngine CCT - Ability to add export csv file from a front-end form

### ISSUE THREAD

**Issue by D3663** [CrocoBlock/suggestions#4809]
I have workers that are not technical and that should not be given access to everything that manage options gives them. However, to do there job they need to be able to down load a csv file from a CCT table. 

The ability to have this as an option on a front-end form would be fix this. A form could be created to give them all teh access they need without opening up the entire dashboard to them.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
