### ISSUE TITLE
JetEngine CCT and Forms permissions align

### ISSUE THREAD

**Issue by D3663** [CrocoBlock/suggestions#4810]
I can create a custom permission for a CCT and enter it in the setup. However, there is a breakdown when creating a front-end form for the CCT. The form ignores the custom permission set in the CCT and only allows someone with manage_options rights to edit the form.  The form should refer to the permission setup in CCT.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
