### ISSUE TITLE
JetEngine CCT csv export does not delimit double-quotation marks in a text field

### ISSUE THREAD

**Issue by D3663** [CrocoBlock/suggestions#4811]
When there are double-quotes (“) in a text field, the export.php program does not delimited the double-quotes properly into something like “” or \”” or something slimier and leaves them as (“). The result is the CSV now has a record with too many fields. 

DoubleQuotesinTextField..csv shows what happens when a text field has double-quotes in it(")
SingleQuotesinTextField.csv shows the same record when the double quotes (") have been changed to single quotes ('). Record now has correct number of fields.
ExportFromMySQL.csv show the record with the double-quotes (") in the text field exported directly from the database as a csv with the correct number of fiels

See attached files created from the CCT UI.
[ExportFromMySQL.csv](https://github.com/Crocoblock/suggestions/files/8018367/ExportFromMySQL.csv)
[DoubleQuoteseinTextField.csv](https://github.com/Crocoblock/suggestions/files/8018368/DoubleQuoteseinTextField.csv)
[SingleQuotesinTextField.csv](https://github.com/Crocoblock/suggestions/files/8018369/SingleQuotesinTextField.csv)

**Comment by kaskad88** [comment]
Fixed in JetEngine v2.11.6

**Comment by D3663** [comment]
Thanks, I just tested and everything worked fine.
