### ISSUE TITLE
Map is missing OSM (OpenStreetMap) / Leaflet as free map alternatives

### ISSUE THREAD

**Issue by rrvoigt** [CrocoBlock/suggestions#4819]
Hi,

The map seems to be missing OSM (OpenStreetMap) / Leaflet (https://leafletjs.com) as an important free alternative to the paid maps like Google and Mapbox (still behind because it doesn't cover all the regions, like Google).

Please strongly consider adding OSM / Leaflet as a map alternative to Crocoblock.

Regards,

**Comment by nreljed** [comment]
#3885

**Comment by brupao** [comment]
+1

**Comment by yeswycan** [comment]
So true we need Leaflet and OSM !

**Comment by Floydtm** [comment]
#5417
