### ISSUE TITLE
Jet Engine - Calendar and Recurring Events

### ISSUE THREAD

**Issue by Nick-Hyatt** [CrocoBlock/suggestions#4820]
**Jet Engine - Calendar and Recurring Events**

**Issue**

Calendar and the associated input via a CPT for Events works well so long as it is a standalone or one off event (i.e. there is only one instance of that event).

However, very often events repeat on a weekly basis (e.g. a coffee morning, children's playgroup, religious service or a fitness class).  Entering the same details for the same day of the week across all 52 weeks in a year is time consuming and inefficient.

**Request**

Jet Engine - Calendar needs a recurring events option.  Perhaps a flag or check box that can be selected when setting up an event to enable it to be repeated at the same time on the same day for either a set period of time (6, 12, 24 or 52 weeks - for example) or for ever if there is no scheduled end point for the meeting or service.

**Additional Information**

Similar to the functionality provided by this - https://theeventscalendar.com/blog/tips/how-to-add-recurring-events-to-a-wordpress-site/

**Comment by loucasl** [comment]
+1

**Comment by spanovic** [comment]
+1

**Comment by doodledude** [comment]
+1

**Comment by morosmo** [comment]
+1

**Comment by PMegre** [comment]
+1

**Comment by m-dejong** [comment]
+1

**Comment by steve-gibbons** [comment]
+1

This type of functionality is REALLY fundamental to an event calendar.  Please prioritize this suggestion.

**Comment by doodledude** [comment]
+1

**Comment by Girovagante** [comment]
+1 Please prioritize!

Ideally interpreting an **rrule** in the place of the current "Allow multi-day" option.
Maybe using a new meta field type, like in this [ACF rrule plugin](https://wordpress.org/plugins/acf-rrule-field/)?

**Comment by pamundita** [comment]
+1

**Comment by abdul44hameed** [comment]
+1

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
