### ISSUE TITLE
Dynamic field display checkbox. Add icon if empty

### ISSUE THREAD

**Issue by brupao** [CrocoBlock/suggestions#4825]
Hi team,
on dynamic field option I would ask the ability to display different icon if all checkbox are empty/unchecked.
![image](https://user-images.githubusercontent.com/99042394/153236689-174658a6-d619-4cb3-a0dc-1aad05c00ad1.png)

I have a "V icon" if checked, I would use "X icon" if unchecked.

Thank you.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
