### ISSUE TITLE
JetEngine Query Builder - WC Product Query - listing with product image

### ISSUE THREAD

**Issue by computerfreak84** [CrocoBlock/suggestions#4826]
Hello

I made a query with query builder for WooCommerce products with the WC Product Query type.

The query outputs an "image_id" of the product.

**But I see no way how to use the product image in a listing item...**

The dynamic image feature for WooCommerce product image does not display the product image when using a listing item for query builder / when using the listing grid with a query builder query.

Any way to do it?

**Comment by UraraReika** [comment]
Hello @computerfreak84 !

Did you use this source for Dynamic Image widget https://tppr.me/76RHA, https://tppr.me/ey3sZ?

**Comment by computerfreak84** [comment]
> Hello @computerfreak84 !
> 
> Did you use this source for Dynamic Image widget https://tppr.me/76RHA, https://tppr.me/ey3sZ?

thanks, that helped, Dynamic Image widget works, I first tried with regular image and other image widgets.
