### ISSUE TITLE
new style for product grid Carousel Dots.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4830]
**Please, describe the feature request, making it clear to understand.**

hello

Great if you add this mode to the Carousel Dots of this widget. The following video :

https://user-images.githubusercontent.com/77163248/153388856-c7c917df-c551-41bb-b791-0ff2014a702d.mp4

I think the new option for choosing the Carousel Dots animation is great. Using this option, we can control the Carousel Dots animation while scrolling.
**Default mode (current mode) - Middle mode (like Instagram slide post) - Animation like this video (I do not know its name)** 
These 3 items can be selected options in this animation.

thank you

**Comment by 79ho3ein** [comment]
thank you dear @UraraReika🌹

**Comment by Michaelgimii** [comment]
@UraraReika , #4648 Will it be added?
