### ISSUE TITLE
Friendly Captcha integration for JetFormBuilder

### ISSUE THREAD

**Issue by ashentertain** [CrocoBlock/suggestions#4831]
European developers urgently need GDPR-friendly spam protection for all forms. Please consider esp. "Friendly Captcha" integration.

JetFormBuilder has great potential but unfortunately in the EU we need a way to protext forms and stay GDPR-compliant.

**Comment by Smalyleinchen** [comment]
+1

**Comment by girafffee** [comment]
Hi everyone)
This feature was included in 3.1.0 version

https://jetformbuilder.com/features/adding-friendly-captcha-to-form/
