### ISSUE TITLE
JetEngine: sale subsites/access in Multisite-installation

### ISSUE THREAD

**Issue by dutuka** [CrocoBlock/suggestions#4834]
Hello,
I would like to have these features for my next project:
- Sale membership in multisite-installation
 + Members can create subsite after pruchase membership 
 + Members have access to serveral subsites
 + If membeship expires, members subsites/access will be disabled/restricted
 + Members subsites/access will be reactivated when members prolong membeship.
 + Custom user roles/menu/account tabs based on memberschip
 + Automator intergration

Examples:
https://www.paidmembershipspro.com/add-ons/pmpro-network-multisite-membership/
https://www.paidmembershipspro.com/add-ons/pmpro-network-membership/

**Comment by MjHead** [comment]
Its to specific functionality. It shoud be implemented as separate plugin, not part of JetEngine
