### ISSUE TITLE
Not able to find where the jetAppointment settings for "Working Hours" is stored

### ISSUE THREAD

**Issue by shubhamkashyapdev** [CrocoBlock/suggestions#4836]
Thanks for the amazing plugin, I have a booking system website created with jetAppointments and i want to show a analytics dashboard of KPI in form of charts like "Total Revenue By Each Room" "Cancellation Rate" etc. Everything is fine but i did not find any data for jetAppointment "Booking Hours" to create a "Total Slots / Booked Slots" chart. Can someone help me here on how can i get that data. I tried to look every possible table id DB but did not find anythings. Thanks in advace :)

**Comment by Floydtm** [comment]
all options are stored in wp_options table https://prnt.sc/IhhkTghqSLTk
