### ISSUE TITLE
JetTabs - new tabs format

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4841]
On the Crocoblock website (namely, this page https://crocoblock.com/plugins/jetformbuilder/), there are tabs on the left AND the right (https://prnt.sc/26tletd).  As I have a lot of features, it would be great for me to be able to do it.

**Comment by cheviader** [comment]
I'd love to have this feature. :)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin. Everything you see is custom made.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
