### ISSUE TITLE
BUG REPORT: Jet Engine Listings remove Polylang's "lang" query argument when Lazy Loading is enabled

### ISSUE THREAD

**Issue by rch-shayne** [CrocoBlock/suggestions#4846]
Hello,

We've encountered a bug with Jet Engine Listings and Polylang (multilingual plugin).
When a listing is set to "lazy load", the current language ( pll_current_language() ) is no longer applied to the query.

So for example, on an English-language page with lazy-load enabled, the listing displays posts in both English AND French. On an English-language page without lazy-load enabled, the listing only displays posts that are set to English.

To test, I used the 'posts-query-args' filter to explicitly set the post query language based on the page's current language, and echo the query arguments to JS console.

```
add_filter( 'jet-engine/listing/grid/posts-query-args', function( $args, $widget, $settings ) {
 	$args['lang'] = pll_current_language();
	echo "<script>console.log('args:',  ". json_encode($args).");</script>";
	return $args;
}, 10, 3 );
```

Here is the $args object on an English-language page when the listing is not set to "lazy load":
![image](https://user-images.githubusercontent.com/62078678/153647558-e84d70c0-9bbb-4364-85b2-246529a888f3.png)

Here is the $args object when the listing is set to "lazy load":
![image](https://user-images.githubusercontent.com/62078678/153647319-9e4357c8-b4bf-4e71-b857-711c722504d0.png)

It seems that when set to lazy load, the listing grid is somehow stripping out the 'lang' argument, or setting it to false.

It's very important to us that this works, so we will be disabling lazy loading and implementing our own custom listing + filtering solution for now.

Thank you!

**Comment by kaskad88** [comment]
Thanks for your feedback.

We tried to reproduce your issue based on the information you provided, but without success.

Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
