### ISSUE TITLE
Jetform Builder not showing the meta field labels and not field names

### ISSUE THREAD

**Issue by gdelfava** [CrocoBlock/suggestions#4847]
Hi, please can you update the Jetform Builder plugin to show the field names and not the field labels by default. It makes it so much easier to map the field names by copying and pasting when using the Post Meta of the Insert/Update Post Submit Actions. Currently you have to open a new windows and go to the metaboxes just to map the field names correctly. This is not good for workflow
<img width="857" alt="Screenshot 2022-02-11 at 14 44 19" src="https://user-images.githubusercontent.com/62187627/153700372-0fc9bb14-286b-4cc1-954f-7d5b0dd93556.png">
.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by gdelfava** [comment]
This to me is actually a bug as the JetEngine Forms does show the meta field names instead of the field labels. If you guys are planning to get rid of Jetengine Forms then you need to make JetForm builder work the same and more user friendly.
