### ISSUE TITLE
border Default in delete filters widget / jet smart filters.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4848]
**Describe the bug**

hello

The delete filter widget has a border by default. https://prnt.sc/26uc3po
Therefore, even if we turn off the border option, the border still exists by default. It should be such that if the border option is disabled, there is no border.

thank you

**Comment by Floydtm** [comment]
We checked everything and it seems that everything works correctly. However, our sites may be configured differently. Please note that this may depend on your theme.

**Comment by 79ho3ein** [comment]
hi @Floydtm, This is common to all templates. I use hello elementor.
When we add the **Remove filter widget**, it has a border by default. While the border option is disabled in the style tab!
Therefore, if we do not need Border, we must turn on the border option and then set its value to 0 to remove the border. And this generates additional code.
This is not a particular problem. But if it is corrected, it is great.

**Comment by Floydtm** [comment]
I understand that this may cause you inconvenience. However, please understand that there are some things that we cannot fix. Our edits may affect backward compatibility.

**Comment by 79ho3ein** [comment]
Yes, I fully understand. thanks for your response.
