### ISSUE TITLE
A few suggestions for developing the Single Images widget / jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4850]
**Please, describe the feature request, making it clear to understand.**

Please consider these few.
1- Pixel value for this part : https://prnt.sc/26unpkl
2- Alignment option for this widget. Now if we reduce this value (https://prnt.sc/26unqjo), the product image will shrink to the left. If you add the alignment option, we can place the widget in the center after resizing.
3- Ability to apply spacing between thumbnails : https://prnt.sc/26unteh     Without moving the images below each other.
4- Fade mode to transfer images. Great if you add a fade mode to this widget as well. Currently images only change as slides. By adding this feature, we have two modes for changing product images. Slide and Fade. this is great.

**a case**

This widget has an extra space from the bottom by default (red arrow). While it should be like the top (green arrow) without space.
https://prnt.sc/26v9gbq

thank you

**Comment by UraraReika** [comment]
1, 2, 3, case - done
4 - There is no possibility to add such functionality.

**Comment by 79ho3ein** [comment]
thanks

**Comment by 79ho3ein** [comment]
hi again

There is another case related to the product image widget ... 
If there are thumbnails, there is plenty of [extra space](https://prnt.sc/0UGQfN92We_M) at the bottom of the widget.
