### ISSUE TITLE
Add Custom Meta Field or Similar to a PRODUCT VARIATION in Woo

### ISSUE THREAD

**Issue by marknicholsonhg** [CrocoBlock/suggestions#4851]
Struggling to find a solution using Crocoblock - Seems so powerful yet I just cannot see a way to add extra information on a Variation Basis

My example is we make furniture and have sizes which dictate how many Doors a cabinet would have - I would like to add this data at the product variation level so a customer can see how many doors their model would have in a filed showing QTY OF DOORS = XXXX

This plugin does it but I want to try to remain in the Crocoblock Eco-System https://pluginrepublic.com/custom-fields-for-woocommerce-variations/

Would love to hear if there is a way to achieve this.

**Comment by UraraReika** [comment]
Hello @marknicholsonhg !

Each variation has its own [description](https://tppr.me/FWr78) field, witch you can use to display some additional info about particular variation. I think that this solution will fits you.

**Comment by marknicholsonhg** [comment]
Hi there,

thanks for this suggestion but no - I wish to be able to add meta field
data via Crocoblock - so that I can for example control the data that shows
that may be universal across several different products/ranges

Possible?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
