### ISSUE TITLE
Possibility to convert the Gregorian calendar to the jalali calendar in jet appoinment 

### ISSUE THREAD

**Issue by TheNoOneIsBack** [CrocoBlock/suggestions#4852]
hi, I think that would be a great option if we could choose the type of calendar ...
for example, The official calendar of the people of the Middle East is Jalali so if a person wants to use jet appointments in the middle east they cant use the Gregorian calendar ... 
so I think it would be a good option if we could choose the type of calendar that suits our national calendar so this product could sell even more in Asia or the Middle East.
Thank you for your  great product ;)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
