### ISSUE TITLE
jet woobuilder bug

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4853]
On a single product page, after selecting a variable and deleting the variable, the page is moved and does not work as before. This problem occurred after updating elementor pro.

wordpress 5.8.3
jet woobuilder 1.11.4
hello elementor 2.4.2
elementor pro 3.6.1
elementor 3.5.5

**Comment by 79ho3ein** [comment]
I have this problem too. I think it is from the new version of elementor pro.


https://user-images.githubusercontent.com/77163248/153747699-5c70f222-617e-4f09-adfc-c23420dc2967.mp4

Of course, this bug only exists on the desktop.
Windows - chrome

**Comment by UraraReika** [comment]
Hello @Michaelgimii!

Describe this issue in more details and please follow this guidelines for opening a new [bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better.

**Comment by 79ho3ein** [comment]
I checked this problem and found that the problem is not with the jet woobuilder. The problem is the new version of elementor pro.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

elementor pro 3.6.2
