### ISSUE TITLE
jet woobuilder is not compatible with elementor page transition.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4854]
If we enable the page transition feature, page transition will not happen well when we enter the product page. Especially if we enable the open new tab option in the product grid widget, page transition rarely happens.

**Comment by UraraReika** [comment]
Hello @Michaelgimii!

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/) our support team. Thank you!

Next time please follow guidelines for opening a new [bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better.
