### ISSUE TITLE
JetWooBuilder, JetSmartFilters & Variation Swatches Issue

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#4855]
Then JetSmartFilters are enabled and trying to sort JetWooBuilder Products Grid with some filters suddenly the images of variations becomes static and not switching anymore.

**Comment by UraraReika** [comment]
Hello @s5t5n! Thanks for the feedback.

Please contact our support team and provide more details to them. We already have few solutions for different types of Swatches plugins and can provide it to you.

Thank you for your understanding.
