### ISSUE TITLE
jet smart filter interferes with the new version of WordPress.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4856]
@UraraReika 

If the new version of WordPress and the new version of jet smart filters are enabled, this error will be displayed in the chrome console :
https://prnt.sc/26uzbd7

Active plugins

elementor 3.5.5
elementor pro 3.6.1
**jet msart filters 2.3.9**
woocommerce 6.2.0
hello elementor 2.4.2
**wordpress 5.9**

This error occurred after updating WordPress to 5.9.

**Comment by MjHead** [comment]
fixed with 2.3.10
