### ISSUE TITLE
Product feature display problem - jet woobuilder

### ISSUE THREAD

**Issue by alisadrona** [CrocoBlock/suggestions#4857]
I use the bulleted list to display product features in the single excerpt widget. But with the bulleted list option, the product feature text moves in a bit and is not aligned with other texts. https://prnt.sc/26v3s7m

This is an annoying problem. I do not know how to code. But a friend gave me this code and the problem was solved . But this code does not work in some cases.

.woocommerce-product-details__short-description ul {
    padding-right: 15px;
}

Is it possible to add an option to the single excerpt widget that solves this problem? So that the bulleted list does not move in this widget. https://prnt.sc/26v3ts6.  I really need it

**Comment by UraraReika** [comment]
Hello @alisadrona !

This options will not be added due to specific of output content.
