### ISSUE TITLE
Row option for carousel (product grid widget) jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4859]
**Please, describe the feature request, making it clear to understand.**

hello

Now if we enable the carousel option, the products will be displayed in only one row and can be scrolled. But it would be great if you could add a row option to the carousel. Using this option, we can specify that the carousel has several rows (One row default). 

Therefore, we need this new option in the carousel section : https://prnt.sc/26v4b24

**Add an example of where this feature is already implemented.**

https://user-images.githubusercontent.com/77163248/153762446-accb18c3-daa9-402d-ae6f-859d0b604e0e.mp4

As you can see in the video above, the products were in 3 rows in a carousel. 

thank you

**Comment by UraraReika** [comment]
I merged this issue with [#4738](https://github.com/Crocoblock/suggestions/issues/4738), which is on the same subject so we could deal with it more efficiently.
