### ISSUE TITLE
Extra space between selecting a variable and the Add to Cart / jet woobuilder button.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4860]
**Describe the bug**

hello

On the single product page, there is a large space between the variable selection option and the Add to Cart button. https://prnt.sc/26v4hqo

This extra distance is quite obvious in Inspect. See these two images : https://prnt.sc/26v4j0t & https://prnt.sc/26v4joi

Even additional padding in this section has caused the title of the variable to be slightly out of balance (blue arrow)

As it turns out, there is a lot of extra space and padding in this section. Please consider them if possible. The large distance between the variable selection option and the shopping cart button undermines the user interface.

thank you for your attention🌹

**Comment by 79ho3ein** [comment]
Another thing in this section is that the variable selection arrow is almost [stuck to the margin](https://prnt.sc/C1QwVvGxSw4c) and there is no option to apply a space.

It would also be great to add an option to control the [distance between variables](https://prnt.sc/JYn7lgce3H74).

**Finally I had a suggestion for the variables section ...**

When the variable list opens, it has a very old user interface : https://prnt.sc/uaomMzbgLtpZ
Is it possible to develop its user interface? [please See similar case](https://prnt.sc/34KGNcm9XHwN). This is really great.
( In the [previous image](https://prnt.sc/9gwWyCGHItwP), the faded sizes are not in stock )

This interface is really great. Please watch the video below : 

https://user-images.githubusercontent.com/77163248/160521399-55bddc5e-bc32-46b8-8ded-ae6e691b089e.mp4

Is it possible to develop this feature in jet woobuilder?

**Comment by 79ho3ein** [comment]
It would also be great if we could move the title of the variable into the field. like this : https://prnt.sc/MzFBNsvPt4Hx
These are really great...

**Comment by 79ho3ein** [comment]
hi again
Also, after adding the Add to Cart button, there is a lot of [extra space at the bottom of the button](https://prnt.sc/FD78Wg_H3r6H).
https://prnt.sc/GTS90RYWbPrc

**Comment by UraraReika** [comment]
Hello @79ho3ein !

We added some margin and pudding controls to our widget that can control space between variations select and add to cart button.

> Another thing in this section is that the variable selection arrow is almost [stuck to the margin](https://prnt.sc/C1QwVvGxSw4c) and there is no option to apply a space.

This is standard select input field and not much we can do about it. But in your case there is some trick with [transparent](https://tppr.me/37HEC) border.

> It would also be great to add an option to control the [distance between variables](https://prnt.sc/JYn7lgce3H74).

Solved with adding additional controls.

Video - is custom styled and script to achieve this styling. UI for select input depends on what browser you use.

> It would also be great if we could move the title of the variable into the field. like this : https://prnt.sc/MzFBNsvPt4Hx

Widget layout based on standard WooCommerce view and it doesn't give us opportunities to do this.

**Comment by 79ho3ein** [comment]
hi, thanks for your response alexander

> We added some margin and pudding controls to our widget that can control space between variations select and add to cart button.

If you mean that these controls are now available in version 1.12.2, no. I tested all the options but it is not possible to eliminate these gaps.

<hr>

one question...
I am not a coder yet and I do not have a good understanding of coding. But I wanted to ask if Je woobuilder should always be based on the structure of WooCommerce? WooCommerce standards are very simple and I don't think developers are even thinking about developing it.
jet woobuilder is a great plugin and I'm more interested in it than any other plugin in the WordPress world. But in the selection of variables, they have a very simple UI. However, for example, in the form of Woodmart, there is a feature of color swatches, which makes the UI much better in selecting variables. But at the moment there is no such thing in jet woobuilder and everything works simply in the variables section. So since the WooCommerce standard is very simple in selecting variables, are color swatches never added to the Woboiler jet? (I know you have a way of adding color swatches to the jet woobuilder but I mean the color swatches feature in the jet woobuilder core.) In any case, I hope color swatches will be added to jet woobuilder soon.
It really is empty.

Anyway, thank you for taking the time to respond in these difficult days in Ukraine.
