### ISSUE TITLE
Ability to transfer the image in the product grid widget.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4861]
**Please, describe the feature request, making it clear to understand.**

It would be great if you could add a product image transfer feature to the product grid widget. Using this feature, we can determine where the product image is displayed. To the left of the content (title, price, etc.), to the right of the content, up or down (Default above). 
For example, if we select the right, it will look like this : https://prnt.sc/26v4txc

Therefore, this feature is required in this section : https://prnt.sc/26v4uln

This is a great feature needed. So if this feature is added, #4780 will not be needed.

thank you🌹

**Comment by UraraReika** [comment]
Due to presets structure of Products Grid widget this functionality can't be added, so use Products List instead.

**Comment by 79ho3ein** [comment]
thank you @UraraReika. Unfortunately, the product list widget is weaker than the product grid. For example, it can not be turned into a carousel. And other cases. In any case, thank you🌹
