### ISSUE TITLE
Social network sharing does not work on single product page.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4862]
**Describe the bug**

I'm using the elementor sharing buttons widget on the product single page, but it does not work. On mobile, it is not directed to a social network like Telegram. This problem only exists on the jet woobuilder single product page and works well on the elemntor theme builder single page.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team. 

Thank you!
