### ISSUE TITLE
Single Sale Badge Widget / jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4864]
**Please, describe the feature request, making it clear to understand.**

Currently, if we use the Single Sale Badge widget, it will be displayed if the current product has a discount. Otherwise it will not be displayed and we can not edit it live.
Please, if possible, add a feature that will display this widget so that we can edit it even if there is no sale product on the website.

**Add an example of where this feature is already implemented. **

I think this request is similar to: #4318

**Finally there is a bug in this widget, I report it in the same issue so as not to open a new request for it.**

If we add this widget for the first time, it is quite clear that it is not in place : https://prnt.sc/26vlg9h  Pay attention to the blue border.
It is clear that the widget is slightly out of margin.Even after customization, it is clear that the widget is not exactly in place : https://prnt.sc/26vlila
While it should be like this : https://prnt.sc/26vljpr          Fully inside the border. Like other widgets.

thank you

**Comment by UraraReika** [comment]
> Currently, if we use the Single Sale Badge widget, it will be displayed if the current product has a discount. Otherwise it will not be displayed and we can not edit it live.
> Please, if possible, add a feature that will display this widget so that we can edit it even if there is no sale product on the website.

In the[ admin area ](https://tppr.me/j8R6C)of Single Product template you can choose what product will be previewed in the editor.

> If we add this widget for the first time, it is quite clear that it is not in place : https://prnt.sc/26vlg9h Pay attention to the blue border.
It is clear that the widget is slightly out of margin.Even after customization, it is clear that the widget is not exactly in place : https://prnt.sc/26vlila
While it should be like this : https://prnt.sc/26vljpr Fully inside the border. Like other widgets.

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. 

Thank you!
