### ISSUE TITLE
The single title widget interferes with the jet menu plugin / jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4866]
**Describe the bug**

When we install the jet menu plugin and jet woobuilder together, the product title widget will not be displayed. This interference occurs when we enable Megamenu in the jet menu plugin : https://prnt.sc/26vn8pd
**We also need to add the mega menu widget to the header and call the megamenu to make the bug happen.**
If you did not succeed in reproducing this bug, I will investigate further. In any case, this bug exists and there is a reason.

thank you

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by 79ho3ein** [comment]
hello @UraraReika , Thank you for your favor.
