### ISSUE TITLE
JetEngine REST API for CPT

### ISSUE THREAD

**Issue by johnfc2021** [CrocoBlock/suggestions#4868]
When I use JetEngine to create a CCT, I get the option to register endpoints for getting items, adding, updating and deleting the items on the CCT itself.

However, this is not something available for CPT, so when I add a CPT, I can manipulate only the core WordPress fields unless I write some custom code to make WordPress update the meta fields. 

Since adding a CPT is easy with JetEngine, registering the endpoints with the meta fields specified should be equally straightforward.

**Comment by johnfc2021** [comment]
This link shows how to register the endpoints manually in your functions.php file, which might be useful to someone: https://stackoverflow.com/questions/43203695/create-post-with-meta-field-wp-rest-api

However, it would be much better to add the meta fields dynamically when adding the CPT with JetEngine, as adding a meta field to the CPT is easy, but remembering to update the functions.php is a bit more of a faff.

**Comment by MjHead** [comment]
Added with 3.0.0 update
