### ISSUE TITLE
Jet Engine, Listing, Meta Key

### ISSUE THREAD

**Issue by chaser32419** [Crocoblock/suggestions#487]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

--------------------------------------------------------------------------------
Giving jet engines listing query the ability to get meta-key or even add custom query to it like your other post widget would make things like display most viewed post, featured posts, most liked posts possible. because you need the meta-key to be able to display them as far as I can tell. 
--------------------------------------------------------------------------------

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

--------------------------------------------------------------------------------
Here is a list of blog posts I've made explaining how to use your plugin to display most viewed post, featured posts, most liked post easily. I am going to be doing most Favorited posts next. I am working on something that involves custom post types so I have to use listing and I can't seem to figure out how to get the meta key for these to work. 

https://sample-demos.xyz/blog/featured-post-setup/
https://sample-demos.xyz/blog/most-liked-post/
https://sample-demos.xyz/blog/most-viewed-posts/
--------------------------------------------------------------------------------

**Comment by Floydtm** [comment]
If you have difficulty setting up, then you better contact the support service https://crocoblock.com/help-center/
