### ISSUE TITLE
JetSmartFilters - Show empty terms in hierarchical selection filter.

### ISSUE THREAD

**Issue by Mesmer99** [CrocoBlock/suggestions#4870]
Hello Everyone.When im changing single filter to hierarchical only term fiel staying avaible.There is no options like show empty terms and etc. like in single one.So that will be cool if that options stay also in hierarchical select filter.Thanks.Also if its can be reached by coding that might be great too.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
