### ISSUE TITLE
Double Opt-In for registration (in the EU)

### ISSUE THREAD

**Issue by kulaber** [CrocoBlock/suggestions#4872]
Hi,

for the EU websites, we need the double opt in option, to make everything right in terms of law.

User is registrating on the website via e-mail.

After that, the user has to verify via a button in the email, to also prevent that this is a spam.

After user clicked on this button in the e-mail, the user is registrated.

Can you please add this function asap? Also for the EU users, it would be very nice.

Thanks Croco Team!

**Comment by alexanderpankart** [comment]
#2473

**Comment by girafffee** [comment]
Follow this issue https://github.com/Crocoblock/suggestions/issues/2473
