### ISSUE TITLE
JetSearch - search through product tags

### ISSUE THREAD

**Issue by Zaanone** [CrocoBlock/suggestions#4873]
I'm making a wine webshop. Each wine has specific product tags attached to them (e.a. 'New Year', 'Summer', 'Fresh', etc). With JetSearch, I cannot search for these product tags automatically. (A plugin that can do this is 'Advanced Woo Search'. However,, this plugin will cost me another 99 dollars a year). Therefore it would be great if JetSearch could do this also. 

Are you guys planning on adding this feature to the JetSearch plugin?

Mentioned in this requests:
- https://github.com/Crocoblock/suggestions/issues/1352 @petranca
- https://github.com/Crocoblock/suggestions/issues/119 @blueberry11
- https://github.com/Crocoblock/suggestions/issues/1183 @jeff1osu

**Comment by x3mp** [comment]
> 

Seems like its never gonna happen... #1183 was closed 2 years ago despite it still not being possible.

**Comment by MjHead** [comment]
Option `Search in taxonomy terms` added with 3.0.0 update
