### ISSUE TITLE
auto reindexing is deactivated after the update - jet smart filters.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4875]
After each jet smart filter update, all filters are disabled. So we have to click the index button, so that the filters are indexed again and displayed.
This is a problematic case. For example, on the website of one of the customers, they updated jet smart filters, but after a week, they realized that there is no product filter!
It is best to do this so that the filters are automatically indexed after each plugin update.

**Comment by alisadrona** [comment]
+1

**Comment by Michaelgimii** [comment]
Excuse me, why did this issue close?

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
