### ISSUE TITLE
JetWooBuilder - Add to cart button > Add custom quantity

### ISSUE THREAD

**Issue by Zaanone** [CrocoBlock/suggestions#4876]
Request: allow the add to cart button to add a product an x amount of times to the cart.

Example:
I'm building a website where I would like to have two buttons per product. 
- a button which adds a product to the cart 1 time (the current add to cart button does this)
- a button which adds adds a product 6 times (or any other amount of times)

I managed to fix it with some custom PHP code,, but it's not a very nice way to do it. The buttons are not very responsive.
It would be great if this was a included feature of the add to cart button.

This is how it looks right now on my website:
Archive product page
![image](https://user-images.githubusercontent.com/82780539/154235198-01167a26-015f-4f78-afc7-22d65a61b900.png)
Single product page
![image](https://user-images.githubusercontent.com/82780539/154234987-325f742e-2c47-4d82-9dcc-fdf9d4b6956e.png)

**Comment by UraraReika** [comment]
Hello @Zaanone. Thanks for the feedback.

I the next release of JetEngine you will be able to complete it https://github.com/Crocoblock/suggestions/issues/5693. Unfortunately this functionality will not be added to the JetWooBuilder.

Thank you for your understanding.

**Comment by UraraReika** [comment]
Fell free to check this kind of functionalities in JetEngine plugin version 3.0.8
