### ISSUE TITLE
Compatibility with Filter Everything plugin

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4877]
Filter Everything plugin is a plugin responsible for creating filters. I try to integrate its functionality with the JetEngine Listing Grid, but I encounter an issue whereas if I enable the Load More option, the listing displays wrong posts: 
filter rules: https://prnt.sc/26vmf4o
the first page of the list is right but when I click to load more it's showing different units
screenshot: https://prnt.sc/26vmfz0
It would be great if you could add official compatibility with this plugin.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
