### ISSUE TITLE
Better performance single Add to cart button with eleemntor pro menu cart widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4878]
On my website, I use the elementor pro menu cart widget and the add to single cart button is from the jet woobuilder plugin. Sometimes when I click add to cart, it takes a few seconds for the product to be added to the cart. Of course, this is the experience of users and they have reported this.
There seems to be a bit of a slowdown between the Add to Cart button and elementor pro menu cart widget.

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

AJAX add-to-cart buttons allow the user to add a product to the cart without reloading the page – a faster, more modern experience. While WooCommerce has a built-in `Enable AJAX add to cart buttons on archives` option, it doesn’t have a similar option for single product pages. So this functionality custom written in our plugin. 

Although you mentioned that it happened sometimes so it can mean that in this particular moment you server was in some kind of stress and it take some more time than usual.

But if you can present steps to reproduce the behavior it will be very nice.

Thank you!
