### ISSUE TITLE
JetReviews ability to query reviews anywhere with JetEngine listing grid

### ISSUE THREAD

**Issue by parfilov** [CrocoBlock/suggestions#4879]
Hello.
There is the often case customers asks to implement, to make a page with all reviews with a review form.
That's would be great to make a review listing template and query all reviews anywhere on the website.

Plus, it would be useful to integrate related addons/features/plugins to JetEngine:
- JetEngine and/or JetFormBuilder to generate review form and add it at the "all reviews" page after all reviews;
- JetSmartFilters to filter by reviews rating and others;
- JetSmartFilters pagination to make reviews pagination.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
