### ISSUE TITLE
Add Next post and Previous Post Widget 

### ISSUE THREAD

**Issue by rithvikpodduturi** [Crocoblock/suggestions#488]
Please add Next post and Previous post buttons which is there in your website
http://cloud.anytimewp.com/97b7c6
Something similar to that with some more styles included

**Comment by realstephenzhao** [comment]
There is a _Post Navigation_ widget among Elementor Pro's Single Post Template widgets, see the [doc](https://docs.elementor.com/article/432-post-navigation-widget) from Elementor official website.

JetElements also has a _Post Navigation_ widget, but it only works with main Query object, which is supposed to be native wordpress Post.

**Comment by rithvikpodduturi** [comment]
Why should I get elementor pro just for one widget when it can be added in JetElements

**Comment by kaskad88** [comment]
Hi! We have a Post Navigation widget. It comes with the JetBlog plugin http://prntscr.com/ozl70j

**Comment by rithvikpodduturi** [comment]
https://tutorialdestination.com/css-introduction/

That doesn't work for god sake, If you need I can provide access show me how to do.

**Comment by kaskad88** [comment]
@rithvikpodduturi, we are currently working on a fix for this issue and will release a patch soon. Thanks for reporting.

**Comment by kaskad88** [comment]
@rithvikpodduturi JetBlog v2.1.20 has been released. Feel free to update!

**Comment by rithvikpodduturi** [comment]
> @rithvikpodduturi JetBlog v2.1.20 has been released. Feel free to update!

Thank you for the update.

I would also like to have Post names instead of Newer posts and Older Posts.

**Comment by Floydtm** [comment]
@rithvikpodduturi, Hi! We will try to implement this functionality in the following plugin updates. Stay tuned!

**Comment by Vigar007** [comment]
> @rithvikpodduturi, Hi! We will try to implement this functionality in the following plugin updates. Stay tuned! #503

Is this update ready yet?
