### ISSUE TITLE
`Edit with JetPlugins` admin bar logo - not vertical centered

### ISSUE THREAD

**Issue by 05edgarBlw** [CrocoBlock/suggestions#4880]
Please fix that, its irritating me, and I always use own css for that.
![fix-logo-alignment](https://user-images.githubusercontent.com/95882520/154297521-a8558a4a-376a-4c58-8276-157473352764.jpg)

**Comment by Floydtm** [comment]
We checked everything and it seems that we do not see such a problem. https://prnt.sc/AcnCB4IS5SCV
