### ISSUE TITLE
jet woobuilder does not support elementor pro WooCommerce notice well.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4884]
elementor in version 3.6 has added the ability to edit WooCommerce notice. But if we use the WooCommerce notice widget in jet woobuilder templates, they do not display well and sometimes they do not even display at all.

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

If you create bug report please use this [template](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

If You create feature request use this [template](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team. Thank you!
