### ISSUE TITLE
Ajax Search Module - stop redirecting to search page if search field is blank 

### ISSUE THREAD

**Issue by KyleIrving** [CrocoBlock/suggestions#4886]
We're using the ajax search module in the header here https://argondigital.com/
Our challenge is when a user clicks the search button - without entering any search terms in the search field - they are redirected to a blank search page. Is there a way to force having to enter a search term? Or stop the redirect to a search page archive? 
Thanks

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by p-ranjan** [comment]
Is there an option to set this function on or off? In my case, when I don't put any search terms, I get all the posts for all terms. That's a wanted feature on my side.

**Comment by dislokacia** [comment]
> Is there an option to set this function on or off? In my case, when I don't put any search terms, I get all the posts for all terms. That's a wanted feature on my side.

Could you, please, check if it will help you?
https://gist.github.com/dislokacia/8269c6710f78bd2103f7f8302461ddd7
