### ISSUE TITLE
JetEngine: Tables Builder: Allow for Dynamic Conditions for Columns

### ISSUE THREAD

**Issue by jamsheehan** [CrocoBlock/suggestions#4887]
### Functionality

Allow Dynamic Content for table columns to hide or display based on an option created by the user, this would be similar to the Conditional Logic used in CPT / CCT backend. 

When enabled the user can select from the options from the various options created by the user. 

If the conditions are not met the column will be hidden. 

On the front end if the column conditions are not the met the column is hidden. 

![Tables Builder Dynamic Conditions](https://user-images.githubusercontent.com/223342/154462179-2cd71ead-8466-413b-afad-4b1d95adb376.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
