### ISSUE TITLE
jet woobuilder 1.12.0

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4888]
**Describe the bug**

hello @UraraReika !
First of all thank you for your attention to our suggestions as well as this great update. Naturally, this big update has small bugs, which I will introduce section by section. Please check them if possible.

**Carousel bugs**
Most of the bugs in this update are in Carousel, which I will describe in order.

1- This bug still exists : #4589
2- After the update, the column option in the Style tab was removed! (For current carousels). But if we add the product grid widget again, this option exists. In fact, for carousels that were created before this update, the column option is removed. https://prnt.sc/26xp5ex
3- I do not know if this depends on the above or not, but the carousel is out of balance and completely out of control. Especially after the preview. https://prnt.sc/26xp87f   **(This may be the case for carousels before this update)**
4- On a tablet and mobile phone, the carousel completely breaks down after navigation. **(This may be the case for carousels before this update)**
5-After the update, the style of the carousel navigation points will be damaged (if you turn the navigation point option on and off, their style will be corrected)
6- **This bug is very important.** A new option (https://prnt.sc/26xpiy6) has been added in the carousel section, which causes a problem when loading the page. This option causes the distance between the carousel to increase and decrease when loading, and hits the ui hard. **Of course, this option is not needed, because in the style tab, we have the option to control the distance between the columns.** Please fix this. It has a very negative experience for users. Please watch this video and pay attention to the distance between the carousel when loading : 
https://user-images.githubusercontent.com/77163248/154479994-f286d6cb-7baf-4a82-9e6b-baa99fe0d145.mp4

7- A new option (https://prnt.sc/26xpu7h) to control the position of the navigation points has been added, which is great. But there is a drawback. The problem is that if we move it down, it will leave the widget. https://prnt.sc/26xpvm0
This is problematic in some cases. In fact, both the current mode and the previous mode are required (distance only from the top)
The video below is from the previous version. I move the navigation switch down, but the navigation points do not come out of the widget. Note the widget background :

https://user-images.githubusercontent.com/77163248/154483739-6c81db3d-d879-4ce9-bd56-5c0e74345047.mp4

In fact, we need a new option to determine if navigation points can be moved out of the widget box. If we choose no, it will be the same as before. If we select yes, like the new version, it can be moved from the widget to outside the widget box. This is very important. Do you need more explanation?

8- In general, the carousel has moved slightly in the opposite direction. Of course I use RTL and it has moved to the left.
https://prnt.sc/26xqh68 (This may be related to number 3)

These bugs were only related to the carousel widget. There are several other cases that I will update this issue. thank you 🌹

**Comment by 79ho3ein** [comment]
9- In the coupon form widget on the payment page, the field and button do not follow the code > float: right or left. See this image : https://prnt.sc/26xqmlq
I considered both the button width and the field width to be 30%. As you can see in the picture, there is gap between them, while they should stick to each other. (Stick on RTL on the right, on LTR on the left)

**Another point is that I consider the button width to be 30% and the field width to be 70%. But they are on top of each other. I do not know if this is a bug or not!**    https://prnt.sc/26xs71u

10- In the new update, when the shopping cart page loads, the coupon buttons are loaded in animation. It's not really animation, but they ruin the interface. Watch the video below. Each time the page is reloaded, the button and the coupon field appear very badly.

https://user-images.githubusercontent.com/77163248/154486989-a3c9da9d-ca7d-4cc0-933f-8664fdc27733.mp4

11- In the city and district field, two items have been added (black dots) https://prnt.sc/26xr6m0
Problem area : https://prnt.sc/26xr5lm
In fact, these are the arrows that look like this : https://prnt.sc/26xrcfi
In the new version, the arrows have been moved to the opposite side and their shape has changed : https://prnt.sc/26xre1s

12- In the Add to Cart button, after clicking the button, the spinner is not in the center. Has moved up. In this picture it is quite clear : https://prnt.sc/26xr85l

13- If we enter the payment page without registration, an anonymous section will be displayed. https://prnt.sc/26xrhww
**This section of the checkout page appears in this section**



**Please let me know if you were unsuccessful in reproducing any of these bugs. thank you**

**Comment by UraraReika** [comment]
1, 3, 4, 5, 6, 8, 11 - We have checked this and everything seems to be working correctly. Perhaps this is related to your site. You can [contact](https://support.crocoblock.com/support/home/) our support team.
2 - This option was useless for carousel and in some case broke layout. Instead we add this [control](https://tppr.me/b6FSQ).
7 - This feature can be useful. But if you know that it can cause some problem then  move it wisely. In fact you can use built in [padding controls](https://tppr.me/ft3Ws) to remedy this shortcoming.
9, 12, 13 - Fixed.
10 - This is due to the order in which the styles are included on the page. You can use this [solution](https://tppr.me/8r6hb) to get around the problem. Or use filter hook to enable this option only for Cart template. Feel free to contact our support team.

**Comment by 79ho3ein** [comment]
hello @UraraReika , I apologize for the delay, I was working on finding a solution to reproduce the bugs ...

**According to the bugs reported above, I will move on.**

1- It does not matter at the moment.

2- Excellent. But it could be better. I will explain about it later.

3- I explored this problem in more depth. This bug occurs in RTL. If we activate the carousel in RTL, the carousel will be tilted. Watch the video below. **First is LTR. Then I reload the page to convert it to RTL**. Then look at the corners of the carousel. It is quite clear that it moves slightly to the left.

https://user-images.githubusercontent.com/77163248/155017953-f5e44a93-8dd0-4738-b4eb-98f79a9c4783.mp4

**At the end of the video, I went back to LTR and the problem was fixed.**

4- As in case 3, this problem only occurs in RTL.

5- It does not actually crash, after each update, the navigation points are automatically deactivated! Reactivate it. This is actually a bug.

6- In this option, the value is not inherited well : https://prnt.sc/26xpiy6
I do not know exactly what the problem is. I just know the values ​​are not well inherited. For example, "Space Between Slides"
I set it to 20 on the tablet, and leave it blank on the mobile. Naturally, 20 should be applied to the mobile as well. But this does not happen. This is why this bug occurs. (Video in 6)
I set it to 20 on the tablet. I also set it to 20 on my mobile and the bug was fixed. The problem is that the value inheritance property has a problem In the "Space Between Slides" option. **This is a problem even in LTR.**

7- it is good. But the previous situation was much better. With respect😎

8- As in case 3&4, this problem only occurs in RTL.

9- Fixed

10- Thank you for your solution

11- This bug occurs when we use universal color in the fields :  https://prnt.sc/OHopGT3zEZBT
**Note that this bug does not occur in the elementor editor. But also visible on the website.**

There is another bug in this section. Once the list is opened, the arrow will be hidden. The video below : 

https://user-images.githubusercontent.com/77163248/155024236-e726375b-b3dc-4ca8-92a3-d68e1d3e01eb.mp4

12- Fixed

13- Fixed
 


**Finally, I add 3 bugs and a request to the above. In the new version, two bugs are created when the carousel is activated. Whether RTL or LTR **

1- Like numbers 3 & 4 & 8, the carousel moves. In the video below, look to the right of the carousel. I will mention it in the video.

https://user-images.githubusercontent.com/77163248/155025896-88fe13e0-348e-4c74-b8d4-1ab2b090f3e5.mp4

As you can see in the video above, everything was fine at first. But when I turned on the carousel, the widget moved slightly to the right. If you pay attention to the product border on the right, the movement is quite clear. Disable the carousel, the problem is solved.

2- By activating the carousel, the product box loses its shadow. Whether in normal mode or in hover mode. In the video below it is quite clear **Of course, it is not seen in the elementor editor. But on the website a little better.**: 

https://user-images.githubusercontent.com/77163248/155027037-d0c98d06-8231-4ab4-a202-2ceb519850d6.mp4

3- If we activate the carousel, there is no space around : https://prnt.sc/-n-qW2DykP5l
We can only use padding. But there is still a problem. Watch the video below. I added code for the product hoverbox mode to detect the problem. **After hovering over the product box, the product box moves up 2 pixels. But why is its border hidden at the top? where is she going? While there is padding.**

https://user-images.githubusercontent.com/77163248/155031331-0ad5674d-c2e6-447f-b661-7fa25e404643.mp4

Even this problem causes the shadow of the product box to be hidden. The shadow is trapped under the product box. https://prnt.sc/BO3tvWahfYVw

I will make this suggestion in a new issue so that we can better address it.


**I really apologize for the length of this report. The new version, while great, also had a lot of bugs. Many and very strange bugs. I have been writing this report for 5 hours .... I hope it is successful in reproducing and fixing it. If possible, please publish the result of the bug reproduction as before.**

**Information**
Theme : hello elementor 2.4.2
Wordpres 5.9
Active plugin : jet woobuilder update - woocommerce update - elementor update - elementor pro 3.5.2

Thank you

**Comment by UraraReika** [comment]
3, 4 - Fixed. Will be available in nearest release.
5 - Fixed, if you update from 1.11.* to next release (1.12.1) everything will be ok.
11 - Colors applied for all borders if you use global Elementor colors. We need only top border color. Arrow disappear because of select 2 default styles.

***
1 - This is how browser handle float numbers in width. You can fix this issue playing around with space between.
2, 3 - https://tppr.me/MI2h0 this options become enable for carousel and this should solve overflow problems.

**Comment by 79ho3ein** [comment]
you :**https://tppr.me/MI2h0 this options become enable for carousel and this should solve overflow problems.** 

Yes, it solves the problem completely. Like previous versions that had no problem. But overall, this solution (#4925 > A&B) is great for all occasions.

you : **11 - Colors applied for all borders if you use global Elementor colors. We need only top border color. Arrow disappear because of select 2 default styles.**  &  **This is how browser handle float numbers in width. You can fix this issue playing around with space between.**

But it was true in the previous version!


In any case thank you for your attention my friend.

**Comment by 79ho3ein** [comment]
excuse me @UraraReika , Another case ... **Of course, this is related to the version before 1.12.0.** 
I wanted to report this for a long time, but I had no idea how to express it better.

As you know, before activating the carousel, the products are displayed in grid. In the grid, if we give a shadow to the product box (https://prnt.sc/sszvFIPeXLgV), this shadow, if it is wide (https://prnt.sc/aOfX6RJGODVY), crosses the widget border, and this is true. But when we activate the carousel, these shadows are trapped in the widget frame. This imposes many limitations. 
**It looks like a bug. Isn't that so?** Please watch the video below :

https://user-images.githubusercontent.com/77163248/155136744-08842a48-7bcb-4792-9077-039671d95bcc.mp4

**Comment by 79ho3ein** [comment]
Another bug in version 1.12.0

If we update hello elementor to 2.5.0, the automatic update **on mobile and tablet** will encounter a problem. In such a way that the update button is displayed again with a different appearance.

**Comment by UraraReika** [comment]
> 

This is how Swiper slider works.

**Comment by UraraReika** [comment]
1.12.1 release

**Comment by 79ho3ein** [comment]
thank you @UraraReika
