### ISSUE TITLE
In Woocommerce Single Product we need a Table to show the variations  in a such way Table columns names would be from Meta Fields from the Parent Product

### ISSUE THREAD

**Issue by Fdiversos** [CrocoBlock/suggestions#4890]
Hi Development Team

After a long and extremely detailed support journey Crocoblocks and us got a conclcusion that a new feature is necessary.

We need a custom feature to allows us to name Table Columns dinamically from Parent or Child Product Meta Fields
   
![image](https://user-images.githubusercontent.com/9354763/154494723-bd1406cd-a037-4690-a610-fe42ffaacd2a.png)

Parent product contains meta fields (text type).
   -var 1 (child)
   -var 2 (child) 
   -var 3 (child) 
 
On single parent product template display children products with labels from the parent product meta field.

**Comment by Fdiversos** [comment]
Considering that a custom new feature could take a long time, could you please guide me in which and where in code file (.php) shoud i add a way that the label of the column can be captured from another custom field in the metabox for the WC Product that we have created.....

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
