### ISSUE TITLE
Critical Wordpress error - JetCompareWishlist

### ISSUE THREAD

**Issue by Zaanone** [CrocoBlock/suggestions#4892]
When I do a health diagnosis of my website. I get two critical errors. When I turn off JetCompareWishlist the critical errors disappear. When I turn JetCompareWishlist back on, the critical errors appear again.

JetCompareWishlist 1.4.5. I reverted back to 1.4.4. It gives the same critical errors

![image](https://user-images.githubusercontent.com/82780539/154513810-c4b1f296-705d-4cfe-b704-da248d04a940.png)

`
### wp-core ###

version: 5.9
site_language: nl_NL
user_language: nl_NL
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-active-theme ###

name: Hello Elementor Child (hello-elementor-child)
version: 2.4.2.1642757367
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
parent_theme: Hello Elementor (hello-elementor)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, menus, automatic-feed-links, title-tag, html5, custom-logo, editor-style, align-wide, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider

### wp-parent-theme ###

name: Hello Elementor (hello-elementor)
version: 2.5.0
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash

### wp-themes-inactive (3) ###

Twenty Twenty: version: 1.9, author: het WordPress team
Twenty Twenty-One: version: 1.5, author: the WordPress team
Twenty Twenty-Two: version: 1.0, author: het WordPress team

### wp-mu-plugins (1) ###

WordPress automation by Installatron: author: (undefined), version: (undefined)

### wp-plugins-active (24) ###

Add-on: Track Sales - Back In Stock Notifier for WooCommerce: version: 1.2, author: codewoogeek
Add-on: Unsubscribe - Back In Stock Notifier for WooCommerce: version: 1.2, author: codewoogeek
All-in-One WP Migration: version: 6.77, author: ServMask (latest version: 7.55)
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: version: 2.6.1, author: codewoogeek
DynamicConditions: version: 1.5.1, author: RTO GmbH
Elementor: version: 3.5.5, author: Elementor.com
Elementor Pro: version: 3.6.2, author: Elementor.com
FileBird: version: 4.9.9, author: Ninja Team (latest version: 4.9.9.1)
Filter Everything PRO: version: 1.6.0, author: Andrii Stepasiuk
JetCompareWishlist For Elementor: version: 1.4.4, author: Crocoblock (latest version: 1.4.5)
JetElements For Elementor: version: 2.6.2, author: Crocoblock
JetEngine: version: 2.11.3, author: Crocoblock
JetMenu: version: 2.1.6, author: Crocoblock
JetSearch For Elementor: version: 2.1.15, author: Crocoblock
JetTabs For Elementor: version: 2.1.15, author: Crocoblock
JetWooBuilder - Custom Quantity Selector: version: 1.0.0, author: Crocoblock
JetWooBuilder For Elementor: version: 1.12.0, author: Crocoblock
Loco Translate: version: 2.5.8, author: Tim Whitlock
OoohBoi Steroids for Elementor: version: 1.9.0, author: OoohBoi
ReviewX: version: 1.4.3, author: WPDeveloper
ReviewX Pro: version: 1.3.2, author: WPDeveloper
WooCommerce: version: 6.2.0, author: Automattic
Woocommerce Side Cart Premium: version: 3.1, author: XootiX
Yoast SEO: version: 18.1, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Niet beschikbaar
imagemagick_version: Niet beschikbaar
imagick_version: Niet beschikbaar
file_uploads: File uploads is turned off
post_max_size: 32M
upload_max_filesize: 32M
max_effective_size: 32 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 4.18.0-305.17.1.lve.el8.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.27 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 32M
php_post_max_size: 32M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.22-MariaDB-log-cll-lve
client_version: mysqlnd 7.4.27
max_allowed_packet: 25165824
max_connections: 500

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

**Comment by 79ho3ein** [comment]
+1
