### ISSUE TITLE
In the checkout form, you can not delete the country field

### ISSUE THREAD

**Issue by alisadrona** [CrocoBlock/suggestions#4893]
**Describe the bug**
In the jet woobuilder plugin checkout field, if we delete the country field, the shipping amount will not be calculated. The only way is to hide the country field.
I think an option is needed to hide the country field.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team. Thank you!

**Comment by Michaelgimii** [comment]
@UraraReika 
I experience this bug on the desktop. True on mobile.
