### ISSUE TITLE
JetFormBuilder send media as attachment

### ISSUE THREAD

**Issue by seangolding1987** [CrocoBlock/suggestions#4896]
It would be of huge benefit it media files could be sent as an email attachment rather than inside the email. Contact Form 7 does this very well: https://blog.cf7skins.com/contact-form-7-file-attachments/

This would solve a LOT of issues for me when clients need to upload PDFs or images etc. to emails

**Comment by hamed-azimi** [comment]
This indeed is a must. We let ANY visitor (including guests) attach files in one of our forms (without storing them in the Media section of the site). and the email is sent to the staff of one of the departments. and we need to attach those files to the email. But unfortunately, it's not currently possible.

**Comment by girafffee** [comment]
This feature was added in version 2.1.0
