### ISSUE TITLE
Date Range Filter - border styling

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4897]
When I select an input field in a Date Range filter, the border changes in color and gets a radius. I am not able to customize the "active" border in the settings of the widget. Please, see my screenshots to understand what I am referring to: https://prnt.sc/1ISW2HWuqI6Q
You can see that the border is different for all browsers. For example, in another browser, the border gets purple: https://prnt.sc/p_VgvzAlkDYA

I would appreciate it if you could add some controls for the active border to the Date Range filter.

**Comment by Floydtm** [comment]
We've [checked](https://prnt.sc/IzR8YmtYNo7i) your request and can't get the bug. Please contact our support team to resolve this issue.
