### ISSUE TITLE
Add the ability for Listing Grid Injection Elements to specify different Item number option for tablet and mobile devices

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [CrocoBlock/suggestions#4900]
For now I couldn't setup different order for Listing grid injection elements for different devices (tablet/mobile etc). It would be very useful.
See the example screenshots here: [https://imgur.com/a/DVQKDpe](https://imgur.com/a/DVQKDpe)

**Comment by petrovui** [comment]
Мне уже отвечали на этот вопрос. Эта функция не привязана к размеру экрана. Если хочешь это реализовать - копируешь для каждого разрешения виджет и меняешь его настройки )
