### ISSUE TITLE
JetEngine: Dynamic Visibility (If "Product Purchased" show or hide Section)

### ISSUE THREAD

**Issue by startupweb** [CrocoBlock/suggestions#4902]
Hello,

I have messaged / live chatted with Crocoblock and they said this feature is not yet available. 

Divi actually has this already available on their "Divi Conditional Options"
https://youtu.be/AM4slNGJ2QI?t=205
- WooCommerce Conditional
- Product Purchased

**Please, describe the feature request, making it clear to understand.**

I would like to have the ability to hide a section and only show it if a certain item is purchased.

For example.  (Pay Per View, Video or Blog Post)
- A video is embedded on the Product Page and the section is hidden to users who have not purchased the product.
- Once the product has been purchased by the user, the video will be shown.

**Add an example of where this feature is already implemented. **

This should be appear in Dynamic Visibility on JetEngine.  I think it would be a fantastic addition to offer a way to add a "PayWall" feature using JetEngine and WooCommerce.

**Feel free to add any videos, links, screenshots to illustrate the requested feature.**

Introducing Divi Condition Options!
https://youtu.be/AM4slNGJ2QI?t=205
- You will see that there is a "Purchase Product" option

Thank you for considering this,
   wiL

**Comment by rtpHarry** [comment]
Challenge accepted :) 

I just published a plugin that will do this. Read about it here:

  - https://github.com/rtpHarry/jet-engine-dynamic-visibility-woo-user-purchased

Download it here:

  - https://github.com/rtpHarry/jet-engine-dynamic-visibility-woo-user-purchased/releases/tag/v0.5.0

I've released it as v0.5.0 as I have barely tested it, but it's late and I wanted to push the release out tonight for you to experiment with. 

Please open an issue over on the repo if you find any problems with it.

**Comment by startupweb** [comment]
Thanks for that, I was curious about it.  

I hope It gets integrated into the system and becomes as dynamic as how Divi's function is.  

Thanks @rtpHarry

**Comment by CaseFixedWebdesign** [comment]
+1 This would be a great addition to the dynamic visibility options.

**Comment by Crocoblock** [comment]
Hi, this was added in version 3.2.7

**Comment by bobras6** [comment]
Hello, I can't find this option and my plugin is the latest updated version
Please tell me exactly where this option was added?

**Comment by UraraReika** [comment]
Hello @bobras6, you can find this condition here - https://tppr.me/p2dOK4, https://tppr.me/nNYlHN

**Comment by bobras6** [comment]
Hello @UraraReika , thank you for your reply
Yes, I check in this section, but it is not there, see the attached file.
https://postimg.cc/ftqbj7X1
Plugins I installed:
JetEngine
JetEngine - Custom visibility conditions
JetWooBuilder For Elementor
WooCommerce
Elementor Pro
Elementor

**please guide me**

**Comment by bobras6** [comment]
**I found the problem** @Crocoblock
The problem is from the new update
By installing the previous version, i.e. 3.3.1, the problem was solved and the option was added.
Please check the new version, it has bugs.

**Comment by bobras6** [comment]
I am still waiting @Crocoblock
@UraraReika Did you not see this problem?
