### ISSUE TITLE
[Bug] Unpublished Taxonomies Appear in Filters

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#4903]
**Describe the bug**
When adding new taxonomies to a draft post, those taxonomies immediately propagate to any JetSmartFilters that use the taxonomies. This happens even when 'Show Empty Terms' is not selected in the filter settings. The result is that terms (which are empty since the post is not live...even appear empty in the Admin Panel) are visible to users. 

**To Reproduce**
This behavior can be reproduced by creating a draft post, assigning it a *new* taxonomy, and checking the JetSmartFilters that use that taxonomy. 

**Expected behavior**
Taxonomies that are otherwise not attached to *published* posts should not appear in filters until the corresponding post is published.

**Comment by SargasTM** [comment]
Перепроверьте

**Comment by Floydtm** [comment]
@yxknmyo, We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by ghost** [comment]
Appears to be working on my end now, too. Thank you both!
