### ISSUE TITLE
Add-To-Cart Widget for JetEngine

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4908]
I totally get it: JetEngine is not built to specifically work with Woocommerce, and I can use JetWooBuilder to have full WC-related features.

But here is the thing: JetEngine is built to create Listings, and one of the important usages of it is to create product tiles. Adding a full add-to-cart widget that has a quantity field as well, will make this very useful. It adds a maximum of 2kb to JetEngine plugin's total size, but it helps us get rid of a full plugin called JetWooBuilder, which we literally don't use for anything other than adding the add-to-cart to the listings that we built using JetEngine. (it really doesn't make sense to have such a big and full plugin active on the website just to add a button. I hope it makes sense to you as well).

**Comment by lifeact** [comment]
+1

**Comment by simonvanoordt** [comment]
Yeah that'd be very handy

**Comment by SanyaOnline** [comment]
+1

**Comment by imeco** [comment]
Good point. Also good to rethink what we have, once in a while

**Comment by anythingituk** [comment]
+1

**Comment by tim-getfetchr** [comment]
+1

**Comment by acaballerop** [comment]
+1

**Comment by BaronVonDerpsalot** [comment]
+1

**Comment by UraraReika** [comment]
In JetEngine 3.0.8 we added Add to cart source for Dynamic link widget that used as Add to cart. You can fell free to check it out.
