### ISSUE TITLE
JetEngine | Profile Builder | JetFormBuilder | Max. Post Restriction (BUG?)

### ISSUE THREAD

**Issue by alexander-pankart** [CrocoBlock/suggestions#4909]
I have set the restriction for 1 post, but users can create more than 1 post.
CPT, JetFormBuilder, JetEngine Profile Builder

![image](https://user-images.githubusercontent.com/69971188/154844791-5eaae51c-66a8-4225-b4fa-6262af8458b4.png)

![image](https://user-images.githubusercontent.com/69971188/154844825-fce42b40-9be9-4415-8d37-d39b68f2f201.png)

![image](https://user-images.githubusercontent.com/69971188/154844873-b387f48a-cc62-446f-989b-0722d6e634a0.png)

![image](https://user-images.githubusercontent.com/69971188/154844900-67c77af7-35be-4338-9794-0ed9fe9b36bb.png)

Am i doing something wrong?

Thank You!

**Comment by girafffee** [comment]
Fixed in version 3.0.3 (JetEngine)
