### ISSUE TITLE
jet woobuilder pagination Carousel.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4910]
**Describe the bug**

In the new version, if we give the paging points a negative distance (To move down), they will go beyond the widget margin. This is not really good. Because this will cause the standard mode of this widget to be lost. If the pagination points leave the widget box, they enter the next widget (bottom widget)
Please correct this. It is better to be like the previous version and the pagination points should not be left out of the widget box. In this case, if we push the pagination points down, the widget frame will move with it. So these points will never go beyond the widget box.
This is so important to me that I prefer to stay in the previous version. Because as I said above, this has caused the product grid widget to go out of its standard mode.

**Comment by UraraReika** [comment]
This feature can be useful. In fact you can use built in [padding controls](https://tppr.me/ft3Ws) to remedy this shortcoming.

**Comment by Michaelgimii** [comment]
Is it possible to add a feature that we can choose between past and present conditions? Using padding in this situation is not really logical.
