### ISSUE TITLE
jet smart filters - elementor pro popup Scrolling problem.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4912]
**Describe the bug**

I'm not sure if this bug is from jet smart filters or not! But if we use the pop-up elementor to display filters, filters that have the ability to scroll (due to the large number), make it difficult to navigate the filters!

**To Reproduce**

1- Add different filters to make the pop-up scroll. (On mobile)
2- For each of the filters, add a few options, so that they can be scrolled.
3- After the above steps, enable the scroll option for filters.
4- Now with the mobile, open the pop-up filters and scroll to access the lower filters.
5- If you place your finger on the filters for which scrolling is enabled to scroll, scrolling will not occur properly.

Note, the problem is not scrolling the options of a filter. But also scroll to access the lower filters. For example, if we use 10 filters in this pop, we have to scroll to access the lower filters. And this is going to be difficult.

**Comment by SargasTM** [comment]
In this situation scroll within scroll
Filters and popups use standard scrolls, how they behave depends only on the browser and device
