### ISSUE TITLE
Stop Jet-Woo-Builder from applying to all products by default

### ISSUE THREAD

**Issue by jakecr94** [CrocoBlock/suggestions#4913]
HI there,

Crocoblock support have requested that I post my feature-request here.

We have a large e-commerce store. For A/B testing purposes, we first need to test any new product-page design before we can permanateley apply it. 

I spent a lot of time creating a new PDP design, but only want to apply the template to a couple of products (we have 50+). However by default, the design applies to all of our products which is not want we want / can allow. 

Would it be possible to prevent the Jet-Woo-Product-Page-Template from applying to all product-pages, and then we can simply apply it to 2-3 products to start with?

Thanks a lot
Jake

**Comment by UraraReika** [comment]
Hello @jakecr94 !

Each product in admin area has this [options](https://tppr.me/qXyqg). So you can set JetWooBuilder template to particular product.

**Comment by jakecr94** [comment]
Hi, thanks, I was aware of this, however still, the template is by default applied to all of our products. Is it possible to disable this and then individually assign the template to the products that we want to use the template for, but for the other products keep our standard template?
thanks

**Comment by UraraReika** [comment]
Set global template options for Single product like [this](https://tppr.me/Kq2jZ).
