### ISSUE TITLE
Crocoblock settings page - Element active/disabled checkboxes for each plugin

### ISSUE THREAD

**Issue by 05edgarBlw** [CrocoBlock/suggestions#4919]
Right now, we can disable separate widgets, we don't need which is great, but if you have y large site with lots of content and pages etc... it can be very overwhelming and confusing to remember which of these modules/elements/widgets you are using currently on the site. And the risk is high to turn something off, that you are actually using, and a part yo you website is destroyed now and you even don't know it. 

So you should have a little hint after each module if this widget/feature is currently active/used on this particular website. Then we can disable things with good conscience and it would really help saving time

Thanks :)

**Comment by Floydtm** [comment]
We are working on it, stay tuned
