### ISSUE TITLE
Jet Engine Meta Field

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#492]
Good afternoon, please consider the possibility of a small revision in arbitrary fields of the Jet Engine

1.Automatic conversion of Cyrillic to Latin - https://prnt.sc/ozms27

2. If the Name / ID field already exists with such a name, then automatically add at the end of 1 or at least inform that such a field already exists.

At the moment, if there are many fields and accidentally gave the same name to several fields, then the fields will not work and it is not immediately clear where to look for a problem for those who do not often work with Jet Engine and do not know this feature of the plugin.

/*Оригинал на русском*/
Добрый день, прошу рассмотреть возможность небольшой доработки в произвольных полях Jet Engine

1.Автоматическая конвертация кириллицы в латиницу - https://prnt.sc/ozms27

2.Если поле Name/ID уже есть с таким названием, то автоматически добавить в конце 1 или хотя бы сообщить, что такое поле уже существует. 

На данный момент если много полей и случайно дал одинаковые названия нескольким полям, то поля не будут работать и не сразу понятно где искать проблему для тех, кто не так часто работает с Jet Engine и не знает этой особенности плагина.

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0
