### ISSUE TITLE
Ability to create templates for backend dashboard pages

### ISSUE THREAD

**Issue by 05edgarBlw** [CrocoBlock/suggestions#4920]
If you have clients and want to give them some instructions and help information, you easily can do that via creating a dashboard widget.

I always using some php for this, putting a video and some text links in it, but its really time consuming tif you want to style this entire thing. So please give us the functionality inside an external module in JetEngine for example to create templates that are later displayed as dashboard widgets and have options for dynamic visiblity like if user role is ..

**Comment by Lonsdale201** [comment]
https://wordpress.org/plugins/dashboard-welcome-for-elementor/
