### ISSUE TITLE
Space Between columns & rows for grid & Carousel - jet woobuilder. 

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4925]
**Before adding a new feature request, please, make sure you’ve checked:**

hello

In the new version, for grid these option : https://prnt.sc/2kCp8NZZC1xM , And if you activate Carousel, we will have this option :
https://prnt.sc/t4StWPFwmgqN
Therefore, we have to control the grid and the carousel separately. But this is not really good. In addition to the complexity, it has caused a lot of bugs in the serious version. Which I have dealt with in #4888.

I have a suggestion for developing this option, please review it. Using this feature, we can control "Space Between columns" in the carousel and grid seamlessly.

1- Please re-add the column tab to the product grid: https://prnt.sc/hy3UVyW5pHkM. (Of course, the names of the columns change. Because it does not only include controlling the distance of the columns.)

2- Great if you remove this option (https://prnt.sc/_DATgYalnRTw) from this section, and move it to the Style tab > Columns. In the Style tab > Columns , the name of this option changes from "Space Between Slides" to "Space Between Columns". Using this option, we can control the distance between the columns. Both on the grid and in the carousel.

3- **In this section, we need three options.**
A : Space Between columns (Both for carousel and grid) : https://prnt.sc/SxwkNytsEoL4
B : Space Between rows (Both for carousel and grid) : https://prnt.sc/N6FGl3D_O_gn
C : space around (Both for carousel and grid) : https://prnt.sc/FECFaxTcfInc
This option is actually the same as Padding. But it happens inside the widget and it will be much better. And of course there is a reason I really do not know how to describe it!

Using these 3 options, we can easily control the carousel & grid. Isn't this really better than the current situation?

You may be wondering if we have only one row in a carousel. So why do we need item A? This option can be deactivated when we activate the carousel. But on the net, we need all three of the above options.
Of course, in the future, we will also need Space Between rows in the carousel. Because this feature will be added : #4738

I hope you agree with that.

Thank you

**Comment by 79ho3ein** [comment]
**One more point**

Currently in the grid, the conditions are not suitable at all! See this image : https://prnt.sc/QUVfMcfIduoW
I set the columns padding to 50 to make it look clearer. **We have 4 different distances in different parts of the grid!**
**Left and right grid** - **Up and down grid** -  space between rows - space between column.
This is not really good.

By adding the above 3 cases, all cases will be solved in the best possible way. Because we have separate control between space between rows, space between column and space around separately.

**Comment by UraraReika** [comment]
A, B - I merged this issue with #4888, which is on the same subject so we could deal with it more efficiently.
C - https://tppr.me/ejTRy

**Comment by 79ho3ein** [comment]
> A, B - I merged this issue with #4888, which is on the same subject so we could deal with it more efficiently. C - https://tppr.me/ejTRy

Yes, c already exists. It is true.
But it would be great if A&B could be added for both grid and carousel.

thank you
