### ISSUE TITLE
product grid box shadow - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4926]
**Describe the bug**

I'm sorry to open a new issue for this. Because it's important...
In the new version, the product Box shadow in the grid works quite well. But when I activate the carousel, it completely disappears. (Of course, in the elementor editor, the shadow is completely hidden. But on the website it is a little better, there is a problem) The problem is quite clear in the video below.
But a very important point! In the grid, the shadow of the product box is completely scattered around the product. But this is not the case with the slider and there is a problem. I even padding the product grid widget, but there is still no shadow. Watch the video below :

https://user-images.githubusercontent.com/77163248/155117049-bc8b79ec-09ed-473f-aa4b-1acb422ad2e3.mp4

As you can see in the video above, even when applying padding to the product grid widget, the surrounding shadow (such as grid) is still not displayed. There is definitely a big problem here.

**Comment by UraraReika** [comment]
I merged this issue with [#4888](https://github.com/Crocoblock/suggestions/issues/4888), which is on the same subject so we could deal with it more efficiently.
