### ISSUE TITLE
JetTab Classic Accordion Styling

### ISSUE THREAD

**Issue by Paulboateng91** [CrocoBlock/suggestions#4929]
Hi team 

Please could you kindly improve the classic accordion styling options?

I was struggling to remove the border (see below)
![image](https://user-images.githubusercontent.com/83450954/155120421-d45017f8-fe36-4918-900f-a0f8fa1b2778.png)

Please see the reference site and design intent below:
[https://mejuri.com/gb/en/shop/products/bold-croissant-dome-huggie](url)
![image](https://user-images.githubusercontent.com/83450954/155118543-10beccfa-9106-4a55-976f-bcda265c2d51.png)

Much appreciated.

Regards
Paul

**Comment by Floydtm** [comment]
Set border width to 0
