### ISSUE TITLE
🔥Price range widget is not compatible with elementor popup - jet smart filter / jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4936]
**Describe the bug**

I am using the product grid widget of the jet woobuilder plugin to display the product archive. I also put the product filter on the elementor popup to be used on mobile.
In the new version, the jet smart filters plugin is compatible with the elementor pop-up. All filters are compatible with elementor popup.
But the **price range widget** is not compatible.
**If we just activate this filter** and set the desired price, then close the pop-up and open it again, the filter removal button will not appear!
The bug is quite obvious in the video below. (In the video below, I also use the checkbox filter to see the difference.)

https://user-images.githubusercontent.com/77163248/155229778-ba30dad2-afdc-4932-a8c2-d07897b5d887.mp4

Another bug in this widget in the new version is that if we consider the shadow for the price range of the widget knobs, part of that shadow will not be displayed. Of course in one of the handles. https://prnt.sc/ETrwphcy-z2J
**This bug only occurs in iOS browsers (Safari, Chrome, etc.).**

**There is another bug in this version that I reported here : #4912**

**Comment by Michaelgimii** [comment]
+1
@MjHead , @Floydtm

**Comment by Michaelgimii** [comment]
excuse me , Why did this issue close?

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by Michaelgimii** [comment]
> This has been added to the plugin.

But I tested this bug in the new version (2.3.11) and it still exists!

**Comment by Floydtm** [comment]
This will be added in the next updates
