### ISSUE TITLE
JetWooBuilder (Products Grid) - Ordering

### ISSUE THREAD

**Issue by brjmichael** [CrocoBlock/suggestions#4937]
It would be interesting and very useful a way to sort the listed products when in 'Use Current Query' mode. That way, I will have more control over how I want to display products on my store page. Here's a tip :)

![jwb](https://user-images.githubusercontent.com/30130470/155263090-e23d8f04-5469-4b06-9084-ad2702fe3ba9.png)

**Comment by UraraReika** [comment]
Hello @brjmichael !

If you use `Current Query` option you can control order from WooCommerce [customizer](https://tppr.me/vUktf).
