### ISSUE TITLE
Add Dynamic Field to Email

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#494]
Hello, is it possible for you to make a finalization here too - https://prnt.sc/ozqvnd display Email from Options Page - https://prnt.sc/ozqxek?

/*Оригинал*/
Здравствуйте, возможно ли с вашей стороны сделать доработку и сюда - https://prnt.sc/ozqvnd выводить Email из Options Page - https://prnt.sc/ozqxek ?

**Comment by MjHead** [comment]
You already can do this:
1. Add hidden form field and set Default Value for this field from Jet Engine / Options Page dynamic tag - http://prntscr.com/p46atm, http://prntscr.com/p46b6s
2. Then use shortcode to pass value of this field into email settings - http://prntscr.com/p46cqk, http://prntscr.com/p46d1z

Unfortunately Elementor Pro for some reason don't allow to use dynamic tags directly on field "To", so at this moment this is only way to pass Option value into Form actions settings
