### ISSUE TITLE
New Add to Cart Button + - for jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4940]
The Add to Cart button is too old. Now all websites and store templates have more beautiful Add to Cart buttons. https://prnt.sc/ZWzCO6fKLEgs
Customers ask us to do this, but we can not add such a button. Adding this feature to the woobuilder jet core is not really hard for you. But it is very important and necessary.
Please think about this. In addition to all this, the old button severely destroys the user interface. Especially on mobile. This is really bad.
Please update this shopping cart button, please

**Comment by UraraReika** [comment]
https://crocoblock.com/freemium/tools/ -> https://tppr.me/C0OIp

**Comment by Michaelgimii** [comment]
thanks @UraraReika , Will this be added to the plugin core in the future?

**Comment by 79ho3ein** [comment]
hi @UraraReika , Can I report bugs in this add-on or have a new suggestion for it?
