### ISSUE TITLE
Suggestion for JetEngine: add information from a Post Type field in Link.

### ISSUE THREAD

**Issue by brjmichael** [CrocoBlock/suggestions#4942]
### The following possibility would be useful and very interesting:

In the link of a Title insert the content of a post type field.

Example:

I have a Post Type titled 'Customers'. I have a field in this Post Type titled 'phone number'. Considering this information, I would like to do the following in a Listing:

Get for the information of a specific customer and use that in the link. The idea is to use a specific customer's phone number to add it to the WhatsApp URL.

Would be like this:

Widget: `Title`   "Talk to the customer"
URL: wa.me/`%phone-number%`

I appreciate the opportunity.

**Comment by Floydtm** [comment]
Use Customize field output for this case https://prnt.sc/PfxA0MeMghdk

**Comment by brjmichael** [comment]
> Use Customize field output for this case https://prnt.sc/PfxA0MeMghdk

Perfect!  Is there a possibility to display more than one variable in a Dynamic Field (or otherwise) and display in Custom Field Output?  Example: `%s%`, `%field2%`, `%field3%`. 

 Thank you!

**Comment by Floydtm** [comment]
You can display several dynamic fields and create your own design

**Comment by brjmichael** [comment]
I understand.  How is it possible to define multiple variables from different Meta Fields in a single custom output?

I use the term `%s` to display a specific Meta Field.  How can I set several different variables in a single output?


Thank you for your dedication. **:)**

**Comment by Floydtm** [comment]
You cannot use multiple variables
