### ISSUE TITLE
User skin changes

### ISSUE THREAD

**Issue by paulpsky** [CrocoBlock/suggestions#4944]
Possibilities for users on the front end to choose whether to see a site in a dark theme or light theme. Like wise membership users to be able to select maybe how their front end page skin looks like, dark or light

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
