### ISSUE TITLE
jet woobuilder increases the amount of DOM elements.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4945]
I use the product grid widget on the home screen to display products. I have 7 carousels for desktop, and 7 carousels for mobile and tablet.
I compared the gt metrix score when carousels exist and when I deleted them. The statistics are very different and show the jet woobuilder greatly increases TBT as well as DOM elements.
When the product grid widget does not exist on the home screen, the statistics are as follows : **TBT > 60** - **DOM > 847**
When there is a product network widget on the home screen : **TBT > 155** - **DOM > 3157**

**Comment by UraraReika** [comment]
What are you comparing to? In my mind you take blank page and get TBT > 60 - DOM > 847, then you put 14 carousels in total in the page. And in every of this carousels you get at least 10 items i guess, and if you enable loop functionality you will get few extra items. So it's something about 140 dom elements but its just content wrap witch has inner elements and as a result you get DOM > 3157 and TBT > 155. What do you expect to get?

**Comment by Michaelgimii** [comment]
You mean this DOM value, 3157 is normal? With this number of widgets

**Comment by UraraReika** [comment]
I mean you use 14 carousels not 1. Products Grid item card itself has quite elements so as a result you get this huge number. So once again what did you expect to get? I sure then each carousel get at least 10 items. And again What are you comparing to? Please take some similar widget with carousel functionality and set of elements in a card from other plugin and check it. Then compare to our.

**Comment by Michaelgimii** [comment]
I tried this with the elementor product widget, the result was a bit close to jet woobuilder. This seems to be normal. The performance of the jet woobuilder seems normal. thanks
