### ISSUE TITLE
Map listing - Add Polygon Functionality 

### ISSUE THREAD

**Issue by Hitlii** [CrocoBlock/suggestions#4947]
###  In general these would be the options that would have to be done
- Add  a second option to make map listing with polygon (Polygon coordinates could be represented in a repeater field, maybe)
- Show a tooltip on Polygon Hover 
- Being able to **conditionally set the color of the polygon** using meta fields (example: if meta field 'status' is equal to  'sold' then the polygon should be on 'red' o gray )

This can have a lot of power in the administrative area and even in the sales area since it has these advantages

1. Visually we can see which properties are available and which are not
2. We can see what area the properties cover
3. We can add custom information to each polygon 
4. On sale dashboard we could make actions on each polygon; See the price of the property and other info, set property status, see purchase information etc. 

 
Something like here, we can see several polygons, the pink ones are the ones that are available and the ones that only have the perimeter are the ones that are sold
![image](https://user-images.githubusercontent.com/62224256/155414702-abf595ac-6ad1-40e1-9f1c-4257ce2d0ca6.png)

On Polygon Click we can see that a pop up opens, in this case it could be the same functionality that is being used now
![image](https://user-images.githubusercontent.com/62224256/155419635-af0bfb21-004f-48cd-84b4-584daa6198ec.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
