### ISSUE TITLE
Word Wrap option for product titles - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4948]
**Before adding a new feature request, please, make sure you’ve checked:**

hello

Currently, we have this feature to control the width of product titles in the product grid widget : https://prnt.sc/p2ZGuB2fHy-L
But this is a problem if the product title is long. For example, if the title of a product on the desktop is 1 line, on iphone 6 Or other small mobile screens, it is displayed in 3 lines. **Due to the width of the screen.**
But it would be great if you could add a new feature to the title width control. We can use this feature for products that have a long title. Using this feature, we can specify that product titles be displayed in only one line, or only in 2 lines. If it is more than 2 lines, it will continue like this ... as a result, it will not enter the third line. Because we set the title to be displayed in two lines only. This feature is extremely useful. Of course, this feature already exists in elementor, except that we can not specify whether the content should be displayed in two lines or one line. Are displayed in one line by default. This feature is called **Word Wrap**. Please watch the video below :

https://user-images.githubusercontent.com/77163248/155429664-87be785f-289d-4264-a3d6-5c4032e22b3e.mp4

All that is needed is that after activating Word Wrap in the product grid, we can specify that the title be displayed in several lines. 1 line, or 2 lines.

**code :** 

selector {
    overflow: hidden;
   display: -webkit-box;
   -webkit-box-orient: vertical;
   -webkit-line-clamp: 2; /* number of lines to show */
}

thank you

**Comment by Michaelgimii** [comment]
hello @UraraReika , Will this be added in the next update?

**Comment by Joliamendi** [comment]
hello @UraraReika , Will a new update be released? Will this feature be added in the new update?

**Comment by Joliamendi** [comment]
Dear jet woobuilder developers, There is a big challenge to display the product title, which will be solved by adding this feature. I understand that you have preferences for each update. But please keep this feature in mind for the next update. Currently, the current control over the length of product titles is very limited.
cheers

**Comment by Michaelgimii** [comment]
I have fixed this feature by using custom css for now. But I really hope this feature will be added in the new version. if possible. Crocoblock team🙏🌹

**Comment by Michaelgimii** [comment]
Hi @UraraReika , I have a question...

To use this feature, I use the following code. But in the iPhone browser (safari) at the end of the text... or three dots are not displayed. Is there a solution for that? thanks

.jet-woo-product-title {
overflow: hidden;
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: 2;
}

**Comment by UraraReika** [comment]
> Hi @UraraReika , I have a question...
> 
> To use this feature, I use the following code. But in the iPhone browser (safari) at the end of the text... or three dots are not displayed. Is there a solution for that? thanks
> 
> .jet-woo-product-title { overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }

This code was presented by @79ho3ein  and our team did'n test it. But this code is not universal and can cause some problems

**Comment by Michaelgimii** [comment]
Thanks for the reply, but is there any way we can use it temporarily before your official release?

**Comment by UraraReika** [comment]
> Thanks for the reply, but is there any way we can use it temporarily before your official release?

We will implement this functionality but like in Elementor without specific CSS properties. Because they can cause some problems in different browsers.

You can use this code this is more optimal 
```
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```
But in this case you will be able to get only 1 line

**Comment by Michaelgimii** [comment]
thank you olexander.
But that's exactly the point. Is there no way we can set the number of lines? This is something that is great and creates an advantage over the two existing options (words and letters).

**Comment by UraraReika** [comment]
> thank you olexander. But that's exactly the point. Is there no way we can set the number of lines? This is something that is great and creates an advantage over the two existing options (words and letters).

Solution that gives you opportunity to do this requires `box-orient` property set to `vertical` but `box-orient` is non-standart.

**Comment by Michaelgimii** [comment]
thank you again

As a last question, **-webkit-line-clamp: 2;** Fixes the line count issue. Do you not recommend it?
I've tested it in different browsers and it works fine. The only problem is that three dots are not displayed in the Safari browser.

**Comment by UraraReika** [comment]
> 

Unfortunately this option doesn't work without `box-orient: vertical`

**Comment by Michaelgimii** [comment]
Thank you for your time olexander.

**Comment by 79ho3ein** [comment]
Hi @UraraReika , i think displaying product titles in only one line (using word wrap) is not a logical method. Because the standard limit for displaying the product title (if the title is long) is two lines. No less, no more. But it would be great if we could set the number of lines to display, but as you said, it's not possible.
So wouldn't it be better if you add responsive support to the Length option in the products title? (screenshot below) This would be much better.
The only current challenge is that whatever value we consider for title length is applied to desktop, tablet and mobile. So if we can take advantage of responsive control, there will be no problem.

https://prnt.sc/cRhtpI-PGQ9F

thank you
