### ISSUE TITLE
jet search generates long URL on the search results.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4949]
**Describe the bug**

I use the jet serach plugin to search my website. But there seems to be a problem with the search results. When a user searches for a web page and the search results page opens, the browser's bar address will display a very long URL.
To test this, I removed the jet search widget and used the elementor search widget instead, then searched for a product (samsung) on the website. See the difference :

**Search in jet search :** https:/domain.com/?s=samsung&jet_ajax_search_settings=%7B%22search_source%22%3A%22product%22%2C%22results_order_by%22%3A%22relevance%22%2C%22results_order%22%3A%22asc%22%7D&post_type=product

**Search in elementor search widget :**  http s://domain.com/?s=samsung

**Comment by Floydtm** [comment]
This is not a bug

**Comment by 79ho3ein** [comment]
hi @Floydtm , That's right- this is not a bug. But is it normal to generate long links in search results?
I tested this in the elementor search widget and even on other websites but none of them created such a long link!
Am I wrong?
