### ISSUE TITLE
Jet Smartfilters: add geolocation search based on custom field

### ISSUE THREAD

**Issue by Bookyourroom** [Crocoblock/suggestions#495]
Hey, I'm a big fan of your recent edition jetbookings, as I run a booking platform myself. However, one thing that has been missing and would be an awesome edition, especially in conjunction with jetbookings, is a geolocation search based on custom fields. 

The idea would be that one can set up a custom field with an adress on each post/product. On the frontend you could then enter an adresse in a searchfield. The adresse is then processed by jetsmartfilters and the posts are shown by distance, showing the post/product with the nearest adresse first. 

This would be incredibly helpful for websites that have event or hotel listings and the customer wants to search for "an event near you". Or for shops with different locations and the customer wants to search for the nearest shop. 

I hope this input helped and thanks for your awesome plugins :)

**Comment by ImmersionNation** [comment]
Oh my word! and if there was a way to plug that into mapbox/google maps.. 
This is all I want for christmas. xD  There would be dancing in the streets!!

**Comment by rensvis** [comment]
This would be great! Looking forward to it. :)

**Comment by TheBigBanik** [comment]
Awesome feature. Resulting geolocation posts would be a superb addition to the plugin.

**Comment by baitasite** [comment]
Is a greate for business listing website

**Comment by ghost** [comment]
Yes, this would be great ;)

**Comment by developer784** [comment]
Has anyone ever done something custom for this solution?  Come on... not even a suggestion here.

**Comment by EnvioMaik** [comment]
+1000 this is like the only feature that absolutely necessary for map listings, how is it not implemented yet? After almost 4 years...

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
