### ISSUE TITLE
Need support for Elementor's new container widget

### ISSUE THREAD

**Issue by tealou** [CrocoBlock/suggestions#4950]
Any ETA on when there might be a patch for Dynamic Visibility to support the Containers in Elementor 3.6 dev, or is there a current JetEngine dev version/code that we can use to convert it? I would gather it's just a matter of targeting the new widget and can't be a huge job, but I'd like to know if there are plans to support it sooner rather than later? 

Otherwise, given the situation in Ukraine, I can get that code together and contribute it back if you need x

**Comment by aperojo** [comment]
Yes please, we need this. The flexbox container is already present as experiment in Elementor Core Beta 3.6
