### ISSUE TITLE
Unable to set Jet Review Input Fields as optional

### ISSUE THREAD

**Issue by LiamX2** [CrocoBlock/suggestions#4951]
Hi there,

Im trying to setup Jet Review on my website, currently the review form inputs are all required, but I wanna set them all like optional. So customers can fill the form to leave review or jump some inputs. Is that achievable? and I also wanna remove review title input but have no idea where to remove it. Thanks in advance and please stay safe.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
