### ISSUE TITLE
JetEngine Dynamic link - more options

### ISSUE THREAD

**Issue by 05edgarBlw** [CrocoBlock/suggestions#4953]
I think the "change post status" and and change "post permalink" are really wanted as options.

**Comment by RoynerG** [comment]
I think the same. That is a function very import for websites about real states, marketplaces etc.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
