### ISSUE TITLE
Add the ability to create promo codes

### ISSUE THREAD

**Issue by demon19851027** [CrocoBlock/suggestions#4954]
Hello, dear developers, perhaps in the future you will want to develop the possibility of adding coupons. That is, the ability to create a full-fledged coupon website.

And if you take up such development in the future, then take into account my suggestion and do not make such mistakes as many developers of such extensions. 

What exactly do I mean by this! It's just that most of these solutions have a similar vulnerability. This is what you can peek at the promo code code in the developer panel.

**This is the vulnerability I'm talking about**

![NO](https://user-images.githubusercontent.com/26875068/155749182-a7fe290c-214d-41e2-8a48-464671a89055.png)

**In fact, everything should be like this**

![Yas](https://user-images.githubusercontent.com/26875068/155749190-3cdbd21c-7fa4-4c1b-89c4-7b4380cacc98.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
