### ISSUE TITLE
JetSmartFilters Query parameters not displaying in url without Apply Button.

### ISSUE THREAD

**Issue by baraapro** [CrocoBlock/suggestions#4956]
**Describe the bug**
I have a product archive page created with JetWooBuilder, and JetSmartFilters. 
I have several filters created, they work great. however when applying filters, or using filters paginations, the url is not displaying the parameters. 

**Expected behavior**
When using the "Apply" button, the parameters are displayed, however when using the filters to apply on "value change", that doesn't work. the pagination also don't display the page number.

is this a bug? or is this the default behavior or jetsmartfilters? i tried looking everywhere, but couldn't find a solution.

**Comment by Floydtm** [comment]
Perhaps your filters are configured differently. Please contact our support team to resolve this issue.
