### ISSUE TITLE
JetTricks ReadMore : Can it only work for mobile?

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#4957]
Hello,

We have some sites with alot of content. This is okey on desktop, but on mobile we would like to use the "Read More" widget to keep it more cleaner for our visitor.

But when we use Read More widget, it will work on all devices. Is it possible to make it just for mobile, or tablet?

We dont want to use it on desktop, just mobile.

Can this be added please?

**Comment by Floydtm** [comment]
Use the following options, for example  https://prnt.sc/oxD8p9Ni_4CM
