### ISSUE TITLE
JetElements: Bar Chart - To display numbers with thousand seperators

### ISSUE THREAD

**Issue by PhakphumV** [CrocoBlock/suggestions#4959]
# To display thousand separators in ticks for both X and Y axis.

Here is an example of current bar chart display.
![1986117](https://user-images.githubusercontent.com/35300139/155880079-509b3821-1d80-4310-bb55-9d5396469278.jpg)

Even the thousand separator is defined in the widget's setting, it only applies at tooltip.
Ticks in axis are still without thousand separator.

And here is the expected bar chart display with thousand separators in Y axis' ticks
![1986168](https://user-images.githubusercontent.com/35300139/155880083-a4a1f99d-af08-4f5b-b184-290bcba8dedf.jpg)

Currently, I added this hard code script to add thousand separator in Y Axis' ticks when having a bar chart display on a page.

```
Chart.instances[0].config.options.scales.yAxes[0].ticks.callback = function(value, index, values){
return value.toLocaleString("en-US")
}
Chart.instances[0].update();
```

This "thousand separator" setting should affect axis' ticks as well as tooltips.

**Comment by Gawuww** [comment]
Added in JetElements v2.6.4
