### ISSUE TITLE
Dynamic Video URL for Jet Engine like ACF

### ISSUE THREAD

**Issue by mattiebrownoz** [Crocoblock/suggestions#496]
I'd like to be able to have a dynamic url to put vimeo and youtube links in. 

It should be able to have a fallback video link and also have the option to either have this fallback video link or hide if value is empty like your other dynamic widgets. 

Here is what I'm using with ACF currently as they have so many more features. Check the screenshots.

![Screen Shot 2019-09-01 at 1 04 58 am](https://user-images.githubusercontent.com/45414921/64065733-b22b1d80-cc54-11e9-85ca-5263af76c166.png)
![Screen Shot 2019-09-01 at 1 05 44 am](https://user-images.githubusercontent.com/45414921/64065738-b820fe80-cc54-11e9-901a-3ff819920a0d.png)

thanks.

**Comment by MjHead** [comment]
You can use Text field type and JetEngine / Custom Field dynamic tag to do the same - http://prntscr.com/p45rhi
