### ISSUE TITLE
Jet Bookings - Advanced Conditional Pricing by no. of customers and age

### ISSUE THREAD

**Issue by imsnk8** [CrocoBlock/suggestions#4960]
A conditional pricing option is very important in jet bookings, especially if we are dealing with tours
Pricing by no. of booking, age of the consumer (adult, child) etc.

I have clients whose tour product ranges depends upon the no. of people booking the product

so if N no. of people book rate is X,
n+1 book then rate is Y
n + 2 book then rate is Z

This helps offer more dynamic products for tour booking websites

Here is an example where this feature is implemented
https://ba-booking.com/ba-book-everything/demo/tour-1

the current alternative is https://ba-booking.com/
but everything in crocoblock environment will be super helpful, I have to use this plugin because Crocoblock cannot do conditional pricing.
![Screen Shot 2022-02-28 at 12 13 29 am](https://user-images.githubusercontent.com/68180667/155883867-14c1dffa-5ca2-4b71-9179-d2d4d02b7523.png)

**Comment by Floydtm** [comment]
https://demo.crocoblock.com/balirento/properties/ocean-star-luxury-cottage/ You can do it all with forms.
