### ISSUE TITLE
Custom checkout field in jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#4961]
**Before adding a new feature request, please, make sure you’ve checked:**

A new feature is great for getting extra information from the customer. Additional information such as national card number, age and other required information.

**Comment by UraraReika** [comment]
I merged this issue with [#4221](https://github.com/Crocoblock/suggestions/issues/4221), which is on the same subject so we could deal with it more efficiently.
