### ISSUE TITLE
Sorting filter options in JetSmartFilter

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4962]
It would be great to sort the JetSmartFilter options on their indexer value. I would like to always show the option with the highest value on top.
Screenshot attached: https://prnt.sc/GukPWX-H35NI

**Comment by stasonua0** [comment]
+1

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
