### ISSUE TITLE
Show variations as simple products. Build a query to display children (list of children products)

### ISSUE THREAD

**Issue by aksamitnaya** [CrocoBlock/suggestions#4966]
I need to call variations from a Variable Product and show them using Product Grid, I'm just asking a way to show those variations which I configure in the WooCommerce Products section and not just show the Parents' ones. 
Don't you even have a query to build using the QueryBuilder? 

нужна опция как Variations as Single Products for WooCommerce. Потом строить квери и показывать список не пэрэнтов продуктов, а чайлдов (сами вариэйшены)

**Comment by UraraReika** [comment]
I merged this issue with [#4955](https://github.com/Crocoblock/suggestions/issues/4955), which is on the same subject so we could deal with it more efficiently.
