### ISSUE TITLE
JetSmartFilter not Working if Listing source is Terms

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#4969]
Hey guys,

I created a listing with the source of the terms type for my model taxonomy, it's a simple listing with just a text widget using dynamic tag to bring the term name of "model".

By adding the listing grid to any page and linking the created listing, it displays all the results perfectly.

The intention is that the client can consult this complete list of models and search if the model already exists with a filter, the first attempt was using the Search type filter created with jetsmartfilter, and then Select, Checkboxes... applying the return doesn't work on the listing grid and still the same result.

if the listing is from source "post", when applying any type of filter the return of information occurs normally.

Guys, I tried in several ways, even using the query variable option in the filter and also set in the taxonomy configuration.

If there is any configuration that I need to know to solve, please let me know.

Sincerely,
Anderson.

**Comment by tizum** [comment]
Hi everyone, does anyone have any idea how to solve this?

**Comment by Satkos** [comment]
+1

**Comment by SargasTM** [comment]
JetSmartFilters currently don't filter terms

**Comment by tizum** [comment]
we're just going to treat the case like this, it doesn't filter and close, any action, do you have plans to add this functionality?

**Comment by tizum** [comment]
Hello I would like to know if there are plans to add the filter by terms, I would really like to bring this functionality to some customers or know that this works using JetEngine and JetSmartFilter, thanks.

This could be added to Querybuilder with an integration with JetSmartFilter, I don't know how to see this working in a simple way like filter post.

@Floydtm @MjHead
