### ISSUE TITLE
Automatically close radio filter after user choses an option

### ISSUE THREAD

**Issue by edwinoonk** [CrocoBlock/suggestions#4970]
We'd like the radiobutton filter to collapse when the user choses an option. It makes no sense to keep the filter open since the user can only select 1 option, keeping the filter open clogs up the screen (especially on mobile) and requires the user to close the filter manually to free up screen space.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
