### ISSUE TITLE
typos in your google ads

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#4973]
just needed to have a look at the jetmenu site and noticed you have typos in your google ads:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/1038062/156583223-0e4621ac-2ff3-4dc8-a97f-f962c294d72d.png">

Elementor is spelled wrong.

**Comment by rtpHarry** [comment]
And woo commerce should be WooCommerce.

**Comment by Floydtm** [comment]
Thank you!
