### ISSUE TITLE
jetwoobuilder + Checkout page not working properly

### ISSUE THREAD

**Issue by yasirshabbirservices** [CrocoBlock/suggestions#4975]
**Describe the bug**
I have created a custom checkout page using jetwoobuilder+ on Astra but it's not working fine. I have tried to remove all the plugins and test one and one also has tested with multiple themes like Astra, kava, kedance, hello. and I have tried to use the old versions of Elementor also jetwoobuilder but getting the same errors.

**To Reproduce**
1. Go to '(https://haseebfoods.com.pk)'
2. Click to 'add any product in cart and click on cart icon on the header and see what's happening also click on proceed to checkout to see the checkout page errors. on checkout page order review widget not working properly'

**Screenshots**
[[If applicable, add screenshots to help explain your problem.]

You can see this loom video to easily understand the issues.
[](https://www.loom.com/share/26690e89e42145d391560a31e95dc55e)

**Desktop (please complete the following information):**

Device name	DESKTOP-OUOD4KT
Processor	Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz   3.50 GHz
Installed RAM	16.0 GB
Device ID	69A4C004-4220-4B62-BC78-3776BA8504E8
Product ID	00330-50346-76549-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

 - Windows 10
 - Browser Chrome (Version 98.0.4758.102 (Official Build) (64-bit))
 - Browser Microsoft Edge (Version 98.0.1108.62 (Official build) (64-bit)
 

**Smartphone (please complete the following information):**
 - Device: [xiaomi Redmi Note 9 Pro and Redmi Note 10 pro]
 - Android 11
 - Browser Chrome (Version 98.04758.101 Updated on 14 Feb 2022)

**Comment by yasirshabbirservices** [comment]
https://www.loom.com/share/26690e89e42145d391560a31e95dc55e

**Comment by UraraReika** [comment]
Hello @yasirshabbirservices !

You can try this solution.
Go to Elementor > Settings > Integration Tab ([link](https://tppr.me/5VWuD)) find this setting ([link](https://tppr.me/736Ev)) set it to disable and save settings. If problem still exist please contact our [support team](https://support.crocoblock.com/support/home/ ).

**Comment by yasirshabbirservices** [comment]
I don't have this option in Elementor Settings. Also m using Elementor Free with Crocoblock lifetime license. And I have used jetwoobuilder on 10+ websites in previous 7 days and getting this same error on every site.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by UraraReika** [comment]
Please describe in more details steps how to reproduce this issue because this steps don't reproduce it.

> To Reproduce
> Steps to reproduce the behavior:
> 
> Go to '(https://haseebfoods.com.pk/)'
> Click to 'add any product in cart and click on cart icon on the header and see what's happening also click on proceed to checkout to see the checkout page errors. on checkout page order review widget not working properly'

or contact our support team where you can provide your site details and we will check everything.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
