### ISSUE TITLE
Jetappoitment

### ISSUE THREAD

**Issue by otaviobertolotti99** [CrocoBlock/suggestions#4976]
Por que não é possível colocar outras regras para locação de produto?

Exemplo:
O cliente só poderia escolher três opções para aluguel do produto:
3 dias, 7 dias ou 14 dias

Por que só é possível configurar a reserva por dia e por semana?

**Comment by Danix933** [comment]
Tente usar o JetBooking, uma vez que a marcação Jet é apenas para marcações horárias ou blocos de tempo inferiores a 24 horas.

**Comment by Floydtm** [comment]
Please, note, that the feature requests can be accepted and processed only if they’re written in English.
