### ISSUE TITLE
Jet Woo Builder - add Cart Builder, Checkout Builder, My Account Builder, Thank You Builder

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#498]
Hello, Jet Woo Builder is no longer young, but still can’t do what competitors like plugins can do, for example this one - http://preview.codecanyon.net/item/woocommerce-page-builder-for-elementor/full_screen_preview/ 23339868? _Ga = 2.224355609.302269598.1567351607-1145844675.1565856355

Specifically, we are talking about creating custom pages in your personal account, basket, checkout page, thank you page.

I think this functionality needed to be implemented yesterday) Thank you!

/*Оригинал*/
Здравствуйте, Jet Woo Builder уже не молод, а всё еще не умеет делать того, что умеют подобные плагины конкуренты, например этот - http://preview.codecanyon.net/item/woocommerce-page-builder-for-elementor/full_screen_preview/23339868?_ga=2.224355609.302269598.1567351607-1145844675.1565856355

Конкретно речь о создании кастомных страниц личного кабинета, корзины, страницы оформления заказа и страницы благодарности. 

Думаю этот функционал нужно было внедрить еще вчера) Спасибо!

**Comment by zimmiel** [comment]
+

**Comment by SirChopper** [comment]
This would compete the Jet Woo package for many people.

**Comment by GOHA81177** [comment]
I support the author of the request!
This functionality is very popular!
Is it so difficult to create it ?

**Comment by NeoAcla** [comment]
i support this also specially the checkout page, the standard checkout page makes your customer abandon there cart due to the layout with full of forms to fill.

why not do the same like OceanWP Theme checkout page or from YITH WOOCOMMERCE MULTI-STEP CHECKOUT page, it makes so neat and pleasant to the eyes.

like this;
![checkout page](https://user-images.githubusercontent.com/19571084/80634155-0b10b700-8a6b-11ea-9253-d64f2747f2da.JPG)

or this one
![checkout](https://user-images.githubusercontent.com/19571084/80634191-211e7780-8a6b-11ea-8db3-d639229c5e8f.JPG)

**Comment by AR352** [comment]
Yes editing checkout, thank you pages, billing and shipping forms and all good things like that are a must have for the JetWooBuilder.
Take a look at the woolementor plugin. It does this jobs very well.
Watch this video from wptuts: Here you can see what we all need for our woocommerce pages!
https://www.youtube.com/watch?v=FAYBXfRyEg4

**Comment by DmitryBychenko** [comment]
Cart page - widget.
Checkout page fields - widget.
Payment page - widget.

These 3 widgets field by field management.
So we can put needed checkout fields (for example, only name and email fields)  & needed payment fields right into Page or Post.
No need to put in Cart, go to Cart, Yes ok, Checkout fields, .... Too difficult.

And use these widgets to customize Cart page, Checkout page and Payment page.
Would be brilliant!

**Comment by rquirola** [comment]
I join this request, don't forget the [conditional fields] at checkout

**Comment by rajas91** [comment]
It would be really grateful to see the above feature added.

here is my wish list:

1. Custom product pages with custom fields and front end user product customization. For Eg. Front end users should be able to customize the product they are buying by adding images, custom texts, etc.

2. Customizable Cart Page: For eg. Designers could change the cart styling and layout.

3. Customizable checkout Pages with multi step checkout ability.

**Comment by ElvinPeter** [comment]
I support this request! Please also add Customized Product Checkout (that can be used for funnels). Make Jet Woo Builder the #1 plugin for WooCommerce. Thanks

**Comment by Lonsdale201** [comment]
I Joined too. :)

**Comment by codeorlov** [comment]
The request was created a year ago, is there any news?  This functionality is necessary.

**Comment by DIntriglia** [comment]
Completely agree as this is very hard to adjust without going into the PHP code for the WooCommerce templates. This would make my life so much easier!

**Comment by flyingcompass** [comment]
+1

**Comment by reachdigitalaus** [comment]
+1

**Comment by Luca1996O** [comment]
+1

**Comment by arekuusa** [comment]
+1

**Comment by coenvandieur** [comment]
+1

**Comment by peepersqueaker** [comment]
Any progress on this? I've been using this > https://powerpackelements.com/
Just not doing it for me.

**Comment by TomEbeyer** [comment]
+1 this is still a gap in the market

**Comment by petranca** [comment]
+1

**Comment by benjaminhaeberli** [comment]
+1

**Comment by bionikdigital** [comment]
+1 If you could add Upsell capability to product, cart and checkout page would be great.

**Comment by coenvandieur** [comment]
also add custom dynamic tabs to existing 3x standard woocommerce tabs pls.
like https://de.wordpress.org/plugins/yikes-inc-easy-custom-woocommerce-product-tabs/ but rahter with meta fields or so

**Comment by alexanderpankart** [comment]
**I endorse this request**.
There does not have to be any major changes to the layout with new functions in the first version. It would be enough if you could drag the individual components into the columns using a widget to design them.

Of course a variation (example: Elementor Multi Step Form) would be desirable.

**Comment by mcj777** [comment]
+1
