### ISSUE TITLE
Some suggestions for developing the Categories Grid widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4981]
**Please, describe the feature request, making it clear to understand.**

hi

some suggestions for developing the Categories Grid widget, please check if possible.

1- Make Product Item Clickable for category item : https://prnt.sc/_TO7ZFR5Ifql

2- CSS Filters for category Thumbnail Similar (#4569) : https://prnt.sc/Ohrz6INYltQQ

3- In this widget, we have the hover settings in a separate section : https://prnt.sc/1GHjmThoQfg0
But isn't it better to delete this section, and add the desired settings to your sections? Like the product grid widget. For example, the title hover settings are moved to the title section : https://prnt.sc/GDo5vUkIuvr9 > https://prnt.sc/9D145pRKw377
Or, for example, the Thumbnail hover settings are transferred to the Thumbnail tab.
Therefore, if all the hover settings are moved to the desired sections, this section (https://prnt.sc/1GHjmThoQfg0) will not be needed and this is much better.

4- I think if CSS Filters are added to this widget, there will be no need for overlay anymore. CSS Filters will be much more efficient.
Even in the product grid widget.

5- BUG : If we enable the Specific Prev Arrow Styles option and create a border, there is no color option for the border. This bug is also present in the product grid widget. https://prnt.sc/nb-2_DCCrg_6

6- These two options seem to be completely useless : https://prnt.sc/pW8_FQiFUd3g
In fact, this setting (https://prnt.sc/y8E6XOonDGzL) does the same thing. 

7- This option (#4603) for category item. (if possible)

8- Please add the border option to the category Thumbnail and category item. Using this feature, we can control the border after the hover.

9- border radious for title. https://prnt.sc/2fLoxmoPQ9st

Finally, what is needed for this widget is to have the Hover and Normal sections (https://prnt.sc/hGUSa8sQG2Hl) in the title, category item, content, Excerpt and Count sections.

thank you

**Comment by UraraReika** [comment]
1, 3, 5, 9 - done
2, 4 - Track this issue https://github.com/Crocoblock/suggestions/issues/4569.
6 - If you think so then don’t use them.
7 - Track this issue https://github.com/Crocoblock/suggestions/issues/4603.
8 - This options already exist.

**Comment by 79ho3ein** [comment]
thank you dear @UraraReika. Please check the #4948 & #5089 for the new version if possible. thanks again
