### ISSUE TITLE
Products Grid Custom Fields / in JetWooBuilder Products Grid 

### ISSUE THREAD

**Issue by martinjakse** [CrocoBlock/suggestions#4986]
If I install the mentioned plugin from the devtools repository and add a custom field (JetEngine Meta boxes), it will be displayed via the JetWooBuilder Products Grid Plugin. 

The problem that arises is that the **custom field DISAPPEARS** if I use -" Enable the Custom Query" builder with custom filter. I urgently need Custom Query to limit the display of products. The Listing grid is by no means a replacement for the JetWoobuilder Product Grid plugin, because it does not work in the Listing Grid "Add to cart" button.

![2022-03-09_13-40-47](https://user-images.githubusercontent.com/20109290/157443772-e75201f5-af36-458a-abcc-32190523f2d4.jpeg) ![2022-03-09_13-40-36](https://user-images.githubusercontent.com/20109290/157443940-c9a3b7aa-efef-4175-a770-2b50bba64ea2.jpeg)

**Comment by UraraReika** [comment]
Hello @martinjakse !

This issue is fixed. please update this [plugin](https://github.com/UraraReika/jet-woo-builder-products-grid-custom-fields).
