### ISSUE TITLE
JetWooBuilder - Billing Form / Shipping Form - Commas in classes

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#4990]
**Describe the bug**
I'm seeing some incorrect concatenation of the class names which is resulting in display issues.

For example:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1038062/157502345-f968819c-5969-4a2a-9a97-ae2ec61bac7a.png">

I've fixed the country field for billing on the left, but you can see what is happening on the right.

From looking at the code, it seems that the default class concatenation somewhere is being done incorrectly and its joining it by comma instead of space:

![image](https://user-images.githubusercontent.com/1038062/157502736-2b632da2-d28c-4e06-8f40-5d3bb8defb63.png)

By setting the class field to wide, rather than leaving it blank, it is resolving the issue.

Shipping country setting based on top screenshot:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/1038062/157502889-4dfe0b36-0176-4fa7-85b9-5371e7a361c0.png">

Billing company setting based on top screenshot:

![image](https://user-images.githubusercontent.com/1038062/157503072-711585ec-9ba8-49d5-bf6f-6ee3450cf143.png)

Setting the class to `Wide` makes it output the correct class:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1038062/157503254-a495e55b-29e6-41ce-bf91-d65765df5473.png">

If you look at the snippet above though you can see that it is happening with other fields. They all have comma separated class lists, but it's just got lucky that it hasn't broken the design with those ones because they aren't after floated 2 col fields.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team. 

This issue exist in old version of our plugin and if you update it you should recreate widget to implement the fix.

Thank you!
