### ISSUE TITLE
Optional meta outputs for Single Meta Widget.

### ISSUE THREAD

**Issue by bouveng** [CrocoBlock/suggestions#4992]
It should be possible to only show any of the metas, like only SKU for example.

I have solved this with CSS for now. But it would be nice of you just could turn off the ones you do not want. I know I can display the SKU using the dynamic tags feature in elementor, but then I lose the dynamic update of the SKU when changing any option on a variable product. ~~(that also has an issue, reported here: https://github.com/Crocoblock/suggestions/issues/4991)~~ Closed. Solved.

Example: showing only SKU on a product:
<img width="420" alt="Screenshot 2022-03-10 at 02 08 10" src="https://user-images.githubusercontent.com/433429/157566900-87dbf4a5-b16e-4f1c-8105-49309b642a82.png">

Thanks in advance!

**Comment by 79ho3ein** [comment]
+1
