### ISSUE TITLE
Available apartment unit ID not passing to order

### ISSUE THREAD

**Issue by wojtishek** [CrocoBlock/suggestions#4993]
**Describe the bug**
After adding apartment to cart, no aparment_unit_id is passed, so the unit is not booked. 

**Version**
JetBooking 2.4.2

**Solution**
There's a wrong index definition in ```jet-bookings/includes/db.php```, line 179:

```$booking['apartment_unit'] = $booking['apartment_unit'];```

should be

```$booking['apartment_unit'] = $this->get_available_unit($booking);```

**Comment by UraraReika** [comment]
Fixed in the latest release.
