### ISSUE TITLE
Should Add the Event Booking Functionality In Jet Booking

### ISSUE THREAD

**Issue by jay639** [CrocoBlock/suggestions#4994]
Jet Booking And Jet Appointment both are designed for booking and appointment purposes. But both do not fulfill the event booking functionally. 

-- What is Event Booking?--
An event is a date where users have events on a specific date. And user can book the event with a payment gateway (woo-commerce)

--What Features it Should Have?---
1. Single date picker option
2. Shortcode to display that event date on multiple pages
3. Widget to display the upcoming/ongoing/completed events

--What is Problem with Current Jet Booking?--
1. It has two date picker check-in and check-out
2. It has working days option this should be disabled since the event may be for one day or multiple

Hope you work on this. Thanks
![cblock-feature-request](https://user-images.githubusercontent.com/22674355/157616439-ddb2da96-80cd-4355-b379-115138e48c8f.png)
![cblock-feature](https://user-images.githubusercontent.com/22674355/157616581-2d881010-8eb2-430d-b730-363431b4a2bf.png)

**Comment by davidwatkins2** [comment]
I agree and please add features like Modern event calendar, especially the bar code in email filter. https://webnus.net/modern-events-calendar/features/

**Comment by UraraReika** [comment]
Hello @jay639. Thanks for the feedback.

> It has two date picker check-in and check-out

In JetFormBuilder where you setup form you can choose what type of field display you want https://tppr.me/jKrfS. Then with the help of our API https://gist.github.com/Crocoblock/0d73be0a11b07fa24c1490f5ad7d0d3a setup datepicker functionality or use our option here https://tppr.me/ug2vs.

> It has working days option this should be disabled since the event may be for one day or multiple

In on of our latest update we present Schedule functionality. So all your need should be solved.
