### ISSUE TITLE
improving slider, carousel with flickity metafizzy instead of slider pro and slick for carousel

### ISSUE THREAD

**Issue by jacktaffa** [CrocoBlock/suggestions#4995]
https://flickity.metafizzy.co/ it's fliccker less than slider pro, and when you scroll left, right is more smooth more than slick, it doesn't blink

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
