### ISSUE TITLE
Add the ability to edit the jetBlocks password reset labels and error field text.

### ISSUE THREAD

**Issue by Rubendj1** [CrocoBlock/suggestions#4996]
Hi Guys,

I was implementing a login flow for my client and I noticed that I cannot edit the text content of the password reset form label and it's error messages. I need this for proper translation of the website. Thanks!

**Comment by Crocoblock** [comment]
was released in version 1.3.10

**Comment by Rubendj1** [comment]
> was released in version 1.3.10

Fantastic, thanks!
