### ISSUE TITLE
JetEngine | JetWoobuilder Add Ability to create custom Product Type

### ISSUE THREAD

**Issue by qoqoshogo** [CrocoBlock/suggestions#4997]
The need for an ability to create custom product types that are also integrated into a woocommerce product type would allow for clearer pathways for websites that have unique or underserved customization solutions. We could extend the ability of custom post types to add product type elements, create a custom product type workflow, or support both separately.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
