### ISSUE TITLE
jet woobuilder 1.12.1

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5000]
**Describe the bug**

hi @UraraReika , Thanks for the new update. In the new version, the main bugs were fixed. But there are still some cases, please check them if possible.

**checkout page**

1- This bug still exists. If we use the universal color for the field color in the field tab, the arrows in the list fields will be corrupted.
https://prnt.sc/gOxJFjBAZUc3  >  https://prnt.sc/_zvUuMXiJDDY
If universal colors are used, the arrows are displayed correctly in the elementor editor. But if you see the output on the website, it is completely broken.

The arrows are displayed well when we disable the universal color.

2- I set the city and province field to 50 x 50, but the title of the bottom field moved away from its place. https://prnt.sc/9Ijl9OqyxRix
I even set the fields Columns Gap to 0 but to no avail.

3- In RTL, the payment field arrows are out of place (red arrow). While they should be in the green zone. https://prnt.sc/W50T2UuqWvIb

4- After opening the list, the boundary between the field and the list is clear. (Border Radius Field ) This was not the case before.
https://prnt.sc/Z1GgRCe-mqCX

**product grid widget**

1- Now, we have 3 controllers to adjust the space between products in this widget.

A : https://prnt.sc/tWO0O8GTP7Ax
B : https://prnt.sc/QWRx6wdTx2mO
C : https://prnt.sc/IKoELZ-_cStb

If we use option C (which is the best), option A&B will be practically useless. So changing the value of the two will not make any changes to this widget.
Of course, if we do not use case C, case B is also useful, but case A really has no use and I think it is better to delete it, Because it (A,B,C) confuses users in using them.

2- In the carousel, by default there is a gap between the products, which causes the widget to go out of its normal state. https://prnt.sc/8a4b5WbXYZI2
Please watch the video below, I set all distances between products to 0. But there is still a gap. **This interval occurs when I activate the carousel** :

https://user-images.githubusercontent.com/77163248/157892937-578c84db-0ead-4b7c-a03c-978f73e268b6.mp4

I did not pay attention to it in version 1.12.0. But this gap did not exist before. I'm still at 1.11.4 and there is no gap.

**Please let me know if you were unsuccessful in reproducing any of these.**

Thank you

**Comment by UraraReika** [comment]
1 - As I mentioned in https://github.com/Crocoblock/suggestions/issues/4888 - Colors applied for all borders if you use global Elementor colors. We need only top border color. Arrow disappear because of select 2 default styles. And this is true for Elementor Checkout widget as well. So in this situation the problem about how Elementor global color applies. Next thing is : 

> If universal colors are used, the arrows are displayed correctly in the elementor editor. But if you see the output on the website, it is completely broken.

And int his case in Editor you see simple select input but on the frontend you can see select2 control. This is because woo scripts that is not applied in Elementor editor.

2 - We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

3 - Fixed
4 - This is because new improve styles for select2 field. You posted this earlier and in the future we will improve this field https://github.com/Crocoblock/suggestions/issues/3793.

product grid widget
1 - Everything will stay on its place. Different users use different controls.
2 - Fixed

**Comment by 79ho3ein** [comment]
thank you dear @UraraReika 

> 1 - As I mentioned in #4888 - Colors applied for all borders if you use global Elementor colors. We need only top border color. Arrow disappear because of select 2 default styles. And this is true for Elementor Checkout widget as well. So in this situation the problem about how Elementor global color applies. Next thing is :
> 

You are absolutely right. But in 1.11.4 I used global colors and this was not a problem! This problem occurred after updating to 1.10.12.


In connection with product grid > 1,       I wrote a description in the new issue #5002 (of course, I wrote before you sent this answer)
Please check, I hope it is useful.

Anyway, thank you🌹

**Comment by 79ho3ein** [comment]
**free mode BUG**

1- Free mode works much better on safari than Android & Chrome IOS . It works very slowly and out of control in Android. (The browser used in Android was Chrome)

2- If we enable overflow with free mode, in Chrome IOS browser, free mode will be affected by overflow performance. After that, I turned off the overflow. But the problem remained. **I do not know, maybe this is the case in Chrome IOS browser. Even before activating the overflow.**

3- In Chrome IOS browser, if you scroll quickly, the side product image will be hidden sooner. In general, the free mode function in Chrome IOS is severely damaged. (Requires a bit of care)

4- In Safari browser, if we scroll quickly, first only the product images are loaded and then the background color, title and price are loaded. Sometimes, even the contents of the carousel are loaded too late.

https://user-images.githubusercontent.com/77163248/158053769-1e8d6e6f-a3bc-4b82-97a5-6934e1915092.mp4

In the video above, the late loading of the carousel content is quite obvious.

5- This problem persists #4589. Please watch the video below.

https://user-images.githubusercontent.com/77163248/158052962-e1b48dfc-a8be-4097-afdc-f4524897de99.mp4

6- **This is not a bug** - Does this option affect the speed of the free mode after activating the free mode? https://prnt.sc/P3gFJllrjQyM
If not, is it better to deactivate (hide) this option after activating the free mode?
If yes, this should not be the case. Because now we have this option for free mode : https://prnt.sc/WYWo_uUO8edu

In general, the free mode functionality is completely different in different browsers. **In Safari, it works better than other browsers.But it also has some bugs in Safari, which I explained above.**  So it was a bit difficult to describe the bugs.
I hope you succeed in reproducing them.

Finally, I had a request from you for Free mode ...

Please enter this link with your mobile and see the first carousel. https://nickpiscitelli.github.io/Glider.js/
This is the smoothest and most excellent free mode. I was looking for something like this to give you an example.
It would be really great if the free mode function in jet woobuilder was like this (in all browsers).


thank you

**Comment by 79ho3ein** [comment]
An important point about free mode...

As you know, free mode has no use in desktop and is only used on tablets and mobiles ,Therefore, if we want to enable free mode, in addition to tablets and mobile phones, it will also affect the desktop And that would be problematic. The only solution to this problem is to double the number of carousels on the website. One for desktop (free mode no), one for mobile and tablet (free mode yes)
But this is not a logical method and it undermines the performance. So I wanted to ask if there is a way that by default, activating free mode has **no effect on the desktop carousel?**
That means activating free mode will only work for tablets and mobiles. Is such a thing possible?

**Comment by UraraReika** [comment]
> You are absolutely right. But in 1.11.4 I used global colors and this was not a problem! This problem occurred after updating to 1.10.12.

In this version arrow color didn't change at all no matter you use global color or simple color picker.

free mode BUG

1, 2 - this issue about swiper slider library that Elementor used so and we.
3, 4 - tested on real device and we did't face this issue. Maybe you use some sort of optimizer and lazy load system on your site.
5 - we can't recreate this issue. Please tell up step by step how to do that for sure. We did the same thing like in your video but everything works proper. Or try to test on another installation.

> In general, the free mode functionality is completely different in different browsers. In Safari, it works better than other browsers.But it also has some bugs in Safari, which I explained above. So it was a bit difficult to describe the bugs.
> I hope you succeed in reproducing them.

This is behaviour of Swiper slider library that is used for carousel functionality.

> Please enter this link with your mobile and see the first carousel. https://nickpiscitelli.github.io/Glider.js/
> This is the smoothest and most excellent free mode. I was looking for something like this to give you an example.
> It would be really great if the free mode function in jet woobuilder was like this (in all browsers).

We using another library.

An important point about free mode...

Just disable tis option https://tppr.me/OcW1t

**Comment by 79ho3ein** [comment]
Thanks for the reply. good luck.

**Comment by 79ho3ein** [comment]
hi @UraraReika
This has nothing to do with version 1.10.2, but I wanted to say it here so as not to open a new issue. About the **best sellers query** in product grid widget ...

I tested this query a lot. But it does not seem to work. In fact, when I activate it, it shows products that have not been sold at all!
In addition, I made several trial purchases on my website, but the product I purchased several times on different accounts was not on the bestsellers list.
You follow the function of WooCommerce, But I feel there is a problem.
I always work with hello elementor. but now I'm trying to find a woodmart theme, to try this subject (bestsellers query) in this theme. I will inform you of the result.

**In addition, I have a question about the best sellers query ...**

How does this query work? That is, how many sales must each product have to include best-selling products?
In addition, if we have no sales and enable this query, it will display products. Shouldn't the list be empty if no products have been sold?
Am I wrong?

**Comment by UraraReika** [comment]
This query was added to display only product that has been selled. And in this case we use total_sales product meta and compare if it more than 0. Try to clean up your Products Sale Report section and [Products meta](https://tppr.me/SDk3d) for total_sales. Then everything should synchronize and show you correct results.

**Comment by 79ho3ein** [comment]
> This query was added to display only product that has been selled.

Exactly. But it is not. Displays products that have not been sold at all. In fact, when we choose the best sellers query, it is no different to this. https://prnt.sc/YsOKbfN956N-

I also checked the items you mentioned above. I even checked for plugin interference, but still this query was of no use. Does it work for you properly?

**Comment by UraraReika** [comment]
This result ([link](https://tppr.me/RPImp)) on clean setup. If you have some orders list and you can check woocomerce reports about sells it's good, but this query took data from `total_sales` product meta field. So if you didn't delete any order or some kind modify orders or reports then `total_sales` = to reports and order data. 

Although you should notice that each product has this meta data. To make all this things work you better clean this meta field so as order and reports data.

**Comment by 79ho3ein** [comment]
oh , thank you alexander, It finally worked. I had two questions ...

As you said, I removed [this meta](https://prnt.sc/EJAhXtgL_Mo_) from all the products and it made this query work(Of course, I did this individually for all products).

1- Is there a way to remove total_sales from all products at once? So that it is not even created in new products? Because when we add a product in WooCommerce, this meta (total_sales) is created automatically.
For example, if we have 1000 products on the website, we have to remove this meta in each product. How can we completely delete this meta?
Another thing is that after deleting total_sales, it is added again.

2- If this meta is removed in all products, will it not be a problem? Does not cause damage to other parts?

thanks again

**Comment by UraraReika** [comment]
1 - Find some code that loops through the products and update this meta data.
2 - Everything should be fine.

**Comment by 79ho3ein** [comment]
thank you❤

**Comment by 79ho3ein** [comment]
Another item about prev & next arrows. Of course, if I am not mistaken, I had reported it before ...
Anyway, there is no border color option in the prev & next arrows section : https://prnt.sc/nb-2_DCCrg_6
This is not related to this version. I just wanted to report.

**Comment by 79ho3ein** [comment]
hi again
I'm still in version 1.11.4 and there is a problem displaying shadows in the Categories Grid widget. If we shade the category tumbnail in the Categories Grid widget, the shadow will not be displayed properly. In fact, no shadows are displayed from the top, bottom, left and right of the image : https://prnt.sc/ohBXQ8pNPtIE

**Comment by 79ho3ein** [comment]
If you install the jet compare & wishlist plugin, a small problem will occur in the product grid widget settings UI. https://prnt.sc/GW7dTi4d-kQ-

**Comment by UraraReika** [comment]
> hi again I'm still in version 1.11.4 and there is a problem displaying shadows in the Categories Grid widget. If we shade the category tumbnail in the Categories Grid widget, the shadow will not be displayed properly. In fact, no shadows are displayed from the top, bottom, left and right of the image : https://prnt.sc/ohBXQ8pNPtIE

This issue exist in 1.11.4 plugin version as well. This is basically not an issue because it was like this always in case of presets functionality. To avoid this behaviour use [margin control](https://tppr.me/y6sIH).

> If you install the jet compare & wishlist plugin, a small problem will occur in the product grid widget settings UI. https://prnt.sc/GW7dTi4d-kQ-

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. 

Thank you!

**Comment by 79ho3ein** [comment]
> This issue exist in 1.11.4 plugin version as well. This is basically not an issue because it was like this always in case of presets functionality. To avoid this behaviour use [margin control](https://tppr.me/y6sIH).
> 

oh thank you. I'm still in 1.11.4 and that's why I experienced this problem.

> We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team.
>

In this case, it is strange that this problem does not exist for you. Of course, this is not a special case. The only thing is that the two controls for the jet compre plugin are attached to their top separator.https://prnt.sc/eVEwsGQcdb9E
While it should not stick : https://prnt.sc/W6sLWS0IyMqI

**active plugins**  
elementor : 3.5.6
e pro : 3.6.4
jet woobuilder : 1.12.1 or 1.11.4
jet compare & wishlist : 1.4.5
woocommerce : 6.3.1

**theme**
hello elementor : 2.5.0

wordpress : 5.9.2


Finally, a very important point is that the overflow mode is displayed with a delay of 2 seconds. Especially on mobile, it is even more than 2 seconds late. It should be noted that I even disabled the cache plugin, I also disabled the CSS optimization options of the element but there is still a problem.
If we have only one carousel, the delay will be minimized. But if we have 4 or 5 or even more carousels, the delay time in the overflow display will increase.
I checked this on other websites that used Overflow and there was no delay in displaying the overflow. Please watch the video below, The delay is quite obvious.

https://user-images.githubusercontent.com/77163248/159253977-5ea34e8a-c67f-48b8-b8ee-aa8efe23bf71.mp4

thank you!

**Comment by 79ho3ein** [comment]
hi
Version 3.6 elementor has been released and there is little interference with jet woobuilder. (product grid widget)
Of course, this bug manifests itself when the elementor flex box is active and we use the product grid widget in a container. If we disable the flex box, there is no problem. (I have not seen any problems so far)
It should be noted that the elementor flex box is in trial mode (but officially released) Anyway, flex box currently has a lot of bugs and I don't think many users will use it. However, if users use the flex box, they will have a problem with the jet woobuilder.

**Comment by UraraReika** [comment]
Watch this issue https://github.com/Crocoblock/suggestions/issues/4725.

**Comment by 79ho3ein** [comment]
Another case ...

I display the product archive using the product grid widget. In addition, with the jet smart filters plugin, I filter products in the archive.
I tried to use the [code](https://prnt.sc/WlF_TFreZNUC) in product archive. So that if no product is found based on the desired filters, a custom "Product not found" message will be displayed. But it does not work and the desired template is not called!
The problem is not the code. Because I use this code in the carousels of this website and the custom template is displayed without any problems.
Using the search filter, I searched for a product that does not exist, but the desired template is not called.

thank you

**Comment by UraraReika** [comment]
> Another case ...
> 
> I display the product archive using the product grid widget. In addition, with the jet smart filters plugin, I filter products in the archive. I tried to use the [code](https://prnt.sc/WlF_TFreZNUC) in product archive. So that if no product is found based on the desired filters, a custom "Product not found" message will be displayed. But it does not work and the desired template is not called! The problem is not the code. Because I use this code in the carousels of this website and the custom template is displayed without any problems. Using the search filter, I searched for a product that does not exist, but the desired template is not called.
> 
> thank you

Does it connected to this issue? If not please create new issue.

**Comment by 79ho3ein** [comment]
Oh right, I'm sorry. This had nothing to do with 1.12.1

**Comment by 79ho3ein** [comment]
This bug is still present in 1.12.1 : https://prnt.sc/rrIcSYH0-c-J

**Comment by UraraReika** [comment]
> This bug is still present in 1.12.1 : https://prnt.sc/rrIcSYH0-c-J

Forgot to change my comment. You need to handle this differently. With the help of WooCommerce options or with the help of JetEngine dynamic visibility. Please contact our support team they will help you. Thank you!

**Comment by 79ho3ein** [comment]
Is there no way to act like before? Because many users do not use conditional features at all. So they can not hide this section. I hope there is a way to solve it completely in the future. The bug is very annoying.
As for contacting support, I prefer not to disturb them in the current Ukrainian situation.
Anyway, thank you

**Comment by 79ho3ein** [comment]
hi again @UraraReika 

Thanks for this update. There is a case from version 1.12 which of course is not a important thing, but maybe it is not bad to know about it ...

After updating to versions 1.12.0 - 1.12.1 and even 1.12.2, some buttons style were reset. For example, the cart update button lost its border and border radious. Also, the buttons on the cart and checkout page lose their border-radious value. In general, this problem only occurred with the cart & checkout page buttons.
