### ISSUE TITLE
Bug in Search Ajax

### ISSUE THREAD

**Issue by ntpereira93** [CrocoBlock/suggestions#5001]
**Describe the bug**
it works in the Elementor editor but in the live one it doesn't work, my indexes settings are all OK..

**To Reproduce**
1. Go to '(https://getimob.growsimple.com.br/)'
2. Click on 'second filter below the banner'
3. See error

**Expected behavior**
Inside the Elementor editor it works perfectly, I expected it to work in live too.. 

**Screenshots**
https://ibb.co/j60Yr0S
https://ibb.co/fNsxHrS
https://ibb.co/XFNnqMY
https://ibb.co/RjCZWWR
https://ibb.co/6bzCd0f

**Comment by Floydtm** [comment]
To resolve this issue, please contact our support team and provide details to the site admin panel
