### ISSUE TITLE
A few suggestions for the product grid widget (column padding)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5002]
**Please, describe the feature request, making it clear to understand.**

The product grid widget is incredibly powerful. But there is a problem in the distance between the column and the row. There are many additional controllers to adjust the distance between products. Which can confuse users. Especially new users. I have a suggestion for developing this section, please review it. It definitely makes things a lot easier than ever. 

As I mentioned in # 5000, we now have 3 controls for adjusting distances in the product network widget. 

A : https://prnt.sc/tWO0O8GTP7Ax
B : https://prnt.sc/QWRx6wdTx2mO
C : https://prnt.sc/IKoELZ-_cStb

**Case A** is completely useless and has no use. In fact, it is better to delete it. (In fact, these two controllers do what C does.)
**Case B** is a useful controller, but it could be better, as I will say later.
**Case C** is currently the best. But its performance can be much more complete.

**But what would be the best settings for distance control?**

It is best to remove options A, B and C completely. All these settings will be integrated in the best possible way in this section :
 > https://prnt.sc/3Gx_H3uk5GUz

In this section, we need two new controllers. **1- Horizontal Gap**   **2- Vertical Gap**
It will actually look like this : https://prnt.sc/rV30ijIsLP39

These two options will solve this problem forever in the product grid widget. **In fact, the jet engine plugin listing widget uses the same method.**

**There is a very important point here.** By changing the value of these two options, no space will be created around the product grid widget. These two options only change the distance between the products, What Case B is doing now.
Therefore, the space around the widget will be 0 : https://prnt.sc/ZUeoiFH7XcVv
If we want to create a space around the widget, we will use this : https://prnt.sc/PlimHSr12KJf
These two controller will only control the space between columns and rows :  https://prnt.sc/NR1J6XBw6nDF

Another thing is that these two controllers should not prevent the shadow box from spreading : https://prnt.sc/sQ3WZtYVfSTJ

Add another item that is not bad ...        This option is hidden when the carousel is activated : https://prnt.sc/YGEKsjsSttpM
Because you will not need it in the carousel, unless #4738 is added.

Eventually it will be this way. Like  jet engine listing grid : 

https://user-images.githubusercontent.com/77163248/157908131-cd760c3e-c382-4c0e-8a6f-177e00881343.mp4

thank you

**Comment by UraraReika** [comment]
First of all Products Grig is not the same as Listing grid and has a lot of differences. We will not remove current controls and add new one for reason i mention here https://github.com/Crocoblock/suggestions/issues/5000. And this can although damage backwards compatibility.

**Comment by 79ho3ein** [comment]
it's true. Thank you
