### ISSUE TITLE
divider for product grid widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5003]
In the product archive, I display products as grid. Products are displayed in 4 rows and 4 columns. I want a border of 1px between products. https://prnt.sc/LnPih3ZWXxeW
For this reason, I enable the Border option. https://prnt.sc/Tnl-9XHsF4dQ But this has a problem. And it doubles the border of each product. As if it is 2 Px. https://prnt.sc/Al7iSfctStMp If you compare this with the previous image, it is clear that the border is a little fatter.
Can you add an option to distribute this border evenly between products? So that each product box (in 4 columns and 4 rows) has only 1px border.
I really need it

**Comment by UraraReika** [comment]
Unfortunately we do not plan to introduce such functionality into our plugin. You can use options that you provide in one of [screenshots](https://tppr.me/aw7Ma) above in combination with this [options](https://tppr.me/b0KUc) and this styles:

```
selector .jet-woo-products__item:nth-of-type(4n + 1) .jet-woo-products__inner-box {
    border-left-width: 0;
}

selector .jet-woo-products__item:nth-last-child(-n + 4) .jet-woo-products__inner-box {
    border-bottom-width: 0;
}
```

Witch you can put like [this](https://tppr.me/I4dVN). Please take a note number 4 in the code is number of [columns](https://tppr.me/iKC4n) .
