### ISSUE TITLE
Jet Engine When deleting meta field, the data stays.

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#5004]
**Describe the bug*

When delete a meta field from jet engine, the information from this meta field is not deleted, but stays in database.

**To Reproduce**
1. Create metafield (text or gallery) in Jet Engine
2. Fill in some information.
3. Without deleting this information, go to Jet Engine and delete meta field.
4. If you create again the same meta field with the same name you will see that information remains. 
5. For example- i create meta field gallery, then I uploaded some images. After that I deleted the meta field, but the gallery was still visible in the post.

**Expected behavior**

When delete a meta field, all the data in the posts or pages, which is filled for this field, must be deleted automatically.

**Comment by apatsidis123** [comment]
Any update with that? Or any workaround to delete the data manually?

**Comment by drakulux** [comment]
I also recently deleted a CPT metabox for over 1000 posts and they are still in the database, Im currently trying to find a solution

**Comment by Crocoblock** [comment]
Done
was released in v3.4.4
