### ISSUE TITLE
JetWooBuilder, adding support for more WooCommerce end-point Templates

### ISSUE THREAD

**Issue by Charlottilottan** [CrocoBlock/suggestions#5009]
I am simulating transactions on an Elementor site with JetWoobuilder.
In most scenarios I have great help from the WooCommerce end-point Templates that JetWooBuilder provides.

However. The specific payment gate I am using has a **_4-attempt fraud policy._**
This means, that after having tried 4 times and failed....

You get **_automatically redirected_** to the ThankYou page (not to the CART as if hitting "abort" after 1-3 failed attempts.

1. IF you have a ThankYou Widget, such as "Orders" it displays a correct error message.
2. But THEN it also shows buttons for you to choose if to "abort", or "try again". I am not sure which end-point this is, but I guess it is **_"cancel-order"_**. Anyhow, that endpoint is not possible for me to customize in JetWooBuilder as today.
3. After hitting the button "try again" the end-point _**"order-pay"**_ is called. This one is another one I cannot customize via the JetWooBuilder Templates.

It would be good to be able to customize these end-points too as they now look so different from the other end-points in terms of design.

Also, if at "My Account" one can show "orders" and from there, one can dig one step further to "**_/view-order/{ORDER_ID}"_** which I believe also would be nice to have a template for.

**Comment by rodolphebertozzo** [comment]
+1000

**Comment by x3mp** [comment]
+1

**Comment by BlueteraLLC** [comment]
+1 - especially for the view-orders endpoint template ability.  I was just looking for that option.  Need to dress that order page up and add more functionality to it.

**Comment by BlueteraLLC** [comment]
@Crocoblock: This functionality has been requested by many people, over multiple years, on Facebook, here and other websites.  It is awesome that we can edit the orders list endpoint template, but it is only partially functional if we cannot also edit the single "view-orders" endpoint.  Why have an awesome orders list page and then something default on the single order page? Please add this functionality for all priority woo endpoints.  Thanks!

**Comment by rtpHarry** [comment]
I've just been trying to test a system that is almost ready to go live and found out that the Order Pay screen can't be styled

**Comment by morosmo** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/2721, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
