### ISSUE TITLE
Advanced Carousel Multi Row

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#501]
Hello, please add in the Jet Elements plugin in the Advanced Carousel widget the ability to choose to display elements in two rows. For example, your competitors have such a widget and this functionality is often used - https://elementpack.pro/demo/element/custom-carousel/
https://prnt.sc/p1a1bn

/*Оригинал*/
Здравствуйте, добавьте пожалуйста в плагине Jet Elements в виджете Advanced Carousel возможность выбрать показ элементов в два ряда. Например у ваших конкурентов есть такой виджет и этот функционал часто используется - https://elementpack.pro/demo/element/custom-carousel/
https://prnt.sc/p1a1bn

**Comment by Floydtm** [comment]
@stasonua0 Hi! You can use this option http://prntscr.com/p1rajf

**Comment by thietaudev** [comment]
Any have idea for slider  for 2 row?, i still have question
