### ISSUE TITLE
JetEgnine Taxonomy Order / Sequence to display backend and frontend 

### ISSUE THREAD

**Issue by futureyoon** [CrocoBlock/suggestions#5011]
https://www.facebook.com/groups/CrocoblockCommunity/posts/5269489263142452/?comment_id=5269497006475011&reply_comment_id=5269509329807112&notif_id=1647057643651742&notif_t=group_comment&ref=notif

![275244936_4908745772543905_4367932245358727070_n](https://user-images.githubusercontent.com/22808337/158007290-36cf65fd-3fd4-459a-b494-484b32ab5baa.jpg)

I have a taxonomy of weekday (Mon, Tue, Wed, Thu, Fri, Sat, Sun)
When I display the selection of this weekday, the sequence goes 
Fri, Mon, Thu, Tue, Sat, Sun, Wed 
It's following the alphabetical order. 
Is there a way to control the sequence of the weekday? like Mon to Sun? 
Please help

**Comment by Floydtm** [comment]
At the moment you can use this [plugin](https://wordpress.org/plugins/intuitive-custom-post-order/)
