### ISSUE TITLE
in jet woobuilder Custom Quantity Selectors + -

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5012]
This plugin is great for jet woobuilder. But won't it integrate with jet woobuilder? It will be much better. Most users are unaware of such a plugin for jet woobuilder. This plugin also has many bugs. So merging it with Jet woobuilder will help develop it. Will this happen in 2022?
https://crocoblock.com/freemium/tools/

**Comment by UraraReika** [comment]
At the moment, we do not plan to include such functionality into our plugin. Now our team is working on more priority tasks.But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
