### ISSUE TITLE
Make an element visible by selecting from smart filter 

### ISSUE THREAD

**Issue by babakneza** [CrocoBlock/suggestions#5013]
Hi,
I have a smart filter to filter my posts. 
I need to make an element visible when user select one of filter items. 
In visibility module how I can define which item was selected in my filters options. 

Thanks in advance.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
