### ISSUE TITLE
Custom product not found for product grid

### ISSUE THREAD

**Issue by mostafasiat** [CrocoBlock/suggestions#5014]
hi
Is it possible to customize the product not found message in this widget? Now we can only edit the text. This is very restrictive. Please add this I really need it. It can also be very useful for other users of this plugin. With this feature we will have a better UI. thanks

**Comment by UraraReika** [comment]
I merged this issue with [#4386](https://github.com/Crocoblock/suggestions/issues/4386), which is on the same subject so we could deal with it more efficiently.
