### ISSUE TITLE
New WooCommerce Product on Frontend with JetEngine

### ISSUE THREAD

**Issue by brjmichael** [CrocoBlock/suggestions#5015]
Hello croco team!  Hope you guys are fine.  Brought some questions and suggestions about JetEngine.

The option to add a new WooCommerce product through the frontend with JetEngine will be interesting.  Currently, when trying to register a product through the **Form Widget**, the data that are entered in the fields defined in the custom Form (price, Sale price...) are only displayed in the fields but are not registered in the product itself.  Is there any other way to do this?

I appreciate the love and dedication of all of you.  Thank you!!  :D

**Comment by mehdimoradi1500** [comment]
+1
I have requested this feature with more details several months ago #4390 
Its totally necessary for JetEngine, being able to add all kind of products from front-end forms
Please add these cool features soon @kaskad88  @Floydtm

**Comment by MjHead** [comment]
WIll be added as separate Post Submit action on next JetFormBuilder update
