### ISSUE TITLE
[JetReviews] Jetengine Usermeta and more

### ISSUE THREAD

**Issue by fabio323ti** [CrocoBlock/suggestions#5016]
I hope someone can help with some settings.
I wish to have usermeta value instead author nickname in reviews section, also Avatar will be nicefull to link to jetengine usermeta.

Another request is to change order field in form review.. description and title are always on first place, can be moved?

many thanks for all.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
