### ISSUE TITLE
Jet woobuilder Recently viewed query

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5017]
On my website, I have provided users with recently visited products, so that they have their visit history. But there is a problem.  Users' browsing history is not recorded in their user panel.
If users visit products and then clear their browser cookies, their entire browsing history will be deleted.This is not really good.  It is better to keep their browsing history in their account so that while they are in their account, they can quickly see the products they have visited.
 Adding to favorites list in the jet compare plugin works the same way. If the user adds a product to their favorites list, that product will be registered in their account.  Therefore, those products will always be available to the user. The recently viewed query should work the same way and the users' observation history should be recorded in their account.

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

In our plugin we use the same method to store recently viewed products as WooCommerce. Cookies `woocommerce_recently_viewed` so if you have some suggestions please contact their team.
