### ISSUE TITLE
JetEngine - product price per volume

### ISSUE THREAD

**Issue by esitio** [CrocoBlock/suggestions#5018]
Hello
Could you add new functionality to jetEngine? 
Add to product price per volume (only show)
I try use dynamic fields, but i'ts not work
If I have price and volume attribute I want to show/calculate price/volume
Example:
1000ml * price (ex. 100$) / volume attribute (ex. 500ml) = 200$ (price for 1000 ml)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
