### ISSUE TITLE
Integration of JetBooking with WebHotelier platform

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#5019]
It would be great if you could create an extention for Jet Booking that integrates the JetBooking to WebHotelier platform.
https://www.webhotelier.net/

**Comment by YossiDavid** [comment]
It will be great!
Thank You!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
