### ISSUE TITLE
Classic Accordion: Add Normal/Hover/Active states for Toggle options

### ISSUE THREAD

**Issue by andrei-nistor** [Crocoblock/suggestions#502]
JetElements: Please add configurable Normal/Hover/Active states tabs for Toggle options in the Classic Accordion widget to allow more flexibility in design. Thank you.
![suggestion](https://user-images.githubusercontent.com/51997613/64187208-7ff60780-ce70-11e9-9ac6-a7bef96059c2.jpg)

**Comment by kaskad88** [comment]
At the moment, we do not plan to introduce such functionality to our plugin. But you can use a custom CSS.
