### ISSUE TITLE
JetThemeCore v2.0.0 Beta

### ISSUE THREAD

**Issue by shinTM** [CrocoBlock/suggestions#5020]
**Hi there, Croco People!**

Despite the war and shelling right outside our windows, we continue working and advancing our plugins.

Today, JetThemeCore Beta v2.0.0 is in the spotlight. It got totally refactored & optimized, yet it's 100% compatibility is guaranteed.

💡 Note: it is a Beta version, so it's not recommended to use on production websites!

CHECK OUT WHAT WE PREPARED

💥Compatibility with WordPress block editor (Gutenberg) 
We added block editor support, so now you can create templates both with Elementor and WordPress block editor. 

💥Multi-conditions for templates

Entire site (e.g., put one header for all web pages)
Singular (display templates/headers/footers on single pages)
Archive (template to output posts archive)
Advanced:
URL Parameter 
Device (mobile, tablet, desktop)
Roles

And from now on, you can assign template conditions right in WordPress admin.

💥Brand new Theme Builder
With its help, you can organize the structure templates, design the so-called Page Templates, and identify the pages where these templates are assigned. 

💥Page templates filtering, searching & importing
You can search the templates by name, filter them by type (page, archive, single, etc.), and import with one button click. 

Go test everything! We appreciate (and deadly need) your feedback, so feel free to share your experience about using the beta in the comments below or on the related Github page.

**Code Refactoring**

The code was completely rendered, thus we rebuilt the location rendering system for templates: headers, footers, pages, singles, and archives. The templates and theirs render work at the same theme locations as before. 

**Gutenberg Support**

Added WordPress block editor (Gutenberg) support. We added the ability to create templates using Gutenberg as the main editor. The Elementor page builder acts as the compatible plugin now https://prnt.sc/VirRYAjd2On2 

**Multiple Changes in the Templates’ Conditions**

- Added the ability to apply multiple conditions to the templates along with the ability to exclude some of them as well. Thanks to that, it would allow more flexibly customize the templates’ 
output. 
- The Conditions manager was moved from the element editor to the WordPress admin panel, now they are on the same level, and you can see the currently active header template https://prnt.sc/7nfmmdh3q7Sp 
- A new Advanced condition category was added. It allows applying the following conditions for the templates: 
-- Parameter URL
-- Roles
-- Devices
https://prnt.sc/PLW7bMr8e5lM 

**Brand New Theme Builder and Its Workflow**

We added a new Theme Builder located in the admin panel in the tab Crocoblock > Theme Builder https://prnt.sc/WGaoPnlQ-6GR  Its main purpose is to organize the templates’ structure, form the Page Templates, and assign them to the pages on where they would be rendered.

- Every template contains three structure elements: header, body, footer. https://prnt.sc/CNSJL5TAU-Ir For these structures, you can use either already created templates, or create new ones https://prnt.sc/0vzgE4u0eTeo 
 All previously created templates are added to the Template Library https://prnt.sc/0EZSy8WdmT81 and can be reused in any Page template structure. Assigned render conditions for templates have no impact on the page templates since Page Templates has its own Condition Manager for the entire block.
- When creating a new page template, the first thing to do is to specify the render conditions via the Condition Manager. It is not necessary at this stage and the template will be in the Unassigned status and, accordingly, if there are no render conditions, then it will not be taken into account. The conditions can be set in the Condition Manager at any time. Also, there are options for duplicating, exporting, and deleting https://prnt.sc/zo95YK03vVA8 the Page Templates. 
- By specifying the conditions for rendering, the page template automatically determines the template type for the body structure. At the moment there can be three types: Page, Single, Archive https://prnt.sc/s0vVuE4bgWB-
- Page templates work with any theme. Thus, assigning the conditions for rendering on the page, we can rewrite one or all of the page structures. If the structure of the page template is empty or disabled, the builder will pull it from the theme itself https://prnt.sc/MeNLKB09eaoC 
- In the Theme Builder, there are options to sort, search, import page templates. https://prnt.sc/QhU6K6D1dg-Q

**Comment by IgorDark** [comment]
No condition for author archive 

![image](https://user-images.githubusercontent.com/40338883/158435104-4f23aa4e-e436-43cb-aded-65e97ef1dcb5.png)

**Comment by sabiertas** [comment]
Magnificent news!! I'm testing this beta in a project that I just started and when I installed it the Kava Theme link was duplicated in the side menu

**Comment by ghost** [comment]
I am still in treatment for a head injury in December, but saw your working despite suffering and will spend some time testing your release. I will add any comments as I can. I noticed the Section theme part is missing from the Template content type dropdown. A screenshot is available [here](https://www.screencast.com/t/aXPgDC0v)

**Comment by shinTM** [comment]
hi wordfishgroup, thank you for your support) we have removed the ability to create sections, as this is the same as pages, and they are not used

**Comment by ghost** [comment]
> hi wordfishgroup, thank you for your support) we have removed the ability to create sections, as this is the same as pages, and they are not used

I think you want to remove the Section Tab from the Theme Parts so as to be consistent with The Theme Content Type dropdown?

**Comment by Clicktoweb** [comment]
Hi everyone.. testing your beta version of Themecore was a pleasure, and I think many people wish they could do more to help you in this difficult time. 
Here are my feedbacks : I think you should resize the pop-up for conditions, as you can see in the screenshot  it goes under left sidebar.
<img width="1412" alt="Capture d’écran 2022-03-18 à 10 56 35" src="https://user-images.githubusercontent.com/101868369/158984275-031cc3f2-8b9d-4574-9be2-620fa9d62295.png">

For Advanced conditions - Device => maybe a selector with devices should be easier than a text field, it's not clear if we have to put px sizes or smartphone, tablet etc.. I have tried excluding smartphone or mobile but no result, still showing header on mobile device.
