### ISSUE TITLE
Jetengine caught an error

### ISSUE THREAD

**Issue by ahmedawais** [CrocoBlock/suggestions#5024]
CRITICAL] : Uncaught Error: Class 'Jet_Engine_Dynamic_Tags_Module' not found in /home/website/html/wp-content/plugins/jet-engine/includes/modules/dynamic-visibility/inc/settings.php:168
The plugin can not be update because of this issue. Could you please help

**Comment by Floydtm** [comment]
Contact our support team, the guys will help you solve the problem. Thank you!
