### ISSUE TITLE
Please: Ban following symbols for user front end inputs

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5025]
the users are theoretically able to do things that they shouldn't be able to do...
I'd suggest, to disallow these guys: `<` `>` `[` `]` `%`
So that no html or shortcode will be rendered on places they don't belong to.

https://user-images.githubusercontent.com/101653721/158686624-605538da-aa8f-4430-8cf8-3f7861f72a41.mp4

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
