### ISSUE TITLE
[JetEngine] Add icon field to Dynamic Repeater

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#5026]
I see the dynamic repeater widget field is missing the icon field like other dynamic widgets. It's really inconvenient when other fields have it built in but dynamic repeater doesn't.
Can you add the icon field to the dynamic repeater in the next update?
Thank you.
![image](https://user-images.githubusercontent.com/89138954/158737645-d04006a1-176a-4951-bc90-292eed21f85e.png)
![image](https://user-images.githubusercontent.com/89138954/158737708-2cc2a43f-a9bf-4b6f-a75e-953f5ae723bf.png)
![image](https://user-images.githubusercontent.com/89138954/158737797-c2b7154f-2b03-4dbb-a9c4-9ca632bffc57.png)

**Comment by taidang26** [comment]
Please add the icon adjustment before or after the label too. For all other dynamic field widgets
![image](https://user-images.githubusercontent.com/89138954/159403264-67f18f01-81c1-471e-9596-35ea28055135.png)

**Comment by kellyrenee814** [comment]
Adding the icon capability be a dream come true :)

**Comment by bbua97** [comment]
+1

**Comment by rustyrayzor** [comment]
+1 i'm honestly surprised this isn't a thing yet o_O

**Comment by cnbizz** [comment]
+1 I want this.

**Comment by simonmilz** [comment]
+1 makes totally sense

**Comment by Galibri** [comment]
This is still missing, even we can't find a macro for it to use in dynamic repeater field.

**Comment by muztagol** [comment]
+1

**Comment by nealzie** [comment]
Can't believe this isn't possible yet!

**Comment by MjHead** [comment]
For such cases you can use Repeater Query + Listing Grid

**Comment by briski-design** [comment]
+1

**Comment by RickSenhorini** [comment]
The dynamic repeater field that exists is now possible to add an icon through the iconpicker.
after creating the repeater:
![image](https://github.com/Crocoblock/suggestions/assets/164532694/cb97813b-a67d-49ab-a1af-907ab293a24a)

configuring the dynamic repeater widget:
![image](https://github.com/Crocoblock/suggestions/assets/164532694/ea210618-43c8-4c5b-8190-e62bf37f5a1a)

and here is the published page:
![image](https://github.com/Crocoblock/suggestions/assets/164532694/f1b3fd42-019b-4a32-ba66-8bbf3fc31de5)

**Comment by RickSenhorini** [comment]
> The dynamic repeater field that exists is now possible to add an icon through the iconpicker. after creating the repeater: ![image](https://private-user-images.githubusercontent.com/164532694/316083152-cb97813b-a67d-49ab-a1af-907ab293a24a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI2OTEsIm5iZiI6MTcxMTEyMjM5MSwicGF0aCI6Ii8xNjQ1MzI2OTQvMzE2MDgzMTUyLWNiOTc4MTNiLWE2N2QtNDlhYi1hMWFmLTkwN2FiMjkzYTI0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzgxMWMzYjAzM2E5MmU5ZWQyNGFkMjI0YzVjYWM5OTBiMjFlMDI0YWFlMzZkN2FjNmU1YjI4ZDU3N2IzZDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g4D_OkbZ2Ktcf6GOFfBi13PEKdBzOYdd5x1xnS_h_Pk)
> 
> configuring the dynamic repeater widget: ![image](https://private-user-images.githubusercontent.com/164532694/316083521-ea210618-43c8-4c5b-8190-e62bf37f5a1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI2OTEsIm5iZiI6MTcxMTEyMjM5MSwicGF0aCI6Ii8xNjQ1MzI2OTQvMzE2MDgzNTIxLWVhMjEwNjE4LTQzYzgtNGM1Yi04MTkwLWU2MmJmMzdmNWExYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTU2ZDZiMTkyY2EyZjdlZTNhMDQwZDg1Mjc5ZDcxYjM1ZGNkNGU0ZDlhY2Q4ZjhjNWU2MzhkMWFhZTE2MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SYlZz-VxS6ejKpGPn4Ep7tQm7w6ky57nV-djrNDSntM)
> 
> and here is the published page: ![image](https://private-user-images.githubusercontent.com/164532694/316083836-f1b3fd42-019b-4a32-ba66-8bbf3fc31de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI2OTEsIm5iZiI6MTcxMTEyMjM5MSwicGF0aCI6Ii8xNjQ1MzI2OTQvMzE2MDgzODM2LWYxYjNmZDQyLTAxOWItNGEzMi1iYTY2LThiYmYzZmMzMWRlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjM1MDk3OTdlNGJjNjIyY2RmZmNmZjQ1NzcwMTg3OTc2OTllZDk3MGRkNzY3MmVhNmUzZTAyYmVlOTg5ZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vYjYX5wgU63fNQrgtHWuMT0nDmSLxzFUS3w7RjhGexo)

<p><i style="color: %cores-icone%; font-size: 30px; vertical-align: middle;" class="fas %teste-icon-svg%"></i>&nbsp; <span style="">%teste-icon-texto%</span></p>

**Comment by RickSenhorini** [comment]
`<p><i style="color: %cores-icone%; font-size: 30px; vertical-align: middle;" class="fas %teste-icon-svg%"></i>&nbsp; <span style="">%teste-icon-texto%</span></p>
`

**Comment by ofmarconi** [comment]
@RickSenhorini If the FontAwesome SVG option is active, it won't work, right?
