### ISSUE TITLE
[JetSmartFilter] Date Range filter, Date Period Filter, Sorting Filter for Repeater Field Date

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#5030]
I have created 1 Meta Field for "Event" CPT. It has a Repeater Field of type Date for events that can happen over several days and I'm having problems with the filter and sort.

Currently, JetSmartFilter is supporting Meta Date, but not yet supporting Date Repeater Field.

Please update it in the future.
![image](https://user-images.githubusercontent.com/89138954/158939224-b8a957e2-5539-49da-a66e-3ed9441438cf.png)
![image](https://user-images.githubusercontent.com/89138954/158940611-7bdca6ca-4db6-44c0-90f5-15f981ba1d1c.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
