### ISSUE TITLE
Ability to disable the navigation display in the product grid widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5032]
I use the product network widget to display the carousel of my products. This widget is powerful in every way, but I have a problem with it.
I do not want the navigation points to be displayed on the desktop. But be displayed on tablets and mobiles. Unfortunately, I can not have such a thing now. Because if I turn off the navigation option, it will also turn off for tablets and mobiles. I think adding a responsive option to the on / off navigation button will solve this problem.

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

This is not the case in this situation. Most slider options handle in JS with Swiper Carousel Library and we can't put some options to breakpoint system. So in this case you can just make font of point `0` in [desktop](https://tppr.me/mkmvD) and actual size in [tablet](https://tppr.me/vpMbT) and mobile.
