### ISSUE TITLE
Set background-image-size

### ISSUE THREAD

**Issue by glorpyz** [CrocoBlock/suggestions#5034]
I would love if Crocoblock would make a function so you can set image size on background images.
Example:

- We upload image, it get copied in different sizes.
- We start create a loop template in Elementor Pro.
- And make a 250x250px column and choose an dynamic background-image and set it center center, cover.
= It will display the full size image in a 250x250 column.

This is unnecessary file transfer which affects the loading speed.

I would like adding a setting where you can choose which background-image-size you want to use of the existing copies. Just like Elementors Responsive Images settings, but for backgroundimages. 
And making it work with your Alternative Listing Template Injections in Listing Grid.

It would become a super product since almost nobody have made a pluginsolution for this. ;-)
Thanks

**Comment by Floydtm** [comment]
I think you'd better leave it [here](https://github.com/elementor/elementor/issues)
