### ISSUE TITLE
JetWooBuilder Products Grid Switcher / Product Loop Load More

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5035]
Pruducts Grid widget got many settings, Product Loop got none. But in Product Loop widget there is a view Switcher, which can switch product view from grid to list. Products Grid widget must have same functions. And same goes to Product Loop widget which have no Load More Add-on.

In modern webstores there is a Switcher / Pagination / Load More / Filters always. Can we make it happen with only one widget (Products Grid / Product Loop)?

**Comment by UraraReika** [comment]
Hello @s5t5n !

Products Grid and Products Loop two different widgets that is why they are different and has it own features, otherwise it would be one widget. In any case all this features will be implemented in our plugins set.
