### ISSUE TITLE
NaN value, JetSmartFilters problem

### ISSUE THREAD

**Issue by PDA77HU** [CrocoBlock/suggestions#5037]
**Describe the bug**

Hi, I am using WPML + Elementor Pro + Crocoblock plugins and I have an issue. With the original language everything works fine, but when I try to change the language, I can see that it download the products, but also applies a filter which was not requested by me. It makes a JetSmartFilter Action, and set the price rage to NaN _ NaN so it will show only the product without prices. When I click on my price range filter it starts working fine. 

**To Reproduce**

Its an adult content webshop site, just fyi, but here are the steps 

1. Go to ['https://tinyurl.com/2p8shpyc']
2. Click on 'if the English language is not chosen, then choose it'
3. Scroll down to '...'
4. See error - the result is wrong. If you try to use the price range filter you will see what happens. Then change the language to hungarian, you will see it works fine. 

**Expected behavior**

The page should not start filtering when the it loads automatically or it should use the prices. 

**Screenshots**
This is the normal request: https://ibb.co/2FMb99k
This is the bad request: https://ibb.co/FznDDD5

**Desktop (please complete the following information):**
Its the same on all OS.

**Comment by SargasTM** [comment]
Перепроверьте
