### ISSUE TITLE
JetSmartFilters cant query the second currency

### ISSUE THREAD

**Issue by PDA77HU** [CrocoBlock/suggestions#5038]
**Describe the bug**

I am using JetSmartFilters and _price tag to query the price of the products. And I am trying to use a language switcher plugin, I tried WPML, and other multi-currency switching plugins but all was the same at the end. 

The problem is: the jetsmartfilters can only query and show the default price, and even when the page language and currency change, the price range filter stays in the original currency. 

**To Reproduce**
You can check it in the page I previously posted in the other Bug report. 

**Expected behavior**

When the currency changes on the page, it should follow it. 

**Screenshots**

This is what the price range filter shows: https://ibb.co/cv9q8ZK
These are the product prices: https://ibb.co/s5SCJ1h

**Desktop (please complete the following information):**
- Same on all OS

**Comment by AdamPZeno** [comment]
Has this been fixed guys?

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
