### ISSUE TITLE
JetWoobuilder - How to add increase or decrease the number of products button?

### ISSUE THREAD

**Issue by ki96hn** [Crocoblock/suggestions#504]

**Comment by Floydtm** [comment]
@ki96hn, Hi! Please provide more information on your request

**Comment by ki96hn** [comment]
http://prntscr.com/p23yjd
I want to have two button "+", "-" for quantity when add to cart. same as:
http://prntscr.com/p2406v

Vào Th 5, 5 thg 9, 2019 vào lúc 16:40 Floyd <notifications@github.com> đã
viết:

**Comment by ki96hn** [comment]
This problem will affect to UX, please upgrade this features!

**Comment by ki96hn** [comment]
@Floydtm : Can you tell me about this question?

**Comment by Floydtm** [comment]
@ki96hn, I am sorry for the long delay! At the moment, we cannot add this to the plugin, because it is often added to the theme itself. There may be conflicts

**Comment by sonnesworld** [comment]
Yes please! Need this as well
