### ISSUE TITLE
Jetengine not working with new Elementor 3.6

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#5042]
Hi guys 

Elementor 3.6 just came out https://github.com/elementor/elementor/releases/tag/v3.6.0 and if you use the new flexbox container it doesn't work with Jetengine.

**Comment by Floydtm** [comment]
We will definitely make compatibility with the new version of the plugin. However, you should have noticed that the [alpha](https://prnt.sc/Qb_mVQ3d7Pgu) status, there will still be edits from the very developers of the elementor

**Comment by Floydtm** [comment]
I understand you. This is your choice
