### ISSUE TITLE
JetWooBuilder Products Grid / Product Loop Lazy Loading

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5044]
Products Grid & Product Loop must have lazy loading feature. Not for the images. For products.

Best illustration for how it must work is a GridBuilderWP Plugin (https://demos.wpgridbuilder.com/, https://demos.wpgridbuilder.com/portfolio/), it would be really cool if products can be loaded with different animations depending of screen position same as any elementor widget can be configured in "advanced - motion effects - entrance animation". And it would be better if this feature could work with DELAY option like https://scrollrevealjs.org/ works, if u know what i mean, so there will be some delay option for products loading as they enter/leave the viewport.

**Comment by UraraReika** [comment]
I merged this issue with [#4987](https://github.com/Crocoblock/suggestions/issues/4987), which is on the same subject so we could deal with it more efficiently.
