### ISSUE TITLE
Capability Type other than post in JetEngine Custom post type bug

### ISSUE THREAD

**Issue by heisenberg0924** [CrocoBlock/suggestions#5045]
If I set any Capability Type other than post, in JetEngine Custom post type, I can't publish any post in that CPT.
![1](https://user-images.githubusercontent.com/79441248/159365801-fd31d28e-018d-45ab-b07b-4f7d8eba844f.png)
![2](https://user-images.githubusercontent.com/79441248/159365803-13af2b92-5691-4d6f-bbb0-75322ba3018e.png)

**Comment by Floydtm** [comment]
Please study these tutorials https://crocoblock.com/knowledge-base/articles/how-to-create-a-custom-post-type-based-on-jetengine-plugin/#title5 https://wordpress.org/support/article/roles-and-capabilities/
