### ISSUE TITLE
[🐛Jetformbuilder] `select` impossible to select the placeholder after the first click

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5046]
By correctly placing 3  Select Field> Terms (status , type and city) 

and despite having checked and placed a placeholder text (select...)
I can't select them (placeholder) by default after the first click.

something is forcing me to do only the available choices.

![select](https://user-images.githubusercontent.com/82481592/159398380-bed897e7-5216-40b3-b1f6-d8f36eff66fa.gif)

**Jetengine forms** 

![jetengine form](https://user-images.githubusercontent.com/82481592/173888123-263b44ae-f6fc-4b1d-a2ac-dfad868c04f3.gif)

**Comment by girafffee** [comment]
Fixed in 2.1.0 version
https://prnt.sc/z5Oncm6hJNQr
