### ISSUE TITLE
jet woobuilder load more plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5047]
**Please, describe the feature request, making it clear to understand.**

The load more plugin is great. You mentioned earlier that it will be added to the jet woobuilder core soon. So I had a suggestion for this great feature, please check if possible ...

in jet woobuilder Load more , When we click the button to load more products, there is no [loading](https://prnt.sc/76OBJWLfMWzj) on the button.
In fact, we now have the same functionality in elementor pro. Please watch the video below : 

https://user-images.githubusercontent.com/77163248/159455242-0691dd13-fa09-44c0-92c3-386e4ed4cdad.mp4

Of course, jet woobuilder uses the elementor button widget for load more . I'm not sure if this will be possible or not. Anyway, great if added.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

You can connected load more click functionality basically to every element you want so just connect this to presented in video functionality and that is all.

**Comment by 79ho3ein** [comment]
hi @UraraReika, thank you. Maybe I did not understand what you mean ...
Was your solution for button action? Or spinner loading after clicking?
