### ISSUE TITLE
Listing Grid to display custom block of no data is found

### ISSUE THREAD

**Issue by casperroux** [Crocoblock/suggestions#505]
Please add ability to read elementor template for here....

![2019-09-04_174205](https://user-images.githubusercontent.com/8598232/64270393-bb113d00-cf3b-11e9-97ad-a874b812d853.jpg)

Created a Events CPT but want to display elementor template when there is no upcoming event at this time....

But can be hiden when an event is added again...

**Comment by Floydtm** [comment]
@casperroux, Hi! Starting with version 1.4.0 this field supports shortcodes

**Comment by casperroux** [comment]
Thanks... will give it a try :)

**Comment by casperroux** [comment]
Work GREAT..... Thanks for the info :)
