### ISSUE TITLE
search filter bug - jet smart filters.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5050]
**Describe the bug**

If we enable the search feature in visual filters, checkboxes and radio filters, there is a bug.

The problem is that we have two buttons to clear the text written in the search box, which has completely destroyed the UI. Please see this image : https://prnt.sc/GeEd4Ia2CKdu

In fact, the delete button (blue) should be removed because its color and size can not be customized. **It should be noted that the image above is in RTL condition.**
This is how it is in LTR : https://prnt.sc/oz_7Z-8Fp2Vf

**To Reproduce**

1- Add a visual widget, radio or checkbox.
2- In the Additional settings, enable the search option.
3- Type a text experimentally. **2 buttons will appear to delete the text.**

thnak you

**Comment by Floydtm** [comment]
Same problem with hello, blocksy, generate press, ocean wp themes https://prnt.sc/sKyXMq9K4zjH there is a suggestion replace this with svg load control

**Comment by 79ho3ein** [comment]
Thank you for your attention @Floydtm.
Will this be fixed in future versions?

**Comment by Floydtm** [comment]
just stay tuned

**Comment by 79ho3ein** [comment]
Thank you @Floydtm

**Comment by SargasTM** [comment]
Пофиксил
