### ISSUE TITLE
Problem choosing template for jet woobuilder products

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5054]
https://prnt.sc/mSHvcJPVnMfT
Every time I add a product to the website, I have to select the jet woobuilder template from the product page section. This is really painful. Why should it be like this? We have to do this for each product. If we do not, the product page will be displayed completely corrupted. Is it possible to correct this? In such a way that we only once determine in what template the products will be displayed.
Our customers are always complaining about this, but there is currently no way out.

**Comment by UraraReika** [comment]
I merged this issue with [#4450](https://github.com/Crocoblock/suggestions/issues/4450), which is on the same subject so we could deal with it more efficiently.
