### ISSUE TITLE
Jet Engine - Query builder allow SQL query joins on joined tables not just base table

### ISSUE THREAD

**Issue by Paul-Heron** [CrocoBlock/suggestions#5059]
The SQL query builder allows you to add multiple joins on tables, but the join table condition must use a value from 'Is equal to base table column' which, unless I'm missing something, does not allow for more complex relationships to be queried properly. 

Ideally, you should be able to choose a value from the previous join not just the base table so that you can correctly join the tables using the relational tables you have created in jetengine e.g.  workouts CPT ->  workouts-exercises relation  ->  exercises CPT

Sorry if I have missed something but I could not find any information and this is my first time using the plugin.

**Comment by bbua97** [comment]
I have the same problem, I have to join different tables without an compare to base table. I need to create/join a "chain" of tables first until I can compare to the base table.
