### ISSUE TITLE
Jet Compare Wishlist request

### ISSUE THREAD

**Issue by StevePositive** [Crocoblock/suggestions#506]
Hello guys,
I find it really annoying that there's no option to style archive wishlist setting - not even to change button text. For me your plugin is not complete.
I would love to have just simple heart added to every picture on product archive.

You should consider adding at least these options to the plugin settings:
* change the text of the button,
* change colors of the button,
* pick the icon,
* change the position of button - under or above product picture - so it would be easier to transform it.

**Comment by emreozpalamutcu** [comment]
I agree it's so annoying. It's been 4 months and they should've solved this by now, let alone it's not even scheduled.

**Comment by Floydtm** [comment]
Guys, with the help of the [jetwoobuilder](https://crocoblock.com/plugins/jetwoobuilder/) and [jetcomparewishlist ](https://crocoblock.com/plugins/jetcomparewishlist/)plugins you can implement any design. Without the jetwoobuilder plugin, you only get integration with default [templates](https://prnt.sc/qkrcp3)

**Comment by emreozpalamutcu** [comment]
Not if you're using Archive Single Template, then there are no options to display wishlist on the product photo, like on the other templates.

**Comment by Floydtm** [comment]
@emreozpalamutcu, hi! Using the elementor plugin or the jetcomparewishlist settings, you can position the elements as you like. Also you can customize everything with css

**Comment by emreozpalamutcu** [comment]
Hi,
Have a look at this photo: https://crocoblock.com/wp-content/uploads/2019/07/icons.jpg

On the archive single, how would I make the button look like that and place it exactly on the photo?

On normal page, when I used the product grid, there would be options to achieve but not possible if you use the product loop.

**Comment by Floydtm** [comment]
For example http://prntscr.com/qlr50s  http://prntscr.com/qlr5b1 http://prntscr.com/qlr5ou http://prntscr.com/qlr5zg http://prntscr.com/qlr6d2
