### ISSUE TITLE
Jet Engine map doesn't work

### ISSUE THREAD

**Issue by DJAZZDESIGN** [CrocoBlock/suggestions#5060]
When we click on an icon on the map, the boxes linked with Listing don't open. We see only [object Object] and the icon to close the box and the black arrow.

To Reproduce
1. Go to https://microbrasserie.stpancrace.com/en/production/our-beers/beer-finder/
2. Click on an icon on the map to open any Sale point on the map to see normaly the information about Sale point
3. See error, the box linked to Jet Engine Listing does't work.

**Desktop:**
 - OS 12.3
 - Browser Safari
 - Version 15.4

<img width="311" alt="Capture d’écran, le 2022-03-23 à 12 19 11" src="https://user-images.githubusercontent.com/102245094/159747503-7dae1800-2d09-4dba-80ad-dfcbc5f420d7.png">

**Comment by DJAZZDESIGN** [comment]
Finally, it's all the Crocoblock plugins that cause problems for the site. When I uninstall all Jet plugins, Elementor works again. Do you have any idea what is in conflict? Thanks for your help

**Comment by Floydtm** [comment]
It's hard for me to answer this. We checked everything on the latest versions of the plugins and everything seems to be working correctly https://prnt.sc/wpCAOlBD2ser Contact our support team to resolve your issue
