### ISSUE TITLE
jet woobuilder Custom "not found message" bug.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5062]
**Describe the bug**

I display the product archive using the product grid widget. In addition, with the jet smart filters plugin, I filter products in the archive.
I tried to use the [code](https://prnt.sc/WlF_TFreZNUC) in product archive. So that if no product is found based on the desired filters, a custom "Product not found" message will be displayed. But it does not work and the desired template is not called!
The problem is not the code. Because I use this code in the carousels of this website and the custom template is displayed without any problems.
Using the search filter, I searched for a product that does not exist, but the desired template is not called.

**To Reproduce**
If you do not succeed in reproducing, I will send more details.

thank you

**Comment by 79ho3ein** [comment]
I had a suggestion regarding this issue ...

Currently, we only have [this section](https://prnt.sc/a-orUE1kJpRR) in the product grid widget, where the message "product not found" is displayed if there is no product.
But for example, if users want to write another message after using filters if there is no product. For example, the desired filter was not found!
But such a thing is not possible now.
Great if you add a new field in [this section](https://prnt.sc/ctkf7i56GoHr). (Similar to the blue box) **This field is displayed when the jet smart filters plugin is enabled!**
Using this field, we can specify what message will be displayed if the user uses the product filter and no result is found. this is great. By adding this feature, the bug reported above will definitely be fixed.
Of course, if I'm not mistaken, a similar offer was previously sent by other users for jet woobuilder, but I did not find it ...

**Comment by UraraReika** [comment]
Please track this [issue](https://github.com/Crocoblock/suggestions/issues/4386) when it will be done all this things will be fixed.

**Comment by 79ho3ein** [comment]
thanks
