### ISSUE TITLE
JetWooBuilder Product Grid how many products are shown switcher

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5067]
There must be an option to switch how many products are shown in grid. Sample: 15 / 30 / 45. And it must be customizable, such as 12 / 18 / 24 etc. And it must have settings to switch view from links (ajax) to dropdown. TY

**Comment by UraraReika** [comment]
I merged this issue with [#4680](https://github.com/Crocoblock/suggestions/issues/4680), which is on the same subject so we could deal with it more efficiently.
