### ISSUE TITLE
Show JetEngine Forms Submissions in the Backend e.g. In Option Page

### ISSUE THREAD

**Issue by emakx** [CrocoBlock/suggestions#5068]
Hello,

Thank you so much for the huge and amazing work you are doing, But I am quite surprised why you don't have to feature to show the form submissions in the WP Back end, something similar to Elementor Submissions.

Are there any plans to add this feature in the near future?

**Comment by girafffee** [comment]
Hi @emakx, I will notify you when this feature is released. You can expect it soon ☺️

**Comment by girafffee** [comment]
Added this functionality in latest versions of JetFormBuilder.
