### ISSUE TITLE
Add Google Map Adaptive Height

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#507]
Good afternoon, please add adaptive height to the Advanced Map widget from the Jet Elements plugin - https://prnt.sc/p2kbzp

/*Оригинал*/
Добрый день, прошу добавить адаптивную высоту в виджете Advanced Map от плагина Jet Elements - https://prnt.sc/p2kbzp

**Comment by kaskad88** [comment]
Added for next version.
Thanks for your report.
