### ISSUE TITLE
JetBlocks Cart Widget style breaks on multiple pages.

### ISSUE THREAD

**Issue by x3mp** [CrocoBlock/suggestions#5071]
**Describe the bug**
The style of the Cart widget completely breaks when on the My Account, Checkout or Cart page.

**To Reproduce**
1. Add a product to the cart
2. Go to any of the said pages above.
3. Open the cart.

**Expected behavior**
The style should not break.

**Screenshots**
In this image the cart is working fine:
![image](https://user-images.githubusercontent.com/12957439/159949650-bb6387a9-e2d3-44b8-aece-411d362d5ae4.png)

The following image is taken on the My Account page:
![image](https://user-images.githubusercontent.com/12957439/159949803-6a80f062-c97d-4c84-b1bc-5ecf8afcb74a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.82

**Additional context**
If trying to fix the style by adding manual CSS its not gonna be the exact same. I spent an hour trying this and this did not result in a 1:1 look from the original.

**Comment by Floydtm** [comment]
What theme are you using?

**Comment by x3mp** [comment]
> What theme are you using?

I'm using the Hello Theme for Elementor.

**Comment by Floydtm** [comment]
We checked everything again and can't get a bug on our side. Could you contact our support team to resolve this issue
