### ISSUE TITLE
🐛🐛JetFormbuilder big bug after switching to elementor 3.6.1

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5072]
Confirmed Bug 
JetFormbuilder lost ability to post and edit (insert/update post)

testing conditions : 
- clean install Wordpress 5.9.2
- jetformbuilder 1.5.5
-  jetengine  2.11.6
- elementor 3.6.1
- elementor pro 3.6.4

open jetformbuilder create a simple post form
send

![Capture d’écran 2022-03-25 020900](https://user-images.githubusercontent.com/82481592/160035575-7e352b60-57be-4385-83b4-93168e6079e6.png)

observe the strange behavior..

on my production site , when you try edit post / post new post a destruction of the account page is inevitable and the new post takes the place of the account page (zombification?)

I hope the culprit will be quickly found .
the php log is full of errors I think you will see it very quickly

**Comment by Floydtm** [comment]
We checked everything again and can't get a bug on our side. Could you contact our support team to resolve this issue
