### ISSUE TITLE
Ability to insert a custom icon (tick) after selecting filters

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5075]
Please add the ability to insert a custom icon for the tick icon : https://prnt.sc/35X_OlQNS6bu
This symbol is required in checkbox, radio and visual filters.
Also in the visual widget > Color, if users select a filter, only the border will be colored. But there really should be no difference between a visual widget and a checkbox and radio. Please add a feature, which will check the desired filter after the user selects the visual filter (color). https://prnt.sc/PIjMcutNOCId

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
