### ISSUE TITLE
Implement User Geolocation for things like Store Locator

### ISSUE THREAD

**Issue by GoncaloSaMKT** [CrocoBlock/suggestions#5076]
Hi everyone,

I've been building a website for a client of mine that owns a Franchise. As the business is expanding there are more and more locations opening.

I've been able to create a Map Listing that shows the various different locations added to the backend, but apparently there is currently no way for a user to filter the locations showing first the one that is closest to them, as any store locator feature would.

That's the reason why I believe this could be a great add-on to Crocoblock, as I'm sure I'm not the first or last who would need it and there's a clear lack of decent plugins out there with this option available.

Have a great weekend,
Goncalo Sa

**Comment by Topicimes** [comment]
+1

This is a feature that is in high demand. There are already many requests for it.

**Comment by pieter-vanhove** [comment]
+1

**Comment by mateitudor** [comment]
I second this...

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
