### ISSUE TITLE
JetEngine - Listing grid injections missing option

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5077]
It would be very helpful if we have a new option for the listing grid ijections extension settings. currently we oly can output a different template it its the Nth number of something or if the corresponding post has certain meta value. I miss the option that we can set shot this template is this post has certain terms/taxonomy(ies)

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
