### ISSUE TITLE
JetEngine - Custom Image size option

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5078]
Currently I use the elementor image module for displaying also dynamic media fields even if ifid the image module from you guys much more cooler and with more settings. but one big option is  missing. you should give us the option to set custom width, height and an object ratio/fit. This setting i really miss.

https://user-images.githubusercontent.com/101653721/160151695-ec326fb9-04ba-4c36-9f43-09f8fb466463.mp4

**Comment by mehdimoradi1500** [comment]
Yes exactly
That's why i use elementor image widget, it should be added

**Comment by maurocarreraok** [comment]
Yes. Please add this. Working with Dynamic Images and Repeater Images it's very complicated.

**Comment by kaskad88** [comment]
Add for the next version 2.11.11
