### ISSUE TITLE
🐛Jetformbuilder bug when redirect to page

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5082]
Hello ,
I Found the source of the bug
despite that @Floydtm said everything is fine 😅
here is how to reproduce the bug

a new wordpress installation all plugins up to date

- jetformbuilder 1.5.5
- jetengine 2.11.6
- elementor 3.6.1
- elementor pro 3.6.4
- make sure before that php_errors.log is empty

create from scratch

- an account page and new post form
- Use redirect to page in the form (to account or any page)
- Send

![Capture d’écran 2022-03-25 182246](https://user-images.githubusercontent.com/82481592/160171772-8143f2fb-d9cf-4490-803a-bb5caa8a0e76.png)

see your log

![Capture d’écran 2022-03-25 183121](https://user-images.githubusercontent.com/82481592/160172311-04931891-36ec-4400-8afc-0f3032489133.png)

```
[25-Mar-2022 17:13:41 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_built_with_elementor() on bool in C:\laragon\www\test\wp-content\plugins\elementor\core\app\modules\import-export\module.php:399
Stack trace:
#0 C:\laragon\www\test\wp-content\plugins\elementor\core\app\modules\import-export\module.php(373): Elementor\Core\App\Modules\ImportExport\Module->get_elementor_page_url('13')
#1 C:\laragon\www\test\wp-content\plugins\elementor\core\app\modules\import-export\module.php(425): Elementor\Core\App\Modules\ImportExport\Module->get_elementor_home_page_url()
#2 C:\laragon\www\test\wp-content\plugins\elementor\core\app\modules\import-export\module.php(63): Elementor\Core\App\Modules\ImportExport\Module->get_config_data()
#3 C:\laragon\www\test\wp-content\plugins\elementor\core\base\base-object.php(142): Elementor\Core\App\Modules\ImportExport\Module->get_init_settings()
#4 C:\laragon\www\test\wp-content\plugins\elementor\core\base\base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings()
#5 C:\laragon\www\test\wp-conte in C:\laragon\www\test\wp-content\plugins\elementor\core\app\modules\import-export\module.php on line 399
```

now remove redirect 

![Capture d’écran 2022-03-25 183454](https://user-images.githubusercontent.com/82481592/160172609-56d1732a-1437-40c1-a8aa-365794b6b2c3.png)

do another test 

![Capture d’écran 2022-03-25 182033](https://user-images.githubusercontent.com/82481592/160172643-18cac525-a551-4cea-840d-bcaeedd11742.png)

no errors now

**Comment by Floydtm** [comment]
I suggested that you contact the support to resolve your request. And I don't see anything wrong with that.

**Comment by girafffee** [comment]
Hi @nreljed!
Can you show the settings of your Redirect to Page action?

**Comment by nreljed** [comment]
@girafffee 

Content redirect

![redirect](https://user-images.githubusercontent.com/82481592/160181025-624cc9da-56c5-4759-b34d-46b4dccbca0a.png)


Content account page

![elementor account](https://user-images.githubusercontent.com/82481592/160181066-32fc6a35-8f50-468f-a90e-7238bde91f52.png)


if it can help the content profile builder but nothing abnormal here

![account](https://user-images.githubusercontent.com/82481592/160181682-8b32a0a8-3312-4b47-9163-da461bf48938.png)

**Comment by girafffee** [comment]
`add_filter( 'jet-form-builder/dev-mode/activate', '__return_true' );`

Place this filter in your theme's functions.php file. Next the requested form to submit via Ajax and once the request is done show all the contents of `__logger`

![image](https://user-images.githubusercontent.com/46720998/160189803-3f3cef27-c98e-4946-935e-e21fd9d2f8a6.png)

P.S. The error in my case is the absence of any action in the form

**Comment by nreljed** [comment]
I see that you are under Twenty Twenty-One I deleted hello theme to stay in the same test environment


![jetfom gif](https://user-images.githubusercontent.com/82481592/160197938-dee01f46-5d04-4e31-b2be-6dc49a5d57a6.gif)

all the contents of __logger 

```
__logger: {,…}
Jet_Form_Builder\Exceptions\Action_Exception: [{message: "failed", file: "plugins\jetformbuilder\includes\actions\types\redirect-to-page.php",…}]
0: {message: "failed", file: "plugins\jetformbuilder\includes\actions\types\redirect-to-page.php",…}
data: [{redirect_type: "static_page"}, {insert_post: {,…}}]
0: {redirect_type: "static_page"}
redirect_type: "static_page"
1: {insert_post: {,…}}
insert_post: {,…}
post-id-75: {__action: "insert", ID: 75, post_type: "post", meta_input: [], post_title: "Lorem ipsum",…}
ID: 75
meta_input: []
post_content: "content"
post_status: "publish"
post_title: "Lorem ipsum"
post_type: "post"
__action: "insert"
file: "plugins\\jetformbuilder\\includes\\actions\\types\\redirect-to-page.php"
line: 103
message: "failed"
version: "1.5.5"
```
