### ISSUE TITLE
jet woobuilder title count

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5088]
In the product grid widget, I consider the title length on the desktop to be 15 words. In this case, the title is displayed in two lines. https://prnt.sc/8WMPV3uEz0s5
But if you see the mobile mode, the title is written in 3 lines or even 4 lines. (15 words have been inherited from the desktop) This is a big problem that I am facing ...
Can you add a responsive option to this section? To be able to consider the length of product titles for desktop, tablet and mobile separately.
Or, for example, a method that we can determine, the length of the title should not exceed two lines or one lines.

**Comment by alican532** [comment]
"Or, for example, a method that we can determine, the length of the title should not exceed two lines or one lines."
It would be great.

**Comment by 79ho3ein** [comment]
#4948

**Comment by UraraReika** [comment]
I merged this issue with [#4948](https://github.com/Crocoblock/suggestions/issues/4948), which is on the same subject so we could deal with it more efficiently.
