### ISSUE TITLE
Add WebP support to Media Control in JetEngine Interface Builder

### ISSUE THREAD

**Issue by deepwaterpixel** [CrocoBlock/suggestions#5092]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work; **No**
- if the feature is missing from the products. **Yes**

**Please, describe the feature request, making it clear to understand.**

WebP image previews in JetEngine's image and gallery fields currently show a blank because of a case statement miss and no default handling.  This is easily fixed by adding the WebP mime type to the case statement found at `jetengine/framework/interface-builder/inc/controls/media.php:143`

**Before:**
```
switch ( $mime_type ) {
    case 'image/jpeg':
    case 'image/png':
    case 'image/gif':
    ...
```
![webp-broken-preview](https://user-images.githubusercontent.com/54284392/160329469-30ae8bed-db1c-483b-b31f-ca328580ed80.png)

**After:**
```
switch ( $mime_type ) {
    case 'image/webp': //This adds WebP support to the preview boxes
    case 'image/jpeg':
    case 'image/png':
    case 'image/gif':
    ...
```
![webp-fixed-preview](https://user-images.githubusercontent.com/54284392/160329434-cc933a0c-754c-45bc-a2c4-230c97eb00fb.png)

**Add an example of where this feature is already implemented.** 

See above for working example.  I have made this change to all my JetEngine installs, because my clients have been complaining about optimized images being impossible to manage without previews.  I agree.

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**This is a simple one-line change that affects every site trying to use optimized WebP images instead of larger PNG or JPG images.**

**Comment by kaskad88** [comment]
I merged this issue with [#5273](https://github.com/CrocoBlock/suggestions/issues/5273), which is on the same subject so we could deal with it more efficiently.
