### ISSUE TITLE
Prevent double click on Data Store Button

### ISSUE THREAD

**Issue by GerardoZenteno** [CrocoBlock/suggestions#5096]
Double clicking on a Jet Engine Data Store Button can increase the number of likes infinitely. This happens on both desktop and mobile devices. I have also noticed that several users have taken advantage of this bug to increase the likes of some posts and I really like to know how to fix it.

Note: I have set all my Data Stores as "Store Type = User Metadata".

https://user-images.githubusercontent.com/21294695/160437260-d68ad1da-1eac-44c4-b25d-01eb56d8ff96.mp4

![sc1](https://user-images.githubusercontent.com/21294695/160437312-6090a046-09af-4da4-a30a-9b5d010b0fdc.jpg)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
