### ISSUE TITLE
JetSearch - Search with CPT metadata

### ISSUE THREAD

**Issue by Topicimes** [CrocoBlock/suggestions#5097]
Hello,

It would be great if JetSearch could display results related to some meta data that come from post type: CPT.

Indeed, currently the search by meta data is not possible, but it uses the title of CPT.

For example, in my case this is a problem.

I explain: I have a title of any activity, for example: "Discovering the fauna of the Vanoise". This CPT is linked to a taxonomy: "Hiking".

Someone who searches for "hiking", in JetSearch, will not see in the search results (before clicking on search), the CPTs linked to the taxonomy "hiking".

So it would be great to add this feature.

Many thanks!

Take care of yourself and your loved ones

**Comment by mehdimoradi1500** [comment]
+1

**Comment by Floydtm** [comment]
Please study this [tutorial](https://crocoblock.com/knowledge-base/articles/jetsearch-how-to-set-a-field-key-to-search-in-custom-fields/)

**Comment by Topicimes** [comment]
Hello,

This does not answer my problem, unless I am mistaken.

Indeed, it allows to retrieve a meta data of the CPT, but I want to retrieve a meta data of a taxonomy which is linked to the CPT.

Thanks for your feedback
