### ISSUE TITLE
[JetEngine] How to display child posts related to another child using listing grid?

### ISSUE THREAD

**Issue by SpaRexDz** [CrocoBlock/suggestions#5098]
Hello, guys.

I'm trying to display child posts related to another child. I've tried everything I could but nothing.
I'm using a "many to many" relation. To make my question clear, I'm not trying to show child posts on the parent post, but child on child.

I appreciate any help.

**Comment by Floydtm** [comment]
Contact our support team, the guys will help you solve this problem.
