### ISSUE TITLE
bug in visual filter (select color), Jet smart filters plugin.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5099]
**Please, describe the feature request, making it clear to understand.**

When we select a color for the color filter, after opening the color panel, it is moved to the bottom row (does not remain in the third column) Please watch the video below :

https://user-images.githubusercontent.com/77163248/160511244-97142e6e-507e-4297-96ea-fce87b6ba091.mp4

In general, when choosing a name and color code, the UI is severely damaged : https://prnt.sc/yAAuzypTd5UY

**This bug does not cause a problem in the plugin process, but it is a bug anyway!**

thanks

**Comment by Floydtm** [comment]
Hello, what device are you getting the bug on?

**Comment by 79ho3ein** [comment]
hi, Also, if we [reduce the browser width](https://prnt.sc/MwMKEfckm9c2) a bit, it breaks 3 rows and the colors are displayed in [two rows](https://prnt.sc/cvbqrCHDCO-j).

**necessary information**

wordpress : 5.9.2
elementor : 3.6.1
e pro : 3.6.4
hello elementor : 2.5.0
jet smart filters : 2.3.11

windows - browser : chrome, Version 99.0.4844.84 (Official Build) (64-bit)

Do you need more information?

**Comment by Floydtm** [comment]
"if we [reduce the browser width](https://prnt.sc/MwMKEfckm9c2) a bit" Don't do it again) At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.

**Comment by 79ho3ein** [comment]
But this request was not a new feature! It was a bug report.
