### ISSUE TITLE
A suggestion for the color selection section of the filter - jet smart filters.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5100]
**Before adding a new feature request, please, make sure you’ve checked:**

when we want to add a color to the visual filter> color, all the colors in WooCommerce are displayed in [this section](https://prnt.sc/hcQXOUOHSCBt).
But if the number of colors of products is high, we will definitely get into trouble. We may never import many colors, or we may import duplicate colors.
The reason for this problem is that when selecting a color from [this section](https://prnt.sc/hcQXOUOHSCBt), all WooCommerce colors are displayed. **Even the colors we already added for the filters.**

To solve this problem, I have a suggestion, I hope you agree with it ...

It is better if we select any color from [this section](https://prnt.sc/hcQXOUOHSCBt), it will be automatically removed from the list to determine what colors we have not yet introduced for the filter.
Under these circumstances, if we introduce all the colors in the filters, there will be no colors in [this list](https://prnt.sc/hcQXOUOHSCBt).
If we [remove a color](https://prnt.sc/PARZTLOiTREQ) from the list of filters, it will return to the list of colors.

In general, by adding this useful feature, we will easily control the colors in WooCommerce, and as a result, we will never have trouble adding colors in the visual filter.

thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
