### ISSUE TITLE
PRODUCT STATUS - new filter for jet smart filters.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5102]
One of the most widely used filters on any website is the PRODUCT STATUS filter. This feature is even available in woodmart theme.
https://prnt.sc/A1kUZ_hmxJ6Y

Of course, for this type of filter, it is better to use the filter switcher widget. Unfortunately, there are no switcher filter in jet smart filters right now. I hope it will be added to the plugin.

**Comment by Floydtm** [comment]
https://prnt.sc/JNcbjTeVIwfB https://prnt.sc/DwWIVyVG4AK6 https://prnt.sc/f7sZP4kR-2eU https://prnt.sc/FhjpzygNt71z
