### ISSUE TITLE
Jet Booking Manual Booking function on the back end of the site

### ISSUE THREAD

**Issue by aaronfevah69** [CrocoBlock/suggestions#5103]
**Jet Booking Manual Booking function on the back end of the site**

where the admin can manually add a booking for either telephone bookings, email bookings, walk in bookings and others

there is no function for this according to your helpdesk staff

without this function the website cannot be your master booking engine, most clients like to have one central up to date source for bookings, the website is the best place for this in my experience

there is an option when you create a orders CPT, to add, but nothing happens

please look at this function as for me this now renders jet bookings usless to 90% of my clients

I will need to look at adding a 3rd party plugin something i dont like to do

**Comment by Lonsdale201** [comment]
+1

**Comment by erubianes1** [comment]
I agree! This is one of the most important needs for JetBooking. It could be good something like in JetAppointment.

Very urgent!!!

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was added in 2.5.0 release.
