### ISSUE TITLE
Ability to display sale price in the cart page - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5106]
**Please, describe the feature request, making it clear to understand.**

hi

Please add this feature if possible so that the products that are on special sale have their [previous prices displayed in the cart](https://prnt.sc/hdGGzClvNUa9). There is a reason to add this feature ...
If we create a discount code and enable [this option](https://prnt.sc/qKnAKRmg4lfX), if the user has a special sale product in their shopping cart and enter the discount code, they will encounter [this message](https://prnt.sc/ZN5HgUv1RxkD).
In this case, the user does not know which of the products in his shopping cart have a sale price. So they have to go back to their product page to find out which product is blocking the code and actually has a sale price.

But if you add this feature, the user can see the products that are on special sale on the cart page. Because the previous prices of special sale products are displayed.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

This is specific functionality that is why we will not implement this in our plugin. Because the price already show you what you got to pay with all taxes if it included.

But if you need this functionality this much then you can use this snippet:
```
add_filter( 'woocommerce_cart_item_price', '__your_theme_prefix_change_cart_table_price_display', 30, 3 );

function __your_theme_prefix_change_cart_table_price_display( $price, $values, $cart_item_key ) {

	$slashed_price = $values['data']->get_price_html();
	$is_on_sale    = $values['data']->is_on_sale();

	if ( $is_on_sale ) {
		$price = $slashed_price;
	}

	return $price;

}
```

**Comment by 79ho3ein** [comment]
thank you
