### ISSUE TITLE
Allow JetCompareWishlist to work with any post rather than just products

### ISSUE THREAD

**Issue by liammaurer** [CrocoBlock/suggestions#5110]
Essentially the title. Thought the plugin would work with any post for a directory site I am using other Crocoblock products on the site but wanted to implement some kind of wishlist and compare features for posts but was unable to do so because the plugin only works with WooCommerce products.

**Comment by UraraReika** [comment]
Hello @liammaurer !

You can use Data Store module in JetEngine plugin. Learn more about it [here](https://crocoblock.com/knowledge-base/articles/jetengine-data-stores-module-overview/). Unfortunately Data Store doesn't give you opportunities to create compare list but it gives you more flexibility in CPT and favourites lists.

As for JetCompareWishlist we will not implement such functionality to our plugin it will works only with products.
