### ISSUE TITLE
Jet engine Profile builder post limits by status 

### ISSUE THREAD

**Issue by morosmo** [CrocoBlock/suggestions#5113]
Hi,
I am just testing crocoblock jet engine post restriction rules.
I see that we can restrict post by post types and roles. The problem is post can only be restrict by publish status.
If user has created one post then they can also be able to create one more and so onn because if we save post from frontend forms and make deafult status od submitted post to pending review then user is able to submit psot again and again un til one of the post is not published.
Please add post status features is resteriction roles so we can restrict post by status also or any status. 
Thanks

**Comment by Topicimes** [comment]
+1

But I found a solution. You just have to use the plugin : https://wordpress.org/plugins/user-posts-limit/

This way, you can easily configure restrictions regardless of the publication status of the post.

I can also sell you lines of code that allow you to automatically change the role of the user depending on a subscription, etc.

**Comment by morosmo** [comment]
Thanks For the help.
I have tested that plugin and dosent feed my needs. Also sorry for that as I already have alot spent.
