### ISSUE TITLE
[Jetsmartfilters] N Selected

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5114]
It was while trying to imitate a `select with search ` that I decided to use the checkbox or radio filters.

These two have the advantage of offering a lot of customizations that cover a wide range of possibilities 🎊
But when you try to imitate the Select type there are 3 omissions

everything is there or almost we will see the 3 final details that are missing. don't worry, I was very careful to document myself well and give all the details to set them up easily so there shouldn't be any problem add them

![N selected hover](https://user-images.githubusercontent.com/82481592/160840168-c2162d8d-3033-4646-b84d-0eb85af48786.gif)

Select + hover : this possibility is absent

- Solution : style > item add hover in the middle [Normal]**[Hover]**[Checked]

_my temporary fix_
```
.jet-radio-list__row:hover {
  background-color: #EDEDED;
  transition: 0.7s;
}

```
item width : if I put border I discover that I have no option to put width at 100% (useful for separations)

- Solution :  style > item width

_my temporary fix_

```
.jet-radio-list .jet-radio-list__item .jet-radio-list__button {
    width: 100%;
}
.jet-radio-list .jet-radio-list__item {
    width: 100%;
}
```
- Introduce N selected
the main reason for their existence is to avoid destroying our super pixel-precise design that is important to us
let's take a real example

now you have your super select + search and you have for example opted for (checkbox filter) multiple choices the customer wants to make several choices..

![Capture d’écran 2022-03-30 100451](https://user-images.githubusercontent.com/82481592/160845093-ca71bbd7-c973-4a1a-9fbd-cadde6f971c8.png)

_oops !now your nice design is broken this is not what you expected from a select..😅_

what you expected is this

![Capture d’écran 2022-03-30 100119](https://user-images.githubusercontent.com/82481592/160845557-23ee51a5-7a25-4f61-87d6-b2130cc2e137.png)

How to add N selected?

N select should probably activate by choosing the dropdown option it should probably look like this

![Advanced select new](https://user-images.githubusercontent.com/82481592/160846708-ad4a3d72-7714-4042-bafd-46618d4e4fb9.png)

**Variation 1**

Display generic message: n items selected

![1pcCb](https://user-images.githubusercontent.com/82481592/160847254-ecaa879b-9b70-427f-b0b1-aad6216fb18c.gif)

```
const ValueContainer = ({ children, ...props }) => {
  let [values, input] = children;

  if (Array.isArray(values)) {
    const plural = values.length === 1 ? "" : "s";
    values = `${values.length} item${plural} selected`;
  }

  return (
    <components.ValueContainer {...props}>
      {values}
      {input}
    </components.ValueContainer>
  );
};
```

**Variation 2**

Display a number of named items before showing the generic message: item1, item2, item3 and n others selected

![LfsJz](https://user-images.githubusercontent.com/82481592/160847294-f35c72c1-ad8b-4438-a870-e237aa09580d.gif)

```
const ValueContainer = ({ children, ...props }) => {
  let [values, input] = children;

  if (Array.isArray(values)) {
    const val = (i: number) => values[i].props.children;
    const { length } = values;

    switch (length) {
      case 1:
        values = `${val(0)} selected`;
        break;
      case 2:
        values = `${val(0)} and ${val(1)} selected`;
        break;
      case 3:
        values = `${val(0)}, ${val(1)} and ${val(2)} selected`;
        break;
      default:
        const plural = values.length === 3 + 1 ? "" : "s";
        const otherCount = length - 3;
        values = `${val(0)}, ${val(1)}, ${val(
          2
        )} and ${otherCount} other${plural} selected`;
        break;
    }
  }
  return (
    <components.ValueContainer {...props}>
      {values}
      {input}
    </components.ValueContainer>
  );
};
```
**Usage**
```
<Select
  {...}
  isMulti
  hideSelectedOptions={false}
  components={{ ValueContainer }}
/>
```

[more documentation and examples here](https://stackoverflow.com/questions/48323716/how-to-render-n-items-selected-rather-than-the-list-of-n-selected-items-with-r)

**Comment by rtpHarry** [comment]
This would be a really good feature.

I had a look at the source code for this plugin, and I can see that the uncompiled source code is included in `_dev` for reference, which is handy for understanding how it works.

However it looks like its all wrapped up inside web-pack so I don't know of any way to access the `fiter/change` event bus event to try to inject anything like the above code into it. 

(BTW the 'filter' / 'fiter' typo is in the source code, not my mistake)

Perhaps it could be done without hooking into the internals using a MutationObserver but I've run out of time that I can invest in this for the moment. Hopefully it will be something that comes along in the future.

**Comment by morosmo** [comment]
+1

**Comment by nreljed** [comment]
@rtpHarry @morosmo 
can you create posts and tag this one?
because it was not taken into account 
the main thing give the post visibility
to the concerned people 
@MjHead 
@SargasTM 

N Selected is an essential component

**Comment by morosmo** [comment]
@nreljed 
Yes, I can do that but @girafffee is already here. they will assign the functionaility request to @MjHead or to main developers of plugin. Lets see when they implement it becuase its much needed thing. Thanks

**Comment by MjHead** [comment]
Added to backlog for 3.2.0 version

**Comment by Michaelgimii** [comment]
Hi friends.

How do you customize the selection field in the jet smart filters plugin?

![download](https://user-images.githubusercontent.com/88034902/219002249-f7a1abbc-ae53-4d86-add7-5ee059b3e764.png)

What I see is very old :

![download (1)](https://user-images.githubusercontent.com/88034902/219002611-690ae1fb-8cc7-4c87-801a-6b15fdd94bad.png)

**Comment by SargasTM** [comment]
в ветке 3.2.0
