### ISSUE TITLE
jet woobuilder add to cart button notice

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5115]
There are 3 types of WooCommerce notice in the Add to Cart button. 1- Out of stock   2- Only 1 left in stock or in stock   3- Available on backorder.

We can only customize Out of stock and in stock notice colors. :  https://prnt.sc/XlTxmuFvB06E      So we can not customize the Available on backorder notice color. Please add this feature.

It would be great if you could add text editing to these 3 items. Using this feature we can customize the text of these 3 items and this is really great. This is especially useful for multilingual websites. I hope you agree with these 2 requests

There are also two bugs in the Add to Cart button 1- In the elementor editor, we can not see the disabled button of the shopping cart live. So we have to see the result on the website after each change and this is very time consuming.
2- Also, we can not edit the mentioned 3 notice (in stock - Out of stock - Available on backorder ) live in the editor.

**Comment by mehdimoradi1500** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
> We can only customize Out of stock and in stock notice colors. : https://prnt.sc/XlTxmuFvB06E So we can not customize the Available on backorder notice color. Please add this feature.

Done

> It would be great if you could add text editing to these 3 items. Using this feature we can customize the text of these 3 items and this is really great. This is especially useful for multilingual websites. I hope you agree with these 2 requests

This type of controls is complex and unnecessary for this purpose WooCommerce provide filter hooks witch you can use to change those labels. 

> 1- In the elementor editor, we can not see the disabled button of the shopping cart live. So we have to see the result on the website after each change and this is very time consuming.

Unfortunately this isn't possible to display both buttons at ones or while select disabled tab. In this case you can just use preview mode https://tppr.me/iLDmC.

> 2- Also, we can not edit the mentioned 3 notice (in stock - Out of stock - Available on backorder ) live in the editor.

You can select appropriate product in [admin area](https://tppr.me/6j1ST)  then in the editor you will be able to see stock status of this [product](https://tppr.me/DjT2x) .
