### ISSUE TITLE
content , style and advanced tab in jet woobuilder Template

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5116]
I want the background color on single product page to be different from other sections of the website. But there is a big hurdle for jet woobuilder here. In jet woobuilder, we do not have three items: content, style and advanced. Whether on a single product page, in a shopping cart or even a checkout page : https://prnt.sc/t4X5-9DzJ2-g      Please add this section.

**Comment by mehdimoradi1500** [comment]
+1
