### ISSUE TITLE
copy to clibord widget for jet engine plugin.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5117]
I did not find any plugin to add such a widget to elementor.Great if you add this widget to jet elements.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
Right now you can find the solution [here](https://wordpress.org/plugins/search/clipboard/)
