### ISSUE TITLE
Jet SmartFilters: Conpatibility wit Blocksy Archive postgrid/cards

### ISSUE THREAD

**Issue by torsten3d** [CrocoBlock/suggestions#5119]
Would be cool, if the Smartfilter could be applied to the native Blocksy Grid you can create for Archives there. So you don't have to build the cards with JetEngine from scratch...

Best,
Torsten

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
