### ISSUE TITLE
Open WooCommerce Quick View Popup on image click instead of separate button

### ISSUE THREAD

**Issue by sn10** [Crocoblock/suggestions#512]
Currently, for JetWooBuilder Products Grid, the default is having a quick view button on hovering over a product and click that button to get a quick view and on clicking the image, it opens another page with the product details. An option to change this would be nice. Essentially, you should be able to select if Quick View should open when you click on a separate Quick View Button or when it should open by default when you click on the image, without leading to a new page.  

UA Elementor already does this. https://uaelementor.com/docs/how-to-enable-quick-view-for-woocommerce-products/

![image](https://user-images.githubusercontent.com/50699632/64472601-804b1700-d17e-11e9-9c8d-73756d9afdac.png)

The Button Click option gives you a Quick View Button on hover whereas the Image Click option lets you click on the product image directly to open the Quick View modal.

**Comment by UraraReika** [comment]
Hi @sn10! That button made for better understanding, that your product card has ability to open quick view. In addition you cat make open quick view what ever you want using option Trigger Type as Click On Custom Selector and in Custom Selector field write custom selector class, for example .jet-woo-product-thumbnail and them your thumbnail will open the quick view https://prnt.sc/q4wkme.
