### ISSUE TITLE
JetAppointment - Multiple instances setup

### ISSUE THREAD

**Issue by breakerh** [CrocoBlock/suggestions#5122]
Make it possible to initialise multiple jet appointments on a single page.

For example we have a page which has 2 choices. Both choices use a jet form builder instance which loads a Jet Appointment calendar.
Without altering your `appointments-init.js`  this isn't possible since it checks if calendar is not null.

If you work with custom (generated) classes or ID's this could be resolved.

For now we altered the code to use the `$scope` argument which is included in the `bookingFormIinit` event adding a custom class to each calendar.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by breakerh** [comment]
@Floydtm Honest and fair response. It's a small edit I have to make to make it work so not an issue at all :) 

For those who also have this issue.
Change the content op `bookingFormIinit` in `appointments-init.js` to:
```js
			if( args.find('.appointment-calendar').length>0&&args.find('.appointment-calendar').hasClass('calendarInitialised') ){
				return;
			}
			const tmpClass = 'calendar_'+Math.floor(Math.random() * 100);
			args.find('.appointment-calendar').addClass(tmpClass);
			args.find('.appointment-calendar').addClass('calendarInitialised');

			settings.selector = '.'+tmpClass;
			settings.namespace = e.data.namespace;
			calendar = new VanillaCalendar( settings );

			if( settings.namespace === "jet-form-builder" ){
				JetFormBuilderMain.filters.addFilter( 'forms/calculated-field-value', calcFiledValue );
			} else {
				JetEngine.filters.addFilter( 'forms/calculated-field-value', calcFiledValue );
			}
```


ps. if not allowed, sorry and please let me know or remove the comment.
