### ISSUE TITLE
JetSmart Filters conflicting with Elementor v 3.6.1

### ISSUE THREAD

**Issue by Vickystha** [CrocoBlock/suggestions#5125]
Hi,

I recently updated Elementor from v. 3.5.4 to the latest one v. 3.6.1. After the update, one of the web page that uses JetSmart Filters is broken. It looks like these plugins are conflicting with one another. Here is the error message:

`Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found in ~/wp-content/plugins/jet-smart-filters/includes/widgets/base.php:316 Stack trace: #0 ~/wp-content/plugins/jet-smart-filters/includes/widgets/base.php(200): Elementor\Jet_Smart_Filters_Base_Widget->base_controls_section_filter_apply_button(Array) #1 ~/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Jet_Smart_Filters_Base_Widget->_register_controls() #2 ~/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls() #3 ~/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack() #4 ~/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base-> in ~/wp-content/plugins/jet-smart-filters/includes/widgets/base.php on line 316`

Has anyone come across similar issue? 

Thanks
Bijaya

**Comment by 79ho3ein** [comment]
hi
No problem for me, of course I disabled the flex box and use elementor pro 3.5.4.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by Vickystha** [comment]
@Floydtm Can you tell me which versions (both Elementor and JetSmart Filters) did you check? Please note the issue happens when updated to Elementor 3.6.1. The issue does not occur in Elementor 3.5.4.

Looks like JetSmart Filters is still using deprecated Class 'Elementor\Scheme_Typography'. So, using the correct class in JetSmart Filters would likely resolve the issue.

**Comment by Floydtm** [comment]
Elementor 3.6.1
JetSmart Filters 2.3.11

**Comment by Vickystha** [comment]
Alright so looks like our website is using older version of JetSmart Filters v. 1.8.3. We need to purchase one for the latest version. I hope upgrading it will fix the issue?
