### ISSUE TITLE
A simple bug in jet woobuilder 1.12.2

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5126]
**Describe the bug**

(I use RTL)

In the product grid widget, the amount of Space Between Slides Does not follow the inheritance feature. As you know, the default value of Space Between Slides is 10 pixels. I put it on tablet 0 to make [this control](https://prnt.sc/IKoELZ-_cStb) work properly.
When I consider Space Between Slides on a 0px tablet, it should naturally be 0px on a mobile phone as well (due to the inheritance feature in elementor) But this inheritance is only observed in the elementor editor. **If I view the site with mobile, the value of Space Between Slides is still equal to 10px.** While it should be 0. Because I set the value of Space Between Slides to 0px on the tablet.

The only solution is to consider the value of Space Between Slides in addition to the tablet, 0 pixels in mobile, the problem is solved.

**After viewing the website with mobile, Space Between Slides is equal to 0. But when the full website is loaded, it changes to 10 pixels. In fact, I think this bug is similar to the rendering problem in the overflow feature.**

**To Reproduce**

First give the Border product item to better detect the bug,

1- Add the product grid widget and enable the carousel.
2- Enter tablet mode and set Space Between Slides to 0.
3- Then enter mobile mode and [delete](https://prnt.sc/xXFOoGTr78s1) the amount of Space Between Slides completely to be inherited from the tablet. **Also in mobile, put the product item in 2 columns.**

Now if you view the website with mobile, there is no space between the product items at first, but when the page fully loaded, the distance between the product items will be 10 pixels. (I experience this bug in Android> Chrome.)

**In addition to this, I experience one new bugs in the elementor editor that did not exist in previous versions of 1.12.2.**

thank you

**Comment by 79ho3ein** [comment]
Another bug in this version is related to overflow. In the overflow, if we decrease or increase the value using [these two buttons](https://prnt.sc/NBdgHhGrEeaJ), no change will be applied unless we enter the number manually.

Another thing about overflows is that overflows, like Space Between Slides, do not support hereditary value. I do not know, maybe there is a reason for it, anyway hereditary trait is really necessary. Because in this case, we have to enter the value separately on the mobile tablet and desktop, and this is very time consuming.

**In fact, all these bugs exist only in the backend.**

thank you

**Comment by UraraReika** [comment]
Control option that we use in this case need to get proper parameters in the frontend so then we can handle this parameters in our script. This option doesn't get data from Elementor inheritance. You need to put value manually. The same thing with overflow control.

> Another bug in this version is related to overflow. In the overflow, if we decrease or increase the value using [these two buttons](https://prnt.sc/NBdgHhGrEeaJ), no change will be applied unless we enter the number manually.

Done

**Comment by 79ho3ein** [comment]
thank you
I forgot to mention the other two...

1-There seems to be a small bug in these [two parts](https://prnt.sc/ee_AGsDreG6z). Please watch the video below :

https://user-images.githubusercontent.com/77163248/163188639-66ea4046-2443-4597-9032-1619d02af4dc.mp4

As you can see in the video above, after renaming the shopping cart update button to (bug), I enabled the automatic update and then reloaded the editor. After loading the editor completely, I disabled the automatic shopping cart update. After that, the text of the auto-update button displayed the default text.

2- As you know, in version 1.12.2, the [rendering problem](https://prnt.sc/n7b_rXKW2cVq) in the overflow was fixed and now, the overflow is applied immediately after loading the page.
A similar problem now exists in Carousel [pagination](https://prnt.sc/ma9K1K0QwLIY). After loading the page, pagination points appear with a significant delay. Especially if the number of carousels is large. Of course, I do not know if this can be solved for the problem at pagination points. Because it is completely different from an overflow. 
**(This is not about 1.12.2. I just did not want to open a new issue for it)**

thanks again

**Comment by UraraReika** [comment]
1 - done
2 - This is the issue of carousel library how the script loads and render.

**Comment by UraraReika** [comment]
release 1.12.3

**Comment by 79ho3ein** [comment]
thank you
