### ISSUE TITLE
JetElements POSTS widget filter

### ISSUE THREAD

**Issue by SirChopper** [Crocoblock/suggestions#513]
It would be great if there was a category FILTER for the JetElements POSTS widget. Just like what is used on the PORTFOLIO widget. https://crocoblock.com/widgets/portfolio/

The difference is, the POSTS widget dynamically pulls the content, but the PORTFOLIO widget is a manual process to add the items.

**Comment by Floydtm** [comment]
@SirChopper, Hi! The [jet-blog](https://crocoblock.com/widgets/smart-posts-listing/) plugin is more suitable for your case. It has the settings you need. http://prntscr.com/p46ddu

**Comment by SirChopper** [comment]
Hi Floyd, thanks for your suggestion. However, I can see that the jet-blog does not support Custom Post Types when I want to use 'Show Filter by Terms'. This option disappears when you select a CPT other than POSTS???? Any ideas....?

**Comment by Floydtm** [comment]
@SirChopper Thank you for your message. We will check this bug and release a plugin update.

**Comment by SirChopper** [comment]
Thanks. That would be most helpful.

**Comment by Floydtm** [comment]
@SirChopper in the plugin settings you need to add filter support for your post type http://prntscr.com/p48xx6 after that everything will work properly http://prntscr.com/p48yis

**Comment by SirChopper** [comment]
Ahhh. There you go. Perfect.
Would it be possible to add the CUSTOM size option for the Thumbnail for that a height can be set? Otherwise, if my original images are not the same dimension, the image is shown at a different size to the others. Choosing 'Thumbnail' displays a bad quality image, but consistent image size....
https://prnt.sc/p491ao

**Comment by Floydtm** [comment]
Featured Post Image Size - here you can select the suitable size for the featured post image (the sizes may vary depending on what theme you’re using). You can register your size for pictures in your themes

**Comment by SirChopper** [comment]
I changed the Thumbnail size in the Media settings, regenerated thumbnails, updated permalinks and the blog images are still bad quality.
https://wordpress-224129-900747.cloudwaysapps.com/test-jet-blog/

I am also using namogo-extras plugin, in which you can choose FULL for the image size but you can also set a height, and you then get a good quality thumbnail. Does that make sense...?
https://wordpress-224129-900747.cloudwaysapps.com/test-namogo-extras/
