### ISSUE TITLE
jet woobuilder carousel pagination.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5130]
hi

This is not a bug, but there is a problem anyway...

**Describe the bug**

As you know, in version 1.12.0, the possibility of [custom positioning carousel pagination](https://prnt.sc/yffXRClT6gX7) was added. If you remember, I said before that the problem with this feature is that it causes the navigation points to go out of the widget ...
**(In previous versions, it was only possible to apply the margin from above, which was great and made the navigation points never go out of the widget)**
In response, you said that we can use [this control](https://prnt.sc/0UPeS_ptA3mW) (so that the navigation points are with the widget and do not go out of it).
**It works, but it creates a problem.**

As you said, I used Padding. (To move carousel navigation points only inside the widget).
But this becomes a problem when there are no products in the carousel : https://prnt.sc/biMNODnZ3HvR + https://prnt.sc/a3bJFadRP-Jk
**This creates a large gap between the two widgets and severely damages the UI.**
But in the version before 1.12.0, where there was only one control for the distance of the navigation points, this problem did not exist.
Is it possible to add [margin control](https://prnt.sc/CJkQUx11CM1e) as before in addition to the [current controls](https://prnt.sc/yffXRClT6gX7)? In this case, we can use it more efficiently and there will be no bugs.

**I wanted to ask you, please keep the **[previous state](https://prnt.sc/CJkQUx11CM1e)** if possible. Only one margin control for navigation points.** please.

**Comment by 79ho3ein** [comment]
Another example of this problem ...
I have created a custom product message not found using [this feature](https://github.com/Crocoblock/suggestions/issues/4386). 
Therefore, [this gap](https://prnt.sc/6uLkpR8Kwv8y) is created when this product grid has no products to display. The only reason for this problem is that in the new version, we use [this control](https://prnt.sc/0UPeS_ptA3mW).

thank you

**Comment by UraraReika** [comment]
Use [column pudding control](https://tppr.me/72W0J) for creating extra space inside widget that will disappear with products grid and you will not have this issue.

**Comment by 79ho3ein** [comment]
This was a great solution. thanks alexander🌹

**Comment by 79ho3ein** [comment]
hi @UraraReika 
How did you add [custom text](https://prnt.sc/oFPFSkW-bya9) to the product grid widget? 
Did you use [this plugin](https://github.com/UraraReika/jet-woo-builder-products-grid-custom-fields)?

**Comment by UraraReika** [comment]
This is product short description.

**Comment by 79ho3ein** [comment]
oh, ok. thank you
