### ISSUE TITLE
2 simple bug in jet woobuilder > cart page > remove product from cart button.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5133]
**Describe the bug**

There are 2 bugs in the button to remove the product from the cart > Hover mode, please check if possible.

1- Button color in hover mode does not support elementor global colors : https://prnt.sc/KRhena0zv8h0

2- The background color of this button is red by default. So if we leave the background color by [default](https://prnt.sc/1LPjmaBzwqvE), after the hover the background color of this button will be red.
At the moment, the only solution is to set the background color of this button to [colorless](https://prnt.sc/SN5fP0bf1rRN).

thank you

**Comment by UraraReika** [comment]
1 - Fixed.
2 - In this case the WooCommerce plugin add this default styles to your button and you can override this with our style controls so i don't see the problem.

**Comment by 79ho3ein** [comment]
thank you

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
