### ISSUE TITLE
Fade mode (gradient) for the overflow attribute - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5134]
**Please, describe the feature request, making it clear to understand.**

It would be great if a gradient could be added to the overflow feature. Using this gradient, we can display the last product that is not fully displayed as a gradient. Of course, I do not know if this can be implemented in jet woo! But if it is added, it will be great.

Current status : https://prnt.sc/iAZmJz6om6J2
the gradient feature : https://prnt.sc/kryG324-8GYa

**In fact, the gradient coating only affects the last product, which is half.**

thank you

**Comment by 79ho3ein** [comment]
Hi again @UraraReika 

As an example, This method is also used in crocoblock changelog :

![fade](https://user-images.githubusercontent.com/77163248/211155183-c67d1f81-a008-4efe-bd0b-8ae172b1b411.png)

If you are adding this feature, it would be great if we could choose whether the fade should be left carousel, right carousel, or both.

**Comment by morosmo** [comment]
+1, Nice little tweak :)

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
