### ISSUE TITLE
JetMenu disappears at search result page.

### ISSUE THREAD

**Issue by incheon-kim** [CrocoBlock/suggestions#5136]
**Describe the bug**
Mega menu with JetMenu disappears whenever search something. Sepearte Mobile hamburger menu doesn't but only JetMenu.

**To Reproduce**
1. search anything. (/?s=keyword)
2. JetMenu disappears. Only wrapper div remains.

**Expected behavior**
1. Present normal heading nav menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/26535870/161541832-754bc7df-dec8-4258-a12e-8ae97fd2eb22.png)

This is what expected
![image](https://user-images.githubusercontent.com/26535870/161541885-5a664f2f-36fc-4467-9f67-bbfb74de3e8d.png)

**Desktop (please complete the following information):**
 - OS: Windows or Mac. Doesn't matter
 - Browser: Chrome, Edge or Safari. Doesn't matter which browser using
 - Version: 

**Smartphone (please complete the following information):**
 - Device: Android or iOS.
 - OS: iOS 14/15, Android 11/12
 - Browser: Safari, Samsung Browser, Chrome (Android)
 - Version:

**Additional context**
I am using Elementor Pro.

**Comment by Crocoblock** [comment]
hi @incheon-kim 

We've tried to reproduce your issue and everything works fine on our side. 
If you have this problem, please create [a ticket](https://crocoblock.com/help-center) including access details for your site where the issue occurred to make sure we can help you.
