### ISSUE TITLE
Jet Woo builder - My Account

### ISSUE THREAD

**Issue by rodolphebertozzo** [CrocoBlock/suggestions#5138]
it is possible with this wonderful plugin to customize the endpoints for each part of the account, except the "forgotten password" part, which poses a problem since there is no possibility to modify the style of the element, it would be necessary to create a widget and an endpoint

**Comment by UraraReika** [comment]
I merged this issue with [#2721](https://github.com/Crocoblock/suggestions/issues/2721), which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
