### ISSUE TITLE
 JetEngine Meta-Fields of type "switcher" to be filtered with SmartFilters

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#5143]
Unfortunately, I can't get it to work or I suspect that it is currently not possible to filter the JetEngine Meta-Field "Switcher" with Smart Filters. 

As a workaround I tried to use Radio instead of Switcher and to set "Yes" and "No" as selection options. However, this does not work quite satisfactorily as a radio filter, because at another point the type Switcher would make sense. At another place (Product Page --> Datasheet) I output the switcher as a Dynamic Field with a callback function (True= Icon1, False= Icon2). With the Radio-Field no callback output is possible.

I hope you understand the problem

**Comment by Floydtm** [comment]
Try setting it up like this. Add a meta field to the post https://prnt.sc/Ldm5YUV1II63 Then create a filter https://prnt.sc/7Zod45_azcpZ https://prnt.sc/HdEpKpLi14my https://prnt.sc/3mrPN5F5Yolk Let me know if this helped you.

**Comment by hb81010** [comment]
It works great! Thank you very much for the quick solution!
