### ISSUE TITLE
JetCompare & Wishlist - Compare Widget - More output customizations

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#5144]
Compared to the JetEngine Dynamic Field widget, the Compare Widget unfortunately has limited options when it comes to output customization.

Here are a few examples:

### **Example 1**
When a meta field of type "**Number**" is output, unfortunately you don't have a field where you can enter a suffix or prefix.
Unfortunately, you can only set a fallback in the Compare widget

![grafik](https://user-images.githubusercontent.com/54399588/161767113-a93843b7-b5f9-4629-8e00-6897961c82b4.png)

### **Example 2**
If a meta field of the type "**Switcher**" is output, it works, but only true/false is output. There is no possibility to output a callback function for the switcher like it is possible with the dynamic field.
![grafik](https://user-images.githubusercontent.com/54399588/161766775-6ec50622-fa8f-4c08-9d4e-4b418fd2e6f9.png)

### **Example 3**
If a meta field of the type "**Checkbox**" is output, only "array" appears as output. Here it would also be great to be able to use the callback output for the checkbox, similar to the Dynamic-Field.
![grafik](https://user-images.githubusercontent.com/54399588/161767848-d628720d-e06c-4280-b622-2db6d9b891fc.png)

It would be cool if the already existing functions (Suffix, Filter field output) could also be found in the Compare widget.

![grafik](https://user-images.githubusercontent.com/54399588/161768701-db19fdf3-0faa-4f5c-a8e7-b1fb6cde230a.png)

**Comment by UraraReika** [comment]
Example 1 - Done.
Example 2:
```
add_filter( 'jet-cw/template-functions/compare-custom-field/switcher-field', function( $value ) {

	$value = filter_var( $value, FILTER_VALIDATE_BOOLEAN );

	if ( $value ) {
		return esc_html( 'True label' );
	} else {
		return esc_html( 'False label' );
	}

} );
```

For custom value output we provide filter hook `'jet-cw/template-functions/compare-custom-field/' . $field_key`. When you call this hook you need to replace `$field_key` with actual key like this `'jet-cw/template-functions/compare-custom-field/switcher-field'` `switcher-field` the key of switcher field. Take a note that this filter hook takes 1 parameter - value of the field witch we handle in the hook function.

Example 3:
```
add_filter( 'jet-cw/template-functions/compare-custom-field/checkbox-field', function ( $value ) {

	if ( empty( $value ) ) {
		return '';
	}

	if ( is_object( $value ) ) {
		$value = get_object_vars( $value );
	}

	if ( ! $value || ! is_array( $value ) ) {
		return $value;
	}

	$result = [];

	if ( in_array( 'true', $value ) || in_array( 'false', $value ) ) {
		foreach ( $value as $key => $val ) {
			if ( 'true' === $val ) {
				$result[] = $key;
			}
		}
	} else {
		$result = $value;
	}

	return wp_kses_post( implode( ', ', $result ) );

} );
```

**Comment by hb81010** [comment]
Thank you, it works too great! That helps me a lot.

I still have one question about Example2:

Is it possible to output e.g. icons with the function "esc_html"? I tried it with FontAwesome icons (Unicode & HTML) instead of the label text, but then only the text is displayed. FontAwesome is also loaded on the page.
Similar to Dynamic Fields, I would like to use an icon for each of the True and False values if that were possible.

**Comment by UraraReika** [comment]
You can return simple string with markup without `esc_html` function.

**Comment by hb81010** [comment]
Thank you, I was thinking too complicated.
Works perfectly
