### ISSUE TITLE
Attach the Media files to Post-Submit Emails instead of sending them as Link [in JetFormBuilder]

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#5146]
Currently, when a JetFormBuilder Form has a Media field, and you also have an Email Post-Submit Action, you can use Macros to insert the URL of the uploaded Media into the text of the email.

This might be better the nothing, but the issue is, that Microsoft Exchange considers emails with only links as spam.

We used our own company's email as the sender, and the email server is a dedicated mail server with a good reputation also the receiver had the sender verified as they were also from the company, but still ended up receiving the email in the Spam. But removing the links from the email body would lead the email to the inbox.

Please consider attaching the uploaded files to the email and send them as Attachment (or at least add an option to let us do it)

Thanks

**Comment by girafffee** [comment]
Added this feature in version 2.1.0
