### ISSUE TITLE
Custom endpoint for jet woobuilder my account page.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5147]
The custom endpoint is an extremely important and useful feature that unfortunately we do not currently have in jet woobuilder. Now on my account page, we are limited to a few tabs like dashboard, orders, URLs, etc. and we can not add a custom tab to the above.
For example, I want to add two new tabs. 1- wishlist 2- Sending a ticket Or any other tab. Please add this feature. It will be very, very great.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
