### ISSUE TITLE
CPT Admin Columns and Filters

### ISSUE THREAD

**Issue by ALPSIT** [CrocoBlock/suggestions#5150]
Hi There,

I have added some Admin Columns and Filters to a CPT, but I have two issues:

1. In Admin Column, the Taxonomy Hierarchy is not showing in Parent > Child order
 - It needs to Show in correct Parent > Child order
- eg. Mercedes (parent), C63S AMG (child).
- At the moment it seems to be sorting by Term ID and this is not any uniform presentation to try and sort by this column
- Sometimes the Parent is at the start, sometimes the parent is at the end, sometimes in the middle.
- See below screenshot
![image](https://user-images.githubusercontent.com/85008592/162105497-9211c0bb-1bdb-4a7c-a152-647f9781658b.png)

2. In Filter, the Term is not showing by name ASC-DESC order
- Imagine the filter is Year but it is sorting by Term Id, not Name.
- Please look at below screenshot and see how difficult it is to find the correct Year when there is no order by name.
![image](https://user-images.githubusercontent.com/85008592/162105554-54cb9de8-8aaf-4d4b-a104-b201a0c2e750.png)

3. It will be good if there was Sort option for Term Columns too
![image](https://user-images.githubusercontent.com/85008592/162105794-662a8c5b-739f-4d79-aad1-4fa8bb962860.png)

**Comment by kaskad88** [comment]
In the next version ( 2.11.10 ):
- 1 case - fixed
- 2 case - added order and order by options https://tppr.me/iQrab
- 3 case - WP_Query does not allow sorting by terms

Thanks for your report!

**Comment by ALPSIT** [comment]
> In the next version ( 2.11.10 ):
> 
> * 1 case - fixed
> * 2 case - added order and order by options https://tppr.me/iQrab
> * 3 case - WP_Query does not allow sorting by terms
> 
> Thanks for your report!

Awesome! thank you!
