### ISSUE TITLE
[JetElements] Video Player is missing 'playsinline' attribute: plays in mediaplayer on iOS

### ISSUE THREAD

**Issue by antoinelbch** [CrocoBlock/suggestions#5154]
**Describe the bug**
Video Player does not play inline but opens in mediaplayer on iOS

**To Reproduce**
1. Add a Video Player
2. Select Video Type = Self Hosted
3. Select Player = Default HTML5
4. Choose Video Source from Media Library
5. Set Video Options > Autoplay to off

**Expected behavior**
On iOS the video should play inline. Instead it opens in the mediaplayer

Reason: `<video>` tag is missing the **playsinline** attribute.
![video-playinline-ios](https://user-images.githubusercontent.com/1252145/162277596-0f6e1dc5-81b0-4264-8093-4b00f147a4a5.jpg)

**Comment by Gawuww** [comment]
Added in JetElements v2.6.4
