### ISSUE TITLE
jet woobuilder best sellers query not working

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5158]
In recent updates, this query has been added which is really useful for our websites. But I still could not understand this query. It does not work at all. When I place the query on the best sellers, it displays the products. While no products are sold on the website. On the other hand, a large number of store website employers want us to display the best-selling products. But I have not been able to use this query yet. This is a really big bug. I used to use the Woodmart template before. In this template, everything worked fine after selecting the query. But in jet woobuilder this does not seem normal. I'm really confused. If there is a specific solution for it, please teach it. This plugin has many users and they want to use this query. I can no longer lie to my customers to prevent them from showing best-selling products. Please fix this query. This is really important to us. This query is the most widely used feature on a store website. thanks

**Comment by Michaelgimii** [comment]
thanks @UraraReika , Will this issue be resolved in the next update? I'm really stressed

**Comment by x3mp** [comment]
As a quick workaround you can create a query fetching products and ordering them by "total_sales".

You can use the Listing Grid to list a custom listing.

Hopefully this helps for the time being!

**Comment by Michaelgimii** [comment]
thanks @UnrealPixel 
Like many other users of this plugin, I do not know how to code. I hope this problem in jet woobuilder is solved once and for all.

**Comment by x3mp** [comment]
> thanks @UnrealPixel Like many other users of this plugin, I do not know how to code. I hope this problem in jet woobuilder is solved once and for all.

I understand. If you want I can help you through the steps. You can send me a message on Facebook. I'm in the group.
[Here is my facebook profile](https://www.facebook.com/roel.petra.942/)

**Comment by Michaelgimii** [comment]
thanks❤

**Comment by Joliamendi** [comment]
+1 
I have this problem too. Please solve this bug

**Comment by UraraReika** [comment]
Please take a close look at this issue https://github.com/Crocoblock/suggestions/issues/4473.

We as well have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team.

Thank you!

**Comment by Joliamendi** [comment]
Thanks @UraraReika ,I did my best, but to no avail ...
Is there any more detailed training for it? And is it possible that this problem will be fixed in a future update?
All WooCommerce products have total_sales by default and will be added again if deleted. Strange, but at woodmart this was not a problem

**Comment by UraraReika** [comment]
We will take closer look at this.

**Comment by Joliamendi** [comment]
thanks @UraraReika, Will this be resolved in the new version?

**Comment by Joliamendi** [comment]
excuse me @UraraReika , Why was this issue closed?
