### ISSUE TITLE
Quick view using elementor pop up does not work for jet engine.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5160]
I wanted to design a professional Quick view using the elementor and jet engine, until the user clicks on the eye icon, the listing image will pop up so the user can see it better. But unfortunately it did not work. 

**How to implement**

I made a listing and put an eye icon inside it. Then I made a pop-up and put an image widget in it. I put the image inside the pop-up dynamically, to display the post image. Finally, I attached the eye icon in the listing to the pop-up, until the user clicks on the icon, the post index image will open as a pop-up, so that the user can see the index image and some information more quickly. Unfortunately, this did not work and the image in the pop-up displayed only the image of the last post.

**Comment by Floydtm** [comment]
To resolve your request, you need to use jetpopup
