### ISSUE TITLE
Ability to edit shipping and billing fields on my account page.

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5164]
We can now edit the fields only on the checkout page, but it is not possible to edit the billing and shiping fields on my account page. Please add.

**Comment by UraraReika** [comment]
You can edit them. Please contact our support team for more information.

**Comment by Joliamendi** [comment]
@UraraReika , Can we delete or rename some fields like checkout fields????

**Comment by UraraReika** [comment]
No you can't.

**Comment by Joliamendi** [comment]
Will this not be added?

**Comment by UraraReika** [comment]
Maybe.
