### ISSUE TITLE
Give Read more widget a option for read less button

### ISSUE THREAD

**Issue by knireis** [CrocoBlock/suggestions#5169]
When clicking the 'read more' button in the read more widget, the hidden section shows up and the butoon disappears. 
Sometimes there is a need for 'read less' button which hides the section again.

Is it possible to make an option so the button does not disappear but stays visible and changes the text on the button to 'read less'? And when clicking the button it hides the section again and shows the original 'read more' button?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.
Right now you can use the Unfold widget.

**Comment by knireis** [comment]
Ok thanks, i realize there is the unfold widget, but then the 'hidden' content has to be in the same widget/column. It has no option to show a separate section. That is a big difference.
