### ISSUE TITLE
Jet Engine UX design

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#517]
Hello, there are a few wishes for the convenience of using the Jet Engine.

1. Everything that is in the tab / accordion should be visually visible, the element becomes part of the tab only if it is pulled under the tab (similar to how it is implemented in the standard Wordpress menu) - https://prnt.sc/p44cme

2. The user should be able to collapse all fields that are related to a tab or accordion - https://prnt.sc/p44dv5

3. The name of the tabs / accordions should be in bold and not available for selection - https://prnt.sc/p44ew1

/*Оригинал*/
Здравствуйте, есть несколько пожеланий для удобства использования Jet Engine.

1. Всё что находится в табе / аккордеоне должно быть визуально видно, элемент становится частью таба только в случае если он подтянут под таб (аналогично как это реализовано в стандартном меню Wordpress)  - https://prnt.sc/p44cme

2. Пользователь должен иметь возможность свернуть все поля которые относятся к табу или аккордеону - https://prnt.sc/p44dv5

3. Название табов / аккордеонов должны быть жирным шрифтом и недоступны для выбора - https://prnt.sc/p44ew1

**Comment by kaskad88** [comment]
Added in JetEngine 2.2.0
