### ISSUE TITLE
The open in new tab option is not displayed by right-clicking. jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5171]
hi

In the product network widget, **if the Make Product Item Clickable option is enabled**, there is no open in new tab option when the user clicks right on the product. https://prnt.sc/6iRhxQtphTTz
[This option](https://prnt.sc/cM4idJBsDx6f) can be enabled to resolve this issue, but it is better if opening a new window is not mandatory. for many reasons...
Also, by enabling the application of the link to the thumbnail and the title, this problem will be solved to some extent. But the problem is that the open in new tab option is only displayed when the user right-clicks on the thumbnail and the title.
I'm not sure if this problem can be solved or not, but Please add this feature, while Make Product Item Clickable is enabled, if the user right-clicks on the product box, the open in new tab option will be displayed. **Of course, I tried this on a similar website that uses Make Product Item Clickable, and if you right-click on the product box, there was an open in new tab option.**

thank you

**Comment by UraraReika** [comment]
While the `<a>` tag is not allowed to contain `<div>` element, so in this case we created structure that imitate same behaviour as `<a>` tag does, for parent `<div>`. So in this case in can't be done.

**Comment by 79ho3ein** [comment]
Thank you
