### ISSUE TITLE
A feature request for booking duration - JetBooking

### ISSUE THREAD

**Issue by DamianMIS** [CrocoBlock/suggestions#5174]
Would be great to have an option to set the booking durations for example minimum amount of days, or types of bookings weekdays (Mon-Fri), weekends (Fri-Mon), full weeks( Fri-Fri and Mon to Mon) and no other custom dates.

**Comment by RobertLloyd45** [comment]
This would be a great addition to the plug-in.

**Comment by Ollie9T7** [comment]
Please add this functionality to the plugin

**Comment by UraraReika** [comment]
This functionality was presented in the latest release of the plugin 2.5.0.

**Comment by Ollie9T7** [comment]
> This functionality was presented in the latest release of the plugin 2.5.0.

This functionality was not added in the 2.5.0 update. We want to be able to allow guests to book set durations. Please re-open this.

**Comment by UraraReika** [comment]
Thanks for the feedback.
 Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. Your report is missing key information. Without it - it is hard for us to filter and prioritize the requests. Thank you for your understanding.
