### ISSUE TITLE
JetAppointments: Add more time to the "Locked Time Before" Feature

### ISSUE THREAD

**Issue by DrumFishDigital** [CrocoBlock/suggestions#5178]
I want to take appointments for my web design agency. I want prospects to be able to book a time with me but only be able to book a week in advance. I can currently only block off 24 hours.

Thanks
Christian Van Noort
![OBwG4H3uBN](https://user-images.githubusercontent.com/103557537/163110540-fb44ee65-122d-49e9-be14-78fd8c0deb70.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
