### ISSUE TITLE
JetEngine. Any record metadata and product attributes in the Dynamic Field widget

### ISSUE THREAD

**Issue by Olegggggggg** [Crocoblock/suggestions#518]
Hello. It would be nice to be able to use the Dynamic Field widget to display any other record metadata and product attributes, and not just the custom fields of JetEngine.

Original in Russian:
Здравствуйте. Было бы неплохо иметь возможность с помощью виджета Dynamic Field выводить любые другие метаданные записи и атрибуты товаров, а не только кастомные поля JetEngine.

**Comment by MjHead** [comment]
You can do this by setting required meta key into "Or enter meta field key" option - http://prntscr.com/p4a5ui. Meta key should be exactly the same as appropriate value of "meta_key" column in postmeta table - http://prntscr.com/p4aeb9, http://prntscr.com/p4afzx, http://prntscr.com/p4agxg

**Comment by Olegggggggg** [comment]
> You can do this by setting required meta key into "Or enter meta field key" option - http://prntscr.com/p4a5ui. Meta key should be exactly the same as appropriate value of "meta_key" column in postmeta table - http://prntscr.com/p4aeb9, http://prntscr.com/p4afzx, http://prntscr.com/p4agxg

Can product attributes also be displayed like this?

**Comment by MjHead** [comment]
Can be done with Query Builder

**Comment by stijns96** [comment]
> Can be done with Query Builder

Can you show how?
