### ISSUE TITLE
An important problem in Dynamic field widget - jet Engine

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5180]
I have created a cpt with a radio field in it On the other hand, I used a dynamic field widget at the front to display the desired option.
For example, the radio meta field has 3 options. I select one of them and I want the name of the radio field I selected to be displayed on the front. But it does not and only value is displayed. I checked all the settings but could not find a solution. I did not find anything even by checking the Filter field output option. The only solution is to use glossary, which prolongs the work a bit.
This problem exists in the radio, checkbox and selection fields.
Maybe adding an option like GET meta name in this section will solve the problem : https://prnt.sc/vEQ7vCiYlGov

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.
Right now you can use glossaries and it will solve your issues
