### ISSUE TITLE
Spam attack on ?jet_engine_action=book

### ISSUE THREAD

**Issue by Medienor** [CrocoBlock/suggestions#5182]
Hi! Today my ISP provider shut down my site due to spam attack on ?jet_engine_action=book

Spam sample:
1nerOx-005WiE-7E-H
MYID 1009 990
<EXAMPLE@cpanel96.proisp.no>
1649911695 0
-received_time_usec .224458
-ident MYID
-received_protocol local
-body_linecount 161
-max_received_linelength 522
-auth_id MYID
-auth_sender MYID@cpanel96.proisp.no
-allow_unqualified_recipient
-allow_unqualified_sender
-local
XX
1
tv-tower@crrt.uz

How can we make sure this doesn't happened again?

The hackers managed to send multiple spam email from my Wordpress email to other people through JetEngine plugins.

**Comment by MjHead** [comment]
Hi! We'll check this and make appropriate changes to make this more secure

**Comment by Medienor** [comment]
@MjHead let me know if you want entire log, they access Wordpress email from jetengine and push emails through PHPmailer with admin email. We blocked new user signups at the moment and run everything v3 captcha now.. let me know if I can help with log

**Comment by MjHead** [comment]
Thanks @Medienor We'll rewrite a bit logic of form submitting to avoid promatically sending data directly with ?jet_engine_action=book, its all we can do from our side at the moment, To protect from spamming with bot directly from the page with form, you need to use captcha. In the future we'll add own addon to additional spam protecting from the bots. Also you can migrate to JetFormBuilder, it already process this part a bit better
