### ISSUE TITLE
Ability to display products on backorder - jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5183]
On one customer's website, there are many products that are sold in advance. So their situation in woocommerce is https://prnt.sc/vsfBqg6Ljpzm

The customer asked me to display the pre-sold products on a separate tab so that users can access them more easily. As far as I checked jet woobuilder queries, there were no queries to display pre-sold products https://prnt.sc/8pJPs0ZrM-PX
Please add this query. Also an important option for pre-sold products is that, as I said above, I want to display the pre-sold products in a new tab. So is it possible to add a feature that pre-sold products are not displayed in other parts of the website other than the desired tab? For example, they should not be displayed in the list of the most serious products. I hope these two features can be added. thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
Right now you can implement this using the jetengine plugin. You need to create a custom query request https://prnt.sc/6zCdMSXPIIDj https://prnt.sc/L0xhj2Oxhoz3 https://prnt.sc/HUP5ZQ99Ci7t
