### ISSUE TITLE
JetWooBuilder - add infimite scroll to the widgets

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#5184]
It would be great if JetWooBuilder widgets (Products Grid or Products Loop) could use the Infinite Scroll feature. The same feature is already available [for JetEngine](https://crocoblock.com/knowledge-base/articles/jetengine-listing-grid-widget-overview/#title1.1). Can we have it for JetWooBuilder too?

**Comment by UraraReika** [comment]
Watch this https://crocoblock.com/freemium/tools/ https://tppr.me/dACAu

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
