### ISSUE TITLE
JetMenu - Icon library missing in Revamp Mode

### ISSUE THREAD

**Issue by bbua97** [CrocoBlock/suggestions#5186]
**Describe the bug**
Once the Revamp Menu is toggled on, there is no possibility to select a menu item anymore. 

**To Reproduce**
1. Go to 'Crocoblock>JetPlugin Settings>JetMenu>General'
2. Click on 'Revamp Menu - On'
3. Go to 'Design-Menus'
4. Try to select an Icon for any Menu-Item -> no icon library

**Expected behavior**
I expected to go to my Menu Settings and select an icon from the icon-library for the menu item like in elementor and any widget else I'm able to add an icon from my icon-library.

**Screenshots**
https://prnt.sc/jj01tlNCNWvQ - Revamp Menu - On
https://prnt.sc/oOZiSzsHHkED - Revamp Menu - Off

**Additional context**
I love the Revamp Menu because it's easy to use, has not too many options but still a lot of functions. Adding additional styling can done with custom css if there's a need for but "disabling" the internal icon library is a still important feature in my eyes. That's the reason I reported this as a bug and not a request. It's basically already a part of JetMenu which is not working with the revamp setting.

**Comment by Floydtm** [comment]
We will not be adding this to the revamp menu. You can always use the old menu. Or use svg instead of icons
