### ISSUE TITLE
JetBlocks - Sticky Section: Add support for new flex box container

### ISSUE THREAD

**Issue by JLAcostaEC** [CrocoBlock/suggestions#5187]
**Describe the bug**
When using Elementor Flexbox Container, the sticky option disappear from the advanced config of container.

**To Reproduce**
1. Enable Experiment: Flexbox Container
2. Go to edit one page with Elementor
3. open Advanced options
4. The JetBlocks Sticky options is missing.

**Comment by mbaierl** [comment]
The so-called "support" told me that they won't support Elementor Flexbox Containers until it is an official feature and not longer an Elementor Experiment. So this might take another year until Crocoblock will work fine with Elementor Containers.

**Comment by Galibri** [comment]
This feature is going to be implemented, It's a big change, and Crocoblock should work on this feature on priority.

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
