### ISSUE TITLE
JetWooBuilder - Add my acount endpoints for the full official WooCommerce range (membership, subscriptions)

### ISSUE THREAD

**Issue by bbua97** [CrocoBlock/suggestions#5189]
***Please, describe the feature request, making it clear to understand.**

Add custom endpoints from official WooCommerce extensions to the JetWooBuilder to get the #1 choice as WooCommerce customizing plugin.

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

E-Learning and Membership Sites are getting more and more popular. There are two official WooCommerce Extensions:
- WooCommerce Membership
- WooCommerce Subscriptions
They work hand in hand together with WooCommerce and offer endless possibilities. Because they work hand in hand this extensions use endpoints for the My-Account page. It would be a game changer if you could use the JetWooBuilder power to also integrate and customize the endpoints for these extensions.

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

This feature can be used for any type of membership site. Also it is a must have if you want to offer subscription products, either physical or digital. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

[WooCommerce Subscriptions](https://woocommerce.com/de-de/products/woocommerce-subscriptions/?utm_source=google&utm_medium=cpc&utm_campaign=marketplace_search_brand_row&utm_content=+woocommerce_+subscriptions&gclid=Cj0KCQjwjN-SBhCkARIsACsrBz7RNc3UQdEVhJ0hx_i8qk2oQE-VtvoZdT-ZautYNBXAJU5QbhfNO5IaAiSbEALw_wcB)

[WooCommerce Subscriptions My Account Pages (Image)](https://prnt.sc/2PMT1Bugh1x8)

[WooCommerce Memberships](https://woocommerce.com/de-de/products/woocommerce-memberships/?utm_source=google&utm_medium=cpc&utm_campaign=marketplace_search_brand_row&utm_content=woocommerce_+memberships&gclid=Cj0KCQjwjN-SBhCkARIsACsrBz7kHe3gfBEOWA3x1pw_U_CHHHLY-Rltzf6w52GjygEv0vFPM2W9ly0aAkKtEALw_wcB)

[Woo Commerce Memberships My Account Pages (Image)](https://prnt.sc/zsZOekGdU9tS)

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by UraraReika** [comment]
I merged this issue with [#2721](https://github.com/Crocoblock/suggestions/issues/2721), which is on the same subject so we could deal with it more efficiently.

**Comment by marowi85** [comment]
+1

I would like to see this as well.

**Comment by morosmo** [comment]
+1

**Comment by alexschneiderru** [comment]
+1
WooCommerce Membership endpoints would be much useful to have.
