### ISSUE TITLE
Easy shopping with Popups

### ISSUE THREAD

**Issue by zimmiel** [Crocoblock/suggestions#519]
Hello Croco-team!
------
|IDEA|
------
Create opportunity easy shopping with Popups as in the example: https://tilda.cc/tpls/page/?q=hvoyastoreru
As I understand for this need make several additions, modification.
1.
You have cool block called "JetBlocks" it has a lot of cool stuff (for example Shopping Cart) It helps pick necessary woo elements where necessary. But what if you add to "JetBlocks" product counter (with total price and +-) so that you can insert singly popup form (img 1)
![1](https://user-images.githubusercontent.com/42843497/64635181-c2d35480-d407-11e9-8dc0-34b9f1e5049a.png)
2.
Need to think how to do with BUY button (which opens the form) ONE-CLICK CHECKOUT.
Because in the example there are several steps:
1 click on product from archive page - open popup with single product
2 click BUY button - open popup with checkout counter and form
For button need function "add to Cart" and, at the same time, close Popup and open Popup with checkout. So need to think how best to do this step.

I think it's not so hard. Need to say some magic words "Croco-Bloco-Croco-Block" and to write some magic code
I hope I help! Thanks!

**Comment by MjHead** [comment]
Part of these could be achieved by JetEngine + JetPopup. The rest is irrelevant for JetBlocks plugin
