### ISSUE TITLE
Add to cart button in simple products - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5190]
In variable products, if a product is not available, the message "out of stock" is displayed and there is an add to cart button, but it is disabled : https://prnt.sc/Ngp89rpNTsS0
There is no problem here.

But in simple products, if the product is not available, the Add to Cart button is hidden : https://prnt.sc/pZhC-OIiuXlc
This severely damages the user interface...
Please add this feature if possible so that in simple products, if the product is not available, **the Add to Cart button is not hidden, but is disabled.**

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Please contact WooCommerce devs.
