### ISSUE TITLE
Filters are not automatically displayed in the desired category

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5192]
**Describe the bug**

I have just migrated to this great plugin. But I encountered a very important bug. In this plugin, if there is no product according to the filter in the archive, that filter will not be displayed. So far there is no problem. But if we consider a border for each filter ( filter widgets > Advanced tab > border ), this border will not be hidden with the widget, but will remain.
Please resolve this issue as soon as possible. Currently the only way is to use the display conditions widget to display the filters in the desired categories and this takes a lot of time. Also, using the display conditions feature for each filter will generate a lot of extra code. While it is not really needed.
thanks crocoblock team!

**Comment by Floydtm** [comment]
same #5093

**Comment by Joliamendi** [comment]
thanks @Floydtm , Is it clear when this problem will be solved?

**Comment by Floydtm** [comment]
Keep for updates
