### ISSUE TITLE
Query Builder Needs to have Request Parameters

### ISSUE THREAD

**Issue by toxickim24** [CrocoBlock/suggestions#5198]
In my "Search Result Page" elementor, I wanted to create a query builder but I cannot find "request parameter" in the settings

![Screenshot_1](https://user-images.githubusercontent.com/22664183/163660651-3470706b-dee2-4b1f-9dcb-f0ac8067443b.png)
![image](https://user-images.githubusercontent.com/22664183/163660680-5a1d9ea4-a346-40da-9bb8-d3d61dea6c48.png)

**Comment by Elsteck** [comment]
Does this help? https://crocoblock.com/knowledge-base/articles/jetthemecore-how-to-create-wordpress-page-template-for-certain-request/

**Comment by MjHead** [comment]
You can use Query Var macros for such purposes
