### ISSUE TITLE
Copy To Clipboard

### ISSUE THREAD

**Issue by wolfamri** [CrocoBlock/suggestions#5199]
Hey Crocoblockers,
I could really use a copy to clipboard widget. I have seen there are a few requests in this regard, so let me renew that.

I think it would be useful for many, many things. 
So far there only seems to be one competitor that is offering that solution, but I don't want to buy another plugin tbh ;).

It could be really simple: A text field for what you want to copy, and a button text. With the rest of the Elementor tools you could then easily create a button by yourself.

Thanks for the consideration ;).

**Comment by Floydtm** [comment]
#3378

**Comment by wolfamri** [comment]
Thank you, I saw that there have been a few requests, that's why I said I wanted to renew it.
The ones that show up when you search for copy to clipboard aren't really useful for most uses. 
The only one that seems universal is from one of your competitors that I don't want to name here. I can send you a pm if you are interested ;).
