### ISSUE TITLE
URGENT BUG DETECTED: JetEngine components behaviour on delete

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5200]
I found a huge bug, that needs to be fixed as soon as possible. please, i inadvertantly messed up my website with this :(
So if you delete a TAX or a CPT and then recreate it with the exact name and permalink, you'll have a big problem, because if you've done that, JetEngine still pretends there is no TAX or CPT with this name/permalink.

I don't know why this is happening, but I think it can be very dangerous, on a live website.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
