### ISSUE TITLE
JetEngine Forms - Separate Radio and checkboxes layout options.

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5202]
Currently we only can set a horizontal/vertical alignment for both radio and checkbox input fields in one particular form.
but if would be much better, if we could set a horizontal/vertical align option for each individual checkbox and radio field instead of the entire form. (Maybe a setting in the backend for each checkbox/radio input)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
You can use this option to resolve your request https://prnt.sc/5THDADp32693
