### ISSUE TITLE
JetEngine Forms - Options for the WYSWYG field

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5205]
Currently we can't really style the WYSWYG editor field. In this example i have installed the hello theme and sorry, but this looks just ugly. It would be great if there were styling options in the form module. and also functional options in the backend, because maybe i dont want that the user can edit heading tags, or links etc. Theoretically its possible ti hide them with css, but the user still could use keyboard shortcuts for this. its just not a very clean way.

so please improve this field a bit more.
Sincerely :)

https://user-images.githubusercontent.com/101653721/163685926-f3e61edc-3521-4185-8a91-709e5ffb56d0.mov

**Comment by Floydtm** [comment]
Check elementor settings please. https://prnt.sc/Q1hlZn36mlxT https://prnt.sc/ajjqykV3LqWy
