### ISSUE TITLE
JetBlocks - Anvanced login form dynamic options

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5208]
It would be amazing, if we could set custom conditions, like only this user role (e.g. admin) is able to login or redirections after login for different roles.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
