### ISSUE TITLE
JetProductGallery optimization

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#521]
1. There is no option for thumbnail size https://prnt.sc/p4r9h3, https://prnt.sc/p4r9ld
2. There are no settings to customize the images in full-screen view.  For now, there is only the lightbox the styles of which cannot be changed. In addition - make the option of connecting the standard lightbox of the Elementor, which can be configured in the Global settings https://prnt.sc/p4c9x8

**Comment by UraraReika** [comment]
Done. Next release.
