### ISSUE TITLE
What is the meaning of this widget?

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5213]
I asked the support, but they couldn't give me a clear answer what is this widget for. I don't understand the sense of the checked state. because if click on it, nothing happens? Can anyone explain it to me please?
![Bildschirmfoto 2022-04-16 um 20 36 14](https://user-images.githubusercontent.com/101653721/163687417-b3365af0-23d7-4d51-b36d-6827b30f2c9b.jpg)

**Comment by Floydtm** [comment]
I'm sorry that support couldn't help you. Please study this tutorial https://crocoblock.com/knowledge-base/articles/jetappointment-how-to-set-custom-item-templates-for-providers-and-services-fields/
