### ISSUE TITLE
Two new widgets for elementor - Code highlight and table of contents

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5214]
It would be really great if you could add a better version of these two widgets to elementor, because the built-in ones are really bad. the code highlight widget is missing some important features for example lots of styling options and a button that opens a new small window with the raw code inside of it. And the tables of content widget also doesnt have lots of styling options and doesnt has an initial state if the box is closed or open by default.

**Comment by Floydtm** [comment]
You better leave it here https://github.com/elementor/elementor/issues
