### ISSUE TITLE
"Recently Viewed Products / Post, etc." functionality 

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#522]
Usually, this feature is added through third-party WC plugins. Maybe it’s worth implementing it in  Listing Grid widget so that it allows the users to display recently viewed posts/products on the site.

**Comment by UraraReika** [comment]
@WildHund, hi! Functionality you want, already included to several widgets, such as Recent Products from JetElements for Elementor https://prnt.sc/q65yq4 and Products Grid with this option https://prnt.sc/q65z3n from JetWooBuilder for Elementor.

**Comment by estercg** [comment]
> @WildHund, hi! Functionality you want, already included to several widgets, such as Recent Products from JetElements for Elementor https://prnt.sc/q65yq4 and Products Grid with this option https://prnt.sc/q65z3n from JetWooBuilder for Elementor.

Hi, I detected this option (recently viewed products) not working correctly, someone else with that problem?

**Comment by UraraReika** [comment]
@estercg more details please.

**Comment by estercg** [comment]
> @estercg more details please.

I put the grid product with the recently viewed option and while you are looking at several products there comes a time that it does not react, it does not show you the last seen, it is very strange and I have checked it in 3 more or less websites

**Comment by UraraReika** [comment]
Check on our side and everything works proper.

**Comment by estercg** [comment]
> Check on our side and everything works proper.

with those steps going correctly? then there is something I do wrong: S
