### ISSUE TITLE
JetWooBuilder - Doesn't work with overridden template files

### ISSUE THREAD

**Issue by bbua97** [CrocoBlock/suggestions#5220]
**Describe the bug**
I want to override some default WooCommerce myaccount templates, but with enabling custom my account page and my account page endpoints it doesn't work.

**To Reproduce**
1. Create the folder "woocommerce" in your child theme folder
2. Create the folder "myaccount" in the "woocommerce" folder
3. Copy the "dashboard.php" template from the woocommerce plugin folder
4. Take any change, for example deleting the "Hello" message from dashboard template
5. No changes with "Custom my account page" and "Custom my account page endpoints" enabled 

**Expected behavior**
As this is a standard procedure to override woocommerce template files, JetWooBuilder should follow this procedure and take the information/templates from the child theme. So if I overwrite the dashboard.php template file for example and delete the "Hello Message" there, I expect that this one doesn't show up anymore.

**Screenshots**
[Template File](https://prnt.sc/_hT1jtm8wLGR)
[Hello Message still there](https://prnt.sc/j13sJtDXrL3x)

**Additional context**
If JetWooBuilder would work also with overridden template files it would give more flexibility also to handle custome endpoints with some workaround.

**Comment by UraraReika** [comment]
Hello @bbua97. Thanks for the feedback.

In our plugin we owerride WC templates as well to make our widgets and endpoints work properly. So if you want somehow owerride this template you should owerride JetWooBuilder templates. 

If you have difficulties feel free to contact our support team.

Thank you!
