### ISSUE TITLE
Call for price in jet woobuilder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5222]
Another important feature in the world of e-commerce is the call for price feature. Please add this feature. This great feature is also available in the woolentor plugin.

https://woolentor.com/demo/product/call-for-price/

This feature in this plugin is such that the add to cart button becomes the call button for price. If the user clicks on the button, the desired number will be called directly. And this great!

**Comment by UraraReika** [comment]
Hello @Joliamendi. This is basically button with `tel:123456789` `href` attribute. You can easily recreate it with the help of simple Elementor Button widget.  Try it.
