### ISSUE TITLE
+ - Buttons To add to cart button

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5223]
Please update the product number buttons in this plugin. The current buttons are very old. Few websites use such buttons.
This is why customers object to this type of button on their websites.
https://woolentor.com/demo/product/woo-logo-3/
Please consider this.

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

Please check [this](https://crocoblock.com/freemium/tools/) out. This [one](https://tppr.me/XAfpL) JetWooBuilder tab.
