### ISSUE TITLE
Custom Icon for Add to Cart Button - jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5224]
Please add the ability to insert a custom icon to the Add to Cart button. This feature is currently available in elementor, but unfortunately this is not possible in jet woobuilder. https://prnt.sc/Zlc7zkqnMQzE

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

Please check [this](https://crocoblock.com/freemium/tools/) out. This [one](https://tppr.me/T5QFM) JetWooBuilder tab.

**Comment by Michaelgimii** [comment]
Will not be added to the plugin core in the future? Many users are unaware of this
