### ISSUE TITLE
JetSearch - search data

### ISSUE THREAD

**Issue by bormotovva** [CrocoBlock/suggestions#5226]
history search data , and also global history search data

https://www.facebook.com/groups/CrocoblockCommunity/permalink/5359418470816197

**Comment by EquilibriumTechx** [comment]
History search, has its own storage, where we then can pull user specific history or the single user can see their search history and clear it if they want to and then we have global search history, meaning every user or overall search history, so we can see what history or keyword or search context all the user has done. It’s quite similar to google search, so we are able to determine what is trending search or what is top searches and etc .

**Comment by Crocoblock** [comment]
was added and released in 3.4.0
