### ISSUE TITLE
CrocoBlock - WPML - Translate Booking systém

### ISSUE THREAD

**Issue by SpaceGoal** [CrocoBlock/suggestions#5227]
**This is write me support Crocoblock, when i ask for translate Booking/Pop up in Spa Templates**

​As stated before JetBooking Plugin cannot be translated and use on multilingual sites. 

As much as we'd love to assist further with this, it is not something that we can resolve
Unfortunately, this is not possible yet, we do not have such functionality

I will pass this issue to the devs, and they will explore if it's possible to implement it in future updates ;) 
Besides, our team made a secure and convenient place for your suggestions! This makes it much easier to place requests and suggestions, furthermore this log will be carefully monitored and worked on https://github.com/CrocoBlock/suggestions/issues

**Comment by UraraReika** [comment]
Hello @SpaceGoal.

Thanks for the feedback. This was released in the latest version of the plugin.
