### ISSUE TITLE
Ajax search widget shall have option to select links from meta fields.

### ISSUE THREAD

**Issue by snehasisripples** [CrocoBlock/suggestions#5229]
Hello team,
It will be great if we can redirect our users to a specific link which will be present in meta fields rather than the only CPT single post page link.
I am facing this problem and I will be really happy if we can bring this feature to ajax search widget.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
