### ISSUE TITLE
Load more feature isn't loading the current query

### ISSUE THREAD

**Issue by dangerjules** [CrocoBlock/suggestions#5232]
Hello! I use the load more infinite scroll on my product category page and it was working fine until I came across this bug today. When I scroll the page to load more products, the products grid widget loads products from all the categories, not respecting the current query.

1. For example, this page is for the "dolls" category: https://lojahappytoys.com.br/categoria-produto/bonecas/
2. Scroll to the end of the page, and the widget will start loading more products.
3. You will see that the whole products grid changes, suddenly its not a dolls category page anymore, because even the products above the load changes.

This is a major issue, that's affecting the navigation of my store.

I am using JetEngine version 2.11.7, JetSmartFilters version 2.3.11, JetWooBuilder version 1.12.3 and the Load More plugin version 1.0.0.

Thank you in advance.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue. https://crocoblock.com/freemium/tools/ Also update the addon, maybe it will solve the problem. Let me know if this helped you.

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
