### ISSUE TITLE
JetEngine Nested Repeater (like in ACF)

### ISSUE THREAD

**Issue by EliasAAA** [CrocoBlock/suggestions#5233]
allow nested repeaters like they do in advanced custom fields. Create and Display Nested Repeater (Repeater Inside Repeater)

**Comment by EliasAAA** [comment]
Is there any progress with this ?

**Comment by ConsultMePL** [comment]
lol, no one gonna reply? another thread on this and no reply...

**Comment by alvarindev** [comment]
Any news regarding this feature? 
I would like to add also the possibility to ouput content from another repeater with the Dynamic repeater widget. Right now you can select one repeater and output all the content inside that repeater field but could be possible to create a Macro to output content from another repeater? Like %repeater-field|field-of-the-repeater...%

**Comment by sherikk** [comment]
+1

**Comment by aayla-secura** [comment]
I'll also add a +1, maybe if enough people request this, they'll pay attention :D

**Comment by josharroo1** [comment]
+1

**Comment by Crocoblock** [comment]
Hi
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/784)
