### ISSUE TITLE
Sticky Add to Cart for jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5234]
**Please, describe the feature request, making it clear to understand.**

Custom Sticky Add to Cart feature can be very useful.

https://user-images.githubusercontent.com/77163248/163976833-0d76e7bb-66c2-4935-8284-fcb04cf6f195.mp4

thank you

**Comment by UraraReika** [comment]
Thanks for the feedback.

We've checked your request and unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks.

But such a goal can be reached using a custom solution only. I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/

Thank you for your understanding.
