### ISSUE TITLE
Ability to display variables in two columns - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5235]
**Please, describe the feature request, making it clear to understand.**

It would be great if we could display the selection of variables in [two columns](https://prnt.sc/0T6hc1o2Dp8M). 
Another important point for this feature is that there is a responsive feature to specify the columns in this section. For example, on the desktop the option to select variable is displayed in two columns, but on mobile it is displayed in one column.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein, thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the one of our add-ons. For now you can override one of WooCommerce template to achieve this results.

Thank you for your understanding.
