### ISSUE TITLE
JetBooking - Ability to Block Days/Dates Per Product/Room/Event.

### ISSUE THREAD

**Issue by josepn77** [CrocoBlock/suggestions#5236]
I have some events that can be booked on Weekends only and some events on Weekdays only.
It would be great if we had the ability to block certain days (mondays, tuesdays, wednesdays, thursdays, etc) and dates (like April 30th or December 24th) per product.

This is needed because we have events that can be booked that are only hosted on Weekends (Saturday and Sunday) and events that are only hosted on Week Days (Mon-Fri).

We also do have some dates (holidays) we don't host any events so we don't want people booking on those specific dates.

**Comment by ghost** [comment]
This would be a great addition to the booking plugin

**Comment by Ollie9T7** [comment]
+1 This would be a very valuable addition to the plugin. It should have been in there as default.

**Comment by RobertLloyd45** [comment]
Please implement this asap, anyone who manages bookings in the real world knows how useful this functionality is!

**Comment by Ollie9T7** [comment]
https://github.com/Crocoblock/suggestions/issues/5376 Take a look at this and see if it is the same/ similar functionality you are looking for. Hopefully thins will get enough people behind to be implemented asap.

**Comment by Crocoblock** [comment]
Will be available in future updates
