### ISSUE TITLE
External linking to Google drive

### ISSUE THREAD

**Issue by josiase95** [CrocoBlock/suggestions#5237]
Hi CB,

So instead of buying more space on your hosting provider, it would be nice if you could link your downloadable files back to Google drive and purchase space there instead. It's way cheaper 😊 Tried it with the audio player, but unfortunately that doesn't work at the moment.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
