### ISSUE TITLE
Calendar Mobile Collapse

### ISSUE THREAD

**Issue by ocbroadband** [Crocoblock/suggestions#524]
**Describe the bug**
When viewing the calendar in desktop mode, when switching to tablet/mobile, the event listing goes away, and you can click the mobile trigger to show the events in the row below the date.  Once the display box is shown, if you change your browser size back to the desktop, the preview does not go away, and you do not have a way to close it as the mobile trigger has disappeared due to it showing the actual listing item in the date box.  The behavior is correct on actual tablets/mobile as you can not go to desktop size.

**To Reproduce**
1. Have a calendar prepared(CPT, Listing, Events Added, etc), and view it as a desktop.
2. Change browser size to mirror tablet/mobile size, and event listing disappears, and tablet/mobile trigger appears.  Click the trigger to show the event listing preview below the date row.
3. Change browser size back to the desktop size.  The preview from the mobile trigger is still displayed.
4. If you change browser back to tablet/mobile size, the trigger appears, and you can then collapse the preview, and then change back to the desktop.

**Expected behavior**
Preview from mobile trigger should disappear once the viewport is back to desktop size or bigger to be able to show event listings in each calendar cell.

**Screenshots**
Video attached.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 76.0.3809.132

**Smartphone (please complete the following information):**
 - Device: iPhone 6S / Chrome

**Additional context**
None.
[Calendar-Mobile-Issue.zip](https://github.com/Crocoblock/suggestions/files/3606821/Calendar-Mobile-Issue.zip)

**Comment by Floydtm** [comment]
@ocbroadband, HI! Thanks for your feedback.

We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support at support https://crocoblock.com/help-center/ for guidance in resolving this issue.
