### ISSUE TITLE
stop on hover for jet woobuilder Carousel (auto play)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5240]
Please add this option, so that if the mouse is on the carousel, the carousel will not move automatically and stop.

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

We use the same carousel library `Swiper` as Elementor. Elementor use not the last version of this library and this version doesn't have this option yet. When Elementor update this library we will make this option.

**Comment by Michaelgimii** [comment]
> We use the same carousel library `Swiper` as Elementor. Elementor use not the last version of this library and this version doesn't have this option yet. When Elementor update this library we will make this option.

@UraraReika , I just found out that elementor uses this feature in its slides widget : https://prnt.sc/OexoAwqVOGwF
Am I wrong?

**Comment by UraraReika** [comment]
@Michaelgimii they use custom written code not built in property.
