### ISSUE TITLE
 Enable Woocommerce Templates Styles - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5241]
**Describe the bug**

hi

When I disable this option in the jet woobuilder settings, several interferences occur on the cart & checkout page. I wanted to ask if this interference is normal and must this option be enabled?
If there is a bug, i explain the interference.

**Comment by UraraReika** [comment]
What option?

**Comment by 79ho3ein** [comment]
[This](https://prnt.sc/hcWCXrLnsyoD). I mentioned in the title

**Comment by 79ho3ein** [comment]
If we disable this option, the following bugs will occur :

- In the shopping cart, [borders become thicker](https://prnt.sc/dcqLIl_3PHQC).
- The apply coupon button is [moved to the opposite side](https://prnt.sc/Cy9iyY-0AS0x). (RTL)
- If we enable auto-update for the shopping cart, [the update button will appear again](https://prnt.sc/RZameKGq0R-s).
- On the payment page, only the border in the order table is [thickened](https://prnt.sc/nGavVLNXqtOH).

**Comment by UraraReika** [comment]
We recommend keep this option enable. So if it enable then plugin enqueue styles to make custom pages widgets look more  consistently.

**Comment by 79ho3ein** [comment]
If your recommendation is that this option be enabled, then there is no problem. thank you
