### ISSUE TITLE
Ability to use Jet shortcodes or ACF's in Rest API plugin settings

### ISSUE THREAD

**Issue by scott7414** [CrocoBlock/suggestions#5246]
I have a membership site where the users enter their API keys and we store them on an ACF on the user profile.
We'd like to display dashboard analytics using the dynamic charts and tables for each specific user.

As of now you can only hard code in one API Key for and endpoints URL., We need that API key to be dynamic to the user so it displays only their data to them. If we could have a drop-down in the plugin Rest API settings to use a User Meta field there, that would be awesome.
https://www.loom.com/share/ca1222fcc472421b8bb4fc8b1b2e8929

**Comment by MjHead** [comment]
Will be added with 2.11.11 update

**Comment by MjHead** [comment]
As for now you can do this from the codewith hook:
```php
add_filter( 'jet-engine/rest-api-listings/request/url', function( $url ) {
    return do_shortcode( $url );
} );
```

**Comment by scott7414** [comment]
Awesome thanks.. Do you have a rough ETA n that update?
