### ISSUE TITLE
Show primary taxonomy in Dynamic Terms widget

### ISSUE THREAD

**Issue by nickhubhub** [CrocoBlock/suggestions#5247]
I choose more than one category/taxonomy
Can you add an option button for select primary category/taxonomy in Dynamic Terms widget?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
