### ISSUE TITLE
How to change the URL slug when apply type to mixed

### ISSUE THREAD

**Issue by shahzaib786** [CrocoBlock/suggestions#5248]
**Describe the bug**
How to change the URL slug when apply type is mixed and whenever we click on each category, the category name should appear at the end of URL instead of this text "?jsf=epro-posts:latest&tax=category:27"

**Expected behavior**
The URL should change to the category name for example: www.blabla.com/ecommerce-trends, when we click on each category filter. Under the apply type "Mixed" or Page reload should reload the page with changed category name in the URL when applying category filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/27821066/164416279-b551e70d-cf52-47d1-a715-1a5629538371.png)

**Comment by Floydtm** [comment]
I understand that this is important to you, but this is not a bug.

**Comment by shahzaib786** [comment]
Ok, but also the apply type of page reload is not working, can you check please?

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!
