### ISSUE TITLE
Hook woocommerce_product_is_visible is not working on Product grid

### ISSUE THREAD

**Issue by beamkiller** [CrocoBlock/suggestions#5249]
**Describe the bug**
Hook woocommerce_product_is_visible is not working on Product grid

**To Reproduce**
```
add_filter( 'woocommerce_product_is_visible', 'hide_specific_product', 9999, 2 );
 
function hide_specific_product( $visible, $product_id ){
   
   if (  $product_id == 35322 ) {
      $visible = false;
   }
   return $visible;
}
```

**Expected behavior**
It hides the product.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
