### ISSUE TITLE
JetEngine - "Allow Custom" option for CCT meta fields

### ISSUE THREAD

**Issue by madmaxpowermx** [CrocoBlock/suggestions#5251]
Currently theres no option to add new values to the metafields like in the CPT. For example, like if we want to add new valures for a checkbox field, for this we have to go to the custom cotent type / glossaries and update from there and it takes some time when you are filling the values and then you have to open new pages for that

regards

**Comment by kaskad88** [comment]
I merged this issue with [#3964](https://github.com/CrocoBlock/suggestions/issues/3964), which is on the same subject so we could deal with it more efficiently.
