### ISSUE TITLE
Feature request: Warning - data will be lost if we change names on fields

### ISSUE THREAD

**Issue by glorpyz** [CrocoBlock/suggestions#5252]
Custom Content Type.
-Edit Content Type.
-Changed field Name/ID.
= Lost my data.

I think a warning would be nice thing to add. :)

**Comment by perks98** [comment]
Yes would be good to have a warning and maybe a converter/transfer tool so it moves the data to the new name maybe?

**Comment by MjHead** [comment]
On change CCT field name, the data will be copied from an old realted DB column into a new one. Such behaviour affects only fields renaming - If you deleting existing field and adding a new one instead - the data from deleted field will be lost, We added this warning into confiramtion popover

Will be released with 3.1.0 update.
