### ISSUE TITLE
One bug and one request for cart page - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5256]
**Please, describe the feature request, making it clear to understand.**

**BUG**

On the shopping cart page, if we use the svg icon to [delete button the product](https://prnt.sc/gumtoqRXdopE) , the color of the icon cannot be changed. (What a normal state, what a hover)

**Proposal**
In the shopping cart table, if we do not write any titles for some sections, such as the delete section, [only one code will be displayed](https://prnt.sc/BfP9us07wRBO). **It would be great if we could write a title, but choose whether to display it or not.**
Just like the [elementor form widget](https://prnt.sc/KSogEapPspKh) which has the same feature.
In fact, this feature causes us to [consider a title](https://prnt.sc/qFyCYzv7XJM2), [hide it for display](https://prnt.sc/yy4VX8t1g8N-), but [no code is displayed here](https://prnt.sc/oTSI01hcYzw2). Instead, the desired title should be displayed.
This offer is not really very important. But it is not bad if it is added.

thank you

**Comment by UraraReika** [comment]
**Bug**
We have checked your request and everything seems to be working correctly. Perhaps this is related to predefined color inside svg file.

**Comment by 79ho3ein** [comment]
hi @UraraReika
It is strange. Now that I have tested, everything is working fine. Anyway, thank you
