### ISSUE TITLE
Jet filters, ability to remove items based on criteria in conjunction with filters

### ISSUE THREAD

**Issue by Emerald-edge** [CrocoBlock/suggestions#5259]
Hi,

Please add the ability to exclude content based on the same things we can filter down by.

Eg when searching fruit if I'm looking for apples I could filter to apples but remove green leaving me with all apple choices that are NOT green hope this make sense.

Further example I want to look at shoes in certain style but not pink ones I'd exclude pink and include the shoe type I wanted.

Kind regards
Chris

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
