### ISSUE TITLE
JetEngine: Allow line breaks and paragraphs when displaying the meta field "textarea"

### ISSUE THREAD

**Issue by raabmar** [CrocoBlock/suggestions#5260]
When we want to show a longer text, we can use the meta field WYSIWYG or TEXTAREA.
Often WYSIWYG fields are not wanted, as the editor can add all possible things and ruin the layout (they perhaps add images, custom formatting, headers, etc.). Therefore, we could use the TEXTAREA.

The only problem is, that TEXTAREA automatically renders the text in a way that does not include any line breaks or a paragraph

So the following text, including line breaks added in the backend ...
![image](https://user-images.githubusercontent.com/15885290/165073531-668730f6-d20a-4711-8591-1fe75dc8f337.png)

... will become this text on the frontend
![image](https://user-images.githubusercontent.com/15885290/165073319-d1b94f76-0886-4730-91d0-e7ec794efc17.png)

---

**There is a workaround by adding `<pre>` tags in the Dynamic Field widget** 
https://www.w3schools.com/tags/tag_pre.asp

`<pre>%s</pre>`
![image](https://user-images.githubusercontent.com/15885290/165073368-addcff6c-c990-4565-ac76-e29b1be2e369.png)

When this workaround is applied the line breaks are shown in the frontend
![image](https://user-images.githubusercontent.com/15885290/165073389-06a4669b-0303-4119-8c2f-12275c122957.png)

It would be nice if there was a setting similar to ACF where it's possible to define if line breaks and paragraphs should be rendered in the frontend or not. This could be set in the field settings or in the widget itself.

**This is a screenshot from ACF as a reference**
![image](https://user-images.githubusercontent.com/15885290/165073959-d57bf530-9e22-4571-b5f0-78af08ce8168.png)

**Comment by edgBlw** [comment]
yeah i agreee. But alternatively for now you can use the dynamic field and the set the filter field output callback option to "Add paragraph tags (wpautop)" :)

**Comment by raabmar** [comment]
Need to try that next time, in my current development I switched already to WYSIWYG and try how it'll work out when the client adds content

**Comment by kaskad88** [comment]
@raabmar You can use the dynamic field widget and the set the filter field output callback option to "Add paragraph tags (wpautop)" https://tppr.me/lzkh
