### ISSUE TITLE
Ability to display Available colors in the product grid widget

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5263]
**Please, describe the feature request, making it clear to understand.**

Please add this feature so that we can display the colors available for each product in the product grid widget. https://prnt.sc/6vakFV07PMrU
This feature is really essential. Most customers want this from us, but unfortunately there is currently no such feature in jet woobuilder.
I do not know if you have thought about it before, so I'm asking if you have any plans to add this feature. a Good news ...

**Comment by Floydtm** [comment]
#361

**Comment by Joliamendi** [comment]
hi @Floydtm , thank you
May I ask if you have any plans to add it in 2022? Thank you for your reply.

**Comment by Floydtm** [comment]
I can't tell you exactly. keep for updates
