### ISSUE TITLE
Ability to exclude sale products in the product grid widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5264]
Please add a new feature so that we can exclude sale products in product displays. This is because most customers, including my customers, have a separate carousel on their website to display sale products. Therefore, there is no need to display sales products in the carousel of Samsung products or other categories.
Only one option is needed to exclude the display of sale products in the product grid widget. thanks

**Comment by Joliamendi** [comment]
+1

**Comment by UraraReika** [comment]
In one of the next update macros functionality for IDs field will be added and you will be able to use this code:

```
add_filter( 'jet-woo-builder/macros/macros-list', function( $list ) {
	$list['on_sale_products_list'] = 'get_on_sale_products_list';
	return $list;
} );

function get_on_sale_products_list() {
	$on_sale_products = array_merge( [ 0 ], wc_get_product_ids_on_sale() );
	return implode( ',', $on_sale_products );
}
```

Like [this](https://tppr.me/mqsZq).

**Comment by Michaelgimii** [comment]
Thank you. Will this code not be added to the plugin? Because this code is deleted every time the template is updated. It will also be usable for all users.

**Comment by UraraReika** [comment]
> Thank you. Will this code not be added to the plugin? Because this code is deleted every time the template is updated. It will also be usable for all users.

You should add this code to your child theme, then this code will not be deleted or rewritten. And don't forget to use this macros in proper field `%on_sale_products_list%`. Yes this will be usable for all users.
