### ISSUE TITLE
MCustom not found message for fillers in product grid widget

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5268]
I want the message no filter found to be found when no product matching the user's filters is found. But in jet woobuilder can only have one message. No products found!
If we use jet smart filters, it is better to add a new option to the product grid that will display a custom message for the filters. Therefore, we can set two custom messages in the product grid widget.
1- When no product is on the list: product not found!
2- No products were found matching the filter!

**Comment by Floydtm** [comment]
#4386
