### ISSUE TITLE
Make Jet Appointments listings available to Jet Calendar

### ISSUE THREAD

**Issue by wexdan** [CrocoBlock/suggestions#5271]
At present, it is not possible to show appointments created in Jet Appointments in Jet Calendar - they can only be viewed in the listing grid.

It would be very useful to be able to show the appointments in the calendar.

This is particularly important where multiple and repeat bookings are concerned, or there are several different services offered.

Thanks!

**Comment by Floydtm** [comment]
This was added in one of the updates https://prnt.sc/EF1_4V8q3gHD Let me know if this helped you.

**Comment by wexdan** [comment]
Thanks for getting back to me.

Unfortunately, I do not see that...

<img width="294" alt="Screenshot 2022-04-27 at 17 16 26" src="https://user-images.githubusercontent.com/65738884/165565055-d3158e3a-6758-42aa-ad71-953dff81b20c.png">

And when I asked support, they said it was not possible, and I should ad it as a feature request.

I wonder what I am doing wrong - can you point me in the right direction? There are no updates showing as available...

**Comment by Floydtm** [comment]
Update jetengine and jetappointment plugins to latest versions https://prnt.sc/s6l0NbuXLVsP

**Comment by wexdan** [comment]
Sad to say, I have:

<img width="1056" alt="Screenshot 2022-04-27 at 17 29 15" src="https://user-images.githubusercontent.com/65738884/165567554-62f10f4e-cc64-4009-bf54-904b87825c40.png">

Anything else I can try?

**Comment by Floydtm** [comment]
Looks like we missed something in the latest jetengine update. We will check everything and fix it in the next update.

**Comment by wexdan** [comment]
Fantastic news! I look forward to it!

Thanks for checking it out.

**Comment by Floydtm** [comment]
We've checked everything and it looks like your request hasn't made it into the plugin release yet and will be added later. You can wait for the appointments plugin update or contact our support team. The guys will update the plugin for you. Thank you!
