### ISSUE TITLE
Change the link structure after activating each filter

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5272]
On some websites, after a filter (Ajax) is applied to the website, the link changes according to that filter. I do not know if this feature is now available in jet smart filters. But please add it. But if it does not already exist, please add it.
thanks

**Comment by Floydtm** [comment]
Explore this tutorial https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-create-a-new-filter-and-apply-it-to-publications/ https://prnt.sc/vTP1Fe-nvu_Z
