### ISSUE TITLE
Webp support for Jet Engine gallery.

### ISSUE THREAD

**Issue by erotser** [CrocoBlock/suggestions#5273]
If you select webp files on your gallery meta you do not see thumbnails at the backend. The rest works fine but it looks like a small oversight.

**Comment by deepwaterpixel** [comment]
In the meantime, if you check the issue I raised, I was able to fix it by adding one line to the mime_type switch statement.  Hopefully this will be rolled into the next update so I don't have to edit the file anymore.  I already have this on live sites so it's important that it remain working until it's officially fixed.

Edit: I just tested the most recent update and WebP images appear to be showing without me making any modifications.  Has this already been patched in v2.11.8?

**Comment by kaskad88** [comment]
> In the meantime, if you check the issue I raised, I was able to fix it by adding one line to the mime_type switch statement. Hopefully this will be rolled into the next update so I don't have to edit the file anymore. I already have this on live sites so it's important that it remain working until it's officially fixed.
> 
> Edit: I just tested the most recent update and WebP images appear to be showing without me making any modifications. Has this already been patched in v2.11.8?

@deepwaterpixel Fix will be in v2.11.9
