### ISSUE TITLE
JetTabs - Mobile functionality for opening and closing tabs

### ISSUE THREAD

**Issue by maumo-cn** [CrocoBlock/suggestions#5274]
Hello!

We are using Jet Tabs Classic Accordion on our website ( https://astridsg.eu/work/ ) and we have a functionality request.

For mobile, we are using the Collapsible option. We like to enable this option since a user can **only open 1 accordion tab at a time**. The problem we are facing with the Collapsible option is that **you can't close an open tab by touching again on it**, it stays open until you click on another accordion tab.

If we disable the Collapsible option, users can close and open an accordion tab by tapping on it. But more than 1 tab can be opened at the same time. **We don't want that.**

What we are looking / requesting for is an option between those two, so **that a user can only open 1 project at a time, but also can close an open project when he/she taps on it again.**

Or maybe not create a new option for this, maybe just make so that the Collapsible option can close an open tab when clicking / tapping on it again.

Is this possible?

Thanks in advance! :)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
