### ISSUE TITLE
 Custom Code with Dynamic fields (JetEngine)

### ISSUE THREAD

**Issue by ignaciosantiago** [CrocoBlock/suggestions#5275]
Hi,

I am creating a listing site (for properties), and I have an external booking engine to let my users book the houses.

For example, for 1 of my properties is:

<div id="apartmentIframe1080262">
<br />
BookingToolIframe.initialize({"url": "https://login.smoobu.com/en/booking-tool/iframe/269035/1080262", "baseUrl": "https://login.smoobu.com/", "target": "#apartmentIframe1080262"})
</div> 

I had created a custom layout with Elementor and JetEngine, where I am showing all the dynamic fieds, but I am not able to make work this code. I am inserting this code with a "Textarea" Meta Field, but it doesn´t work.

Can you help me?

**Comment by MjHead** [comment]
For such case will be better to create custom shortcode to print this data in page content. Because implementing such functionality directly in Dynamic Field could cause security issues in the future
