### ISSUE TITLE
Count number of posts in a relation between CPTs

### ISSUE THREAD

**Issue by DaniloRie** [CrocoBlock/suggestions#5276]
I wanna count the number of posts in a relationship between 2 custom post types.
Sample:
I have a custom post type called films and another called actors, i want to output the number of films in relation to an especific actor.
Like Brad Pitt (Actor) have 3 posts (films) related in the actor -> film relationship. And autput the number 3 in a dynamic field or header.

Thanks!

**Comment by MjHead** [comment]
You can do this with Query Builder and Query Count dynamic tag - just create a query to get related films for actor and than use this query for Query Count dynamic tag
