### ISSUE TITLE
Jetwoobuilder - Login widget

### ISSUE THREAD

**Issue by rodolphebertozzo** [CrocoBlock/suggestions#5278]
When wrong values are entered in the login widget, there is no notice message indicating that the fields are wrong, just a refresh of the page. Can you fix this problem and add an error notice to this widget

**Comment by UraraReika** [comment]
Hello @rodolphebertozzo, thanks for the feedback.

We have checked your request and everything seems to be working correctly. We checked both Login widgets that our plugin has: Checkout Login Form and Myaccount Login Form. After you press the button page refresh and if something wrong you will get default WooCommerce notice for different types of mistakes.


![Image](https://user-images.githubusercontent.com/22199143/197797149-6d592a24-9c4e-4800-bc0d-585fe413f565.png)


So perhaps this is related to your site. Please contact our support team.

Thank you!
