### ISSUE TITLE
Attachment file link by ID - Open new window (code example added)

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#5279]
In a future possible to add a little extra function, to allow the link to open in a new window?

At the moment you can use the following jQuery code to do this manually

// for the dynamic field widget add your custom css and replace the "kattints2" 

    jQuery(document).ready(function( $ ){
      $('.kattints2').on('click', function(){
          event.preventDefault();
    var clickRef2 = $(this).find('a:eq(0)').attr('href'); 
    window.open(clickRef2, '_blank');  
  })
  
});

**Comment by kaskad88** [comment]
Add for the next version 1.1.3

**Comment by kaskad88** [comment]
https://github.com/MjHead/jet-engine-attachment-link-callback - @Lonsdale201  you can update manually from this repository
