### ISSUE TITLE
JetForm Builder  - Allow multiple not 100% width fields under each other with no relation

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5281]
https://user-images.githubusercontent.com/101653721/165716559-17764254-0ce3-412e-a253-51a9bc5144dd.mov

Currently if you have multiple fields in one line then you have a small field with maybe only 50% width and unert that row you want again 2 50% width fields. this is not possible because the rows are trying to always fit the 100% which kind of limitates you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
