### ISSUE TITLE
Dynamic Image Size (same as Elementor) (Height, Width, Fill-Cover-Contain-Auto)

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#5282]
Hi,

Please add more Dynamic Images Properties so we can play around with more functions such us

Height px/%
Width px/%
Fill : Cover, Auto, Contain, etc.

**Comment by Floydtm** [comment]
#5078

**Comment by kaskad88** [comment]
Add for the next version 2.11.11
