### ISSUE TITLE
"show if empty " option & Custom icon for jet woobuilder product grid/list star rating.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5283]
**Please, describe the feature request, making it clear to understand.**

Please add this feature to the product grid widget if possible, so that it is still displayed even if the [star rating](https://prnt.sc/7u9zMjvnonSX) are empty. (This feature is very useful in ui)

It would also be great if you could add a custom icon to display the Star rating in this widget. (Custom Icons for  Star rating)

thank you

**Comment by UraraReika** [comment]
I merged this issue with #4781, which is on the same subject so we could deal with it more efficiently.

**Comment by 79ho3ein** [comment]
hi
I'm sorry, I did not remember at all that I had a similar request before. Of course, the custom icon was not a duplicate. 

Anyway, thank you
