### ISSUE TITLE
Add variations swatches widget for JetWooBuilder

### ISSUE THREAD

**Issue by vmavrikios** [CrocoBlock/suggestions#5284]
Hi Crocoblock

A nice feature missing is to be able to add dynamic variation swatches in product loop.
[Your article](https://crocoblock.com/troubleshooting/articles/fail-to-add-attractive-variation-swatches-to-woocommerce-archive-page/) on this is nice to have but not easy to implement out of the box + you need to buy another premium plugin (that who knows for how long it will be compatible with Crocoblock plugins) 

The quantity widget is also not easy to customise as is.

So if we are talking about being able to fully customise purchase experience, how can we miss out these elements, which are two of the most essential interactive fields for an end-user. 
Modern conversion layouts need to be flexible to adapt to variable needs, depending on the way products are marketed.

Would love to see more flexibility in this soon.

Many thanks to the team

--

P.S.
Another option would be to be able to add these to any Listing Item used by a Listing Grid widget with JetEngine.
Personally, I would prefer working with JetEngine only, not having to switch on JetWooBuilder.
I understand this is doable only if a template for archive and single pages can be set e.g. by the theme or PRO Elements for Elementor.
But JetEngine is so powerful and adds all this dynamic capabilities to designers like me (that cannot go so far with code) that could be the only one tool for customising the purchase journey on a website.

**Comment by UraraReika** [comment]
I merged this issue with [#361](https://github.com/Crocoblock/suggestions/issues/361), which is on the same subject so we could deal with it more efficiently.
