### ISSUE TITLE
JetEngine - Admin menu bug "Edit with crocoblock plugins"

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5285]
The logo is aligned properly within the kava theme, but if you use the hello theme, the logo alignment looks like this:

![logo](https://user-images.githubusercontent.com/101653721/165837950-7042d51a-3300-4542-9c53-f337cd699e9f.jpg)

**Comment by kaskad88** [comment]
Fix for the next version ( 2.11.10 ). Thanks for your report!
