### ISSUE TITLE
JetEngine Settings page - Admin menu cut off

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5287]
Again, if you use kava everything works fine, 
but if you have the hello theme installed and you are clicking on certain tabs on the settings page, the admin menu get cutt off sometimes or is laggy

https://user-images.githubusercontent.com/101653721/165838904-aa12bf5d-8b07-4222-b023-fe74994b0f3d.mov

.

**Comment by MjHead** [comment]
Tested with Hello theme, Astra and GeneratePress in 3 different browsers - can't reproduce the issue
