### ISSUE TITLE
New move in autoplay option - jet woobuilder product grid

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5288]
In the product grid widget, if we enable the autoplay option, it will quickly return to the starting point when the carousel is finished.
Please add a new option, that if the autoplay option is enabled, we can control the speed of return.
If you see the carousel on this website, when the carousel ends, it slowly returns to the starting point. Finally, it would be great if we could control the carousel's return speed. https://web.dev/patterns/web-vitals-patterns/carousels/carousel-autoplay/

**Comment by UraraReika** [comment]
Hello @Joliamendi, thanks for the feedback.

In our plugin we use Swiper Slider library for our carousel and unfortunately this library doesn’t have such option. But in next major release 2.1.0 new JS trigger will be presented. With the help of this trigger you will be able to handle this functionality like this:
```
add_action( 'wp_footer', function () {
	echo '
	<script>
		jQuery( document ).on( "jet-woo-builder-swiper-initialized", ( _, swiper ) => {
			swiper.on( "reachEnd", () => {
				// First parameter - slide index, second parameter - animation speed.
				swiper.slideTo( 0, 5000 );
			} );
		} );
	</script>
	';
} );
```
Just add this code to you child theme `functions.php` file.

Thank you for your understanding.
