### ISSUE TITLE
Modal/Popup inline editor (similar to Tooltip)

### ISSUE THREAD

**Issue by ofmarconi** [CrocoBlock/suggestions#5291]
It would be wonderful if we could create Popups/Modals right in the editor of the current page.

JetTrick already has the Tooltip that helps a lot!

My suggestion is to improve the Tooltip so that we can create simple popups.

something similar to this: https://www.dynamic.ooo/widget/modals/

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
