### ISSUE TITLE
For the Login Form widget, add the option "Lost your password?"

### ISSUE THREAD

**Issue by Floydtm** [CrocoBlock/suggestions#53]
For the Login Form widget, add the option "Lost your password?"
 https://prnt.sc/mgyfet https://prnt.sc/mgygln https://prnt.sc/mgyhav https://prnt.sc/mgykwp

**Comment by knireis** [comment]
+1 because at the moment the lost password option comes in view only after entering a wrong credential and this is confusing for my visitors.

**Comment by stasonua0** [comment]
+1
The widget is currently useless without this function.
