### ISSUE TITLE
Create a button with a dynamic link to recover deleted posts - JetEngine

### ISSUE THREAD

**Issue by koke2801** [CrocoBlock/suggestions#5301]
I'm creating a project, product catalog mode, and just like you can add a button with a dynamic link to delete or edit the post type, it would be great if you could add the feature to retrieve a deleted post type.

please consider it, thank you!!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
