### ISSUE TITLE
JetElements Testimonials Widget Only Showing First Slide

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#5304]
**Describe the bug**
Site is running Jet Elements 2.6.4.

The testimonial slide has started acting strangely. It is only showing the first slide.

As an experiment I turned on dots navigation and it thinks there is only one dot, but the markup for the slides is showing in source.

As a further experiment I started a new page, with a default Testimonials element dropped onto the page, and then even turned it to Elementor canvas to stop anything else interfering, and its still showing just one dot and can't navigate between slides:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1038062/166660665-ede05fe3-782b-470b-b7ae-b6ef8923cdf7.png">

In this shot you can see slick dots has just found one slide, but there are lots of slides in the markup and you can see on .slick-track that the carousel autoplay is ticking along, but something has gone wrong:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1038062/166660936-5c74719f-df4e-474a-b257-3a84cea6b7b9.png">

In the admin / editor it is working as normal:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/1038062/166661347-c500abb4-68de-4051-8878-32d1b11bbfc3.png">

I have just tried this on another site and the same thing is happening, so this definitely seems to be a bug:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1038062/166661479-952ee3db-ebb8-480c-b36a-ba712bc243ec.png">

**To Reproduce**
1. Add Jet Elements Testimonials widget to the page
2. View it on the front end

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 101

**Comment by Floydtm** [comment]
Update the plugin to version 2.6.5 Thank you!

**Comment by rtpHarry** [comment]
Thanks, for some reason the plugins hadn't registered that new versions were available. I manually clicked the check for updates and it came through. Fixed on the site now.
