### ISSUE TITLE
Add Off Canvas Slider

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#5306]
Add the posibillity to add OFF-CANVAS Slider option on th e Listing widget.
https://youtu.be/QteosgBNe9Q?t=759

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
