### ISSUE TITLE
Range filter does not update min and max price dynamically according to selected products - woocommerce

### ISSUE THREAD

**Issue by aminjabari** [CrocoBlock/suggestions#5307]
**Describe the bug**
Range filter derives min and max amount of products price according to ALL woocommerce available products. 
**To Reproduce**
1. Create a range filter for woocommerce product price
2. Create a new page with elementor
3. Add elementor products widget
4. Select few low-price products
5. Add range filter to the page and select the created filter in step one
6.  Relate the filter to elementor products widget
7. Publish and see the results 

**Expected behavior**
I expected that the range filter derives min and max price values from selected products within elementor widget or any other widget for selecting products. 

**Screenshots**
https://snipboard.io/58PcRo.jpg

As you can see in this screenshot, max price of selected products is 55 euro. But Price filter max is 1000 euro (price of one of our products is 1000 euro, but it is not selected in this list)

**Additional context**
I clicked index filters button numerous times. but it did not solve the issue.

**Comment by 79ho3ein** [comment]
If I understand what you mean, I do not see a similar problem on my website. This may be related to your website.

**Comment by aminjabari** [comment]
**Range filter setting screenshot** (https://snipboard.io/fkRzTc.jpg)

**Edit page screenshot** (https://snipboard.io/aeEGY5.jpg)

**Jetsmartsfilter setting screenshot:** (https://snipboard.io/v3DjkB.jpg)

I deactivated all plugins, except Elementor, Elementor Pro, JetsmartsFilter and Woocommerce.  (All of them updated to the newest version)

You can check live version of described issue in **[this link](https://test.aminjabari.com/elementor-3253/)**

Why this is happening for me?

I would appreciate if you can check and describe the problem.

Thank you

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
