### ISSUE TITLE
Jet Engine integration proposal with the Divi builder

### ISSUE THREAD

**Issue by cmolinah86** [CrocoBlock/suggestions#5309]
Hello,

I wanted to request the possibility of evaluating a Crocoblock Jet Engine integration with the Divi builder.

I have been able to use it quite a bit and some of the functions are working fine but others are giving me problems.

For example:

I have created an options page for slider data.

Options created:
- Image
- Title
- Description
- Text Button
- Link button

The problem is that when I try to load the data of the options page in the Slide of the home of my website, it does not work.

I think that integrating with the Divi builder just as it has been done with Elementor can be a great value contribution since the Divi Theme community is huge.

Greetings

**Comment by Floydtm** [comment]
#4379
