### ISSUE TITLE
Feature request for Jet Booking Plugin

### ISSUE THREAD

**Issue by manashjyotix** [CrocoBlock/suggestions#5313]
Hello, Crocoblock I want to make a booking site for myself. There are too many CPT for each CPT I want to add booking system. But there is one down side sorry but Jet Booking is now support only 1 CPT. Please do the above features to Jet Booking plugin.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
