### ISSUE TITLE
[JetformBuilder] Button Action Type -> Field Visibility

### ISSUE THREAD

**Issue by usblsb** [CrocoBlock/suggestions#5316]
Hello, good morning.

All the form fields have a visibility setting **(Field Visibility)**.

The field button (Action Button) field has no visibility setting.

Can you put the visibility setting **(Field Visibility)** for the button field **(Action Button)**?

**Thanks**

![Action Button](https://user-images.githubusercontent.com/105101643/167244804-0f60d5e4-7e47-445f-94e1-5bf7ee79c799.jpg)

**Comment by Floydtm** [comment]
Read this tutorial https://jetformbuilder.com/features/conditional-visibility/
