### ISSUE TITLE
[IMPORTANT BUG] JetSmartFilter + JetWooBuilder: When use filter product with ajax options. Details bugs in comment

### ISSUE THREAD

**Issue by ki96hn** [Crocoblock/suggestions#532]
http://prntscr.com/p6sklk
http://prntscr.com/p6slc8

**Comment by Floydtm** [comment]
@ki96hn, Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help
