### ISSUE TITLE
User Page Rewrite BUG!

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#5320]
Hi
I have a front-end dashboard made by profile builder and a single user page, when I set the User Page Rewrite on nickname
The URL will not change! 

Actually I want to use custom field to be used in the user single page link, but right now it's not possible to achieve it by jet engine so I map the specific field to nick name
1- please fix this issue if its a bug
2- being able to select custom field to use in User Page Rewrite

![4](https://user-images.githubusercontent.com/86493591/167379924-1503aafa-833e-496e-a534-ec6cfee46890.png)

**Comment by 79ho3ein** [comment]
+1

**Comment by Floydtm** [comment]
Everything works correctly. You should have noticed that this is a different meaning. nicEname and nicKname https://prnt.sc/Cl7vUY48u62q https://prnt.sc/LTmwqLIZmSo_ 
the nicename value is taken from the database https://prnt.sc/0jMskPn0kFJ8

**Comment by mehdimoradi1500** [comment]
Thank you, so can i map any custom field to user_nicEname?  
The second link doesn't show any content (https://prnt.sc/LTmwqLIZmSo) 
 
Is it possible to consider this issue 👇
*being able to select custom field to use in User Page Rewrite*

**Comment by Floydtm** [comment]
"being able to select custom field to use in User Page Rewrite"
At the moment, we do not plan to introduce such functionality into our plugin.
