### ISSUE TITLE
JetBlocks Login Form Error Not Disappearing

### ISSUE THREAD

**Issue by jimhuds** [CrocoBlock/suggestions#5325]
When an incorrect login is entered, the error message is shown below the form but does not disappear and is shown for all users.

I'm not that knowledgeable on this sort of thing so I've pasted the response from my hosting support 

> This is being caused by the JetBlocks For Elementor plugin which is handling the login for in this case.
> 
> Specifically, the issue occurs in the files:
> jet-blocks/templates/jet-login/global/messages.php
> jet-blocks/includes/class-jet-blocks-handlers.php
> 
> There they use a pair of wp_cache_set and wp_cache_get functions, however once the message is set using wp_cache_set, it's never reset or removed, just stays there.
> 
> What I think they wanted to do is that when you log in and fail, the page reloads but you need to somehow see what was the issue. WordPress by default does that by redirecting with a query parameter in the URL which states the reason. They cache the error returned by WordPress so it can be shown on the login page after it reloads. This is incorrect use of this mechanism which leads to the error being cached for every user and is never reset.
> 
> I've temporarily added a small fix to the jet-blocks/templates/jet-login/global/messages.php file which will cause the cached message to be deleted after being requested. This will limit the impact of this issue.
> 
> ![180490 Large](https://user-images.githubusercontent.com/23201061/167590973-0cd5bd96-8fae-4061-9a22-ad1fd71cf786.jpeg)
> 
> Unfortunately, there are two problems with that solution at the moment:
> - the fix will be removed as soon as the plugin is updated
> - the fix requires to flush Object Cache after the message is displayed, thus causing a performance penalty

Using latest plugin versions and also have the new Elementor Containers enabled if that helps.

Thanks

**Comment by jimhuds** [comment]
Any info on this? The error returned after updating the plugin so I've had to add the fix above again. Cheers

**Comment by jimhuds** [comment]
Still getting this issue. Would be great to get this solved. Thanks

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-blocks/tree/sug/issue%235325
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by CeciliaTabbi** [comment]
I had this happen and found it was cause by an async javascript plugin I had. I added an exception to JetEngine and the issue was resolved.
