### ISSUE TITLE
JetWoo Builder can't translate "You may be interested in …"

### ISSUE THREAD

**Issue by sonnesworld** [CrocoBlock/suggestions#5326]
**Describe the bug**
I want to change the text You may be interested in... for upsell products with Loco translate and can find the string but the change is not visible in frontend.

I use JetWoo Single Template and Upsells widget.

**Screenshots**
Widget
![screenshot-eskimo-shop ch-2022 05 10-11_32_36](https://user-images.githubusercontent.com/57396134/167597774-ae4e251a-e475-44cb-b951-978eab601e34.jpg)

Changed the text in Loco translate
<img width="689" alt="image" src="https://user-images.githubusercontent.com/57396134/167597104-1655bd49-64dd-4272-b476-3c8e4ebaef01.png">

Still the default text
https://eskimo-shop.ch/p/savona-wohndecke-landschaft/
![screenshot-eskimo-shop ch-2022 05 10-11_30_44](https://user-images.githubusercontent.com/57396134/167597417-a90fe5e3-76d7-47d6-be1c-2036ef93b1e5.jpg)

Many thanks for checking

**Comment by UraraReika** [comment]
Hello @sonnesworld !

You use Upsells widget but in translate file if you look attentive you will notice Cross Sell widget. As for Upsells widget we use WooCommerce template so if you want to translate it file this you would translate WooCommerce plugin.

**Comment by sonnesworld** [comment]
Hi Urara, now it works, sorry for that. The first time I tried everything out nothing worked.
