### ISSUE TITLE
JetSmartFilters multi-level horizontal radio filter with child categories listed below parent categories when the parent category is selected

### ISSUE THREAD

**Issue by GDUpson** [CrocoBlock/suggestions#5329]
Please add the ability to be able to create a horizontal radio filters with child categories listed below parent categories when the parent category is selected.

Here is a quick and dirty visual as an example for your understanding.

![Horazontal-radio-filter-with-child-categories-](https://user-images.githubusercontent.com/88692162/167665313-1a5ac451-9ead-45b5-a5c2-4e3dfeaad6ec.png)

I was surprised when advised by support that this functionality isn't achievable.

I thought that this would be a reasonably basic function which I have seen on many stand alone themes.

I intended to switch my entire work flow over to Crocoblock but it's clear that are some significant limitations here.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
