### ISSUE TITLE
bug in sorting "recently viewed" query - jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5330]
I wanted to display "recently viewed" products by time. That is, the products are displayed in exactly the order that the user has visited.
Unfortunately, sorting does not work properly for this query : https://prnt.sc/2vjwoFFPRU7z
Of course, it only shows the products correctly up to 4 times, but more than 4, irregular products are displayed.
Please resolve this issue.

**Comment by UraraReika** [comment]
In this case this is not a bug, because sorting works correct due to option that you choose. Date sorting takes publish date and sort the products grit to it. There is no specific option to sort recently viewed products by time or any other option.

**Comment by Michaelgimii** [comment]
tnx @UraraReika , Will this feature be added?

**Comment by UraraReika** [comment]
No it won't.
