### ISSUE TITLE
bug in ajax add to cart - jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5335]
I try to customize WooCommerce notice using elementor and display them on the product page. But there is a very important problem. The problem is that if Ajax Add to cart is enabled in Jet WooBuilder, after adding to cart on the product page, the WooCommerce notice will not be displayed!
Therefore, the page must be reloaded after adding to the cart, to display the WooCommerce notice. Please fix this bug

**Comment by zahnd** [comment]
Hi @Michaelgimii, where could you enable Ajax Add to cart in JetWooBuilder? Don't find this option. Thank you
