### ISSUE TITLE
jetAppointment: Users can edit their own schedules

### ISSUE THREAD

**Issue by crislome** [CrocoBlock/suggestions#5336]
So here is my suggestion... I was studying jetAppointments to see the possibility of using it for Online Classes, where the student could schedule a single class or several classes through the MultiBooking feature. But for me to be completely satisfied, the student when scheduling the class, there should be the option to register the student and he himself could change the day and time of the classes when necessary, but I was informed that this feature is not possible in the recent version of jetEngine.  It would be very interesting to add this possibility since by jetEngine's programming this is already built in. So here is my suggestion.

**Comment by mpelczar** [comment]
Yes! I think its important feature. This is the only thing that for me jetappointment lacks :(
Would be also vert satisfied implement this feature and let clients change schedule in their profile or through email link.

**Comment by Ricarditu** [comment]
Also, I think there should be a way to custom edit the number of slots for multibokking per service. For example, service A allows to book 4 slots at once and service B allows 5.
The option for users to edit their appointments on the frontend, as @mpelczar says, would be a great improvement!

**Comment by Crocoblock** [comment]
Hi
I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/6401)
