### ISSUE TITLE
hover effect for category grid widget - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5337]
**Please, describe the feature request, making it clear to understand.**

hi

Currently, the category grid widget does not have a suitable hover effect. In fact, only some of them, such as shadows, can be controlled.
Please watch the video below : 

https://user-images.githubusercontent.com/77163248/168039347-48afdd3a-53ea-4638-b56a-970e1c06451e.mp4

These effects are present in elementor : https://prnt.sc/kFQDshTXUTKy

Please add this feature if possible.

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
