### ISSUE TITLE
JetSmartFilters: More suggestions for missing features

### ISSUE THREAD

**Issue by jandrabek** [Crocoblock/suggestions#534]
Hello, so far JetSmartFilters is best filtering plugin for Elementor. However is missing some important features. I'll try to fit all of them into this post.

1. Filtering logic. Now there is for checkboxes only one logic which is OR. Some filters needs to use also AND logic.
2. Count - missing number of items in each taxonomy.
3. Hide empty terms - every term is now showing and without count there is no way to tell if it shows empty results.
4. Ajax filter for current query - not sure if this is real issue but ajax is not working for current query but when you specifi query via post type ajax works fine.
5. Multiple select. Something similiar to checkboxes but in a select filters.
6. Preselect - when you have filters on taxonomy page and you go there, filters are empty so you have the taxonomy selected but it doesn't show in filter. It would be great to have taxonomy selected by default if it is contained in filters.

This might be so fat all. I'm glad I found Crocoblocks.

**Comment by scubaninja1977** [comment]
allow the ajax filters to lookup an array instead of a single entry on a page or multiple pages

**Comment by DAikuki** [comment]
We really need these features.

**Comment by DAikuki** [comment]
UP
Any news ?

**Comment by davidamarek** [comment]
+1

**Comment by yosnap** [comment]
+1

**Comment by c-kunnen** [comment]
Any updates? This is a necessary feature.

**Comment by VantageUAV** [comment]
Any updates? Still getting terms showing for empty taxonomies

**Comment by marowi85** [comment]
+1

**Comment by 0mid2248** [comment]
+1
there is an option for show/hide empty terms but its not working idk why

**Comment by Crocoblock** [comment]
done in JetSmartFilters 3.6.0
