### ISSUE TITLE
Jet Engine repeater support for the image comparison widget

### ISSUE THREAD

**Issue by erotser** [CrocoBlock/suggestions#5342]
It would be nice to have the jet elements image gomparison widget (aka before after) to support repeater fields. 
There is no way to crate an unknown number of before after scenarios in a custom post type right now.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
