### ISSUE TITLE
JetEngine: Audio Player Waveform Upgrade

### ISSUE THREAD

**Issue by Paul1x** [CrocoBlock/suggestions#5343]
A option to activate the audio waveform instead of the boring progress bar. I attached an example:
![ezgif-5-835aeee782](https://user-images.githubusercontent.com/105491414/168280878-d465a21f-cdf9-4425-a7ad-7d4e3418abe0.jpeg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
