### ISSUE TITLE
Better Carousel/Slider for widgets (Products Grid/Advanced Carousel) etc.

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5345]
Hi there. There is a bunch of widgets with Carousel/Slider options. Products Grid uses swiper, Advanced Grid uses slick. Both of them (js plugins) are very hard to customize with css and uses data attributes for all customizations. There is no reason at all to use diffrent js plugins in diffrent widgets. Swiper and Slick really not so good at all. There is a top notch plugin which used in Salient Theme for wordpress, and it calls FLICKITY. Maybe Crocoblock team may integrate this js carousel to your widgets and remove this thresh swiper and flicker? It really cannot be styled to mobile app view in many situations.

Just look at FLICKITY options... This is a real carousel and it can be styled more better than swiper or flicker:
https://flickity.metafizzy.co/options.html

Swiper and Slick are not true carousels. They are sliders. And they called Swiper SLIDER and Slick SLIDER. Flickity called Flickity CAROUSEL.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
