### ISSUE TITLE
Datepicker specific checkin days

### ISSUE THREAD

**Issue by avdstelt** [CrocoBlock/suggestions#5346]
Hi,

Is it possible to only activate specific days on the datepicker to checkin like for example on Monday and Friday?

Greetings Arjan

![image](https://user-images.githubusercontent.com/851114/168416233-3bd3fcdf-5988-40a1-b2fd-e4cd49349188.jpeg)

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by avdstelt** [comment]
> Describe your request in more detail, if possible, add screenshots or video. Thank you!

Hi,

I have a customer and the only days to checkin/checkout are on Friday and Monday.

Is it possible to only be able to select these days in the datepicker and the other days are blocked for selecting?

See the image in the first post as an example.

Greetings Arjan

**Comment by Floydtm** [comment]
I understand you, but this is not possible now. And while we can not add it. Thank you!
