### ISSUE TITLE
Jetsmartfilter Range filter: Only minimim or maximum, not both

### ISSUE THREAD

**Issue by MichielWolvers** [CrocoBlock/suggestions#5347]
**Please, describe the feature request, making it clear to understand.** I would like to have the ability with Jetsmartfilter Range filter to only select the Maximum or Minimum, instead of both. 

While having the ability to have both minimim AND maximum filter is sometimes useful, it may lead to customer drop-off because a too specific range is selected. When the selected range is too specific, no products may show show to the customer, leading to the customer thinking that the website is not working.

Having only a maximum will increase the selected range and thus increase the chance of products returning to the customer, leading to a better customer experience.

**Add an example of where this feature is already implemented.** 

Working example: https://www.pricewise.nl/sim-only/

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
