### ISSUE TITLE
Order Listing Grid posts by WooCommerce product attributes

### ISSUE THREAD

**Issue by vmavrikios** [CrocoBlock/suggestions#5349]
Hi Crocoblock..

From my research, experimentation, enquiry and replies from your tech support ..apparently it is not possible yet to order posts by product attributes. 
One is limited to order WooCommerce products by date, price, author and other meta ..but not by custom fields added like product attributes.

I am currently working on an ecommerce project ..that focuses a lot on product attributes for their products in order to give their clients enhanced filtering capabilities. It came by surprise that building everything with JetEngine and using JetSmartFilters at the end we were not able to order them by those product attributes.

Please look into it and incorporate it in a future update.

Kind thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
