### ISSUE TITLE
JetEngine. Woocommerce meta data and product attributes in the Dynamic Field widget

### ISSUE THREAD

**Issue by Olegggggggg** [Crocoblock/suggestions#535]
Hello. It would be nice to be able to use the Dynamic Field widget to display Woocommerce meta data and product attributes in the Dynamic Field widget.

**Comment by elias8808** [comment]
I agree with Oleg, for example I am trying to create a custom grid listing and I need to show product attributes but it doesn't let me. How can i fix this?

**Comment by blkaka** [comment]
You can do it. Just Enable archives for Product attributes. Then you can see the product attributes in the  Dynamic terms widget

**Comment by elias8808** [comment]
Where can active archives for product atributes?

**Comment by blkaka** [comment]
You can [see here](https://demo.zoomworld.vn/wp-content/uploads/2020/02/enable-attribute-archive.png)

**Comment by Olegggggggg** [comment]
> You can do it. Just Enable archives for Product attributes. Then you can see the product attributes in the Dynamic terms widget. the result [here](https://demo.zoomworld.vn/custom-product-loop-1) for the color attribute

This is not quite what need, if you make a display as you wrote, you can only display all the attributes at once, there is no way to display one attribute separately and arrange them differently. If add the ability to display attributes with the Dynamic Field widget, this will give much more freedom for design and layout on the page.

**Comment by tbalza** [comment]
Not a fix, but a default title widget has a dynamic option for displaying woocommerce attributes

**Comment by MjHead** [comment]
Can be done with Query Builder

**Comment by rpgraul** [comment]
> Can be done with Query Builder

can you explain how?
