### ISSUE TITLE
JetFormBuilder: use multiple calculated fields 

### ISSUE THREAD

**Issue by tomaski** [CrocoBlock/suggestions#5351]
**Describe the bug**
When adding more than one calculated field to a form, only the last one gets executed.

**To Reproduce**
Build any kind of form where multiple calculations need to be performed. For example:
add field 1
add field 2
add field 3
add calculated field 1 to sum up field 1 and 2
add calculated field 2 to calculate field 3 * any value

**Expected behavior**
Both calculated fields should return value.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: 
   - Chrome 101.0.4951.54
   - Firefox 100.0

**Smartphone**
 - Device: Samsung S22 Ultra
 - OS: Android 12
 - Browser 
   - Chrome 101.0.4951.61
   - Brave 1.38.113
   - Samsung 17.0.1.69

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
