### ISSUE TITLE
JetAppointment: Couldn't add a new appointment after submitting the form

### ISSUE THREAD

**Issue by arekuki** [CrocoBlock/suggestions#5352]
I did a Set Up in the plugin JetAppointments v.1.6.9 (Elementor v.3.6.5, Wordpress v.5.9.3)
Problems: 
- not selected "Provider" https://prnt.sc/AH_4VoVn8wcO
- also not selected "Services " in the "Static Page Booking Form" (jetEngine) https://prnt.sc/1J-DGfyNtCmb

I configured in JetAppointments and forms (jetEngine)
I filled out the form Appointment in the page.
Problems: 
- empty in Appointments (admin) after submit https://prnt.sc/Y0Gm5gEPhlME

Reinstalled the version Elementor v.3.5.6. 
I repeated set up and send. Also problems.

Can you fix it please

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
