### ISSUE TITLE
Column count not changing on Mobile/Tablet - Woo Categories Grid

### ISSUE THREAD

**Issue by HBiSoft** [CrocoBlock/suggestions#5359]
**Describe the bug**
I'm using the Woo Categories Grid.
The issue I have is that I want to set the column count to 2 when viewing on a mobile device and 4 columns when viewing on a desktop.

It works fine on a desktop, 4 columns are shown as expected. I switch to mobile and set the column count to 2, but it doesn't change anything. When I view it on a mobile device, only one column is shown.

**To Reproduce**
1. Edit site with "Elementor"
2. Add/edit "Woo Categories Grid"
3. In "General", set a column to mobile and select 2 columns
4. Update

**Expected behavior**
I want to set the column count to 2 when viewing on mobile, 3 on tablets, and 4 on a desktop.

**Screenshots**
![Screenshot 2022-05-16 at 19 07 15](https://user-images.githubusercontent.com/35602540/168646350-9acbd04c-3924-488e-8d7d-81e013f4666e.png)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
