### ISSUE TITLE
Ability to control Border and Border radius , in normal and hover mode / jet woobuilder product grid widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5361]
Now we can not control the Border and Border radius in normal and hover mode. This creates limitations in some cases.
Please move the Border and Border radius options to the Normal and Hover subset so that we can control these two values ​​in both normal and normal modes. https://prnt.sc/typ08HVo4lkw

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
