### ISSUE TITLE
Make separate filters work as union

### ISSUE THREAD

**Issue by felixthen00b** [CrocoBlock/suggestions#5367]
I have created several checkbox filters for a JetEngine Listing. Now when I use them one after another, it will only display the intersection of all of them. However, in my case, I want the results to show up as union.

On the website of one of my customers, they want people to find clubs and organizations in accordance to their interests. Now there are filters for sports categories, art categories, handiwork, music etc. The users usually have several interests, so when they choose sports and art categories, they want to see all results of both, not only the intersections (not many clubs do sports **and** art).

At the moment, there is no way to choose whether you want several filters to show intersection or union results - only intersection is possible. 

Thanks for looking into this!

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7592)
