### ISSUE TITLE
Booking Rules for Jet Booking

### ISSUE THREAD

**Issue by Ollie9T7** [CrocoBlock/suggestions#5370]
There needs to be a way to specify rules for the JetBooking calendar. EG: To only allow bookings on certain days for set durations such as: Only allow bookings on Monday for 4 nights and on Friday for 3 nights. 

This is a feature in many hotel/ apartment booking services to maximise booking potential and allow room changeovers on a single day rather than spaced randomly throughout the week.

This would help save money and offer a more efficient service to guests.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
