### ISSUE TITLE
Slider Widget motion effects

### ISSUE THREAD

**Issue by bombarda-rpd** [CrocoBlock/suggestions#5374]
It will be nice to have the possibility to set different text motion effects on the slider widget, instead of to all the content.
Right now this widget is pretty similar with the one that comes by default on elementor.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
