### ISSUE TITLE
Group days together for JetBooking

### ISSUE THREAD

**Issue by Ollie9T7** [CrocoBlock/suggestions#5376]
The ability to group days together so users can only make bookings that fit within the booking rules. IE: Grouping (Monday - Friday) and (Saturday - Sunday) so users can only book those two groups.

This is commonly used by hotels/ vacation rentals to maximise booking potential. For example, an available week in summer is very valuable to a hotel, they want to book out the whole week and not just 1 or 2 days. The way the plugin is currently setup, users can book random days and therefore may prevent other users booking longer stays.

A use-case is Centre Parcs [https://www.centerparcs.co.uk/](url) (Vacation Rental) in the UK. They only allow bookings to be made for 3 nights, 4 nights or 7 nights so that they can recover costs and allocate appropriate accommodation based on length of stay.

Another use-case is Canopy and Stars (vacation rental) in the UK. [https://www.canopyandstars.co.uk/britain/england/devon/pickwell-manor/hideaway-treehouse-at-pickwell-manor](url). They only allow bookings to be created on specific days and then the user must select the pre-determined duration of stay.

This would also be useful for other industries: Function room/ arena rental for weekdays or weekends only, not random days.

I think this feature should have been included as standard as it is more suited towards hotel/ rental bookings that follow a more structured approach to bookings. 

The current booking plugin is more tailored towards booking bike rental or car rental which requires less of a structured calendar.

Also the ability to add a minimum booking period. EG: users cannot make a booking if the booking period begins in less than 2 days from the current day. This is very useful for hotel/ vacation rental so the facility can prepare the accommodation before the guest arrives.

Motopress is a plugin that allows booking rules to be added, that may be worth looking into for inspiration.

**Screenshots from Centre Parcs website illustrating the calendar functionality**

<img width="2560" alt="Screenshot 2022-05-18 at 11 57 52" src="https://user-images.githubusercontent.com/53235713/169023597-808bf74a-960c-4345-9c7c-333bac80b212.png">
<img width="2560" alt="Screenshot 2022-05-18 at 11 59 16" src="https://user-images.githubusercontent.com/53235713/169023815-f2478cde-b829-45ae-b8e2-e85b004068ac.png">

**Screenshots from Canopy and Stars website illustrating the calendar functionality**

<img width="2560" alt="Screenshot 2022-05-18 at 12 04 17" src="https://user-images.githubusercontent.com/53235713/169024669-0683b879-1ec0-46e1-8130-c69f2efbb51f.png">

**Screenshots from Motopress Booking Rules illustrating the Booking Rules Settings**

<img width="2560" alt="Screenshot 2022-05-18 at 12 05 21" src="https://user-images.githubusercontent.com/53235713/169024905-c5631785-fa95-4049-95c3-485f638933be.png">

**Comment by Rikardo01** [comment]
How I see many users have this request in past year and nothing for me without this minimum stay , conect to booking com and multilanguage is nothing bcz will have only problems with clients and always say that will be and have priority my opinion that hi never will do this and is better to move to another plugin for this that have sorry for this but is true

**Comment by UraraReika** [comment]
> The ability to group days together so users can only make bookings that fit within the booking rules. IE: Grouping (Monday - Friday) and (Saturday - Sunday) so users can only book those two groups.

Unfortunately there is no options in daterange picker library that we use to achieve this results. You can make some kind of shotrtcuts but they work from current day. As a small woraround you can use Week-long booking with week day offset options - https://tppr.me/KIkZK9.

> This is commonly used by hotels/ vacation rentals to maximise booking potential. For example, an available week in summer is very valuable to a hotel, they want to book out the whole week and not just 1 or 2 days. The way the plugin is currently setup, users can book random days and therefore may prevent other users booking longer stays.

> Another use-case is Canopy and Stars (vacation rental) in the UK. [https://www.canopyandstars.co.uk/britain/england/devon/pickwell-manor/hideaway-treehouse-at-pickwell-manor](https://github.com/users/Crocoblock/projects/13/views/url). They only allow bookings to be created on specific days and then the user must select the pre-determined duration of stay.

In 2.8.0 version of the plugin new booking rules was released that looks like this - https://tppr.me/spQFuY, also this options can be setuped individually for separate apartments. So you can set check in and check out date and  users will should make only this kind of bookings.

> A use-case is Centre Parcs [https://www.centerparcs.co.uk/](https://github.com/users/Crocoblock/projects/13/views/url) (Vacation Rental) in the UK. They only allow bookings to be made for 3 nights, 4 nights or 7 nights so that they can recover costs and allocate appropriate accommodation based on length of stay.

You can also setup minimal days stay and this option even more specific because you can set it for individual seasons - https://tppr.me/JrMGSZ.

> This would also be useful for other industries: Function room/ arena rental for weekdays or weekends only, not random days.

Once again you can use custom schedule functionality to disables some days and leave only days thet you need. You can set in individually for each apartment - https://tppr.me/jZMVXF.

> Also the ability to add a minimum booking period. EG: users cannot make a booking if the booking period begins in less than 2 days from the current day. This is very useful for hotel/ vacation rental so the facility can prepare the accommodation before the guest arrives.

For this one you can use Starting day offset option that can be set globally, individually or per season - https://tppr.me/gEfBqC. 

You can also [contact](https://support.crocoblock.com/support/home/ ) our support team so they can help you if you have some additional questions.

Thank you!Thank you for your understanding.
