### ISSUE TITLE
Installation Wizard stuck

### ISSUE THREAD

**Issue by tomaski** [CrocoBlock/suggestions#5382]
fresh WP install with just Elementor, Elementor Pro and Crocoblock Wizard.

Chose the Car Dealer demo and installed all required and recommended plugins. Also opted to replace existing data, overwriting everything with demo content.

Installation stuck at 98% due to terms progress not being ticked.

Here a screenshot:

![firefox_2022-05-19_13-56-57](https://user-images.githubusercontent.com/24636007/169288061-06ba8d11-2377-477f-8667-68db93db4438.png)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
