### ISSUE TITLE
Automatic creation of cart and checkout page in jet woobuilder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5383]
In Jet woobuilder, when we design the cart and checkout page, we have to manually put the shortcode of these two pages on the page, and this is really annoying. But in elementor, all the steps are done automatically and we do not need to put the desired code shortcode on the page.
Therefore, it is great if after selecting the desired template for the cart and checkout page, the desired shortcodes are automatically applied. https://prnt.sc/7Zu_LMWfYF_2
This feature is really essential.thanks

**Comment by UraraReika** [comment]
Hello @Joliamendi !

After you install and setup WooCommerce plugins this pages automatically created with proper shortcodes. If not you can go to WooCommerce > Status, Tools tab and press this [button](https://tppr.me/mRgnv).
