### ISSUE TITLE
checkout page fields in jet woobuilder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5384]
For the first time, I used the elementor checkout widget, which has just been added to elementor. In this widget, when we change the style of the fields, all the fields change seamlessly. Even the country field is not a text field : https://prnt.sc/r7BwACwMZDKE

But unfortunately in jet woobuilder the situation is not good and when we change the style of the fields, only the style of the text fields change. Therefore, the country field, which is used as a list, does not change : https://prnt.sc/DdE6b7oJPE9a

Please fix this problem. So that if we change the style of the fields, all the fields will change seamlessly. Just like elementor. I hope it will be updated soon.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. Thank you!

**Comment by Joliamendi** [comment]
@UraraReika 
When I customize the billing firm checkout page, the country field (or any field that opens as a drop-down list) does not change, and the changes are only to text fields such as name, company name, and zip code. Similar fields apply. Isn't that so for you?

**Comment by Joliamendi** [comment]
https://prnt.sc/qdNCk9Avecv6

If you look closely at the screenshot above, list fields have less padding than text fields. Therefore, list fields are thinner. This is not the case in elementor, and all fields will be exactly the same. Is this issue solvable on your part?

**Comment by UraraReika** [comment]
> When I customize the billing firm checkout page, the country field (or any field that opens as a drop-down list) does not change, and the changes are only to text fields such as name, company name, and zip code. Similar fields apply. Isn't that so for you?

In my case everything is good, that is why i asked you to contact our support team.

> If you look closely at the screenshot above, list fields have less padding than text fields. Therefore, list fields are thinner. This is not the case in elementor, and all fields will be exactly the same. Is this issue solvable on your part?

We test this in several WordPress installation with different versions and i should say that Elementor Pro and JetWooBuilder templates have same behaviour. For now this is the most optimal way to handle this.
