### ISSUE TITLE
Box shadows for checkout fields

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5385]
Please add the box shadow option to the checkout fields. This feature is now available in the Element payment widget. https://prnt.sc/Ka8EuZHDCgr-
So please if you add this feature, please add the ability to customize the fields in normal and active mode. So that we can customize things like: border, border radious, background color, box shadow in both normal and active mode. This is really great.

**Comment by 79ho3ein** [comment]
Good idea👌🏻
