### ISSUE TITLE
Equal columns height NOT WORKING - JetEngine

### ISSUE THREAD

**Issue by brunacarolinar** [CrocoBlock/suggestions#5387]
In JetEngine, when we use a listing grid on a page and clicking on the "Equal columns height" option, it no longer works.

It used to work and the columns were the same size of the box, regardless of the text, currently this functionality that is very important is no longer working.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
