### ISSUE TITLE
JetEngine Bidding/Auction widget for CPTs & CCTs

### ISSUE THREAD

**Issue by aleebalari** [CrocoBlock/suggestions#5388]
Overview: With JetEngine we have the ability to create CPTs and CCTs like Ads, Products, or Services. With the various payment gateways, those items can be purchased. It would be a cool if users can **bid** on those ads, or products rather than paying a fixed cost.

Important features:
>>Auction duration
>>Reserved price
>>Bid History

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
