### ISSUE TITLE
JetEngine - Listing grid - More possibilities in column styles

### ISSUE THREAD

**Issue by otomasz** [CrocoBlock/suggestions#5389]
Hi,

I am writing with a request to introduce more custom column settings in the listing grid.
There is currently no choice.

![Zrzut ekranu 2022-05-20 o 09 46 30](https://user-images.githubusercontent.com/23310832/169480277-60a737ed-afb0-453b-95e9-2d2acaa623ca.png)

**It is very good if it was possible to set horizontal and vertical by%, px and em.**

**Comment by kaskad88** [comment]
Add for the next version 2.11.10
