### ISSUE TITLE
Images loop pagination

### ISSUE THREAD

**Issue by zimmiel** [Crocoblock/suggestions#539]
In Gallery Slider, in Product Single, I could not find how to loop through the switching of images.
It would be nice to do loop the pictures so that the prohibition icon does not appear.
https://www.loom.com/share/aa111fa8217245c69fef346256af9655

**Comment by UraraReika** [comment]
Done. Next release.

**Comment by zimmiel** [comment]
Hi @UraraReika 
Sorry for the late answer/question.
This closed. are you sure it's Done?
Because nothing has changed JetWooBuilder 1.6.3
here is a quick example https://www.loom.com/share/65cc705c99cc49778498a32ddeaaf77e
(sorry not prepared design)

**Comment by Floydtm** [comment]
@zimmiel, update JetProductGallery For Elementor plugin

**Comment by zimmiel** [comment]
@Floydtm I have JetProductGallery 1.1.3

**Comment by Floydtm** [comment]
@zimmiel, uncheck this options https://prnt.sc/sphfqz and check this https://prnt.sc/sphg8a let me know if this helped

**Comment by zimmiel** [comment]
@Floydtm thank!
Yeah, Infinite Loop. Not seen before.
Everything works great!
