### ISSUE TITLE
JetEngine - Listing Grid - Missing Spinner Feature In Infinite Scroll Load

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#5393]
I was initially trying to figure out what class was added to the infinite scroll which dims it as I wanted to change its colour.

While looking into this further, I found out that there is an unimplemented feature which exists in the lazy load, but not in the infinite scroll feature.

When you set a listing grid `Load more type` to `Infinite scroll`:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1038062/169648169-7d626bb8-f296-42d7-be00-b1c666c4e97a.png">

And then scroll on the front end, the listing grid just dims slightly and then loads the next items.

There is no spinner added to the bottom like this:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/1038062/169647913-e1d66cee-396f-4e20-8f77-6d8e2741581f.png">

From looking in `wp-content/plugins/jet-engine/assets/js/frontend.js` I found that the `lazyLoadListing` there are lines like this to show and hide a spinner:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/1038062/169648259-b9663e10-1baa-4578-99a1-893fa1b105cb.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1038062/169648267-15ea2ac1-1dd2-49aa-b365-9f33051a6791.png">

The `handleInfiniteScroll` function above it doesn't have this feature implemented though.

My client has had several people commenting that certain events are not shown on the website, but it seems that they are not understanding the infinite scroll is happening and they are scrolling away once they think they have reached the end of the page.

Adding this feature in was a simple process. 

Here is the complete `handleInfiniteScroll` function with the four new lines marked `// NEW`:

```javascript
		handleInfiniteScroll: function( event ) {
			var self  = this,
				page  = parseInt( self.container.data( 'page' ), 10 ),
				pages = parseInt( self.container.data( 'pages' ), 10 );

			if ( self.container.hasClass( 'jet-listing-not-found' ) ) {
				return;
			}

			if ( page === pages ) {
				return;
			}

			if ( JetEngine.lazyLoading ) {
				return;
			}

			if ( ! self.container.outerHeight() ) {
				return;
			}

			if ( $( window ).scrollTop() + $( window ).outerHeight() < self.container.offset().top + self.container.outerHeight() ) {
				return;
			}

			page++;
			JetEngine.lazyLoading = true;
			
			// NEW
			$wrapper = $(self.container).parents('.jet-listing-grid');
			// NEW
			$wrapper.addClass( 'jet-listing-grid-loading' );

			JetEngine.ajaxGetListing( {
				handler: 'listing_load_more',
				container: self.container,
				masonry: self.masonry,
				slider: self.slider,
				append: true,
				query: self.settings.query,
				widgetSettings: self.settings.widget_settings,
				page: page,
			}, function( response ) {
				JetEngine.lazyLoading = false;
				// NEW
				$wrapper.removeClass( 'jet-listing-grid-loading' );
				$( document ).trigger( 'jet-engine/listing-grid/after-load-more', [ self, response ] );
			}, function() {
				JetEngine.lazyLoading = false;
				// NEW
				$wrapper.removeClass( 'jet-listing-grid-loading' );
			} );

		},
```

Please can you consider adding this into the next release? 

At the moment my modifications are going to be lost when you release the next version of JetEngine, and this seems like a valuable UI improvement.

**Comment by Lonsdale201** [comment]
+1 :)

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by rtpHarry** [comment]
I've been checking for this every few weeks and waiting for to arrive and I've just realised that it is now implemented as an option.

If you have an existing website with a listing control, then you can now turn this on as an option:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1038062/184360903-22e604ad-153a-49f5-a01d-9fb36b803a17.png">
