### ISSUE TITLE
Automatic length for product title in product grid widget

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5398]
There is an annoying problem with the product grid widget. The titles of the products I sell on my website are usually long. On the desktop, I set the length of the product titles to 55 words and so far there is no problem. But if the user sees the website with the tablet or mobile, the product title is displayed in 3 or even 4 lines, and this completely disrupts the order of the page.
So it is possible to add a new feature, so that we can specify how many lines the product title will be displayed in the product grid widget?
For example, I want the product title to be displayed in only two lines. If the title was longer than 2 lines, it should be displayed as ... (three dots). Please add this feature soon. I really need it. Thanks a lot

**Comment by UraraReika** [comment]
I merged this issue with [#4948](https://github.com/Crocoblock/suggestions/issues/4948), which is on the same subject so we could deal with it more efficiently.
