### ISSUE TITLE
JetWoo Product layout - Add option to include filtering on tag

### ISSUE THREAD

**Issue by knireis** [CrocoBlock/suggestions#54]
At the moment is possible to filter on category. We need option to filter on category and/or tag.

**Comment by CrocoBlock** [comment]
It is possible to filter using tags as well as any other custom taxonomies, please, check this screenshot to find out how http://prntscr.com/mpre7e . 

Best regards from CrocoBlock team

**Comment by knireis** [comment]
You might have misunderstood my point. I'm not sure where you made the screenshot. I am talking about the product grid element. There is only option for Category, not Category and Tag (see the first screenshot).
In the second screenshot you see the native Elementor option, they have the option i described.
![schermafdruk van 2019-02-25 11-13-38](https://user-images.githubusercontent.com/2702064/53330482-dfd28b00-38ee-11e9-89e1-1478a7fbdd91.png)
![schermafdruk van 2019-02-25 11-12-29](https://user-images.githubusercontent.com/2702064/53330497-e6610280-38ee-11e9-8a76-dffc9ff88c0e.png)
