### ISSUE TITLE
Hide error messages in the Instagram widget for non-admins

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#5400]
**Please, describe the feature request, making it clear to understand.**

I would like to have a feature that would allow hiding the error message that the Instagram feed isn't working so that only admins can see it. 

**Add an example of where this feature is already implemented. **

For example, when my client changed their password it broke the connection to the Instagram feed widget and then displayed a really large message saying that the connection was lost. _Smash balloon Instagram feed_ has a feature to hide this message.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
