### ISSUE TITLE
The coupon is open by default - can be displayed next to the checkout form

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5401]
Please add a feature so that we can open the coupon form by default (Always be open).
Another thing that is very important is why do we have to have another format to place coupon form? Why can't we put the payment coupon next to checkout form?
If you look at the elementor pro checkout page, the payment coupon form is used next to the checkout form. On the other hand, this form is active by default and we do not need to click to open it.
Please resolve this so that we can place the coupon form on the checkout page in the desired location. The current situation is really limiting...

**Comment by Michaelgimii** [comment]
Having the coupon form enabled by default is great. But it would be great if enabling this feature was optional. In other words, we can determine whether the coupon form is open by default or works as usual.

**Comment by UraraReika** [comment]
Hello @Joliamendi, Thanks for the feedback.

Unfortunately, we do not plan to introduce such functionality into our plugin. And will stick to default Woocommerce functionality and layout without additional customization. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin or some adon.

Thank you for your understanding.
