### ISSUE TITLE
Optimization Jet Engine Listing Grid

### ISSUE THREAD

**Issue by The-Friendly-Ghost** [CrocoBlock/suggestions#5404]
When I try to optimize my website, I get a message from Lighthouse saying that the carousel dots of the Listing Grid Widget are not optimized. I tried to fix this optimization error myself, but it doesn't seem to be possible from within the widget.

![image](https://user-images.githubusercontent.com/89775408/169899837-afb07685-dc00-4fa8-81e6-802dd78b0e52.png)

**Comment by kaskad88** [comment]
Fix for the next version (2.11.10). Thanks for your report!

**Comment by edgBllw** [comment]
f
