### ISSUE TITLE
JetSmartFilters - Check Range Filter - Labels for Option List Entries

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#5405]
Would it be possible to add an individual label for each entry in the check range filter. For example, for ratings as in the following example, this possibility would be great.

![Original](https://user-images.githubusercontent.com/54399588/170041609-e9cd3d5c-842a-4b59-8899-5075feb02b41.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
