### ISSUE TITLE
Smartfilters , Is hierarchical then Exclude Or Include Items 

### ISSUE THREAD

**Issue by Qubadi** [CrocoBlock/suggestions#5409]
**Before adding a new feature request, please, make sure you’ve checked:**
Hi

I use Smartfilters from Crocoblocks, there are some things I think should be improved.

1. When you choose to create New Filter and when you try to select (SELECT) then select Is hierarchical then Exclude Or Include Items disappears.

It is not possible to choose a specific Taxonomy or Categories.

I really hope you add this so that we have the freedom to choose.

Thanks

**Comment by Floydtm** [comment]
At the moment this is not a bug. You must understand that some things work as they were intended and it is not always possible to make big changes. Thank you!
