### ISSUE TITLE
Custom svg for unit price - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5410]
**Please, describe the feature request, making it clear to understand.**

It would be great if you add custom Svg to the price unit. I saw this feature on [one of the websites](https://prnt.sc/6U0RSp2hMl22) and it was really great. Using this method, we can choose to display the default price unit, or display a custom unit. In fact, showing a custom price unit does not mean a new price unit. It is a unit of price with a different appearance. For example, we can display the dollar with a very nice svg, and that's great.

thank you

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. You can use this https://woocommerce.com/document/change-a-currency-symbol/ solution.

**Comment by 79ho3ein** [comment]
thank you
