### ISSUE TITLE
[JetWooBuilder] "A password will be sent to your email address." is not translated when setting a different locale.

### ISSUE THREAD

**Issue by antoinelbch** [CrocoBlock/suggestions#5416]
Plugin: JetWooBuilder
Widget: Registration Form
Issue: string `A password will be sent to your email address.` is not translated when setting a different locale.
Reason: incorrect string referenced in JetWooBuilder
JetWooBuilder file: /wp-content/plugins/jet-woo-builder/templates/widgets/myaccount/registration-form.php
Line: 40
`<p><?php esc_html_e( 'A password will be sent to your email address.', 'woocommerce' ); ?></p>`

I have checked. The 'woocommerce' domain does not contain the string 'A password will be sent to your email address.'. It does contain another string:
WooCommerce file:
/wp-content/plugins/woocommerce/templates/myaccount/form-login.php
Line: 99
`<p><?php esc_html_e( 'A link to set a new password will be sent to your email address.', 'woocommerce' ); ?></p>`
I believe `A link to set a new password will be sent to your email address.` is the string that should be referenced in registration-form.php inside JetWooBuilder.

**Comment by UraraReika** [comment]
Hello @antoinelubach !

This issue already fixed, please wait a bit for release.
