### ISSUE TITLE
Jet Filters - Ajax Array issue

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#542]
Currently, when you have smart filters configured on a single listing this is working well, The issue comes when you are running multiple listing grids on the same page. When a filter is applied via ajax, it will only search and return the first results as ajax is configure to only search for one ajax element.

the ajax side of smart filters, need to be able to search in an array and then return entires from an array.

This will allow for more complex and dynamic listing grids and all for nesting of listing grids.

**Comment by Floydtm** [comment]
@scubaninja1977, Hi! At the moment we are not
plan to do it. Perhaps in the future we will consider your request. Thank you for your request!

**Comment by scubaninja1977** [comment]
Hi Floydtm, just one quick thing I see that you are working on the ability to have listing grids inside other listing grid to create one listing grid, this is exactly the issue I have right now and what is failing with the filters, so the other update you are doing with this, will that work with filters?

**Comment by Floydtm** [comment]
Technically, it will be very difficult because it was not provided for. You need to redo your list, you need to get rid of nesting.

**Comment by scubaninja1977** [comment]
Getting rid of the nesting is not an option, and if you look at the facebook group, you will notice that more and more people are starting to do this exact thing as i am, and everyone that is doing the same nesting grid layout, IE a venue grid and then events underneath from another listing grid, the filters will not work.
