### ISSUE TITLE
More Table preset template please!

### ISSUE THREAD

**Issue by NeoAcla** [CrocoBlock/suggestions#5421]
Hello guys,

Just wondering if the dev's team are working on creating a template for table? Especially on product table with woocommerce.

I saw this another 3rd party plugin offering a crazy tables with so much templates and demos.
https://demo.wooproducttable.com/?_gl=1%2A14xa9fr%2A_ga%2AMTA4MzkyNzE4Ni4xNjUzNjMxMTIy%2A_ga_4768F4PBJ1%2AMTY1MzYzMTEyMi4xLjEuMTY1MzYzMjI5Mi4w&_ga=2.125304652.777439722.1653631123-1083927186.1653631122

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
