### ISSUE TITLE
A small bug about the checkout page > form fileds.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5422]
**Describe the bug**

hi
Not sure if this is a bug or not. I'm also not sure if this is a jet woo issue. But anyway ...

In the billing form & shipping form, the size of the list fields (such as country) is different from the other fields. There is no difference in the editor and everything is fine. But in the frontend, the country field (list fields) is a little thinner than the other fields.
Country field in the editor : https://prnt.sc/BY6ukZRlfYmB
Country field in the frontend : https://prnt.sc/hR2pAxs2ScJi

If you pay attention to the pictures above, the country field is different from other fields in terms of size, and this difference is noticeable only on the frontend.
To better understand this difference, I put the country field and a text field next to each other to better understand the difference.
> https://prnt.sc/14zzFmU5C06N

thank you

**Comment by UraraReika** [comment]
Please take a note at this issue https://github.com/Crocoblock/suggestions/issues/5384.

**Comment by 79ho3ein** [comment]
thank you . So, is it solvable in the future, or is it naturally so?

**Comment by 79ho3ein** [comment]
hi again @UraraReika 
After updating WordPress to version 6, the crocoblock icon in wordpress dashboard will not be displayed. https://prnt.sc/ytlxcWWGWzfx
