### ISSUE TITLE
auto Align for product grid price

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5428]
**Please, describe the feature request, making it clear to understand.**

hi

If you'm up to date, in elementor pro 3.7, the [auto Align](https://prnt.sc/A6SHjNr0gSM7) for read more feature has been added, which improves the UI in the posts widget.
So, if you add such a feature to the price of the Product grid widget, it would be great.
In the product grid widget, if the product is for sale, the order of displaying the price is not appropriate. As you can see in [this](https://prnt.sc/dNT1jm3FQtEx) picture, the price balance has deteriorated due to the previous price.

So, please add the **auto Align** feature to the price of the product grid widget. This feature keeps product prices always in line. If the description was not enough, please see the pictures below.

Before activating this option : https://prnt.sc/ct7VlMplILh3
After activating this option : https://prnt.sc/LnMJyNUCMC2y

thank you

**Comment by UraraReika** [comment]
I merged this issue with [#5364](https://github.com/Crocoblock/suggestions/issues/5364), which is on the same subject so we could deal with it more efficiently.
