### ISSUE TITLE
Solar (jalali) calendar for jet booking

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5431]
hi crocoblock team

In our country, because we have a different calendar, we can not use this plugin. So is it possible to add solar date support (jalali) to this plugin?
Now [this plugin](https://wordpress.org/plugins/wp-parsidate/) adds jalali calendar to wordpress, but only converts WordPress and WooCommerce calendars to jalali...

thank you

**Comment by UraraReika** [comment]
I merged this issue with [#4013](https://github.com/Crocoblock/suggestions/issues/4013), which is on the same subject so we could deal with it more efficiently.
