### ISSUE TITLE
elementor popup action for jet engine form

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5432]
I wanted the elementor pop-up to open after users submitted the form. Unfortunately, the jet engine does not currently support elementor pop up.
Please add elementor popup support. Many users do not want to use jet popup for any reason. Please make this choice available to your users.

**Comment by Floydtm** [comment]
https://crocoblock.com/freemium/tools/ https://prnt.sc/CJH9faLu-h3r
