### ISSUE TITLE
A better way to select a category in the Categories Grid widget

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5433]
This method is very bad for selecting categories. Because finding the desired category ID is very time consuming. https://prnt.sc/CqAZrtHbpvji
This method : https://prnt.sc/uFTyit5YpVFA        is much better and more principled than the current method for selecting the desired category. Correct this if possible

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
