### ISSUE TITLE
Smart Filter Targeting

### ISSUE THREAD

**Issue by CavenMzero** [CrocoBlock/suggestions#5435]
Hi, sorry if this has been requested, but couldn't find it the list.

For **JetSmartFilter** when selecting _"This filter for"_ dropdown.
The dropdown list is very limited.

With the current setup of filters, you can not have filters target different widgets.
From my experience and what I am struggling with right now, I need to have a filter for each product loop widget I have onb my page, however that does not work.

Furthermore, I would like it if you can the options for **Listing Grid** to the dropdown, additionally, an **option** one can **tick** to allow for **class targeting** system so that one target a specified List Grids for filtering.

This will allow for much more complex loops and filtering to be done.

**Comment by Floydtm** [comment]
Hi, at the moment we do not plan to extend filters to other widgets
