### ISSUE TITLE
Product Grid/List Template

### ISSUE THREAD

**Issue by CavenMzero** [CrocoBlock/suggestions#5436]
Hi,

So for this one, it rather straight forward.
Much like with Listing Grid, I would like it if we can select a custom template/listing for these widgets.

No offence to you guys, but super limiting style wise with what you currently have, I think you should rather cut down your Presets to like 5 and allow for custom templates instead. 
Shouldn't be that hard as you already have it setup for Listing Grid.

These two things coupled together will expand what is possible in Crocoblock by a ton and will stop people from having to find work around to not being able to run multiple listing grids and filters at the same time.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
Right now you can use the product loop or build a custom listing with jetengine plugin
