### ISSUE TITLE
Issues in Yoast header (crocoblock profile builder) 

### ISSUE THREAD

**Issue by jwamsterdam** [CrocoBlock/suggestions#5437]
Hi,

I am using crocoblock profile builder including Yoast SEO. 
In the header of my user account page, I see the following errors:

```
<link rel="canonical" href="https://www.domain.comdentist-firstname-lastname/singe-user/" />
--> after the domain name, a forward slash is missing

<meta property="og:url" content="https://www.domain.comdentist-firstname-lastname/singe-user/" />
--> Here as well, the forward slash is missing in the URL.
```

Thank you!

**Comment by kaskad88** [comment]
Hello @jwamsterdam 
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
