### ISSUE TITLE
Ability to order Listing Grid by Term menu_order

### ISSUE THREAD

**Issue by StevenVanWingerden** [CrocoBlock/suggestions#5438]
Please make an option to order listing grid items by the menu_order of the term:

![image](https://user-images.githubusercontent.com/39831934/171193585-56cb59e5-e2db-421f-9535-cf6d4a8406e0.png)

**Comment by kaskad88** [comment]
Order by `menu_order` in Term sQuery is not available https://developer.wordpress.org/reference/classes/wp_term_query/__construct/#parameters

If you meant `term_order` then use Query Builder https://tppr.me/9d2lb
