### ISSUE TITLE
Add filter by my location in JetSmartFilters

### ISSUE THREAD

**Issue by dbruddy** [CrocoBlock/suggestions#5439]
Hello! I am using JetSmartFilters in a listing website, but I think that is a good idea to add FILTER BY MY LOCATION FUNCTIONALITY in the plugin.

Something like this:
https://www.demoapus-wp1.com/findus/

You can see in the search form that you have an option that you can filter by your location
![Screen Shot 2022-05-31 at 10 12 35 AM](https://user-images.githubusercontent.com/38367035/171199210-4c11b58d-5ae7-42d8-9179-fd2e3ff5858d.png)

**Comment by dburke-ux** [comment]
+1 on this. The map listings are so great, and do most of what I need, but I've needed to use another plugin for a few clients that needed a "Find Near Me" button.

**Comment by dbruddy** [comment]
What other plugin did you used, bro?

**Comment by dburke-ux** [comment]
https://wordpress.org/plugins/wp-store-locator/

The featureset is decent, but you definitely need more front end skills to use it compared to JE Maps.

**Comment by dbruddy** [comment]
Thank you I will check it.

**Comment by simonclay** [comment]
+1 for this feature.

**Comment by dburke-ux** [comment]
@simonclay, I think JetEngine & SmartFilters have added a feature to satisfy this need. But, I haven't used it myself yet.

https://crocoblock.com/knowledge-base/articles/jetengine-setting-geosearch-based-on-user-geolocation/

**Comment by simonclay** [comment]
Thanks Dan, yes, I have just been talking to support about it. 

I need the visitor to be able to enter their town or postcode rather than have their location automatically detected.

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
