### ISSUE TITLE
JetTabs - Needs to be supported on Internet Explorer

### ISSUE THREAD

**Issue by alanalouise** [Crocoblock/suggestions#544]
While Internet Explorer should be deprecated by now, it's still got a % of browser usage stats, so our team must still support the browser. I have tried to use JetTabs on a few sites now, and have had to change to do incompatibility with Internet Explorer. The tabs will not change on this browser, and so, I can't use this element in its current state. Will have to wait under developers of this plugin add compatibility for IE browser.

**Comment by Floydtm** [comment]
@alanalouise, Hi! We try to adhere to all requirements from elementor https://docs.elementor.com/article/38-requirements Our team will check the plugin and release an update if necessary. Thanks you!
