### ISSUE TITLE
JetWooBuilder Single Product Template - Template Layout Settings is missed

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5442]
In JetWooBuilder Templates in a dashboard you can create a diffrent templates such as Shop page template/Arhive Template/Single product template etc. If a shop page template is chosen, there will be this option in elementor page settings, so you can choose a wordpress template for shop page, but in jetwoobuilder single product page template this setting is missed. Can it be resolved?
![screenshot-artelperelygina com-2022 06 02-04_01_09](https://user-images.githubusercontent.com/29761044/171525684-c9817fb8-ed69-4c25-b1a4-9021546a676b.png)

**Comment by UraraReika** [comment]
I merged this issue with [#4450](https://github.com/Crocoblock/suggestions/issues/4450), which is on the same subject so we could deal with it more efficiently.
