### ISSUE TITLE
Jetsmartfilters "Date Range"  start from today and cant select previous date?

### ISSUE THREAD

**Issue by yokirahmada** [CrocoBlock/suggestions#5445]
Hello,
Can jetsmartfilters "Date Range"  start from today and cant select previous date?
![inbound4537092628627328093](https://user-images.githubusercontent.com/91268568/171657583-1e1d56da-8b61-4447-8be9-993ead54073c.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
