### ISSUE TITLE
JetBooking Can book without selecting dates. Required checkbox not working.

### ISSUE THREAD

**Issue by majoross** [CrocoBlock/suggestions#5455]
It is also not working properly on the Telephone field, if it has a mask on it.

**Comment by UraraReika** [comment]
Hello @majoross !

Please use this [template](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to post correct bug report, so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests.

 Thank you for your understanding.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. If you still need help with this issue or have any other questions about the JetBooking plugin, please start a new thread.
