### ISSUE TITLE
JetSmartFilters Elasticsearch/ElasticPress compatibility (AJAX)

### ISSUE THREAD

**Issue by jimhuds** [CrocoBlock/suggestions#5463]
The AJAX product filters on my web store take quite a while to load products. It would be great to have the option to integrate Elasticsearch/ElasticPress.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
