### ISSUE TITLE
JetWooBuilder Custom Product Badges

### ISSUE THREAD

**Issue by martinjakse** [CrocoBlock/suggestions#5464]
Hello Oleksandr Rudyi "UraraReika",

Is it possible to access Product Custom Badges information in some way via the REST API. The problem I have is that products with all the data and custom metaboxes and taxonomies are synced across the POS platform. The only thing I can't sync is Product Custom Badges. I really ask for your help, Martin

**Comment by UraraReika** [comment]
Hello @martinjakse !

For current version of the plugins you can't do that. But next version will have some Rest API functionalities and if you specify what exact info you need to get we will try to implement it.

**Comment by UraraReika** [comment]
In the next release of the plugin you will be able to achieve your needs with the help of this endpoint `jwb-custom-product-badges-api/v1/badges-list/`
