### ISSUE TITLE
JetAuction: A completely new plugin

### ISSUE THREAD

**Issue by LTimerr** [CrocoBlock/suggestions#5465]
A completely new plugin where users can create ads where they can choose whether it is an auction or not. You can also set what the starting bid is and how long the period should be. 
Other users can then bid on the ad. 

I hope this is possible because the whole thing takes Crocoblock to another level.

Although Crocoblock is already at a very high level.

Kind regards!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
