### ISSUE TITLE
JetChat: A private messaging plugin

### ISSUE THREAD

**Issue by LTimerr** [CrocoBlock/suggestions#5466]
A user can send messages to another user, for example to agree on a meeting place and time. The whole plugin would be pretty helpful for that. Also, since there is no good PM plugin, I think. I think the whole thing would be worthwhile for the whole Crocoblock and JetPlugin concept.

Kind regards

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
