### ISSUE TITLE
Listing Grid ' More Options

### ISSUE THREAD

**Issue by maurocarreraok** [CrocoBlock/suggestions#5467]
<img width="305" alt="Screen Shot 2022-06-07 at 11 51 45" src="https://user-images.githubusercontent.com/68023943/172411686-b6a41f1e-b42a-476f-9e27-20e23998cd16.png">

So right now, we have only this options.

Will be great that instead of columns horizontal or vertical gap to have 
Margins instead.

Most of the time the Vertical gap, is added as well to the FIRST LINE (top) and this generate an space that is useless in pixel perfect designs.

I mean, we can add margin into the listing but this is not great experience.

**Comment by dburke-ux** [comment]
Yes, I've run into the same issues as you, as well as some addition UX concerns:

- As you mentioned, padding is added to the top which interferes with pixel-perfect
- Setting spacing in the listing grid widget means if you want to adjust spacing later, you need to edit every listing grid on every page
- Adding padding in the listing item template allows spacing to be controlled globally, but it adds space on left column, interfering with pixel-perfect

My solution has been: no margin or padding on listing item templates, no vertical/horizontal gap in Listing Grid widgets. Instead I use this CSS to set spacing globally:

```
/* Space Grid items */
.jet-listing-grid__item {
    padding: 0.5em;
}

/* Kill outer padding to keep grid aligned w/ page content */
.jet-listing-grid__items {
    margin: -0.5em; - /* negative of the value above for listing grid item padding */
    width: calc(100% + 1em); /* double the value above for listing grid item padding */
}
```

**Comment by maurocarreraok** [comment]
Thanks @dburke-ux ! I mean sure that i can use that snippet but is not ideal. I'm hoping that Croco solve this issue or add more flexible elements.

Another thing is creating "Layouts" using Listing Grids. Like 1 big post on the LEFT and 2 others on the right (same height as the left post) this is not possible using 1 listing...

I try to use Grid Builder, but is not useful because is not dynamic, is manual. But well... Hoping a solution for that as well.

**Comment by mateitudor** [comment]
I second this. It would be awesome to create a setting that adds a class that you can customize from css, or just have a layout builder <3

**Comment by MjHead** [comment]
We planned such features with one of upcoming major updates by adding separate widget. Probably 3.2.0 or 3.3.0
