### ISSUE TITLE
Changes made to JetEngine components (CPT, metaboxes) get reverted back to initial state

### ISSUE THREAD

**Issue by hoanghuy1903** [Crocoblock/suggestions#547]
I'm using JetEngine latest version 2.0.3 on my live site, having some custom post types and custom taxonomies and meta boxes imported from a staging site using JetEngine 1.x.

Everything seems to work fine but I notice that any changes i made to the Custom post types or Custom taxonomies will return to it initial state just like after importing, even newly created CPT or CT or meta boxes will not show up on their list after being saved (they still show on admin menu though).

Anyone else having the same problem? What is the potential reason of this bug/issue and how to fix it dev team?

**Comment by Floydtm** [comment]
@hoanghuy1903, Hi! Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help
