### ISSUE TITLE
JetWooBuilder widgets are missing in Single Product Template

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5472]
![screenshot-artelperelygina com-2022 06 08-17_19_17](https://user-images.githubusercontent.com/29761044/172640335-6adbf7ae-58c3-4fe5-b25e-1c97c42baf38.png)

In theme constructor then choosing Single Product Template JetWooBuilder widgets are missing. They works only in JetWooBuilder Template Builder templates.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by petrovui** [comment]
> We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

Solve this issue by installing back JetThemeCore. It resolves the problem. Maybe someone will find dat info usefull.
