### ISSUE TITLE
JetBooking: Advanced Prices should not be overridden by Weekend Prices

### ISSUE THREAD

**Issue by BlueteraLLC** [CrocoBlock/suggestions#5475]
It has come to my attention that in JetBooking, the Advanced Pricing settings are being overridden by the Weekend Prices.  In other words, I have set up multi-day discounts in Advanced Prices (7 days = $140 per night).  I have Weekend Rates set as Mon - Th $175 and Fr - Sun $200.  So if someone books a 2 night weekend, it would be $400.  If they book 7 nights it should be $980.  

This is a common setup for most hotel booking websites.  However, in JetBooking, if you set up Weekend Rates, the Advanced Rates do not apply at all.  It is like they do not exist.  So 7 days ends up being $1,300 (based one Weekend Rate settings) instead of $980 (Advanced Rate settings).

I just confirmed with Crocoblock that this current functionality is what they intended.  This really should be updated so that the Advanced Rates take priority over the Weekend Rates.  In most cases I have ever seen, someone booking for extended periods should be getting the best rates.

**Comment by UraraReika** [comment]
У каждого апартамента есть секция настройки цен бронирования https://tppr.me/i4j0G. В форме бронирования эти ценны что бы нормально отображались настройка такая https://tppr.me/NU8Si, в сайдбаре есть подробное описание что бы было понятней как эта опция работает https://tppr.me/VXigG. Суть проблемы в том что порядок применения цен был не совсем корректный. Пользователь достаточно подробно описал проблему у себя в ишью https://github.com/Crocoblock/suggestions/issues/5475. 

Правильный порядок применения должен быть такой:
- Самый низший приоритет о обычной цены https://tppr.me/i7GXN 
- Далее идет Weekend price https://tppr.me/i7GXN, поскольку он задаться для конкретных дней недели
- Следующим по приоритету идет обычно Price Rate https://tppr.me/MeG6M так как в нем задаться временной промежуток в виде количества дней.
- Высший приоритет у резонных цент, так как они самые конкретные и при их помощи можно задавать конкретные дни, как праздники.

**Тестирование:**
- У вас должна быть установка с настроены букингом и желательно что бы и формы сращу были настроены под продвинутые цены.
- Нужно настроить все возможные виды цен.
- Далее проверить правильность из применения, сохранен ли тот порядок что был описан выше
- Проверить разные комбинации наследования, по типу обычная цена рейт прайс, обычная цена викенд прайс, обычная викенд рейт прайсы, рейт прайсы и викенд, далее подмешать сезоную цену, и что бы рейт или викенд или того и того переходило диапазон сизон прайсов.
- Все должно работать правильно и не конфликтовать друг с другом, так же проверить на типе бронирования по типу пер дей и пер найт.

**Comment by UraraReika** [comment]
Complete in latest release
