### ISSUE TITLE
Change the priority between advanced rates and weekend prices

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#5481]
*Current problem*

I am using JetBooking. I have set up weekend rates and also the Advanced Rates for multiple-day discounts.  My expectation was that the Advanced Rates for multiple days should override the weekend rates, but that is not happening.  The weekend rates are overriding the Advanced Rates. 

*What I expect*

Currently, we cannot use both weekend rates and multi-day discounts, which is not ideal.  I would be glad if there was an ability to: 
a) enable both 
b) have the multi-day discounts take priority over weekend rates
c) have a setting that will change this priority

**Comment by UraraReika** [comment]
I merged this issue with [#5475](https://github.com/Crocoblock/suggestions/issues/5475), which is on the same subject so we could deal with it more efficiently.
