### ISSUE TITLE
bug in product list widget - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5483]
**Describe the bug**
hi
I have reported this bug before. You checked this and apparently there was no problem for you. But it is strange that I experience this bug in all circumstances. Even by disabling all plugins (except elementor, jet woobuilder, wooCommerce)
So I will show this bug again with a video, please check it if possible. In fact, the problem is that there is a lot of empty space next to the thumbnail : https://prnt.sc/glt7Zq8XkzEI

**To Reproduce**

https://user-images.githubusercontent.com/77163248/173055025-944c5599-32ea-4e97-85f3-fbf0c4b2f005.mp4

thank you

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue. https://prnt.sc/q1R3YgPuOzov

**Comment by 79ho3ein** [comment]
thank you @Floydtm
