### ISSUE TITLE
Ajax add-to-cart for Listing Grids

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#5485]
I have the "Enable AJAX add to cart buttons on archives" option enabled in Woocommerce.

Then I created a listing using JetEngine for products, and then customized the Shop and Product Categories page using Elementor, and used Listing Grid to display the Archive of products.

Now, when I visit the /shop page or any product category page and I add a product to the cart, it still redirects to the product page, instead of adding it to the cart via Ajax and opening the Elementor's cart widget's panel that we've added to the header.

Upon my request from the developers, they mentioned that Ajax currently only works IF we also use JetWooBuilder, but we don't need that plugin and due to the scale of the project, we need to avoid adding new plugins as much as possible, especially when we don't need any of their features. Having that complete/big plugin (JetWooBuilder) added just to get the Ajax work (which is a built-in feature of Woocommerce, and we expect any 3rd party plugin to support the core features at the very least), doesn't really feel right.

I hope you have a hotfix for this.

Thanks

**Comment by PPharma** [comment]
Please add this.

**Comment by simonvanoordt** [comment]
This is essential for any JetEngine product listing

**Comment by lifeact** [comment]
+1

**Comment by Michaelgimii** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello @Dadparvar !

Please specify, what exact widget you use to add products to cart in Listing?

**Comment by hamed-azimi** [comment]
Hi @UraraReika 

I'm using the default add-to-cart widget included in Elementor itself:
https://ibb.co/xhM6TKc
https://ibb.co/31H1Dn3

**Comment by lifeact** [comment]
Hi @Dadparvar   Elementor PRO is bloated.... + not FREE.... Why use this trash when there are powerful croco plugins?

**Comment by hamed-azimi** [comment]
@lifeact I found that so called trash to be a better fit for my needs atm.

**Comment by lifeact** [comment]
@Dadparvar everyone chooses their own way
Good luck bro

**Comment by UraraReika** [comment]
> Hi @UraraReika
> 
> I'm using the default add-to-cart widget included in Elementor itself: https://ibb.co/xhM6TKc https://ibb.co/31H1Dn3

Okey, i got you and need to tell you something about this widget. Basically this widget made for single product page and if you take a closer look on DOM structure of this element you can clearly see this https://tppr.me/zMxbj. But the listing item gives you an opportunity to use it in listings grid widget and doesn't broke any functionalities. That is why `Enable AJAX add to cart buttons on archives` option enabled in WooCommerce not working in this case.

Depending on what theme you use there can be additional option similar to [this](https://tppr.me/pzv7F) that JetWooBuilder has so it can helps you.

In other case please track the JetEngine improvements when we implement such functionality to the core or Dev Tools solution.

**Comment by tizum** [comment]
+1 Please add this, Ajax add to cart work with listing grid only the page type is archive, i want to add listing grid for another pages

**Comment by PPharma** [comment]
Yes, this would be great to have. We don't use a theme. Just plain Elementor and JetEngine.

**Comment by hamed-azimi** [comment]
@UraraReika Thanks

But here is the thing: JetEngine offers Listing. What's the purpose of Listing? To create those Grid Items. What do you put on the grid item when it is for a product? Obviously, add-to-cart is a MUST.

JetEngine doesn't include a dedicated add-to-cart widget, nor does it extend the exiting widget to support the archive pages. We are forced to use a complete large plugin [JetWooBuilder] just to get one tiny little feature [ajax add to cart]

My suggestion is, either to extend the Elementor's add-to-cart to support it or, simply add the widget you already created for JetWooBuilder into the JetEngine so that JetEngine gets its own fully functioning add-to-cart that also offers a quantity field and also supports the ajax functionality.

As I said before, the reason we don't use JetWooBuilder is not to save money. We already have a Lifetime All-Inclusive license. We literally don't need 99.9% of that plugin, and our project is on large scale and we need to do anything we can do to avoid adding unnecessary stuff. I hope you understand the situation and get back to us with good news.

Thanks

**Comment by tizum** [comment]
@UraraReika 

This option could be added to the Dynamic link when Woocommerce is installed, so we could have options to dynamically choose the product id, activate quantity of items, add to cart with ajax, and make a good customization in the button and quantity field, this functionality would be great for JetEngine just without having to use JetWooBuilder.

Please think about it, thank you!

**Comment by dyonatandias** [comment]
I stopped using it because I don't have this feature. what Anderson mentioned makes perfect sense. I hope to have these features soon so I can use them.

**Comment by hamed-azimi** [comment]
Andrey Shevchenko posted a solution on my FB post for this: 
https://github.com/MjHead/jet-woo-qty-for-add-to-cart?fbclid=IwAR0zbBT5DKELai7i6CQ4VMUgxSMpskgjO94jZEQ3Yl7h7rXQRlL_A-gYQJk

But you know what? now that they made this shortcode, they can quickly finish it as a complete add-to-cart widget and add it as a new feature to the upcoming JetEngine update. They've already done this for JetWooBuilder, so they are not going to develop something that has never been done before, and they have all the rights to their codes I assume, so they can code-reuse.

**Comment by PPharma** [comment]
Please include this into JetEngine so it works as a core JetEngine feature.

**Comment by UraraReika** [comment]
The solution of this was added with last plugin release and you free to try it. But this functionality still need some final touches. So please stay tuned with this issue https://github.com/Crocoblock/suggestions/issues/5693.

**Comment by PPharma** [comment]
Related issue:
https://github.com/Crocoblock/suggestions/issues/5693
