### ISSUE TITLE
Change in CCT fields with "has single page" option enabled doesn't update related page/post

### ISSUE THREAD

**Issue by zahnd** [CrocoBlock/suggestions#5489]
**Describe the bug**
Changing the title field of a CCT with the option "has single page" enabled, doesn't update the title field of the related/connected post/page. It seems that after the initial creation of the connected post, the values of the post won't be updated if the CCT is changed afterwards.

**To Reproduce**
1. Create a CCT with the option "has single page" and link the corresponding fields to title and content
2. Check if the post was successfully created after adding a CCT
3. Change either the value of the connected title or content field in the CCT
4. Check if the values of the linked post are updated. They are not.

**Expected behavior**
Changing the values of a CCT with option "has single page" enabled should always update the linked title and content field of the linked post.

**Screenshots**
https://monosnap.com/file/6MN44N8o6LIGRrdCfHuyOuDWsoTNAz
https://monosnap.com/file/3CjHXWhofSUNYgxJWiHyhIAq26c7ki
https://monosnap.com/file/mO9wQXnKFFdsFAirypNvkln4HowJOq

**Additional context**
JetEngine version: 2.11.10
WordPress version: 6.0

**Comment by basement440** [comment]
Is this a bug that is going to be "fixed" or is the "has single page" option working as it should? I'm trying to figure out if a CCT is the right solution for a project.
