### ISSUE TITLE
Submit the form by hitting Enter key on keyboard when the form uses Ajax

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#5490]
Upon my communication with the agents/devs in Crocoblock, this was what I received:

----------
In JetFormsBuilder, Enter key won't work for forms with AJAX Submit type, because the action button has attribute type="button", but with "reload page" it has the type="submit". Button won't submit the form on its own. It is a simple button that is used to perform some operations by using javascript.
----------

It would be very useful to extend this to make the forms with Ajax to submit the form on Enter pressed.

**Comment by PPharma** [comment]
+1

**Comment by girafffee** [comment]
Fixed in 2.1.0
