### ISSUE TITLE
Ability to display search history in jet search plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5496]
**Please, describe the feature request, making it clear to understand.**

It would be great if website users could see their search history. This feature is implemented in some websites and is very useful. With this feature, the user can see 5 (or X) of their recent searches, and if they want to go back to their previous search, they can do so quickly.

Something exactly like the one I simulated in Photoshop : https://prnt.sc/2iRwOuTjRc8y

The only feature that this feature requires is the ability to specify the number of user histories. For example, I want users to be able to see only their last 5 searches.

**Comment by mehdimoradi1500** [comment]
Great idea like always 👍👍

**Comment by Michaelgimii** [comment]
+1

**Comment by Joliamendi** [comment]
+1
Great feature

**Comment by Crocoblock** [comment]
was added and released in 3.4.0
