### ISSUE TITLE
 Connect the Youtube channel to the Video Playlist widget (Jet Blog)

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#55]
Good afternoon, I would like to in the Jet Blog plugin, the Video Playlist widget, directly output the Youtube channel, ideally generally by playlists. It would be great for my clients who have a video on the Youtube channel that appears weekly and this functionality would save their time very much.

/*Оригинал на русском*/
Добрый день, хотелось бы в плагине Jet Blog, виджет Video Playlist, напрямую выводить канал Youtube, в идеале вообще по плейлистам. Это было бы здорово для моих клиентов, у которых видео на Youtube канале появляется еженедельно и данный функционал очень бы с экономил их время.

**Comment by oceandiveloper** [comment]
+1

**Comment by kaskad88** [comment]
Added for next version (v2.1.17).
Thanks for your report!
