### ISSUE TITLE
Ability to display products in several columns - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5500]
**Please, describe the feature request, making it clear to understand.**

hi

If possible, please add this feature to the product network widget so that we can display products in multiple columns.
Exactly like this : https://prnt.sc/NeYVei9qQJOC

It would also be great if add the ability to activate Carousel (like the product grid widget)

https://user-images.githubusercontent.com/77163248/173613745-8378ecaa-1997-468d-a825-0fa7a5b5859b.mp4

thank you

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/4738, which is on the same subject so we could deal with it more efficiently.
