### ISSUE TITLE
Advanced Woo Labels

### ISSUE THREAD

**Issue by MichaelaKubasova** [CrocoBlock/suggestions#5503]
Hi, its possible to create a advance woo labels for products? Because crocoblock product grid doesnt work with 
Advanced Woo Labels – Product Labels for WooCommerce by ILLID

**Comment by UraraReika** [comment]
Hello @MikaelaDeCub !

For now we don't have our own solution with such functionality. But if you okey with Advanced Woo Labels – Product Labels for WooCommerce by ILLID and you want to use it with our widgets then please contact our support team where you can provide your credits and we will help to integrate third party plugin to our environment.

Thank you!

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. If you still need help with this issue or have any other questions about the JetWooBuilder plugin, please start a new thread.
