### ISSUE TITLE
send jetappointment emails after checkout process

### ISSUE THREAD

**Issue by leonelpaez** [CrocoBlock/suggestions#5507]
Jet appointment just send confirmation (custom) email after click the submit the final button of the form, but if you have woocommerce integration it is suppose that the confirmation email have to be sent after the payment process, otherwise the user will recive the confirmation email without finis the entire process (the mos important step, the payment) 
This ir a reallllly needed feature guys!

thanks

**Comment by maliktanveerdhool** [comment]
You can solve this problem by using workflow in jet appointment settings. @leonelpaez
