### ISSUE TITLE
jetformbuilder submit button bug 🪲

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5511]
jetformbuilder lost the ability to do fullwidth on submit button

 **jetformbuilder 2.0.6**

![jetformbuilder bug1](https://user-images.githubusercontent.com/82481592/173902807-1bf6497c-c945-4c7f-9f31-2c0ff8ce35ba.gif)

**jetengine 2.11.10**

![jetengine](https://user-images.githubusercontent.com/82481592/173902824-59dae77f-d63e-4ba7-877b-f35615db03c7.gif)

**Comment by girafffee** [comment]
Fixed, check in 2.1.0 version
