### ISSUE TITLE
Advanced display of products based on users' mobile models (jet woobuilder)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5512]
**Please, describe the feature request, making it clear to understand.**

Many users are jet woobuilders who sell mobile accessories on their website. Like myself.
On one of the websites, I came across a great idea that was very interesting to me. This feature can only be used by those who sell mobile accessories on their website ...

**This feature works in such a way that when you enter the website with your mobile, your mobile model is identified by JavaScript code and as a result, all the accessories are displayed according to your mobile model. this is fabulous.**
If you agree with this feature, please add it to the product grid widget as a query.

**Comment by 79ho3ein** [comment]
This is a really great idea. But can it be implemented in jet woobuilder? How does this feature display products according to the user's phone? Does each mobile model have to be categorized separately, or does it operate based on product titles?

**Comment by Michaelgimii** [comment]
hi @UraraReika , Is it known when the new jet woobuilder update will be released? Now more than 3 months have passed since the last version...
Will this be an update with big changes?

**Comment by UraraReika** [comment]
Hello @Michaelgimii. Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But we've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/

Thank you for your understanding.
