### ISSUE TITLE
JetEngine Glossary extension

### ISSUE THREAD

**Issue by LTimerr** [CrocoBlock/suggestions#5515]
Hello, I use a lot of glossaries, and would be very happy for a more orderly listing if it were possible if you could just move the glossaries up or down like Meta Fields.
![Screenshot_13](https://user-images.githubusercontent.com/93724776/174054261-65d38f7c-fd8b-4335-9963-5fc8eb53f8ca.png)

**Comment by MjHead** [comment]
Added with 3.0.5 update
