### ISSUE TITLE
new order for sorting filter widget (most visited)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5516]
**Please, describe the feature request, making it clear to understand.**

hi @Floydtm , The jet smart filters plugin is incredibly powerful. But a new option would be great if it was added.
On some websites, we can sort the products by the number of hits. For example, by adding this feature, users can filter products based on the most visited. Of course in the sort widget.
Please add a new order (most visited) to the sorting filter widget : https://prnt.sc/qDUlJM1vcWef 
Also please add the ability to insert a custom icon to this widget : https://prnt.sc/lOEnhiz-7LV0
thanks

**Comment by Floydtm** [comment]
I understand that this is important to you. However, this is not so simple. To implement your request, we need a mechanism that will collect information about the posts viewed. We don't plan to do that right now. Perhaps we will come back to this. Thank you!
