### ISSUE TITLE
Smart Filters + JetWooBuilder => Display child categories of a specific category

### ISSUE THREAD

**Issue by Basilou38** [CrocoBlock/suggestions#5517]
I am currently developing an e-commerce site for a client, he sells trailers, I have created a "trailers" category with associated child categories, it works well with your filter module, but my client also wants to sell trailer accessories. independently, i.e. in a page that is not part of the general "shop" page of wocommerce, this causes me problems because if I create a "Categories Grid" module and only displays the desired category and I click on a category, I am redirected to the general shop page of woocommerce with the filter activated .

I have a custom template for woocommerce store page (I'm using JetWooBuilder + JetSmartFilters ), I can't create another page with child categories of a specific parent category (ID?), I manage to display categories, but when I click on a category, I get redirected to the woocommerce store page with the active filter (JetWooBuilder template).

here is a video capture to better understand the problem :
https://www.loom.com/share/439eb7ebdcac45ea9dd121b9deb0349e 

Possible to do that ? Here are the steps I'd like to create :
1- Create a page that is not part of the woocommerce store page (I use elementor => easy)
2 - In this page, I only display child categories linked to a specific parent category (ID?)
3 - If I click on a child category, a page loads and displays all the products associated with this child category => On this page, we can choose the attributes associated with this child category, I suppose by using the "Filter of checkboxes"?
4- On this page, if I click on a child category product, the page loads the single product => we can add to the basket (I have a custom template for single products)
In order to fully understand what I want to create, here are the user steps that I would like to do (it looks like this site which is not a wordpress => (https://www.knott-remorque-boutique.fr/ersatzteile.html )

If it is possible, can you show me with a video capture? Or make me a sample page on my site? (sorry for the language, I use google translate 😉 )

**Comment by Floydtm** [comment]
Perhaps I do not quite understand you correctly, but you can make any template and assign it to the desired product category. check out this tutorial https://crocoblock.com/knowledge-base/articles/jetwoobuilder-how-to-set-up-a-custom-product-taxonomy-template/ let me to know if it will help you

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.
