### ISSUE TITLE
Calculated duration of the slot in JetAppointments

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#5521]
**Please, describe the feature request, making it clear to understand.**

Make the default slots or Time Picker pre-selected automatically, based on the Calculated field value or a Number field value. 

**Add an example of where this feature is already implemented.**

I'm building a website for a pressure cleaning company. It charges per m2 cleaned. I'm looking to use JetAppointment for scheduling cleaning jobs, but the appointment duration must depend on the meters that customer specifies. Having the customer manually calculate and fill the slots is an extra barrier that will cost leads.
Example: I would like to allow a calculated field to automatically select the number of necessary time slots-> so as opposed to the customer clicking and selecting one time slot tile, the amount of tiles selected will equal X (being the number of slots needed to clean the selected amount of m2's).

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
