### ISSUE TITLE
JetEngine Feature Request for Dynamic Image

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#5522]
Hi guys, I had this idea saved to request here, after the last update that brought news to Dynamic Image Widget I can't leave it in the drawer anymore, let's go!

Guys, currently the dynamic image element DOM has an attribute called loading="lazy"

![image](https://user-images.githubusercontent.com/6773491/174308728-1d0e4c6e-63ed-482f-a114-95c23e25ecd4.png)

I believe that this makes the image load with lazy loading, because I end up noticing it sometimes when I enter the page, especially if I use the dynamic image for a banner, or a banner list with listing grid, the image name appears quickly and then the image appears.

I would like to request that an option be added to enable and disable the lazy attribute in the element.

And also suggest a novelty for JetEngine to get ahead in the matter of optimization, which is to add a class to the image, so we can exclude it from the lazy loading of WP Rocket images in a faster and more dynamic way for our listings.

I'll leave the documentation I found on WP-Rocket in the ways that are possible to do.

https://docs.wp-rocket.me/article/15-disable-lazy-load-on-specific-images

**So there are these two requests:**

1 - Add Option to disable/enable Lazy attribute
2 - Add a custom Class directly to the image class, to facilitate WP Rocket optimization, and also to use it in another way if other users want it.

this happens when I test in gtmetrix, it accuses the banner that I have 1920x560 at the entrance of the site in the form of a slider made with dynamic image taking the information from an options page repeater and rendering in a listing grid with a slider on the homepage, it accuses directly the dynamic image element

![image](https://user-images.githubusercontent.com/6773491/174311536-6c651078-d453-4935-b2ee-4e307545c17e.png)

**Comment by Lonsdale201** [comment]
+1 :)

**Comment by 79ho3ein** [comment]
+1

**Comment by marreiradigital** [comment]
+1

**Comment by dyonatandias** [comment]
+1

**Comment by DaviAppelDuarte** [comment]
+1

**Comment by dantetesta** [comment]
2 Possíveis Soluções

**1 - Remover de todas as paginas o atributo:**
```
<?php
function remove_lazy_load_attributes($content) {
    return preg_replace('/(<img[^>]+) loading="lazy"/', '$1', $content);
}
add_filter('the_content', 'remove_lazy_load_attributes');

?>
```


**2 - Remover só da página HOME:**
```
function remove_lazy_load_attributes($html) {
    if (is_home()) {
        return preg_replace('/(<img[^>]+) loading="lazy"/', '$1', $html);
    } else {
        return $html;
    }
}
add_filter('the_content', 'remove_lazy_load_attributes');
```

**Comment by tizum** [comment]
It didn't work cool, because it removes the lazy from other images that I don't want to disable.

> 2 Possíveis Soluções
> 
> **1 - Remover de todas as paginas o atributo:**
> 
> ```
> <?php
> function remove_lazy_load_attributes($content) {
>     return preg_replace('/(<img[^>]+) loading="lazy"/', '$1', $content);
> }
> add_filter('the_content', 'remove_lazy_load_attributes');
> 
> ?>
> ```
> 
> **2 - Remover só da página HOME:**
> 
> ```
> function remove_lazy_load_attributes($html) {
>     if (is_home()) {
>         return preg_replace('/(<img[^>]+) loading="lazy"/', '$1', $html);
>     } else {
>         return $html;
>     }
> }
> add_filter('the_content', 'remove_lazy_load_attributes');
> ```

**Comment by dyonatandias** [comment]
+1

**Comment by tizum** [comment]
@kaskad88 I would like to know if these options are being analyzed by the team?

**Comment by kaskad88** [comment]
@tizum Yes, we plan to add this feature in upcoming versions

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.4
