### ISSUE TITLE
JetMenu Caching - Cloudflare & VUE

### ISSUE THREAD

**Issue by Bayron2304** [CrocoBlock/suggestions#5523]
So this is the issue I'm having; When I purge all my caches (Cloudflare, Varnish by Cloudways, Breeze caching plugin) and reload my homepage on desktop, that is the version of JetMenu that all my caches use. Meaning my mobile menu's layout isn't how it should be. Vice versa, if I purge all my caches and visit a page of my website on mobile first then JetMenu displays the mobile menu also on desktop because of my caches caching the mobile version.

How can I solve this? It just seems it's something to do with VUE because of the difference in rendering desktop vs. mobile. Excluding .JS files that come with JetMenu doesn't solve the problem either.

**Comment by Floydtm** [comment]
We have studied your request and it seems that this is not a bug on our part. You need to set up caching properly. At the moment, I can offer you the [WP Fastest Cache plugin](https://wordpress.org/plugins/wp-fastest-cache/) which has the necessary [settings](https://www.wpfastestcache.com/premium/mobile-cache/)
