### ISSUE TITLE
border radius control for Before and after displaying search results - jet search

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5526]
**Please, describe the feature request, making it clear to understand.**

hi crocoblock team!

A new and interesting design for this widget can be great ...
[This is](https://prnt.sc/SSZK9HSOtRTi) how my search box is designed, and [it changes](https://prnt.sc/Q1cPrX0WOk6y) when search results appear. (Please note the search box border radius and search results).
**In fact, my question is, is possible you add a feature, so that we can control border radius before and after the search result is displayed?** In the two images, please see the border radius before and after the search results open :

Before displaying the results (normal mode) : https://prnt.sc/CWqfW_mwsCVZ
after displaying the results : https://prnt.sc/4U_BmsJTthHb

**Another example**
Before displaying the results (normal mode) : https://prnt.sc/guHQ6bePFtvH
after displaying the results : https://prnt.sc/QD2HoFajZXL2

In fact, this feature works in a way that merges the search box and search result when search results are displayed. **To add this feature, just add the ability to control the border radius, before and after displaying search results.**

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
