### ISSUE TITLE
JetWooBuilder Load More affect Products Result Count 

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5527]
There is a widget Products Result Count and then the Load More button is pushed it's not affect Products Result Count. So if on Products Archive page showing 1-15 products and Load More is pushed it's still showing 1-15 numbers but there is already more products on page.

**Comment by UraraReika** [comment]
Hello @s5t5n !

Please take a closer look on this issue https://github.com/Crocoblock/suggestions/issues/2592.
