### ISSUE TITLE
Poll & Vote with statistics and CSS

### ISSUE THREAD

**Issue by glorpyz** [CrocoBlock/suggestions#5529]
Poll function would be great!   Displayed with shortcode.
Not so many nice-looking out there and WPForm costs to much for just getting their Poll.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
