### ISSUE TITLE
Jet Woo builder - custom shop templates based on taxonomy 

### ISSUE THREAD

**Issue by andrewkirkcaldy** [Crocoblock/suggestions#553]
It would be great to have the functionality to create custom shop templates based on taxonomy. 

Certain categories need different layouts and content as we typically use them for landing pages. 

Having to create static or bespoke coded pages negates the need for Woo builder. 

Would be great to see.

**Comment by UraraReika** [comment]
Next release.

**Comment by andrewkirkcaldy** [comment]
great news. Look forward to seeing this in the next release
