### ISSUE TITLE
JetFormBuilder Select Autocomplete doesn't work in Elementor Popup

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#5530]
I created a form using JetFormBuilder and in some of the dropdowns, I enabled the "Use Autocomplete" feature which is added by "JetFormBuilder Select Autocomplete".

It works fine when we use the form in pages, but if we use the form in an Elementor Popup, it won't open the dropdowns that have "Use Autocomplete" but other dropdowns that don't use this feature open without an issue.

I hope you have a hotfix for this as we are using forms on various Elementor Popups and usually our forms have multiple dropdowns that some of them have "Use Autocomplete" enabled due to having many options.

Thanks

**Comment by girafffee** [comment]
Please try with the current version of Select Autocomplete
