### ISSUE TITLE
jet woobuilder checkout fields

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5538]
**Please, describe the feature request, making it clear to understand.**

hello

In jet woobuilder payment fields, if we fill in the field using the words we [used before](https://prnt.sc/9iGSImhm3-3B), the background color of the field will [change](https://prnt.sc/DJF7HvjzK-pL) and this color can not be controlled. 
This background color change occurs only in text fields such as name, company name, and so on.

Please add a new feature to control this color if possible. (Maybe this request is similar to this : # 3793)

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

This is how your browser client handle autofill functionality. If you will use different browser from Chrome then you will face different behaviour. Although we will not add controls to our plugin for styling this feature.

Thank you for your understanding.

**Comment by 79ho3ein** [comment]
ok, thank you @UraraReika
