### ISSUE TITLE
JetEngine - New Loading Load more Indicator+Text not showing on iPhone

### ISSUE THREAD

**Issue by secondsky** [CrocoBlock/suggestions#5539]
**Describe the bug**
On Desktop the Loading Indicator for Load more which was introduced with JetEngine 2.11.11 is visible and working.
On iOS it doesnt show up at all.

**Desktop (please complete the following information):**
iOS 15.5

**Smartphone (please complete the following information):**
iPhone 13 Pro

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
