### ISSUE TITLE
Letting not Admin users to add Gallery Images without entering Elementor backend

### ISSUE THREAD

**Issue by limitcracker** [Crocoblock/suggestions#554]
I think it would be very beneficial to have a way for a simple user to add images to a gallery without going inside Elementor and tweaking Crocoblock around.

I am imagining something like a connected folder that user adds images and it updates on the frontend automatically. **Something like the Smart Posts add on of Crocoblock, but for the Image Gallery addon.**

Br,
John

**Comment by Floydtm** [comment]
@limitcracker, Hello! Could you describe your request in more detail? And if you can give an example of how it works
