### ISSUE TITLE
Listing grid - Create a grid with option not based on columns so we can stack items

### ISSUE THREAD

**Issue by miguel-cravidao** [CrocoBlock/suggestions#5543]
Hello,

I don't know if this is possible to achieve in another way but sometimes i need to render items in a way that i can't define a number columns because all the items need to be inserted from left to right, inlined.

![image](https://user-images.githubusercontent.com/8440771/174786559-a13df697-5bb5-4cd4-bd07-8309ea6df9be.png)

On this image, i have a room with comodities, represented with icons.
I just want them to render from left to right, inlined and stacked.

The comodities are dynamic so i can have none or 20.
Having to use the grid with pre-defined columns I get lots of problems in terms of design as you can imagine.

If i want the icons to be close i have to use 10 columns, but if i need bigger precision i need more columns and that option is not available (but also doesn't make sense). Now imagine setting this up for some breakpoints.

See the example below, lots of space between items because the 10 columns are now inside a larger container.

![image](https://user-images.githubusercontent.com/8440771/174787205-8040ea23-475e-4ff3-aac9-cd425ce9f1c3.png)

That's why we need a solution not based on columns also.

**Comment by Floydtm** [comment]
We have reviewed your request and it appears that it is not related to improving the plugin or that it is a bug.

**Comment by loucasl** [comment]
Could you just add each icon as a separate widget, all of which are inline and have padding around them? Then you never have to worry about adding columns

You would just need to assign dynamic conditions to each one so that they show / hide depending on if the room has them

**Comment by miguel-cravidao** [comment]
> Could you just add each icon as a separate widget, all of which are inline and have padding around them? Then you never have to worry about adding columns
> 
> You would just need to assign dynamic conditions to each one so that they show / hide depending on if the room has them

Hello @loucasl, thanks for your reply.

That's a workaround but its not dynamic. If the client adds new comodities (icons) we would have to edit the interface each time.

Thanks for your time!

**Comment by miguel-cravidao** [comment]
> We have reviewed your request and it appears that it is not related to improving the plugin or that it is a bug.

Hello @Floydtm, thanks for your reply.

Can you please explain me how this works? I was told by the Crocoblock chat to create tickets here for all feature suggestions i would like to make.

If its true, can you elaborate how this request doesn't improve the plugin? There is another approach for these situations? I don't see how, seems Crocoblock team always try to solve things through listing grids and listing items with custom queries if needed.

In that case, i think its very important to have more options to "list" things, and since we are going for container layouts with flexboxes, seems totally legit to have the option to output posts items inlined horizontally and wrapping.

Thank you.

**Comment by Floydtm** [comment]
You can contact the support and the guys will help you set everything up as suggested @loucasl Thank you!

**Comment by miguel-cravidao** [comment]
@Floydtm thanks for your reply. The support team told me to open this suggestion here, that's why I im here.

**Comment by Floydtm** [comment]
Your request cannot be added to the plugin itself. You can use the workaround that @loucasl suggested
