### ISSUE TITLE
Date support on calculated field in JetFormBuilder

### ISSUE THREAD

**Issue by spingoo** [CrocoBlock/suggestions#5546]
Calculations using date is of importance. For example: a product that is purchased with an expiration date. One field is the starting date, and it add the value of a numeric field, for example: months = 3, then the calculated expiration date shall be starting date + 3, and it will show the value with a date format.

**Comment by fabio323ti** [comment]
+1 missing feature very important, missing in Jetform also.

**Comment by girafffee** [comment]
The new version of JetFormBuilder 3.0-beta is now available to you.
You can check if your case is working now.

For example:
1. Add a Calculated Field to the form.
2. In the formula, write `"%date_field|addMonth(3)|toDate%"` (yes, with quotation marks)
3. There is a new Value type option in the Calculated Field settings. There you have "as String"

More details about Calculated Field macros
https://github.com/Crocoblock/jetformbuilder/wiki/Frontend-Macros---Filters
https://github.com/Crocoblock/jetformbuilder/wiki/Frontend-Macros---External-Macros

JetFormBuilder 3.0-beta https://github.com/Crocoblock/suggestions/issues/6408

**Comment by nicolas-wl** [comment]
@girafffee how can I format date to another notation?
"%date_field|format_date(d/m/Y)%" is not working for me

**Comment by ghost** [comment]
> The new version of JetFormBuilder 3.0-beta is now available to you. You can check if your case is working now.
> 
> For example:
> 
> 1. Add a Calculated Field to the form.
> 2. In the formula, write `"%date_field|addMonth(3)|toDate%"` (yes, with quotation marks)
> 3. There is a new Value type option in the Calculated Field settings. There you have "as String"
> 
> More details about Calculated Field macros https://github.com/Crocoblock/jetformbuilder/wiki/Frontend-Macros---Filters https://github.com/Crocoblock/jetformbuilder/wiki/Frontend-Macros---External-Macros
> 
> JetFormBuilder 3.0-beta #6408

..................................................
How to replace a field value with (3) ?
