### ISSUE TITLE
Value from Metafield on JetFormBuilder

### ISSUE THREAD

**Issue by spingoo** [CrocoBlock/suggestions#5547]
When using JetFormBuilder, many times the field is associated to the taxonomy post, and the name of the taxonomy is required instead of the default ID value. It is not clear what variable needs to be inserted in the **Value from Metafield** field. Maybe you should have a popup indicating what are the names of the variables that can be used in order to get the values.

What would be the variable to insert in case of the taxonomy name (term name)?, not the ID.

![Taxonomy name - Edit Form](https://user-images.githubusercontent.com/108023153/175108271-8a610364-cd90-4c0d-89b1-7d775dc6af17.png)

**Comment by Floydtm** [comment]
By default, when you choose the Post Type or Term, the values of the options will be taken from post\term or page IDs. However, in this bar, you can specify the name of the concrete meta field from which the value will be pulled. Be aware that this will work with the custom meta fields only. This can be found in the plugin documentation.
