### ISSUE TITLE
Multi select in JetFormBuilder

### ISSUE THREAD

**Issue by lagethomas** [CrocoBlock/suggestions#5548]
Is there a way to use a multiple selection in select? When we have too many terms and we use Box it pollutes the page.

**Comment by ofmarconi** [comment]
Hey @lagethomas, similar this?
https://harvesthq.github.io/chosen/#:~:text=Sloth%20Bear-,Multiple%20Select,Polar%20Bear,-Hide%20Search%20on

**Comment by lagethomas** [comment]
Yes, similar this!
It's is possoble in next update?

Em qui., 23 de jun. de 2022 10:03, Orlando Marconi ***@***.***>
escreveu:

**Comment by girafffee** [comment]
Added in version 2.1.3
