### ISSUE TITLE
box shadow for jet smart filters pagination widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5549]
**Please, describe the feature request, making it clear to understand.**

Please add the box shadow option for pagination widget items if possible. https://prnt.sc/IOx2WSZW6zpV
It is also great if we can control the shadow of the box in normal, hover and active modes.

thank you

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
