### ISSUE TITLE
JetEngine Profile Builder - Hide admin bar more options

### ISSUE THREAD

**Issue by edgBllw** [CrocoBlock/suggestions#5550]
We can choose certain user roles, that can access the backend panel, but please also give us the ability to to that with the admin bar hiding. not only for admins. because in lots of cases you have another role that can access the backend but isn't an admin. then without the admin bar in the front end, it looks strange

**Comment by Floydtm** [comment]
You can use this [plugin](https://wordpress.org/plugins/user-role-editor/) to create a new role or customize the current one.
