### ISSUE TITLE
JetEngine: Add a field to dynamic image for ALT tag

### ISSUE THREAD

**Issue by mindingear** [CrocoBlock/suggestions#5551]
Adding a dynamic field to be able to write custom ALT text for images would be very valuable SEOwise.
Something similar to what they have done here: https://e-addons.com/elementor-addon/image-custom-alt/

**Comment by tizum** [comment]
+1 
@kaskad88 this can be added along with this request: https://github.com/Crocoblock/suggestions/issues/5522#event-6846159348
Very good your request by the way @mindingear

**Comment by mindingear** [comment]
@tizum  Awesome! Thanks! :)

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.4

**Comment by h-mortazavifar** [comment]
Is there a way to display alt tag for light box in dynamic field carousel?
