### ISSUE TITLE
Shortcode for jet smart filter/ jet search 

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#5552]
Being able to use the shortcode of jetsmart filters and jet search
I was thinking about styling the the filters and search widgets in Gutenberg (jet style manager) and then use the shortcode of the styled widgets in any where in the site
So it makes these plugins compatible with any theme
@Floydtm

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by mehdimoradi1500** [comment]
@Floydtm i wished once, my request assigned to... 😂
