### ISSUE TITLE
Add (+/-) Button Number Incrementers (Number field in forms)

### ISSUE THREAD

**Issue by IreneDania** [CrocoBlock/suggestions#5553]
I would like to add plus and minus button for the booking form for adults and kids. Something like the screenshot attached.
![WhatsApp Image 2022-06-22 at 11 12 34 AM](https://user-images.githubusercontent.com/108114937/175505199-92590e03-c554-4cfa-bcec-2ed9388ed1fd.jpeg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
