### ISSUE TITLE
Random post - in JetEngine Listing

### ISSUE THREAD

**Issue by glorpyz** [CrocoBlock/suggestions#5555]
Hi.
1) I have made a special Post Types, in JetEngine for Quotes.  Example "After rain comes sunshine"
2) And I have made a Listing, with a Slider showing these post-quotes.

My feature request is to choose **"random post"** so JetEngine choose some random posts and slides them (or shows them normal).
Random could be useful in different situations.
It would be great if we could choose how many, like 10 random, or unlimited random.

Else the visitors will see the same newest quotes all the time and missing the oldest.

Thanks

**Comment by Floydtm** [comment]
You can set up a random order right now. Look at the listing grid or Query Builder settings https://prnt.sc/q9U1xtSi7kdg https://prnt.sc/yvlqO2BH6Z1T
