### ISSUE TITLE
Jet WooBuilder Sorting filter bug

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#5558]
Hello,

In Jet Woobuilder "shop template" **sorting filter widget from jet smart filters** (sort products by price, date etc.)  d**oesn't work with "Ajax" and "Page Reload"**, when the option is **"WooCommerce archive with JetWooBuilder"**. Works only with "Page reload" with  "Apply button" . Please see images in comment below.

**Comment by mary151** [comment]
![sorting1](https://user-images.githubusercontent.com/56391303/175807777-a1647a44-18bb-44e8-bba6-8fe894e53921.png)
............................................................
![sorting2](https://user-images.githubusercontent.com/56391303/175807779-48f16709-2c59-4a9f-a083-bf27a9a475ec.png)
............................................................
![sorting3](https://user-images.githubusercontent.com/56391303/175807782-0b67026b-8393-44ad-8fa5-74eaac6744ec.png)
............................................................
![withapply](https://user-images.githubusercontent.com/56391303/175815387-ee1c4237-6f0d-4080-a086-0a073578791a.png)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
