### ISSUE TITLE
Jet WooBuilder Jet Smart filters radio filter bug

### ISSUE THREAD

**Issue by mary151** [CrocoBlock/suggestions#5559]
Hello,

I wanted to add product categories as radio smart filters in Jet WooBuilder. But when I choose **"Page Reload" as "Apply Type"**, it is not reloading the page. Nothing happen.

Also ** ajax also don't work** - it shows only loop of one product.

![screenshot-localhost-2022 06 25-19_12_48](https://user-images.githubusercontent.com/56391303/175807998-de8f97d0-0d58-490a-9945-6c7aae112b44.png)
![screenshot-localhost-2022 06 26-12_41_04](https://user-images.githubusercontent.com/56391303/175808459-f9013df3-6bea-4b5d-9462-50361544d104.png)

![screenshot-localhost-2022 06 25-19_13_50](https://user-images.githubusercontent.com/56391303/175808022-85995ba5-7d3a-4b8d-82e3-cff131161e85.png)

![ajax](https://user-images.githubusercontent.com/56391303/175808659-e204f8a0-cd14-4ca0-a190-bc043761df49.png)
![ajax1](https://user-images.githubusercontent.com/56391303/175808663-4f6e4b81-c857-4fb2-b32f-8f03c8cacbaa.png)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
