### ISSUE TITLE
Booking rules for jet booking

### ISSUE THREAD

**Issue by RobertLloyd45** [CrocoBlock/suggestions#5569]
Allow bookings for set durations eg: 2 nights, 4 nights or 7 nights. The guest will select their length of stay, this is much more organised than allowing random dates and random durations. It allows the booking provider to be more efficient with room changes and adds more structure to the hotel/ rental.

This would work by allowing bookings on certain days only. Eg; Fridays or Mondays.

Example; The guest would choose Friday for 2 nights and leave on Sunday.

The ability to prevent bookings for a set period from todays date would also be helpful. Eg; bookings can only be made after 3 days from today.

**Comment by UraraReika** [comment]
Hello @RobertLloyd45. Thanks for the feedback.

I've checked your request. At the moment, we do not plan to introduce such functionality into core of our plugin. But such a goal can be reached using a custom solution only.

I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/.

Thank you for your understanding.
