### ISSUE TITLE
Jet Smart Filters- select filter menu, org. by parents 

### ISSUE THREAD

**Issue by ImmersionNation** [Crocoblock/suggestions#557]
Would it be possible to add the function to the select filter to group terms by parents when filtering through a hierarchical taxonomy?  (Like the checkboxes functionality, but in de list instead)

Thank yoooouuuu!!!!

**Comment by Floydtm** [comment]
@ImmersionNation, Hi! From the technical side, this is now impossible to do. Perhaps in the future we will implement this in the plugin. keep for updates
