### ISSUE TITLE
BUG in jet smart filters (only in RTL websites)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5570]
hi @Floydtm, I apologize for tagging. But I finally found the cause of a bug and now was the best time to report it. I have reported this once before but I will close it and please keep this issue.

**Describe the bug**
If the website is RTL, in the visual filters, checklist and radio list, the items are completely stuck together. Please see [this photo](https://prnt.sc/MPorLp6XMGEz).
**But in LTR this problem does not exist and there is a standard distance between the options :** https://prnt.sc/G_88NpDbxxa2

Please fix this bug in the new version if possible. 

**To Reproduce**

1- Add visual , checkbox list and radio list filters.
2- Activate the counter to display.
3- View filters in both RTL and LTR. The difference is quite clear.

**Screenshots**

in RTL : https://prnt.sc/ADYPlBHxgF7v
in LTR : https://prnt.sc/3YM_8W2Jg05c

This bug has been tested on desktop and Android, Chrome browser. Of course, it is present in all browsers.

thank you !

**Comment by 79ho3ein** [comment]
hi @Floydtm , good time.
I understand that RTL users are in the minority, I also understand that you have priorities for each update. But please check and fix this bug if possible. This bug has been present in jet smart filters for almost a year now. This bug seriously damages the UI on RTL websites. I've fixed it now with some custom css but it would be great if it was fixed in the plugin core.
Thank you for your attention.

**Comment by Michaelgimii** [comment]
+1
I have this problem too. This issue has been around for a long time. Is it possible to fix this problem in the new version of jet smart filters? please @SargasTM

**Comment by SargasTM** [comment]
done, will be available in the next version
