### ISSUE TITLE
JETSmartFilters: add additional providers to Pagination widget

### ISSUE THREAD

**Issue by trofimartya** [CrocoBlock/suggestions#5575]
Almost all widgets have Additional Providers except Pagination. It would be great if you can allow to have multiple providers for Pagination widget too.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
