### ISSUE TITLE
Query builder - WC Product Query doesn't load dynamic data in listings

### ISSUE THREAD

**Issue by makaus** [CrocoBlock/suggestions#5576]
**Describe the bug**
Move from legacy queries to Query builder.

Choose WC Product Query instead of Posts Query in Query Builder
On page where Listing grid is used, images, prices, etc. will not show if WC Product Query. Shows perfectly when choosing Posts Query(in Query Builder) and setting Post Type to Products.

**To Reproduce**
1. Use WC Product Query in Query Builder
2. Create listing and load dynamic info from products
3. Create listing grid and use listing
4. Dynamic info missing from listing on frontend
5. Info is showing if Posts Query is chosen instead of WC Product Query

**Expected behavior**
Dynamic info showing. Like using the now "legacy" query methods directly on the Elementor Widget - Listing Grid.

**Additional context**
Products shows in Preview results in Query Builder and the products get listed in the Listing Grid, but with fallback image and only information from some widgets

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by makaus** [comment]
I can try. I have 3 templates on my frontpage which uses 3 different listing grids but the same listing element.

If i use WC Product Query, is only shows some(description and brand name(custom tax)) of it.

In the picture, you can see when i edit the listing(inside the template with the listing grid), the information shows up, but when you see the listing in action(to the right) the info is missing but the description. like the dynamic link between every product and what the widget think it have to display is missing. If i use Posts Query in Query Builder, it finds all information.
I have featured, most sold and newest as three templates and i can force it to fail if i change one of the queries in the Query Builder, and the other with Posts Query still works
![Screenshot 2022-06-30 at 07 47 40](https://user-images.githubusercontent.com/8776403/176603145-28b685dc-d32a-4899-9a1b-e4e090204523.png)
![Screenshot 2022-06-30 at 07 51 57](https://user-images.githubusercontent.com/8776403/176603152-9483ce3e-de43-4be1-9c4c-bc9c267c88bb.png)
.

**Comment by MjHead** [comment]
Fixed with 3.0.2 update

**Comment by JorensM** [comment]
@MjHead I'm still experiencing this issue
