### ISSUE TITLE
JetSmartFilters

### ISSUE THREAD

**Issue by Olegggggggg** [Crocoblock/suggestions#558]
Hello. The new version of JetSmartFilters has a great opportunity to hide empty filtering options. But it would be nice to be able to hide the filter label if all filtering options were hidden.

Original in Russian:
Здравствуйте. В новой версии фильтров появилась отличная возможность скрывать пустые параметры фильтрции. Но было бы неплохо иметь возможность скрыть и метку фильтра в том случае если все параметры фильтрции были скрыты.

**Comment by Floydtm** [comment]
@Olegggggggg, hi! this should work in the latest version of the plugin
