### ISSUE TITLE
JetElements> Slider / Advance Carousel widget - Image Lazy Load

### ISSUE THREAD

**Issue by Assistmysite** [CrocoBlock/suggestions#5580]
Please add lazyload for images inside the slider and Advance Carousel widget to reduce the loading speed... This function is must if the slider is used as the full screen header slider ( with background img ). In our experience Jet sliders slows down the website a lot and we were forced to use an alternatives in number of projects....

**Comment by simonst** [comment]
++1 this would be really helpful as well as webp support in the slider

**Comment by simonst** [comment]
why closed? is this implemented?
