### ISSUE TITLE
JetBooking | Accept a previously booked Check-In date as someone elses Check-Out date.

### ISSUE THREAD

**Issue by maaxjahz** [CrocoBlock/suggestions#5581]
Dear Crocoblock team, 

For a customers website I have used the Balirento theme with JetBooking functionality. 

There is already this option for the Booking period where you can not include the last booked date (check-out date) for someone elses check-in date: https://gyazo.com/fa50b39c1ac7101af2b6e796ef694fdb

This means that once a period is booked, a next booker can still select the previously booked Check-out Date as their Check-In Date.

However when someone tries to book a previously booked check-in date as their check-out date, this date won't be available to book.

I would love to see an option being developed where this option can be given, as people will leave at 10:00 and new visitors will enter at 15:00, which means a previously booked check-in dates should be available to book as a check-out date aswell.

**Comment by UraraReika** [comment]
I merged this issue with [#3755](https://github.com/Crocoblock/suggestions/issues/3755), which is on the same subject so we could deal with it more efficiently.
