### ISSUE TITLE
JetBooking | Check-In & Check-Out dates only on specific day(s) of the week.

### ISSUE THREAD

**Issue by maaxjahz** [CrocoBlock/suggestions#5582]
Dear Crocoblock team,

I have been using JetBooking for a website to rent out campers/caravans.

The customer of the website only wants to have customers check-in and check-out on a certain day (friday)

However unfortunately there is no option to do so with the jetbooking functionality so far. 
I tried to get this done with the weekly booking configuration, but that only let people book from monday to sunday, which is totally not what we want at all. 

Weekly bookings functionality: 
https://gyazo.com/6625f4871096e2a9eab7fb19e8d2ecd4

I would love to see the development team implement a feature where you could select only certain day(s) of the week as Check-in or Check-out. Another nice thing would be to have more functionality with the weekly booking feature to where you can select yourself wheter certain days can be selected as check-in dates & then only have the option to book for 7 days from those day(s) of the week onwards. Because right now the functionality is very lacking in my opinion.

**Comment by UraraReika** [comment]
Hello @maaxjahz !

Specific days for booking functionality was presented in latest 2.5.0 release. Check it out. 

If we talk about booking period then I merged this issue with [#5376](https://github.com/Crocoblock/suggestions/issues/5376), which is on the same subject so we could deal with it more efficiently.
