### ISSUE TITLE
JetTricks - scroll horizontal containers 

### ISSUE THREAD

**Issue by otomasz** [CrocoBlock/suggestions#5584]
Hi,

JetTricks lacks the possibility of creating **horizontal scrolling containers** for mobile devices. 📱 

Currently, it is standard to use horizontal scrolling on many mobile websites.

![1*owfJDGpP-n707h-FZuDDKg](https://user-images.githubusercontent.com/23310832/176739539-1636eafd-ff8e-49a7-a94b-ae5e7b275846.gif)

I think this solution will bring you new customers and existing users will love it ❤️ 
For you it is probably not a lot of work and for us it is a big step forward 👍

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
