### ISSUE TITLE
Progress Bar for JetEngine Listing Grid Slider

### ISSUE THREAD

**Issue by ALPSIT** [CrocoBlock/suggestions#5585]
Hi Team,

Would be awesome to have a Progress Bar option for Listing Grid Slider and any other slider widgets Crocoblock offers.

See below screenshot example.

![image](https://user-images.githubusercontent.com/85008592/176847387-218e03b9-6e90-48e8-8109-263f16ed851a.png)
![image](https://user-images.githubusercontent.com/85008592/176847431-d97dbbc0-239f-4bbc-a179-893a65415600.png)

Kind Regards,

Alp Aydogdu

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by ALPSIT** [comment]
> At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

I agree - there is much more priority tasks than this one haha. was just an idea to think about.
