### ISSUE TITLE
JetFormBuilder fields from reusable blocks are not shown in PostSubmit register user action

### ISSUE THREAD

**Issue by rlb222** [CrocoBlock/suggestions#5589]
**Describe the bug**
When I edit a JetFormBuilder form and place a Reusable Block with multiple fields, these fields are not shown when I edit the 'register user' form action.

 There is a workaround, but it's not desirable.

**To Reproduce**
1. Make a reusable block from several fields on a JetFormBuilder form. Give it a name (e.g. myFieldGroup) 
2. Go to another JetFormBuilder form. 
3. Add the Reusable Block (e.g. myFieldGroup) on the form.
5. Update Form 
6. Click on 'JetForm settings'
7. Scroll down to 'PostSubmit Actions', 'Register User'. 

**Bug description, Unexpected behavior**  
The newly added fields in the Reusable Block are not shown.
 
**Expected behavior, what should happen**
I should see the added fields that are in the reusable block

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version Latest JetEngine 3.0 JetFormBuilder (pro) 2.0.6

**Additional: Workaround**
I can select the reusable block and 'Convert to Regular Blocks'. And the fields are shown in the Form actions.

**Comment by girafffee** [comment]
Fixed in version 2.1.1

**Comment by rlb222** [comment]
Thank you !For the fix and for this notification!Regards René —//—Op 28 nov. 2022 om 10:50 heeft Sasha Ivanenko ***@***.***> het volgende geschreven:﻿
Fixed in version 2.1.1
