### ISSUE TITLE
Horizontal and Isotopic layout of search result

### ISSUE THREAD

**Issue by keuchnee** [Crocoblock/suggestions#559]
Hello all,

First of all please excuse me for my English mistakes because I am French

I bought Jetsearch some time ago, and I noticed that the display of the results is not customizable at the level of the display which is only available in vertical.

Which is not aesthetic when one displays the images of the posts. So I would like to know if it would be possible to have a horizontal display and an isotpic display of the results.

I add examples in image to understand at best :

![exemple2](https://user-images.githubusercontent.com/56161870/66211213-dfd40e00-e6bb-11e9-9913-8ef8ca2f21df.jpg)
![exemple1](https://user-images.githubusercontent.com/56161870/66211214-dfd40e00-e6bb-11e9-915a-29373d32ffa3.jpg)

Thank you in advance for your answers.

**Comment by Floydtm** [comment]
@keuchnee, Hi! At the moment we have no way to implement this. If we collect more requests for your question, we will definitely try to implement it. Thanks you!
