### ISSUE TITLE
Jet Smart Filter is not showing on the frontend when I try to filter the archive template using normal textbox meta key.

### ISSUE THREAD

**Issue by mdinjamul** [CrocoBlock/suggestions#5594]
**Describe the bug**
The Bug is that I have a website where I have created a custom post type to review mobiles and laptops, in that post type I have a few custom text fields for "Processor", "RAM", "Storage" etc. and I want to filter out the archive page of the mobile and laptop using that custom text field value ( "Processor", "RAM", "Storage"). but it does not work. I need a checkbox filter to filter out the mobiles and laptops based on "Processor", "RAM", and "Storage" but the filter is not showing on the frontend.

**To Reproduce**
1. Go to https://programmerinjamam.com/test/mobile-phone/
2. Look on the left side, there should be the filter I have added
3. See The error there is no checkbox filter

**Expected behavior**
There should be display a checkbox filter I have created using jetsmartfilter.

**Screenshots**
1. https://prnt.sc/PX5jYvbAxeT4 (Meta Fields, using these fields I want to filter my archive page)
2. https://prnt.sc/oxYBWPivD3Wi (Filter Setting Page)
3. https://prnt.sc/xTf6TEEAPxXd (Elementor Settings)
4. https://prnt.sc/_ba5AFNhZ4bo (No filter showing)

**Additional context**
This is working using another third-party plugin called "Filter Everything" see the screenshot you can understand
 https://prnt.sc/pZDO_1Ipxd4y (Here I have used the "Filter everything" plugin and it is working)
 But I need jet smart filter.

**Comment by Floydtm** [comment]
This is not a bug. Learn the documentation how to [configure](https://crocoblock.com/knowledge-base/article-category/jetsmartfilters/) checkbox filter.
