### ISSUE TITLE
text field for cpt cant be seen, jet engine

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#5597]
hi 
when i add text/text area/number field field to CPT, i cant add any text to it

![Capture](https://user-images.githubusercontent.com/86493591/177326913-e4703a8d-141f-4c1b-8206-638bd14f8f56.JPG)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
