### ISSUE TITLE
JetFormBuilder is uploading images but not showing in the form

### ISSUE THREAD

**Issue by deepwaterpixel** [CrocoBlock/suggestions#5599]
**Describe the bug**
Using any JetFormBuilder form, Media fields do not work.  When I select the image, it is uploaded to the site, but not shown on the form.  This then means if the Media field is **required**, the form submission fails.

**To Reproduce**
1. Go to a form with a Media field
2. Select **Choose files...**
3. Pick a photo or photos
4. Try to submit form (if required field) or submit and check data

**Expected behavior**
I expect to see an image on the form and be able to submit it.

**Screenshots**
Screenshot doesn't help, the file just isn't in the form, but it is on the site.

**Desktop (please complete the following information):**
 - OS: macOS 12.4 Monterrey
 - Browser: All (Chrome, Brave, Safari, Firefox, Edge)
 - Versions: Various

**Additional context**
On the same site, the **Media** field for JetEngine's forms works fine.  However, I _need_ features in JetFormBuilder, so having **Media** fields not working is bad.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
