### ISSUE TITLE
Dropbar widget Adaptive button layout

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#56]
Dropbar widget Adaptive button layout

Please add the ability to select on phones and tablets adaptive button layout
http://prntscr.com/mp6g0m

/*Оригинал на русском*/
Прошу добавить возможность выбора на телефонах и планшетах адаптивное расположение кнопки
http://prntscr.com/mp6g0m

**Comment by kaskad88** [comment]
Done. Available in JetElements 1.15.13
