### ISSUE TITLE
Show Post Count with custom query

### ISSUE THREAD

**Issue by jurdekker** [Crocoblock/suggestions#560]
Hi all, Sorry for my bad english

I am satisfied with the widgets of the plugin, but I miss one more.
Is it possible to create a widget that shows the post count and where the query can adjust, like what grid has. I use this in a single post template to show how much a child relationship it has. 
It might also be useful to show how much post it has on a dashboard or something.

thanks in advance.

**Comment by Floydtm** [comment]
@jurdekker, hi! Could you describe the request in more detail? if you can attach screenshots or video
