### ISSUE TITLE
is Mobile, does not detect Firefox on iOS iphone 13 pro

### ISSUE THREAD

**Issue by ofmarconi** [CrocoBlock/suggestions#5604]
Hello could you check if this is really a bug?

thx!

**Comment by ofmarconi** [comment]
It was enabled in my Firefox application: Show Desktop Version

![image](https://user-images.githubusercontent.com/6594795/177652369-32a7f0f7-9363-43a8-9d97-c3b292d0b48a.png)

When this is enabled, there is no way to detect that it is a mobile device?

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by ofmarconi** [comment]
Hello Floyd Firefox, has an option called: Site Version for Desktop.

This prevents identifying if it is a cell phone.
