### ISSUE TITLE
Add more field options in JetEngine

### ISSUE THREAD

**Issue by luxpatrick** [Crocoblock/suggestions#561]
**Please, describe the feature request, making it clear to understand.**

add more field types to the JetEngine like a number field. For example to display numbers in a dynamic content widget like star rating widget from Elementor. 

**Add an example of where this feature is already implemented. **

In Pods plugin you have that field (among others) 
By adding this field you'll make JetEngine more suitable as a substitute for ACF and Pods. 
User won't have to have several plugins activated.

**Comment by philmatt** [comment]
+1
I would also love JetEngine to add some logic conditions to their meta fields (like ACF)

**Comment by kaskad88** [comment]
I merged this issue with #1009, which is on the same subject so we could deal with it more efficiently.
