### ISSUE TITLE
JetAppointment: Time Limit for appointment with on-hold status 

### ISSUE THREAD

**Issue by ovirex** [CrocoBlock/suggestions#5611]
I think (and I need) It would be very useful to add a time limit to appointments that are in "on-hold" status.

Use case: When a user pays for an appoinment but It never finish paying, that date is now "on-hold" until the administrator does something. Of course, when the user is on the checkout page, the date should be "on-hold" so someone else can't "steal" its date (that's how it works at the moment). But if the user never finish the payment, the date should be released. 

It should be an option asking "how much time you want to wait for the user payment" or "on-hold time limit".

**Comment by MjHead** [comment]
It was added with 1.6.10. From this version you can automatically change On Hold to Failed after selected amount of time - https://i.imgur.com/3oPMCs1.png
