### ISSUE TITLE
Dedicated database table for CPT (like CCT)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5615]
**Please, describe the feature request, making it clear to understand.**

hi crocoblock team!

As you know, in jet engine, every type of post we create is stored in the wp_jet_post_types table. But if the number of posts in one post type increases, say 700, this can have a significant impact on website speed. 

**The desired solution**

**Please add this possibility so that we can create a dedicated table for each CPT.** Just like CCT. This is really important. In fact, if you add this feature, again by default, all post types will be stored in the wp_jet_post_types table. But if you want, we can assign a dedicated table to it.

Please add [this section](https://prnt.sc/kHDNEv-7VgFk) to CPT. That would be great.

**Comment by saeed-1987** [comment]
Yes it will be so good
So we don't be worried about having archive and taxonomies, but in cct we have this limitations

**Comment by jaimenurbina** [comment]
excellent Proposal like this would be somewhat more agile consultations

**Comment by unitedonline** [comment]
+1

**Comment by mehdimoradi1500** [comment]
Yes totally great proposal, i wish they consider it
I dont know about the backend of coding but this is really cool feature

**Comment by Lucky5111** [comment]
Rather than having a custom table for post types, I think having a custom meta table for those custom post types will be better. Since most slower queries are because of joining that post_meta table.

**Comment by mehdimoradi1500** [comment]
I was reading the cct overview and it was written that the archive, taxonomy and single post of cct will be implemented and improve but it doesn't happen for quite long time
![Screenshot_20220822-125716_Chrome](https://user-images.githubusercontent.com/86493591/185876557-c2b1b317-81ce-4f86-85d7-1f397b806d99.jpg)

**Comment by Lucky5111** [comment]
Unfortunately yeah. CCT is a good option but I feel like they aren't updating it as much. Plus they do not give documentation on a lot of things that could make our lives easier.

You can use a CCT with a custom taxonomy, just create a relationship, but the only issue is if you go to a child term it will not work. For now, using it for post meta and the default post table seems like a good idea.

**Comment by mehdimoradi1500** [comment]
Hi @Floydtm
May you please consider this proposal
I checked Metabox plugin and they did it great, please check it out
https://docs.metabox.io/extensions/mb-custom-table/

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
I think in the future we will focus on cct updates
Thank you!
