### ISSUE TITLE
sql query dynamic tags

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#5617]
It would be great if the dynamic tags of Elementor could collect the data from a sql query. You can only collect the metas of the post.
![Captura de pantalla 2022-07-08 a las 18 45 51](https://user-images.githubusercontent.com/90837626/178036076-ea61dfcb-748e-4a42-add7-aae301128a04.png)

**Comment by MjHead** [comment]
Added `Current Object Field` Dynamic Tag. Works similary to appropriate part of Dynamic Field widget

**Comment by kaskad88** [comment]
Added with 3.0.5 update

**Comment by JuanCar29** [comment]
Cool
