### ISSUE TITLE
Bug in the new Jetformbuilder update when updating a cct through a form. #Jetformbuilder

### ISSUE THREAD

**Issue by RoynerG** [CrocoBlock/suggestions#5619]
There is a bug in the new version when updating a cct through a form, what it does is to duplicate the entry instead of updating it. Please check it.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by RoynerG** [comment]
It is not on my side. because before the version worked fine, it updated the cct, but after updating jetformbuilder to 2.1 I get the error that it does not update but duplicates the post and creates a new one.

**Comment by Floydtm** [comment]
Have you contacted the support team about this?
