### ISSUE TITLE
Preview image in webp format > media field - jet engine

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5622]
**Describe the bug**
hi
To categorize (Taxonomy) my new post type, I created a media type field. **The problem is that if the image format is webp, their preview is not displayed in the media field :** https://prnt.sc/l17BUfI96y6y
But if the image format is jpg or png, there is no problem and the preview is displayed correctly : https://prnt.sc/G49xcakaqTKw

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
