### ISSUE TITLE
JetEngine – Ability to hide " Name: " for meta fields in the CPT interface

### ISSUE THREAD

**Issue by fostira** [CrocoBlock/suggestions#5625]
The "Name: [slug] " which appears below the meta fields is cluttering the interface and is tightly attached to the field description. We need more spacing between the name and description and also the ability to hide the "Name: " altogether in order to have cleaner and less confusing interface for end users which is going to use the CPT.

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.3
