### ISSUE TITLE
JetSmartFiler - AJAX Pagination Top Scroll Distance

### ISSUE THREAD

**Issue by AuraWP** [Crocoblock/suggestions#563]
Hi there,

Using **JetSmartFilter > AJAX Pagination**, it would be great to have the ability to adjust the distance from the top margin when reloading the content via AJAX mode.

_The reason is that sometimes the page may contain some Hero-Slider, and this causes the AJAX reload to show the content partially._

I did it through a "hard-code hack" by editing line 184 oft the file:
**/wp-content/plugins/jet-smart-filters/assets/js/public.js**

`if ($ scope.hasClass ('jet-filters-pagination__link') && $ scope.data ('apply-type')) {

	// FROM:
	$ ('html, body'). stop (). animate ({scrollTop: $ provider.offset (). top}, 500);

	// TO:
	$ ('html, body'). stop (). animate ({scrollTop: $ provider.offset (). top - 230}, 500);
	
}`

I await more comments.

Thanks,
Martin

**Comment by JohnPixle** [comment]
@Floydtm we definitely need this option for the pagination, @AuraWP has a good point, would be very handy to have a UI control for this. Thanks for your consideration!

**Comment by SEwebm** [comment]
Hey just wanted to ask, is there an option like this already?

Would be nice to _optionally_ enable scrolling on pagination in general.

**Comment by UraraReika** [comment]
> Hey just wanted to ask, is there an option like this already?
> 
> Would be nice to _optionally_ enable scrolling on pagination in general.

This option already in the widget. Each Pagination widget from JetSmartFilters has this [option](https://tppr.me/KD0q0).

**Comment by SEwebm** [comment]
Oh I guess I missed that, still I can't seem to find an option to disable the scrolling because setting the offset to achieve no scrolling is only useful if I had a fixed height of the content, which in my case is depending on the screen width.
