### ISSUE TITLE
Shortcode for Thank you page template

### ISSUE THREAD

**Issue by Carolinekjeldgaard** [CrocoBlock/suggestions#5640]
Hello,
I am a marketer and in my work, I need to be able to track each page of a funnel in order to optimize and market and remarket to the right people.
I miss being able to create a static URL for the Thank you page on which I can ADD the Thank you page Template onto. I need a static URL for my template so I can add the right HTML codes from Google Ads, tag manager, and google analytics so I can track exactly where people are coming from in paid traffic, who buys, and eventually optimize for more of that kind of people.

If I can not add this code to the final step of the funnel I can not track my numbers as a marketer. 

So please create such a feature so I can either: Track the template by adding a code to it from google ads, OR I can ad the template either through a shortcode or something else onto my Static page dedicated to Thank you Page.

Thank you and I am looking forward to hearing from you very soon.

**Comment by UraraReika** [comment]
Hello @Carolinekjeldgaard! Thanks for the feedback.

Thank you page template it just a simple Elementor template that grabs and handle WooCommerce data. So in this case you can add whatever you can’t code to this template. You can use for example HTML or Shortcake widgets from Elementro plugin and put your code that will track traffic. But maybe I misunderstood you, in this case please follow guidelines for opening a new feature request, so we can help you better https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md.

Thank you for your understanding.
