### ISSUE TITLE
JetEngine query - excluding a specific post will not work when 3rd party plugin - Search Exclude is active

### ISSUE THREAD

**Issue by e-cubed** [CrocoBlock/suggestions#5642]
Here is a screenshot with the post ID in the excluded by ID field (the post that should be hidden is the 2nd in the list: The Where, What..
![unnamed-1](https://user-images.githubusercontent.com/6537449/178775490-a88f9569-2ba5-4d8b-ab47-ae854bbfba6d.png)

As you can see I'm using a keyword search query + exclude post.
The exclude post does not hide when the 3rd party plugin - Search Exclude (https://wordpress.org/plugins/search-exclude/) is active.
This is a compatibility issues between plugins. I understand it's not solvable by the support desk. Just hopeful that you would be able to include this fix in future updates.

Thank you.

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.3
