### ISSUE TITLE
Ability to display the Callback value of name (without using glossary)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5643]
**Please, describe the feature request, making it clear to understand.**

hello
Currently, when we create a text field (for example, a text field) for post type, it is not possible to select a name in the dynamic field widget > [Callback field](https://prnt.sc/MdVdLpukK6YW).
In fact, Jet Engine only displays the value of each field. But I want to display the [name](https://prnt.sc/mYp6hMNSydIB).
I tried a lot but there doesn't seem to be a solution. Please check this issues @Floydtm  thanks.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
