### ISSUE TITLE
JetFormBuilder - We need Reset password option

### ISSUE THREAD

**Issue by manashjyotix** [CrocoBlock/suggestions#5646]
Hi, Crocoblock

JetFormBuilder is good for making Login, Registration, Update profile page but I never saw Reset password option.

**Comment by mehdimoradi1500** [comment]
We definitely need
Also in so many countries email is not used but it's a required field for jet form builder
I like to use only phone number to register/login

**Comment by girafffee** [comment]
This feature was added to User Login addon in version 2.0.0. Watch this video to understand how to set up a form for reset password.
https://youtu.be/lxW5d0tvUro
