### ISSUE TITLE
Grid switch

### ISSUE THREAD

**Issue by zimmiel** [Crocoblock/suggestions#565]
Hello CrocoTeam!
When will the time, make a switch to display grid variations. Grid switch. So that the user can switch the grid view of the product _(img 1,2,3)_
![img_1](https://user-images.githubusercontent.com/42843497/66433548-38433c80-ea29-11e9-9e24-33b454fe22e8.png)
![img_2](https://user-images.githubusercontent.com/42843497/66433549-38dbd300-ea29-11e9-927d-70c4469f1824.png)
![img_3](https://user-images.githubusercontent.com/42843497/66433552-38dbd300-ea29-11e9-9dae-1d62df2a6098.png)

**Comment by stasonua0** [comment]
+1

**Comment by scubaninja1977** [comment]
+1 on this. :)

**Comment by realstephenzhao** [comment]
This should be applied to **Listing Grid of Jetengine** too. All you need is to add a switch widget and design two different template.

**Comment by woofworkshop** [comment]
I'm joining !! Very necessary functionality
+100500

**Comment by einzique** [comment]
I am also looking for this functionality. has this been implemented in any way for listinggrids?
