### ISSUE TITLE
Crocoblock Portfolio Slider Feature request

### ISSUE THREAD

**Issue by MjolnerThor** [CrocoBlock/suggestions#5651]
This feature does not exist in the summary of crocoblock widgets. This feature contains a smooth and nice-looking portfolio image that gives your web design agency a more professional look. It also gives the website a presentation that gives it more life:  

First
The first you see is an image and a logo of the company that it concludes, the image is a representation of the company that it involves.
Image: https://gyazo.com/3ac3ad89ec71a2260e5292f8ca07d0bc 

Second 
When you hold your mouse over the widget the image goes inwards and a photo of the website that is in question pops out along with a mobile version of the website too. Also, you can see some more text and a link to the website.
Functionality: https://gyazo.com/229a76c193c5637137677187efd73980

This feature works perfectly for a web design company or for someone who has a portfolio of some sort, someone who wants to show his previous work.

Source to where I found this feature: https://www.digitalsilk.com/web-design-company

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
