### ISSUE TITLE
Jetsmartfilters active tags widget double `::` 👀👀

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5654]
I don't know what happens with jetsmartfilters but it displays double `:: `
while I didn't put in filter label and active filter label or the others I have checked everywhere

![Capture d’écran 2022-07-17 174123](https://user-images.githubusercontent.com/82481592/179416732-15c3bd05-d8b9-4f33-b9c7-ca436fc04fdc.png)

![Capture d’écran 2022-07-17 174806](https://user-images.githubusercontent.com/82481592/179416816-2dc69847-2fad-47d0-9674-648e6e898793.png)

the absence of control over certain elements also such as the
**look at the reset button**

```
selector .jet-smart-filters-active-tags .jet-active-tag {
     font-size: 14px;
}

selector .jet-smart-filters-active-tags .jet-active-tag {
     align-items: center;
}

```

**Comment by SargasTM** [comment]
done, will appear in the next version
