### ISSUE TITLE
Starting Screen feature request

### ISSUE THREAD

**Issue by MjolnerThor** [CrocoBlock/suggestions#5655]
This feature does not exist in the selection of crocblock widgets. 

First
The first you can see is a screen just for the departments of the website.

Second
Then you can move your mouse to any of the departments to choose which department you want to enter. 
https://gyazo.com/a53817b4894bb80d7aa56772fa648549 - GIF

The reason for the feature.
The reason for the feature is that it makes your website more alive, and you can also make it so that you can have more departments to choose from than just 2 choices. For example, if you have 6 different departments for your website then you can just add 4 more columns. It gives the visitors more of a presentation.

Source where I found the feature: 
https://www.knoppbio.com/

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
