### ISSUE TITLE
Wishes by field type "Map"

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#5656]
Hello, I see you have added a new "Map" meta field as per my longtime request https://github.com/Crocoblock/suggestions/issues/1354, thank you for that.
But your version of the functionality does not take into account two important points:

1. Manual address entry
2. Autocomplete when entering an address based on hints from Google Map or other maps. 

Example: https://drive.google.com/file/d/1wWh5juRlTmsa_bLqcY7UElaJgQnIFel1/view

**Comment by fostira** [comment]
+1 Much-needed feature! 

https://github.com/Crocoblock/suggestions/issues/5623

**Comment by sahilpopli** [comment]
+1 

also do add a button to fetch the user location for the map field. So we can create forms to get user location for User meta as well as CPT/CCT.

**Comment by antoinelbch** [comment]
+1

**Comment by kaskad88** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5624, which is on the same subject so we could deal with it more efficiently.

**Comment by kaskad88** [comment]
Added in JetEngine v3.1.0
