### ISSUE TITLE
JetSmartFilters don't work with URL with filtered value

### ISSUE THREAD

**Issue by riandeodato** [CrocoBlock/suggestions#5657]
Hello! How are you?

I have a problem: I created a snack menu for a hamburger restaurant website, which you can see here: https://pits.riandeodato.com/cardapio.

The JetSmartFilter for taxonomies that filters snacks by category is working correctly, but I'm trying to use the URL with filtered value functionality on the homepage of the site here: https://pits.riandeodato.com/url/

The problem is that when clicking on the first card: "Opções de Carne", the menu page is filtered correctly (The link is: https://pits.riandeodato.com/cardapio/?jsf=jet-engine:resultados&tax=categorias- menu:6), but if I try to click on another filter above, for example "Frango", it doesn't filter anymore (the link is with something I don't know how to remove https://pits.riandeodato.com/cardapio/?jsf= jet-engine:results&tax=categories-menu:7%2C6%2Coperator_AND).
This: **%2C6%2Coperator_AND**

I tested my filter with AJAX, mixed and page reload and nothing worked. I'm desperate, I've tried everything.

Please, help-me! :/

**Expected behavior**
The operation expected by me is that when clicking on the home card with URL with filtered value, the menu and filters work normally.

**Screenshots**
![radio-filter](https://user-images.githubusercontent.com/5727798/179604367-b0eb1397-0790-4fcf-ae1a-090539ed9185.png)
![button-URL-with-filtered](https://user-images.githubusercontent.com/5727798/179604363-9889b142-a54f-4f15-bba1-f38ea1e99b59.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 103.0.5060.114

**Comment by Floydtm** [comment]
Your request is not a bug. It seems to me that you initially chose the wrong direction. You cannot filter by category while in a category. You need to think differently about the whole logic of work
