### ISSUE TITLE
simple BUG / If the jet menu is enabled, the crocoblock icon will be removed from the dashboard.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5665]
**Describe the bug**
When I activate the jet menu plugin, the crocoblock icon is removed from the dashboard : https://prnt.sc/ZDUPHx5qtASQ

**To Reproduce**

Just activate the jet menu plugin.

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
