### ISSUE TITLE
Check-in Date Blocked For New Booking - Losing 1 Night Between Stays

### ISSUE THREAD

**Issue by Veekay2001** [CrocoBlock/suggestions#5666]
Hello,

I recently made a booking system with JetBooking but the check-in date for 1 booking can not be taken as a check-out date for the previous booking. For example: 
Person 1 books from Jan 1 - Jan 5
Person 2 books from Jan 6 - Jan 10
This leaves the room empty on the night from Jan 5 - Jan 6. If person 3 wants to book this night, Jan 5 can be selected as check-in but Jan 6 can **not** be selected as check-out, therefore, it can't be booked and the room will stay empty for 1 night. This is a big issue with this plugin because it means that the room will stay empty every night before a new booking, it makes covering your cost as a business very difficult...

The JetBooking plugin has the potential to be a great plugin but without a fix to this issue it is close to useless, I would very much appreciate it if you could look into this issue

Thanks in advance!

**Comment by UraraReika** [comment]
I merged this issue with [#3755](https://github.com/Crocoblock/suggestions/issues/3755), which is on the same subject so we could deal with it more efficiently.
