### ISSUE TITLE
add a feature for variation images with color , size in single product 

### ISSUE THREAD

**Issue by imranch9417** [CrocoBlock/suggestions#5670]
hi Crocoblock 

i suggest you to add a feature in your group of plugins or add a addons 

if suppose a single product have multiple color then your current plugins can not handle or do not have option to add multiple images with variations (yes it have one image option with each variation  ) at least 4 to 6 images 
we can show 4 to 6 images with one variation like single color images but not with multiple color images 
and also it's not compatible with others 3rd party plugins 
so a person can not add multiple variation images  for now while using your group of plugins 

details..
if suppose a product have 2 or more colors like red , blue , green and so on 
it's must work when we click on green color it'll show at least 4 to 6 images related that color , when we click on red  color it'll show at least 4 to 6 images related that color and same like other colors as well 
i try at least more then 3 weeks but in the end i'm going to deactivate this plugins 

it's lost of my a lot of time and money as well 

https://user-images.githubusercontent.com/103455220/180196496-3ec213b2-4c2a-4ca8-aa58-2f8ba2010d50.mp4

now i need to buy other plugins to fulfill my requirements  

Best Regards for future  

https://user-images.githubusercontent.com/103455220/180197218-54b59698-3aba-40e6-b308-5fbc00bb51e6.mp4

**Comment by UraraReika** [comment]
I merged this issue with [#2619](https://github.com/Crocoblock/suggestions/issues/2619), which is on the same subject so we could deal with it more efficiently.
