### ISSUE TITLE
Progress bar for product grid widget carousel (jet woobuilder)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5672]
It would be great if you add a new feature in the product grid widget so that if autoplay is enabled, we can display a progress bar to users. 
Check out this feature in the video below

https://user-images.githubusercontent.com/88034902/180246995-0ffbd367-6908-4bfd-aef5-739d9d7d9ed6.mp4

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
