### ISSUE TITLE
Jetformbuilder WYSIWYG field does not keep formatting ⚡

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5676]
for some reason jetformbuilder does not support emoji on WYSIWYG field

this situation, which went unnoticed for me, has become visible and embarrassing because now we almost only see that from the moment you notice it

How to reproduce the bug 🐛 

1 - post a simple post with title and content like I did, put a layout with emoji

![Capture d’écran 2022-07-23 004430](https://user-images.githubusercontent.com/82481592/180582252-c3bb6fe2-1a1f-49fb-bdf8-aa2ac643835a.png)

2 - create a simple edit post form to edit this post, you will see that the layout is not the same

![Capture d’écran 2022-07-23 004350](https://user-images.githubusercontent.com/82481592/180582260-9f2a7e42-f8ba-4a12-9154-fed1f48b81e1.png)

editing posts in the backend is necessary because of SEO (rankmath type plugins etc) the consequence all posts seen through jetformbuilder will lose their formatting

**Comment by girafffee** [comment]
@nreljed Hi
This code snippet can fix it.

```php
add_filter(
    'jet-form-builder/fields/wysiwyg-field/config',
    function ( $config ) {
        $config['tinymce'] = array_merge(
            $config['tinymce'],
            array(
                'paste_as_text' => false,
                'paste_auto_cleanup_on_paste' => false,
                'paste_remove_spans' => false,
                'paste_remove_styles' => false,
                'paste_remove_styles_if_webkit' => false,
                'paste_strip_class_attributes' => false,
            )
        );
        return $config;
    }
);
```
