### ISSUE TITLE
Jetengine dynamic tag in redirect after delete ⚡

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5682]
it would be so simple and efficient if i had a dynamic tag in redirect after delete in dynamic link

there are so many possible scenarios to configure

![Capture d’écran 2022-07-24 151001](https://user-images.githubusercontent.com/82481592/180651022-da21e295-2d73-4fb9-992f-b546d9fea9aa.png)

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.4
