### ISSUE TITLE
layout changes when selecting smartfilter checkbox (Gutenberg) 

### ISSUE THREAD

**Issue by rlb222** [CrocoBlock/suggestions#5683]
**Describe the bug**
On a page with a smartFilter checkbox and a Listing Grid, when I select the checkbox: 
The page layout is changed, because the flexbox CSS of the listing grid is changed.

The Listing Grid has flexbox rows and stacks. And the CSS of these is altered:
1. The row definition is changed to a stack (`flex-direction: column;`). So all content next to an image is now placed under the image.
2. The first item from the list, the CSS is changed also. 
 
This is (what i found) due to changes in the definition of the `.wp-container-<nr>` after filling in the checkbox from the smart-filter.

```
example of the inline styles that are changed
 <style>
    .wp-container-2 {
        display: flex;
        gap: 0.5em;
        flex-wrap: nowrap;
        align-items: center;
    }
 </style>
```

**To Reproduce**

_Setup_
1. Create a Listing Grid (CCT in my case) with a row. In the row there is on the left side: an dynamic image. on the right side a couple of rows (5) each with 1, 2 or 3 dynamic fields from the same CCT.
2. Create a radio smartFilter for on field of the CCT ( a yes/no field in my case)  
3. Create a page in Gutenberg blocks editor
4. Add a column block. 30% 70%
5. In the 30% block, put the smart filter type radio (from 2), with 'filter for: listing grid', 'type: Ajax'. 
6. In the 70% block, put the Listing Grid from (1.)

_Try the behaviour_
7. Open the page (from 3), you see a radio on the left and a list of entries on the right. Nothing in the radio is selected.
8. Click on the radio to select. The list of items is changing due to the filter.  _The problem is the appearance is changing (because of the changing CSS)_

**Expected behavior**
I expected for the layout of the elements to remain the same after using the smartFilter.

**Actual behavior**
a. All the content of all the items are ending up beneath the image, and
b. Only with the first item, there is an extra change: The first row was also changed into a stack. 

**Screenshots**
<img width="935" alt="Screenshot 2022-07-24 at 17 38 34" src="https://user-images.githubusercontent.com/10956492/180655066-818bdd5b-8bba-4752-813a-13a153675962.png">

<img width="1031" alt="Screenshot 2022-07-24 at 17 38 42" src="https://user-images.githubusercontent.com/10956492/180655073-5ac1a839-ad08-4473-9a9a-b85277da4929.png">

**Desktop**
 - MacOS
 - chrome and safari
 - JetEngine 3.0.1, JetSmartFilters 2.3.12 

**Additional context**
I see there is a shift in the definition of the inline CSS: `.wp-container s`. The first of the containers seems to be affected after the selecting of the checkbox.

I hope you have enough information to examine and fix this!
Thanks, René

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
