### ISSUE TITLE
Typo in get_settings('lisitng_id');

### ISSUE THREAD

**Issue by mateitudor** [CrocoBlock/suggestions#5684]
**Describe the bug**
There is a typo in your method for getting listing ID's: **'lisitng_id'** instead of 'listing_id'.

**To Reproduce**
$listing_id = $listing_grid->get_settings('lisitng_id');  → works ✅

**Expected behavior**
$listing_id = $listing_grid->get_settings('listing_id'); → fails 🛑

**Comment by MjHead** [comment]
Yes, its known issue but unfortunately at the moment we need to process it as is due to backward compatibility reasons
