### ISSUE TITLE
JetWooBuilder: Functionality to allow different types of zooming on product images

### ISSUE THREAD

**Issue by WEBLOTI** [CrocoBlock/suggestions#5686]
It would be great if the individual image widgets have the functionality to allow you to choose various types of zoom in such as: Lens, Windows, Inner and at the same time also allow to choose the type of cursor like: crosshair or cursor....

This is something that can already be done with free plugins like "Product Image Zoom for WooCommerce" but why install another plugin if it can be integrated to JetWooBuilder?

This is something simple that a developer would not take long to do, I think it would add value to the plugin.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by WEBLOTI** [comment]
I understand that there are other priorities for you but I don't understand why you have to close it and mark it as completed if it is not. 

Although it says that in the future you do not exclude it. The truth is that I don't know what is going on with your customer service but these last few months you have been handling it very badly. 

I thought that's what this channel is for. "Open suggestions for features that one may need whether or not it is a priority for you'.
