### ISSUE TITLE
Custom icon for single rating and product grid & product list widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5688]
Please add the possibility of inserting a custom icon (svg) to the rating stars of single rating, product grid and product list widgets.

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello! Thanks for the feedback.

At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. Right now in our widgets we use our custom icons and default WooCoomerce aproach so the rating functionality works proper. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
