### ISSUE TITLE
Extra features for listings builder

### ISSUE THREAD

**Issue by sigersmit** [Crocoblock/suggestions#569]
- When building a listing it would be nice to make the whole box linkeable, with the post url or a custom URL
- When using a **Dynamic field** option and the Object source is Excerpt and the Automatically generated excerpt is on > The option to set the number of characters the excerpt may have
-  When using a **Dynamic Link** field, set the kind of URL, like mailto: , tel: or url.
- When using **Dynamic Link** and **Dynamic Field** and **Dynamic Terms**, have the option to set display inline, so we can place multiple items horizontally. (maybe in the way Dynamic Meta is done?)

**Comment by MjHead** [comment]
done
