### ISSUE TITLE
JetEngine Dynamic Link Add To Cart with New Features

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#5693]
Guys I was so happy to see the changelog about the update, but disappointed to see the new feature working for Dynamic Link.

The first is that when I select the source add to cart I can't enable the quantity button.... I need this adjustment to be able to uninstall JetWooBuilder from my site, believe it or not I use it just because of the Add To widget Cart that works perfectly.

The second problem was that when applying a Standard visual style from the site to the listing item it was perfect, but the button was very bad at the front end, it didn't work at all and completely broke the layout of the listing and it was a horrible gray button.

The most interesting is it worked with Ajax and I can change the Label of the button, that's great, my main product page is an Archive page, so I had no problem with Ajax, but I haven't tested it on a normal page.

Kindly guys, make an effort to make this dynamic Link Add To Cart functionality more complex

Thanks

**Comment by DaviAppelDuarte** [comment]
+1

**Comment by dyonatandias** [comment]
+1

**Comment by PPharma** [comment]
Please add this soon.

**Comment by hamed-azimi** [comment]
Great work so far with the recent updates. Not much is remaining to achieve this. I hope to finally see it fully implemented. A full, feature-rich add-to-cart widget with the rich support of ajax and a quantity field is a boost for sales.

**Comment by zahnd** [comment]
+1

**Comment by hamed-azimi** [comment]
Any update on this?

The other issue was created 1.5 months before this was closed although it wasn't fully implemented, telling the remaining part will be implemented in this issue.

But this one also is not finished after months.

Now you only need to add a quantity field to fully finish this (or simply copy that one widget from WooBuilder to JetEngine)

**Comment by tizum** [comment]
I keep waiting for these improvements, I even lose performance on a site by using jetwoobuilder.

these quantity adjustments would be great and also about the style of the button and choosing the quantity.

**Comment by SINFOUND** [comment]
Why is this taking so long? Please add this. its not trivial to have.

**Comment by UraraReika** [comment]
Hello everyone, right now this task in the work and soon will be released.

Thank you for your understanding.

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.9
