### ISSUE TITLE
Jet Woo Product Gallery Causing Conflict

### ISSUE THREAD

**Issue by vincent20022** [CrocoBlock/suggestions#5696]
**Describe the bug**
Error Causing a conflict to some plugins

**To Reproduce**
1. Install Variation Swatches for Woocommerce
2. Enable Variation Swatches and Jet Woo Product Gallery
4. See error on developer tools by inspecting element

**Screenshots**
![image](https://user-images.githubusercontent.com/47505842/181177875-a015bbe3-33ac-4638-a3fb-f70f679cf042.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Chrome

**Comment by UraraReika** [comment]
Hello @vincent20022 !

Thanks for the feedback.

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
