### ISSUE TITLE
Some new features for jet compare & wishlist plugin > compare page

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5698]
**Please, describe the feature request, making it clear to understand.**

hello
Please check the following if possible...

1- Box shadow for Add to Compare button (Like #5317) Maybe you have added it in the new version. I haven't reviewed it yet
2-[Horizontal and vertical alignment](https://prnt.sc/PxNFLJBPXR-O) for remove icon (Now the icon is on the left side) : https://prnt.sc/EHXrE6-4g-xe
3- Custom width for the remove button : https://prnt.sc/-HVFVpPBx27v
4- By adding the above, [this control](https://prnt.sc/U2XRGduMSWIQ) will be useless.
5- Ability to display the remove button, [in the product image District](https://prnt.sc/xBu-V13wHJKM). Currently we can only assign one row to the remove button. This can be a limitation for the ui. Please add this feature if possible. So we can put the remove button next to the product image : https://prnt.sc/oU_6Qiu6rssw
6- Possibility to disable the link for the product title
7-Tooltip for title
8- [Trim Type](https://prnt.sc/Ys2DQKun0ukX) for title
9- Horizontal alignment for product titles
10- Thumbnail size control
11- Horizontal alignment for Thumbnail
12- [Two new controls](https://prnt.sc/iuZR36CHSmMV) for displaying prices in the comparison widget.
13- Support for custom empty comparisons (Maybe you have added it in the new version. I haven't reviewed it yet)
14- border radious for Thumbnail

<hr>

Finally, there are two important things for this widget...

1- In this widget, the style tab options are not displayed conditionally. For example, if we disable the add to cart button in the product grid widget, in the style tab, all the controls related to the add to cart button will be hidden. It's great and makes everything look useful.
But in this widget, I didn't add the add to cart button, but there are [controls](https://prnt.sc/WVmJRZNatI96) for it in the style tab. Or, for example, I have disabled product descriptions, but its controls are still displayed in the style tab. (Of course, this issue exists for all options of this widget and they are not displayed conditionally.)

2- As a suggestion, it would be great if you add the add to wishliset option to the [data type](https://prnt.sc/QBn46oQhJGVH) section. We can add an add to wishlist button so that users can add their desired product to the wishlist.

thank you

**Comment by UraraReika** [comment]
1 - 1.5.1 release.
2 - We will not implement this controls, but will add some additional default styles to keep elements centred.
3, 4, 5, 12 - This functionality will not be included in the core of the plugin.
6, 7, 8 - Use `'jet-cw/template-functions/title’` hook to modify title output whatever you want.
9, 10, 11 - Exist for Wishlist widget. But this functionality will not be added for the Compare table widget.
13 - Use this solution https://gist.github.com/UraraReika/e9f09e16c678e78a6f9bfc85fc0d765a. Like in Products Grid and Products List widgets.
14 - Done.

Important things
1 - This is not possible in this situation.
2 - Done. Wait for next release.

For the future point to exact widget where you want to see changes or improvements.

**Comment by 79ho3ein** [comment]
thank you @UraraReika.

>For the future point to exact widget where you want to see changes or improvements.

Sorry, I didn't understand what you meant

**Comment by UraraReika** [comment]
Specify the widget in which you want to add changes

**Comment by 79ho3ein** [comment]
> Specify the widget in which you want to add changes

thank you

**Comment by yousef-miri** [comment]
Why isn't there an option to create an empty wishlist template?
