### ISSUE TITLE
JetEngine: A way to add metaboxes or custom fields to product attributes (not terms)

### ISSUE THREAD

**Issue by chipweb** [CrocoBlock/suggestions#5700]
Hello.

After speaking with the support team, I have found that there is no way with JetEngine to assign metaboxes to WooCommerce product attributes. 

Please do not confuse this with product attribute terms. With these you can add metaboxes but not with the attributes themselves. Here is a screenshot:

![image](https://user-images.githubusercontent.com/25765113/181239455-3fe07469-3562-476b-b069-4708de7da273.png)

**Comment by Floydtm** [comment]
You need to create custom attributes and only then you can attach custom fields to them https://prnt.sc/MqlZz66YzY0W https://prnt.sc/bKSMO0cX8TH1 https://prnt.sc/84J93N496UvN

**Comment by chipweb** [comment]
With that method we can attach custom fields to the terms of the attribute. I was suggesting to add custom fields to the attribute (not terms).
