### ISSUE TITLE
Additional providers in Gutenberg

### ISSUE THREAD

**Issue by dislokacia** [CrocoBlock/suggestions#5704]
If there are 2 Listing Grids on the page and we need to filter only the one of them, then in elementor pagebuilder we can connect the filter and provider via [CSS ID ](https://prnt.sc/XWvZLNtw-BOz) and [this one](https://prnt.sc/45Os0-29bjkh)
But in Gutenberg at the moment there is no such possibility to connect the filter with provider and there is no possibility to [add the additional provider](https://prnt.sc/OF3u6qiRZ6P7).
Could you please add it in the next updates?

**Comment by MjHead** [comment]
Will be added with JetEngine 3.0.3 update. Closing here to avoid duplicating, because same issue already added into our roadmap

**Comment by sahilpopli** [comment]
+1 i also reported the same yesterday
