### ISSUE TITLE
Lazy Load button makes CSS disappear (like .wp-container-99 )

### ISSUE THREAD

**Issue by rlb222** [CrocoBlock/suggestions#5711]
**Describe the bug**
When I set 'Lazy Load' to true on a Listing Grid, the css definitions of the `wp-container-99` are deleted.
This makes the flex box definition disappear.

Everything here is done in Blocks (Gutenberg), no elementor.

**To Reproduce**
1.  I have a (blocks) jet engine listing with the definition of one property name: 'myproperty'.  I have rows and stacks (flex box) to define the layout. 
2. I make a new page 'mypage'. I place a Listing Grid with the name 'myproperty' 
3. When I view the page, the text and the picture are shown next to each other. Just like I designed it.
4. I go back to the page 'mypage'. And set the 'lazy load' of the Listing Grid to 'on'.5. 
5. When I view the page, the text and the picture are shown _beneath_  each other. In the CSS the definition for the flex box (`display: flex`) has disappeared. The definition for the '.wp-container-26' is not present. That was the place where the `display: flex` was defined.

**Expected behavior**
I expected the CSS definition not to disappear when setting 'Lazy Load' on. 

**Screenshots**
***Lazy Loading off***
<img width="869" alt="Screenshot 2022-07-29 at 18 31 49" src="https://user-images.githubusercontent.com/10956492/181804297-5739bd0c-e401-4848-becb-37addf6d8e44.png">

<img width="284" alt="Screenshot 2022-07-29 at 18 32 00" src="https://user-images.githubusercontent.com/10956492/181804304-9e427827-a2b2-4d39-a00c-c19ab7cfc46d.png">

***Lazy Loading on***
<img width="706" alt="Screenshot 2022-07-29 at 18 32 09" src="https://user-images.githubusercontent.com/10956492/181804316-e604bb41-b8bb-4f25-9479-93f6c538d30b.png">

<img width="260" alt="Screenshot 2022-07-29 at 18 32 19" src="https://user-images.githubusercontent.com/10956492/181804326-3e6d8ae8-e826-41a3-a4bc-f9b20b2091f7.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome, safari
 - Version: current

**Additional context**

**Comment by rlb222** [comment]
It's maybe connected to issue #5683

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
