### ISSUE TITLE
Custom Content Type for Calendar Widget

### ISSUE THREAD

**Issue by DeaDy0001** [CrocoBlock/suggestions#5718]
Hi, i am Michael

I am building a website for my company and would like to set up a calendar for my customers.

YouTube streams should be displayed there. This can also be multiple streams for each project.

for the performance of the website it is certainly better if the streams do not have to be created in CPT, since no single page is required either.

Is it possible to add a possibility for CCT to the calendar widget?

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.4
