### ISSUE TITLE
bug in product grid widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5720]
After updating to version 2.0.1 in the product grid widget in the grid item section, the box shadow option has been removed in the hover tab. This has caused all product carousels that used the hover box shadow to be disabled. Please fix this problem. I can't go back to the previous version

**Comment by Michaelgimii** [comment]
@UraraReika

**Comment by 79ho3ein** [comment]
#5689

**Comment by UraraReika** [comment]
2.0.2 release.
