### ISSUE TITLE
🔥 Jet Engine Feature Request - Allow Meta Data Entry in Elementor Editor

### ISSUE THREAD

**Issue by perks98** [CrocoBlock/suggestions#5726]
Using Jet Engine it would be good to have additional compatibility with Elementor page builder plugin so that users can input Jet Engine custom metadata or taximonies while editing the page that has those fields in the Elementor editor.

Currently you can only add and edit Jet Engine custom fields in the edit page dashboard, so users have to go to two locations of there to update the custom field data and the page builder to edit the style of other areas of the same page.

**Current location (bottom of page edit):**
![Screenshot_482](https://user-images.githubusercontent.com/55829113/182563107-f437bc45-0d2e-47eb-bdc1-74e7de833eb6.jpg)
 

**Ideal Elementor page builder spot:**
![Screenshot_483](https://user-images.githubusercontent.com/55829113/182563222-cdefbded-d8fd-4333-a340-ba9fe81ac925.jpg)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by perks98** [comment]
Hi @Floydtm. I think this is a big missing feature as I get a lot of customers struggle using WordPress and Elementor for the first time, asking them to go to the page edit section as the very bottom is another step which shouldn't be needed. I can understand there are other nicer features but I see this as a quality of life feature as I feel there are more priority updates around Gutenburg which is a shame really as there are more people using Elementor or other upcoming page builders.

If not this feature request would you be able to look in to meta data positioning on the page. For example, if you add meta data fields to the Pages post type, rather it being at the very bottom can there be a feature so you can position it below the title, before the content area input, or even on the sidebar?

**Comment by Floydtm** [comment]
In the admin panel, you can configure everything as you like. https://prnt.sc/1XUhDw8-swM_
