### ISSUE TITLE
500 error when try to save a listing

### ISSUE THREAD

**Issue by chenisra** [CrocoBlock/suggestions#5727]
I create a listing item.
when I try to save it at elementor I get a 500 error.
I increased the memory limit and still happaned.
after that, I try to deactivate plugins
and still get a 500 error.
after that, I try to change Jet engine version from 3.0.2 to 3.0.1,
and finally it worked.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
