### ISSUE TITLE
Possibility to customize the add to compare widget message - jet compare & wishlist

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5729]
**Please, describe the feature request, making it clear to understand.**

hi

As you know, we can only compare 4 products. If the user adds a fifth product to the comparison list, a [message](https://prnt.sc/erjx99N1NQs_) will be displayed.
This message cannot be customized at this time. So it would be great if you could add controls to customize this message. **Some controls such as :**
1- Ability to edit text message
2- Message popup shadow control
3- typography
4- Absolute length and width of the popup and other required controls

thank you!

**Comment by UraraReika** [comment]
Possibility to change the message will be added in the next version of the plugin. But style controls will not. The layout of this message separated from the widget and can't be styled from it. And make options inside dashboard is old styled and messy. So in this case we recommend you to use simple CSS. The message has two unique classes `jet-compare-message jet-compare-message--max-items` that can be used like this:

```
.jet-compare-message.jet-compare-message--max-items {
    // your CSS here...
}
```

**Comment by 79ho3ein** [comment]
thank you @UraraReika
