### ISSUE TITLE
Allow post parms and other settings to be added to widegets, notibaly the products grid. :)

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#573]
I'm trying to build products and show only related products on some of my pages for a business listing, the issue comes where im using the products grid widget on my main shop page, and it is impossible to design the same layout with a listing grid, sales, badges, currency symbols, etc.

Please, can you fix this so we can use post parms on the product grids widget and then I can directly add this to a business page without having to build a listing grid?

thanks

**Comment by scubaninja1977** [comment]
Might be better to have the ability to have the post parms added to widgets so we can show related or other macros in accordance to our needs. :)

**Comment by Floydtm** [comment]
@scubaninja1977, Hi! if you use the listing grid widget then you need to build a single item with meta fields for discounts, currencies, etc. If you use the product grid widget, then it has such an option http://prntscr.com/pwgneu. If none of the options suits you, then describe your request in more detail. Thank!

**Comment by UraraReika** [comment]
Hi @scubaninja1977, we're going to close out this ticket for now due to inactivity. Please let us know if you still need any help and we'll be glad to reopen and troubleshoot further.
