### ISSUE TITLE
Some suggestions for improving the single rating widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5730]
**Please, describe the feature request, making it clear to understand.**

hello
Please consider the following to improve this widget : 

1- Custom icon (svg)
2- Full control over text editing (The [text editing feature](https://prnt.sc/eRByxYek3pon) has been added in the new version. But [parentheses](https://prnt.sc/8m02w12cGnYC) cannot be controlled.)
3- The possibility of displaying the variable (number of review) in the text. This is available in elementor : https://prnt.sc/s0PuGr51L_q9
4- Ability to move stars to the other side of the text (Suitable for multilingual sites) https://prnt.sc/fiP5xGIkMhGK
5- Custom ID for text link - if we click on the text of this widget, [there is an ID](https://prnt.sc/Hkcon0jjr9Zv). This id will move the user to the comments section. **Please add this feature so we can change this id and have control over it.**

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein! Thanks for the feedback.

1 - Unfortunately we do not plan to introduce such functionality the core of our plugin. But in the future we do not exclude the possibility of adding this functionality to some of add-on.
2, 4, 5 - Will be in 2.1.0 version of plugin.
3 - This is not a widget but Dynamic Tag. And we will not add such functionality to our plugin. With the help of previous point you will be able to achieve desirable result.

Thank you!

**Comment by 79ho3ein** [comment]
Hi @UraraReika , thank you
