### ISSUE TITLE
Jet engine + SmartFilter with Bricks = perfect combination

### ISSUE THREAD

**Issue by LuisYGM** [CrocoBlock/suggestions#5732]
Do you plan to integrate jet engine and smart filter with bricks in the future?

**Comment by hb81010** [comment]
+1

Performance was never excellent because of Elementor. Since the 3.6 Elementor update, the dynamic elements have become much slower.
Elementor is a bottomless pit and I would also be happy if all plugins were compatible with Bricks.

I use Elementor only because of Crocoblock

**Comment by desupero** [comment]
It's time that the team at CB really started to develop with Bricks in mind and allow all elements that only work with Elementor (JetTricks) to work in Bricks as well. People are leaving Elementor in droves, but the CB team seem unaware of this fact.

**Comment by MjHead** [comment]
Integrated since 3.1.1, with later updates planned to add more features to this integration
