### ISSUE TITLE
jet woobuilder product grid box shadow ux

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5734]
In a recent update, the box shadow option added to hover section. 
**But one question...**
Why is the box shadow option removed from the blue section and moved to the red section? https://prnt.sc/crcincOTvZFP
This was not a smart change. Because if the user enters the hover section, he will see two shadow box options, which can be misleading.
https://prnt.sc/txeYKFPpxwnD

Therefore, I think it is better to move the shadow of the normal mode box to its previous section, below the background color. This creates a much better ux. https://prnt.sc/z0ttXuoDvAgv

**Comment by UraraReika** [comment]
Check out latest release 2.0.3!
