### ISSUE TITLE
Nested Listing Grids

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#574]
Allow the ability to nest listing grids, so for example, I have a venue and events that are linked to the venue, I would need to create a listing gird for events and then listing grid for venues, but in the venue I would need to nest the events listing grid, currently you can do this but the search functionality only works on page reload, which is not practical if you have multiple filters configured.

This will open you listing grids and search functions and actually put you miles ahead of many of your competitors as I have researched and this is not doable in many other plugins.

**Comment by scubaninja1977** [comment]
If you need an example of a website where you can test out what asking, then let me know I have a working site, but the only flaw for this is the ajax filters. thanks

**Comment by scubaninja1977** [comment]
I believe the thing that is missing the fact that currently, jet smart filters is not able to search through an ajax array, so when you filter it only searches and returns the results in the first section attached to the first venue, and when you reset, it will replace all the events on the venues with that in the first venue.

**Comment by fvenuto** [comment]
Hi, i've the same issue. 
How did you manage to solve it? @scubaninja1977

**Comment by MjHead** [comment]
done

**Comment by trybguet-dev** [comment]
@MjHead where is the fix available? Or in which version will nested listing grids allow for Jet Smart Filters to work properly?

**Comment by trybguet-dev** [comment]
@MjHead could you please explain how this was fixed? Nested grids are still not working with filters in the current version. Thank you.
