### ISSUE TITLE
Product title length in jet woobuilder plugin

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5743]
**Please, describe the feature request, making it clear to understand.**

hi @UraraReika 
Your plugin is really great. But I had an important request for it...
Currently, we can set the length of product titles in words or letters. But this has an important drawback. The problem is that if, for example, on the desktop, we consider the length of the title to be 40 characters and the title is displayed in two lines, it will be displayed in 3 or 4 lines in mobile. I didn't really find any solution for it. 

So, if possible, please add a new feature to manage product title length. So that we determine the length of the product title based on the number of lines. If we consider two lines, on all devices, the title will be displayed in only two line, which is really great.

For example, here the line length is set to 2 and only two lines will be displayed. The rest of the content is displayed as three dots : https://prnt.sc/7GbeT-jbcRAn
As a result, the third line will never be displayed.

If it is possible for you, please add this to the plugin in the next update. please.

**Comment by UraraReika** [comment]
Hello @Joliamendi!

I merged this issue with [#4948](https://github.com/Crocoblock/suggestions/issues/4948), which is on the same subject so we could deal with it more efficiently.

Thank you!
