### ISSUE TITLE
Quantity selector and Load more clash

### ISSUE THREAD

**Issue by jimhuds** [CrocoBlock/suggestions#5748]
When scrolling infinite scroll with the Load More devtool, the custom quantity selectors from the Quantity Selector devtool disappear back to default after first scroll.

**Comment by UraraReika** [comment]
Hello @jimhuds! Thanks for the feedback.

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. https://support.crocoblock.com/support/home/ 

Thank you for your understanding.
