### ISSUE TITLE
Smart Post Tiles Layout

### ISSUE THREAD

**Issue by woofyoso** [CrocoBlock/suggestions#5753]
Hi all. I hope you are doing well. :)
I have a nice feature to propose. It would be great if we have an option to change the Smart Post Tiles Layout separately for every device and also to have an option to choose one tile so we can create nice sliders :)
With this option/setting, the widget will be even more powerful.  \o/
https://imgur.com/JDagqjP

Many thanks for considering my request.
Igor

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
Right now you can use this [solution](https://crocoblock.com/plugins/jetgridbuilder/)
