### ISSUE TITLE
bug : category grid widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5755]
In the category grid widget, if a category is empty, the manual selection option will not find it. https://prnt.sc/IxPwLjFeUB5a

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

Please describe your issue in more details. Your screenshot doesn't show the full picture.
What category is empty? What should option find?

Thank you.

**Comment by Michaelgimii** [comment]
hi @UraraReika , Let me put it more simply. In the [select id](https://prnt.sc/r0fFCwLf6f9T) method, we can display a category even if it is empty.
But in manual selection method, we cannot display any empty category. A category must have at least one product so that we can select it manually.
While this option is disabled : https://prnt.sc/HcxK4vxBmT4N
Generally, the problem is that if a category is empty, we cannot select it from [this section](https://prnt.sc/V0qGsLmQxMg-) to be displayed. Even if it is empty.
This is the case even with the product grid widget : https://prnt.sc/dmLw9Yzm9m0g

**Comment by UraraReika** [comment]
Check out latest release 2.0.3!
