### ISSUE TITLE
Request for a new jet plugin (only for elementor)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5757]
hi crocoblock team!

I had a request for your team to produce a new plugin for elementor. This plugin will be a very simple but wonderful plugin.
As you know, elementor is the biggest WordPress page builder and it's getting bigger every day. But in all its sections and widgets, it has deficiencies. If you look at the elementor github, there are hundreds of requests from users who have a series of simple requests. But since elementor has priorities for publishing its updates, it can take ages to add a small request.

**What is the new jet plugin supposed to do?**
As I said above, elementor widgets have many shortcomings. This plugin will compensate for these shortcomings. This causes a wave of elementor users to come to crocoblock to file requests to add new features. I will personally buy this plugin.
I will give an example of the development of this plugin...
The Slides widget in elementor does not have the border radius option. This could be a request to add this feature. And many features that elementor currently needs.
Please check this offer. thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
