### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Jet_Dashboard\Utils' not found

### ISSUE THREAD

**Issue by imsadhappy** [CrocoBlock/suggestions#5758]
Fatal error: Uncaught Error: Class 'Jet_Dashboard\Utils' not found in /var/www/wp-content/plugins/jet-engine/includes/modules/modules-updater.php:274

**Stack Trace**
1. Jet_Engine_Modules_Updater->get_update() /var/www/wp-includes/class-wp-hook.php:309
2. WP_Hook->apply_filters() /var/www/wp-includes/plugin.php:191
3. apply_filters() /var/www/wp-includes/option.php:1992
4. set_site_transient() /var/www/wp-includes/update.php:354
5. wp_update_plugins() /var/www/wp-includes/class-wp-hook.php:307
6. WP_Hook->apply_filters() /var/www/wp-includes/class-wp-hook.php:331
7. WP_Hook->do_action() /var/www/wp-includes/plugin.php:524
8. do_action_ref_array() /var/www/wp-cron.php:138
9. {main} thrown in /var/www/wp-content/plugins/jet-engine/includes/modules/modules-updater.php on line 274

**To Reproduce**
Steps to reproduce the behavior: unknown

**Expected behavior**
unknown

**Installed Plugins**
JetBlog For Elementor 2.2.16
JetElements For Elementor 2.6.3
JetEngine 2.11.3
JetEngine - dynamic tables builder 1.0.2
JetEngine - Get attachment file link by ID 1.1.1
JetEngine - Trim string callback 1.0.1
JetMenu 2.1.7
JetPlugins Dynamic Data Addon 1.3.3
JetProductGallery For Elementor 2.1.2
JetSearch For Elementor 2.1.16 
JetSmartFilters 2.3.11
JetStyleManager 1.3.4 	
JetTabs For Elementor 2.1.16
JetTricks 1.4.1 
Elementor 3.5.6
Elementor Pro 3.6.4 

Important: plugins page & wordpress update page are not opening.

**Comment by Crocoblock** [comment]
@imsadhappy 
Sorry for delay! This has been fixed and released in JetEngine 3.2.5

Thank you for report
