### ISSUE TITLE
add "favorites" or "bookmark" button for posts.

### ISSUE THREAD

**Issue by ttsunamitr** [Crocoblock/suggestions#576]
Hello, i know that there is wishlist button woocommerce products. but can you add "favorites" or "bookmark" button for Posts.?

**Comment by Floydtm** [comment]
@ttsunamitr Hi! At the moment, we do not plan to do this. Maybe soon we will do it. You can use this [plugin](https://wordpress.org/plugins/favorites/) for your request.

**Comment by imCorfitz** [comment]
Hi @ttsunamitr - I was looking for same the other day.. This is somewhat supported by Crocoblock today using Data Stores: https://www.youtube.com/watch?v=XfjQS7li9G4. You suggestion here appeared in a Google Search result why I am adding this link for future visitors.
