### ISSUE TITLE
product grid add to cart not displayed

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5762]
**Describe the bug**

hi
If you add the product grid widget, the add to cart button is not displayed : 
![download](https://user-images.githubusercontent.com/77163248/184216685-015a99dc-2654-4422-87e3-b4cd8ece4f53.png)

It actually exists, but it has no style and is completely white. While previously visible (before version 2)
But the text of the button is displayed in the product list widget : 
![download (1)](https://user-images.githubusercontent.com/77163248/184216856-09d8429f-52ce-4e90-8399-42cb231bf633.png)

**A suggestion**

Please change the default style of the add to cart button in the Product grid and product list widgets to make it more noticeable than the current state. For example : 
![download (2)](https://user-images.githubusercontent.com/77163248/184216990-0d947c17-79a0-4e3b-9104-24ed9dbf5089.png)

thank you

**Comment by UraraReika** [comment]
Check out latest release 2.0.3!
