### ISSUE TITLE
Custom icon for add to cart Button in product grid / list widgets + other things

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5763]
**Please, describe the feature request, making it clear to understand.**

If possible, please check out these few suggestions for improving the add to cart button in product grid / list widgets.

1- Please add custom icon for add to cart button of product grid / list widgets.

2- Possibility to edit the add to cart text

3- If the Quantity Input option is off, [this option](https://prnt.sc/HPtu1dsnE_Ue) will have no effect. Therefore, it is better to display this option when Quantity Input is active. Otherwise, it will not be displayed.

4- Alignment option for add to cart text. Currently, if we increase the width of the button, the text is not centered : https://prnt.sc/yY4pWqppz_ga
(This problem exists only in the product list widget. Of course, you don't need to add text alignment option. Center it by default. Just like the product grid widget)
**notice** : In the product grid widget, if we move the button to the right or left, the alignment of the add to cart text will be messed up : https://prnt.sc/HyReXsIBuKdZ

5- [Custom position](https://prnt.sc/RmC5zSzG73Ru) for Add to Cart button. Using this option + items 1 and 2, we can display the add to cart button in a very beautiful and modern way. like this : https://prnt.sc/95JJDsMBToqu
**This is really cool and many modern websites display the add to cart button like this.**

6- Custom icon to display after clicking the add to cart button - If the user clicks on the button, a custom icon will be displayed. For example, tick icon. This makes the user understand that the product has been added to the shopping cart.

7- Hover animation for add to cart button : https://prnt.sc/o9On-mSzcu8V

8- Because of the translation, the Use default ajax add to cart styles button is out of the box  : https://prnt.sc/Bgi4o2hM_DZQ
To solve this issue, is there a way to move the title of this option to the second line if it is long, so that the switcher button does not go out of the editor box?

9- Automatically align for add to cart widget - If for any reason the add to cart button is https://prnt.sc/LKyDAbINwpNv, this option will do it. There is this feature in elementor post widget : https://prnt.sc/L2ewJyToFkPC

thank you!

**Comment by UraraReika** [comment]
1 - You can use this plugin from dev tools https://tppr.me/2TBHA.
2 - We will not add this feature to our plugins. In this case you can use WooCommerce hooks or some third party plugins. 
3 - This option makes sense even if no input field is included. Example: https://tppr.me/MXQra and https://tppr.me/yNqse.
4 - Fixed.
5 - This options will not be added. There are a lot of different widget presets that you can use. For example preset 2 when you hover on item card the buttons shows like this https://tppr.me/5vgSU.
6 - Track this issue https://github.com/Crocoblock/suggestions/issues/5363.
7 - This feature will not be added.
8 - You can make your editor panel as wide as you want https://tppr.me/9q02v. In other case write about this problem to Elementor support.
9 - Track this issue https://github.com/Crocoblock/suggestions/issues/5364. 

All changes will be available in the next release.

**Comment by 79ho3ein** [comment]
Thank you for your time @UraraReika , Regarding #1, given the 3rd party plugin you created for it, will this feature never be added to the jet woobuilder?

**Comment by UraraReika** [comment]
No it will not.

**Comment by UraraReika** [comment]
Check out latest release 2.0.3!
