### ISSUE TITLE
Bookings start and end time.

### ISSUE THREAD

**Issue by GeckoStudioIbz** [CrocoBlock/suggestions#5764]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work; CHECKED
- if the feature is missing from the products. CHECKED

**Please, describe the feature request, making it clear to understand.**

I need a combination of JetBooking and JetAppointments to make a multi-day booking with specific start and end times. Like this, I could have a booking with specific start day-time and specific end day-time.

For example, I am developing a web site for a Rent a Car, so I need to specificate "I want a car for August 15 at 9:00 to August 24 at 8:30", or "I want a car for August 15 at 9:00 to August 24 at 17:00" and the program calculates how many days (9 days in first case, 10 in second).

Previously, I used "[Car Rental Booking System for WordPress](https://codecanyon.net/item/car-rental-booking-system-for-wordpress/21663173)", but this plugin is little difficult to use and not allow to have a post type view. But for the final web client is the best example.

Image from plugin form.

![image](https://user-images.githubusercontent.com/111125411/184346553-53005298-b704-41d4-896f-9a60b3334a13.png)

In my case, I don't need to have "office", but it would be great option too.

Thanks

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1597, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
