### ISSUE TITLE
bug in jet woobuilder + elementor container

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5768]
If you add three widgets product list , product grid and category grid in a row container :
The Categories Grid widget is full width.
The Products List widget is less than half the width.
The width of the Products Grid is about 90 percent.

Shouldn't those two widgets work like the product list widget? 
Add elementor button widget to compare its width in column and row container.

**Comment by UraraReika** [comment]
I merged this issue with [#4725](https://github.com/Crocoblock/suggestions/issues/4725), which is on the same subject so we could deal with it more efficiently.
