### ISSUE TITLE
JETENGINE Custom Post Meta table

### ISSUE THREAD

**Issue by Lucky5111** [CrocoBlock/suggestions#5770]
On custom post types, jet engine should make another table for them for metadata. 

`[CPT_name]_post_meta` instead of 'post_meta' 

There are two ways you can achieve this, you can use the EAV model which is just like the post meta table, but for only a certain post type. Or you integrate the names of the field into the columns, so instead of meta_key, you would have separate columns for each datatype like price, colour, etc.

You would have to use the EAV model since that is used with wpress.

In turn, this will make queries faster, and less bloated. Think about it like this, you have woocommerce installed, and it takes around 8 keys for the post_meta table, let's say you have 20,000 products. You would have over 150,000 rows in one table. All your queries for custom post types will go slow since they are in the post_meta table, but if it was separate it will be much more faster.

**Comment by Floydtm** [comment]
Right now you can try [CCT](https://crocoblock.com/knowledge-base/articles/jetengine-how-to-create-a-custom-content-type/)
