### ISSUE TITLE
JetEngine: Ability to 'hide' the meta field names from view

### ISSUE THREAD

**Issue by iamdanbarrett** [CrocoBlock/suggestions#5775]
Could there be an option within the meta fields props to 'hide' the name text when editing a post against the meta fields as they are often not required at this level. We attempted to do this via CSS but it also removes the description too as its a single class handling both within the same div. Even if you put them into a separate div would help we could then hide it via CSS

**Comment by kaskad88** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5625, which is on the same subject so we could deal with it more efficiently.

**Comment by absoonoo** [comment]
Easy Use this code in dashboard :
.cx-control__description {
    display: none;
}

**Comment by Crocoblock** [comment]
@absoonoo 
as mentioned in #5625, this option was added in JetEngine v3.0.3 https://i.imgur.com/dci1eL2.png

**Comment by klecka** [comment]
@Crocoblock could you also add this feature for relation meta field?

**Comment by Crocoblock** [comment]
@klecka 
Please, create a separate issue for this
