### ISSUE TITLE
Ability to display the best sellers on the product archive page / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5776]
hi
Using [this order](https://prnt.sc/0-83jgXTsDLG), I want to display a product carousel in the product archive so that the user can see the best sellers of each category. So, for example, if the user enters the Apple category, he can see its best sellers. Therefore, no matter what category you enter, you can see the best sellers of that category.
Is this possible in jet woobuilder now? If not, is it possible to add it? This can be super awesome.
Adding a new query (current category) to [this section](https://prnt.sc/nV_OCjMV-3Su) can make it possible.
I hope there is a solution for this great feature. thanks

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Use this widget option https://tppr.me/3F5RG in combination with this order https://tppr.me/1duz5 from Customizer.
