### ISSUE TITLE
Add options pages Rest API endpoints

### ISSUE THREAD

**Issue by ChrisGV04** [CrocoBlock/suggestions#5777]
**Please, describe the feature request, making it clear to understand.**

I've been working on several projects that use WordPress as a Headless CMS and power the content with JetEngine and CCT, but something that we have not been able to use is Options pages. If we create one, there seems to be no way of getting the values from the WordPress API the same way we use for CCT. As of now, we have had to create a CCT with the options and tell the customer to edit the first item on the table, which looks very strange and on the front-end we have to query only the first item.

It would be really nice to be able to include the options pages inside of the API endpoints so that we can query them using the WordPress Rest API and consume the options on our front-end so that we can totally use WordPress as a headless cms.

It would also be nice if the meta boxes for post types where included on the Rest API too!

**Add an example of where this feature is already implemented.**

Advanced Custom Fields Pro (ACF pro) does it. If you create options pages, add metaboxes or custom post types they are also registered on the WordPress API.

**Comment by MjHead** [comment]
You can add filed into rest API with switcher in field settings - https://i.imgur.com/YyuqY77.png Such switcher allowed for both - meta boxes fields and options pages fields

**Comment by N0N4M3BNS** [comment]
> You can add filed into rest API with switcher in field settings - https://i.imgur.com/YyuqY77.png Such switcher allowed for both - meta boxes fields and options pages fields

After enabling the button, how to use it? I mean how about the URL to call the option page

**Comment by Feldrise** [comment]
Hello ! This issue seems old but I can't find anywhere the endpoint URL and this is the clothest to an answer I can find on the internet ^^'
