### ISSUE TITLE
middle mode for overflow option / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5781]
If we enable the overflow option in jet woobuilder, after the first navigation the carousel will be displayed like this : https://prnt.sc/xuTmuvCV2n96
In fact, only the last product is overflow.

But it will be great if you add middle mode option for overflow. With the addition of this feature, if we activate it, after the first scrolling, both the first product and the last product have an equal amount of overflow : https://prnt.sc/CzYFk3SYzx56

middle mode can only be used if the overflow option is enabled.

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thanks for the feedback.

Unfortunately with this functionality cant be achieved with the help of current version of library for slider and default options that it has. So in this situation your request will not be completed.

Thank you for your understanding.
