### ISSUE TITLE
An item about disabled mode in the product grid widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5783]
hello

Using [these settings](https://prnt.sc/EG0_WQcPYuMK), I'm trying to implement a case where the desired button is completely disabled after the carousel reaches the end of the list. It works, but there is a problem. **The problem is that the arrow button slowly disappears.**

Please watch this video :

https://user-images.githubusercontent.com/77163248/184892733-ee422477-4288-4bc0-a655-5ee840db343d.mp4

As you can see in the video above, when the button is disabled, it happens slowly. Is there a way to fix it? so that the button is immediately disabled.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Yes, there is a way to fix it. Please use some CSS like this selector .jet-arrow {
    transition: all 0s;
}.

```
selector .jet-arrow {
    transition: all 0s;
}
```

**Comment by 79ho3ein** [comment]
thank you my friend
