### ISSUE TITLE
sales order does not work well on variable products / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5784]
To display top sellers products, I set the product grid widget like this : https://prnt.sc/9Ms_q2AL7CkH
But in variable products, this order of products does not work properly. WooCommerce displays [this order](https://prnt.sc/U0qWRD1zG-1w), But in the product grid widget, the order of these products is displayed incorrectly.

Actually, the sales order in the product grid widget only works wrong on variable products. But it is true in simple products. Please fix this. This order is really important in (variable) products. thanks

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

Please show a screenshot that the order of the products is wrong in our widget. Also, what is wrong with it? If you are based on this screenshot, then this is not entirely correct https://prnt.sc/U0qWRD1zG-1w. You can use the standard bestseller product output shortcode. Or use for example another widget that displays the order correctly.

Thank you!

**Comment by Michaelgimii** [comment]
@UraraReika 
What WooCommerce shows : https://prnt.sc/TcT_Ei_Bn2Yd
What the product grid shows :  https://prnt.sc/bnFbaHNgxjaG

**This bug exists only in variable products. In simple products, everything works fine.** Does it work well for you?

**Comment by UraraReika** [comment]
Yes, it works well for me. And i don't think that this is Products Grid widget bug. Try to test output with standard shortcode.

`[products limit="3" columns="3" best_selling="true" ]`

**Comment by Michaelgimii** [comment]
> [products limit="3" columns="3" best_selling="true" ]

I tested this as well. The wrong products are displayed. Are you sure you tested it for variable products? Simple products are not a problem. But variable products are displayed incorrectly.

**Comment by UraraReika** [comment]
> > [products limit="3" columns="3" best_selling="true" ]
> 
> I tested this as well. The wrong products are displayed. Are you sure you tested it for variable products? Simple products are not a problem. But variable products are displayed incorrectly.

Good. If you use this shortcode and got result that is not correct than you should wright to official WooCommerce support so they can fix it inside their plugin.
