### ISSUE TITLE
Custom stock status

### ISSUE THREAD

**Issue by MichaelaKubasova** [CrocoBlock/suggestions#5788]
Hello, 

I use, code snippet for custom stock status, when we need more stock statuses. But jetwoobuilder product grid/carousel didn't work with custom stock status. Please help.

**Comment by UraraReika** [comment]
Hello @MikaelaDeCub! Thanks for the feedback.
 
Please follow guidelines for opening a new [bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests.

 Thank you for your understanding.

**Comment by UraraReika** [comment]
In our Products Grid widget we use custom function to output messages depending on statuses. In this case we handle 3 default statuses, but in this function we have filter hook `jet-woo-builder/template-functions/custom-stock-status` that you can use to handle you r custom output.

If you have difficulties feel free to contact our support team.

Thank you!
