### ISSUE TITLE
Underline in the Old Price - jet search

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5790]
**Describe the bug**

hi @Floydtm , Please check this simple item.
**(It's not a bug, but it wouldn't be bad if this problem were fixed in JetSearch)**

If the product price has an Old Price, the Old Price has an underscore : https://prnt.sc/V06K30Y7SiBx

Please remove this underscore if possible. 

thank you

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side https://prnt.sc/dLm4txDZcPcM The widget has stylish product price settings. Check them out

**Comment by 79ho3ein** [comment]
hello @Floydtm , Did you test this in hello elementor theme?

I think this is a simple case between jetsearch and hello elementor theme. Because I installed the astra template to test, and Jet Search did not have the problem of the underline for old price in this theme : https://prnt.sc/S0CCEBec7WPT
On the other hand, I use the jet woobbuilder plugin in the hello elementor theme, but this plugin does not have the problem of displaying the underline in the old price.

Anyway, thank you for your kindness

**Comment by Floydtm** [comment]
Tell me on which theme you had this case? Perhaps we will add this to the plugin

**Comment by 79ho3ein** [comment]
> Tell me on which theme you had this case? Perhaps we will add this to the plugin

thank you @Floydtm , I have this problem in **hello elementor** theme.

**Comment by 79ho3ein** [comment]
Hi again @Floydtm, I was going to report this but I remembered I did it before.

Were you successful in reproducing this item in Hello Elementor theme? I have a workaround for it now, but is there a plan to fix it in the next release?

thank you

**Comment by Floydtm** [comment]
Unfortunately, now I have this bug, we will check your request

**Comment by 79ho3ein** [comment]
thank you @Floydtm
