### ISSUE TITLE
Please add JetEngine Listing Grid VERTICAL SLIDER function

### ISSUE THREAD

**Issue by justgkp** [CrocoBlock/suggestions#5791]
Please add JetEngine Listing Grid VERTICAL SLIDER. Although there is horizontal slider it's verch much important to slide vertically as well. Please add this function.

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/418)
