### ISSUE TITLE
Theme Templates are indexable

### ISSUE THREAD

**Issue by Kornform** [CrocoBlock/suggestions#5803]
**Describe the bug**
I hope it's a bug and not intended behaviour:

My bug fix would be to exclude those elements/pages created with the "Theme Templates" from the Google search results, or to not make them accessible when not logged in.

When I create an element with "Theme Templates" it creates a page which is indexable and can be found in Google. When I do it in Elementor it won't show up anywhere – with the exception when you are logged in, then you can access that element within your page.

This means, my element/page is accessible:
"my-website[.]com/?jet-theme-core=footer". 
I can access this site even when I'm not logged in.

In comparison Elementor creates templates which can't be accessed when you are not logged in:
"my-website[.]com/?elementor_library=footer".
In comparison that site can't be accessed when when I'm not logged in.

Best Regards

**Comment by Crocoblock** [comment]
has been fixed in version 2.1.3
