### ISSUE TITLE
Hover effect on JetWooBuilder product thumbnails causes a bug when enabling webp images with <picture>

### ISSUE THREAD

**Issue by marcofrasson** [CrocoBlock/suggestions#5805]
Hello, the hover effect on JetWooBuilder product thumbnails causes a bug when enabling webp images with <picture>

**Comment by UraraReika** [comment]
Thanks for the feedback.

 Please follow guidelines for opening a new [bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. 

Thank you for your understanding.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. If you still need help with this issue or have any other questions about our product, please start a new thread.
