### ISSUE TITLE
Filter products grid by stock status

### ISSUE THREAD

**Issue by arcaswebdesign** [CrocoBlock/suggestions#5811]
In the PRODUCTS GRID widget we have various options to filter by category, sale status, popularity etc. - would it be possible to add an option for Stock Status too, so that we can ensure that only instock items are displayed, for example? 

I'm hopeful it would be an easy enough filter to add in to the QUERY BY box with an option **Stock Status** and we can then pick from any available stock status to filter by?

**Comment by UraraReika** [comment]
This improvements will be added in the next release. In this control you will find a new type of query https://tppr.me/9bM48 `stock_status`. After selecting this type of query, a new additional control will appear https://tppr.me/vDQWy in which you can select the type of status, as well as combine them by selecting several. Then get a list of products according to the specified parameters.

**Comment by arcaswebdesign** [comment]
Thanks for taking my suggestion into account, that sounds perfect!

**Comment by Michaelgimii** [comment]
> This improvements will be added in the next release. In this control you will find a new type of query https://tppr.me/9bM48
hi @UraraReika  , How is this new feature different from this option? https://prnt.sc/CtW9jqILzR5W

**Comment by arcaswebdesign** [comment]
>How is this new feature different from this option? https://prnt.sc/CtW9jqILzR5W

I believe that the existing option is merely to _order_ the products by stock status whereas the new option allows us to _filter_ the products by stock status.

**Comment by Joliamendi** [comment]
+1
