### ISSUE TITLE
IMPORTANT!!! JetSmartFilters current Version breaks Elementor

### ISSUE THREAD

**Issue by edgBllw** [CrocoBlock/suggestions#5812]
I tested it on ALL of my sites. The current JetSmartFilters Plugin (2.3.13) isn't compatible with Elementor (that has a higher version than 3.6.8). The bug is, you can't access the Elementor edit mode anymore. The Elementor loading screen just "loads" forever. On every post type (pages, listing items ...) this bug exists, except the own elementor library templates. there everything just works fine

https://user-images.githubusercontent.com/105508226/186225740-b25428ce-dec8-4b06-b2c2-805983b8b539.mov

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
