### ISSUE TITLE
Jet Booking... pass additional field values to show on Paypal’s transaction invoice

### ISSUE THREAD

**Issue by ProteoV** [CrocoBlock/suggestions#5815]
Hi Team!

I was wondering if there’s a way, or code snippet available where we can pass additional field values to show on Paypal’s transaction invoice?
In PayPal section details, now only send the word "Booking"; I need see there the "Booking Details"

That is, I need that instead of showing only the name of the product (in this case the only product is Booking), put the Booking Details, which in Jet Booking would really be the equivalent of the service we are selling. I need to see that information in my PayPal account.

Regards!
Pablo

**Comment by UraraReika** [comment]
Hello @ProteoV. Thanks for the feedback.

 Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), and describe your issue in more details, so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. 

Thank you for your understanding.

**Comment by UraraReika** [comment]
Hello @ProteoV. Thanks for the feedback.

 Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), and describe your issue in more details, so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests. 

Thank you for your understanding.

**Comment by UraraReika** [comment]
In this case you should look for the solution in the PayPal plugin that you use. And find there a code part that formed details section of the payment. In this section you probably will find some hook, or you can rewrite plugin template and there you can get booking details depending on order id like this:

`$details = $this->get_booking_order_details( $order_id );`

Then output this data like this:

```
<ul class="woocommerce-order-overview woocommerce-thankyou-order-details order_details"><?php
	foreach ( $details as $item ) {
		echo '<li>';
			if ( ! empty( $item['key'] ) ) {
				echo $item['key'] . ': ';
			}
			if ( ! empty( $item['is_html'] ) ) {
				echo $item['display'];
			} else {
				echo '<strong>' . $item['display'] . '</strong>';
			}
		echo '</li>';
	}
?></ul>
```
