### ISSUE TITLE
Jetwoobuilder has problem with elementor containers

### ISSUE THREAD

**Issue by MichaelaKubasova** [CrocoBlock/suggestions#5818]
I create a website which has two containers next to on computer, but on mobile device I want only one container with 100% width, but somehow he take width with computer setup, but if I change width on mobile in elementor editor, not working.

**Comment by UraraReika** [comment]
Hello @MikaelaDeCub !

Please describe your request in more details. You can use this template https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Thank you!

**Comment by MichaelaKubasova** [comment]
I create a website which has two containers next to on computer, but on mobile device I want only one container with 100% width, but somehow he take width with computer setup, but if I change width on mobile in elementor editor, not working.

To Reproduce Steps to reproduce the behavior:

Screenshots If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: MacOS
Browser Chrome, Firefox, Safari
Version Chrome - Version 104.0.5112.101; Firefox - 104.0; Safari - Version 15.6.1; 

Smartphone (please complete the following information):

Device: iPhone 11 pro
OS: iOS 15.6.1.
Browser: Safari, Chrome and Firefox


Video: https://screencast-o-matic.com/watch/c3jZoGVTt4E

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. 

Thank you!
