### ISSUE TITLE
Jetwoobuilder products widget has problem with custom code stock status

### ISSUE THREAD

**Issue by MichaelaKubasova** [CrocoBlock/suggestions#5819]
I use custom snippet code for edit stock status like "pre-order" but when I add products widget from crocoblock, product with "pre-order" is showing like in stock.

**Comment by UraraReika** [comment]
Hello @MikaelaDeCub !

Please describe your request in more details. You can use this template https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Thank you!

**Comment by MichaelaKubasova** [comment]
I use custom snippet code for edit stock status like "pre-order" but when I add products widget from crocoblock, product with "pre-order" is showing like in stock.
To Reproduce Steps to reproduce the behavior:

Desktop:

OS: MacOS
Browser Chrome, Firefox, Safari
Version Chrome - Version 104.0.5112.101; Firefox - 104.0; Safari - Version 15.6.1;

Smartphone:

Device: iPhone 11 pro
OS: iOS 15.6.1.
Browser: Safari, Chrome and Firefox

Here is url with examples: https://www.tiler-market.sk/elementor-4070/ 
First product is crocoblock product grid widget, second product is elementor product widget.

**Comment by UraraReika** [comment]
In our Products Grid widget we use custom function to output messages depending on statuses. In this case we handle 3 default statuses, but in this function we have filter hook jet-woo-builder/template-functions/custom-stock-status that you can use to handle you r custom output.

If you have difficulties feel free to contact our support team.

Thank you!
