### ISSUE TITLE
JetEngine Map Listing - Open listing popups on marker mouseover

### ISSUE THREAD

**Issue by aronhawkins-4** [CrocoBlock/suggestions#5823]
I want to open each listing popup when its corresponding map marker gets hovered over by the mouse.

**Comment by inveress** [comment]
Seconding this. It would be extra useful to be able to specify different popup content when hovered vs when clicked.

**Comment by kaskad88** [comment]
This feature will be available in JetEngine v3.1.7

**Comment by inveress** [comment]
Thank you!
