### ISSUE TITLE
Dynamic Field: Allow adding dynamic data as a fallback value

### ISSUE THREAD

**Issue by orelhassid** [CrocoBlock/suggestions#5828]
**Before adding a new feature request, please, make sure you’ve checked:**

## Description
When using Dynamic Field to display the page title I would like to add a fallback value but as dynamic data.

## Example
I want to add an alternative page title, so I added Meta Boxes for all pages with the following fields (Overline, Headline (title), Description, Cover Image)
I want to display the Headline as the page title. but if it's empty use the default page title.

## Why?
Because the page title needs to be short and clear like "About", and "Contact" but I want to display a long page title/headline like "Hi, nice to meet you" but if it does not exist just use the page title name.

## Alternative option
Is to duplicate the Text widget and use Dynamic visibility.

![image](https://user-images.githubusercontent.com/57160714/187025798-8368e300-8e02-450a-b78f-bca988d7c7f4.png)

**Comment by Crocoblock** [comment]
Hi @orelhassid. 

This was added in version 3.0.7.
