### ISSUE TITLE
Crocoblock Jet Engine Calendar Appearance/Functionality

### ISSUE THREAD

**Issue by shaggira** [CrocoBlock/suggestions#5829]
The calendar's functionality on the JetBookings is generally bugging. When I scroll through the months, it doesn't give me the right order of months because another arrow appears in the middle for scrolling the months. It’s weird for the calendar to work that way. If you look at any international booking website, whether it’s accommodation, flights or car rentals, the calendar doesn’t function like that. Is there any way to set the calendar to display the months in the correct order or only one month at a time? 

You can find my calendar on the form (Check-in/Checkout) on this link: http://villavoila.com/properties/villa-carmina-mykonos/

![unnamed](https://user-images.githubusercontent.com/112256750/187030421-b485bace-8c65-46b7-94b9-82effd3890ed.png)

**Comment by shaggira** [comment]
Hi guys, any update with this?

**Comment by UraraReika** [comment]
> Hi guys, any update with this?

In our roadmap

**Comment by UraraReika** [comment]
Hello @shaggira !

We have documentation about for JetBooking calendar JS API. Where you can implement whatever you want solution. In your case you need to add this code to your `function.php` file in child theme:

```
add_action( 'wp_footer', function () {
	echo '<script>
		window.jetBookingState.filters.add( "jet-booking/input/config", ( config ) => {

			config.stickyMonths = true;
		
			return config;
			
		} );
	</script>';
}, 99 );
```

Feel free to try it own.

**Comment by TipoSamuel** [comment]
Hi @UraraReika where can I review that documentation you mention?

In my JetEngine form I am placing separate check-in and check-out fields and I would like for each field to show the calendar by single month.

![Jet-Booking](https://user-images.githubusercontent.com/107733998/207684923-d080d7e9-e0c1-484b-afff-cf2d517855f4.jpg)

**Comment by UraraReika** [comment]
> Hi @UraraReika where can I review that documentation you mention?
> 
> In my JetEngine form I am placing separate check-in and check-out fields and I would like for each field to show the calendar by single month.
> 
> ![Jet-Booking](https://user-images.githubusercontent.com/107733998/207684923-d080d7e9-e0c1-484b-afff-cf2d517855f4.jpg)

Here you are https://gist.github.com/Crocoblock/0d73be0a11b07fa24c1490f5ad7d0d3a
