### ISSUE TITLE
"Border Radius" functions in Single Images (in JET WOO BUILDER)

### ISSUE THREAD

**Issue by zimmiel** [Crocoblock/suggestions#583]
Hello!
would be nice add in "Single Images" in JET WOO BUILDER the function image Border Radius (img_1)
![1](https://user-images.githubusercontent.com/42843497/66993927-1e62c300-f0d5-11e9-9eb2-4f821d5a62ed.png)

You already have a function "Box Shadow" it's good. So these two functions "Border Radius" and "Box Shadow" will give more flexibility, variations in design.

**Comment by UraraReika** [comment]
Done. Next Release.
