### ISSUE TITLE
product grid badges position / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5830]
The product grid widget is a great widget. But there is a big limitation in the badges section. In this section, we cannot place the badges in the desired position.
For example, we wanted to display badges in [this location](https://prnt.sc/tHGJqqH_ozhY). But it is not possible.
Please add options for badges so we can display it in the desired position. Currently we only have the [margin option](https://prnt.sc/B75TUJMz6HCA) and that is not really enough.
Please keep this in mind. thanks

**Comment by 79ho3ein** [comment]
+1

**Comment by Joliamendi** [comment]
please @UraraReika. The options in the image below will be great for setting the position of badges. The addition of this feature removes the current restrictions.

![badges](https://user-images.githubusercontent.com/103376243/210396525-470c5714-ba72-4ff2-ad70-4e0577169d16.png)
