### ISSUE TITLE
JetFormBuilder issues with required fields & conditional logic

### ISSUE THREAD

**Issue by websetters** [CrocoBlock/suggestions#5831]
Dear Crocoblock team, unfortunately I noticed a bug that does not allow me to use your plugin.

I have created a form with which it should be possible to upload real estate. Since different fields should be displayed in the form for different property types, I use the Conditional Logic function. Showing or hiding the elements works, but as soon as I have a Required field in another logic which is not filled in, I can't go to the next step in the form. Also, the error messages that the field is required are missing. 

Best regards

**Comment by girafffee** [comment]
Already available in beta 3.0
https://github.com/Crocoblock/suggestions/issues/6408

You need to enable this option, then required fields will be ignored if they are hidden.

![image](https://user-images.githubusercontent.com/46720998/213576121-78a40c7d-9cbb-4a38-904e-072137e0172f.png)

**Comment by pierresubotai** [comment]
Will this functionnality be released for jetEngine Forms ?
It will also fixe the bug in this issu : https://github.com/Crocoblock/suggestions/issues/1568
