### ISSUE TITLE
Show/Hide Passwords

### ISSUE THREAD

**Issue by Avram-Baskin** [CrocoBlock/suggestions#5832]
It would be helpful to have a Show/Hide option in password fields.

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by Avram-Baskin** [comment]
The attached screen shots illustrate the suggested functionality.  These happen to be from the Wordpress login, but this functionality is widely used.  The default state is for the password to be masked.  A toggle button, usually an eye icon, but sometimes text (Show/Hide) allows the user to toggle back and forth between showing and hiding the password.

<img width="331" alt="Password Hide" src="https://user-images.githubusercontent.com/95720249/188633235-8db223a3-6cf2-4d30-b9db-e43c16ab363c.png">
<img width="344" alt="Password Show" src="https://user-images.githubusercontent.com/95720249/188633238-a3862e14-ccc1-47d2-9bf0-11523ad4478e.png">

**Comment by Floydtm** [comment]
Oh. You misunderstood me a little. Which widget are you requesting this enhancement for. Or is it about forms?

**Comment by Avram-Baskin** [comment]
The password and confirm password fields that are used when logging in.

Avram Baskin
Be yourself, 
everyone else is already taken
Oscar Wilde

**Comment by Rubendj1** [comment]
It woulf also be nice to add this functionality to passwordfield in JetFormbuilder for custom registration forms.

**Comment by Crocoblock** [comment]
was added in 3.3.4
