### ISSUE TITLE
jet woobuilder canvas mode not work

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5836]
If we select the [canvas option](https://prnt.sc/uWav9YUiSZLd) in the jet woobuilder templates, it does not work. Therefore, by selecting this option, the header and footer will still be displayed.

**Comment by UraraReika** [comment]
Thanks for the feedback.

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. We use theme Hello Elementor. Maybe you have specific settings for separate product here https://tppr.me/XYdRk. Please contact our support team.

Thank you!
