### ISSUE TITLE
JetBlocks Reset Password Form Widget shows 3 password input fields instead of 2

### ISSUE THREAD

**Issue by Raxol** [CrocoBlock/suggestions#5837]
**Describe the bug**
The Reset Password Form Widget shows 3 password input fields (1x New Password, 2x Repeat Password) but should only show 1 _New Password_ and 1 _Repeat Password_ fields.

**To Reproduce**
1. Visit page with the widget added and request a password reset link to be sent to your email
2. Open the reset link
3. See 3 password input fields (see screenshot)

**Expected behavior**
As it's standard everywhere nowadays that we only need to repeat the password once to confirm it we should only have 2 input fields.

**Screenshots**
![Screenshot 2022-08-30 at 14-06-07 Passwort zurücksetzen](https://user-images.githubusercontent.com/1255793/187432436-9eacd852-c511-40fa-af68-f1f3cdecfe3a.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 104.0

**Additional context**
- JetBlocks For Elementor 
- Version: 1.3.3
- The error is found in: jet-blocks/templates/jet-reset/global/reset-password-form.php 
line 81 - 94
The input field "jet_reset_new_user_pass_again" is added twice.

**Comment by edgBllw** [comment]
I also noticed that issue. What you need to do to fix it temporarily until they've fixed it, is this:

`document.querySelectorAll('.jet-reset__field :is(input, label:not(:first-child))').forEach(uselessFields => {
  uselessFields.remove();
});`
