### ISSUE TITLE
Jet Appointments Booking + Make.com (Webhook)

### ISSUE THREAD

**Issue by Wanooo0** [CrocoBlock/suggestions#5838]
I try to create event in Google Calendar from my form created with (jetappointment).

My (jetappointment) form is properly connected to my webhook. 

But I dont have any access to Start Date field or and slotEnd or End Date items... 

I dont see the "appointment_date_new" expandable item in the available macros in "make.com" webhook settings.

How to get StartStart and SlotEnd values from my form?

(a french user - sorry for my bad english)

![image](https://user-images.githubusercontent.com/77484326/187454298-e8188bb5-cdef-4025-9b3f-6c637cf9acad.png)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by Wanooo0** [comment]
> We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

Thanks for you reply. I will check all my settings today. Greetings
