### ISSUE TITLE
Variable title on product page / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5840]
In the variable selection section, the title of the variable is not centered vertically : https://prnt.sc/TPFBpqVf10lO
Please add a new control for the vertical alignment of variable titles.

**Comment by UraraReika** [comment]
Hello @Michaelgimii. Thanks for the feedback.

Unfortunately, we can't do it without additional customization of WooCommerce template so we will leave this functionality as it is.

Thank you for your understanding.
