### ISSUE TITLE
lazy load for product grid / list and category grid widget.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5842]
Please add lazy load option to jet woobuilder widgets. Enabling this feature is completely optional : https://prnt.sc/-KVOaEzSKTlG
This feature is available in elementor. So it's great if you add it in jet woobuilder.

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

I merged this issue with [#4987](https://github.com/Crocoblock/suggestions/issues/4987), which is on the same subject so we could deal with it more efficiently.

And for the future before adding a new feature request, please, make sure you’ve checked if the feature is already added to the backlog or in work.

Thank you!
