### ISSUE TITLE
responsive option for Animation Speed in product grid and category grid widgets

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5846]
It would be great if you could add [Responsive option](https://prnt.sc/HfHkopYLLw2l) to [Animation Speed](https://prnt.sc/bqT9Y3FizJr6) ​​control.

**Comment by UraraReika** [comment]
In our plugin we use Swiper Slider library for carousel functionality. And this library doesn't give us opportunity add this property to breakpoints system. Check off documentation https://swiperjs.com/swiper-api#param-breakpoints. So this option will not be added.

Thank you!
