### ISSUE TITLE
selected mode for the selection field - jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5847]
In some jet woobuilder widgets we have [this field](https://prnt.sc/XGtfsg3DI_so) to select options. It will be great if you add one item to it. so that the selected options are highlighted.
An example to describe this request is the WooCommerce feature selection section on the product page. On the add product page, features that are selected have a different color than options that are not selected : https://prnt.sc/wXK6JxZtiTc2
Adding this simple feature can be very useful. thanks

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thanks for the feedback.

This is default Elementor control that we use to build our widget https://developers.elementor.com/docs/controls/classes/control-select2/. And the look of this option depends on Elementor plugin. Some theme although style Elementor controls. In fact as you can see selected options have brighter color https://tppr.me/6wr49. But if you want to make it better then write to official Elementor support team.

Thank you!
