### ISSUE TITLE
responsive option for Products Number / jet woobuilder 

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5849]
It would be great if you could add a responsive option to the [Products Number control](https://prnt.sc/mWqMiwye5a7t). In certain cases, the number of products in mobile, tablet or mobile needs to be different, and this option will also help a lot. Please add this item. thanks

**Comment by UraraReika** [comment]
Hello @Michaelgimii!

Unfortunately this option can't be transformed into responsive. Because the value of it used in the backend where we cant specify and handle breakpoints. 

Thank you!
