### ISSUE TITLE
BUG Images don´t show when I use the image accordion element and I activate webp images with Imagify

### ISSUE THREAD

**Issue by ignaciosantiago** [CrocoBlock/suggestions#5854]
**Describe the bug**
Images don´t show when I use the image accordion element and I activate webp images with Imagify

**To Reproduce**
1. Go to https://ignaciosantiago.com/clientes/supernova/showroom/

**Screenshots**

![02-09-2022_12-00-54](https://user-images.githubusercontent.com/5451478/188115565-92199c2f-868a-40bd-957b-c47f0e420eb8.jpg)

![02-09-2022_12-01-33](https://user-images.githubusercontent.com/5451478/188115806-3523a04f-5bc3-4515-9673-c8ed18c26786.jpg)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later

**Comment by Crocoblock** [comment]
was released in version 2.2.1
