### ISSUE TITLE
The possibility of adding the coupon form in the desired place on the checkout page / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5855]
hello crocoblock

One of the biggest weaknesses in jet woobuilder is that we cannot place the coupon form of the checkout page in the desired location. In fact, we have to display the coupon form in a different template ([Checkout Top Template](https://prnt.sc/JWayWzlZIMLy)) than the checkout forms. This is not really good.
For example, if we want to display the coupon form in [this](https://prnt.sc/JZFtXiDH79lN) section, we can't!

This is possible in elementor pro, but not in jet woobuilder. Please fix this feature. So that we can create the checkout page in only [one template](https://prnt.sc/NQaHfdkmJSCC). This is really important. thanks

**Comment by UraraReika** [comment]
I merged this issue with [#5401](https://github.com/Crocoblock/suggestions/issues/5401), which is on the same subject so we could deal with it more efficiently.
