### ISSUE TITLE
Suggestions for jet compare & wishlist.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5859]
hello @UraraReika , Since #4697 is under development, I had some suggestions to complete the functionality of this plugin with jet woobuilder. Please check them out.

A : Currently, the [favorites option](https://prnt.sc/Ad3-gy4YYZ-t) in the Product grid widget is displayed only when we hover over the product box. Please add an option to specify whether the interest button should be displayed on hover, or always displayed. Like this option : https://prnt.sc/cMiBSdy3_EYE
According to the above screenshot, if we select **none**, it will always be displayed.

B : If we enable[ this option](https://prnt.sc/KlD6JcR96PdT), the title in [this section](https://prnt.sc/vYLP-igJ8GHQ) will be misleading. Isn't it better to change its name to remove if you select the Use as Remove Button option?

C : It would be great if you could add an option like this. **called typography**
For example, I just want to use the icon. If I turn typography off, [all controls related to typography in the style tab](https://prnt.sc/bOPdlYBS6WUc) will be removed.
Also, if we turn off this option, [these texts](https://prnt.sc/9CAxZ1I1jcG_) will also be hide, which is great.

D : Please add background and box shadow option for icon : https://prnt.sc/dJAyNg-mXMb2
**(These options will be needed if typography is disabled in the C condition)**

E : By default, there is no box shadow option for hover and added sections: : https://prnt.sc/7jjHvsdcejiK
This option is displayed only if we activate it in normal mode.
Exactly like [this problem](https://github.com/Crocoblock/suggestions/issues/5720) that was solved before in the product grid. 

**compare**

A : In compare, if we remove the text, the icon is not centered exactly. This problem does not exist in the wishlist. https://prnt.sc/AxOMDl7qjrPR  
As you can see in the previous image, the comparison icon is not centered and is tilted to the left.

B : It would be nice if you add an option so that we can customize the compare & wishlist buttons (even the jet popup quick view button) in one box. https://prnt.sc/Iz4BcHp6T2jf
**In fact, we need a new section in the style tab of the product grid widget, so that we can have a common background, box shadow, border, and border radius for these buttons.**
We can customize the background of these buttons both individually and in groups, which is great.

**Comment by 79ho3ein** [comment]
> A : Currently, the [favorites option](https://prnt.sc/Ad3-gy4YYZ-t) in the Product grid widget is displayed only when we hover over the product box. Please add an option to specify whether the interest button should be displayed on hover, or always displayed. Like this option : https://prnt.sc/cMiBSdy3_EYE
According to the above screenshot, if we select none, it will always be displayed.

+1 , This is really important

**Comment by Joliamendi** [comment]
+1

**Comment by UraraReika** [comment]
A - This option will not be added to the core of our plugin. But you can use this piece of code to solve the issue:
```
.jet-woo-products .jet-woo-products__item .jet-woo-products-cqw-wrapper {
	opacity: 1;
	visibility: visible;
}
```
B - This made so because originally option lies in the Added tab. That is why everything will stay as it is.
C, D - We will keep this section as it is.
E - Done. Wait next release.

Compare 
A - Track this issue - https://github.com/Crocoblock/suggestions/issues/5698
B - This one connected to JetWooBuilder so please create a new thread and describe the issue in more details.
