### ISSUE TITLE
Spinner to apply Ajax in jet compare & wishlist plugin.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5860]
It would be great if you add a spinner for the compare & wishlist buttons in the product grid widget. For example, when the user clicks on add to wishlist, this spinner will be displayed and after that, the product will be added to wishlist. It will be incredibly beautiful. Please add it.
The use of this spinner can be optional. We can enable or disable it. An example of this beautiful spinner :

https://user-images.githubusercontent.com/88034902/188272176-5225ce0c-de83-4a43-b42a-cfee86e2706e.mp4

**Comment by UraraReika** [comment]
Unfortunately we do not plan to introduce such functionality into our plugin. But you already can make a trick with the help of CSS. My example will be including FontAwesom icon set but you can use whatever you want with small modifications:

```
selector a.jet-compare-button__link.jet-compare-button__link--icon-left.jet-cw-loading {
	position: relative;
}

selector a.jet-compare-button__link.jet-compare-button__link--icon-left.jet-cw-loading:before {
	content: "\f110";
	font-family: "Font Awesome 5 Free";
	font-weight: 900;
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
	left: 15px;
	animation: rorate 0.5s infinite linear;
}

selector a.jet-compare-button__link.jet-compare-button__link--icon-left.jet-cw-loading .jet-compare-button__icon {
	visibility: hidden;
}

@keyframes rorate {
	from {
		transform: translateY(-50%) rotate(0deg);
	}
	to { 
		transform: translateY(-50%) rotate(360deg);
	}
}
```

You can put this styles in Elementor Pro Advance Tab Additional CSS section.
