### ISSUE TITLE
bug : jet engine > listing widget with elementor custom font.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5863]
**Describe the bug**
HI @Floydtm There is a strange bug between Jet Engine and Elementor's custom font, which I realized after a long time is a bug from the listing widget. The explanation is very detailed. Therefore, I go directly to the stages of reproduction.

**To Reproduce**
1- Upload your custom fonts to Elementor.
2- In the Global Fonts section, create one or more fonts that use your custom font : https://prnt.sc/ySR2xz8eQd4o
3- After that, edit a page with Elementor and add a few paragraphs in it. (Connect the paragraph font to the global font we created in step 2)
4- On the same page, add the **listing widget** (have content)
5- Reload the Elementor editor.
6- After the editor has reloaded, go to the Custom Fonts section of the Elementor site settings : https://prnt.sc/WK9P-54zEffD
7- In this section, for testing, add only one font and remove one font (only for testing)
5- Save the changes, and click the close button to enter the editor : https://prnt.sc/Tgx9hG5dHS6n

**After that, if you look carefully in the Elementor editor, the paragraph font, which was a custom font, is broken.** The only solution is to reload the editor.

- Please note that fonts are broken only in the editor. 

**Now, if you remove the listing widget from the page and repeat the above steps, the fonts will not be broken.**

If you did not understand the above steps well, please watch the video below. (my language is Persian. I hope it is clear before and after the font is broken.)

https://user-images.githubusercontent.com/77163248/188320481-4753f585-6396-4fb6-9ac9-c0c88cf02286.mp4

Second 25 : The font is correct.
Second 33 : The font is broken.

**details**
theme : hello elementor
elementor : new version
wordpress : new version
jet engine : new version
elementor pro : new version

I hope you are successful in reproducing it.

thank you

**Comment by kaskad88** [comment]
@79ho3ein 
Currently with Elementor v3.13.4, Elementor Pro v3.13.0 & JetEngine v3.1.5 this issue does not appear
