### ISSUE TITLE
Please add "Forgot Password" functionality to Jetformbuilder's User Login Action plugin

### ISSUE THREAD

**Issue by unitedonline** [CrocoBlock/suggestions#5865]
The existing "Forgot Password" functionality at this point can only be accomplished via the "JetBlocks For Elementor" plugin.

This creates an issue for all of us who do not wish to use the bloated Elementor page builder.
Please consider adding this functionality to the User Login Action plugin for allowing web developers to create a "Forgot Password" form.
Also please add OTP, Twillio, WebHook, Second Factor Authentication,  and Double Opt-in support to this plugin.
(Just like "Actions Pack" by https://wpfolk.com/ and Piotnet's advanced form builder features https://pafe.piotnet.com/)

Thank you

**Comment by LevelUpGit** [comment]
+1

**Comment by morosmo** [comment]
+1

**Comment by girafffee** [comment]
This feature was added to User Login addon in version 2.0.0. Watch this video to understand how to set up a form for reset password.
https://youtu.be/lxW5d0tvUro
