### ISSUE TITLE
Ability to disable the button to increase / decrease the number of products on the product page / jet woobuilder plugin

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5866]
It would be great if you could add a new property to the button widget so we can disable [this control](https://prnt.sc/DSzCjRDHu1Nk). For example, some customers tend to just add the product to their cart on the product page. If they wish, they can increase the number of desired products in the cart page. thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
