### ISSUE TITLE
Possibility to change the variable title position in Jet Woobuilder plugin

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5867]
If possible, please add a new feature so that we can choose to display variable titles in 2 places.
1- Default (next to variable selection field)
2- Above variable fields : https://prnt.sc/GnWfY9M1Dmwx

**Comment by UraraReika** [comment]
Hello @Michaelgimii, Thanks for the feedback.

At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

For now you can simply rewrite WooCommerce template and make your own layout.

Thank you!
