### ISSUE TITLE
Custom spinner for add to cart widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5869]
It would be great if you could add the ability to change the spinner icon of the add to cart button. The current spinner is not really cool for a modern website. I hope this is possible. thanks

**Comment by Joliamendi** [comment]
+1

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
