### ISSUE TITLE
The possibility of displaying the most visited products in jet woobuilder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5870]
hello crocoblock team

It would be great if you add the most visited products query to jet woobuilder. This is what our customers want from us, but we are not able to add it at the moment.
I guess you don't add this feature because it slows down the website. Because this query challenges the database. But please add this feature, so we can use it if needed. Of course, many large online stores use this query. It can be very useful in its own right. If anyone doesn't mind slowing down this query, they can use it in Jet woobuilder. Otherwise, we will not use it. But please give this option to your users. thank you

**Comment by UraraReika** [comment]
Hello @Joliamendi, Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But you can make this solution with the help of JetEngine or (Advanced Custom Fields) and small code snippet.

First of all create meta field text or number type https://tppr.me/E3fA6 set min value to `0` and default value to `0` as well https://tppr.me/PACME. Add this pease oof code:

```
add_action( 'woocommerce_before_single_product', function () {

	global $product;

	$product_id  = $product->get_id();
	$visit_count = get_post_meta( $product_id, 'product-visit-count', true );
	$visit_count = intval( $visit_count );

	$visit_count++;

	update_post_meta( $product_id, 'product-visit-count', $visit_count );

} );
```

`product-visit-count` - your meta field key.

This code will increase view count every time someone view product.

Next add Products Grid widget on your page set query like this https://tppr.me/bjqkQ and add `Query Id` param like this https://tppr.me/8ki4I. Then add this code snippet to your child theme:

```
add_action( 'jet-woo-builder/query/most_viewed', function( $query ) {

	$query->query_vars['meta_query'][] = [
		'key'     => 'product-visit-count',
		'value'   => 0,
		'compare' => '>',
	];

	$query->query_vars['meta_key'] = 'product-visit-count';
	$query->query_vars['orderby']  = 'meta_value_num';
	$query->query_vars['order']    = 'DESC';

} );
```
This code will handle your meta field and display product according to it. It will show only product that beed viewed and order them by views.
