### ISSUE TITLE
The possibility of displaying the price of variable products dynamically in the Jet Woobuilder plugin

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5876]
hi
After selecting the variables, the prices of the variables are updated in the add to cart button widget. https://prnt.sc/Z8arAz740zyS
This is not really interesting. Please improve this.
Actually after selecting the variables, the price should not be updated in the add to cart button widget. Rather, it should be updated in the Single Price widget.
After the user selects the desired variables, the price (Single Price widget) will be updated immediately. This is really great.
In general, the add-to-cart button widget should not display a price. Please review and correct this. it's too important. thanks.

**Comment by ossamainternational** [comment]
I hope to get this fast!

**Comment by 79ho3ein** [comment]
+1
This is really great. But the thing is that jet woobuilder follows WooCommerce functionality. But if jet woobuilder can somehow improve this, it would be really great.
If we always move within the framework of WooCommerce, we will always remain in a limited space. So it would be great if jet woobuilder works on these. I hope it is possible.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. But you can use this small code snippet, it will help you to replace the top variable product price with the one of the current variation, while also hiding the variation price.

```
add_action( 'woocommerce_variable_add_to_cart', '__your_theme_prefix_update_price_with_variation_price' );

function __your_theme_prefix_update_price_with_variation_price() {

	global $product;

	$price = $product->get_price_html();

	wc_enqueue_js( "      
		$( document ).on( 'found_variation', 'form.cart', function( event, variation ) {   
			if( variation.price_html ) $('p.price').html(variation.price_html);
			$('.woocommerce-variation-price').hide();
		} );
		
		$( document ).on( 'hide_variation', 'form.cart', function( event, variation ) { 
			$('p.price').html('" . $price . "');
		} );
	" );

}
```

Thank you!

**Comment by Michaelgimii** [comment]
hi @UraraReika , Thanks for this great code. After adding this code, everything works fine. The only problem is that after selecting the variables, the cart button part jumps a little. Is there a solution for that? please

https://user-images.githubusercontent.com/88034902/189631231-b15ef696-5cd9-4d0a-9bf1-b312322a7ca8.mp4

**Comment by UraraReika** [comment]
Update `wc_enqueue_js()` code like this:

```
wc_enqueue_js( "      
    $( document ).on( 'found_variation', 'form.cart', function( event, variation ) {   
	    if( variation.price_html ) $('p.price').html(variation.price_html);
    } );
    
    $( document ).on( 'hide_variation', 'form.cart', function( event, variation ) { 
	    $('p.price').html('" . $price . "');
    } );
" );
```

And add this style to your widget like this https://tppr.me/Y0pbD:

```
selector .woocommerce-variation-price {
    display: none !important;
}
```

**Comment by Michaelgimii** [comment]
thank you veru much

**Comment by ossamainternational** [comment]
Hi @Michaelgimii pls could you share where you put both codes? it's been a while searching for that solution too!

**Comment by Michaelgimii** [comment]
hi @ossamainternational , I tested this code again and there seems to be a problem. Among the prices among the variables, the sale price of one of the variables is not displayed. Anyway, put the following code in your template function and add the css snippet above to the custom css of the add to cart widget. 


add_action( 'woocommerce_variable_add_to_cart', '__your_theme_prefix_update_price_with_variation_price' );

function __your_theme_prefix_update_price_with_variation_price() {

	global $product;

	$price = $product->get_price_html();

	wc_enqueue_js( "      
    $( document ).on( 'found_variation', 'form.cart', function( event, variation ) {   
	    if( variation.price_html ) $('p.price').html(variation.price_html);
    } );
    
    $( document ).on( 'hide_variation', 'form.cart', function( event, variation ) { 
	    $('p.price').html('" . $price . "');
    } );
" );

}
