### ISSUE TITLE
Display dynamic widget (profile, log out) in the header after someone logged in

### ISSUE THREAD

**Issue by ossamainternational** [CrocoBlock/suggestions#5877]
Hi, 
We hope to see this feature ASAP! 
once someone is registered in the store, Display a dynamic element (profile, log out) in the header instead of a static header.

**Comment by RoynerG** [comment]
dynamic visibility

**Comment by rtpHarry** [comment]
As @RoynerG says, dynamic visibility would let you do this:

https://crocoblock.com/knowledge-base/articles/jetengine-dynamic-visibility-module-options-overview/

There is also JetThemeCore which lets you display different templates based on criteria such as logged in, user role, etc:

https://crocoblock.com/plugins/jetthemecore/

**Comment by ossamainternational** [comment]
I think you can't display a dynamic widget that gives the customer to (Login Out) after he Logged In!
If  I'm wrong let me know guys

**Comment by rtpHarry** [comment]
Hmm, I did a bit of research and it seems that maybe this is missing. It's quite easy to implement though.

Just add this to your `functions.php`:

```
function rtp_wp_logout_url( $atts ) {
	$default = array(
		'redirect' => '',
	);
	$a = shortcode_atts($default, $atts);
        return wp_logout_url($a['redirect']);
  }
  add_shortcode('wp_logout_url', 'rtp_wp_logout_url');
```

And then set the log out button to use a dynamic shortcode tag:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/1038062/189601644-46251868-6ff4-45b6-a7e2-0abbee68a4e5.png">

You can leave the `redirect="/"` if you want to be taken to the default WordPress logout page.

There is also a WooCommerce version of this which you could replace my code with quite easily:

```
// https://www.collectiveray.com/login-logout-links-woocommerce-menu#h2-change-functions-php-to-create-woocommerce-logout-link-and-login-link
function rtp_woo_logout_url()
{
	$redirect = '';
	if(function_exists('wc_get_page_id')) {
		$redirect = get_permalink(wc_get_page_id('myaccount'));
	}
	
	return wp_logout_url($redirect);
}
add_shortcode('woo_logout_url', 'rtp_woo_logout_url');
```

This will log you out using WooCommerce features and drop you off on the WooCommerce login page, which is going to be styled nicely to match the theme, instead of the default WordPress login page.

**Comment by ossamainternational** [comment]
Hello buddy!
I appreciate your help, but I didn't catch that yet! let me give you a clue about how I designed my header:: 
the header consists of Logo, Search, Button (where I add my account link, I name it 'Account" ), and Cart...
so, how can I make the button shows up with logout after someone logged in? 
As you put above **And then set the log out button to use a dynamic shortcode tag** should I set the shortcode in the Account button?

**Comment by Floydtm** [comment]
@ossamainternational 
Describe your request in more detail, if possible, add screenshots or video. Thank you! You were offered several options, but none of them fit. You can also use the auth link widget

**Comment by rtpHarry** [comment]
@ossamainternational If you look back at [this comment](https://github.com/Crocoblock/suggestions/issues/5877#issuecomment-1242715255) then I describe two ways that you can set it up.

I would recommend using dynamic visibility. You set the dynamic visibility of your Account button to be only visible when the user is not logged in.

Then you make another button next to it, using the logout snippet I [suggested here](https://github.com/Crocoblock/suggestions/issues/5877#issuecomment-1243361004). Use dynamic visibility to only show that button when the user is logged in. 

It might look a bit messy in the editor, but when you look at it as a site visitor you will only see one of the two buttons, depending if you are logged in or not.

**Comment by ossamainternational** [comment]
Hi Buddy! thanks for sharing it works fine!
I have one more Qst pls: How to display another widget ACCOUNT SETTING so after somebody logs in it will appear as two widget LOG OUT & ACCOUNT SETTING

Thanks sir ::))

**Comment by ossamainternational** [comment]
Hi buddy! much appreciated 
I'm facing an error, I do all the steps above, and it works well but after clicking on **STORE LOGO** which includes the home page URL it appears **ACCOUNT** does not **LOG OUT**.

**Comment by ossamainternational** [comment]
YOOO MAAN! You're amazing, much appreciated 🙌🙌🙌

**Comment by rtpHarry** [comment]
No worries, glad it helped. Don't forget to close the issue if its all sorted now :)
