### ISSUE TITLE
WooCommerce MPN (manufacturer part number) / GTIN / EAN / UPC Support

### ISSUE THREAD

**Issue by maverick85** [CrocoBlock/suggestions#5879]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
Not according to the information received on ticket 106642

- if the feature is missing from the products.
YES.

**Please, describe the feature request, making it clear to understand.**
WooCommerce natively only expects a SKU number. SKU is, as is known, Stock Keeping Unit, and a LOCAL identifier for the product.
Most products have their own Part Numbers, which are universal, just like the GTIN counterpart, which is a global identifier.

**Add an example of where this feature is already implemented. **
WPSSO Product Metadata for WooCommerce SEO

**Provide a detailed explanation of where this feature should be used, and if there are any alternatives already.**
This feature is practically MANDATORY for any serious web store, as the above references are GLOBAL AND UNIQUE identifiers for the products.

There are alternatives, just like the one provided above.
The biggest problem is, if you use such plugins, then the Meta Elements provided by Crocoblock DO NOT ALLOW this information to be added to the product page. We're still trying to figure out how to get around CrocoBlock to be able to add this information to the product page, where Crocoblock is actually MAKING EVERYTHING MORE DIFFICULT.

Feel free to add any videos, links, screenshots to illustrate the requested feature.
I won't even put the product name, because searching for any of the available codes here, you'll find the product elsewhere. As you should, using global identifiers.
![Screenshot 2022-09-09 at 11 39 43](https://user-images.githubusercontent.com/10200278/189332349-f76ef82a-0505-482b-bc84-46c1a07f7392.png)

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by UraraReika** [comment]
Hello @maverick85, Thanks for the feedback.

You can use JetEngine plugin for display this info. Here are some tips:
1 - Install JetEngine to unlock dynamic widgets and some specific dynamic tags for Elementor.
2 - Setup product info. Like in your screenshot. My setup - https://tppr.me/oGic1.
3 - Open JetWooBuilder single product template of Elementor Pro Single product template for edit.
4 - In my case i use widget Dynamic field but if you familiar with dynamic tags you can use them as well. Feel free to contact our support team. Drag and drop Dynamic widget in desirable place. 
5 - Setup widget like this https://tppr.me/bCTpl. Key for `Custom meta field/repeater key` option you can get like this.
     5.1 - Go to edit product page https://tppr.me/tTMru. Any product.
     5.2 - Right click input field https://tppr.me/tvMpX. Press inspect and you will get this picture. Copy name field https://tppr.me/Qmz4h.
     5.3 - Paste in to widget field.
6 - Same steps for other field.

Result you can see it https://tppr.me/JGZo0. Then widget gives you opportunity to style your widget as well as edit output.

**Comment by maverick85** [comment]
Dear @UraraReika, does this add these fields to the the schema mpn, gtin etc?
Structured product data like product:ean etc for use with merchant feeds?

From the conversation I had with support via regular, it doesn't seem like it, and if not, then this is not an acceptable solution for this data.
Thank you for your reply.

**Comment by UraraReika** [comment]
You can output whatever field you want from this list https://tppr.me/YEun9 with the help of the steps above. I just uses fields that you present in your screenshot.

**Comment by maverick85** [comment]
Thank you @UraraReika . We'll go through your instructions and test.
