### ISSUE TITLE
Delete a Meta Field and also delete it from the database

### ISSUE THREAD

**Issue by borjamerino-v** [CrocoBlock/suggestions#5880]
We have detected that when we create a CPT and add Meta Fields to it, if we delete one of them, it is not completely removed, leaving a trace of it in the database.

We think that when deleting a Meta Fields, for example, you should also delete it from the database and we suggest that you do so.

**Comment by 79ho3ein** [comment]
+1

**Comment by JairoLopezCo** [comment]
+1

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/5004)
