### ISSUE TITLE
Two important problems in displaying favorites in the jet woobuilder Product Grid widget

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5885]
**Describe the bug**

Hi crocoblock team

1- After updating jet woobuilder to version 2.0.4, I put query on favorites in the product grid widget, but it displays all products. While we had not added any product to the list of favorites.

2- I decided to add add/remove button to favorites using [this option](https://prnt.sc/ReFOWKh5at01) in the product grid widget. So that users can add the desired product to their wishlist by clicking on the button. If they click on the button again, the product will be removed from the wish list.
But there is a very important problem. **The interest button is displayed only when the user hovers the mouse over the product box.**
This is especially problematic for users who visit the website on mobile. Because if the user clicks on the product, she will enter the product page.

Please add an option to the product grid widget > wishlist so we can specify whether the add to wishlist button is always display, or only when the user hover over the product box by mouse.

This is a very important issue. Please make it your priority. Thanks.

joila

**Comment by UraraReika** [comment]
Hello @Joliamendi! Thanks for the feedback.

1 - Fixed;
2 - Please track this issue https://github.com/Crocoblock/suggestions/issues/5859.

**Comment by Joliamendi** [comment]
thank you @UraraReika , excuse me, Will these be resolved in 2.0.5, or future jet cw update?

**Comment by UraraReika** [comment]
It will be solved in 2.0.5

**Comment by Joliamendi** [comment]
thank you @UraraReika.
Can I ask the second item, will it be added in the next update of jet CW or not?

**Comment by Joliamendi** [comment]
Hi @UraraReika. Is it known when the 2.0.5 version will be released?

**Comment by Michaelgimii** [comment]
+1 
Is there an update for it yet?

**Comment by Joliamendi** [comment]
Hi @UraraReika , Is there any news about the release of version 2.5? please
