### ISSUE TITLE
Smart Filter > Date Range Filter > Style Inputs > Color does not work

### ISSUE THREAD

**Issue by Rubenzella** [CrocoBlock/suggestions#5888]
The color styling option for the "inputs" in the date range filter does not apply any color, either from global color or color picker.

1. Click on Date Range Filter Widget
2. Click on Style
3. Scroll down to Inputs
4. Try to change the color for the placeholder text.

The placeholder text does not change the color you picked.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
[Elementor _ Calendar Page.zip](https://github.com/Crocoblock/suggestions/files/9555004/Elementor._.Calendar.Page.zip)
