### ISSUE TITLE
Possible bug in jet compare and wishlist plugin

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5889]
**Describe the bug**

If the user is not logged in and adds products to her wishlist, if she logs in, the products she added to her wish list before logging in will be deleted.
But in WooCommerce shopping cart it works fine. If the user adds products to his shopping cart before logging in, after logging in, the items added to the shopping cart are saved in his user account.

**To Reproduce**

1- As a guest user, add some products to your wishlist.
2- After that register or login to the website

You can see that the products you added to your wish list before logging in and registering have been removed.

**Comment by UraraReika** [comment]
Hello @Joliamendi. Thanks for the feedback.

This problem can appear depending on settings that you use for storing lists. So if you setup your settings like this https://tppr.me/wnP4h then when you not log in your selections will be stored in cookies and you will get data from cookies. But you see that this option enabled https://tppr.me/LVty9. This means that when you were log in and add products to the list it saved your data to user meta and when you log in you pull the data from this user meta.

So that is why you get this strange behaviour. Just setup plugin settings correct.

**Comment by Joliamendi** [comment]
Hi @UraraReika , Apologies for the delay.
I think you don't understand what I mean. If a user (guest) adds a product to her wishlist and then login, after logging in, that product will not be in the user's wishlist and will be deleted. I selected cookie and session but there is this problem for both.
But in WooCommerce, if you add a product to the cart as a guest user and then log in, this product will be in your cart after logging in.

**Comment by UraraReika** [comment]
> Hi @UraraReika , Apologies for the delay.
> I think you don't understand what I mean. If a user (guest) adds a product to her wishlist and then login, after logging in, that product will not be in the user's wishlist and will be deleted. I selected cookie and session but there is this problem for both.
> But in WooCommerce, if you add a product to the cart as a guest user and then log in, this product will be in your cart after logging in.

Please show me screenshot how you setup your wishlist settings.

**Comment by Joliamendi** [comment]
> > Hi @UraraReika , Apologies for the delay.
> > I think you don't understand what I mean. If a user (guest) adds a product to her wishlist and then login, after logging in, that product will not be in the user's wishlist and will be deleted. I selected cookie and session but there is this problem for both.
> > But in WooCommerce, if you add a product to the cart as a guest user and then log in, this product will be in your cart after logging in.
> 
> Please show me screenshot how you setup your wishlist settings.

![jet cw](https://user-images.githubusercontent.com/103376243/194047230-95cf47a3-a3cb-4996-bcc3-bf16e7a6272f.png)

**Comment by UraraReika** [comment]
As i said in my previous message the problems is in how you setup the wishlist. You enabled this option https://tppr.me/wJCBy and it means that if user logged in he will store wishlist info in user meta as well as he will get data from there. So if user meta is empty you will nothing to get.

In your case user is logged out and start to add products to list. So he has some products in it and while he not log in his data stored in session or cookies whatever you choosed as well as takes data from session or cookies. But ones you log in and this option is enabled https://tppr.me/wJCBy you will get data from user meta which is empty or can has different set of products.

**Comment by Joliamendi** [comment]
thank you @UraraReika , If I disable [this option](https://tppr.me/wJCBy) it works fine, but it is no longer stored in the users account!
So how does the WooCommerce cart work? Everything is good in it.

**Comment by UraraReika** [comment]
Woocommerce carts data stores in session

**Comment by Joliamendi** [comment]
Right, according to the screenshot I posted above, shouldn't they behave like WooCommerce? But it doesn't.
