### ISSUE TITLE
CountDown Widget

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#589]
I'm currently setting up events post type with date and time as the event start and would be great to use the countdown timer and have it dynamically lookup the date and time field so that it can be automatically calculated.

This would suddenly open up the countdown marker to be more useful in a larger setup

**Comment by scubaninja1977** [comment]
Ok, so you can configure the countdown to work dynamically but it will only work for a date and not a time, the issue is if we have an event that starts at 10 am, we are unable to get the countdown widget to countdown till a particular date and time.

**Comment by Floydtm** [comment]
Your request can be implemented using real versions of JET plugins
