### ISSUE TITLE
product carousel box Custom Style (border radius)

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5894]
**Please, describe the feature request, making it clear to understand.**

I wanted to create such a beautiful carousel with jet woobuilder : https://prnt.sc/XabNtDqAdZkj
As you can see in the screenshot above, the beginning of the carousel and the [end](https://prnt.sc/pZPtSb4h5EKL) of the carousel are round.

But currently this possibility is not available in jet woobuilder. It would be great if you add an option so we can customize the border radius on the first and last product boxes. Such a similar feature exists in the jet menu plugin for the megamenu widget.

This is something that would be great if added. (This option will only control the border radius)

https://user-images.githubusercontent.com/103376243/189773708-3ac9e234-7ced-47c6-8556-e67a290a99f5.mp4

**Comment by UraraReika** [comment]
Hello @Joliamendi, Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But you can use some small css code to achieve this result, put this code to your advanced tab of the widget if you have Elementor Pro:

```
selector .jet-woo-carousel {
    border-radius: 25px;
}
```

If not add some specific identifier for your widget like this https://tppr.me/FsDWd and paste next code to customizer for example:

```
#round-corners  .jet-woo-carousel {
    border-radius: 25px;
}
```

**Comment by Joliamendi** [comment]
thanks

**Comment by Joliamendi** [comment]
@UraraReika , Thanks for the code. This code applies to the visible part of the product grid widget. But I meant to apply the border radius for the first and last box of the product. Please see the video below. Is there a way for it?

https://user-images.githubusercontent.com/103376243/189895253-3c14f9aa-9f11-4043-bd4f-4f75aa2facac.mp4

**Comment by UraraReika** [comment]
Please contact our support team they will help you to implement this solution.
