### ISSUE TITLE
JetElements - Dropbar - Flex container bug

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#5895]
Jetelements version: 2.6.7
Elementor version: 3.7.4
Elementor Pro version: 3.7.5

Desc:

Looks like, if using the Dropbar widget, no matter whether you enter a template or plain text, in all cases the content is displayed incorrectly, as if it were slipping under every other element. Playing around with the Z-index settings does not solve it.

**Comment by amadeus77** [comment]
![image](https://user-images.githubusercontent.com/60214411/232720367-90163da9-c608-4845-adab-a8bc0d0c3e9d.png)
In my eyes the bug still isn't fixed!
