### ISSUE TITLE
Add SQL Query Results Dynamic Tag For Use In Listing Grid Widget

### ISSUE THREAD

**Issue by NimaBakhtiyari** [CrocoBlock/suggestions#5898]
Add SQL Query Results Dynamic Tag For Use In Listing Grid Widget > Posts & Author Parameters > Include or Exclude Posts By IDs Field; There is no way to filter listing grid widget posts by SQL query results returned by Jet Engine Query Builder.
For example, if you get the product IDs of orders that are only in completed status, there is no way to include or exclude Posts by those IDs in the listing grid widget.
But this was just an example and unlimited possibilities will be added by this feature.
![image](https://user-images.githubusercontent.com/90132570/189882565-4e762e03-caee-4243-8d23-282f2cce9f60.png)
![image](https://user-images.githubusercontent.com/90132570/189883105-2b425f7c-57da-49ee-a930-07648f92ef2d.png)

**Comment by MjHead** [comment]
https://github.com/Crocoblock/suggestions/issues/5617 - similar issue already exists and will be implemented with 3.0.5 update

**Comment by NimaBakhtiyari** [comment]
> #5617 - similar issue already exists and will be implemented with 3.0.5 update

thanks

**Comment by NimaBakhtiyari** [comment]
> #5617 - similar issue already exists and will be implemented with 3.0.5 update

It seems that it is still not implemented with version 3.0.6.1. If it is implemented, where can I find it?
