### ISSUE TITLE
CPT layout fields to be side by side (50% width)

### ISSUE THREAD

**Issue by pintolog** [CrocoBlock/suggestions#59]
Please make a layout design that the CPT fields will be 50% wide so it will be side by side.

I know ACF can do 50% width for the fields, can jet-engine do this also?

![image](https://user-images.githubusercontent.com/7497319/53398759-1bcf2400-39b3-11e9-8864-cf5642611d89.png)

**Comment by RodSuper** [comment]
I love this idea! Good thinking

**Comment by MjHead** [comment]
Added in JetEngine 1.4,0
