### ISSUE TITLE
JetSmartfilter Permalinks to Correspond with Wordpress Slugs

### ISSUE THREAD

**Issue by glissprints** [Crocoblock/suggestions#590]
I'm trying to use JetSmartFilters to link to a specific set of product categories/attributes in my Megamenu, but the urls looks like this: https://glissprints.com/shop/?jet-smart-filters=epro-archive-products/default&_tax_query_product_cat%5B%5D=66

The wordpress generated slug is clean and has the correct breadcrumbs on the page, for example: https://glissprints.com/product-category/printables/
However, going to this link does not have the correct category selected in the left sidebar, as shown in the screenshot
![Screen Shot 2019-10-20 at 4 35 55 PM](https://user-images.githubusercontent.com/56806154/67168295-f59e3000-f357-11e9-9322-0a6243589352.png)

**Comment by realstephenzhao** [comment]
Yes, this is not SEO-friendly, so I use Ajax on click to avoid this ugly slug.

See this same open issue -> https://github.com/Crocoblock/suggestions/issues/243

**Comment by UraraReika** [comment]
I merged this issue with #243 , which is on the same subject so we could deal with it more efficiently.
