### ISSUE TITLE
Add A Counter Ability Or Separate Widget For Palceing Post Rank Counting Ability In Listing Grid 

### ISSUE THREAD

**Issue by NimaBakhtiyari** [CrocoBlock/suggestions#5900]
For example, we want to list the best-selling products on our site in the order of sales, but to show the rank of each one, there is no available tool.
Something like the picture below:
![image](https://user-images.githubusercontent.com/90132570/189895931-b9205e74-a18e-481b-9f33-0b4b501d9b1a.png)

**Comment by Floydtm** [comment]
You can implement this with jet engine plugin right now. To do this, you just need to use a query builder. You will also need to [install](https://crocoblock.com/freemium/tools/) [this](https://prnt.sc/ngKMirI0nqCk) add-on to display the counter. Here is what I managed to do https://prnt.sc/feLlUJkxdWQw Unfortunately, we don't have a tutorial on this topic yet, but you can contact our support team and the guys will help you. Thank you!

**Comment by NimaBakhtiyari** [comment]
> You can implement this with jet engine plugin right now. To do this, you just need to use a query builder. You will also need to [install](https://crocoblock.com/freemium/tools/) [this](https://prnt.sc/ngKMirI0nqCk) add-on to display the counter. Here is what I managed to do https://prnt.sc/feLlUJkxdWQw Unfortunately, we don't have a tutorial on this topic yet, but you can contact our support team and the guys will help you. Thank you!

Thank you, you are the best
