### ISSUE TITLE
Jet Smart Filters and mega menu

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#591]
The filters work great but can be a little difficult to configure layouts etc, one suggestion, would be a mega menu style option on Drop-Downs, This will allow people to display a large number of filters, nicely inline, see image for sample.

![73127470_2396796630428841_2204043269162139648_o](https://user-images.githubusercontent.com/51353309/67176639-795e2800-f3fd-11e9-96f7-4de012c7edb4.jpg)

**Comment by UraraReika** [comment]
I merged this issue with #650 , which is on the same subject so we could deal with it more efficiently.
