### ISSUE TITLE
Open URL link in new browser tab

### ISSUE THREAD

**Issue by unitedonline** [CrocoBlock/suggestions#5917]
I have a CPT text field and a JetFormBuilder corresponding url field.

Ηow do I render the URL field with the option to open in a new browser tab?

I do not see this option in the "Make Clickable" callback selection.
Customizing the field output with <a href=\"%s\" target="_blank">URL Link</a>  unfortunately does not work.
Can you please include this feature sometime in the future ?

Thank you

**Comment by kaskad88** [comment]
Hello @unitedonline.
Unfortunately the "Make Clickable" callback does not have such an option https://developer.wordpress.org/reference/functions/make_clickable/.

But you can use the `Dynamic Link` widget for your case https://tppr.me/vKW2D
