### ISSUE TITLE
required mark control for jet woobuilder checkout fields.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5921]
**Please, describe the feature request, making it clear to understand.**

Hi

It would be great if you could add an option to allow customization of the required mark. Just like jet form that uses [this control](https://prnt.sc/wWS6cM4boyPT).

This control is required for Checkout Billing Form, Checkout Shipping Form and Checkout Additional Form widgets. Especially the Checkout Additional Form widget, which has no control over the required mark : https://prnt.sc/XCwWQzpYUDHe

thank you.

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Unfortunately there is no appropriate hook which can help us to change this mark.

Thank you for your understanding.
