### ISSUE TITLE
Adding A Macro For Woocommerce Cross Sell Poducts IDs

### ISSUE THREAD

**Issue by NimaBakhtiyari** [CrocoBlock/suggestions#5925]
Adding A Macro For Woocommerce Cross Sell IDs For Current Product Or Some way Like This to Filter Listing Grid, Right Now No Way To Show Cross Sell Product With Custom LIsting Grid Or maybe I Don't Know!

**Comment by UraraReika** [comment]
Hello @NimaBakhtiyari! You can use this small snippet to achieve needed result.

```
add_filter( 'jet-engine/listings/macros-list', 'jet_register_custom_macros' );

function jet_register_custom_macros( $macros_list ) {
	$macros_list['jet_upsell_ids_products'] = 'jet_upsell_ids_products';
	$macros_list['jet_cross_sell_ids_products'] = 'jet_cross_sell_ids_products';
	return $macros_list;
}

function jet_upsell_ids_products() {
	global $product;

	if ( ! $product ) {
		return;
	}

	$upsells_products = $product->get_upsell_ids();

	return implode( ',', $upsells_products );
}

function jet_cross_sell_ids_products() {
	global $product;

	if ( ! $product ) {
		return;
	}

	$cross_sell_products = $product->get_cross_sell_ids();

	return implode( ',', $cross_sell_products );
}
```

**Comment by NimaBakhtiyari** [comment]
> Hello @NimaBakhtiyari! You can use this small snippet to achieve needed result.
> 
> ```
> add_filter( 'jet-engine/listings/macros-list', 'jet_register_custom_macros' );
> 
> function jet_register_custom_macros( $macros_list ) {
> 	$macros_list['jet_upsell_ids_products'] = 'jet_upsell_ids_products';
> 	$macros_list['jet_cross_sell_ids_products'] = 'jet_cross_sell_ids_products';
> 	return $macros_list;
> }
> 
> function jet_upsell_ids_products() {
> 	global $product;
> 
> 	if ( ! $product ) {
> 		return;
> 	}
> 
> 	$upsells_products = $product->get_upsell_ids();
> 
> 	return implode( ',', $upsells_products );
> }
> 
> function jet_cross_sell_ids_products() {
> 	global $product;
> 
> 	if ( ! $product ) {
> 		return;
> 	}
> 
> 	$cross_sell_products = $product->get_cross_sell_ids();
> 
> 	return implode( ',', $cross_sell_products );
> }
> ```

Hello Dear Developer, Thanks For Your Help, Where should I Add This? In Child Theme Function.PHP Or In Plugin Folder

**Comment by UraraReika** [comment]
Use it in the child theme functions.php
