### ISSUE TITLE
Jet Smart Filter GEO

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#5927]
Hello, consider the option to allow the user to select the radius of displaying objects on the map or in listings in the filter. Now there is a functionality where we determine the radius ourselves, we have conditionally assigned 5 km., but is it suitable for a site visitor? Someone yes, and someone needs 10 km., but we do not give the opportunity to change it on the site yourself.

/*Оригинал*/
Здравствуйте, рассмотрите вариант дать возможность пользователю выбрать в фильтре радиус отображения объектов на карте или в листингах. Сейчас есть функционал, где мы сами определяем радиус, назначили условно 5 км., но подходит ли это посетителю сайта? Кому-то да, а кому-то нужно 10 км., но мы не даем возможности это изменить на сайте самостоятельно.

**Comment by kskonovalov** [comment]
+1 sounds useful

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
