### ISSUE TITLE
jet woobuilder widgets in elementor flex box container

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5935]
**Describe the bug**

Hi

In the previous version, the problem of the width of public widgets ( product grid and Categories Grid ) in the container was solved. 
But this problem currently exists in product list, checkout and cart widgets and other widgets.
**The problem is that if the direction of the container is row, if we add jet woobuilder widgets, they have very small width.**

**A few examples**
- [product list widget](https://prnt.sc/dRztjK8oqAQE)
- [Checkout Additional Form	](https://prnt.sc/-x4xdOSFXH6I)
- Checkout Billing Form
- and all widgets

We can control it using the [width of the widgets](https://prnt.sc/LAuaSMSuYmJq), but it would be much better if they were 100% by default.

**Comment by UraraReika** [comment]
Hello @79ho3ein, thanks for the feedback.

See no problem with this. This is how this functionality works.  You can check this not only with JetWooBuilder widgets but with default Elementor widgets as well.

**Comment by 79ho3ein** [comment]
Hi, thanks
