### ISSUE TITLE
Ability to create checkout, cart, etc templates faster in jet woobuilder.

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5936]
**Please, describe the feature request, making it clear to understand.**

Hi crocoblock team.

Currently, it is a bit difficult to create checkout and cart pages even my account in jet woobuilder. Especially for new users. But this process is much faster in elementor. It would be great if you could speed up the process of creating these pages in jet woobuilder like Elementor.

**Steps to create cart page or... in jet woobuilder**
1- Create a page
2- Put the shortcode inside it
3- Create a page in jet woobuilder : https://prnt.sc/XMz9tkSjoGTs
4- Selecting a page in WooCommerce : https://prnt.sc/-JiSdsoAeqv0
5- Select page in WooCommerce configuration > Jet Woobuilder tab : https://prnt.sc/ip4gtMK_0SKl

**Steps to create cart page or... in elementor**
1- Create a page
2- Select the desired page from the site settings : https://prnt.sc/lAXeylY-CwbV

Please improve the process of creating WooCommerce pages in jet woobuilder.

**proposed solution**
1- create a page
2- Create template in jet woobuilder : https://prnt.sc/XMz9tkSjoGTs   -    After saving, a message will be displayed according to the widgets used. Should it be selected as a checkout (for example) page? If we choose yes, the page for cart or checkout will be selected automatically.

This is just a suggestion. Because Elementor works like that. Please do whatever you can but only improve the current situation. thanks

**Comment by Lonsdale201** [comment]
We should add that normally Woocomerce creates the mandatory pages according to the language you have set up, so we can remove the first and second points from the Jetwoo procedure. But, good point. It would be nice to have something like JetThemeCore for a transparent interface to set and manage these. :)

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello @Joliamendi , thanks for the feedback.

First of all I need to mention if you instal, activate WooCommerce and setup store settings after it the default pages already created with proper shortcodes and selected in WooCommerce settings. If not you can easily do it by go to WooCommerce > Status > Tools Tab and here you can find Create default WooCommerce pages. After you pressing this options all pages will created with all right settings and shortcodes. So now we can remove 3 steps from your creation and replace it with only one. 

Now you need just create JetWooBuilder template and setup it in the options. So to activate and use our templates you need only 3 steps.

Functionality of our plugin build the way that it automaticaly detects this created pages and replace it with Elementor templates. But it doesn't create it. And unfortunately but we do not plan to introduce such functionality into our plugin.

Thank you for your understanding.
