### ISSUE TITLE
Jet elements parallax New Conteiners

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#5938]
Good afternoon. There is a Section Parallax Extension in JetEments, but this extension does not work for containers. Please add Parallax Extension for containers.

**Comment by stasonua0** [comment]
Is something required of me?

**Comment by andreluizts1-2** [comment]
Hi, i cant find the parallax dropdown menu on layout container from Elementor, even i installed the jetelements plugin and activate it

**Comment by aalexandr21** [comment]
@andreluizts1-2 

<img width="486" height="597" alt="Image" src="https://github.com/user-attachments/assets/4ae8d81c-9d02-4d3a-b2ad-80e793e769d8" />

If you have some other questions, please get in touch with our support team https://crocoblock.com/help-center
