### ISSUE TITLE
Pagination doesn't work with user query

### ISSUE THREAD

**Issue by studiokoch** [CrocoBlock/suggestions#5944]
I have a normal user query to display a user list via the tables builder.
This works fine, however, I want to add pagination.

I cannot add the number of results so it can work with the pagination filter.

Thanks,
Paul

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue. 
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by studiokoch** [comment]
I made a new Query. New name, but exactly the same. And that worked fine.
Strange, but problem solved. :-)
