### ISSUE TITLE
[Bricks Page Builder] [Option Page] More flexibility and meta key filter for Repeater Field on Options Pages Item

### ISSUE THREAD

**Issue by LiamX2** [CrocoBlock/suggestions#5945]
Hi there, I noticed there is no Meta query filter for repeater field within Options Pages. Could you please add more flexibility for repeater fields on Options pages. I have attached the comparison images for your reference.

Thanks a lot.
<img width="287" alt="Screen Shot 2022-09-21 at 11 19 33 am" src="https://user-images.githubusercontent.com/74690623/191393616-f96ad23f-d1f6-41ad-836f-a0e24fc969d3.png">

<img width="273" alt="Screen Shot 2022-09-21 at 11 19 59 am" src="https://user-images.githubusercontent.com/74690623/191393621-f1e2febb-eaab-4e04-b45d-8e140220da0d.png">

**Comment by oncps** [comment]
Muito bom!!!
E no elementor, Pode adicionar também, um campo do tipo "número" para limitar a quantidade que o usuário possa adicionar o repeater... 
Um exemplo: Piotnet forms tem isso..
Lá eu consigo limitar a quantidade que o usuário pode adicionar repeater .

**Comment by MjHead** [comment]
Its functionality added by Bricks builder core, we can't affect it. But with 3.1.1 planned to add compatibility of Bricks Query Loop  with JetEngine Query builder. Query builder has Repeater query type since 3.1.0, so you can use this combination
