### ISSUE TITLE
[JetBooking] Move / add global timeframe setting (daily booking, weekly booking, multiday booking) for individual bookable objects

### ISSUE THREAD

**Issue by Seifenigel** [CrocoBlock/suggestions#5949]
Instead of having a setting to decide wether or not your whole pool of bookable objects (accommodations, objects, etc) should be rented on a weekly, daily or custom base, make this an option for each object localy.

This would give a wider variety of uses and the ability to add eg daily events to a accomodation booking.

**Comment by oncps** [comment]
Isto será muito útil .
Definir horário  e valores para cada dia selecionado individualmente..
Exemplo: definir dias da semana colocar um preço para cada dia ..
E ter a opção de adicionar separadamente para finais de semana e feriado prolongado , que seria  outros valores que podemos adicionar .

**Comment by UraraReika** [comment]
Check 2.6.3 release
