### ISSUE TITLE
Better ui to display wishlist, compare and... buttons in jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5957]
It would be nice if you add an option so that we can customize the compare & wishlist buttons (even the jet popup quick view button) in one box. https://prnt.sc/Iz4BcHp6T2jf
In fact, we need a new section in the style tab of the product grid widget, so that we can have a common background, box shadow, border, and border radius for these buttons.
We can customize the background of these buttons both individually and in groups, which is great.

**Comment by UraraReika** [comment]
Hello @Michaelgimii, thanks for the feedback.

You can already achieve this result like this https://monosnap.com/file/mgSQVioRCRhDDLNo8skLT0MfYUPFjB. If you struggle with this please contact our team.

Thank you for your understanding.

**Comment by Michaelgimii** [comment]
Hi @UraraReika , In the above screenshot condition, can we seamlessly create a box shadow for it?

**Comment by UraraReika** [comment]
> Hi @UraraReika , In the above screenshot condition, can we seamlessly create a box shadow for it?

This one is tricky but possible with some custom styles.
