### ISSUE TITLE
JetElements: Instagram widget (more display settings)

### ISSUE THREAD

**Issue by philmatt** [Crocoblock/suggestions#596]
I would like to request that the display settings in the Instagram widget be expanded:

**Add the ability to control both the source (My Photos vs All Photos) and the photo tag at the same time**
_E.g. Show all My Photos tagged #summer_ 
![image](https://user-images.githubusercontent.com/47516673/67357824-59b92380-f513-11e9-81a1-ac6457ee3d3b.png)

**Comment by Floydtm** [comment]
@philmatt, Hi! We cannot realize this. API does not allow it
