### ISSUE TITLE
JetEngine Feature Request - Copy to clipboard

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#5967]
Hello everyone, I come once again to request an improvement in the optimization of our work with JetEngine, I usually create several fields for Options Pages, CPT, Metaboxes and CCT according to the project and I always copy and paste the Name Id several times to configure forms , shortcodes and the like, I think you understand....

My suggestion is that by clicking on the Name, the information is automatically copied to the clipboard :) It's simple, but I believe it would help a lot and reduce the chance of copying the name id wrong, with space or missing a letter for example.

Thanks to everyone on the team for the great work you've been doing.

![image](https://user-images.githubusercontent.com/6773491/191881783-75889eee-a8f1-482a-bab9-94797992346e.png)

**Comment by marreiradigital** [comment]
+1

**Comment by dyonatandias** [comment]
+1

**Comment by 79ho3ein** [comment]
+1

**Comment by DaviAppelDuarte** [comment]
+1

**Comment by royallogic** [comment]
+1 very usefull

**Comment by dantetesta** [comment]
+1 go go go

**Comment by taidang26** [comment]
+1 I think it will be more suitable to integrate into JetTrick. Hopefully they will have an update soon.

**Comment by tizum** [comment]
that would be great, copy the names easily, without error, without space, and one click away.

**Comment by dyonatandias** [comment]
+1

**Comment by morosmo** [comment]
+1

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.9
