### ISSUE TITLE
Widget Variable Table for Jet Woo Builder

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#597]
Hello, due to the fact that the templates created by Jet Woo Biulder are not integrated with plugins that can display variable products in the form of a table, could you create a widget for Jet Woo Builder that displays a table with all product variations?
Here is an example plugin - https://welaunch.io/plugins/woocommerce-variations-table/

/*Оригинал*/
Здравствуйте, в связи с тем что в шаблоны созданные Jet Woo Biulder не интегрируются плагинами которые умеют выводить вариативные товары в виде таблицы, не могли бы вы создать виджет для Jet Woo Builder который бы выводил таблицу со всеми вариациями товара? 
Вот пример плагина - https://welaunch.io/plugins/woocommerce-variations-table/

**Comment by UraraReika** [comment]
I merged this issue with #273, which is on the same subject so we could deal with it more efficiently.
