### ISSUE TITLE
Dynamic table customization

### ISSUE THREAD

**Issue by bombarda-rpd** [CrocoBlock/suggestions#5970]
The customization of a dynamic table could be taken even further. It should be able to: 
Set a mouse over per line. 
Set different colors per line
Set different borders per colum.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
