### ISSUE TITLE
JetReviews custom fields & rich text editor 

### ISSUE THREAD

**Issue by MasterOfWeb** [CrocoBlock/suggestions#5973]
It would be cool to have the option to add custom fields in the reviews so we could have a "author website" field or a dedicated "pros" & "cons" fields.

At least, it would be great to have the review content field with a rich text editor.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
