### ISSUE TITLE
Fatal Error with JetPopup and Elementor 3.7.7

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#5976]
Description
After updating today to 3.7.7 the site stops working, and i get this fatal error:

PHP Fatal error: Uncaught TypeError: Elementor\Core\Files\CSS\Base::get_style_control_value(): Argument https://github.com/elementor/elementor/pull/1 ($control) must be of type array, null given, called in /public_html/wp-content/plugins/elementor/core/files/css/base.php on line 682 and defined in /public_html/wp-content/plugins/elementor/core/files/css/base.php:738Stack trace:#0 /public_html/wp-content/plugins/elementor/core/files/css/base.php(682): Elementor\Core\Files\CSS\Base->get_style_control_value()https://github.com/elementor/elementor/pull/1 [internal function]: Elementor\Core\Files\CSS\Base->Elementor\Core\Files\CSS\{closure}()https://github.com/elementor/elementor/pull/2 /public_html/wp-content/plugins/elementor/core/files/css/base.php(448): call_user_func()https://github.com/elementor/elementor/pull/3 /public_html/wp-content/plugins/elementor/core/files/css/base.php(347): Elementor\Core\Files\CSS\Base->parse_property_placeholder()https://github.com/elementor/elementor/pull/4 [internal function]: Elementor\Core\Files\CSS\Base->Elementor\Core\Files\CSS\{closure}()https://github.com/elementor/elementor/pull/5 /public_html/wp-content/plugins/elementor...',

Steps to reproduce
Updated from 3.7.7 to 3.7.6. In console there is a swiper error and the website is down.
Also i have JetPopup 1.5.6 installed

**Comment by DanielRuf** [comment]
See also https://github.com/elementor/elementor/issues/19894

**Comment by Floydtm** [comment]
@ciprianpentelescu this problem should be fixed in the updated 1.6, check the plugin update and let me know if it helped you.
