### ISSUE TITLE
Jetblog - Smart Posts List - Allow more settings to be tablet/phone responsive

### ISSUE THREAD

**Issue by karifritsch** [CrocoBlock/suggestions#5977]
Other wishes:
- Allow us to customize the width of the hidden filter (Some category names are long) or only categories that have results in queries
- Ability to show custom categories with meta/move category from on top of thumbnail to above/below content
- paging arrows to be above articles

Responsiveness:
Pretty much everything
- Mark first post as featured
- featured post and regular image/layout, buttons, meta
- show post terms on top of thumbnails
- post terms filter
- set width/% for heading title vs filter

I have a smart post list that looks exactly the way I want it on desktop, but it looks absolutely horrid on mobile.

**Comment by PixelDesigns** [comment]
The JetBLog plugin is not mobile friendly. I'm using Elementor, and if I switch mobile view, it can't be set the post image position on Smart Post List widget. CSS formatting must be used. This: 

_@media screen and (max-width: 767px) {
.jet-smart-listing__post {
flex-wrap: wrap !important;
}
.jet-smart-listing__post-thumbnail.post-thumbnail-simple {
max-width: 100% !important;
flex: 0 0 100% !important;
}
.has-thumb-postion-left.has-post-thumb .jet-smart-listing__post-content {
margin-left: 0px !important;
margin-top: 8px;
}
}
@media screen and (max-width: 767px) {
.jet-smart-listing__posts {
margin-left: 0 !important;
margin-right: 0 !important;
}
}_

<img width="353" alt="Képernyőfotó 2023-03-27 - 14 20 50" src="https://user-images.githubusercontent.com/14098927/227944531-0a17922b-ff4c-4ef9-bea7-c744e98758e0.png">
Post Image Position, and Post Image Max Widht: No mobile option

And the Show Filter by Terms: No off option on mobile view.

**Comment by Crocoblock** [comment]
was added in JetBlog 2.3.8
