### ISSUE TITLE
JetBooking - Calendar View

### ISSUE THREAD

**Issue by IreneDania** [CrocoBlock/suggestions#5979]
I am using Jetbooking plugin. Is there a way to view the booking in calendar format? Just like JetAppointments allows.

**Comment by UraraReika** [comment]
Hello @IreneDania ! Thanks for the feedback.

Right now this isnt posible but this task is in our backlog!

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6303, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
