### ISSUE TITLE
Add style options for Dynamic Repeater listing widget

### ISSUE THREAD

**Issue by sigersmit** [Crocoblock/suggestions#598]
In the Dynamic Repeater widget it is possible to style the Items and Delimiter. It would also be nice to style the whole listitem (e.g. the general tab) with a background color, border, border-radius, box-shadow etc. Now I have to add a custom style to the widget.

It would be nice if one could choose a icon before a repeater item, choose before or after and set some margin. (Like Elementor does with a button).

It would als be nice if it is possible to set multiple repeater-boxes to the same height.

I really like the option to specify the item format, that gives a lot of freedom!

Thank you!

**Comment by MjHead** [comment]
From 2.3.0 you can build items for repeater the same way as Listings Items and showcase repeaterfields with Listing Grid widget
