### ISSUE TITLE
Taxonomy Tiles widget

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#599]
Currently, you can only define tiles to be shown or it will show the first ones, allow tiles to be sorted and display random tiles.

**Comment by Floydtm** [comment]
@scubaninja1977, Hi! Do you want to randomly sort products? Do you miss this option?

**Comment by Floydtm** [comment]
Like this? http://prntscr.com/pso5nd

**Comment by scubaninja1977** [comment]
Hi sorry, I mean on the Taxonomy Tiles widget, you cant show random on this

**Comment by UraraReika** [comment]
Done. Next Release.
