### ISSUE TITLE
Date Timestamp issue "U"

### ISSUE THREAD

**Issue by FrencharmeMedia** [CrocoBlock/suggestions#5993]
Hello Guys
when i make Meta Field with Timestamp i always get wrong date, one day back

If i submit a Form with a date (for example 28.09.2022) than in Backend is 2022-09-27 and in Frontend it shows 27.09.2022
What can i do to prevent this issue

Thank you
David

**Comment by MjHead** [comment]
Since 3.1.1 update added filter `jet-engine/datetime/use-wp-date` to enable saving timestamps with timezone offset added^ it should fix this problem. Usage example - `add_filter( 'jet-engine/datetime/use-wp-date', '__return_true' );`
