### ISSUE TITLE
Allow to save date as timestamp in JetEngine repeater fields

### ISSUE THREAD

**Issue by fonnfjell** [CrocoBlock/suggestions#5995]
Makes it possible to make queries to search/select and sort on dates in repeater fields.
 
Used in example, where you have the post type arrangement, and use repeater fields with several dates where the dates do not come directly after each other, like... 
2022-09-10
2022-09-11
2022-09-14
2022-10-01
2022-10-02
<img width="1230" alt="Screenshot 2022-09-30 at 10 35 46" src="https://user-images.githubusercontent.com/49978233/193230283-6404dbe0-e3dd-499e-85ec-b98b0595a87c.png">

**Comment by fonnfjell** [comment]
Also integrate this functionality with the Calendar widget.

**Comment by kaskad88** [comment]
Added in JetEngine v3.0.8
