### ISSUE TITLE
Bug with calendar display on JetAppointments

### ISSUE THREAD

**Issue by unitedonline** [CrocoBlock/suggestions#5998]
Would it be possible to fix a calendar display bug when using JetAppointments please?
The calendar days are split between the time slots.

Thank you

![image](https://user-images.githubusercontent.com/1244205/193248813-bcb1238c-3bf6-4fa2-83dc-476a702d85eb.png)

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by unitedonline** [comment]
Hello and thank you for your reply @Floydtm

I've received an answer from the support department, that this is the way the appointment plugin was designed by the developer(s) (i.e. to show the time slots between the days of the month).

IMHO it looks awkward, and I've received a couple of complaints from clients, but there's nothing I can do about it. 
Hopefully at some point in the future, it will be redesigned with custom templates and the ability to style all the fields via Elementor or even the block editor.

I thought it was a bug, but I guess not. Please feel free to close this issue.

Thank you so much again.
