### ISSUE TITLE
"Responsive" panel when using split screen.

### ISSUE THREAD

**Issue by ofmarconi** [CrocoBlock/suggestions#5999]
When I try to work with split screen, it would be interesting that this column disappears and only the commands that really matter come to the top of the panel:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/6594795/193283400-764a1c3e-6b94-4e7a-b684-ac31f0494bf3.png">

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
