### ISSUE TITLE
Repeating dates for CPT to display them within Listing Calendar (JetEngine)

### ISSUE THREAD

**Issue by Crocoblock** [Crocoblock/suggestions#60]
Repeating dates for custom post types (e.g., Events), to set when displaying with Listing Calendar widget (JetEngine) - to enable displaying event post types with the needed frequency in the Calendar.

**Comment by cloudghost1** [comment]
Just wondering if this ever got solved.

**Comment by Cosirax** [comment]
Would be really nice to have this implemented soon!

**Comment by jade7700** [comment]
Will this feature be implemented?

**Comment by breakused** [comment]
+1

**Comment by slobodandzebo** [comment]
+1

**Comment by marowi85** [comment]
+1

A feature for recurring events would be great.

**Comment by simonbouchard** [comment]
+1 

PLEASE!

**Comment by estebanip** [comment]
It would be perfect with recurring events

**Comment by Girovagante** [comment]
+1
I desperately need this feature, ideally using RRules.

**Comment by fielddaychurch** [comment]
+1

This would be incredible.

**Comment by alexplex** [comment]
I too, desperately need this feature.

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
