### ISSUE TITLE
Responsive Title Product Widget Jet Woo

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#600]
Hello, there is a need to set the adaptive font size in the product header widget for Jet Woo Builder - https://prnt.sc/pngy72

/*Оригинал*/
Здравствуйте, есть необходимость задавать адаптивный размер шрифта в виджете заголовка товаров для Jet Woo Builder - https://prnt.sc/pngy72

**Comment by Floydtm** [comment]
@stasonua0, Hi! Check out these options http://prntscr.com/pso2ry This should help you.
https://www.w3schools.com/cssref/css_units.asp
