### ISSUE TITLE
Custom template for Product grid

### ISSUE THREAD

**Issue by ivgmz** [CrocoBlock/suggestions#6000]
I think it would be a good option to add the functionality in the product grid module to attach your own template instead of the default ones, as well as in the upsell products module, but with the ability to turn them into a carousel and be able to make custom queries.

Thank you.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into the core of our plugin. Now our team is working on more priority tasks. Right now by the way you able to use custom queries in this widget. But if you want combination of all this functionalities we strongly recommend you to use Listing Grid widget from JetEngine plugin.

Thank you for your understanding.
