### ISSUE TITLE
Crocloblock JetWooBuilder bug in Endpoints Templates

### ISSUE THREAD

**Issue by ghccn394thc3fg** [CrocoBlock/suggestions#6001]
Hello, I think I noticed a big mistake in the Crocloblock jetwoo builder plugin, I believe other people have seen this too and I haven't found a solution anywhere. When editing templates for the endpoints of the My Account page, for example " orders ", the first block we see is possible to edit with the element and jetwoobuilderm, however if we go a step further and go to " view order " there is a page that does not allow customization by crocloblock, which makes no sense! You for example customize the address page with colors and fonts, however when you click "Add Address" or "Edit Billing Address" you see a form template that you cannot edit! Has anyone seen a solution to this problem?

**Comment by UraraReika** [comment]
Hello @rodrigofreitas4598! Thanks for the feedback.

For that moment you can find controls for this endpoints inside Account content widget https://tppr.me/8j4mI.
