### ISSUE TITLE
Add Relation Meta Data into Elementor Dynamic Tag

### ISSUE THREAD

**Issue by FrencharmeMedia** [CrocoBlock/suggestions#6003]
Could you please add the Relation Meta Data into the Elementor Dynamic Tag?
Would be usefull for some Styling Stuff like dynamic Color and so on.
Also the Ability to Edit/Update Relation Meta Data with Form
Thank you
Best Greetz
David

**Comment by MjHead** [comment]
also added Macros with the same functionality
