### ISSUE TITLE
JetBooking - Booking List to Frontend

### ISSUE THREAD

**Issue by bodibel** [CrocoBlock/suggestions#6009]
Hi

I would like to show my clients the bookings of the products they offer on their Profile page. Is this possible?

Eg: One of my clients has 3 cars and I would like to be able to display for each car which one has been booked and for when. I would like to get this from JetBooking and display it in a list as well as in a calendar. Also, I would like to set a separate color for owners when they indicate in the calendar that the auto was booked by them.

**Comment by Qubadi** [comment]
1+
