### ISSUE TITLE
smarts filters in backoffice

### ISSUE THREAD

**Issue by xavigarciagomez** [Crocoblock/suggestions#601]
Could be a good idea can apply filters in backoffice, with your plugin jet engine i have created a custom taxonomy for woocommerce products which is very usefull and i have created a column in the backoffice all products with name brand and i can see all asociations, but i cant order it by brand and could optimize a lot have filters for select only one brand for editing only its products.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
