### ISSUE TITLE
compatibility of jet compare & wishlist plugin with bricks builder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6011]
**Please, describe the feature request, making it clear to understand.**

Please, if possible, make the jet compare... plugin compatible with Bricks Builder page builder.

thank you

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. We highly recommend to use JetEngine data store in this case.

Thank you for your understanding.

**Comment by 79ho3ein** [comment]
thank you @UraraReika, But I have two questions about it.

1- Can we display a counter for data stor like [this](https://prnt.sc/MaHNUQ4j31PI)?

2- Also, is it possible to compare WooCommerce products using data store?
