### ISSUE TITLE
Injections in Repeater Listing Grid not working when condition is based on value inside Repeater

### ISSUE THREAD

**Issue by voneff** [CrocoBlock/suggestions#6014]
**Describe the bug**
I was trying to use Listing Grid Injections for a repeater field group listing on a single page of a Custom Post Type (CPT) to change the style of listing items based on a selection in a radio field **inside** the repeater field group. When I use other options like "On each N item", the injections work. I also tried other fields, like basic text fields, but it seems to me that the value inside the repeater meta fields is not getting picked up. 

My issue seems quite similar to this closed issue from last year, but is not referring to CCTs: [#2682](https://github.com/Crocoblock/suggestions/issues/2682)

**To Reproduce**

1. Create a CPT and add a Repeater field group. Inside that repeater field group, add a Radio field with three options and various other content fields.
2. Create three listings that make use of different fields from that repeater fields group mentioned above.
3. Add a listing grid that queries the Repeater field and check "Inject Listing Grid". Add injections with the "Depends on item meta field value" option.
4. Set respective keys, set operator to "Equal" and add the corresponding option values.

**Expected behavior**
I expected to see different listing items, according to the selection I made when adding the repeaters in the custom post type edit screen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - JetEngine, Elementor, WP: all current

**Comment by gualtier** [comment]
+1, same case.

**Comment by Crocoblock** [comment]
Released in JetEngine 3.5.6
