### ISSUE TITLE
Custom database table for CPT/Metabox

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#6015]
Hi guys @Floydtm 
**Custom database tables for cpt and meta fields**

**1- Custom database for CPT**
It would be so optimized if we have separate database table for each cpt we creat. 

**2- Custom database for meta fields**
Metabox/Pods/Acf plugins have a great feature to save a group of fields to a separate custom table, that's improving the performance strongly.
The positive point of this solution is that we can add a group of fields (with a custom database table) to existing post types like Users!

**Solution:** 
It should be implemented in CPT and Metabox features of JetEngine; add an option like this: "register in a separate database table"

Note: ability to convert current way of saving meta fields (each meta fields in a row) to new one (each meta field in a column)
Note: CCT has so many limitations
![metabox1](https://user-images.githubusercontent.com/86493591/194891162-cb68b64d-8695-4af9-a1cd-a19640cb4708.jpg)

![Screenshot_20221004-025923_YouTube](https://user-images.githubusercontent.com/86493591/193704426-7782181b-7b77-41e2-a7a4-c56c6fc5ef8c.jpg)

Note: metabox plugin is able to move the old way of saving meta fields to custom database tables, link attached
https://youtu.be/JaEvtYa4Hcg

**Comment by fostira** [comment]
+1

**Comment by 79ho3ein** [comment]
+1
This is really needed.

**Comment by Joliamendi** [comment]
+1

**Comment by Michaelgimii** [comment]
+1
Now, if the amount of posts in post type is high, we will definitely face speed problem. So crocoblock please

**Comment by saeed-1987** [comment]
Its totally necessary!
I have to use few plugins (acf pro and cpt ui) to achieve it but hope to see it soon in JetEngine
Great request

**Comment by satomiao** [comment]
+1

**Comment by yannicklmb** [comment]
+1. It is a very good proposal. But I also think they could make the queries compatible with JetEngine's own CCTs. After all, they are improving the compatibility between Crocoblock and Bricks every day.

**Comment by Nima786** [comment]
Honestly, this should've been done a long time ago. I believe implementing this, will affect the query speed significantly, specially for larger sites with tons of custom meta fields. Hope, we'll see it sooner rather than later...

**Comment by LevelUpGit** [comment]
+1
[4914](https://github.com/Crocoblock/suggestions/issues/4914)

**Comment by mehdimoradi1500** [comment]
Hi @LevelUpGit
I think if we could set custom DB table for cpt and Metabox, would be much more powerful instead of expanding the abilities of CCT (cct has its own usage) 

Assume that you want to use The standard POSTS or USERS of WordPress! And you need to add 10 custom fields to them! In this case you have to use Meta box of JetEngine and using custom DB table will be so powerful. Because you have so much control and you are not worry about the speed of Query

In other case, when we need to add a CPT, it will be so powerful to set a custom DB table! So all fields including title, featured image and content will be save in a custom table!

**Comment by Nasimart** [comment]
+1
I added a cpt few months ago with almost 10 custom fields. After few months i knew about custom database table and like how acf handle it. 

I wish it will be possible to convert it to new database table and it would definitely increase the speed

Im sure crocoblock will handle it even better

**Comment by LevelUpGit** [comment]
> Hi @LevelUpGit I think if we could set custom DB table for cpt and Metabox, would be much more powerful instead of expanding the abilities of CCT (cct has its own usage)
> 
> Assume that you want to use The standard POSTS or USERS of WordPress! And you need to add 10 custom fields to them! In this case you have to use Meta box of JetEngine and using custom DB table will be so powerful. Because you have so much control and you are not worry about the speed of Query
> 
> In other case, when we need to add a CPT, it will be so powerful to set a custom DB table! So all fields including title, featured image and content will be save in a custom table!

Totally agree, it is much needed, for example we have custom post type with 50 meta fields, and right now we have 100,000 records in DB, it' functioning but it would be much better to have them in separate table. We considered to rebuild it with pods or something similar with this option.

Hope this get's traction.

**Comment by Mrgreen93** [comment]
+1
I have the same issue, i have a multi vendor website with so many sellers! 
I used metabox of JetEngine to add 15 custom fields to users of wp.
I wish they implement custom db table soon for these two features: cpt and meta box

I don't like to switch to acf or other plugins

**Comment by jornessim** [comment]
+1 
It's essential and will be helpful to have custom database tables.

**Comment by monolithMktg** [comment]
+1
Needed by devs

**Comment by ghost** [comment]
This will be great feature.

**Comment by ofmarconi** [comment]
+1!

**Comment by SanyaOnline** [comment]
+1

**Comment by JuanCar29** [comment]
It would be great

**Comment by oceandiveloper** [comment]
+1 I'm often torn between the choice of having slow CPT queries with all the benefits of CPTs on the one side and fast CCT queries thanks to separate DB tables without the benefits of CPTs (e.g. taxonomies, ACF support) on the other side. 
If we could have a new option to combine the benefits of both methods, meaning using CPT with taxonomies and ACF support while storing meta fields in a custom DB table, this would be awesome!!!

**Comment by Mrgreen93** [comment]
Hi @oceandiveloper Thank you
That's why i exactly asked for! I always get headache between choosing CPT or CCT!
But with this solution there will be no confusion and headaches any more
CCT should be used for its own use cases
And CPT should be improved with this solution, I hope

**Comment by graeme-farhomes** [comment]
+1

**Comment by Michaelgimii** [comment]
Hi @MjHead , Any news on this feature?

**Comment by Mrgreen93** [comment]
@MjHead is there any plan for this feature, i need to know the Timeline for future projects

**Comment by morosmo** [comment]
+1

**Comment by Lucky5111** [comment]
+1 really needed.

**Comment by MjHead** [comment]
At the moment the work on this feature not yet started. If nothing will change in our roadmap, it planned for late summer or start of autumn

**Comment by Mrgreen93** [comment]
> it planned for late summer or start of autumn

Thank you, plz implement a convert key for those who want to save their cpt to custom database table 🙏

**Comment by amirulsyafiqrosly** [comment]
Most needed feature! +1000

**Comment by ziv770** [comment]
YES!!! We need this feature very much, it will improve the performance of sites that use many CPT posts

**Comment by ofmarconi** [comment]
@MjHead could you update the status for us? Thank you, this is a long awaited feature.

**Comment by sekhsoyebali** [comment]
+1

**Comment by MechelAbdo** [comment]
+1000

**Comment by CMRD77** [comment]
+1

**Comment by mehdimoradi1500** [comment]
@MjHead as autumn has come, and so many users asked for this, is there any news? Plz update the status

**Comment by 79ho3ein** [comment]
It is very important to be able to have a dedicated database table for cpt and cpt meta. I hope the crocoblock team will introduce this feature soon. With the release of this feature, we will no longer worry about performance on websites with a lot of content.

**Comment by MechelAbdo** [comment]
i'd been told that this feature will be available in 3.4.0 in autumn. but i see now is 3.3.0  in beta.
i stop working on my website till this feature is available.

**Comment by usmanlatif** [comment]
+1

**Comment by lcrvtt** [comment]
+1. 
Additionally, the current lack of support for CCT dynamic data in Bricks further limits CCT's usability.

**Comment by whyohssab** [comment]
+1

**Comment by lcrvtt** [comment]
@MjHead my license is due for renewal soon, and I would appreciate some insight into whether planning for this renewal is included in your roadmap. This feature is crucial for me (and I'm sure for others too); therefore, if it is not part of your plans, I may have to consider switching to a competitor that allows for custom tables. Thank you for your response.

**Comment by MjHead** [comment]
added in 3.5.0 update
