### ISSUE TITLE
Zooming Issue JetProductGallery

### ISSUE THREAD

**Issue by spoonboy90** [Crocoblock/suggestions#602]
The main product image (1st image) doesn't zoom fully but the subsequent images do.

I have all full images 1500x1500px but the first image is only zooming to a 600x600px image the rest zoom to full

See video for demo of problem - [YouTubeVideo](https://www.youtube.com/watch?v=b_y0Tz2kSoo&feature=youtu.be)

Problem has been raised with you support 

> Thank you for paying attention to this case. The issue should be fixed globally. Please describe this case at Git repository so that our team adds this case to our backlog https://github.com/CrocoBlock/suggestions/issues?fbclid=IwAR0MBzsfuJA1WKM97SEP7jW1WhsiI6faWVG5hWm-BYInkJ3Tf1mFmFROVKI 

Kind regards, Maryna
Crocoblock support team

**Comment by Floydtm** [comment]
@spoonboy90, Hi! Change the width of the picture in the settings of the customizer http://prntscr.com/psp9fs you need to set the width more
