### ISSUE TITLE
JetProductGallery - Link Video Instagram

### ISSUE THREAD

**Issue by rogeriolixa** [CrocoBlock/suggestions#6021]
Hi Croco!
I would like to know if it would be possible to add Instagram/Facebook link and maybe even TikTok on JetProductGallery in the "video" part today only has external options for Vimeo and Youtube.

I believe that adding this option would make it much more dynamic to create pages and sites incorporating social media that year after year are taking up space from online stores and information sites.
I believe that having this option would be more interesting for a client to continue investing with a home site with integration with the main social networks.

**Comment by UraraReika** [comment]
Unfortunately we do not plan to introduce such functionality into our plugin. In this stage this social media don't give us a tool to extract and handle video the way our widget need. But in the future we do not exclude the possibility of adding this functionality.
