### ISSUE TITLE
JetTabs / JetEngine

### ISSUE THREAD

**Issue by sigersmit** [Crocoblock/suggestions#603]
It would be great if the repeaterfield from JetEngine generates tabs in JetTabs. I can set dynamic values, but if the value for one repeater field is empty, the tab will still show up, but no content. 

Say for a product I have specs like Size, Material, Documentation etc. Some products do have documentation, some don't. When they don't it would be nice if the tab Documents is not visible. Maybe by setting "hide if empty" or automagically :-)

**Comment by tippexs** [comment]
Hi. Any news on that? I have the exact same problem. Is there any code reference arround how to do it with elementor hooks for example?

**Comment by kaskad88** [comment]
Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )
