### ISSUE TITLE
Create JetEvent - the one stop event solution!

### ISSUE THREAD

**Issue by iamalsoandy** [CrocoBlock/suggestions#6030]
It would be great to have an Event plugin (not a small ask, I know!)

Similar in theory to JetBooking and JetAppointment, but with more of an event focus - with the ability to book tickets and so on.

Kind of like [Eventbrite](https://www.eventbrite.co.uk/) or [WP Event Manager](https://wp-eventmanager.com/), but with the lovely JetEngine take on it. Features in there that would be useful:

- Event date / time. 
- Single day event
- Multi day event
- Recurring event
- Ticket types / tiers (different price points etc)
- Ticket confirmations
- Event organiser
- Event location
- Link to payment

Yeah - I'm aware it's no small thing! But it would be awesome...

**Comment by dshamsession** [comment]
Yes this would be amazing!

Do you create reservation-tools and event-booking so fare with the jetbooking plugin? If yes, I would love to see...

**Comment by m-dejong** [comment]
This is needed very much.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1688, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
