### ISSUE TITLE
jet smart filters new UI bugs

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6034]
**Describe the bug**

Hi @Floydtm , The new UI version of jet smart filters plugin has serious problems in ui and ux. If possible, please check the following. I hope it will be useful in improving it.

1- In RTL, the filters page is completely broken : https://prnt.sc/4kUsb--7xXwE 
BUT in LTR : https://prnt.sc/yBMgC5eeifuk

2- In the visual filter, there is a serious problem. In the new version, colors are displayed in [one column](https://prnt.sc/GuD_na3gjh7R). **The main problem here is that if we have a lot of colors here, if we want to add a new color we have to go to the end and it takes a lot of time to scroll.**
So, I had two suggestions to solve this problem...

A : I think one column for each color is too much. Because each color item is a [large part of it without use](https://prnt.sc/6ytT9U-u8JWN). Because we will only have the name and color code in each item. Not a paragraph. So it is much better if the color items are displayed in 3 columns. See this ui : https://prnt.sc/tyIo18u2ky_v

B : Now, if we want to add a new color, we have to go to the bottom of the list and click on the Add New button. So if we have many colors, scrolling to the end of the list can be time consuming. **I think it is much better if you put the add new button at the beginning.** https://prnt.sc/JMqtIfosH461
In this case, any new colors we add will be displayed at the top and the colors at the bottom of the list will be the old colors.

3- In the new version, the Filter Labels section has been moved to the bottom of the page. In the visual filter, it will be difficult to access this section due to the fact that the page scroll will be long. (Of course, this problem will be solved by improving the two items mentioned above) But it would be great if, like WooCommerce, you added the ability to move using drag and drop for the Filter Labels section. I prefer this section (Filter Labels) to be at the top of the page. Like the old ui.

4- On RTL, the settings button is stuck to the other side. https://prnt.sc/y0Sm7D9pRzU1
but in LTR : https://prnt.sc/bvej6hpMxbs0 **(its OK)**

5- Again in RTL, the content of the page is stuck to the left and there is a lot of space on the right.
in RTL : https://prnt.sc/2vflnkKTkukH
but in LTR : https://prnt.sc/UmLBMi51uxia **(its OK)**

6- Space between Sort by and clear filters button in RTL.
in RTL : https://prnt.sc/LMBZyguWnsEP
but in LTR : https://prnt.sc/8ZqyrM3305pY **(its OK)**

7- List arrows are attached to text in RTL.
in RTL : https://prnt.sc/KKYPWSexVGyi
in LTR : https://prnt.sc/O_Fv0SjnHyAj

The speed has been greatly improved in the new version. By fixing these things, everything will be perfect. 

Thank you for your attention

**Comment by 79ho3ein** [comment]
Another example in RTL : https://prnt.sc/D-WZxW5eWthe

In general, in the new ui, almost all parts of it in RTL are in trouble.

**Comment by SargasTM** [comment]
1, 4, 5, 6, 7. RTL - done
2. A. - done
2. B. - does not make sense because the new element will be added at the end anyway
3. The Filter Labels section is rarely used by users, so it was decided to move it to the end
To quickly jump to the end of the page, you can use the "END" button on the keyboard.

The update will be available in version 3.0.1

**Comment by 79ho3ein** [comment]
thank you @SargasTM

**Comment by 79ho3ein** [comment]
Hi again @SargasTM , Thanks for the great update.

There is a relatively old bug in filters that occurs in RTL. I have already described it fully **[here](https://github.com/Crocoblock/suggestions/issues/5570)**. Please take a look if you can. This bug severely affects the UI in the frontend.

thank you
