### ISSUE TITLE
Add Post Author Role to Dynamic Visibility Options

### ISSUE THREAD

**Issue by stapolin** [CrocoBlock/suggestions#6035]
There are many options to choose from when using the Dynamic Visibility feature, but recently when creating a directory website I discovered the need to set the visibility of some elements within the design so they only show depending on the Post Author's Role. 

For example, 

There are 2 roles (Supplier & Supplier Plus)

When a member upgrades to Supplier Plus, they get extra features like having a video banner in the header of their listing, or the ability to include more photos in their listing and add their phone number etc..

On the front end post design I have 2 banner designs, one to be shown to visitors if the Post Author is on the Supplier plan (User Role: supplier), and another to show if the Post Author is on the Supplier Plus plan (User Role: supplier_plus).

**Comment by Floydtm** [comment]
It's available right now https://prnt.sc/S18IkAELfP7p

**Comment by stapolin** [comment]
> It's available right now https://prnt.sc/S18IkAELfP7p

No, What I mean is the Author's role, not the current visitor role (user role).

I figured it out, though, using User Meta

![screenshot-wedding stapolin ie-2022 10 11-19_47_06](https://user-images.githubusercontent.com/17647985/195174543-3b1915a1-a8da-434b-9b7a-599d6a93ae7d.png)
