### ISSUE TITLE
Jet Poup 1.6.0 breaks form made with jetformbuilder when inside it. I have to roll back to Jet Popup 1.5.5

### ISSUE THREAD

**Issue by alfredo49** [CrocoBlock/suggestions#6037]
**Describe the bug**
Jet Poup 1.6.0 breaks form made with jetformbuilder when inside it, roll back to Jet Popup 1.5.5 and all works ok

**To Reproduce**
Create a popup, put inside it a jet form builder.
Then form styles are broken (header, stepts, field etc etc)

**Screenshots**
![screen1](https://user-images.githubusercontent.com/16021586/194865182-763b4a60-0747-47f1-b188-580fa916778c.jpg)

**Comment by Floydtm** [comment]
Fixed in updated 1.6.1 Let me know if this helped you

**Comment by alfredo49** [comment]
Yes, in my case issue is solved.

Thxs
