### ISSUE TITLE
To be able to separate upsell and related products templates

### ISSUE THREAD

**Issue by isaacwillz** [CrocoBlock/suggestions#6039]
Hello, 

Is it possible to separate upsell and related product templates? Basically to be able to apply different templates to both of them not same

Best regards

**Comment by UraraReika** [comment]
Hello @isaacwillz. Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into the core of our plugin. But you can use on of the hooks to handle this. Like this 

```
add_filter( 'jet-woo-builder/final-custom-archive-template', function ( $template ) {

	if ( 'up-sells' === wc_get_loop_prop( 'name' ) ) {
		$template = 14199;
	}

	return $template;

} );
```

Here you manually rewrite template for up-sells products where 14199 is the id of Archive Item template.
