### ISSUE TITLE
auto alt for product image in product grid widget - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6058]
**Please, describe the feature request, making it clear to understand.**

Hi

It would be great if you could add a new option to the jet woobuilder widgets (product grid/list & categories grid), so that the alt will get the product images automatically from the product title. This will be great for SEO.

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein !

Unfortunately, we do not plan to introduce such functionality into our plugin. but with next version of our plugin you will be able to rewrite template in witch you can modify thumbnail output function.

For example:

This template `wp-content/plugins/jet-woo-builder/templates/widgets/global/products-grid/item-thumb.php`
like this
```
$thumb_args = [
	'alt' => wp_strip_all_tags( get_the_title( $product_id ) ),
];

$thumbnail    = jet_woo_builder_template_functions()->get_product_thumbnail( $size, $thumb_effect, $thumb_args );
```

Like that $thumb_args = [
	'alt' => wp_strip_all_tags( get_the_title( $product_id ) ),
];

$thumbnail   = jet_woo_builder_template_functions()->get_product_thumbnail( $size, $thumb_effect, $thumb_args );

**Comment by 79ho3ein** [comment]
thank you @UraraReika

**Comment by Michaelgimii** [comment]
Hi @UraraReika , I had a question about the jet woobuilder plugin if possible...

Will jet woobuilder update be slow from now on? Previously, major updates were released for it almost every 1 month, but it has been very slow for almost 4 months. thanks

**Comment by UraraReika** [comment]
> Hi @UraraReika , I had a question about the jet woobuilder plugin if possible...
> 
> Will jet woobuilder update be slow from now on? Previously, major updates were released for it almost every 1 month, but it has been very slow for almost 4 months. thanks

We are currently working beyond our capacity, the situation is very difficult and it is difficult to release large and high-quality updates with the same frequency as before. We make every effort to support our product. But don't worry, everything will be fine.

**Comment by 79ho3ein** [comment]
> Hi @UraraReika , I had a question about the jet woobuilder plugin if possible...
> 
> Will jet woobuilder update be slow from now on? Previously, major updates were released for it almost every 1 month, but it has been very slow for almost 4 months. thanks

Do you know that Ukraine has been at war for several months? In fact, they have been attacked...

**Comment by Michaelgimii** [comment]
> We are currently working beyond our capacity, the situation is very difficult and it is difficult to release large and high-quality updates with the same frequency as before. We make every effort to support our product. But don't worry, everything will be fine.

yes.

**Comment by 79ho3ein** [comment]
> > We are currently working beyond our capacity, the situation is very difficult and it is difficult to release large and high-quality updates with the same frequency as before. We make every effort to support our product. But don't worry, everything will be fine.
> 
> yes.

So please don't expect everything to go as before.
