### ISSUE TITLE
listing sort date ASC /  DESC > countdown timer 

### ISSUE THREAD

**Issue by ppskmg** [Crocoblock/suggestions#606]
Баг при сортировке по кастовому полю даты с виджетом таймера. 
при выводе постов категории с использованием листинга. 

В листинге используется виджет таймера в качестве даты указано кастомные поле.

баг при сортировке по дате

https://yadi.sk/d/9RZo8MTBjBj9Lg

**Comment by WildHund** [comment]
Could you please describe the request in English so that it can be accepted and processed by our team?

**Comment by Floydtm** [comment]
@ppskmg, Hi! In the meta field settings you use the save as timestamp option. Try changing the metadata type to date http://prntscr.com/psbo4o http://prntscr.com/psbod7
