### ISSUE TITLE
Possibility to export/import option pages as json files (jetengine plugin)

### ISSUE THREAD

**Issue by peterhrnciar** [Crocoblock/suggestions#607]
It would be great to add possiblity to export/import option pages as json files in JetEninge plugin. For now you have possibility to export/import custom post types and taxanomies. Why not to have also Option pages?

**Comment by serg-pervushin** [comment]
+1

**Comment by ciprianpentelescu** [comment]
Export / Import Option pages is a must. Especially when you have a complex structure. Please add this option to Jet Engine.

**Comment by kaskad88** [comment]
@ciprianpentelescu This feature has been available for a long time https://prnt.sc/26vg8mi.
