### ISSUE TITLE
JetPopup ajax loading sys

### ISSUE THREAD

**Issue by shinTM** [CrocoBlock/suggestions#6073]
wp_script_is() | Function | WordPress Developer Resources
Determines whether a script has been added to the queue.

1. Первая загрузка происходит как обычно, тем хитрожопым способом как ты сразу сказал, при этом на аякс загрузку ловятся все ассеты, которые должны подключиться и кешатся. Словить их можно через вызов ВП-шного хука для принта скриптов. Есть риск что так не поймает скрипты, которые должны грузиться в хедере, но такие по идее итак подключатся сами по себе. Ловить их нужно сразу с названием и строкой для подключения. 

Потом при следующей загрузке, перед тем как парсить контент попапа ты проверишь, есть ли в кеше какие-то данные, если есть, то все, можно не парсить а подключать из кеша. Подключаешь их в самый последний момент, прям перед принтом. и перед подклчением, проверять по названию подключен ли уже такой ассет (двойная проверка нужна - подключен ли самим ВП через https://developer.wordpress.org/reference/functions/wp_script_is/ и наша проверка про нашу проверку чуть позже). Если не подключен, подключать и  обязатьльно добавлять в стек наших подключенных скриптов, чтоб несколько попапов не подключили один и тот же скрипт. Это наша проверка, про которую перед этим было. 

При запросе контента ты проверяешь, если кеш есть, то процедуру обновления кеша повторять не нужно, только отдать контент

Ну и кеш просто сбрасывать при любом сохраненнии попапа, чтоб следующая загрузка на фронте обновила его.

Так у тебя будет одна херовая загрузка и все остальные нормальные и ты поймаешь все ассеты, которые собирался подклчить попап

Схему с депендсами Элементора можешь оставить и собирать их из 2х источников - Элементор + то что сам наловил, там все равно по хендлам они храниться будут

Воможно схему с ассетами элементора нужно будет применять на фронте при 1й загрузке, а сам ловить будешь на аякс запрос, чтоб наверняка все поймать

2. Поймать ассеты при отрисовке попапа и всунуть в ответ или передать в ЖС чтоб всунуть в тело страницы. Но тут большой риск что не сработают инициализации каких-то скриптов т.к. не будет нужных ивентов. Но хотя эта проблема наверное и для 2го способа есть

**Comment by ofmarconi** [comment]
news?
