### ISSUE TITLE
JetSmartFilters | Automatic indexing for glossaries

### ISSUE THREAD

**Issue by LTimerr** [CrocoBlock/suggestions#6078]
Hello, I would bring to JetSmartFilters the extension that glossaries are also automatically indexed and, that when you create an ad, it is immediately displayed in the filters.

So I have the problem that every time a new ad is created, I have to re-index the filters, which is quite inefficient for me.

I hope this can be implemented.

Thanks for reading

![Screenshot_5](https://user-images.githubusercontent.com/93724776/196721359-bbd7f8e9-94ba-40ee-99a4-05d53d1119cc.png)

**Comment by mateitudor** [comment]
Smart Filters desperately needs an update for so many issues :(
