### ISSUE TITLE
Problem with Parent / Child option for Option pages - result 404 page - JetEngine plugin

### ISSUE THREAD

**Issue by peterhrnciar** [Crocoblock/suggestions#608]
**Describe the bug**
If you add parent page for option page and then click on that page in Wordpress menu, there is problem with redirect to 404 page. Page is not showing because of wrong url adress.

**To Reproduce**
1. Go to 'JetEngine options pages'
2. Click on 'Create new, set parent page, save it'.
3. Then test it in Wordpress menu under the parent page you choose
4. After clicking on it you see 404 page.

**Comment by kaskad88** [comment]
Hi, @peterhrnciar

We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support at support https://crocoblock.com/help-center/ for guidance in resolving this issue.

Thanks.
