### ISSUE TITLE
Two requests for the add to cart button for the product grid widget - jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6083]
**Please, describe the feature request, making it clear to understand.**

Hi, Please check these items if possible to improve the product grid widget.

1- Possibility to edit the text of the **[read more button](https://prnt.sc/VSdudRuJ-MS7)**. (As you know, if we activate the Add To Cart Button feature in the product grid, this button (read more) will be displayed if the product is variable)

2- "Hide in variable products" option for Add To Cart Button option - Using this feature, if we activate the Add To Cart Button option, another option will be displayed (Hide in variable products). If we enable this option, the Add To Cart Button will be hidden for variable products. This will be very effective in ui design.

thank you!

**Comment by UraraReika** [comment]
Hello @79ho3ein! Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. But you can use hooks solutions:

1 - New label for Read more button
```
add_filter( 'woocommerce_product_add_to_cart_text', function( $text, $_product ) {

	if ( $_product->is_purchasable() && ! $_product->is_in_stock() ) {
		$text = 'Your label here';
	}


	return $text;
}, 10, 2 );
```

2 - For hiding variable product button
```
add_filter( 'woocommerce_loop_add_to_cart_link', function( $link, $_product ) {
	if ( 'variable' === $_product->get_type() ) {
		$link = '';
	}

	return $link;
}, 10, 2 );
```

Thank you for your understanding.

**Comment by 79ho3ein** [comment]
thank you @UraraReika
