### ISSUE TITLE
JetBlocks plugin without requiring Elementor

### ISSUE THREAD

**Issue by unitedonline** [CrocoBlock/suggestions#6084]
I would like to kindly request for your development team to look into making the JetBlocks plugin independent of Elementor, (or perhaps develop a separate plugin) so it may be used on Bricks builder and Gutenberg as a stand alone plugin.
The main reason is that I would like to use the Password Reset functionality.

Thank you

**Comment by MjHead** [comment]
Password reset funcitonality planned as JetFromBuilder addon in a next few months so you'll can use it with different builders
