### ISSUE TITLE
VERY IMPORTANT - REMOVE MEDIA WHEN CLICK IN TRASH

### ISSUE THREAD

**Issue by oncps** [CrocoBlock/suggestions#6088]
HELLO PEOPLE.
HAVE YOU NOTICED THAT, WHEN A USER CREATES A POST THROUGH THE FORM (JETFORMBUILDER), AND HE HAS THE OPTION TO ADD FEATURED PHOTO AND PHOTO IN THE GALLERY, AND IF AT ANY MOMENT HE NEED TO "CHANGE" THE PHOTO, JUST CLICK ON THE GARBAGE (DO FORM, AND CHANGE THE PHOTO FOR THE SAME FORM, CORRECT?

OK, BUT HAVE YOU NOTICED THAT INSIDE WORDPRESS, THE PHOTO HE REMOVED FROM THE FORM IS STILL THERE?

PLEASE NEED TO CREATE A NATIVE FUNCTION OF JET ENGINE AND/OR JETFORMBUILDER, WHICH, WHEN THE USER CHANGES THE PHOTO, THE PHOTO THAT THE USER REMOVES THROUGH THE FORM, MUST ALSO BE REMOVED FROM WORDPRESS, SO WE DON'T HAVE SO MANY IMAGES INSIDE OUR WORDPRESS! !!
YOU NEED TO CREATE A FUNCTION TO REMOVE PHOTOS FROM BOTH THE GALLERY AND THE HIGHLIGHT PICTURE WHEN THE USER CLICKS THE TRASH TRASH ON THE JETFORMBUILDER FORM

**Comment by MjHead** [comment]
Added into the internal backlog with proper description. Will be implemented with on of 3.x branch updates
