### ISSUE TITLE
CROCOBLOCK VERY IMPORTANT, LOOK THIS

### ISSUE THREAD

**Issue by oncps** [CrocoBlock/suggestions#6089]
WATCH THE VIDEO BELOW!!!

Hello how are you ?
The crocoblock needs to create a function, for form (JetFormBuilder),
example:
if the User fills in a Hidden Type field, but he unintentionally fills the field, but decides to choose another item from the select field, note in the video below, that the form keeps what was typed in that hidden field.

See in the video that in the select field, I selected YOUTUBE first...
A field appeared for me to Add the URL, I wrote a Any URL, (just for testing), however, for some reason, I didn't want the YOUTUBE option anymore, so I selected "INSTAGRAM", and continued filling the form normally..
but did you see that the YOUTUBE field, which I had filled in, and then it was hidden, it remained filled and was inserted in the Post Type?

need to create a function that erases data from fields that are hidden and filled.

WATCH THE VIDEO BELOW!!!

https://user-images.githubusercontent.com/61298091/197196192-5046f355-0575-4bca-95d6-b84b856ea109.mp4

**Comment by MjHead** [comment]
Similar functionality planned for the JetFormBuilder 3.0.0 update. At the moment this update on the testing stage
