### ISSUE TITLE
Query Builder: Post not in doesn't work when Post in is filled

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#6090]
**Describe the bug**

When Query Builder - Post & Page - Post in has a value, then it ignores whatever is in the "Post not in" setting.

**To Reproduce**
1. Create a query
2. Fill query with correct post types etc.
3. Add a collection of value to Query Builder "Post & Page" tab "Post in" value (for example, a relationship)
4. Add a post or collection of posts to exclude to the "Post not in" field
5. Query still shows the excluded posts.
 
**Expected behavior**
If I have a collection of posts [A, B, C, D], which I add to Post in, then all four posts will be shown; this is as expected.

But if I then add the id for post C to the "Post not in" field, I'd expect the query to return: [A, B, D]. 

Instead it returns the same [A, B, C, D], completely ignoring the posts specified in "Post not in".

**Screenshots**
![PostNotInError](https://user-images.githubusercontent.com/8066290/197205008-579e892d-c04b-46e2-8917-7d00c29953ef.png)

**Desktop (please complete the following information):**
- JetEngine version: 3.0.5
- Elementor version: 3.7.8
- Wordpress version: 6.0.3
- OS: Windows 10 Pro v 21H2
- Browser: Firefox v105.0.3 (64-bit)

**Comment by MjHead** [comment]
Posts query uses default WP_Query to get posts from the DB. According to WP_Query documentation you can't combine these parameters in the same query - https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters, https://i.imgur.com/T23R6br.png
