### ISSUE TITLE
JetWoobuilder: archive linking

### ISSUE THREAD

**Issue by JPITH** [CrocoBlock/suggestions#6091]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

So i ask someting when creating a archive item have the possibility to add the link of the archive directly on a woobuilder module or on all the section

**Add an example of where this feature is already implemented. **

so that when i click on the archive price it's redirect me to the product or even the stars

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.

**Comment by UraraReika** [comment]
This feature was added in 2.1.0 version of the plugin - https://tppr.me/DmOZ1.
