### ISSUE TITLE
standardize Dynamic visibility for all

### ISSUE THREAD

**Issue by oncps** [CrocoBlock/suggestions#6092]
please need to standardize dynamic conditions, ✅ in query builder ✅ listing grid ✅ dynamic visibility. for example, in the advanced tab of the element, when we select the "dynamic visibility" option, there is no option "greater than or equal" or "less than or equal", only the option "greater than" or "less than".. but there in the listing grid in posts query, there is the option "greater than or equal" and "less than or equal... and there is not even in the query builder... and also these dynamic conditions could be made just like jetformbuilder, there in jetformbuilder, we can choose several options to hide or show, for the same field.. notice that in dynamic visibility we can only choose a condition to show or hide for each item... please standardize this!!!!

**Comment by edson-webeddy** [comment]
Hey,
This question is very important in logical comparators, if there is less or equal <= and greater or equal => in the query builder. It should have these two conditions for users who are not so familiar with the logical operators to apply in dynamic visibility.
Or you use 2 logical operators to get this result.
 (>) and (equal).

**Comment by ofmarconi** [comment]
+1

**Comment by pool586** [comment]
+1 very useful.

**Comment by oncps** [comment]
@MjHead Wasn't this added in the new version of JetEngine? See that in the listing Grid has this option... but in the advanced tab of any widget, you do not have this option "Greater or Equal" or "less or equal"... Please standardize this by adding in the ADVANCED tab, and put this also in "Query Builder" when we create a dynamic condition... there also does not have...  See image below.

My Version JetEngine 3.0.6.1.

thanks
![a01](https://user-images.githubusercontent.com/61298091/202180447-5535f876-a3bc-4273-b047-011f7f1ef774.png)

**Comment by kaskad88** [comment]
@oncps New conditions ( Greater or Equal, Less or Equal and other ) in Dynamic Visibility will be available in JetEngine v3.0.7
