### ISSUE TITLE
Multivendor-marketplace

### ISSUE THREAD

**Issue by Disenowebclub** [CrocoBlock/suggestions#6094]
Neither we nor support have found a feature for the seller to manage, create or modify WooCommerce orders from the front-end. We believe this is a fatal bug for the service offered by Crocoblock "multivendor-marketplace". There is no use being able to create products on the front-end if you cannot manage sales.

We look forward to prompt news on this matter.

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by MjHead** [comment]
Closed because no client feedback provided
