### ISSUE TITLE
jetengine query builder - wc products query built before `product_type_selector`, impacting product type queries

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#6099]
**Summary**
Are you hardcoding the types of woocommerce products that are being searched to the built in product types, maybe?

Because my queries don't work for WC product types that are made from WooCommerce addons, eg `booking` and `accommodation-booking`, unless the `product type` of the query is explicitly set.

**Describe the bug**
I have WooCommerce Bookings installed on top of WooCommerce.

I've created a query in the query builder, and restricted it to the category "safari":

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/1038062/197545890-79506a5a-8f40-465c-b86a-e4ac281fd204.png">

It gives zero results, but there are 24 products in that category.

They are all `booking` type products, which is a woocommerce product type, but it is added in by a the WooCommerce Bookings plugin.

It says on the UI that this field is optional:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1038062/197546133-65d7d512-2817-4a7b-8943-1aefcf16bf53.png">

However, unless I select 'booking' I get zero results.

Left blank, 0 results:

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/1038062/197546273-b705a94c-397d-4558-8c74-b046fb6f680a.png">

With 'booking' selected, 24 results:

<img width="1566" alt="image" src="https://user-images.githubusercontent.com/1038062/197546668-44a16974-51df-406b-ba36-294836a31395.png">

The only other settings I've adjusted in this query are the order in general:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/1038062/197546930-684472ba-3933-4cdc-a9c5-11b45e14834d.png">

Btw the safari category doesn't really seem to affect this, as such, but I wanted to show that zero `booking` results are being returned by a product query that doesn't specify type, and otherwise the products from other categories would have been displayed in my examples.

With `booking` as the type, and `safari` category removed, this also gives me 24 `booking` products, as they only exist in the safari category:

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/1038062/197548354-fbb5ce25-270e-4285-9fda-1ae993da2b07.png">

So my gut feeling is that it is something to do with the product type, and this being an extended product type perhaps. Are you  hardcoding the types of woocommerce products that are being searched to the built in product types, maybe?

The same issue happens if I try to select `bell tents` category, which contains products of type `accommodation-booking`. (This product type is added in by the WooCommerce Bookings Accommodation addon, which is an addon for WooCommerce Bookings)

Zero results with product type left blank:

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/1038062/197548759-d7de1c24-b654-4d66-a99f-c831281b0214.png">

Works if I specifically select the `accommodation-booking`:

<img width="1560" alt="image" src="https://user-images.githubusercontent.com/1038062/197549091-82e318be-d641-4392-b6dc-4426d0c10fe9.png">

**Comment by rtpHarry** [comment]
Looking at the code, it seems you are pulling in the list of product types using a woocommerce function.

The same function is being used to pass the options to the Vue component, and to build the final query.

Building the javascript vue component:

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1038062/197550873-e40db58e-4146-44c6-b9dc-74f76915d6ed.png">

Building the final query:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1038062/197551756-2a0deb37-1280-4145-b963-ba7c1ef3c8e2.png">

So this seems like its a priority issue - the `wc_get_product_types()` is being used to build the final query, before the `product_type_selector` filter has been run.

Looking in the accom and booking plugins, these are just being run with the default priority:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/1038062/197552574-209f4376-e28a-4dd6-886c-e99c63bc9854.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/1038062/197552685-c95428d2-d882-4e34-83b3-3b95bd2ed063.png">

So I think it is ultimately pointing back to JetEngine building the query before the plugins have all finished registering.

Perhaps it needs to be called after `plugin_loaded` - https://developer.wordpress.org/reference/hooks/plugins_loaded/

**Comment by UraraReika** [comment]
Hello @rtpHarry, thanks for the feedback.

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. We install plugin that create new custom product types. After it create new product with this product type. Then create query like this https://tppr.me/YxYGb and https://tppr.me/Iod5B. As you can see everything working correct without manually select the post type.

Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
