### ISSUE TITLE
JetElements - More info / content widgets

### ISSUE THREAD

**Issue by WardWilmsen** [CrocoBlock/suggestions#61]
I would love to use one package as my main elements / add-on provider for Elementor. 
Now I use different elements from different providers, which causes me higher costs + I need to keep every package up-to-date which causes more maintenance.

So I want to suggest some elements that helped me a lot in the past to display more 'text content' in a stylish and modern way.

The elements I still miss in JetElements are elements like the following ones:

- https://powerpackelements.com/demo/card-slider/

- https://uaelementor.com/widgets/info-box/ (Especially the one at the bottom => text overflowed - images)

I think this would be a big improvement if any element like this can be added to the JetElements plugin.

**Comment by shinTM** [comment]
use slider widget for that feature, it will be avaliable in the next 1.15.14 released version https://github.com/CrocoBlock/suggestions/issues/124
