### ISSUE TITLE
JetSmartFilters: adding "All" and default selected taxonomy

### ISSUE THREAD

**Issue by meksone** [Crocoblock/suggestions#610]
Hi, it would be great to have two options in JetSmartFilters, Visual Filter Type, Color/Image mode ("radio" behaviour).
One useful option is the "all items" filter, and the second option is the ability to select one of the configured taxonomy as default checked.

Now I've used a simple jQuery to select one taxonomy as default, but isn't optimal: on page load i see briefly all items, then the filtered view after the jQuery selected the correct taxonomy.

Thanks for any consideration.

**Comment by meksone** [comment]
Strange, nobody thinks that's useful :D

**Comment by arekuusa** [comment]
+1

**Comment by renestefancic2** [comment]
Please

**Comment by frydhogg** [comment]
yes. we need this

**Comment by Lucienjay** [comment]
can you please share your jQuery for this?

**Comment by graphitestudios** [comment]
other smart filters have this... so the visual one definitely needs this too.

**Comment by im-bot689** [comment]
+1

**Comment by marowi85** [comment]
+1

@meksone

Would you be so kind and share your jQuery code with us? As default selection is still not possible.

**Comment by meksone** [comment]
@marowi85 
here's the code;
```
<script>
// Automatic category click
jQuery(document).ready(function(){
jQuery(function(){
jQuery('.jet-color-image-list__label').eq(0).click(); 
});
});
</script>
```
The value inside parenthesys (in the example, .eq(0) ) points to the menu element number; 0 is the first.

Cheers!

**Comment by marowi85** [comment]
Works great. Thank you so much! :)

**Comment by im-bot689** [comment]
@meksone 

Where should I Paste this code?

**Comment by marowi85** [comment]
> @meksone
> 
> Where should I Paste this code?

I placed it in a html widget below the JetSmartFilter widget.

You may have to change the ".jet-color-image-list__label" class. In my case it's a radio filter, that's why I chose ".jet-radio-list__label". You will find the correct class name with the developer console by examining the label.

**Comment by im-bot689** [comment]
@marowi85 Can you share some screenshots, That would be a great help!

**Comment by im-bot689** [comment]
Thanks a lot @marowi85

**Comment by im-bot689** [comment]
It's working but if I click on other options its says "data is not found".

**Comment by SargasTM** [comment]
added an option for all items and the ability to deselect in the visual filter for radio behavior.
will be in version 3.3.0

**Comment by marcieee73** [comment]
The filter label changes but does not filter accordingly :(
