### ISSUE TITLE
Bug: Repeater field names don't work with extended alphabets

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#6101]
**Describe the bug**
Repeater field names allow the user to use any kind of letters when naming the field (during meta box or post type creation).

However, when trying to show the repeater field using a Dynamic Repeater block, only fields with standard English-language a-z + 0-9 lettering seems to work.

**To Reproduce**
1. Create a repeater.
2. Create a repeater field named using letters such as å, ä, or ö (standard Swedish letters).
3. Insert data.
4. Create a Dynamic Repeater block in the editor.
5. Insert repeater field name in the item field.
6. Dynamic Repeater shows the repeater field name, not the values.

Correlation:
1. Repeat above steps, keeping everything the same, but exchange å for a.
2. Dynamic repeater shows correct values.

**Screenshots**
![ExtendedAlphabetError](https://user-images.githubusercontent.com/8066290/197783707-33b23560-813b-4523-917a-f10e6c23dde2.png)

**Desktop (please complete the following information):**
- JetEngine version: 3.0.5
- Elementor version: 3.7.8
- Wordpress version: 6.0.3
- OS: Windows 10 Pro v 21H2
- Browser: Firefox v105.0.3 (64-bit)

**Comment by kaskad88** [comment]
Hello @filwi. To correctly stored the repeater data in the database, the names of the repeater fields should contain only **latin letters**, **numbers**, `-` or `_` **chars** https://tppr.me/IDo6N
