### ISSUE TITLE
Bug: Repeater Field delimiter Trims intentionall whitespaces

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#6102]
**Describe the bug**
When adding a space at the beginning or end of a delimiter, that space is removed (trimmed).

Thus is it not possible to create sentence-like repeater fields, such as "I work with computer, graphics, QA."

**To Reproduce**
1. Create a Dynamic Repeater.
2. Add ", " as a delimiter.
3. The delimiter is changed to "," on the front end.

![Trim1](https://user-images.githubusercontent.com/8066290/197786994-4d42b2d3-b422-4783-bda5-dbefb2b52276.png)

Case 2:
1. Create a Dynamic Repeater.
2. Add ",&#32;" (that is, an HTML ASCII code for a single space) as a delimiter.
3. The delimiter is changed to "," on the front end.

![Trim2](https://user-images.githubusercontent.com/8066290/197787213-67af1977-1e82-4729-96f2-c34d16eb4fbc.png)

Case 3:
1. Create a Dynamic Repeater.
2. Add ",&emsp;" (that is, an M-width space) as a delimiter.
3. The delimiter is shown as expected on the front end.

![Trim3](https://user-images.githubusercontent.com/8066290/197787704-b6a2f955-9cc7-462d-a830-5f450d7492dc.png)

**Expected behavior**
A delimiter should be able to include spaces, especially if they are added intentionally, such as by typing in the ASCII-code.

**Desktop (please complete the following information):**
- JetEngine version: 3.0.5
- Elementor version: 3.7.8
- Wordpress version: 6.0.3
- OS: Windows 10 Pro v 21H2
- Browser: Firefox v105.0.3 (64-bit)

**Comment by kaskad88** [comment]
Fix for the next version - v3.0.7. 
Currently you can use `&nbsp;` or `&emsp;`
Thanks for your report!
