### ISSUE TITLE
The bug of the new version of jet compare & wishlist and jetwoobuilder + Important request.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6112]
**Describe the bug**

Hi team!

As you know, adding products to wishlist is not useful for guest users and this is a feature for registered users on the website. In all websites, it is possible to add products to the wishlist only if the user is registered. On these websites, if the user clicks on the add to wishlist button, she will be redirected to the registration page. Also, if she clicks on the button to view the archive of wishlist, she will be redirected to the registration page. **This is a major weakness in the jet CV plugin, which does not allow this.**
The bug that was added in the new version of jet wobuilder is that if the guest user adds a product to her wishlist and then enters her wishlist archive, no product is added to her wish list. This is a very serious matter. Because users think this is a bug in the website.
So I had an important request to solve this issue.

Please add a new option to the jet CV plugin settings. If we enable this option, if guest users click on the add to wishlist button or want to view their wishlist archive, they will be redirected to the login page. This is a very logical and principled solution. Please check it out. This is an important topic that is currently troubling. The screenshot below is an illustration of the above solution.

![Screenshot (860)](https://user-images.githubusercontent.com/88034902/199125425-38a1a19e-b5d1-4780-b40a-c6b307fdc90a.jpg)

I hope you agree with it. cheers🥂

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello @Michaelgimii, thanks for the feedback.

About the bug, we have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. https://support.crocoblock.com/support/home/.

About new feature at the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

In the next release of the plugin you can use action hooks to handle this behaviour.

For compare:
```php
add_action( 'jet-cw/compare/render/before-add-to-compare', function( $product_id, $context, $render ) {
    // Check if the user is logged in
    if ( ! is_user_logged_in() ) {
        wp_send_json_error( [
	        'redirect_url' => 'https://example.com/new-page'
        ] );
    }
}, 10, 3 );
```
For wishlist:
```php
add_action( 'jet-cw/wishlist/render/before-add-to-wishlist', function( $product_id, $context, $render ) {
   // Check if the user is logged in
    if ( ! is_user_logged_in() ) {
        wp_send_json_error( [
	        'redirect_url' => 'https://example.com/new-page'
        ] );
    }
}, 10, 3 );
```

And add this small piece for JS
```js
jQuery(document).ready(function( $ ){
   $(document).on( 'jet-cw-response-failed', function( event, response ) {
	   window.location.href = response.data.redirect_url; // Keeps page history.
           or
           window.location.replace( response.data.redirect_url ); // Cleans page history.
   } );
});
```

Thank you for your understanding.
