### ISSUE TITLE
compatibility of jet smart filter with elementor loop builder.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6113]
**Please, describe the feature request, making it clear to understand.**

Hi team.

It would be great if you make jet smart filters fully compatible with Elementor's loop builder. Especially the pagination widget.

**Comment by MjHead** [comment]
We cannot 100% guarantee that such integration is possible, because it not 100% depends on JetSmartFilters plugin, but we'll consider it

**Comment by Michaelgimii** [comment]
Hi @MjHead , Do you rarely leave Elementor?

**Comment by MjHead** [comment]
Its not related leaving or not leaving Elementor. The problem that all loop-related functiomality implemented on Elementor side, all JetSmartFilters compatibility may be done only on JSF side. If we'll faced some blocking problem on Elemenotr side - we'll can't resolve it like we do for JetEngine or JetWooBuilder widgets compatibility. So as I said we can't 100% guarantee that this integration is possible. I'll can give more detailed answer when we invesigate this issue deeply.

**Comment by Michaelgimii** [comment]
thank you @MjHead

**Comment by hitsgee** [comment]
Any update on when JSF will work with the new loop builder? I really need this and will not be renewing my subscription if not made compatible.

**Comment by lgrube3** [comment]
Bumping this. This is a deal breaker for me using JetSmartFilter. Any updates on when JSF will work with Loop Grid widget?

**Comment by Joliamendi** [comment]
Is there any news about this feature? Will it be possible for jet smart filters to be compatible with Elementor loop builder?

**Comment by Michaelgimii** [comment]
Now elementor loop builder has reached enough power. I hope crocoblock will adapt to this feature soon.

**Comment by hitsgee** [comment]
Any update on if this is going to be compatible?

**Comment by Michaelgimii** [comment]
Hi @MjHead
Will jet smart filters be compatible with Loop Grid? Is there a plan for that?

**Comment by DanielShuster** [comment]
Hey, any news about it?

**Comment by MjHead** [comment]
Will be released with JetSmartFilters 3.2.0 next week
