### ISSUE TITLE
one bug in new version of jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6114]
**Describe the bug**

Hi

In the new version of jet woobuildet, if we add the product grid widget and change the size of its price, its size will not change in real size, but it will be a little bigger. The reason for that is the default size of the product price in this widget, which is shown in the browser inspect (screenshot below)
**Please note that this bug only occurs in Single product for product grid widget.**

![Screenshot (863)](https://user-images.githubusercontent.com/77163248/199222457-1c0ab096-64da-4e18-8182-bed2e8bb032b.png)

**To Reproduce**

1. On the single product page, add the product grid widget.
2. Change the size of the price in this widget. It changes abnormally.

Now check the size of the price using the browser inspector. By default, there is a size of 1.25em for the price of the products, which caused this bug.

**Comment by Michaelgimii** [comment]
+1

**Comment by Michaelgimii** [comment]
Hi, Is there a plan to fix this bug?

**Comment by 79ho3ein** [comment]
thank you @UraraReika 🥂
