### ISSUE TITLE
JetEngine - jetFormBuilder - post expiration period

### ISSUE THREAD

**Issue by Picrold** [CrocoBlock/suggestions#6117]
Hello CrocoBlock Team,

I hope everything is going well, I'm trying to add an expiration period to my CCT, but it seems it doesn't work with the jetFormBuilder-insert/Update custom content type item. Currently, the Post Expiration Period addon works with the post types only,

Can we get that post expiration period plugin for the CCT also.

Kind regards,
Picrold Canada - picrold.ca

**Comment by Cosirax** [comment]
would be really nice to get this implemented soon!

**Comment by Lonsdale201** [comment]
+1

**Comment by satomiao** [comment]
+1

**Comment by sekhsoyebali** [comment]
+1
