### ISSUE TITLE
JetEngine Form: Hierarchy selection in front end form. (Taxonomy hierarchia)

### ISSUE THREAD

**Issue by xcubex** [CrocoBlock/suggestions#6118]
Hi!

Is it possible to make hierarchy selection fields in profile form, so users can limit the selections?

Like car brands and models, or country, county and the city.
It would be best with automatic ajax loading, after the selected parent category, and children :)
(As in JetSmartFilters.)

Now, I have a taxonomy with many children and grandchildren that are just shown as a single alphabetical list :(

The request does not refer to JetFormBuilder, but to JetEngine Form!

Thanks in advance!

**Comment by MjHead** [comment]
JetEngine forms its a legacy from functionality, there is no new features planned for it, only bug fixes. All new funcitonality and features will be implemented into JetFormBuilder
