### ISSUE TITLE
Add ability to hide 'cx-ui-kit__description' and 'cx-control__description' in the CPT admin screen

### ISSUE THREAD

**Issue by yorkshiredesigner** [CrocoBlock/suggestions#6124]
I find that my clients are often confused by the layout of the CPT admin panel, I would love to see an overhaul of the design to make it cleaner. Even just an option to hide 'cx-ui-kit__description' and 'cx-control__description' will help clean it up. My clients don't need to see these values and it only confuses them.

**Comment by Lonsdale201** [comment]
![image](https://user-images.githubusercontent.com/23199033/199963448-07faf1eb-26b9-4476-8a32-ac19b8afb895.png)
:)

**Comment by yorkshiredesigner** [comment]
I've setup the meta through the CPT settings rather than in 'Meta Boxes', would it make more sense to set them up in 'Meta Boxes' instead?

**Comment by kaskad88** [comment]
@yorkshiredesigner the CPT interface also has the `Hide meta field names` option https://tppr.me/x80LX
