### ISSUE TITLE
Elementor 3.8 Listing Grid bugs: Dynamic Tags - ACF field values not displayed !

### ISSUE THREAD

**Issue by samuelbauer-io** [CrocoBlock/suggestions#6125]
**Describe the bug**
1. In the listing item dynamic tags -> ACF Fields are not displayed
2. "Equal height" option does not work due to "div.e-con" wrapper element introduced in Elementor 3.8 

**To Reproduce**
1. Add custom post type
2. Add ACF Pro field group with text and image field
3. Create new post with ACF fields filled
4. Create a listing template for the post type: Add text and image widget with dynamic tags -> ACF Field values 
5. Create a query for the post type
6. Add this listing widget in Elementor Page & set equal height

**Expected behavior**
Displaying of post ACF values and listing items equal height. Both not present.

**Screenshots**
Before:
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/39118610/199947547-ffc59c75-13db-4ffb-998b-623efea07730.png">
After update to Elementor 3.8:
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/39118610/199948311-f6bfa2e4-10fa-4586-8e27-a42f541a6a24.png">

**Desktop (please complete the following information):**
 -/-

**Smartphone (please complete the following information):**
-/-

**Additional context**
This issue applies to **post and terms listing**! Maybe user listings, too.

**Comment by samuelbauer-io** [comment]
@MjHead Thank you for checking - Urgent issue

**Comment by MjHead** [comment]
We already working on. Fix will be added with 3.0.7 update.
