### ISSUE TITLE
Saving/Exporting JetAppointments 

### ISSUE THREAD

**Issue by woofyoso** [CrocoBlock/suggestions#6130]
Hi, dear Crocos. I hope you are doing well.
I want to request a feature.
Is it possible to add an **export** button in appointments?
I think this will be very useful to many users of the JetAppointments plugin.

Thanks in advance,

PS: I was searching for an exciting thread but I couldn't find any. Sorry if there is a similar feature request,

**Comment by andressavw** [comment]
YES! I need this too.

**Comment by MjHead** [comment]
Currently on testing stage. Will be added with JetAppointments 2.0.2 update
