### ISSUE TITLE
Open JetPopup when clicking on container

### ISSUE THREAD

**Issue by mateitudor** [CrocoBlock/suggestions#6131]
The feature is simple, please consider extending JetPopup to open when clicking an Elementor container.

Thanks!

**Comment by rtpHarry** [comment]
Isn't this already possible with custom selector?

Go to the JetPopUp screen (Admin > Jet Pop Up > All) then click edit settings:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/1038062/204575427-2267bfd2-0c83-49d3-85c3-00e94fc347ed.png">

Then assign that class to your element you want to be the trigger (and make sure the Conditions are including the popup on that page)

**Comment by Crocoblock** [comment]
was added in JetPopup 2.0.8 https://imgur.com/0hNCB8d
