### ISSUE TITLE
JetEngine add Dynamic Field filter field output: "generate excerpt / trim string" options

### ISSUE THREAD

**Issue by Cosirax** [CrocoBlock/suggestions#6132]
Hey there,

it would be nice to have the "generate excerpt" option not only when I choose as object field excerpt. E.g. when I have some CCT and I would like to have something like an excerpt of it its generelly not possible to create one (or am I missing something?) however so it would be nice to have generally the option to shorten strings by the filter field output option.

In my imagination it would look like:
![generate excerpt trim string](https://user-images.githubusercontent.com/35615340/200172297-49ca67b2-ec40-48bf-b4fe-aebb6d64cc85.png)

**Comment by MjHead** [comment]
https://i.imgur.com/5fg3o3t.png this option already included as Module
