### ISSUE TITLE
JetEngine - Data Stores - clear posts on delete plugins

### ISSUE THREAD

**Issue by Picrold** [CrocoBlock/suggestions#6133]
Hello, Teams

I added the wishlist to the post from the data stores sections; I can add a post to the wishlist page and remove it; it works with no issues. Plus, I added the JetEngine - Data Stores - clear posts on delete plugins to clear deleted posts once it's been removed, but that plugin didn't remove any deleted posts from the data stores.

Clear posts on delete work only with CPT, not CCT

**_From the Support Team

Hi!

Indeed, the addon does not currently work with CCT items. I have noted this as a feature request for our future roadmap. Hopefully, our devs will address it in the future!

Kind regards,
Vicky, Crocoblock Team_**

Can we get that feature request for CCT?

Kind regards,
Picrold Canada
picrold.ca

**Comment by Picrold** [comment]
Hello Crocoblock,

I hope everyone is well; please, is there any update on the request?

Many thanks

Picrold Canada

**Comment by Picrold** [comment]
Hello Crocoblock,

I hope everyone is well; please, is there any update on the request?

Many thanks

Picrold Canada

**Comment by bormotovva** [comment]
JetEngine Remove CCT item from data store on delete
https://gist.github.com/Crocoblock/22045ed3b3209e2ae5c96bd66a2b9564
