### ISSUE TITLE
Multiple Post & Page Clauses

### ISSUE THREAD

**Issue by tadytomas** [CrocoBlock/suggestions#6136]
I need to display all posts in the category, but filter out multiple posts that I have entered to the "posts" meta-fields on the home page. Currently, it's possible to filter by only one meta-field (with the function "Post Not In"). 

Why do I need to do it? I'm setting up a news media website homepage where I have a top section with top stories and below several lists with latest articles in several categories. Editors add articles to specific "top story" widgets with the "posts" meta fields on homepage as mentioned above. What I have to achieve is when they select certain articles for the "top story" widgets, these are not displayed in latest articles below.

I guess it's a pretty standard scenario for many websites, I'm quite surprised this is not possible. :( 

![example](https://user-images.githubusercontent.com/5558262/200381454-4e9df99c-d112-47de-8fe8-33299bd4b9af.png)
![homepage](https://user-images.githubusercontent.com/5558262/200381462-18759fb3-6f6c-4f2a-ae09-05132756bd57.png)

**Comment by MjHead** [comment]
With 3.1.1 added Query Results macros. You can use it to exclude already showed posts

**Comment by tadytomas** [comment]
Thank you!!
