### ISSUE TITLE
@stasonua0 Hi! You can use this option http://prntscr.com/p1rajf

### ISSUE THREAD

**Issue by thietaudev** [CrocoBlock/suggestions#6139]
HI!, can u show again case?
link is broken

**Comment by UraraReika** [comment]
Hello @thietaudev!

You shouldn’t create such an issue here. Please follow our guidelines https://github.com/Crocoblock/suggestions/tree/master/.github/ISSUE_TEMPLATE. If you want to tag someone do it it the same issue you were talking .

Thank you for your understanding.
