### ISSUE TITLE
JetEngine - jetFormBuilder - post expiration period

### ISSUE THREAD

**Issue by Picrold** [CrocoBlock/suggestions#6146]
Hello CrocoBlock Team,

I hope everything is going well, I'm trying to add an expiration period to my CCT, but it seems it doesn't work with the jetFormBuilder-insert/Update custom content type item. Currently, the Post Expiration Period addon works with the post types only,

**_Hey,

Currently, the Post Expiration Period addon works with the post types only. I have noted your question as a feature request, but I cannot give any approximate time frames for its implementation. All new feature requests are processed by our devs in the order of relevance.

Check your ticket status https://support.crocoblock.com/helpdesk/tickets/88178

Kind regards,
Vicky, Crocoblock Team_**

Can we get that post-expiration period plugin for the CCT

Kind regards,
Picrold Canada - picrold.ca

**Comment by fostira** [comment]
This would be also much needed. For instance if your websites have GDPR policy to keep form submissions (made into a CCT) for a certain amount of time.

**Comment by createque** [comment]
Agree. Post Expiration Period addon not work properly with JetFormBuilder - it is not possible to insert/update custom content type as @Picrold wrote.
For now, due to this issue  I have turn off Post Expiration Period addon, because it is useless in my cases...

**Comment by Picrold** [comment]
Hello Crocoblock,

I hope everyone is well; please, is there any update on the request?

Many thanks

Picrold Canada

**Comment by Picrold** [comment]
Hello Crocoblock,

I hope everyone is well; please, is there any update on the request?

Many thanks

Picrold Canada
