### ISSUE TITLE
Setting accordion icons globally instead of setting them for each individual accordion element

### ISSUE THREAD

**Issue by SolunaCG** [CrocoBlock/suggestions#6148]
Hey there! 

As suggested by the support team I´m requesting this:

I´m creating an encyclopedia with medical terms for a client and he´d like to have one field in the wordpress backend where he can simply add all the terms with the corresponding descriptions. I´m using the "dynamic data addon" in combination with an options page and the crocoblock accordion. It´s working but it´s really annoying that me or my client have to set the icons for "accordion closed" and "accordion active" for every single element in the encyclopedia since the encyclopedia of my client contains hundreds of terms. 

It´d be great if these icons could be loaded globally for all the elements. 
![Bildschirmfoto 2022-11-09 um 08 46 54](https://user-images.githubusercontent.com/114682524/200769760-ff02b45f-ab32-4fea-a82a-cd3595eb31a0.png)

**Comment by kaskad88** [comment]
@Soluna1989 Are you use the JetPlugins Dynamic Data Addon for this case ?

**Comment by SolunaCG** [comment]
Yes, that´s what I´m using.

**Comment by kaskad88** [comment]
@Soluna1989 You can set global icon settings in the Dynamic settings section of the Accordion widget https://tppr.me/8GMG9

**Comment by SolunaCG** [comment]
omg thanks a lot! don´t know.. sometimes I think too complex when things can be done so easily...
