### ISSUE TITLE
Jet Smart Filter bug

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#615]
Hello, I noticed a bug in the Jet Smart Filter plugin.

Despite the fact that it is worth checking it out - https://prnt.sc/pp6gee
Headers from the filters are still displayed - https://prnt.sc/pp6go2

And a similar problem with SELECT, set to hide - https://prnt.sc/pp6h3o
but they are still displayed ... despite the fact that there are no values ​​in the SELECTs themselves - https://prnt.sc/pp6hfk

Please solve these problems and this filter can already be used in online stores with more than one type of product with the same set of attributes.

/*Оригинал*/
Здравствуйте, заметил баг в плагине Jet Smart Filter.

Несмотря на то что стоит галочна скрыть - https://prnt.sc/pp6gee
Заголовки от фильтров всё же выводятся - https://prnt.sc/pp6go2

И похожая проблема с SELECT, поставил скрыть - https://prnt.sc/pp6h3o
а они всё равно выводятся... несмотря на то что значений в самих SELECT нет - https://prnt.sc/pp6hfk

Решите пожалуйста эти проблемы и данный фильтр можно уже использовать в интернет-магазинах не с одним типом товаров с одинаковым набором атрибутов.

**Comment by UraraReika** [comment]
Done. Next release.
