### ISSUE TITLE
Change Drop-Down List in Custom Query part of Listing Grid Widget into a Search

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#6150]
Right now, the way to add a custom query to a listing grid is to choose it from a drop down list:

![Query1](https://user-images.githubusercontent.com/8066290/200782430-b2eca747-3d8f-4244-a27b-0e9b0b7489aa.png)

With dozens and soon hundreds of queries, which we need since we no longer use the page specific, depreciated post queries, it becomes hard to find the right query.

We'd like to have a search function for adding queries, the same as for adding listings:

![Query2](https://user-images.githubusercontent.com/8066290/200783570-6561fbf4-81e5-48ea-bbce-643470b37ff1.png)

**Comment by Crocoblock** [comment]
was added in JetEngine 3.5.3 https://imgur.com/ZJC2XN2
