### ISSUE TITLE
JetSearch - Ability to Add Link in Notification Text

### ISSUE THREAD

**Issue by GrayersDad** [CrocoBlock/suggestions#6152]
The title says it all.

Sorry, no results were found. Please "Contact" us.

Where "Contact" is a link to the contact page

**Comment by Lonsdale201** [comment]
![image](https://user-images.githubusercontent.com/23199033/201074494-a2dd626a-c0d4-4786-8ef0-dbe1656de8c2.png)
You can to this, just simple add a html a href inside the Negative Search results panel.

**Comment by GrayersDad** [comment]
Don't know why its not working for me?

**Comment by Crocoblock** [comment]
was added in version 3.3.0
