### ISSUE TITLE
WooCommerce errors for Jet Woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6154]
Hi crocoblock.

In the woocommerce status section, there are flaws that point to jet woobuilder. Please check them out.

/home/mysite/domains/domain.com/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/cart/cart-empty.php version 3.5.0 is out of date. The core version is 7.0.1,
/home/mysite/domains/domain.com/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.0.1,
/home/mysite/domains/domain.com/public_html/wp-content/plugins/jet-woo-builder/templates/woocommerce/checkout/form-checkout.php

**Comment by rtpHarry** [comment]
I see this has been closed but I just want to point out that a more thorough check needs doing as it appears to depend what features are enabled as to what is reported in the woo status section.

I came to report this as I have the my-account section custom skinned and that is showing as out of date:

```
/wp-content/plugins/jet-woo-builder/templates/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 7.0.1,
```

So all templates need checking not just the originally reported ones.

**Comment by kochhase** [comment]
And now is the core version 7.4

**Comment by UraraReika** [comment]
> And now is the core version 7.4

Some WC templates were updated so we will check that and update everything in the next release of our plugin.
