### ISSUE TITLE
JetEngine REST Api Doesn't Work With Repeaters

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#6155]
**Describe the bug**
I tried and tried to submit data for a repeater that I had created in JetEngine, on a CPT via the REST Api:

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/1038062/200961722-f4ff30de-28e6-4a8f-ad5f-0edee656db73.png">

All I got was errors and errors along the lines of `rest_additional_properties_forbidden` / `location is not a valid property of Object.` or `rest_invalid_type` / `meta.location-pay-rate is not of type Object.`

![image](https://user-images.githubusercontent.com/1038062/200961757-53d5491e-74a4-468e-ade0-7bb1f93dc28c.png)

![image](https://user-images.githubusercontent.com/1038062/200961777-66952dfd-3530-40d7-903e-d7c834f4005d.png)

After trying for hours I opened a support ticket and got given this snippet:

```PHP
add_filter( 'jet-engine/meta-boxes/rest-api/fields/schema', function( $result, $field_type, $field_settings ) {
    if ( $field_type === 'object' && $field_settings['type'] === 'repeater' ) {
        if ( ! isset( $result['schema'] ) ) {
            $new_result = $result;
            $new_result['additionalProperties'] = true;
            $result = array();
            $result['schema'] = $new_result;
        }
    }
    
    return $result;
}, 0, 3 );
```

This is the example they gave about how to structure the request:

![image](https://user-images.githubusercontent.com/1038062/200961934-e39717d5-8ad7-426f-b733-86d58394177e.png)

And this is how I successfully populated the data using a POST request:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/1038062/200962032-6a07eabd-d20b-4f81-9777-28241038ae62.png">

I'm not sure if this is a limitation / bug in the system, or what was going on? 

All I know is that my request finally worked and I'm posting it here so the information is out in public for the next developer that runs into this. I tried searching the web and got nowhere, so this snippet is a lifesaver.

**Comment by ihslimn** [comment]
This was fixed in 3.1.1, thank you for reporting
