### ISSUE TITLE
Users listing grid in random order

### ISSUE THREAD

**Issue by owong** [CrocoBlock/suggestions#6157]
Hi, I would like to able to show a Users listing grid in random order. 
I've created a Real Estate website and it has about 500 associated agents (users). The site includes a Agents Directory, but I need to show them in random order, but the option doesn't exist for Users Query.
<img width="1622" alt="Screen Shot 2022-11-10 at 08 49 42" src="https://user-images.githubusercontent.com/7605405/201124745-31a052b7-ad34-47bf-8da2-eaf53dbc4ca6.png">

I've already used the order option, but just for post listing grid. That's would be perfect for Users too.

<img width="280" alt="Screen Shot 2022-11-10 at 08 49 59" src="https://user-images.githubusercontent.com/7605405/201125906-8ea5e489-1fc3-47b8-8c7d-ad680875419b.png">

Thanks for your great work!!

**Comment by xtofr** [comment]
Hi,
+1
Actually I thought it was already there... And I sold it 😬....
Hope kaskad88 will find à solution
Thanks anyhow
Courage and strength to you

**Comment by kaskad88** [comment]
Hello.
By default, WP users query does not support random order. 
But there is a custom solution https://gist.github.com/kaskad88/fba279e0ebfa4dbf37f3462688e8af79
