### ISSUE TITLE
Advanced Map Widget

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#616]
Currently, this widget does not work as expected in dynamically adding multiple pins and locations to a single map, I am able to create a listing grid that displays many maps, which doesn't offer any real benefit.

What I would like to be able to create is the following, have 2 columns on a single page, in the first column have the listing grid, for example, businesses. Then in the 2nd column have the map widget, and be able to set the address as dynamic, so it displays all listings in the first column on the map at the same time.

**Comment by kaskad88** [comment]
I merged this issue with #136, which is on the same subject so we could deal with it more efficiently.
