### ISSUE TITLE
jet woobuilder bug

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6162]
**Describe the bug**

Hi @UraraReika , On the product page, the size of the price of the products is out of normal and is displayed a little bigger. This bug appeared in the latest version. Please check it out. thanks

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6114, which is on the same subject so we could deal with it more efficiently.

**Comment by Michaelgimii** [comment]
tthank you @UraraReika , Is there a time frame for the release of the amendment?
