### ISSUE TITLE
JetTricks' tooltip attached to custom selector

### ISSUE THREAD

**Issue by dislokacia** [Crocoblock/suggestions#617]
Need to attach Jettricks' tooltip to custom class our id. It will be very useful for example in case when we need to display a tooltip near the button or another element, but not its container. 
![PU76rPifzn1GXfyif7zjW_lFnv6IqJMFFA](https://user-images.githubusercontent.com/44621240/67703960-f456ae00-f9bc-11e9-8f3a-2ce4624e19de.png)

**Comment by ZemezLab** [comment]
available from version 1.2.4
