### ISSUE TITLE
How to get products of current category in Listing Grid

### ISSUE THREAD

**Issue by JorensM** [CrocoBlock/suggestions#6171]
I have a product listing grid that is located in the Category Archive page. I need to know what posts query I must create to have the listing grid display the products of the current category. I cannot use 'use as archive template', as I must pass additional post queries to the listing grid.

**Comment by morosmo** [comment]
> I have a product listing grid that is located in the Category Archive page. I need to know what posts query I must create to have the listing grid display the products of the current category. I cannot use 'use as archive template', as I must pass additional post queries to the listing grid.

Hi!
Here the steps to get your results:

1. Create WC Product Query using jet Engine
![step1_1](https://user-images.githubusercontent.com/87468744/202099680-18f9eb53-7aae-4d6e-81c7-9b7daaf87339.png)
![step1_2](https://user-images.githubusercontent.com/87468744/202099714-2d6624ec-1dc8-4d5a-bf33-f15065857a2f.png)

2. Create Lisitng Design
3.Create Archive Template 
![step3_1](https://user-images.githubusercontent.com/87468744/202099816-1355c898-cfb8-4510-8562-287293749a7e.png)
![step3_2](https://user-images.githubusercontent.com/87468744/202099827-66ee7a8c-f592-4b63-8471-e1b0e7e69200.png)

4. Results
![r4](https://user-images.githubusercontent.com/87468744/202099872-f17c3892-d66f-42b8-a664-6a8a12b05284.png)
![r3](https://user-images.githubusercontent.com/87468744/202099875-8cca3f5e-c493-4ff2-93d3-261210a46986.png)
![r2](https://user-images.githubusercontent.com/87468744/202099878-d21785d8-d053-4017-a387-5adc21a9fd4b.png)
![r1](https://user-images.githubusercontent.com/87468744/202099880-51635256-aa02-4898-b963-d1b9318e5b5c.png)

You can also add additional Parameters in your query to narrow down results.

**Comment by JorensM** [comment]
@morosmo Thanks for the response. Is there any way to achieve this result using the Posts Query section in the listing options?

**Comment by morosmo** [comment]
> @morosmo Thanks for the response. Is there any way to achieve this result using the Posts Query section in the listing options?

Here you go, Its much easier:'

From Post Quey Choose tax Query--
![post](https://user-images.githubusercontent.com/87468744/202140863-9085ffc8-ea1b-4414-b78a-64e00efac559.png)

Put this micro in "Terms" field:
%queried_term% 

Thanks

**Comment by JorensM** [comment]
@morosmo Hi sorry, I decided to go with the Query Builder method after all. I have another issue. When I use WC Product Query, the listing grid items don't show the product's metadata.

The circled fields are getting the data from the product's meta fields:
![capture43](https://user-images.githubusercontent.com/17122123/202142048-af424131-e684-4c44-806c-12e76cd97701.PNG)

This is the listing grid item's option:

![Capture44](https://user-images.githubusercontent.com/17122123/202143302-e18f9d7f-35cf-4b5f-82f0-3a95fc922ec4.PNG)

**Comment by UraraReika** [comment]
https://github.com/Crocoblock/suggestions/issues/6175
