### ISSUE TITLE
Check-out reservations are still available on JetBooking.

### ISSUE THREAD

**Issue by JacsSalvador** [CrocoBlock/suggestions#6173]
When I make a booking with JetBooking, the check-out is shown in the calendar as available and not busy. How can I solve this?

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.
