### ISSUE TITLE
Bug: Calendar Listing Widget Caption padding & margin sets on wraper instead of caption

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#6174]
**Describe the bug**
Don't know whether this is a feature or a bug, but when working with the caption in the JetEngine Calendar Listing widget, any changes to the caption padding and margin are set on the jet-calendar-caption wrapper, rather than on the jet-calendar-caption__name wrapper. 

This means that it is impossible to add padding/margin between the text and the navigation arrows.

Perhaps the best solution would be to allow the user to add padding/margin to the caption wrapper, the caption name, and the caption navigation individually.

Setup:
- JetEngine version: 3.0.6.1 
- Elementor version: 3.8.1
- Wordpress version: 6.1
- OS: Windows 10 Pro v 21H2
- Browser: Firefox v106.0.5 (64-bit)

![CaptionWrapper](https://user-images.githubusercontent.com/8066290/202132562-41b6f508-2bb6-4be6-8a10-09e5460dd215.jpg)

**Comment by kaskad88** [comment]
Added the `Gap between caption elements` setting . 
This setting will be available in JetEngine v3.1.7
