### ISSUE TITLE
Listing grid items won't retrieve meta data from WC Product Query.

### ISSUE THREAD

**Issue by JorensM** [CrocoBlock/suggestions#6175]
**Describe the bug**
When I use the WC Product Query to get products, the listing grid item fails to display the meta data of the product, created as dynamic fields in the product listing grid item.

**To Reproduce**
1. Create a meta field for products
2. Create a WC Product Query and apply it to a listing grid
2. Create a listing grid item and include in it a dynamic field widget that points to the meta field.

**Expected behavior**
Should display the meta data.

**Screenshots**
![capture43](https://user-images.githubusercontent.com/17122123/202154433-03a47b0a-a229-4d78-97ba-98aabed9b08f.PNG)
![Capture44](https://user-images.githubusercontent.com/17122123/202154468-3cd4599d-8e13-4701-a6f9-e2a324291b91.PNG)

**Comment by JorensM** [comment]
Supposedly this was fixed (#5576), but I'm still experiencing the issue.

**Comment by UraraReika** [comment]
Hello @JorensM, thanks for the feedback.

We have checked your request and everything seems to be working correctly.
- Created meta fields for Products https://tppr.me/w3wPd
- Created query without modifications https://tppr.me/DgBdG
- Setup meta field in some products 
- Created listing grid with source query where WC Product Query selected https://tppr.me/olUUI
- Display meta fields with the help of Dynamic Field https://tppr.me/W5wYB and Dynamic Image widgets https://tppr.me/jOyy

Result - https://tppr.me/OcMUa

Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!

**Comment by JorensM** [comment]
@UraraReika Thank you for your response. The issue was that I hadn't specified the correct listing source and query in the listing item's settings.
