### ISSUE TITLE
JetCompare Table Widget - Hook filter outputs disappear when removing products

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#6186]
JetCompareWishlist For Elementor: 1.5.2

If a visitor removes a product from the Compare table, all contents of custom fields (e.g. checkbox, switcher) where a filter hook is used are blanked out. 
If you refresh the page, the fields appear correctly again.

Before removing
![Screenshot 2022-11-20 120945](https://user-images.githubusercontent.com/54399588/202898977-0fe0168d-d7b1-411e-8254-6ab8eddc451a.jpg)

After removing a product
![Screenshot 2022-11-20 121015](https://user-images.githubusercontent.com/54399588/202898981-1323b4ce-0c3d-411a-bc35-a7009dd00fee.jpg)

**Comment by UraraReika** [comment]
Hello, thanks for the feedback.

About the bug, we have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. https://support.crocoblock.com/support/home/.

Thank you for your understanding.
