### ISSUE TITLE
JetWooBuilder edit checkout page, cart page, thank you page & my account page 

### ISSUE THREAD

**Issue by OktopusD** [Crocoblock/suggestions#619]
I suggest that you add a feature to edit cart page, checkout page, thank you page and my account page in Woocommerce. Currently we have to buy other plugins to do that and it's annoying because other plugins are not compatible with jetWooBuilder. Would be a great feature, so we could actually use only your plugin!

**Comment by UraraReika** [comment]
I merged this issue with #498, which is on the same subject so we could deal with it more efficiently.
