### ISSUE TITLE
[Query Builder] Add description field to communicate what the query is for

### ISSUE THREAD

**Issue by antoinelbch** [CrocoBlock/suggestions#6194]
When creating queries I try and give them a clear and descriptive name. Nevertheless, when I come back at a later time or work in a team, it is not always clear from the title what is its goal or where it is/should be used.

Having a field, besides the title, where a longer description could be added would be very helpful to provide more information about the query to myself or team members.

**Comment by Floydtm** [comment]
Added in version 3.1.5
Thank you!
