### ISSUE TITLE
 Modify item header restrictions in characters, not words

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#62]
Good evening, this function, as I understood it, was created to ensure that the product cards were even, and the basket buttons were on the same level, but this functionality, which limits the words, does not solve this problem, but this problem is 100% number of characters.

/*Оригинал на русском*/
Plugin - Jet Woo Builder, Widget - Product Grid
http://prntscr.com/mqipzj
Добрый вечер, данная функция как я понял была создана для того чтобы карточки товара были ровные, а кнопки корзины на одном уровне, но данный функционал, который ограничивает по словам, не решает этой проблемы, но такую проблему в 100% случаев решает ограничение заголовка по количеству символов.

**Comment by SashkoWooTeam** [comment]
Release 1.4.0 Jet Woo Builder
