### ISSUE TITLE
Only Login user can Leave Comments on Reviews (Jet Reviews)

### ISSUE THREAD

**Issue by morosmo** [CrocoBlock/suggestions#6200]
Hi @Crocoblock @MjHead 
I just started using jet review by crocoblock in one of my project. I need to now Is its possible on jet reviews to do these things ?

**1. Add additonal field on review form:**
Currently we can add only number field . Is it possible to add "Text" or "Select ", chekcbox type fields?
![form field1](https://user-images.githubusercontent.com/87468744/203849910-4d0a91fb-5ba3-4c3e-b58e-edc49267700e.png)

I see this article on crocoblock :https://crocoblock.com/knowledge-base/articles/how-to-enable-dynamic-reviews-for-any-post-type/
But I dont now how they put the legend fiield inside review form:
![Form fields](https://user-images.githubusercontent.com/87468744/203849891-bf1a086e-a289-4191-88f7-4624a127a6d7.png)

Just like we enable that only login user can leave comments.

**2. How can we restrict comments like reviews so only login user or user role selected on backend can leave review on comments**

![comments 1](https://user-images.githubusercontent.com/87468744/203850349-6a9a4149-7f37-4672-9cdd-5c2bb8fcfc1f.png)
![comments 2](https://user-images.githubusercontent.com/87468744/203850352-b36e32a4-c7a2-4d42-ab97-31be79cb905a.png)

Functionailt Needed:
![comments 3](https://user-images.githubusercontent.com/87468744/203850560-eb8e877d-fb14-4275-8c96-0557dfeb34da.png)

**3. How can user edit their review or comment if they make a mistake . If someone wants to edit their review hwo can they do that . There is not button on review when we login so user can edit their review or comment.**

![reviews](https://user-images.githubusercontent.com/87468744/203851149-ba44c042-3ab0-4d17-be32-1cb0639cc52f.png)

Thanks in Advance!

**Comment by morosmo** [comment]
Hi @Floydtm Thanks for assigning. 
@shinTM Any update on this?

**Comment by morosmo** [comment]
@shinTM IF these features are not available can team work on that in future updates?

**Comment by morosmo** [comment]
@Floydtm No Respose at all :(

**Comment by Floydtm** [comment]
@morosmo Please review this information https://crocoblock.com/faq/ https://prnt.sc/ohDLnKcC-uTN

**Comment by morosmo** [comment]
@Floydtm Thanks for Sharing
