### ISSUE TITLE
Listing Grid not showing search results on search page.

### ISSUE THREAD

**Issue by JorensM** [CrocoBlock/suggestions#6201]
**Describe the bug**
The Listing Grid widget is not showing search results on my search page.

**To Reproduce**
1. Create some products
2. Add Listing Grid widget to search page, and enable "Use as Archive Template" option
3. Go to search page, and search for a product

**Expected behavior**
Should show search results

**Screenshots**
Here are my settings for the widget: 
![settings](https://user-images.githubusercontent.com/17122123/203923712-6dc10fcf-49a8-4719-a378-22c1a45b2ed3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 107

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
