### ISSUE TITLE
Feature Req: Add Query/Relationship name to Deletion Confirmation dialogue box

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#6202]
When you're deleting a query from the query list or a relation from the relationship list, you get a deletion confirmation - but nowhere does it say **which** query/relation you're deleting.

It would be better to have the query/relation name in the deletion confirmation in case you click on the wrong one (which is easy to do when you've got a lot of them):

![QueryName](https://user-images.githubusercontent.com/8066290/203929958-24042cff-b211-4246-a009-a41d934524d5.jpg)

**Comment by morosmo** [comment]
+1

**Comment by kaskad88** [comment]
Added in JetEngine v3.1.4
