### ISSUE TITLE
Jetformbuilder Stripe Recurring Payment

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#6211]
Jetformbuilder Stripe Recurring Payment option is not there at the moment as addon but it's a very much needed feature. Any plan to start working on this?

**Comment by morosmo** [comment]
+100000

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/6293)
