### ISSUE TITLE
Removing products from favorites using Ajax in product grid widget.

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6218]
**Please, describe the feature request, making it clear to understand.**

Hello crocoblock team.

We display the wishlist using the product grid widget. Therefore, in this widget, we activate the settings related to the jet CW plugin. In this widget, using [these settings](https://prnt.sc/BNE51HN7u-qI), if users click on the heart icon, the product will be removed from the wishlist. But there is a very serious problem here.
The problem is when users delete the product from the wishlist, the product is not deleted by Ajax. Rather, they have to reload the page to remove the product from the list. Many users report this to us as a bug.
I hope you add Ajax support in the near future. Thanks to the great crocoblock team.

**Comment by 79ho3ein** [comment]
similar to #6111

**Comment by UraraReika** [comment]
I merged this issue with #6111, which is on the same subject so we could deal with it more efficiently.
