### ISSUE TITLE
Customize WP Login page with croco

### ISSUE THREAD

**Issue by bombarda-rpd** [CrocoBlock/suggestions#6220]
Hello! 
It will be realy nice to have to possibility to customize WP login page with croco instead of using other plugins!

**Comment by Lonsdale201** [comment]
What's the difference if you do it with an extension that doesn't fit the profile instead of another specialised extension?  :)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
