### ISSUE TITLE
responsive control for title Length in product grid/list widget - jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6225]
**Please, describe the feature request, making it clear to understand.**

Hi

If possible, please add the responsive feature to the product grid/list widget > [title Length](https://prnt.sc/fh0xa1MNJqds).
Currently, we can only enter a value that applies to both desktop, tablet, and mobile, which creates issues with responsiveness.
But if you add responsive control to this option, it will be great and we won't have any problem.

thank you

**Comment by Lonsdale201** [comment]
Yes, its a good suggestion, btw if you need a temporary solution:

@media screen and (max-width: 767px) {
.selectedclass {
display: -webkit-box;
  -webkit-line-clamp: 3; /* Change the row number here */
  -webkit-box-orient: vertical; 
  overflow: hidden;
  }
  }

**Comment by Joliamendi** [comment]
This is really needed. Please crocoblock 😍

**Comment by UraraReika** [comment]
Hello and thanks for the feedback.

Unfortunately this option cant be done as responsive. This happens because this functionality handles in the backend with the help of standard methods where no opportunities to add responsiveness.

Thank you for your understanding.
