### ISSUE TITLE
How to Allow or Disallow Comments from frontend Forms.

### ISSUE THREAD

**Issue by morosmo** [CrocoBlock/suggestions#6239]
**Please, describe the feature request, making it clear to understand.**

I open ticket on support team and here on github some of my ticket are assigned just. I open ticket on support team 2 days ago but they are busy I think so maybe any one can help me with that.

I jsut want  to change the post commenting status for frontned forms but dont nwo what is the meta key for that..
By default wordpress allow us to enable/disable comments for each post. IS it possible to Allow or Disallow Comments from frontend 
form of jetengine or jetforbuilder?

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

We have authors on website so I need this in frontend forms so they cna change the comment status as they wish. IF someone wants to disable comments on any post they can see the dropdown in form liek this as we have in wordpress screen:
![image](https://user-images.githubusercontent.com/87468744/205691051-5237024a-17dc-4b21-a231-aa490f1b4dd9.png)
or  we can work with checkmark field like this:
![image](https://user-images.githubusercontent.com/87468744/205691414-6122f275-2851-464c-b466-fb91cfd9af8c.png)

So this options will get update when we update from frontend.
Thanks in advance!

**Comment by Floydtm** [comment]
As far as I know, this can be done right now. The main thing is to know the name of the option and its value. You can see it in the database https://prnt.sc/IMFA7CDC-qBz Here is a short video for you 
[comments.zip](https://github.com/Crocoblock/suggestions/files/10157485/comments.zip)
