### ISSUE TITLE
JetBooking: add function to set price depending on amount of guests

### ISSUE THREAD

**Issue by zehjotkah** [CrocoBlock/suggestions#6242]
For a serious booking website it would be useful to be able to set a price depending on the amount of guests. 
Example: 
1 guest price per day 50,- € 
2 guest price per day 45,- € -> total 90,- € 
... and so on.

**Comment by Floydtm** [comment]
You can implement this case using calculated fields. If you have problems with this, you can contact our support team. Thank you!
