### ISSUE TITLE
JetEngine Listings | Possibility to style Not found Message

### ISSUE THREAD

**Issue by LTimerr** [CrocoBlock/suggestions#6245]
Hello,

as the title says, it would be nice if there was an option to style the Not found Message message.

As you can see in the screenshot, it is hard to see.

![Screenshot_1](https://user-images.githubusercontent.com/93724776/205944938-665ad18c-c3a2-48f5-910a-9f02c0261f26.png)

Thanks for reading.

**Comment by Picrold** [comment]
+1

**Comment by morosmo** [comment]
+1

**Comment by MjHead** [comment]
done

**Comment by LTimerr** [comment]
> 

Thank you for such a quick turnaround! You are the best!
