### ISSUE TITLE
Support for Bricks Builder

### ISSUE THREAD

**Issue by Calebvw** [CrocoBlock/suggestions#6248]
**Make the Elementor Jet plugins compatible with Bricks Builder.**

**Comment by Floydtm** [comment]
We are working in this direction. Stay tuned for updates. Thank you!

**Comment by Michaelgimii** [comment]
Hi @Floydtm 
Will jet woobuilder and jet search be compatible with bricks? If yes, will it be done in 2022? thanks

**Comment by Floydtm** [comment]
To begin with, we integrate with the jetengine plugin. Stay tuned for updates
