### ISSUE TITLE
Add possibility in JetWooBuilder to create templates for individual Woo categories.

### ISSUE THREAD

**Issue by Nepalcem** [Crocoblock/suggestions#625]
Clients wish to have the possibility in JetWooBuilder to create templates for individual Woo categories.

Currently there is an option to use Products archive template for jetwoobuilder and create a query for specific category .

However the store shop page contains links to products categories in standard format and you cannot replace them with the product archive links.

**Comment by UraraReika** [comment]
I merged this issue with #553 3, which is on the same subject so we could deal with it more efficiently.
