### ISSUE TITLE
Request Flexibility in Product Gallery

### ISSUE THREAD

**Issue by Aishpadai** [CrocoBlock/suggestions#6252]
Hi Team,

1. I want the Thumbnails to the left of the featured Image 
2. Along with it, I also want the Featured Image to slide left & right.

Maybe the solution could be to have either,
1. Two options in the Transition effect (Highlighted below)
          A. Slide vertically (up & down)
          B. Slide Horizontally (Left & Right)
![unnamed (1)](https://user-images.githubusercontent.com/119829485/206418498-79ef4335-5944-4e19-8f57-b6151521df6f.png)

2. Give a separate option to have the thumbnails as well either vertical or horizontal.

**Comment by UraraReika** [comment]
Hello @Aishpadai. Thanks for the feedback.

After next plugin release you will be able to achieve this with the help of filter hook like this:

```
add_filter( 'jet-woo-product-gallery/slider/options', function( $options ) {
	$options['direction'] = 'horizontal';
	return $options;
} );
```

Simply add it to your child theme `function.php` file. This hook will rewrite controls option for main slider.

Thank you!
