### ISSUE TITLE
Tool tips text should support dynamic data

### ISSUE THREAD

**Issue by erotser** [CrocoBlock/suggestions#6253]
As I've realized in the tooltips part of the jettricks plugin you do not have the ability to add dynamic text on the tooltip.

eg: You wish to make a tooltip that displays dynamic data from a meta field from a cpt.
etc.

**Comment by Lonsdale201** [comment]
![image](https://user-images.githubusercontent.com/23199033/206552218-6a055eea-28fd-4b17-9a42-9751fa51fa53.png)
I don't understand, since it supports dynamic tags. :)
