### ISSUE TITLE
JetSmartFilters not working with the new Elementor Loop Grid Widget

### ISSUE THREAD

**Issue by marowi85** [CrocoBlock/suggestions#6254]
**Describe the bug**

JetSmartFilters does not seem to be compatible with the new Elementor Loop Grid widget that is part of the new Loop Builder.

I just tried to make such an layout filterable, but it doesn't work. I also tested a normal Elementor Posts widget to make sure the filter is created correctly, and with that the filters work.

**Plugin versions**

Elementor Version 3.9.0
Elementor Pro Version 3.9.0
JetEngine Version 3.0.7
JetSmartFilters Version 3.0.2

**Comment by Floydtm** [comment]
#6113
