### ISSUE TITLE
Typo on Edit Content Type page

### ISSUE THREAD

**Issue by vcpaige** [CrocoBlock/suggestions#6256]
When you add or edit a CCT, on the right side there's a "Forms" section that says: "You need to install and activate Jet**From**Builder plugin to create CCT-related forms".

**Comment by morosmo** [comment]
@vcpaige 
Jet Engine forms marked as legacy. Please use jetformbuilder forms if you wnat to manage CCT from frontend profile builder. IF you are not usign frontend post submission or other profile builder features just leave as it is.

If you have already created forms using jetengine forms. Please convert jetengine forms to jetformbuilder form using this tool.
https://github.com/Crocoblock/jet-form-builder-converter

Thanks :)
