### ISSUE TITLE
Add dynamic data for text color and background color options in widgets

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [Crocoblock/suggestions#626]
See the screenshot here: https://imgur.com/a/OJWG0K3
This will greatly expand the ability to style block lists and improve usability.
For example: this feature allow to display colored labels for post grid. Colored categories and tags etc.

**Comment by Floydtm** [comment]
@Morgunov-Vitaly, Hi! leave your request here https://github.com/elementor/elementor/issues/new/choose
