### ISSUE TITLE
Interference of jet smart filters with version 3.9 of Elementor pro.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6262]
**Describe the bug**

Hi @SargasTM.

The new version of Elementor Pro has a serious bug with the jet smart filters plugin.

If you update **Elementor Pro** to version 3.9, filters will not work on Elementor **popup**. Please check this out if possible. it's too important.

thank you

**Comment by Michaelgimii** [comment]
Oh, I hadn't noticed that at all. More than 10 filters are now disabled for mobile users. I hope there is a quick fix for it.

**Comment by SargasTM** [comment]
hooks changed in elementor pro v 3.9.0
done, will appear in the next version

**Comment by 79ho3ein** [comment]
thank you @SargasTM

**Comment by Michaelgimii** [comment]
Hi @SargasTM ,Thanks for the quick action.
Is the release time known? approx

**Comment by SargasTM** [comment]
@Michaelgimii  I'm planning this week

**Comment by mnemotiv** [comment]
> @Michaelgimii I'm planning this week

any hint which hooks changed? I may fix myself until it's released

**Comment by mnemotiv** [comment]
> hooks changed in elementor pro v 3.9.0 done, will appear in the next version

any hint which ones changed? I could fix myself for now, as I need it today asap

**Comment by mnemotiv** [comment]
temporary workaround (backwards compatibility):

```js
window.addEventListener( 'elementor/popup/show', function ( e ) {
	$( document ).trigger( 'elementor/popup/show', [ e.detail.id, e.detail.instance ] );
} );

window.addEventListener( 'elementor/popup/hide', function ( e ) {
	$( document ).trigger( 'elementor/popup/hide', [ e.detail.id, e.detail.instance ] );
} );
```

of course, there's "Elementor way" to work with events, but...
