### ISSUE TITLE
JetWooBuilder Stock Status much needed improvements

### ISSUE THREAD

**Issue by towable** [Crocoblock/suggestions#627]
Stock Status widget is very limited in functionality and could do with tweaks to status location, content and styling. For example;

- Stock status should be able to be shown on shop pages, archive pages, single product pages and product grids / sliders 
- Enable and disable what stock status is shown, eg only 'in stock', only 'out of stock', or both / other status
- Ability to change text content of each stock status - eg 'change out of stock' to 'now sold' or 'in stock' to 'Available'
-Ability to apply a product image 'overlay' on all out of stock items to 'darken / lighten' images of out of stock items
- Ability to add text (change text content if desired) and style text on overlay to represent status of stock
- Ability to display ribbons to denote stock status with the same change functionality as above

**Comment by WildHund** [comment]
We appreciate your offering us suggestions for the widget's improvements. However, at this time we’re unable to proceed with all the requests. Unfortunately, these features are not very required by many clients at this time. Maybe these features will be added in the future, but there are no time frames to fulfill them.

**Comment by UraraReika** [comment]
Hello @towable !

Most part of functionality that you want already exist in current plugin version. The other features will be added step by step in the future. Some functionality you can add by overriding the template in your child theme.
