### ISSUE TITLE
add zoom hover effect to list grid

### ISSUE THREAD

**Issue by sasanam** [CrocoBlock/suggestions#6274]
please add zoom hover effect to jetengine List grid 
i mean when we hover to product or list read more button appear 
i added u link for example :
http://demo2.themelexus.com/autozpro/product-brand/brandix/

**Comment by Lonsdale201** [comment]
Things like that are too specific, and it's hard to make a system as wide-ranging as the Listing grid actually work properly, and in multiple variations. I think that would be more of a problem than just taking advantage of the features. With css and a :hover pesudo element, you can do it in a few lines. :)

**Comment by Floydtm** [comment]
@sasanam 
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
