### ISSUE TITLE
Some page slugs are not listing in Meta Boxes Specific Posts field

### ISSUE THREAD

**Issue by tanujgoyal2006** [Crocoblock/suggestions#628]
I was trying to add meta field to some specific pages So I added meta box and added desired pages into specific posts field. I added some of the pages from listing but not all. Is this an error/bug or I am doing something wrong? Please advice.

Below is some screens attached so you can understand the issue well.

1. This screen will confirm that the page which I wanted to add in specific post is exist in the pages.
![page exist](https://user-images.githubusercontent.com/57218823/67942689-6ec24080-fbfe-11e9-9dde-083817261d81.jpg)

2. Now if I try to add this page in Meta box > Specific Posts section then It doesn't appear there.
![page not showing](https://user-images.githubusercontent.com/57218823/67942745-8c8fa580-fbfe-11e9-9b1f-a1b7ab05d3d0.jpg)

Hope I have explained the issue in best possible way to understand. Please check this on priority.

Thanks

**Comment by Floydtm** [comment]
Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help
