### ISSUE TITLE
Tables in Jet table builder doesnt refetch and update it data by itself even after reloading it.

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#6287]
So I made a form to put things in that table, now when I entered new data it doesn't reload or at least update its content even after manually doing it. I need to go to the elementor editor to change minimal things and then that's when it'll reload and shows up my newly added data.  Weird

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
