### ISSUE TITLE
JetEngine does not show images converted to webp on the front end

### ISSUE THREAD

**Issue by smiljimenez** [CrocoBlock/suggestions#6292]
Hello JetEngine team, I hope you are doing well and that you can have a good day at work. I know very well that the customer service trade is sometimes stressful due to so many requests and demands from users. However, the effort, time and energy they invest is reflected in that they do the best they can.

Sorry to bother you, I write to you because they are my last alternative, due to attempts to solve it on their own. I found out that JetEngine doesn't show the webp images which are generated by the Performance Lab plugin, this happens by itself and when the media fields are saving the images in url format and not id.

I will explain so that you understand.

I have a job portal built with JetEngine where job seekers can post their profile. It happens that the photographs of the profiles are usually heavy and for this reason I decided to install the official wordpress plugin called "Performance Lab", to convert the images to webp format. So it worked correctly.

But I ran into a somewhat strange obstacle, which I thought was my server or some plugin that prevented the images from being displayed in webp format from the front end, since regardless, only the original format of the image was displayed, despite from which the webp format was generated.

I use Elementor to display content dynamically with JetEngine from the front end, that is, users fill out a form and a CCT content is published, which will be displayed through an elementor template.

The problem I found out is that when JetEngine media field, it saves images in url format and when it outputs in webp format, it still takes the same old url and not the new one from webp format. However, the only way I found out that if it can display the webp images, is only and when I tell the media field to save the images with the id.

JetEngine team, I am reporting this issue to you, in order to see if there is a chance of finding a solution. The obvious solution would be to specify that the media fields save the images with the ID, however, if I do that I will lose the images that users saved in each of the published content of both user profiles.

Isn't there a way for JetEngine to use the webp url without resorting to formatting the media field from url to id?

I will share a video where the problem is shown: https://www.youtube.com/watch?v=su9xOQsycCs

**### I'm also going to share the conversation I had with one of your customer service agents. So that you can review and verify the attempts we made together to solve the problem:**

with Crocoblock
Started on December 19, 2022 at 03:17 PM Kyiv time EET (GMT+0200)

---

03:17 PM | Reggie Luis Ch: Something else...

03:17 PM | Operator: Hey! Let's deal with whatever you have, but I need to know what are the details of your support request. 
 Could you please guide us, answering in the field below:

03:17 PM | Reggie Luis Ch: Hello JetEngine team, I hope you are doing well and that you can have a good day at work. I know very well that the customer service trade is sometimes stressful due to so many requests and demands from users. However, the effort, time and energy they invest is reflected in that they do the best they can. 
 Sorry to bother you, I write to you because they are my last alternative, due to attempts to solve it on their own. I found out that JetEngine doesn't show the webp images which are generated by the Performance Lab plugin, this happens by itself and when the media fields are saving the images in url format and not id. 
 I will explain so that you understand. 
 I have a job portal built with JetEngine where job seekers can post their profile. It happens that the photographs of the profiles are usually heavy and for this reason I decided to install the official wordpress plugin called "Performance Lab", to convert the images to webp format. So it worked correctly. 
 But I ran into a somewhat strange obstacle, which I thought was my server or some plugin that prevented the images from being displayed in webp format from the front end, since regardless, only the original format of the image was displayed, despite from which the webp format was generated. 
 I use Elementor to display content dynamically with JetEngine from the front end, that is, users fill out a form and a CCT content is published, which will be displayed through an elementor template. 
 The problem I found out is that when JetEngine media field, it saves images in url format and when it outputs in webp format, it still takes the same old url and not the new one from webp format. However, the only way I found out that if it can display the webp images, is only and when I tell the media field to save the images with the id. 
 JetEngine team, I am reporting this issue to you, in order to see if there is a chance of finding a solution. The obvious solution would be to specify that the media fields save the images with the ID, however, if I do that I will lose the images that users saved in each of the published content of both user profiles. 
 Isn't there a way for JetEngine to use the webp url without resorting to formatting the media field from url to id? 
 I will share a video where the problem is shown:

03:17 PM | Operator: Thanks for clarifying! Please wait a bit, I'm looking for the available agent for you to help! 😉

03:17 PM | Reggie Luis Ch: https://www.youtube.com/watch?v=su9xOQsycCs

03:17 PM | Anastasiia from Crocoblock: Hi there!

03:29 PM | Anastasiia from Crocoblock: Did you use JetEngine or JetFormBuilder to create a form?

03:29 PM | Reggie Luis Ch: JetEngine

03:30 PM | Anastasiia from Crocoblock: JetEngine forms are legacy. Could you please try with JetFormBuilder plugin? We also have a converter, so you won`t lose the progress 
 
 https://github.com/Crocoblock/jet-form-builder-converter

03:33 PM | Reggie Luis Ch: Mm... I don't understand, but JetFormBuilder is paid, right? 
 Could you please explain in more detail, please excuse my ignorance.

03:33 PM | Anastasiia from Crocoblock: Here you can download JetFormBuilder plugin. It is free 
 
 https://wordpress.org/plugins/jetformbuilder/ (https://wordpress.org/plugins/jetformbuilder/)

03:36 PM | Reggie Luis Ch: Ok, sorry I didn't explain myself better, what I mean, how could this help me with the mentioned problem? 
 I'm a bit confused, please excuse my ignorance.

03:37 PM | Reggie Luis Ch: Do you think that if I install the jetformbuilder it could help me to solve the mentioned problem?

03:37 PM | Reggie Luis Ch: Excuse my questions, it is to learn and better understand your proposal

03:39 PM | Anastasiia from Crocoblock: Sure, that's alright! You use a third-party plugin and I can't guarantee that we are compatible with it. However, we can try to check with formbuilder. Engine Forms will no longer be updated, so we recommend using JetFormBuilder plugin. There are more features and options

03:41 PM | Reggie Luis Ch: I see if I install it, what will happen to the current forms I have? They will be deleted?

03:42 PM | Anastasiia from Crocoblock: No, they will be saved

03:43 PM | Reggie Luis Ch: Well, I'll try to see if it solves the problem and let you know. It's going to take a while, because I'm going to make a backup on the website and then I'm going to test if the webp images will show up.

03:44 PM | Anastasiia from Crocoblock: Ok, sure. I'm here

03:44 PM | Reggie Luis Ch: Thanks :)

03:44 PM | Anastasiia from Crocoblock: No problem. Hope it will work for you

04:17 PM | Reggie Luis Ch: Hello again, I did the tests and the problem still persists. I think the only way to solve this problem is to make the images are saved with the ID instead of the URL. :(

04:18 PM | Reggie Luis Ch: Do you know of a way to have the media field save the files with the ID without losing any data that was previously saved to the database?

04:22 PM | Reggie Luis Ch: My theory is this, when an image is uploaded and saved with the URL, it seems jetengine doesn't replace it with the new image that has been converted to webp format. But if it works, only and when the image is saved with the ID.

04:22 PM | Reggie Luis Ch: It's like I showed in the video I sent earlier

04:23 PM | Reggie Luis Ch: Where I showed that I had 2 media fields where: 
 One saved the image with the URL and another with the ID, to show the differences.

04:29 PM | Anastasiia from Crocoblock: _This message was deleted_

04:29 PM | Anastasiia from Crocoblock: Sorry for the delete message. Let me consult with the team, please wait a moment

04:30 PM | Reggie Luis Ch: Sure :)

04:35 PM | Anastasiia from Crocoblock: Have you chosen the right format and filled out all the fields in the media field? 
 [Image "image.png"]

04:44 PM | Reggie Luis Ch: Yes, that's established

04:45 PM | Anastasiia from Crocoblock: Ok, great

04:47 PM | Reggie Luis Ch: Although I clarify, it is not that I am trying to upload webp images. Rather, I upload a JPG image and a wordpress plugin called Performance Lab is in charge of transforming it to webp.

04:47 PM | Reggie Luis Ch: It's like I said at the beginning of the conversation

04:48 PM | Reggie Luis Ch: So when the image is converted to webp. JetEngine displays it in the font end only if the image was saved with the ID.

04:49 PM | Anastasiia from Crocoblock: I see, checking with the tech team if we can do something

04:51 PM | Reggie Luis Ch: I really appreciate your interest in helping me, seriously. :)

04:53 PM | Anastasiia from Crocoblock: I was told that you need to upload files in the webp format iniatially

04:56 PM | Reggie Luis Ch: It is that this option is not feasible for me, because those who upload the images are users. Let me explain, the people who use my website post their profile to look for a job and the profile images are uploaded in JPG format, so I cannot force users to convert those images in webp format, because I will offer a bad experience for them .

04:56 PM | Reggie Luis Ch: I can do that in case I'm uploading an image to be used for web design.

04:57 PM | Reggie Luis Ch: But my clients are users who register and publish, they usually upload their images from their cell phones and they are not computer technicians like me.

04:58 PM | Reggie Luis Ch: That's why I needed to use the Wordpress plugin "Performance Lab" to automatically convert those JPG images to webp and thus optimize my website

04:59 PM | Reggie Luis Ch: A thousand apologies for all this inconvenience, I know you are not obliged to help me. That's why I really appreciate your time.

05:02 PM | Anastasiia from Crocoblock: Thank you for the empathy, I understand your situation and you are right to be upset, but the tech agent told me that we do not guarantee anything. 
 We are open to suggestions 😊 but that depends on lots of factors. Anyways, you may submit the feature request to make it happen or at least find out why it could be realized (our devs are commenting the suggestions on our Git (https://github.com/CrocoBlock/) directly

05:06 PM | Reggie Luis Ch: Thank you very much for trying to help me 
 I have one last question. Is there a way to change the format of the media field from URL to ID without losing the data?

05:08 PM | Anastasiia from Crocoblock: If you iniatially selected Media ID format in the media field, then if you changed it, the images will be deleted

05:11 PM | Reggie Luis Ch: Well I have no choice, I just have to laugh haha, I'll see if I can get other alternatives.

05:12 PM | Reggie Luis Ch: thank you very much my dear :)

05:12 PM | Anastasiia from Crocoblock: That must be so frustrating, I understand you. You can leave a git request and our developers will answer you via email

05:12 PM | Reggie Luis Ch: I'll try, thanks again for everything

05:13 PM | Anastasiia from Crocoblock: No problem 🙏

05:13 PM | Operator: Help Anastasiia understand how they’re doing:

05:13 PM | Operator: Rate your conversation

---
Exported from Crocoblock on December 19, 2022 at 05:21 PM Kyiv time EET (GMT+0200)

**Comment by smiljimenez** [comment]
Hello, could you help me? I have not received an answer :(

**Comment by kaskad88** [comment]
Hello @smiljimenez
The best solution is still to use the media field by url.
But in JetEngine v3.1.4 we added a minor solution for new images to be loaded via a JetEngine form
