### ISSUE TITLE
In Form turn on/off the Woocommerce integration in JetBooking

### ISSUE THREAD

**Issue by bodibel** [CrocoBlock/suggestions#6295]
I am building an auto rental website with JetBooking, where several companies can advertise their cars. Visitors to the site can pay the rental fee through the Woocommerce integration. But I would need the ability for companies to book appointments themselves via FrontEnd interface, in case their booking is not made through the site. To do this, I would need to be able to turn off JetBooking and Woocommerce integration here in the Form they manage.

Or is there some other way to do this?

Thank You

**Comment by UraraReika** [comment]
this feature implemented in release 2.6.2
