### ISSUE TITLE
Making the image slider widget responsive relative to number of slides displayed

### ISSUE THREAD

**Issue by MayaNikolova** [CrocoBlock/suggestions#63]
In my template I have included Jet Engine Dynamic field picking up a gallery meta field type. Call back is to display a gallery slider.
The widget allows you to select how many slides to display. 
 
I would like to be able to display a different number of slides on mobile vs desktop.
As a comparison, the Elementor slider widget is responsive and it is possible to have a different number of images depending on the screen size. Can this be done for the JE widget as well

Thanks!

**Comment by MjHead** [comment]
Added in JetEngine 1.4,0
