### ISSUE TITLE
Meta value order offset is not working

### ISSUE THREAD

**Issue by tanujgoyal2006** [Crocoblock/suggestions#630]
I was trying to order listing elements according to the meta field I created. But it is not showing any records.

Please check screenshots which can help you to understand this issue.

1. I have created this meta field to choose existing posts.
![slots order in meta field](https://user-images.githubusercontent.com/57218823/67944431-7b489800-fc02-11e9-921e-25fd07135266.jpg)

2. After that I have used this meta field ID in order offset of listing grid Post query section to order records as per the order of this meta field but it is now working and not showing any records.
![setting-order](https://user-images.githubusercontent.com/57218823/67944502-9c10ed80-fc02-11e9-837c-c76566533bc9.jpg)

Hope I have explained it correctly. Please provide solution asap.

Thanks

**Comment by Floydtm** [comment]
Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help
