### ISSUE TITLE
Include Elementor Loop as an option for Jet Smart Filters

### ISSUE THREAD

**Issue by ashleyhughesdesign** [CrocoBlock/suggestions#6302]
Hi!  With Elementor's new Loop feature, it would be great if that was an option in the 'apply this filter to' dropdown menu for Jet Smart Filters.  I haven't found a workaround yet and support suggested I post this here.

**Comment by morosmo** [comment]
+1

**Comment by 79ho3ein** [comment]
https://github.com/Crocoblock/suggestions/issues/6113
