### ISSUE TITLE
JetBooking calender view

### ISSUE THREAD

**Issue by Redesite** [CrocoBlock/suggestions#6303]
I was wondering why the "back end" of jetBookings (where you see all your bookings) is NOT the the same as the "back end" of jetAppointments? The jetAppointments back end is much nicer. It has a calender, timeline and filters... Why isn't there these features on the JetBooking?

Furthermore it would also be nice if it was possible to have an overview of all the rooms in the calender. See picture for reference.
![Idea](https://user-images.githubusercontent.com/121241482/209160929-93b635df-ea97-4ad4-b153-fb3a55a089cc.png)

I believe these changes would make the JetBooking compete with big booking systems.

**Comment by Crocoblock** [comment]
was added in JetBooking 3.5.0 https://i.imgur.com/l87deYT.png
