### ISSUE TITLE
Jetbooking | Check-in and Check-out on specific days

### ISSUE THREAD

**Issue by avdstelt** [CrocoBlock/suggestions#6309]
Is it possible to add the function to only check-in/check-out on specific days?

For example only check-in/out on Friday and check-out/in on Monday?

For an example just have a look at https://www.natuurhuisje.nl/vakantiehuisje/66648 here you only can select Monday and Friday to check-in and check-out the rest of the week is grayed out.

I think this is a feature more people are interested in for there B&B websites.

Greetings Arjan

**Comment by UraraReika** [comment]
Hello @avdstelt! Thanks for the feedback.

Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. We've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/.

Thank you for your understanding.
