### ISSUE TITLE
Admin Columns not sortable on post terms

### ISSUE THREAD

**Issue by scubaninja1977** [Crocoblock/suggestions#631]
Add the ability to filter and sort the post terms when using to show admin columns.

**Comment by Floydtm** [comment]
@scubaninja1977, Hi! Describe your request in more detail. If possible, attach screenshots with examples. Thanks you!

**Comment by scubaninja1977** [comment]
Sure I have a post type configured and when I choose admin columns there is an 3 options I can choose from, Meta Value, POst terms and callback.

So Meta value and Custom Callback both have a sortable option, but the Post terms do not, this is what I mean about, adding the sortable option

**Comment by AjayToker** [comment]
+1 on this

**Comment by cultweba** [comment]
+1 on this

**Comment by efrat-eyal** [comment]
+1

**Comment by fabricioventura** [comment]
Nothing yet for this very important item?

You should not forget to adjust these pending issues, which seem small, but make a huge difference in the day to day of those who develop websites.

This solution request is from 2019, it's been 3 years :(

**Comment by kaskad88** [comment]
The **WP_Query** does not allow sorting posts by terms. 
Use the Admin Filters.
The ability to filter posts by terms is already available https://tppr.me/haMb4.
