### ISSUE TITLE
Elementor finder support in jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6312]
**Please, describe the feature request, making it clear to understand.**

Hi

Elementor Finder provides a very quick way to access all website templates and pages. But unfortunately, it is not possible to access the templates made with Jet Woobuilder, and the search time does not help.
I don't know if this compatibility should happen from your side or Elementor. But if it is possible from your side, please support Elementor Finder. **So that templates made with Jet Woobuildet are accessible in Elementor Finder.**

thank you

**Comment by UraraReika** [comment]
Hello @79ho3ein! Thanks for the feedback.

Please specify your request , what do you mean by Elementor Finder, this https://tppr.me/BXRwy?

**Comment by 79ho3ein** [comment]
Hi @UraraReika 

>what do you mean by Elementor Finder, this https://tppr.me/BXRwy?

no😐, elementor finder : https://prnt.sc/Cd5MwyxaHNOQ

We can access Finder from in any part of the website (even the WordPress dashboard) with ctrl + E buttons.
Finder helps us to quickly access different parts of the site such as pages, Elementor templates such as header and footer. But the thing is that the templates made with jet woobuilder are not found in Finder.

**Comment by UraraReika** [comment]
> Hi @UraraReika
> 
> > what do you mean by Elementor Finder, this https://tppr.me/BXRwy?
> 
> no😐, elementor finder : https://prnt.sc/Cd5MwyxaHNOQ
> 
> We can access Finder from in any part of the website (even the WordPress dashboard) with ctrl + E buttons. Finder helps us to quickly access different parts of the site such as pages, Elementor templates such as header and footer. But the thing is that the templates made with jet woobuilder are not found in Finder.

Sorry for not understanding your primal request.

In this situation Elementor search for post types that not excluded from search like this:

```
$post_types = get_post_types( [
	'exclude_from_search' => false,
] );
```
And all our templates posts types not only JetWooBuilder, but JetEngine listings and JetThemeCore templates has this search parameter like that:

`'exclude_from_search' => true`

This parameter excludes records of this type from search results on the site. And then manually adds their library post type like this:

`$post_types[] = Source_Local::CPT; // Source_Local::CPT = 'elementor_library'`

In this situation they didn't provide any hook that can be reached and modified so we can see other types of templates in their search. So in the next update we will provide filter hook `'jet-woo-builder/post-type/args'` for our register_post_type function arguments where you can change this parameter in your child theme so then you can see our templates in Elementor finder.

Thank you for your understanding.

**Comment by 79ho3ein** [comment]
thank you @UraraReika
