### ISSUE TITLE
🪲[BUG] Jetengine 3.0.9 dynamic link > profile page > url no longer works

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#6313]
big bug introduced in jetengine 3.0.9
dynamic link > profile page
no longer allows access to the url

Jetengine v3.0.8
![Capture d’écran 2022-12-27 145018](https://user-images.githubusercontent.com/82481592/209676400-eb040f23-13de-4aff-87e9-849334a25d70.png)

![Capture d’écran 2022-12-27 145451](https://user-images.githubusercontent.com/82481592/209676630-0eed5616-8366-4718-b2f9-462883f98e67.png)

-I can access and edit my form

Jetengine v3.0.9

![Capture d’écran 2022-12-27 145559](https://user-images.githubusercontent.com/82481592/209676799-675403ab-cddc-4a39-a3b5-51629d116424.png)

-I can't access and edit my form anymore

going back to version 3.0.8 fixes the problem

I am using Jetformbuilder v2.1.11

**Comment by kaskad88** [comment]
Fixed in 3.0.9.1
