### ISSUE TITLE
🪲[BUG] Jetformbuilder 2.1.11 media field destroy the images?

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#6315]
Despite the efforts of @girafffee 
jetformbuilder has difficulty with smush type plugins and probably other image optimization plugins 
the situation becomes harshly complicated concerning the fate of images uploaded through the media field
the plugin is not ready to manage the upload and the processing of images at the same time
we hope that another upload logic will put an end to this problem

![Capture d’écran 2022-12-27 151321](https://user-images.githubusercontent.com/82481592/209680199-6f1073cc-d6e9-4aa6-9521-3004335deb45.png)

![Capture d’écran 2022-12-27 151411](https://user-images.githubusercontent.com/82481592/209680209-ac10dbb0-923c-4d1f-8923-c91e29a21096.png)

**Comment by girafffee** [comment]
Hi, @nreljed
Try checking your case with the latest commit. https://github.com/Crocoblock/jetformbuilder

**Comment by nreljed** [comment]
> 
@girafffee thank you for the contribution
the upload on jetformbuilder works without blocking and in the background the images are processed and optimized normally
your fix works correctly 👌😊


![Capture d’écran 2022-12-27 195012](https://user-images.githubusercontent.com/82481592/209714884-175d6069-a935-457a-9472-ff2111064861.png)
![Capture d’écran 2022-12-27 195120](https://user-images.githubusercontent.com/82481592/209714802-e595e0ff-2f10-4ef6-bb7d-24bb0c97fab9.png)




I am closing #5565 which is no longer relevant
I just leave the problem for the watermarks here
with watermark plugins it doesn't seem to work
I did the test at the moment with 3 plugins all almost with the same logic and especially this options
![Capture d’écran 2022-12-27 202732](https://user-images.githubusercontent.com/82481592/209714805-f4b6a232-9657-456e-aa93-090b2cfd55cc.png)
![watermark](https://user-images.githubusercontent.com/82481592/209715206-9c5dd304-d51a-40d6-b9f9-66bcd7ac7f03.png)


if you have a trick or fix to work around the problem and access the watermark plugins through the frontend form 🤞
maybe make this type of plugins believe that the upload is done natively through jetformbuilder?

**Comment by girafffee** [comment]
I chose the first plugin from your list to test. It worked for me with this snippet:

```php
add_filter(
	'jet-form-builder/form-handler/core-fields',
	function ( $fields ) {
		if ( ! defined( 'IMAGE_WATERMARK_PATH' ) ) {
			return $fields;
		}
		Image_Watermark::instance()->check_extensions();

		return $fields;
	}
);
```

Add it to your child theme's functions.php

**Comment by nreljed** [comment]
> I chose the first plugin from your list to test. It worked for me with this snippet:
> 
> ```
> add_filter(
> 	'jet-form-builder/form-handler/core-fields',
> 	function ( $fields ) {
> 		if ( ! defined( 'IMAGE_WATERMARK_PATH' ) ) {
> 			return $fields;
> 		}
> 		Image_Watermark::instance()->check_extensions();
> 
> 		return $fields;
> 	}
> );
> ```
> 
> Add it to your child theme's functions.php

@girafffee thank you it works well
