### ISSUE TITLE
Be able to use a Repeater Listing in a Custom Taxonomy

### ISSUE THREAD

**Issue by djoo** [CrocoBlock/suggestions#6317]
In backend it's possible to add a metabox including a repeater inside a taxonomy.

Would be great if we can use a Listing Repeater as Well. Right now it's impossible. When we create a Listing based on repeated, the taxonomy (custom) are not on the list.

**Comment by kaskad88** [comment]
Hello @djoo 
You can use the Query Builder for the repeater fields https://tppr.me/Jf6Pl and create a repeater listing by the repeater query https://tppr.me/tIKRA.

Inside the listing item you can use the Dynamic Field widget to output the repeater field values https://tppr.me/WniUD

https://crocoblock.com/knowledge-base/articles/how-to-set-repeater-query-type/
