### ISSUE TITLE
JetSmartFilters AJAX Search Remebering Filters When Going Back

### ISSUE THREAD

**Issue by wheretotravelorg** [Crocoblock/suggestions#632]
After filtering results (AJAX) in JetSmartFilters, and I click on a post/product that it filters, it brings the user to the post/products page (good).

Option 1: The problem is when I hit the back button to show results again it resets all of the filters. Is there a way to have the filters not reset when going back, without disabling AJAX?

Option 2: If it cannot be done without disabling AJAX: I know I can disable AJAX and add an "apply filter" button, is it possible to have one button for all of the filters, instead of one button PER filter?

Thanks a lot for all of your help, it is really appreciated!

**Comment by Floydtm** [comment]
@wheretotravelorg, Hi! Options 1: There is no way to implement this case. Options 2: for this there is a separate widget https://prnt.sc/pst1s7

**Comment by wheretotravelorg** [comment]
For option 1 that is understandable.

For option 2 you did not understand what I was explaining. I know there is an "apply filters" option already, but you have to add a button for each filter option. There should be one apply button that works for all of the groups of filters at the same time.

For example if I had checkbox filters and a radio filter on the same page there would only by one apply button that applies both,  not one apply button for each filter type

**Comment by Floydtm** [comment]
You probably misunderstood me. Each widget has a apply button. And there is a separate apply button widget that processes all filters at once
