### ISSUE TITLE
Simple filter in jet smart plugin

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6320]
**Please, describe the feature request, making it clear to understand.**

Hi team.

I have recently migrated to the jet smart filters plugin. This plugin is extremely powerful in customizing the style of filters. But I did not find some simple features in it. Of course maybe there is and I just couldn't find it.

I want to create a very simple filter like the image below.

![filters](https://user-images.githubusercontent.com/103376243/210004878-83e7e413-4ff2-444d-820e-1914da5e78cf.png)

But there seems to be no filter to create it. Also, the ability to display a divider in this filter (like Elementor icon list widget) will be great : 

![divider](https://user-images.githubusercontent.com/103376243/210005111-ed165496-2019-4cf6-b4a7-bd9acb441d05.png)

**Comment by Michaelgimii** [comment]
+1
It would also be great to be able to add an icon for this type of filter. Like the wp Grid builder plugin that offers this great filter :

https://user-images.githubusercontent.com/88034902/210005704-e62fa2d0-0a3e-4893-bbf1-f5badcf2224f.mp4

**Comment by Floydtm** [comment]
your request can be implemented using a radio or checkbox filter https://tppr.me/8xDTf https://tppr.me/kpyAQ as for styling, it can be done using css
