### ISSUE TITLE
Entrance Animation for product Grid widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6321]
**Please, describe the feature request, making it clear to understand.**

Hi crocoblock team.

It would be great if you provide some animations to display the products attractively. This feature will definitely have many fans. Below is an example of this cool feature.

https://user-images.githubusercontent.com/88034902/210006462-9082b3e2-2aa1-4c2a-94b4-abedb65a5ccb.mp4

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
