### ISSUE TITLE
JetElement Bar Chart Tooltip - Setting Disappear as soon as background color is set

### ISSUE THREAD

**Issue by machachen** [CrocoBlock/suggestions#6325]
The Jetelement Bar Chart Tooltip setting will become default as soon as the background color is set. As shown in screenshot below.

(Without Setting Background Color)
![1](https://user-images.githubusercontent.com/58905862/210131208-9e8d79a0-8661-4a6e-95d5-2432c6f4eeda.png)

(With Background Color Set)
![2](https://user-images.githubusercontent.com/58905862/210131222-e0b9aca7-aac8-4bea-9dd9-586709256d40.png)

Thank you!

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-elements/tree/add/issue%236325
