### ISSUE TITLE
Global Setting Not Applied to The Bar Chart

### ISSUE THREAD

**Issue by machachen** [CrocoBlock/suggestions#6326]
Global Setting For both font and color wouldn't applied to the bar chart as shown in the image below.

![1](https://user-images.githubusercontent.com/58905862/210131282-2221f548-4069-467d-9f7a-ad3cc6760d22.png)
![2](https://user-images.githubusercontent.com/58905862/210131284-bb2320f3-bd97-4414-a98b-bf2bb03dab8f.png)

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-elements/tree/Branch_add/issue%236326
