### ISSUE TITLE
JetSmartFIlters: Sort filter results based on the amount of boxes checked

### ISSUE THREAD

**Issue by wheretotravelorg** [Crocoblock/suggestions#633]
It would be great to be able to sort results based on relevancy to the amount of checkboxes selected. (Ex: If one post has 3/5 tags of the checkboxes selected, it would be displayed before a post that only has 1/5 tags of the checkboxes selected) This would greatly improve the relevancy of the results for the user and provide more accurate results, rather than just display results in alphabetical, chronological, random order of any post that contains one or more of the checked boxes.

Thanks!

**Comment by Floydtm** [comment]
We have examined your request and it does not belong to the filter plugin. Filters do only filtering according to your request. Perhaps we will do the sorting by relevance for the following providers http://prntscr.com/pt90jt Thank you!

**Comment by wheretotravelorg** [comment]
Yes I know it does not belong to the plugin, that is why I am suggesting to add it to better filter JetEngine custom posts
