### ISSUE TITLE
More compatibility of jet woobuilder with jet smart filters plugin (Product custom message not found)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6334]
**Please, describe the feature request, making it clear to understand.**

Hi team!

In the previous version, the custom product not found message feature was added to the jet woobuilder plugin. But there is a small limitation at the moment...

If we use jet smart plugin filters + product Grid widget, we cannot assign a custom message for the filters. **For example, the user activates the desired filters, but there are no products matching those filters. So the message: No products matching the filters were found. is shown.** 
This is something we are unable to do at this time.

The image below is what we need :

![filters](https://user-images.githubusercontent.com/88034902/210399034-32202332-aa74-4c46-ab49-efa34a56cd0f.png)

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But you can use this snippet to fulfill your needs:

```
add_filter( 'jet-woo-builder/shortcodes/jet-woo-products/not-found-message', '__your_theme_prefix_set_custom_not_found_message' );

function __your_theme_prefix_set_custom_not_found_message( $message ) {

	if ( isset( $_REQUEST['action'] ) && 'jet_smart_filters' === $_REQUEST['action'] ) {
		$query = new WP_Query( $_REQUEST['defaults'] );

		if ( ! $query->have_posts() ) {
			$message = 'Your filter settings do not return a match. Please choose other options';
		}
	}

	return $message;

}
```

Thank you for your understanding.
