### ISSUE TITLE
[BUG] Ajax Search's query returns true for is_admin()

### ISSUE THREAD

**Issue by JorensM** [CrocoBlock/suggestions#6338]
When I do `pre_get_posts` action and filter out admin pages using `!is_admin()`, the Ajax Search widget's query doesn't get filtered out, meaning that it returns `true` for `is_admin()`, even though it's a client-facing widget.

```
    function mts_alter_query($query){
          if(is_admin()){
                 echo "hello";
          }
    }
    add_action( 'pre_get_posts', 'mts_alter_query', 999);
    
```

When you echo something during the Ajax Search's query, the ajax search displays an error. And in the case of this script, it does display an error, meaning that it returns `true` for `is_admin()`

**Comment by MjHead** [comment]
Ajax Search widget uses common WP logic to serve AJAX requests through admin-ajax.php file. Its WP Codex recommendation. So yes, is_admin() function always returns true for AJAX requests handled by admin-ajax.php. You need to use this function in combination with wp_doing_ajax() or make your check based on some different conditions.

**Comment by JorensM** [comment]
@MjHead Seems kind of weird that a customer-facing widget's query returns true for `is_admin()`
