### ISSUE TITLE
JetSmartFIlters: Checkbox Filter Multiple Tags

### ISSUE THREAD

**Issue by wheretotravelorg** [Crocoblock/suggestions#634]
When selecting multiple options in the checkboxes filter, it will display all results with any (1) or more of the selected options, there should be an option for it to display only results that contain ALL options selected, not just one of them. 
This would greatly help in filtering a lot of results or to get truly specific results. 

For example, on a real estate website, to filter house listings to show houses that contain a pool and a fireplace, you would check the pool and fireplace boxes, and it would only display results that are tagged with BOTH pool and fireplace, not just one of those.

Thanks!

**Comment by Floydtm** [comment]
@wheretotravelorg, Hi! We checked the filters and they work correctly. If you have any problems, you can always contact our [support](https://support.crocoblock.com) Thank you!

**Comment by wheretotravelorg** [comment]
You did not read my suggestion clearly

**Comment by wheretotravelorg** [comment]
Might want to double check that because there are other filter plugins that offer this option such as reactive search pro. You guys need to implement this
