### ISSUE TITLE
Custom Quantity Selectors plugin integration with jet woobuilder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6342]
**Please, describe the feature request, making it clear to understand.**

Hi crocoblock team.

jet woobuilder is an extremely powerful plugin next to Elementor. These two plugins together will make a powerful store website.
But as a relatively new user, I would like to make a criticism of the jet woobuilder plugin.

jet woobuilder still uses old and obsolete buttons to determine the number of products.

![jet](https://user-images.githubusercontent.com/103376243/210811605-254eb44f-9a9b-4728-b104-c028d1aba0b1.png)

Integrating the Custom Quantity Selectors plugin into the core of jet woobuilder is great and at the same time essential. We are now in 2023 and we have to use the methods of the day.
More importantly, most WordPress users tend to avoid installing too many plugins. Therefore, the integration of these two plugins with each other will be a very important event.

Great crocoblock team, let's start the new year with this awesome update💣.

**Comment by Joliamendi** [comment]
**In addition, after activating the Custom Quantity Selectors plugin, the following error is displayed :**

The plugin generated 442 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by 79ho3ein** [comment]
+1
I hope this plugin will be integrated into the jet woobuilder core. This is a feature that will definitely be appreciated by all users.

**Comment by morosmo** [comment]
+1

**Comment by Michaelgimii** [comment]
+1
This is really great. crocoblock please!!!!

**Comment by UraraReika** [comment]
Hello and thanks for the feedback.

Unfortunately i can't give you and answer right now about adding this addons straight in to the core of our plug in but in the future we do not exclude the possibility.

Thank you for your understanding.
