### ISSUE TITLE
Improve Show View Cart Link feature in jet woobuilder (Preview in the editor)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6343]
**Please, describe the feature request, making it clear to understand.**

Hi

Currently, if we enable the Show View Cart Link feature, we cannot customize it visually in the editor. So the only way is to view it in the frontend after the changes are applied, and that doesn't seem like a logical solution.

I think it's great that if this feature is enabled, if we're in the single add to cart widget style tab > view cart section, the view cart button will appear so we can customize it live. After exiting the view cart button customization section, this button will be hidden. I'm not sure if this is possible to implement, but it seems like a smart solution.

Another and easier way is, when we activate the Show View Cart Link feature, this section will be displayed in the editor so that its customization can be seen directly.

thank you

**Comment by morosmo** [comment]
+1

**Comment by Michaelgimii** [comment]
+1

**Comment by UraraReika** [comment]
Hello! Thanks for the feedback.

In this case, the inscription is formed with the help of a java script, exactly after adding the product to the cart, so in this case, we will not add the display of this button in the editor.

Sorry and thank you for your understanding.

**Comment by 79ho3ein** [comment]
thank you @UraraReika
