### ISSUE TITLE
Query builder - Add the possible to set AND OR operators in query clauses

### ISSUE THREAD

**Issue by RoynerG** [CrocoBlock/suggestions#6346]
It would be great if the query builder as the possibility to set the operator type (AND , OR) in "Where (query clauses)" panel.
This is a simple setting that will add an infinity more possibilities to the builder!

![image](https://user-images.githubusercontent.com/89561214/210889330-bd5a009f-0144-44b6-8b3c-887d5d74dad9.png)

Please 🙏. I love crocoblock.

**Comment by morosmo** [comment]
+1500

**Comment by naturalweb-business** [comment]
+1
And it would be very useful if you could also use other SQL functions like GROUP_CONCAT() and others, it would also be ideal if Custom SQL Queries could be filtered and pagination with Jetsmartfilter.

**Comment by kaskad88** [comment]
This feature is available since version 3.2.0
