### ISSUE TITLE
Infinite scroll for product Grid widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6348]
**Please, describe the feature request, making it clear to understand.**

Hi crocoblock team

It would be great if you add the Infinite scroll feature to the product Grid / list widget. This would be a great and useful feature.

**Comment by UraraReika** [comment]
Hello @Michaelgimii!

Right now you can use on of dev tools solution https://tppr.me/Xb9xG follow this link https://crocoblock.com/freemium/tools/. But right now in our roadmap to ad such widget globally  with the help of JetSmart filters so stay tuned.
