### ISSUE TITLE
badges position in product Grid widget

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6349]
**Please, describe the feature request, making it clear to understand.**

Hi team.

In the new version of the jet woobuilder plugin, the Vertical Position option for badges has been added in the product Grid / list widget.
But there is still a fundamental problem. **The problem is that the badges can only be moved within the image area.** This is a major limitation.
Because we can't display badges in desired position.
So, it would be great if you consider the scope of moving badges in the Grid item scope(It is now moveable within the thumbnail range).

**Comment by UraraReika** [comment]
Hello @Joliamendi! Thanks for the feedback.

Unfortunately  we will not provide this functionality in the core of our plugin. But you can simply rewrite template in your child theme to achieve this, for example like this - https://tppr.me/sFvf5. Then if you set up such controls option https://tppr.me/VXcZ7 you will be able to see this - https://tppr.me/J0iTA badge in the corner of the product card and to in the corner of thumbnail wrapper.
