### ISSUE TITLE
JetSmartFIlters: Enable Multiple Options To Be Automatically Selected in the Front End

### ISSUE THREAD

**Issue by wheretotravelorg** [Crocoblock/suggestions#635]
In the back end you can choose only one of the options to be automatically selected in the front end, it would be great if you could enable it so that more than one or all of the options are automatically selected in the front end.

Thanks

**Comment by Floydtm** [comment]
We have reviewed your request. If we do this then the meaning of the plugin is lost. Thanks you!

**Comment by wheretotravelorg** [comment]
It would be very benificial to have more than one option automatically checked in multiple scenarios
