### ISSUE TITLE
Jet Map Listing Zoom and Center Map Click on Marker 

### ISSUE THREAD

**Issue by damianrivadulla** [CrocoBlock/suggestions#6351]
Hello, I would like Jet Map Listing to have the option to automatically zoom in and center the map when a marker is clicked to see its location on the map in detail along with the informative popup.

Once the popup is closed the map should return to the previous state in regards to zooming.

I hope the request is understood. I looked everywhere and couldn't find how to do it

**Comment by jdgranja** [comment]
Hello, I'm looking for this too.

**Comment by kaskad88** [comment]
Hi @rivadami @jdgranja 
This feature is already implemented https://prnt.sc/KsgA010YWq0L
