### ISSUE TITLE
JetBooking Skip Payment

### ISSUE THREAD

**Issue by bodibel** [CrocoBlock/suggestions#6353]
Hi

I have a website where I use JetBooking and JetFormBuilder. On the site you can book appointments in two places, in two forms. However, I only need Woocommerce integration for one of them. For the other one I would like to turn it off.
I found code to do this for JetAppointment, but unfortunately not for JetBooking! 

Is there a way to do this?

Thank You!

**Comment by UraraReika** [comment]
I merged this issue with #6295 , which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
