### ISSUE TITLE
jet woobuilder 2.1.2 Bug

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6357]
**Describe the bug**

Hi @UraraReika
There are two important bugs in the new version of jet wooobuilder. In the following, I will explain them. Please let me know if you are not successful in reproducing them.

1- In all pages, if we add the product Grid/list widget, the product link will be the link of the current page.

**To Reproduce**

1- Create a page.
2- Add the product Grid / list widget.
3- Save the Elementor editor, and view the page in the frontend. If you click on any product in the product Grid / list widget, the product page will not open. Rather, the page will somehow be reloaded.

<hr>

2- When we select or delete the desired variable, these actions are associated with lag. **Please watch the video below :** 

https://user-images.githubusercontent.com/77163248/211197259-3dbc01f7-20ac-48d0-9ae7-4ca45d51b70f.mp4

This is a specific bug. I hope you are successful in reproducing it. 

**To Reproduce**

If we have a header in **sticky** mode and the number of widgets used in this header is large, the variable selection section in jet woobuilder will be associated with lag. In order to test, I placed 30 elementor menu cart widgets in this header.

This bug will be fixed in two ways. 

1- Disable the sticky mode in the header.
2- Sticky mode is active, but there should not be too many widgets in the header.

Please note that this bug did not occur at first and appeared after the update.

thank you

**Comment by Lonsdale201** [comment]
https://crocoblock.com/knowledge-base/articles/jetwoobuilder-devtools-products-grid-load-more-addon/

Also not working with the newest verison. :)

**Comment by Joliamendi** [comment]
> https://crocoblock.com/knowledge-base/articles/jetwoobuilder-devtools-products-grid-load-more-addon/
> 
> Also not working with the newest verison. :)

Why is the load more feature not included in the jet woobuilder core? Is there a specific reason? Even Elementor's posts widget offers this feature. jet woobuilder doesn't do it with its power?

**Comment by outrank-james** [comment]
Similar issue here too - Looks like the Product Archive template will take the first product link for the title and image where permalink is activated on title and image. The button to add to cart or view product goes to the correct product, but the image and title link will go to the first product in the loop

**Comment by mayanksdudakiya** [comment]
So if we add "Product Grid" widget on homepage or any other page other than "shop" then single product link not working. Its happening in newer version too.

**Comment by UraraReika** [comment]
Hello @79ho3ein. Thanks for the feedback.
1 - Fixed and new release will be soon.
2 - This behavior doesn't only happen in JetWooBuilder templates, so we can't attribute it to problems with our plugin and its template building. This problem occurs due to the specific way the Elementor Pro sticky header works, and it will work in a similar way not only in templates built with the help of our plugin or Elementor Pro, but also on a standard template.

@Lonsdale201 right now this issue fixed and updated with some new features  and in the process of testing 

@outrank-james 

> Similar issue here too - Looks like the Product Archive template will take the first product link for the title and image where permalink is activated on title and image. The button to add to cart or view product goes to the correct product, but the image and title link will go to the first product in the loop

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. https://support.crocoblock.com/support/home/ 

Thank you for your understanding.

**Comment by 79ho3ein** [comment]
thank you @UraraReika 

Regarding the second one, do you know exactly why this problem occurs? I have never been able to reproduce it in just Elementor + Elementor Pro. So I can report it to Elementor developers.

**Comment by Joliamendi** [comment]
Hello @UraraReika 

>@Lonsdale201 right now this issue fixed and updated with some new features and in the process of testing.

Do you mean that the load more feature will be added to the plugin core?

**Comment by UraraReika** [comment]
> Hello @UraraReika
> 
> > @Lonsdale201 right now this issue fixed and updated with some new features and in the process of testing.
> 
> Do you mean that the load more feature will be added to the plugin core?

Right now no.

**Comment by 79ho3ein** [comment]
@UraraReika 

Regarding the second issue, are there any details I can pass on to the Elementor team so they can identify the problem faster?
I could never reproduce this bug without jet woobuilder (only in elementor and elementor pro).
