### ISSUE TITLE
JetEngine Relations > Register separate DB table > Missing MySQL Index

### ISSUE THREAD

**Issue by pr24ch** [CrocoBlock/suggestions#6358]
I created some relations with JetEngine, selecting the "Register separate DB table" option. The tables were all created successfully, but no indexes were created for the parent_object_id and child_object_id, which made the queries slow.

I had previously used the relations of Metabox.io, but in the backend with several 100 relations can no longer be loaded or becomes extremely slow. The GUI of JetEngine is more cleverly built in this regard. After I changed the relations in the code from Metabox to JetEngine, the queries became extremely slow, which was due to the missing indexes mentioned above. After I added them manually, the page runs as fast as before.

**Comment by Crocoblock** [comment]
was added in JetEngine 3.5.4 https://i.imgur.com/1MjZtQh.png https://i.imgur.com/nrNnctW.png
