### ISSUE TITLE
WooCommerce Product Grid/List - Permalink URL Loop Issue

### ISSUE THREAD

**Issue by outrank-james** [CrocoBlock/suggestions#6360]
When using the JetEngine WooCommerce Product Grid and List block, and you have title permalink and image permalink selected, while viewing the front end of the shop, the block seems to use the first URL in the loop for all products on the page (for the image and title), the buttons to add a product to cart and view product remains in tact.

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by outrank-james** [comment]
Rolling back to a previous version fixes the issue, so definitely something on the latest version. I'll get a ticket in with Support.
