### ISSUE TITLE
Bricks Builder сompatibility

### ISSUE THREAD

**Issue by Picrold** [CrocoBlock/suggestions#6362]
Hello Team,

I hope everything is going well; we plan to build a new website using Bricks Builder. Can we get Jetsmartfilter, jetsearch, jetblocks, and jetformbuilder for Bricks Builder?

Many thanks

Picrold Canada

**Comment by Floydtm** [comment]
We are currently working in this direction. We will soon release an update for the jetengine plugin. this will allow you to use filters with the bricks builder. Regarding other plugins, I cannot tell you whether there will be integration with bricks builder. Stay tuned for updates.
