### ISSUE TITLE
auto idexer bug / jet smart filters

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6368]
**Describe the bug**

Hi

If we disable the jet smart filters plugin and then re-enable it, the filters will not be displayed in the frontend. The filters will not be displayed until we click on the Apply Indexer button. Please fix this. So that after reactivating the plugin, the filters are automatically indexed and the filters are displayed.

**To Reproduce**

1. Make sure you have some filters on your website.
2. Disable the jet smart filters plugin.
3. Activate it again.
4. View the front end. Filters are hidden.

**Filters are not displayed in the frontend until we click the Apply Indexer button.**

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
