### ISSUE TITLE
Dynamic Table Query Builder

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#6369]
Hello, consider choosing Query in the table widget https://prnt.sc/n7dVUd9663dK , and not in the table itself https://prnt.sc/8t-GbqZAuYhw , otherwise you have to create duplicate tables for each Query.

I will have about 10 tables on my site, all of them are completely identical, but I have to create ten duplicates, since they differ in Query.

Imagine if we created a new Listing Grid every time, just for the sake of introducing a new Query into it. But fortunately we do not do this, since we select the Query in the Listing Grid widget itself, which makes it reusable, unlike dynamic tables.

/*UA original*/
Привіт, розгляньте можливість вибору Query у віджеті таблиці https://prnt.sc/n7dVUd9663dK , а не в самій таблиці https://prnt.sc/8t-GbqZAuYhw , інакше доводиться створювати дублікати таблиць під кожен Query.

У мене на сайті буде близько 10 таблиць, усі вони абсолютно однакові, але я змушений створити десять дублікатів, оскільки вони відрізняються Query.

Уявіть якби ми створювали кожен раз новий Listing grid, тільки заради впровадження в нього нового Query. Але ми цього на щастя не робимо, так як Query вибираємо в самому віджеті Listing Grid, i робимо його багаторазовим, на відміну від динамічних таблиць.

**Comment by kaskad88** [comment]
@stasonua0 Привіт. Така можливість вже є, через опцію **Rewrite table query** https://tppr.me/4OUWM

**Comment by stasonua0** [comment]
Супер, велике спасибі!

**Comment by stasonua0** [comment]
> @stasonua0 Привіт. Така можливість вже є, через опцію **Rewrite table query** https://tppr.me/4OUWM

У новому проекті насолоджуюся цим доопрацюванням. Дякую!
