### ISSUE TITLE
JetBookings Error

### ISSUE THREAD

**Issue by BatLegion** [CrocoBlock/suggestions#6373]
Im getting this error on my website.

Fatal error: Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in
Followed by a large list of other issues.

Stack trace: #0 /usr/www/users/avondpybar/wp-content/plugins/jet-booking/includes/form-fields/check-in-out-render-trait.php(101): date('Y-m-d', '19-01-2023') #1 /usr/www/users/avondpybar/wp-content/plugins/jet-booking/includes/vendor/fields-core/smart-field-trait.php(31): JET_ABAF\Form_Fields\Check_In_Out_Render->field_template() #2 /usr/www/users/avondpybar/wp-includes/class-wp-hook.php(308): JET_ABAF\Form_Fields\Check_In_Out_Render->getFieldTemplate(NULL, Array, Object(Jet_Engine_Booking_Forms_Builder)) #3 /usr/www/users/avondpybar/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array) #4 /usr/www/users/avondpybar/wp-content/plugins/jet-engine/includes/modules/forms/builder.php(860): apply_filters('jet-engine/form...', NULL, Array, Object(Jet_Engine_Booking_Forms_Builder)) #5 /usr/www/users/avondpybar/wp-content/plugins/jet-engine/includes/modules/forms/builder.php(1485): Jet_Engine_Booking_Forms_Builder->render_field(Array) #6 /usr/www/users/avondpybar/wp-content/plugins/jet-engine/includes/modules/forms/builder.php(1610): Jet_Engine_Booking_Forms_Builder->render_row(Array) #7 /usr/www/users/avondpybar/wp-content/plugins/jet-engine/includes/modules/forms/render/booking-form.php(67): Jet_Engine_Booking_Forms_Builder->render_form(true) #8 /usr/www/users/avondpybar/wp-content/plugins/jet-engine/includes/components/listings/render/base.php(210): Jet_Engine\Forms\Render\Booking_Form->render() #9 /usr/www/users/avondpybar/wp-content/plugins/jet-engine/includes/modules/forms/widgets/booking-form.php(2554): Jet_Engine_Render_Base->render_content() #10 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/controls-stack.php(2268): Elementor\Jet_Engine_Booking_Form_Widget->render() #11 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack->render_by_mode() #12 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base->render_content() #13 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Widget_Base->print_content() #14 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element() #15 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content() #16 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/element-base.php(1354): Elementor\Element_Base->print_element() #17 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/base/element-base.php(449): Elementor\Element_Base->print_content() #18 /usr/www/users/avondpybar/wp-content/plugins/elementor/core/base/document.php(1669): Elementor\Element_Base->print_element() #19 /usr/www/users/avondpybar/wp-content/plugins/elementor/core/base/document.php(1095): Elementor\Core\Base\Document->print_elements(Array) #20 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/frontend.php(1153): Elementor\Core\Base\Document->print_elements_with_wrapper(Array) #21 /usr/www/users/avondpybar/wp-content/plugins/elementor/includes/frontend.php(1048): Elementor\Frontend->get_builder_content(15496) #22 /usr/www/users/avondpybar/wp-includes/class-wp-hook.php(308): Elementor\Frontend->apply_builder_in_content('

Please any assistance here would be helpful.

**Comment by UraraReika** [comment]
Hello @BatLegion! Thanks for the feedback.

Please follow guidelines for opening a new bug report https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md, so we can help you better. This report is missing key information like: Steps to reproduce, screenshots your setup. Without it - it is hard for us to filter and prioritize the requests.

Thank you for your understanding.
