### ISSUE TITLE
title Length for product title in cart Cart Table widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6375]
**Please, describe the feature request, making it clear to understand.**

Hi team.

Please add 3 options [Length, Line Wrap and Tooltip](https://prnt.sc/QNwX5samvGOa) as cart table widget products. Currently, if the product title in the cart table widget is long, we have no control over it.

![t](https://user-images.githubusercontent.com/88034902/211794451-db3fa0ae-d83c-48d7-bdff-fcd20ca76aaa.png)

**Comment by morosmo** [comment]
+1

**Comment by UraraReika** [comment]
Hello and thanks for the feedback.

Unfortunately this functionality will not be implemented to the core of our plugin. But you can use this code snippet in your `functions.php` file of child theme. This snippet will add trim and tooltip functionality.

```
add_filter( 'woocommerce_cart_item_name', function ( $title, $item, $item_key ) {

	$_product          = apply_filters( 'woocommerce_cart_item_product', $item['data'], $item, $item_key );
	$product_permalink = apply_filters( 'woocommerce_cart_item_permalink', $_product->is_visible() ? $_product->get_permalink( $item ) : '', $item, $item_key );

	$length = 3; // Words/signs length.
	$after  = '...'; // Sign after trim.

	// For word trim.
	$title = wp_trim_words( $title, $length, $after ); // use `wp_html_excerpt( $title, $length, $after )` for  trim.

	// Add tooltip.
	$title = '<span title="' . $_product->get_name() . '">' . $title . '</span>';

	if ( $product_permalink ) {
		$title = sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $title );
	}

	return $title;

}, 10, 3 );
```

If you want to add line wrap as well than just simply use this styles on title wrapper like this:
```
.product-name {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

Thank you for your understanding.
