### ISSUE TITLE
Suggestions for improving Custom Quantity Selector the plugin / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6377]
Hi crocoblock team.

I had two small requests for the Custom Quantity Selectors plugin. I hope you add them.

1- Transition Duration for Quantity Selector > hover mode

**(In general, it would be great if you add the Transition Duration option in all jet woobuilder widgets that have a hover section)**

2- Please add border and box shadow options to [this section](https://prnt.sc/VqWbp0DnnX2t) so that we can control these two in normal and hover modes.

3- I'm not sure if you run this. But it would be really great if when we change the number using the + - button, the number changes with a nice animation.
In this animation, when the number changes, it moves up and the next number is added from the bottom. Please see the following link.

https://codepen.io/Unleashed-Design/pen/wvGgzPO

**Comment by morosmo** [comment]
nice to have it :) +1

**Comment by UraraReika** [comment]
Hello @Michaelgimii!

1, 3 - Unfortunately, we do not plan to introduce such functionality into our plugin.
2 - done.

You can now find this changes in plugins git repo.
