### ISSUE TITLE
possible BUG in Custom Quantity Selector plugin / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6378]
**Describe the bug**

Hi

If we have a product that has, for example, 2 in stock, if the user clicks on the + button in the shopping cart, the number of the product will not exceed 2, but the shopping cart will be loaded using Ajax. As many times as the user clicks, the shopping cart will be loaded using Ajax.
While if we do not use the Custom Quantity Selector, if the user clicks on the top arrow, the number of products will not exceed 2 and the shopping cart will not be loaded in Ajax.

**To Reproduce**

1- Update your shopping cart product quantity Increase/decrease buttons using the Custom Quantity Selector plugin.
2- Add a product to cart that has 2 or n inventory.
3- In the shopping cart, click on the + button to increase the number of products.

If the inventory of the desired product is 2, by clicking the + button, the number of products will not exceed 2, but each time you click the + button, the shopping cart will be loaded in Ajax.

It is better that if the number of products does not increase, the shopping cart should not be loaded by Ajax with each user click. If you disable the Custom Quantity Selector plugin, if you increase the number of products, the number of products will not exceed 2. After that, if the user uses the arrow above to increase the number of products, the shopping cart will not be loaded as Ajax.

**Comment by Michaelgimii** [comment]
Hi @UraraReika , It looks like you mislabeled jet booking.

**Comment by UraraReika** [comment]
You can now find this changes in plugins git repo.
