### ISSUE TITLE
"Recently Viewed" Feature. Would be nice and It´s really common

### ISSUE THREAD

**Issue by eybel** [Crocoblock/suggestions#638]
I believe this is a must have feature. Users tend to loose track of what they found sometimes.

**Comment by Floydtm** [comment]
@eybel, Hi! Please specify for which plugin do you need it? Thanks you!

**Comment by eybel** [comment]
For JetElements that already has Sale Products, Featuerd products, Recent Products but it doenst have Recenlty Viewed Products this is a nice featured for sidebars. It helps users to remember which product  they looked at.

Thanks!

**Comment by kaskad88** [comment]
Recently Viewed Products widget is already available in the Elementor. http://prntscr.com/quy0jw
