### ISSUE TITLE
Add map_meta_cap -> true option when change a Post Type > Capability Type 

### ISSUE THREAD

**Issue by fagnerguima** [CrocoBlock/suggestions#6384]
When we create a post_type and choose a custom Capability Type, we need the map_meta_cap param can be set as true. This is important when do you need to use another plugin like Members ou User Role Editor to create a new Role and set all capabilities.

With map_meta_cap => false the post_type don't have all capabilities registered. 

https://justintadlock.com/archives/2010/07/10/meta-capabilities-for-custom-post-types

**Comment by kaskad88** [comment]
Added in JetEngine v3.1.4
