### ISSUE TITLE
[Feature Request] "Exists" and "Doesn't Exist" Operator in Conditional Logic for Metaboxes

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#6385]
Right now, you can show Meta Boxes to editors using Conditional Logic, but only two kinds: "Equal/Not Equal" and "In/Not in the List".

I'd like to have a conditional logic option for "Exists" the same what that it's used in Dynamic Visibility: if there is (or isn't) a value entered in the Field specified, then show the Meta Field to the editor.

Example 1:
A switcher field that states "Rentals Available". If it's set, then meta fields with options for rentals are shown to the editor.

Example 2:
A text field that states "Item price". If it is filled (that is, if there's a price), then show the meta field of "Rebate/Discount" to the editor.

**Comment by kaskad88** [comment]
It was implemented in JetEngine 3.2.0
