### ISSUE TITLE
Accordion widget doesn't respond well to quick clicks in a row

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#6387]
Currently if you click the accordion widget a lot in a row in a very short amount of time, the widget doesn't respond quite well. it recognized the clicks even if the effect for opening or closing is happening in that particular moment. so these clicks get summed up and will perform all. 

https://user-images.githubusercontent.com/119750572/212292301-4a20a7a0-8d19-4401-9be2-6576c79611db.mov

What lots of other websites do is to only respond for clicks if the opening or closing effect is done, no matter how often or quick you click at it. you also should implement that. it looks more professional. (so the widget is disabled for a click during the opening or closing state) - you cant see it an the video but i clicked at it very fast in a row, and it didn't break

https://user-images.githubusercontent.com/119750572/212292111-a74ad140-58c4-47ec-b3c2-da4dceec4dfe.mp4

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
