### ISSUE TITLE
JetElements - Vimeo Video Player - Missing GDPR Option - Please ADD!

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#6391]
vimeo offers this nice url parameter inside the iframe called **dnt** (do not track (https://vimeo.zendesk.com/hc/en-us/articles/360001494447-Player-parameters-overview where it says "dnt")) which is essential for users isnide the eu. it prevents viemo from loading cookies and analytics. but if you enter a vimeo url inside the player this parameter doesnt get rendered in the html. 

these two options allow us to setup do not track for vimeo videos
- ?dnt=1 or &dnt=1
- ?dnt=true or &dnt=true

please fix that if you put one of these versions manually in the vimeo url input, that is does get rendered, its very important due to privacy settings. (gdpr)

and it also would be nice if you could implement another toggle under **vimeo options** like "Do not track" wich also takes care of it by implementing this parameter in the final html of the site. This would be even more convenient and and solves the issue by entering the dnt parameter into every single one dynamic field if you have listings with dynamic vimeo videos (like testimonials). so we dont have to rely that the client puts the dnt parameter every time the right way.

Ah and by the way, i noticed another bug, currently the html title attribute for the video player widget in the vimeo mode is "vimeo Video Player". please change this to vimeo with an uppercase at the beginning like "**V**imeo Video Player"

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by Crocoblock** [comment]
released in JetElements 2.7.0
