### ISSUE TITLE
jetBooking conflicts with jetEngin Form Calculation

### ISSUE THREAD

**Issue by faisalbinali12** [CrocoBlock/suggestions#6392]
**Describe the bug**
JetBooking conflicts with JetEngin Form Calculation Field.
JetEngin Form or JetForm Builder has a checkin_checkout field from JetBooking.
Every time I try to use this field then, the calculated field won't work.

However, when I use the old version of JetBooking (around 2.5)
then it's working fine.

**Screenshots**

1 - With "Check-in/check-out" Field

![324736398_1830115090706285_5778178166759753440_n](https://user-images.githubusercontent.com/59834838/212487997-103933cd-1cb9-43ae-9ed2-4c1efb520aa0.jpg)

2 - "Check-in/check-out" Field

![324501465_755065996070646_6240578947047232248_n](https://user-images.githubusercontent.com/59834838/212488048-45c48f50-1a26-4db7-8fd5-a922ff0ea6c9.jpg)

3 - Without "Check-in/check-out" Field

![324440293_4217588841698428_7684403297350193735_n](https://user-images.githubusercontent.com/59834838/212488088-6dce6436-3f34-4e35-a3b4-6801fccf08b6.jpg)

**Comment by UraraReika** [comment]
Hello @faisalbinali12. Thanks for the feedback.

There were some issues with this functionality but in the last release of our plugin we fixed it. So please try to update ad check it one more time if not please contact our support team so we can check the issue on your side. https://support.crocoblock.com/support/home/ 

Thank you for your understanding.
