### ISSUE TITLE
UI improvement in cart table widget (in tablet and mobile mode) - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6395]
**Before adding a new feature request, please, make sure you’ve checked:**

Hi

Currently, there is a lot of empty space in cart table widget on mobile and tablet. Please see the image below.

![Screenshot_202301145_194530_Chrome](https://user-images.githubusercontent.com/77163248/212553377-42fe5e21-09fd-4b43-85ea-65b2985ee9f5.jpg)

It would be great in terms of UI if you could remove this white space. To solve this issue, just move the remove product button to the side of the product image in this widget (only in tablet and mobile mode) And delete the other empty space above it (where the remove product button is now).

The image below is what I am thinking of. I hope it can be done.

![Screenshot_202301145_194530_Chrome](https://user-images.githubusercontent.com/77163248/212553721-5779fd5c-d698-4048-9d0a-7073d725c4c4.jpg)

thank you

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5141, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
