### ISSUE TITLE
CCT repeater inside meta keys are not displayed

### ISSUE THREAD

**Issue by Hydra56g** [CrocoBlock/suggestions#6397]
Hi, im using your jetengine cct builder and your form builder module, I contact you to hope that someone can take my request quickly. 
I start converting my CPT into CCT And so I also converted the form so that it adapts to publish no longer a CPT but a CCT And I realize at the end of a big problem. The meta keys of repeater columns are not displayed in the list to associate the correct keys before publishing... 
**I took screenshots to illustrate all this.**

![Sans titre 2_20230115223203](https://user-images.githubusercontent.com/109702289/212569675-faa4627f-e503-4f18-8bd3-9b2656660998.png)
![Sans titre 3_20230115223644](https://user-images.githubusercontent.com/109702289/212569678-c6368eba-a65e-47c5-a6d4-c34829fb3293.png)
![Sans titre 5_20230115223853](https://user-images.githubusercontent.com/109702289/212569680-b57f6d15-19dc-410c-8bf5-84c8540f295b.png)

**the last photo illustrates the form when I want to publish a CPT, there it works.** 

I hope this can be resolved quickly because it creates a big problem for me. 
Thanks in advance 👍

**Comment by morosmo** [comment]
+1 Really need this to fix. I just soverted my 12 forms from jetengine forms to jetformbuilder. Everytime I need to map fields manually and also update some of the data in form actions.

**Comment by Floydtm** [comment]
You can do it right now. You need to configure the fields in the form like this https://tppr.me/bgBz2 in notifications, you need to specify the name of the repeater, and leave the fields empty https://tppr.me/yTJjY but keep in mind that the fields in the site and in the form itself must be named the same https://tppr.me/QKcSt Done. after sending the form, everything will be in place. let me know if this helped you. Thanks!

**Comment by Hydra56g** [comment]
> 

 I just tried your advice and indeed it works! Thank you so much , it is thanks to you that I will be able to continue my website.!
