### ISSUE TITLE
smooth auto play for jet woobuilder product grid/list and categories grid widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6398]
**Please, describe the feature request, making it clear to understand.**

smooth auto play is a great and useful feature that is currently missing in jet woobuilder. Using this feature, products are automatically and smoothly navigated. You can see exactly this feature on the website below.

https://codepen.io/osingh/pen/wOqrPX

Actually, we need two new options.

1- smooth autoplay
2- smooth autoplay Speed

thanks

**Comment by UraraReika** [comment]
Hello @Michaelgimii. Thanks for the feedback.

Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. For now you can achieve this functionality with the help of combining few options that we already have.

You should use autoplay delay in combination with speed and free mode option like this https://tppr.me/NTaFY. Please take o note that animation speed should be a little bit bigger than autoplay delay this is very important in case you won’t have some glitchy look. Than you although need to add some additional option to slider with the help of filter hook right in to your child theme:

```
add_filter( 'jet-woo-builder/tools/carousel/options', function( $options ) {
	$options['autoplay']['waitForTransition'] = false;

	return $options;
} );
```

Although this will not work with loop option.
