### ISSUE TITLE
JetEngine -> Jetlisting: Make Listing item clickable -> add option to open URL in NEW WINDOW

### ISSUE THREAD

**Issue by windkracht20-nl** [Crocoblock/suggestions#640]
Would be great if you could add the option to open the link for 'Make Listing item clickable' in a NEW window instead of current window only.

**Comment by kaskad88** [comment]
Added for the next version (2.2.0).
Thanks for your report!

**Comment by windkracht20-nl** [comment]
Great! ;-)

Met vriendelijke groet,
Bjørn Spruijt
 
windkracht20
Herwensedijk 20
6914 KE  Herwen
T:+31-316-540700



Op 12 dec. 2019, om 13:11 heeft Dmitriy Bartoshchak <notifications@github.com> het volgende geschreven:

**Comment by nod74** [comment]
Hello, was this feature added? I can´t find it.
