### ISSUE TITLE
improve Dynamic Bullets functionality / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6404]
Hi

The Dynamic Bullets feature in jet woobuilder is great. But there are two problems.

1- When we scroll the carousel, Dynamic Bullets change quickly and there are no transitios for it. This makes the UX suffer a lot. Please check [this link](https://swiperjs.com/demos#pagination-dynamic) and compare Dynamic Bullets here and jet woobuilder. Things are not good in jet woobuilder.
Actually, the problem is that there are no transitions in Dynamic Bullets jet woobuuilder. **The following code seems to solve the problem.** I have taken this code from the swiper js carousel whose link was posted above.

transition: .2s transform,.2s left;

2- If Dynamic Bullets are enabled in Jet woobuilder, when you reload the page, Dynamic Bullets will move around a lot. In the video below, pay attention to the moment when Dynamic Bullets are shown.

https://user-images.githubusercontent.com/88034902/212927499-8d589029-633e-40e3-a8ff-11af5a32bda3.mp4

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thanks for the feedback.

1 - Please take a closer look to our styles we have one that you mentioned. And i don't see the difference between your example and JetWooBuilder carousel.

2 - Fixed and will be in next release.

Thank you!

**Comment by Michaelgimii** [comment]
Hello @UraraReika 

1- We currently have an option for the speed of the carousel, but no option to control the speed of the navigation dots. That's why the navigation dots change so fast. Am I wrong?

**Comment by UraraReika** [comment]
> Hello @UraraReika
> 
> 1- We currently have an option for the speed of the carousel, but no option to control the speed of the navigation dots. That's why the navigation dots change so fast. Am I wrong?

There is no option to set navigation dots transition speed. And Swiper library doesn't present such an options. But you can use CSS to control this type of functionality.

**Comment by Michaelgimii** [comment]
> > Hello @UraraReika
> > 1- We currently have an option for the speed of the carousel, but no option to control the speed of the navigation dots. That's why the navigation dots change so fast. Am I wrong?
> 
> There is no option to set navigation dots transition speed. And Swiper library doesn't present such an options. But you can use CSS to control this type of functionality.

Maybe this issue has been fixed in the serious versions of swiper js. But in general, what we see in the swiper js demo, the speed of moving Dynamic Bullets is equal to the carousel speed animation. But in jet woobuilder, even if we set the carousel animation speed to 3000, Dynamic Bullets still change fast.

**Comment by UraraReika** [comment]
> > > Hello @UraraReika
> > > 1- We currently have an option for the speed of the carousel, but no option to control the speed of the navigation dots. That's why the navigation dots change so fast. Am I wrong?
> > 
> > 
> > There is no option to set navigation dots transition speed. And Swiper library doesn't present such an options. But you can use CSS to control this type of functionality.
> 
> Maybe this issue has been fixed in the serious versions of swiper js. But in general, what we see in the swiper js demo, the speed of moving Dynamic Bullets is equal to the carousel speed animation. But in jet woobuilder, even if we set the carousel animation speed to 3000, Dynamic Bullets still change fast.

Default speed parameter for Swiper slider is 300 ms in JetWooBuilder default speed is 500 for more smooth transition. Transition for bullets changes equal to .2s witch is 200ms so with default Swiper slider parameter it seems like speed is the same or almost the same.

And one more time speed parameter doesn't effect bullets transition.

**Comment by Michaelgimii** [comment]
> > > > Hello @UraraReika
> > > > 1- We currently have an option for the speed of the carousel, but no option to control the speed of the navigation dots. That's why the navigation dots change so fast. Am I wrong?
> > > 
> > > 
> > > There is no option to set navigation dots transition speed. And Swiper library doesn't present such an options. But you can use CSS to control this type of functionality.
> > 
> > 
> > Maybe this issue has been fixed in the serious versions of swiper js. But in general, what we see in the swiper js demo, the speed of moving Dynamic Bullets is equal to the carousel speed animation. But in jet woobuilder, even if we set the carousel animation speed to 3000, Dynamic Bullets still change fast.
> 
> Default speed parameter for Swiper slider is 300 ms in JetWooBuilder default speed is 500 for more smooth transition. Transition for bullets changes equal to .2s witch is 200ms so with default Swiper slider parameter it seems like speed is the same or almost the same.
> 
> And one more time speed parameter doesn't effect bullets transition.

I have no knowledge of coding and therefore I do not understand your words well. But I still say that in jet woobuilder, when Dynamic Bullets is turned off, the default navigation points have transitions. But if we activate Dynamic Bullets, these points have no transitions. Therefore, after adding the following code, the problem was solved.

.elementor-49 .elementor-element.elementor-element-6383808 .jet-woo-carousel .swiper-pagination .swiper-pagination-bullet{
    transition: all 300ms;
}

**Comment by Joliamendi** [comment]
Hi @UraraReika 
I agree with Michael. By default, navigation points have a transition duration. When we navigate the carousel, the navigation points move well and there is no problem. But when we activate Dynamic Bullets, the navigation points move quickly. so that there are no transition durations for it. If you check before and after activating Dynamic Bullets, the difference is quite obvious.
