### ISSUE TITLE
free mode bug (With scrolling, it returns to the original location) - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6405]
**Describe the bug**

Hi

If the free mode feature is active, there is a problem. The problem is that if we scroll the carousel, after scrolling the page, the carousel returns to its original position. For the free mode feature, this is a fatal event.

**To Reproduce**

1- Add multiple product carousels (product Grid widget) on your website.
2- Be sure to enable the freemode feature for all carousels.
3- Scroll through one of the carousels and then stop. Remember where free mode left off.
4- If you scroll the page after that, the free mode will be reset in the carousel of the previous step.

**Please watch the video below :**

https://user-images.githubusercontent.com/77163248/212938634-ec6f6a91-b43f-4e1c-9ce7-6a5c68fa9267.mp4

I am experiencing this bug on Android - Chrome browser. I have not tested other browsers such as Safari.

**Active plugins :**

elementor - elementor pro - woocommerce - jet woobuilder

**theme**

Hello elementor

**Comment by UraraReika** [comment]
Hello @79ho3ein! Thanks for the feedback.

We have tested this issue in different setups and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. https://support.crocoblock.com/support/home/ 

Thank you!

**Comment by 79ho3ein** [comment]
thank you
