### ISSUE TITLE
Allow conditional templates for Jet Woo Builder - Single Product Template

### ISSUE THREAD

**Issue by joelcrump** [CrocoBlock/suggestions#6409]
Currently it's only possible to set one single product template in the Woo Page Builder options, I've never had a website that required only one product template. Specially sites that use Jet Engine meta fields, it makes sense to have conditional Product templates, conditional by product categories and tags, and possibly meta fields.
**Add an example of where this feature is already implemented. **
Elementor - but Jet Woo Builder overrides the Elementor template settings.

Maybe an alternative is to just allow Elementor single product templates to override Jet Woo Builder templates if the conditional rules apply. Or add conditional rules to Woo Page Builder

Thanks sorry if this is already in the works, I couldn't find it in the roadmap

**Comment by Floydtm** [comment]
Hi, with woo page builder you can make different units for the product. In the settings, you specify the main template for all products. If you need to apply another template to the product, you can do it on the product page https://tppr.me/ZSeVU

**Comment by joelcrump** [comment]
Ah thanks Floyd, I asked a support member Nikita, and he said there was
only one single product template possible! Thanks for this. Sorry for
suggesting something that's already possible. Although rules would be great
as it would save a lot of work on large inventory sites.
Thanks again for the quick reply

*Joel Crump *

<https://www.webbros.co.nz>

*Please don't send us any account logins or credit card details via email. *If
you send us any logins or passwords via email*,* please reset your password
after we've used it to safeguard your account if either one of us got
compromised. We recommend using a service like https://privnote.com/
<https://privnote.com/>or something similar when sending sensitive
information.

**Comment by UraraReika** [comment]
Hello @webbrosdigital! 

You can although use JetWooBuilder in combination with JetThemeCore and in this case you will be able to set conditions.
