### ISSUE TITLE
JetWooBuilder don't work with Lazy Load

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#641]
**Describe the bug**
Using the Product Thumbnail Effect feature with LazyLoad (anyone) optimization feature, photos load one below the other. 

**To Reproduce**
When LazyLoad is active the Product Thumb Effect does not work correctly: https://youtu.be/icv6iohGHUA I used WP Rocket's LazyLoad as an example, but any Lazy Load gives this problem.

**Screenshots**
https://youtu.be/icv6iohGHUA

**Comment by UraraReika** [comment]
Done. Next Release.

**Comment by marcofrasson** [comment]
Hi, Product Thumbnail Effect with a3 Lazy Load dont work after update fix - https://wordpress.org/plugins/a3-lazy-load/

**Comment by UraraReika** [comment]
a3 Lazy Load plugin doesn`t  support parameters which we added to fix this issue. But you can use it's settings to disable lazy load on image that you need, like that https://prnt.sc/q5wxfg.

**Comment by MikeKoulouras** [comment]
The issue remains. Any news on that?

**Comment by bdong7761** [comment]
2025 still not resolved
