### ISSUE TITLE
bug in JetWooBuilder Custom Quantity Selector - single product

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6411]
Hi team.

There seems to be an annoying bug in the Custom Quantity Selector. The problem is that the width of the number field interferes with the width of the + - buttons. If we set the width of the number field and then change the width of the +- buttons, the width of the +- buttons will also change the width of the number field. Please watch the video below.

https://user-images.githubusercontent.com/88034902/213452544-e43bf542-513a-466d-a23b-f010ac79e200.mp4

It would be really great if the width changes of these two parts don't affect each other. As you can see in the video above, when I increased the Buttons Width, the width of the number field decreased.

**Comment by UraraReika** [comment]
Unfortunately this behaviour will stay. With this option  https://tppr.me/NP7ju we control not the width of quantity input but the width of the area in which quantity input exist. And we add custom quantity controls to the same area and with the help of this option - https://tppr.me/E2gAI we control percentage of the field width to the controls. That is why you can see this behaviour but this is the most optimal way to do this.
