### ISSUE TITLE
hover color for border in custom Quantity Selector / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6414]
Hello

In the custom Quantity Selector plugin, in the style section, we have control over three color options, background color and box shadow in normal and hover mode. https://prnt.sc/cpb1Ve9JmFsK

But we have no control over the [border color](https://prnt.sc/b-5oSU-K7-YE) in normal and floating mode. This is a very useful feature. So great if you add it. thanks

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thanks for the feedback.
You need to set border before select colours like this - https://tppr.me/e4SHc after this you will be able to see hover color in appropriate tab https://tppr.me/e4SHc.
