### ISSUE TITLE
Feature Request: Open posts in a modal

### ISSUE THREAD

**Issue by MastodontMedia** [CrocoBlock/suggestions#6415]
I would really like an option to open posts/ products in a modal instead of navigating to the actual page.

**Comment by Floydtm** [comment]
Сurrently you can do this with jet plugins. Contact our support team and they will help you with this issue.

**Comment by MastodontMedia** [comment]
Are you sure?
I spoke to your support just before i posted this and they said it was not possible.

**Comment by Floydtm** [comment]
I don't know what you need in detail, but it seems your question has been resolved. Thank you!
