### ISSUE TITLE
[JetEngine] Bricks - Listing Grid Warning in Editor

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#6417]
Bricks: 1.6.2
JetEngine: 3.1.0

When I want to display a Listing Item with the Listing Grid, the following message appears in the Bricks Editor after I refresh the Bricks Editor.

`Warning: Undefined array key "popup" in ...\Local Sites\bricks-energy\app\public\wp-content\themes\bricks\includes\assets.php on line 401`

![grafik](https://user-images.githubusercontent.com/54399588/213860785-9d493909-1463-45df-a5c6-e66dffd70d33.png)

But in the FrontEnd everything is displayed correctly without any message.

I do not use pop ups. At first I thought it might be related to the fact that I also use the query loop from Bricks on this page.
But also on a blank pages came this warning

If only the listing grid is inserted without selecting a listing the message will disappear. So it must have something to do with the listing.
In the Bricks settings I have selected that the post type Listing Items can be edited with the Bricks Editor.

Maybe someone else still has the problem

**Comment by FirstSunnyPhantom** [comment]
JetEngine: 3.1.0 - вже був встановлена
Bricks: 1.6.2 - оновив до цієїж версії
Bricks settings -> Post type -> Listing Items - також checked у мене

І різні лістінги використовуються на сторінках.
Але таких помилок не має у мене.

Тому не знаю навіть, як це фіксити.
Можливо хтось ще перевіряв наявність цієї помилки?

**Comment by RagnarLodbrok94** [comment]
JetEngine: 3.1.0 - was already installed
Bricks: 1.6.2 - updated to the same version
Bricks settings -> Post type -> Listing Items - also checked for me

And different listings are used on the pages.
But I don't have such mistakes.

Therefore, I don't even know how to fix it.
Maybe someone else checked for this error?
