### ISSUE TITLE
Vertical alignment for the Quantity title in the cart table widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6418]
**Please, describe the feature request, making it clear to understand.**

Hi team

On mobile and tablet, the Quantity title is not in the center. https://prnt.sc/p5ZYOm-0dMFG
This issue causes a lot of damage to the ui in tablets and mobiles.
So it would be great if you add a vertical alignment option **for the Quantity option** in [this section](https://prnt.sc/AI5l3NsePOdX). This option will only be useful for tablet and mobile. thanks

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thanks for the feedback.

I must mention that none of the titles in this view is centred. It just how basic styles of theme you use and plugins works. You can check it with increasing some font styles for example in other elements. And we will not provide this type of controls now or in the future.

You can use this styles to fulfil your needs:

```
selector .product-quantity {
    position: relative;
}

selector .product-quantity::before {
    position: absolute;
    top: 50%;
    left: 12px;
    transform: translateY(-50%);
}
```

Thank you for your understanding.
