### ISSUE TITLE
Custom Quantity Selector display problem after page reload in jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6421]
**Please, describe the feature request, making it clear to understand.**

Hi

I use Quantity Selector on product and cart page. But there seems to be a problem. The Custom Quantity Selector is displayed with a delay when the page loads. At first it will be displayed [like this](https://prnt.sc/TPfsojgZlpbM) and after 2 seconds the +- buttons will be displayed.
But if you view this position in Woodmart template, there is no problem and +- buttons are displayed without any delay. Please watch the video below. In the video below I reloaded the screen 2 times but the + - buttons never show with a delay.

https://user-images.githubusercontent.com/88034902/213915149-3e0a274e-b6e3-434e-a637-32fe7156e09f.mp4

**Comment by UraraReika** [comment]
Unfortunately in this case custom add-on has different approach on adding custom quantity selectors, js based that is why first of all page loaded and only then scripts. This behaviour cause this issue. In this case this is the most optimal way to handle this functionality without additional template rewrite^ maybe in the future this will be changed.

Thank you for understanding !
