### ISSUE TITLE
time offer for sale products in jet woobuilder 

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6422]
**Please, describe the feature request, making it clear to understand.**

Hi team.

According to crocoblock website, can we display sales timer for products in jet woobuilder? https://prnt.sc/CIH2GKR4kKW-

If not, would this be possible using the Elementor [countdown widget](https://prnt.sc/LvGHy5jzLnur)?

Thanks in advance

**Comment by Floydtm** [comment]
What you see on our website is a custom solution made using the Countdown timer widget. You can also implement a similar solution on your website. Thank you!

**Comment by Joliamendi** [comment]
Hi @Floydtm, thanks for the reply.

Can you tell how we can implement it using countdown widget? please

**Comment by Floydtm** [comment]
Check this setting in the widget https://tppr.me/aDfpO Or choose a custom date https://tppr.me/t3MLn
