### ISSUE TITLE
Unable to fetch image in Lisitng item in Buicks Builder

### ISSUE THREAD

**Issue by rentaterry** [CrocoBlock/suggestions#6423]
**Describe the bug**
When using Buicks Builder for Listing Grid item building, no image could be found as image shown below:
[https://i.imgur.com/QUWATcX.png](https://i.imgur.com/QUWATcX.png)
It could be done by using jetengine Dynamic Image however, lack of "Image Fit" setting resulting layout problem. 

It worked normally in CPT Single:
[https://i.imgur.com/QUWATcX.png](https://i.imgur.com/QUWATcX.png)

It would be great if both issues could be fixed. Thank you.

**Comment by hb81010** [comment]
I also have the same issue with the featured image in Bricks withe the Listing Grid and also use the workaround with the "Dynamic Image" element

**Comment by rentaterry** [comment]
> I also have the same issue with the featured image in Bricks withe the Listing Grid and also use the workaround with the "Dynamic Image" element

Yep. Also, most of styles edited in Listing are missing in Listing Grid.

**Comment by RagnarLodbrok94** [comment]
Hi.

1. "It could be done by using jetengine Dynamic Image however, lack of "Image Fit" setting resulting layout problem."

In Dynamic field has control for image fit.
https://prnt.sc/j4LmGTfBaQfS

2. "When using Buicks Builder for Listing Grid item building, no image could be found as image shown below:"

Planned for 3.1.3 update
