### ISSUE TITLE
[JetSmartFilters] - Filter-Support of Bricks Query Loop (Template)

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#6424]
I am glad that SmartFilters is now available for Bricks. Here is a suggestion for possible feature request

I have to partly create my listings with the Query Loop Template because some elements like Off-Canvas and Modal currently don't work in the JetEngine Listing Template.

It would be great if Smart Filter would also support the Bricks Query Loop in the future. E.g. similar to Elementor, where you also have a lot of choices

**Comment by MjHead** [comment]
Already in progress. Planned for JetSmartFilters 3.1.0
