### ISSUE TITLE
[JetEngine & Bricks Builder] String Length missing in Dtnamic field

### ISSUE THREAD

**Issue by rentaterry** [CrocoBlock/suggestions#6425]
Hi there,

"String Length" can not be found in Dynamic Field widget in Bricks Builder which is in elementor
<img width="241" alt="螢幕擷取畫面 2023-01-23 090717" src="https://user-images.githubusercontent.com/75129305/213950840-8572c8b1-46e4-4939-b1c5-de299596a54b.png">

Please add the feature to Bricks Builder. Thank you!

**Comment by RagnarLodbrok94** [comment]
Hi.

This callback is not included in the default Dynamic field callbacks.

So you need to download it from this link - https://github.com/Crocoblock/jet-engine-trim-callback.

Result - https://prnt.sc/EZs7EfBV9W3l

You can find other additional callbacks in Crocoblock DevTools.
https://crocoblock.com/freemium/tools/

**Comment by rentaterry** [comment]
> Hi.
> 
> This callback is not included in the default Dynamic field callbacks.
> 
> So you need to download it from this link - https://github.com/Crocoblock/jet-engine-trim-callback.
> 
> Result - https://prnt.sc/EZs7EfBV9W3l
> 
> You can find other additional callbacks in Crocoblock DevTools. https://crocoblock.com/freemium/tools/

Thanks for the reply. I forgot the freemium page as it worked perfectly.
