### ISSUE TITLE
Not being able to scroll through product gallery in lightbox view

### ISSUE THREAD

**Issue by janderup** [CrocoBlock/suggestions#6426]
**Describe the bug**
I am using the JetProductGallery Gallery Slider widget on my website. When you visit the web page, you can scroll through the product gallery. But when you click on the image for the lightbox view, you can no longer scroll to the next or the previous image. You then have to close the lightbox view to scroll to another image.

**To Reproduce**
1. Add the Gallery Slider widget to your web page.
2. Add multiple images to them.
3. Click on the image for lightbox view.
4. Try to slide to the next image (you can't).

**Expected behavior**
I would have expected it to be possible to slide through the product gallery in lightbox view.

**Desktop:**
 - Windows 10 
 - Browser: Google Chrome (Version 109.0.5414.75)
 - JetProductGallery (version 2.1.9)

**Comment by UraraReika** [comment]
Hello @janderup! Thanks for the feedback.

Maybe you have this option enable https://tppr.me/xhVRg, please disable it and everything should work fine.

Thank you!
