### ISSUE TITLE
JetBlog Smart Post List widget Query & Control

### ISSUE THREAD

**Issue by Pixemotion** [CrocoBlock/suggestions#6433]
**Describe the bug**
I'm using the Smart Post List widget to show custom posts created with JetEngine.
I have created a Query with the Query builder that I want to use with the widget. The custom query is set to display only 2 categories of my custom posts. I have set the widget to display filters by terms so it will show the 2 categories above the listing.
The issue is that the listing displays posts from the 2 categories I've set in the custom Query, but in the filters it shows all categories instead of just the 2 I've set.

**To Reproduce**

**Expected behavior**
Filter by terms should be "synchronized" with the custom query. If 2 categories of my custom post are set in my custom query, then filters should display 2 categories as well and not all categories. 

**Screenshots**
![cap1](https://user-images.githubusercontent.com/8656509/214612678-050413f0-d682-4a86-b342-2b1f7359126a.jpg)

**Desktop (please complete the following information):**
 - OS: OSX 
 - All browsers
 - latest

**Additional context**

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-blog/tree/fix/issue%232266
