### ISSUE TITLE
JetBooking: Add Option for Checkin Dates & Times

### ISSUE THREAD

**Issue by dalexdesigngroup** [CrocoBlock/suggestions#6434]
We are so close to finishing our project, however, our service requires a check-in Date & Time and Check-out Date & Time.

The current booking form can only accept bookings by the day, however, adding this as an option expands the usability of the booking form to allow the user to only book a location that is open during the selected time. This is useful for rental-based bookings, and time-based bookings, who need to easily access not only check-in dates but arrival times etc. 

Allowing this option would be great:
<img width="426" alt="Screen Shot 2023-01-25 at 9 42 18 PM" src="https://user-images.githubusercontent.com/84207663/214754138-3548d3e6-0f2a-48bd-8c96-fc1cde4f1c99.png">

This is a variation of the same booking form ( www.usebounce.com )
<img width="414" alt="Screen Shot 2023-01-25 at 9 44 55 PM" src="https://user-images.githubusercontent.com/84207663/214754360-7f4d0b8b-7fb5-4a4d-9144-e6b1f421a1d4.png">

**Comment by dalexdesigngroup** [comment]
Seems like the most basic way to start this feature would be Adding a new option here for MM.DD.YY HH:MM a or something more robust. 
<img width="265" alt="Screen Shot 2023-01-25 at 9 50 25 PM" src="https://user-images.githubusercontent.com/84207663/214754929-e2432009-fd41-4523-b7f3-18c9d6b6ab24.png">

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1597, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.

**Comment by Qubadi** [comment]
+1

**Comment by Qubadi** [comment]
I completely agree with **dalexdesigngroup**, we are also creating a website for a client. We also do not have the option to add pick up time and drop off time, only dates. So when a customer orders a car, the customer does not know when he/she will pick up the car. All cars in the world have both date and time, that goes without saying. If you had ordered a car, how can you know when the car is ready for collection? The person who created Jetbooking seems like he has never booked a car online, otherwise he would have shown this and entered the time too.

**Comment by maliktanveerdhool** [comment]
> We are so close to finishing our project, however, our service requires a check-in Date & Time and Check-out Date & Time.
> 
> The current booking form can only accept bookings by the day, however, adding this as an option expands the usability of the booking form to allow the user to only book a location that is open during the selected time. This is useful for rental-based bookings, and time-based bookings, who need to easily access not only check-in dates but arrival times etc. 
> 
> Allowing this option would be great:
> <img width="426" alt="Screen Shot 2023-01-25 at 9 42 18 PM" src="https://user-images.githubusercontent.com/84207663/214754138-3548d3e6-0f2a-48bd-8c96-fc1cde4f1c99.png">
> 
> This is a variation of the same booking form ( www.usebounce.com )
> <img width="414" alt="Screen Shot 2023-01-25 at 9 44 55 PM" src="https://user-images.githubusercontent.com/84207663/214754360-7f4d0b8b-7fb5-4a4d-9144-e6b1f421a1d4.png">
> 
> 

Hi did you get any solution using jet booking?

**Comment by UraraReika** [comment]
> > We are so close to finishing our project, however, our service requires a check-in Date & Time and Check-out Date & Time.
> > The current booking form can only accept bookings by the day, however, adding this as an option expands the usability of the booking form to allow the user to only book a location that is open during the selected time. This is useful for rental-based bookings, and time-based bookings, who need to easily access not only check-in dates but arrival times etc.
> > Allowing this option would be great:
> > <img alt="Screen Shot 2023-01-25 at 9 42 18 PM" width="426" src="https://user-images.githubusercontent.com/84207663/214754138-3548d3e6-0f2a-48bd-8c96-fc1cde4f1c99.png">
> > This is a variation of the same booking form ( [www.usebounce.com](http://www.usebounce.com) )
> > <img alt="Screen Shot 2023-01-25 at 9 44 55 PM" width="414" src="https://user-images.githubusercontent.com/84207663/214754360-7f4d0b8b-7fb5-4a4d-9144-e6b1f421a1d4.png">
> 
> Hi did you get any solution using jet booking?

We currently working on it

**Comment by maliktanveerdhool** [comment]
hi thanks, do you have any idea when you can launch this hourly update?
