### ISSUE TITLE
JetEngine - Query Builder - SQL QUERY and Calculated Column with custom function: error creating query only on front-end

### ISSUE THREAD

**Issue by w3b-beweb** [CrocoBlock/suggestions#6435]
**Describe the bug**
I'm building a custom query of type SQL QUERY; my target is to retrieve a date meta field (saved in DB as timestamp) of a custom post type, and format the date. The results will then be used in a hidden elementor form field, to use the formatted date in the form email body. 
To format the date field I'm using "Calculated columns" feature, "Custom" as calculate function and then FROM_UNIXTIME mysql function. It works perfectly in the query builder as shown by query preview (see screenshot #1 below), 

but on frontend the query is missing a comma "," in the SELECT statement, causing a php fatal error (see also screenshot #2 below):

"_WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(meta_value, '%d\\/%m\\/%Y') AS 'custom(meta_value)' FROM cs_postmeta AS postmeta ' at line 1 for query **SELECT custom(meta_value) FROM_UNIXTIME (meta_value, '%d\\/%m\\/%Y')** AS 'custom(meta_value)' FROM cs_postmeta AS postmeta  WHERE post_id = '22562' AND meta_key = 'course-date' LIMIT 1;_"

**To Reproduce**
1. Go to JetEngine -> Query Builder
2. Create a "SQL QUERY" with calculated columns and  custm calculate function, like in the screenshot #3 below:

3. Use it on frontend as a dynamic value 
4. See error in the log

**Expected behavior**
A syntatically working query on the frontend also, as in the query preview in the backend

**Screenshots**
1. 
![immagine](https://user-images.githubusercontent.com/306774/214792898-b537b869-cdc5-47f6-990e-6f0672fb6a79.png)
2.
![immagine](https://user-images.githubusercontent.com/306774/214797227-47b18575-015e-4a62-aba1-8d81163161a7.png)
3.
![immagine](https://user-images.githubusercontent.com/306774/214794770-39b5d297-b763-4d26-bf6c-8bbba80bb1a6.png)

**Desktop**
 - OS: Windows 11
 - Browser: Firefox, chrome, edge, opera
 - Version: n/a

**Additional context**
Wordpress: 6.1.1
Elementor: 3.10.1
Elementor Pro: 3.10.2
JetEngine: 3.1.0

**Comment by kaskad88** [comment]
Hello @w3b-beweb 
I tried to reproduce your steps and looks like all works fine https://tppr.me/jTgJs

Could you please attach a screen or describe more details how you output sql value on front-end

**Comment by w3b-beweb** [comment]
Hello @kaskad88
I'm using the query as value of a hidden field in an elementor pro form:

![immagine](https://user-images.githubusercontent.com/306774/217306290-3ce29a02-a011-41ab-af35-e5b3b879c9bc.png)

"CORSI: Data di sovlgimento formattata" is the name of the query you can see in my opening message above.
When I go to the page whit that form, the hidden field has no value, and my debug log contains this:

`[07-Feb-2023 16:34:52 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(meta_value, '%d\/%m\/%Y') AS 'custom(meta_value)' FROM xx_postmeta AS postmeta ' at line 1 for query SELECT custom(meta_value) FROM_UNIXTIME (meta_value, '%d\/%m\/%Y') AS 'custom(meta_value)' FROM xx_postmeta AS postmeta  WHERE post_id = '22798' AND meta_key = 'course-date' LIMIT 1; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/elementor/modules/page-templates/templates/canvas.php'), Elementor\Modules\PageTemplates\Module->print_content, call_user_func, ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->ElementorPro\Modules\ThemeBuilder\Classes\{closure}, ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->do_location, ElementorPro\Modules\ThemeBuilder\Documents\Single_Base->print_content, ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_content, ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->get_content, Elementor\Modules\Library\Documents\Library_Document->get_content, Elementor\Core\Base\Document->get_content, Elementor\Frontend->get_builder_content, ElementorPro\Modules\ThemeBuilder\Documents\Theme_Document->print_elements_with_wrapper, Elementor\Core\Base\Document->print_elements, Elementor\Element_Base->print_element, Elementor\Element_Base->print_content, Elementor\Element_Base->print_element, Elementor\Element_Base->print_content, Elementor\Element_Base->print_element, Elementor\Widget_Base->print_content, Elementor\Widget_Base->render_content, Elementor\Controls_Stack->render_by_mode, ElementorPro\Modules\Forms\Widgets\Form->render, Elementor\Controls_Stack->get_settings_for_display, Elementor\Controls_Stack->get_parsed_dynamic_settings, Elementor\Controls_Stack->parse_dynamic_settings, Elementor\Controls_Stack->parse_dynamic_settings, Elementor\Base_Data_Control->parse_tags, Elementor\Core\DynamicTags\Manager->parse_tags_text, preg_replace_callback, Elementor\Core\DynamicTags\Manager->Elementor\Core\DynamicTags\{closure}, Elementor\Core\DynamicTags\Manager->parse_tag_text, call_user_func_array, Elementor\Core\DynamicTags\Manager->get_tag_data_content, Elementor\Core\DynamicTags\Tag->get_content, Jet_Engine_Dynamic_Function_Tag->render, Jet_Engine_Dynamic_Functions->call_function, Jet_Engine_Dynamic_Functions->get_query_var, Jet_Engine\Query_Builder\Queries\SQL_Query->get_var, W3TC\DbCache_WpdbNew->query, W3TC\DbCache_WpdbInjection_QueryCaching->query, W3TC\_CallUnderlying->query, W3TC\DbCache_WpdbNew->query, W3TC\DbCache_WpdbInjection->query, W3TC\DbCache_WpdbNew->default_query`

**Comment by kaskad88** [comment]
@w3b-beweb 
In your case, the Dynamic Functions tag is not appropriate.

**Solution for your case:**

1) Add the following code to the `functions.php` file of your `child theme`:
```
add_shortcode( 'my_custom_sql_column_value', function() {

	$query_id = 38; // need replace query id
	$column   = 'custom(meta_value)';

	$query  = Jet_Engine\Query_Builder\Manager::instance()->get_query_by_id( $query_id );
	$items  = $query->get_items();
	$result = null;

	if ( ! empty( $items ) && isset( $items[0] ) && isset( $items[0]->$column ) ) {
		$result = $items[0]->$column;
	}

	return $result;
} );
```
2) Change the `$query_id` variable value https://tppr.me/JDllb on your query id from url https://tppr.me/P3tUx
3) Choose the `Shortcode` dynamic tag for `Default Value ` and paste shortcode `[my_custom_sql_column_value]` https://tppr.me/yMo8j

**Comment by w3b-beweb** [comment]
ok, thanks!

**Comment by ikhwanbreaks** [comment]
> @w3b-beweb In your case, the Dynamic Functions tag is not appropriate.
> 
> **Solution for your case:**
> 
> 1. Add the following code to the `functions.php` file of your `child theme`:
> 
> ```
> add_shortcode( 'my_custom_sql_column_value', function() {
> 
> 	$query_id = 38; // need replace query id
> 	$column   = 'custom(meta_value)';
> 
> 	$query  = Jet_Engine\Query_Builder\Manager::instance()->get_query_by_id( $query_id );
> 	$items  = $query->get_items();
> 	$result = null;
> 
> 	if ( ! empty( $items ) && isset( $items[0] ) && isset( $items[0]->$column ) ) {
> 		$result = $items[0]->$column;
> 	}
> 
> 	return $result;
> } );
> ```
> 
> 2. Change the `$query_id` variable value https://tppr.me/JDllb on your query id from url https://tppr.me/P3tUx
> 3. Choose the `Shortcode` dynamic tag for `Default Value ` and paste shortcode `[my_custom_sql_column_value]` https://tppr.me/yMo8j

I am very grateful for the code you shared.

But I have a problem, because I want to add a shortcode for the value directly from the Query Result Count, without the other frills used for Dynamic Visibility.

Thank you, if you are willing to share the code.
