### ISSUE TITLE
JetSmartFilters | Range Filter Indexer Options

### ISSUE THREAD

**Issue by LTimerr** [CrocoBlock/suggestions#6440]
Good day, it would be very good if the range filter could also have the possibility to set the indexer options exactly the same as all the other filters.

Thanks for reading.
![Screenshot_1](https://user-images.githubusercontent.com/93724776/215103467-96d7495b-826b-4ec0-9974-9ee31d0f7acb.png)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by liiakerosene** [comment]
https://app.intercom.com/a/inbox/rn7ho5ox/inbox/admin/4628518/conversation/133270500249057#part_id=comment-133270500249057-21895623362
