### ISSUE TITLE
Add the full functionality of multi-step checkout in jet woobuilder.

### ISSUE THREAD

**Issue by syed-majid-akhtar** [CrocoBlock/suggestions#6445]

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by UraraReika** [comment]
I merged this issue with [#4415](https://github.com/Crocoblock/suggestions/issues/4415), which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
