### ISSUE TITLE
JetEngine - QueryBuilder Shortcodes

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#6446]
Hello, everyone, I really like using custom functions and returning values in shortcodes, I use them to facilitate the return of a very specific value and apply it in the listings grid settings.

I really like using Posts Query because of this benefit that exists, but as it is being legacy I am prioritizing using QueryBuilder for other things when it is not necessary.

But sometimes we need to fetch information with a custom function, and compare this value within a filter, but using shortcodes in QueryBuilder is not yet available.

Here is my suggestion, I believe that the power of uniting the querybuilder + shortcodes will open new paths for those who already use custom functions.

Thank you, I'm very pleased with the big updates coming to JetEngine and other Crocoblock plugins.

![image](https://user-images.githubusercontent.com/6773491/215382561-71d6e452-5914-463f-8946-521fb46a5044.png)

![image](https://user-images.githubusercontent.com/6773491/215382652-bf4bf116-307d-45f7-a201-ead497ce8228.png)

**Comment by morosmo** [comment]
+1

**Comment by dyonatandias** [comment]
++1

**Comment by DaviAppelDuarte** [comment]
+1

**Comment by marreiradigital** [comment]
I find myself using the old Query post because QueryBuilder still doesn't accept shortcode! The great @Crocoblock , add the shortcode in the QueryBuilder.

To understand the context, I left a link to a video lesson that shows why..

https://youtu.be/M2UYR-2GX1k?t=869
14:28

**Comment by DudeDude95** [comment]
+1 Query Builder to accept shortcodes.

Here is my use case (https://github.com/Crocoblock/suggestions/issues/6461)

A shortcode would allow me to solve my issue in the interim until "current month" macro is introduced.

**Comment by tizum** [comment]
@MjHead Do you have anything planned for this feature?

**Comment by MjHead** [comment]
Added Shortcode Result macro. Will be released with 3.1.4 update
