### ISSUE TITLE
Icon List widget with dynamic options

### ISSUE THREAD

**Issue by EliKO109** [CrocoBlock/suggestions#6447]
I would love to see an icon list widget by CB that would be able to get dynamic options like the tabs/accordion/price list.
I can think of many ways to use it with a repeater field or even taxonomies or posts.
here are 2 examples for the use case:
- a repeater field that shows bullets (like features or services) and you want to show it as a list with a static icon
- show categories of a CPT as a list

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
