### ISSUE TITLE
JetProductGallery Slider widget bug

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#645]
**Describe the bug**
I have a problem with the JetProductGallery Slider widget ... the first photo does not zoom correctly. The zoom of the first photo is the crop version. Other photos are zoomed in normally. See this link: https://goflow.digital/clientes/masate/aliancas/aliancas-de-ouro-18k-e-diamante-mod-woh/

Crocoblock support told me this:

> Hi Marco,
> Please, set the needed width for zoom here http://prntscr.com/ptavtc
> Kind regards, Veiki

But, this makes no sense as it is telling me that you need to upload the full image to the gallery, but this is compromising all site optimization and speed.

Note that the problem is only with the main image. The others zoom works perfectly.

And the final support answer was this below, but I still consider it a bug (ticket 3241):

> Hi Marco,
> It works only this way - you have the bigger thumbnail and the smaller one.
> You can try to optimize the image to make it lighter.
> Kind regards, Veiki

**To Reproduce**
Use widget Gallery Slider with Image Featured

**Expected behavior**
The widget needs to work properly, loading zoom images only when requested, without having to load the full size image on the slider.

**Comment by marcofrasson** [comment]
Hi @Floydtm , isn't this a bug?

**Comment by Floydtm** [comment]
@marcofrasson, Hi! This is not a bug, just set the width in the settings that matches the width of your pictures. Thanks you!
