### ISSUE TITLE
JetBooking - the Days off feature does not save days off

### ISSUE THREAD

**Issue by loran750** [CrocoBlock/suggestions#6452]
**Describe the bug**
You cannot save the "Days off" features in the Schedule settings does not save anything

**To Reproduce**
1. Go to Admin > Bookings > Settings > Schedule (/wp-admin/admin.php?page=jet-abaf-settings)
2. Click on 'Days off'
3. Add some days, save
4. Refresh the page if needed
Nota : there is NO api call NOR url called when we click on save

**Expected behavior**
- Have a list of days-off instead of empty list.

**Screenshots**
![image](https://user-images.githubusercontent.com/2526608/215830484-08d412cb-5605-4cab-b402-477e649b46b2.png)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
tested the 31th January 2023 with all plugins up-to-date: 
- WordPress 6.1.1
- JetEngine 3.1.0
- JetBooking 2.6.1.1
- JetThemeCore 2.0.7

**Comment by UraraReika** [comment]
Fixed in release 2.6.2
