### ISSUE TITLE
JetBooking - when you disable a day, the date picker cannot select dates of the following week

### ISSUE THREAD

**Issue by loran750** [CrocoBlock/suggestions#6453]
**Describe the bug**
When you set a day as disable, you may want for example to disable sundays.
And on the frontend, when you want to select a days range, you cannot the checkout day after the next following day off 

**To Reproduce**

**Expected behavior**
When I disable a day, I would be able to select a day-range in ALL the ranges available, for example from saturday to next saturday or from sunday to next sunday.

**Screenshots**
settings : 
![image](https://user-images.githubusercontent.com/2526608/215832758-e47b263a-4566-4bab-8c49-15d3d45aeaa8.png)

Disable mondays : 
![image](https://user-images.githubusercontent.com/2526608/215833201-0a2bde41-26d6-4c14-b5bf-77f298221121.png)

Cannot select after sunday after the week where I select the check-in day. All is grayed beyond sunday: 
![image](https://user-images.githubusercontent.com/2526608/215833376-16cd23f4-922d-4d65-8935-80b431f25cef.png)

**Desktop (please complete the following information):**
 - Ubuntu and Windows
 - Google Chrome up-to-date

**Smartphone (please complete the following information):**
 - Desktop

**Additional context**
tested the 31th January 2023 with all plugins up-to-date:

WordPress 6.1.1
JetEngine 3.1.0
JetBooking 2.6.1.1
JetThemeCore 2.0.7

**Comment by loran750** [comment]
![image](https://user-images.githubusercontent.com/2526608/215834656-3b5a1f97-e18a-4f2b-8165-7be1f597ec26.png)

**Comment by edelm4nn** [comment]
same her, the checkout-date is not clickable - we are using it for a car rental. Saturday and Sunday shouldnt bee available for rent or bring back a car, but the checkout date ist not visible or clickable 
![image](https://user-images.githubusercontent.com/34338490/215977625-96750d3c-beb3-4301-825b-af616d34a082.png)

**Comment by UraraReika** [comment]
Hello @loran750! Thanks for the feedback.

In the next release we will provide some JS hooks that will help you to achieve this results. Simply add this snippet in your child theme `functions.php` file 
```
add_action( 'wp_footer', function () {
	echo '<script>
		jQuery( document ).on( "jet-booking/init", () => {
			window.JetPlugins.hooks.addFilter( "jet-booking.date-range-picker.disabled-day", "jetBooking", ( disabled, arr ) => { 
				if ( disabled && "booked" === arr[1] ) {
					return disabled;
				}
				
				return false;
			} );
		} );
	</script>';
} );
```

You although can contact our support team https://support.crocoblock.com/support/home/ for additional help.


Thank you for your understanding.

**Comment by UraraReika** [comment]
Check 2.6.3 release

**Comment by loran750** [comment]
hello @UraraReika 
the plugin 2.6.3 does work ONLY with the above code, otherwise, it's the same than before. Why ? Because people would not install that code.
As for me, the feature does not work as previewed because it' would need that code (or perhaps it's created in the functions.php automatically ?)

**Comment by UraraReika** [comment]
> hello @UraraReika the plugin 2.6.3 does work ONLY with the above code, otherwise, it's the same than before. Why ? Because people would not install that code. As for me, the feature does not work as previewed because it' would need that code (or perhaps it's created in the functions.php automatically ?)

You need manually add this code snippet to your `functions.php` file. Maybe your site need additional setup in this case you can contact our support team https://support.crocoblock.com/support/home/ for additional help. For now this is temporary solution and in the future we will develop it.

Thank you for your understanding.

**Comment by loran750** [comment]
hello @UraraReika 
I get it and I have added it in functions.php and it works.
So for me, as long as it works, I'm okay with how it's done for the moment.

**Comment by Qubadi** [comment]
1+
