### ISSUE TITLE
💡 Feature Request [JetEngine]: Dynamic Terms Widget - Add Fallback Field

### ISSUE THREAD

**Issue by perks98** [CrocoBlock/suggestions#6455]
The dynamic field widget has a fallback section, but the dynamic terms widget does not. Can you add please 🙏

**Dynamic Fields fallback section:**
![Screenshot_718](https://user-images.githubusercontent.com/55829113/216348404-3e680098-7b2d-40de-9f35-f1ab67631c9e.jpg)

**Missing section on Dynamic Terms widget:**
![Screenshot_719](https://user-images.githubusercontent.com/55829113/216348439-74008dac-cfae-4104-8c37-7975aa56debf.jpg)

**Comment by Crocoblock** [comment]
was added in JetEngine 3.5.3 https://imgur.com/Xiztjzd
