### ISSUE TITLE
💡 Feature Request [JetEngine]: Current Object Field Tag Missing Advanced Input Options

### ISSUE THREAD

**Issue by perks98** [CrocoBlock/suggestions#6456]
When using the 'Current Object Field' dynamic tag with Elementor it is missing advanced options that would bring before, after and fallback options. Can this be added please 🙏

**This tag:**
![Screenshot_717](https://user-images.githubusercontent.com/55829113/216347776-204a9d18-d083-4a44-a4ae-7d5a42f3389c.jpg)

**Missing this option:**
![Screenshot_716](https://user-images.githubusercontent.com/55829113/216347879-6562bde9-cb31-4792-9f3c-1ad95d0726f2.jpg)

**Comment by kaskad88** [comment]
Fix will be in JetEngine v3.1.2
