### ISSUE TITLE
Custom filter sorting in jet smart filters

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#646]
Hi, it would be very convenient to set custom sorting in https://prnt.sc/pu3nvg filters without creating new filters.

/*Оригинал*/
Привет, было бы очень удобно задавать пользовательскую сортировку в фильтрах https://prnt.sc/pu3nvg не создавая при этом новых фильтров.

**Comment by stasonua0** [comment]
Здравствуйте, сортировка значений есть во всех фильтрах которые я знаю, но в Jet Smart этого нет и моя заявка с 8 ноября еще не рассмотрена. Можно узнать почему?

**Comment by MjHead** [comment]
Done
