### ISSUE TITLE
Introduce "Current Month" Macro

### ISSUE THREAD

**Issue by DudeDude95** [CrocoBlock/suggestions#6461]
I have a Custom Post Type named "Calendar Months" ("January", "February", "March" etc)

I would like to order these Calendar Months on the front-end using the listing grid widget by the current month.

For example, it is currently March.

That means, I would like the post named "March" to show first, then "April", then "May" and so on rather than the default ordering.

![image](https://user-images.githubusercontent.com/123473359/216391947-15ff619d-6632-43cd-9bfa-79414a2c4e66.png)

Thanks :)

**Comment by tizum** [comment]
+1

**Comment by MjHead** [comment]
Planned for 3.1.3

**Comment by MjHead** [comment]
Added `Current Date` macro with next options:
- Day of month - for example 12, 23
- Day of week - Sunday, Monday
- Current month name - March, April
- Current year - 2023
- Custom - date format string with any parameters from the list - https://www.php.net/manual/en/datetime.format.php

**Comment by DudeDude95** [comment]
Thank you crocoblock!

**Comment by morosmo** [comment]
@MjHead Thaankyou

**Comment by MjHead** [comment]
@Dudeney95 @morosmo Just note - it will be released with 3.1.3 update in 1 week or so

**Comment by tizum** [comment]
@MjHead Could you look at this request?
https://github.com/Crocoblock/suggestions/issues/6446

I'm still using the legacy version of Post Query due to not having this functionality.
