### ISSUE TITLE
yoast global meta description does not recognize metafield 

### ISSUE THREAD

**Issue by yaron86** [CrocoBlock/suggestions#6462]
i have a property post type with several meta field, one of the meta field is "property_desc" (textarea field) which i want to add this as a meta description in yoast.

under Yoast -> Settings -> Content Types - > Properties, i added the "property_desc" meta field and a lorem-test text like so: 

![image](https://user-images.githubusercontent.com/3582979/216436317-c897fcb1-34f6-4cef-b6a8-a0653d7f4dcc.png)

and on the frontend view source, only the lorem-test is appear, and the "property_desc" meta field does not output at all
![image](https://user-images.githubusercontent.com/3582979/216437179-97ca7608-0f39-446b-89b7-6861e60abf5a.png)

**Comment by kaskad88** [comment]
Hello @yaron86 
You need use the following variable `%%cf_property_desc%%` for your case
https://yoast.com/help/list-available-snippet-variables-yoast-seo/
https://tppr.me/dxnvs
