### ISSUE TITLE
JetBooking- setting the check-ins/ check-outs only for Saturdays.

### ISSUE THREAD

**Issue by gosiaasking** [CrocoBlock/suggestions#6467]
Hi guys,
I'm struggling to set up the booking setting that allows me booking only on Saturdays.
For example, some properties in high season (July & August) can be rent only from Saturday till Saturday, for min. 7 days (alternatively for 14 or 21 days).
I can only set up a seasonal price and a min. stay, but what about check-in/out only on Saturdays?
Anyone faced this problem too?

**Comment by UraraReika** [comment]
Hello @gosiaasking! Thanks for the feedback.

In next update we will present some new JS hooks that will help you to achieve some kind of functionality you need. You can check the snippet example here https://github.com/Crocoblock/suggestions/issues/6453. 

But in general such a goal can be reached using a custom solution only. We highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/  

Thank you for your understanding.

**Comment by gosiaasking** [comment]
Hi,
when your next update for Jetbooking will be released?
