### ISSUE TITLE
Shortcode in bricks builder

### ISSUE THREAD

**Issue by laurentgarin** [CrocoBlock/suggestions#6468]
Hi,
When you add a jetformbuilder shortcode in bricks builder there is message "Please select form to show"

[jet_fb_form form_id="146" submit_type="reload" required_mark="*" fields_layout="column" enable_progress="" fields_label_tag="div" load_nonce="hide" use_csrf=""]

It is strange because in the shortcode there is the form ID.

Jetformbuilder beta3

**Comment by olpo24** [comment]
same here

**Comment by laurentgarin** [comment]
> same here

It work now with the release.
