### ISSUE TITLE
Relations between posts and medias not working in JetEngine

### ISSUE THREAD

**Issue by abweil** [Crocoblock/suggestions#647]
**Description**
When setting a relation between any post type and media type ("attachment"), search result is always empty when looking for a media in the post and from the media menu, we can select the post but this relation does not get saved with the media.

**Steps to reproduce**
1. Go to JetEngine > Relations
2. Set "Parent post type" to "post" or a custom post type.
3. Set "Child post type" to "Media file".
4. Set "Realtion type" to "One to many" (only tested for this relation type, but it is probably the same for the others)
5. When in a post page for the selected post type, the "Related media file" field appears but search result is always empty (could this be due to Media special status "inherit"?).
6. When in a media page, the "Related post" field appears and I can search and select a post, but when I update the Media, the field is emptied.
("Media file" is a translation from my french UI, it might not be exactly the same in english)

**Expected behavior**
Search results should be shown for media in post and the relation should be saved in the media screen.

**Screenshots**
In post page : no result for research
![noresults](https://user-images.githubusercontent.com/18311638/68461466-8f942280-020a-11ea-8333-82cd7f4cf9aa.jpg)

In media page while updating
![before](https://user-images.githubusercontent.com/18311638/68461522-b3576880-020a-11ea-8085-2b5a774e90d4.jpg)

After update: field has been blanked
![after](https://user-images.githubusercontent.com/18311638/68461568-ca965600-020a-11ea-97a6-1d97a0485190.jpg)

**Desktop :**
 - OS: Windows 10
 - Browser : Chrome 78.0.3904.97
 - Version : JetEngine 2.1.2

**Comment by kaskad88** [comment]
Fix for the next version(2.2.0).
Thanks for your report!
