### ISSUE TITLE
JetBooking - Days Off/On Mode Switching

### ISSUE THREAD

**Issue by cranstantinople** [CrocoBlock/suggestions#6471]
Ability to switch mode for a booking item from "Available by Default with Days Off/Unavailable" to "Unavailable by Default with Days On/Available".  Several customers would like to set up bookings for events such as farmers markets that only happen once or twice a month.  Setting up all the "Days" off to accommodate this is unintuitive.

**Comment by andre-xavier-berger** [comment]
+1

**Comment by Qubadi** [comment]
+1

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1586, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
