### ISSUE TITLE
Add upsell to show up in product grid (jetwoobuilder)

### ISSUE THREAD

**Issue by thejojk** [CrocoBlock/suggestions#6472]
I wish to see upsell as a option for what product that is listed in the product grid

**Comment by UraraReika** [comment]
Hello @thejojk! Thanks for the feedback.

This functionality already exist in JetWooBuilder Products Grid and Products List widgets. This functionality works in JetWooBuilder Single Template and JetWooBuilder Cart Template. How to use:
1 - Open JetWooBuilder Single Product or Cart Template;
2 - Add Products Grid widget;
3 - Save template;
4 - Reload this template;
5 - Check result https://tppr.me/ZzcXH - on JetWooBuilder Single Template, https://tppr.me/zqchH - Cart Template.

Thank you for your understanding.

**Comment by thejojk** [comment]
Hi,

Ok. I suppose I then must use Jetwoobuilder single product page and not elementor single product page?


Best regards
Joe

**Comment by UraraReika** [comment]
We will add compatibility with Elementor Pro tempalates in one of the next releases

**Comment by thejojk** [comment]
Hi,

Thanks, good to hear!

/Joae
