### ISSUE TITLE
JetTabs - Tabs Widget - Make Image Dynamic

### ISSUE THREAD

**Issue by BonnFlow** [CrocoBlock/suggestions#6477]
Add the feature to place a Dynamic Image (Post Image / Custom Meta Field Image) into the Image Field, which helps the user to build better-looking Tabs, like in the attached image. 
![Crocoblock_Tabs_FeatureRequest](https://user-images.githubusercontent.com/124771683/217477003-a2dd0c7a-c5e5-4843-bebf-f05d56e7bfd7.jpg)
![feautre_dynimg](https://user-images.githubusercontent.com/124771683/217477644-5fcd62a7-d781-4d88-929b-3a9a3a451888.png)

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-tabs/tree/fix/sug%236477

**Comment by BonnFlow** [comment]
Hi @bazilik1095 Your Link is a 404.

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
