### ISSUE TITLE
[Jetwoobuilder][JetEngine] Product Quick View Popup not work in Listing Grid 

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#6484]
Following the instructions, I made Quick view Pop-up. 
https://crocoblock.com/knowledge-base/articles/how-to-create-a-product-quick-view-with-jetwoobuilder-and-jetpopup/

But I want to Use Jetengine query to display products with Similar Product (https://crocoblock.com/knowledge-base/articles/jetengine-listing-grid-widget-how-to-display- dynamically-related-posts-on-the-single-post-page-template) in the same category or Recently viewed Products (https://crocoblock.com/knowledge-base/articles/jetengine-how -to-create-recently-viewed-section-using-data-stores-module/).

I tried putting the Archive product of JetWoobuilder into the Listing Grid of JetEngine to try, the normal interface works quite well but the Quick view Pop-up part does not work.

Is this claim workable? If so, please include it in the next update.

**Comment by UraraReika** [comment]
Hello @taidang26 and thanks for the feedback.

If you create quick view popup based on JetWooBuilder plugin functionality it definitely will not work with JetEngine. In your case you need to build dynamic popup using this article https://crocoblock.com/knowledge-base/articles/jetpopup-how-to-build-a-dynamic-popup-to-work-with-jetengine-listings/. If you will have some difficulties feel free to contact our support team. https://support.crocoblock.com/support/home/ 

Thank you for your understanding.
