### ISSUE TITLE
jet woobuilder product grid widget update

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6485]
**Please, describe the feature request, making it clear to understand.**

The product grid widget is a very powerful widget. It's called product Grid, but if you check its html structure, it's not built with Grid. This issue has caused this widget to not behave as it should. For example, we don't have an option to set **row gap** and **column gap**. Rather, we can only create this gap by using padding. This is not really a logical way.

So do you have any plans to rewrite this awesome widget using css Grid? This is an important issue. thanks

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6226, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
