### ISSUE TITLE
calculated field is not working when deviding by a field that is equal to zero.

### ISSUE THREAD

**Issue by yanivalm** [CrocoBlock/suggestions#6489]
"I have a calculated field that divides two fields. The issue is that if both fields are left empty (equal to zero), the form breaks.
The only solution I found so far is to set a default value, but this is not ideal because the fields should remain empty until the user inputs data.

 The fields I'm using are 'bruto-size' and 'neto-size', and the formula for the calculated field is (%FIELD::neto-size% / %FIELD::bruto-size%) * 100. On an older version, this worked fine, but with the current version, it causes the form to break if 'bruto-size' is 0."

**Comment by girafffee** [comment]
Hi, @yanivalm
Did I understand you correctly that your Calculated Field doesn't work at all, even after filling in the 'bruto-size' and 'neto-size' fields?

**Comment by yanivalm** [comment]
Yes. Only if i set default value for the bruto size which is higher than zero. נשלח מה-iPhone שלי‫ב-10 בפבר׳ 2023, בשעה 12:34, ‏‏Sasha Ivanenko ***@***.***> כתב/ה:‬﻿
Hi, @yanivalm
Did I understand you correctly that your Calculated Field doesn't work at all, even after filling in the 'bruto-size' and 'neto-size' fields?

**Comment by girafffee** [comment]
@yanivalm just pushed the fix

You can manually download the plugin from this repository or wait until we release an official update.
