### ISSUE TITLE
smart filters > different filter sets in categories

### ISSUE THREAD

**Issue by mek7com** [Crocoblock/suggestions#649]
Suggestion: set the filters per category!
    We require different filter characteristics per category!
    Requires motorcycle accessories
    Chain sizes are different than helmets or clothing.
    Oils have completely different characteristics.

    Specify a fixed filter set for each category!
    Or function
    If no filter is provided, nothing will be displayed.

    www.zap-technix-shop.com

**Comment by UraraReika** [comment]
You can do this by creating custom templates for taxonomies. Based on #553.
