### ISSUE TITLE
JetBooking: Ability to edit/change the booking status in frontend or Post Type

### ISSUE THREAD

**Issue by avdstelt** [CrocoBlock/suggestions#6491]
Hi,

It would be nice if we can change the booking status in the frontend or Post type so that we can make a custom page and use the profile builder to edit the booking data.

Greetings Arjan

**Comment by morosmo** [comment]
Currently , We have to do a very long process. first we need to create form then hide everything setting up everything and hen we can update post using form submit action from frontend. Please add an easy way to perform frontend task so we cna build much complex dashboard layouts for our customers
+1

**Comment by Qubadi** [comment]
1+

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1433, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.

**Comment by Rahul13052004** [comment]
did you guys find the solution?
