### ISSUE TITLE
JetEngine - Query Builder Advanced SQL Dynamic Image widget

### ISSUE THREAD

**Issue by pauserratgutierrez** [CrocoBlock/suggestions#6492]
I'm using JetEngine Query Builder with Advanced SQL. I'm trying to display an image but the data looks like this:
`[chat_amb_user_img] => a:2:{s:2:"id";s:3:"601";s:3:"url";s:94:"https://webdomain.com/wp-content/uploads/nameofthefile.jpg";}`

The Dynamic Image widget doesn't allow to pull it. The Dynamic Field allows to pull it, but the custom field output -> Get Image By ID doesn't work (because it contains more than the id).

Would be great to have an option to pull an image from that data.

**Comment by pauserratgutierrez** [comment]
I was saving the user meta image as Array (url and id). I changed that to ID only to be able to display using the Dynamic Field -> Callback -> Get image by ID. But I want to use the Dynamic Image widget and I can't because there's no option to select the query dynamic data.

**Comment by morosmo** [comment]
+1 if query values cna be selected by other widgets to that will be much apprecited.

**Comment by pauserratgutierrez** [comment]
With a Dynamic Field widget we can select everything, but then we need to use custom CSS to style things (for example for an image, because the widget is used for text fields, not image fields):
![image](https://user-images.githubusercontent.com/73240206/219340150-a0d5058f-d616-4609-b3cc-0c39e0526314.png)

But JetEngine has a Dynamic Image widget, which we can't use to display dynamic images other than for this simple use cases...:
![image](https://user-images.githubusercontent.com/73240206/219340465-e6a842ce-145a-4e78-aee8-d60d622fc4d4.png)

EDIT: We can't use the Dynamic Image widget to display the data from an image in that case because the data is saved as ID of the image, and the Dynamic Image widget doesn't know there's an "image" to be pulled, because it's an id...

**Comment by pauserratgutierrez** [comment]
> With a Dynamic Field widget we can select everything, but then we need to use custom CSS to style things (for example for an image, because the widget is used for text fields, not image fields): ![image](https://user-images.githubusercontent.com/73240206/219340150-a0d5058f-d616-4609-b3cc-0c39e0526314.png)
> 
> But JetEngine has a Dynamic Image widget, which we can't use to display dynamic images other than for this simple use cases...: ![image](https://user-images.githubusercontent.com/73240206/219340465-e6a842ce-145a-4e78-aee8-d60d622fc4d4.png)

We can't use the Dynamic Image widget to display the data from an image in that case because the data is saved as ID of the image, and the Dynamic Image widget doesn't know there's an "image" to be pulled, because it's an id...

**Comment by Floydtm** [comment]
Will be added in version 3.2.5 https://tppr.me/t1afM https://tppr.me/8YOoC
