### ISSUE TITLE
[JetFormBuilder] Combine multiple fields into one

### ISSUE THREAD

**Issue by rentaterry** [CrocoBlock/suggestions#6495]
Hi technical team,

Hope you all well. 

Here is my request:
Please add the ability of combining multiple fields into one. For example, Posts Title added by users is compsed of [TermA]&[FieldB] for more conformity and easy to read. I tried on JetFormBuilder and it only allows numbering combination (not calculation). It would be great if the plugin supports all kinds of typing.

![screenshot-28truck-bricks ooooo one-2023 02 12-00_30_23](https://user-images.githubusercontent.com/75129305/218269489-dc94917f-5409-48ea-8680-7de5e947361d.png)

**Comment by morosmo** [comment]
+1 Please add this much needed

**Comment by rentaterry** [comment]
> 

Hi, I have received a response from the support team which worked perfectly:


Hi @rentaterry
Try to enclose your formula in quotation marks.
"%brand%%model%"
