### ISSUE TITLE
Entry/exit effect for disabled mode / jet woobuilder carousel

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6497]
Hi team.

On one of the websites, I saw a very interesting feature for disabled mode, which was really cool. On this website, when the carousel reached its end (disabled mode), the arrow was hidden along with the effet. It also appears with the effect when the arrow reappears.

https://user-images.githubusercontent.com/88034902/218307530-cf588044-d657-47cb-8ba9-3cd049cad851.mp4

It would be great if you add this feature in jet woobuilder. Only one switcher button will be enough to activate this effect (for disabled mode).

**Comment by UraraReika** [comment]
Hello @Michaelgimii and thanks for the feedback.

Unfortunately  we do not plan to introduce such functionality into our plugin. However you can use this simple css:

```
selector .swiper-button-disabled {
    opacity: 0;
    transition: all 0.3s;
}

selector .jet-swiper-button-prev.swiper-button-disabled {
    left: -50px;
}

selector .jet-swiper-button-next.swiper-button-disabled {
    right: -50px;
}
```
