### ISSUE TITLE
Compatible with Elementor version 3.11.0 - jet plugins (Especially jet woobuilder)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6498]
**Please, describe the feature request, making it clear to understand.**

Hi

The new version of Elementor will be released tomorrow and it has two important features that jet plugins need to be compatible with.

1- Copy & Paste Between Websites
2- Upgrade Swiper Library to 8.4.5

Especially the jet woobuilder plugin that uses Elementor's swiper is very important to be compatible with the new version. **In addition, it would be great if the jet engine plugin also migrated to swiper Library.**

thanks

**Comment by Joliamendi** [comment]
Hi @UraraReika 

Version 3.11 was released. After updating elementor and updating swiper, product grid carousel is completely broken.

**Comment by 79ho3ein** [comment]
Hi everyone.

Please note, until jet woobuilder releases an update for it, you can disable swiper update in elementor settings. Of course, this option is disabled by default after updating Elementor.

**Comment by antoinelbch** [comment]
+1

**Comment by Michaelgimii** [comment]
Hi @UraraReika, After 4 months of updating, there is still no compatibility?

**Comment by Michaelgimii** [comment]
Hi @UraraReika, Are you aware of this? There was no news of it in the new version.

**Comment by JuliaKiselyova** [comment]
+1 https://github.com/Crocoblock/issues-tracker/issues/6097

**Comment by LaxusCroco** [comment]
+1 compatibility for JetProductGallery (the images in the Gallery widget of Elementor are not visible when JetProductGallery and Upgrade Swiper Library are activated)

**Comment by hitsgee** [comment]
There is a new pull request in Elementor that will remove the old swiper library and make the new upgrade expirment core/merged. 

JetWoo will break if this is not fixed soon 

PR: https://github.com/elementor/elementor/pull/27616

**Comment by Crocoblock** [comment]
compatibility with 8.4.5 version of swiper slider was added and released in JetWooBuilder 2.1.13
