### ISSUE TITLE
JetEngine + JetSmartfilter: Ability to use checkbox filter with 'checkbox' custom fields

### ISSUE THREAD

**Issue by RodSuper** [Crocoblock/suggestions#65]
Hi,

I would love to see the Checkbox filter work with custom meta fields 'checkbox'.

I'm working on a real estate website where I want admins to check special features about the property: Close to sea, Garage, Large garden, etc. In the backend I have set this up as a 'checkbox' custom field. On the frontend, I want users to be able to filter the features they are looking for using the checkbox filter.

**Comment by MjHead** [comment]
Hi @RodSuper. If I understand you correctly, at this moment you can do this by selecting "Manual Input" as Data Source for Checkboxes filter. Then manually set the same choices as for backend select field and set this field name as Query Variable for filter.

**Comment by RodSuper** [comment]
Hi @MjHead Thanks for replying. Thanks for helping me solve the select option! This works great!

However, the part regarding the connection between 'checkbox filter' and 'checkbox custom field' doesn't seem to work properly yet. I've added an example here: https://homes.rotsinbranding.nl/woningen-overzicht/

I've added checkbox options called 'special features' to properties. You can find a checkbox filter at the bottom of the filterbar. It seems that the checkbox filter doesn't work with multiple checked boxes. However, in the backend I want admins to be able to check all the fitting boxes.

Do you also have an idea if this is possible already?

I've added screenshots of my 'Custom meta box' and 'Smart Filter' settings.
<img width="1364" alt="screenshot 2019-02-27 at 12 45 09" src="https://user-images.githubusercontent.com/47865142/53488335-4b9f2a00-3a8e-11e9-871a-8c2b670feb44.png">
<img width="1738" alt="screenshot 2019-02-27 at 12 44 22" src="https://user-images.githubusercontent.com/47865142/53488336-4b9f2a00-3a8e-11e9-9951-25ceea824f63.png">

**Comment by MjHead** [comment]
You need to add some custom PHP to make this work. Here is an example - https://gist.github.com/MjHead/17860a68ca13f909aa00678623073a0b. The problem is the Checkboxes field stored as array, so you need to change Compare operator for appropriate query variable

**Comment by RodSuper** [comment]
Hi @MjHead thanks for your suggestion. I've added the code and it works partially. Unfortunately it breaks all the other checkboxes. Can I ask your advice for two things:

- How can we make the PHP work without it breaking the functionality of other checkbox filters?

- I want the checkboxes to work as an 'AND' field. For example, I want only homes who have both a 'Pool' AND 'Garage'. At the moment it works as an IF. Do you have a suggestion for this to work?

Thanks in advance!
Rod

**Comment by alriksson** [comment]
+1, right now it's only possible to use in combination with taxonomy.

**Comment by MjHead** [comment]
Hi @RodSuper, sorry for delay. We'll try to implement functionality to manage this things from admin area. For now, could you please create a ticket at our support portal with your access details - https://kava.ticksy.com/ and I'll try to figure it out on your website.

**Comment by bevanjkay** [comment]
@MjHead any update on if this is coming soon?

**Comment by smatzis** [comment]
+1

**Comment by Rubenzella** [comment]
Hey guys, is this staked checkbox filter option been implemented?

**Comment by MjHead** [comment]
Hi! We added an option to implement this
