### ISSUE TITLE
Jet Smart Filter show more

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#650]
Hello, please make the setting possible for the number of displays of checkboxes and radio buttons - https://prnt.sc/pumkxw
For example, they set in the filter settings to show no more than 5 checkboxes, after which the "show more" button appears, just like it was done in the woof filter, here is the screen - https://prnt.sc/pumlvs

/*Оригинал*/
Здравствуйте, сделайте пожалуйста возможность настройки для количества показа чекбоксов и радио кнопок - https://prnt.sc/pumkxw
Например задали в настройках фильтра показать не более 5 чекбоксов, после чего появляется кнопка "показать еще", точно так же как это сделано в woof filter, вот скрин - https://prnt.sc/pumlvs

**Comment by MjHead** [comment]
Done
