### ISSUE TITLE
The possibility of removing the price from out of stock products - jet woobuilder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6501]
Hi crocoblock team

Throughout the website, I use the product grid widget to display products. This is a unique widget. But there is a very important problem for customers. On our website, prices change several times a month (often increase). We set the stock to 0 for the products that we are no longer going to stock. But their prices are still displayed in the product grid widget.
I wanted to request you, please add a new option, so that the price is not displayed in the products whose stock is equal to 0. **Please note that only the price is not displayed.**

This option is very useful and we can enable it if we want. I think this option can be added under the [Stock Status](https://prnt.sc/A_8hg1D7tFC5) option in the product grid widget.

Hope you add this feature. thanks❤

**Comment by morosmo** [comment]
+1

**Comment by Joliamendi** [comment]
+10000 please!!!

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello 👋  Thanks for the feedback.

At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Right now you can rewrite price template of Products Grid widget in your child theme `templates/widgets/global/products-grid/item-price.php`. And ad additional check:
```
if ( ! $product->is_in_stock() ) {
	return;
}
```

Like this https://tppr.me/fdVCd

Thank you for your understanding.
