### ISSUE TITLE
Float value is not allowed in Jet Engine custom field Number Field.

### ISSUE THREAD

**Issue by machachen** [CrocoBlock/suggestions#6504]
After the latest update of Jet Engine.
The number field does not allow numeric value with decimal points any more.
Was that intended? 

Many of my site's setting are done with the float value and sort logic based on it. 
<img width="576" alt="Screen Shot 2023-02-13 at 9 53 15 AM" src="https://user-images.githubusercontent.com/58905862/218353964-95fd5a41-ad71-4a2e-8dd0-42ab860b2c45.png">

Thanks!

**Comment by kaskad88** [comment]
@machachen Hello. 
What version of JetEngine do you have ? 
Could you please attach a screen of CPT or CCT page settings

**Comment by kaskad88** [comment]
Fixed in JetEngine v3.1.1
