### ISSUE TITLE
JetSmartFilters v.3.1.0 beta

### ISSUE THREAD

**Issue by MjHead** [CrocoBlock/suggestions#6509]
Hi,

We are almost getting ready to release JetSmartFilters v3.1.0 and we would like to ask you to help us test JetSmartFilters v3.1.0 Beta.

You can download beta version from your Crocoblock account.

**Please note that is a beta version, not stable release, so its not ready to use on production websites!**

### URL Aliases

We have added new functionality, allowing you to change the filtered data URL using aliases. The main purpose of this feature - replace URL parts you don't like to with anything you want. For example - _your-site.com/sample-page/jsf/jet-engine:query-id/_ with _your-site.com/sample-page/filters/_ etc.

The pathway is as follows:

**Smart Filters > Settings > URL Structure Settings**

<img width="676" alt="image" src="https://user-images.githubusercontent.com/4987981/218676563-3cb4d7a8-79ec-4f66-9eea-459483378c81.png">

The Use URL Aliases toggle switch enables aliases functionality. Aliases are added using the repeater. Every alias consists of two mandatory fields: needle and replacement. Needle stands for the desired value in the URL, and Replacement contains the value that will be used instead of the needle.

**How it works**

When we apply filters from the website’s front end, those filters write data in the URL (Apply type = Page reload / Mixed); thus, the URL data is generated as before, e.g., _/jsf/jet-engine/tax/category:27/_. Afterward, this row passes through all iterations of aliases added through the repeater. If there is a match, the needle value is substituted by replacement. For instance, if we have `needle=/jsf/jet-engine/ `and `replacement=/filter/ `in the first iteration, the outputted result will be _/filter/tax/category:27/_. In the following iteration, the plugin will search for the needle in this new row. Once all replacements are done, the new row will be appended to the URL.

On the backend, everything happens the other way around. The filter returns the URL containing _/filter/tax/category:27/_, and before the parse request event, the replacement takes place in the reverse order; the replacement value is changed to that from the needle field. For example, _/filter/tax/category:27/_ has `needle=/jsf/jet-engine/ `and `replacement=/filter/`, so the output will be _/jsf/jet-engine/tax/category:27/_. Then this row is parsed into request parameters.

Since every value change for alias words is a cycle, and each subsequent iteration uses the changed value from the previous iteration, it is important to set the right order of the aliases in the repeater. For this matter, we added the possibility of swapping them using a simple drag & drop.

Example:
Input row – `/jsf/jet-engine/tax/category:1;post_tag:2/`

<img width="627" alt="image" src="https://user-images.githubusercontent.com/4987981/218677668-ea94c4ed-50cb-4f9c-b5b4-8a1659154be0.png">

First iteration – _/`filter`/tax/category:1;post_tag:2/_
Second and final iteration – _/`filter-tax`/category:1;post_tag:2/_

But if you swap the aliases, then there will be no /filter/tax/ during the first iteration, and the result after the second iteration will be as follows: /filter/tax/category:1;post_tag:2/

In the admin panel below the repeater, there is a new block called See how the aliases will look, which helps to visualize how changes in the URL occur during direct and reverse transformation.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/4987981/218678374-f82f8947-2cdb-465e-8f53-ec06e0e1476d.png">

Searching and replacement occur in the part of the URL after the Site Address (URL):

<img width="622" alt="image" src="https://user-images.githubusercontent.com/4987981/218678634-4296a3a4-f629-4b05-913c-e7811346470b.png">

So, you can use pages, archives, etc., in the aliases. 
Remember that such a value combination as needle=/page-name/jsf/jet-engine/ and replacement=/page-name/filter/ will work only on the /page-name page.

Additionally, if there are no JetSmartFilters keywords in the URL (like '/jsf/', '?jsf=', '&jsf='), the aliases will not be applied, even if there are matching needle values.

### Bricks query loop filters provider

Also we added a new provider, **Bricks query loop** – https://tppr.me/ljful – which is available only for filter elements in the Bricks editor. The purpose of this provider is to filter a certain element that displays a listing of posts (terms, users, etc.) on the page. This provider works with the Bricks’ native Query loop builder.

Each provider has its own small integration features on the provider side. Speaking about the Bricks query loop, it works as follows: 

- Select the provider in the desired filter (a standard step performed for any other provider).
- There can be several Query loop elements on the page, so make sure to activate the Is filterable option in the one you want to filter – https://tppr.me/7GBoY.
- If you want to filter multiple Query loop elements, you need to link them to the corresponding filters by ID. In the Bricks query loop, the option for filter ID input is located right after the Is filterable option – https://tppr.me/Scsqz.

Other than that, working with this provider is similar to working with any other JetSmartFilters provider.

Please leave in the comments below any feedback according this beta.

**Comment by morosmo** [comment]
@MjHead 
Thanks for the update.

**Comment by Michaelgimii** [comment]
If the jet engine plugin is not installed, will there be a URL Structure Settings option in the jet smart filters settings?

**Comment by nreljed** [comment]
@MjHead 
thank you for this surprise update it's a good surprise ! your betas are always on top and almost no bugs I would have liked to see the N Selected addition for the dropdowns for more efficiency for already existing sites, if this addition requires changing just two lines of codes why not add it to the list?

**Comment by laurentgarin** [comment]
Hi, i just test with bricks, this don't work, i d'ont see error in console.

It is a query loop for a CPT create with jetengine.

https://imgur.com/a/R67vw8L

**Comment by MjHead** [comment]
@Michaelgimii Yes, it will work without JetEngine

**Comment by MjHead** [comment]
@nreljed Sorry, not clearly understand your request, could you please add some screenshots or more detailed description

**Comment by MjHead** [comment]
@WebAtelier47 Hm, strange. I'll try to reproduce this on clean installation, not faced such issue during the tests

**Comment by laurentgarin** [comment]
Sorry it is not a request, it is just to inform that i just test in bricks builder and this don't work
https://imgur.com/a/R67vw8L

**Comment by MjHead** [comment]
@WebAtelier47 Message about request was for @nreljed I got your problem and we already starting to check it

**Comment by nreljed** [comment]
> @nreljed Sorry, not clearly understand your request, could you please add some screenshots or more detailed description

Yes here is the post source #5114  where I tried to simplify and explain in detail the advantages and why this addition has a real value

**Comment by Picrold** [comment]
Amazing idea

**Comment by Joliamendi** [comment]
Thanks for the update.

Please add elementor loop builder compatibility for future updates.

**Comment by laurentgarin** [comment]
@MjHead For info https://www.loom.com/share/3e885213680f469bbac3409809dcb50c

**Comment by nishidshajib** [comment]
**Wow Great**

**Comment by MjHead** [comment]
@WebAtelier47 We uploaded Beta 2 with couple small fixes. Still can't reproduce your issue in exactly way you show - works fine. But can you install Beta 2. If it will not help - maybe you have this error reproduced on some remote staging website and could send me an access details with PM in Facebook - https://www.facebook.com/andremjhead

**Comment by laurentgarin** [comment]
@MjHead I sent you a PM in messenger

**Comment by GabrielVornicu** [comment]
Is it somehow possible to make their names appear instead of that id for the filtered categories??
For example, I have a taxonomy called Bulgaria, instead of id:4 Bulgaria should appear.

**Comment by hb81010** [comment]
@MjHead It looks better with Beta 2. I also tested a bit and had the same problem as WebAtelier47. But now the filters I tested work. But I still have to do a detailed test.

**Comment by hb81010** [comment]
Addition to Bricks:

I noticed something while testing

I like to use dynamic elements in my queries like a dynamic lightbox, off-canvas or modal (from BricksExtras) to hide additional information and still deliver compact and clear listings. This is especially useful for mobile devices.

I noticed that after filtering, load more, pagination (all AJAX) the respective elements are no longer executed. This only happens when AJAX is executed. With a page reload it works.

Would be cool if this is supported in the future.

----

Otherwise, it looks quite good with the beta 2. I just noticed that when I enable "Apply indexer" in the indexer options, that then the featured image is not displayed and my filter no longer works. I tested it with the Checkbox Field

This is the output

Fatal error
: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, bool given in ....\wp-content\plugins\jet-smart-filters\includes\indexer\data.php:120

![grafik](https://user-images.githubusercontent.com/54399588/219855597-a79bee30-403b-433f-9bbd-fe046823546c.png)

**Comment by Michaelgimii** [comment]
Hi @MjHead

I apologize that it is not related to this beta version. But please see this bug report? https://github.com/Crocoblock/suggestions/issues/3366
This is a very important item. I hope you will consider it for future versions🙏

**Comment by wpeasy** [comment]
Hey guys, definitely not working yet.  Looking forward to a working version.
See this for a simple Category Checkbox filter. 
https://wpeasy.sharepoint.com/:v:/s/WPEasyOnboarding/EQIdS51zuahJr2p_zAEhHeABFxJk9p2Cw1avtkgxbKlEFA?e=mCTZfW

**Comment by wpeasy** [comment]
Actually playing again today it does work. However, only if the  Loop Query is set to  JetEngine Query Builder
This is OK, but needs to be made clear to users.

**Comment by wpeasy** [comment]
Also, Pagination not working and no "Load More"

**Comment by nreljed** [comment]
hello @MjHead @SargasTM 
a customer tells me again about this bug that I can't fix 

https://user-images.githubusercontent.com/82481592/221572272-068d17d2-947f-49eb-bf42-8324fee6197b.mp4

I tried typing multiple values like
2000
3000
5000
etc

filter settings 
![Sans titre](https://user-images.githubusercontent.com/82481592/221574283-2cb89522-fd77-41bf-a8dd-a95bacd38f3f.png)



I also don't have the possibility of putting a (min - max placeholder )
instead of displaying numbers
is it possible to give us the option to do this?

![Sans titre](https://user-images.githubusercontent.com/82481592/221573019-02ba5f63-02a0-4cba-ab73-da54de79aa0f.png)

I also didn't have the possibility to hide the slider and keep only the inputs for the moment I use this 
```
.jet-range__slider {
   display: none;
}
```

**Comment by sekhsoyebali** [comment]
Please fix this issue - https://github.com/Crocoblock/suggestions/issues/6551

**Comment by MjHead** [comment]
Thanks all for the feedback. At the moment we on the final stage of checking and fixing this

**Comment by tole011** [comment]
Hope that problem with Bricks and AJAX will be fixed. So far I managed to work only with page reload.

**Comment by MjHead** [comment]
@tole011 We tried a lot of different set-ups and can't reproduce this bug. Maybe you have a remote staging website with this bug reproduced and can send me фn access details with PM in Facebook - https://www.facebook.com/andremjhead

**Comment by tole011** [comment]
> @tole011 We tried a lot of different set-ups and can't reproduce this bug. Maybe you have a remote staging website with this bug reproduced and can send me фn access details with PM in Facebook - https://www.facebook.com/andremjhead

Sorry to waste your time. Just tried it on a new installation and it worked as should. So, it must be my mistake... Keep up the great work!
Best regards.

**Comment by mehdimoradi1500** [comment]
Hi guys, thanks alot for bricks compability
In the JSF settings, there is a part to enable/disable modules for different filters of elementor

It should be changed for bricks/Gutenberg websites...
I think it has been forgotten

**Comment by mehdimoradi1500** [comment]
Hi @MjHead 
I created a checklist filter to show categories
1- I've toggled on the "Group terms by parents" but  there is no option to set horizontal spacing for the items (child of each parent) in bricks!
2- also any option to collapse all parent categories by default. Assume that we have 10 categories and 5 sub categories then we have a list by 50 items!! 
3- there is not option to only show parents categories! Jsf show all cats and sub cats by default

Please add more controls to make jsf better to be able to design sth like this filter:
![IMG_20230310_043707](https://user-images.githubusercontent.com/86493591/224197126-bf281b41-bbc7-4741-b343-69aff2493aed.jpg)

**Comment by wpeasy** [comment]
Will there be a "Load More" and "Pagination"?

I'm holding off on a project waiting for this. Deciding if I need to buy WP GridBuilder or if I can use JetEngine and JetSmartFilters
