### ISSUE TITLE
JetTabs : Full width tab title container

### ISSUE THREAD

**Issue by amirahmadh** [Crocoblock/suggestions#651]
Hi Guys,

This suggestion are based on support ticket that i raised to Jet support team.

As they already helped on it, i would suggest it to be featured in the next JetTabs update.

------

We requested for help to make the tab title area in full width as the default is not.

(refer attachment)
![image](https://user-images.githubusercontent.com/57563106/68528946-109b0900-0334-11ea-9c15-e841a1239691.png)

this is what we plan it to be.

(refer attachment)

![image](https://user-images.githubusercontent.com/57563106/68528956-30323180-0334-11ea-95b9-d002ee1c7315.png)

and Jet Support team help us by adding this custom CSS 

(refer attachment)

![image](https://user-images.githubusercontent.com/57563106/68530516-9d00f800-0343-11ea-9ff9-e92fd300185f.png)

and final result 

(refer attachment)

![image](https://user-images.githubusercontent.com/57563106/68530530-b6a23f80-0343-11ea-8cb6-428385f1fbfb.png)

i would suggest this feature to be added in tab setting / style.
as in 'enable full width' toggle switch. much easier.

thank guys!

**Comment by stasonua0** [comment]
+1

**Comment by kaskad88** [comment]
Added to the next version
