### ISSUE TITLE
Listing grid slider vertical

### ISSUE THREAD

**Issue by Livireweb** [CrocoBlock/suggestions#6510]
Good morning, I would like to request, if possible, that the slider of the listing grid could also be vertical. It would give a lot of play and many options in development. Thank you.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by aperojo** [comment]
> Good morning, I would like to request, if possible, that the slider of the listing grid could also be vertical. It would give a lot of play and many options in development. Thank you.

That would be an awesome feature 👍
