### ISSUE TITLE
Can't install JetPorductGallary from Update & installation darshboard

### ISSUE THREAD

**Issue by Picrold** [CrocoBlock/suggestions#6512]
Hello Crocoblock,

I hope everything is going well, please I Can't install JetPorductGallary from Update & installation dashboard

![image](https://user-images.githubusercontent.com/117189621/218906702-1ba825e0-f28b-4b20-af96-5a30c3bbff6e.png)

Please Help

Picrold Canada
picrold.ca
.

**Comment by Floydtm** [comment]
Hello. We checked everything and everything seems to be working fine. You can try to install the plugin again, there may have been problems on the server side. If the problem remains, contact the support team, we will help you solve the problem. Thank you!
