### ISSUE TITLE
[JetBlocks 1.3.5] Navigation Menu - Mobile Menu Style setting not working

### ISSUE THREAD

**Issue by soiluoi** [CrocoBlock/suggestions#6513]
**Describe the bug**
On Jetblocks ver 1.3.5, Navigation Menu - Mobile Menu Style setting not working. I can't change any attribute sush as background color, shadow, padding.
Using Elementor Version 3.11.0 
**To Reproduce**
1. Create a Menu with some items
2. Add Navigation Menu into section
3. Check Mobile Responsive
4. Change anything in Mobile Menu Style setting
5. See error

**Screenshots**
I change Background color and Box shadow but it doesn't change in preview
![Screenshot_1](https://user-images.githubusercontent.com/37627736/218931757-81adbc2f-7a45-4f14-8d97-3fd630d163e4.png)
![Screenshot_2](https://user-images.githubusercontent.com/37627736/218932503-981715a7-996e-429d-98a1-648b6c157b93.png)

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-blocks/tree/fix/issue%232170

**Comment by soiluoi** [comment]
> https://github.com/ZemezLab/jet-blocks/tree/fix/issue%232170

I can't access your link. pls check it again

**Comment by Floydtm** [comment]
@soiluoi This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by soiluoi** [comment]
Pls fix this. I have to work on a lot of website. And i can't add css to all. So I really need it
