### ISSUE TITLE
Add the possibility to customize the map listing popup close button

### ISSUE THREAD

**Issue by klecka** [CrocoBlock/suggestions#6515]
JetPopup has a nice customizable close button for the popup.
The map listing popup does not. You should add the same settings there. At the moment the close button is obstructed by google maps ui elements on mobile devices.
Maybe a possibility of closing the popup via a text link would also work.

**Comment by MjHead** [comment]
At the moment this is possible only with custom CSS. Additional options not planned to avoid editor overload
