### ISSUE TITLE
styling issue - elementor core options not working for only one widget

### ISSUE THREAD

**Issue by tommy83** [CrocoBlock/suggestions#6516]
Install latest WordPress version.
Install latest elementor + elementor pro.
Install latest crocoblock elements plugin
PHP 7.4.

1. Now create an elementor page.
2. Now go to Elementor -> Settings -> Features -> deactivate everything on this page (experiments and stable options).
3. Before you go to elementor default settings and open typrographie option for H1 tags. Setup custom font and custom fontsize.
4. Add widget "slider" to content area. Setup H1 for title. Remove all custom font styles from this widget title in STYLE tab.
5. But its not possible to inherit font style by elementor default settings here: https://ibb.co/bgXX81W

The only way to save time and not setup font-style for each slider widget is:
1. Click widget slider
2. In general tab select H1 tag for title
3. Go to style tab. Jump to title font. Select global font style.

So our question is:
Why its not possible to inherit H tags by this options like for all other crocoblock widgets here:
https://ibb.co/bgXX81W

For all other widgets of crorocblock and other thirdparty widgets its working. For slider widget we need to switch the logic to inherit font style and using global style. This have no reason and no logic.  
 
Its better to work in one workflow and in one logic and how all other crorocblock widgets working.

BR
Tommy

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-elements/tree/fix/sug%236516
