### ISSUE TITLE
JetEngine - Bug to Render Color in layout from Options page using dynamic tags

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#6519]
Hello everyone, after the last Elementor update a very important feature that I use is not working and I will explain it below, please analyze it with, because Elementor practically threw the responsibility to Crocoblock on JetEngine, although I suspect that the problem is not Be with us, but it's worth seeing and if you can help we would be very grateful! because there is a problem.

I recorded a video and I speak in Portuguese, but just by following along, any of you will be able to reproduce it, all plugins are updated according to the video, and I do a test on a newly installed website. it bugs others, and I also have friends who have the same problem.

https://eadvideos.vmaker.com/record/Fguy3VXm22biWtSS

Currently, when using options page to put focused metafields to automate the color process, it is not working when seen in the front-end, even using different fields like the colorpicker type or normal text field passing the hex of the desired color.

when using dynamic tags to retrieve the color value and using it in widgets it doesn't render anymore, it just stopped working something that always worked until Elementor updated to 3.11....

Another feature that works halfway is, when using the theme's Global Colors, it is now possible to use dynamic tags and get these colors from the Options page, we managed to register our colors there, when using the constructor and adding the global color style in widgets like title , text, icon and also background of sections, container and borders for example, in the builder part it works perfectly, however when we go to the front-end it loses all the style and becomes the default of the site.

Any questions I'm available to help them.

Here you can follow, because there is a topic with many comments open for months where there was no solution yet.
https://github.com/elementor/elementor/issues/20368

here is my most recent thread reporting the issue which was closed.
https://github.com/elementor/elementor/issues/21357

**Comment by morosmo** [comment]
+1

**Comment by kaskad88** [comment]
Hello @tizum. 
Unfortunately, we can't help you, this issue should be fixed by Elementor team in core plugin. Moreover, this issue manifests itself not only with JetEngine, but also with ACF and other dynamic plugins

**Comment by kaskad88** [comment]
But, you can use the JetEngine Option dynamic tag in widgets https://tppr.me/c2Nt8
