### ISSUE TITLE
JetEngine Calendar Widget - Start Calendar with Sunday Option

### ISSUE THREAD

**Issue by caracalcreative** [CrocoBlock/suggestions#6520]
The calendar widget starts the week with Monday. It is pretty standard for most calendars to start the week visually with Sunday. I'm surprised this wasn't a standard option already set in this widget from the start.
<img width="1416" alt="Screen Shot 2023-02-16 at 12 07 33 PM" src="https://user-images.githubusercontent.com/125596208/219451188-0c61d93f-5405-4770-b65c-93c0e164f73e.png">

**Comment by kaskad88** [comment]
Hello @caracalcreative.

The start of the week in the calendar widget depends on the global Wordpress setting `Week Starts On` https://tppr.me/2ALZX https://tppr.me/crIXO
