### ISSUE TITLE
jet woobuilder carousel > Space Between slides option

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6525]
Hi team.

In the product grid widget, there is a Space Between option in the carousel section. The current location of this option is slightly unavailable. I think it would be much better if this option was moved to the Style > Columns tab. **Because in this case, we will have access to both the padding option and the Space Between option in one place.**
Just like the loop grid widget in Elementor : https://prnt.sc/KRj5AHHbuv1o

**Please note that this option is displayed if the carousel is active.**

### In general, the product grid/category grid widget will be perfect as below.

First of all, it is better to rename the [column option](https://prnt.sc/rUTTe4E7XUMn) to **layout** in the style tab of this widget.

In general, it would be great if you could present the options in the Style > Column tab in a more intelligent way. What I think :

**A:** If the carousel is disabled, two options will be displayed in the Style > Columns tab :  &nbsp; **1- row gap** &nbsp;  &nbsp; **2- coulmn gap**
**B:** If the carousel is enable : &nbsp; **1- padding** &nbsp; &nbsp; **2- Space Between**

**Comment by UraraReika** [comment]
In our case Product Grid widget can be simple grid or carousel so we made distinctions between this layouts. And control Space Between initially  works as option for carousel config and then with the help of library script transformed to styles, that is why we  use it in the carousel controls sections.

**A:** Please track this issue - https://github.com/Crocoblock/suggestions/issues/6226
**B:** We have some widgets improvements in our roadmap so please stay tuned for updates

**Comment by Michaelgimii** [comment]
Hi @UraraReika, Thanks for the update.

>We have some widgets improvements in our roadmap so please stay tuned for updates.

So will the product grid widget be rebuilt as a grid in the near future? (row gap/column gap)
