### ISSUE TITLE
Jet Tricks: Unfold Widget: Official Site Demo Video is a Lie?

### ISSUE THREAD

**Issue by AkhilAniyan** [CrocoBlock/suggestions#6527]
Dear Team,

I installed Jet Tricks, just for the "Unfold Widget" after seeing your demo video (In the second section, auto-loop video) in your sales landing page: https://crocoblock.com/widgets/unfold/

But when I try to configure it the same way shown in the video, I found that it's not possible to achieve!

My requirements are simple:

1. I need the button should be JUSTIFIED (But I could find only left, right, and center options).
2. I want to place the button icon AFTER TEXT. By default, it's before the text.

The thing is, you are showing all these in that video.

**Example for First Requirement (Button Justification):** 

https://nimb.ws/bTvY14
https://nimb.ws/FMf8zT

Example for Second Requirement (Button Icon Position): 

https://nimb.ws/f1EPT8
https://nimb.ws/g8capz

Note: Please guide me if I'm doing something wrong and how I can achieve this.

Note: I'm using the latest version of Elementor, Elementor PRO, Jet Tricks, etc. I hold all the products of Crocoblock. But only Jet Engine, Jet Tricks, and Jet Blocks are Installed.

Thanks
Akhil.

**Comment by Floydtm** [comment]
I am sorry that this happened. We will try to fix this in the next updates of the plugin. In the meantime, you can add this css code
`.jet-tricks-icon {
    display: flex;
    order: 2;
    margin-left: 4px;
}
.jet-unfold__button {
    width: 100%;
    align-items: center;
    justify-content: center;
`

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-tricks/tree/fix/sug%236527

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
