### ISSUE TITLE
new widget for jet woo builder : woocommerce order tracker

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6529]
Hi

It would be great if you add a new widget to customize the woocommerce order tracker. Currently, if we add the woocommerce order tracker shortcode in the Hello Elementor theme, it is very simple and there is no possibility to customize it.

![woocommerce order tracker ](https://user-images.githubusercontent.com/103376243/220056547-57e458bb-4ee1-4d85-9dff-63945582d6c4.png)

**Comment by UraraReika** [comment]
Hello @Joliamendi and Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into the core of our plugin our plugin. In case if you really want to have some elementor controls over this order tracker I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/  

Thank you for your understanding.
