### ISSUE TITLE
Jet Smart FIlters - Select Field Drop Down Option sorting

### ISSUE THREAD

**Issue by KittyFolks** [Crocoblock/suggestions#653]
The options in the select dropdown are sorted randomly.
I would need the options to be sorted as they appear in the category list.
There are Main categories and sub categories - the subs are not sorted under the main cat.

Main cat
- sub
- sub
- sub
Main cat
- sub
- sub
etc

Is this something coming up soon?

**Comment by Floydtm** [comment]
@KittyFolks, Hi! Thank you for contacting. Our team has reviewed your request. Unfortunately, we will not be able to implement it now.
