### ISSUE TITLE
input in the popup will automatically activate the keyboard after the popup opens - Jet Search + Jet Smart Filters

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6533]
**Describe the bug**

Hi @Floydtm.

After updating Elementor Pro to version 3.11, there is a problem with some Jet widgets. I use the jet search widget in Elementor popup. When the user opens the popup, the search (jet search) widget activates the keyboard in mobile. Or as another example, we use the search filter (jet smart filters) in the Elementor popup. When the user opens the filters popup, the mobile keyboard is immediately activated. This has greatly affected ux...
**It should be noted that I experienced this bug with Android phone - Chrome browser.**

Is there any quick fix from you? Or should it be solved by Elementor? 

Thanks in advance

**Comment by Floydtm** [comment]
I did some tests with their search widget and got the same result. So I think I should leave it [here](https://github.com/elementor/elementor/issues)  But I see you already did it. Thank you!

**Comment by 79ho3ein** [comment]
thank you @Floydtm
