### ISSUE TITLE
JetEngine Minimum number of days depending on the month

### ISSUE THREAD

**Issue by dwajstak** [CrocoBlock/suggestions#6535]
Hello,
I use JetEngine and the business requires that the minimum number of booking days depends on the month. For example:
In May we can make a booking for a minimum of 3 days
In July we can make a booking for a minimum of 5 days

I managed to find such an event **datepicker-first-date-selected**, but I have absolutely no idea how to use it. I just wrote a function below to calculate minDays to be passed and updated in object configuration when first date is selected.
```javascript
function minDays(date) {
    const month = date.getMonth();
    const year = date.getFullYear();

    if (month === 1 && year % 4 === 0) {
        return 2;
    }
    if (month === 1) {
        return 3;
    }
    if (month === 3 || month === 5 || month === 8 || month === 10) {
        return 2;
    }

    return 1;
}
```
Please give me tips how I can update the minDays property after selecting the first date using the function to calculate these days. 
Unless I can do it another way?

BR

**Comment by UraraReika** [comment]
Hello @dwajstak! Thanks for the feedback.

Recently in 2.6.0 version of JetBooking plugin new date picker configuration options: min_days, max_days, start_day_offset. You can set this options globaly for all site, lockaly for separate booking instance and for seasons.
1 - go to booking instance post type and open it for edit. 
2 - add new seasonal price https://tppr.me/kPMOk
3 - name it set specific price enable config options and set them, don't forget to set season range - https://tppr.me/ZQ6Hd

After all this steps in the frontent page of this booking instance between season date range you will get apropriate config options.

If you want to make it globaly for all your booking instances then I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life  https://crocoblock.com/customs/  

Thank you for your understanding.
