### ISSUE TITLE
Scroll Navigation Widget- Add external link

### ISSUE THREAD

**Issue by ArcadyBe** [CrocoBlock/suggestions#6543]
Can you please add an external link function to the scroll navigation widget. At the moment the navigation is only possible within the page section. It would be useful to add an external link to other pages too...  Thanks

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
