### ISSUE TITLE
Add a pagination option to the User Query Builder - JetEngine

### ISSUE THREAD

**Issue by MJNinja** [CrocoBlock/suggestions#6552]
I am currently busy with a project where I need to show users on a website, but the information for these users isn't stored in a CPT (Custom Post Type) but is part of the Users section inside of WordPress. I've made use of the Meta Boxes feature inside of JetEngine to add additional meta boxes to the existing Users.

I then created a query inside of the Query Builder to get all the relevant users to display in a Listing Grid widget. In addition to this Listing Grid widget, I also need to add a Pagination widget, as there can be quite a lot of users displayed on the website.

I then noticed that there isn't a Pagination option inside of the User Query Builder, which I need to set up the amount of user per page the Pagination widget will work with.

![Pagination for User Query](https://user-images.githubusercontent.com/35722976/220943030-1e30e0c8-b01e-4ece-b229-0d9aaaaec340.PNG)

I wanted find out if this can be added, so that I can implement the Pagination widget with my User Listing Grid.

**Comment by MjHead** [comment]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/4987981/224931488-22d0b1a9-35bf-4e8d-a5e2-94306e556075.png">
Here is Number option. It works similar to Posts per page option for Posts query. To add pgination - you can just use Pagination widget from JetSmartFilters
