### ISSUE TITLE
Map listing cluster should open listings in a popup when they have the same address - JetEngine

### ISSUE THREAD

**Issue by MJNinja** [CrocoBlock/suggestions#6553]
I am currently busy with a project where I need to show posts from a CPT (Custom Post Type) in a Map Listing widget. I managed to get set everything up correctly, but then I encountered that when multiple listings have the exact same address, which in my use case can happen, just show a number that indicated the number of listings in that area, and when you click on it nothing happens.

If one spreads them out a bit more so that individual markers show, then when clicking on a marker, it opens a small popup with information, but it doesn't do that when it is a cluster number.

![Current Map Cluster](https://user-images.githubusercontent.com/35722976/220955179-e26b2782-f928-407a-ab86-588cbfbc05e8.PNG)

I wanted to found out if we can get an option when someone clicks on that cluster number, that we get a popup that shows all the listings that are in the area (it can even have a scroll inside the popup, should the content be a lot).

On a similar website that I developed, that made use of Dokan, they have this implemented and it it works perfectly.

![Map Cluster](https://user-images.githubusercontent.com/35722976/220955553-54964df9-603e-4338-acdf-11740840daaa.PNG)

Here is what the popup looks like when clicking on the number.

![Map Cluster Popup](https://user-images.githubusercontent.com/35722976/220955652-fafee482-9890-474d-a64b-a0b427be46e4.PNG)

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
Now you can enable [this](https://tppr.me/rQEx6) option, it should help in your case
