### ISSUE TITLE
[Bricks Builder] [jetEngine] Data store Function

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6556]
**Describe the bug**
1. The counter's numbers of the "Data store" feature are not instantly reflected when the user clicks on the 'data store' button, and the user needs to refresh the page to see the updated numbers.
2. There is no option to style the background of the 'active' data store button.

**Video**
https://user-images.githubusercontent.com/68687765/221518277-5a6b624b-e936-44cc-ab4d-6f14c6588a1b.mp4

**Desktop (please complete the following information):**
OS: [macOS]
Browser [chrome]
Version [110.0.5481.100]

**Comment by RagnarLodbrok94** [comment]
1. We didn't add the {cf_jet_engine_store_count_storename} tag. This is a native Bricks tag that just gets the value of the meta field.
When we add our tags, it will work.
2. [Controls added](https://prnt.sc/4pQL0QtzMuEl)

The 'active' data store button will be in the next release.
