### ISSUE TITLE
[Bricks Builder] [jetEngine] Dynamic Visibility Condition

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6557]
There are only a limited number of **Dynamic Conditions** available in **Bricks Builder**
For example, the following conditions are not available
1. Query has item
2. Is profile page
3. Is mobile device
4. Listing is even, is odd
5. Value is checked
6. Switcher condition

It would be helpful if JetEngine's **Dynamic Visibility Conditions** could be added.

**Comment by MjHead** [comment]
At the moment there is no API in Bricks to register custom conditions. If such API will appear - we'll add requested conditions

**Comment by pauserratgutierrez** [comment]
> At the moment there is no API in Bricks to register custom conditions. If such API will appear - we'll add requested conditions

Hi, just now Bricks has released a Conditions API in 1.8.4.

https://academy.bricksbuilder.io/article/element-conditions/#api

**Comment by sekhsoyebali** [comment]
+1

**Comment by pauserratgutierrez** [comment]
#6962
