### ISSUE TITLE
Archive Tags don't work for product variations

### ISSUE THREAD

**Issue by mbaierl** [CrocoBlock/suggestions#6558]
**Describe the bug**
For product variations the Archive Tags widget does not return any tags. 
It has to render the tags of the parent product, since there are none assigned to the variation product.

File: plugins/jet-woo-builder/includes/widgets/archive-product/jet-woo-builder-archive-tags.php
Function: render_callback (line 169)
Snippet:
`echo jet_woo_builder_template_functions()->get_product_terms_list( 'product_tag', $settings['count'] );`

File: plugins/jet-woo-builder/includes/class-jet-woo-builder-template-functions.php
Function get_product_terms_list (line 498)
Snippet:
`public function get_product_terms_list( $taxonomy, $count ) {`

This function has to get the parent product in case it's a variation.

Pseudocode:
```
if(is_a($product, 'WC_Product_Variation') {
 $product = $product->get_parent_product();
}
```

Please fix.

**Comment by UraraReika** [comment]
In the next release of the plugin we will present `'jet-woo-builder/template-functions/terms-list/' . $taxonomy` fillter hook that can help to handle such an issue.
