### ISSUE TITLE
Prohibited sign in disabled arrow / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6569]
On the desktop, if we put the mouse on the disabled arrow, the **forbidden sign** will be displayed. This is something that did not exist before the release of disabled mode. It doesn't even happen [here](https://swiperjs.com/demos#pagination-progress).
it would be great if you correct this behavior. **so that if we place the mouse on the disabled arrow, the prohibited sign will not be displayed.**
This is a very small but important item. thanks

**Comment by UraraReika** [comment]
This is additional and more clearly sign of disabled arrow so the user can be sure that this arrow is disabled for interaction. 
You can use this styles to disable it:
```
selector .jet-woo-carousel .jet-arrow.swiper-button-disabled {
    cursor: pointer;
}
```

**Comment by Michaelgimii** [comment]
thanks @UraraReika
About this issue, another request came to my mind, which I will raise in new issue.
