### ISSUE TITLE
Ability to choose Cursor type in Jet Woobuilder carousel disabled arrow.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6570]
In association with : https://github.com/Crocoblock/suggestions/issues/6569
It would be really great if you add a new Cursor option to the product grid widget so that we can select the Cursor type on the disabled arrow. **Currently, Cursor is set to not-allowed by default.**
But if you add this property, we can control Cursor in disabled arrow. In fact, we only need **3 types of Cursors**.

- pointer
- auto
- not-allowed

It is not difficult for you to add this feature. But it can be very important. This is one of the great advantages of jet woobuilder. Control over the smallest details.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
