### ISSUE TITLE
JetEngine / JetTabs Accordion Query Bug

### ISSUE THREAD

**Issue by gelenfarkas** [CrocoBlock/suggestions#6574]
**Describe the bug**
When I use JetTabs Accordion with Dynamic Query Builder, subsequent requests return an empty result for every Dynamic Jet Query everything that follows after that.

**Screenshots**
![image](https://user-images.githubusercontent.com/75224956/221881024-c810ecb9-eb36-4562-9431-1469e7d1338a.png)
![image](https://user-images.githubusercontent.com/75224956/221881689-de32295f-d1d5-42ae-af16-21b0a1050906.png)

**Version:**
JetEngine - Version 3.1.2
JetTabs - Version 2.1.21

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
