### ISSUE TITLE
JetElements - Links Broken In Flip Box

### ISSUE THREAD

**Issue by GazDog** [CrocoBlock/suggestions#6578]
If I update JetElements to 2.6.9 then the links break in the flip box. I roll back to the previous version 2.6.8 and all works well. 

**Describe the bug**
The link does not work in JetElements  2.6.9 flip Box

**Comment by Lonsdale201** [comment]
+1

**Comment by bazilik1095** [comment]
https://github.com/ZemezLab/jet-elements/tree/fix/issue%236578

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
