### ISSUE TITLE
Updating the swiper library breaks the product grid > carousel widget.

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6579]
If we enable swiper library update option in elementor settings, jet woobuilder carousel crashes.

**Comment by 79ho3ein** [comment]
Hi @Joliamendi

This is a recurring issue. You have covered this [here](https://github.com/Crocoblock/suggestions/issues/6498#issuecomment-1427736952) before!

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6498, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
