### ISSUE TITLE
[JetEngine Visibility Conditions]  Add woocommerce subscription status as Visibility Condition

### ISSUE THREAD

**Issue by knireis** [CrocoBlock/suggestions#6580]
It would be good to have the option the use the Woocommerce subscription status as a parameter for the visibility conditions settings in  JetEngine.

**Comment by tealou** [comment]
Not sure if you need help there, but you can do that by using User Role - Subscriptions changes user Roles automatically based on status, so if you configure that correctly it should work out of the box. You can create/edit user roles with User Role Editor.

**Comment by UraraReika** [comment]
You can solve this issue with the help of `User role` dynamic visibility option.
