### ISSUE TITLE
Two suggestions for improving the counters in the Categories Grid widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6584]
Hi

Please consider these two requests to improve the counters in this widget.

1- Custom position for the counter : 

![1](https://user-images.githubusercontent.com/77163248/222452650-0fa06217-1788-49df-9221-8c951ff1a3dd.png)

2- Absolute width and height for counter box : 

![2](https://user-images.githubusercontent.com/77163248/222452939-e348b362-c641-4158-842f-f6d0dc99796a.png)

For example, the box number 2 is much smaller than 50 or multi-digit numbers. This feature makes the size of the counter box equal for all numbers, which would be great.

thank you

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6347, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
