### ISSUE TITLE
JetEngine Dynamic Link widget: Link only applied to text

### ISSUE THREAD

**Issue by pauserratgutierrez** [CrocoBlock/suggestions#6589]
**Describe the bug**
The Dynamic Link widget only applies the a link to the text. If we add an icon, padding and any other thing, the only clickable area is the one that has text. In addition, if we only want an icon, the link doesn't work because there's no text.

**To Reproduce**
1. Add a Dynamic Link widget
2. Style it to have an icon, or padding or remove the text and keep only an icon
3. The link only applies to the text

**Expected behavior**
The link should be applied to the whole Dynamic Link widget, not only to the text. Or at least, give us the option to choose where we want to apply the link (Text, icon, whole div...)

**Screenshots**
![image](https://user-images.githubusercontent.com/73240206/222898652-533febf5-0a6d-4e8e-a975-96e9b5e5a156.png)

**Comment by sekhsoyebali** [comment]
+1
I tried the same thing and found that the link only applied to the text and not to the icon.
.....
But I found a different way to do this - 
`<a href="{site_url}/mensajes?r=%s"><img src="{site_url}/wp-content/uploads/image.jpeg">Chat</a>`

**Comment by MjHead** [comment]
Please use Dynamic Link widget. It puts icon and apply styles inside link - https://tppr.me/4hs0y On your screen there is Dynamic Field widget + customized output. With such setup all data inside Field format option replaces default content of the field. Icon added before the content and styles applied to common parent of icon and content.

If you need custom link which can't be created by Dynamic Link widget - the only way add the icon inside the custom HTML markup you added inside Field format option

**Comment by pauserratgutierrez** [comment]
> Please use Dynamic Link widget. It puts icon and apply styles inside link - https://tppr.me/4hs0y On your screen there is Dynamic Field widget + customized output. With such setup all data inside Field format option replaces default content of the field. Icon added before the content and styles applied to common parent of icon and content.
> 
> If you need custom link which can't be created by Dynamic Link widget - the only way add the icon inside the custom HTML markup you added inside Field format option

Hi, thanks for your reply. I can't use the Dynamic Link widget because the data I need isn't outputed in the widget. It's data from a Custom SQL Query from Query Builder, which is only accessible using the Dynamic Field Widget and not the Dynamic Link:
Dynamic Field:
![image](https://user-images.githubusercontent.com/73240206/230895866-9a8223df-ff7e-4ab5-af71-fe224f707810.png)

The Dynamic Link doesn't have the Query and data I need to select...
In Source I can't select "Post, Term, User, Object data", and then, I can't select "chat_amb_user_id" for object field because it's not there.
