### ISSUE TITLE
JetEngine Dynamic Visibility for Bricks Builder

### ISSUE THREAD

**Issue by pauserratgutierrez** [CrocoBlock/suggestions#6590]
Bricks builder has dynamic visibility, but we can't perform checks based on query builder loops and based on data from external crocoblock dynamic things. Would be cool to be able to use all Crocoblock's Dynamic data in the native bricks builder dynamic visibility, as well as also be able to use the native JetEngine Dynamic Visibility for widgets and sections in Bricks.

**Comment by sekhsoyebali** [comment]
+1

**Comment by pauserratgutierrez** [comment]
Another similar issue: https://github.com/Crocoblock/suggestions/issues/6557

**Comment by MjHead** [comment]
At the moment there is no API in Bricks to register custom conditions. If such API will appear - we'll add requested conditions

**Comment by pauserratgutierrez** [comment]
> At the moment there is no API in Bricks to register custom conditions. If such API will appear - we'll add requested conditions

Hi, just now Bricks has released a Conditions API for developers in 1.8.4

https://academy.bricksbuilder.io/article/element-conditions/#api

**Comment by RuanPienaarCode** [comment]
+1

**Comment by pauserratgutierrez** [comment]
> At the moment there is no API in Bricks to register custom conditions. If such API will appear - we'll add requested conditions

Hi, just a headsup, the conditionals API for Bricks was added in 1.8.4: https://academy.bricksbuilder.io/article/element-conditions/#api
