### ISSUE TITLE
Full size menu gets glitchy on desktop when browser window is resized a small amount. 

### ISSUE THREAD

**Issue by brianlichty** [CrocoBlock/suggestions#6601]
**Describe the bug**
Full-size menu gets glitchy on desktop when a browser window is resized a small amount. See this video to see the issue.

https://www.dropbox.com/s/h3mp6n2chhbvrq9/2023-03-07_12-19-13.mp4?dl=0

**To Reproduce**
This is my dev but you can take a look here for a bit. 
https://brianl180.sg-host.com/
Just use a decent-sized browser window and then just make it slightly larger (or smaller) to see the problem.

**Expected behavior**
When resizing a browser window a small amount I would expect the menu to adjust without having to refresh the browser.
Certainly, it should not roll off the end of the window.

**Screenshots**
https://www.dropbox.com/s/h3mp6n2chhbvrq9/2023-03-07_12-19-13.mp4?dl=0

**Desktop (please complete the following information):**
 - OS: Mac/PC anything
 - Browser All Browsers
 - Version N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Thanks!

**Comment by shinTM** [comment]
@RagnarLodbrok94 тут треба консольлогати, так хз чого в нього не вірно бере відступ

**Comment by brianlichty** [comment]
> тут треба консольлогати, так хз чого в нього не вірно бере відступ

Not sure what you mean by "there is a need for console log, so why don’t you take access in the new" I am not a developer, I am just hoping to get the menu to respond correctly, thank you!

**Comment by Floydtm** [comment]
@brianlichty don't worry, this comment was not addressed to you. We will try to solve your question. Thank you!

**Comment by brianlichty** [comment]
> @brianlichty don't worry, this comment was not addressed to you. We will try to solve your question. Thank you!

@Floydtm Hi - I was wondering if you had a solution yet? Any luck?

**Comment by Crocoblock** [comment]
Hi @brianlichty 

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.

We apologize for the delay and thank you for your understanding.

**Comment by brianlichty** [comment]
> Hi @brianlichty
> 
> We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
> 
> We apologize for the delay and thank you for your understanding.

Maybe because my comment was from a year ago and we've deactivated your plugin and moved on?
