### ISSUE TITLE
Ability to Change icon and spacing of icon in select filter

### ISSUE THREAD

**Issue by morosmo** [CrocoBlock/suggestions#6605]
**Describe the bug**
![image](https://user-images.githubusercontent.com/87468744/224002342-d47226ad-72cb-4837-9783-cc8d2163061a.png)

**To Reproduce**
1. Go to 'jetsmart filters'
2. Create a Filter
3. Drop select filter widget on frontend
4. No option to change or replace icon
5. See error

**Expected behavior**
I am facing this issue from very start as there is no option or no class assing to select field chevron. We are not able to change spacing from right. Please add this ad also addd a field to pick custom icon. 

Thanks

**Desktop (please complete the following information):**
 - OS: [Window 11]
 - Browser [Chrome
 - Version [Latest]

**Comment by Picrold** [comment]
+1000

**Comment by morosmo** [comment]
@Floydtm @SargasTM @SargasTM Any Update on this things as its too complicated to handel with css?
