### ISSUE TITLE
Enable link to product from featured image using Product List widget

### ISSUE THREAD

**Issue by dollhauss** [Crocoblock/suggestions#661]
Feature request to link to a product by clicking the featured image while using the Product List module.

Link to product from featured image works in the Product Grid and Product loop widgets, but not on the Product List widget.

Do you possibly have a filter for this?

**Comment by UraraReika** [comment]
Done. Next Release.

**Comment by dollhauss** [comment]
Fantastic news! ;-)
Thanks!
