### ISSUE TITLE
Make JetBooking booking status editable for custom dashboard

### ISSUE THREAD

**Issue by Helmchen77** [CrocoBlock/suggestions#6616]
For a custom booking dashboard, JetBooking lacks the ability to adjust the status accordingly. JetBooking uses different status parameters than regular posting. Please add a possibility to edit the status under JetBooking.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.

**Comment by Wsmayfreelancer** [comment]
Hello.. 
Edit Booking Status

You mean change The Names?

**Comment by UraraReika** [comment]
> Hello.. Edit Booking Status
> 
> You mean change The Names?

You can change status here - https://tppr.me/bHE0H like this https://tppr.me/FCYPg and result https://tppr.me/22BzG

**Comment by dalexdesigngroup** [comment]
Hey @UraraReika - We are looking at a similar need. We have a 2 sided marketplace, we need a way to show customers their upcoming bookings, as well as show our hosts the bookings they have each day. We do not want to give backend access to anyone other than our staff to look at bookings.

It also makes sense that if this is a "Booking" plugin, we should have the option to "Check-In / Check-Out" the booking as well as archive past bookings so the data is not lost but it does not create a super long list of bookings - this gets very messy

**Comment by UraraReika** [comment]
> We are looking at a similar need. We have a 2 sided marketplace, we need a way to show customers their upcoming bookings, as well as show our hosts the bookings they have each day. We do not want to give backend access to anyone other than our staff to look at bookings.

Please follow this issues - https://github.com/Crocoblock/suggestions/issues/6009 and this one https://github.com/Crocoblock/suggestions/issues/6491 they are similar to your request.

> It also makes sense that if this is a "Booking" plugin, we should have the option to "Check-In / Check-Out" the booking as well as archive past bookings so the data is not lost but it does not create a super long list of bookings - this gets very messy

We will take a closer look at this request.
