### ISSUE TITLE
[Jet Booking and Jet Engine] Few suggestions for booking for tour operators and rentals.

### ISSUE THREAD

**Issue by asteriskoit** [CrocoBlock/suggestions#6617]
Hey guys, few requests to make the booking (and forms) more complete...

-In the Booking Settings, allow also a custom duration for each "product", not only a day-booking or a week-booking. 
Would be nice if check-in/check-out dates could dynamically fill up based of the selected service duration. (e.g. if i set that the tour is standard 5 days, when booking form is filled, if check-in returns 20/05, then check-out automatically fills with 24/05 etc.)

-on one-day bookings, please REMOVE the check-out option in the form "checkinout" widget as it confuses people while filling the form

-In the booking pricing, allow to differenciate categories of pricing with a repeater (e.g. allow to put an adult price, a children price etc.)

-Better connection with woo-commerce: one Product is created (booking) and it connects with the Booking selected CPT (in my case, tours). This means that i have no control on the product itself and then any woo-commerce product based plugin (for example woo-commerce DEPOSITS) will not work. Either implement this missing function within the jet booking plugin (the ability to select the possibility to book by paying a deposit fee) or within jet forms, please. It could also be a widget for woo builder inside the check-out widgets. If there was also the possibility to conditionally display the deposit based on selected check-in dates, that'd be awesome (eg. i selected a tour that departs in 25 days / the deposit payment does not display and im forced to check-out paying the full amount -- i selected a tour that departs in 40 days / the deposit payment displays alongside with the full payment and i can choose which one to pay ). 

<img src="https://yithemes.com/wp-content/uploads/2022/07/YITH-Deposits-Down-Payment-WooCommerce-Booking-Deposit.jpg">

For rentals/tour websites it's VITAL to have the possibility to require a down-payment to reserve a service.

-Include within JET FORMS a field for acceptance, as most countries legally require a privacy policy/ terms&conditions to be accepted before sending a form. This is doable only by using a checkbox field, but the label field in the checkbox are not really HTML friendly. Even elementor forms have that option.

Ideally, would be nice to have almost all YITH booking and YITH Deposits - Downpayments features as the Crocoblock package is AMAZING but lacks a lot on the booking section.

**Comment by loran750** [comment]
I do support this feature !

**Comment by loran750** [comment]
same !!! mandatory !

**Comment by Rikardo01** [comment]
Me to

**Comment by UraraReika** [comment]
> In the Booking Settings, allow also a custom duration for each "product", not only a day-booking or a week-booking.
> Would be nice if check-in/check-out dates could dynamically fill up based of the selected service duration. (e.g. if i set that the tour is standard 5 days, when booking form is filled, if check-in returns 20/05, then check-out automatically fills with 24/05 etc.)

Unfortunately this type  of functionality will not be directly added to the plugin core. But you can use our API to extent it functionality - https://gist.github.com/Crocoblock/0d73be0a11b07fa24c1490f5ad7d0d3a. Here is example:

```php
add_action( 'wp_footer', function() { ?>
  <script>
  	const daysNumber = 5; // Duration number.
  
        // For forms field.
        jQuery( document ).on( "jet-booking/init-field", ( $event, $field ) => {
            const format = window.JetABAFInput.field_format || "YYYY-MM-DD";
  
            $field.bind( "datepicker-first-date-selected", ( event, obj ) => {
                $field.data("dateRangePicker").setEnd( moment( obj.date1 ).add( daysNumber, "d" ).format( format ) );
            } );
        } );
  
        // For calendar widget.
        jQuery( document ).on( "jet-booking/init-calendar", ( $event, $calendar ) => {
            $calendar.bind( "datepicker-first-date-selected", ( event, obj ) => {
                $calendar.data( "dateRangePicker" ).setEnd( moment( obj.date1 ).add( daysNumber, "d" ).format( "YYYY-MM-DD" ) );
            } );
        } );
  </script>
<?php } );
```

You can add it to your child theme `functions.php`.

**Comment by UraraReika** [comment]
> on one-day bookings, please REMOVE the check-out option in the form "checkinout" widget as it confuses people while filling the form

The parameters of this widget do not depend on calendar configurations and settings. Instead, the widget presents all possible options that can be customized.  Also, some of the options are available both globally and individually for individual apartments, and the field widget settings in the form are common to all apartments. Therefore, the settings will remain as they are.

**Comment by girafffee** [comment]
> Include within JET FORMS a field for acceptance, as most countries legally require a privacy policy/ terms&conditions to be accepted before sending a form. This is doable only by using a checkbox field, but the label field in the checkbox are not really HTML friendly. Even elementor forms have that option.

With the recent update of JetFormBuilder 3.2, a new [Advanced Choices Field](https://jetformbuilder.com/features/advanced-choices-field-block-overview/) block has appeared.

This field is ideal for static options that contain html markup.
Here's an example of how you can implement the Acceptance field with Advanced Choices Field:

(paste this into your Block Editor)
```html
<!-- wp:jet-forms/choices-field {"allow_multiple":true,"name":"acceptance","required":true,"style":{".jet-form-builder-choice\u002d\u002ditem":{"border":{"width":"0px","style":"none"}}}} -->
<!-- wp:jet-forms/choice {"value":"1","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}}} -->
<!-- wp:jet-forms/choice-control {"label":"Do you confirm with our \u003cstrong\u003e\u003ca href=\u0022#privacy-policy\u0022 data-type=\u0022internal\u0022 data-id=\u0022#privacy-policy\u0022\u003eSupport Policy\u003c/a\u003e\u003c/strong\u003e?"} /-->
<!-- /wp:jet-forms/choice -->
<!-- /wp:jet-forms/choices-field -->
```
Result:

![image](https://github.com/Crocoblock/suggestions/assets/46720998/a4d270bf-ffd0-491b-ad5a-4b803e2c134f)

![image](https://github.com/Crocoblock/suggestions/assets/46720998/535068b0-2781-47ed-ac6a-4093f22e9e7b)

**Comment by UraraReika** [comment]
> In the booking pricing, allow to differenciate categories of pricing with a repeater (e.g. allow to put an adult price, a children price etc.)

Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

There is also an existing solution: use the calculate field in which you can set the appropriate formula based on the data selected in the fields about the number of children and the number of adults, as well as any other category of people. Using the `%ADVANCED_PRICE::_check_in_out%` macro to get the total price with all price settings, then use the usual math to calculate the percentage of this price for the selected category of guests and multiply by the number of these guests. Do this for each category if it has a discount, and sum everything up.

You although can  [contact](https://support.crocoblock.com/support/home/ ) our support team and they will help you to do that.

> -Better connection with woo-commerce: one Product is created (booking) and it connects with the Booking selected CPT (in my case, tours). This means that i have no control on the product itself and then any woo-commerce product based plugin (for example woo-commerce DEPOSITS) will not work. Either implement this missing function within the jet booking plugin (the ability to select the possibility to book by paying a deposit fee) or within jet forms, please. It could also be a widget for woo builder inside the check-out widgets. If there was also the possibility to conditionally display the deposit based on selected check-in dates, that'd be awesome (eg. i selected a tour that departs in 25 days / the deposit payment does not display and im forced to check-out paying the full amount -- i selected a tour that departs in 40 days / the deposit payment displays alongside with the full payment and i can choose which one to pay ).

This issue can be solved by using a booking mod based on WooCommerce, then you can use all the applications related to it. Right now this approach of booking a bit limited but will developed to something more with time.

Thank you for your understanding.
