### ISSUE TITLE
JetBlocks Breadcrumbs: php8 error

### ISSUE THREAD

**Issue by computerfreak84** [CrocoBlock/suggestions#6618]
JetBlocks Breadcrumb widget gives me the following error when using php8 in woocommerce categories:

Warning: Trying to access array offset on value of type bool in serverpath/wp-content/plugins/jet-blocks/includes/modules/breadcrumbs/cherry-x-breadcrumbs.php on line 793

Latest versions of woocommerce, wp and everything. I can only solve it by going back to php 7.4

**Comment by Floydtm** [comment]
@computerfreak84, hi! Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by computerfreak84** [comment]
Hello, I have since found out that the error only happens when the following plugin is active and PHP version is 8 or newer.

Product Feed Manager – WooCommerce to Google Shopping, Social Catalogs, and 170+ Popular Marketplaces
By [RexTheme]

https://wordpress.org/plugins/best-woocommerce-feed/

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know.
