### ISSUE TITLE
Repeater Fields (Dynamic Data Addon) for Accordion Widget

### ISSUE THREAD

**Issue by Sayeed1440** [Crocoblock/suggestions#662]
Hi there,

I was planning to have a FAQ section in my course pages (single course page, completely dynamic). The idea was to offer the client to add FAQ questions as per his needs (2,4,6,10 etc.).

The best possible way was to do it through repeater fields and accordion widget. However, I see the accordion widget doesn't support dynamic data addon. 

I would request you to add this feature to the accordion widget too. 

Thank You

**Comment by stasonua0** [comment]
+1

**Comment by kaskad88** [comment]
Added an ability with JetTabs 2.1.6 and JetPlugins Dynamic Data Addon 1.3.0 ( https://github.com/ZemezLab/jet-elements-dynamic-data )
