### ISSUE TITLE
About Appointment and booking Capacity for not user.

### ISSUE THREAD

**Issue by Serqana** [CrocoBlock/suggestions#6620]
Appointment and booking Capacity for not user. İ need capacity for number of people.. for example one user make booking for 5 person. Total capacity for example 10 person. When capacity full. Systems warning to how many persons can make for booking and stop booking.

Also i wish that one solved as soon as possible. Because of my client waiting my project after 2 weeks later.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5948, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
