### ISSUE TITLE
bug in the checkout page (coupon form) - jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6627]
Hi

When the checkout page is loaded, the coupon form is first open and after the page is fully loaded, it is closed. I checked this in some themes (woocommerce) and they did not have the same problem.
This is especially evident in the desktop browser (Chrome).

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by Michaelgimii** [comment]
@Floydtm, As you know, on the checkout page, the coupon form is closed by default. When we click on it, it will open and the coupon form will be displayed. But when the checkout page is loaded (or even if we reload it), the coupon form first opens for about 1 second and then closes.
But this problem does not exist in other themes. So I think the rendering of coupon form part in Jet woobuilder has a little problem. Because it behaves differently when the page is loaded (first it is open for about 1 second and then it closes)

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
