### ISSUE TITLE
Jettricks Tooltips dynamic shortcode not working in latest version(s)

### ISSUE THREAD

**Issue by CaseFixedWebdesign** [CrocoBlock/suggestions#6635]
**Describe the bug**
I have a listing item (jeteninge) with a tooltip on hover. It loads an Elementor section (containing dynamic data) with a dynamic shortcode  like [elementor-template id="123"]. It loads just fine in Jettricks version 1.4.1. but does not 'load' when using 1.4.2 or 1.4.3

**To Reproduce**
1. Go to Jetengine to create a listing (image) with tooltip to an elementor section.

**Expected behavior**
I expect the shortcode to load as it does in 1.4.1

**Desktop (please complete the following information):**
- Elementor 3.11.5
- Elementor pro 3.11.6
- Wordpress 6.1.1.
- Jetengine 3.13.1
- Jettricks not working in 1.4.2 and up

example on https://mirjamkrowinkel.nl (working now, but not when updating jettricks)

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
