### ISSUE TITLE
[Bricks Builder] Profile Builder Compatibility

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6640]
Hello Croco team,
Please add Profile Builder compatibility with Bricks Builder. 
The Single user template option in the profile menu widget is not working in Bricks Builder.

**Comment by RagnarLodbrok94** [comment]
Hi.
To see the User Page tab, you need to return to the Pages tab. If you enable the Single user page option, the User Page tab will appear.

The single user profile menu will only be available on the Single User Page.
Pages -> Single User Page (or User Page -> Template).
So don't try to display a single user profile menu on any page.

I checked this on my local project:
https://prnt.sc/vaxe8TZFL2d8
https://prnt.sc/SFpxesjEkixj
https://prnt.sc/Q816EK99Towv

This docs about JetEngine: User Profile Builder Overview:
https://crocoblock.com/knowledge-base/articles/jetengine-user-profile-builder-overview/
