### ISSUE TITLE
bug in jet smart filters 3.1.0 > URL Structure Settings UI (only in RTL)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6644]
Hi @Floydtm 

In the URL Structure Settings section, there is a problem displaying the buttons. This problem only occurs on RTL websites.

in LTR : https://prnt.sc/OBJFWdk83Gne

in RTL : https://prnt.sc/LBwaFsdHC6-E

thank you

**Comment by SargasTM** [comment]
Done
Will appear in version 3.1.1

**Comment by 79ho3ein** [comment]
thanks❤
