### ISSUE TITLE
Load More(JetEngine)

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#665]
https://abroadinsights.com/cultural-events/europe/   . 
1. Refresh the page. If I set the filter/filters so that there is only one match, the "Load More button" is still there even is there is nothing more that can be "Loaded more";
2. Refresh the page. If I use use the "Load More" button to display all events, then use any filter, then use the "Remove all filters" button, the "Load More" button do not reappear.

**Comment by Biblothecaire** [comment]
+1

**Comment by ocbroadband** [comment]
Same Issue..
https://dev.ocsoa.info/events/

**Comment by ocbroadband** [comment]
Any headway on this?

**Comment by WildHund** [comment]
We are currently working on fixing this issue. Please stay tuned in order to find out when it will be solved. Thank you!

**Comment by ocbroadband** [comment]
Thanks for the reply, appreciated.

**Comment by kaskad88** [comment]
Fix for the next version (2.2.0).
Thanks for your report!
