### ISSUE TITLE
JetFormBuilder Form Widget for Bricks Builder

### ISSUE THREAD

**Issue by pauserratgutierrez** [CrocoBlock/suggestions#6651]
Right now, the only way to add a JetForm to Bricks is by using the shortcode widget provided by bricks. That usually works perfectly, but the design cappabilities are limited to CSS only (or JetStyleManager). I suggest to make the JetEngine / JetFormBuilder Widget with Bricks Builder so we can style everything using the builder (like in Elementor).

**Comment by sekhsoyebali** [comment]
+1

**Comment by girafffee** [comment]
Hi everyone)
This feature was included in 3.2.0 version
