### ISSUE TITLE
[Chart Builder] Add meta data support for columns

### ISSUE THREAD

**Issue by MaxFanov** [CrocoBlock/suggestions#6654]
Currently the columns only allow for the default data that a post has,
My request is simple (but probably not simple to implement) I'd like to have the option to add columns with meta data, for instance I have a post type (made by jet post types) which has meta data of views and I'd like to have an option to build the charts with that numeric data.

I think this feature will enhance jetEngine and align the items to a standard and have a more complete eco system (if jetEngine allows me to create meta data for posts, why not let me use it in the other modules?)

**Add an example of where this feature is already implemented. **
IMO only in custom code, but I haven't seeked for any other packages.

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 
Chart builder > columns.

**Comment by kaskad88** [comment]
Added in 1.0.6 version
