### ISSUE TITLE
[Bricks Builder] [jetEngine] Profile Menu Widget Bug

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6655]
**Describe the bug**
The "Single user page's menu" of "Profile Menu widget" is not showing on page in Bricks Builder.

**Account Page Menu**
<img width="1305" alt="Account Page Menu" src="https://user-images.githubusercontent.com/68687765/227220041-c8a43167-c424-491d-bbee-b24cb6414fdf.png">
**Profile Page Menu**
<img width="1305" alt="User Page Menu" src="https://user-images.githubusercontent.com/68687765/227220131-3a9623ac-6ecb-4754-adc3-8e77ce431ed0.png">
**Issue Video**
https://user-images.githubusercontent.com/68687765/227219862-de0f4892-f683-46af-be61-a1a5c1b630ac.mov

**Desktop (please complete the following information):**
OS: [macOS]
Browser [chrome]
Version [110.0.5481.100]

**Comment by RagnarLodbrok94** [comment]
Hi.
To see the User Page tab, you need to return to the Pages tab. If you enable the Single user page option, the User Page tab will appear.

The single user profile menu will only be available on the Single User Page.
Pages -> Single User Page (or User Page -> Template).
So don't try to display a single user profile menu on any page.

I checked this on my local project:
https://prnt.sc/vaxe8TZFL2d8
https://prnt.sc/SFpxesjEkixj
https://prnt.sc/Q816EK99Towv

This docs about JetEngine: User Profile Builder Overview:
https://crocoblock.com/knowledge-base/articles/jetengine-user-profile-builder-overview/

**Comment by sekhsoyebali** [comment]
When we use a non-existent username in the URL, like I did with the name 'tese,' it shows a "critical error" or "Blank Page".
<img width="1470" alt="Screenshot 2023-04-01 at 2 30 09 PM" src="https://user-images.githubusercontent.com/68687765/229276632-be410dbf-44e4-4a35-9dcd-5721269e5559.png">
