### ISSUE TITLE
Ability to change the color of the product thumbnail for products that are out of stock in jet woobuilder.

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6668]
Hi

It would be great if you add this feature to Jet woobuilder so that products that are out of stock will change (darken) the color of the thumbnail in these products. This makes users understand at first glance that this product is out of stock.

This feature is required for product grid and product list widgets.

**Comment by moxet** [comment]
@Joliamendi i am not sure exactly but did you tried dynamic visibility to show different (darker) thumbnail if stock of current product is 0

**Comment by Joliamendi** [comment]
> @Joliamendi i am not sure exactly but did you tried dynamic visibility to show different (darker) thumbnail if stock of current product is 0

@moxet yes, but we can't use this feature in jet woobuilder.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/2407, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
