### ISSUE TITLE
Text prefix for single price widget - jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6671]
Hi team

It would be great if you could add this option so we can add a text next to the price (single price widget). Like this picture.

![1](https://user-images.githubusercontent.com/88034902/228231893-9252d7e0-80ac-4fb5-867a-32f1acd6b48a.png)

Please add this feature. It is very useful. thanks

**Comment by UraraReika** [comment]
Unfortunately we will not add such functionality to our plugin or widget. In our Single Price widget we use default WooCommerce method that print price template `woocommerce_template_single_price()` and in this case you can simply override this template - wp-content/plugins/woocommerce/templates/single-product/price.php.

You will find a hint how to do it in the comment of this file.
