### ISSUE TITLE
Editing records from listings in popup directly on the page

### ISSUE THREAD

**Issue by LevelUpGit** [CrocoBlock/suggestions#6673]
Extend possibility of editing Posts/CCT by using Forms in JetPoup, but without having to have seperate editing page (Right now we have an a option to edit in popup but only single pages LaborTime [example](https://crocoblock.com/dynamic-templates/labortime/)). This means when we have record listings made via listing or table builder, and row with "Action" button, when we click it should open popup in existing page to edit that particular row see screenshoot bellow.

![Screenshot_3](https://user-images.githubusercontent.com/69863985/228288137-ef368f29-ba74-4abe-89c9-5e6ff4fb6263.jpg)

**Comment by MjHead** [comment]
You already can do this.
- Set up JetPopup for listing item by this instruction - https://crocoblock.com/knowledge-base/articles/jetpopup-how-to-build-a-dynamic-popup-to-work-with-jetengine-listings/ For table all the same, you just need to use template Listing Item template with PopUp trigger as content for the table column
- Add the form for editing the post into PopUp content.
- Set up of the form should be the same like for editing single post - https://jetformbuilder.com/features/insert-update-post/#how-to-update-post-via-form

**Comment by LevelUpGit** [comment]
I appreciate your answer, but we couldn't get it to work with CCT.

**Comment by MjHead** [comment]
You can try to add this code into functions.php or with some snippets plugin:

```php
add_action( 'jet-engine/compatibility/popup-package/get-content', function() {
	if ( ! empty( $_POST['data']['postId'] ) ) {
		$_GET['_item_id']     = $_POST['data']['postId'];
		$_REQUEST['_item_id'] = $_POST['data']['postId'];
	}
} );
```

And then change form setup to get required data from Query variable

<img width="653" alt="image" src="https://user-images.githubusercontent.com/4987981/228806865-0d8eacf7-a0f8-4334-b0a5-8cb74c26edd3.png">

<img width="958" alt="image" src="https://user-images.githubusercontent.com/4987981/228807090-42531adc-2cc0-41cd-99d4-a893a471d928.png">
