### ISSUE TITLE
Create a JSON formatted "settings field" for CCTs.

### ISSUE THREAD

**Issue by DarylMeese** [CrocoBlock/suggestions#6677]
Having a single field where settings and variable data could be stored in JSON format for a CCT would increase the flexibility and scalability of the CCT system. Furthermore, it would make it easier for users to experiment with different ideas/requirements without touching the actual database structure.

**Comment by MjHead** [comment]
Hi! I got your point, maybe later we'll add such functionality as DevTool addon. Because adding such logic into core will cause a nightmare with filtering the data stored in such way

**Comment by DarylMeese** [comment]
I wouldn't even make this field filterable. Just communicate this is a
"settings" field, it is for values used more "behind the scenes."

For example, I have a "discount card" CCT. It has fields such as number of
stamps, active stamp image, and inactive stamp image. None of those fields
will ever need to be filtered on.

BTW, you guys do great work and I pray for your safety and victory every
day.

Daryl
