### ISSUE TITLE
recurring payments via stripe

### ISSUE THREAD

**Issue by macpheek1** [CrocoBlock/suggestions#6679]
Hi, it would be great if I could collect recurring subscription payments via stripe. This is the only thing stopping my client from using your plugin at the moment, and I think your plugin will make their website so much better, so it's a shame! I hope you can implement this feature

**Comment by Lonsdale201** [comment]
+1

**Comment by sekhsoyebali** [comment]
+1

**Comment by Galph** [comment]
+1

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on it https://github.com/Crocoblock/suggestions/issues/6293
