### ISSUE TITLE
Feature Request: JetEnging - Dynamic Link media meta field type support

### ISSUE THREAD

**Issue by mlo520** [Crocoblock/suggestions#668]
Hello, 
I love the **Hide if value is empty** function of Dynamic Link widget. I wanted to it use it to show/hide a listing of download links of **media files**, but I realize it only works with text meta field. It would be awesome if it will support the media field. This way we can have a download function and have better visibility control whether the post has the media files or not.

Many thanks!
Mike

**Comment by Floydtm** [comment]
@mlo520, Hi! You are better off using a dynamic repeater widget. example http://prntscr.com/pwxffo http://prntscr.com/pwxfn8 http://prntscr.com/pwxfvf
