### ISSUE TITLE
JetAppointment schedule - add an extra day and working hours apart from from working hours

### ISSUE THREAD

**Issue by enfoucer** [CrocoBlock/suggestions#6680]
Hello, JetAppointment - is there a way to make schedule for doctor in this particular scenario:

- John works every monday from 10:00-12:00 (set up in Work Hours).
- However, from time to time, he comes over on thursday or friday (or other day) - 15:00-17:00.

Is there a way to set up Work Hours for every monday (cycle in Work Hours) and just add this extra day in an easy way?
Instead of using working days, one by one, to set up every day from scratch or multiple days off to achieve same thing?

**Comment by MjHead** [comment]
If you need to override specific days on regular basis, you can use working days settings. If you need override only specific days - you can use this option and add days you want
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/4987981/228828908-db2d496e-8dc7-438a-9ba5-e0dd21ebe48e.png">

**Comment by enfoucer** [comment]
I know those settings, but I need to add a single day that is not on regular basis as well - keep both.
For example:
I want to keep on regular basis only mondays 10:00-12:00 (every week) but be able to add an extra single day as well - 11th of April. But not every tuesday - only once, this time only.
Screen attached.
![Zrzut ekranu 2023-03-30 o 17 22 55](https://user-images.githubusercontent.com/129390972/228885210-17e42929-b447-4411-97c3-dd89526d1ac0.png)
