### ISSUE TITLE
Video player - movie chapters

### ISSUE THREAD

**Issue by magdakubis** [CrocoBlock/suggestions#6682]
Would be great if either the video player widget or the video playlist widget could playback timed video links. Both YouTube and Vimeo have the ability to share links to specific point in time of the videos. Both platforms suport timed links, so that you can start watching a video from a specific timestamp. Unfortunately the Video Playlist widget will not play these links from the timestamp but rather start them from the beginning of a movie. I have a platform where I share tutorials - I'd be nice to be able to include a list of video chapters so that the user can click on the chapter and the video would start from that point. Thanks.

**Comment by magdakubis** [comment]
![Uploading Screenshot 2023-03-30 at 1.46.50 PM.png…]()

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by magdakubis** [comment]
Cant wait!

I can test :)


Pozdrawiam, 

Magda Kubiś
Akademia Tortu
me.com/akademiatortu
