### ISSUE TITLE
Bring "GET PRODUCT ID FROM" to the Apartment Booking Action - JetBookings / JetForms

### ISSUE THREAD

**Issue by dalexdesigngroup** [CrocoBlock/suggestions#6686]
<img width="1082" alt="Screen Shot 2023-03-31 at 1 13 30 PM" src="https://user-images.githubusercontent.com/84207663/229198846-f0efb435-92bc-44da-b887-60e2af46b8f8.png">

The JetForm Builder has the "Add to Cart/ Redirect" add-on which has very useful features for booking based marketplaces however this add-on does not properly link the woocommerce order to the booking ( bookings places with this add-on enabled show no related order )

Adding these features directly into the WooCommerce integration of the Apartment Booking settings would allow us to selected the correct product for that booked item, while keeping the woocommerce related order correctly linked. 

Hopefully this would also help us become closer to resolving the issues we are having with the Condition Event "gateway.sucess" not working for woocommerce integrations.

**Comment by MjHead** [comment]
Now JetBooking has a direct integration with WooCjmmerce and can be used without JetFromBuilder. Looks like this is the case you need
