### ISSUE TITLE
[Bricks Builder] [jetEngine] Bricks Popup not Working for Listing Grid

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6687]
Describe the bug
The Native Bricks's Popup is not working for Listing Grid. I added click interaction on button and set target popup on Listing Grid but in the output, it is not working.

Desktop (please complete the following information):
OS: [macOS]
Browser [chrome]
Version [110.0.5481.100]

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know and describe your request in more detail, if possible, add screenshots or video. Thank you!
