### ISSUE TITLE
[Bricks Builder] [jetEngine Profile Builder] Issue with 'user nicename' page rewrite

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6688]
Describe the bug
The user nicename is not working in the 'user page rewrite' setting on the Profile Builder module of JetEngine. When I try to access the profile page with the URL of the user nicename, a blank page is shown. You can also check the attached video for clarification.
[https://drive.google.com/file/d/1sjjfQIg793GnmeTeYCEkQNWPQkV2AkNR/view?usp=sharing](https://drive.google.com/file/d/1sjjfQIg793GnmeTeYCEkQNWPQkV2AkNR/view?usp=sharing)

Desktop (please complete the following information):
OS: [macOS]
Browser [chrome]
Version [110.0.5481.100]

**Comment by Floydtm** [comment]
Hi. What you show in the video is different. Pay attention to the names. In the profile buller, it is nicename. In the user settings, it is nickname. So the option in the builder profile takes the value from the database. Here it is https://tppr.me/76vt0 Let me know if this helps you. Thank you very much!

**Comment by RagnarLodbrok94** [comment]
[User nicename](https://prnt.sc/ecgcNk05-L6z) is a field from the database.
[Result](https://prnt.sc/CWAuiF50pzpj)
