### ISSUE TITLE
new widget for jet woobuilder : Archive Result Count widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6690]
Hi team!

One of the best and most useful feature that jet woobuilder is missing is the Archive Result Count widget. Using this widget, we can display the number of products in an archive to users, and this will be really great.

Currently, the woolentor plugin provides a widget for it. Please add it. https://prnt.sc/RR1bIHiqAgZ8

cheers

**Comment by 79ho3ein** [comment]
It is similar to [this issue](https://github.com/Crocoblock/suggestions/issues/4262). It should be seen what is the easiest way to add. Using a dynamic tag, or a new widget (as you said)

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thank you for your feedback!

JetWooBuilder has this kind of widget - https://tppr.me/pPPvwZ. But unfortunately this widget not working with JetSmartFilters.

I merged this issue with https://github.com/Crocoblock/suggestions/issues/4262, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.

Thank you for understanding!
