### ISSUE TITLE
Jet Blog Gutenberg support

### ISSUE THREAD

**Issue by createque** [CrocoBlock/suggestions#6691]
Since I completely abandoned the Elementor ecosystem, what I miss the most in Gutenberg is the news/magazine plugin.

**Jet Blog** is great, but currently it only supports Elementor.

My problems would be over if **Jet Blog** also supported Gutenberg.

Would it be possible in the near future?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
