### ISSUE TITLE
Implement "Justify Content" feature for Listing Grid widget

### ISSUE THREAD

**Issue by apatsidis123** [CrocoBlock/suggestions#6692]
Just implement "Justify Content" feature for Listing Grid widget meaning the options: "space-between, space-around, or space-evenly"

It is pretty much self-explanatory and i am surprised that the only way to correct that is to trim the meta fields length.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
