### ISSUE TITLE
Add the ability to add extra custom fields to WooCommerce Checkout Billing Form Widget

### ISSUE THREAD

**Issue by alexschneiderru** [CrocoBlock/suggestions#6694]
It would be very helpful:
1) being able to add extra custom fields to Billing Form Widget for the WooCommerce Checkout page;
2) to add to the widget fields created by another plugin capable of adding such fields to the checkout (e.g. billing plugin).

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/4221, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
