### ISSUE TITLE
Some requests to improve badges in product grid widget and Single Sale Badge widget - Jet Woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6696]
Hi

If possible, please check the following items to improve the badges in these two widgets.

1- If we enable Custom Size in product grid widget > badges, and consider a custom size, there is no option to align the text horizontally and vertically : https://prnt.sc/ukhGkaGZLvii   (Please note that the display is inline)

2- The customization options in product grid widget > badges are great. But there are not many customization options in the Single Sale Badge widget. While we have them in product grid widget > badges! 

Options such as :

A : Image and gradient for background : https://prnt.sc/vvb3IMWNBFgs
B : https://prnt.sc/WBKZsA7bn331

And many other customization options that exist in product grid widget > badges, but not in Single Sale Badge widget.

thank you

**Comment by UraraReika** [comment]
1 - Added default styles so from now on badges label will always be displayed in the centre of the wrapper.

2a - This is different control types, and in this case we can simply replace it without damaging backwards compatibility. So for the time being it will be like that.

2b - done

All this changes will be available in next 2.1.6 release

**Comment by 79ho3ein** [comment]
thank you @UraraReika, Please check [this issue](https://github.com/Crocoblock/suggestions/issues/6949) for the next version if possible.

**Comment by UraraReika** [comment]
> thank you @UraraReika, Please check [this issue](https://github.com/Crocoblock/suggestions/issues/6949) for the next version if possible.

This issue solved already and will be in the next release as well

**Comment by 79ho3ein** [comment]
thanks bro❤
