### ISSUE TITLE
JetEngine + Elementor (wrong link to profil page)

### ISSUE THREAD

**Issue by Yooyoo1987** [CrocoBlock/suggestions#6701]
**Describe the bug**

**To Reproduce**
1. Make a profile page (with Profile Builder)
2. Make user page, single user page
3. Make a listing for users, add a (link) HTML tag to the first container, set the link source to Profile Page URL (settings: profile Page= Single user page, Context= Queried User)
4. If jetEngine version is 3.1.0 or below, everything works fine
5. If jetEngine version greater then 3.1.0:
    -if currently logged in: click on any user in listing grid, allways the curretly logged in user profile page loaded
    -if logged out: click on any user in listing grid, the link go to 404 page
6. If jetEngine version equal to 3.1.3.1:
    -if currently logged in: click on any user in listing grid, allways the curretly logged in user profile page loaded
    -if logged out: click on any user in listing grid, the link href is good

**Expected behavior**
Even logged in or logged out, the link must go to the selected user profile page.

**Screenshots**
Link settings:
![image](https://user-images.githubusercontent.com/47029705/230393357-fab1da53-bbd6-4fae-b04b-6069aedb2534.png)

With jetEngine 3.1.0 the link href is good, even if logged in:
![image](https://user-images.githubusercontent.com/47029705/230393804-f28d3f98-5ff8-4c4a-af66-c97b14e3d6cf.png)

With jetEngine 3.1.3.1 logged in, the link href is wrong:
![image](https://user-images.githubusercontent.com/47029705/230394207-c6b510c9-f981-496d-b2c4-8a903009d3e0.png)

With jetEngine 3.1.3.1 logged in, the link href is good:
![image](https://user-images.githubusercontent.com/47029705/230394657-4ea15ed8-a4b0-4ed5-b5bb-c076d2ac906c.png)

**Comment by kaskad88** [comment]
Hello @Yooyoo1987 
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
Thanks.

**Comment by kaskad88** [comment]
Fixed in 3.1.4 
Thanks for your report!
