### ISSUE TITLE
Jetwoo Loop Grid 

### ISSUE THREAD

**Issue by gupevieira0703** [CrocoBlock/suggestions#6723]
Add query to exclude categories is a must...

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a new [feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritize the requests.

Thank you for your understanding.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.
