### ISSUE TITLE
[JetEngine] Custom Taxonomies Hierarchical Rewrites leads to 404 error page

### ISSUE THREAD

**Issue by lcrvtt** [CrocoBlock/suggestions#6724]
**Describe the bug**
Rewrite Hierarchical (Either hierarchical rewrite tag or not) option does not work for children/descendants taxonomies

**To Reproduce**
1. Start to create a custom taxonomy with jetengine for a custom post type
2. Leave all default Advanced Settings except: 
Activate Rewrite Hierarchical (Either hierarchical rewrite tag or not)
Activate Hierarchical (Is this taxonomy hierarchical (have descendants) like categories or not hierarchical like tags)
3. Add your custom taxonomy
4. Navigate to that newly created taxonomy and Add New Category
5. Add a second New Category and choose the first category created in step 4 as the Parent Category
6. Hover your mouse on this newly created category in Step 5 and click 'view'
7. The page that opens is a 404 error page

**Expected behavior**
Have a correct taxonomy page and no 404 error page.

**Screenshots**
![hierarchical-slugs-404-1](https://user-images.githubusercontent.com/6670642/231243840-5b37547e-84cd-44b0-bd09-398d1abcf995.png)
![hierarchical-slugs-404-2](https://user-images.githubusercontent.com/6670642/231243904-be55db64-5e28-485e-a248-ca5495dde440.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Chrome 112 / Jetengine 3.1.4

**Smartphone (please complete the following information):**
N/A

**Additional context**
It works for the first level category.

**Comment by LevelUpGit** [comment]
+1

**Comment by kaskad88** [comment]
@lwst @LevelUpGit 
For the hierarchical structure to work for children taxonomies, it is also necessary that the **Register Query Var** option is not empty https://tppr.me/yhLgp https://tppr.me/AMv2I https://tppr.me/p1e2s

**Comment by LevelUpGit** [comment]
@kaskad88 Hi, there is an a issue for Register Query Var, there is no filed to set custom in in latest JetEngine just to switch it on/off. 
![Screenshot_2](https://user-images.githubusercontent.com/69863985/233945167-61bbd772-14c4-4b34-9963-028536ac2487.jpg)

**Comment by kaskad88** [comment]
> @kaskad88 Hi, there is an a issue for Register Query Var, there is no filed to set custom in in latest JetEngine just to switch it on/off. ![Screenshot_2](https://user-images.githubusercontent.com/69863985/233945167-61bbd772-14c4-4b34-9963-028536ac2487.jpg)

@LevelUpGit Hi, the **Register Query Var** field need setup in Taxonomy instance.
JetEngine -> Taxonomies -> Your Taxonomy -> Advanced Settings Tab https://tppr.me/3QL5s

**Comment by LevelUpGit** [comment]
Thank you, my mistake.
