### ISSUE TITLE
Jetbooking better integration with Tours

### ISSUE THREAD

**Issue by sea4all-g** [CrocoBlock/suggestions#6725]
Hi there and congrats for your great job ! 
our team develop a new Tour site but we realize there is a problem with calendar and booking.
The idea of how Tours are working is : we have a Tour and we can serve 40 people for that Tour. if i book that tour with Jetbooking calendar for example for 5 people at 30/5/2023 after that the calendar shows that i can not book again the same date ! ( show " sold out")
So it must be configured depending on how many people should be in that specific Tour . As i understand now it is working as a Room availability only but for Tours or for Car Rentals it is not working properly.
Also there must be a better back end office so the client can edit / see all the submitted bookings. For example we can not filter the bookings per category /date / status etc...
That's all for me keep doing the same great work !

**Comment by Wsmayfreelancer** [comment]
Currently jetengine booking doesn't have that options yet but would you a custom development for this...

Tips possible solution will be done with php and you on your DB

**Comment by UraraReika** [comment]
Hello @sea4all-g. Thanks for the feedback.

I merged this issue with https://github.com/Crocoblock/suggestions/issues/6620, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.

Filtering system will be available in the next major release.

Thank you for your understanding.
