### ISSUE TITLE
Icon Spacing not work in Data Store Button widget

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6727]
Hi crocoblock team @Floydtm and @MjHead 

I'm trying to create space between the icon and the label using the Icon Spacing option in the Data Store Button widget. But this option (Icon Spacing) does not work at all : https://prnt.sc/B8_78uz8cTnC
**This makes the icon stick to the label and there is no space between them.**

This is a very minor bug, please keep it in mind for the nearest update❤

It would also be great if you added an option for the icon so we could move it to the right or left side of the label. Because in the label option we can display the store count and it is very important to be able to display it in the desired location : https://prnt.sc/-NRcM0-8tk8b

**Comment by kaskad88** [comment]
Hi @Michaelgimii 
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
Thanks.
