### ISSUE TITLE
Allow NULL for Number Field (JetEngine Meta Boxes / CCT) Instead of 0 if the Field is Empty

### ISSUE THREAD

**Issue by satomiao** [CrocoBlock/suggestions#6732]
I am writing to request a feature enhancement for the JetEngine Meta Boxes / CCT plugin. Currently, when the CCT (Custom Content Type) is updated and the number field is left empty, it automatically sets the value to 0. However, as we all know, empty, null, or blank are not equal to 0.

I kindly request that the plugin be updated to allow for NULL values in the number field instead of automatically setting it to 0 when left empty. This would ensure that the field accurately reflects the absence of a value, rather than displaying an incorrect default value.

**Comment by LevelUpGit** [comment]
+1

**Comment by ihslimn** [comment]
You may add this snippet
```php
add_filter( 'jet-engine/custom-content-types/update-item/sanitize-field-value', function( $value, $name, $field ) {
	if ( ! empty( $field['type'] ) && $field['type'] === 'number' && \Jet_Engine_Tools::is_empty( $value ) ) {
		$value = null;
	}
	
	return $value;
}, 10, 3  );
```

to functions.php of your active theme, or to some snippets plugin if you prefer those.

It may be that some users already rely on the fact that empty number fields become 0, so it would be better to use this filter for now
