### ISSUE TITLE
[Bricks Builder] Calendar lose style when switching months

### ISSUE THREAD

**Issue by Rubenzella** [CrocoBlock/suggestions#6739]
I've created a calendar and displayed on frontend. My events have a background color based on terms.
They look fine when you land on the page where the calendar is or refresh the page.

When you switch month and the calendar loads the events, the background color is lost. Inspecting it, it seems it's not loading the id of the element, and so its styling.

![Screenshot 2023-04-16 at 5 14 05 pm](https://user-images.githubusercontent.com/19385581/232279778-036ed989-705c-4d98-8e46-9c2f060e0529.png)
![Screenshot 2023-04-16 at 5 14 13 pm](https://user-images.githubusercontent.com/19385581/232279795-df126119-d82a-4baa-86bc-ab81fe8a4ace.png)
![Screenshot 2023-04-16 at 5 14 19 pm](https://user-images.githubusercontent.com/19385581/232279789-fa68bf10-d9f8-4be1-9e19-dbd8bc7ffdce.png)

**Comment by RagnarLodbrok94** [comment]
Hi, @Rubenzella.
Please describe in as much detail as possible how we can replicate this bug.
Maybe you can record a video?

**Comment by Rubenzella** [comment]
Hi @RagnarLodbrok94,
I've created a local environment to replicate the issue and I ended up having an opposite behaviour, ie no style on page load but styled once moving through the months.

In this instance I've created a relation between two post types.

1- create 2 post types and related them with one to many
2- create a taxonomy for a cpt, create some terms
3- create some random posts and related them, assigning a term each. Also publish dates should be in different months.
4- create a listing for the calendar with bricks
  4a- insert a block for each term, assign each a different colour
  4b- set dynamic visibility: dynamic data / taxonomy created / contains / "name of the term" for each block
  4c- insert a dynamic widget, post title, context = related items
5- open a page in bricks, insert calendar widget and set listing to the newly created
6- Check frontend. The colour for the blocks isn't loaded consistently when loaded or moving through the months

**Comment by RagnarLodbrok94** [comment]
Done.
Will be in version 3.2.0

**Comment by Rubenzella** [comment]
Having a new and similar issue with the calendar and Bricks.

When the page loads, the events are not loaded, by switching months, they show up.

The screenshot is when I load the page before moving back and forth between the months to see the events displayed.

<img width="1301" alt="Screenshot 2024-01-29 at 8 26 29 pm" src="https://github.com/Crocoblock/suggestions/assets/19385581/28e295f5-0ac4-462d-872c-b840fcf3aee2">
