### ISSUE TITLE
[Bricks Builder] Conditional visibility not working with repeaters

### ISSUE THREAD

**Issue by Rubenzella** [CrocoBlock/suggestions#6741]
As of now, the only way to hide a repeater in the frontend if it is empty, is by using the widget and toggle the visibility.

If I need to hide an entire element (a div for instance) wether the repeater has content or not, the condition does not work.
I can set easily set the same condition based on a custom field, and it works.

I believe this is not a bug, just a missing compatibility?

**Comment by RagnarLodbrok94** [comment]
Hi, @Rubenzella .
Please describe in as much detail as possible how we can replicate this bug.
Maybe you can record a video?

**Comment by Rubenzella** [comment]
Hi @RagnarLodbrok94,

https://github.com/Crocoblock/suggestions/assets/19385581/fc113378-06e2-428c-a5e3-9ad9963ec32c

**Comment by RagnarLodbrok94** [comment]
Hi, @Rubenzella .
We didn't add these dynamic tags.
In our case - je_jobs_test-repeater_repeater-title-1.

This is a built-in functionality in Bricks and we can not do anything with it.
We'll try to fix it in the future.
Thanks for understanding.
