### ISSUE TITLE
Jet smart filters 3.1.1 BUG : Filters do not work on Elementor popups.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6742]
Hi @Floydtm 

In the new version of Jet smart filters, if we display the filters using **Elementor popup**, they will not work. **In fact, filters work well only for the Administrator role.**

It should be noted that I use filters for the **product grid** widget of the **Jet woobuilder** plugin.

### details

theme : Hello elementor, version 2.7.1
wordpress : 6.2
elementor : 3.12.1
elementor pro : 3.12.2
jet smart filters : 3.1.1
jet woobuilder : 2.1.4

Please let me know if you are not successful in reproducing the bug.

thank you

**Comment by Michaelgimii** [comment]
+1
Will there be an update for it soon?

**Comment by 79ho3ein** [comment]
Hi again @Floydtm

Is this bug confirmed? It seems that other users are also experiencing this bug

https://github.com/elementor/elementor/issues/20713
