### ISSUE TITLE
At JetEngine Custom Field to Elementor Background Slideshow

### ISSUE THREAD

**Issue by revywebdesign** [CrocoBlock/suggestions#6744]
Hello,

I'd like to be able to dynamically show slideshow images as backgrounds through the use of JetEngine. 

See the image for an example of where this would be a useful feature. 

![image](https://user-images.githubusercontent.com/131111040/232655887-9986e2be-cc17-41b1-8424-ad13824abf26.png)

**Comment by Floydtm** [comment]
Hello, to resolve your request, you need to leave your request [here](https://github.com/elementor/elementor/issues). Thank you!

**Comment by revywebdesign** [comment]
This is a Crocoblock suggestion, not an Elementor one though.
