### ISSUE TITLE
File download tracking

### ISSUE THREAD

**Issue by MajorFusion** [CrocoBlock/suggestions#6748]
Many of my clients would like to have an easy, at-a-glance way to see how many times a particular file on their website has been downloaded. I used to use a document manager like Download Monitor. It would be very helpful if there were some of those features inside of the Custom Content/Post Type systems.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
