### ISSUE TITLE
JetWooBuilder sale badge widget error

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#675]
**Describe the bug**
When editing a single product template with a product that does not have a promotional price AND the template has the sale badge widget, it gives error 500.

**To Reproduce**
When editing a single product template with a product that does not have a promotional price AND the template has the sale badge widget, it gives error 500.

**Comment by Floydtm** [comment]
@marcofrasson,  Hi! Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help
