### ISSUE TITLE
JetEngine changing a post to another author! You CANNOT!!

### ISSUE THREAD

**Issue by DestackTerapias** [CrocoBlock/suggestions#6751]
**Describe the bug**
I have a website that I am migrating to JetEngine from Toolset. This new site, I will allow subscribers to create/edit/delete their own CPTs. While everything is working correctly, I decided to test changing the author from administrator to one of the subscribers, but I could not. So I created a dummy subscriber, and noticed that in the author's element I could only change to administrator and no other subscriber.

This is TERRIBLE, since I am transferring over 200 CPTs and I need to assign them to each subscriber, which I CANNOT.

**To Reproduce**
1. Go to 'any CPT that you already added Author as a support feature for a post type' and make sure you have other users (subscribers) to try to change.
2. Click on 'any post type already created and go to option screen to click on the checkbox Author'
3. Scroll down to 'the newly added Author's box and try to change to another subscriber'
4. See error! You cannot change to another subscriber!!

**Expected behavior**
I expected to be able to change that specific post to another subscriber but I cannot! I have 4 users and I cannot change a post from one to another.

PLUS - if I change the current subscriber to Administrator, I CANNOT change back to Administrator!!

**Screenshots**
![1](https://user-images.githubusercontent.com/125477422/233171516-c34bc6fd-d0ac-471e-9ae7-e6871001f760.png)
![2](https://user-images.githubusercontent.com/125477422/233171657-09cfccdc-6023-45f8-a4b2-8611c07280af.png)
![3](https://user-images.githubusercontent.com/125477422/233171785-9b441057-ed32-4289-83e1-e8f6c72efa8b.png)

**Additional context**
This is MAJOR and need a FIX right now!!

**Comment by satomiao** [comment]
Change the user to the author user role instead of the subscriber if you want to update the CPT on the back-end.

**Comment by ihslimn** [comment]
@DestackTerapias  As you can see here https://wordpress.org/documentation/article/roles-and-capabilities/#subscriber subscribers do not have a right to do anything but read, so they cannot be assigned as author of the post. Like @satomiao says - change their role to Author, or give them a capability to create posts (via User Role Editor plugin or similar)

**Comment by DestackTerapias** [comment]
You guys are CORRECT!! OMG, how did I not think that?? Thank you so much!!!
