### ISSUE TITLE
Allow more than 6 items for Listing Grid widget

### ISSUE THREAD

**Issue by prostylewebdesign** [Crocoblock/suggestions#676]
It would be great to allow more than 6 columns for the Listing Grid widget. Currently there is a max of 6 and in my instance I need 10 columns (small items). A roundabout way of going around this is by creating two columns and place the Listing Grid widget in each column and set 5 columns for each column with order_offset. However, this ruins the tab order and is really not an ideal way of handling it. 

<img width="321" alt="Screen Shot 2019-11-15 at 11 10 32 PM" src="https://user-images.githubusercontent.com/6346436/68989609-15613080-07fe-11ea-972c-696335c7176a.png">

**Comment by kaskad88** [comment]
I merged this issue with #388, which is on the same subject so we could deal with it more efficiently.
