### ISSUE TITLE
Add Gutenberg Additional CSS classes support for JetFormBuilder Block

### ISSUE THREAD

**Issue by satomiao** [CrocoBlock/suggestions#6764]
The JetForm Block has a feature that allows users to add additional CSS classes by going to Block > Advanced > Additional CSS Class(es). However, even after adding these CSS classes, they are not appearing on the front-end of the website. Therefore, there seems to be an issue with the functionality of the Additional CSS Class(es) setting.

**Comment by girafffee** [comment]
Done in 3.0.7
