### ISSUE TITLE
JetEngine Relation bug with a Query Builder for that Relation

### ISSUE THREAD

**Issue by pauserratgutierrez** [CrocoBlock/suggestions#6767]
I'm using JetEngine 3.1.4 (JetFormBuilder 3.0.4 and JetFormBuilder user login action 2.0.0). Also, I'm in BricksBuilder 1.7.3

I have created a user many to many relation that saves to the user metadata. With a jetformbuilder form I update the relations to add and remove users so simulate a following system. I'm using parent as followers and child as following. To display a count for each, I use Dynamic Field widgets with source of Post/Term/user/object -> object field of "parents from followers" and a filter field output -> callback field values count (for arrays). I setted up a fallback value to 0. Everything works.

But I need to loop the followers and following, and nativelly, the loop only allows to loop following. So I create a custom sql query in query builder to display followers.
![image](https://user-images.githubusercontent.com/73240206/233834914-3c60140b-506e-4267-ae24-da5903559ec8.png)

When I activate this query, the dynamic value count I used earlier stops working and fallbacks to 0. If instead of Value current user Id I use the value of someone else's ID, it works. So seems that when I query this values the other Dynamic widget gets an empty array?

**Comment by kaskad88** [comment]
@pauserratgutierrez 
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
