### ISSUE TITLE
JetBooking and WooCommerce integration creates booking before payment

### ISSUE THREAD

**Issue by tornewmedia** [CrocoBlock/suggestions#6772]
I'm using the JetBooking plugin with JetFormBuilder. I have the WooCommerce integrations turned on.

When the user selects their dates and completes the form, when pressing submit they are taken to the WooCommerce checkout page to make their payment. This all works as expected.

The issue is that as soon as they press submit on the form a booking is created in the admin under JetBooking and marked as 'Created'. 

If they go on to pay it is marked as 'Complete'.

Is this expected behaviour? To me it seems as though it's a bug as a booking shouldn't be created until payment is made.

I know the form as conditions where you can set if the payment was a success but this applies to using the Stripe addon to the form rather than WooCommerce.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6619, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
