### ISSUE TITLE
[BUG] JetMenu 2.3.0 - Not displaying in Mobile

### ISSUE THREAD

**Issue by dev500designs** [CrocoBlock/suggestions#6779]
When working with JetMenu 2.3.0 the plugin is not showing on mobile view.

It's showing the submenu, but the submenu template is **empty**.

Works fine on desktop and when reverted to previous version 2.2.4

**Comment by VCalazans** [comment]
In my application it is not being possible to work with the item template in version 2.3.0 of the hamburger menu.

**Comment by StenderIternum** [comment]
Having the same issue - The html is empty on mobile view, when trying to display a template.

**Comment by StenderIternum** [comment]
Fixed in 2.4.0 for me
But this issue persists : https://github.com/Crocoblock/suggestions/issues/1744
