### ISSUE TITLE
Jetbooking and Jetppointment need big changes.

### ISSUE THREAD

**Issue by Qubadi** [CrocoBlock/suggestions#6783]
Hello

I and many others agree that it is time for Crocoblock to make some changes in the back end for both Jetbooking and Jetappointment. These two plugins have not had any particular changes in terms of back end design, this has been the case for several years.

Med is in 2023, and AI technology has exploded now it's time, do you web designers and web developers in Crocoblock think it's time to make some changes, that you don't keep doing the same old things?

I mean, Crocoblock needs a big change in the back end both for Jetbooking and Jetappointment. These two plugins work perfectly fine in the front end, and you can design exactly what you want, but unfortunately in the back end it looks absolutely awful.

I hope that you start to look around a bit, and these changes on the market today, and modernize your back end design. Now is the time for this.

The time Crocoblock spends on Github, Chat, Ticket, getting to answer things, had they spent on the developments, they would have finished a long time ago.

I hope you at Crocoblock do not take this as criticism but as a suggestion, both for Crocoblocks and us as your customers. The more you bring, the more customers will come to you.

If you provide modern designs, the more people are willing to buy these products from you. Many thanks to all of you at Crocoblock, and hope we see those changes very soon.

I will also send you some pictures. Thanks again, Peace

https://i.postimg.cc/pTPLQFBs/Jetbooking-and-Jetappointment-design-back-end-1.png
https://i.postimg.cc/RFGVgZs4/Jetbooking-and-Jetappointment-design-back-end-2.png
https://i.postimg.cc/cCH12G2Y/Jetbooking-and-Jetappointment-design-back-end-3.jpg

**Comment by anon2225** [comment]
+1
