### ISSUE TITLE
JetSearch compatibility for Bricks Builder

### ISSUE THREAD

**Issue by Scarlywebs** [CrocoBlock/suggestions#6785]
Hello Crocoblock team! I am wondering if possible that JetSearch be compatible with the Bricks page builder. Currently, Bricks Builder only uses the default WordPress search and would like ( and probably others ) to be able to create advanced searches and create awesome styles that Jet Search offers.

Please let me know if this would be possible, thanks.

**Comment by mehdimoradi1500** [comment]
Yes it will be nice to have it in bricks builder @MjHead, please make it possible

**Comment by codewithrabha** [comment]
After using elementor for years now I am learning Bricks and soon I am planning to switch into bricks. So not only JetSearch I would like to request the whole Crocoblock suite to be compatible with Bricks.

**Comment by jade7700** [comment]
There is still no search plugin as powerful as jet search for bricks builder, it would be great if they made it compatible with bricks as they did with jetengine and jetsmart filter.

**Comment by Scarlywebs** [comment]
> After using elementor for years now I am learning Bricks and soon I am planning to switch into bricks. So not only JetSearch I would like to request the whole Crocoblock suite to be compatible with Bricks.
@codewithrabha 

The whole Jet Elements set is very nice but I don't think would be necessary for the whole Crocoblock Set to be compatible with Bricks Builder, plus Bricks does 70% of these things.

What particular ones do you need for Bricks?

**Comment by MjHead** [comment]
Added with 3.2.0
