### ISSUE TITLE
[ JetBooking ]Weekly booking option

### ISSUE THREAD

**Issue by emdutac** [CrocoBlock/suggestions#6788]
Hi, in the jetBooking check-in-out field, I need to impose the check-in and check-out days (Saturday in my case). Do-you know if it's possible ? If not, with Jquery how easily check if days are Saturdays ? Thanks a lot for your answer !

**Comment by UraraReika** [comment]
Check out lates 2.8.0 release

**Comment by emdutac** [comment]
Thanks a lot, your are great !
