### ISSUE TITLE
JetSmartFilters Search Filter on Post Title and/or Custom Field

### ISSUE THREAD

**Issue by Lance2j** [Crocoblock/suggestions#679]
If these two features already exist, I sure haven't found out how to do it. I need to set the search filter for a Post Title and a custom field. 

The specific scenario is that my custom post type contains 2,000 records of Fig Varieties. The Post Title is the name of the fig variety. A custom field contains the synonyms for the fig varieties. So a search needs to be performed on both the title and synonym fields.

So the first issue is that JetSmartFilters does not seem to support searching specifically on a post title.

The second issue is JetSmartFilters does not seem to support searching on two fields in a single search with an OR option. That is, a search should provide results if the search criteria is contained within either the post title OR the synonym field.

This is critical for my project.

**Comment by Floydtm** [comment]
@Lance2j, Hi! Thank you for your message! We have reviewed your request. At the moment, we can’t add conditions and / or Even so, you can use the search filter with one of the options http://prntscr.com/pyn3be You can also specify the title of the post and its synonyms in one meta field
