### ISSUE TITLE
Jalali Calendar support for jet engine and jet form builder plugins.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6792]
Hi crocoblock team.

Is it possible to add Jalali Calendar support? Because currently it is practically not possible for us to use date fields in jet form and jet engine plugins.

https://en-ca.wordpress.org/plugins/wp-shamsi/

thank you

**Comment by ashkankhalili** [comment]
hey, 
you can use dynamic filed widget, in settings, select metadata for field, in metafield select your customer metadata for date,
change "Filter field output" to 'YES'
set CALLBACK to "Format date, Localized, Legacy"

Done! 
you get the date format as what been set for Wordpress.

**Comment by ashkankhalili** [comment]
> Hi crocoblock team.
> 
> Is it possible to add Jalali Calendar support? Because currently it is practically not possible for us to use date fields in jet form and jet engine plugins.
> 
> https://en-ca.wordpress.org/plugins/wp-shamsi/
> 
> thank you


hey,
you can use dynamic filed widget, in settings, select metadata for field, in metafield select your customer metadata for date,
change "Filter field output" to 'YES'
set CALLBACK to "Format date, Localized, Legacy"

Done!
you get the date format as what been set for Wordpress.

**Comment by MohammadReza-Ebrahimian** [comment]
hi. 
could you please make a short tutorial video?

@ashkankhalili

**Comment by ashkankhalili** [comment]
> hi. could you please make a short tutorial video?
> 
> @ashkankhalili

hi,
please do as follow : 
1- add a dynamic field widget to your page or listings template 
2-in content tab select the source as post/term/user/object data
3-select "DATE" for object field
4-scroll down turn the "Filter field output" to YES
5-in call back drom menu select "FORMAT DATE, LOCALIZED LEGACY"

All done ... it shows the default date format of your wordpress website, if you set your wordpress language to PERSIAN, then you will have the persian calendar.

for the reference, please check the attached image.
if you need more help you can send me a message i will explain it with more details :) 
![123](https://github.com/Crocoblock/suggestions/assets/14147491/fa63af55-d926-4937-a8c4-d3dafe6e5417)

**Comment by keshvari** [comment]
@ashkankhalili  

Hi Ashkan 
Do you know if this solution applies to multilanguage sites? For example, what would happen if the user changes the language to English in a page which is primarily in Persian ?

**Comment by ashkankhalili** [comment]
> [@ashkankhalili](https://github.com/ashkankhalili)
> 
> Hi Ashkan Do you know if this solution applies to multilanguage sites? For example, what would happen if the user changes the language to English in a page which is primarily in Persian ?

Hi, 
As of my understanding , when you set the call back to localized, it will change the date type with respect to the website language.
but to be honest i have never test it practically.
Incase if you have test it let us know :)

**Comment by namefarid** [comment]
@ashkankhalili 
سلام اشکان جان
در خصوص نمایش تاریخ ها به شمسی مشکلی نیست
اما برای استفاده کردن از ویجت فرم جت فرم و اینکه دیت پیکرش به شمسی باشه مشکل دارم!

درباره این موضوع راه حلی داری؟

**Comment by ashkankhalili** [comment]
> [@ashkankhalili](https://github.com/ashkankhalili) سلام اشکان جان در خصوص نمایش تاریخ ها به شمسی مشکلی نیست اما برای استفاده کردن از ویجت فرم جت فرم و اینکه دیت پیکرش به شمسی باشه مشکل دارم!
> 
> درباره این موضوع راه حلی داری؟

درود بر شما، 
در مورد جت فرم باید بگم اصولا از دیت پیکر دیفالت وردپرس استفاده میکنه تا جایی که من یادم هست، اگر افزونه پارسی دیت و داشته باشیداصولا فارسی باید بیاد.
اگر نمیاد میتونین با اضافه کردن کد های زیر کلا دیت پیکر میلادی و روی جت فرم بردارید و براش جلالی یا همون فارسی و قزار بدید در واقع توی فرم دیت پیکر و قرار ندید و بجای اون یک فیلد تکست یا تاریخ بزارید و کارهای زیر و انجام بدید اوکی میشه .

1-این کد و در فانکشن قالب قرار بدید : (function.php)

```
 function add_jalali_datepicker_assets() {
    wp_enqueue_style(
        'persian-datepicker-css',
        'https://cdn.jsdelivr.net/npm/persian-datepicker@1.2.0/dist/css/persian-datepicker.min.css'
    );

    wp_enqueue_script('jquery');

    wp_enqueue_script(
        'persian-date-js',
        'https://cdn.jsdelivr.net/npm/persian-date@1.1.0/dist/persian-date.min.js',
        ['jquery'],
        null,
        true
    );

    wp_enqueue_script(
        'persian-datepicker-js',
        'https://cdn.jsdelivr.net/npm/persian-datepicker@1.2.0/dist/js/persian-datepicker.min.js',
        ['jquery', 'persian-date-js'],
        null,
        true
    );
}
add_action('wp_enqueue_scripts', 'add_jalali_datepicker_assets');

```

2-در المنتور یک custom JS ایجاد کنین و کد زیر و داخلش بزارید : 

```
jQuery(document).ready(function ($) {
    $('.jalali-date').persianDatepicker({
        format: 'YYYY/MM/DD',
        initialValue: false,
        autoClose: true,
        calendar: {
            persian: {
                locale: 'fa'
            }
        },
        onSelect: function (unix) {
            var gDate = new Date(unix);
            var gregorian =
                gDate.getFullYear() + '-' +
                String(gDate.getMonth() + 1).padStart(2, '0') + '-' +
                String(gDate.getDate()).padStart(2, '0');

            $('.jalali-date').val(gregorian);
        }
    });
});

```
3- در فرمتون همونطور که عرض کردم یک فیلد نوشته یا تاریخ بزارید و کلاس سی اس اس زیر و بهش بدید (text filed / date filed)
jalali-date

فقط دقت کنین که همین کلاس و حتما باید به فیلد مورد نظر بدید .
تست کنین اگر مشکلی بود بفرمایید.
