### ISSUE TITLE
[JetWoobuilder] Fields on checkoutpage not working properly have to rollback to 2.1.4

### ISSUE THREAD

**Issue by avdstelt** [CrocoBlock/suggestions#6799]
With the current version the Checkoutpage is not rendering the input fields correctly?

For example when I choose the district field the input field is missing also when I use customized fields and remove the district field it is still active on the frontend?

I have to rollback to 2.1.4 to get the Checkoutpage working again in the backend but on the frontend it still shows the district field without the input field?.

Using Kava childs theme.

Greetings Arjan

**Comment by Michaelgimii** [comment]
What is the most serious version of jet woobuilder? I still see version 2.1.4.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
