### ISSUE TITLE
[Bricks Builder] Add JetFormBuilder element with styling options

### ISSUE THREAD

**Issue by oceandiveloper** [CrocoBlock/suggestions#6805]
In Bricks Builder we currently don't have a JetForm Element like in Elementor/Gutenberg.
Would be great if you could add a Bricks specific element to choose a form from JetFormBuilder and allow for styling options for the form parts (inputs, labels etc.)

**Comment by sekhsoyebali** [comment]
+1

**Comment by girafffee** [comment]
Hi everyone)
This feature was included in 3.2.0 version
