### ISSUE TITLE
Extension for JetEngine GeoLocation [JetEngine, JetSmartFilters]

### ISSUE THREAD

**Issue by LTimerr** [CrocoBlock/suggestions#6808]
Good day!

It would be good if the user himself had the option in GeoLocation first in which radius he wants to filter. In addition it would be still good, one could omit the Map simply and the user has the option even to enter an address, where he wants to filter. The posts are then simply displayed in a listing grid, which are linked via the query ID with the filter.

**Comment by EnvioMaik** [comment]
+1 very needed feature!

You can add a default address with radius on the backend. They just need to move that feature to the front end, so users can select a location and radius to filter listings.

**Comment by LTimerr** [comment]
Exactly it would also make more sense if every user could set the radius himself.

**Comment by MjHead** [comment]
This feature will be added with 3.3.0 update. At the moment available for beta testing. So close this issue in prefer of beta - https://github.com/Crocoblock/suggestions/issues/7140
