### ISSUE TITLE
[JetSmartFilters] - Pagination of Bricks Query Loop on Archive Page

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#6809]
In relation to https://github.com/Crocoblock/suggestions/issues/6652

I may have noticed a new bug now.

If I filter/sort etc. within a product category (template) with AJAX, the products from other categories are also displayed after filtering.

Before AJAX: (All 3 Products form a Category)

![grafik](https://user-images.githubusercontent.com/54399588/237006816-21a23f08-cccc-4b4e-a2bf-af1aa46dbbc1.png)

After AJAX: (All Products)

![grafik](https://user-images.githubusercontent.com/54399588/237006859-9a7b86c6-4f12-4a6b-8b5e-5fec5df13147.png)

This is how my Bricks Loop Query looks.

![grafik](https://user-images.githubusercontent.com/54399588/237006976-45ccedfc-6b66-4427-8fe7-24497a22af08.png)

I have only selected products. Apparently Bricks recognises which category you are in and then only outputs the products. I don't think there is anything with "Current Term" or something like that. But the query has to be right. It works with the pagination of Bricks

As a check, I wanted to try it with "Page Reload" instead of AJAX. But then I am redirected to my startpage after confirming the button. On another page, which is not a template, I tested it and then both functions work.

**Comment by hb81010** [comment]
Update: the problem also occurs with the Search filter

**Comment by hb81010** [comment]
Short question: I just saw that there was no fix in the current update. Will there be a fix for this in the next update?

**Comment by RagnarLodbrok94** [comment]
Hi, @hb81010 
Switch this option [Ajax Request Type->Referrer](https://prnt.sc/jNZKP8iz4I0u).
It will help you.
