### ISSUE TITLE
"WooCommerce Featured Products" is showing only one Column (if set) on desktop, but not on mobile :-(

### ISSUE THREAD

**Issue by reinhardjung** [Crocoblock/suggestions#681]
Just one Column on Mobile? Can you please updates this?

Thank you for contacting our support team! I am sorry for the long delay! Unfortunately, right for now the default column number is set to 2 for mobile. Please, feel free to submit a feature request to Git repository https://github.com/CrocoBlock/suggestions/issues and our team will explore if it's possible to implement. 

Kind regards, Maryna
Crocoblock support team

**Comment by Floydtm** [comment]
@reinhardjung, hi! The layout of this widget depends on the settings of the theme itself. The fact is that we can’t influence this because this widget displays the shortcode of the woocommerce  plugin
