### ISSUE TITLE
Jet Smart Filters: Add an option to close a radio filter dropdown when a choice is made

### ISSUE THREAD

**Issue by scharj** [CrocoBlock/suggestions#6813]
When a radio filter is used as a dropdown (Additional Settings > Dropdown Enabled), you have to actively close the dropdown field after a choice is made. With a radio filter this should not be necessary, as you can only choose one option and the value change already filters the listing.

Right now you would have to use a workaround with a popup and a "Apply filter" button, which is not really user friendly.

I would therefore request an option "Close dropdown on value change" when "Dropdown Enabled" is set to "Yes" in Elementor.

**Comment by darthquack** [comment]
+1

**Comment by scharj** [comment]
@SargasTM: Any chance to get this feature in the near future?

**Comment by stopmanny** [comment]
hey, this jQuery worked for chechbox dropdowns with the appy button @scharj 
  
 jQuery(function(){ jQuery('.jet-filter-items-dropdown__apply-button').on('click', function(){
jQuery('.jet-filter-items-dropdown ').removeClass('jet-dropdown-open')  }); }); 


this should work on radio dropdown with a minor hiccup 

  jQuery(function(){
    jQuery('.jet-radio-list__input').on('click select', function(){
       
     jQuery('.jet-filter-items-dropdown ').removeClass('jet-dropdown-open')
        
   
     
    });
});

**Comment by Crocoblock** [comment]
Hi
you can use this code https://gist.github.com/aalexandr21/a9de910f73d9d129f67f8fe81210a4a3 
for filters where enabled the Dropdown with apply button  https://i.imgur.com/fsJYSHi.png
