### ISSUE TITLE
[🟡Bricks Builder] Jetsmartfilter 3.1.1 select goes crazy with "External Files"

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#6817]
Activate the CSS loading method > External Files option
![Capture web_11-5-2023_55447_realimmo test](https://github.com/Crocoblock/suggestions/assets/82481592/dc84ae42-b3cd-4d9f-9cd9-3474aa1de780)

causes a bug (frontend) on select widget and sort in an unexplained way

![Capture d'écran 2023-05-11 055056](https://github.com/Crocoblock/suggestions/assets/82481592/eba0a520-0180-452d-80b2-fdaf4f2a626b)
![ggg](https://github.com/Crocoblock/suggestions/assets/82481592/298ee671-f808-4424-8b9b-a3255d0db63f)

Re-enabling inline styles fixes the problem.
I haven't seen any other jetsmartfilters malfunction other than that
Maybe a little update will fix this problem.

**Comment by sekhsoyebali** [comment]
+1

**Comment by RagnarLodbrok94** [comment]
Done.
This fix will be in version 3.1.3
