### ISSUE TITLE
Alignment option for price and price title in Checkout Order Review widget - Jet Woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6819]
Hi

If possible, please add an option to align the price and title in the Checkout Order Review widget. For example, the image below is what it is now : 

![1](https://github.com/Crocoblock/suggestions/assets/77163248/9d6e2363-ab7e-4517-849d-332f6b441310)

But by using this option, we can put the price and price title on the left side(in RTL).

![2](https://github.com/Crocoblock/suggestions/assets/77163248/5e2131d5-b28b-4c64-8fbe-b0808b66e5f0)

Please note that the alignment of the price and the title of the price is different from the alignment of other sections. As you can see in the image above, the price and the price title are on the left side, but the other sections are on the right side.

thank you

**Comment by UraraReika** [comment]
Sorry but unfortunately, this is not possible.

Thank you for your understanding.
