### ISSUE TITLE
Border problem in Checkout Order Review widget (jet woobuilder)

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6822]
The border option does not work well in the Checkout Order Review widget. There is border option in this widget, in the Table Heading and Table Cell sections. Both of them are not working as expected. Watch the video below.

https://github.com/Crocoblock/suggestions/assets/88034902/372f6cbe-efcb-4444-9918-acd3481e6753

As you can see in the video above, there are a few problems. First, by default, this widget has a border on 4 sides that cannot be controlled.

Please pay attention to the 48th second of the video. When I set the top border to 1px, a pale border is created. But then, when I set the bottom border to 1, it affects the top border again.
In general, the border options in this widget are problematic. I hope this video helps to fix it.

**Comment by UraraReika** [comment]
> As you can see in the video above, there are a few problems. First, by default, this widget has a border on 4 sides that cannot be controlled.

- Fixed. Border styled for this table removed.

> Please pay attention to the 48th second of the video. When I set the top border to 1px, a pale border is created. But then, when I set the bottom border to 1, it affects the top border again.

In this widget we use `border-collapse: collapse;` style for table so you can see only one border not doubled but in this case it's kinda overlaid on top of each other and initial border color has transparency `border-top: 1px solid rgba(0,0,0,.1);` so you can see such an glitchy effect. Nothing special  about it just use solid colours.
