### ISSUE TITLE
Pagination of a dynamic table

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#6827]
1. Create a query with some data from another query.
2. I create the dynamic table of the query
3. In a page I put the table and the pagination widget
4. I assign them the same id
5. When I click on the pagination, it repeats the same results, instead of showing the following ones.
6. Could it be the problem of bringing the results of another query? It happens to me in all the places that I have tried this method
![Captura de pantalla 2023-05-16 122752](https://github.com/Crocoblock/suggestions/assets/90837626/b38b9b69-9dbe-435d-93f6-de4f6b5a4182)
![Captura de pantalla 2023-05-16 122815](https://github.com/Crocoblock/suggestions/assets/90837626/827a6e95-e245-4b64-b1cf-027e8a3c6545)
![Captura de pantalla 2023-05-16 122909](https://github.com/Crocoblock/suggestions/assets/90837626/b0c7d512-440b-4bdd-8cf4-eae96ffba150)

**Comment by kaskad88** [comment]
Hi @JuanCar29 
**Solution for your case:** assign the different Query ID for another query  in Query Builder https://tppr.me/AAx8e
