### ISSUE TITLE
Jet Engine - Meta Box - repeater - only texte, no visual editor ...

### ISSUE THREAD

**Issue by Biblothecaire** [Crocoblock/suggestions#683]
On the page / post, i have the CPT repeater, but i only can ad texte, it's a HTML block
No link, No paragraph or i need to code, take time for nothink !
Why not ad a visual editor ?

**Comment by kaskad88** [comment]
This feature has been implemented https://github.com/Crocoblock/suggestions/issues/397 and will be available in the new JetEngine 2.2.0 release after testing.
