### ISSUE TITLE
Advanced features for datepicker

### ISSUE THREAD

**Issue by Quinnnnnnv** [CrocoBlock/suggestions#6833]
I've been using JetFormBuilder for various websites. Especially for booking websites I'm able to create a custom post type for the bookings/reservations and the only thing I am missing is more customization of the datepicker field. I want to be able to block certain dates and certain days of the week. For example when a restaurant is open from Wednesday to Sunday I want to block the Mondays and Tuesdays from the datepicker so website visitors cannot make reservations for those days. 

I'm aware that Crocoblock also has the JetAppointments plugin which does allow you to create a datepicker with this level of customization. The only problem is that you're stuck with the JetAppoinments plugin for this form to work. Sometimes you want to be able to use a customized datepicker for a custom post type like certain events etc. 

It would make my life much easier if the datepicker in JetFormBuilder would allow for blocked dates and blocked days of the week. The same for the timepicker.

**Comment by UraraReika** [comment]
Hello @Quinnnnnnv ! Thanks for the feedback.

Such functionality exist in JetBooking plugin. You can block separate dates as well as days of the week. If you have some problems with this functionality please contact our support team.

**Comment by Quinnnnnnv** [comment]
Well... JetBooking and JetAppointments do not have the features that JetFormBuilder has. For example. I want my clients to be able to block days in the reservation system. How I see this working with JetFormBuilder is that I set up an options page or custom post type where my clients will be able to add dates that they want to block. The values from these fields can then be used in a ''block these dates'' feature in the JetFormBuilder so that the whole process can be dealt with in the front end. 

Right now it's only possible to set a start and end date for the datepicker in JetFormBuilder. You can't block any date in between those dates. That is what I would like to see.
