### ISSUE TITLE
Make it so we can edit CPT in Elementor

### ISSUE THREAD

**Issue by peaklabs-dev** [CrocoBlock/suggestions#6834]
Make it so that we can edit CPT not only in Gutenberg but also in Elementor. So that we don't have to create templates in Elementor and use Templates with dynamic data, but directly create CPT tempale data and everytging in the CPT using Elementor. So everything happens in the CPT now elemtor template needed.

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by peaklabs-dev** [comment]
Makes no sense, I realised. I wanted to make a CPT and then instead of creating a template in Elemntor that applies to all CPTs and brings them together, I just wanted to edit the post type in Elementor, which makes no sense! Also, I forgot about listings/ loops and all that stuff, so it already works perfectly and the current system is a flawless system.
