### ISSUE TITLE
Jet Appointment - Possibility to choose Template for Appointment Confirmation / Cancellation

### ISSUE THREAD

**Issue by scharj** [CrocoBlock/suggestions#6838]
There is no possibility to choose a Landingpage oder Template for the page that is opened, when someone confirms or cancels an appointment. You need to build redirects which is not really user-friendly. Right now, opening an confirmation/cancellation-link  looks like a mistake.

I would therefore request the possibility to choose a template for this landingpage.

**Comment by Crocoblock** [comment]
Hi @scharj !

Added in version 2.1.0
Please update the plugin and check

Have a nice day!
