### ISSUE TITLE
JetBooking enhancement

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#684]
I had a look at the GUI for the booking system and have a few suggestions. 

This is the text from the General setting tab:
Additional table columns
Labels:
"You can add any columns you want to booking table. We recommend add cloumns [sic] only before table creating. When you added new columns, you need to map these columns to apopriate form field in related booking form."

"Cloumns" is obviously misspelling and should be corrected. 

About language:
Yes. It is a table. So it has columns. We know. We knew already.It is not very informative. 
So instead perhaps something like this:
"You need to add a column for each of the ways that your booking order can be different.
If they are on different days they need a column for days.
In they have different colors you need a color column, where color can be specified.
If they are either "smoking or nonsmoking"  you need a column - smoke_or_not - that can specify the choice for that order. 

Each variable then needs to be defined in your orders, so that each order can inform each column in the table!"

Related post type:
"This will specify which post type that will store information in the booking table. So you need to choose the post type that you have made in order to store the information about each single order. The table will look at all posts of this post type and collect the information from there."
This might just be my bad understand of how this works....

Related post type column
The explanation of how to use this makes no sense at all.
I have read it several times just dont understand.
Please try to exlain or give some example. 

Apartment post type 

This makes sense if and only if what you book is an apartment.
If a dentist need to have online booking, this makes no sense at all. 

I think this needs to be a general version of apartment booking:  "Appointment" or "Booking" will work for most usercases.

So perhaps "Booking post type" to include all.
And explanatory text like this:
"You can select the booking- or appointment- post type, that holds the description of your offer. "
This will generalize the usercase from hotel booking to most kinds of bookings.

**Comment by UraraReika** [comment]
Release 2.6.0
