### ISSUE TITLE
Possibility to customize the payment form fields (= checkout payment widget)

### ISSUE THREAD

**Issue by wnt-it** [CrocoBlock/suggestions#6840]
To make the websites consistent, it would be great if the form fields of the payment widget (e.g. for direct debit) could be customised.

Example of where this feature is already implemented: Checkout billing form widget

Please, note, that the feature requests can be accepted and processed only if they’re written in English.
![Feature Request Customize Formfields Checkout Payment Widget]
(https://github.com/Crocoblock/suggestions/assets/66781534/efa81159-b21c-4ad6-915b-17457d3c7199)

**Comment by SolunaCG** [comment]
+1

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Right now you can although use global Elementor styles for forms - https://tppr.me/jKXq8.

Thank you for your understanding.
