### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by DanielShuster** [CrocoBlock/suggestions#6842]
Hello, have a problem with countdown timer, In the example iv'e set for same date and time. It shows different times, and it shows the style from left to right, and some issue with the seconds? We don't have 90 seconds in a min :)
In the example, the top one = Elementor timer.
Button = Jet Engine.

** My site in Hebrew (RTL)

Thank you!

https://github.com/Crocoblock/suggestions/assets/101641809/e4e5ef78-e1a8-47cc-97e7-deb4260f4b63

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
