### ISSUE TITLE
JetProductGallery: Add support for 3D model viewer and augmented reality

### ISSUE THREAD

**Issue by tiago-123** [CrocoBlock/suggestions#6849]
Dear Crocoblockers, would it be possible to implement this feature from Google that allows for "easily display interactive 3D models on the web & in AR"? You can find it here (https://modelviewer.dev/) and here (https://developers.google.com/ar/develop/webxr/model-viewer). My suggestion would be to add support for this feature in the JetProductGallery plugin. Currently it is possible to show videos in the product gallery, but if we could also show products in augmented reality, I believe this could prove very useful for a large number of use cases.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/3721, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
