### ISSUE TITLE
JetSmartFilters conditions - AND connection (there is only OR)

### ISSUE THREAD

**Issue by Arbthiter** [Crocoblock/suggestions#685]
Hello,

We are facing a serious problem. Our JetSmartFilter in Elementor Pro Archive is not working as We excepted:

- When Movie Genre is set to Horror (example) there are XY posts so all of them
- When Dub/Sub is set to CZ dub (example) there are XY pages of posts
- BUT when We chose to set: Genre Horror + CZ Dub in same time - Filter give Us all Posts of both of them mixed, not combined as we want (CZ dub of Genre Horror).

*copied from Ticket

Please, investigate / implement this feature. Thanks! It's important for us.

Best regards,

Peter

**Comment by realstephenzhao** [comment]
You have to manually add some code to function.php of your child theme at this moment. The code below is written for ACF checkbox fields by Crocoblock support, but it should work on Jetengine checkbox meta fields as well.

/* Allow Checkboxes Filter(relation between checkbox is "OR") */

```add_filter( 'jet-smart-filters/query/final-query', 'jet_set_compare_operator' );
function jet_set_compare_operator( $query ) {
	// Replace '_preice_level' with your custom field name
	$meta_key  = '_preice_level';
	$new_query = array(
		'relation' => 'OR',
	);
	if ( ! empty( $query['meta_query'] ) ) {
		foreach ( $query['meta_query'] as $index => $meta_query_row ) {
			if ( is_array( $meta_query_row ) && !empty( $meta_query_row['key'] ) && $meta_key === $meta_query_row['key'] ) {
				foreach ( $meta_query_row['value'] as $value ) {
					$new_query[] = array(
						'key'     => $meta_key,
						'value'   => sprintf( '"%s"', $value ),
						'compare' => 'LIKE',
					);
				}
				$query['meta_query'][ $index ] = $new_query;
			}
		}
	}
	return $query;
}
```

**Comment by Arbthiter** [comment]
Thanks for Code. I tried it but it doesn't work. I overwritten in my case:
'relation' to 'AND' 
$meta_key to 'taxonomy'
... of course I tried it's original version too for both of them.

I attach screenshots links of the settings:
[](https://najrozpravky.tv/wp-content/uploads/2019/11/crocoblock-screenshot-1.png)
[](https://najrozpravky.tv/wp-content/uploads/2019/11/crocoblock-screenshot-2.png)
[](https://najrozpravky.tv/wp-content/uploads/2019/11/crocoblock-screenshot-3.png)

**Comment by realstephenzhao** [comment]
> 
> 
> Thanks for Code. I tried it but it doesn't work. I overwritten in my case:
> 'relation' to 'AND'
> $meta_key to 'taxonomy'
> ... of course I tried it's original version too for both of them.
> 
> I attach screenshots links of the settings:
> https://najrozpravky.tv/wp-content/uploads/2019/11/crocoblock-screenshot-1.png
> https://najrozpravky.tv/wp-content/uploads/2019/11/crocoblock-screenshot-2.png
> https://najrozpravky.tv/wp-content/uploads/2019/11/crocoblock-screenshot-3.png

Ohh, sorry. I misunderstood your question before.

Code above has been altered by me once. Now I show you the original code below. Just remove that line inside `query()`, the relation will act as "AND". I had tested before, it worked like a charm.

```
/**
 * Allow Checkboxes Filter(relation between checkbox fields is "AND")
 */
add_filter( 'jet-smart-filters/query/final-query', 'jet_set_compare_operator' );

function jet_set_compare_operator( $query ) {
	
	// Replace '_preice_level' with your custom field name
	$meta_key  = '_preice_level';
	$new_query = array();

	if ( ! empty( $query['meta_query'] ) ) {

		foreach ( $query['meta_query'] as $index => $meta_query_row ) {

			if ( is_array( $meta_query_row ) && !empty( $meta_query_row['key'] ) && $meta_key === $meta_query_row['key'] ) {
				foreach ( $meta_query_row['value'] as $value ) {
					$new_query[] = array(
						'key'     => $meta_key,
						'value'   => sprintf( '"%s"', $value ),
						'compare' => 'LIKE',
					);
				}

				$query['meta_query'][ $index ] = $new_query;
			}

			

		}

	}

	return $query;

}
```

**Comment by Arbthiter** [comment]
Thanks. We have one more problem with this application. I forgot to mention it, sorry. There is only taxonomy / terms search based checkboxes... not custom fields (we are not using them). What we do is put all phrases into taxonomy field as terms (you can check that in screenshots).

I hope this will help to find the solution.

**Comment by Arbthiter** [comment]
Hello, any news? :)

**Comment by S-Simon** [comment]
This looks awesome, any idea how to modify it for woocommerce product categories?

Thank you!

**Comment by realstephenzhao** [comment]
> Hello, any news? :)

Sorry, I have no idea now.

**Comment by realstephenzhao** [comment]
Seems this issue had been solved since JetSmartFilters added the relationship between fields months ago.

**Comment by MjHead** [comment]
Done
