### ISSUE TITLE
🐞BUG : jet smart filters not work with elementor popup on mobile

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6853]
**Describe the bug**

Hi crocoblock team

On the clients' websites, we display the product filter on the Elementor popup. After updating jet smart filters to the new version, the filters on the elementor popup do not work (on mobile).

Is there a workaround or quick fix for this?

**Comment by 79ho3ein** [comment]
Similar to : https://github.com/Crocoblock/suggestions/issues/6742

**Comment by SargasTM** [comment]
mobile is not the cause of the bug
in version 3.1.1 filter initialization has been redesigned. Now each filter is initialized separately on the js hook elementorFrontend.hooks.addAction('frontend/element_ready/jet-smart-filters-' + filterName')
I don't know it's a bug or a feature but in Elementor if the "Improved Asset Loading" option is enabled, when the user is not logged in, then the widgets that are in the popup will not fires this hook
<img width="1100" alt="image" src="https://github.com/Crocoblock/suggestions/assets/5094971/622b64cc-5079-43f1-9020-f12e88cf6db3">

**Comment by Joliamendi** [comment]
Hello @SargasTM 

Yes you are right. So is this a problem on Elementor side, or can it be fixed by you? So I disable this option for now so that the filters work.

**Comment by Joliamendi** [comment]
Do we need to report this to Elementor?

**Comment by MjHead** [comment]
@Joliamendi We looked deeper into this and looks like had found the solution. Also, not sure about your exact case, but some time ago we added tiny solution for making better UX for filters on mobile. Please take a look, maybe it fits you - https://crocoblock.com/knowledge-base/jetsmartfilters/how-to-create-responsive-filters-with-jet-offcanvas-column-addon/

**Comment by Joliamendi** [comment]
tahnk you @MjHead,

>We looked deeper into this and looks like had found the solution.

Will the desired solution be implemented in the next version?

**Comment by SargasTM** [comment]
Yes
in version 3.2.0 there will be no problem, I hope))

**Comment by Joliamendi** [comment]
Thank you dear ones
