### ISSUE TITLE
Selecting Relationships in Wordpress

### ISSUE THREAD

**Issue by yepyeh** [Crocoblock/suggestions#686]
Hi There,

I am using Jet Engine for my Custom Post Types.
I am using it for a Travel site.
So I have Trips as one CPT. And Destinations as another CPT.
I have made a Relationship between these two.
But in the Backend of Wordpress when linking them together you get this "Please enter 3 or more characters" to search and select the CPT.
I find this very annoying! And would like to see it as just a check box, just as we see when you have a Taxonomy.

Is there a way to change this? It would be so much better!!!

Oh and hide "Set Parent Destinations
Name: relation_19cdc0d3830768fd4a5c730003e4170a"
This is not necessary.

Kind Regards
Steven
![Screenshot 2019-11-20 at 12 46 08](https://user-images.githubusercontent.com/2827763/69328044-1c19f880-0c81-11ea-8ce2-82f548078da1.png)

**Comment by MjHead** [comment]
Re-factored with 2.11.0
