### ISSUE TITLE
simple bug in Checkout Order Review widget - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6863]
**Describe the bug**

Hi

The Checkout Order Review widget on the front end creates extra space at the bottom. This extra space does not exist in the editor. But it is clearly visible in the front end. Especially in mobile, this distance is more. 
I've tested this on mobile - Chrome browser and I see a lot of extra space at the bottom of the Checkout Order Review widget. Please pay attention to the two screenshots below that are on the desktop :

### in editor

![editor](https://github.com/Crocoblock/suggestions/assets/77163248/dce0163d-efd9-4677-8f93-a77715ee7c66)

### in frontend

![frontend](https://github.com/Crocoblock/suggestions/assets/77163248/97c11667-2c79-4024-912e-c93c725ba7bf)

**To Reproduce**

1. Add the Checkout Order Review widget in a container.
2. To better understand the problem, add another widget like Checkout Payment at the bottom of this widget.
3. Set the Gap value in the parent container of these two widgets to 0.
4. In the editor, there is no gap between these two widgets (because we set the gap value to 0 in the previous step)
5. Now check the checkout page in the frontend. The distance between these two widgets is large. In fact, the Checkout Order Review widget creates extra space at the bottom. **Especially in mobile, this distance is very large.**

**Desktop :**
 - windows
 - Browser  : chrome
 - Version 114.0.5735.90 - 64bit

**Smartphone :**
 - Device: Android
 - 13
 - Browser : chrome
 - Version 111.0.5563.116

thank you

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!

**Comment by 79ho3ein** [comment]
thank you @UraraReika.

Before contacting support, I hope this video helps you resolve the issue. The Checkout Order Review widget on the front end has an extra margin at the bottom. Please watch the video below.

https://github.com/Crocoblock/suggestions/assets/77163248/20066387-9624-4b15-9228-5a4961315b35

**Comment by UraraReika** [comment]
In my case margin exist in editor as well as in the frontend. But it will be fixed.
