### ISSUE TITLE
[Jetmap Listing] Add max zoom out option

### ISSUE THREAD

**Issue by mapsiter** [CrocoBlock/suggestions#6864]
Max zoom out option for the map so it won't zoom out the borders of the world (north, south, east, west). Now it does and it looks unprofessional with gray areas above and below the map while the map becomes a series of small, multiple world maps. It's possible to set with Google maps api and for a good example, pls see Airbnb. Attached is how Jetmap listing looks like when zoomed out to a maximum. ![PXL_20230606_151054828.jpg](https://github.com/Crocoblock/suggestions/assets/3584270/43830776-e661-4732-b371-3fd24bce22d5)

**Comment by MjHead** [comment]
v. 3.2.5

**Comment by mapsiter** [comment]
How is it compeleted?
