### ISSUE TITLE
Possibility to edit the title of the checkout payment widget

### ISSUE THREAD

**Issue by wnt-it** [CrocoBlock/suggestions#6865]
Hello Croco-Team, 

I noticed that there is currently no way to customise the title (= "Select payment method") of the Checkout Payment widget. 

Would be great if you can add the possibility to edit the title without using custom CSS, so that the corporate design of the website can continue.  

Here is a screenshot for better understanding: 
![Crocoblock suggestion](https://github.com/Crocoblock/suggestions/assets/66781534/2e88f77f-c9ac-47af-b1aa-b1603d5bbfba)

Thanks in advance. :)

**Comment by UraraReika** [comment]
Hello @wnt-it!

By default this widget and area in WooCommerce has no any headings. That is why there is no any controls for it. Maybe you use some theme or third party plugin that add this markup. Please [contact](https://support.crocoblock.com/support/home/ ) our support team and they will help you to solve this issue.

Thank you!
