### ISSUE TITLE
Undfold widget inside elementor tabs (container) only works on initial open tab

### ISSUE THREAD

**Issue by StenderIternum** [CrocoBlock/suggestions#6866]
**Describe the bug**
With Elementor containers activated, you can have all widgets in tabs - but your unfold widget doesn't work if it is in a tab that is not open on load - ie not the first tab. 
It seems like the HTML is there, but the trigger and separator is hidden, and the masking is not apparent. 

**To Reproduce**
Use elementor PRO with containers - 
Use JetElements unfold widget inside tabs with the normal Elementor pro widget. 

**Expected behavior**
When switching tabs, the unfold widgets should start closed, and work

I am on Versions : 
Elementor : Version 3.13.4 
Elementor PRO : Version 3.13.2
JetElements For Elementor : Version 2.6.10
JetEngine : Version 3.1.6.1
Wordpress : Version 6.2.2

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by StenderIternum** [comment]
@bazilik1095 Any ETA on when this will be out? 
Right now i have !important css to fix it, but the transition is not very smooth.
