### ISSUE TITLE
JETBOOKING PLUGIN ADD CALENDAR AND EASIER MANAGING

### ISSUE THREAD

**Issue by BMIncredible** [CrocoBlock/suggestions#6868]
Hi, I have the full bundle of crocoblock and bought it to build a future rich Real Estate Website. I wanted to add booking functionality so I can rent houses, apartments to potential guests. 

The issues are these: 

1. There is no calendar. I found out that in jetappointments this is there. Like... ok!? 
2. From the post type that is created once the booking is created there is a small windows that let's you "edit" the booking. Just put a dropdown there for the status of the booking so it is easier to change it not typing it. 
3. A drop down with search for users so I can change the user easier
4. Check In - Check Out Dates. Once I click on them a calendar to pop up so I can change the dates from there if needed.
5. In the calendar view, if and when you add it. You MUST add it. When I click on a booking to be able to edit it fast. Let's say a pop up opens that let's me edit the whole thing.
6. There is no search in the bookings. This is MANDATORY. How am I supposed to find a specific booking??? Please add this!!!

**Comment by UraraReika** [comment]
Hello @BMIncredible , thanks for your feedback!

1. There is special  field type for JetForms called Check-in/check-out dates - https://tppr.me/RI5RU similar field exist i JetEngine forms as well. There is although Elementor widget - https://tppr.me/7mV7p for displaying booking calendar. This is how it look at the frontend - https://tppr.me/dBcZ2.
2. This is the list of created bookings - https://tppr.me/cWHrF. If you press edit button popup will show - https://tppr.me/BuZpY. Here as you can see status field presented as dropdown field where you can select any status you want - https://tppr.me/WhbSH.
3. Please specify this one. Where you want to see this functionality; how should it work and for what purpose ?
4. As you can see from the previous answers our date picker system works exactly like this.
5. You can edit whole booking in the popup from admin panel as I said in  point 2.
6. One of our next release will have filtering functionality witch will help you to search booking more convenient.

**Comment by BMIncredible** [comment]
Hi, yes the filtering and searching of bookings is important. Also if the bookings, like all the bookings where available in a calendar format so the property manager can have a clear overview of what's happening. Not to just check the availability. 
Also, check in check out I think it'd be great to seperate them in the database. So I can be able to send over this data to the coresponding post type of orders and be able to save that data as a timestamp for filtering. I tried to make this work now by adding a date range filter in a page but it doesn't read the check in check out dates. 
In the screenshot below you will see what I'm trying to build. 
https://prnt.sc/ZhXz048gv0PY

It would also be great, all the functionality of the booking management to be able to put it in a form on the front end. Just like editing a post. This would be great because then we have the ability to style it however we like and the client won't have to login to the backend to manage bookings. All on the front end.

**Comment by UraraReika** [comment]
> Also if the bookings, like all the bookings where available in a calendar format so the property manager can have a clear overview of what's happening.

Please keep an eye on this issue - https://github.com/Crocoblock/suggestions/issues/6303

> Also, check in check out I think it'd be great to seperate them in the database. 

Check in and check out dates stored in DB separately in timestamp.

> So I can be able to send over this data to the coresponding post type of orders and be able to save that data as a timestamp for filtering. I tried to make this work now by adding a date range filter in a page but it doesn't read the check in check out dates.
> In the screenshot below you will see what I'm trying to build.
> https://prnt.sc/ZhXz048gv0PY

RIght now you can't do that but please rrack this issue - https://github.com/Crocoblock/suggestions/issues/6009, 

> It would also be great, all the functionality of the booking management to be able to put it in a form on the front end. Just like editing a post. 

https://github.com/Crocoblock/suggestions/issues/6401
