### ISSUE TITLE
Multi step form builder

### ISSUE THREAD

**Issue by clovercreate** [Crocoblock/suggestions#687]
Hello guys, is it possible to make a form builder with:
Multi Step Form, Repeater Fields, Conditional Logic, Calculated Fields and more.

Just like this example:
https://pafe.piotnet.com/docs/form-builder/

That would be great!

**Comment by tole011** [comment]
This is long overdue. What is the point of paying for all-in-one plugins when I can accomplish more and more features with free third-party plugins?

**Comment by Floydtm** [comment]
It looks like these plugins cover your request https://crocoblock.com/plugins/jetengine/ https://wordpress.org/plugins/jetformbuilder/
