### ISSUE TITLE
Ability to remove or customise POIs on Google map

### ISSUE THREAD

**Issue by inveress** [CrocoBlock/suggestions#6870]
I often don't need Google's POIs (points of interest) showing on my map, and it would be nice to remove them.

It would be great to have either:

(a) An option to switch them all off, or
(b) Options to customise which ones appear, or
(c) Some way of hooking into the map that's being generated so that I can add my own maps commands to it (to add things or hide things).

I think some form of option (c) would be great if it also allows adding things such as polygons (for which I have also seen a request in GitHub).

**Comment by Lonsdale201** [comment]
Since you can use a custom map style, when you create one here : https://snazzymaps.com/ you simply don't display what you don't need, for example POIs. It's completely unnecessary to put in such functionality when you can easily do it yourself.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by inveress** [comment]
> Since you can use a custom map style, when you create one here : https://snazzymaps.com/ you simply don't display what you don't need, for example POIs. It's completely unnecessary to put in such functionality when you can easily do it yourself.

@Lonsdale201 - How does this help when making a map in JetEngine? Are you saying we can use a SnazzyMap as the basis for a JetEngine map?

To clarify, I don't just want a map, I am plotting points on it dynamically in JetEngine, so it needs to be something usable in JetEngine. I was initially trying to add in extra external JS code to make changes to the map but I have not been successful.

**Comment by inveress** [comment]
> At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

Thanks for this response @Floydtm. I know it's not within the bounds of support but can you offer any advice on how I could possibly add extra JS code via header insertion (for example) to make changes to a JetEngine Map? For example, a map polygon that is attached to a button to switch it on and off? I'm really stuck.

There is apparently a patch that allows this functionality but I haven't got it to work:
https://github.com/Crocoblock/suggestions/issues/5738
