### ISSUE TITLE
[JetEngine] Ability to add a custom field to section slideshows in Elementor

### ISSUE THREAD

**Issue by revywebdesign** [CrocoBlock/suggestions#6872]
Hello,

I'd like to be able to add a JetEngine meta field for section background slideshows in Elementor. It is possible to do this for background images but not slideshows.

**Comment by Lonsdale201** [comment]
There are several solutions. You can use the Jetelements slider system (there is a header, subtitle, description and buttons) or you can use the free steroid for elementor plugin and create sliders from columns (glider is the name of the function).

**Comment by Floydtm** [comment]
Hello! Unfortunately, we can't fulfill this request because it's out of our control. You need to leave a request [here](https://github.com/elementor/elementor/issues), or use other options that were suggested in the comments. Thank you!
