### ISSUE TITLE
Jet Compare Wishlist - Wishlist button opens the product as well.

### ISSUE THREAD

**Issue by brezitski** [CrocoBlock/suggestions#6887]
**Describe the bug**
When the "Make Product Item Clickable" is enabled from Jet Products Grid, and the wishlist button is in the top right corner, and you click on it, it adds the item to the wish list but it also opens the product itself. 

**To Reproduce**
1. Go to 'https://lemar.bg/test/'
2. Click on 'Wishlist button'
3. See error

**Expected behavior**
The wishlist button should not open the product but only add the product to the wishlist.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox Developer Edition]
 - Version [115.0b5]

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S21 Plus]
 - OS: [Android 13]
 - Browser [Samsung Internet Browser]
 - Version [19.0.3.12]

**Additional context**
The Test page provided in this bug description is set to PRIVATE. Please respond to this so we can make it Public and you can test it. The issue appears on all browsers and OS but the above info is for the latest tests.

**Comment by UraraReika** [comment]
This issue about JetWiiBuilder and not JetCompareWishlist, so the fix will be available in one of the next releases.
