### ISSUE TITLE
Compatibility of jet compare and wishlist with bricks builder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6892]
Hi crocoblock team!

Do you have a plan for the compatibility of jet compare and wishlist plugin with bricks builder? I hope you have it in your plans.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6011, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
