### ISSUE TITLE
[Bricks Builder] Error encountered while creating Nested listing.

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6895]
I have created a nested listing on Bricks Builder using this tutorial (Nested Post's listing under Term Listing) - https://www.youtube.com/watch?v=H3qA4O5gNOk. However, an error is being displayed. Please refer to the attached image.

<img width="779" alt="Screenshot 2023-06-21 at 8 20 29 PM" src="https://github.com/Crocoblock/suggestions/assets/68687765/529f88af-8b40-4a68-93bb-e4ae1666c1f8">

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by sekhsoyebali** [comment]
@Floydtm Follow this exact tutorial(Splitting with Category) using Bricks Builder, and you will be able to identify the bug. - https://www.youtube.com/watch?v=H3qA4O5gNOk
