### ISSUE TITLE
jet search : Ability to display search results in multiple columns

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6896]
Hi crocoblock team,

It would be great if you could add the ability to display search results in multiple columns. for example in the screenshot below, the search results are displayed in two columns.

![search](https://github.com/Crocoblock/suggestions/assets/77163248/3a0b1484-eac3-4d8a-b08a-8948b76a4135)

**Comment by Crocoblock** [comment]
was added and released in JetSearch 3.5.0
