### ISSUE TITLE
JetSearch v3.1.0 Beta

### ISSUE THREAD

**Issue by MjHead** [CrocoBlock/suggestions#6898]
Hi,

We are almost getting ready to release JetSearch v3.1.0 and we would like to ask you to help us test JetSearch v3.1.0 Beta.

You can download beta version from your Crocoblock account.

Please note that is a beta version, not stable release, so its not ready to use on production websites!

### Search Suggestions widget

A new widget for Elementor and a block for the WordPress Block editor called Search Suggestions. The examples below inspired the first widget version:

- https://www.aliexpress.com/
- https://www.amazon.com/
- https://www.target.com/ (except for the Recently Viewed section)
- https://www.newegg.com/

The new widget is called Search Suggestions. This widget is different from the Ajax Search widget. We decided to separate them because, despite some similar elements in the UI and options, the widgets perform different tasks. Ajax Search displays quick search results based on the beginning of the search phrase. The results range can be very wide since the search starts from the first three characters entered. Search Suggestions helps the user choose the most appropriate search phrase, depending on the search query options that have already been used on this site or pre-set by the admin. Thus, the new widget neither searches for any site content nor returns any search results. All results will be displayed already on the search results page. 

Mixing these widgets will not work because it will be confusing for the user. Imagine the following scenario: first, the user enters a search phrase, and in the dropdown, they see options in which this phrase has already been searched. Second, the user clicks on one of the presented options, and the content in the dropdown reloads, displaying quick search results already. However, when the user clicks the “Search” button, the widget still redirects to the search results page. 

I haven’t come across such strange logic on any live website. That’s why we have two separate widgets. It’s not in our plans to merge them.

**Terminology**

The widget displays recommended search queries (suggestions). The list of these suggestions is formed from previously entered real search queries (or those manually entered by the site administrator). Therefore, in the context of this widget, suggestions are basically search queries.

**Logic and UI on the front end**

The widget outputs a standard search form. When you start entering text in the Search field, the widget looks for matching search queries in the database on this website and displays a list of queries containing the entered text, i.e., suggestions. Suggestions are sorted by Weight. Weight is the number of searches for this query. This means that if a suggestion has a Weight of “1,” this exact phrase/word was searched for once, and if its Weight is 28 – users searched it 28 times. The higher the Weight, the higher this suggestion will be placed inside the dropdown in the search form.

Clicking on a suggestion in the dropdown is similar to entering this search phrase in the search field and clicking the “Submit” button. In both cases, you will be redirected to the search page with the selected suggestion as a search query. At the same time, the Weight of the suggestion in the database will increase by 1. If the user enters a unique search phrase and submits the form, this phrase will be added to the suggestion base with a Weight of “1.”

Each suggestion can have one parent. When entering a search phrase, the widget will run a search in the Suggestions database. If any of the found suggestions has a parent, then this parent item will supersede that suggestion, and the sorting will be performed taking into account the parent’s Weight. This logic is responsible for typing errors; for example, we have “iphone” and “ihpone” suggestions. We have assigned “iphone” as the parent of “ihpone.” Now if the user starts typing “ihp” instead of “iphone,” they will be shown the parent suggestion, which is “iphone.” 

**Widget settings**
- _Placeholder Text_ – placeholder text for the Search field.
- _Show preloader_ – show/hide the preloader (loading animation) before showing suggestions. If the option is enabled, a dropdown with a preloader will appear as soon as you start entering a search query and will be replaced by a list of suggestions afterward. If the option is disabled, the dropdown will appear only when the first suggestions are found.
- _Highlight Searched Text_ – whether or not to highlight the entered text in the list of found suggestions.
- _Number of Suggestions_ – allows setting the maximum number of suggestions displayed in the dropdown.
- _Show Submit Button_ – show/hide the search button.
- _Submit Button Label_ – if the button is shown, you can set a text label for it.
- _Submit Button Icon_ - if the button is shown, you can set an icon for it.
- _Show Categories List_ – show/hide the category Select. This Select is not related to suggestions at the moment. Using it, you can select a category where the search will be performed later (similar to the Ajax Search widget).
- _Taxonomy_ – allows choosing which taxonomy terms will be shown in the category Select.
- _Select Placeholder_ – placeholder text for the category Select.
- _Show Suggestions Below Search Form_ – show/hide the list of suggested search queries below the search form. Clicking on a suggestion in this list works similarly to selecting this suggestion in the form. In both cases, you will be redirected to the search page with the selected suggestion as a search query. 
- _Suggestions List_ – allows setting where to get suggestions for this list: from the most popular search queries on the site, from the latest search queries, or manual input. With manual input, you just need to enter a list of search queries separated by commas. This list is not directly related to the Suggestions database. When you click on these suggestions, their processing will occur as with a regular search query, meaning if it is already in the database, its Weight will be increased by 1. If this is a new request, it will be added to the Suggestions database with a Weight of “1.”
- _Number of Suggestions_ – the maximum number of the most popular or latest suggestions we want to show.
- _List of Manual Suggestions_ – a field for entering a list of Manual Suggestions.
- _Show Suggestions on Input Focus_ – allows you to determine whether to display or not a list of recommended suggestions when clicking on the Search field.
- _Suggestions List_ – is configured similarly to the same option for Show Suggestions Below Search Form.
- _Number of Suggestions_ – is configured similarly to the same option for Show Suggestions Below Search Form.
- _List of Manual Suggestions_ – is configured similarly to the same option for Show Suggestions Below Search Form.

**Admin UI to manage suggestions**

All recorded search queries you can find under the **Crocoblock > JetPlugins Settings >JetSearch > Suggestions**. Here you can manually add new suggestions or edit existing (change naming, weight of suggestion or attach parent to this suggestion)

Parent functionality can be used to manage typos or spelling variations. You can use some suggestion as main - parent. And attach all variations of this suggestion as children. In this case, parent suggestion will be shown in the widget on front when user start to input any of it's children names.

**Please leave your feedback and any found bugs or issues in the comments below**

**Comment by mehdimoradi1500** [comment]
Hi thank you guys
It will be great to make it compatible with bricks builder 🙏

**Comment by Joliamendi** [comment]
cool update!

Unfortunately, due to busy work, I cannot review this beta version. But I saw the YouTube review video and had a few questions and a suggestion...

1- As seen in the video, the new widget is exactly like the old one, but with new features. It is true?

2- Is the preloader disable button added only in the new widget, or will we have it in the old widget as well?

### suggestion

I hope it is possible in this version, please add a custom icon for the categories section of the search widget.

![jet search](https://github.com/Crocoblock/suggestions/assets/103376243/332ab932-b9da-4888-83cf-7a6f3344e0fc)

**Comment by nreljed** [comment]
hello, 
I switched to bricks builder months ago and elementor is the past for me and probably for many others here.
don't let your plugins stay away from the bricks sphere, it's important that they stay compatible from day 1

don't forget that your user base is also evolving in terms of skills and awareness on performance and good practice (never again unjustified infinite divs like elementor) the whole future is at stake on your ability to evolve on this precise point. remain compatible with bricks in priority then elementor after..

I also expect a lot from jetsmartfilters beta to stay at the top 1 of the most advanced filters and 100% bricks compatible

**Comment by Lonsdale201** [comment]
> 

Yes, next year there will be another fashion site builder that will be up to date. Right now there are two, brick and break dance. :D I always have a good smile on my face when people talk about it. (In the background Gutenberg is progressing nicely, evolving and will be able to wipe all the unnecessary page builders off the map in years to come)
