### ISSUE TITLE
compatible Jet woobuilder with bricks builder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6903]
Hi crocoblock team.

Do you have any plans to make jet woobuilder compatible with bricks builder?

**Comment by 79ho3ein** [comment]
https://github.com/Crocoblock/suggestions/issues/5941

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5941, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
