### ISSUE TITLE
JetBooking 

### ISSUE THREAD

**Issue by Wieldopje** [CrocoBlock/suggestions#6904]
**Describe the bug**
Whenever you create a booking and proceed to the checkout page it already creates a booking even if you haven't paid. Therefore bookings can be made which will block the calender and result in loss of income.

**To Reproduce**
1. Go to a booking site
2. Book a room and proceed to checkout
3. The booking is added to the bookings calender already

**Expected behavior**
1. Go to a booking site
2. Book a room and proceed to checkout
3. Pay for the room
4. Add the booking to the calender

Thank you in advance!

**Comment by UraraReika** [comment]
We made this booking - https://tppr.me/mYMXU, and it displays in our booking list - https://tppr.me/LkIAs with status `Created` and this is important, payment not done yet. If in this situation we go to our apartment we will see that booked dates is free to book - https://tppr.me/aqTBR. So in this situation despite booking item was created it will still possible to book this date while status is `Created`.

Our plugin has status system that block or unblock booking dates depending on selected status.

If something works incorrectly in your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
