### ISSUE TITLE
Direct messaging admin to user in user account

### ISSUE THREAD

**Issue by smithy5021** [CrocoBlock/suggestions#6906]
It would be a game changer for certain types of websites to give the option to have a direct messaging communication system between Admin to User and User to User.
It could be added to JetEngine to integrate with the membership aspect of it.
It would allow a user to connect to their profile and send messages to other users or to the admin and have all their communication stored on the same page just like a messaging app.
What do you think ?

**Comment by Lonsdale201** [comment]
Own opinion. This is the kind of functionality that is outside. The message box function is available in many specialised plugins, it is easier to use. Also people don't like to "monitor" many pages. They prefer to have the standard and practical channels. Especially those that have apps on the phone (fb, discord messenger, email, etc.). If you are an app developer it is useful. For a website it's redundant.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
