### ISSUE TITLE
compatibility of jet compare and wishlist with bricks builder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6914]
Hi team!

jet CW It is a special plugin in its own way. Therefore, at the moment, we do not have a way to add products to wishlist in bricks builder. Please make this a priority.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6011, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
