### ISSUE TITLE
Permalink Apply Filter not Supported

### ISSUE THREAD

**Issue by danielbarenkamp** [CrocoBlock/suggestions#6916]
Hi there,

about woo jet engine builder.

In this file "include/class-jet-woo-builder-template-functions.php" line 284 you use:

`return esc_url( $product->get_permalink() );`

However your code NOT respect wp coding standard and the post_type_link filter is not applied. We are plugin developers and this causes an error in our code and all customers using your plugin. 

Please add the filter by replacing above code wit this:

`return esc_url( apply_filters( 'post_type_link', $product->get_permalink(), get_post($product->get_id()), false, false  ) );`

**Comment by danielbarenkamp** [comment]
Any update?

**Comment by UraraReika** [comment]
Hellp @danielbarenkamp !

This method `$product->get_permalink()` that we used to get product permalink has filter hook inside. If you follow the sequence , you will see it. We call the following method - https://tppr.me/FqqWF  which in turn calls the following method - https://tppr.me/89g8y. This method calls several hooks - https://tppr.me/sRcjc and https://tppr.me/mfbnB. You can use one of them to fulfil your needs.

So we don't see the need to add the hook you mentioned.

If you specify your problem, we will try to help you.

Thank you for your understanding
