### ISSUE TITLE
Jet Engine / CPT Fields UI Bug

### ISSUE THREAD

**Issue by Vigar007** [CrocoBlock/suggestions#6917]
![jet](https://github.com/Crocoblock/suggestions/assets/108021806/4da6ecbd-cff7-4fad-bde6-49fe7e9d5cc9)
Bug Report

**Step 1**: create a CPT, then chose the select field, add something like “apple” and save.

**Step 2**: Try adding “berry” and save.

**Step 3**: Click on POST TYPE or refersh and “berry” is gone.

It only allows you to save once.
Jetengine 3.2.1 ---- reverting back to 3.1.6.1 solves the problem.

**Comment by nivelsurstudio** [comment]
me pasa lo mismo

**Comment by Vigar007** [comment]
> me pasa lo mismo

Revert back to 3.1.6.1 until they fix it

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
