### ISSUE TITLE
Can You Please Add Settings for Permalinks?

### ISSUE THREAD

**Issue by mukesh120** [CrocoBlock/suggestions#6919]
By Default the url only contains the custom post type in the URL, however, I would also like to have custom taxonomy in the URL. And I also want to customize the depth of that taxonomy.

For instance, If I have a parent category and a sub-category, I would only like to show the parent category and then the URL. 

For example, my custom post type is Bible, and my custom taxonomy is Titus, and I have written an article in that. I would like it to show like - http://example.com/onlinebible/titus/summary

instead of  - http://example.com/onlinebible/summary

**Comment by Lonsdale201** [comment]
https://hu.wordpress.org/plugins/permalink-manager/
