### ISSUE TITLE
Intermittent JetForm Population Issue Linked to Undefined Index in JetEngine Plugin

### ISSUE THREAD

**Issue by 97NovaClaw** [CrocoBlock/suggestions#6920]
**Describe the bug**
Intermittent issues are occurring with the JetEngine plugin during the population of a JetForm tied to a Custom Content Type (CCT). The form is designed to populate with data fetched from a table based on a URL query variable, but it occasionally fails to do so. A PHP Notice for an undefined index 'action' is being thrown in `type-pages.php`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a JetForm to be populated with data from a CCT, using a URL query variable to fetch the data.
2. Navigate to the form's page.
3. Sometimes, the form fails to populate with data.
4. Upon checking the server error logs, a PHP Notice is found, indicating an undefined index 'action' in `type-pages.php`.

**Expected behavior**
The JetForm should consistently populate with the correct data fetched from the CCT based on the URL query variable.

**Screenshots**
[Not available - error visible in server error logs]

**Desktop (please complete the following information):**
 - OS: [All]
 - Browser [All]
 - Version [All]

**Smartphone (please complete the following information):**
 - Device: [All]
 - OS: [All]
 - Browser [All]
 - Version [All]

**Additional context**
Upon inspecting the JetEngine code, the PHP Notice appears to originate from the function `is_type_page()` within the `type-pages.php` file. The function is trying to access `$_REQUEST['action']` without first verifying if the index 'action' is present in the `$_REQUEST` superglobal. 

Proposed solution is to add an `isset()` check as follows:

```php
public function is_type_page() {
    $ajax_check = wp_doing_ajax() && isset($_REQUEST['action']) && $_REQUEST['action'] === $this->get_page_slug();
    return (!empty($_GET['page']) && $this->get_page_slug() === $_GET['page']) || $ajax_check;
}
```
The above change should prevent the PHP notice and might improve the form's data population reliability. I look forward to a resolution in an upcoming update.

**Comment by 97NovaClaw** [comment]
After trying my own suggested fix, this seemed to not work. If any other suggestions could be made that  would be helpful, ps crocoblock team you guys are awesome, thanks for your products - they slap

**Comment by kaskad88** [comment]
@GOOCHprime 
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
Thanks.
