### ISSUE TITLE
JET SEARCH - Ajax Search - Ability to use Template in live results area

### ISSUE THREAD

**Issue by Bertnick1** [CrocoBlock/suggestions#6926]
I would like to ask if it is possible to implement a solution to use Custom Templates in the Live results area of ​​the Ajax search.
In order to further customize the display, for example it would be interesting to be able to have two columns or three columns in the results.

**Comment by oceandiveloper** [comment]
+1 I already [suggested something like this 3 years ago](https://github.com/Crocoblock/suggestions/issues/1499) but JetSearch is not a priority apparently.

**Comment by GastonIsDead** [comment]
@Gawuww 

для лістинг темплейта не працює хайлайт пошукового запиту в результатах: ні в тайтлі, ні в контенті, ні в кастомних полях
без лістинг 
без нього все працює ок як і раніше

**Comment by GastonIsDead** [comment]
фукнціонал Make listing item clickable не працює в results area АЯКС сьорчу. курсор змінюється як при реакції на клікабл елемент, але нічого не відбувається при кліку.
відео: https://drive.google.com/file/d/17s--pYAgy3YhIdGSOkphShwn6sY6Ow6S/view?usp=sharing

**Comment by Crocoblock** [comment]
was added and released in 3.4.0
![image](https://github.com/Crocoblock/suggestions/assets/47778274/01a8e4fc-83f4-44e9-ae77-a3c3af0847b9)
![image](https://github.com/Crocoblock/suggestions/assets/47778274/ba1f0695-e2e6-449c-86cd-3113d2f24a95)
