### ISSUE TITLE
JetSearch Plugin - Combine Ajax Search widget with Search Suggestions widget.

### ISSUE THREAD

**Issue by Cub4nezU** [CrocoBlock/suggestions#6928]
It would be fantastic to have a widget that combines both functionalities. When the user clicks on the search bar, the suggestions should appear, and as the user begins typing, the Ajax feature should come into play to provide real-time results. This would create a seamless and efficient search experience for the users.

**Comment by Michaelgimii** [comment]
It's really strange to me why they decided to have two different widgets. When we use the Search Suggestions widget, we don't have many of the previous widget settings. That's why I didn't use the new Search (Suggestions) widget.

**Comment by MjHead** [comment]
No, there is no plan on this not now nor in the future. It is separated in 2 widgets because these widget have mutually exclusive UI/UX/Logic on the front.
