### ISSUE TITLE
JetWooBuilder(Single Rating) optimization 

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#693]
In the case there is at least one rating, the widget is displayed  https://prnt.sc/q04aqb 
But when there are no ratings, nothing is shown https://prnt.sc/q04b4a. The widget is also displayed when the zero is set  https://prnt.sc/q0kbpj. The visible structure of the page is simply broken when there is nothing at all. In addition, it is better if the client sees that there is a rating system, but no ratings, and another when it is not clear whether there is a rating system at all.

**Comment by UraraReika** [comment]
Done. Next release.

**Comment by marcofrasson** [comment]
Hello! I need to hide the stars when the product has no ratings. I am using version 1.5.0 which adds the stars even when the product has no ratings. I need them to be hidden, as it was before, and it's the WooCommerce standard. Maybe have a filter to hide them, is it possible?

**Comment by Floydtm** [comment]
@marcofrasson, hi! we will refine this option in the next plugin release
