### ISSUE TITLE
Jet Engine Rich text Fields

### ISSUE THREAD

**Issue by JPITH** [CrocoBlock/suggestions#6931]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**
can you had the type of fields rich text(WYSIWYG) in metafields like ACF does

**Add an example of where this feature is already implemented. **
![Add-New-Field-Group-‹-Body-Beautiful-—-WordPress](https://github.com/Crocoblock/suggestions/assets/87413188/895f7587-acfd-478d-ad67-460bc731d728)

**Comment by Lonsdale201** [comment]
Jetengine also have this type of meta field 🙃

**Comment by kaskad88** [comment]
@JPITH https://tppr.me/GMujx
