### ISSUE TITLE
Jet Search Intergrate with Jet Profile Builder

### ISSUE THREAD

**Issue by sadra44** [CrocoBlock/suggestions#6938]
Hey there,

since profile builder is part of Jet Engine features, many may activate this feature to make unique profiles.
Such sites usually require a search bar to search for users as well.

I Think it would be great if Jet Search also supports User Profiles as a source of search and clicking on results takes users to the profiles built with Jet Engine.

There are other Search plugins that can be used to search for users, but they show results in form of default wordpress Author pages, ot the profiles built with jet engine.

It would also be great to set User Metaboxes to the search as well: for example user custom profile pics or any other information.

Thanks!

**Comment by moxet** [comment]
I recommend you use JetSmartFilter search element and display your users in listing?

**Comment by Crocoblock** [comment]
After release 3.5.0 you can show in the search result list of Users
![image](https://github.com/user-attachments/assets/dd2d8702-1a31-465d-ad37-2a4c0ecadaeb)
