### ISSUE TITLE
How to exclude object cache from a specific listing and query?

### ISSUE THREAD

**Issue by smiljimenez** [CrocoBlock/suggestions#6940]
Hello, I hope you are well. Congratulations on the amazing JetEngine tool.

I am writing to you here because I have a particular problem that I have been trying to solve for several weeks. It happens that I am using redis for the object cache. I am using Profile Builder, Custom Content Type, Listing and Query Builder for a job portal. He built a dashboard for people who post their job openings, where they can view a list of their postings. The thing is that when they delete a post, because it is not reflected due to the object cache, the only way would be to clear the object cache.

I have been documenting that there are ways to delete the object cache in Redis, but that I would need some keywords or names that the developer uses for the cache.

Is there a way to clear the object cache in redis for a specific listing and query builder? So, don't stop caching objects to the other listings.

I'm trying to do this, from this video but with Jetengine: https://www.youtube.com/watch?v=dbHbhdR10B4

**Comment by sekhsoyebali** [comment]
Follow

**Comment by kaskad88** [comment]
In JetEngine v3.3.0 added an ability to disable query caching https://tppr.me/qf3R1
