### ISSUE TITLE
focus status control for Custom Quantity Selectors - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6944]
Hi

Currently, when we click on the + - buttons in the Custom Quantity Selectors plugin, the focus color is not controllable and actually the focus color is taken from the hover color. Please add the ability to control focus status to the +- buttons in the Custom Quantity Selectors plugin.

thanks

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce additional style functionality into our plugin. Right now we kepp only maintaining the plugin without implementing new functionality.

Thank you for your understanding.
