### ISSUE TITLE
errors in jet woobuilder theme builder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6950]
In recent versions of jet woo builder > Elementor, three errors are constantly displayed in the editor. 

![error](https://github.com/Crocoblock/suggestions/assets/88034902/dd27aa5e-3e68-45dc-a057-a6c5aa90fbd9)

This error can be seen in all the pages we create with Jet Woobuilder. Especially single product.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
