### ISSUE TITLE
Autocomplete on JetSearch 3.1.0 has error - v3.0.3 does not

### ISSUE THREAD

**Issue by pajtai** [CrocoBlock/suggestions#6951]
**Describe the bug**
When using JetSearch v3.1.0 autocomplete, I get the following error. I get no error with JetSearch v3.0.3

```
[19-Jul-2023 19:13:53 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Jet_Search_Rest_Search_Route::prepare_terms_data() in wp-content/plugins/jet-search/includes/rest-api/endpoints/search-route.php:196
Stack trace:
#0 wp-content/plugins/jet-search/includes/rest-api/endpoints/search-route.php(56): Jet_Search_Rest_Search_Route->set_query_settings()
#1 wp-includes/rest-api/class-wp-rest-server.php(1181): Jet_Search_Rest_Search_Route->callback()
#2 wp-includes/rest-api/class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request()
#3 wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch()
#4 wp-includes/rest-api.php(410): WP_REST_Server->ser in wp-content/plugins/jet-search/includes/rest-api/endpoints/search-route.php on line 196
[19-Jul-2023 19:14:28 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in wp-content/plugins/jet-search/includes/ajax-handlers.php on line 176
```

I can see that `prepare_terms_data` is in the `Jet_Search_Ajax_Handler` handler class and not `Jet_Search_Rest_Search_Route`

**To Reproduce**
1. Set up search with JetSearch automcomplete

**Expected behavior**
Autocomplete results appear

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
I fixed the issue by rolling back to version 3.0.3. The bug is in JetSearch version 3.1.0.

**Comment by Crocoblock** [comment]
Released in version 3.2.1
