### ISSUE TITLE
Activating jet search creates two site health error.

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6952]
Hi @MjHead,

After activating the jet search plugin, I encounter two errors in the health section of the site. Please check them out if possible.

![jet s](https://github.com/Crocoblock/suggestions/assets/103376243/ec3cb210-e0ec-412d-95a6-76a3769ba44a)

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.
