### ISSUE TITLE
geo_query_distance calculating wrong?

### ISSUE THREAD

**Issue by lepsii** [CrocoBlock/suggestions#6953]
Hello, I think that the geo_query_distance is calculated completely incorrectly. I tried to sort the posts by distance. They are also sorted, but they are completely messed up.

When I look at the preview in the query builder, I see my posts and also the field "geo_query_distance". However, as I said, the sorting does not fit. I would really like to see nicer geo features.

![Unbenannt](https://github.com/Crocoblock/suggestions/assets/25620165/beabc50f-5ce8-4d8c-8120-63c4b250db1f)

**Comment by kaskad88** [comment]
@lepsii 
Thanks for your feedback.

Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

Thanks.
