### ISSUE TITLE
JetSmartFilters - JetEngine CPT Meta Key Filter 

### ISSUE THREAD

**Issue by agarwalc** [CrocoBlock/suggestions#6955]
Trying to migrate a radio filter that uses custom field data on JetEngine CPT to Visual filter, but can't find this option.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
