### ISSUE TITLE
Jetbooking and some request/changes need

### ISSUE THREAD

**Issue by Qubadi** [CrocoBlock/suggestions#6959]
Hello

First of all, please if this has been brought up before, send us the request id and I can follow up on it. 3.5K have been written, so unfortunately I don't have the opportunity to go through all of this, so I'm writing some suggestions for the Croco team.

I've been using Croco plugins for a few years now, and I'm personally happy with the general Croco plugins.

But there are 2 plugins that I want to bring this up and they are Jetbooking and Jetappointment.

1. Jetbooking in itself is not a booking system, in order to use Jetbooking, you have to have an additional plugin such as Jet engine, which you also have to pay for.

If you are going to buy Jetbooking, you also have to buy another plugin to be able to use Jetbooking.

I have never seen this anywhere and only at Croco.

I have the lifetime package and that part is not such a big problem for me.

2. As I said, Jetbooking is not a complete booking system even if you have Jetengine plugins.

Jetbooking does not have its own calendar.

Jetbooking does not have any search places on the Jetbooking back end.

Jetbooking does not have anything called Upcoming booking.

Jetbooking has no time and only date.

On the Jetbooking back end, add new booking, there you have to manually fill in all the information, and when you select a date to book an appointment for a customer, the price does not show any seats either.

Jetbooking has no pictures, if a room or a car is booked it only shows titles and no pictures.

Jetbooking has no filter you can use.

Jetappointment also has a lot of shortcomings in the booking system in the back end.

I'm not writing this to bash Crocoblock's products, quite the contrary.

I am writing this so that Croco will be improved and not slaughtered.

All this I have written, many people have taken this up with you, both on chat, ticket support, youtube comment, facebook group etc...

I recommend the Croco team to spend a few minutes on Google and see how a booking system really looks and should be.

I also recommend the Croco team to learn and acquire ideas such as the Booqable booking system or Vikrent.

I also recommend Croco teams, the very days and hours they spend answering us here and there, that they spend half of it on improving their products.

We are in an AI technology world and are not in the 90s year.

Strongly recommend, that Croco starts to renew itself and not go in the old circle round and round.

I thank you again for what you do and try to deliver.

You have also done a lot of good things, but there is also a lot that is undone and not complete.

Wish you all a nice day.

Hoping for better changes and better functionalities.

Qubadi

**Comment by MjHead** [comment]
Sorry, but closing this - thanks for the general recommendations, it was interesting to read, but the whole thing it's not something we can add to roadmap and work with
