### ISSUE TITLE
JetEngine – Leaflet Maps | GDPR Compliance and Customization 

### ISSUE THREAD

**Issue by clmnsm** [CrocoBlock/suggestions#6960]
Hello,

to use embedded maps in germany, we need a data processing agreement with the tile provider.

Unfortunately, OpenStreetMap does not provide DPAs.

A simple solution is to run a tile proxy on the webserver – but to make this work with JetEngine, I need to replace the hardcoded tile url with my own.

`wp-content/plugins/jet-engine/includes/modules/maps-listings/assets/js/public/leaflet-maps.js (Line 67)`

For example:
```
L.tileLayer('https://my.custom.domain/osm/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo( map );
```

This, however, will be overridden by every update.

Can you add a filter (or setting) to replace the tile url when using Leaflet Maps?

**Comment by kaskad88** [comment]
@clmnsm
Could you add your code snippet that you want to add ?

**Comment by clmnsm** [comment]
I'm currently replacing `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` with `https://my.custom.domain/osm/{z}/{x}/{y}.png` by directly editing the file leaflet-maps.js and then deploying that file to the server.

If you just rewrote it so the tile url could be set from PHP via a filter (maybe via wp_localize_script? I'm not sure) this could be made update-proof easily.

**Comment by kaskad88** [comment]
In JetEngine v3.2.4 will added 2 JS filters `jet-engine.maps-listings.leaflet.tileURL` and `jet-engine.maps-listings.leaflet.tileOptions` for the Leaflet Map https://tppr.me/W19OE

Example of using these filters:

```
add_action( 'wp_footer', function () {

	$script = "
		window.JetPlugins.hooks.addFilter(
			'jet-engine.maps-listings.leaflet.tileURL',
			'JetEngine.leaflet.tileURL',
			function( tileURL ) {
				return 'https://my.custom.domain/osm/{z}/{x}/{y}.png';
			}
		);
	
		window.JetPlugins.hooks.addFilter(
			'jet-engine.maps-listings.leaflet.tileOptions',
			'JetEngine.leaflet.tileOptions',
			function( tileOptions ) {
				tileOptions.attribution = 'TEST';
				return tileOptions;
			}
		);
	";

	wp_add_inline_script( 'jet-maps-listings', $script, 'after' );
} );
```

**Comment by clmnsm** [comment]
Thanks, that sounds like a great solution.

**Comment by Floydtm** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by Gio76** [comment]
After updating to Version 3.2.4, Leaflet maps are not working in the backend when entering a new CPT. The map is just showing blank and you are not able to drop any pins. Reverted back to Version 3.2.3.2 until the map is fixed.

**Comment by kaskad88** [comment]
@Gio76 Thanks for your report! Fix well be in the next version.
