### ISSUE TITLE
JetBooking PDF Generator

### ISSUE THREAD

**Issue by SulovBD** [CrocoBlock/suggestions#6963]
We use JetBooking to create a booking website including Event tickets, Bus tickets, Hotel Booking, Tour Bookings, etc.

Most of the booking websites send e-tickets after purchase and booking confirmation PDFs.

We can't generate such things using Crocoblock plugins. Your JetBooking plugin is incredible but I believe many of us need this feature as well.

Please add this feature as early as possible

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1295, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
