### ISSUE TITLE
[Bricks] [Jet Engine] Dynamic Terms widget for Bricks

### ISSUE THREAD

**Issue by Allespat** [CrocoBlock/suggestions#6964]
In Elementor we can use Dynamic Terms widget to display custom taxonomy contents (ID, name, descriptions...).
I wish the same widget just in Bricks, as there is no way at the moment to grab those informations dynamically.

**Comment by RagnarLodbrok94** [comment]
Done

**Comment by Allespat** [comment]
Love you for that!
