### ISSUE TITLE
🐞BUG : jet woobuilder product Grid in elementor container

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6966]
Hi @UraraReika,

It seems that there is an important bug between the product grid widget and the Elementor container. **This bug can only be seen in mobile. I am experiencing this bug in android - chrome browser.** and I will explain the reproduction steps in the following. Please let me know if you are not successful in reproducing this bug so I can investigate further.

1- Make sure the container is active.
2- in a page, add a container in column direction.
4- Add two Product grid widgets in this container and display **only one product** in each (using the specific id query).
5- In order to better understand this bug, consider a border for both widgets in the grid item section (in product grid style tab).
6- Now in the container, set the **Gap between elements** to 0.
7- Now check the result in the frontend or reduce the width of your browser. The product grid widget will exit from its original state. Please watch the video below. (I apologize for the confusion of the website. Because I have changed it to LTR to make it easier for you to understand)

https://github.com/Crocoblock/suggestions/assets/77163248/7ead2f93-fee1-42b1-88b7-b297c5b1cca3

### A few notes about this bug

1- This bug only occurs in mobile.
2- We will encounter this bug only if there is 1 product in the Product grid widget. (For example, suppose we use a filter for which there is only one product). I accidentally encountered this bug in the same situation.
3- I tested this bug in the section and there is no problem and it only occurs in container.

thank you

**Comment by UraraReika** [comment]
Hello. Thanks for feedback.

We have tested this behaviour with our other widgets and with Elementor Pro Products widget as well as with some posts widgets. And this particular issue occurred every time if we following your steps. So in this situation I. can’t tell that this is JetWooBuilder Products Grid widget problem but it is the way how the container works and how it handle responsiveness.

**Comment by 79ho3ein** [comment]
thank you

**Comment by 79ho3ein** [comment]
Hi again @UraraReika,

I checked this bug in product widget and Loop Grid widget and there is no problem. I am only experiencing this bug in the product grid widget. thanks anyway.

**Comment by 79ho3ein** [comment]
Hi again @UraraReika,

I checked this bug in product widget and Loop Grid widget and there is no problem. I am only experiencing this bug in the product grid widget. **I set the width of the product grid widget to full width and the problem was solved. I hope it can be solved in the plugin core.**
