### ISSUE TITLE
[Jetsmart filters] - result count widget

### ISSUE THREAD

**Issue by horejsi-prsi** [CrocoBlock/suggestions#6969]
Hello,

would it be possible to add a widget for result count? 

I use only jetsmart filters to filter elementor loop and I miss this feature a lot. I only need to display the count of results from the query.

Now it`s only possible with Jetengine [https://crocoblock.com/knowledge-base/jetengine/query-results-count-dynamic-tag-for-wordpress/](url)

Thanks.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
I understand that this is important to you, but this is the functionality of the jetengine plugin
