### ISSUE TITLE
Add a way of formatting the date field for dynamic repeater

### ISSUE THREAD

**Issue by andrewbond23** [Crocoblock/suggestions#697]
I would like to request a way of changing the date format in the dynamic repeater? currently, there is no way i can find in order to be able to the date format.

**Comment by kaskad88** [comment]
Added for JetEngine 2.2.0.
Starting from version 2.2.0 you can use the following macros `<div>%date_meta|format_date%</div>` or `<div>%date_meta|format_date(F j, Y)%</div>` (with custom date format).

Thanks for your report.

**Comment by mwu8888** [comment]
I have JetEngine 2.2.6. Can you please give more details where to use macro "<div>%date_meta|format_date(F j, Y)%</div> " so I can change date format in the dynamic repeater?

Can you also direct me how to change the time format in the dynamic repeater?

Much appreciate it!!!

**Comment by kaskad88** [comment]
> I have JetEngine 2.2.6. Can you please give more details where to use macro "
> 
> %date_meta|format_date(F j, Y)%
> " so I can change date format in the dynamic repeater?
> Can you also direct me how to change the time format in the dynamic repeater?
> 
> Much appreciate it!!!

Example to use macros:
<img width="543" alt="Снимок экрана 2020-04-01 в 09 54 30" src="https://user-images.githubusercontent.com/14362877/78107979-21413e00-73ff-11ea-8981-5b6dbc50d6fd.png">

I use the following macros - %date_meta|format_date(F j, Y)%, where
 - date_key - name of the date field in repeater
 -  F j, Y - date format, which can be changed https://wordpress.org/support/article/formatting-date-and-time/

**Comment by rahaabasi** [comment]
Very Nice 
And if I want to change the Date to show Solar or Jalali calendar , Is that help ?

**Comment by enricgomez** [comment]
If you want to write your date format more literary and stylish:
`<span><i class="fas fa-calendar-alt"></i> %horari-cartellera|format_date(l d/m/y)% a les %horari-cartellera|format_date(H:i)%h</span>`

<img width="365" alt="imagen" src="https://user-images.githubusercontent.com/15028929/109032638-23228880-76c6-11eb-8de7-06aec1cfad25.png">

**Comment by pxmjc** [comment]
Hi, I have a checkbox inside a repeater, but I can't find the macros to show the results of the checkbox, it only shows me array, someone could help me please.

**Comment by kaskad88** [comment]
@pxmjc After JetEngine 2.9.1 release you can use the follow macros to display checkbox values in the Dynamic Repeater widget `%_repeater_key_|render_checkbox%`, where `_repeater_key_`- need replace to your repeater key
