### ISSUE TITLE
Jet Engine data store : new Store type > user IP

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6972]
Hi crocoblock team,

It would be great if we could set data store based on user ip. So in this case, each user with one IP can only like each post once. This is a very important option that is currently missing. Bricks builder [website](https://bricksbuilder.io/roadmap/) uses exactly this method to collect likes. Please keep this in mind as it is very important.

**Comment by Michaelgimii** [comment]
Hi @Floydtm, Have a question about this request?

**Comment by Floydtm** [comment]
@Michaelgimii Hi. I understand everything. I put this label for myself, because I need to talk about it with the developer

**Comment by MjHead** [comment]
In theory this is possible only by creating some additional DB table, to store the data in bounds with user IP or any other identifier. This is huge part of functionality so we added it to backlog of version 3.4.0, so it take some time until release

**Comment by Crocoblock** [comment]
was released in 3.4.0
