### ISSUE TITLE
JetWooBuilder - Sale badge does not work on variable products

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#698]
**Describe the bug**
When using the percentage term on the promotion label (% percentage_sale%), variable products that contain variation discounts have this image problem where they don't take the discount amount and / or don't fall back on it.

https://imgur.com/KZonwQv

**Comment by UraraReika** [comment]
Hi @marcofrasson! Considering the specifics of variable products where you can set sale price for every variable https://prnt.sc/q66y88, based on this widget display correct sale percentage https://prnt.sc/q66ymp, from biggest to lowest. As for this case https://prnt.sc/q670tu, probably you set wrong data in product.

**Comment by Floydtm** [comment]
merge this issues with #700

**Comment by marcofrasson** [comment]
Hello! When I use the sale badge for variable products, it shows two percentages, which is the smallest and largest value. I need to show only one value, it can be the biggest promotional, how can I filter it?

**Comment by marcofrasson** [comment]
I modified line 68 of the class-jet-woo-builder-macros.php file to show the largest discount and when the largest discount is 0, show the smallest. This way I can only get one discount shown on the sale badge.

If you don't enter this by default, you could have a show or not setting this way.

`$percentage_sale = ( ( 0 != $percentage_max ) ? $percentage_max . '&#37;' : $percentage_min . '&#37;' );
`

**Comment by Floydtm** [comment]
@marcofrasson, thanks for your report! We cannot realize this from the technical side.
