### ISSUE TITLE
Dynamic visibility - Show or hide gallery based on number of images in custom field

### ISSUE THREAD

**Issue by RodSuper** [CrocoBlock/suggestions#6986]
Hi, I would love to see an option to dynamically show or hide a gallery widget based on the number of images set in the custom field for that gallery.

So for example: Show the gallery widget only if there are 5 or more images added to the custom field.

My use case: Use different gallery layouts depending on the amount of images.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
