### ISSUE TITLE
Show apply button enable/disable option is not needed in radio filter widget

### ISSUE THREAD

**Issue by alithedvlpr** [CrocoBlock/suggestions#6992]
In your radio filter widget, when I select "apply type" "page reload" then it doesn't work until you enable the show apply button. If it has work with the button then there is no need to give the option to enable this.

**Comment by Floydtm** [comment]
@alithedvlpr hi, this is not a bug, because you have a choice to enable this button in the widget itself or use a separate Apply Button widget

**Comment by alithedvlpr** [comment]
If i do not enable this button, then filtration is not working.
