### ISSUE TITLE
Why did Crocoblock removed the Check Mark widget for JetFormBuilder?

### ISSUE THREAD

**Issue by Bentonabento** [CrocoBlock/suggestions#6998]
Hello, 

The "Check mark" widget was removed in the latest versions of JetEngine, we can't use an Elementor custom template for checkbox/radio anymore, this feature was really useful why did you removed it? 

Also, the new "Advanced Choices Field" widget does not support a dynamic list of choices from a custom Query, and Gutemberg is much less ergonomic to use compared to Elementor, can you please put this widget back? I am currently stuck and i fear that most of my forms currently using that widget won't work anymore...

Thank you

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
