### ISSUE TITLE
Cross-browser date and time picker for JetEngine custom fields

### ISSUE THREAD

**Issue by MjHead** [CrocoBlock/suggestions#7]
Problem:
Safari doesn't support default HTML5 datetime UI for input type date.

Solution:
Implement cross-browser control for date and time fields.

**Comment by Psmeg** [comment]
Yes, this is definitely one of those little UI/UX areas that is currently lacking in JetEngine. Manual input isn't really a smooth and streamlined way to add dates to any CPT.

**Comment by MjHead** [comment]
Added in JetEngine 1.4,0
