### ISSUE TITLE
JetWooBuilder - Sale Badge error 500

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#700]
**Describe the bug**
When we create a template for the "Archive Product" and use as an example a product that has a promotional price, inserting the sale badge widget, as soon as we switch to a product that does not have the promotional price, it gives error 500 when editing this template. I believe it is because the promotional label is null.

But it works correctly in "Single Product", which recognizes when a product has no promotional price.

Log WordPress:

```
Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site and notifies you with this automatic email.

In this case, WordPress has detected an error with its plugin: **JetWooBuilder For Elementor.**

First, visit your site (https://www.* * *.com/) and check for any visible issues. Then visit the page where the error was found (https://www.* * *.com/wp-admin/post.php?post=333&action=elementor) and check for any visible issues .

Contact the support team where you host your site for help investigating this issue.

If your site appears to be broken and you cannot access your control panel as usual, WordPress now has a special "restore mode". This allows you to securely log in to your dashboard and investigate further.

To keep your site secure, this link will expire in 1 day. Don't worry about it, however, a new link will be emailed to you if the error occurs again after the link expires.

When looking for help with this issue, you may be asked to provide some of the following information: WordPress version 5.3 Current theme: Digital - Child (version 1.0) Current plugin: JetWooBuilder For Elementor (version 1.4.2) PHP version 7.3.11

Error Details ================ An error of type E_ERROR was caused at line 61 of the file / home / bwtrw481 / public_html / site / wp-content / plugins / jet-woo- builder / includes / class-jet-woo-builder-macros.php. Error message: Uncaught Error: Calling a member function get_type () on null in / home / bwtrw481 / public_html / site / wp-content / plugins / jet-woo-builder / includes / class-jet-woo-builder-macros .php: 61 Stack trace: # 0 /home/bwtrw481/public_html/site/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php(174): Jet_Woo_Builder_Macros-> get_percentage_sale (NULL, false) # 1 [internal function]: Jet_Woo_Builder_Macros -> {closure} (Array) # 2 / home / bwtrw481 / public_html / site / wp-content / plugins / jet-woo-builder / includes / class-jet -woo-builder-macros.php (176): preg_replace_callback ('/% ([a-z _-] +) (\\ |…', Object (Closure), '% percentage_sal…') # 3 / home / bwtrw481 /public_html/site/wp-content/plugins/jet-woo-builder/includes/widgets/archive-product/jet-woo-builder-archive-sale-badge.php(210): Jet_Woo_Builder_Macros-> do_macros ('% percentage_sal … ') # 4 /home/bwtrw481/public_html/site/wp-content/plugins/jet-woo-builder/includes/widgets/archive-product/jet-woo-builder-archive-sale-badge.php(2 32): Elementor \ Jet_Woo_Builder_Archive_Sale_Ba
```

**Comment by UraraReika** [comment]
H1 @marcofrasson! Try to switch widgets render method https://prnt.sc/q6nmai.

**Comment by marcofrasson** [comment]
Dont work, in another site:

Fatal error: Uncaught Error: Call to a member function get_type() on null in /home/goflowdi/public_html/clientes/teste/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php:61 Stack trace: #0 /home/goflowdi/public_html/clientes/teste/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php(174): Jet_Woo_Builder_Macros->get_percentage_sale(NULL, false) #1 [internal function]: Jet_Woo_Builder_Macros->{closure}(Array) #2 /home/goflowdi/public_html/clientes/teste/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php(176): preg_replace_callback('/%([a-z_-]+)(\\|...', Object(Closure), '%percentage_sal...') #3 /home/goflowdi/public_html/clientes/teste/wp-content/plugins/jet-woo-builder/includes/widgets/archive-product/jet-woo-builder-archive-sale-badge.php(210): Jet_Woo_Builder_Macros->do_macros('%percentage_sal...') #4 /home/goflowdi/public_html/clientes/teste/wp-content/plugins/jet-woo-builder/includes/widgets/archive-product/jet-woo-builder-archi in /home/goflowdi/public_html/clientes/teste/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php on line 61

**Comment by marcofrasson** [comment]
https://prnt.sc/q6whoi

**Comment by Floydtm** [comment]
@marcofrasson, hi! We cannot reproduce this bug. Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help

**Comment by cargaladrillos** [comment]
2026 and the problem persists, fixed with this version thanks to Claude

<?php
/**
 * JetWooBuilder Macros Class
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

if ( ! class_exists( 'Jet_Woo_Builder_Macros' ) ) {

	/**
	 * Define Jet_Woo_Builder_Macros class
	 */
	class Jet_Woo_Builder_Macros {

		/**
		 * Return available macros list
		 *
		 * @return mixed|void
		 */
		public function get_all() {
			return apply_filters( 'jet-woo-builder/macros/macros-list', array(
				'percentage_sale' => array( $this, 'get_percentage_sale' ),
				'numeric_sale'    => array( $this, 'get_numeric_sale' ),
			) );
		}

		/**
		 * Return verbose macros list
		 *
		 * @return string
		 */
		public function verbose_macros_list() {

			$macros = $this->get_all();
			$result = '';
			$sep    = '';

			foreach ( $macros as $key => $data ) {
				$result .= $sep . '%' . $key . '%';
				$sep    = ', ';
			}

			return $result;

		}

		/**
		 * Get percentage sale.
		 *
		 * Returns percentage sale for current product.
		 *
		 * @since 1.4.0
		 * @since 2.1.8 Refactored. Removed unused parameter.
		 * @since 2.1.13 Better RTL support.
		 *
		 * @return string
		 */
		public function get_percentage_sale() {

			global $product;

			if ( ! is_a( $product, 'WC_Product' ) ) {
				return null;
			}

			$percentage_sale = '';

			if ( 'variable' === $product->get_type() ) {
				$prices = $this->sort_variation_price( $product );

				if ( $prices['regular_min'] > 0 && $prices['regular_max'] > 0 ) {
					$percentage_min  = round( 100 - ( $prices['sale_min'] / $prices['regular_min'] * 100 ) );
					$percentage_max  = round( 100 - ( $prices['sale_max'] / $prices['regular_max'] * 100 ) );
					$percentage_sale = ( ( $percentage_min != $percentage_max ) ? ( $percentage_min . '-' . $percentage_max ) : $percentage_max );
				}
			} else {
				$regular_price = (float) $product->get_regular_price();
				$sale_price    = (float) $product->get_price();

				if ( $sale_price > 0 && $regular_price > 0 ) {
					$percentage_sale = round( 100 - ( $sale_price / $regular_price * 100 ) );
				}
			}

			return is_rtl() ? '&#37;' . $percentage_sale : $percentage_sale . '&#37;';

		}

		/**
		 * Get numeric sale.
		 *
		 * Can be used for sale price budge. Returns numeric sale for current product.
		 *
		 * @since 1.4.0
		 * @since 2.1.13 Better RTL support.
		 *
		 * @return string
		 */
		public function get_numeric_sale() {

			global $product;

			if ( ! is_a( $product, 'WC_Product' ) ) {
				return null;
			}

			$numeric_sale = '';
			$symbol       = get_woocommerce_currency_symbol();

			if ( 'variable' === $product->get_type() ) {
				$prices = $this->sort_variation_price( $product );

				if ( $prices['regular_min'] > 0 && $prices['regular_max'] > 0 ) {
					$numeric_min  = $prices['regular_min'] - $prices['sale_min'];
					$numeric_max  = $prices['regular_max'] - $prices['sale_max'];
					$numeric_sale = ( ( $numeric_min != $numeric_max ) ? ( $numeric_min . '-' . $numeric_max ) : $numeric_max );
				}
			} else {
				$numeric_sale = floatval( $product->get_regular_price() ) - floatval( $product->get_price() );
			}

			return is_rtl() ? $symbol . $numeric_sale : $numeric_sale . $symbol;

		}

		/**
		 * Sort prices for variable product
		 *
		 * @param $product
		 *
		 * @return array
		 */
		public function sort_variation_price( $product ) {

			$prices = $product->get_variation_prices( true );

			foreach ( $prices['price'] as $product_id => $price ) {
				$product_obj = wc_get_product( $product_id );

				if ( ! $product_obj ) {
					unset( $prices['price'][ $product_id ] );
					unset( $prices['regular_price'][ $product_id ] );
					continue;
				}

				$prices['price'][ $product_id ] = wc_get_price_to_display( $product_obj );
			}

			if ( empty( $prices['price'] ) || empty( $prices['regular_price'] ) ) {
				return array(
					'sale_min'    => 0,
					'sale_max'    => 0,
					'regular_min' => 0,
					'regular_max' => 0,
				);
			}

			asort( $prices['price'] );
			asort( $prices['regular_price'] );

			return array(
				'sale_min'    => current( $prices['price'] ),
				'sale_max'    => end( $prices['price'] ),
				'regular_min' => current( $prices['regular_price'] ),
				'regular_max' => end( $prices['regular_price'] ),
			);

		}

		/**
		 * Do macros inside string
		 *
		 * @param      $string
		 * @param null $field_value
		 *
		 * @return string|string[]|null
		 */
		public function do_macros( $string = '', $field_value = null ) {

			$macros = $this->get_all();

			return preg_replace_callback(
				'/%([a-z_-]+)(\|[a-z0-9_-]+)?%/',
				function ( $matches ) use ( $macros, $field_value ) {

					$found = $matches[1];

					if ( ! isset( $macros[ $found ] ) ) {
						return $matches[0];
					}

					$cb = $macros[ $found ];

					if ( ! is_callable( $cb ) ) {
						return $matches[0];
					}

					$args = isset( $matches[2] ) ? ltrim( $matches[2], '|' ) : false;

					return call_user_func( $cb, $field_value, $args );

				}, $string
			);

		}

	}

}
