### ISSUE TITLE
bug in jet engine optimize DOM

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#7002]
Hi,

After activating the optimize DOM, the dynamic field widget was broken in Elementor, and after checking the widget, I realized that many of the style settings of this widget were removed.

**Comment by SolunaCG** [comment]
I thought this was already a known thing. 

In the announcement thread of JetEngine v3.2.0 Beta it says 

> After you enable Optimize DOM, it will be necessary to restyle the Dynamic Field and Dynamic Link widgets everywhere you use them.

Or do I misunderstand you here?

**Comment by Michaelgimii** [comment]
It seems you are right. Thank you @SolunaCG.
