### ISSUE TITLE
JetWoo: Quantity button redirects to product page

### ISSUE THREAD

**Issue by sonnesworld** [CrocoBlock/suggestions#7006]
**Describe the bug**
When I add a quantity button on an archive page and I change the quantity I get redirected to the single product page just by clicking on “+” or “-“. 

**To Reproduce**
1. Go to https://staging.fierz-gmbh.ch/produkt-kategorie/dan-dryer-produkte/wickeltische/, scroll to the last product with a price
2. Click on '1' on the left side of the cart for changing quantities
3. You get redirected to the product page 

**Expected behavior**
The quantity should change, but I won't get redirected to an other page. 

**Screenshots**
Please can you check: https://nimb.ws/uOHyJY

**Comment by Floydtm** [comment]
@sonnesworld You have probably created your listing using the listing grid widget. If you have enabled the "make listing clickable" option there, it will behave as in the video. Check this option, for your case, you need to turn it off https://tppr.me/VPaV4

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.

Please [contact](https://support.crocoblock.com/support/home/ ) our support team for additional help.

Thank you!
