### ISSUE TITLE
Archive Product Loop Hook's

### ISSUE THREAD

**Issue by carlospinhod** [CrocoBlock/suggestions#7007]
**Describe the bug**
Cant use hooks with Products Loop as archive
the hook works in the Elementor Editor, but wont display on live website.

**To Reproduce**
1. Add Elementor widget 'Products Loop'
2. in JetWoo Archive Template add the hook widget and select 'Before Item Title'
3. to child theme add this code to functions.php

function woocommerce_show_product_loop_sale_flash()
{
    global $product;

    if (current_user_can('edit_pages')) {
        // Check if the product is on sale
        if ($product->is_on_sale()) {
            $product_categories = get_the_terms(get_the_ID(), 'product_cat');

            if ($product_categories && !is_wp_error($product_categories)) {
                echo '<div class="product-categories">';
                foreach ($product_categories as $category) {
                    echo '<a href="' . esc_url(get_term_link($category)) . '">' . esc_html($category->name) . '</a>';
                }
                echo '</div>';
            }
        }
    }

}
add_action( 'woocommerce_before_shop_loop_item_title', 'woocommerce_show_product_loop_sale_flash', 10 );

**Expected behavior**
This should display the content i return from the hook.

**Additional context**

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Widget in archive product template - https://tppr.me/sTyyA 
Child theme code - https://tppr.me/joM85
Result - https://tppr.me/R2JWl

Thank you!
