### ISSUE TITLE
🐞 jet woobuilder 2.1.6 bugs

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7010]
Hi @UraraReika,

In the new version of Jet woobuilder, there are some bugs that I will describe below. **Please note that I am facing these bugs in RTL and have not tested LTR.** Please let me know if you are unsuccessful in reproducing any so I can investigate further.

1- The rendering of the product grid widget has become very annoying. For example, the number of products per slide is 3, but when the page is reloaded, the number of products per slide becomes 1 and then returns to 3 after about two seconds.

2- After the update, the default height of the Single Sale Badge widget has increased, which is not controllable at all. Even if we set the padding to 0 or use a new custom control.

**before update**

![b](https://github.com/Crocoblock/suggestions/assets/77163248/e0dc5abe-ad5d-4c7b-bb1f-fd4b0a8d1649)

**after update**

![a](https://github.com/Crocoblock/suggestions/assets/77163248/64126cb7-a771-445e-85b9-ae70657daf33)

3- On RTL, the Single Sale Badge widget is out of the box.

![Screenshot](https://github.com/Crocoblock/suggestions/assets/77163248/310d1c85-b878-424b-98da-09ccf5faaf5c)

On the other hand, if we move the Single Sale Badge to the left, it will not completely stick to the box widget.

![Screenshot (1)](https://github.com/Crocoblock/suggestions/assets/77163248/5d42fca5-5bcf-47ef-b091-dcaf979573bf)

4- After clicking the add to cart button, the spinner will be placed on the text.

![4](https://github.com/Crocoblock/suggestions/assets/77163248/9b67e36e-4a98-4884-a16d-eda52a8d1395)

5- If we have the custom quantity selector plugin, after selecting the variable on the product page, the quantity button is broken.

https://github.com/Crocoblock/suggestions/assets/77163248/f68a6460-fc57-4b97-8800-d79005ad2a86

6- On the cart page, if we use a custom icon (both svg and Elementor icon library) for the remove product button, it is completely broken in the editor. But there is no problem in the front end. Especially the svg icon has a serious problem.

![t](https://github.com/Crocoblock/suggestions/assets/77163248/092a0ae6-5023-4851-9931-b47b0c8f257a)

7- If the custom quantity selector plugin is active, whether in simple products or in variable products, if the Stock management option is disabled, it causes the width of the custom quantity selector to go out of the normal state (increase). For example, in the image below, the Stock management option is disabled in the bottom product.

![7](https://github.com/Crocoblock/suggestions/assets/77163248/e0c21189-a2e4-465d-8192-0b166e162f48)

8- There is still a problem with [this bug](https://github.com/Crocoblock/suggestions/issues/6949). Because the remaining div creates 10px spacing.

![5](https://github.com/Crocoblock/suggestions/assets/77163248/3efe40f8-aa09-4216-b0fb-256c4cc5bf85)

Finally, I have a question. Do we need to download and install this plugin to fix the custom quantity selector plugin bug, or will the changes be applied with the jet woobuilder plugin update?

thank you

**Comment by UraraReika** [comment]
Everything is fixed. In case of point 7 you will need to download new version of quantity selector plugin.

**Comment by 79ho3ein** [comment]
thank you @UraraReika

**Comment by 79ho3ein** [comment]
@UraraReika 

>Everything is fixed. In case of point 7 you will need to download new version of quantity selector plugin.

The version of this plugin is still 1.0.0. Has it not been uploaded yet?

**Comment by UraraReika** [comment]
> @UraraReika
> 
> > Everything is fixed. In case of point 7 you will need to download new version of quantity selector plugin.
> 
> The version of this plugin is still 1.0.0. Has it not been uploaded yet?

it been updated, too small changes to up version.

**Comment by 79ho3ein** [comment]
thank you

**Comment by 79ho3ein** [comment]
excuse me @UraraReika, Are these things fixed in version 2.1.6.1?
After updating to 2.1.6.1 version, the bugs are still there and of course one more bug has been added. In the Editor > Cart page, the Update Cart Automatically option is enabled, but there is still an update cart button. On the other hand, there is too much space between the field and the button to apply the coupon. (RTL)

![Screenshot](https://github.com/Crocoblock/suggestions/assets/77163248/8cc6f65d-afac-4f2a-ad78-3c1442ab1964)

**Comment by UraraReika** [comment]
> excuse me @UraraReika, Are these things fixed in version 2.1.6.1? After updating to 2.1.6.1 version, the bugs are still there and of course one more bug has been added. In the Editor > Cart page, the Update Cart Automatically option is enabled, but there is still an update cart button. On the other hand, there is too much space between the field and the button to apply the coupon. (RTL)
> 
> ![Screenshot](https://user-images.githubusercontent.com/77163248/260219607-8cc6f65d-afac-4f2a-ad78-3c1442ab1964.png)

2.1.6.1 version was quick release to fix some Elementor editor issues. Everything from this issue will be fixed in 2.1.7 version.

**Comment by 79ho3ein** [comment]
Great, thank you

**Comment by 79ho3ein** [comment]
Hi @UraraReika, 

In version 2.1.7 a few simple problems still exist.

1- Item 7 still exists. I even downloaded and installed the Custom quantity selector plugin again.


2- Problem 4 is solved, but two new problems have arisen.

A : After clicking the button, the distance between the text and the spinner icon is too large.

![A](https://github.com/Crocoblock/suggestions/assets/77163248/d5ba21ad-c9de-4bcf-a75b-bb6697bab1a8)

B : After the product is added to the cart, the tick icon is completely attached to the text.

![B](https://github.com/Crocoblock/suggestions/assets/77163248/19b1a024-2774-4cfe-8086-277ff1c51099)


3- If we use the Product grid widget on the single product page, the color of the previous price is not as expected. For example, in the screenshot below, the color of the price is completely red. But the color of the price is much lighter than that.

![C](https://github.com/Crocoblock/suggestions/assets/77163248/e6102371-7cb5-4ea8-ac5f-39ab66f47df6)


As a last small request, please add a **Margin control** to the Quantity Selector option to create space between the Quantity Selector and the Add to Cart button. 

### If I need to report these in a new issue, please let me know

thanks

**Comment by UraraReika** [comment]
1 - We have double checked your issue and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

2a - Unfortunately this distance can be handle only with custom css. By default it will be like that sticking to the side of the button depending on site direction.

2b - We've tasted this issue and everything seems to be okey - https://tppr.me/Clrmf.

3 - This is how new versions of WooCommerce handle this style, but fixed when use JetWooBuilder widgets.

**Comment by 79ho3ein** [comment]
Hi @UraraReika,

Did you check these in RTL?  Anyway, I will investigate further to find out exactly what the problem is.

**Comment by 79ho3ein** [comment]
Hi again @UraraReika,

Referring to [these few things](https://github.com/Crocoblock/suggestions/issues/7010#issuecomment-1708201050) :

1- I tested this again. This bug occurs if the product inventory is 0 and the product type is of simple.

2a - Actually the problem here is that after clicking the add to cart button, the text moves slightly to the right (in RTL). This is what has come in the new version. Please watch the video below. Immediately after clicking the button, the "Add to Cart" text will move slightly to the left.

https://github.com/Crocoblock/suggestions/assets/77163248/25232f40-d523-43d6-a2da-60e54d6876ac

2b - Your screenshot won't open. But this one works well in LTR. But in RTL, after the product is added to the cart, the tick icon is completely attached to the text.

![265994500-19b1a024-2774-4cfe-8086-277ff1c51099](https://github.com/Crocoblock/suggestions/assets/77163248/d47d5dd3-d819-408c-ae8f-9a868bd170ce)

>3 - This is how new versions of WooCommerce handle this style, but fixed when use JetWooBuilder widgets.

You mean if we use the product grid widget there shouldn't be any problem? I use the product grid widget exactly. But the color of the previous price is out of control. Of course, as I mentioned, this problem only occurs in single product.

thanks.

**Comment by UraraReika** [comment]
1 - Please one more time describe this bug in more details. If the product inventory is 0 then this product is out of stock. I try recreate this bug with old and new description but have no success. Everything works correctly with latest versions of the plugins. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

2b - LTR - https://tppr.me/t05Ad, RTL - https://tppr.me/3oLwg. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

3 - Yes in the next release of our plugin everything should be fine.

Thank you!

**Comment by 79ho3ein** [comment]
> 1 - Please one more time describe this bug in more details.

You are right. What I said about the balance of 0 was not logical. Because it is not possible. 

But about the details, the problem is that if the product is simple, and we don't enable [this option](https://prnt.sc/E9F--WxKxhr2) in WooCommerce product settings, the input width of this product will be bigger than other products.

![Screenshot](https://github.com/Crocoblock/suggestions/assets/77163248/f6e9a9b0-137c-49ad-aa6a-845fff91e5b1)

**Comment by UraraReika** [comment]
First product settings - https://tppr.me/RjOhb
Second - https://tppr.me/O3v5Z
Result - https://tppr.me/xyVEn

**Comment by 79ho3ein** [comment]
Thanks for the screenshots. According to your second screenshot, which is almost without style, I understand what the problem is.

1- On the Content tab of the Cart Table widget > Quantity Selector , set Buttons Width to 30.
2- On the Style tab > Quantity Input , set the Width to 60px.
3- In the same section, set the padding to 10 from the top and bottom : https://prnt.sc/HbczZNKianGb

Now if you see the result, the width of Quantity Input in that product (your first screenshot) will be more than the others. Actually, the problem is from step 3 (padding). But it is strange what it has to do with **product management** in product settings.
