### ISSUE TITLE
JetWooBuilder Update Errors 2.1.6

### ISSUE THREAD

**Issue by AguilArtDesign** [CrocoBlock/suggestions#7013]
Errors when updating to the new version 2.1.6

- Widget "Add to Cart" does not respond to the indicated width, it adjusts itself and the modifications do not work
- Widget "Archive Thumbnail" effects stopped working

https://github.com/Crocoblock/suggestions/assets/141839637/bca5c4f3-7c06-4b91-a239-c8b285dc051b

**Comment by UraraReika** [comment]
> Widget "Add to Cart" does not respond to the indicated width, it adjusts itself and the modifications do not work

Fixed.

> Widget "Archive Thumbnail" effects stopped working

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Fixes will be available in the next release.

Thank you!

**Comment by tealou** [comment]
Can replicate. Same problem here. Had to turn off the Thumbnail effects.
