### ISSUE TITLE
JetTabs: Custom ids/anchor links for tabs

### ISSUE THREAD

**Issue by RFDM-Cathleen** [Crocoblock/suggestions#702]
I know that there are built-in anchor links for the tabs and they work fine. However, having a URL with "jet-tabs-control-2288" is very unsightly and not very professional. Can you please modify the plugin to either allow for a custom id to be assigned, or to please use the tab label for the id? We have come up with a line that will do this, but our modifications will be overridden in the next plugin update. Here is what we have to create the content-specific tab Ids.

In plugins > jet-tabs > includes > addons > jet-tabs-widget.php
Replace line 1311:  'id' => 'jet-tabs-control-' . $id_int . $tab_count,
with:
'id'            => str_replace(" ", "-", strtolower( $item['item_label'] ) ) . '-tab',

**Comment by kaskad88** [comment]
For your needs, in the next release of the plugin, the `Control CSS ID` option will be added http://prntscr.com/rj3jkj
