### ISSUE TITLE
[jetBooking] Enable custom fields in ical integration template

### ISSUE THREAD

**Issue by nickj-git** [CrocoBlock/suggestions#7020]
While the ical integration has good potential, the inability to add custom fields to the appointments using the template limits its use.

I've got a hall hire scenario where I add the details of the booking such as contact name, organisation, email and phone which cannot be added using a macro yet in the template. The standard fields can just show the title and status which aren't that relevant for the scenario where I hire out one space but can't see in my calendar (using ical) who the booking is for and other details of the booking.

**Comment by Crocoblock** [comment]
was released in 3.2.0
