### ISSUE TITLE
JetWooBuilder - Search template did not assign

### ISSUE THREAD

**Issue by Akosr86** [CrocoBlock/suggestions#7021]
I created a Search results page template for my woocommerce products in crocoblock/woo page builder using the Archive item template, and assign that in the woocommerce/settings/JetWooBuilder/Archive products/Search page template (enable custom archive product), but the product search results did not appear if I use the jet search widget on the frontend. It still uses the default elementor/woocommerce search results template instead of the crocoblock one.

The rest of my JetWooBuilder templates seems to work fine, But I can't assign this one.

I am on Elementor V 3.15.1
Elementor Pro V 3.15
JetWooBuilder for Elementor V 2.1.5
WooCommerce 7.9.0
Wordpress 6.2.2

**Comment by UraraReika** [comment]
It seems that you understand this option incorrectly and used it wrong. It helps if you attach some screenshots to the issue so we can help you better.

Although you cat [contact](https://support.crocoblock.com/support/home/ ) our support team, so we can help you directly  ob your site.

Thank you!

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.
