### ISSUE TITLE
Jet Booking, Availability Calender

### ISSUE THREAD

**Issue by jannelundin** [CrocoBlock/suggestions#7022]
I was wondering if it would be possible to make the availability calender
with the checkin and checkout days half marked like the attached image
<img width="434" alt="Skärmavbild 2023-08-14 kl  09 57 51" src="https://github.com/Crocoblock/suggestions/assets/65285087/874e2c0f-a243-4439-854c-178aee2c4f36">
Kind regards Janne L

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5170, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
