### ISSUE TITLE
JetWooBuilder - Issues displaying Single add to cart properly after update

### ISSUE THREAD

**Issue by shahabmohi** [CrocoBlock/suggestions#7025]
**Describe the bug**
After updating the JetWooBuilder plugin to any version beyond 2.1.5, the composition of 'single add to cart' items gets distorted and does not respond to any changes in CSS parameters.

**To Reproduce**
1- Have a single product page via Woo page builder.
2- Upgrade the JetWooBuilder plug-in.
3- Voila!

**Expected behavior**
I expected the CSS to remain the same and not get distorted.

**Screenshots**
![Screenshot 2023-08-15 180421](https://github.com/Crocoblock/suggestions/assets/66645514/0f3f7673-8ff0-4e32-b956-c262efc3b1cb)
![Screenshot 2023-08-15 174637](https://github.com/Crocoblock/suggestions/assets/66645514/db8496ae-fb10-44a6-94a5-5cd323ce5a04)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 115.0.5790.171 

**Smartphone (please complete the following information):**
 - Device: IPhone 14
 - OS: 16.6
 - Browser Chrome
 - Version

**Comment by Michaelgimii** [comment]
Hi @UraraReika, Is there a time for the release of a new version (fixing bugs)?
