### ISSUE TITLE
JetBooking - Unable to book using the backend, if there's more units.

### ISSUE THREAD

**Issue by FutterupTiger** [CrocoBlock/suggestions#7026]
**Bug**
When we try and book a date, using the backend JetBooking, we're unable to make more bookings on a given date even if there is more than one unit. It will book the first unit, but not create bookings after that on the same date. 

**To Reproduce**
1. Go to 'admin -> JetBooking -> Add New'
2. Create new booking
3. Press Add New
4. Create the same booking on the same date again.
5. See error. 

**Expected behavior**
A new booking with another Unit ID

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 115.0.5790.171

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
