### ISSUE TITLE
jet woobuilder category grid > exclude by name

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#7028]
The new **exclude by name** option for the category grid widget would be great. Currently, there is only the possibility to exclude using ID, which is a bit difficult.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
