### ISSUE TITLE
[jetBooking] Bookings not showing in admin panel after updating to V2.8.0

### ISSUE THREAD

**Issue by avdstelt** [CrocoBlock/suggestions#7029]
After updating to version 2.8.0 my bookings are not showing up in the admin panel? 

I also did the database update.

See attached images.

Greetings Arjan

![bookings](https://github.com/Crocoblock/suggestions/assets/851114/a1089f3c-381a-44fa-8258-948e4089d98e)
![console_log](https://github.com/Crocoblock/suggestions/assets/851114/808b0928-8141-49d6-b3c6-02cf7b70a113)

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by avdstelt** [comment]
Ok will do that thank you.
