### ISSUE TITLE
JetElements Posts & Pages in a Popup

### ISSUE THREAD

**Issue by schndr-cdn** [Crocoblock/suggestions#703]
Hi guys,
I would like to request a feature about Popup function. I realized there is no Plugin which can open a created page or post with in a Pop-up. If I give an example: I have a Post Carousel from JetElements on my start page and links are opening like always on the new-page. If this Post would open in a Pop-up I think that would be first in the Market. I saw in Elementor's Github so many people search for this function.

Greetings

**Comment by Floydtm** [comment]
@schndr-cdn, Hi! Your request can be implemented using the [jetengine](https://crocoblock.com/plugins/jetengine/) and [jetpopup](https://crocoblock.com/plugins/jetpopup/) plugins. 
[Uploading example.zip…]()
