### ISSUE TITLE
Is it Possible to have load more button/infinite scroll instead of pagination for the shop page made by products loop widget?

### ISSUE THREAD

**Issue by sabbirahasanhabib** [CrocoBlock/suggestions#7031]
Hello,
@UraraReika 
How's everything going? I have read an issue about load more/infinite scroll for the products grid widget..but i am using **products loop** widget for showing my products..is it possible to have the same feature in products loop widget? 

Any help would be appreciable?

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But you can use solution presented in JetSmartFilters  - https://crocoblock.com/knowledge-base/jetsmartfilters/pagination-overview/. If you use pagination widget you can find load more option there.

Thank you for your understanding.

**Comment by sabbirahasanhabib** [comment]
Thanks ..The pagination widget will solve my issue

**Comment by sabbirahasanhabib** [comment]
Hi @UraraReika,

I have tried the "pagination" widget to show load more button for products but it only shows next 4 products and then it just disappeared... Is there any way to use it in a continuous process...???

Actually Load more option is available for product grid/product list but not for product loops...its really frustrating to not have this important functionality...

There is another way to show this with listing grid but it involves jetengine...which is a very heavy plugin..We the people, who are using only jetwoobuilder , kind of stucked in this situation...

Hope u understand

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
