### ISSUE TITLE
Some bugs in jet product gallery plugin > Gallery Slider widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7032]
Hi,

I installed and used the Jet Product Gallery plugin for the first time. After checking, I noticed some flaws in the Gallery Slider widget, which I will explain below. Please note that I have reviewed these items in RTL.

1- If we disable the Navigation option in the slider settings for the featured image, there are still customization options for it in the Style tab : https://prnt.sc/jcUoyvuZ3NcY

2- If the number of thumbnails is small, the image will not be placed exactly in the center, but on the right side of its position. If the number of thumbnails is small, the image will not be placed exactly in the center, but on the right side of its position. https://prnt.sc/ak4iXpklEvnM

3- If we disable the Prev/Next Arrows in the featured image, it is almost impossible to navigate through it using swiping on mobile.

4- If we enable Dynamic Bullets for pagination, the pagination does not render properly when the page loads. (This bug previously existed in the product grid widget of the Jet Woobuilder plugin and was fixed)

5- The speed of change in Dynamic Bullets is very fast and not visible at all. This bug also existed before in the product grid widget and was fixed. I hope I have conveyed my meaning well.

6- Like the fourth one, the thumbnail rendering seems to lag after the page is loaded.

thank you

**Comment by UraraReika** [comment]
3 - If you feel discomfort with mobile swiping try to change this option.

**Comment by 79ho3ein** [comment]
What should I change to? You mean I don't disable Prev/Next Arrows?

**Comment by UraraReika** [comment]
> What should I change to? You mean I don't disable Prev/Next Arrows?

Sorry for not attaching screenshot, this option - https://tppr.me/y9Q6.
