### ISSUE TITLE
JetEngine Query is not being updated 

### ISSUE THREAD

**Issue by grazieleoliveira** [CrocoBlock/suggestions#7034]
**Describe the bug**
I've been trying to build the following flow using Crocoblock Jetengine:
- User sends a form with information
- Then user goes to next page and a chart is shown. The chart shows a comparison of all the data sent by the users. The chart must be updated right after the user sends the form

In order to achieve this, I have created REST API endpoint for CCT. When the user sends the form, it updates the CCT correctly.
To verify if the endpoint was also being updated correctly, I made a request using the browser and verified that the new data was there, meaning the GET to my endpoint is fine.

After that, I created a Chart using Chart builder to display the data, and also created a Query using Query Builder to get the data and connect it to the chart.  The problem is: the query doesn't give me the updated data from REST API.

**Expected behavior**
I believe the expected behavior was for the query to dynamically update this data, which is not what is happening.

**Video**
This is a video showing the weird behavior that occurs. 
1. Form sends the data
2. Data is updated on CCT and also on REST API endpoint 
3. The query in query builder does not get updated
4. When I click on "add query" button, the query suddenly updates. 

https://github.com/Crocoblock/suggestions/assets/9582465/5adb7a97-cca1-4be8-9118-5c9850497b99

I would be very grateful if you guys could help me with this

**Comment by jileon** [comment]
I am having the same issue with querying a CCT both using a CCT query and SQL query in query builder. The query will not update unless I add a new query, or change something about what I'm querying, then change it back in order to refresh. Would appreciate any help on this issue.

**Comment by kaskad88** [comment]
In JetEngine v3.3.0 added an ability to disable query caching https://tppr.me/qf3R1
