### ISSUE TITLE
Issues with product quantity input and add to cart icon by product grid widget

### ISSUE THREAD

**Issue by sabbirahasanhabib** [CrocoBlock/suggestions#7035]
Hi,

I am facing an awkward issue with the product grid widget..i used product grid widget in the single product page made by jetwwobuilder to show some custom products there with carousel functionality. However, the product input field doesn't show in the frontend but it is appearing in the backend..again if i use the product grid widget in my homepage it shows the product input but not the add to cart icon there? I am stucked about this strange behaviour. I am using Hello elementor theme and all the croco plugins are up to date...Can you please check the product quantity and add to cart icon with product grid widget in the following pages i mentioned...Any help would be appreciable

**Comment by sabbirahasanhabib** [comment]
@UraraReika 
Here are some screenshots:
This is a single product template where i used product grid widget....

This image is from the the backend editor

![Screenshot_18](https://github.com/Crocoblock/suggestions/assets/137334915/20acdf65-1ef2-4e4b-8eee-6f952a850af3)

This image from the frontend ( All Plugin based and cloudflare based Caches are cleared )

![Screenshot_19](https://github.com/Crocoblock/suggestions/assets/137334915/be87b406-db69-4989-a1b6-dfd32b663560)

Even I tried disabling all other plugins  and switch to twenty twenty three theme except turned on woocommerce, jetwoobuilder, custom add to cart for jetwoobuilder and custom quantity selector for jetwoobuilder plugin...but it doesn't solve the issue

**Comment by sabbirahasanhabib** [comment]
Hi, @UraraReika 
I can see u have self assigned this but i don't know what it actually means...is the issue only happening in my end or is it a bug? plz let me know if this is going to be solved otherwise i have to move with different solution..Thanks

**Comment by UraraReika** [comment]
> Hi, @UraraReika I can see u have self assigned this but i don't know what it actually means...is the issue only happening in my end or is it a bug? plz let me know if this is going to be solved otherwise i have to move with different solution..Thanks

the problem is in the queue

**Comment by sabbirahasanhabib** [comment]
Thanks a lot for the reply...i will wait... Thanks again

**Comment by UraraReika** [comment]
Hello and sorry for delay!

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!

**Comment by sabbirahasanhabib** [comment]
Hello @UraraReika 
the issue in the homepage resolved by the updated custom add to cart icon plugin that u have made an week ago..i don't know what u have tweaked but it solved the issue in the homepage...but it still persists in the single product page that i have mentioned earlier in the post.. the quantity input and quantity selector is not showing as i have described earlier...i believe there is still a bug or something in the custom quantity selector plugin...problem with only by the additional dev plugins(quantity selector) and the core croco plugin is working good..

one solution i have found that>> i made a listing by jetengine with archive product templates and when i use that by listing grid widget in the single product page along with the product grid widget, the problem resolves and the quatity input and selector shows there in product grid widget. i think somethings triggered with the listing grid...

**Comment by UraraReika** [comment]
> Hello @UraraReika the issue in the homepage resolved by the updated custom add to cart icon plugin that u have made an week ago..i don't know what u have tweaked but it solved the issue in the homepage...but it still persists in the single product page that i have mentioned earlier in the post.. the quantity input and quantity selector is not showing as i have described earlier...i believe there is still a bug or something in the custom quantity selector plugin...problem with only by the additional dev plugins(quantity selector) and the core croco plugin is working good..
> 
> one solution i have found that>> i made a listing by jetengine with archive product templates and when i use that by listing grid widget in the single product page along with the product grid widget, the problem resolves and the quatity input and selector shows there in product grid widget. i think somethings triggered with the listing grid...

I've tried to reproduce  the issue with the help of your description and failed. Perhaps this is somehow related only to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
