### ISSUE TITLE
jet compare and wishlist compatibility with bricks builder.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#7036]
Hi crocoblock team,

We can easily add products to interest in bricks builder by using jet engine plugin. But there is no way to create product compare. It will be great if you make the jet compare and wishlist plugin compatible with bricks builder. I hope this is in your plans.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
