### ISSUE TITLE
Security Issue with Jet Smart Filters and Jet Table Builder - Potential IDOR Vulnerability

### ISSUE THREAD

**Issue by tapmag** [CrocoBlock/suggestions#7037]
Plugin Versions: Jet Smart Filters - 3.2.0 , Jet Table Builder 1.0.7

### Description:
I've identified a potential security vulnerability when using Jet Smart Filters in conjunction with Jet Table Builder. Specifically, there's a risk of exposing sensitive data through the /wp-admin/admin-ajax.php endpoint.

### Steps to Reproduce:

- Create a table showing CCT data using Jet Table Builder.
- Implement Jet Smart Filters to filter and sort the table data. Add Dynamic visibility to the table to be visible only to admins.
- Go to front end and use filters. Observe the AJAX request made to /wp-admin/admin-ajax.php.
- Copy the request and remove the cookie header.
- The endpoint exposes restricted data without authentication. Moreover, by modifying the table_id parameter in the request, it's possible to retrieve data from other tables.

### Expected Behavior:
Data should only be accessible to authorized and authenticated users. /wp-admin/admin-ajax.php. request should only return table data if custom visibility conditions are met.

### Actual Behavior
Restricted data is accessible without authentication. Modifying the table_id parameter can potentially expose more data and be a IDOR vulnerability

### Additional Context:

Tables tied to user-specific queries seem secure.
The issue arises predominantly with tables that are intended to display all data to privileged users (like admins). For example - a table that shows all form submissions on a site. The query to retrieve this data would not be tied to a particular user.

### Potential Solution:
A similar issue is observed with **Jet Popup** when using a popup to show full details of a cct item in a Jet Table. However , with Jet Popup if you set visibility conditions  sections within the popup , the AJAX request made to /wp-admin/admin-ajax.php. will not return the html sections unless custom visibility conditions are met.

If something similar can be done for Jet Table Builder , such that if there are custom visibility conditions on the table , when Jet Smart Filters reloads the table data , it honours the custom visibility conditions on the page.,

**Comment by MjHead** [comment]
We added an ability to include signature into the filters request:

<img width="971" alt="image" src="https://github.com/Crocoblock/suggestions/assets/4987981/d7c90f29-91d2-4efb-b456-89597fde7941">

When signature is enabled, for each provider on the page generated unique signature according to provider settings, this signature added to each request. On the backend, before processing filters, the same signature generated by provider settings form the request. If provider settings was changed before the request, generated signature will not match signature from the request. If signature doesn't match, there no results will be returned. So, when you using this option, if request settings was changed, for example table id like in initial issue, request won't be completed
