### ISSUE TITLE
JetBooking Conditional Days Additional Price

### ISSUE THREAD

**Issue by chunibyuu** [CrocoBlock/suggestions#7041]
Hello . 
I have a listings for rental . I want to set up the days rental for additional prices . 1-2 days is original price . For 3 days , add/deduct an additional price to the original price per day . For more than 3 days they will be redirected to request a quote page . 
Thanks !

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Right now you can use price rates to control price per day depending on how many days you want to book. Please clarify the part about redirection.

Thank you for your understanding.

**Comment by chunibyuu** [comment]
> Thanks for the feedback.
> 
> Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.
> 
> Right now you can use price rates to control price per day depending on how many days you want to book. Please clarify the part about redirection.
> 
> Thank you for your understanding.

Thanks for your immediate response .

Okay . This is what I actually wants for the Conditional Days Rental booking . 1 - 2 days , the renter will pay the original base price . Let's say $500 is the original price . But if they booked for 3 days , there will be an additional let's say $500 again to the original rental base price which is $500 that will be total of $1000 . I don't want the calculations to be multiplied by days which is the " add rates " currently fucntion is ( price per nights / days ) .

Regarding redirection , I just want to skip that part for now . I just want the above calculations to be implemented .

Will it requires some custom coding like JS ? If yes , how ?

**Comment by chunibyuu** [comment]
@UraraReika 
Hi again . I was able to calculate it through conditional logic with 2 different calculations field . The problem is I need to show it in woocommerce checkout and obviously I need both calculations to appear based on logic of what the renter has chose from the dates . 

I only want to show what is appropriate amount to be displayed like I said based on what they have booking dates they have chose from . ( if the previous thread can't be solved . )

Here is a screenshot what I am talking about .
![booking amount](https://github.com/Crocoblock/suggestions/assets/140369017/b1b3c715-06a7-4e0c-8a9e-7712368ead8d)

I want to display only the amount that is based upon the renter's choice from booking dates . 

Is it possible now ? If yer , how ?

Thanks !

P.S. Sorry for the typo in the screenshot . The below amount is " **less than 3 days** " 
Cheers ~

**Comment by chunibyuu** [comment]
@UraraReika 
I just changed my conditional logic into this : 
![screencapture-27d080a651-nxcli-io-wp-admin-post-php-2023-08-24-11_26_09](https://github.com/Crocoblock/suggestions/assets/140369017/79fe5690-bd78-4e1a-9bc2-aae2b5762947)

But still it won't calculate it . 
Any help ?

**Comment by UraraReika** [comment]
I've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such complex cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.
