### ISSUE TITLE
Interference between elementor and jet product gallery.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7043]
Hi,

When I activate the jet product gallery, there is a problem with the  nested carousel widget, as you can see in the video below. **It should be noted that when I disable the Improved CSS Loading option in Elementor settings, the problem is solved.** But if this option (Improved CSS Loading) is enabled, but the jet product gallery plugin is disabled, there will be no problem.

https://github.com/Crocoblock/suggestions/assets/77163248/596a1b11-aa5c-4586-8c6e-ce87cb54b632

**active plugins :**

elementor
elementor pro
jet product gallery

**Comment by UraraReika** [comment]
Please specify what exact widget did you use? `the nested carousel widget` what widget is that?

**Comment by 79ho3ein** [comment]
nested carousel It's a new widget in Elementor (from elementor 3.14).

https://github.com/orgs/elementor/discussions/22580

**Comment by UraraReika** [comment]
We will keep track this issue while this feature in beta status. 

Thank you for understanding!

**Comment by ArongodCoder** [comment]
@79ho3ein 
We have checked your request and everything seems to be working correctly now.

It seems Elementor team [disable the Improved CSS Loading option](https://prnt.sc/uZIBaRYuLjfK) in [3.24 Update](https://developers.elementor.com/elementor-3-24-developers-update/).
Perhaps this is related to your site. To fix you can install Elementor update. If you need any help or consultation, please [contact](https://support.crocoblock.com/support/home/) our support team.

Thank you!
