### ISSUE TITLE
JetWooBuilder - Box Shadow and Border

### ISSUE THREAD

**Issue by zimmiel** [Crocoblock/suggestions#705]
Hello
In JetWooBuilder - Single Images does not work functions Box Shadow and Border
![JetWooBuilder](https://user-images.githubusercontent.com/42843497/69732787-ebc8d300-1134-11ea-9cee-fddc7e7a50ee.png)

_(JetWooBuilder without JetProductGallery)_

**Comment by UraraReika** [comment]
Hi @zimmiel! We deeply sorry that our widget can't make things that you need, but from the beginning this controls style the main image of the products gallery and if the image only one, styles would not apply.
