### ISSUE TITLE
Add to cart Background color changes when activating slider in listing grid widget

### ISSUE THREAD

**Issue by sabbirahasanhabib** [CrocoBlock/suggestions#7054]
Hi, @UraraReika @Floydtm @MjHead 
I have created a product listing with jetengine and used archive product widgets in the template as i read from this forum it is possible to use jetwoobuilder archive widgets directly into jetengine listing template...It works just perfectly. 

Basically my motive is to show some specific product/featured/sale in a carousel mode in my homepage. I know i could use product grid widget but it is limited for showing extra things in the product card. However, the listing grid widget is pulling all the data just perfectly from the template but when i enable slider two tiny problems arrived

1. The add to cart button(Archive add to cart button widget) background color changes to black from orange and all the styles in the add to cart button
2.  when pressing the add to cart it kinda freeze for 2-3 seconds and there was no default loading icon there which was present in the normal mode and if i do not use the slider option everything works perfectly.

**This is the image of jetengine listing template made by jetwoobuilder archive widgets**

![Screenshot_22](https://github.com/Crocoblock/suggestions/assets/137334915/08a4ba90-fd64-4e1f-bfb0-fc349aca0d42)

**This is the image of listing grid widget in normal mode placed in homepage**

![Screenshot_23](https://github.com/Crocoblock/suggestions/assets/137334915/b6bd4226-3b6e-46ff-bd5e-7fb58dda49cd)

**This is the image when i activate slider placed in homepage**

![Screenshot_24](https://github.com/Crocoblock/suggestions/assets/137334915/4c277b48-de92-45ff-aa10-f68c8f50ce15)

The listing grid is an awesome feature for resolving all the problems we have but i guess there are some styling issues there when enabling slider.
I have tried using custom css to change the button color but it doesn't work in slider mode but it does work in normal mode...There are many ways to show featured/related/upsells but those are without carousel option as far as i know and i cant use product grid for carousel for its limitations.

Hope to get an awesome reply from you :)

**Comment by sabbirahasanhabib** [comment]
###Update###
@UraraReika @kaskad88 
I have figured out the issue. If i select "inactive" the additional breakpoints in elementor settings the issue resolved..but this is not a permanent solution bcoz i need additional breakpoints to work with..i contacted elementor they said , the third party addon(crocoblock) is fully responsible to adapt new update from elementor..As the addon(crocoblock) is using their plugin editor to make things work.. So plz fix the issue...

one more thing if i active additional breakpoints mega menu is not responsive in mobile version.if i inactive it things work perfectly.. I have used vertical mega menu in my account template from jetwoobuilder to show the endpoints (as instructed from your YT channel video)...so plz make things easy for us..we need additional breakpoints as well as crocoblock..

**Comment by UraraReika** [comment]
Hello. Thanks for the feedback.

> I have figured out the issue. If i select "inactive" the additional breakpoints in elementor settings the issue resolved..but this is not a permanent solution bcoz i need additional breakpoints to work with..i contacted elementor they said , the third party addon(crocoblock) is fully responsible to adapt new update from elementor..As the addon(crocoblock) is using their plugin editor to make things work.. So plz fix the issue...

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

> one more thing if i active additional breakpoints mega menu is not responsive in mobile version.if i inactive it things work perfectly.. I have used vertical mega menu in my account template from jetwoobuilder to show the endpoints (as instructed from your YT channel video)...so plz make things easy for us..we need additional breakpoints as well as crocoblock..

Please follow guidelines for opening a [new bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better.

Thank you for your understanding.
