### ISSUE TITLE
JetEngine > Export SmartFilters ?

### ISSUE THREAD

**Issue by pierresubotai** [CrocoBlock/suggestions#7059]
Hi !

Is there a possibility to export SmartFilters via Skin Export ?

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by pierresubotai** [comment]
Hi.
In the "Skin manager" below "Jetengine" menu in the WordPress Admin Area, you can export or import a skin.
this includes :
Post types, Taxnonomies, Meta boxes, Relations, options Pages, Glossaries, Queries, Listing Items.

But not the SmartFilters.

It would be super useful to be able to export SmartFilters too like the others to use a "SKIN" from a site to another.

Hope it's clearer.

Regards

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.
Right now you can use import and export to transfer your filter data https://tppr.me/aKhxX

**Comment by pierresubotai** [comment]
Hi, 
thanks. I'll try this.

It's a pity that this feature is not included in the Skin Manager

Regards
