### ISSUE TITLE
No of person in booking and calendar availability 

### ISSUE THREAD

**Issue by michalczajka** [CrocoBlock/suggestions#7062]
Please add two things 

1. possibility to add person number and multiply this number per reservation
Eg. Reservation for 3 person on trip - trip price 50€ is 150€ total.

2. when I have 5 possible items to reservation if one of them is bought it should show not available in calendar. In my case I have 5 bike trips and it’s not possible to book more then 1 in a day. There is only one guide for trips.

**Comment by UraraReika** [comment]
> possibility to add person number and multiply this number per reservation
> Eg. Reservation for 3 person on trip - trip price 50€ is 150€ total.

In this case you can use calculated field in the form and set the formula that will multiply cost of the booking on the number of persons like this https://tppr.me/87KQKy. Wheres persons is a field name to get value from and _check_in_out - is the name of the field that returns the number of days booked

For more info please [contact](https://support.crocoblock.com/support/home/ ) our support team.

> when I have 5 possible items to reservation if one of them is bought it should show not available in calendar. In my case I have 5 bike trips and it’s not possible to book more then 1 in a day. There is only one guide for trips.

I've checked your request. Unfortunately, we do not plan to introduce such functionality into our plugin. But such a goal can be reached using a custom solution. I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such complex cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.
