### ISSUE TITLE
JetElements: Add possibility to select different image sizes for different devices

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#7064]
Currently, the Advanced Carousel widget provides the possibility to set image size only for desktops: https://prnt.sc/R8RyFLs3bBtz
It would be great to have the possibility to switch image sizes for different device types separately (e.g. I would like to have smaller-sized images for mobile).

**Comment by bazilik1095** [comment]
Немає можливості реалізувати даний функціонал
