### ISSUE TITLE
JetAppointment: edit the appointments from the front-end 

### ISSUE THREAD

**Issue by Linkeofit** [CrocoBlock/suggestions#7066]
Hello, we have a request for the product: 
Could the client, edit the appointments from the front-end? The idea is not to give access to the Wordpress´s admin area and that our clients can edit the  appointments like a post type from his customized interface.

**Comment by olyaastep** [comment]
+

**Comment by Crocoblock** [comment]
Hi 
I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/6401)
