### ISSUE TITLE
Integration of jetwoobuilder with Paid member subscription

### ISSUE THREAD

**Issue by michele-sp** [CrocoBlock/suggestions#7068]
The two plugins do not work well together. My website includes a member subscription as a “Student", who gets a 50% discount on some categories of products. Subscribed "Student" users should see the discounted prices on the shop page. This happens correctly immediately after the login. However, the discount disappears when the shop page is refreshed. Instead, the discount is applied correctly if I do not customize the product archive with Jetwoobuilder.

It would be nice if you could smooth the integration of the two plugins.

Best wishes

**Comment by UraraReika** [comment]
Please [contact](https://support.crocoblock.com/support/home/ ) our support team so we can check this issue on your side.

Thank you!
