### ISSUE TITLE
Logic for displaying custom fields in Jet Engine

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#707]
Hello, I ask you to consider the possibility of introducing a functionality that can show or hide arbitrary fields in the admin panel, depending on the user's choice, whether the field is empty or not empty.

**Example:**
The user has the opportunity to choose: Hide portfolio or show on the service template page - https://prnt.sc/q36d5k
It would be logical to hide the fields that belong to the portfolio, since there is no need to display them.

/*Оригинал*/
Здравствуйте, прошу рассмотреть возможность внедрения функционала который сможет показывать или скрывать произвольные поля в админ панели в зависимости от выбора пользователя, пустое или не пустое значение поля.

**Пример:**
У пользователя есть возможность выбора: Скрыть портфолио или показать на странице шаблона услуги - https://prnt.sc/q36d5k
Логично было бы скрывать поля которые относятся к портфолио, так как в их отображении нет необходимости.

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0
