### ISSUE TITLE
JetSearch compatibility with TranslatePress

### ISSUE THREAD

**Issue by hankristian** [CrocoBlock/suggestions#7071]
Hi there,

I'd like to suggest the compatibility to TranslatePress. Sadly JetSearch seems to only get the default language for it's search query. So changing the language returns to no results in the expected language (or you'd have to keep searching with default language).

I think this should be crucial to implement.

Thanks,
Kristian

**Comment by Crocoblock** [comment]
Was fixed and released in JetSearch 3.5.0
