### ISSUE TITLE
JetWooBuilder - how to add input text to single product page

### ISSUE THREAD

**Issue by martinjakse** [CrocoBlock/suggestions#7073]
Hello to all Crocoblock enthusiast,

I was wondering if you can help me find out how to add input text field into a single product page for just a specific products.
You can see the example in this video: https://www.youtube.com/watch?v=u5TS7jBL-H0

Every bit of help is very appreciated,

Martin

**Comment by UraraReika** [comment]
I've checked your request. Such a goal can be reached using a custom solution only or you can use presented plugin. I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such complex cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.
