### ISSUE TITLE
🐞 Jet smart filters bug : Filters will not work if vpn is enabled.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7076]
Hi team,

When the vpn is on, the filters and even the paging widget are completely disabled And they don't work. I am experiencing this bug in Chrome-Android browser and I have not checked other browsers and devices.

thank you

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by 79ho3ein** [comment]
To be honest, I don't know exactly where the problem is. In fact, this problem only exists in my country because people use vpn due to the filtering of social networks like Instagram.
On the other hand, this problem only occurs in one of the popular vpn (v2ray). Therefore, I think it is better for us to deal with this problem. Because it is definitely a lot of trouble to diagnose it. Because I don't think you use vpn in Ukraine. thanks anyway
