### ISSUE TITLE
JetElements WooCommerce Sale Products show pagination

### ISSUE THREAD

**Issue by aloMalbarez** [Crocoblock/suggestions#708]
**Describe the bug**
woocommerce Sales does not have pagination

**To Reproduce**
1. Go to pages menu
2. Add new page
3. Click on 'edit with elementor'
4. Add a section
5. Search for the widget 'WooCommerce Sale Products'
6. Add the widget
7. See Eerror: settings has no 'Show pagination' checkbox

**Expected behavior**
A checkbox to enable or disable pagination

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![01-jet-elements-woo-sale-products-paginationCapture](https://user-images.githubusercontent.com/1757139/69811158-3ba6a900-11cc-11ea-89b0-43a63648986d.PNG)

![02-jet-elements-woo-sale-products-pagination-withpatchCapture](https://user-images.githubusercontent.com/1757139/69811177-49f4c500-11cc-11ea-9a53-19cd454369c4.PNG)

A suggested patch:
```
--- a/public/wp-content/plugins/jet-elements/includes/addons/vendor/jet-elements-woo-sale-products.php
+++ b/public/wp-content/plugins/jet-elements/includes/addons/vendor/jet-elements-woo-sale-products.php
@@ -61,6 +61,14 @@ class Jet_Elements_Woo_Sale_Products extends Jet_Elements_Base {
 				'type'    => Controls_Manager::SELECT,
 				'default' => 'desc',
 				'options' => jet_elements_tools()->order_arr(),
+      ),
+      'paginate' =>	array(
+				'label'        => esc_html__( 'Show Pagination', 'jet-elements' ),
+				'type'         => Controls_Manager::SWITCHER,
+				'label_on'     => esc_html__( 'Yes', 'jet-elements' ),
+				'label_off'    => esc_html__( 'No', 'jet-elements' ),
+				'return_value' => 'true',
+				'default'      => 'true',
 			)
 
 		);
```

**Comment by UraraReika** [comment]
Done. Next release.
