### ISSUE TITLE
Problem with Query Builder (Comparison by data)

### ISSUE THREAD

**Issue by lagethomas** [CrocoBlock/suggestions#7082]
When building a query using query builder to display posts of the day, it respects the Global time and not the local time. Therefore, when the time here in my region reaches 09:00pm, the posts disappear as if it were already 00:00am, that is, it does not respect my -3 time zone. How can I resolve this?

![2023-09-11_21-29](https://github.com/Crocoblock/suggestions/assets/47001888/dda54d34-ce1a-4afa-b1f1-462b36fad869)

**Comment by kaskad88** [comment]
@lagethomas 
**Solution**: add the following code to the functions.php file of the child theme
`add_filter( 'jet-engine/datetime/use-wp-date', '__return_true' );`
