### ISSUE TITLE
Jetwoo Product Grid - Order by Random with pagniation 

### ISSUE THREAD

**Issue by Rubenchico** [CrocoBlock/suggestions#7093]
Hi, 

I have a issue with the order by option "Random". 
When is set the product grid on Random en when is go to a another page with the pagination. 

When I go to the next page via the page, I see products that were previously visible. And it should actually be the case that you only see "new" products every time.

Hopefully this can be resolved.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. But here is workaround how to make it work:

```
add_filter( 'jet-woo-builder/shortcodes/jet-woo-products/final-query-args', function ( $query_args ) {

	// Get seed from session variable if it exists.
	$seed = false;

	if ( isset( $_SESSION['seed'] ) ) {
		$seed = $_SESSION['seed'];
	}

	// Set new seed if none exists.
	if ( ! $seed ) {
		$seed             = rand();
		$_SESSION['seed'] = $seed;
	}

	// Update ORDER BY clause to use seed.
	$query_args['orderby'] = 'RAND(' . $seed . ')';

	return $query_args;

} );
```

Simply add this code snippet to your child theme `functions.php`. If you want it works for Products List Widget use this hook `jet-woo-builder/shortcodes/jet-woo-products-list/final-query-args` instead.

This snippet will let you display a random list of random posts that stay in the same order for as long as the session exists. This makes sure that the pagination will be consistent.

Thank you for your understanding.
