### ISSUE TITLE
JetSmart Filter Version 3.2.1 Date Range for user_registered not working

### ISSUE THREAD

**Issue by wisiagency** [CrocoBlock/suggestions#7097]
**Describe the bug**
Before JetSmart Filter Date Range and Date Period Working on Post Date and Meta for user_registered

**To Reproduce**

**Expected behavior**
Date Range can Filter User Registration Date

**Screenshots**
![image](https://github.com/Crocoblock/suggestions/assets/114271739/8818bd72-b08d-47df-bfdd-5cbfd5333690)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Latest

**Additional context**

**Comment by Crocoblock** [comment]
Released in version 3.2.5
