### ISSUE TITLE
Add ordering option for JetSmartFilters (order A-Z, values from meta fields)

### ISSUE THREAD

**Issue by Crocoblock** [Crocoblock/suggestions#71]
An ability for the JetSmartFilters to sort the items from listing grid by values from meta field (e.g., custom price field), A-Z alphabetical order.

**Comment by RodSuper** [comment]
+1

**Comment by Samurhan** [comment]
+1

**Comment by sermalefico** [comment]
ASC and DESC order, number of items per page...

**Comment by Floydtm** [comment]
Available in the plugin starting from version 1.7.0
