### ISSUE TITLE
After the latest update of jetwoobuilder and jetpopup>> single title is not showing in product quick view popup

### ISSUE THREAD

**Issue by sabbirahasanhabib** [CrocoBlock/suggestions#7103]
Hello @Floydtm @UraraReika 
After the latest update single title is not showing in the frontend.
I have tested with this>>>
**Theme: Hello Elementor
Activated Plugins: All Crocoblock suite + Elementor+Elementor Pro+ Woocommerce**

![Screenshot_24](https://github.com/Crocoblock/suggestions/assets/137334915/9fca7b8f-bb9c-4775-a8e4-8926a1b13a66)

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
