### ISSUE TITLE
🐞 Bricks - JetSmartFilters - Filtering does not work when 0 results are achieved

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#7105]
If I filter a Bricks query with JetSmartFilters that it comes to 0 results, then the query gets stuck.
I can then no longer reset the filters by deleting the set filters. It remains then with 0 results

Bricks: 1.9
JetSmartfilters: 3.2.1
JetEngine: 3.2.3.2 (Since 3.2.4 unfortunately several problems) 

Edit: In a test environment with 3.2.0 it still seems to work

**Comment by MjHead** [comment]
was fixed with JetSmartFilters 3.2.2 update
