### ISSUE TITLE
Smart Post Tiles

### ISSUE THREAD

**Issue by JamieB100** [CrocoBlock/suggestions#7107]
For Smart Post Tiles, when Custom Query is enabled - no option to change the number of slides. 
For Smart Post Tiles - Content Title, no option to change the background colour.

**Comment by Floydtm** [comment]
@JamieB100 hi! 
1. The number of slides directly depends on the number of posts. You can adjust it in the query itself
2. If possible, we will add this in the next update

**Comment by Crocoblock** [comment]
was released in version 2.3.6
