### ISSUE TITLE
Bricks - JetSmartFilters - Update Bricks 1.9.1 broke SmartFilters

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#7109]
After updating from Bricks 1.9 to 1.9.1 the filters do not work anymore
Here more people have problems

https://forum.bricksbuilder.io/t/wait-updating-to-1-9-1-broke-jetsmartfilters/15536/4

**Comment by MjHead** [comment]
We fixed the problem, will try release the fix today. Thanks Bricks team for quick reaction and releasing 1.9.1.1 update with which helped to fix this quickly
