### ISSUE TITLE
JetEngine Listing Grid Load More Bug

### ISSUE THREAD

**Issue by sheaoliver** [Crocoblock/suggestions#711]
Hello Crocoblock Team,

I have discovered a bug with the Listing Grid. When your Post Query -> order_offset is set to order by Rand and you turn on the capability to "Load More," pressing the load more element does not exclude the previously displayed items. 

It appears that the load more element re-randomizes the entire query and then sometimes displays previously displayed items.

To see this in action, please visit: http://bestbookmonkey.com/stagingsite04/load-more-bug/

There are 5 custom post types ("Books") that load with this query. I set it to show 2 books. Hit the "Load More" button twice and you're likely to see the same book loaded more than once.  

Thanks again for your great software!

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by kaskad88** [comment]
Fix for the next version (2.2.0).
Thanks for your report!

**Comment by sheaoliver** [comment]
Thank you!!!

**Comment by Digital03** [comment]
Was solution in 2.2.0 beta 5? i cant make it works

**Comment by chrisecostanza** [comment]
Hello, I am encountering this issue again using JetEngine 2.4.12. Is anyone else running into this?

OS: MacOS
Browser Chrome
Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by santiagoscham** [comment]
Same issue!

**Comment by marrisonlab** [comment]
Same issue!

**Comment by kaskad88** [comment]
@marrisonlab  I tried to reproduce your issue and looks like all works fine.

Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)

**Comment by busyfritz** [comment]
Having this issue on our website: https://pineviewbuildings.com/building-inventory/

**Comment by rafsalcedo** [comment]
Having the same issue on 2025
