### ISSUE TITLE
Jetwoobuilder Product thumbnail effect breaks when serving WEBp images by <Picture> Tag

### ISSUE THREAD

**Issue by sabbirahasanhabib** [CrocoBlock/suggestions#7111]
Hello,

I am using jetwoobuilder along with Imagify...The product thumbnail effect breaks when activating Imagify..For your knowledge i am serving webp by imagify. This is a very popular plugin for image optimization having around 800k installation...Please fix this in your next release.

[screen-capture (1).webm](https://github.com/Crocoblock/suggestions/assets/137334915/7b102c4e-dd4b-4794-b7fb-39e13c6299e0)

**Comment by sabbirahasanhabib** [comment]
##Update##
The issue solved by ticking only rewrite rules in Imagify settings. The img tag was conflicting with crocoblock

**Comment by sabbirahasanhabib** [comment]
Hi, I am reopening the issue bcoz upon my investigation i have come to know that
Rewrite rules doean't work for webp when u have cloudflare or any other CDN..so the only way is to use picture tag instead of image tag...but this breaks the product image animation bcoz it has image tag...The situation is like i am kind in the middle of two giant elephant. one is cloudflare who does not let me rewrite. htaccess and another is croco which can not let me use the picture tag and breaks if i use it...

So is there any way to serve my images in webp format bcoz it is googles recommendation...Almost all the plugins use one of these methods that i mention to serve webp

**Comment by UraraReika** [comment]
Please describe the steps how we can reproduce this issue. You can use this template - https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md. Or [contact](https://support.crocoblock.com/support/home/ ) our support team so we can check this issue directly on your site.

Thank you!

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.

**Comment by sabbirahasanhabib** [comment]
there was a conflict if i use imagify plugin webp...the issue was solved by provivng webp through wprocket settings
