### ISSUE TITLE
URGENT Bug - Use get_home_url() instead of get_site_url()

### ISSUE THREAD

**Issue by cvl01** [CrocoBlock/suggestions#7113]
**Describe the bug**
On WordPress installations where the site url is not equal to the home url, the jet-search widgets currently do not work. JetSearch is trying to make requests to wp-json on the site url, whereas wp-json/ is accessible using the home url. 

**To Fix**
In `plugins/jet-search/includes/assets.php`, in line 152, 160, 161 change `get_site_url()` to `get_home_url()`

**Comment by josbroers** [comment]
Is there an ETA on this ticket. I'm facing the same issue.

**Comment by MjHead** [comment]
this will be fixed with 3.2.0 update in a few days
