### ISSUE TITLE
Dran n drop manual sorting on relation Children/Parent

### ISSUE THREAD

**Issue by apatsidis123** [CrocoBlock/suggestions#7114]
By that option it is possible to sort the list in front as it is on the back

![Στιγμιότυπο οθόνης 2023-09-22 141454](https://github.com/Crocoblock/suggestions/assets/74135399/f27f18a4-9333-4dab-9c9c-b616c7a690f3)

so it is possible to sort manually the list a relation child or parent like the following:
![Στιγμιότυπο οθόνης 2023-09-22 141514](https://github.com/Crocoblock/suggestions/assets/74135399/ab374fcf-21b2-420e-89f7-4800f5687321)

But regarding on sorting manually that list on the back, a drag n drop (or just numeric order) would be good to have. Or else any other way to sort is manually is 1) disconnect all the child/parent and connect them with the order you want (that is not that good solution if the connected objects are a lot)  2) to set meta field numbers and choose sort by numeric field (that is not also good if there is a many-to-many connection so you have to give enormous amount of digits to be sure that wont sorting wont be lost in other parent cpts). 

For example if the relation is many-to-many on Concerts to Bands, and you want to sort the bands on the Concert Single manually (so which bands performing on the current concert) you have to give many digits so to be sure that on another concert the band will be still sorted, not that easy to maintain)

So i think a manual sorting way drag n drop or numeric order (on the spot) will solve that issue.

**Comment by MjHead** [comment]
Added with 3.6.0 update
