### ISSUE TITLE
URL Link on dropbar widget

### ISSUE THREAD

**Issue by bombarda-rpd** [CrocoBlock/suggestions#7117]
When adding the dropbar widget it will be nice to see a field to add a link on the image.
On mouseover the content appears and on click it goes to  the specific URL.

This is useful when you have a grid with logos (example) and you want to link the visitors the websites.

**Comment by Floydtm** [comment]
We do not plan to implement such functionality in our plugin at the moment. After talking to the developer, we realized that this could lead to backwards compatibility errors. Thank you!
