### ISSUE TITLE
Jet appointment without time picker

### ISSUE THREAD

**Issue by Evelinevm** [CrocoBlock/suggestions#7124]
Can you make an option where you don't have to select a time in the calender. I just want to select a date, I don't need the time slots and picker.

**Comment by MjHead** [comment]
You can do this with JetBooking and One Day Bookings option enabled
<img width="1264" alt="image" src="https://github.com/Crocoblock/suggestions/assets/4987981/61140335-e31c-4b05-b9a3-b96bdd4aacd9">
