### ISSUE TITLE
Ability to sell software licenses via WooCommerce

### ISSUE THREAD

**Issue by mansoorih** [CrocoBlock/suggestions#7126]
Hello, I had a detailed discussion on Crocoblock support chat, and I'm told this feature is not available and I was advised to submit this feature request.

As an online seller of software products and digital goods using WooCommerce, I need the ability to easily deliver license keys, download links, and activations codes to customers after purchase.

This can be achieved in WooCommerce currently using paid extensions from WooCommerce and other third-party plugin sellers, costing over $300+ to $400+ annually. However, building this functionality natively into JetEngine or the JetWooBuilder would provide digital sellers using Crocoblock an affordable option to deliver licenses.

My request is for the ability to:

- Upload or add a comma separated list or line-by-line text file of license keys/activation codes or download URLs to a JetEngine custom post type or custom content type
- Connect the custom content or custom post to WooCommerce products
- After purchase, automatically deliver one of the licenses from the CPT/CCT to the customer via email on their My Account
- Have a 'Redeem' option in their 'My Account' to redeem.
- Allow admin to view which licenses are used/redeemed or unused, with if possible with date stamp when it was redeemed.

This would greatly improve the digital commerce capabilities offered in JetWooBuilder. Sellers would have an integrated, self-hosted option to sell software or digital products using Crocoblock plugins versus paying for external extensions.

The number of digital products being sold online is exponentially growing. Providing the functionality to easily distribute license keys and downloads would make Crocoblock an even more attractive option for WooCommerce store owners. I have attached screenshots of how this feature is available in a digital e-commerce platform [Sellix.io](https://sellix.io/).

Please consider adding this capability natively in a future release of JetWooBuilder or JetEngine or via a separate plugin. I'm happy to provide more details and use cases if helpful. Thank you for your consideration!

![image](https://github.com/Crocoblock/suggestions/assets/92026716/7dffa215-0dac-4360-8591-08833498b2e8)
![image](https://github.com/Crocoblock/suggestions/assets/92026716/be37d5a3-ecbc-4f2b-bc2c-a5a70ccc9d66)
![image](https://github.com/Crocoblock/suggestions/assets/92026716/e3e549b6-627d-47c4-983f-c12cb72f6208)
![image](https://github.com/Crocoblock/suggestions/assets/92026716/2f039222-aa4c-4068-a0af-61a6f0d2408d)
![image](https://github.com/Crocoblock/suggestions/assets/92026716/4c025beb-0642-4cb3-ac54-d478177dc23b)

**Comment by mansoorih** [comment]
@Floydtm - you added the label of question, but haven't asked anything past 5 days. Do you have a question for me?

**Comment by Floydtm** [comment]
@mansoorih it's for me. At the moment, we do not plan to introduce such functionality into our plugin. At the moment, I can offer you to look for a ready-made solution or make a custom one. Thank you!
