### ISSUE TITLE
JetSmartFilters AJAX loads default heme template instead of JetWooBuilder's archive template on "Products Loop" Widget

### ISSUE THREAD

**Issue by Andritsos** [CrocoBlock/suggestions#7127]
**Describe the bug**
Hello, I am using JetSmartFilters and JetWooBuilder along with Elementor Pro, WooCommerce and Astra theme. 
I have created a shop page using JetWooBuilder and I am using the Product Loop widget.
I have the Layout Switcher option enabled and I have created two Archive Templates in JetWooBuilder which are inserted in the appropriate field.

I also have some filters for that widget. The filters work correctly but AJAX loads the theme default archive template instead of my own custom archive template.

At WooCommerce -- > Settings --> JetWooBuilder I have ticked the options for:

"Enable custom shop page"
"Enable custom archive product" --> This is set to Default. If I specify either my List or Grid template then AJAX loads that for both  Grid or List view.
This issue happens with and without caching plugin (WP-Optimize)
--

<br class="Apple-interchange-newline">

**To Reproduce**
1. Go to https://yetipay.me/tools-and-integrations/
2. Use any filter option
3. See error

**Expected behavior**
It was supposed to load my custom list or my custom grid layout 

**Screenshots**
This is how it starts and how it's supposed to look after the filters are applied:
<img width="1440" alt="Screenshot 2023-10-02 at 1 33 47 PM" src="https://github.com/Crocoblock/suggestions/assets/146656738/c530af35-af15-48fb-b9a8-3730374e799a">

This is how it looks:
<img width="1440" alt="Screenshot 2023-10-02 at 1 33 09 PM" src="https://github.com/Crocoblock/suggestions/assets/146656738/1f483c61-ed7a-4396-9f1e-50f313531ece">

**Desktop (please complete the following information):**
 - OS: [MAC OS]
 - Browser [Chrome, Safari, maybe more-not tested]
 - Version [117.0.5938.132]

**Additional context**
I have tried experimenting with JetSmartFilters settings like:

Ajax Request type (all three options)
Indexer Settings ( Enable / Disable ) // We want to have it enabled

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. We tested it with default Ajax Request type and with enable & disabled Indexer settings. Please [contact](https://support.crocoblock.com/support/home/ ) our support team, if you haven't done so yet, and we will help you set up everything on your site.

Thank you for understanding!
