### ISSUE TITLE
JetTabs For Elementor broken 2.1.25.1+

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#7128]
Latest version breaks the functionality.

latest version working: Version 2.1.25 (September 20, 2023)

Error:

wp-json/jet-tabs-api/v1/elementor-template {"code":"rest_forbidden","message" ... 

Im using tabs to load templates with ajax. I suppose is the 2.1.25.1 version.

**Comment by Floydtm** [comment]
@ciprianpentelescu Thank you for writing to us. We apologize for the inconvenience and will fix this bug as soon as possible.
