### ISSUE TITLE
Text alignment issues with "Dynamic Field" widget

### ISSUE THREAD

**Issue by mhason** [Crocoblock/suggestions#713]
Hi,

Seems like the text alignment for Dynamic Field widget is not consistent and sometimes it is not working and needs a manual CSS workaround.

Please see the following short screencast for an example:
https://www.loom.com/share/cc5c8ca7114444cc9d8ceb0e71065feb

Thanks
Maurice

**Comment by Floydtm** [comment]
@mhason, Hi! Switch the option value to multiline http://prntscr.com/q4yl8f
