### ISSUE TITLE
Ajax search in custom fields - JET Search

### ISSUE THREAD

**Issue by mojzesz777** [CrocoBlock/suggestions#7144]
I use variant products for which I fill in the SKU field without indicating the main SKU. That is, Product 1 consists of variants A, B, C.
Product A has the code AX1111
Product B has the code AX2222
Product C has the code AX3333

I set the "search in custom fields" field to _sku in Ajax search, but JET doesn't see it. I contacted Crocoblock and they confirm that ajax search does not include the variant sku field...
So create a store using the most popular #woocommerce system, but be careful, you can't create variants because you won't find them using the "sku code."
![Screenshot_48](https://github.com/Crocoblock/suggestions/assets/109803899/393449a4-7ecd-4937-99f5-9866ea8ec96c)
![Screenshot_49](https://github.com/Crocoblock/suggestions/assets/109803899/fd2bc05c-2489-404d-9fe8-432863180c8c)

Where's the sense here????
More: So what's the point of this field in WooCommerce if it can't be used for searching, only for displaying?

**Comment by darthquack** [comment]
+100

**Comment by Crocoblock** [comment]
was added in version 3.3.0
