### ISSUE TITLE
Icon spacing issues in RTL languages for Dynamic Link

### ISSUE THREAD

**Issue by mhason** [Crocoblock/suggestions#715]
When creating a Dynamic Link with an icon it is impossible to set the margin of the icon from the text if the document is in RTL.

**To Reproduce**
1. Make sure you are working on WordPress with an RTL language
2. Drop a Dynamic Link into the page
3. Add an icon to the Dynamic Link
4. Select the "Style" tab and try to change the "Icon gap" parameter

**Expected behavior**
Increase or decrease the margin of the icon from the text by adding a left margin to the icon

**Screenshots**
A full screencast showing the issue is available here:
https://www.loom.com/share/55491feb75714f8fb1dec737b457dd8e

**Desktop (please complete the following information):**
 - OS: [MacOS High Sierra]
 - Browser [Chrome]
 - 78.0.3904.108 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**

**Comment by kaskad88** [comment]
Fix for the next version (2.2.0). 
Thanks for your report!
