### ISSUE TITLE
While submiting form like booking and appointment. I need a customized backend where i can add my fields and fetch data from form

### ISSUE THREAD

**Issue by FarhanDevShaikh** [CrocoBlock/suggestions#7154]
This feature I'm talking about is the same as the booking form, but I want to have my own customized backend.
for example
![image](https://github.com/Crocoblock/suggestions/assets/100278448/ec8a0baf-f71f-4362-91a9-b7cd39a91ca6)
In the above image, it will fetch only these details.
But for example, I'm creating a ticketing system so when the customer raises a request it should fetch details from the form and show in the backend with the fields I want to display.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/7019, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
