### ISSUE TITLE
jet woobuilder custom quantity selector bug

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7157]
**Describe the bug**

Hi

1- Changing the size of the positive and negative buttons in the custom quantity selector causes the button to go out of the frame on mobile phones and tablets, which is clear in the video below.

https://github.com/Crocoblock/suggestions/assets/77163248/4e0e554e-313f-4530-9a66-ced95f98b441

If this bug is difficult to fix from the infrastructure, adding a new margin control will solve the problem. This is the solution I use temporarily. my website is RTL.

@media (max-width:768px) {
.jet-woo-quantity-button-added.position-horizontal {
    margin-left: 12px
    }
}

2- If the "inline font icon" option is enabled in the Elementor settings, the default custom quantity icons will be corrupted.

![A](https://github.com/Crocoblock/suggestions/assets/77163248/7dacf538-cd3f-44a4-af79-955731a97bab)

3- I don't know why, but if I use SVG icons for the + and - buttons, the buttons don't work as expected. I actually click on the + button, but the number of products decreases! But when I use icons from the Elementor library, this problem no longer occurs.
**Please note that this bug occurs in the custom quantity selector of the cart page.**

Below I have added the svg icons that I used. I hope it is useful in reproducing the bug.

[icon.zip](https://github.com/Crocoblock/suggestions/files/13197711/icon.zip)

thank you

**Comment by UraraReika** [comment]
1, 3 - fixed.
2 - unfortunately JetWooBuilder - Custom Quantity Selector plugin will not support compatibility with this option.

You can download latest version here - https://github.com/UraraReika/jet-woo-builder-custom-quantity-selectors

**Comment by 79ho3ein** [comment]
thank you @UraraReika
