### ISSUE TITLE
Customize the range filter to be able to contain pre-ordered list "not only numbers"

### ISSUE THREAD

**Issue by MechelAbdo** [CrocoBlock/suggestions#7158]
the actual range filter contain only numbers with same step.
if we want to put filter for RAM of device  i cant put 2, 4, 8, 16, 32... or refresh rate of screen 60, 90, 120, 155, 240,...
or even put ordered list like screen resolution sd, hd, fhd, 2k, 4k,...
this is very needed feature.

**Comment by MjHead** [comment]
This looks more like case for checkboxes field. In theory - yes, it could be implemented in the UI of range, but under the hood it will be not the actual range, but better UI wrapper for checkboxes logic. Actual range filter is based on the comparison logic on the query side. And in theory filter could pass into query such expression - field_name > hd and field_name < 2k, but any query can't handle this.
