### ISSUE TITLE
JetSmartFilter Apply Button with Dynamic Redirection

### ISSUE THREAD

**Issue by andressavw** [CrocoBlock/suggestions#7163]
When we work with SEO, it is necessary to build urls with dynamic values, mainly coming from filters. It would be extremely necessary for the jetSmartFilter's Apply Button to work in the same way as the JetFormBuilder redirection (Custom URL), where it could add filter parameters to assemble the url.

I would also like to take this opportunity to request that within JetFormBuilder, it is possible to pass parameters from the JetSmartFilter fields within this Custom URL redirection.

![image](https://github.com/Crocoblock/suggestions/assets/48529799/457e3a19-558f-4c25-85e1-31971de8e810)

**Comment by SargasTM** [comment]
If you choose Apply type -> AJAX, the URL will remain clean without visible details.
If you choose Apply type -> Page reload the parameters will be added to the URL during redirection.
<img width="267" alt="image" src="https://github.com/user-attachments/assets/9311a883-3ef2-4357-a09f-dd97d320d952">
