### ISSUE TITLE
Feature request: Add repeating dates to Listing Grid

### ISSUE THREAD

**Issue by alexplex** [CrocoBlock/suggestions#7167]
I've just tried the 3.3.0-beta3 version with the repeating dates feature for the calendar. And I understand the repeating dates and Advanced Date field type only works with the calendar module. 

It would be really awesome if this feature would work with the Listing Grid too.

**Comment by TorbenE84** [comment]
ANy NEws on that?

**Comment by Crocoblock** [comment]
Hi. How to show advanced dates ( all recurring dates) in the posts listing or on the single post page:

1) Create the advanced date field and set it up. My example: https://prnt.sc/44pyTpU5adfA

2) Build a SQL query 
https://crocoblock.com/knowledge-base/jetengine/jetengine-query-builder-sql-query-type/
https://prnt.sc/K6I6S9iZnI6v  >https://prnt.sc/Nl81gipXjO-L
You may even add sorting
https://prnt.sc/79qouyeeMM3K

3) Build a listing for the query: 
https://crocoblock.com/knowledge-base/jetengine/how-to-create-query-builder-listing-template/
https://prnt.sc/Ujwrv6eBlvGV  > https://prnt.sc/GOW1F2I_jC8M >>https://prnt.sc/YX7xqzQ872Hl

4) Add the listing grid widget with this listing for the query to the single post page or to the posts listing
https://prnt.sc/hhQGPXm5lYma

You are all set!

If the Advanced Date meta field Recurrency rule is set manually https://prnt.sc/4uSpdm3NMG4t you need a different approach. Add the below code to the functions.php file of your current active child theme or to the Code Snippets plugin (or any other similar plugin that allows adding PHP snippets): https://gist.github.com/aalexandr21/e6d861be00007c451a56c199eb3d87ea

Then, on the page of the event or in the event listing, use the shortcode [get_adv_date_manual_input meta_key='adv_date' separator="<hr>" divider="/"] (where adv_date is the name of the meta field)

https://prnt.sc/oyYuIDpdFP3l
https://prnt.sc/rcBOFFqP5NEZ
