### ISSUE TITLE
The problem of updating the data store counter as Ajax in bricks

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#7169]
Hi crocoblock team,

I use 2 plugins jet engine and wp rocket on my website with bricks builder. I have a custom post type and on its single page I have used a datastore widget to allow likes for portfolios. The problem that exists is that if users like the desired work sample in the front end, the Ajax action is executed, but the counter is not updated. Therefore, the user must reload the page to update the counter, and this has made the data store practically unusable.

**Comment by Crocoblock** [comment]
If using our dynamic data macro https://i.imgur.com/FF1EY43.png there is no bug

If you still have issue please create a ticket including access details for your site where the issue occurred to make sure we can help you https://crocoblock.com/help-center
