### ISSUE TITLE
JetBooking - Set Days Delay Before Allowing a Booking

### ISSUE THREAD

**Issue by sheaoliver** [Crocoblock/suggestions#717]
Hello Crocoblock Team,

I would like to request another feature for JetBooking. For many types of bookings, a period of time may be required before the booking date. It would be very useful if an admin could set a specific number of days ahead that a booking may happen (in relation to the current date).

For example, let say that you rented cabins in the wilderness. During the summer months, the admin/caretaker of the cabins might only need one day to prepare a cabin for a new booking. However, in the winter, you might need 3 days to plow the roads, bring in firewood, top off a propane tank, and ensure emergency supplies are in the cabins. So, taking a booking with no delay would be impossible.

If an admin could go to the booking table and set a “number of days delay” from the current date, that would ensure that bookings would be made with the proper amount of lead time for the admin/caretaker. 

Thanks again for your help and consideration of this feature.

Cheers!
Shea

**Comment by UraraReika** [comment]
Release 2.6.0
