### ISSUE TITLE
Timeline calendar

### ISSUE THREAD

**Issue by NoeVBD** [CrocoBlock/suggestions#7178]
I need a booking calendar, but have the option to view it on a timeline.
Could it be done somehow?

Thanks!!

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.

**Comment by NoeVBD** [comment]
Sorry, I've attached an example of a timeline calendar view.
It would be giving the option in the reservation calendar to have another view on the timeline.

Thanks
![IC-Project-Timeline-Template](https://github.com/Crocoblock/suggestions/assets/144664551/7bf0d980-0e26-4a03-a1b9-5ec010367dfe)

**Comment by NoeVBD** [comment]
As a diagrama de Gantt.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/1425, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
