### ISSUE TITLE
JetEngine Options Page shortcodes in frontend?

### ISSUE THREAD

**Issue by ak47marx** [Crocoblock/suggestions#718]
Hi, I have create an options page. How can I display the field  in front-end inside of regular text?

For example ACF has this:

This is a story about a boy named [acf field="name"]. He is [acf field="age"] years old.

**Comment by ak47marx** [comment]
Hi, any updates? :)
Just wondering if it would be something simple like a shortcode snippet in functions.php or something more extensive and would need to hire a developer?

**Comment by Floydtm** [comment]
@ak47marx, hi! Thank you for the message! We are currently working on a new version of the plugin. We will try to implement your wish in the next release. stay tuned

**Comment by ak47marx** [comment]
Very cool, thanks :)
