### ISSUE TITLE
Logged-in render state for Jetformbuilder

### ISSUE THREAD

**Issue by aquaminh** [CrocoBlock/suggestions#7183]
**Before adding this feature request, I've checked:**

- there's no such feature added to the backlog or in work;
- there's no such feature in the products.

### Logged-in render state

Render state is such a powerful JFB feature. It'd be even better if a render state called something like "LOGGEDIN" added to the list.

One use case: A contact form where logged in user can submit the message in the LOGGEDIN state without having to fill in existing fields. And for unlogged users, they will see required fields e.g name, email, etc.

Actually I'm using two forms to show/hide as per user login status. But it's harder to maintain two forms at a time.

I've also tried block visibility features to show/hide logged in and logged out users but some blocks don't have this setting e.g submit button.

The render state is also helpful where actions such as "register new user" and "edit user" can be conditionally performed.

**Comment by girafffee** [comment]
Hi @aquaminh,
Just added an example of registering custom render states.
https://gist.github.com/girafffee/eb3a6b5a3afa6fa28733985d5c29320c

**Comment by aquaminh** [comment]
> Hi @aquaminh, Just added an example of registering custom render states. https://gist.github.com/girafffee/eb3a6b5a3afa6fa28733985d5c29320c

Hi @girafffee,

The added render state doesn't show up in the switch render state button:

<img width="275" alt="Screenshot 2023-11-14 at 1 36 14 PM" src="https://github.com/Crocoblock/suggestions/assets/15320292/e6926f56-33e3-4d03-826b-fec7bf11cfef">

Could you please have second look?

Thanks a lot.

**Comment by girafffee** [comment]
@aquaminh 
Registered states can not be available in Action Button, because then the meaning of their existence breaks down. Because one of them is active only for authorized users, and the other for guests.
Therefore, they can be used only in Conditional Block, and in events for post-submit actions with the prefix "ON." as well as for other states.

**Comment by aquaminh** [comment]
> @aquaminh Registered states can not be available in Action Button, because then the meaning of their existence breaks down. Because one of them is active only for authorized users, and the other for guests. Therefore, they can be used only in Conditional Block, and in events for post-submit actions with the prefix "ON." as well as for other states.

Got it. Thank you.
