### ISSUE TITLE
Jet Form Media Drag and Drop

### ISSUE THREAD

**Issue by preciousjoyb** [CrocoBlock/suggestions#7188]
Jet Form Media Drag and Drop

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by cwinkler8** [comment]
I'm not sure if this is what @preciousjoyb meant, but it would be nice to allow front-end form users to select a file from the media library. Ideally, with the ability to select from only a specific folder like "approved images".

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7279)
