### ISSUE TITLE
WP CLI support for Jet Pugins

### ISSUE THREAD

**Issue by i4marketing** [Crocoblock/suggestions#719]
Please add WP CLI support for all Jet Plugins

**Comment by stijnvanouplines** [comment]
+1

I use the WP CLI to update a lot of sites.

When you do `wp plugin list` all JetPlugins have no updates. We have to manually login to all sites to update JetPlugins.

**Comment by Floydtm** [comment]
Guys, technically there is no way to apply this to our plugins.

**Comment by i4marketing** [comment]
> Guys, technically there is no way to apply this to our plugins.

Most other plugins have implemented it including elementor, so I am confused why 'technically' you can't?

**Comment by whysthatso** [comment]
is there any other way / approach to script the update process? i'm looking at taking on a client set of 10+ sites with jet plugins. manual plugin update is pretty uneconomical on such a scale.

**Comment by stijnvanouplines** [comment]
What exactly is the problem? If it's possible through the dashboard updates, then it shouldn't be too difficult to have that functionality through the CLI?

**Comment by Preen** [comment]
This is fubar.
