### ISSUE TITLE
Version 3.2.0 - Suggestion sessions table not created but deletion attempted

### ISSUE THREAD

**Issue by huush** [CrocoBlock/suggestions#7193]
**Describe the bug**
When using Jet Search after update to 3.2.0 the debug log is receiving this error.
"WordPress database error Table [site]_wp63647.wpxg_jet_search_suggestions_sessions' doesn't exist for query DELETE FROM wpxg_jet_search_suggestions_sessions WHERE created_at < '2023-11-16 00:00:01' made by require('wp-blog-header.php'), wp, WP->main, do_action_ref_array('wp'), WP_Hook->do_action, WP_Hook->apply_filters, Jet_Search_Token_Manager->schedule_token_cleanup, Jet_Search_Token_Manager->clean_old_tokens"

However, the Session usage settings have not even been enabled after update. So, 
1, the table doesn't exist, and 
2, the plugin is trying to act on that table even though the function isn't enabled. 

**To reproduce**
Upgrade to 3.2.0 and use the search with debug turned on. 

**Expected behavior**
These errors shouldn't appear. 

**Screenshots**
![Screenshot 2023-11-16 154849](https://github.com/Crocoblock/suggestions/assets/15254297/e8979417-2ee1-4965-ab4d-a47f1e4b6881)

**Desktop (please complete the following information):**
 - Linux server host
 - Chrome user

**Comment by Crocoblock** [comment]
was released in version 3.2.0.1
