### ISSUE TITLE
Two bugs in the quantity selector plugin (jet woobuilder)

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#7195]
Hi

There are two bugs in the quantity selector, which customers actually reported to us.

1- If the inline font icon option is enabled in the Elementor settings, the + and - icons in the quantity selector are broken.

2- If we use svg icons for + and - button, the function of the + button will have problems. The problem is that by clicking on the + button, the number of products decreases. This happens sometimes, but it does exist. When I change the svg icons to elementor library icons, the problem is solved.

I hope a quick solution for these two problems will be published.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/7157, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
