### ISSUE TITLE
JetEngine WPML and multilingual ready

### ISSUE THREAD

**Issue by wpsumo** [Crocoblock/suggestions#72]
Please make JetEngine multilingual and WPML ready, right now I'm forced to use ACF if I want to use dynamic content. This is a core thing you guys should prioritize.

**Comment by gringadgets** [comment]
I second for this also. Most of the agencies / prelancers uses multi lingual plugins and compatibility from them is a must. i.e. the Custom Post Mame cannot be translated. if we have a CPT "events" cannot find the string to translate it. Breadcrumbs sample: Home (Translatable) -> Events - CPT (NOT translatable) - Open House - Taxonomies (translatable) -> post type title (translatable)

**Comment by vovkasolovev** [comment]
+1

**Comment by RodSuper** [comment]
Hello, can I add the request to also add Polylang integration for JetEngine?

This is a much-needed option as JetEngine becomes a bigger and better plugin for many :)

**Comment by pierrehansen** [comment]
+1 Half of my websites are running on Polylang. Absolute must have. For now it's a non buy criterion.

**Comment by optimify** [comment]
+1 also from me for Polylang Integration . I tried it with the plugin WP Slug Post Type Custom Language, but unfortunately it doesn't work either (only with a Custom Post Type which I insert myself via functions.php).

**Comment by dbuchal** [comment]
@optimify

But not for Meta Fields/Boxes!

**Comment by dbuchal** [comment]
Still struggle with multilingual translations, using WPML, but not all things could be translated, like radio/checkbox option values in Metafields/boxes. Any suggestions to solve that issue?

**Comment by acornavi** [comment]
Any news?

**Comment by dbuchal** [comment]
Since one of the last JetEngine Updates radio/checkbox option values in Metafields/boxes works fine with WPML (for my project).

**Comment by seosquirrel** [comment]
The problem of Meta Box and Polylang remains relevant.

**Comment by lifeact** [comment]
+1 add please compotable with Polylang
