### ISSUE TITLE
Sort by calculated columns in SQL query

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7200]
In SQL queries, you cannot sort by calculated columns. We have to do a SQL in advanced mode. It would be nice if they integrated it, to be able to filter later since in advanced mode you cannot filter or pagination.
![Captura de pantalla 2023-11-22 182534](https://github.com/Crocoblock/suggestions/assets/90837626/a046c5c6-8e42-4817-96bd-fad2deb38d5b)

**Comment by satomiao** [comment]
Yesss!!! Additionally, kindly take into account ensuring compatibility between the advanced mode of SQL queries and the pagination feature of JetSmartFilter.

**Comment by Crocoblock** [comment]
Done
was released in v3.4.4
