### ISSUE TITLE
Editing Query in the Elementor Editor's Popup Window

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#7204]
Hello, please consider the possibility of adding the functionality of editing / create Query in the popup window. This will save a lot of time for website developers. https://skr.sh/sMwTGjhHspQ.

You consider the old version of queries legacy, but it was much friendlier to developers in terms of availability and speed of work.

**Comment by MjHead** [comment]
Query now is editable from the front-end
