### ISSUE TITLE
2 bug in new version of jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7206]
**Describe the bug**

Hi team,

In the new version of jet woobuilder, there are two bugs that I will explain below.

1- In the card table widget, the svg icon is not displayed and its color cannot be controlled.

![Screenshot 1](https://github.com/Crocoblock/suggestions/assets/77163248/6c8801d6-b836-4873-bd53-ceab22261fd7)

2- After the update, controlling the input width and **quantity selectors** in the cart table widget has become very difficult and the desired result cannot be implemented. (After the update, the custom quantity selector width was changed in this widget)

**As a small feature request, please add a margin control to the custom quantity selector if possible. This helps to create space between the button and the custom quantity selector. For now, the code below is the solution.**

.quantity.jet-woo-quantity-button-added.position-horizontal {
    margin-left: 10px !important;
}

cheers

**Comment by UraraReika** [comment]
1 - fixed

2 - Default width style `width: 100%;` was added for quantity input and control changes to max-width for better display with custom quantity selector. This fix was added to prevent different element width for different product typed and stock quantities.

As for margin controls you can use this one - https://tppr.me/ugFIV or similar control in other widgets with buttons, https://tppr.me/S5wRa.

**Comment by 79ho3ein** [comment]
Hello and sorry for the delay @UraraReika,

>As for margin controls you can use this one - https://tppr.me/ugFIV or similar control in other widgets with buttons, https://tppr.me/S5wRa.

I have thought about this before. But the problem is that in the products where the quantity is hidden, the margin in the button causes an empty space to be created.

![Screenshot](https://github.com/Crocoblock/suggestions/assets/77163248/512dd67e-eaaa-4c30-bf46-1ad7fdcf996c)

So if this margin is added to the quantity, there will only be a gap if there is a quantity, and that's great. I hope I have expressed my words well.

<hr>

Another bug in this version is that in RTL, after adding the product to the cart, the tick icon is displayed on the right side of the text. Whereas before it was on the right side of the text.

**Before** :

![1](https://github.com/Crocoblock/suggestions/assets/77163248/9fdd0c76-ef17-44dc-9585-74ab8afdb947)

**Now :** 

https://github.com/Crocoblock/suggestions/assets/77163248/ef57ddf0-80c8-41a4-be80-0cdc5bfb44f0

If this icon in RTL is placed on the left side of the text (in RTL), the problem will be solved.

thank you

**Comment by UraraReika** [comment]
Slightly change selectors and now you can use this margin controls - https://tppr.me/ziUQw fog gap between button and quantity input.

We have checked your RLT issue and everything seems to be working correctly - https://tppr.me/1tXkU. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!

**Comment by 79ho3ein** [comment]
>Slightly change selectors and now you can use this margin controls - https://tppr.me/ziUQw fog gap between button and quantity input.

In this case, the result will be : https://prnt.sc/UXaiUUe30qHH

>We have checked your RLT issue and everything seems to be working correctly - https://tppr.me/1tXkU. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/) our support team.

thanks

**Comment by UraraReika** [comment]
> In this case, the result will be : https://prnt.sc/UXaiUUe30qHH

In the next release this control will be referred to another selector and everything will be looks nicely.

**Comment by 79ho3ein** [comment]
Nice! thank you

**Comment by 79ho3ein** [comment]
> > In this case, the result will be : https://prnt.sc/UXaiUUe30qHH
> 
> In the next release this control will be referred to another selector and everything will be looks nicely.

Hi @UraraReika,

This is broken again in the new version. Do I need to create a new number for it Or is the report here enough?

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/274695d4-97c9-46be-9b7b-ab37a5b5c477)
