### ISSUE TITLE
Smart Filter url aliases and variation product parameter

### ISSUE THREAD

**Issue by MMMRuiyang** [CrocoBlock/suggestions#7211]
After i active the crocoblock use url aliases, my parameter for variation product not working anymore it will make the url with the parameter link to error 404

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by MMMRuiyang** [comment]
Thx for reply i will check again
