### ISSUE TITLE
Listing grid - top padding

### ISSUE THREAD

**Issue by up-creator** [CrocoBlock/suggestions#7213]
Hi

I know it's not a big thing, but i believe this will help a lot of people, because of the time it takes to make changes to design, because of this top padding.

When using the widget Listing Grid, why is it that the Horizontal Gap, also makes room above the first row of listings?
The Gap attribute are known to be between elements, not around them.

I hope you will look into this, as it saves a lot of time writing css, every time we make a Listing Grid.

**Comment by ihslimn** [comment]
Thank you for reporting!
We cannot make it fixed automatically for all users, as some may have built their sites relying on that top/bottom padding.
Yet, the control will be added in 3.5.5 to allow for easier adjustment.
![image](https://github.com/user-attachments/assets/ccf7a5c7-29db-4b72-8e21-56ff262910af)

This control will be added for Elementor and - if you are using JetStyleManager - to Block Editor

**Comment by up-creator** [comment]
Hi Mykhailo

Thank you, i understand that 😊

Thank you for listening and making this change.

Med venlig hilsen

Mark Jesper Eriksen
Web Developer

***@***.******@***.***>
+45 63 60 20 19
[signature_1929240313]
Vestergade 165C - 5700 Svendborg
***@***.******@***.***>    +45 63 60 20 00
www.uptime.dk<https://uptime.dk/>     Find vej<https://goo.gl/maps/FHo1EDXJcft>

From: Mykhailo Kulinich ***@***.***>
Date: Tuesday, 6 August 2024 at 14.57
To: Crocoblock/suggestions ***@***.***>
Cc: Mark Eriksen ***@***.***>, Author ***@***.***>
Subject: Re: [Crocoblock/suggestions] Listing grid - top padding (Issue #7213)

Thank you for reporting!
We cannot make it fixed automatically for all users, as some may have built their sites relying on that top/bottom padding.
Yet, the control will be added in 3.5.5 to allow for easier adjustment.
image.png (view on web)<https://github.com/user-attachments/assets/ccf7a5c7-29db-4b72-8e21-56ff262910af>

This control will be added for Elementor and - if you are using JetStyleManager - to Block Editor

**Comment by up-creator** [comment]
Hi Mykhailo
 
Thank you, i understand that 😊
 
Thank you for listening and making this change.

**Comment by Crocoblock** [comment]
done in JetEngine 3.5.5
