### ISSUE TITLE
JetWooBuilder - Single Add To Cart - Display Type Has Lost Its Value

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#7219]
Sorry for the rough bug report, this is as much time as I have available now as I'm working to a deadline.

Twice over the last few months, the Single Add To Cart setting "Display Type" has reverted / wiped itself out.

Have you changed the stored value during a recent update? Or something else that would break it?

I find my detail page instead of being in a block / column mode, its reverted back to a row mode.

When I edit the page, the Display Type is blank, which indicates to me that it couldn't find a value to match it to / the value is blank:

<img width="302" alt="image" src="https://github.com/Crocoblock/suggestions/assets/1038062/85fd712c-babd-4163-a471-9466583f3789">

When I click on it I see this, which is normal I think:

<img width="288" alt="image" src="https://github.com/Crocoblock/suggestions/assets/1038062/6d71f090-75ff-4392-86fd-8316640661b7">

And when I select it, it is fixed.

It has happened on live version of the site, and I didn't get around to reporting it, but just went over to check something on the dev mirror and its here as well. 

It has happened on all templates that contain that widget, and the templates haven't otherwise been edited.

**Comment by UraraReika** [comment]
Thanks for the feedback.

We're sorry for the inconvenience, but over the past few releases, we've been working to ensure that the widget displays correctly in all possible conditions and views. The latest release has the final version of this functionality that we will stick to in the future and it will not change. 

Thank you for your understanding.
