### ISSUE TITLE
jet woobuilder : Custom text for after adding to cart

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#7220]
Hi crocoblock,

It would be great if, like bricks, you add the possibility to add custom text in different conditions for add to cart.

1- Normal mode : Add to cart

2- Adding to cart : When the Add to Cart button is clicked.

3- Added to cart : When the product is added to the cart.

We also need an option to specify how many seconds after the product is added to the cart, the button text changes back to Add to cart.

![Screenshot](https://github.com/Crocoblock/suggestions/assets/103376243/c7730966-4962-417a-bd5c-642a33baaab5)

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
