### ISSUE TITLE
Dynamic Visibility Query Count for Gutenberg does not work

### ISSUE THREAD

**Issue by Tony-Baker** [CrocoBlock/suggestions#7225]
**Describe the bug**
The dynamic visibility module for Gutenberg does not function when using the query count feature.

**To Reproduce**
Steps to reproduce the behaviour:

Go to any clean install of JetEngine and try to use the Query count function in the Dynamic Visibility module for Gutenberg. The module does not function. 

**Expected behaviour**
The module should function as advertised and intended. It works fine in Elementor, but the Gutenberg version has not been implemented correctly.

**Comment by kaskad88** [comment]
Fixed in JetEngine v3.3.4
