### ISSUE TITLE
Add template support to woocommerce widgets

### ISSUE THREAD

**Issue by dzamanakos** [CrocoBlock/suggestions#7226]
Hi, as a website developer that uses your plugins I would like to be able to select a page builder template for all of crocoblock woocommerce widgets.

At that moment the widgets : products grid, products list, woocommerce recent products, woocommerce featured products, woocommerce sale products, woocommerce best sellers, woocommerce top rated products, woocommerce products doesnt support templates made with woo page builder. 
Some support only some presets for the design, others can only be changed via the appearance tab and/or custom css.

For example, we want all "product blocks" to be the same in all parts of the website (ex. archive pages, also see products in single product page, pages with on sale products, product tabs in home page etc). 

In order to have the same design we can :
1. use your widgets, change the appearance tab, do some custom css for each widget in order to be exactly the same
2. make a template "Archive Item" in woo page builder and use listings and query builder to build the website

No 1 has the disadvantage that if we want to make the sale price red we have to edit all pages containing the widgets and change a lot of css. Also is more difficult to add something that doesnt exist via code (for example an attribute under the product title).
No 2 has the disadvantage that we need much more time developing the same functions as the widgets do, but we can use a template and do anything we want.

Concluding, i thing that template selection in all of your widgets is a must have.

best,

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin and will not add template functionality to every widget that can display a product loop. For example this widget woocommerce recent products, woocommerce featured products, woocommerce sale products, woocommerce best sellers, woocommerce top rated products, woocommerce products have shortcode based output and in this case you can use this setting - https://tppr.me/AflRP as well as next two. But in general each of these widgets has its own unique application, as well as appearance, for use in a variety of cases and situations.

If you want to use one template across you can use Archive Item template in combination with Products Loop and Elementor Pro products widgets. Or you can create JetEngine Listing template that supports the functionality of the JetWooBuilder archive widgets.

Please [contact](https://support.crocoblock.com/support/home/ ) our support team For more information.

Thank you for your understanding.
