### ISSUE TITLE
Jet wishlist fails to parse first wishlist button in product loop after AJAX filter/pagination

### ISSUE THREAD

**Issue by breakerh** [CrocoBlock/suggestions#7231]
**Describe the bug**
Jet wishlist fails to parse the first wishlist button in a product loop after ajax filter or pagination.
When you navigate to a new page (which is loaded through AJAX with jet smart filters) the first item shows the raw output of the crocoblock macro's.

**To Reproduce**
1. Create archive template
2. Add product loop
3. Add pagination (or another jet smart filter)
4. Add product item template
5. Add wishlist button
6. Open category or shop page
7. navigate to another page
8. First item doesn't render the wishlist button

**Expected behavior**
Consistent rendering of the button no matter what

**Screenshots**
[Screenshot of the error](https://i.imgur.com/lLCjCeO.jpeg)
[Screenshot of desired result](https://i.imgur.com/DTAoV8U.jpeg)

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version 119.0.6045.200

**Additional context**
Seems like an issue with the render content function inside the plugin.
Reloading the page solves the issue, but that's not desired.
All plugins (elementor, wordpress, crocoblock, woocommerce) are up to date

**Comment by breakerh** [comment]
I enabled wp debug and there were no errors while navigation FYI
Placing 'default' wishlist or duplicating the element also doesn't solve it.

**Comment by breakerh** [comment]
Any update on this?
For the current user we can solve this by using page reload. But there are some cases where this isn't desired.

I will try to make some time and look into it my self. If found I will create a PR.

**Comment by UraraReika** [comment]
Thanks for the feedback and sorry for the delay.

We have checked your request and tried to recreate it followed your steps but everything seems to be working correctly, https://tppr.me/nPuLL4, https://tppr.me/QfwhsJ. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!

**Comment by Fullstak-nl** [comment]
This issue is already resolved indeed.
Forgot to comment that here.
