### ISSUE TITLE
Jet woobuilder bug in Safari browser

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7240]
Hi @UraraReika, Good time,

In the **Safari browser,** the variable selection section is completely broken.

![1](https://github.com/Crocoblock/suggestions/assets/77163248/726d2128-357d-4c88-9bc6-9c75f4efd81c)

I am not sure if this bug also exists in LTR. But I see this bug in RTL. Is there a quick fix for this problem? 

Thanks in advance.

**Comment by 79ho3ein** [comment]
As another problem, if the product's inventory quantity is 1, the Custom Quantity Selectors will still be empty.

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/a2762ea1-4364-4087-b700-7ae9b2102979)

This problem was fixed in previous versions. But it came back again.

**Comment by UraraReika** [comment]
Hello @79ho3ein!

> In the Safari browser, the variable selection section is completely broken.

Technically speaking this in not a bug, this is how Safari browser display this element. And there is numerous article’s how to solve this issue and set the default Chrome look for all browsers or any other browsers on your choice.

**Comment by 79ho3ein** [comment]
Hi @UraraReika, thank you,

So, will this be fixed in the next release? Or can the problem be solved by us? Because this problem did not exist before.

**Comment by UraraReika** [comment]
Perhaps I didn’t understand you correct about problem you point, but if the problem connected to the variable select styles it was always like this and this functionality didn't change. So maybe please specify your request.

**Comment by 79ho3ein** [comment]
Please see the screenshot below which is in **Chrome browser - Android**. But if you see the screenshot at the beginning of this issue, it is clear that the variable selection option is very narrow and it is difficult for users to click on it. In fact, it seems that Safari ignores the padding of variable selection option.

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/b0c1a813-7df4-43f3-bfbf-74e06852ff71)
