### ISSUE TITLE
Jet Woo Builder - checkout coupon form missing html wrapper "checkout_coupon"

### ISSUE THREAD

**Issue by breakerh** [CrocoBlock/suggestions#7246]
**Describe the bug**
The Jet Woo Builder "Checkout Coupon Form" is missing a wrapper with the class "checkout_coupon" around the coupon form.

**To Reproduce**
1. edit your checkout template
2. Add Checkout Coupon form
3. Save
4. Open checkout
5. It's shown, but default expanded and can't be toggled.

**Expected behavior**
Toggle function and default collapsed.

**Screenshots**
With missing wrapper:
![image](https://github.com/Crocoblock/suggestions/assets/2008632/994e9263-ca96-4876-8858-732d23d8eab7)
HTML with missing wrapper (If I add the html wrapper toggling works, but styling is missing):
![image](https://github.com/Crocoblock/suggestions/assets/2008632/4d76cd57-2789-4209-97c6-6e62dc206145)

What it should be:
![image](https://github.com/Crocoblock/suggestions/assets/2008632/2fe15cea-8018-48b9-bdce-52c2dfb30beb)

**Desktop :**
 - OS: Windows
 - Browser Chrome
 - Version 120.0.6099.109

**Additional context**
The main issue is the toggle function, but it's also not applying the CSS of the wrapper..
I know this used to work on other sites we've built. I guess it has something to do with the recent woocommerce blocks and enhanced gutenburg integration etc..

**Comment by UraraReika** [comment]
Hello @breakerh! 

Unfortunately you can't use Checkout Coupon Form widget inside the body of the main checkout template. For this purpose you should use Checkout Top template. This is because main template itself is a form and you can't use form tag inside form tag. That is why you have this strange behaviour.

Thank you for understanding.

**Comment by webcoreinc** [comment]
You're own article shows the coupon form inside the regular checkout form. Croco articles routinely have wrong info and/or are outdated lol. 

https://crocoblock.com/knowledge-base/troubleshooting/elementor-pro-checkout-widget-not-working-with-jetwoobuilder/
