### ISSUE TITLE
Order query SQL

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7247]
Jetengine query builder
query type SQL
order & order by

Sorting does not work when changing from ascending to descending. This error only occurs in the new version 3.3.2
With version 3.3.1 it works.
![Captura de pantalla 2023-12-17 114539](https://github.com/Crocoblock/suggestions/assets/90837626/1f5aeca6-c616-4df6-9419-0cd93fb2d325)

**Comment by kaskad88** [comment]
@JuanCar29 Thanks for your report.
Fix will be in JetEngine v3.3.2.1

**Comment by abraham-td** [comment]
> @JuanCar29 Thanks for your report. Fix will be in JetEngine v3.3.2.1

I updated to version v3.3.2.1 and still having this issue

**Comment by Floydtm** [comment]
@abraham-td, hi! Very strange. Could you please contact support so that we can check your request in detail? Thank you!

**Comment by JuanCar29** [comment]
I have already sent a ticket to support.
I have realized that it only happens when a table union is made. The desc order does not appear in the code.
![Captura de pantalla 2023-12-20 200646](https://github.com/Crocoblock/suggestions/assets/90837626/69094b9b-1ab2-449e-83c8-d02a3a10211b)

**Comment by kaskad88** [comment]
> I have already sent a ticket to support. I have realized that it only happens when a table union is made. The desc order does not appear in the code. ![Captura de pantalla 2023-12-20 200646](https://private-user-images.githubusercontent.com/90837626/291992971-69094b9b-1ab2-449e-83c8-d02a3a10211b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTIwMzcsIm5iZiI6MTcwNDE5MTczNywicGF0aCI6Ii85MDgzNzYyNi8yOTE5OTI5NzEtNjkwOTRiOWItMWFiMi00NDllLTgzYzgtZDAyYTNhMTAyMTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEwMzUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYWMwYWVhYzQ5MTIyYzE5YTA1OTMyZDcyZmU2MTM3ZThjYTlkNzNlNGNkNGI1MTEyMTY1ZDg1MGUxZmU5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxmbKu8jGsMihsHM3w3Dz7zkCxjr8TueWBtgA5fG220)

Fix in JetEngine v3.3.3
