### ISSUE TITLE
A problem in the pagination of the product grid widget - jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7250]
Hi,

Currently, the pagination position of the product grid widget can be controlled using the position control. But this has a problem. Because it causes the pagination to be placed on its bottom content. **Like the screenshot below**.

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/816de6b8-4572-4681-adaf-7aac07420fe4)

To solve this problem, we can use the column padding control in the style tab of this widget. This solves the problem, but creates another problem. The problem is that if the number of sliders is not enough to display the pagination, there will be a lot of empty space at the bottom of the widget, which will affect the UI. **Like the screenshot below**.

![Screenshot_2](https://github.com/Crocoblock/suggestions/assets/77163248/c100605c-a306-4b82-b475-58525ed96b64)

### proposed solution :

It would be great if, in addition to the current options, we could statically control the pagination position using the margin control.

thank you

**Comment by UraraReika** [comment]
Combination of default Elementor controls and JetWooBuilde widget controls pretty flexible and you can achieve results you need. The solution that we currently have in our widget quite universal and can be used in many different scenarios.

We will not add additional controls for pagination element of the carousel. And in case of current positioning they will not work properly.

**Comment by 79ho3ein** [comment]
>The solution that we currently have in our widget quite universal and can be used in many different scenarios.

But unfortunately, there is a problem in the above scenario.

I agree that there is a lot of flexibility now. But this flexibility will be completed if you add the possibility to **override the absolute position to the pagination.**
