### ISSUE TITLE
Change HTML tags for JetEngine listing wrappers

### ISSUE THREAD

**Issue by zehjotkah** [CrocoBlock/suggestions#7256]
Using JetEngine listings and in Bricks/Elementor the element "Listing Grid". 
I'd like to be able to change the HTML tag for those elements. 

Seems to be a standard function for standard elements in Bricks: 

![Bildschirmfoto 2023-12-21 um 18 30 23](https://github.com/Crocoblock/suggestions/assets/111518041/fbcbb711-14ee-4c3d-a67a-13af8609b4d4)

Also seems to be a standard function for standard elements in Elementor. 

<img width="278" alt="Bildschirmfoto 2023-12-21 um 18 31 44" src="https://github.com/Crocoblock/suggestions/assets/111518041/70aea9bb-ca10-4483-ac64-b51170083865">

There is already a comment from another user which describes it well: https://github.com/Crocoblock/suggestions/issues/7140#issuecomment-1759911339

This way we could use correct semantics in our website's DOM. 

Instead of: 

```
<div class="jet-listing-grid__items">
<div class="jet-listing-grid__item"></div>
<div class="jet-listing-grid__item"></div>
</div>
```

The correct HTML semantics: 

```
<ul class="jet-listing-grid__items">
<li class="jet-listing-grid__item"></li>
<li class="jet-listing-grid__item"></li>
</ul>
```

**Comment by heckpet** [comment]
Highly needed! I'm not using the listing grid because of this issue regarding accessibility.

**Comment by norman-pixelkings** [comment]
Yes this is very much needed! I would like to output an unordered list or a table. Then the listings (Twig) template should output 
`<li></li> or <tr><td></td></tr>`
 etc. In the wrapper I would like to add the `<ul></ul> or <table></table>`.
Now I have to use some javascript to inject this.

**Comment by afagard** [comment]
> Highly needed! I'm not using the listing grid because of this issue regarding accessibility.

Can you reference how this isn't accessible? Or am I not thinking of the correct use-case. I'm thinking of grids. In Bootstrap:

```
<div class="row">
<div class="col-md-6">
<div class="col-md-6">
</div>
```

is valid and accessible and matches this output. I can understand for true lists a div-like structure isn't proper (nav's and such), but depending on the content can still be accessible.

I would really only use the listing grid to render, well, grids and a repeater to render ordered or bulleted lists (performance plays a roll too - listing grids aren't the fastest)

**Comment by zehjotkah** [comment]
@afagard You're correct that in many cases, a div-based grid can be perfectly accessible, especially for layout purposes like in your example.

However, the accessibility concern here is more about semantic meaning rather than just visual layout. When we're dealing with a list of items (even if displayed in a grid), using list elements (`<ul> and <li>`) can provide better semantic structure and improve screen reader navigation.

For example, if we're displaying a grid of products, blog posts, or any collection of similar items, semantically these are still a list. Screen readers can better understand and navigate this content when it's marked up as a list, providing users with information like the total number of items and allowing them to jump between list items easily.

That said, you're absolutely right that the appropriate HTML structure depends on the specific use case. For pure layout grids, div structures are fine. For lists of content items, semantic list structures are often preferable.

**Comment by ihslimn** [comment]
Thabk you all for the feedback!
This feature will be implemented, though not as a widget setting as of now.
The code will have to be added to make it possible, instructions will come with the release.

**Comment by meisterx2020** [comment]
@ihslimn 

Is it possible to use a  filter to modify the output of the JetEngine Listing Grid and replace the `<div>` wrapping elements with more semantic tags like` <ul>` or` <table>`? 

For example, applying a filter to adjust the wrapper and item tags dynamically based on the desired structure. 

If such a filter exists or could be implemented, it would greatly enhance flexibility and accessibility for developers.

**Comment by ihslimn** [comment]
<details>
<summary>
Code
</summary>

```php
class JEC_Change_Tags {
	
	public function __construct() {
		add_filter( 'jet-engine/listing/render/jet-listing-grid/settings', array( $this, 'apply_settings' ) );
		add_filter( 'jet-engine/listing/grid/nav-widget-settings', array( $this, 'nav_settings' ), 10, 2 );
		add_filter( 'jet-engine/listing/render/default-settings', array( $this, 'default_settings' ) );
	}
	
	//set 'is-ul-listing' setting to 1 if tags need to be changed to ul / li
	//change tags
	public function apply_settings( $settings ) {
		$settings['is-ul-listing'] = $this->is_ul_listing( $settings );
			
		if ( ! empty( $settings['is-ul-listing'] ) ) {
			$settings['list_items_wrapper_tag'] = 'ul';
			$settings['list_item_tag'] = 'li';
		}

		return $settings;
	}
	
	//set default value for compatibility with JetSmartFilters
	public function default_settings( $settings ) {
		$settings['is-ul-listing'] = '';
		return $settings;
	}
	
	//save 'is-ul-listing' to nav settings for compatibility with Load More
	public function nav_settings( $widget_settings, $settings ) {
		$widget_settings['is-ul-listing'] = $this->is_ul_listing( $settings );
		return $widget_settings;
	}
	
	//check if 'is-ul-listing' setting should be set for block / widget / element 
	//
	//for Elementor and Block Editor - widget / block must have 'listing-ul' class
	//for Bricks Builder - element must have a 'data-listing-ul' attribute
	public function is_ul_listing( $settings ) {
		if ( ! empty( $settings['is-ul-listing'] ) ) {
			return 1;
		}
		
		$class = '';
		
		if ( ! empty( $settings['_css_classes'] ) ) {
			$class = $settings['_css_classes'];
		} elseif ( ! empty( $settings['className'] ) ) {
			$class = $settings['className'];
		} elseif( ! empty( $settings['_attributes'] ) && is_array( $settings['_attributes'] ) ) {
			foreach ( $settings['_attributes'] as $attr ) {
				if ( ! empty( $attr['name'] ) && $attr['name'] === 'data-listing-ul' ) {
					$class = 'listing-ul';
					break;
				}
			}
		}
		
		return false !== strpos( $class, 'listing-ul' ) ? 1 : '';
	}
}

//create an instance of a class
new JEC_Change_Tags();
```
</details>

https://gist.github.com/Crocoblock/65387eeb54340f91c8df5be199a9a83d here is the code that should be added - _starting from JetEngine 3.6.1_ - to functions.php of your active theme or to code snippets in order to change wrapper tags

For it to take effect on a particular Listing Grid widget/block, a certain class/attribute should be added to that widget/block:
- in Elementor and Block Editor - add class `listing-ul` to the listing that should have tags changed https://i.imgur.com/Nuwu27A.png https://i.imgur.com/Fxhu3Xn.png
- in Bricks Builder - add `data-listing-ul` attribute with any value https://i.imgur.com/ksiIz9y.png

Compatibilirt with JetSmartFilters / Load More feature included.
If items wrapper tag is `ul`, item taf will be set to `li` automatically (in the code, item tag is set explicitly just for demonstration purpose)

**Comment by Crocoblock** [comment]
was added and released in JetEngine 3.6.1

**Comment by aayla-secura** [comment]
That's great. Do you think you could also add a UI control for it? I'd assume it's pretty easy to do: two additional select settings for a listing grid.

**Comment by meisterx2020** [comment]
@ihslimn @Crocoblock 
I would like this feature to work with `<table>` as well.
