### ISSUE TITLE
JetProductGallery does not work inside Elementors Nested Tabs Widget

### ISSUE THREAD

**Issue by lensbreak** [CrocoBlock/suggestions#7257]
As soon as you place the gallery inside a nested element like the new Tab widget by Elementor Pro the JetProductGallery falls apart, e.g. with the vertical thumbnails slider. Used it on a plain Elementor Pro + Hello Theme setup. Please make JetProductGallery fully compatible with Elementor.

**Comment by lensbreak** [comment]
When will this bug be resolved? The JetProductGallery is currently completely useless...

**Comment by lensbreak** [comment]
@UraraReika @Floydtm Can you please answer when this bug finally will be resolved or do we have to wait again 1+ year??

**Comment by lensbreak** [comment]
OK this company seems to be dead. No answers. No bug fixes. Still no updates since months as stated on the official website:

JetProductGallery 2.1.14
October 16, 2023

**Comment by UraraReika** [comment]
Hello @lensbreak! Sorry for the long delay.

We will work on thin issue for our next release.

Thank you for understanding.

**Comment by GastonIsDead** [comment]
new issue noticed
when gallery slider widget is nested inside elementor's tab, sliders can slide out of it's limits. beyond the first or last item into blank space. issue persists only during sliding with a mouse cursor, not navigation arrows.
normal gallery slider is placed for comparison.
video of the issue: https://drive.google.com/file/d/127Yvp_DdPh9suYXVoiHZwIlEx5yJFwXb/view?usp=sharing

**Comment by Crocoblock** [comment]
@lensbreak 
was fixed in version 2.1.15
please update the plugin
