### ISSUE TITLE
simple bug in new version of jet search

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7261]
Hi,

After updating to the new version, as we can see in [this screenshot](https://prnt.sc/aqhuY6qMeFWg), the text is stuck to the search icon.

Actually, the problem here is that the **right padding** is not applied at all in the input section. **I am experiencing this in RTL.** 

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/ebe9eb07-e32c-4d20-be69-11f7b8d87ab0)

As noted in the screenshot above, changing the amount of right padding makes no difference. It doesn't work at all.

**Comment by Crocoblock** [comment]
was released in 3.2.2
