### ISSUE TITLE
add image ratio in Products Grid widget

### ISSUE THREAD

**Issue by yaron86** [CrocoBlock/suggestions#7263]
in the Products Grid widget, the image size i can control is only these options here: https://prnt.sc/0AKgQgJREOdS
it would be nice if there was some other options to choose like this here:
https://prnt.sc/Hf64-Xh-TNE6

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
