### ISSUE TITLE
 [Jet Woo Builder] Custom product badges with image

### ISSUE THREAD

**Issue by taidang26** [CrocoBlock/suggestions#7264]
Hello dev team,

I'm looking for a solution to create an image above the product. I'm not sure whether to call it badges or watermark. But basically it's an image displayed above and covering the product image and I can insert images to suit the sales campaign. 

I tried searching but there was only [JetWooBuilder Custom Product Badges](https://github.com/UraraReika/jet-woo-builder-custom-product-badges), and it worked really basically just adding Badges and didn't have the customization of adding images and display like I wanted.

I think this feature is very good for e-commerce websites and it is quite popular in Vietnam. So can you add this feature?
Thank you.

Reference site: https://supersports.com.vn/

![image](https://github.com/Crocoblock/suggestions/assets/89138954/0ef3d5a3-18fb-455a-b023-0f4b78cde59e)

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
