### ISSUE TITLE
JetPopup Integration Issue with Gutenberg Blocks in WordPress 6.4

### ISSUE THREAD

**Issue by satomiao** [CrocoBlock/suggestions#7265]
Since the release of WordPress 6.4, JetPopup is unable to attach to any Gutenberg blocks. I submitted a ticket in November to address this issue, but as of now, the bug remains unresolved.

**Comment by Crocoblock** [comment]
Hi @satomiao!

We were aware of this issue and today we released JetPopup 2.0.3, which fixes it
