### ISSUE TITLE
Bug in JetEngine with Bricks Builder

### ISSUE THREAD

**Issue by lagethomas** [CrocoBlock/suggestions#7267]
When I place a jet’s Dynamic Field in Bricks to bring information, this metafield information is not indexed and it does not appear in the editor.
Even though the indexing option is enabled.
When you go to conditions and mark that it is an individual page so that we can view the updated information, it applies and loads the information, but I need to do this action with each new field added.

https://drive.google.com/file/d/1-9TF321meHe7dYGcWWG4gDizPn7gDb-Y/view

**Comment by MjHead** [comment]
Fix will be released with version 3.3.4 in a few days
