### ISSUE TITLE
jetWooBuilder | single images in a quickview popup issue

### ISSUE THREAD

**Issue by yaron86** [CrocoBlock/suggestions#7271]
hello guys
i have a woocommerce website, i have a quickview popup inside the template of the popup i added the single images widget, when i try to style the widget it does not work properly, the issues are:

1. when i set the thumbnail to be vertical like in this image: https://prnt.sc/zEVr2KhDhISI on the frontend it does not work and shows horizontal: https://prnt.sc/uIxNwd0UOs6_
2. when i set a padding to the thumbnail: https://prnt.sc/PSzQ_Iec0Mod it does not work on the frontend: https://prnt.sc/w8ES_L7Fz9r9
3. when i click the thumbnails it does not show in the main image, it just open the image in a fullscreen lightbox: https://prnt.sc/qlCihXNouHm8

**this issues appears only when the single images widget is inside the quickview popup**

**Comment by Crocoblock** [comment]
was released in version 2.1.10
