### ISSUE TITLE
Drag and Drop Sections From the Front End

### ISSUE THREAD

**Issue by Avram-Baskin** [CrocoBlock/suggestions#7285]
This was a request from one of my clients.

This is a specific use case, but I think it has general application on any website.

Their website includes FAQs on several of the pages.  Each FAQ (question and answer) is in a separate section.  The client would like logged-in Administrators to be able to reorder the FAQs from the front end by dragging and dropping a section.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
