### ISSUE TITLE
⚠️FATAL BUG In Jet Engine 3.3.3 - compatibility problem with Jet Form Builder

### ISSUE THREAD

**Issue by brjmichael** [CrocoBlock/suggestions#7287]
I use JetAppointments for a veterinary care service. Customers make appointments using a JetFormBuilder form.

Until the last version, everything was fine, but in this latest update the following problems are occurring:

PROBLEM 1:

> When completing the scheduling form and clicking to send, the APPOINTMENT is created but the EMAIL is not sent, not even through JetAppointment Workflows. And if I take any other action after sending the email, such as redirecting the page, it doesn't work either. The operation is interrupted when sending the email for some unknown reason.

PROBLEM 2:

> I was forced to go back to a stable version of JetEngine, which for my current system, is version 3.2.5.
> 
> In this version (3.2.5), I don't have a problem with sending emails in JetFormBuilder but I have a problem with Listing Grids when used with Listing PopUp.
> 
> I have a listing grid that lists appointments through SQL QUERY. In the list item, I have some information that I preferred to display through a JetPopUp using Listing PopUp and Loading content with Ajax (within the popup) to dynamically load the information. So far so good.
> 
> The problem is when I do some filtering on my Listing Grid and the position of the items changes.
> 
> Example: Item 01 has a dynamic text 'ABC'. When I create a filter looking for another item, and imagine that there is only one item found, because this item is in the same position (01) on the grid, the dynamic information returned is the same as Item 01.
> 
> Therefore, I do not use filtering, even using pagination the data returns correctly, the problem is only when I use filters.
> 
> I imagine you are already aware of this, as this problem does not occur in version 3.3.3 of Jet Engine. I was very happy when this version came out with the correction of this Listing Grid flaw, but as I mentioned previously, the version brought another more serious problem, which affected the sending of emails in JetFormBuilder.
> 
> Ultimately, this is my situation at the moment.
> 
> I appreciate all the support and commitment from the team.

**Comment by Crocoblock** [comment]
Hi @brjmichael!
Problem 1: We are aware of this problem and continue to work on it

Problem 2: We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.

**Comment by Crocoblock** [comment]
fixed in JetAppointment 2.0.6
