### ISSUE TITLE
Bug in the latest JetAppointment 2.0.5 - LISTING GRID BUG

### ISSUE THREAD

**Issue by brjmichael** [CrocoBlock/suggestions#7292]
The **Appointment Query** options are not available in the **Listing Grid** in latest version 2.0.5 of JetAppointments.

**Comment by Crocoblock** [comment]
@brjmichael  Do you mean this tab? 
![image](https://github.com/Crocoblock/suggestions/assets/47778274/f3d53c0e-ce84-4a5a-b1a8-265638a47c49)

If yes - check this option in the general settings 
![image](https://github.com/Crocoblock/suggestions/assets/47778274/3c081ab5-e883-4796-a086-4b62f3892c98)

**Comment by brjmichael** [comment]
Exactly. I was not aware of this legacy option. Thank you very much!

Do you have any updates on the issues in the latest version of JetEngine that affect the Listing Grid?

**Comment by Crocoblock** [comment]
@brjmichael what kind of issues?

**Comment by brjmichael** [comment]
@Crocoblock I detailed some problems with JetEngine this week. #7287

**Comment by Crocoblock** [comment]
Thank you for your response
I'm closing this issue as resolved
