### ISSUE TITLE
Add more than 1 header in the REST API Endpoints

### ISSUE THREAD

**Issue by rodny098** [CrocoBlock/suggestions#7294]
If you select Authorization type/Custom header, there is only option for adding 1, but some apis require more than 1 header.

![image](https://github.com/Crocoblock/suggestions/assets/35738313/b61b9709-fcec-48e5-9801-97b03077d04e)

Thanks

**Comment by Crocoblock** [comment]
HI @rodny098!

Currently, you can use this [hook-filter](https://gist.github.com/Crocoblock/a72d2b200423463c3ff62fd6efd756c6#change-headers-before-the-request-is-made) to add two or more headers

We are also planning to add this feature to the plugin in the future. 
Thanks for your understanding.
