### ISSUE TITLE
Add more custom Jetwoo builder account endpoints

### ISSUE THREAD

**Issue by dariogalleno** [CrocoBlock/suggestions#7295]
Hi there, 
please I need to add more custom account endpoint in order to create templates to assign to in order to display f.e. customer wishlist, customer points and rewards, membership, gift card amounts and other utilities from also from 3rd party plugins thet use shortcodes to display own data.

default endpoints are to limited as customers need much more info on their account..

please it will be a very great and important update and super functionality feature!!
hope it make sense..

many tks in advance for you help and coop.

waiting for yours 
tks 
dario

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/2721, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.

**Comment by dariogalleno** [comment]
Hi @UraraReika<https://github.com/UraraReika> ,
tks for your reply concerning the merge of my previews post to this one.
please should I get in touch with you as I tryied to get some code update but there are some features I'm not able to achieve.?
I was able to add in backend custom endpoint and the capability to select templates for custom endpoint

I’m not able to display custom endpoint in my account page and add it to woocommerce endpoint menu.

Can I send you the files I updated as you can check what I did ? I would like to share with you my work , and hope it should be helpful .


many tks in advance
ciao
Dario






Dario Galleno
+39 339 4095309

Da: Oleksandr Rudyi ***@***.***>
Inviato: lunedì 15 gennaio 2024 08:44
A: Crocoblock/suggestions ***@***.***>
Cc: dariogalleno ***@***.***>; Author ***@***.***>
Oggetto: Re: [Crocoblock/suggestions] Add more custom Jetwoo builder account endpoints (Issue #7295)


I merged this issue with #2721<https://github.com/Crocoblock/suggestions/issues/2721>, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
