### ISSUE TITLE
XSS problem with JetEngine 3.3.3 forms module

### ISSUE THREAD

**Issue by ManuBermudez17** [CrocoBlock/suggestions#7297]
Hello.

First of all, sorry my English, I am writing this with the help of Google Translate.

A few weeks ago, our IT security department gave us a Pentest report. In this report I am notified of an XSS issue.

After many tests, we realized that this problem only occurred on pages where they had inserted forms created from the JetEngine Form module, we did not use JetFormBuilder.

**EXAMPLE**
I create a page, and add a simple form generated from the Jet Engine Form module.
If I visit the page and add JS in the URL, this JS is executed: `https://www.example.com/prueba-jetengine-2hd63hd/?nusyx"><script>alert(1)</script>sekwj=1`

As you can see, the alert that we have entered from the URL opens. 
![photo1_](https://github.com/Crocoblock/suggestions/assets/41609179/0603dddb-12be-4ed6-ac06-fe83ceac1ba5)

Then in the same Form a text appears 
![photo2](https://github.com/Crocoblock/suggestions/assets/41609179/4695356d-29df-48c8-89ce-c41e099fd7e2)

If we view the HTML code, we can see that those URL parameters have been entered in the "action" of the form without cleaning that URL of HTML tags. 
![photo3_](https://github.com/Crocoblock/suggestions/assets/41609179/137b7248-010e-49d3-8622-28f625b34e44)

If we do the same with any other URL that does not contain a jetengine form, it works correctly, we have no XSS problems.

After the tests, the next thing we did was replicate this problem on another local website, in order to certify that it was not only on our website.
We created a new wordpress from scratch on our local machine, with only jetengine installed, and that problem continues to occur. ![photo4](https://github.com/Crocoblock/suggestions/assets/41609179/4c487afc-c0f5-4862-9758-5b79d741735f)

![photo5](https://github.com/Crocoblock/suggestions/assets/41609179/55332d66-6954-4071-9a90-e0b799db9677)

We have been able to find a possible solution, but we do not know if it will be the best option.
 

**POSSIBLE SOLUTION**
`/jet-engine/includes/modules/forms/builder.php`
![photo6](https://github.com/Crocoblock/suggestions/assets/41609179/dc6e6e3c-9431-49fc-849d-92fe0fc79a23)

Pass `$action` through the `esc_url()` function. This way the JS is not executed and the form is sent correctly.

Thank you so much :)

**Comment by MjHead** [comment]
Fixed with 3.3.6. Also please avoid using JetEngine Forms - it marked as legacy very long time age and doesn't gets any support except critical bug fixes

**Comment by ManuBermudez17** [comment]
Thank you so much!!!!
