### ISSUE TITLE
[Jet Booking] Inherit custom field in the Jet Form Builder from main search Booking filter field (for example number of guest)

### ISSUE THREAD

**Issue by alfredo49** [CrocoBlock/suggestions#7299]
Hi!

When you try to search a booking form example in home page, when you submit and select the room, there is a form (jetformbuilder) where the date range is automatically filled (inherit from main booking) but fields as "guest" arent filled automatically , the user has to select it again

It was very interesting in cases with these extra field, they can be automatically filled as date range field.

Regards

**Comment by Nordiccraftmedia** [comment]
you can use dynamic links with args in the results page, and pass the persons number to jetform builder…

**Comment by UraraReika** [comment]
Hello @alfredo49! Thanks for the feedback.

For the booking form, the date field is mandatory and is sufficient to create a new reservation, as for the other fields, although they may affect the booking, they are not necessary, so they are not processed automatically, unlike the date field.

In this situation you can use fields presets settings as @Nordiccraftmedia suggested. Here is the link for more info -  https://jetformbuilder.com/features/preset-settings/. Please [contact](https://support.crocoblock.com/support/home/ ) our support team if you are experiencing difficulties.

Thank you!
