### ISSUE TITLE
jetbooking

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7300]
This option that jetappoinment has is very necessary in jetbooking. Set a limited range from the current date.
![Captura de pantalla 2024-01-15 134940](https://github.com/Crocoblock/suggestions/assets/90837626/2b025d58-3749-4e10-99ec-943c3956f938)

**Comment by JuanCar29** [comment]
When do you have any idea of ​​being able to include this function?

**Comment by UraraReika** [comment]
@JuanCar29 this functionality will be delivered in 3.4.0 release.

**Comment by MjHead** [comment]
Added in 3.4.0
