### ISSUE TITLE
bug in jet woobuilder Custom Quantity Selector > only for one stock products

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7304]
**Describe the bug**

Hi,

if the products stock quantity is 1, the Custom Quantity Selectors will still be empty.

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/a2762ea1-4364-4087-b700-7ae9b2102979)

This problem was fixed in previous versions. But it came back again.

### Also, after updating the Custom Quantity Selector plugin, two simple bugs have appeared.

1- By changing the width of the custom quantity, this option will be displayed in the center. Whereas before it was on the left side. **(According to the screenshot below)**

2- According to the screenshot below, the custom quantity buttons are not located vertically in the center and are actually lower than their former position. 

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/cf6eedaf-f889-47fb-8c40-8fa6a9f0ad26)

**Comment by Crocoblock** [comment]
was released in version 2.1.10
