### ISSUE TITLE
Add switcher for preset settings of the JetFormBuilder

### ISSUE THREAD

**Issue by lugitpl** [CrocoBlock/suggestions#7305]
Please add a switcher in JetFormBuilder settings->options tab (or other place like Form settings - individually for each created form) to let users decide if preset settings of the JetFormBuilder forms will work for guest or only logged users (when it comes to pull some dynamic values). Your support team helped me with the code which I add to my child theme:

```
add_filter(
    'jet-form-builder/preset-sanitize',
    function ( $sanitize, \Jet_Form_Builder\Presets\Sources\Base_Source $source ) {
        if ( is_a( $source, \Jet_Form_Builder\Presets\Sources\Preset_Source_Post::class ) ) {
            return true;
        }

        return $sanitize;
    }, 10, 2
);
```

It would be nicer if this setting we would be able to turn on/off in admin panel of JetFormBuilder instead of adding manually some code to a file.

**Comment by Crocoblock** [comment]
Hi @lugitpl!
We have added this issue to our backlog and this feature will be implemented in 3.3.0

Thank you for your request.
