### ISSUE TITLE
The problem with the new version of WooCommerce with Jet Woobuilder

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#7308]
It seems that in the new version of WooCommerce, changes have been made in the woo notice and js codes of the cart and checkout page. Please check these items.

**Comment by Crocoblock** [comment]
Hi @Joliamendi!

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? 

Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.

**Comment by Joliamendi** [comment]
@UraraReika, @Crocoblock

The new version of WooCommerce comes with changes that made it difficult to customize some sections. See for example the WooCommerce Coupon widget that was customized with jet woobuilder but is now uncontrollable.

![woo coupon](https://github.com/Crocoblock/suggestions/assets/103376243/193a8797-015c-4056-8c69-8ab3484669db)

**Comment by Joliamendi** [comment]
Hi, Is there any update?

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

We have the latest versions of the plugins - https://tppr.me/8xEcZU and styles applying goes well - https://tppr.me/dndeot.

Thank you!
