### ISSUE TITLE
jetformbuilder select field value default

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7309]
In a selection type field that shows the terms of a taxonomy, I am trying to set the default value of a field and it does not take it. I have tried entering a number and it works. I have tried %producto% and '%producto%'

![Captura de pantalla 2024-01-18 180022](https://github.com/Crocoblock/suggestions/assets/90837626/387adc48-e00c-466c-86d1-24d17bdee72d)

**Comment by chamb55** [comment]
"Yes, this is correct, and the JetFormBuilder select field must be improved. I am experiencing this issue, and it's also not showing taxonomies' second level (not displaying child categories). I will report this in a new topic."

**Comment by loucasl** [comment]
> In a selection type field that shows the terms of a taxonomy, I am trying to set the default value of a field and it does not take it. I have tried entering a number and it works. I have tried %producto% and '%producto%'
> 
> 
> 
> ![Captura de pantalla 2024-01-18 180022](https://github.com/Crocoblock/suggestions/assets/90837626/387adc48-e00c-466c-86d1-24d17bdee72d)
> 
> 

Have you tried without the %?

**Comment by Crocoblock** [comment]
Hi @JuanCar29!

`%producto%` is a field in the form, so you need to write `'%producto%'` in the default value (add single quotes at the beginning and end)

**Comment by JuanCar29** [comment]
> Hi @JuanCar29!
> 
> `%producto%` is a field in the form, so you need to write `'%producto%'` in the default value (add single quotes at the beginning and end)

I have tried the 2 options without quotes and with single and double quotes.

**Comment by Crocoblock** [comment]
Hi @JuanCar29! 

sorry for delay

try add dynamic value for your select field where `value to set` enter `'%productos%'`, `apply type` = always, `field` = 'productos' and `operator` = `not empty`

**Comment by JuanCar29** [comment]
Thank you very much, that's how it works.

**Comment by Crocoblock** [comment]
Have a nice day
