### ISSUE TITLE
Add option in editor to set the number of post terms rendered in JetElements Post Widget 

### ISSUE THREAD

**Issue by 319heads** [Crocoblock/suggestions#731]
Currently the post widget only returns one single term with no option in the editor to increase this amount to show more than one tag, category etc. 

The current plural language in the editor "Shows Terms From" already implies this should be returning more than one term since it's not labeled as "Show a Term From". 

Even a hook we could add to our functions.php file to manually change the value would be great. 

As a workaround I've had to edit the **$num** value (increasing it from 1 to 999) in the **render_post_terms()** function located in the plugin's **jet-posts-shortcode.php** file.

**Comment by 319heads** [comment]
Any word if this will be included in an upcoming release? Thanks!

**Comment by kaskad88** [comment]
Added for the next release. Thanks for your report.
