### ISSUE TITLE
Jet WooBuilder - Elementor Upgrade Swiper Libary Support

### ISSUE THREAD

**Issue by hitsgee** [CrocoBlock/suggestions#7311]
**Describe the bug**
Jet WooBuilder is yet to support the Elementor Stable feature "Upgrade Swiper Libary". When this feature is enabled the carousel arrows are broken.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6498, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
