### ISSUE TITLE
JetEngine Listing Grid Issue with displaying related Projects to Services using Query Builder

### ISSUE THREAD

**Issue by bbmaster-spiresw1** [CrocoBlock/suggestions#7313]
Hi all, does anyone know how to display related posts that I have selected with a checkbox from a Glossary? Can’t get it working in Query Builder it just displays anything I have selected rather than the related item to the single post
It’s a custom post type called Projects with a tax called Project Type and then I have Services with Service Type. 
I’m trying to get selected projects to appear with the different services. 
So for example, the service Project Management shows related project management projects that have been selected with a checkbox in the CPT.
If the Project has multiple crossover, ie could appear on PM and Quantity Surveying for example, I would like it to appear on both the Project Management and Quantity Surveying Single Post pages.

Hope that makes sense. 

Any help gratefully received.

Here is the page I'm referring to: https://greenwoodprojects.burntwoodwebdesign.co.uk/services/project-management/

**Comment by Crocoblock** [comment]
Hi @bbmaster-spiresw1!

In your case, the glossary should contain the value of the post ID

if you want to display selected posts from the checkbox field, you need to add a posts query, where in the Post IN field use the "Current meta value" or "Current meta value as a string" macro and enter the name of your meta field 
![image](https://github.com/Crocoblock/suggestions/assets/47778274/2c9a514f-c186-4421-862d-49edef1ad6b4)

if this does not help you, please contact our support team https://crocoblock.com/help-center/ and we will help you
