### ISSUE TITLE
Jet appointment : issue to add manually new appointment

### ISSUE THREAD

**Issue by marieangeline92** [CrocoBlock/suggestions#7316]
**Describe the bug**
When I want to manually add an appointment, if I select a service it shows me all the providers even though they are not associated with the selected service

**To Reproduce**
1. Go to Jet appointment
2. Click on Appointments
3. Click on Add new
4. Select Service
5. Select Provider
6. Complete all fiels compulsory
7. Click on Add new

**Expected behavior**
when I select a service, only the providers who can perform it should be proposed. I shouldn't be able to select all providers.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/Crocoblock/suggestions/assets/153361897/f3b90016-f4c6-46eb-b1a4-587effd8b421">

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.4
 - Browser : chrome
 - Version 119.0.6045.159

**Comment by Crocoblock** [comment]
Hi @marieangeline92 

was fixed and released in jetAppointment 2.1.1
