### ISSUE TITLE
Jet Engine: Dynamic Calendar Widget Pulling Repeater Fields

### ISSUE THREAD

**Issue by e-cubed** [CrocoBlock/suggestions#7317]
We are looking to adding a listing for 'course dates' to a Calendar listing widget. 
The course date field is a repeater field within a post type.

At the moment, it doesn't seem like the Calendar widget works with repeater fields. Please consider adding this feature. This is important for events that does not reoccur but have multiple dates.

**Comment by Propaghandist** [comment]
+1 for this, adding the capability to use a date meta-field within a repeater as the source for the calendar widget would be great!

**Comment by Crocoblock** [comment]
Hi @e-cubed, @Propaghandist!

To solve this problem, you can use the Repeater Query. Just create this query, and select in the calendar. In the General setting select `Date from custom field` and enter the name of your repeater date field 
![image](https://github.com/Crocoblock/suggestions/assets/47778274/770a76b2-d898-40e2-8f53-2d0d774ca533)
 
If this does not help you, please contact our support team https://crocoblock.com/help-center/ and we will help you
