### ISSUE TITLE
BUG: Jet Elements button hover no longer takes on set border radius for button, and defualts to 0px when left blank

### ISSUE THREAD

**Issue by portrayaloflife** [CrocoBlock/suggestions#7318]
**Describe the bug**

Before with Jet Elements buttons when you set the border radius, the hover effect would take on that same radius while leaving the hover border radius blank. After updating, now instead of taking on that same radius it displays a 0px radius. 

So say you had a button set to a 10px border-radius, and left border-radius blank on hover. Now when you hover it will show 0px border-radius, making your button look broken. Or forcing you to update all your buttons on all your sites. 

**To Reproduce**
1. Go to your website and place a Jet Elements Button
2. Click on Set Border-radius to 10px, and leave hover border-radius blank
3. View the front end and see your button and hover over it 

**Expected behavior**

Roll back button behavior for hover radius to take on the main border radius

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by Crocoblock** [comment]
was released in 2.6.16
