### ISSUE TITLE
Product Video in light box

### ISSUE THREAD

**Issue by WildWolf-Ryzen** [CrocoBlock/suggestions#7324]
Please add the video in the lightbox for Gallery Grid element so the user can see all of the photos and the video.
The way it is now the video is not available in the light box and the user must exit the light box to open the video.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
