### ISSUE TITLE
[Bug] Listing Item Settings - Missing Meta Data / Repeater Key as a link source

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#7325]
**Describe the bug**
I'm using a repeater query to generate a listing grid. However, there is no way to use a repeater key value in the Link Source of the Listing Item Settings.

In the Dynamic Field settings, there is an option to use repeater query fields as a source, and in the dynamic image you can insert the repeater field key, but for the Link Source, that option is missing.

**To Reproduce**
1. Create a Repeater and a text and/or post Repeater Field.
2. Edit page and save URL/post link in Repeater Field.
3. Create Listing 
4. Go to Listing Item Settings
5. Go to Listing Settings
6. Select Query Builder or Repeater Field (doesn't matter, it doesn't work in both of them)
7. Enable Make listing item clickable
8. See error

**Expected behavior**
The ability to specify the repeater field as a source, at least when using the listing source "query" or "repeater".

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox v.122.0 
 - Elementor Pro Version 3.18.3
 - JetEngine Version 3.3.4

**Comment by Crocoblock** [comment]
was added in JetEngine 3.5.4
