### ISSUE TITLE
[Bug] Dynamic Field does not Filter the fallback value

### ISSUE THREAD

**Issue by filwi** [CrocoBlock/suggestions#7326]
**Describe the bug**
When I'm using a Filter field output/Get Image by ID in a Dynamic field to get an image from a relation media field, the image is correctly rendered when it exists, but when the fallback image (as specified in the Dynamic field's fallback value) is rendered, it is rendered as an ID, rather than the image.

This suggests that the Filter field output - Get Image by ID does not work on the fallback image.

**To Reproduce**
1. Create a relationship between two CPTs that have media fields in them.
2. Create a media meta field for the relationship.
3. Create a listing with a dynamic field that displays the image from the relationship media field.
4. Create a fallback media field for the dynamic field.
5. Add image to the relationship - image renders correctly.
6. Remove image from relationship - fallback image renders as image ID.
7. See error

**Expected behavior**
That the Filter field output would filter both the specified field and the fallback field the same way.

**Screenshots**
![bild](https://github.com/Crocoblock/suggestions/assets/8066290/43599739-3d9e-40cd-a5f0-f07638eb274a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox v. 122.0 
 - Elementor Pro v. 3.18.3 
 - JetEngine v. 3.3.4

**Comment by kaskad88** [comment]
Hi @filwi 
For your case, it is better to use Dynamic Image widget instead of Dynamic Field widget.
