### ISSUE TITLE
 Issue with Dynamic Visibility in JetEngine #4902

### ISSUE THREAD

**Issue by bobras6** [CrocoBlock/suggestions#7329]
Hello
@Crocoblock 
I hope you're doing well. I just wanted to circle back to an issue I raised earlier regarding Dynamic Visibility in JetEngine (#4902). It seems like it hasn't caught anyone's eye yet.

It's become more apparent to me that this issue has cropped up in the latest version. Any chance someone could take a look and shed some light on what's going on? A bit of guidance or an update would be awesome.

I know you guys are busy, but I think resolving this hiccup would make a lot of users happy.

Thanks for your time and assistance.

Best,

**Comment by bobras6** [comment]
Hello friends
Thanks to you, it was fixed in version 3.3.5
At least say that it is fixed, let's not wait

**Comment by bobras6** [comment]
hi 
@kaskad88 @UraraReika 
The issue in the new version has been resolved, but we are encountering a new problem. The condition for displaying content for users who have purchased the product works correctly. However, when we activate the 'hidden' option, the content becomes hidden for both those who have made purchases and those who haven't
**Please check**

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

We have two heading with conditions - https://tppr.me/RaZ0pF. First heading has this condition - https://tppr.me/fbV3TT, second this - https://tppr.me/q3SFIn. If we open purchased product we will see first heading - https://tppr.me/mXlM4R. If open not purchased product second - https://tppr.me/hO9vIj.

Thank you!
