### ISSUE TITLE
JetSmartFilters - Default Sorting (sort by) for WooCommerce

### ISSUE THREAD

**Issue by dollhauss** [Crocoblock/suggestions#734]
Using JetSmartFilters I am trying to create a default sorting filter on my WooCommerce archive.
Sort by Latest
Sort by Price - Low to High
Sort by Price - High to Low
Sort alphabetically - A-Z
Sort alphabetically - Z-A

Like the standard WooCommerce archive filter.

I believe this is not posssible to implement using JetSmartFilters?

Is it possible to add this option in future or is there a way to make this work?

Thanks.

**Comment by UraraReika** [comment]
I merged this issue with #555, which is on the same subject so we could deal with it more efficiently.
