### ISSUE TITLE
Add the ability to override template in JetBlocks, specially for JetReset

### ISSUE THREAD

**Issue by andikarm** [CrocoBlock/suggestions#7340]
Hy Guys,

I was implementing a reset password flow for my client and noticed that I could not override the template. I tried to copy template from the plugin to my theme like this "/my-themes/jet-blocks/jet-reset/global/" or "/my-themes/jet-blocks/jet-reset/" but it did not work.

For now, so that my goal is achieved then I make edits directly in the plugin, I know this is not right but I have to do it. FYI I have made 4 client websites like this.

Thanks!

**Comment by MjHead** [comment]
Hi, the rewrite works by next scheme, for example

```
jet-blocks/templates/jet-reset/global/lost-password-form.php >>> /my-theme/jet-blocks/jet-reset/global/lost-password-form.php
jet-blocks/templates//jet-nav-menu/global/mobile-trigger.php >>> /my-theme/jet-blocks/jet-nav-menu/global/mobile-trigger.php
jet-blocks/templates/jet-logo/global/index.php >>> /my-theme/jet-blocks/jet-logo/global/index.php
```
