### ISSUE TITLE
JetTabs make it possible to close all items of a collapsible accordion

### ISSUE THREAD

**Issue by Daan001** [CrocoBlock/suggestions#7343]
The classic accordion has an collapsible option. However, when enabling this option, one accordion item will always stay opened. It would be helpfull if there was an extra option to allow users to fully close the accordion to it's initial state.

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by Crocoblock** [comment]
was released in 2.2.3
