### ISSUE TITLE
Dynamic Visibility: Multiple OR/AND scenarios

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#7345]
Hi, I use Dynamic Visibility almost in every website but despite the too many fields that can cover, we cannot create more complex scenarios like the following one.

Show element if condition met:
USER ROLE is Editor
OR 
USER ROLE is Author

AND (this and will be applied to both of the OR scenarios)

metafield exists or any other condition we want.

Now this is impossible and it is a very simple logic.

Thanks.

**Comment by kaskad88** [comment]
@TheBigBanik Hi. Have you tried this solution https://prnt.sc/8RzCw7WQht31 https://prnt.sc/rRv_d7-cnS-- ?

**Comment by TheBigBanik** [comment]
Yes, this solution means that the user is Administrator and Editor at the same time, putting them in the same field works as AND and not OR. Thank you for your time.

**Comment by kaskad88** [comment]
@TheBigBanik No. The `User Role` condition works as OR https://prnt.sc/F6hariDQxFgj https://prnt.sc/U9VNhMWb7IIZ

**Comment by TheBigBanik** [comment]
You are absolutely right. I don't know how I "print" it in my brain that it works as an AND. Thank you for verifying that it is correct.

**Comment by TheBigBanik** [comment]
Don't take this request under consideration, it was my misunderstanding of the functionality.
