### ISSUE TITLE
JetSmartFilters: Deprecation warnings.

### ISSUE THREAD

**Issue by MaxFanov** [CrocoBlock/suggestions#7349]
Upon installing jetSmartFilters the plugin echos deprecation notices

`Deprecated: Creation of dynamic property Jet_Smart_Filters_Service_Filter::$_multilingual is deprecated in /var/www/vhosts/redacted/httpdocs/wp-content/plugins/jet-smart-filters/includes/services/filter.php on line 34

Deprecated: Creation of dynamic property Jet_Smart_Filters_Admin_Dynamic_Query_Base@anonymous::$itemKey is deprecated in /var/www/vhosts/redacted/httpdocs/wp-content/plugins/jet-smart-filters/admin/includes/dynamic-query/manager.php on line 34

Deprecated: Creation of dynamic property Jet_Smart_Filters_Admin_Dynamic_Query_Base@anonymous::$itemLabel is deprecated in /var/www/vhosts/redacted/httpdocs/wp-content/plugins/jet-smart-filters/admin/includes/dynamic-query/manager.php on line 35`

I think this should be taken care of.

Thanks
![image](https://github.com/Crocoblock/suggestions/assets/52853841/43ce3001-1a02-4d41-8b39-e682225b51cc)

**Comment by Crocoblock** [comment]
fixed and released in v3.4.4
