### ISSUE TITLE
Filter Option for user custom fields

### ISSUE THREAD

**Issue by Phirstfilm** [Crocoblock/suggestions#735]
Hi

I have a wordpress user database where people can register via Profile Builder Pro.
In the Profile Builder Pro there are alot of custom fields which are sent into the database of wp users.

Now it would be very helpfull if you could adress these custom fields from the users and show it on the front page with the possibility to filter them.

At the moment the jet smartfilter doesn't allow to pull in this data only manual which make no sense if you have 100 entries.

Example of stored data in wp-users:
**User:** 
Bob
**Sex:**
 Male
**Hobbies:** 
Karate
Diving
Tennis
Cars
Gaming 

No you should be able to make a smart filter which adresses the data from Hobbies without rewriting every single one in the manual mode.

Would that be possible to implement?

Best regards and thx for you so far good plugins!!
David

**Comment by MjHead** [comment]
Can be done with JetSmartFilters and Query Builder
