### ISSUE TITLE
[JetFormBuilder] - Submission error if optional field has no value and a custom server-side callback validation function has been assigned

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#7350]

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by ghost** [comment]
kk, i have a form with the following fields: name (mandatory), email (mandatory), phone number (optional), message (mandatory). i'm using the ajax submit method (i haven't tested it with the classic reload method). I have assigned a custom server side callback validation function to the email field, namely `is_email`, i.e. the wordpress internal function. the problem occurs when an optional field, in this case `phone number`, is validated with a custom server side callback validation function. In my case it is called `edg_is_tel` (it simply checks the value for a preg_match pattern for a phone number) to validate the phone number. But if the field has no value on form submit, which can be the case with an optional field, the submit does not work, because somehow the assigned validation function thinks that no value is an invalid value. i also tried to add the prefix `jet_fb_v_` to the function name and rename my function to `jet_fb_v_edg_is_tel` (because the prefix used to be mandatory and was always appended automatically). but unfortunately that didn't help either
