### ISSUE TITLE
Adding Time Range Along with Booking Jet Booking

### ISSUE THREAD

**Issue by awsj007** [CrocoBlock/suggestions#7354]
Hi, I need to know if is there any possibility of adding time using jet booking because I have a situation where I need to book Hall for 4 Hrs and maybe for the next 4 hrs there is any other booking. Also, users are able to select 1 full day booking or maybe they can select a range of dates for a specific event.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin for the time being. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

I merged this issue with [issue](https://github.com/Crocoblock/suggestions/issues/1597), which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.

Thank you for your understanding.
