### ISSUE TITLE
JetWooBuilder 2.1.10 - Products Grid widget shows products although query builder query does not return products

### ISSUE THREAD

**Issue by xitromedia** [CrocoBlock/suggestions#7355]
**Describe the bug**
When using a JetEngine juery builder query and that query does not return a result, the products grid lists all products using  the number of posts setting from the widget's query settings, which results in showing wrong products although there should none be shown and only a message appear that nothing was found.

After wasting a lot of time (yes, i am angry because of that) i found the place where the code is buggy:

jet-woo-builder/includes/shortcodes/traits/products-shortcode.php > query() line 24

If the query builder query returns an empty result array there, the widget's query will be executed, which is not wanted, i assume.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Crocoblock** [comment]
Hi @xitromedia 

Fixed and released in version 2.1.11
