### ISSUE TITLE
Issue with PayPal gateway on a JetFormBuilder

### ISSUE THREAD

**Issue by redshapeagency** [CrocoBlock/suggestions#7362]
**Describe the bug**
I've created a Form in order to update a meta field inside an user - like adding some "coins" in order to recharge it by the user. It works perfectly and you can chose how many coins you want to put inside your account selecting from 3 options inside a selector block.
Now the issue is when I activate the PayPal Gatway and I try it with the PayPal sandbox everything work and I can see the fake transition on the sand box user and I get the success message but the meta field is unchanged - still the same value. If i deactivate the gateway everything works great and I can get the field update.

**To Reproduce**
1. Create a form with the Paypal gateway
2. Using the form to updating an user meta field (INT)
3. Try the form getting the Success Transition message - but not the changed valued inside the user.
**Expected behavior**
The behavior should be getting the PayPal success message and getting the user meta field update 
**Screenshots**
Not necessary
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 121

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by redshapeagency** [comment]
In fact I've tried the Paypal gatway even on a Subscription Form in order to create a new user, and the issue is the same.
I was wondering if this is connected to the fact I'm using the test mode/sand box in this test and maybe when I'll put the website online I will get everything working.
If anyone can help me, please do it - I need to put this website online in few days and the payment is the last step to get working.
Thanks

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by redshapeagency** [comment]
Hi, Thank you for your reply - but what you mean with "it seems to work correctly"?
Maybe It is just one setting not set correctly because if i exclude the Paypal Gateway everything working great. It is like after the Transiction validation (and it is validated as in the sandbox account i can see the money going down) the form doesn't carry on. I've tried with other type of form (user creation, message via email, etc) and the situation is the same.
Can you just tell me the setting you're using?

**Comment by redshapeagency** [comment]
And maybe someone else has this issue. Sharing a solution or an answer is the best practice in this kind of cases and following the github's collaboration spirit

**Comment by Floydtm** [comment]
I don't deny that you set it up incorrectly. We recreated the case you described above. You can contact support to resolve the issue.

**Comment by redshapeagency** [comment]
You're not getting my point. If we sort out the situation on github It can become something that can be referred to by someone else with the same issue in the future. For sure I've setup something wrong.
If you cannot help me because I've to contact the support Can you post the link to some tutorial or video or something that can help us to understand what is wrong and that can be allow us to sort out the situation?

**Comment by redshapeagency** [comment]
UPDATE: It is the same with the Stripe Gateway. I've got everything working and I've got the success payment on paypal or stripe and the money gotten - I can see the form submission with the success label inside Form Records and I can see the payment success inside the tab Payment. So everything should work in the correct way but the metafield is not updated.

**Comment by redshapeagency** [comment]
Furthermore JetFormBuilder is a free addon - so you don't have a license key for it. How can I contact the support if the ask me the email connected with a license key?

**Comment by Crocoblock** [comment]
hi @redshapeagency 
you may not be using "event". see attachment
![image](https://github.com/Crocoblock/suggestions/assets/47778274/dbc8101e-5660-4bb4-9219-38e19245ec49)

**Comment by redshapeagency** [comment]
> hi @redshapeagency 
> 
> you may not be using "event". see attachment
> 
> ![image](https://github.com/Crocoblock/suggestions/assets/47778274/dbc8101e-5660-4bb4-9219-38e19245ec49)
> 
> 

That was it. Perfect!!! It works. Thank you so much!!!
