### ISSUE TITLE
Move Preloader setting on a listing basis in Jetsmartfilter

### ISSUE THREAD

**Issue by abojmei** [CrocoBlock/suggestions#7375]
Sometimes we use a listing inside another listing. Making the preloader general for the whole site, will show more than the preloader inside the same block as you can check in the screenshot. I would like to suggest adding a preloader setting in the listing grid block setting and the ability to turn it off on a listing basis.

![Screenshot 2024-02-23 at 13 44 19](https://github.com/Crocoblock/suggestions/assets/133910992/8e3739d0-f3ba-4b8d-b2ac-a0a932ecdb4e)

**Comment by Crocoblock** [comment]
fixed and released in v3.4.4
