### ISSUE TITLE
Colorpicker meta field disregarded in gradient background type

### ISSUE THREAD

**Issue by mateitudor** [CrocoBlock/suggestions#7382]
**Describe the bug**
Let me preface that I don't know whether this is an Elementor or Crocoblock or just my bug.
When choosing a dynamic tag for a container gradient background type, it renders fine in the back-end but gets disregarded in the front-end. (Attached pictures.)

The Lazy Load Background Images is not turned on.

**To Reproduce**
1. Create a simple HEX (no alpha) colorpicker meta field for a post or page.
2. Add a page, add a color to that meta field. 
3. Create a listing with a simple container.
4. Add the color to the background or background overlay, as one of the gradient points.
5. Add a random color to the other part of the gradient range.
6. The gradient renders fine on the back end, but gets disregarded in the front-end, falling back (although no fallback set) on the dynamic meta tag, but just as a simple background color, not a gradient.

<img width="449" alt="Screenshot 2024-02-27 at 15 58 01" src="https://github.com/Crocoblock/suggestions/assets/77252839/e067ae00-5682-4cc4-acd8-54c1da0f9fac">

<img width="1051" alt="Screenshot 2024-02-27 at 15 53 11" src="https://github.com/Crocoblock/suggestions/assets/77252839/da24299d-db8c-4b08-95dd-71a8501c47ea">

**Comment by kaskad88** [comment]
Hello @mateitudor 
It is Elementor issue 
Follow for https://github.com/elementor/elementor/issues/10885
