### ISSUE TITLE
[BUG] In Gutenberg in dynamic content the "Query Results Count" has preselected but unfunctional first query

### ISSUE THREAD

**Issue by xokko** [CrocoBlock/suggestions#7384]
**Describe the bug**
In Gutenberg dynamic content you can e.g. insert the "Query Results Count" into a text field. This setting has preselected first query instead of "Select Query...", which is at the bottom! The problem is, if you want to use the first one and don't click on anything in this select field, it will show a query but **it will not work**! You have to click an other one and than the first one again.

**To Reproduce**
1. Have some Queries and a listing
2. Go to block editor, insert your listing, create a paragraph block to show the count of your objects
3. Click on Dynamic Content > Custom Data > Query Results Count
4. See: The first one is selected (do not click it)
5. save the page and test it

**Expected behavior**
The counter should show the correct number but it shows 0.

**Screenshots**
![image](https://github.com/Crocoblock/suggestions/assets/1278415/91d8e4ba-209e-4716-b9b0-d79cf903deb7)

**Desktop (please complete the following information):**
Everywhere

**Additional context**
I think it is the wrong sorting causing the problem. Just put the select option "Select Query..." at the top.
<img width="164" alt="image" src="https://github.com/Crocoblock/suggestions/assets/1278415/aa3b0b40-892b-448a-9011-607c31039e01">

**Comment by xokko** [comment]
I think it is a bigger problem: I have similar issues in other parts or JetEngine.
For example in Dynamic Visibility, if I select Query Results as source, the preselected items do not get applied, even after pressing _Apply_. (See in screenshot)
<img width="664" alt="image" src="https://github.com/Crocoblock/suggestions/assets/1278415/bfce2dd3-298c-487d-8a24-70579ff5f066">

But even worse: after managing to apply the settings (after selecting other items first), it gets the right settings but it results in an error! I even had to delete my page, because **WordPress gave me an error**!
<img width="703" alt="image" src="https://github.com/Crocoblock/suggestions/assets/1278415/8941adce-286d-4e45-90c7-5338bf34497d">

Here is the error from WordPress:
.../jet-engine/includes/modules/dynamic-visibility/inc/conditions/base.php  
Error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in .../jet-engine/includes/modules/dynamic-visibility/inc/conditions/base.php:189

Please fix it fast, I need this function!

**Comment by Crocoblock** [comment]
fixed and released in v3.4.3
