### ISSUE TITLE
Jet appointment / order appointment in calendar view

### ISSUE THREAD

**Issue by marieangeline92** [CrocoBlock/suggestions#7386]
Please, Can you display appointments in order for each calendar day? At the moment, they're displayed out of order. I'd like them to be from the earliest to the latest in each day. 
<img width="1280" alt="Capture d’écran 2024-02-27 à 22 50 37" src="https://github.com/Crocoblock/suggestions/assets/153361897/02c681e2-f0ed-4d47-bb70-05e12c5f78fd">

**Comment by marieangeline92** [comment]
Hello @MjHead, 
I hope you are well. 
Were you able to make any progress on my request? 
Thanks in advance 
Regards,

**Comment by Crocoblock** [comment]
was fixed and released in JetAppointment 2.1.3
