### ISSUE TITLE
 More options for JetBlocks registration plugin to prevent spamming

### ISSUE THREAD

**Issue by Bookyourroom** [Crocoblock/suggestions#739]
Hey, 
I am using the JetBlock registration and login elements for my website. 
Unfortunately, we received a lot of spam emails because bots registered at our platform.
The problem is that I haven't found a way to add functionalities like reCaptcha or any other security measure to the registration element. It would be awesome if you could include something like this in the future. 

Thanks ;)

**Comment by Floydtm** [comment]
@Bookyourroom, hi! https://crocoblock.com/knowledge-base/articles/how-to-add-a-registration-form-to-the-website-captcha-integration/
