### ISSUE TITLE
Ability to block Days or Weekdays on Date Picker form field

### ISSUE THREAD

**Issue by Ravisi** [CrocoBlock/suggestions#7393]
It will be very helpfull if we can select which Weekdays are available in the "Date Picker" form field, for example to only be selectable Mondays and Tuesdays. Also to block specific Dates.

**Comment by UraraReika** [comment]
Hello @Ravisi !

Thanks for the feedback. You can find this in plugin settings - https://tppr.me/MsDKny Booking > Settings > Schedule. You although can find more info here - https://crocoblock.com/knowledge-base/jetbooking/how-to-manage-days-and-weekends-in-booking/.
