### ISSUE TITLE
[jet booking] - woocommerce translation incorrect 

### ISSUE THREAD

**Issue by Fullstak-nl** [CrocoBlock/suggestions#7398]
**Describe the bug**
in `jet-booking/includes/wc-integration/class-wc-product-jet-booking.php` on line 91 the string to translate is `View Details`  where it should be `View details` according to woocommerce translation files.

**To Reproduce**
Use Jet Booking in another language then english

**Expected behavior**
To follow the given translation from woocommerce.

**Comment by breakerh** [comment]
This also applies to `Book now`. Same file, also referring to a translation in woocommerce.. But there's no such string in the woocommerce translation file!

**Comment by Crocoblock** [comment]
was released in v3.3.1
