### ISSUE TITLE
JetSmartFilters - enable dynamic Default Filter Value

### ISSUE THREAD

**Issue by Earl1190** [CrocoBlock/suggestions#7399]
Hi,

in the last release you added the 'Default Filter Value' option to the Smart Filters Settings. Please add the option to set this default value in a dynamic way, maybe with shortcodes generated with the JetEngine Shortcode Generator. In my case i use a Date Period Filter and need 'first day of week' - 'last day of week' as a default value. 
This option whould be great and very useful. 

Many thanks.

**Comment by thedarkonemarc** [comment]
+1

**Comment by whyohssab** [comment]
+1 i neeeeed

**Comment by bee1yash** [comment]
+1

**Comment by bmcontentcreation** [comment]
Yes please add it. Let's say I have a dateperiod filter I want to be able to have today's date pre selected.

**Comment by Earl1190** [comment]
Hi,
Crocoblock added a filter hook for the JetSmartFilters 3.5.4 called 'jet-smart-filters/filters/predefined-value' .

You can set a default dynamic value by using the filter in that way:
`add_filter( "jet-smart-filters/filters/predefined-value", function( $value, $filter_id, $filter_name ) {
if ($filter_id === 131) {
return 28 //or use a php function to get your value// ;
}
return $value;
}, 10, 3 );`

**Comment by bmcontentcreation** [comment]
Thank you! How would I go about having todays date preselected? What parameters do I need to enter?

**Comment by Earl1190** [comment]
@bmcontentcreation : when you open your jetsmartfilter in the wordpress backend, you find the filter_id at the last position of your url, for example: https://your.domain.com/wp-admin/admin.php?page=jet-smart-filters#/846

Then make sure, that you turn "Use Default Filter Value" on. 

In your functions.php or plugin or... add the filter in this way:

`add_filter( "jet-smart-filters/filters/predefined-value", function( $value, $filter_id, $filter_name ) {
		if ($filter_id == 846 /*in my example case*/) {
				$date= date('Y.m.d',strtotime('today'));
				return $date; }
				return $value;
	}, 10, 3 );`

**Comment by bmcontentcreation** [comment]
Wow, ok. I'm not quite comfortable in touching the code. Is it better to create a child theme for this? Or if I were to add it to code snippets I think this is even better. In code snippets what should I do? Enter php code and try to run it? 
Thank you!

**Comment by Earl1190** [comment]
I use it in Code snippets and it works as i expected it. Yes, simply add a PHP snippet, save and activate. Then it should work.

**Comment by bmcontentcreation** [comment]
Ok I will give it a try and come back to you. Thank you so much!

**Comment by bmcontentcreation** [comment]
I got an error. Do I need to add anything else in the php snippet?

**Comment by bmcontentcreation** [comment]
Line 1 unclosed "("

**Comment by Earl1190** [comment]
I updated the snippet. Sorry for the delay. Now there are no errors left.

**Comment by bmcontentcreation** [comment]
Dude! Thank you very very much!!! 
It worked! Really thank you!

**Comment by TheBigBanik** [comment]
Great, though, it doesn't seem to apply on radio filters. Have you tried it on radio or checkbox filters?

**Comment by joehdevwp** [comment]
+1
