### ISSUE TITLE
Jetengine tabs + UX/UI

### ISSUE THREAD

**Issue by alriksson** [Crocoblock/suggestions#74]
Tab view would be very nice to see in jetengine, adding some good UX/UI which is missing today.

> The Tab field is used to group together fields into tabbed sections. This helps tidy up the UI by reducing the need to scroll through fields. When creating a “tab field” it is important to note all fields following the “tab field” (or until another “tab field” is defined) will be grouped together using the “tab field” label as the tab heading.

https://www.advancedcustomfields.com/resources/tab/

**Comment by MjHead** [comment]
Hi @alriksson Thanks for suggestion. We'll planning to completely rebuild JetEngine meta boxes and post types edit UI. With this update we'll add such things as tabs

**Comment by alriksson** [comment]
@MjHead Sounds great, jetengine is lacking too many features and UX/UI to be picked above ACF PRO. Any ETA on this "completely rebuild of jetengine"?
