### ISSUE TITLE
Timber/Twig Views deprecated? or just an after thought?

### ISSUE THREAD

**Issue by MaxFanov** [CrocoBlock/suggestions#7402]
**Describe the bug**
JetEngine provides a performance tab that includes usage of Timber templating language for listing, 
Firstly version 1 should be totally dismissed since it is not maintained anymore by the Timber team, 
Secondly attempting to install version 2 through JetEngine results in a failed ajax which is a result of a critical error.

`Got error 'PHP message: PHP Warning: Undefined variable $sources in /var/www/vhosts/{redacted}/httpdocs/wp-content/plugins/jet-engine/includes/components/timber-views/inc/integration.php on line 84`

**To Reproduce**
1. Go to JetEngine admin menu
2. Click on "Performance" tab
3. Enable "Timber/Twig Views"
4. Click "Install Timber 2.x"

**Expected behavior**
Install Timber as a dependency.

**Additional context**
Is it just something old that was leftover? or it's just an unexpected bug?

**Comment by Floydtm** [comment]
@MaximMitrofanov, hi!! Can you tell me what version of php you are using to get the warning?

**Comment by MaxFanov** [comment]
@Floydtm PHP 8.2.16

**Comment by kaskad88** [comment]
@MaximMitrofanov 
Will be fixed in JetEngine v3.4.2.
Thanks for you report
