### ISSUE TITLE
[Jetsearch] unlimited post number

### ISSUE THREAD

**Issue by hzb666** [CrocoBlock/suggestions#7406]
Now the max post number in one search query is 150, how to set an unlimited post number?

**Comment by Crocoblock** [comment]
Hi @hzb666 !

To solve this problem, you can use the `jet-search/ajax-search/query-args` filter by setting the largest number :
```php
add_filter( 'jet-search/ajax-search/query-args', function($args){
	$args['posts_per_page'] = 999;
	
	return $args;
});
```

but I don't recommend you to use unlimit, in some cases it can lead to a decrease in search speed
