### ISSUE TITLE
jet woobuilder category grid - Dynamic tag for before & after count

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7408]
Hi,

If possible, please add dynamic tag support to the before & after count options. This will allow us to display the counter along with the category title. **For example :** T-shirt (55)

thank you

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Right now you can override widget template and output result you want. Template: `templates/widgets/global/categories-grid/item-count.php`.

Like this:
```
printf(
	'<span class="jet-woo-category-count">%4$s: %2$s %1$s %3$s</span>',
	$category->count,
	esc_html__( $this->get_attr( 'count_before_text' ), 'jet-woo-builder' ),
	esc_html__( $this->get_attr( 'count_after_text' ), 'jet-woo-builder' ),
	$category->name
);
```

Thank you for your understanding.
