### ISSUE TITLE
Feature request : Option to change date format of the data field also in custom post edit in backend (not only frontent)

### ISSUE THREAD

**Issue by gtcrea** [Crocoblock/suggestions#741]
Feature request : Option to change date format of the data field also backend (not only frontent).
In the custom post backend the format of the date field is always the American one. I would like to have the possibility to change the date format (eg from 2017-01-07 to 07-01-2017).

**Comment by omojahed** [comment]
Please, is there a workaround ?

**Comment by lolirado** [comment]
Please do

**Comment by kaskad88** [comment]
Add for the next version( 2.10.3 ). Thanks for your report!
