### ISSUE TITLE
Jetblog - Smart Posts List - Allow choose number of terms

### ISSUE THREAD

**Issue by enricgomez** [CrocoBlock/suggestions#7410]
On the widget Smart Posts List of JetBlog it does not allow to choose more than 1 term to show.
We need to show more terms as it's happening already with Smart Post Tiles.
We don't understand why this is not implemented in Smart Posts Lists. Also would be great to choose what child term to use. Sometimes we need last child term, not all it's parents.

Thanks

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by enricgomez** [comment]
Thanks! You're great.

**Comment by Crocoblock** [comment]
was released in 2.3.7
