### ISSUE TITLE
Jet Woo Product QUERY

### ISSUE THREAD

**Issue by zampnaris** [CrocoBlock/suggestions#7412]
In the default WC product query in the query builder you can not add 2 taxonomies and use the OR relation.( the field does not exists)

You have to use the post query then , post type product and then add the two different taxonomies with the IN relation and then choose Or in the relation field between taxonomies in the end of the page.

Default WC product query is faster than post query.

![image (1)](https://github.com/Crocoblock/suggestions/assets/84714743/f205a91f-650a-48a4-9c86-5f9582933b50)
![image](https://github.com/Crocoblock/suggestions/assets/84714743/5a6d8b88-b5ea-4f7e-acbb-5dafc7c75ead)

**Comment by UraraReika** [comment]
Hello and thank you for feedback! This is known issue and unfortunately, right now WC_Product_Query does not work correct with OR. As soon as this issue will solved we will implement it to Query Builder functionality.

Thank you for your understanding.
