### ISSUE TITLE
Different images for same product

### ISSUE THREAD

**Issue by natxo1** [Crocoblock/suggestions#742]
Do you have any application that allows you to display different product images in the list depending on the category chosen on a page? I have a drawing and it is printed on different products (t-shirt, cup, cap ...). to avoid creating a product for t-shirt, mug ... can I create a product and have the highlighted image show the image that meets a condition? for example, to show the image whose title contains "cup", "t-shirt" ... this way I could create several pages showing the same products but with a different image ... I know it is a bit strange what I ask ... thanks!

**Comment by Floydtm** [comment]
Thank you for contacting us! At the moment, we do not have such functionality in any of our products.
