### ISSUE TITLE
JetEngine Query builder: add price range filter for woocommerce

### ISSUE THREAD

**Issue by bnqtoan** [CrocoBlock/suggestions#7431]
Could we implement a price range filter for WooCommerce in JetEngine query builder? Currently, it only allows filtering by an exact price, which isn't very practical.

![image](https://github.com/Crocoblock/suggestions/assets/2143150/31bf5637-6e76-45e9-9a9b-9d6705e06dab)

**Comment by UraraReika** [comment]
Thanks for the feedback.

`WC_Product_Query` by its structure didn't give us opportunity to this with the help of default parameters, so in this case we need to find out some kind of workaround. 

If you plan to use it with variable products, you should take a note that this type of products are something complicated to filter by price. So the following is not perfect, but show you a way to enable a price range in WC_Product_Query - https://tppr.me/HnwvLZ.

Thank you for your understanding.
