### ISSUE TITLE
Jet Popup / Jet Woo Builder - Add to cart popup

### ISSUE THREAD

**Issue by Fullstak-nl** [CrocoBlock/suggestions#7432]
When you create the add to cart popup, the code doesn't load a product id or information, rendering the popup quite useless imho..
You can't even set `You've succesfully added "product name" to your cart!`.

This can be fixed if it loads the same variables as the quick view event.
```js
  productId: jQuery(n).closest("[data-product_id]").data("product_id"),
  templateId: t,
  isJetWooBuilder: true
```

**Steps to reproduce the behavior:**
1. Add a jet popup and try to build is as a real add-to-cart popup
2. Make sure it's setup like mentioned [here](https://crocoblock.com/knowledge-base/jetwoobuilder/how-to-create-a-purchase-popup-notification/)
3. Publish, load product page for example
4. Click Add to cart
5. See that it's only loading variables like `popup_id`, `popupId`, `page_url` etc.. so it doesn't load the product_id while rendering the popup content.

**Expected/desired behavior**
Pass the needed variables to let us show product information.

**Workaround (for now)**
While I would love that it just worked without any changes i've taken a look at the code and wrote a temporary fix/hack that makes sure you can load product data.

1. Create a new Elementor Code item
2. Paste the following code:
    ```html
    <script defer>
    document.addEventListener('DOMContentLoaded', function() {
	    jQuery(function(){
		    const handleJetPopupWithWCEvents = () => {
                        jQuery(document).off("wc_update_cart added_to_cart").on("wc_update_cart added_to_cart", (t,o,i,n)=> {
		            let a = jQuery(n).closest(".jet-popup");
		            a.length && a.hasClass("quick-view-product") && jQuery(window).trigger({
		                type: "jet-popup-close-trigger",
		                popupData: {
				                popupId: a.attr("id"),
				                constantly: !1
		                }
		            });
		            let d = jQuery(n).closest("[data-purchase-popup-id]");
		            if (d.length) {
		                let t = d.data("purchase-popup-id");
		                t && jQuery(window).trigger({
				    type: "jet-popup-open-trigger",
				    popupData: {
				        popupId: "jet-popup-" + t,
				        productId: jQuery(n).closest("[data-product_id]").data("product_id"),
				        templateId: t,
				        isJetWooBuilder: true
				    }
		                })
		            }
                        })
		    }
		    let i = {
		        "jet-single-images.default": handleJetPopupWithWCEvents,
		        "jet-single-add-to-cart.default": handleJetPopupWithWCEvents,
		        "jet-woo-builder-archive-add-to-cart.default": handleJetPopupWithWCEvents,
		        "jet-single-tabs.default": handleJetPopupWithWCEvents,
		        "jet-woo-products.default": handleJetPopupWithWCEvents,
		        "jet-woo-products-list.default": handleJetPopupWithWCEvents,
		        "jet-woo-categories.default": handleJetPopupWithWCEvents,
		        "jet-cart-table.default": handleJetPopupWithWCEvents,
		        "jet-woo-builder-products-loop.default": handleJetPopupWithWCEvents
		    };
		    jQuery.each(i, function(e, o) {
		        elementorFrontend.hooks.addAction("frontend/element_ready/" + e, o)
		    });
	    });
    });
    </script>
    ```
3. Save.
4. The popup now loads with product data!

ps. at the moment above script won't load any variations. This can be solved by replacing the productId: ... to load `.jQuery('.variation_id').val()`. Even if (for production or to roll out in the plugin) this isn't trustworthy enough it would also be possible to load the variation id (or product id if simple product) with php. If you make sure you run your filter on `jet-popup/ajax-request/get-elementor-content` before the one in `Jet_Woo_Builder_Popup_Package` is executed you could get the latest product in the cart.
```php
$cart = WC()->cart->get_cart();
$item = end($cart);
$product = wc_get_product($item['variation_id'] ?? $item['product_id']);
```

I don't mind to create a simple plugin for it if this will take ages to implement?
I know you guys are busy since i've posted other issues which are open and silent for a while now. ( No bad words, just acknowledging that you guys have a super heavy  load)

**Comment by UraraReika** [comment]
Thanks for the feedback.

Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

In the next release of the plugin you will have simplified way to implement your functionality. We added JS hook for purchase popup data:
```js
window.JetPlugins.hooks.applyFilters( 'jet-woo-builder.purchase-popup.data', {
        popupId: 'jet-popup-' + popupId
}, event, fragments, hash, button )
```
With all `wc_update_cart` and  `added_to_cart` actions parameters. And you can use this hook like this:
```js
window.JetPlugins.hooks.addFilter( "jet-woo-builder.purchase-popup.data", "jetWooBuilder", ( data ) => {
	data.productId = 23;
	data.templateId = 12;
	data.isJetWooBuilder = true;

	return data;
} );
```

Thank you for your understanding.

**Comment by WP-Webdeveloper** [comment]
Hi @UraraReika, how can we use the hooks for better code? Is it possible to use it with the 'custom add to cart' button?

@Fullstak-nl is there a version I could use with the 'customer add to cart' button widget?

**Comment by UraraReika** [comment]
Hello @WP-Webdeveloper! 

You can use hooks as shown in the example above - https://github.com/Crocoblock/suggestions/issues/7432#issuecomment-2024664757. Use child theme to include custom script or third party plugin for example this - https://wordpress.org/plugins/custom-css-js/.

Yes it is possible to use it with custom add to cart button.

**Comment by WP-Webdeveloper** [comment]
Hi @UraraReika,

I'm a coding dummy, my JetPopup ID is 3156 and I want to apply products. So I used tried this code (and variations):

![Image](https://github.com/user-attachments/assets/78105bd4-26f6-4034-afc6-efec212bcf31)

It doesn't pull data like the code from @Fullstak-nl does. I must be doing something wrong... What is it?

**Comment by UraraReika** [comment]
@WP-Webdeveloper 

Please [contact](https://support.crocoblock.com/support/home/ ) our support team so they can help you.

Thank you!

**Comment by WP-Webdeveloper** [comment]
Hi @UraraReika,

Hmm okay, I was hoping to get this done today. Been struggling with it all morning. Not sure why the code isn't working. Thanks for your fast response tho! I hope this will work, I really need it for a project.
