### ISSUE TITLE
JetSmartFilters - Add Search box styling when selected (Elementor)

### ISSUE THREAD

**Issue by Xyala** [CrocoBlock/suggestions#7434]
I'm using Elementor and I wish there would be a way to control the styling of the Input field when such field is selected. (Active)
This would allow me to control the styling of the borders when it's not active

![image](https://github.com/Crocoblock/suggestions/assets/15124463/8c9cc4b4-db37-4775-a51d-fb48fba15a8f)

**Comment by SargasTM** [comment]
done
branch [release/3.5.6](https://github.com/ZemezLab/jet-smart-filters/tree/release/3.5.6)

**Comment by Crocoblock** [comment]
Added in JetSmartFilters 3.5.6 https://imgur.com/ZG5RZ9O 
Please, update
