### ISSUE TITLE
Pre-fill more Woocommerce Checkout fields in JetEngine Forms (with the Checkout Fields Map)

### ISSUE THREAD

**Issue by CINQxo** [CrocoBlock/suggestions#7440]
I have a Jet form with woocommerce check-out. I would love to be able to pre-fill more check-out fields that are already filled out in the jet form with the use of the "Woocommerce Checkout Fields Map", such as date of birth.

![image](https://github.com/Crocoblock/suggestions/assets/165077987/0b7580f2-a510-4f11-b43e-1c568e593479)

**Comment by UraraReika** [comment]
Hello @CINQxo! Thank you for your feedback!

Initially this functionality use default WooCommerce checkout fields. And this list looks like this: 

```php
[
	'billing_first_name',
	'billing_last_name',
	'billing_email',
	'billing_phone',
	'billing_company',
	'billing_country',
	'billing_address_1',
	'billing_address_2',
	'billing_city',
	'billing_state',
	'billing_postcode',
	'shipping_first_name',
	'shipping_last_name',
	'shipping_company',
	'shipping_country',
	'shipping_address_1',
	'shipping_address_2',
	'shipping_city',
	'shipping_state',
	'shipping_postcode',
	'order_comments',
]
```

Field such as date of birth that you mentioned probably custom made field created programmatically or with the help of third party plugins. In this case this field will not be traced automatically and you will not see it in form options list. But you can add this field manually with the help of filter hook `jet-booking/wc-integration/checkout-fields` like this:

```php
      add_filter( 'jet-booking/wc-integration/checkout-fields', function( $fields ) {
              $fields[] = 'custom_field_key';
              return $fields;
      } );
```

If you have some difficulties with this please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
