### ISSUE TITLE
Multiple post types with booking system

### ISSUE THREAD

**Issue by iamingars** [CrocoBlock/suggestions#7442]
Hello best team! I want to make a web page for renting with different categories of rentals: property, tools, etc. I stopped at the question, how is it possible to add a booking for each type of post? Is this not possible. Because in the booking settings I can only link to one post type.
Is it possible to apply bookings to different created posts?

![B-_-Zi_3egaLsaTcaIzSGpH-l-Jln9G0DA](https://github.com/Crocoblock/suggestions/assets/165165108/61271aff-fcba-42c8-9d17-7012dfb968c1)

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/2573, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
