### ISSUE TITLE
Display the price of the day when hover it at calendar

### ISSUE THREAD

**Issue by site-it** [CrocoBlock/suggestions#7444]
Hello, I asked if it already exist that feature that I ll describe. The support team intervened me here.
 I would like to ask you if jetbooking, could display the price of the day when cursor hover the day at calendar.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/5419, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
