### ISSUE TITLE
[BUG] Query Builder > Query Type : REST API Query (Query with Key and Value) 

### ISSUE THREAD

**Issue by tizum** [CrocoBlock/suggestions#7445]
Query Builder > Query Type : REST API Query

The bug occurs when I try to use the Query in my API request, which has 100 results. I'm attempting to fetch the last 100 email campaigns directly from ActiveCampaign.

What I intend to do?

I want to filter by segmentid. When I fill in the Key with "segmentid" and add the value, for instance, "249", it returns 0 results, even though there are 3 records.

I've tried numerous ways to formulate the Query, but none work. I even tried following a tutorial with CCT where I used something like this: [{"field":"segmentid","operator":"=","value":"249","type":"INTEGER"}], but that doesn't work either.

![image](https://github.com/Crocoblock/suggestions/assets/6773491/644d609d-87f8-4643-82f5-216c0ff3c3c6)
![image](https://github.com/Crocoblock/suggestions/assets/6773491/12180c6d-cefb-4e47-8d4f-daf57fd944e2)
![image](https://github.com/Crocoblock/suggestions/assets/6773491/05e2f42e-d3fa-41ae-8f32-6be258b2cd2b)
![image](https://github.com/Crocoblock/suggestions/assets/6773491/6702a555-58ff-489e-b8a3-16e81f31193b)

I'm doing this directly, which will be part of dynamically passing values through smartFilter. I need to put a filter on the listing I'm making with the Table Builder.

Please check and correct the errors.

**Comment by ihslimn** [comment]
You should look into a documentation of the API you are using.
At this time, JetEngine only forms a request and sends it to the API. Then, API returns results, that may be filtered if sent parameters are valid.
There is no filtering of API query happening in Wordpress, the filtering happens on a remote server.

I belive a correct way to query ActiveCampaign API is described here https://developers.activecampaign.com/reference/pagination#filtering
(thus, in your case, it may be 
key: filters[segmentid]
value: 249)
but it would be better to contact their support if you would not succeed in setting it up as you need.

**Comment by tizum** [comment]
You're welcome! I had already discontinued that project.

I believe the error was just in the way I was querying the API. 

For the key, I was using only "segment" instead of "filters[segmentid]".
