### ISSUE TITLE
%wc_get_purchased_products%

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7447]
I'm trying that macro and I'm not getting results. What does it return? I thought that the products purchased by a user ?

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new bug report](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.

**Comment by JuanCar29** [comment]
I make a query in the query builder using the macro and it does not return the expected results. They would be a user's purchases.
![Captura de pantalla 2024-03-30 113556](https://github.com/Crocoblock/suggestions/assets/90837626/36c8c18d-b189-4d60-a2a6-0b32f6f661ba)

**Comment by Crocoblock** [comment]
fixed and released in v3.4.3
