### ISSUE TITLE
Custom meta fields in the woocommerce order confirmation letter.

### ISSUE THREAD

**Issue by Balazs0922** [Crocoblock/suggestions#745]
I've created the custom meta datas with jet engine plugin. I've made a single product page with jetwoo builder. I portayed the meta datas with dynamic field widget. I'd like them to put in the woocommerce order confirmation letter. How can i do this? How can i put the custom meta fields in the email. So they can see in the confirmation letters.

**Comment by Floydtm** [comment]
Thank you for writing to us! Unfortunately, there is no way to implement your request, because it depends not only on us, but also on woocommerce plugin
