### ISSUE TITLE
Add a separate product as a one-click UpSell when Clicking Add-to-Cart

### ISSUE THREAD

**Issue by ingarb** [CrocoBlock/suggestions#7451]
On most of sites we make, we use a separate plugin to make upselling extremely easy. Would be super helpful to have this as functionality inside Crocoblock!

Example:
Customer wants to buy a laptop, and I want to make it super easy to add a travel charger or the most popular carrying case.

If I add separate products under the main product as up-sells, they don't sell nearly as well, as when the customer can make a single click to add it before pressing "Add to cart" on the laptop product-page. In addition the up-sells are presented to the customer right above the "Add to cart" button in a simple way.

This works wonders on the revenue of the Accessories!

![image](https://github.com/Crocoblock/suggestions/assets/10940126/e12a3715-fc0a-4ea9-a716-4bb9fb0c184d)

Possible to get inside Crocoblock?

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
