### ISSUE TITLE
 JetElements For Elementor 2.6.17 crashed my site

### ISSUE THREAD

**Issue by matke-84** [CrocoBlock/suggestions#7460]
As the title says, the last update crashed my site with a fatal error. By going back to version 2.6.16 everything works normally.

**Comment by Jameshallsm** [comment]
Same I have the following error

`Fatal error: Uncaught Error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)
in .../public_html/wp-content/plugins/jet-elements/includes/addons/jet-elements-services.php on line 1500`

**Comment by matke-84** [comment]
Yep. That's the error.

**Comment by Nachtkastje** [comment]
For me it looks like it just straight gave up, deleted files and pushes some cool error codes...

The Error on my side is: 
`[04-Apr-2024 12:25:25 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/home/username/domains/domain.com/public_html/wp-content/plugins/jet-elements/includes/modules/loader.php' (include_path='.:/usr/local/php82/lib/php') in /home/username/domains/domain.com/public_html/wp-content/plugins/jet-elements/jet-elements.php:111`

The jet-elements folder now only has 3 files: packages.json / index.php / jet-elements.php
For me i needed to re-install the entire plugin to get it working.

**Comment by matke-84** [comment]
It is very interesting that no one came forward and at least apologized for the inconvenience. For me, one of the worst supports I've ever encountered. I don't see the purpose of this github. I sent a complaint about a very big problem and no one deigned to respond. The short answer is enough, that's how much decency someone should have. We all paid for these plugins, we didn't get anything for free.

**Comment by Crocoblock** [comment]
Hi @matke-84 @Jameshallsm !
Sorry for delay

Yes, after update you may see this error because you have php 7.4, but yesterday we released a fix for this error, so please update the plugin
