### ISSUE TITLE
JetProductGallery - Set Product Video Position

### ISSUE THREAD

**Issue by luxmediq** [CrocoBlock/suggestions#7465]
Currently the JetProductGallery only allows the positioning of a product video in the first or last position in the thumbnails. This is not optimal, because

- If the video is in the last thumbnail position, the customer will rarely see it if more than 4-6 product images are used.
- If the image is in first position of the thumbnails, the customer is confused because he clicked on a product in the archive and lands on a page that display a video, not the product he clicked on.

It is therefore desirable to be able to select the postion of the product video in the thumbnails. The simplest solution would be to add a third placement option to the two already available:

1. After Product Gallery Images (avaialble as display first)
2. After Product Image (feature request)
3. Before Product Gallery Images (available as display last)

This feature is available in many other premium product gallery plugins (e.g. Product Video Gallery for Woocommerce). Displaying a product video in second or third position is done in many webshops and large platforms like Amazon.

Thank you.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

If you want to point customer about video existence in your product page then you can display video in popup and in this case you will see video icon - https://tppr.me/okj8qV that you can customise. 

Thank you for your understanding.

**Comment by xblomx** [comment]
I would also like this to be possible
