### ISSUE TITLE
JetFormBuilder replaces old images in CPT when uploading new ones

### ISSUE THREAD

**Issue by xand3rrx** [CrocoBlock/suggestions#7466]
**Describe the bug**
I have a CPT with a gallery field and JetFormBuilder form with a media field (with multiple files upload supported) mapped into that gallery field. For some reason, whenever a user updated a post in that CPT from frontend, it will replaces the old uploaded images in gallery field with the new uploaded ones. Is this the normal behavior of JetFormBuilder?

**Expected behavior**
It should keep the old images too and add the new ones

**Comment by Crocoblock** [comment]
Hi @xand3rrx 

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
