### ISSUE TITLE
JetSmartFilters / Automatic reload is not working when the "reload page" method is selected

### ISSUE THREAD

**Issue by EstebanToloza** [CrocoBlock/suggestions#7469]
The automatic reload is not functioning when the "reload page" method is selected, it only works when the apply filter button is added. However, on other sites I have, such button is not necessary.

**Comment by ihslimn** [comment]
You may use this https://gist.github.com/Crocoblock/d02643683afd3d383f274226e83dfa27 for now
Add this JS script and give needed widgets a 'jet-smart-filters-instant-app' class

**Comment by EstebanToloza** [comment]
> You may use this https://gist.github.com/Crocoblock/d02643683afd3d383f274226e83dfa27 for now Add this JS script and give needed widgets a 'jet-smart-filters-instant-app' class

Thank you very much, it works well as a temporary solution. It would be very good if it were included in future updates.

**Comment by Crocoblock** [comment]
Added in JetSmartFilters 3.5.6
