### ISSUE TITLE
Custom field with nested repeater

### ISSUE THREAD

**Issue by davidrockbass** [CrocoBlock/suggestions#7470]
Is there any way to do a custom field with nested like this using jet engine? If there is any custom solution please help me with this.

![404766622_1720259951832561_2861523867427006357_n](https://github.com/Crocoblock/suggestions/assets/11694038/d46b8fea-6e77-409d-91bc-cb5edaf69120)

**Comment by dominikgraef** [comment]
Plus 1

**Comment by Crocoblock** [comment]
Hi
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/784)
