### ISSUE TITLE
JetWoo Builder Attributes widget archive

### ISSUE THREAD

**Issue by iamdanbarrett** [Crocoblock/suggestions#748]
After speaking with your team on live chat and you have looked but it appears it is not yet possible to add attributes into product tiles using the 'Dynamic Terms' widget - it shows them in the editor but on the front end you get a warning saying: 'Dynamic Terms widget allowed only for Posts listing source or in Post context'

**Comment by Floydtm** [comment]
You need to check this option http://prntscr.com/q9xo6q if this method is selected then everything should work
