### ISSUE TITLE
JetSmartFilter - bricks builder query loop - No data was found - translation or custom option

### ISSUE THREAD

**Issue by rousarp** [CrocoBlock/suggestions#7480]
**Describe the bug**
function get_no_results_content() returns an English message without the possibility of translation or connection to the field in the bricks loop for the text or template setting field to return a zero result.

**To Reproduce**

**Expected behavior**
Wire this message to an adjustable field in the bricks loop

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RagnarLodbrok94** [comment]
It is the same issue - https://github.com/Crocoblock/issues-tracker/issues/8707

**Comment by Crocoblock** [comment]
Hi @rousarp 

Now you can use this field https://prnt.sc/ESZ-_YNVi41n
Result https://prnt.sc/oC2xB7LA46TJ 

Was added in JetSmartFilters 3.5.1
