### ISSUE TITLE
Jetengine query builder type post

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7481]
There is an error in the type of post query, when you want to search in a meta with the in the list option and the string has white spaces.
When it is done as SQL by joining the post and postmeta tables, this error does not occur and the results are displayed correctly.
![Captura de pantalla 2024-04-17 122840](https://github.com/Crocoblock/suggestions/assets/90837626/f39f8017-ce29-4562-8642-25a4159d05e4)
![Captura de pantalla 2024-04-17 122904](https://github.com/Crocoblock/suggestions/assets/90837626/b7a0e530-9138-4a30-95fc-296c21f19e4c)

**Comment by LaxusCroco** [comment]
+1
