### ISSUE TITLE
jet engine query builder bug

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7482]
Hi crocoblock team,

According to [this screenshot](https://prnt.sc/Kq_HcoZzfqgZ), I want to display the number of comments of each user in their account. As you can see in the screenshot below, the count are displayed correctly in the query builder.

![Screenshot](https://github.com/Crocoblock/suggestions/assets/77163248/e35d9c44-e4a1-4615-8997-eaf0996c44df)

But after displaying this value using the **query result count** dynamic tag in the user account, the total amount of views of the website will be displayed.

**Comment by Crocoblock** [comment]
Hi @79ho3ein 

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.

**Comment by 79ho3ein** [comment]
Hi @Crocoblock, I apologize for the delay. I will do it now.
