### ISSUE TITLE
JetCompare&Wishlist | Deprecated: htmlspecialchars(): Passing null to parameter #1

### ISSUE THREAD

**Issue by jmandrille** [CrocoBlock/suggestions#7488]
In debug mode it shows the error where the button is placed to compare 

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in ***/public_html/wp-content/plugins/jet-compare-wishlist/includes/widgets/compare/jet-compare-button.php on line 55

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in ***/public_html/wp-content/plugins/jet-compare-wishlist/includes/widgets/compare/jet-compare-button.php on line 58

**My versions:**
Wordpress  6.5.2
Versión de PHP 8.2.18 
WooCommerce 8.6.1 
JetCompare&Wishlist 1.5.6

**Comment by jmandrille** [comment]
In compare widget:

**Deprecated:** htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in ***/public_html/wp-content/plugins/jet-compare-wishlist/includes/widgets/compare/jet-compare-widget.php on line 721, 723, 728, 730, 735)

**Comment by Crocoblock** [comment]
was fixed and released in 1.5.7
