### ISSUE TITLE
jet woo builder pagination seo issues

### ISSUE THREAD

**Issue by Salimoh** [CrocoBlock/suggestions#7492]
**Describe the bug**

Paginated urls are loaded using Ajax. Google recommend placing html <a> links pointing to paginated urls for better crawling and indexing.  Google deprecated use of rel=next prev. 

Also, paginated urls must not be canonicalise to first page. Each page must be indexable

This is one of the biggest issues of jet woobuilder creating on ecommerce sites that use it.

Please fix it.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) or [bug reports](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.
