### ISSUE TITLE
Validation for glossary entries

### ISSUE THREAD

**Issue by randywombat** [CrocoBlock/suggestions#7496]
When adding items to a JetEngine glossary, you can type anything you want in the 'Name/ID' field. But later on, if you have included anything other than alphanumerics and dashes, this generates errors with using smart filters, and probably elsewhere too. So it would be good to have some validation for the user at the point of adding the item, to make sure disallowed characters are actually disallowed. (Or at least a tooltip!)

**Comment by Crocoblock** [comment]
Hi @randywombat 

We plan to add this in v3.5.0, like this https://prnt.sc/PJjiyrBdraSw
Thank you for requerst!
