### ISSUE TITLE
 JetListing WC3 Validation Errors - jet-listing

### ISSUE THREAD

**Issue by reachdigitalaus** [Crocoblock/suggestions#750]
Hi, We have created some listing and all working great.
However, if we add a HTML tag, like H4 in the widget to the title, we get an error as a DIV is generated inside the <h4>, this happens to any other tag you pick.

Example:

<h4 class="jet-listing jet-listing-dynamic-field display-multiline"><div class="jet-listing-dynamic-field__content">My title</div></h4>	

The above HTML code produces validation errors.

**Comment by kaskad88** [comment]
Fix for the next version (2.2.0).
Thanks for your report!
