### ISSUE TITLE
JetForm - Stripe Subscription Integration

### ISSUE THREAD

**Issue by chrispx001** [CrocoBlock/suggestions#7506]
Hi, Could you please consider introducing "Stripe Subscriptions" functionality into JetForms as a Pro add on and alternative to PayPal.

I have recently starting implementing Paypal subscriptions. We don't have any customers who use PayPal anymore. (10 years ago we had many) but the experience for the business and for the end custom is a little old fashioned and PayPal is now much less popular than it used to be.

Stripe offers a modern solution, faster setup for businesses and many more flexible tools and controls and supports fantastic subscription options. It would be a far better asset to corocblock than PayPal. I have looked into building something using Stripe and Zapier but it will take a while and I think most people would prefer to use Stripe over PayPal if given the choice.

Here is the Stripe API Ref.
https://docs.stripe.com/api/subscriptions

Thank you.

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on it https://github.com/Crocoblock/suggestions/issues/6293
