### ISSUE TITLE
Jet Engine Slider Arrows - How to show all the time 

### ISSUE THREAD

**Issue by debihazelden** [Crocoblock/suggestions#751]
I'm using Jet Engine and the slider. Is there any way to keep the arrows on the slider even when there are only enough elements to fill the slider?

e.g. I have it set to show 3 and at the moment I only have 3 items in there. Is there script I can add to show the arrows?

My problem is that I have a slider that has 3 showing but 1 is pushed off the screen so I need the slider. Image attached. When there are only 3 items in the slider the arrows don't show. When there are 4 items they show.

Is there any script I can add to show the arrows all the time even when only 3 elements in there? The screenshot below has arrows because there are 4 elements in the slider. 

Many thanks

<img width="1444" alt="Screen Shot 2019-12-12 at 8 52 56 am" src="https://user-images.githubusercontent.com/54105268/70697569-ab815d00-1cbd-11ea-91af-563767a28933.png">

**Comment by Floydtm** [comment]
@debihazelden, hi! Thanks for your report! At the moment, we can not say that this is a bug. Everything is working correctly. I think for this you need a developer who will do it for you.
