### ISSUE TITLE
[Listing Grid] I can't find Terms Query or Posts Query in listing grid

### ISSUE THREAD

**Issue by doanthaoan** [CrocoBlock/suggestions#7513]
**Describe the bug**

**To Reproduce**
1. Add a listing grid widget
2. Click on 'added listing grid above'
3. On the left panel for listing grid widget option
4. Can't find the Terms Query or Posts Query anymore (only can see the Custom Query)

**Expected behavior**
Can use the Terms Query, Posts Query as before.

**Screenshots**
![image](https://github.com/Crocoblock/suggestions/assets/6356542/6056a327-0ca7-4461-8b60-ae19c104ff7f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome Version 
 - Version 124.0.6367.119 (Official Build) (64-bit)

**Additional context**
I'm using the JetEngine version Version 3.4.4 & Jet Element for Elementor Version 2.6.17.1

Regards,

An Doan

**Comment by Lonsdale201** [comment]
Jetengine - > query builder

**Comment by doanthaoan** [comment]
Hi Lonsdale201, 

I created a custom query using Query Builder, but when I use it on my listing grid with pagination widget, it causes me a bug that the pagination disappeared after clicked on the page.

Have you ever run into this kind of bug or have any information about it?

**Comment by doanthaoan** [comment]
Ah, I see the terms and posts query is legacy now and I can open it again by the link there.
