### ISSUE TITLE
Change placeholder text on supported features when creating custom post type

### ISSUE THREAD

**Issue by Wibbskiii** [CrocoBlock/suggestions#7527]
When you create a custom post type you sometimes uses Wordpress standard fields lite Title or editor. When you do that, it would be good to be able to change the placeholder text to mimic and help the user understand what to write in the field. 

For example:
Here have I made a custom post type for Stores (Butik), I want to use the Title field for the Store namn. Now it only says "Add title", look here https://prnt.sc/JqXdTqCSCaod. Here I want to change to "Enter the name of the store"

**Comment by kaskad88** [comment]
Hello @Wibbskiii 
You can use the `enter_title_here ` filter to change the placeholder text.
https://weplugins.com/wordpress/how-to-use-enter_title_here-filter-in-wordpress/
