### ISSUE TITLE
Add an option for front-end user submitted events.

### ISSUE THREAD

**Issue by asagiannini** [Crocoblock/suggestions#753]
The dynamic calendar is a powerful tool, but it would be more useable if it allowed front end users to create their own events for review via a form.

**Comment by Digital03** [comment]
You can do it activating FORMS in your JetEngine.

**Comment by asagiannini** [comment]
> You can do it activating FORMS in your JetEngine.

Would this mean once a user submitted the form and I approved it, it could be automatically added to directory and/or calendar?

**Comment by MjHead** [comment]
> > You can do it activating FORMS in your JetEngine.
> 
> Would this mean once a user submitted the form and I approved it, it could be automatically added to directory and/or calendar?

Yes, you can create a form with Insert Post notification, set inserted post status to Draft. Then, when you manually switch status of created post to Publish it will appear in required Listing

**Comment by asagiannini** [comment]
Dang, very slick. Thanks so much for the quick response time and help.
