### ISSUE TITLE
Apply existing WooCommerce shipping options to JetBooking products.

### ISSUE THREAD

**Issue by santonax** [CrocoBlock/suggestions#7531]
JetBooking products seem to be only "virtual" at the moment, so any existing WooCommerce shipping options are not applied at checkout. 

It would be good to have this feature added to the JetBooking plugin in the future, if possible, particularly for particular types of equipment. 

For example, imagine a shop selling power tools that wants to offer a rental option on their products. With this feature added, the customers of this shop would be able to choose their tool, select the hire/rental period and when the tool is added to checkout they can choose whether they want to pick up from the store or select if they want the tools delivered to their home or workshop address.

This would work for a variety of different types of equipment, from smaller to bigger (even cars for example!). 

Hope this makes sense and to see this feature added in the future! :)

**Comment by UraraReika** [comment]
Hello @Sara-MilkandTweed please take a look at this similar issue - https://github.com/Crocoblock/suggestions/issues/7404 you anc find solution in it if you need it right now. 

In the next release of our plugin there will be and option to control this product state.

**Comment by Crocoblock** [comment]
was released in 3.4.1

**Comment by santonax** [comment]
Hello! with regards to the above release, thanks for adding that in!

I just tested it on my site, and by doing that I realised that it was not exactly what I meant (sorry maybe I didn't explain very well in the first comment). 

JetBooking products were already behaving as "virtual" (for me at least) before the update because when placing a booking and going to checkout to pay/book the item, I did not get any of the shipping options already set in my WooCommerce store. 
So for my type of product, which is a equipment rental, we need to give people the option to have it shipped to their desired location. 

JetBooking currently doesn't show any delivery options and particularly for equipment rental (big or small items) it would be good to give customers option to have the item delivered to them. 

Would it be possible to integrate existing WooCommerce shipping rules/settings with JetBooking and JetBooking Products? 

If there's already an easy way to do this please let me know - if not and possible to do I'd would be a great feature to have!

Thank you! :)

**Comment by UraraReika** [comment]
Hello @santonax !

In release 3.4.1 we added this option - https://tppr.me/cSh37P, so you can control whatever you product virtual or not and to have opportunity set shipping data in checkout page.

If you create your booking product before this update all your product will be marcked as virtual like in screenshot this made for backwards compatibility purposes. And when you book some item you will not see any shipping info no in the cart - https://tppr.me/7Wo9QD nither in checkout -https://tppr.me/kwnkfm.

But if you uncheck this option - https://tppr.me/Cs2R0k and update booking product. Then make some booking in the cart page you will see some shipping info - https://tppr.me/IwcnIW as well as possibility to edit it. And in the checkout page you will see shipping form - https://tppr.me/QfAYLs.

**Comment by santonax** [comment]
Thanks for the reply @UraraReika! I'll try again! 🤞🏻☺️
