### ISSUE TITLE
Listing grid - 2 Order by diferent meta field concadenated or a method to group post

### ISSUE THREAD

**Issue by Digital03** [Crocoblock/suggestions#754]
Hi.

I have 2 fields, one for Day and other for Time. I want to order by time, and later group by day with another order to display posts in correct order. But when i do it on  second order not work.

If i do 2 order querys with different term, name, date, it works, but if 2 order query with meta fields, second order not apply.

I wrote to your support helpdesk and they said to suggest this implementation here.

**Comment by MjHead** [comment]
@Digital03 You need to use Meta Clause option for Order By control. But first you need to add required meta clauses to query. You can do this in the next way - add 2 posts query items, each of Meta Query type (separate clauses for date and time) - http://prntscr.com/qadwof. Then add 2 items for Order By parameters. For each item select Meta Clause as Order By value and set perviously created meta clauses name into "Meta clause to order" control - http://prntscr.com/qadyel

**Comment by Digital03** [comment]
Okay Okay... but more simply.

Meta query with meta clause, to query only the desired days and get small query, in my case from today to...
Order by meta query Hour.
Order by meta clause from the meta query.

It works and the all day events (with blank meta field time) shows first.  

Perfect :D

**Comment by Digital03** [comment]
No, i was wrong... when add more demo posts to develop, my solution not work...

 i make how you says and it works.

**Comment by mattkub** [comment]
Hello @MjHead i got similar issue. I made "promoted posts" through its own taxonomy. I would like to make an order to always show promoted posts first (posts that has checked in taxonomy "promoted") and then order posts by relevance.
Could you help me out with this kind of issue?
