### ISSUE TITLE
two simple issue in jet woobuilder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7540]
Hi,

I have two small problems with RTL that I wanted to point out. Although they can be easily solved with css...

1- In the product grid widget, the percentage is on the right side of the number. While it should be on the left side.

![Percentage](https://github.com/Crocoblock/suggestions/assets/77163248/b756d963-99df-4c0e-be4b-0f1c79e93852)

2- On the checkout page, there is a lot of space between the text and the checkbox.

![1](https://github.com/Crocoblock/suggestions/assets/77163248/1a75e022-40de-4c14-bea3-268af089b083)

thank you

**Comment by UraraReika** [comment]
1 - fixed and will be available in the next 2.1.13 release. 
2 - we do not plan to add options that will control this gap and keep default WC styles.

Thank you for understanding

**Comment by Crocoblock** [comment]
was released in JetWooBuilder 2.1.13

**Comment by mor832** [comment]
Hey Crocoblock,
You fixed it for Arabic but for Hebrew which is also RTL
the percentage sign needs to be on the right

Since I found this thread I reverted to a version before 2.1.13 and it works fine

**Comment by Crocoblock** [comment]
Hi @mor832 
Please create a separate issue for this
