### ISSUE TITLE
BUG : jet form builder eye icon position in RTL

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7546]
Hi crocoblock team,

In RTL websites, the position of the eye icon is not in the right place. In fact, the eye icon and the password are placed on top of each other.

![bug](https://github.com/Crocoblock/suggestions/assets/77163248/c6cbae7a-9790-4c42-90d0-b4009b2a548d)

**Comment by Crocoblock** [comment]
was fixed in JetFormBuilder 3.4.1
