### ISSUE TITLE
Adding the option to display YouTube SHORTS videos in the "Video Player" Widget

### ISSUE THREAD

**Issue by pintolog** [CrocoBlock/suggestions#7547]
Hi,
Please add the option to display YouTube SHORTS videos in the "Video Player" Widget & make it dynamic with CPT & CCT.
Right now the options for video type are only:
• YouTube
• Vimeo
• Self Hosted
<img width="293" alt="image" src="https://github.com/Crocoblock/suggestions/assets/7497319/dc036e35-de9e-4abf-9c95-646455bc5372">

Thanks,
Gabriel.

**Comment by bazilik1095** [comment]
This has been added to the plugin. After that, there will be a testing phase. And will be released later.

**Comment by Crocoblock** [comment]
released in JetElements 2.7.0
