### ISSUE TITLE
Issue with using query builder with bricksbuilder query loop upon upgrading to jet engine 3.4.5 & 3.4.6

### ISSUE THREAD

**Issue by khalidouhdane** [CrocoBlock/suggestions#7549]
I have a products query loop in bricksbuilder popup, built using jet engine query builder with bricksbuilder query loop, working perfectly on version 3.4.4, issue happens upon upgrading to version 3.4.5

1. Create products query in jet engine query builder
2. Create brickbuilder popup and create a product card query loop (bricksbuilder) using some elemets, assign the query you built using jet engine to it.
3. create a button that open the popup.
4. Open the popup and you'll see that featured images are not rendering for example, title is showing up in my case

**Expected behavior**
Normally All elements should show.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - Version: 125.0.6422.113 (Official Build) (64-bit)

Important note: Downgrading to jet engine 3.4.4 solves the issue.

**Comment by Crocoblock** [comment]
Hi @khalidxhunters 
for now our dynamic elements don't work in Bricks Ajax popup, so just use standard elements from Bricks Builder

**Comment by khalidouhdane** [comment]
> Hi @khalidxhunters for now our dynamic elements don't work in Bricks Ajax popup, so just use standard elements from Bricks Builder

Hi @Crocoblock, I'm not using jet engine dynamic elements, I'm using native bricks image element with native featured image dynamic tag, and as I mentioned problem is solved upon dowgrading, so I don't think it's a popup support issue, something just went wrong from 3.4.4 to 3.4.5.

**Comment by khalidouhdane** [comment]
I've tested again with 3.4.6 and the issue now is even bigger, all listings now are barely showing any meta data we've setup on the products using jet engine, and then listed them using {je_meta_key}.

I'm using a WC Product Query with bricksbuilder query loop.


A picture of the products from the category page using: 3.4.4
![image](https://github.com/Crocoblock/suggestions/assets/45321468/edd492f8-127f-4fce-98c7-afd657f6d972)
Same from upgrading to 3.4.6:
![image](https://github.com/Crocoblock/suggestions/assets/45321468/ee1af807-95fd-4420-b194-ab4c5f163e00)

**Comment by khalidouhdane** [comment]
using listing grid widget:
![image](https://github.com/Crocoblock/suggestions/assets/45321468/f9c783c8-fc5c-4abf-b8b1-78520f02cf02)
![image](https://github.com/Crocoblock/suggestions/assets/45321468/626d90ad-d1e8-4b14-b90b-921a5c781965)

**Comment by khalidouhdane** [comment]
is the bricks builder native query loop no longer supported?

**Comment by khalidouhdane** [comment]
After futher invistigation, seems that the issue is that certain bricksbuilder dynamic tags aren't working inside the query loop with jet engine query builder, post id for example is not working now, and meta data is showing now because we had setup a condition on it based on a bricks builder dynamic tag (and since that isn't working, it wasn't showing). now that we removed the condition it's showing. but some Dynamic tags from bricks aren't working anymore, post id.. certain woo tags...

Post ID seems to not work only on a custom attribute in which we have normaly a funtion there that takes the post Id, but with jet engine 3.4.6, not even the post ID works there, on the other hand post slug title are working there...

They only work on listing grid by jet engine & overall in jet engine 3.4.4.

I deactivated all the plugins to make sure this isn't because of another plugin (although the fact that the problem is solved upon downgrading would suggest that is strictly because of the upgrade).

**Comment by Crocoblock** [comment]
Hi @khalidxhunters 
Sorry for delay and misunderstanding

i tried to reproduce your issue, but in my case, after 3.4.5 update i dont get image in the Image element only

please contact our support team https://crocoblock.com/help-center, describe you issue with more details and provide access to your site and we will help you

Thank you for your understanding

**Comment by Crocoblock** [comment]
Hi @khalidxhunters 

this issue is fixed in JetEngine 3.5.3. Pls update the plugin, if you have this problem, please contact our support team https://crocoblock.com/help-center/
