### ISSUE TITLE
I only miss a feature in JetEngine ( dynamic conditions for sections/columns/widgets )

### ISSUE THREAD

**Issue by Digital03** [Crocoblock/suggestions#755]
Hi.

I love jetengine and this posibilities, but i miss a feature to be perfect content creator for wordpress, conditions to show.

Some examples of free plugin that do this:
https://wordpress.org/plugins/dynamicconditions/
https://wordpress.org/plugins/dynamic-visibility-for-elementor/

**Comment by dantedanieltesta** [comment]
Its very important!!  I Need this feature!

**Comment by Labona** [comment]
So this is not yet possible? huh, would be super needed!

**Comment by designworksinteractive** [comment]
Struggling with this as well atm conditional logic is critical for fields

**Comment by azimdotnet** [comment]
An example of a dynamic condition is well implemented by dynamic.ooo.
https://www.dynamic.ooo/widget/dynamic-visibility-for-elementor/

**Comment by Weetab1x** [comment]
Yes, this would be great. Using another plugin now, but would prefer if this was in Jetengine.

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0
