### ISSUE TITLE
creation of listing grid repeater for the image comparison widget

### ISSUE THREAD

**Issue by kevinv217** [CrocoBlock/suggestions#7555]
Basically I am trying to create a list of repeater grids for the image comparison widget, but I can't find a way to call those created fields and enter it in the normal way, help?

![Imagen de WhatsApp 2024-06-07 a las 08 37 17_ad7746bd](https://github.com/Crocoblock/suggestions/assets/67294341/39b951b3-d45c-4125-b6f9-d4a303b2a63d)
![Imagen de WhatsApp 2024-06-07 a las 08 37 18_dc40746c](https://github.com/Crocoblock/suggestions/assets/67294341/24ce716f-a7a8-4a64-8a5b-cb58cbbd7d42)

**Comment by Crocoblock** [comment]
Hi @kevinv217 

First, create repeater query
Then select this query [here](https://github.com/Crocoblock/suggestions/assets/47778274/544929df-b052-40f7-be86-c7d981caa806), or if you use Image Comparison in the Listing Grid use this query [here](https://github.com/Crocoblock/suggestions/assets/47778274/f03c9929-a28e-4d6d-99c1-8657152c638c)

Then in the widget use Dynamic Tag - [Current Object Image Field](https://github.com/Crocoblock/suggestions/assets/47778274/2652ab66-8d42-472f-aebb-a6b1343c188f) and select (or write) the meta field from the repeater
