### ISSUE TITLE
JetSmartFilter search by author stopped working

### ISSUE THREAD

**Issue by hericjr** [CrocoBlock/suggestions#7556]
After the latest updates to Jet Smart Filter and Jet Engine, the author filtering function has stopped working when using the '[Author & post type filter](https://crocoblock.com/knowledge-base/jetsmartfilters/jetsmartfilters-devtools-author-and-post-type-filter-addon/)' add-on.

Error:
When filtering by author, the option selected in the filter does not load, neither in AJAX nor on a reloaded page.

The error happens on any device, whether desktop or mobile.

JetEngine Version 3.4.6
JetSmartFilter version 3.4.5

With Jet Smart Filter version 3.3.2 and the latest version of JetEngine, I can still filter by author, so I believe the error is in the recent JetSmartFilter or the 'Author & post type filter' add-on needs to be updated

This fix would be very useful to keep plugins updated.

Thanks in advance.

**Comment by Crocoblock** [comment]
Hi @hericjr 

After 3.3.0 you don't need this addon, you can use **Plain Query**

Firstly, go to WordPress Dashboard > JetEngine > Query Builder > Add New and add a new query of the type "Users Query". We will use this query to generate a list of authors: https://prnt.sc/FDkhfRLLh9oA

Then, create a filter in JetSmartFilters. You can use Select/Radio/Checkbox filter type. Choose "JetEngine Query Builder" as the Data Source: https://prnt.sc/nMUnPh8wFEo9

You can find more information about this data source here: https://crocoblock.com/knowledge-base/features/filters-data-source-overview/#jetengine-query-builder-source

Apply the "Plain Query Variable" dynamic tag to the Query Variable field and insert a random string, such as 'author_ids': https://prnt.sc/UJCsPtOLB7VF
Save the filter. 

Create a Posts Query in JetEngine > Query Builder and follow this configuration: 
https://prnt.sc/NLVfY4o7zpP4
https://prnt.sc/pJVRhNHyiv2Y

Apply the query to the Listing Grid widget that displays your posts and display the filter https://prnt.sc/tWbCvlkOYfWk

**Comment by hericjr** [comment]
Hi @Crocoblock,

I followed the steps and it worked. Thank you for the feedback.

There were a lot of turns to make a simple author filter, I think it could already be native to JetSmartFilter.

I think it could be a Wordpress query issue, but this solution has already helped me.

Thank you once again.

**Comment by Seventhose** [comment]
The problem with this query is that if you have too many authors it will blow up your website.

With 4000 authors I can't even load the page without the browser to crash.
