### ISSUE TITLE
The possibility of creating a wallet using jet engine

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#7558]
Hi crocoblock team,

Is it possible to create a wallet for WooCommerce using jet engine? It seems possible, but if not, will it be difficult to make it possible in future updates?

**Comment by J-WPD** [comment]
This would be incredibly useful! Being able to build a multivendor platform with JetEngine would be a game changer, most of the things are already there.

**Comment by 79ho3ein** [comment]
+1

**Comment by MjHead** [comment]
sorry, it's to specific functionality to implement it in JetEngine

**Comment by J-WPD** [comment]
If not a wallet then a way for users to get paid out individually with the multivendor marketplaces you have set up? The demo sites you have are nice, but having everything go into the owners account and having to pay out each user individually is not particularly useful.
