### ISSUE TITLE
BUG : jet smart filters and elementor Optimized Control Loading

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7559]
Hi crocoblock team, @Floydtm and @SargasTM

If the **Optimized Control Loading** option is enabled in the Elementor settings, the position control does not work in the filter counter settings.
**Please note that the Optimized Control Loading option will be activated by default on new sites in the next version of Elementor.**

- As a small matter in this counter section, if we select space between in the position control, the **Horizontal Offset** control will not be usable. Therefore, if we choose space between, it is better to hide the Horizontal Offset control.

![1](https://github.com/Crocoblock/suggestions/assets/77163248/f6dd3488-357a-48f8-8d0d-a78e2f658b30)

thank you

**Comment by Joliamendi** [comment]
Hi @Crocoblock, Is there any news about this? I'm still facing it in the new version.

**Comment by Crocoblock** [comment]
Fixed in JetSmartFilters 3.5.6 
Please, update
