### ISSUE TITLE
Product Grid Widget: Allow Customisation of the "Out of Stock" badge (instead of just the "Sale" badge)

### ISSUE THREAD

**Issue by ricardoaraujo330** [CrocoBlock/suggestions#7561]
Hi Crocoblock team!

I think title says it all. Product Grid Widget only allows customizing the sale badge. Since the "out of stock" badge is also very common and comes by default with many themes, it would be awesome is your widget also allows customizing the out of stock badge along with the sale badge. Please consider it. Thank you!

**Comment by UraraReika** [comment]
Hello @ricardoaraujo330 !

If you enable stock status in product grid widget - https://tppr.me/PFieXN you will be able to change status labels as well as style it - https://tppr.me/a3hue7. So about what kind of customisation you mean? In case something else then this in that case we do not plan to introduce some new controls to our widget for now.

Thank you for your understanding.

**Comment by ricardoaraujo330** [comment]
Hi @UraraReika!

Thank you for your feedback, this is nice to know, in fact i've missed that setting, must confess.

In that case, I will rephrase my question, if I may, in this topic.

The sale badge appears in the upper right corner, above the product image. I would like the stock statuses to appear in the same position. Additionally, I do not want the "in stock" status to be shown (to avoid conflicts with items on sale), I only want the backorder and out of stock statuses to be visible.

I hope this can be possible in a future version.

Thank you!

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks.

I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such custom cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.
