### ISSUE TITLE
[Feature Request] Discount on different items in WooCommerce shopping cart

### ISSUE THREAD

**Issue by pgm-stevaelb** [CrocoBlock/suggestions#7562]
We are looking the possibility to add discounts to the shopping cart on different items.

**Example:** A discount when you buy 3 items in our shop. The discount would automatically apply to the lowest priced item (or having the possibility to make it also apply to the total price) in the shopping cart.
So only when at least three (or an X amount) items are in the cart (could be different items) and then apply eg 20% to the lowest priced item or the full cart.

This could be addition to the JetWooBuilder or some dynamic way of adding a discount to the shopping cart page.

**Comment by Lonsdale201** [comment]
Jetwoobuilder is a plugin that helps you from the design side. I think it's very much out of the scope of what jetwoobuilder is for. There are lots of plugins that you can use to do what you want, and most of them are free.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
