### ISSUE TITLE
Set 100% Opacity for Thumbnails Pagination in JetProduct Gallery Slider

### ISSUE THREAD

**Issue by ricardoaraujo330** [CrocoBlock/suggestions#7568]
**Product:** JetProduct Gallery

**Feature Description:**
Currently, the JetProduct Gallery widget does not provide an option to set the opacity of the thumbnails in pagination to 100% for the gallery slider. This feature would be extremely useful for ensuring that all thumbnails are clearly visible and not affected by any opacity settings that may reduce their visibility.

**Importance:**

**Enhanced Visibility:** Ensuring that all thumbnails are fully visible without any opacity reduction improves the user experience by making it easier to see all available images clearly.
**Design Flexibility:** Providing this option gives designers more control over the appearance of their product galleries, allowing them to match the gallery style with the overall design of the website.

**Expected Effect or Functionality:**
An option in the JetProduct Gallery settings that allows users to set the opacity of thumbnails in pagination to 100% for the gallery slider. This setting should be easily accessible and adjustable within the style or design tab of the widget settings.

**Example of Implementation:**
For instance, in Elementor, similar features are often implemented through a simple slider or toggle in the style settings of a widget. This allows users to set the desired opacity level with ease.

**Additional Context:**
Providing an option to set 100% opacity for thumbnails would greatly benefit users who rely on clear and fully visible thumbnails to enhance their product presentation. Currently, there is no straightforward way to ensure that thumbnails have full opacity, which can lead to a less than optimal user experience.

Thank you for considering this feature request. It would be a valuable addition to the JetProduct Gallery widget, enhancing its functionality and user satisfaction.

**Comment by Crocoblock** [comment]
was added in JetProductGallery 2.1.17 
elementor - https://tppr.me/SBwdZu 
guten - https://tppr.me/lrene7
