### ISSUE TITLE
JetBooking. select both Day & Night time booking options

### ISSUE THREAD

**Issue by IreneDania** [CrocoBlock/suggestions#7570]
I need to have per night pricing in my booking calendar.
However company sells also 1 day. I cannot  replace the check-in/check-out field by a date field because the DATE field in JetForm Builder lets user to select any date even those are fully booked or (days-off).
The option allow checkout only days https://prnt.sc/yRTmqP19Yz3m is confusing and not good user experience when you are booking 1 day and instead you need to book 2 days.
It's a shame that JetBooking does not allow you to select both Day & Night time booking options.

**Comment by Aldermoon2** [comment]
For each room create the necessary booking blocks via “units”, see documentation for units manager

**Comment by IreneDania** [comment]
> For each room create the necessary booking blocks via “units”, see documentation for units manager

Thank you for your suggestion! Units Manager is for a different thing: 
https://crocoblock.com/knowledge-base/jetbooking/how-to-manage-units-via-the-wp-dashboard/

This is a feature request from our client discussed on a ticket with the Crocoblock tech team.

**Comment by dancoLgh** [comment]
Hello, I have the same case.
My client has rooms (like a hotel) have check-in and check-out and also bungalows that are per day.

**Comment by Crocoblock** [comment]
was added in JetBooking 3.5.1
