### ISSUE TITLE
Conditional filters

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#7571]
Well, despite Crocoblock is the most multifunctional plugin I have seen (amazing features) it lacks the conditional filtering. What I mean, is that if we use 2 or 3 separate filters and one Apply button, we should be able to set a condition so the apply button will be activated if all filters have selected values. That way, the results page will show only the desired posts, saving resources and time from the user to find what he needs.

**Comment by Crocoblock** [comment]
Added in JetSmartFilters 3.5.7 https://i.imgur.com/Ynw7bAE.png

**Comment by TheBigBanik** [comment]
Youpiiiiiiii. Thank you guys. you always deliver our requests. Keep up your excellent work. :)
