### ISSUE TITLE
some issues in jet woobuilder my account builder

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7572]
Hi,

1- Actually this is not a bug. But there is no option to control the typography of this text.

![1](https://github.com/Crocoblock/suggestions/assets/77163248/c27e589c-80b0-4500-8931-ed1a4c5c58c6)

2- The order table has an extra margin from the bottom, which is solved with this code. It would be great if this margin was removed by default.

.woocommerce-orders-table{
 margin: 0px !important;
}

3- The variable display section of the product is far from the right side. Also attached as product (above).

![Screenshot](https://github.com/Crocoblock/suggestions/assets/77163248/c765247f-d4fc-4c54-bd15-dbd8b4d0b982)

4- Also, in the address template, there is no option to edit the address button.

![Screenshot_1](https://github.com/Crocoblock/suggestions/assets/77163248/a4039ad1-af90-4587-bc2b-605b1aa5b622)

thank you

**Comment by UraraReika** [comment]
1. If you cant find any related style controls here - https://tppr.me/LINwM8 in Account Content widget that mean that there is no such controls and we do not have in nearest plans to add such controls. So please use plain CSS in this case.
2. Done
3. This is default WC behaviour that works both in LTR and RTL.
4. Same as point 1.

Thank you!
