### ISSUE TITLE
Jet Woobuilder: new template for view order and edit address

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7573]
Hi,

It would be great if you add a template like bricks to customize the view order page. Currently, the customization options of this page and edit address page have been integrated into the my account content widget. One of the biggest current weaknesses is that it is not possible to edit the view order page live.

![Screenshot](https://github.com/Crocoblock/suggestions/assets/77163248/fb4f478a-f707-4b1c-bb5c-a416d1b8a38a)

It would also be great if a plugin was added for the address editing section.

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/2721, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
