### ISSUE TITLE
JetWooBuilder product grid malfunction

### ISSUE THREAD

**Issue by shahabmohi** [CrocoBlock/suggestions#7574]
**Describe the bug**
JetWooBuilder product grid malfunctions when put in Carousel mode, and nothing can fix it except deactivating the carousel.

**To Reproduce**
1- Open any blank page in Elementor.
2- Select a product grid, select any preset, and then turn on the carousel option.

**Expected behavior**what
The product grid is supposed to be centered.

**Screenshots**
![Screenshot 2024-06-19 183320](https://github.com/Crocoblock/suggestions/assets/66645514/bde694d9-33fb-4525-bf2b-2ee0aeafc336)

**Desktop (please complete the following information):**
 - OS: Windows & Mac
 - Browser Chrome, Safari and Edge
 - Version 2.1.12 of the Jetwoobuilder

**Comment by rameesareno** [comment]
Same issue I am getting.
https://www.awesomescreenshot.com/video/28951402?key=5d7904c1b775b9eeb9ea37b1805d8908

**Comment by rameesareno** [comment]
Add this to your global css.

.jet-woo-carousel.swiper-container{
  overflow: hidden;
}

**Comment by shahabmohi** [comment]
You can also disable the "Upgrade Swiper Library" feature in Elementor and it goes back to normal, but I am tired of scavenger hunting to find the bug every time there is an update to Elementor or to Jetwoobuilder!

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Tested on latest Elementor and Elementro Pro version as well as JetWooBuilder. Also tested with Upgrade Swiper Library active and inactive -  https://tppr.me/jol6ra.

Thank you!

**Comment by shahabmohi** [comment]
I have 4 different websites with Crocoblock, and the same thing happens every time on each different site. Test it with sections and columns instead of a flexbox container and let me know if you still see it working properly.

**Comment by UraraReika** [comment]
> I have 4 different websites with Crocoblock, and the same thing happens every time on each different site. Test it with sections and columns instead of a flexbox container and let me know if you still see it working properly.

Please [contact](https://support.crocoblock.com/support/home/ ) our support team so we can check this issue on your side.

Thank you!
