### ISSUE TITLE
Child page of the main post page

### ISSUE THREAD

**Issue by nitinmi9** [Crocoblock/suggestions#758]
Hi, thanks for some wonderful WordPress plugins.

I wanted to request for an additional feature that can be potentially useful for many people.

As for now against every post there is a single post page. Sometimes some particular fields in the post can be very lengthy and may not make sense to load in the initial loading. This is especially true when one uses a custom field.

E.g., I have Companies type custom post and within that many custom fields wherein the information keep on building over period. E.g., Past financial information of the Company.

It might make sense to allow calling such kind of lengthy information on a separate page rather than the main post page. On the main post page there can be some excerpt of information + link for complete information on a separate page.

As for now, I am using your Jettabs to collapse the information but ideally I would want to open the information on a separate page.

Please do include this in your further developments or guide if there is some workaround.

**Comment by Floydtm** [comment]
@nitinmi9, hi! It seems to me that the options page should help you. there you can store the necessary information and display it in any place on your site. this way you can redirect the client from the single page to the page where you will show more detailed information about the company
