### ISSUE TITLE
Redirect "www" subdomain: www.crocoblock.com -> crocoblock.com

### ISSUE THREAD

**Issue by erobertsme** [CrocoBlock/suggestions#7580]
**Describe the bug**
Currently if you try to visit https://www.crocoblock.com it displays the default "Welcome to nginx!" page.

**To Reproduce**
Enter https://www.crocoblock.com in your browser's address bar

**Expected behavior**
Visiting https://www.crocoblock.com should redirect to the website at https://crocoblock.com

**Screenshots**
![image](https://github.com/Crocoblock/suggestions/assets/9193319/a2839391-f02c-4199-b217-e7cb6ff4bdcb)

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Additional context**
I have tried to reach out to support multiple times about this. Browsers have a keyboard shortcut to add "www." and ".com" with `ctrl + enter` allowing a user to type "crocoblock" then hit `ctrl + enter` to visit a website quickly.

Additionally, many user often use "www." by default either out of habit, convention, or they may think that it is necessary.

The solution for this is ridiculously simple and there is no reason for https://www.crocoblock.com not to redirect to the site.

**Comment by yuriybratchenko** [comment]
Thanks, done
