### ISSUE TITLE
Add CPT featured image to WooCommerce Cart fields when using Plain Booking Mode

### ISSUE THREAD

**Issue by mafisatz** [CrocoBlock/suggestions#7586]
When using Plain as the Booking Mode, the cart has the CPT fields filled out correctly on a booking, however the image is sourced from the product named “Booking” as configured by the wizard.

<img width="1340" alt="Screenshot 2024-06-26 at 5 06 49 PM" src="https://github.com/Crocoblock/suggestions/assets/167733505/7b764536-e985-497d-a777-399189cfcb37">

As per screenshot, the fields that are filtered to the cart are the post title and the units which are sourced from the CPT, however the image field is sourced from the woocommerce product, which makes it useless.

It would make sense (and more complete) to have the featured image of the CPT filter to the cart instead of the generic product.

As per support this is not possible now and hence this feature request.

**Comment by Crocoblock** [comment]
> It would make sense (and more complete) to have the featured image of the CPT filter to the cart instead of the generic product.

Added in JetBooking 3.5.2
