### ISSUE TITLE
jet smart filters : Rendering filters need improvement

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7588]
Hi crocoblock team,

On the archive page when the page loads, the css in the filters loads with a lot of delay and this is very noticeable and affects the CLS. is it possible for you to improve it? Please watch the following video :

https://github.com/Crocoblock/suggestions/assets/77163248/d9894cdf-9d04-4d36-b73c-45181d41771f

As you can see in the above video, after every reload of the page, the css of the filters is loaded with a delay. While other content is rendered immediately.

**Comment by Crocoblock** [comment]
Fixed in JetSmartFilters 3.5.6 
Please, update

**Comment by 79ho3ein** [comment]
Hi @Crocoblock,

I'm still having trouble rendering filters in the new version.
