### ISSUE TITLE
Date period filter according to tour check in and check out dates

### ISSUE THREAD

**Issue by hash-cha** [CrocoBlock/suggestions#7589]
I'm developing a travel website with tour deals. Tours can be one day, two days, or three days. I want users to filter and view deals based on their check-in and check-out dates. For example, if someone fill checks in today and checks out the day after tomorrow, they should see the 3-day deals. Can you help me with this?

**Comment by UraraReika** [comment]
I've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such complex cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.
