### ISSUE TITLE
 Request for Feature to Add Templates to Tooltips in JetTricks Hotspot Widget

### ISSUE THREAD

**Issue by SwenHong** [CrocoBlock/suggestions#7590]
Currently, the JetTricks Hotspot Widget only allows text to be entered in tooltips. However, it would be beneficial to add a feature that allows templates to be inserted in tooltips, in addition to text. This functionality would enable users to include content such as images and links in tooltips, significantly enhancing the user experience.

For example, on an interior design site, this feature can be used as shown in the attached link.

https://www.ggumim.co.kr/star/view/5434

I sincerely request that you consider adding this feature. Thank you.

https://github.com/Crocoblock/suggestions/assets/166370763/e3628ae4-642a-4bcf-b319-0accc4ab72c4

**Comment by Crocoblock** [comment]
was added and released in JetTricks 1.5.0
