### ISSUE TITLE
JetSmartFilter: AND (Intersection) logic between checkbox items for JetEngine Query Builder

### ISSUE THREAD

**Issue by iangoh0414** [CrocoBlock/suggestions#7592]
Hi,

Are you able to implement AND logic between checkbox items in JetSmartFilter Checkboxes Filter in elementor?

I need AND function between the checkbox items in 1 filter. Currently, it is OR function.
AND logic is only possible between 2 filters checkbox items but not in 1 filter.

Currently, this is possible using the taxonomy data source and set Relational Operator to intersection.
However, I am using the "JetEngine Query Builder" as data source and it is not working.

**Example**
Item 1 is assigned taxonomy type A
Item 2 is assigned taxonomy type B
Item 3 is assigned taxonomy type A & B

**Current situation**
When Type A and Type B are checked in filter, item 1, 2 and 3 will show.

**Idea Situation**
When Type A and Type B are checked.
If AND is implemented, only item 3 should be shown because it is the only one that is assigned Type A and Type B (taxonomy)

Please implement the option for us to choose AND logic for JetEngine Query Builder data source ASAP as we really need this functionality

Thank you.

Ian

**Comment by iangoh0414** [comment]
@Crocoblock Able to address this issue?

**Comment by Crocoblock** [comment]
Hi @iangoh0414 

Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.

**Comment by iangoh0414** [comment]
I still hope you can implement **Intersection** filter for JetEngine Query Builder data source. Please consider adding this feature.
The problem using taxonomy (which has intersection) is I can't sort the taxonomy values properly.
In my taxonomy, I have another column for sorting, so I can sort the values using query but can't do Intersection filter.

Problem with taxonomy sorting
I have values 10V 24V 50V 90V 100V 120V
**Ideal sorting**
10V
24V
50V
90V
100V
120V

**Result**
10V
100V
120V
24V
50V
90V

**Comment by Crocoblock** [comment]
Added in JetSmartFilters 3.5.6 https://imgur.com/9X78CKr 
Please, update the plugin
