### ISSUE TITLE
Query Builder - WC Product Query - Load more shows products from different category

### ISSUE THREAD

**Issue by zahnd** [CrocoBlock/suggestions#7593]
**Describe the bug**
I'm using the Query Builder to get all the products of a current category to be used on archive pages. I'm using the Tax Query to query only the products of the current "queried term". Pagination is active and set to a limit of 9. 

Pagination is enabled by using the jetSmartFilter pagination widget and configured to show a load more button. 

When navigating to the archive page, the products shown are correctly filtered and only from that category. But, as soon as I click on load more to get the next 9 elements, products from all categories are shown.

It seems as the Tax Query parameter got lost when clicking load more. 

Enabling or disabling pagination has no effect. It's always the same result. 

**To Reproduce**
1. Go to Query builder
2. Create a new query of type "WC Product Query"
3. Select only published posts
4. Enable pagination and set limit 9
5. Add a tax query of type product_cat for field "Term ID" and Terms "Queried Term".
6. Create an archive template in Elementor Theme Builder
7. Create a listing grid or use JetWooBuilder Products grid
8. Add JetSmartFilter pagination widget
9. Go to archive and press "load more"

**Expected behavior**
When clicking load more, only products of the "Queried term" should be displayed. Not from all categories. 

**Screenshots**
<img width="634" alt="Screenshot 2024-06-29 at 11 43 30" src="https://github.com/Crocoblock/suggestions/assets/3197552/b9b6add8-eb38-4f61-9f3b-c39e5d166e86">
<img width="733" alt="Screenshot 2024-06-29 at 11 54 42" src="https://github.com/Crocoblock/suggestions/assets/3197552/8cd820d1-3534-4d56-b459-5af6d1160f31">
<img width="763" alt="Screenshot 2024-06-29 at 11 56 08" src="https://github.com/Crocoblock/suggestions/assets/3197552/d6bbc40d-fbef-45a6-99ee-2368e0292bdb">

**Additional context**
JetEngine 3.5.0
JetWooBuilder 2.1.12
Elementor 3.22.3
Elementor Pro 3.22.1
WordPress 6.5.5
WooCommerce 8.8.5

**Comment by Crocoblock** [comment]
Hi @zahnd 

We've tried to reproduce your issue and everything works fine on our side. Are you using Query ID? If no - please, try with it.
![image](https://github.com/Crocoblock/suggestions/assets/47778274/cecbab27-d240-4efb-aaf7-d8470d3c6985)


Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
