### ISSUE TITLE
Error. License key invalid

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#7594]
**Describe the bug**
I changed the license key, now the old one cant be deactivated.
My recommendation for future updates is: let the user remove the keys, even if they are invalid

**To Reproduce**
I dont know how to reproduce the behavior, as on other sites it works fine.

**Expected behavior**
You cant update the plugins anymore from the admin area.

**Screenshots**
![Screenshot_2](https://github.com/Crocoblock/suggestions/assets/46810010/40d4865e-f512-4213-bace-1de6c6a4384e)

**Additional context**
My recommendation for future updates is: let the user remove the keys, even if they are invalid

**Comment by Crocoblock** [comment]
Hi @ciprianpentelescu 

please create a [ticket](https://crocoblock.com/help-center/) including access details for your site where the issue occurred to make sure we can help you.

**Comment by flyzal** [comment]
Is this resolved?

**Comment by Crocoblock** [comment]
Please, try to do the following:

Go to Crocoblock > License

![image](https://github.com/user-attachments/assets/86d47071-a980-4522-a7c2-f484ac8d3a2b)

When you’re on the license page, click on the Ctrl Alt D on your keyboard.

❗ If you use Mac, the shortcut is Control Option D.

![image](https://github.com/user-attachments/assets/93cfd77a-ff91-4b25-931d-aa9b8333b3f4)


After that, the popup will appear. You’ll need to choose the Delete License Data option and click on the Go button.

![image](https://github.com/user-attachments/assets/f6db07a8-e072-48bd-9473-a4f7ec72029b)


Then, add your license and try to update the plugin.

**Comment by flyzal** [comment]
Thanks, solved, this will help many!

**Comment by flyzal** [comment]
Hi CB Team,

Thanks, solved.

*Regards,*

*MF*
<https://mysignature.io/editor/?utm_source=expiredpixel>

**Comment by amitsarkerr** [comment]
Thanks. your solutions solved the license deactivating issue.
Followed CTRL + ALT + D in mac.

**Comment by tutods** [comment]
CTRL ALT D or CTRL OPTION D didn't work for me

**Comment by itagentuur** [comment]
Thanks, easy fix
