### ISSUE TITLE
Custom Meta Storage for CPT

### ISSUE THREAD

**Issue by DaviAppelDuarte** [CrocoBlock/suggestions#7598]
When we update a postmeta that is in the storage folder, the add_action('updated_post_meta' action is not triggered, making it impossible to use it for custom functions. If you can't use this action, at least include some documentation of the action that is being used for this update.

**Comment by MjHead** [comment]
Will be fixed with 3.5.2 update

**Comment by Crocoblock** [comment]
was released in JetEngine 3.5.2
