### ISSUE TITLE
Relationships Between Taxonomies and Custom Fields

### ISSUE THREAD

**Issue by jasonb4u** [CrocoBlock/suggestions#76]
When shall we expect RELATIONSHIPS to happen like Toolset, ACF & Pods?
Yr gonna have to get yr game together to match the bigboys !

This must be the only way to get yr attention as I dont see any admins or staff seeing to posts on Facebook where most people are hanging out and asking for assistance.

Toolset: https://toolset.com/documentation/post-relationships/

ACF: https://www.advancedcustomfields.com/resources/relationship/

PODS: https://pods.io/docs/learn/field-types/relationship/

Jason Beard

**Comment by MjHead** [comment]
Hi @jasonb4u Posts relationships was adeed in JetEngine 1.2.0 - https://documentation.zemez.io/wordpress/index.php?project=jetengine&lang=en&section=jetengine-posts-relations

**Comment by jasonb4u** [comment]
Taxonomies and Custom Fields, just like Toolset .

**Comment by MjHead** [comment]
@jasonb4u You can currently create/edit taxonomies with JetEngine, you can add the same Taxonomy for different post types, you can add custom fields for taxonomies, you can add custom fields to posts, you can create relationships between different post types (like in Toolset - https://toolset.com/documentation/post-relationships/) and much more. Could you, please be more specific what exactly you need to do?

**Comment by pierrehansen** [comment]
Is there are reason why we can't create a relation within the same post type? Relations from products to products for example.

**Comment by hamed-azimi** [comment]
> please be more specific what exactly you need to do?

What I see that is really missing, and can be a big game changer, is to have CPT to Taxonomy relationship.

For example, now we have a CPT called "Shipping Restrictions" which has many to many relation with Products. (so we can add many products while adding a shipping restrictions, and we can add many shipping restrictions to products. this helps us set shipping restrictions in product level)

But we also need to set shipping restrictions at Product Category level (which requires a many to many relation between Shipping Restrictions CPT and Product Category which is a taxonomy)

This was just one real example. There are many other examples that will help us create very complex and useful features.

**Comment by antoniode11** [comment]
My friend jasonb4u I think he refers to having relationships of taxonomies to, for example, Country, State, City, area, I have never seen this relationship easily made to, for example, locate properties, or for example car brands and models. I would like to know how to put those related categories in a select field and that according to the selected brand it shows the models of that brand

**Comment by djstini** [comment]
Hi, to revive/add on to this, is there a way to assign terms to users?
