### ISSUE TITLE
Time and Date Format for Jet Engine Meta Field

### ISSUE THREAD

**Issue by Sayeed1440** [Crocoblock/suggestions#760]
As of now the Time format of the Jet Engine Meta field is 24 Hours and Date Format is d/m/y. This is not changing from Wordpress general settings.

Kindly add this feature.

Thank You

**Comment by omojahed** [comment]
This is very important for a lot of people.
Please, is there a workaround ?

**Comment by rahaabasi** [comment]
Hello
You have an amazing plugin but unfortunately dos not support to change the calendar and we can not use that and it seems you are not going to fix this because
![download](https://user-images.githubusercontent.com/73196425/96635442-b4ed4400-1328-11eb-8b69-0066b6f057d3.png)
 this ticket was open about a year ago.
Your support staff told me I have to open ticket and you will answer 
Thanks.

**Comment by lolirado** [comment]
Please update this feature request.

**Comment by saifurpro** [comment]
please update this feature. I need the feature urgently. I have purchased the plugin but some of the small -small features are missing.

**Comment by Zegklitz** [comment]
+1

**Comment by pbuw** [comment]
Would be great if you could add this feature!

**Comment by CaseFixedWebdesign** [comment]
+1

**Comment by albrechetti** [comment]
I need this too please implement this feature!

**Comment by developernerds** [comment]
NEED this feature! Please add a way to format the date and time output! I would like it to match the one I chose for wordpress.

**Comment by spix18** [comment]
how this not available yet , its has been 1 years and 5 month.

**Comment by KingGrizzly** [comment]
+1

**Comment by RuanPienaarCode** [comment]
+1

**Comment by dexit** [comment]
../plugins/jet-engine/assets/js/admin/meta-boxes.js

You can change it here.

**Comment by wordpressman** [comment]
This should really be fixed, nobody wants to hack the plugin code at each update !

**Comment by ACTx22** [comment]
+1

**Comment by chervince** [comment]
+1

**Comment by evolvenl** [comment]
Really need this, Jetengine can do so much, but a simple feature for dateformat isn;t possible?

**Comment by mirajadesign** [comment]
We really can't do this yet? Umm... Wow.

**Comment by vinnyCalixto** [comment]
Any news?

**Comment by brianmaksy** [comment]
Would likewise like to know - thanks!

**Comment by developernerdsacademy** [comment]
Please add the option to set your format for the date in the forms or in the plugin settings! Most people in America do not read time as 13:00 instead of 1:00 and my users are confused. It's a simple fix. So, we humbly ask that you add it as an addon even.  Thanks!

**Comment by pbuw** [comment]
I found an easy solution for the date format:
1. In the Post Type settings -> Activate "Save as Timestamp".
2. Use the "Dynamic Field" in the frontend
3. Activate "Filter field output" 
4. Select callback "Format date (localized)"

Now you can customize the format of the date like you want to. 😀
Hopefully, this will help.

**Comment by justgkp** [comment]
Above function works only in Dynamic filed. It can not be used elsewhere. If they make it available I would say Crocoblock is the best.

**Comment by kaskad88** [comment]
Add for the next version( 2.10.3 ). Thanks for your report!

**Comment by justgkp** [comment]
you promised that it will be added in the next version (2.10.3) but I didn't see any change except your fake promise. If you have fixed the bug please express it here. #760 
![Screenshot-2021-12-23-at-9 27 51-PM](https://user-images.githubusercontent.com/71189434/147264953-5df9e43c-0e77-4269-8e7a-a995141e273c.jpg)

**Comment by kaskad88** [comment]
Hello @justgkp. Solution for your case: https://gist.github.com/kaskad88/eb35ae49f312d95746b13d3fde25d0f1 . Add this code in functions.php file of your child theme.

**Comment by justgkp** [comment]
Thanks for the immediate support. It worked exactly as mentioned. 
I have another problem, if there are **more than one meta_field** with **date format** how will I solve it? Please help me.

**Comment by kaskad88** [comment]
@justgkp Solution: https://gist.github.com/kaskad88/eb35ae49f312d95746b13d3fde25d0f1#file-modify-shortcode-output-L11-L13

**Comment by tbrady85** [comment]
> @justgkp Solution: https://gist.github.com/kaskad88/eb35ae49f312d95746b13d3fde25d0f1#file-modify-shortcode-output-L11-L13

Hi @kaskad88, this fix doesn't seem to be working for me. I confirmed that line 11 was changed to match my date meta field id, but still showing arbitrary numbers.
![crocoblock](https://user-images.githubusercontent.com/19779430/152597495-89749abb-455a-46ae-8c30-74566e22e4b5.png)
![crocoblock2](https://user-images.githubusercontent.com/19779430/152598689-e2ef3065-5934-450c-9ac6-6ad7c453fe4c.png)
![event_date](https://user-images.githubusercontent.com/19779430/152598690-a3b046fb-9afc-4a87-8762-f7ddc84d9dd6.png)

**Comment by liiakerosene** [comment]
To display the date format
https://wordpress.org/support/article/formatting-date-and-time/
![image](https://user-images.githubusercontent.com/101399164/157857000-6bd10301-da3e-4991-ada9-70e2bbbf74f2.png)

**Comment by Saranichev** [comment]
Подскажите как сделать чтобы записывался в таком формате времени xx.xx.xxxx
подойдет даже вариант через function.php

Tell me how to make it recorded in this time format xx.xx.xxxx
even the option via is suitable function.php

![image](https://user-images.githubusercontent.com/89551820/171622396-086562ea-c6a4-4f3b-acef-1869d4866716.png)
![image](https://user-images.githubusercontent.com/89551820/171622472-2da0eef4-581b-4f70-8a51-ecf1bdd16f51.png)
![image](https://user-images.githubusercontent.com/89551820/171622688-9b5b7093-c10f-4c24-bcfc-47ed3881cdc7.png)
![image](https://user-images.githubusercontent.com/89551820/171622710-fefce3e1-c173-425d-9a0e-a7c5c293ba36.png)
![image](https://user-images.githubusercontent.com/89551820/171622914-c427e487-bfbf-4d66-88a7-8f3396f3a309.png)
![image](https://user-images.githubusercontent.com/89551820/171623006-2bae830e-d431-45ff-90fa-06c7995aafc4.png)

**Comment by sarbajit1998** [comment]
Easy Solution
1. Filter Field Output - ON
2. Choose - Format date (Localized)
3. Format - g:i A
Problem Solved Perfectly

**Comment by estevan-ulian** [comment]
Format hour to 24h:
G:i = 21:00

**Comment by churongcon** [comment]
> To display the date format https://wordpress.org/support/article/formatting-date-and-time/ ![image](https://user-images.githubusercontent.com/101399164/157857000-6bd10301-da3e-4991-ada9-70e2bbbf74f2.png)

Do you know how to translate to another language ?

**Comment by gsqrt2** [comment]
That is not an acceptable solution. Meta field data may be used in a countless number of ways in the backend, it should not depend on a specific widget for display.
One could argue that you can manipulate the value at will when working on the backend, but if you want to maintain compatibility, eg for replacing ACF, you should be able to choose the format from the meta field options.
