### ISSUE TITLE
JetElements compatibility for BricksBuilder

### ISSUE THREAD

**Issue by RuanPienaarCode** [CrocoBlock/suggestions#7604]
Integrate JetElements with BricksBuilder to allow users to utilize JetElements widgets within the BricksBuilder environment.

Product:

JetElements

Importance:

This integration will enhance the flexibility and functionality of BricksBuilder, providing users with a broader range of design tools and options, resulting in a more seamless building experience.

Desired Functionality:

Support all JetElements widgets in BricksBuilder.
Ensure styling, layout, and customization options of JetElements widgets are fully functional in BricksBuilder.
Optimize performance for smooth usage without conflicts or slowdowns.
Example of Implementation:

JetElements is successfully integrated with Elementor, allowing users to drag, drop, and customize JetElements widgets seamlessly.

Use Case:

This feature will benefit web developers and designers using BricksBuilder for various website types, enhancing their ability to create unique and feature-rich web pages.

Attachments:

[Video: JetElements Widgets in Elementor](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
Thank you for considering this feature request.

Best regards,

Ruan Pienaar

**Comment by SolunaCG** [comment]
+1

**Comment by MjHead** [comment]
Hi, sorry, at the moment we have no plans to make JetElements compatible with Bricks builder.

**Comment by SolunaCG** [comment]
More and more people (including our company) have switched to Bricks for various reasons. Having your plugins compatible with Bricks is very important for many users! Maybe there’s a chance you could reconsider this decision and reopen this thread @MjHead ?

![Crocoblock YouTube-Post](https://github.com/user-attachments/assets/85a4399c-6f30-43f9-80f6-7e1accd001f9)
