### ISSUE TITLE
Jet Appointments - Provider capability to edit their availability 

### ISSUE THREAD

**Issue by magdakubis** [CrocoBlock/suggestions#7607]
It would be great if the providers could edit their available time slots via JFB front end forms.
Currently an admin has to set things up and manage the calendar availability for each provider, which in some cases is a lot of work as they change on a weekly basis if not daily basis for some businesses...

**Comment by Crocoblock** [comment]
Hi @magdakubis 
I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/6401)
