### ISSUE TITLE
Products Grid widget with custom Archive Product template

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#761]
When I create an Archive Product template with JetWooBuilder, I can customize which items to put.

But when I'm going to use the Carousel Products Grid widget
  JetWooBuilder itself, I can not use this template I created, just the ones you created, but this way the layout is totally different.

How do I create a simple carousel with Archive Template here: http://documentation.zemez.io/wordpress/index.php?project=jetwoobuilder&lang=en&section=jetwoobuilder-product-archive-template#

**Comment by Floydtm** [comment]
@marcofrasson, hi! At the moment, we do not plan to introduce such functionality into our plugin. Thanks!
