### ISSUE TITLE
[JetEngine] Add Dynamic Selector for switcher

### ISSUE THREAD

**Issue by rob1998** [CrocoBlock/suggestions#7611]
### Description

Introduce a new dynamic selector for fields. For example text (text, textarea, URL, email) and number fields. This selector should allow users to select a switcher option/meta field and then provide two fields: one for when the value is true and another for when the value is false.

### Proposal

Create a dynamic selector that integrates with text and number fields, enabling users to choose a switcher option/meta field. This selector should provide two input fields: one for true values and another for false values. If possible, these fields should support dynamic content.

### Current Limitation

Achieving this functionality currently requires using dynamic visibility, which necessitates duplicating widgets for handling different values.

### Benefits

This feature streamlines the process by eliminating widget duplication, enhancing usability and efficiency for users.

### Example Use Case

If a switcher is on, I want to link to a landing page; if off, I want to link externally. Another use case could be displaying a specific message based on the switcher's state, avoiding the need to duplicate content blocks.

<img width="276" alt="Screenshot 2024-07-09 at 14 54 46" src="https://github.com/Crocoblock/suggestions/assets/1560707/83d47ff6-0aa3-4e41-bec6-568c9df1023c">

**Comment by Crocoblock** [comment]
Hi @rob1998 

To solve this problem, you can use a shortcode
![image](https://github.com/user-attachments/assets/a4498fad-6862-4c1d-9f10-64c826e28e6e)
![image](https://github.com/user-attachments/assets/93b231fa-f9e6-4ada-a877-4580283fa3d6)
