### ISSUE TITLE
Bricks Pop-Up interaction in Components 

### ISSUE THREAD

**Issue by Tw1L1ght12** [CrocoBlock/suggestions#7615]
**Describe the bug**
Bricks pop-ups are losing styling in Components.

**To Reproduce**
1. Add a button with interaction 'show element -> pop up' on click
2. Add components anywhere
3. Click button
4. Pop up looks like absolute mess

**Screenshots**
![изображение](https://github.com/user-attachments/assets/6c43e950-4c34-4895-8536-fb966f511de4)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: latest

**Additional context**
Latest version of WordPress, Bricks and JetEngine

**Comment by Crocoblock** [comment]
Hi @Tw1L1ght12 
Did you add conditions in the popup?

**Comment by Tw1L1ght12** [comment]
> Hi @Tw1L1ght12 Did you add conditions in the popup?

No
Looks like problem happens cuz of ajax loader in loop, and now I'm not sure that this is a jetengine bug

**Comment by Crocoblock** [comment]
@Tw1L1ght12 
yes, that's because ajax is enabled
I am forwarding this issue to the developer

if there is any news, I will report here

**Comment by Crocoblock** [comment]
was fixed in JetEngine 3.5.5
