### ISSUE TITLE
JetEngine Components: add html text field

### ISSUE THREAD

**Issue by cabez0n275** [CrocoBlock/suggestions#7616]
The new components function is great and will make our work much easier. We have only missed the possibility of including rich text fields (html) so that the component field allows including links, bold, etc.

Many thanks for your work.

**Comment by Crocoblock** [comment]
Hi @cabez0n275 
Can you explain more, maybe with screenshots?

**Comment by cabez0n275** [comment]
Hello @Crocoblock 

Currently the "Control type" option of the Component function offers the option "Text" and "Text area", in both cases when using the component in Elementor editor only allows you to enter **plain text**, without the option to define bold styles, include links, etc..
We believe this would be a very interesting option.

Thank you very much in advance.

**Comment by savimigreg** [comment]
Agreed, we are also in desperate need for this. The WYSIWYG field would achieve this if added. With the "Text area" field you can't even add line breaks without adding <br> which isn't ideal for large bodies of content.

**Comment by arcaswebdesign** [comment]
+1 for this, the principal of the components is great but at the moment too limited in terms of the controls, if we could enable a fuller rich-text editor for any textarea fields that would be a vast improvement.

**Comment by Crocoblock** [comment]
Added in the [JetEngine 3.6.0](https://github.com/Crocoblock/suggestions/issues/7842#:~:text=Rich%20Text%20%D0%A1ontrol%20Type%20for%20Components)
