### ISSUE TITLE
JetEngine - Shortcode/Widget - Callback - Get Permalink/URL by ID

### ISSUE THREAD

**Issue by engrrajonahmed** [CrocoBlock/suggestions#7617]
It would be beneficial to have a callback function that retrieves permalinks/URLs based on IDs.

For instance, within a field of CPT or CCT, if we have an array of IDs for posts, pages, media, or users, we should be able to obtain the permalinks/URLs for these objects using their respective IDs.

**Comment by MjHead** [comment]
You can do this with Dynamic Field widget

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/13b18b9b-bc15-48a3-8c62-baf0a5ef708a">

**Comment by engrrajonahmed** [comment]
@MjHead Thanks for your reply. The solution works only for a single entry. I am talking about an array of IDs. Thank you once again!
