### ISSUE TITLE
🔴 JetAppointment Workflows - Events triggered improperly (2.1.0)

### ISSUE THREAD

**Issue by brjmichael** [CrocoBlock/suggestions#7620]
Hello team! First, thanks for the great work :)

I’m having problems with Workflow. I set up an event to send an email 2 days before the appointment to remind the customer. The problem is that even if the appointment is **cancelled**, the email is still sent.

It is important that scheduled events, such as sending email 2 days before the appointment, are triggered only if the appointment status is Pending or On-Hold.

> JetAppointment: 2.1.0

Thanks!

**Comment by Crocoblock** [comment]
was fixed and released in JetAppointment 2.1.3
