### ISSUE TITLE
Optimize Performance by disabling render of Dynamic Visibility while editing with elementor

### ISSUE THREAD

**Issue by ricardoaraujo330** [CrocoBlock/suggestions#7625]
Hi,

I use numerous dynamic visibility rules on my single product pages, and I've noticed that it significantly slows down the page render every time I open it to edit with Elementor. This can be quite cumbersome, especially when working on large e-commerce sites with many products.

Proposed Solution:
I would like to suggest an optimization feature where the dynamic visibility rules are rendered only on the frontend, rather than during the editing phase in Elementor. This would greatly enhance the editing experience by reducing the load and improving the performance of the Elementor editor.

Benefits:

Improved performance and faster load times while editing pages in Elementor.
Reduced resource usage, leading to a smoother editing experience.
Enhanced efficiency for users managing large sites with multiple dynamic visibility rules.
Additional Information:

This feature would be particularly beneficial for e-commerce sites with complex product pages.
It could be implemented as an optional setting, allowing users to enable or disable frontend-only rendering of dynamic visibility rules based on their needs.
Thank you for considering this suggestion. I believe it would be a valuable improvement for many Elementor users.

Best regards,
Ricardo

**Comment by DaviAppelDuarte** [comment]
+ 1

**Comment by DaviAppelDuarte** [comment]
I've seen cases of waiting around 5 minutes for the editor to load before actually being able to edit. It would be nice to optimize this.

**Comment by MjHead** [comment]
We double checked this logic - dynamic visibility applied only on the front-end, not in the editor

**Comment by ricardoaraujo330** [comment]
That's a tremendous improvement!!! 💥 💥
I still can't believe they finally improved this! I've already avoided editing my single product template because it's too slow to open 😅 When's the new version released?
