### ISSUE TITLE
Custom Meta Storage for CPT (New issue)

### ISSUE THREAD

**Issue by DaviAppelDuarte** [CrocoBlock/suggestions#7628]
Functions such as searching for postmetas related to the current post are not being able to correctly fetch the postmetas from the custom storage. You may need to fix this for plugins that use this functionality.

![1](https://github.com/user-attachments/assets/1d0885c3-02e3-4ffb-ba0a-278b35a03af5)
![2](https://github.com/user-attachments/assets/4c51cee7-9641-4eec-a909-4ed1dba891e3)
![3](https://github.com/user-attachments/assets/54971223-d26c-4a21-8cf0-5795a2943473)
![4](https://github.com/user-attachments/assets/6ce1b0da-53cb-4caf-b614-0965874d4e5e)

**Comment by Crocoblock** [comment]
Fixed and Released in JetEngine 3.5.6
