### ISSUE TITLE
Add Gap Option to Product Grid

### ISSUE THREAD

**Issue by ricardoaraujo330** [CrocoBlock/suggestions#7629]
The product grid currently does not have an option for setting gaps between items; it only provides padding. This limitation makes it difficult to optimize the spacing around the product grid. As a result, the items on the page do not appear to be aligned properly to a grid.

**To Reproduce**

1. Go to the product grid settings.
2. Attempt to adjust spacing between products using the available options.
3. Notice that only padding can be adjusted, which affects the entire grid layout rather than just the spacing between items.

**Expected behavior**
A clear and concise description of what you expected to happen:

There should be an option to set gaps between grid items, similar to the gap property in CSS Grid Layout. This would allow for better control over the spacing between products, both horizontally and vertically, without affecting the overall alignment and structure of the grid.

Screenshots
<img width="1637" alt="Screenshot at Jul 18 15-34-51" src="https://github.com/user-attachments/assets/c4221760-b248-417d-91d7-e2cc823b3775">

**Additional context**
Padding does not seem to be the correct solution here since it adds space around the entire grid rather than just between the products. Adding a gap option would allow for more precise control over the layout, ensuring that the items are visually aligned to a grid. This is particularly important for creating clean, professional-looking product displays.

Thank you for considering this suggestion.

**Comment by ricardoaraujo330** [comment]
BEFORE i've opened this topic, i was using this css on my site:

```
.jet-woo-products {
width:100%;
}
```

because i was having an issue before, where there was an horizontal scroll on mobile devices with a small gap on right side. It was quite annoying. It looked like this on almost every page because I use a lot the product grid widget:
![IMG_9866](https://github.com/user-attachments/assets/68aa0d96-dd43-4c53-9c20-55cac2327e5b)

Just now, i removed that css and the grid looked adjusted to it's box, like this:

<img width="1115" alt="Screenshot at Jul 18 17-30-08" src="https://github.com/user-attachments/assets/193ae73b-2075-4899-82cc-254fa8b08c57">

HOWEVER, after inspecting, found the problem... this is hiding the padding of the last element on the right side, and that is very likely the reason why i had an horizontal scroll on mobile, please check the hidden padding here:
<img width="1640" alt="Screenshot at Jul 18 17-23-34" src="https://github.com/user-attachments/assets/735e518d-12d8-4ef6-8ad2-bad27f2ee4d3">

Please create a way to use gap between rows and columns for this widget, instead of padding or margins.

Hope this discovery helps you fix it in a near future!

**Comment by 79ho3ein** [comment]
https://github.com/Crocoblock/suggestions/issues/6226

**Comment by UraraReika** [comment]
I merged this issue with https://github.com/Crocoblock/suggestions/issues/6226, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
