### ISSUE TITLE
select two min days just at weekends

### ISSUE THREAD

**Issue by eusouomaxoliveira** [CrocoBlock/suggestions#7630]
How to configure JetBooking so that on weekends, the number of days for reservation must be two and on weekdays only one day can be reserved?

Example:

Monday to Tuesday
Tuesday to Wednesday
Wednesday to Thursday
Thursday to Friday
Friday to Sunday
Saturday to Monday.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Right now you can use this code snippet to achieve much needed result.

```php
add_action( 'wp_footer', function() {
	?>
	<script>
        jQuery( document ).on( "jet-booking/init-field", ( $event, $field ) => {
            $field.bind( "datepicker-first-date-selected", ( event, obj ) => {
                const dayNumber = moment( obj.date1 ).day();
                const iterator = ( 5 === dayNumber || 6 === dayNumber ) ? 2 : 1;

                $field.data( "dateRangePicker" ).setEnd( moment( obj.date1 ).add( iterator, "d" ).format( "YYYY-MM-DD" ) );
            } );
        } );
	</script>
	<?php
} );
```

For help please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you for your understanding.
