### ISSUE TITLE
Jet woobuilder 2.1.13 bug - Navigation arrows are not displayed.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7634]
Hi @UraraReika,

After updating jet woobuilder to the new version, the navigation arrows are not displayed in the product grid widget carousel.
Please let me know if you are not successful in reproducing the bug so that I can check more closely.

**Comment by Crocoblock** [comment]
was fixed in JetWooBuilder 2.1.14
