### ISSUE TITLE
JetProductGallery: for variable subscription

### ISSUE THREAD

**Issue by vpurovitalis** [CrocoBlock/suggestions#7638]
Hello!

Now Gallery slider works only with the Variable Product type. Please add a feature to other product types, especially variable subscription - WooCommerce Subscriptions - https://woocommerce.com/products/woocommerce-subscriptions/ - has more than 90k active installs. And getting more popular.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Originally our plugin works with default WooCommerce product types. We can't foresee all possible product types from different plugins and their functionality, so we stick to standard types. Based on this we do not plan to introduce such functionality into our plugin. 

I've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our [custom service](https://crocoblock.com/customs/  ) - we take such complex cases, that cannot be implemented globally, and bring them to life.

Thank you for your understanding.
