### ISSUE TITLE
JetSearch 3.5.0

### ISSUE THREAD

**Issue by Vigar007** [CrocoBlock/suggestions#7640]
With the latest version of JetSearch 3.5.0 I have to allow API calls, this means a hacker can simply see my users by entering "wp-json/wp/v2/users".

www.test.com/**wp-json/wp/v2/users**

I had to revert to 3.4.4

**Comment by SolunaCG** [comment]
+1 Can confirm that

**Comment by Vigar007** [comment]
I understand JetSearch 3.5.0 now use REST API, however all security plugins have REST disable by default, can I have a function to allow JetSearch?

**Comment by Crocoblock** [comment]
was fixed and released in JetSearch 3.5.2 

also you can use filter to switch from REST API search to AJAX 
```add_filter( 'jet-ajax-search/assets/localize-data/use-legacy-ajax', '__return_true' );```

**Comment by Vigar007** [comment]
It's working perfect now, thanks!
