### ISSUE TITLE
Jet Element For Bricks

### ISSUE THREAD

**Issue by andrijs29** [CrocoBlock/suggestions#7641]
I think u guys need add element for Bricks because in elementor you have it and the widget in elementor is so good and  realy help
Because many people recommend me to try bricks because its much faster then elementor, i try it but the element or widget there not as much as jet element 
Such audio, its standard audio from wordpress, no way to hide something and bit hard
or copy to clipboard element
Why should add? because i think in bricks not many plugin give element or widget, many of them just class  and template only

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7604)
