### ISSUE TITLE
Jetformbuilder: Add "Drag and Drop" for Media Field Attachment

### ISSUE THREAD

**Issue by cookiemachine** [CrocoBlock/suggestions#7642]
For the "media field" attachment, we currently have a button that allows the front-end user to upload media files from their PC via navigating to the file manually. Having a drag and drop area to just drop the files would be much more user friendly. Ideally, we would be able to choose if we want to allow drag & drop or manual file selection for the (registered) front end user.

I would be very happy to see this feature implemented.

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7279)
