### ISSUE TITLE
Uncaught Error in JetEngine and JetSmartFilters Integration with Bricks Theme

### ISSUE THREAD

**Issue by httpspace** [CrocoBlock/suggestions#7650]
I am experiencing a critical issue with the integration of JetEngine and the Bricks theme. The error occurs when trying to call the get_props() method, resulting in an uncaught error. This issue prevents the normal functioning of my WordPress site.

Error Details:

Uncaught Error: Call to a member function get_props() on null in /home/webdiruser/public_html/{mywebsite}.com/wp-content/plugins/jet-engine/includes/components/bricks-views/components/base-element.php:94
Stack trace:
#0 /home/webdiruser/public_html/{mywebsite}.com/wp-content/plugins/jet-engine/includes/components/bricks-views/components/base-element.php(57): Jet_Engine\Bricks_Views\Components\Base_Element->register_general_controls()
#1 /home/webdiruser/public_html/{mywebsite}.com/wp-content/themes/bricks/includes/elements/base.php(114): Jet_Engine\Bricks_Views\Components\Base_Element->set_controls()
#2 /home/webdiruser/public_html/{mywebsite}.com/wp-content/themes/bricks/includes/elements.php(192): Bricks\Element->load()
#3 /home/webdiruser/public_html/{mywebsite}.com/wp-content/themes/bricks/includes/elements.php(176): Bricks\Elements::load_element()
#4 /home/webdiruser/public_html/{mywebsite}.com/wp-includes/class-wp-hook.php(324): Bricks\Elements::load_elements()
#5 /home/webdiruser/public_html/{mywebsite}.com/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/webdiruser/public_html/{mywebsite}.com/wp-includes/plugin.php(565): WP_Hook->do_action()
#7 /home/webdiruser/public_html/{mywebsite}.com/wp-includes/class-wp.php(830): do_action_ref_array()
#8 /home/webdiruser/public_html/{mywebsite}.com/wp-includes/functions.php(1336): WP->main()
#9 /home/webdiruser/public_html/{mywebsite}.com/wp-blog-header.php(16): wp()
#10 /home/webdiruser/public_html/{mywebsite}.com/index.php(17): require('...')
#11 {main}
  thrown
  
Environment Details:
WordPress Version: 6.6.1
JetEngine Version: 3.5.3
JetSmartFilters Version: 3.5.3
Theme: Bricks Child Theme
Child Theme Version: 1.1
Parent Theme Version: 1.9.9
Theme Author: Bricks
Theme URI: https://bricksbuilder.io/
Author URI: https://bricksbuilder.io/

**Comment by Crocoblock** [comment]
@httpspace hi

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.

**Comment by httpspace** [comment]
I have identified and resolved the issue. The problem was with the Nginx configuration.

Initially, it was:

nginx

location / {
    try_files $uri $uri/ /index.php?$is_args$args;
    index index.html index.htm index.php;
}
I changed it to:

nginx:

location / {
    try_files $uri $uri/ /index.php?$args;
    index index.php index.html index.htm;
}

After this change, everything is working correctly.

Thank you!
