### ISSUE TITLE
JetEngine - Wrong input type for tax meta field `Register Query Var`

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#7656]
If you want hierarchical URL structures for your taxonomy terms, you need to enable the `Rewrite Hierarchical` option. To ensure that nested terms are accessible via the URL and don't result in a 404 error, you should also enable the `Register Query Var` toggle. Everything works fine for Custom Post Types (CPTs), but there was an issue with taxonomies: you used a text field instead of a boolean value. I entered true (although any value would work) to make it functional. But that feels very clunky and irritating to me. Could you please update the control type to match the CPT interface?

CPT interface:

![toggle-control](https://github.com/user-attachments/assets/9a888f63-6edb-4fb9-92e5-c612bf4bbf53)

Tax interface:

![text-control](https://github.com/user-attachments/assets/739e9b39-0abd-45dc-958d-51e9d18b1069)

**Comment by ihslimn** [comment]
Actually, this parameter can be a string https://developer.wordpress.org/reference/functions/register_taxonomy/ as is written here https://i.imgur.com/PLuMGrk.png (as well as the equivalent parameter in Post Type), and it is a taxonomy slug by default.
Looking into the code - it has always been that way, so it may be some users use it to set taxonomy query var to something they need it to be.

This is why this control is a text field and not just a switcher, and it will remain as it is.
We will consider adding some button to set it to taxonomy slug in one click.

In your case it is better not to set it to "true", but to a taxonomy slug.

**Comment by ghost** [comment]
Thanks for the explanation. But why isn't the input for the CPTs also a text field? Because for both `register_taxonomy()` and `register_post_type()` this key can either be a boolean but also a string.

**Comment by ihslimn** [comment]
Alas, I cannot say for sure why those controls differ. The functionality was added more than five years ago, and I doubt there are any records left on why it is as it is.
All I can say is one of the next version will make a process of setting query_var for taxonomy a bit more clear and convenient.
Thank you for creating this issue.

**Comment by Crocoblock** [comment]
> All I can say is one of the next version will make a process of setting query_var for taxonomy a bit more clear and convenient. 

done in JetEngine 3.5.5
