### ISSUE TITLE
 add to cart ajax and popup

### ISSUE THREAD

**Issue by neurohost** [Crocoblock/suggestions#766]
Hello, I was wondering if it is possible to add the product to the cart without reloading the page, from the product page, and then show a popup, I give you an example on the following website: 

https://www.mrwonderfulshop.com/en/bathmat-narwhal.html

**Comment by Steriotis** [comment]
I wish for the new year a must "Ajax cart" widget from Crocoblock. Please "copy" the OceanWp feature on this 😉. Show cart after adding the product with ajax is also a must!
