### ISSUE TITLE
slider to the WooCommerce archives page

### ISSUE THREAD

**Issue by marcofrasson** [CrocoBlock/suggestions#7666]
Hello, I would like to add a slider to the WooCommerce archives page. I use JetWooBuilder to generate the archives, but I think it has to do with JetProductGallery. How do I do this?

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

Thank you for your understanding.
