### ISSUE TITLE
A question regarding dynamically assigned hotspots

### ISSUE THREAD

**Issue by CvW17** [CrocoBlock/suggestions#7667]
Hi all. I have a Jettricks Hotspot widget that I need help with. I have 12 hotspots items, and they all get their data dynamically from posts. How would I go about  hiding empty fields. So if a posts only has data till item 10, how would I hide the empty hotspots item 11 and 12.

**Comment by Crocoblock** [comment]
Hi @CvW17 

by default, it can't be done, but we have added the code which should do it 🙂
kindly give it a try
https://gist.github.com/aalexandr21/5de33debf6354115b015bf680a08399e

**Comment by CvW17** [comment]
Hi.

I have added this code, but it does not seem to do the trick. Thank you though.

**Comment by Crocoblock** [comment]
@CvW17 

Can you please describe your problem in detail, with screenshots to better understand why the code does not work?
