### ISSUE TITLE
Conditional Display for JetEngine Fields

### ISSUE THREAD

**Issue by henrique-voni** [Crocoblock/suggestions#767]
**Feature Descripton**

A field for each widget/section that we can set a condition based on JetEngine meta fields (i.e. "$custom_meta_field_1 > 0"). The widget/section will be displayed **only** if the condition is matched.

This becomes very helpful when we have, for instance, related posts inside a single template. Currently, we can only use "hide if empy" in the listing widget, but this makes no sense because sometimes the entire section must be hidden. 

**Similar project:** [Eleconditions ](https://github.com/dudaster/ele-conditions) - I've tested this plugin and it is buggy sometimes. Something native from Crocoblock that is linked to the custom variables created by JetEngine would be much more efficient. 

PS: I've double-checked with Crocoblock support about this plugin and they are aware that it doesn't work very well with JetEngine.

**Comment by kaskad88** [comment]
I merged this issue with #755, which is on the same subject so we could deal with it more efficiently.
