### ISSUE TITLE
JetSmartFilters - Since 3.5.3 the check icon is missing for selected elements

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#7673]
OS: Windows 11
WordPress: 6.6.1
Bricks: 1.9.9
Browser: Chrome, Firefox etc.

Hi,

I have noticed a bug in the latest version.

I have updated SmartFilters from 3.5.1 to 3.5.3 and since then the check icon is no longer displayed for selected elements. But it could also be that it already occurred with 3.5.2

![grafik](https://github.com/user-attachments/assets/49cbd4e5-f9b2-425c-9af3-d37aeb931ba6)

![grafik](https://github.com/user-attachments/assets/48a5ee77-8f4b-4c42-9d19-2f1bae58d96a)

**Comment by Crocoblock** [comment]
Hi @hb81010 

This is a known bug, a fix will be in JetSmartFilters 3.5.4

Thanks for the report!

**Comment by Crocoblock** [comment]
was fixed and relaesed in JetSmartFilters 3.5.4
