### ISSUE TITLE
Add Dynamic visibility feature to meta fields in CPT

### ISSUE THREAD

**Issue by pintolog** [CrocoBlock/suggestions#7684]
I have CPT with JetEngine and i want to display the fields by the category that the user will choose.
For example, if the user choose category "VIDEO" field 1+2 will displayed
If the user choose Digital files field 3 will be displayed

Can you please add to CPT a feature of Dynamic visibility ?

![image](https://github.com/user-attachments/assets/ca8a0a1e-f1fb-4c33-a8b2-ec1a7d3cb434)

This feature exist in ACF:
https://www.advancedcustomfields.com/resources/conditional-logic/

**Comment by nkedem138** [comment]
+1

**Comment by Crocoblock** [comment]
Hi

to solve this problem, you can use metaboxes with conditional logic in metaboxes https://i.imgur.com/Nn6RZPI.png 

You cal also use conditional logic in meta-fields https://i.imgur.com/MWwvqp8.png , but it only works with other fields
