### ISSUE TITLE
Bug - JetTricks & JetPopup: Sticky Column interferes with Popup

### ISSUE THREAD

**Issue by cookiemachine** [CrocoBlock/suggestions#7686]
When "sticky column" (Jet Tricks) is activated, it interferes with any Popups that are opening in the area of the sticky column (sticky column is still visible and the Popup lies below the column / can't be seen properly).

**Comment by Crocoblock** [comment]
Hi @cookiemachine 

You need to change the z-index in the popup https://i.imgur.com/t51Ho4l.png

**Comment by cookiemachine** [comment]
> Hi @cookiemachine
> 
> You need to change the z-index in the popup https://i.imgur.com/t51Ho4l.png

Thank you!
