### ISSUE TITLE
JetEngine feature request - Dynamic repeater preview visable in listing item

### ISSUE THREAD

**Issue by rondondenderon** [CrocoBlock/suggestions#7694]
A preview of Dynamic repeater content inside a listing item.
This would improve the design capabillity.

![Scherm­afbeelding 2024-08-16 om 13 45 03](https://github.com/user-attachments/assets/5adfa83f-0596-4a19-a59f-3c9ad6993372)

When using a repeater in a post to give the backend user the capability to ad content blocks. And displaying them with a JetEngine listing. In the listing item the is no preview of the content inside one of these repeaters.

![Scherm­afbeelding 2024-08-16 om 13 46 56](https://github.com/user-attachments/assets/4130a839-fc7a-43da-a6e1-06feca4f1a87)
![Scherm­afbeelding 2024-08-16 om 13 46 32](https://github.com/user-attachments/assets/c4dcac1d-1734-4a2d-945e-83e3a3519db9)

**Comment by Crocoblock** [comment]
Hi @rondondenderon 

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue, some screenshots of your query settings, listing settings? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
