### ISSUE TITLE
Upgrade Particle Effects to Support tsParticles Library

### ISSUE THREAD

**Issue by vipe3** [CrocoBlock/suggestions#7696]
**Description**:

Before submitting this feature request, I have verified that the current implementation of Jet Tricks only supports the older `particles.js` library, which limits the potential for more advanced and visually appealing effects.

**Feature Request**:
Please consider upgrading the particle effects in Crocoblock, specifically in Jet Tricks, to support the newer `tsParticles` library. This library offers a wide range of features beyond what `particles.js` provides, such as confetti, fireworks, and other dynamic particle effects that can significantly enhance the visual appeal of websites.

**Why This is Important**:
- **Enhanced Functionality**: tsParticles allows for more complex and customizable effects, such as confetti explosions on thank-you pages, fireworks for special events, and much more, which are not possible with the older library.
- **Competitive Advantage**: Competitors, such as the Premium Addons for Elementor, have already integrated tsParticles, making their plugins more attractive for users looking for advanced visual effects. Without this update, Crocoblock might fall behind in offering cutting-edge design capabilities.
- **Ease of Transition**: tsParticles is backward compatible with `particles.js`, meaning the transition should be straightforward while offering a significant upgrade in terms of performance and capabilities.

**Example of Existing Implementations**:
- Premium Addons for Elementor already utilizes tsParticles in their particles section add-on, allowing for a broader range of visual effects that are currently not possible with Jet Tricks.

For more details on the advantages of tsParticles over `particles.js`, you can refer to the [tsParticles GitHub repository](https://github.com/tsparticles) and [this article](https://dev.to) discussing its benefits.

**Attachments**:
Feel free to explore additional resources or demo configurations from the [tsParticles documentation](https://particles.js.org/samples).

**Comment by Crocoblock** [comment]
was added and released in JetTricks 1.5.0
https://imgur.com/FsT0YQj
