### ISSUE TITLE
Jetengine - CCT query no longer works with multiple items separated by commas

### ISSUE THREAD

**Issue by fatguts** [CrocoBlock/suggestions#7700]
Since v3.5.2 of Jetengine, the CCT query section has a minor bug. Running a query from the Listing Grid where you have multiple items separated by commas no longer works as it should. 
If these values are text fields, none of the items are shown in the Listing Grid. If the values are numeric, only the first item in the list is displayed in the Listing Grid, and everything after the first comma is ignored. 

**Steps to reproduce the behavior:**
Set up a CCT, and add fields such as a "CCT Name" as a text field, and "CCT Rank" as a number field.
Add one item to the CCT, adding values such as "Test1" to the "CCT Name" field, then "1" to the "CCT Rank" field. Add another item to the CCT, adding values such as "Test2" to the "CCT Name" field, then "2" to the "CCT Rank" field.

Go to a page, and insert a Listing Grid. Chose the newly set up CCT as the source.

Do a Content Type Query on the Listing Grid - set the query to the "CCT Name" field, and add "Test1,Test2" to the Value field. You will see that it displays nothing in the List Grid. 
If you change the query value to either "Test1" or "Test2 it will display each individually. 

Change the query to the "CCT Rank" field, and add "1,2" to the Value field. You will see that it only displays the first item in the Listing Grid, and ignores everything else after the first comma.
This has been happening since v3.5.2 of the plugin. Reverting to v3.5.1 fixes both these issues. 

**Notes:**
Having compared v3.5.1 and v3.5.2 plugins, I discovered the file here is the offending culprit: includes\modules\custom-content-types\inc\factory.php
Specifically, a few rows of code from line 167 has changed:

v3.5.1:
```
				if ( ! is_array( $value ) ) {
					$value = preg_split( '/(?<=[^,]),[\s]?/', $value );
				}

				array_walk( $value, function( &$item ) {
					$item = str_replace( ',,', ',', $item );
				});

				if ( 1 === count( $value ) ) {
					$value = $value[0];
				}
```

v3.5.2
```
				$array_operators = array( 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN' );

				if ( ! is_array( $value ) && in_array( $operator, $array_operators ) ) {
					$value = preg_split( '/(?<=[^,]),[\s]?/', $value );

					array_walk( $value, function( &$item ) {
						$item = str_replace( ',,', ',', $item );
					});

					if ( 1 === count( $value ) ) {
						$value = $value[0];
					}
				}	
```			

So that code above is causing the issue.

**Comment by ihslimn** [comment]
have you set it up like

some_field
LIKE (or Equal)
1,2,3

if so, then you just need to change operator to IN

The change in 3.5.2 was introduced because before the change, if you had field with values like "Foobar str., 123"
and set is as above, it turned into

some_field
LIKE
array("Foobar str.", "123")

making it impossible to correctly query by text fields containing commas.

Do you have a lot of queries set up like I described?
It may be that we will find a way to correct operators, and give you some script to do that automatically, but I believe it is better to review the queries and change operators from LIKE/Equal to IN.

**Comment by fatguts** [comment]
Hi,

Thanks for the quick response. 

> have you set it up like
> 
> some_field
> LIKE (or Equal)
> 1,2,3
> 
> if so, then you just need to change operator to IN

Correct, that is how I had it working before.

> The change in 3.5.2 was introduced because before the change, if you had field with values like "Foobar str., 123"
> and set is as above, it turned into
> 
> some_field
> LIKE
> array("Foobar str.", "123")
> 
> making it impossible to correctly query by text fields containing commas.

Ok, I can see why that needed to be changed. 

> Do you have a lot of queries set up like I described?
> It may be that we will find a way to correct operators, and give you some script to do that automatically, but I believe it is better to review the queries and change operators from LIKE/Equal to IN.

Only 5 or 6, so it's easy to change them over. It is working fine with the IN operator as you specified, so I'll close this thread.
Thanks again for the quick support!
