### ISSUE TITLE
Show terms only for logged in user

### ISSUE THREAD

**Issue by andyprakash9** [CrocoBlock/suggestions#7702]
After Crocoblock support told me that this feature does not exist as yet I would like to point out below one shortcoming of the Terms Query in Query Builder.

My multi user (author role) site has access to the same CPT and same Taxonomy connected to that CPT. But they are not allowed to access each other's posts since this is a company internal website. Only the Editor role can see all of the users and their posts and taxonomies.

In my taxonomy archive page I used a listing grid to show the taxonomy item with its description and meta fields and post count in each term. I do not want the logged in user to see the terms in this archive page where he has not created any posts. I thought it would be an easy fix but apparently Crocoblock Customer Care told me it can't be done.

Upon exploring Terms Query in depth I realised there is no way I can set it up so it can only show terms which have posts by the queried or current user.

Request you to kindly add this feature as soon as possible as this would increase the power and flexibility of Terms Query.

Thanks and regards
Anand

**Comment by MjHead** [comment]
This feature is not supported by core WP_Term_Query class, so we can't implement it as part of Terms Query. You can try to use advanced SQL mode and AI query generator (or plain ChatGPT) to generate required SQL query and than cast tis query results into the WP_Term object, this will force the advanced sql query return results similar to WP_Term_Query

**Comment by andyprakash9** [comment]
Thank you for the reply. I will see if I can manage to make it work.
