### ISSUE TITLE
JetAppointments Google Calendar(s) sync

### ISSUE THREAD

**Issue by ImAlbatross** [CrocoBlock/suggestions#7703]
Last post about this was in 2020, But  I would live for appointments to be able to sync with a google calendar. Reason being that i would love for clients to schedule meeting with me, and outside work i get sent i accept to my google calendar, like events and photo sessions with a company I am partnered with. They schedule me with a google invite, and biggest thing is trying to then go in a block out that day or even weeks in the jetappointment is a little cumbersome. Appreciate it Croco Team :)

**Comment by Crocoblock** [comment]
Hi @ImAlbatross 

I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/3517)
