### ISSUE TITLE
JetEngine - Image and Gallery meta fields - AVIF images don't show up - Please add image/avif to your MIME type list

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#7706]

**Comment by ihslimn** [comment]
coulf you please give some more info on how to recreate the issue?
it seems that AVIF is being displayed in Dynamic Image correctly, as well as in Dynamic Field

**Comment by ghost** [comment]
No, I mean in the backend. When you have a gallery field, AVIF images aren'T shown there but a gray placeholder. Everything works on the frontend. It's just the backend

**Comment by ihslimn** [comment]
oh, I see now. thank you for reporting!
fixed, will be in one of the next versions

**Comment by Crocoblock** [comment]
Released in JetEngine 3.5.6
