### ISSUE TITLE
Since 3.5.2 - Querys only return 1st result

### ISSUE THREAD

**Issue by tyekynan** [CrocoBlock/suggestions#7707]
**Describe the bug**
I have MULTIPLE queries that only return the first result (when there are multiple results). I can revert jetengine back to 3.5.1 and everything works fine.

**To Reproduce**
Custom Content Type Query
From CCT
_QUERY_
Field = Item ID
Compare = Equal
Value = Related Items - From Relation - Child Object - Query Variable - cct_id

**Expected behavior**
I go to the page of the parent, there is a query variable in the URL. The page should have multiple child items in the table.
This works on 3.5.1, but if I update to 3.5.2 or newer, it only shows the first result.

**Screenshots**
Not Available

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 128.0.6613.84 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not Available

**Additional context**
The example query given is not the only query I have where this happens. It seems all of my related queries are doing this. I have disabled all plugins except jetengine and the problem persists. The only fix is reverting back to 3.5.1

**Comment by Crocoblock** [comment]
@tyekynan [check it out please](https://github.com/Crocoblock/suggestions/issues/7700#issuecomment-2302118858)
