### ISSUE TITLE
Custom Meta Storage (Beta) does not work with Product (woocommerce Built-in post type)

### ISSUE THREAD

**Issue by hicham1989s** [CrocoBlock/suggestions#7712]
Hi there,

I love the Custom Meta Storage (Beta), however when it is enabled for the Product  (woocommerce Built-in post type) it does not store it in into the Custom DB table but instead it just adds the meta field data into wp_postmeta as if the Custom Meta Storage is not enabled.

This is very unfortunate as I need this working to save database size. 

![customdb-jetengine](https://github.com/user-attachments/assets/10cbe087-d853-4ca6-b282-721e9349e7f8)

**Comment by MjHead** [comment]
At the moment Custom Meta Storage can handle only meta fields added with JetEngine UI to the CPT where this Storage is enabled, so it can't handle whole list of the fields related to the CPT (including built-in fields ow the WooCommerce Products)

**Comment by mateitudor** [comment]
"closed as completed" but it's not completed...
