### ISSUE TITLE
Add the CPT  List of posts as a taxanomy for blog categories

### ISSUE THREAD

**Issue by iamabhishekgarg** [CrocoBlock/suggestions#7713]
Add the CPT  List of posts as a taxanomy for blog categories

![image](https://github.com/user-attachments/assets/61bd7679-50f5-4dd0-b946-77134c49f62f)

**Comment by Crocoblock** [comment]
Hi @iamabhishekgarg 

Please describe your issue in more detail, add some one more screenshots. Thank you!
