### ISSUE TITLE
JetWooBuilder - Checkout - Note field missing

### ISSUE THREAD

**Issue by mateitudor** [CrocoBlock/suggestions#7714]
**Describe the bug**
Not sure if it's a bug or an omission but at the checkout, the customer note field is missing.

**To Reproduce**
1. Create a custom checkout page with JetWooBuilder
2. Add all the components for testing
3. View page

**Expected behavior**
A customer note field should appear on the page.

**Desktop (please complete the following information):**
 - Agnostic

**Smartphone (please complete the following information):**
 - Agnostic
 
**Additional context**
JetWooBuilder 2.1.14

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
