### ISSUE TITLE
Meta Box screen not loading

### ISSUE THREAD

**Issue by lucasvinni97** [CrocoBlock/suggestions#7716]
**Describe the bug**
When you go to Jet Engine > Meta Box > Add New or editing existent one the screen not loads. It show blank screen. On the console appear follow error message to vue related issue:

"vue.js?ver=2.6.11:634 [Vue warn]: Property or method "window" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

(found in <Root>)
vue.js?ver=2.6.11:634 [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'JetEngineWCMBConfig')"

(found in <Root>)
vue.js?ver=2.6.11:1897 TypeError: Cannot read properties of undefined (reading 'JetEngineWCMBConfig')
    at Proxy.eval (eval at createFunction (vue.js?ver=2.6.11:11649:14), <anonymous>:72:439)
    at Vue._render (vue.js?ver=2.6.11:3551:24)
    at Vue.updateComponent (vue.js?ver=2.6.11:4067:23)
    at Watcher.get (vue.js?ver=2.6.11:4478:27)
    at Watcher.run (vue.js?ver=2.6.11:4553:24)
    at flushSchedulerQueue (vue.js?ver=2.6.11:4311:15)
    at Array.<anonymous> (vue.js?ver=2.6.11:1989:14)
    at flushCallbacks (vue.js?ver=2.6.11:1915:16)"

**To Reproduce**
1. Go to Wp Admin '...'
2. Jet Engine > Meta Box
3. Add New or Edit 

**Screenshots**
![s1](https://github.com/user-attachments/assets/79526741-27c3-411f-ad5d-5b64b883db74)

**Desktop (please complete the following information):**
 - Chrome 128.0.6613.113

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.
