### ISSUE TITLE
JetPopup completely missing Close button styling options

### ISSUE THREAD

**Issue by Joe-Bloggs** [CrocoBlock/suggestions#7718]
'Close button' styling options are completely missing in JetPopup. 

<img width="1511" alt="Screenshot 2024-09-02 at 11 16 11 am" src="https://github.com/user-attachments/assets/9f3aec9f-2287-4285-9179-e6d1806b6574">

**Comment by Floydtm** [comment]
We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue.

**Comment by Crocoblock** [comment]
@Joe-Bloggs 
we were able to reproduce this problem ourselves and pass the issue to dev

**Comment by Crocoblock** [comment]
fixed in JetPopup 2.0.7
