### ISSUE TITLE
bug in jet engine queries in all versions after 3.5.0

### ISSUE THREAD

**Issue by saqi-sn** [CrocoBlock/suggestions#7719]
**Describe the bug**
I have some CCTs which are related to some pf my CPTs via a one to many relation in order to show them in a single CPT template created with elementor I use the jet tabs accordion widget with the query. but at both query preview or the frontent it only shows the latest item, ONE ITEM ONLY. its specialy  problem when the latest CCT in draft as the query doesnt care that I have selected to only show the published items. this problem is happening in all the versions after 3.5.0, I saw that you have changed something about the related items and query builder in version 3.5.1 it might have something to do with that.
Thank you for the great product
**To Reproduce**
1. Go to : create a related CCTs query in the query builder and use it with jet tabs. I use the related items dynamic tag in the query builder which works fine in version 3.5.0

**Expected behavior**
showing all the related CCTs

**Comment by Crocoblock** [comment]
Hi @saqi-sn 

Please, check this https://github.com/Crocoblock/suggestions/issues/7700#issuecomment-2302118858
