### ISSUE TITLE
FacetWP Hierarchy Select addon Like Feature (checkbox, dropdown) Request

### ISSUE THREAD

**Issue by MagicaDaGipnoz** [Crocoblock/suggestions#772]
The hierarchy feature is requested a while a go on youtube 
https://www.youtube.com/watch?v=F00H7xn8PF4

The feature is requested for destinations page (listing country) for themes like Travengo (
removed from Crocoblock demo content list )
https://crocoblock.com/templates/

Main idea is to have a possibility to filter tours only by Region or only by country or only by city. 
- Region 
- - Country
- - - City 

Example 
https://facetwp.com/documentation/facets/facet-types/hierarchy/
https://facetwp.com/add-ons/hierarchy-select/

I am pretty much sure that the feature is THE Crocoblock missing feature for different types of websites.
Thank you

**Comment by Floydtm** [comment]
@MagicaDaGipnoz,  hi! Thanks for the report! We recently released a beta version of the plugin. It is available for download in your account. Here you can check out the changes https://github.com/Crocoblock/suggestions/issues/737
