### ISSUE TITLE
Day off does not work

### ISSUE THREAD

**Issue by niquini** [CrocoBlock/suggestions#7720]
JETBOOKING

![Captura de Tela 2024-09-02 às 18 16 26](https://github.com/user-attachments/assets/1a2cdc9e-387f-42af-a1f3-819de226ca0b)

Why doesn't the calendar appear to select the days I want to book for reservations?

**Comment by Crocoblock** [comment]
Hi @niquini 

We've tried to reproduce your issue and everything works fine on our side. have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you

**Comment by UraraReika** [comment]
Hello @niquini. Thanks for the feedback.

If I understand your request correctly than i should notice you that this is not how this functionality works. This is probably what you need - https://github.com/Crocoblock/suggestions/issues/1586.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

You can also use this article for better understanding how this functionality works - https://crocoblock.com/knowledge-base/jetbooking/how-to-manage-days-and-weekends-in-booking.

Right now I merged this issue with [[issue]](https://github.com/Crocoblock/suggestions/issues/1586), which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.

Thank you for your understanding.

**Comment by niquini** [comment]
The problem is that I can't select the dates to close (day off). The fields are locked

> Em 3 de set. de 2024, à(s) 11:47, Oleksandr Rudyi ***@***.***> escreveu:
> 
> Hello @niquini <https://github.com/niquini>. Thanks for the feedback.
> 
> If I understand your request correctly than i should notice you that this is not how this functionality works. This is probably what you need - #1586 <https://github.com/Crocoblock/suggestions/issues/1586>.
> 
> Please follow guidelines for opening a new feature request <https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md>, so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.
> 
> You can also use this article for better understanding how this functionality works - https://crocoblock.com/knowledge-base/jetbooking/how-to-manage-days-and-weekends-in-booking.
> 
> Right now I merged this issue with [issue] <https://github.com/Crocoblock/suggestions/issues/1586>, which is on the same subject so we could deal with it more efficiently. Please feel free to continue the conversation there.
> 
> Thank you for your understanding.
>

**Comment by niquini** [comment]
Ninguém passa por isso? Não consigo selecionar os dados que não quero vender (dia de folga). Os campos de seleção de dados estão bloqueados

  ![ Uploading Screenshot 2024-09-18 às 23.50.21.png...]()

**Comment by niquini** [comment]
https://crocoblock.com/knowledge-base/jetbooking/how-to-manage-days-and-weekends-in-booking/#pid=2


In this link we can select the data and they are blocked. This must be something related to configuration
