### ISSUE TITLE
JetSmartFilter - Check Range Filter - Labels for manual ranges

### ISSUE THREAD

**Issue by bcasni** [CrocoBlock/suggestions#7723]
I would like to add labels to my manually added range options. 

I.e. 1-3 "low"; 4-6 "middle"; 7-10 "high"

This is possible in the visual filter, but the visual filter cannot handle ranges.

**Comment by Crocoblock** [comment]
Hi @bcasni 

I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7658)
