### ISSUE TITLE
Add a stripe subscription payment plan with jet form builder

### ISSUE THREAD

**Issue by jabedkhan** [CrocoBlock/suggestions#7726]
**Please, describe the feature request, making it clear to understand.**

To get payment from Stripe we can integrate this with the normal way that is okay to get only one time or a certain amount of payment. But most of the time we need to add the subscription option with the stripe. In Stripe we have an option to create a subscription product that we can get payment weekly, monthly, or yearly in a requiring way. 

So we need to integrate the subscription model for Stripe with the Jet Form Builder. I think it will help us to grow our business.

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/6293)
