### ISSUE TITLE
JetMenu more options to mobile

### ISSUE THREAD

**Issue by Digital03** [Crocoblock/suggestions#773]
Hi.

Why not to have an options where add and order simly "widgets" for show over and under menú, or in the bottom of layer, like a search box, a text box (or shortcodes), copyright, logo, button, social icons... 

Other idea was a template block selection for show in these zones. 

Example idea of mobile menu as i mean:

Logo
Search bar
Menu

Lang flags (by shortcode)
Social Icons

**Comment by Digital03** [comment]
A more clean example of mobile menu layer:

Template over
Menú Block
Template under

Template footer

**Comment by shinTM** [comment]
Done v 2.0.0 https://prnt.sc/r8er58
