### ISSUE TITLE
Asterix (Required Field Indicator) Appears Before Entrance Animation Completes in JetWooBuilder Widgets

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7732]
Bug Description:
When using the JetWooBuilder plugin to customize the "My Account" page in WooCommerce, I noticed an issue with the display of the asterisks (indicating required fields). Specifically, when I add an entrance animation to a container holding widgets like the Edit Account or Edit Shipping/Address widgets, the asterisks appear before the rest of the widget and the page content.

This issue occurs when the container has an entrance animation applied (e.g., fade-in). The rest of the content animates correctly, but the asterisks appear prematurely, which creates a visually inconsistent experience, as shown in the attached screenshot.

I also encountered the same behavior when applying an entrance animation to the Register Form created using JetFormBuilder. However, for the register form, I have worked around the issue by hiding the asterisks using custom styles. Still, this could provide additional insight into the overall issue.

Steps to Reproduce:
Navigate to the My Account page.
Add the Edit Account, Edit Address/Shipping widget via JetWooBuilder, or Register Form using JetFormBuilder.
Apply an entrance animation (e.g., fade-in) to the container that holds the widget.
Load the page and observe the animation.
Notice that the asterisks appear before the rest of the widget finishes loading.

Expected Behavior:
The asterisks should be animated along with the rest of the widget content and only appear once the entire widget is visible, not before the rest of the animation finishes.

![Posnetek zaslona 2024-09-09 185359](https://github.com/user-attachments/assets/4d454c30-9dd1-41a6-9053-10264087b788)

![Posnetek zaslona 2024-09-09 193047](https://github.com/user-attachments/assets/175fcf67-8c4b-4f99-9704-fb3af6c73c10)

Desktop Information:
OS: Windows 11
Browser: Chrome, Edge
Version: Latest versions
Mobile Information:
Device: Samsung Galaxy A71
Browser: Chrome

Additional Context:
This issue appears to be related to the animation applied to the container and seems to affect multiple JetWooBuilder widgets. It also occurs with the JetFormBuilder Register Form, although the issue is less noticeable there due to a workaround. I haven't tested all the widgets, but so far, this happens with the Edit Account, Edit Shipping widgets, and Register Form.

**Comment by Crocoblock** [comment]
done in the JetWooBuilder 2.1.15
