### ISSUE TITLE
Ability to save meta boxes as array

### ISSUE THREAD

**Issue by TheBigBanik** [CrocoBlock/suggestions#7736]
Hi, it would be great if there was an option in the meta boxes to select if all fields should be saved as an array or not. like the repeater field that has the ability to save in separate fields but the opposite. That way, a CPT for business for example could have 2-3 meta fields but with multiple fields inside in the array to reduce the size of databases.

**Comment by MjHead** [comment]
Hi! Thanks for you suggestion, but this functionality will cause a lot of compatibility issues (with other JetEngine components, with other Crocoblock plugins and even with WordPress core logic in some cases). As alternative you can use Custom Meta Storage - it also will reduce DB size, but keep your meta fields compatible with Query Builder, filters and getting/updating data with WordPress meta fields API - get_post_meta(), update_post_meta() etc.
