### ISSUE TITLE
Advanced Validation is unusable, change to onBlur

### ISSUE THREAD

**Issue by cwinkler8** [CrocoBlock/suggestions#7741]
Currently, the advanced validation in JetFormBuilder is essentially unusable and inefficient. The live validation does a server-side callback after every couple of keystrokes. The experience is terrible on a desktop and unusable on a mobile device.

1. Create a form with Email field
2. Add advanced validation to email field > server-side callback > Is_user_email_unique
3. Save the form
4. Slowly type a few letters to see how frustrating it is
5. Try it on mobile

https://github.com/user-attachments/assets/be759fa2-06a0-48e0-86d5-a665361bbca9

**Comment by Crocoblock** [comment]
added in JetFormBuilder 3.4.3
