### ISSUE TITLE
Unable to Remove or Style Border in JetWooBuilder Account Widgets (Account Downloads and Orders Widgets)

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7743]
Describe the bug
In the JetWooBuilder plugin, multiple widgets related to the "My Account" section, including "Account Downloads" and "Account Orders," display an automatic border that cannot be removed or styled. The border persists despite attempts to adjust the border settings to "None" or set the border width to 0px. The issue has been observed in both the "Account Downloads" and "Account Orders" widgets, but it may also affect other widgets that have not been tested yet.

To Reproduce

Go to the Elementor editor using JetWooBuilder.
Add the "Account Downloads" or "Account Orders" widget to a page.
Try to remove or modify the widget's border by setting it to "None" or by setting border width to 0px.
Observe that the border remains visible on the front end despite the settings.
Expected behavior
The border should either be completely removed or styled according to the user's custom settings (border type, width, and color). Users should be able to control the appearance of the border in line with the design of their website.

Screenshots
![Posnetek zaslona 2024-09-13 080024](https://github.com/user-attachments/assets/e7e42803-022e-47e7-8e67-38ef3b7ca38f)
![Posnetek zaslona 2024-09-13 080039](https://github.com/user-attachments/assets/46dacf1e-a196-42ee-85e7-205dbc1b38bc)
![Posnetek zaslona 2024-09-09 212258](https://github.com/user-attachments/assets/40869650-5e52-4cf1-b2a5-1be8b6cdb0f7)
![Posnetek zaslona 2024-09-09 212307](https://github.com/user-attachments/assets/47afbb06-8474-483d-bed5-a28b1360682a)
![Posnetek zaslona 2024-09-09 212351](https://github.com/user-attachments/assets/f31e2c08-0ff0-47d1-8148-cdc0b822cbd8)

OS: Windows 11
Browser: Chrome and Edge
Version: Latest versions
Smartphone (please complete the following information):

Device: Samsung Galaxy A series (Exact model unknown, possibly A71 or A75)
OS: Android
Browser: Chrome
Version: Latest version
Additional context
This border issue is not critical but would be good to address, as it affects the design consistency of the page. Ideally, users should have control over whether the border is displayed and how it is styled. The problem has been confirmed for "Account Downloads" and "Account Orders" widgets, but it may also affect other JetWooBuilder widgets related to the "My Account" section.

**Comment by Crocoblock** [comment]
done in the JetWooBuilder 2.1.15

**Comment by jenko-code** [comment]
hello. that works. nice ;)
