### ISSUE TITLE
Feature Request: More Styling Options for Empty Message in JetWooBuilder My Account Widget (account downloads and account orders widgets)

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7744]
Hi Crocoblock team,

I would like to request more styling options for the "Empty Message" in the JetWooBuilder "Account Downloads" and "Account Orders" widgets. Currently, there are limited styling options for the empty message, as shown in the attached screenshots. Specifically, I would like to be able to:

- Change the position of the button, text, and icon more freely.

- Have the ability to place elements like the button and text in the center of the widget, especially to avoid large empty spaces below the content.

- Customize the icon or even remove it entirely, as I’ve set it to transparent in my case due to the lack of styling options.

These are my style setting in the backend:
![Posnetek zaslona 2024-09-13 095752](https://github.com/user-attachments/assets/3b91a2fa-d27f-484f-847d-e0318b93c04a)
![Posnetek zaslona 2024-09-13 095829](https://github.com/user-attachments/assets/09dc7033-4899-4f91-a4be-e9c3bda6bb30)
![Posnetek zaslona 2024-09-13 095839](https://github.com/user-attachments/assets/78aea019-a39c-400b-bc20-db2cff74ca46)
![Posnetek zaslona 2024-09-13 100041](https://github.com/user-attachments/assets/3dee79bc-a6d4-4998-9f25-08eebd28d7fb)
![Posnetek zaslona 2024-09-13 100048](https://github.com/user-attachments/assets/73d67e41-fb84-449b-909e-d0b0e13fe83a)

I have attached two examples from the front end:

1. One showing how the empty message looks with the original settings.
![Posnetek zaslona 2024-09-13 115631](https://github.com/user-attachments/assets/3c0f52c5-d5d1-4db0-9f27-8ba2e778ac1c)

2. Another showing how it looks after applying a code snippet to adjust the styling. Even though the snippet helps a bit, it would be much more user-friendly if these styling options were built into the widget settings, reducing the need for custom code.
![Posnetek zaslona 2024-09-13 115358](https://github.com/user-attachments/assets/341dabb9-582d-40ee-adbf-6f0a0573ddc8)

Here is the code snippet I am currently using:

.elementor-jet-myaccount-order.jet-woo-builder .woocommerce-info {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%; /* Adjust if necessary to ensure it takes the full height of the container */
    text-align: center;
    gap: 20px; /* Add a 20px gap between the elements */
    margin-bottom: -15px; /* Add a -50px margin to the bottom */
}

.elementor-jet-myaccount-downloads.jet-woo-builder .woocommerce-info {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%; /* Adjust if necessary to ensure it takes the full height of the container */
    text-align: center;
    gap: 20px; /* Add a 20px gap between the elements */
    margin-bottom: -15px; /* Add a -50px margin to the bottom */
}

While this is not a critical issue, it would be great if, in the future, more advanced styling controls could be added to make it easier to position elements like the button and text without relying on custom code snippets. This would allow for more consistency in design and better control over the widget appearance.

Thank you for considering this feature request!

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
