### ISSUE TITLE
[Bug] - A category (9) is automatically assigned to the post.

### ISSUE THREAD

**Issue by anis-infowind** [CrocoBlock/suggestions#7746]
**Describe the bug**
When a post is published or updated, a category (9) is automatically assigned to the post.

![Pasted image (2)](https://github.com/user-attachments/assets/7d93d8b8-1129-499c-bc0a-c25595438328)

**Comment by Floydtm** [comment]
Describe your request in more detail, if possible, add screenshots or video. Thank you!

**Comment by anis-infowind** [comment]
@Floydtm 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Add New Post'
2. Select a Category
3. Click on 'Publish' button
4. See error 'a category with number' will automatically be added

![image](https://github.com/user-attachments/assets/f9f7ed4c-d529-4e30-994a-327f6b703dc8)
![screenshot-www_infowindtech_com-2024_09_23-16_21_33](https://github.com/user-attachments/assets/94bb6e44-ae93-4e17-be7e-30d77801f6a3)
