### ISSUE TITLE
Inconsistent Margins in JetWooBuilder Archive Templates

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7747]
Hi Crocoblock team,

I’m experiencing several issues with margins and spacing when using JetWooBuilder templates for upsells and cross-sells. The issues are inconsistent and vary between different websites and pages, making them difficult to replicate consistently. Here are the details:

**1. Archive Thumbnail Bottom Margin**
There is an automatic bottom margin applied to the archive thumbnail, which I have not set. This margin is visible and may become disruptive depending on the layout. I wanted to bring this to your attention, as this behavior might not be as intended.
![Posnetek zaslona 2024-09-13 140349](https://github.com/user-attachments/assets/55be0634-2eb7-4041-824b-79f485140d3f)
![Posnetek zaslona 2024-09-13 140359](https://github.com/user-attachments/assets/940dc00c-a80c-492c-9f64-a9b842784af8)
![Posnetek zaslona 2024-09-13 140519](https://github.com/user-attachments/assets/5f2ee557-7153-48ba-bfef-2562b2f60ef5)

**2. Add to Cart Button Top and Bottom Margins**
This is the more critical issue. In the JetWooBuilder template, a large bottom margin appears in the back end for the "Add to Cart" button, even though it hasn’t been configured.

On the front end, however, the behavior is different:

The bottom margin does not appear on the front end, but a top margin is consistently shown.
This top margin appears across all areas, including upsells and cross-sells.
![Posnetek zaslona 2024-09-13 140339](https://github.com/user-attachments/assets/db76242e-e6e1-4441-af3c-b7c0014bad73)
![Posnetek zaslona 2024-09-13 151102](https://github.com/user-attachments/assets/61bf9213-892b-4f1f-91ff-61bf434d6dba)
![Posnetek zaslona 2024-09-13 152259](https://github.com/user-attachments/assets/c20030eb-15cc-450c-a004-1f094c246ce5)
![Posnetek zaslona 2024-09-13 152307](https://github.com/user-attachments/assets/a15218cf-010b-4b5a-8e16-c5ddb0dbf1f6)
![Posnetek zaslona 2024-09-13 140438](https://github.com/user-attachments/assets/d9b5233d-4ef6-40fa-8388-1fa790020a37)

**3. Quantity Selector Not Displaying on Upsells**
I’ve encountered an issue where the Quantity Selector does not appear on the front end for upsells, even though it is enabled in the back end. As shown in the attached screenshots:

The Quantity Selector is enabled in the back-end settings with both the increase and decrease icons (+ and -), but these buttons do not appear on the front end for upsells.
The issue only occurs with upsells. On other areas of the site, the quantity selector works and appears as expected.
![Posnetek zaslona 2024-09-13 135919](https://github.com/user-attachments/assets/dd5b749e-4f1a-4010-a479-6d196c445bfa)
![Posnetek zaslona 2024-09-13 154532](https://github.com/user-attachments/assets/a785dec9-0b87-4599-bce1-a373f2c812cf)

**4. Unexpected Large Gaps Between Products**
On one of my websites, I’m also noticing large gaps between products in both upsells and cross-sells. These gaps cannot be controlled through Elementor settings. Strangely, this issue did not exist a few weeks ago, and I now see it appearing randomly, even though all plugins are updated, cache has been cleared, and nothing has changed in the settings.

Even more confusing is the fact that this issue does not appear on another website, despite having the same setup, plugins, and settings. This makes it seem like something unusual is happening, which I hope we can resolve together to better understand the root cause.
![Posnetek zaslona 2024-09-12 172828](https://github.com/user-attachments/assets/f1b19b2b-f3e2-4357-9d7c-a3faae25a418)

This gap between the products remains even when I resize the browser window. The gap creates a very odd effect, and I’m unable to modify or adjust it through any settings in the back end.
![Posnetek zaslona 2024-09-13 155104](https://github.com/user-attachments/assets/58e97908-b8c0-46bc-bde4-99daad538e37)

**5. JetWooBuilder vs JetEngine**
I’m using JetWooBuilder templates exclusively for upsells and cross-sells, so I am not sure how these templates would behave on other pages like the shop page. However, I have created an identical template using JetEngine Listings/Components, where the behavior is more consistent:

In JetEngine, the "Add to Cart" button does not experience the same top or bottom margin issues.
The only remaining issue in JetEngine is the bottom margin for the archive thumbnail, which still persists but is less problematic.
This indicates that the margin issues in JetWooBuilder are likely specific to how the plugin handles certain elements within upsells and cross-sells.
![Posnetek zaslona 2024-09-13 155936](https://github.com/user-attachments/assets/45242168-bb55-47e4-a336-afa561d28340)
![Posnetek zaslona 2024-09-13 160112](https://github.com/user-attachments/assets/d9aa0e5e-6d3f-4335-9d77-f9f087ea26f2)

**Conclusion**
I realize that these issues are inconsistent and difficult to replicate consistently across different environments. However, I hope that with the screenshots and details provided, we can start resolving these problems. I believe that once we address some of these margin and spacing issues, we will have a clearer path forward.

Please let me know if you need any more information or clarification. I appreciate your help with this!

**Comment by UraraReika** [comment]
1, 2 - Fixed;
3 - We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.
4 - This issue can be caused with theme that you used or with some plugin updates. If you didn't change ani setting gaps between product items than default WooCommerce gaps is used. You can set this gaps by using Archive Item settings like this - https://tppr.me/j2J75r to get this result - https://tppr.me/dunmco.

Thank you!

**Comment by Crocoblock** [comment]
done in the JetWooBuilder 2.1.15
