### ISSUE TITLE
JetWooBuilder "Archive Add to Cart" Icon Not Displaying on Both Back-End and Front-End

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7748]
Describe the bug:
The custom icon for the "Archive Add to Cart" button in JetWooBuilder does not display on either the back-end (Elementor editor) or the front-end. I have enabled the custom icon in the settings, but it doesn’t show up anywhere. The icon used to display correctly before, but I’m not sure when it stopped working as I haven’t worked on the website for some time.

To Reproduce:

Go to the JetWooBuilder template.
Add the "Archive Add to Cart" button and enable the custom icon in the settings.
Place the button in various sections (e.g., upsells, cross-sells, or wishlists).
Save and check both the Elementor editor and the front-end.
Notice that the custom icon is not displayed anywhere.
Expected behavior:
The custom icon should be visible on both the back-end (Elementor editor) and the front-end.

Screenshots:
I’ve attached screenshots showing the settings where the custom icon is enabled and the locations where it is applied, but it does not appear on either the back-end or front-end.
![Posnetek zaslona 2024-09-13 162418](https://github.com/user-attachments/assets/1eacfd76-f74c-43c6-b89d-613acd8addf4)
![Posnetek zaslona 2024-09-13 162441](https://github.com/user-attachments/assets/1b6409ec-b248-440c-94d8-5ff435c663c6)
![Posnetek zaslona 2024-09-13 162834](https://github.com/user-attachments/assets/49b1388d-391e-4bd2-9932-df0ddb17223d)
![Posnetek zaslona 2024-09-13 162902](https://github.com/user-attachments/assets/789f293f-0c9e-44eb-8658-852b3b415506)
![Posnetek zaslona 2024-09-13 163106](https://github.com/user-attachments/assets/796f33f1-e7a0-44f2-a617-5c04398aa4b0)
![Posnetek zaslona 2024-09-13 163148](https://github.com/user-attachments/assets/e886adf8-b81f-4120-a21e-4a8a6fcb1104)
![Posnetek zaslona 2024-09-13 163625](https://github.com/user-attachments/assets/ac2d1187-5c93-4335-92d2-b06e5afba992)
![Posnetek zaslona 2024-09-13 163631](https://github.com/user-attachments/assets/84a6d757-b0f6-445e-b19c-c85aa5da5071)

Desktop (please complete the following information):

OS: Windows 11
Browser: Chrome and Edge (latest versions)
Smartphone (please complete the following information):

Device: Samsung Galaxy A71
OS: Android
Browser: Chrome
Additional context:
This issue specifically affects the Archive Add to Cart button. I have tried it across different templates (upsells, cross-sells, wishlists), and the custom icon no longer appears. It used to work before, but I am unsure when it stopped displaying, as I haven’t worked on the website in a while.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!
