### ISSUE TITLE
Prevent Multiple Additions to Cart for Digital Products with Real-Time Button Update (with code that 100% works for Archive add to cart button)

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7750]
**Feature Description:**
I’ve created a code solution that prevents customers from adding a product to the cart more than once, solving a common issue in WooCommerce for digital products. WooCommerce already has a built-in feature to restrict a customer from purchasing more than one of the same product, but the problem arises when a customer clicks the "Add to Cart" button more than once. If this happens, the page refreshes, leading to a frustrating error message, which can discourage customers and lead to cart abandonment.
![Posnetek zaslona 2024-09-13 181810](https://github.com/user-attachments/assets/f1549f2d-2bf4-4103-9067-ca8131d3418f)

To solve this issue, I’ve created a fully responsive and synchronized solution that works perfectly across all devices and in real-time. My code prevents the customer from re-adding a product to the cart once it’s already added, avoiding page resets and error messages. Furthermore, this solution updates in real-time, even when:

- The "Add to Cart" button is moved (e.g., when using a layout switcher),

- The customer uses multiple tabs in the browser,

- The customer switches layouts of the screen,

- The customer opens a quick view popup.

**Why This Feature is Important:**
The current user experience when attempting to add a product more than once can be frustrating and lead to cart abandonment. By preventing unnecessary page reloads and error messages, this feature would provide a smoother checkout process. Many users and developers are searching for solutions to this issue, but no plugin currently offers a comprehensive fix. While some PHP snippets can block the button, they don’t synchronize across different tabs, devices, or layouts, and they don’t adapt to real-time actions such as removing the item from the cart.
![Posnetek zaslona 2024-09-13 181305](https://github.com/user-attachments/assets/ace5c3ed-e9ee-47cb-a65a-62c5e189e07e)
![Posnetek zaslona 2024-09-13 181314](https://github.com/user-attachments/assets/32611b61-2117-4fb8-9fe6-448e3ffd9c92)

**Custom Code and Adaptation:**
The code I’ve created specifically applies to the "Archive Add to Cart" button, and while it works perfectly for my use case, it may need to be adjusted for other types of "Add to Cart" buttons. The real-time updates work across all layouts and devices (desktop and mobile), and I’ve ensured that it synchronizes even when switching between different layouts or opening quick views. I am happy to share my code, but it might need further adaptation for other use cases.

**Purpose of Sharing the Code:**
My intention in sharing this code is to help Crocoblock improve its product by possibly integrating this feature into their plugins. I would love to see this functionality built directly into the JetWooBuilder plugin, as I believe it is an essential feature for many WooCommerce users, particularly those selling digital products. By preventing multiple additions to the cart and updating the button state in real-time across all contexts, this feature would significantly enhance the shopping experience.

**Example and Code:**
I’m including the code I created to solve this issue. Please note that it’s designed for the "Archive Add to Cart" button and may need adjustments for other buttons or use cases. However, I hope this code can serve as a useful starting point for integrating this feature into JetWooBuilder.

`add_action('wp_ajax_get_cart_items', 'get_cart_items');
add_action('wp_ajax_nopriv_get_cart_items', 'get_cart_items');
function get_cart_items() {
    // Get all items in the cart
    $cart_items = [];
    
    foreach ( WC()->cart->get_cart() as $cart_item ) {
        $cart_items[] = $cart_item['product_id'];
    }

    // Return the cart items as a JSON response
    echo json_encode($cart_items);
    wp_die();
}
`

`jQuery(document).ready(function($) {
    // Function to update add-to-cart buttons based on cart contents
    function updateAddToCartButtons(cart_items) {
        $('a.add_to_cart_button').each(function() {
            var product_id = $(this).data('product_id');
            
            // If the product is in the cart, disable the button and change the text
            if (cart_items.includes(product_id)) {
                $(this).text('Added').prop('disabled', true).addClass('disabled').css('pointer-events', 'none');
            } else {
                console.log('Resetting button for product ID:', product_id);

                $(this).off('click touchstart')  // Remove previous events
                       .text('Add to cart')  // Reset the button text
                       .prop('disabled', false)  // Enable the button again
                       .removeClass('disabled')  // Remove the disabled class
                       .css('pointer-events', 'auto');  // Enable pointer events
                       
            }
        });
    }

    // Initial cart check on page load
    function refreshCart() {
        $.ajax({
            url: wc_add_to_cart_params.ajax_url,
            type: 'POST',
            data: { action: 'get_cart_items' },
            success: function(response) {
                var cart_items = JSON.parse(response);  // Parse the response into an array
                updateAddToCartButtons(cart_items);
            }
        });
    }

    // Refresh the cart on page load
    refreshCart();

    // Listen for the add to cart event
    $(document.body).on('added_to_cart', function(event, fragments, cart_hash, button) {
        var product_id = button.data('product_id');
        button.text('Added').prop('disabled', true).addClass('disabled');

        // Refresh the cart
        refreshCart();
    });

    // When an item is removed from the cart, refresh the buttons
    $(document.body).on('removed_from_cart', function(event, fragments, cart_hash, button) {
        var product_id = button.data('product_id');

        $('a.add_to_cart_button[data-product_id="' + product_id + '"]').each(function() {
            $(this).text('Add to cart')
                   .prop('disabled', false)
                   .removeClass('disabled')
                   .css('pointer-events', 'auto')
                   .css('cursor', 'pointer');
        });

        // Manually trigger fragment and cart refresh
        $.ajax({
            url: wc_cart_fragments_params.wc_ajax_url,
            type: 'POST',
            data: { action: 'get_refreshed_fragments' },
            success: function(data) {
                if (data && data.fragments) {
                    $.each(data.fragments, function(key, value) {
                        $(key).replaceWith(value);
                    });
                    $(document.body).trigger('wc_fragments_refreshed');
                }
            }
        });
    });

    // Refresh the buttons when fragments are refreshed
    $(document.body).on('wc_fragments_refreshed', function() {
        refreshCart();
    });

   // Watch for layout switcher loading completion
    var observer = new MutationObserver(function(mutations) {
        mutations.forEach(function(mutation) {
            if (!$(mutation.target).hasClass('je-layout-switcher--loading')) {
                // When loading is done, refresh the buttons
                refreshCart();
            }
        });
    });

    // Observe layout switcher element changes
    var targetNode = document.querySelector('.je-layout-switcher');
    if (targetNode) {
        observer.observe(targetNode, { attributes: true, attributeFilter: ['class'] });
    }
    
    // Observe changes on jet-popup elements based on 'jet-popup--show-state' and 'jet-popup--loading-state' classes
    var popupNodeList = document.querySelectorAll('.jet-popup');
    popupNodeList.forEach(function(popupNode) {
        if (popupNode) {
            var popupObserver = new MutationObserver(function(mutations) {
                mutations.forEach(function(mutation) {
                    if ($(mutation.target).hasClass('jet-popup--show-state') && !$(mutation.target).hasClass('jet-popup--loading-state')) {
                        // Popup is shown and no longer loading, refresh the buttons
                        refreshCart();
                    }
                });
            });

            // Observe class attribute changes
            popupObserver.observe(popupNode, { attributes: true, attributeFilter: ['class'] });
        }
    });
});
`

**Conclusion:**
This feature is highly important for improving the user experience, especially for shops selling digital products. The real-time synchronization across multiple tabs, devices, and contexts is something I believe many users are looking for, but no plugins currently offer. I hope my code can assist in the implementation and help Crocoblock provide this much-needed feature.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

We are grateful for your suggestions and will take them into account when developing similar functionality, but it would be much better to create a general solution that will work for all cases of adding to the cart. 

Also, it would be better not to focus on individual plugins that depend on the WooCommerce, but to try it out directly in it, you can also contact the WooCommerce developers with a suggestion.

Thank you for your understanding.
