### ISSUE TITLE
Map marker image from custom field unneccessary loads 'full' image size. 

### ISSUE THREAD

**Issue by cvl01** [CrocoBlock/suggestions#7752]
**Describe the bug**
When setting a image from a meta field in jet engine map listing, the 'full' image size is loaded, while the marker is most often no bigger than 20-50px. So this is a big waste of resources and unnecessary loading time. 

**Solution**
in `plugins/jet-engine/includes/modules/maps-listings/inc/render.php:349` change `full` to `thumbnail`
```php
if ( $image_id ) {

	$image_cache_key = 'jet_engine_marker_' . $image_id;
	$image_url = wp_cache_get( $image_cache_key );

	if ( ! $image_url ) {
		$image_url = wp_get_attachment_image_url( $image_id, 'thumbnail' );
		wp_cache_set( $image_cache_key, $image_url );
	}
} else {
	$image_url = $image;
}

```

**Comment by Crocoblock** [comment]
Added https://i.imgur.com/xtkLCqg.png in JetEngine v3.5.7
