### ISSUE TITLE
Please add option to vary number of columns in Product Loop

### ISSUE THREAD

**Issue by vishal19121981** [CrocoBlock/suggestions#7754]
Since we cannot alter the number of Columns in Product Loop based on device type like the way we see in Listing Grid, it ruins the comfort of displaying items conditionally

**Comment by UraraReika** [comment]
Thanks for the feedback.

Please follow guidelines for opening a [new feature request](https://github.com/Crocoblock/suggestions/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), so we can help you better. This report is missing key information. Without it - it is hard for us to filter and prioritise the requests.

But if I understand you correctly you can change number of columns for Archive Items. Open Archive Template in editor and go to template settings - https://tppr.me/1Z7bvT. Here you can enable Column Count option - https://tppr.me/zJiv9e and set number of columns for different device types. 

Thank you for your understanding.
