### ISSUE TITLE
JetEngine - Added missing size units

### ISSUE THREAD

**Issue by stijnvanouplines** [CrocoBlock/suggestions#7757]
Can you please have a look at [this commit](https://github.com/stijnvanouplines/jet-engine/commit/9aad9e87eecbf96c04d3beb40ef5e2e734178f74) that will add missing size units to all dynamic widgets?

**Comment by Crocoblock** [comment]
Added in JetEngine v3.5.7

**Comment by stijnvanouplines** [comment]
It seems there was an issue during the implementation. Currently, there are two options for adding a custom value for “field_padding.”

I think you should modify this line:
```php
'size_units' => jet_engine()->elementor_views->add_custom_size_unit( array( 'px', '%', 'em', 'rem', 'custom' ) ),
```

to:
```php
'size_units' => jet_engine()->elementor_views->add_custom_size_unit( array( 'px', '%', 'em', 'rem' ) ),
```

I've noticed this issue in other fields as well.
