### ISSUE TITLE
Editor Load Level on "NONE" Removes Front-End Style Settings

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7759]
**Describe the bug:**
When I set the "Editor Load Level" to NONE in the JetPlugins settings, the style settings are completely removed, even from the front-end. Based on my understanding, setting this option to "NONE" should speed up the page loading time by disabling the editor’s extra styles while editing in the back-end, but it should not affect the front-end styles. This issue seems to occur with JetBlocks, JetTabs, JetElements, and JetTricks, which are the only plugins I’m using, but I haven’t tested others. The issue is present both on the back-end and front-end.
![Posnetek zaslona 2024-09-21 100156](https://github.com/user-attachments/assets/31be0b50-d7ca-4941-b29c-27696a1ade99)
![Posnetek zaslona 2024-09-21 100211](https://github.com/user-attachments/assets/517174f4-3ea2-486a-83ad-e383995d1f8b)
![Posnetek zaslona 2024-09-21 100441](https://github.com/user-attachments/assets/f445d941-8f93-459d-b2d2-064497eb17cc)
![Posnetek zaslona 2024-09-21 100516](https://github.com/user-attachments/assets/025d9a71-b196-4c3b-a0de-8d189077d36f)
![Posnetek zaslona 2024-09-21 100905](https://github.com/user-attachments/assets/d1e4b6fe-d568-4d76-bbc0-9dc553d3a09c)
![Posnetek zaslona 2024-09-21 101428](https://github.com/user-attachments/assets/49310cc9-040a-46b1-a129-65f90f127b07)
![Posnetek zaslona 2024-09-21 101444](https://github.com/user-attachments/assets/c8c05a81-62cf-4b6f-96d5-e9022053d16e)

**To Reproduce:**

- Go to JetPlugins settings.

- Set the "Editor Load Level" to NONE.

- View the front-end of the site with any of the affected Jet plugins.

- See that the style settings for JetBlocks, JetTabs, JetElements, and JetTricks are not applied, causing display issues.

**Expected behavior:**
The expected behavior is that setting the Editor Load Level to NONE should not affect the front-end styles. Only the editor styles for the back-end should be disabled to improve performance, while the front-end appearance should remain the same.

**Desktop:**
OS: Windows 11
Browser: Chrome, Edge
Version: Latest
Smartphone (please complete the following information):

**Device:** 
Samsung Galaxy A71
OS: Android
Browser: Chrome
Version: Latest

**Additional context:**
I’m wondering if this behavior is intended or if it’s a bug. I expected that disabling the editor styles with NONE would not affect the front-end. If this is not the intended behavior, I would appreciate any guidance on how to fix this or if there’s a workaround.

**Comment by MjHead** [comment]
It's a problem with options naming and communication in admin area from our side. This option speed up editor and front-end by disabling Styling options in widgets. This will improve both - editor and front-end performance (mostly editor, but some impact on front-end also exists). But yes, it works by complete removing these options. In case of **None** all styling options will be removed and widget elements only can inherit global styles or could be styled manually. You can play around with this option to find balance for you
