### ISSUE TITLE
Malformed JSON when exporting CPT as skins

### ISSUE THREAD

**Issue by mbellezi** [CrocoBlock/suggestions#7766]
**Describe the bug**
When a choose a CPT for export using the Sknin manager the JSON file is truncated and malformed. Example:

{"post_types":[{"id":"15","slug":"videos-cpt","status":"publish","labels":"a:1:{s:4:\"name\";s:7:\"V\u00eddeos\";}","args":"a:23:{s:6:\"public\";b:1;s:18:\"publicly_queryable\";b:1;s:7:\"show_ui\";b:1;s:12:\"show_in_menu\";b:1;s:17:\"show_in_nav_menus\";b:1;s:12:\"show_in_rest\";b:1;s:9:\"query_var\";b:1;s:7:\"rewrite\";b:1;s:12:\"map_meta_cap\";b:0;s:11:\"has_archive\";b:1;s:12:\"hierarchical\";b:0;s:19:\"exclude_from_search\";b:0;s:10:\"with_front\";b:0;s:14:\"show_edit_link\";b:0;s:16:\"hide_field_names\";b:0;s:15:\"delete_metadata\";b:0;s:12:\"rewrite_slug\";s:10:\"videos-cpt\";s:15:\"capability_type\";s:4:\"post\";s:13:\"menu_position\";i:-1;s:9:\"menu_icon\";s:25:\"dashicons-format-standard\";s:8:\"supports\";a:2:{i:0;s:5:\"title\";i:1;s:6:\"editor\";}s:13:\"admin_columns\";a:0:{}s:13:\"admin_filters\";a:0:{}}","meta_fields":"a:2:{i:0;a:12:{s:5:\"title\";s:4:\"Tipo\";s:4:\"name\";s:4:\"tipo\";s:11:\"object_type\";s:5:\"field\";s:5:\"width\";s:4:\"100%\";s:7:\"options\";a:1:{i:0;a:4:{s:3:\"key\";s:0:\"\";s:5:\"value\";s:0:\"\";s:9:\"collapsed\";b:0;s:2:\"id\";i:2708;}}s:15:\"repeater-fields\";a:0:{}s:4:\"type\";s:6:\"select\";s:9:\"collapsed\";b:0;s:2:\"id\";i:8626;s:8:\"isNested\";b:0;s:14:\"options_source\";s:8:\"glossary\";s:11:\"glossary_id\";s:2:\"12\";}i:1;a:11:{s:5:\"title\";s:4:\"Link\";s:4:\"name\";s:4:\"link\";s:11:\"object_type\";s:5:\"field\";s:5:\"width\";s:4:\"100%\";s:7:\"options\";a:0:{}s:15:\"repeater-fields\";a:0:{}s:4:\"type\";s:8:\"textarea\";s:9:\"collapsed\";b:0;s:2:\"id\";i:4362;s:8:\"isNested\";b:0;s:14:\"options_source\";s:6:\"manual\";}}"}],"taxonomies":[],"listings":[],"components":[],"meta_boxes":[],"relations":[],"options_pages":[],"glossaries":[],"queries":[],"content":null,"custom_content_types

**To Reproduce**
1. Go to JEngine -> Skins
2. Click on Export
3. Scroll down to CPT and choose a CPT and export.
4. See error on the generated file

**Expected behavior**
A valid JSON shoyld be generated.

**Comment by Crocoblock** [comment]
Hi @mbellezi 

We've tried to reproduce your issue and everything works fine on our side. please contact our support team regarding this case - https://crocoblock.com/help-center/ 
create a ticket including access details for your site where the issue occurred to make sure we can help you.
