### ISSUE TITLE
[Bug] JetSmartFilters, date and select filters disappear

### ISSUE THREAD

**Issue by matke-84** [CrocoBlock/suggestions#7768]
**Describe the bug**
Hi. I have a bilingual site. In the default language, the filters work normally. When I switch to another language in smart filters, date and select filters disappear. This happens with version 3.5.6. In version 3.5.5 everything works normally.

**To Reproduce**
1. Everything works in the default language.
2. I click on another language (polylang plugin), the date and select filters disappear

**Expected behavior**
When I change languages ​​this shouldn't happen.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: edge and firefox

**Smartphone (please complete the following information):**
 - Device: Samsung s21 fe
 - OS: Android 14
 - Browser: samsung and chrome

**Comment by Bequiet19** [comment]
I confirm this bug. The same thing is happening to me with the latest version JetSmartFilters 3.5.6. I went back to version 3.5.5, everything works as it should.

**Comment by Crocoblock** [comment]
fixed in JetSmartFilters 3.5.7
Please, update the plugin
