### ISSUE TITLE
Duplicate or export Jet Engine forms

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#777]
Hello, please make it possible to duplicate or export Jet Engine forms. Thanks.

/*Оригинал*/
Здравствуйте, сделайте пожалуйста возможность создания дубликатов или экспорта форм Jet Engine. Спасибо.

**Comment by Floydtm** [comment]
@stasonua0, thanks for the report! We will consider your requests. Now you can use the Duplicate Post plugin to duplicate http://prntscr.com/qelz2k forms

**Comment by stasonua0** [comment]
Thank you, I installed this plugin, but forgot to specify the display in forms in it.

**Comment by alican532** [comment]
> @stasonua0, thanks for the report! We will consider your requests. Now you can use the Duplicate Post plugin to duplicate http://prntscr.com/qelz2k forms

Hello, Duplicate Post plugin does not duplicate jetengine forms.

**Comment by stasonua0** [comment]
> > @stasonua0, thanks for the report! We will consider your requests. Now you can use the Duplicate Post plugin to duplicate http://prntscr.com/qelz2k forms
> 
> Hello, Duplicate Post plugin does not duplicate jetengine forms.

Yes, duplicates the post, but the content is not duplicated. It's a pity

**Comment by jazir5** [comment]
How can i duplicate a form while retaining all form settings?

**Comment by AjayToker** [comment]
+1 for this... need this badly for users.

I created a MASSIVE user registration form... then would like to duplicate it, remove the password fields and just allow the user to update the meta (password is updated through WPFusion).

I'm now having to re-create the entire registration form without the password fields. 

Would be a time saver!!!

**Comment by pascal-parent-za** [comment]
Exporting forms would be useful, if only to go from dev to stage to prod

**Comment by yosnap** [comment]
Please, I though we can see this feature en JetEngine 2.4

**Comment by bluehavoc** [comment]
It doesn't really duplicate the form. You still have to go in and re-create your layout and fields.  Is there something I'm missing?

**Comment by createdbyred** [comment]
This is much needed... Why can't export forms like with other JetEngine contents?? I too have a long form and need to replicate it... no way to.

**Comment by Floydtm** [comment]
https://prnt.sc/tqc17b https://prnt.sc/tqc1ji
