### ISSUE TITLE
JetEngine conflict with Rank Math SEO

### ISSUE THREAD

**Issue by rubixvi** [CrocoBlock/suggestions#7770]
**Describe the bug**

**To Reproduce**
1. Go to Jet Egnine
2. Click on Turn on Profile Builder
3. Goto Home 
4. Press 12
5. Missing Meta Description and Meta Title.

**Expected behavior**

Requires to still be present the SEO description and title.

**Comment by Crocoblock** [comment]
Hi @rubixvi 

We've tried to reproduce your issue and everything works fine on our side. please contact our support team regarding this case - https://crocoblock.com/help-center/
create a ticket including access details for your site where the issue occurred to make sure we can help you.

**Comment by Crocoblock** [comment]
was fixed and released in the JetEngine 3.5.7
