### ISSUE TITLE
Hide Elementor Pro content

### ISSUE THREAD

**Issue by Lagardien** [CrocoBlock/suggestions#7772]
For some projects, I use Free Elementor with JetPlugins, and it's good enough for me. 
However, there is one thing that annoys me : Elementor pro related content. 
While using JetPlugins (which covers most of Elementor Pro features) I am fustrated to constantly see those "upgrade buttons". 

So here's my idea, it's pretty simple:
Adding some sort of switch button in Crocoblock's settings that would completely hide any Elementor pro content. Obviously, this would be greyed out if Elementor Pro is installed. I am convinced that I am not the only person that needs such a feature. 

I found the plugin "White Label" that allows to hide "Elementor Pro Nags" and "Elementor Pro Widget" for Non-admin users. It's working fine but if you are the admin then it won't work, but at least I know that it is possible to make it and it would be great to have it built in Crocoblock.

Thanks for considering that feature request.
Loïc

**Comment by Crocoblock** [comment]
Hi @Lagardien 

Unfortunately, we will not add this option to our plugins because it relates to the functionality of the Elementor plugin. Therefore, you need to contact Elementor support and submit your request to them.

Thank you for your understanding!
