### ISSUE TITLE
JetProductGallery - Show video in the lightbox

### ISSUE THREAD

**Issue by Aurelien-Frois** [CrocoBlock/suggestions#7776]
Hi,
It would be fantastic if the video added in the Gallery Slider also could be show when the lightbox is triggered.
Actually only the images are show in the lightbox.
Any custom JS or ideas to achive this ?
Yhanks by advance.

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin and PhotoSwipe library that we use for light-boxing images doesn’t support this feature.

Thank you for your understanding.
