### ISSUE TITLE
In Bricks Builder, JetSmart Filter to filter 4-level taxonomy, not displaying the empty terms.

### ISSUE THREAD

**Issue by AleWarriorPrior** [CrocoBlock/suggestions#7777]
**Describe the bug**
Used the Jetsmart filter - select filter for a 4-level hierarchy filter. The terms number for the 1st, 2nd, 3rd, 4th levels are list below
2 terms - 30 terms - 700 terms - 3000 terms

Basically this filter is used for filter the locations.

I've imported all the terms, built the filter in the Bricks builder, switched on "Show empty terms", but unless I've assigned the terms to certain posts, the terms will not display in the frontend.

**To Reproduce**
1. Create the filter -> Hierarchy on -> put in the 4 level taxonomy
2. In the bricks builder, insert the smartfilter widgets, assign the query ID, setup the query loop within the bricks builder. 
3. In the indexer options, make sure "if term empty" to show.
5. not all the terms showed up, unless the terms are assigned to certain queried posts.

**Expected behavior**
The filter should display all the taxonomies being created and assigned.

**Screenshots**

Below is my bricks settings, I was able to filter the posts that has the terms assigned.
![image Microsoft EdgeDev002413@2x](https://github.com/user-attachments/assets/cf645537-6732-4e1f-98b1-e89f4f9476d7)
![image Microsoft EdgeDev002415@2x](https://github.com/user-attachments/assets/b086fbb5-1d5c-48a3-8181-7090395403b9)

And this is the frontend, it should display more terms but now it's empty

![image Microsoft EdgeDev002417@2x](https://github.com/user-attachments/assets/3e055d56-bd1c-4464-9437-441e84fc7d97)

**Comment by Crocoblock** [comment]
Hi @AleWarriorPrior 

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
