### ISSUE TITLE
Feature Request: Hover to Display Primary Image on Thumbnails

### ISSUE THREAD

**Issue by raikkonen211** [CrocoBlock/suggestions#7780]
Dear Crocoblock Team,

I hope this message finds you well.

I’m currently using your amazing products and have a feature suggestion that would enhance the user experience. I would love to have an option where, when users hover over a thumbnail image, it automatically becomes the primary image without requiring a click. This functionality would be very useful for users to preview different product images quickly and would add a smoother interaction to the overall browsing experience.

Please let me know if this feature can be considered for future updates or if there’s any workaround to achieve this effect with the current tools.

Thank you for your time and continuous support!

Best regards,
Christos

**Comment by Crocoblock** [comment]
Hi @raikkonen211 
You can use JetWooBuilder, which works with the Product Loop and Product Grid widgets https://i.imgur.com/IkjWnvD.png

**Comment by raikkonen211** [comment]
Hello, thank you for your reply.

We use Elementor Pro Builder. Is it possible to use this function with it?
