### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by Shepstar** [CrocoBlock/suggestions#7784]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

It would be great if JetSmartFilters would also work with Premium AddOns "Woo Products".

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

As we use Premium AddOns and the Woo Products Widget for the category pages it would be great if you could use JetSmartFilters to filter the products.

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 
Feel free to add any videos, links, screenshots to illustrate the requested feature.
Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by Floydtm** [comment]
@Shepstar, hi! At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
