### ISSUE TITLE
JetSmartFilters - Request for a Dynamic Tag of "Filter Label" 

### ISSUE THREAD

**Issue by lorikmahmuti** [CrocoBlock/suggestions#7787]
I contacted the support team to ask if there is any dynamic tag that outputs the "Filter Label" of the filter, preferably on Bricks Builder, and after telling me that there is not yet a dynamic tag for that, they guided me to make a request for that. 

One of many use cases is in the "Placeholder Text" of the Checkbox Filter (Dropdown option enabled). 

![CheckboxFilter-Placeholder dynamic-tag](https://github.com/user-attachments/assets/43994bb3-9e20-4a84-b6c5-bd235a5ff4ae)

As you can see on the screenshot above, there is the option for the "dynamic tag", instead of typing a static text it would be great to have a dynamic tag that outputs the Filter Label. By default it shows the text "Select some options..." (as you can see on the screenshot below).

![checkbox-group-filters](https://github.com/user-attachments/assets/c846532b-166d-450f-8b60-874b505f8e80)

Thanks in advance.

**Comment by Crocoblock** [comment]
Hi @lorikmahmuti 

You can use dynamic data in the field https://i.imgur.com/A1QUk0g.png 
Sorry for the confusion

**Comment by Crocoblock** [comment]
Hi @lorikmahmuti 

Please describe your request in more detail, why do you need to use dynamic data for filter labels if they need unique names?

**Comment by lorikmahmuti** [comment]
> Hi @lorikmahmuti
> 
> Please describe your request in more detail, why do you need to use dynamic data for filter labels if they need unique names?

In this case I am using one single "Checkbox Filter" element, so the checkbox filters are grouped filters in one element. In this case the only way to output the Filter Label of every Checkbox Filter on the "Placeholder" text is by a dynamic tag of filter label.

**Comment by Crocoblock** [comment]
Hi @lorikmahmuti 

Unfortunately, we cannot add such an option because the Filter Label is specified in each filter separately here https://i.imgur.com/i7LGheI.png

But you can use custom action `wp_insert_post` with which you can update the meta field _filter_label for specific filters

**Comment by lorikmahmuti** [comment]
Hi @Crocoblock 

I guess you are not clearly understanding my point. Let me make it more clear to you what I mean.

On the image below, as you can see I have one (1) "Checkbox Filter" element(widget) with "5" Checkbox Filters on "Select Filter" area (Market with Red on the left side of screenshot 1).  I've enabled the "Show Filter Label" option just to show you that every Checkbox Filter has it's specific Filter Label (Green Highlighted Text on the screenshot) name as you mentioned in your reply. 

Now what I want to achieve is on the "Placeholder" text (Blue Highlighted on the screenshot 1) I want to show the Filter Label (Green Highlighted on screenshot 1) and not any static text. This option it's very basic and maybe should be a built-in toggle option on the Dropdown Enabled settings of Checkbox Filter (ex. "Show Filter Label on Placeholder text"). 

But knowing that this option is not there, I asked for a dynamic tag that I can put on the Placeholder Text input, to achieve what I want (Screenshot - 2). 

Screenshot 1:
![image](https://github.com/user-attachments/assets/cbc4c7be-cb23-41d3-a4a4-b8e1bc19c781)

Screenshot 2:
![image](https://github.com/user-attachments/assets/356caba7-9939-4b36-b8bd-98c2d5d505aa)
