### ISSUE TITLE
Feature Request: Hover to Display Primary Image on Thumbnails #7780

### ISSUE THREAD

**Issue by raikkonen211** [CrocoBlock/suggestions#7788]
Feature Request: Hover to Display Primary Image on Thumbnails #7780
Hello, thank you for your reply.  We use Elementor Pro Builder. Is it possible to use this function with it?

**Comment by Crocoblock** [comment]
HI @raikkonen211 

We are not the developers of the Elementor plugin, if you need this functionality in this plugin, please get in touch with the developers of that plugin. Perhaps you need this option in the dynamic image widget?
