### ISSUE TITLE
Unable to open listing grid items in a new tab

### ISSUE THREAD

**Issue by DudeDude95** [CrocoBlock/suggestions#7790]
**Describe the bug**
The ability to open links created in a listing grid is absent. For example, if I have a listing grid of posts, and the link is set to the single post, I must left click it to open it. I cannot open it by right-clicking the item and opening in a new tab nor can I middle click (click the scroll wheel to open links in new tabs).

**To Reproduce**
1. Create a listing grid template.
2. Ensure the template has a link.
3. Publish the template and insert it anywhere.
4. As a front-end user, try to open the link in a new tab either right-clicking or by middle-clicking with the scroll wheel.

**Expected behavior**
By middle clicking a link, I can open links in a new tab. Is it not possible with items made in the listing grid.

**Comment by Crocoblock** [comment]
Hi @Dudeney95 

It's because tag `a` is lower
So you can use CSS:
```css
a.jet-engine-listing-overlay-link {
   z-index:999;
}
```
