### ISSUE TITLE
Date Period Filter not working after 3.5.7 Update

### ISSUE THREAD

**Issue by SEwebm** [CrocoBlock/suggestions#7792]
**Describe the bug**
Filtering posts with the date filter does not seem to work after the update to JetSmartFilters 3.5.7 (at least with the Elementor Pro Posts widget).

**To Reproduce**
1. Create Test page and date period filter with filter settings seen in the provided screenshot below
2. Place posts widget (posts published in different years required) and filter
3. Select Year
4. See filter has not been applied to results.

**Expected behavior**
The filter results (posts widget) only show posts of the year selected in the date period filter.

**Screenshots**
![Bildschirmfoto 2024-10-16 um 13 24 34](https://github.com/user-attachments/assets/91bae055-4fb5-4808-8d07-be662d857796)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma (14.7)
 - Browser: recent Firefox and Chrome versions

**Additional context**
The issue does not produce any JS or PHP errors / warnings. I ensured that the filter widget has the correct settings applied for this to be expected to work. If the issue does not seem to be reproducible for others it could be due to a incompatibility with another 3rd party plugin.

Thanks for your time.

**Comment by DaviAppelDuarte** [comment]
+ 1

**Comment by Crocoblock** [comment]
was fixed in JetSmartFilters v3.5.7.1
