### ISSUE TITLE
Relationships: Settings for Post Status

### ISSUE THREAD

**Issue by theheadphonelist** [CrocoBlock/suggestions#7794]
Content on my site is created across multiple CPTs and CCTs, and various authors will enter the information.  They need the ability to add relationships before content is published (in draft mode), so it all shows up simultaneously when published.  Currently, it is only possible to connect published posts.

It would be ideal if there was an option for the relationship to select the post status that will be visible in the relationship connection box, like on the query builder page shown below.
![image](https://github.com/user-attachments/assets/2ee2050c-3b16-4a6c-a628-89853c66999c)

This will also be useful for an upcoming use case of displaying private posts with relationships for subscribers.

**Comment by Crocoblock** [comment]
Hi @theheadphonelist 

You can use `jet-engine/relations/types/posts/get-items/post-statuses`  hook, where the first param - is the array of statuses, second - post_type slug, third - Jet_Engine\Relations\Relation Object

Example:
```php
add_filter( 'jet-engine/relations/types/posts/get-items/post-statuses', function( $statuses, $post_type, $relation ) {
	$statuses = [ 'publish', 'private', 'draft' ];

	return $statuses;
}, 10, 3 );
```

**Comment by Crocoblock** [comment]
Hi @theheadphonelist

You can use `jet-engine/relations/types/posts/get-items/post-statuses` hook, where the first param - is the array of statuses, second - post_type slug, third - Jet_Engine\Relations\Relation Object

Example:
```php
add_filter( 'jet-engine/relations/types/posts/get-items/post-statuses', function( $statuses, $post_type, $relation ) {
	$statuses = [ 'publish', 'private', 'draft' ];

	return $statuses;
}, 10, 3 );
```
