### ISSUE TITLE
Relationships: Dynamic Visibility Settings

### ISSUE THREAD

**Issue by theheadphonelist** [CrocoBlock/suggestions#7795]
Create settings for dynamic visibility for both the parent and child relationship.  I am requesting this as I have a relationship where the same CPT is both the parent and child, and they should only be displayed based on the CPT taxonomy.

Example:
Parent: CPT1 Taxonomy 1 only
Child: CPT1 Taxonomy 2 only

**Comment by Crocoblock** [comment]
Hi @theheadphonelist 

describe your issue in more detail, with some examples and screenshots
