### ISSUE TITLE
Looking up related items for object when table doesn't yet exist logs error

### ISSUE THREAD

**Issue by aayla-secura** [CrocoBlock/suggestions#7796]
When using `Jet_Engine\Relations\Relation::get_children` or `get_parents` or related methods, it queries the database, without checking if the table exists. But the table is only created when the first related item is connected. So if there aren't yet any related items yet on any relations, the table won't exist and it will log an error:

```
WordPress database error Table 'wordpress_test.wptests_jet_rel_default' doesn't exist for query SELECT ...
```

Not a fatal error, code will proceed, but it's good practice to check if the table exists to avoid unnecessary errors in the log.

Probably this check should be implemented in the database class's `query` method and just return null if it doesn't exist.

**Comment by Crocoblock** [comment]
was fixed and released in the JetEngine 3.6.0
