### ISSUE TITLE
Fatal error with JFB Form Preview and Bricks

### ISSUE THREAD

**Issue by Joe-Bloggs** [CrocoBlock/suggestions#7802]
I am getting a Fatal Error when trying to preview a JetFormBuilder Form with Bricks.

All other plugins have been deactivated. The only active plugin is JetFormBuilder and Bricks Builder theme.

The details of the error are below:

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /sites/domain.com/files/wp-content/plugins/jetformbuilder/modules/onboarding/preview.php:65 Stack trace: #0 /sites/domain.com/files/wp-includes/class-wp-hook.php(324): JFB_Modules\Onboarding\Preview->render_form_preview() #1 /sites/domain.com/files/wp-includes/plugin.php(205): WP_Hook->apply_filters() #2 /sites/domain.com/files/wp-includes/formatting.php(3980): apply_filters() #3 /sites/domain.com/files/wp-includes/class-wp-hook.php(324): wp_trim_excerpt() #4 /sites/domain.com/files/wp-includes/plugin.php(205): WP_Hook->apply_filters() #5 /sites/domain.com/files/wp-includes/post-template.php(436): apply_filters() #6 /sites/domain.com/files/wp-content/themes/bricks/includes/settings/settings-page.php(325): get_the_excerpt() #7 /sites/domain.com/files/wp-content/themes/bricks/includes/settings/base.php(17): Bricks\Settings_Page->set_controls() #8 /sites/domain.com/files/wp-content/themes/bricks/includes/settings.php(42): Bricks\Settings_Base->__construct() #9 /sites/domain.com/files/wp-content/themes/bricks/includes/elements/base.php(571): Bricks\Settings::set_controls() #10 /sites/domain.com/files/wp-content/themes/bricks/includes/elements/base.php(113): Bricks\Element->set_controls_before() #11 /sites/domain.com/files/wp-content/themes/bricks/includes/elements.php(206): Bricks\Element->load() #12 /sites/domain.com/files/wp-content/themes/bricks/includes/elements.php(190): Bricks\Elements::load_element() #13 /sites/domain.com/files/wp-includes/class-wp-hook.php(324): Bricks\Elements::load_elements() #14 /sites/domain.com/files/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #15 /sites/domain.com/files/wp-includes/plugin.php(565): WP_Hook->do_action() #16 /sites/domain.com/files/wp-includes/class-wp.php(830): do_action_ref_array() #17 /sites/domain.com/files/wp-includes/functions.php(1336): WP->main() #18 /sites/domain.com/files/wp-blog-header.php(16): wp() #19 /sites/domain.com/files/index.php(17): require('...') #20 {main} thrown in /sites/domain.com/files/wp-content/plugins/jetformbuilder/modules/onboarding/preview.php on line 65

**Comment by Crocoblock** [comment]
Hi @Joe-Bloggs 

We've tried to reproduce your issue and everything works fine on our side. have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
