### ISSUE TITLE
JetFormBuilder: Post Submission Action: Create Multi-Site / Network Site

### ISSUE THREAD

**Issue by creativewp24** [CrocoBlock/suggestions#7805]
After discussing with your team, and trying to work out a solution to a planned project, its become clear you cant use jetformbuilder forms to create new sub sites in the network on a multi-site website. This is particularly useful if a client has multiple clients that they create things like custom webinar platforms for or custom portal areas for clients. I feel the multi-site options of Wordpress whilst generally used less, are often used by more commercially wealthier clients, meaning theres space to make some pennies by simplifying this process of creating network sites and functions too.

Whilst many crocoblocks functions work, the form is particularly where we would suggest adding additional post submission actions as we are currently going to have to extend the form functionality with custom codes or snippets. Something we would prefer to not have to do.

**Comment by Crocoblock** [comment]
Hi 

Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. However, in the future, we will not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for being so understanding.
