### ISSUE TITLE
JetSmartFilters: Predefined Active Filters via Custom Field Support for Default Values

### ISSUE THREAD

**Issue by jkdone** [CrocoBlock/suggestions#7809]
Hello JetSmartFilters team,

I would like to request an enhancement to the current functionality for managing predefined filters and dynamic URL rewriting.

**Current Challenge:**
- The existing solution of creating speaking URLs via the URL rewriting settings is not flexible enough for my needs.
- I am building listing pages using Elementor and utilize these pages as templates via the Elementor Theme Builder for pages (or a custom post type).
- I would like to create individual listing pages where specific filters are pre-applied, while still being able to leverage the flexibility of Pages in WordPress (e.g., adding text, images, etc.) and also have the full control from an SEO perspective over my accessible URLs. 

**Example:**
Let’s say I have a website about bicycles (just an example). I have several filters like bike type (Mountain Bike, Gravel Bike, etc.), price range, manufacturer, condition (new, used), etc. 

Pages like `/type/mountainbike/` could be created using taxonomies. However, if I want to create a specific page for "used mountain bikes under $1500 from a certain brand," and place it on a URL like `/xyz-mountainbikes-under-1500-euros/`, I would like to have all the relevant filters pre-selected. At the same time, I want users to have the ability to remove, change, or add filters.

The **Query Builder** allows filtering, but it doesn't set the filters as "active" filters. And currently, the **Default Value** feature cannot be dynamically pre filled.

**Feature Request:**
I would like to request the ability to use **Default Values** with **Custom Fields**. 

This would allow me to:
1. Assign custom fields for filter values like manufacturer, type, price range, etc. to pages or a custom post type
2. Create a page (or custom post type) for a specific filter combination
3. Use these custom field values (e.g., brand = xyz, type = mountain bike, price = 1500) to dynamically pre-fill the filters default value when that specific URL is loaded. 

This way, I could maintain full flexibility in creating pages while having predefined active filters, and users would still have the option to modify the filters. It is also a more elegant solution than the Rewriting of URLs with more control over the URLs of the website.

Thank you for considering this request!

Best regards
jkdone

**Comment by Crocoblock** [comment]
Hi @jkdone 

Now you can use hook `jet-smart-filters/filters/predefined-value`, where:
first param - entered value in the `Default Filter Value` field
second param - filter id
third param - filter type (radio, select, check-range, etc)

Example:

```php
add_filter( 'jet-smart-filters/filters/predefined-value', function( $value, $filter_id, $filter_type) {

	if ( $filter_id == 10193 ) {
		return 'some-value';
	}

	return $value;
}, 10, 3 );
```

Also with this code, you can use the JetEngine macro in the `Default Filter Value` field https://i.imgur.com/rR3FX3T.png 
```php
add_filter( 'jet-smart-filters/filters/predefined-value', function( $value ) {
	if ( function_exists( 'jet_engine' ) ) {
		return jet_engine()->listings->macros->do_macros( $value );
	}

	return $value;
}, 10 );
```
