### ISSUE TITLE
Continuous wp-admin.ajax on edit posts increasing hundreds requests on server

### ISSUE THREAD

**Issue by irfanjutt12** [CrocoBlock/suggestions#7810]
Hi Support ,
We are facing high CPU usage due to continuous Ajax request on admin posts while editing , a lot ajax request are continuous running on hover, on writing any text in editor So I want this ajax request only work when we click to publish or  update post
I'm sharing here which hook is running continuous
Action Hook: jet-engine/meta-box/update-conditions
<img width="950" alt="Screenshot_119" src="https://github.com/user-attachments/assets/d51d9e8f-cc39-487a-911f-0b7579d03e59">
<img width="958" alt="Screenshot_120" src="https://github.com/user-attachments/assets/557249b7-65ab-4668-b9b4-fd3fd6b8fc73">
<img width="952" alt="Screenshot_121" src="https://github.com/user-attachments/assets/a58d8174-3c61-43f4-916f-b854734b7212">

**Comment by Crocoblock** [comment]
Hi @irfanjutt12 
We know about that issue, and we are working on it. The fix will be in JetEngine v3.5.8. 

Thank you for reporting!
