### ISSUE TITLE
Jet wooBuilder 2.1.14 BUGs

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#7814]
**Describe the bug**

Hi team,

After updating jet woobuilder to the new version, there are problems in the pagination of the product grid widget.

1- The border control is missing.

![Screenshot](https://github.com/user-attachments/assets/96598838-1fe0-4183-849c-1301b8f6fbbb)

2- Gap and alignment controls do not work at all.

![Screenshot_1](https://github.com/user-attachments/assets/318fca6a-640a-40c0-a787-e894bba7e4fb)

3- By default, the pagination buttons are slightly away from the bottom. Before the new version, they were attached to the bottom border of the widget.

![Screenshot_2](https://github.com/user-attachments/assets/a304d51e-7bfe-48f6-add1-6eec115725bc)

4- The colors of the pagination buttons in "normal mode" are much lighter than the color we choose.

![Screenshot_3](https://github.com/user-attachments/assets/919a0bfa-bc5a-4002-9ef4-079826b77a5a)

Thank you

**Comment by Crocoblock** [comment]
was fixed and released in JetWooBuilder 2.1.16
