### ISSUE TITLE
extra jet engine requests are on the front end

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#7815]
Hi,

Immediately after activating the Jet engine, 3 js requests are displayed on the front end. This is while only jet engine is activated and none of its features and widgets are used on the page.

**Requests:**

- jet-engine/assets/lib/jet-plugins/jet-plugins.js?ver=1.1.0
- wp-includes/js/jquery/jquery.min.js?ver=3.7.1
- jet-engine/assets/js/frontend.js?ver=3.5.7

**Comment by ihslimn** [comment]
@Joliamendi 
JetEngine scripts get loaded only if there are any JetEngine widgets/blocks (including in popups that are on the page) on the page, or if there a data store with "Store item on view" enabled.
If you still have them loaded without above conditions fulfilled - please, contact our support and provide them an access to your installation.
