### ISSUE TITLE
Dropdown WooCommerce Shopping Cart not closing when clicking outside or ESC

### ISSUE THREAD

**Issue by zahnd** [CrocoBlock/suggestions#7817]
Hi

The dropdown of the WooCommerce Shopping Cart widget does not close if one clicks outside the dropdown or pressing ESC. And there seems no option to enable it like in the unfold widget. 

Thanks and best regards, Stefan

**Comment by Crocoblock** [comment]
added in JetBlocks 1.3.16 https://i.imgur.com/0cYiTzX.png
