### ISSUE TITLE
Exporting and importing skin: glossary and query IDs shuffled

### ISSUE THREAD

**Issue by aayla-secura** [CrocoBlock/suggestions#7820]
I have multiple glossaries and query builder queries which are used as inputs for select fields. When I exported *everything* from my skin and imported it into another site, the glossaries and queries were shuffled or disabled. The site may have had previous JetEngine data, but I manually deleted everything before the import.

For example select fields that were meant to take input from glossary X, were using glossary Y; fields that were configured to use query X were now set to not use any query, because the query was imported with a different, now non-existend ID, etc...

I wiped the whole database and tried again and this time it worked. I suspect that when there may have been previous data that was deleted, the start ID of queries and glossaries would be non-0, which caused the newly imported glossaries and queries to get a different ID. I think in this case, the ID used by meta fields, conditional visibility, etc, should also be updated.

**Comment by Crocoblock** [comment]
Hi @aayla-secura 
When you export your data from site A, the IDs are not exported as they will be added to the DB when you import them, as the IDs must be unique. So when you import queries to site B you need to edit them and select the actual Query

**Comment by aayla-secura** [comment]
I see, thanks for replying. Do you think it's possible that the import functionality automatically detects the new IDs of the queries and updates them, so I don't have to manually re-set them? I mean if the query itself and the field that uses it are exported together, this kind of linking should be possible, I would think? Can this issue be reopened please?
