### ISSUE TITLE
Posts Query returns -1 posts instead of 0 posts if "Post In" current meta field value is empty

### ISSUE THREAD

**Issue by DudeDude95** [CrocoBlock/suggestions#7826]
**Describe the bug**
I have a meta field for my homepage named "Posts to show".

Its datatype is "Posts" and "Multiple" is set to "True".

This allows me to show specific posts on my homepage which have been selected:

![image](https://github.com/user-attachments/assets/d802e43a-afdd-4a68-bf6e-35a7060d96ee)
_Three posts selected and saved as a metafield to the homepage_

To get the selected posts to show on the front-end, I use a Posts Query:
![image](https://github.com/user-attachments/assets/908e4ba4-0886-41ce-8aaf-6ac4c670b056)

And the result is this:
![image](https://github.com/user-attachments/assets/9b722387-1906-493f-9f95-9d8ecb998f78)
_The three posts selected and saved to the meta field are shown on the front-end_

The issue I'm having is when no posts are selected in the meta field. If no posts are selected, you would expect no posts to load on the front-end (0). However, the opposite happens and ALL posts will show (-1).

For example, here is the meta field with no saved posts:
![image](https://github.com/user-attachments/assets/5c2b6c8f-53a2-49ab-83e6-760d59a4f0f6)

And here is the front-end:
![image](https://github.com/user-attachments/assets/3240c3dc-ee68-4969-942f-0d4553836bab)
_As you can see EVERY post is displayed instead of none._

This is a bit of a nightmare when it comes to editing in Elementor as if there are a lot of posts, I cannot edit the template with the list grid widget as there are too many posts to load. Not just this, but it means I have to create a separate metafield (switcher) to manage hiding it as the option to hide the listing grid widget if the query is empty, doesn't work.

If no posts are saved in the meta field, the query should return 0 posts, not all of them.

**To Reproduce**
1. Using JetEngine, create a metabox for a page or a metafield for a CPT.
2. Make this field a "Posts" field and allow Multiple.
3. Ensure you have many posts saved.
4. Select just some of these posts in your newly created field.
5. Create a query to display these saved posts.
6. Create a listing grid for posts.
7. On the page with the meta field assigned, add a listing grid with the custom query.
8. See how it appears with posts saved (just fine) and without any posts saved (it returns all posts).

**Expected behavior**
If no posts are saved in the Posts meta field, the listing grid should return 0 posts ("No data was found message") rather than all of them.

**Comment by Crocoblock** [comment]
Hi @Dudeney95 

You need to set `Fallback`. For example `'none'` https://i.imgur.com/9eXpIDK.png

**Comment by Dudeney95** [comment]
Worked a treat, thank you! :)
