### ISSUE TITLE
WooCommerce Product Variations Swatches need

### ISSUE THREAD

**Issue by IgorShkarin** [Crocoblock/suggestions#783]
Hello, 

I just want you make this functionality: https://getwooplugins.com/plugins/woocommerce-variation-swatches/?utm_source=wp-admin-plugins&utm_medium=settings-tutorial&utm_campaign=woo-variation-swatches&utm_term=twenty-twenty

I would love to buy it from you guys.

**Comment by RasmusLindberg** [comment]
Could allso use this from you

**Comment by IgorShkarin** [comment]
> Could allso use this from you

Excuse me, you suggest me to develop it?

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin. Link this issue with #361

**Comment by jspassov** [comment]
I will appreciate this functionality too. Above mentioned plugin has terrible support and they are blaming jetwoobuilder if you ask for help (as you can see)

> Shamser Suzon 
> 1 day ago
> Hi Yanko,
> Please check this guideline: https://www.loom.com/share/96e49f5ff69942b3b54d327c4d185bc3
> And Implement this code: https://gist.github.com/ahmedeshaan/28852324145d7b83770cfba6880a2f0a
> And please ask your JetWooBuilder author to include this fix in their plugin.
> Thank you

By the way it's an old answer (just copied and pasted) that does not resolve my issue. 
So guys, please make us happy with swatches and additional variation images inside the core plugin :-)
