### ISSUE TITLE
JetTricks hotspot seems to completly break when Elementor is updated to version 3.25.0

### ISSUE THREAD

**Issue by StenderIternum** [CrocoBlock/suggestions#7830]
JetTricks hotspot seems to completely break when Elementor is updated to version 3.25.0, When I updated, the hotspots didn't show up and nothing was clickable - Reverting Elementor to 3.24.4 fixed the problem.

**Comment by Crocoblock** [comment]
Hi @StenderIternum 

We've tried to reproduce your issue and everything works fine on our side. have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
