### ISSUE TITLE
[Bug] JetElements - slick dots

### ISSUE THREAD

**Issue by matke-84** [CrocoBlock/suggestions#7831]
**Describe the bug**
Hi. With version 2.7.1 the slick dot no longer displays properly. I'm talking about the posts widget. With version 2.7.0 everything works as it should.

**Expected behavior**
Slisk dots should display horizontally without numbers.

**Screenshots**
![Capture](https://github.com/user-attachments/assets/9b71f9cf-d3fc-467c-85a6-5ba240ab0678)

**Desktop (please complete the following information):**
 - OS: Win10, Win11
 - Browser Edge, Firefox

**Smartphone (please complete the following information):**
 - Device: Samsung S210fe
 - OS: Android 14
 - Browser Samsung, Chrome

**Comment by Crocoblock** [comment]
Hi @matke-84 

This issue was fixed and released in JetElements 2.7.1.1

Thank you for reporting!

**Comment by matke-84** [comment]
Thank you for fix! ;-)
