### ISSUE TITLE
Add Left-Right Sliding Filter Functionality in JetSmartFilters

### ISSUE THREAD

**Issue by jahidhasann2** [CrocoBlock/suggestions#7835]
Hello Crocoblock Team,

I would like to request a new feature for JetSmartFilters to enhance the user experience by adding left-right sliding functionality for filters. Currently, filters are displayed in static layouts, but a horizontal slider or carousel option for filters would provide a more dynamic and interactive design, particularly for sites with numerous filter options or for mobile-friendly interfaces.

This feature would allow users to browse filters more easily by sliding left or right, improving accessibility and user engagement. Ideally, the slider would include customization options for navigation (arrows, dots, or swipe) and autoplay settings.

Thank you for considering this feature request! It would be a fantastic addition to the JetSmartFilters toolkit.

**Comment by Crocoblock** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. However, in the future, we will not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for being so understanding.
