### ISSUE TITLE
Ability to set automated tasks based on CCT data etc..

### ISSUE THREAD

**Issue by MiffedLyric559** [CrocoBlock/suggestions#7841]
---
name: Feature request
about: Suggest an idea for this project
title: Automation feature
---

**Initial Description**

I believe this would fit best as a standalone module / plugin or a part of JetEngine.
Basically the idea is that you should be able to create automation tasks based on CCT/CPT/MetaData fields. Visually it could be its own section under JetEngine and you can create automations that can be connected to different parts of the whole system.

**Add an example of where this feature is already implemented. **

An example would be if you have a CCT with a radio field and datefield. Say the options for the radio field are "Yes" and "No". In our case we are selecting "Yes" and setting the date one week in the future.

Using this new Automation feature we could link the automation to run on the selected date in the CCT field. Automation could for example be that it switches the radio field back to no.

**Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. **

If this system is made a bit moduler so that it can be used across the whole JetEngine environment and connected to other systems as well.

I do not have any links, illustrations as of right now but I could cook something up if that helps make this happen ^^

**Last Notes**

I belive a system like this would add great value to the JetPlugins platform and it would also open up endless possibilities for more advanced systems.

**Comment by MiffedLyric559** [comment]
*ADD

I will gladly assist in testing and coming up with ideas for this if you choose to implement it.

**Comment by Crocoblock** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. However, in the future, we will not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for being so understanding.
