### ISSUE TITLE
JET Popup action button close the popup, then scroll the page to the top automatically

### ISSUE THREAD

**Issue by geeko1936** [CrocoBlock/suggestions#7843]
When using jet popup for filtering listing grid on mobile for example. Once the listings have been filtered the user can see the bottom of the page because the page got shorter. It would be really useful when using jet popup for filtering to be able to bring back the user to the top of the page when it closes the popup and wants to see the results of the filtering

**Comment by Crocoblock** [comment]
was added in JetPopup 2.0.8 https://imgur.com/DQxFacX
