### ISSUE TITLE
JetEngine - Image and Gallery meta fields - JFIF images don't show up - Please add image/jfif to your MIME type list

### ISSUE THREAD

**Issue by leandro81** [CrocoBlock/suggestions#7845]
We have an oldie problem whan users can upload your images in Post Types.

Some of them, send Whatsapp imagens in jfif extension. Please, update to Jetengine could read these kind of images.

Thank you!

**Comment by ihslimn** [comment]
Is the problem that you cannot upload file, or they do not show as thumbnail in the field? 
Because if you cannot _upload_ them, this has to do with Wordpress uploads filtering https://eu.siteground.com/kb/fix-sorry-not-allowed-upload-file-type-error-wordpress/
