### ISSUE TITLE
Add Multiple Payment Gateway option in the JetForm

### ISSUE THREAD

**Issue by SjPavel** [CrocoBlock/suggestions#7847]
Hii there,

Add multiple payment options like PayPal+Stripe together in Jetform. The user can select one option and pay. 
But only one payment option can be used inside the jetform. Will be show both payment options in the frontend. 

Please add this feature on the Jetform. 

Best Regards
Pavel

**Comment by Crocoblock** [comment]
Hi @SjPavel 
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/jetformbuilder/issues/440)

**Comment by franitpro** [comment]
> Hi @SjPavel I am closing this issue because it is a copy
> 
> Please keep an eye on [it](https://github.com/Crocoblock/jetformbuilder/issues/440)

The link you told to keep eye on is already closed. 
What to watch then?
