### ISSUE TITLE
Add support for Font Awesome 5 and SVG in Jet Tabs

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#785]
Hello, please consider adding Font Awesome 5 support and the ability to load SVG instead of icons in Jet Tabs (as it is implemented now in all Elementor widgets)

/*Оригинал*/
Здравствуйте, прошу рассмотреть возможность добавить поддержку Font Awesome 5 и возможность загрузки SVG вместо иконок в Jet Tabs (так как это реализовано сейчас во всех виджетах Elementor)

**Comment by kaskad88** [comment]
Added for the next version. Thanks
