### ISSUE TITLE
Display WooCommerce orders on the frontend

### ISSUE THREAD

**Issue by satomiao** [Crocoblock/suggestions#786]
Hi, I would like to request a feature which enable the customers' order to be displayed on the frontend. 

Toolset has that feature which allowing the customization of the customers orders layout and display it on the frontend. 
https://toolset.com/learn/create-an-ecommerce-wordpress-site/displaying-more-information-from-woocommerce/how-to-display-woocommerce-orders-on-the-front-end/

Post Table Pro by Barn2 Plugin has similar feature too
https://barn2.co.uk/list-woocommerce-orders-front-end/

Also, for multi-vendor marketplace (for example the site with WooCommerce Product Vendors installed or with just simple front-end **Product** submission form), to display the orders that a "vendor" received. 
 
Thanks.

**Comment by UraraReika** [comment]
Hello @satomiao !

You can use Query Builder from JetWngine plugin and with the help of Listing Grid widget output orders on frontened.
