### ISSUE TITLE
in my site user can uploading pdf file, for post type "post" , post meta name/id:   'content_file_media',  'content_file_media' meta store file in the format of : media URL,  by using jetform , form i d is 478,  i need to stop form submission if pdf file is already uploaded to database. write code for show the form submission error or status in form bottom this error shuld shown to users. stop submitting the form.

### ISSUE THREAD

**Issue by Lobhinitech** [CrocoBlock/suggestions#7860]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by Crocoblock** [comment]
https://github.com/Crocoblock/suggestions/issues/7861
