### ISSUE TITLE
bug at 3.5.8 with wpml 

### ISSUE THREAD

**Issue by kochhase** [CrocoBlock/suggestions#7865]
Undefined array key "enable_single_user_page" in /var/www/vhosts/hosting149688.a2ec7.netcup.net/httpdocs/h2-national-summit.de/wp-content/plugins/jet-engine/includes/compatibility/packages/wpml/inc/profile-builder.php on line 51

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ihslimn** [comment]
Thank you for reporting. This issue does not affect the functionality of the plugin. Yet, it is fixed, this warning will appear no more in the next version of the plugin

**Comment by Crocoblock** [comment]
was fixed and released in the JetEngine 3.6.0
