### ISSUE TITLE
Coupon and login icons - top checkout template not updating

### ISSUE THREAD

**Issue by taniasupagirl** [CrocoBlock/suggestions#7866]
**Describe the bug**
The icon colour of the Checkout top template for the coupon and login form does not update to the colour I specified

Here are my settings specified in elementor:
![Screenshot 2024-11-20 at 08 47 36](https://github.com/user-attachments/assets/67dd5b50-d39f-4e5a-8742-e4178317a400)

Here is what the page looks like
![Screenshot 2024-11-20 at 08 49 30](https://github.com/user-attachments/assets/17d4acff-4c24-4c77-9416-ea86493a41f7)

Icon still shows the default blue.

**Comment by taniasupagirl** [comment]
The same happens on the cart page. Styling (colours and fonts) selected on elementor is not applying to the template pages.

**Comment by ArongodCoder** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/) our support team.

Thank you!
