### ISSUE TITLE
JetFormBuilder Server Callback Not Working After Disabling WordPress Endpoints

### ISSUE THREAD

**Issue by hazratbilal0079** [CrocoBlock/suggestions#7867]
When I disable WordPress REST API endpoints for security purposes, the JetFormBuilder server callback functionality stops working. This happens even when all form conditions are correctly configured.

Details:
JetFormBuilder relies on server callbacks for certain dynamic actions.
Disabling REST API endpoints for security purposes appears to interfere with these callbacks.
Despite meeting all form validation and conditions, the expected behavior (such as form submissions or field population) fails to occur.
How can I resolve this issue while maintaining the security of my WordPress REST API? Is there a way to allow specific JetFormBuilder endpoints or configure the settings to ensure callbacks work without compromising security?
![Screenshot 2024-11-20 201855](https://github.com/user-attachments/assets/aaebbc3c-9398-4ea5-88a7-4447ce7aa38c)

**Comment by hazratbilal0079** [comment]
![Screenshot 2024-11-28 095127](https://github.com/user-attachments/assets/a5d99dd2-212f-4b1a-8b82-0d74fe2218ad)
The issue is still there and not yet gets fixed even with the rest api fixed in the 3.4.4 update!

**Comment by MjHead** [comment]
You need to check how to include/exclude specific callbacks on the side of the tool with which you disabled the Rest API. As for now the only solution move this check on the action side and report this error only after submit the form. We added an ability to change the way how the validation endpoint processed into the roadmap, but it will be implemented not earlier than in 2-3 months

**Comment by hazratbilal0079** [comment]
Still awaiting for this implementation.

**Comment by aalexandr21** [comment]
@hazratbilal0079 

Was added in 3.5.0
https://prnt.sc/7I9bpc6MC7mk

**Comment by hazratbilal0079** [comment]
I have 3.5.1.2 version and still unable to find that option.
![Image](https://github.com/user-attachments/assets/115ff153-5672-4025-a56a-1e8dafab8cd8)

**Comment by aalexandr21** [comment]
@hazratbilal0079 

Sorry for that 😅

This option will be in the next update

**Comment by hazratbilal0079** [comment]
not yet even in 3.5.2
