### ISSUE TITLE
Shopping cart trigger type mixed

### ISSUE THREAD

**Issue by zahnd** [CrocoBlock/suggestions#7869]
Hi

The shopping cart widget has two trigger types: hover and click.
![image](https://github.com/user-attachments/assets/8a41eeaf-2740-4220-baac-c1e644483e86)

When the shopping cart is set to hover, it works fine on desktop. But on mobile, it doesn't work as the first click triggers the href and opens the cart. 

It would be nice if on mobile, one click would trigger the hover and a second click opens the link (to the cart). 

Or have some sort of a mixed trigger with which on desktop, hover would open the cart, and on mobile, a click would open the cart.

As always, thank you very much for your work and great plugins!

Thanks and best regards, 
Stefan

**Comment by Crocoblock** [comment]
added in JetBlocks 1.3.16
