### ISSUE TITLE
Jet Tricks: Jet Unfold Widget - Undefined array key "separator_height"

### ISSUE THREAD

**Issue by rtpHarry** [CrocoBlock/suggestions#7872]
I've been working on a site recently, and noticed that the error logs are filling up with this:

```
"PHP message: PHP Warning: 
Undefined array key "separator_height" in 
/www/public/wp-content/plugins/jet-tricks/includes/addons/jet-unfold-widget.php 
on line 999", 
```

I'm not sure if this is new or what, but its making it difficult to work with the error logs as its getting in the way.

Can a fix be applied for the next version please?

**Comment by Crocoblock** [comment]
was fixed and released in JetTricks 1.5.0
