### ISSUE TITLE
Reinstate Previously working JetForm Builder UI/UX

### ISSUE THREAD

**Issue by RoldanAncajas** [CrocoBlock/suggestions#7883]
Hi Guys,

I just noticed the radical changes to the JetForm Builder UI/UX. Sorry, but it has become really ugly now.

![image](https://github.com/user-attachments/assets/3694d67a-f52e-4ed7-9e66-a2709d81162c)

As compared to the previous interface:

![image](https://github.com/user-attachments/assets/144684b0-efe9-4d1a-8c24-fc0c50f76ae5)

While I understand the changes, I find that the new layout is quite difficult to navigate compared to the previous version.

I'm currently working on a project using the builder, and I’m having some trouble finding elements, as some are not immediately visible and require extra clicks to access.

To clarify, the issue isn’t with the functionality—those features are excellent—but rather with the user interface and overall layout. I believe there’s room for improvement in terms of making the interface more intuitive and user-friendly.

If possible, I would suggest considering a return to some elements of the previous UI design as a starting point, and then building on it for improvements. The earlier design was simpler, cleaner, and much easier to navigate, which I think would benefit users like myself.

The former layout/design illustrates the more intuitive, user-friendly design that many developers, including myself, appreciate. The current Gutenberg-like layout, while functional, feels a bit more cumbersome.

I’m confident that with some adjustments, the JetForm Builder can become even more user-friendly.

Looking forward to hearing your thoughts.

Best regards,
Roldan

**Comment by MjHead** [comment]
You compare separate plugin and legacy module inside JetEngine
