### ISSUE TITLE
Support for Custom SVG Admin Menu Icons in JetEngine

### ISSUE THREAD

**Issue by PinkStudio-Design** [CrocoBlock/suggestions#7885]
**Feature Description:**
Enable support for custom SVG files as admin menu icons when creating custom post types or taxonomies in JetEngine. This would allow users to upload or link SVG files that render directly in the WordPress admin menu, providing a modern, scalable alternative to Dashicons or base64-encoded images.

**Why It’s Important:**
- Brand Consistency: Developers can use branded SVG icons that align with the site's identity.
- Scalability: SVGs provide higher quality and adaptability across devices compared to raster images.
- Ease of Use: Simplifies the process by eliminating the need for PHP functions or external plugins to add custom SVG icons.
- Modern Standards: SVGs are widely used in modern web development and provide better styling flexibility.

**Desired Effect:**
When creating a custom post type or taxonomy in JetEngine, users should see an option to upload or link an SVG file for the admin menu icon. The icon should render correctly in the WordPress admin interface without the need for manual coding.

**Example of Existing Implementation:**
Currently, users must rely on custom PHP snippets or additional plugins to add SVG icons, which can be cumbersome and increases the dependency on external tools.

Example Code (Current Alternative):

```
function add_svg_menu_icon() {  
    add_menu_page(  
        'Custom Post Type',  
        'CPT',  
        'manage_options',  
        'cpt_slug',  
        '',  
        'data:image/svg+xml;base64,[encoded_svg_data]'  
    );  
}  
add_action('admin_menu', 'add_svg_menu_icon');  

```

**Where It Should Be Used:**
This feature should be integrated into the "Advanced Settings" section of JetEngine's post type and taxonomy creation interface. Developers should be able to upload the SVG file through the UI or input a URL to an external SVG.

**Screenshots/Links:**
[StackOverflow Discussion on Custom SVG Menu Icons](https://stackoverflow.com/questions/30620226/custom-svg-admin-menu-icon-in-wordpress)

This feature will modernize JetEngine's customization capabilities and provide a seamless user experience for developers.

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/6875)
