### ISSUE TITLE
JetSmartFilters - Active Filters - Active filters from glossary separated by comma - Usability issue

### ISSUE THREAD

**Issue by Joe-Bloggs** [CrocoBlock/suggestions#7886]
I'm using JetSmartFilters for a listing grid. I've got quite a few filters setup with Glossaries.

The issue is the 'Active filters' output the glossary as a string of terms separated by comma.

<img width="1338" alt="Screenshot 2024-12-03 at 2 42 49 pm" src="https://github.com/user-attachments/assets/7f9300ef-cd86-4b2b-b274-8165f379e9a6">

In the example above, I'm filtering holidays properties by monthly availability. 

If I now want to remove the filters, I can't just remove each month individually, I need to remove everything and start again. 

Is there any way to output the glossary items individually, rather than a string of all items used as filter?

**Comment by Crocoblock** [comment]
Hi @Joe-Bloggs 
use the Active Tags widget.

**Comment by Joe-Bloggs** [comment]
> Hi @Joe-Bloggs use the Active Tags widget.

Ah okay, that's better, thank you.
