### ISSUE TITLE
JetForm Add-on - PayPal Recurring Payment 1.1.1 - Cancel via PayPal / Admin Not Working.

### ISSUE THREAD

**Issue by janmaartendewit** [CrocoBlock/suggestions#7887]
**Describe the bug**

1 - User Canceling an account, if someone cancels their account from PayPall it is not registrated in the JetFormBuilder/subscriptions. It stays active.
2 - Admin - Canceling the account, manually as administrator from the Subscriptions page I get the popup 
"Successfully suspended subscription! 204: No Content" or "Invalid HTTP code. 422: Unprocessable Entity"

<img width="390" alt="Screenshot 2024-12-04 at 10 47 10" src="https://github.com/user-attachments/assets/ce255589-c302-4f71-8321-1564904894a4">

1. Users pays for a subscription. JetForms with PayPal Recurring Payments 
2. Payment Complete -> User Role changed. 
3. Users Cancels a subscription via PayPall.
4. User Role is not changed. While it should be downgraded.

**Expected behavior**
User Role should be changed when a user cancels membership on Paypal.

Already submitted this at the Crocoblock support.

I am waiting over **3 months** for a fix, this major bug is critical for the Add-On because, if it doesn't function properly, the Add-On loses its purpose entirely.

**Comment by Crocoblock** [comment]
Hi @janmaartendewit 

We've tried to reproduce your issue and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also, have you contacted our support team regarding this case - https://crocoblock.com/help-center/ If not, please create a ticket including access details for your site where the issue occurred to make sure we can help you.
