### ISSUE TITLE
Jet engine smart filter location and distance - Country Restriction

### ISSUE THREAD

**Issue by Dims8** [CrocoBlock/suggestions#7889]
Hello, would it be possible to add a country restriction to the location and distance smart filter

**Comment by Crocoblock** [comment]
Hi @Dims8 

You can use the code from this page to limit the search of addresses to certain countries: https://gist.github.com/LaxusCroco/6e3b65ba16d09e79a404553ce6eb5bfb

Our code example limits the search to French locations: https://prnt.sc/QA0oogfJeoYi

This is the list of supported parameters: https://developers.google.com/maps/documentation/places/web-service/autocomplete#optional-parameters

**Comment by Dims8** [comment]
I inputed the code and it hasn't changed anything i still get places from all countries, would it be an issue with the version of jet engine smart filters?

**Comment by Crocoblock** [comment]
@Dims8 
send screenshot of your settings from JetEngine->JetEngine->Maps Settings please

**Comment by Dims8** [comment]
![Uploading Screenshot 2024-12-05 at 4.38.14 PM.png…]()

**Comment by Dims8** [comment]
![Uploading Screenshot 2024-12-05 at 4.38.14 PM.png…]()

**Comment by Dims8** [comment]
[Screenshot 2024-12-05 at 4.38.14 PM.pdf](https://github.com/user-attachments/files/18019986/Screenshot.2024-12-05.at.4.38.14.PM.pdf)

**Comment by Crocoblock** [comment]
Are you aadding the code to the function.php child theme or code snippets plugin? 
If yes - please, contact our support team regarding this case - https://crocoblock.com/help-center/ create a ticket including access details for your site where the issue occurred to make sure we can help you.

**Comment by Dims8** [comment]
Yes i tried adding with both but it still doesnt change anything unfortunately
