### ISSUE TITLE
[Bug] Conditional visibility for repeater fields not working?

### ISSUE THREAD

**Issue by aayla-secura** [CrocoBlock/suggestions#7892]
**Describe the bug**
When defining a repeater field with several fields, and setting up conditional visibility for some sub-fields based on another sub-field (a switcher), then in the editor, none of the sub-fields is hidden regardless of switcher status.

**To Reproduce**
1. Create a meta box for a post type for example
2. Create a repeater field
3. Create one switcher sub-field and two other sub-fields
4. Define conditional visibility for the two other sub-fields: show one when switcher enabled and show the other when switcher disabled
5. Create or edit a relevant post and add a repeater item
6. See that all sub-fields are shown regardless of switcher position

**Expected behavior**
I expect it to work like the conditional visibility for non-repeater fields where a field can be hidden/shown based on switcher position (or in general value of another field)

**Screenshots**
Step 4:
![Screenshot 2024-12-06 111505](https://github.com/user-attachments/assets/f5a63995-7845-4f44-860c-770730596289)
![Screenshot 2024-12-06 111457](https://github.com/user-attachments/assets/e80f6034-47f2-4d1f-8225-bd215e6044e2)

Step 6:
![Screenshot 2024-12-06 111533](https://github.com/user-attachments/assets/652887ff-bc70-4995-bc59-cde6e6b2fed9)
![Screenshot 2024-12-06 111527](https://github.com/user-attachments/assets/a0421600-c1d5-470e-a594-c07944cea038)

**Desktop (please complete the following information):**
 - Chrome Version 131.0.6778.87 (Official Build) (64-bit)

**Comment by Crocoblock** [comment]
Hi @aayla-secura 

We've tried reproducing your issue, and everything works fine. Could you please provide us with more detailed information about this issue, a screenshot of settings in the repeater field, version of JetEngine? Also, have you contacted [our support team](https://crocoblock.com/help-center) regarding this case? If not, please create a ticket including access details for your site where the issue occurred to ensure we can help you.

**Comment by aayla-secura** [comment]
Hi and thank you for replying :)

Huh, that's super strange... I can no longer reproduce it either! I have no explanation for why it was behaving like this before, I haven't changed anything or updated JetEngine (I was using the latest version). Oh, well, I guess please ignore then :)
