### ISSUE TITLE
JetEngine - Macros - Please add the option to return 'Labels' in macros

### ISSUE THREAD

**Issue by Joe-Bloggs** [CrocoBlock/suggestions#7899]
I've got a glossary select field and I simply want to create a macro that returns the 'Label' of the selected glossary item.

Currently, I can only return 'value' with %jet_engine_field_name|my_glossary_item|field_value% or return the field meta name with %jet_engine_field_name|my_glossary_item|field_name%.

No way to return only the label.

**Comment by Crocoblock** [comment]
@Joe-Bloggs You can use the shortcode generator https://i.imgur.com/iLROb5R.png 
then use this shortcode in the Shortcode Result macro https://i.imgur.com/Hx8KJXG.png

**Comment by Joe-Bloggs** [comment]
@Crocoblock the shortcode on its own renders the label perfectly fine and I think I can probably just live with the shortcode, however the solution using the shortcode in a macro, and then using the macro in the Customised field output of a dynamic field seems to completely break the page.

See the screenshot, this is what I'm trying to do and it's breaking the template.
<img width="613" alt="Screenshot 2024-12-10 at 9 15 25 pm" src="https://github.com/user-attachments/assets/7ad4d228-f997-4b38-a886-59340e071396">

**Comment by Crocoblock** [comment]
Try add `%` symbol here https://i.imgur.com/UECKCPG.png

**Comment by Joe-Bloggs** [comment]
Yep ok, that solves the issue of the broken template. % added and the template is not broken, that worked. Thank you.

But now I'm just trying to figure out why is the field not returning or not showing any output if it's placed inside Bricks query loop.

Basically, I've got 2 meta fields setup:

1. first field is the 'Currency' where user selects the currency (which is the Glossary item, the one I'm trying to return)
2. second field is the Repeater field for the price table - product name and the price.

See the screenshot here: 
<img width="1354" alt="Screenshot 2024-12-10 at 9 47 37 pm" src="https://github.com/user-attachments/assets/4ca63502-e453-43f2-b3f5-bc5f7913e6e2">

What I'm trying to achieve is to create a repeater query loop as on the second screenshot that shows product name, duration, and the price.

The price field is a dynamic field and I need to customise the output of the field and put the chosen currency infront of the price number.

The shortcode seems to work fine and returns the correct value/label when it's outside the query loop, but when I place the shortcode inside the query loop I don't get any output at all. 

<img width="637" alt="Screenshot 2024-12-10 at 9 51 27 pm" src="https://github.com/user-attachments/assets/a894a86f-c5fa-4e75-b0b3-d372c7529c7d">

Any idea what am I doing wrong here?

**Comment by Crocoblock** [comment]
Please, contact our support team](https://crocoblock.com/help-center) regarding this case, and create a ticket including access details for your site where the issue occurred to ensure we can help you.
