### ISSUE TITLE
Do not hide lable Jet Smart Filters

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#790]
Hello, the filter values ​​are hidden, but the headers are not hidden, as a result, the user sees many headers and does not understand why they were here, since they have nothing to do with this category of goods.

The insertion of such custom code solves this problem, but I would like such a basic function to be implemented from the box. 
https://prnt.sc/qgicsw
/*Оригинал*/
Здравствуйте, скрываются значения фильтра, но не скрываются заголовки, в результате пользователь видит множество заголовков и не понимает почему они тут оказались, так как никакого отношения к данной категории товаров они не имеют. 

Эту проблему решает вставка такого кастомного кода, но хотелось бы чтобы такая базовая функция, была реализована с коробки
https://prnt.sc/qgicsw

<script>
jQuery(document).bind('ready ajaxComplete', function() {
jQuery('.jet-filter').each(function () {
//radio
var visible = jQuery(this).find('.jet-filter-row').length;
var hidden = jQuery(this).find('.jet-filter-row.jet-filter-row-hide').length;
if(visible > 0) {
if (visible === hidden) {
jQuery(this).hide(500);
} else {
jQuery(this).show(500);
}
}

//select
visible = jQuery(this).find('.jet-select__control option').length - 1;
hidden = jQuery(this).find('.jet-select__control option.jet-filter-row-hide').length;
if(visible > 0) {
if (visible === hidden) {
jQuery(this).hide(500);
} else {
jQuery(this).show(500);
}
}
});
});
</script>

**Comment by Floydtm** [comment]
@stasonua0, hi! This is added to plugin version 1.6.0 Check for updates
