### ISSUE TITLE
Date fields saved timestamp corresponds to date in UTC zone

### ISSUE THREAD

**Issue by aayla-secura** [CrocoBlock/suggestions#7903]
**Describe the bug**
Meta fields containing date, time, datetime, when saved as a timestamp, result in a timestamp that corresponds to the given date but in UTC zone rather than the local zone.

What I mean is, for example if a date field contains '2024-12-11T13:00' and its settings are to save it as a timestamp, the timestamp saved is `1733922000` which corresponds to 1pm UTC time on Dec 11, even though my timezone in Wordpress is UTC +2.

The Current date macro would return a timestamp in the local timezone, i.e. it will return `1733922000` when it is 3pm local time (UTC+2), and as a result timestamp comparison using this macro for the meta field (as part of a query builder query for example) would be equal at 3pm local time instead of 1pm.

I think this is unexpected. Date fields should be treated as being in the local timezone.

The conversion from the datetime selected in the field to a timestamp should assume the date is in the local timezone.

**Comment by MjHead** [comment]
Timestamp is saved as UTC. When you converting it back to display on the front - there is ability to choose how it will be converted - with timezone from settings or without. This behavior controlled by 'jet-engine/datetime/use-wp-date' hook. By default converting is disabled to avoid backward compatibility issues. To enable it you need to use this code snipet

```php
add_filter( 'jet-engine/datetime/use-wp-date', '__return_true' );
```
