### ISSUE TITLE
Cpt Custom Meta Storage with JetFilters in Taxnonmies Archive pages.

### ISSUE THREAD

**Issue by nachirvon** [CrocoBlock/suggestions#7908]
i have a custom cpt which use Custom Meta Storage.
i have filters and sorting for my cpt archive page. but this filters and sorting for metafileds dont work just in Taxnomies Archive Page. but in main cpt Archive page working very good.

**Comment by Crocoblock** [comment]
Hi @nachirvon 

We've tried reproducing your issue, and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also, have you contacted [our support team](https://crocoblock.com/help-center) regarding this case? If not, please create a ticket including access details for your site where the issue occurred to ensure we can help you.

**Comment by nachirvon** [comment]
> Hi @nachirvon
> 
> We've tried reproducing your issue, and everything works fine on our side. Could you please provide us with more detailed information about this issue? Also, have you contacted [our support team](https://crocoblock.com/help-center) regarding this case? If not, please create a ticket including access details for your site where the issue occurred to ensure we can help you.

------------------------------------------------------------------------------------------
Hello,
I have a custom CPT with **custom meta storage**.
i design custom archive page for this cpt and thier taxnomies.
in this archive page i have a ranged filter ( by jetfilter plugin) for  my grid listing of my cpt.
this filters was work in the archive page but dont work on the taxnomies archive page.
Of course, only when I use custom meta storage, the filters are not applied.

**Comment by Crocoblock** [comment]
@nachirvon 
I tried reproducing your issue, and everything works fine 
Contact [our support team](https://crocoblock.com/help-center) regarding this case, please create a ticket including access details for your site where the issue occurred to ensure we can help you.
