### ISSUE TITLE
Jetengine php generator for query builder + bricks more compability

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#7914]
I like to ask for an enhancement! 

1- when we make a query with JE query builder, it will be great to view/edit/copy the php code, and use it in bricks query editor(php) or any where else?

2- when we choose jetengine query in bricks query loop, we can't use other features like infinite scroll, live, search and ajax loaded... 
but if we use query editor (php) of bricks we have access to the features i mentioned above! 
please see the images to understand the issue

![IMG_20241216_155753_832](https://github.com/user-attachments/assets/00ed86f1-59a4-4118-ab6a-1fe3c37da3bd)
![IMG_20241216_155743_443](https://github.com/user-attachments/assets/31514b0b-3297-4bcb-badb-687aafecb5b6)

**Comment by MjHead** [comment]
Hi. 1st unfortunately is impossible. 2nd - added to the JetEngine 3.6.4 version backlog. Closing this issue for now in prefer of an internal issue to avoid duplicates.
