### ISSUE TITLE
JetFormBuilder - Conditional block - operator Equal doesn't work with checkbox/radio

### ISSUE THREAD

**Issue by Joe-Bloggs** [CrocoBlock/suggestions#7916]
Hey guys,

I've got a 'glossary' list created. Then, in my JFB form, I've got a checkbox field with a source from this glossary.

I then have conditional blocks in the form set up to show based on given values from the glossary.

I'm expecting the conditional block to show if the checked checkbox equals the chosen 'value'. 

The condition doesn't work if:

1. the operator is set to 'Equal' the 'value'
2. the operator is set to 'Equal' the 'Label'
3. the operator is set to 'Contains text' of the 'Label'

It will only work if the operator is set to 'Contain text' of the 'value'

Detailed screen recording here: https://www.loom.com/share/da457574d87249f388f166a4953ab322?sid=53db3cd1-f7cc-4435-8918-a1a339d2d91f

**Comment by Crocoblock** [comment]
@Joe-Bloggs Hi!
For fields with multiple values, you must use the `In the list` operator
