### ISSUE TITLE
JetMaps:  Filters + CPT compatible  Maps plugin

### ISSUE THREAD

**Issue by sbtre** [Crocoblock/suggestions#793]
I would loooove you to introduce **JetMaps**, which is a **JetSmartFilter**, **JetEngine Listing** and **Custom Type Type / Meta fields** compatible Crocoblock map extension for Elementor.

This would make the Jet plugin suite really epic and outstanding. Best using OpenStreetMap and Google Maps API ;-)

I had strong ressonance in Facebook CrocoBlock group, too:
https://www.facebook.com/groups/CrocoblockCommunity/permalink/2912420342182701/

**Comment by koystrubvs** [comment]
Hi
It will be cool if you just add a new type of record to JetEngine-Map (so already added to ACF)
And to add to the JetFilter is a new type of filter - Map.

**Comment by kaskad88** [comment]
Added in JetEngine 2.8.5
