### ISSUE TITLE
JetEngine: Load More doesn't work when offset is used

### ISSUE THREAD

**Issue by RumenGeorgieff** [Crocoblock/suggestions#795]
JetEngine has a problem. Its function for "Load More" (https://crocoblock.com/knowledge-base/articles/jetengine-how-to-use-load-more-functionality-within-listing-grid-widget/) doesn't work when Posts Query -> Order and Offset is used. It loads the same posts not old ones.

**Comment by kaskad88** [comment]
Fix for the next version (2.2.0).
Thanks for your report!
