### ISSUE TITLE
Dynamic Terms Not Showing on Shop Page When Filter Applied

### ISSUE THREAD

**Issue by MacGuyver-jv** [Crocoblock/suggestions#797]
I have a shop page that shows custom product attributes using a custom archive that utilizes "dynamic terms" and "products loop" These work fine from the main shop page. When I apply jet filters, I get the following warning "Dynamic Terms widget allowed only for Posts listing source or in Post context".

I believe this is a bug, and I would like to resolve it. If it is not a bug, is there another way to show custom product attributes?

I am using Wordpress v5.3.2, Elementor v2.8.3, and all of the latest Jet Elements as of January 4th, 2020.

I have attached pictures below. You can also see the way this works for yourself by going to: https://mymedicarefinder.com/?post_type=product and applying filters yourself.

Please let me know if any other information is required.

Without filters:
![single_product_no_filters](https://user-images.githubusercontent.com/50686550/71772808-cf803900-2f1f-11ea-9005-8276119dfe3d.png)

With filters:
![single_product_with_filters](https://user-images.githubusercontent.com/50686550/71772810-d1e29300-2f1f-11ea-9022-9767fef3298c.png)

**Comment by Floydtm** [comment]
@MacGuyver-jv, hi! Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help
