### ISSUE TITLE
Elementor Form Redirect Option is not taking dynamic value from Jet Engine Text Meta

### ISSUE THREAD

**Issue by Sayeed1440** [Crocoblock/suggestions#799]
Hi There,

If you go to this page and fill the download brochure form, the form gets submitted but the redirect is not working.

https://theresearchgate.com/product/nursing-conference-2020/

The form is made with the elementor form widget. The issue was from there end so I reported it to those guys. They said they will fix it in the next update. And as promised they fixed it when they released the 2.3 Pro version. However, it is still not working.

I went back to them again and they mentioned, they have fixed it and it's working for the ACF URL meta field but it's not working for the Jet Engine text meta field. They also asked me to inform you guys and said we will also notify our developers.

So, here I am.

Please look into the issue from your end once. Do let me if you need any further explanation on this. 

Thank You.

**Comment by Floydtm** [comment]
@Sayeed1440, hi! We fixed it for our part. Contact our support to fix this on your site. Thanks you!
