### ISSUE TITLE
New feature: multi field selection for JetEngine

### ISSUE THREAD

**Issue by casperroux** [Crocoblock/suggestions#8]
For more complex filtering options
Filter from one select to another and another....

**Comment by MjHead** [comment]
Hi @casperroux Did you mean something like this - http://prntscr.com/mnm4q2? https://www.tirerack.com/content/tirerack/desktop/en/homepage.html

**Comment by casperroux** [comment]
Yes…. Almost
I want to do Type / Make / Model / Year and then display a result
Type can by like Commercial / Agriculture / Construction / Motorcycle / Boat/ Passenger…..
The result can be a Tyre or battery or something else specific to a particular Vehicle Model….

**Comment by casperroux** [comment]
Lets say you have 2600 models: Merecedes, Toyota, Audi, BMW, Suziki.....
The 1st Select will make this less: if you choose Passenger, you now have 2000...
The 2nd Select will make it less: you choose Toyota, you have 90 models...
The 3rd Select will make it less: you have 1 or 2 or 3 depending on the year...
The 4th Select gives you then the final result of ONE... 
and then display the Tyre or battery or anything else related to that specific MODEL

Another request then, would probably be hide all "products" in the LISTING,... 
until all selects are used... (If this makes sense)
I don't want to display a lot of products if only one is applicable to a said Model...

**Comment by MjHead** [comment]
Thanks @casperroux We already planning to do something like this. Such feature will be added in next 2nd or 3rd major release of JetSmartFilters

**Comment by casperroux** [comment]
This is GREAT NEWS...
When this is done... I will be upgrading to LIFETIME :)

**Comment by casperroux** [comment]
Do you have any news/update with regard to this feature ?

**Comment by casperroux** [comment]
And still nothing....

**Comment by casperroux** [comment]
I would like to know if there is any progress in regard to this request.....

**Comment by kaskad88** [comment]
This feature is available in JetSmartFilters v1.6.0 and later. Demo - https://demo.crocoblock.com/cardealer/
