### ISSUE TITLE
JetSmartFilters - multiple Query Variables in one filter

### ISSUE THREAD

**Issue by secondsky** [Crocoblock/suggestions#802]
Option to use more than one Query Variable when creating a filter.
This is sometimes useful as i might want to search in two fields for the same value.

**Comment by delightfuldude** [comment]
+1

**Comment by Lonsdale201** [comment]
+1 :)

**Comment by UmairAnwar** [comment]
can you tell me how to use it ?

**Comment by Lonsdale201** [comment]
Not developed yet. :(

**Comment by alessandrotorres** [comment]
Any news for this useful feature?

**Comment by Lonsdale201** [comment]
This feature already implemented.

**Comment by alessandrotorres** [comment]
In Search type filter I set multiple variables but in search results It
seems variables doesn't work simultaneously, but one exclude others.

Il dom 31 ott 2021, 22:44 Lonsdale201 ***@***.***> ha scritto:

**Comment by 12beto12** [comment]
I have the same problem that alessandrotorres, I'm able to set multiple Query Variables, but when I type in the search filter it only shows the results of one match specific to one of the Query Variables, if I write a field that I know it's part of another variable, it doen't show any results. Would be usefull to add some type of logical conditions like "AND" or "OR" to let it look on another variables. This could be accomplished by setting multiple search filters but it seems like a waste of space in the filters area

**Comment by MjHead** [comment]
Done

**Comment by damianrivadulla** [comment]
Hi, any update here? 
I read "done" but there is no option for searching in multiple fields and the same time. 
Thanks

**Comment by araujolima129** [comment]
Mesmo problema
