### ISSUE TITLE
Visual Form Builder (JetForms?)

### ISSUE THREAD

**Issue by vmorten** [Crocoblock/suggestions#804]
I would really like to see a visual form builder in Crocoblock like the one in Elementor Pro (https://elementor.com/widgets/form-widget/) or Raven Elements (Jupiter X Theme). Maybe it could be called JetForms or add it to an existing tool.

Contact Form 7 is a good plugin don't get me wrong, but it feels so old compared to the form widget in Elementor Pro. It's so easy and quick to build forms with this tool and everything is in the front end while also having some advanced features. To integrate a CRM like MailChimp just paste the API in the settings and it's done.. no need for an extra plugin.

What could make it better than Elementors form widget would be to give more customization options to stuff like Selectors, Checkboxes and Radio buttons etc.

I hope to see this in the future!

**Comment by stasonua0** [comment]
Jet Engine has a visual form designer with powerful functionality

**Comment by vmorten** [comment]
Thank you, my bad! It must have slipped past me.

Had a look and it seems good, but does it integrate with CRM tools like MailChimp? Can't see it, as a marketer this option is crucial. Having to install two extra plugins like CF7 and MailChimp-addon to get this feature is such a waste and doesn't help to keep the site slim with minimal plugins.

**Comment by stasonua0** [comment]
https://jetelements.zemez.io/subscribe-form/

вт, 7 янв. 2020 г., 11:47 vmorten <notifications@github.com>:

**Comment by vmorten** [comment]
I've seen the Subscribe form, but it lacks more advanced options like:

- Message field.
- Radio buttons etc.
- Being able to send custom notification emails (via uniqe ID and shortcode) to admins or other key roles through "Actions after submit".
-  Set custom width in % to each field in the form.

With these options I can create one single form for collecting prospects, sending out a lead magnet and adding them to a CRM tool with automation. With the current setup I either have to use several other plugins or have two different forms which is not ideal.

**Comment by kaskad88** [comment]
Hi, @vmorten. The MailChimp integration will be added in JetEngine 2.3.0

**Comment by vmorten** [comment]
Thank you for answering @kaskad88.

Will we also be able to send a email as a notification? For example in the Elementor Pro Form I can set "Actions after submit" to "Mailchimp" and "Email". That way a prospect can subscribe mailchimp and we will recieve a normal email notification on this action.

**Comment by kaskad88** [comment]
> Thank you for answering @kaskad88.
> 
> Will we also be able to send a email as a notification? For example in the Elementor Pro Form I can set "Actions after submit" to "Mailchimp" and "Email". That way a prospect can subscribe mailchimp and we will recieve a normal email notification on this action.
Yes, it is possible. https://crocoblock.com/knowledge-base/articles/jetengine-booking-form-send-email-notification-overview/

**Comment by kaskad88** [comment]
> > Thank you for answering @kaskad88.
> > Will we also be able to send a email as a notification? For example in the Elementor Pro Form I can set "Actions after submit" to "Mailchimp" and "Email". That way a prospect can subscribe mailchimp and we will recieve a normal email notification on this action.

Yes, it is possible. https://crocoblock.com/knowledge-base/articles/jetengine-booking-form-send-email-notification-overview/

**Comment by vmorten** [comment]
Thank you! Looking forward to JetEngine 2.3
