### ISSUE TITLE
Categories Grid 

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#805]
Increase the number of category grid columns. Right for now the max value is 6 https://prnt.sc/qkvjly.

**Comment by ryanfurtner** [comment]
I came here to say this one, I really need it for a site im working on at the moment! Damn!

**Comment by ryanfurtner** [comment]
Any update on this?

**Comment by Floydtm** [comment]
Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
