### ISSUE TITLE
Use JetBookings to book a fitness class

### ISSUE THREAD

**Issue by pixelbirdptyltd** [Crocoblock/suggestions#806]
Use JetBookings to allow logged in users to see a list of available fitness classes that they can click a "Book Class" button, where the admin can set a limit on the total number of bookings per class to restrict numbers. If a particular class is full then it would say something like "Class Full". 

Further to that a Waitlist could be set so people could join the waitlist and as people cancel their booking inside a cancel window timeframe the first person on the waitlist would join the class.

**Comment by MjHead** [comment]
Can be done with JetAppointments
