### ISSUE TITLE
JetSearch and JetBlog compatibility issue with Dokan Multi Vendor plugin

### ISSUE THREAD

**Issue by Hameedhudeen** [Crocoblock/suggestions#807]
**Describe the bug**
I'm using Dokan for multi-vendor functionality. JetSearch plugin conflicted with several pages (Showed blank pages) and statistics of Dokan which I have attached in the images below. I contacted Dokan about this, they told me that JetPlugins must make some changes
to make it compatible with Dokan.
Images: https://imgur.com/a/pBzDla9

**To Reproduce**
1. Install & enable Dokan and JetSearch or JetBlog
2. Go to Dokan's admin dashboard from wp-admin backend
3. Under "At a Glance", the content are not visible.
4. Go to withdraw, vendor pages under Dokan dashboard in wp-admin. The pages are blanked out
5. This issue only occurs with Dokan when JetSearch or JetBlog are activated.

**Expected behavior**
I kindly request you to fix this bug. Dokan is a widely used multi vendor platform.
These plugins render some major functions of it unusable.

**Screenshots**
https://imgur.com/a/pBzDla9

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Issue tested on Dokan v 2.9.30, JetSearch 2.1.0 and JetBlog 2.2.0

**Comment by Floydtm** [comment]
This was fixed in the plugin version 2.1.1
