### ISSUE TITLE
Horizontal Timeline - Slide 3 dates/items at once

### ISSUE THREAD

**Issue by ninjaclan** [Crocoblock/suggestions#808]
I am using the Horizontal Timeline widget and I need a feature missing on settings: The possibility to slide more than 1 date/item at once when clicking on prev/next navigation arrows.

**Comment by ninjaclan** [comment]
Hi guys, how can i change manually the code to move 3 dates at once when click on arrows.
![aaa](https://user-images.githubusercontent.com/47866733/74371933-7d50f400-4db8-11ea-885c-036754113033.jpg)

**Comment by kaskad88** [comment]
Added for the next version.
Thanks for your report!
