### ISSUE TITLE
JetSmartFilters multiselect

### ISSUE THREAD

**Issue by rocketeer76** [Crocoblock/suggestions#811]
Regarding JetSmartFilters. I would like to have a dropdown with multiselect checkboxes. That way the layout of the site can align with other dropdown lists.

https://www.cssscript.com/multiselect-dropdown-list-checkboxes-multiselect-js/

You can also find an example here. They call it fselect:
https://facetwp.com/documentation/facets/facet-types/fselect/

In an ecommerce store, I would be able to have a dropdown list where I can select and filter several colors with checkboxes instead of having separate individual checkboxes outside of the dropdown list.

**Comment by justdudeone** [comment]
Yes, multi-chose filter fields are absolutely necessarily!!! Add it please!!!

Better samples at: https://github.com/Crocoblock/suggestions/issues/1125

**Comment by rocketeer76** [comment]
Any news on this feature request?

**Comment by anderoav** [comment]
Any news?

**Comment by nreljed** [comment]
#3885

**Comment by c-kunnen** [comment]
Any updates on this request? Would be a really nice feature to have.

**Comment by MjHead** [comment]
Done (as additional options for the Checkboxes filter)

**Comment by anabellafp** [comment]
@MjHead Is this implemented already? I can't find this option anywhere...

**Comment by digitalmurph** [comment]
> Done (as additional options for the Checkboxes filter)

HI, please can you tell us exactly where to find this setting? I cant see it anywhere! Thanks

**Comment by portrayaloflife** [comment]
+1

**Comment by atikrahman146** [comment]
+1

**Comment by Tokyaina** [comment]
+1

**Comment by Crocoblock** [comment]
https://crocoblock.com/knowledge-base/jetsmartfilters/jetsmartfilters-how-to-create-a-new-filter-and-apply-it-to-publications/#dropdown-enabled
