### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ghost** [Crocoblock/suggestions#812]
Hi. Was asked to leave a suggestion for features. Relates to the booking system.

1) The dates in/out from the original search should follow through to the single page. Currently the user creates a search and then has to put the same dates in again on the form.

2) Pricing should be integrated in some way. How much a property costs, seasonal pricing and a system that when the user selects dates, the total cost comes up.

3) Following number 2 above, payment integration.

**Comment by UraraReika** [comment]
All of this already exist in the product.
