### ISSUE TITLE
Jet Smart Filters, Products Loop, and Item Count do not work in unison

### ISSUE THREAD

**Issue by MacGuyver-jv** [Crocoblock/suggestions#813]
I have a somewhat specialized product that needs custom categories. I also need to display my custom attributes in an attractive way. I currently use an archive template combined with products loop, so I can have a custom product view when displaying my shop page. 

There are currently only 30 products while I set up my website, but I plan to have thousands. I will eventually need to be able to filter on factors such as state, county, year, and product category.

 I currently use jetsmart filters to filter on county and state. When I apply the filters, the product count does not update. When I click on the next page, it simply goes to the next page as if there were no filters applied. Neither of these situations are ideal.

I either need the product count and pagination buttons to work with the filters, or I need to be able to set the maximum number of products that will show up in a products loop. Otherwise, I will not be able to display all of my products that fit my selected filter. Another solution would be to make product grid or product list fully customizable with custom taxonomies.

**Comment by realstephenzhao** [comment]
You're right.

JetSmartFiters can't work with default wordpress archive pagination(slug like: `.../blog/page/2`) currently, which is created by option from built-in Elementor Posts or Posts Pagination from JetElements. Whenever I click the pagination to other pages, applied filters would be blank again. I hope it could be fixed since this is very important to SEO.
@Floydtm

**Comment by Floydtm** [comment]
I don’t quite understand your request. Filters work only with the pagination widget from the plugin itself. In order for the product counter to be updated, you need to configure indexing options. If you display products using the products loop, you must configure the number of products in the settings of the woo plugin. If you still have questions, please issue them in more detail with screenshots or a video. You can also contact our support team.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. Hopefully, you were able to find a solution to your problem! If you still need help with this issue or have any other questions about our product, please start a new thread.
