### ISSUE TITLE
JetEngine: Allow Dynamic Image to grab author photo/gravatar

### ISSUE THREAD

**Issue by tf5bassist** [Crocoblock/suggestions#819]
Currently, there is no way to include a dynamically provided post author photo and/or avatar/gravatar in posts.  Please update the Dynamic Image widget to pull not just post image/thumb, but also post author photo/avatar/gravatar.

As there is no author block included in any of the Crocoblock plugins, this would be critical to the forthcoming functionality of making a single post template.

**Comment by MjHead** [comment]
Done
