### ISSUE TITLE
JetElements: Post Navigation including post title

### ISSUE THREAD

**Issue by tf5bassist** [Crocoblock/suggestions#820]
The JetElements Post Navigation box does not appear to have a way of pulling the post title of the previous or next post the way that even the Kava theme post navigation offers.  For those of us not using Kava theme (or completely ignoring functionality of the theme being used) and designing entirely in Elementor, having the ability to customize the previous/next post navigation to include the post titles being referenced is very helpful.

**Comment by Floydtm** [comment]
merge with #503
