### ISSUE TITLE
Cherry Framework Bug causes failed asset loading in JetMenu

### ISSUE THREAD

**Issue by jsonhuntrods** [Crocoblock/suggestions#831]
JetMenu uses the Cherry Framework which currently has a bug and is not maintained anymore.

This is the issue:
https://github.com/CherryFramework/cherry-framework/issues/178

This is the fix:
https://github.com/CherryFramework/cherry-framework/pull/181

Using a fork of Cherry Framework with that PR would fix the problem, the bug specifically is that JetMenu loads assets from the wrong directory at times, depending on your Wordpress configuration. The result is cherry-js-core.js and cherry-handler.js 404. A simple way to reproduce would be to just install JetMenu in production on a site and check the JS console when loading. The primary difference in the wrong asset path is that "www" is appended to the beginning when it shouldn't be.

**Comment by ZemezLab** [comment]
Cherry Framework 5 was successfully deleted (v1.6.0)
