### ISSUE TITLE
JetWoo Builder's Taxonomy Tiles collapse with IE11

### ISSUE THREAD

**Issue by eijimorotomi** [Crocoblock/suggestions#832]
I purchased JetWoo Builder for using Taxonomy Tiles.
And it seems pretty convenient.

But when I see the tiles in demo page with Internet Explore 11, it collapse pretty hard.

https://crocoblock.com/widgets/taxonomy-tiles/

**Desktop**
 - OS: Windows 10
 - Browser: Internet Explore
 - Version: 11

It will be great, if you can resolve this collapse.
Thanks!

**Comment by UraraReika** [comment]
Hi, @eijimorotomi! Based on the fact that we are developing expanding functionality for the elementor plugin, we rely on their recommendations. With version 3 of their plugin, they stopped supporting IE. https://developers.elementor.com/elementor-dropping-support-ie/
