### ISSUE TITLE
Jet Elements Dashboard Bug Causes Assets To Not Load - Fix Included

### ISSUE THREAD

**Issue by jsonhuntrods** [Crocoblock/suggestions#833]
The Jet Elements Dashboard fails to instantiate on some hosts because the JS it depends on can't load.

This is similar to https://github.com/Crocoblock/suggestions/issues/831 but the bug is actually present in the plugin code - not a dependency.

In `plugins/jet-elements/includes/module/loader.php` - function `include_modules()`

This

`$url = str_replace(
   '\\',
   '/',
   str_replace( untrailingslashit( ABSPATH ), esc_url( site_url() ), $dir )
);`

should be changed to 

`$url = str_replace(
   '\\',
   '/',
   str_replace( plugin_dir_path( $dir ), plugin_dir_url( $dir ), $dir )
);`

in order to ensure the JS loads properly.

Specifically this handles when WP is located in a subdirectory like "www" on some common WP hosts.

**Comment by kaskad88** [comment]
Hello. To solve this problem, try installing this plugin [jet-fix-framework-url.zip](https://github.com/Crocoblock/suggestions/files/4354578/jet-fix-framework-url.zip). If the problem persists, please contact our support team at https://crocoblock.com/help-center/ for instructions on how to solve this problem (and mention that I was directed by you and refer to this problem).
