### ISSUE TITLE
Multiple Markers on Map showing all entries from custom post type 

### ISSUE THREAD

**Issue by eybel** [Crocoblock/suggestions#838]
For real state, hotels, turism, car dealers, construction, authors, listing items type of websites having 1 map showing all entries from a custom post type would make a big difference. I cant use the advanced map widget since I can only add markers manually, that wont work for most of my projects.

a Pin or Marker could come from a meta field (location, maybe coordinates or address) from each post. Then the Map Widget with some settings could show all those pin/markers.

Thank you

**Comment by stasonua0** [comment]
Guys, we really want to make such sites using Crockoblock. Give us such an opportunity please! :)
https://myhometheme.net/agency/

**Comment by eybel** [comment]
Awesome! thank you for all the hard work, our team is definitly staying with crocoblocks.

**Comment by shibindinesh** [comment]
+1 For the feature @stasonua0 @eybel There is a free plugin called "[Travelers Map](https://wordpress.org/plugins/travelers-map/)" which does this functionality, but they do not use Google Map and instead use another free map service. Would love to see Crocoblock team implement the same functionality in Map widget (Google Maps)

**Comment by kaskad88** [comment]
This functionality is now at the testing stage and will be available in JetEngine v2.3.0.
I merged this issue with #136, which is on the same subject so we could deal with it more efficiently.

**Comment by eybel** [comment]
Great news! You guys are definitly taking crocoblock to the next level.

With this and *Profile User Builder* and its future features (like: control
how many posts user can upload and/or assign pakackes to them "bronc,
silver, gold") I can definitely create these type of websites:

1) Real states (with agents since they will be limited on how many posts
they can upload)
2) Car Dealers
3) Bookings (hotels, hostels, rooms for rent, etc...
4) Others in mind...

Thank you for letting me know.
