### ISSUE TITLE
JetSearch with Products out of stock

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#842]
**Describe the bug**
Hello, I would like to know how I can hide out-of-stock products from research and from the rest of the site. I have already activated the option "Hide out-of-stock products in the catalog", but it doesn't work.

**Screenshots**
https://prnt.sc/qrk4us
https://prnt.sc/qrk4xd
https://prnt.sc/qrk4z3

**Comment by marcofrasson** [comment]
Hello, what's up? I understand that they are in high demand, but when bugs hinder the full functioning of the plugin, it ends up delaying all customers that use the plugin.

**Comment by AmitBobrov** [comment]
Any progress?
It's an otherwise awesome plugin, but I can't use it because it shows a lot of out of stock products.

**Comment by marcofrasson** [comment]
Agree @AmitBobrov @Floydtm

**Comment by marcofrasson** [comment]
@UraraReika @kaskad88

**Comment by mymottow** [comment]
+1

**Comment by preyes24973** [comment]
Why is this thread closed. This issue is not fixed. Is there at least a snippet to exclude out-of-stock products?

**Comment by mymottow** [comment]
I agree ... I need this to work!

**Comment by tatenalan** [comment]
I am trying to solve the same issue. I found not solution for the moment

**Comment by jantowell** [comment]
Experienced the same issue with showing out of stock products. I found a fix that is built into the Ajax Search widget settings. Assuming you are using Elementor, edit the Ajax Search by selected "Exclude" then in the Terms field enter "Product visibility: outofstock" and this will fix the issue. Hope this helps someone.

**Comment by tatenalan** [comment]
> Experienced the same issue with showing out of stock products. I found a fix that is built into the Ajax Search widget settings. Assuming you are using Elementor, edit the Ajax Search by selected "Exclude" then in the Terms field enter "Product visibility: outofstock" and this will fix the issue. Hope this helps someone.

It works, thank you Jantowell for sharing the solution with the community!

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know.

**Comment by Irinel123** [comment]
Hello, I still can't find a solution to hide products that are out of stock. How can I do this if the bug has been fixed?

**Comment by tatenalan** [comment]
> > Experienced the same issue with showing out of stock products. I found a fix that is built into the Ajax Search widget settings. Assuming you are using Elementor, edit the Ajax Search by selected "Exclude" then in the Terms field enter "Product visibility: outofstock" and this will fix the issue. Hope this helps someone.
> 
> It works, thank you Jantowell for sharing the solution with the community!

@Irinel123 If you are using Crocoblock Ajax Search widget and Elementor you can try this, It worked for me
