### ISSUE TITLE
JelBlog: Smart Posts List - Show filter by Terms from Custom Category

### ISSUE THREAD

**Issue by mztmoraes** [Crocoblock/suggestions#846]
Hi all

By default, the widget could display only standard Posts categories https://prnt.sc/qrrd2b, not custom terms https://prnt.sc/qrrcyp. 

It would be great if the option to filter by custom category was possible.

I would also like to add the Filter by Terms option in the "Use Custom Query" option.

Best

**Comment by mztmoraes** [comment]
Hi! 

How the status of this issue Is it possible to implement? 

Best Regards

**Comment by Floydtm** [comment]
@mztmoraes, hi! Now our team is working on more priority tasks. Your request with pending status

**Comment by kaskad88** [comment]
Added for the next version
