### ISSUE TITLE
JetSmartFilter Pagination AJAX error

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#848]
**Describe the bug**
When I use an AJAX filter, when trying to load the next page, it gives this error described in the gif. I'm using OceanWP.

**Screenshots**
https://imgur.com/a/SQDzZC2

**Comment by marcofrasson** [comment]
Another thing, active filters only appear for prices. When using a taxonomy as a filter, it is not in the active filters.

https://prnt.sc/qruhsz
https://prnt.sc/qrui5f

**Comment by marcofrasson** [comment]
One more, when a filter does not appear, because I am using the indexer and not showing it, Elementor still renders this area with 20px, and if I have several filters missing, there is a large unnecessary blank space.

https://prnt.sc/qruk6x

**Comment by marcofrasson** [comment]
Another error, when I select a filter and the page reloads, all other counters change the number. See that before the filter was marked (29) and then it went to (386), meaningless. In addition to the other filters also changing the counter.

https://imgur.com/a/98S2hHj

**Comment by marcofrasson** [comment]
Hello, what's up? I understand that they are in high demand, but when bugs hinder the full functioning of the plugin, it ends up delaying all customers that use the plugin.

**Comment by Floydtm** [comment]
@marcofrasson, hi!
 **1** our filters only work with pagination from the filter plugin. use this widget http://prntscr.com/qv2qfm
**2** fixed. keep for updates.
**3** This is not a bug. The filter does not disappear from the markup. Thus, there are 20 pixels when it is not displayed. Indent between widgets 0 pixels http://prntscr.com/qv2v20
