### ISSUE TITLE
JetThemeCore/JetEngine?: Default page template/page template assignment

### ISSUE THREAD

**Issue by tf5bassist** [Crocoblock/suggestions#851]
It seems that there is no functionality for creating a Page template and then assigning it as a Default Page template.  

Example: 
- There are several static pages created, such as About, Contact, Resources, etc.  
- In most themes, all pages are automatically skinned the same with the ability to then customize each page separately if necessary.
- Without a default page template available, each page needs to be hand-authored in Elementor, causing massive duplication of efforts.

Requests:
- Add functionality to allow a Page template in Crocoblock > My Library > Pages to be set up as a default for all pages, similar to the logic available for single post templates
- Add functionality to assign a Page template to a certain page, similar to the logic available for single post templates
- Allow for writing the page in the WordPress editor (Classic or Gutenberg), save the Page, and then have the Page display with the default or specified Page template

Thanks!

**Comment by Floydtm** [comment]
@tf5bassist, hi! In one of your issues I replied that there is no such functionality for pages and sections. To create a template for the pages you need to create a new single template. As a source you need to select the pages http://prntscr.com/quh77w

**Comment by tf5bassist** [comment]
Interesting.  I was trying to find documentation about exactly that the other day to no avail.  I posted in the FB group, and again, haven't seen much in the way of information on this.

https://www.facebook.com/groups/CrocoblockCommunity/permalink/2975948205829914/

Is there anything weird or out of the ordinary that needs to be done for this to work?
