### ISSUE TITLE
Responsive Dynamic Repeater Fields

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#854]
Hello, please make it possible to change the list to the vertical position for the phone - https://prnt.sc/qspkr3
Thanks!

/*Оригинал*/
Здравствуйте, сделайте пожалуйста возможность изменять для телефона список на вертикальное положение - https://prnt.sc/qspkr3
Спасибо!

**Comment by kaskad88** [comment]
Added for the next version.
Thanks for your report!
