### ISSUE TITLE
JetSmartFilters - Sliding Panel for Filters 

### ISSUE THREAD

**Issue by secondsky** [Crocoblock/suggestions#855]
It would make sense to provide a panel widget in which the other search widgets can be put in.
I mean a "off canvas" slide in or reveal panel which can be shown or hidden by a click on a button.

**Comment by Floydtm** [comment]
@secondsky, hi! Use the [hamburger panel](https://crocoblock.com/widgets/hamburger-panel/) widget. So you can implement your request. For example http://prntscr.com/quen7c
