### ISSUE TITLE
JetSmartFilters - use more than one query field (custom field) for the filters

### ISSUE THREAD

**Issue by secondsky** [Crocoblock/suggestions#856]
Right now i can only filter based on one field (query var). 
This is valid for the search widget and for the checkbox widget.

For the search widget it would be great to specify multiple custom fields in which the search can happen.
The same goes for checkbox filter. The same value could be written in different fields, and all are interesting to filter for. Right now i would need to use 2 search widget with the same filter values.

**Comment by vloot65** [comment]
This would be a great feature to add!!

**Comment by MjHead** [comment]
Done
