### ISSUE TITLE
Add Mailpoet integration to Jetengine Form

### ISSUE THREAD

**Issue by knireis** [Crocoblock/suggestions#857]
You have some integrations in the Jetengine plugin, but the one i really miss is Mailpoet. Many of my clients use Mailpoet to send their newsletters and integration would be more than welcome.
Regards

**Comment by leegaughanbrown** [comment]
I've just purchased the lifetime JetEngine package, it's really great, but it could do with a few more integrations. I would love to see MailPoet added. I have 15 sites I'm converting to Elementor/JetEngine, they all use MailPoet.

**Comment by ghost** [comment]
Any updates on this?

**Comment by tomislavhofman-codecons** [comment]
Any updates on this?

**Comment by MjHead** [comment]
Added as separate Addon

**Comment by stapolin** [comment]
> Added as separate Addon

Can you point me in the direction of the Mailpoet addon? I can find one for JetFormBuilder, but not for JetEngine forms. 
I don't use the block editor, which is why I use Jetengine forms instead of JetFormBuilder. 

Cheers.
