### ISSUE TITLE
JetEngine: Dynamic Field block duplicates all content when used on a Page

### ISSUE THREAD

**Issue by tf5bassist** [Crocoblock/suggestions#858]
**Describe the bug**
If the Dynamic Field block to pull Post Content is used in a page that was created in the WordPress editor (ie, has already created content before Elementor), the whole page content including the sidebar content will be duplicated (sidebar formatting will be mostly missing).

Screenshot attached

**To Reproduce**
1. Create a page in WP editor (Classic editor in this instance, let's say it's the About page)
2. Attempt to make a default page template by copying majority of previously created single post template over to a default page template in Crocoblock > My Library > Pages
3. Realize that there's not a way of assigning a default page template
4. Edit About page in Elementor
5. Click gear icon at bottom left and switch page template from Default to Elementor Full Width
6. Insert previously created default page template from My Library in new page
7. Clean up prior text field and just use Dynamic Field block set to pull Post, same as it was in Single Page Template
8. Save and view page
9. Notice that the Content area now has the full page actually duplicated within that block (screenshot attached)

**Expected behavior**
Either the Dynamic Field block set to pull Post Content will either pull just the content area of the page content and not sidebars and duplicate titles, or it won't work at all.

![About](https://user-images.githubusercontent.com/2079716/73148713-95174100-4072-11ea-83db-a4ce41a94ae2.png)

**Comment by Floydtm** [comment]
@tf5bassist, hi! “Understand that there is no way to set the default page template” Understand that we don’t have such functionality. Also I can not reproduce the bug in my site. Please, submit a ticket https://support.crocoblock.com provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help you
