### ISSUE TITLE
Menu widget impovements

### ISSUE THREAD

**Issue by alriksson** [Crocoblock/suggestions#86]
Improve the menu widgets:
- To add icons on top layer and drop down layer
- Add more controls over the design, possibility to style position of close button.
- Function to control width
- Ability to control animation for hamburger canvas on mobile/tablet
- Possibility to control the to player of hamburger menu both on jetblock and mobile hamburger breakpoint hamburger menu. To not only have click to drop down but to click to navigate further down and go back to main menu function, Example of mobile menu: https://www.creditcards.com/

**Performance:**
- Remove duplication functions in jetmenu by not giving control options both backend and frontend elementor editor. Just override each others code. And bloat the performance and not built for performance or UI/UX in mind. Very confusing for the users to handle this widget. Wrote another ticket about replace instead of override code: https://github.com/CrocoBlock/suggestions/issues/73

**Comment by shinTM** [comment]
most of your comments have been added and fixed in version 2 0 0
