### ISSUE TITLE
"Select" inside the repeater

### ISSUE THREAD

**Issue by Olxa** [Crocoblock/suggestions#862]
Hello!
Could you add a select field inside the repeater field?
In this way, I would like to add for example social networks, the choice of a network from the drop-down list and the value (link) in the text box, well, or similar elements
Thanks!
plugin JetEngine

*Здравствуйте! 
Могли бы вы добавить поле "select" внутри поля "repeater"?
Я хотела бы таким образом добавлять к примеру социальные сети, выбор сети из выпадающего списка и значение (ссылка) в текстовом поле, ну или подобные элементы

p.s динамический вывод соцсетей тоже был бы в тему

Спасибо

**Comment by kaskad88** [comment]
I merged this issue with #1027, which is on the same subject so we could deal with it more efficiently.
