### ISSUE TITLE
pagination in widgets "Smart posts list" and "smart post tiles"

### ISSUE THREAD

**Issue by Olxa** [Crocoblock/suggestions#864]
Hello!
Could you make pagination work in widgets "Smart posts list" and "smart post tiles", otherwise it turns out beautiful, but not functional conclusion of posts
Thanks

**Comment by Floydtm** [comment]
@Olxa, hi! These widgets currently have Paging Control http://prntscr.com/qufywy http://prntscr.com/qufz8a
