### ISSUE TITLE
JetWooBuilder dont show prices in product variable

### ISSUE THREAD

**Issue by marcofrasson** [Crocoblock/suggestions#865]
**Describe the bug**
Hello, the promotional price for variable products is not shown when using the JetWooBuilder widget, see the price differences for simple and variable products.

I need the promotional price of the variation to be shown urgently, how do I do this?

http://prnt.sc/qulw87
http://prnt.sc/qulw9c
http://prnt.sc/qulwag

**Comment by marcofrasson** [comment]
Hello, what's up? I understand that they are in high demand, but when bugs hinder the full functioning of the plugin, it ends up delaying all customers that use the plugin.

**Comment by Floydtm** [comment]
@marcofrasson, hi! I close this request. Our technical support should resolve this issue with you.
