### ISSUE TITLE
Add version numbers to downloads

### ISSUE THREAD

**Issue by awakekat** [Crocoblock/suggestions#874]
**Before adding a new feature request, please, make sure you’ve checked:**
Nothing previously requested

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**
Please add version numbers to all your downloadable products. This will help when downloading a product previously to know which file is the newest, yes there is date stamp, but adding the version number to the filename is really helpful.

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.
Version numbers on all downloadable products

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 
All that exists now is just the product name, with the version number in the name one can see the previous downloads and safely delete them knowing they are the older version of the product.

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by Floydtm** [comment]
@awakekat, hi! Please describe your request in more detail
