### ISSUE TITLE
Jetengine: Adding a repeater option in the new front end forms 

### ISSUE THREAD

**Issue by asmarove** [Crocoblock/suggestions#875]
You can have a repeater for the custom post, I thought that all field types in CPT are the same in the front end forms, but unfortunately, there is no option to have a repeater for the front end forms.

**Comment by Salah-Asmar** [comment]
![Annotation 2020-01-30 111848](https://user-images.githubusercontent.com/32307693/73435997-5cb58280-4352-11ea-913d-1fd6c94e00cc.png)

**Comment by hannesalagoste** [comment]
This feature really helpful I hope it will be added.

**Comment by mielenzio** [comment]
+1 Very useful

**Comment by barrychapman** [comment]
+1

**Comment by barrychapman** [comment]
Is there a workaround?

**Comment by mielenzio** [comment]
I also would appreciate a work around! Thanks for any tips :)

**Comment by mrkteq** [comment]
+1 I too hope this can be added soon.

**Comment by mielenzio** [comment]
Is there already a possivble release date? Or is it already in the pipeline for the development?

**Comment by Dennisvb** [comment]
+1 This would be a great option. Hopefully it is added soon.

**Comment by nreljed** [comment]
#3514

**Comment by kaskad88** [comment]
This feature is already available since version 2.4.0
