### ISSUE TITLE
it could stop creating a search of several query variables *

### ISSUE THREAD

**Issue by Brunowilliang** [Crocoblock/suggestions#876]
you search by code, name or all together

**Comment by Floydtm** [comment]
@Brunowilliang, hi! Please describe your request in more detail

**Comment by Brunowilliang** [comment]
To be able to search with several variables, that would be wonderful

**Comment by Floydtm** [comment]
@Brunowilliang, I understand you, just tell me which plugin does it need?

**Comment by Brunowilliang** [comment]
JetSmartFilters and JetSearch

**Comment by Floydtm** [comment]
@Brunowilliang,  In the JetSearch widget, you can specify several custom fields, separated by commas http://prntscr.com/r78qou In JetSmartFilters, this does not work. Technically, it’s difficult to implement it yet.
