### ISSUE TITLE
Front End Form Date Field not passing through to Calendar

### ISSUE THREAD

**Issue by mdegeiso** [Crocoblock/suggestions#877]
**Describe the bug**
I created a calendar following [Crocoblock's Video](https://www.youtube.com/watch?v=sm3qbH82kMM) then tried to create a form to allow a front end user to enter events. The date fields as they pass from form to custom post type and back to calendar don't seem to match up. This appears to be the input from the form to the custom post type. I can create events on the back end and have then show on the calendar, but when created from the form, they don't work

**To Reproduce**

1. Create Calendar as per video
2. Create a form to add an event and ensure to map a date field on the form to the date field created for the custom post type.
3. Enter an event from the form and enter a date from the back end to compare date formated in custom post for event.

Attached are screen shots taken

**Expected behavior**
Event Entered via front end form, should show in calendar

**Screenshots**
See Attached

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10 (1903)
 - Browser [e.g. chrome, safari] Edge Chromium (EdgeDev), Chrome
 - Version [e.g. 22]  Chrome Version 79.0.3945.130

**Smartphone (please complete the following information):**
no testing done.

[Calendar Date Issues.docx](https://github.com/Crocoblock/suggestions/files/4134625/Calendar.Date.Issues.docx)

**Comment by kaskad88** [comment]
Hi @mdegeiso. 
Add this code https://gist.github.com/MjHead/66bf31e429f14f9224771f15ccd3b569 to the **functions.php** file your child theme. Only change a key name  from `_date_field` to your key name `event-date`

Thanks
