### ISSUE TITLE
"JetElements Subscribe widget", auto-complete option not available

### ISSUE THREAD

**Issue by iamranjithbabu** [Crocoblock/suggestions#879]
"JetElements Subscribe widget", auto-complete option not available

Please refer to the following URL,
https://prnt.sc/qvlbw5
https://prnt.sc/qvlcvi

**Comment by kaskad88** [comment]
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support at support https://crocoblock.com/help-center/ for guidance in resolving this issue.

Thanks
