### ISSUE TITLE
Clear database after delete custom fields and taxonomied

### ISSUE THREAD

**Issue by Floydtm** [Crocoblock/suggestions#89]
When deleting custom fields or taxonomies it seems that all the data is left in the database (it should be deleted).
Is this critical issue being actively worked on? When will this be addressed in an update? Kinda becoming more and more worried about my use of Crocoblock on a very important website when so many best practices are being ignored.

**Comment by JairoLopezCo** [comment]
What happened with this?

**Comment by apatsidis123** [comment]
If that is resolved, i still see the data in the database after deleting a meta field. And more specific, if i re-create the custom field with the same id, i can see the data also on the wordpress.
