### ISSUE TITLE
Alt tags for images

### ISSUE THREAD

**Issue by FHPhoto** [Crocoblock/suggestions#890]
For a good **SEO** site you must use **alt tags** in your images. That’s what i always do but your widget **_(Image Layout)_** don’t show them in the broncode so the SEO don't work correct. Could you solve this in an update because it is very important. Thx!! 

http://www.fransheidenis.nl/portfolio-cosplay/

**Comment by kaskad88** [comment]
Fix for the next version. 
Thanks for your report!

**Comment by FHPhoto** [comment]
And i see you have fix it. Thank you so much and so fast. **Great team.**
