### ISSUE TITLE
Listing Grid -dynamic background-image (featured image) for a column in the listing item.

### ISSUE THREAD

**Issue by goerans** [Crocoblock/suggestions#894]
Crocoblock support team said that I need to add the dynamic background-image on a section in the listing-item, but I need it to be set on a column. 

![Listing grid with alternative liting item2](https://user-images.githubusercontent.com/60660282/73822309-12bb1980-47f6-11ea-9119-0c874231260f.jpg)

**Comment by goerans** [comment]
![listing item background on column](https://user-images.githubusercontent.com/60660282/74024031-438b8200-49a1-11ea-82bd-85ce840d390d.jpg)
![listing grid missimg background image](https://user-images.githubusercontent.com/60660282/74024038-46867280-49a1-11ea-85c4-d7c525da9d73.jpg)

**Comment by kaskad88** [comment]
Fix for the next version.
Thanks for your report!
