### ISSUE TITLE
Jet Smart Filters: Range Filter should work with taxonomies and also would be able to take multiple values in query from meta field

### ISSUE THREAD

**Issue by iamirfanali** [Crocoblock/suggestions#896]
Hi there. Hope you are doing well.
I have a feature suggestion for Range filter in Jet Smart Filters. Right now Range filter wont work with taxonomies and also won't take multiple values from meta field in its query.
Lemme explain my problem that I am facing right now. I have a website where I am using jet smart filters. I have paper products in my store. I have categorized all my products on the basis of COLOR, USAGE(Application) and WEIGHT etc. by using custom taxonomies. So I have used Range filter for WEIGHTS. One can come and filter the products on the basis of its weight and place an order. one product is available in different weights so all those weights are added in it through custom taxonomy.
As Range filter won't work with taxonomy so I used the custom field to add those weights. Now the filter works ok when we have only single weight for that product but if we have more then one weight it would take 1st weight as query parameter and neglects the other ones.

So what I want it would be great if Range Filter should start working with taxonomies or it can start taking more then 1 values as it query parameter from meta field. According to my need and also for other usage I think this should be a must functionality in every filter that we have in Jet Smart Filters. It will helps a lot in different purposes.

**Comment by iamirfanali** [comment]
Can you please let me know that when this feature going to be added in the plugin or you can suggest me to fix this issue

**Comment by Floydtm** [comment]
@iamirfanali, hi! Sorry, you can only set the weight for the product in this format: https://prnt.sc/qydi26 If you need a different weight for the products, do this using the attributes http://prntscr.com/qye48o http://prntscr.com / qye4le and filter by taxonomy. Nevertheless, the range filter will not be able to fulfill your request and this depends not only on us, but also on the woocommerce plugin. Thank you for understanding

**Comment by Floydtm** [comment]
We will consider the possibility of a range filter for taxonomies. keep for updates

**Comment by iamirfanali** [comment]
this link is not working http://prntscr.com/qye48o

**Comment by iamirfanali** [comment]
@Floydtm is range filter works if I add variations for a single product.  I mean we can assign a weight to every variation in a product.

**Comment by Floydtm** [comment]
Understand that the range filter works on the variable http://prntscr.com/qyeuu4 http://prntscr.com/qyew3g If you create other product variants this field will be unchanged and it will not work for you

**Comment by iamirfanali** [comment]
Can you please help me with one thing. I wanted the slide handler (the one at the right side) that I have mentioned in the screenshot won't send any query request only the slider handler at the right side will send the query.
https://prnt.sc/qyxtch

It will be good if you mention someplace in the code where this functionality is working so I can alter it for now until the suggested functionality comes in your plugin.

**Comment by Paulscs** [comment]
Did this get implemented?
