### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by Gugutete** [Crocoblock/suggestions#899]
• Add a simple Trim option (the chance to cut some "X" number words) to the Title Widget not the excerpt, this is a very helpuf functionality for e-commerce and everyone need a grid that respect height dimension.
• When I create a listing product grid with jet, I can't insert a BUY button that is in ajax, the only one available is the one with number product shown and not in ajax.
• When I create a product grid with your native widgets it's not possible to show custom field inside those product grid. Being your a plugin to add custom data it's a bit strange.

**Comment by UraraReika** [comment]
1 and 2 already in our plugin functionality
3 - you can use one of our custom addons to fulfil your needs - https://tppr.me/txAZF here - https://crocoblock.com/freemium/tools/
