### ISSUE TITLE
Heading tags

### ISSUE THREAD

**Issue by blueberry11** [Crocoblock/suggestions#9]
add the option for customizing "Headings tags" in all widgets, it's important for SEO.

**Comment by kaskad88** [comment]
- [ ] JetBlocks
- [ ] JetBlog
- [ ] JetCompareWishlist
- [ ] JetElements
- [ ] JetEngine
- [ ] JetMenu
- [ ] JetPopup
- [ ] JetProductGallery
- [ ] JetReviews
- [ ] JetSearch
- [ ] JetSmartFilters
- [ ] JetTabs
- [ ] JetThemeCore
- [ ] JetTricks
- [ ] JetWooBuilder

**Comment by aksamitnaya** [comment]
SEO request: nofollow attribute for JetMenu
