### ISSUE TITLE
Time format in JetApointment

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#902]
Change the date format for the appointment times? 24 hour time is not common in north america, would be great if I can change to 12 hour.

Set the time output to be in a different format on the form. Ie. Instead of 14:00 it says 2pm.

**Comment by twiw** [comment]
PLEASE!!! Is there a workaround for this? My client will not like it in 24 hour time.

**Comment by Floydtm** [comment]
@twiw, added in plugin version 1.1
