### ISSUE TITLE
Integrating JetEngine meta-fields in any place via code (hook / shrortcode, etc...)

### ISSUE THREAD

**Issue by LeonaTech** [Crocoblock/suggestions#905]
Hi! I like the JetEngine plugin. It helps me develop many custom features without coding or integrating third-party plugins. Can you make in the future function what will make possible integrating JetEngine meta-fields from post-types, options, and other dynamic data via hooks or shortcode into another PHP/js code or places where I can't add a dynamic field with Elementor?

**Comment by Floydtm** [comment]
@LeonaTech, hi! We recently added a shortcode generator, now you can use it for your needs http://prntscr.com/r3ds28
