### ISSUE TITLE
JetEngine: Listings do not display dynamic background set in column in Listing Grid

### ISSUE THREAD

**Issue by poziomapl** [Crocoblock/suggestions#912]
**Describe the bug**
When I create a new Listings layout in the JetEngine options and try to set a dynamic background on the column as the background from a custom ACF image field or a featured image in the Elementor editor preview the image shows up. However, when I try to display the Listing grid element on any page, the image (background) of the column is not displayed.
 
**To Reproduce**
1. Create new Listing in JetEngine
2. Set on **column background as a dynamic image.** (dynamic image as background will shows up)
3. Create/edit any Page by chose Listing Grid and set created Listing as displayed. (listing is showed without this set background).

**Expected behavior**
The background set on the column as dynamic should display the correct image.

**Additional context**
The problem only occurs as a background set on the column. All other elements such as the image load dynamic content correctly.

**Comment by kaskad88** [comment]
I merged this issue with #894, which is on the same subject so we could deal with it more efficiently.
