### ISSUE TITLE
JetTabs for Elementor does not work with the browser (internet explorer 11)

### ISSUE THREAD

**Issue by SMGerena** [Crocoblock/suggestions#913]
**Describe the bug**
I am using JetTabs (plugin) as an accordion in a website, I did a contact accordion with this plugin. 
However, this accordion does not work with (internet explorer 11). Each tab of the accordion do not open. That is blocking the users of the website to have contact with us. 
This is happening only with explorer 11, this plugin woks perfectly with safari, chrome, edge, firefox.

**To Reproduce**
1. Go to https://www.qcotton.com.au/ in internet explorer 11.
2. Click on Contact (in the menu)
3. Click on any tab with a circle that has a (+) symbol and just try to open any of them.
4. See error, the tabs of that accordion do not open in internet explorer 11.

**Expected behavior**
I need the accordion let the users keep in touch with us anytime and for that the users have to be able to open any tab of that accordion and have access to the information that we have in the each tab.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: It does not work in any IOS or Windows.
 - Browser Internet Explorer 11.
 - Version 11.

**Smartphone (please complete the following information):**
 - It does apply for now.

**Additional context**
I hope you have already a solution for internet explorer 11 otherwise I have to find another solution and not use anymore this plugin that is amazing for others browsers except internet explorer 11.

Thanks very much

**Comment by Floydtm** [comment]
@SMGerena, Hi! Most features will display properly in IE but because IE is an older browser, it is incapable of supporting some of the modern web technologies that Elementor may utilize for some of its features. read this [documentation](https://docs.elementor.com/article/38-requirements)
