### ISSUE TITLE
Range filter improvements 

### ISSUE THREAD

**Issue by WildHund** [Crocoblock/suggestions#917]
Now, moving the toggle in Range filter it becomes difficult to establish the exact value. 

Besides, there is a need to add Min and Max input fields where the user can manually add values. So filtering will be much faster and more convenient. I set the Range filter on this page  https://onetime.store/pgr/napkins-paper-disposable/ 
You can see how convenient it is to use it in practice.

**Comment by MjHead** [comment]
Done
