### ISSUE TITLE
Possibility to upload a media via forms for not registered users

### ISSUE THREAD

**Issue by Phirstfilm** [Crocoblock/suggestions#918]
Hi

I suggested to make it possible to upload media (photos, etc.) for non registered users.

At the moment the problem is, that when you create a new jetengine form and add a media field it is only possible to upload a media for registerd users.
(from JetEngine Forms: _Note: _for security reasons this field will work only for logged-in users!__)

For a front end submission this is not ideal and make the form useless for non registered users.

Can you please change that.

Thanks in advance!

Best regards,
David

**Comment by Floydtm** [comment]
@Phirstfilm, hi! Unfortunately, at the moment, for security, this field  works only for logged in users.
