### ISSUE TITLE
Use hierarchical filters in any order

### ISSUE THREAD

**Issue by me2i** [Crocoblock/suggestions#920]
**Please, describe the feature request, making it clear to understand.**

Now, if you use the hierarchical filters, you must choose your filter-options in a specific order. So, for instance, if you have a webshop with clothes and you can filter by category, size and color, then I must first select a category, before I can select a size or color. But I need to be able to start filtering with any field. Sometimes I want to see all clothes of a certain size and other times I want to see everything of one color. This is currently not possible, because I can only choose a size when I also have chosen a category.

**Add an example of where this feature is already implemented.**

I don't have a specific example from another website, but i think my explanation above says it all. The hierarchical filters feature is great already! It's just that I can't be bound by having to choose the filters in a certain order.

**Comment by Floydtm** [comment]
@me2i, hi! The essence of features:
You can combine several filters of the same type in a hierarchy. The hierarchy will be available only after selecting the previous one. You can build the filter in any order, it will work from the first elemen. What you offer can be implemented with ordinary filters without using the option "Is hierarchical"

**Comment by me2i** [comment]
@Floydtm thanks for your reply. Indeed, with the ordinary filters I can filter in any order I like, but then I don't have the functionality of the hierarchical filter. So to summarise it: I need the functionality of the hierarchical filters with the flexibility to choose the filters in any order. That is the feature request I'd like to make. So would you please open this issue again? Thanks!

**Comment by Floydtm** [comment]
@me2i Understand us. During development, we relied on specific cases of using filters and they only work like this "The hierarchy will be available only after selecting the previous one". Use the [indexer](https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-set-indexer-option-for-filters/) setting. There you can hide items if they are empty

**Comment by me2i** [comment]
@Floydtm thanks for your suggestion! That was exactly what I was looking for!
