### ISSUE TITLE
Use JetSmartFilters to filter Elementor Portfolios.

### ISSUE THREAD

**Issue by bechamp1** [Crocoblock/suggestions#921]
Hello!

Please add the ability to filter Elementor Portfolios to your JetSmartFilters. I can filter Posts of various types and Products, and I can index Portfolios, but I can't filter Portfolios. Unfortunately, this makes JetSmartFilters useless to me, even though I love the way it integrates with Elementor and its ease of use. 

If you elect not to introduce this functionality, would you please explicitly state in your documentation and instructions on how to use the filters with Elementor that filtering Portfolios is not possible? I ended up having to contact Crocoblock directly to confirm that I couldn't do it. 

It's irritating that both you and Elementor use the ease of integration of your two systems as a selling point and then fall down on such an obvious (to me, anyway) matter. 

Thank you for your attention.

**Comment by Floydtm** [comment]
@bechamp1, hi! We are working on it. keep for updates
