### ISSUE TITLE
Add support of using Spacer widget for Jet Engine Listing grid

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [Crocoblock/suggestions#922]
You might wonder - Why is the Spacer widget?
But everything is very simple - with the help of this widget it is very convenient to set image areas with a exact defined height. To do this, just specify the height of the Spacer and set a dynamically linked image (for example, a featured image) as the background.
This is almost the only way to create beautiful post cards with the identical image height. But in some reason, Spacer widget doesn't work properly with the Jet Engine listing! I beg you - correct this defect!

**Comment by kaskad88** [comment]
I merged this issue with #395, which is on the same subject so we could deal with it more efficiently.
