### ISSUE TITLE
Conditional logic field Jet Engine Form

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#923]
Hello, I ask you to consider the possibility of introducing field mapping logic depending on previously selected values.

For example, in one of the Elementor add-ons this is https://pafe.piotnet.com/docs/form-builder/ and I used it, but now I need a form with calculation of values ​​from meta fields, and as far as I know only a form can do this from Jet Engine, but the lack of field display logic is a big minus.

/*Оригинал*/
Здравствуйте, прошу рассмотреть возможность внедрения логики отображения полей в зависимости от ранее выбранных значений.

Например в одном из аддонов к Elementor это есть https://pafe.piotnet.com/docs/form-builder/ и я использовал это, но теперь мне нужна форма с калькуляцией значений из мета полей, а такое насколько мне известно умеет только форма от Jet Engine, но вот отсутствие логики показа полей большой минус.

**Comment by MjHead** [comment]
Added in JetEngine 2.4.0
