### ISSUE TITLE
Jet Engine Custom Callback for Page Order in Admin Columns

### ISSUE THREAD

**Issue by blaquemasque** [Crocoblock/suggestions#924]
Hi

It would be a huge help if there was an easier way to add the 'menu_order' post attribute to the Admin Columns of a custom post type created in Jet Engine. Even if its just an included custom callback option, so it can be made sortable as well.

<img width="898" alt="Screen Shot 2020-02-17 at 5 01 32 pm" src="https://user-images.githubusercontent.com/2913580/74638611-2b88df00-51a7-11ea-8fa9-2df908083075.png">

<img width="1877" alt="Screen Shot 2020-02-17 at 4 54 26 pm" src="https://user-images.githubusercontent.com/2913580/74638524-0005f480-51a7-11ea-9e16-132d72e3f5f1.png">

**Comment by ocbroadband** [comment]
Yes, please advise on this!   And any/all of the other 'default' WP fields that we can pull in as a custom callback.
