### ISSUE TITLE
Fetch media URL from media custom field 

### ISSUE THREAD

**Issue by pierrehansen** [Crocoblock/suggestions#927]
I would like to have the ability to create a listing of pdf's with direct links to each file (for example http://website.de/wp-content/uploads/2020/02/file.pdf).

Until now it isn't possible (asked in chat) to fetch the URL of the media file itself. Workaround would be an extra custom field for URL (manually added) which is not very handy or custom programming. Would be a definite "buy instantly" criterion for me.

Thanks for (hopefully) considering in a future update.

Best regards
P.Hansen

**Comment by MjHead** [comment]
Hi! You can  do this by using regular media field and registering custom callback for Dynamic Field widget. Here is a code for this callback - https://gist.github.com/MjHead/525db5dd35d3076a74c79cae6ff89086. You need to add this into your theme or child theme functions.php file. Than you can output this link in the listing grid by Dynamic Field widget - http://prntscr.com/r56h4p

**Comment by pierrehansen** [comment]
Hello MjHead, I commented the issue above (link) and hoped that I would get an answer to my specific problem. Could you maybe have a look? Thank you very much!

https://gist.github.com/MjHead/525db5dd35d3076a74c79cae6ff89086
