### ISSUE TITLE
Headline widget. Dynamics in Listing templates  

### ISSUE THREAD

**Issue by aksamitnaya** [Crocoblock/suggestions#928]
In Headline widget Text image dynamic settings work well in Listing template and on Single template 
https://prnt.sc/r1yood, https://prnt.sc/r2r81r
but doesn't show correctly in Listing Grid: https://prnt.sc/r1yoyt

**Comment by kaskad88** [comment]
Added for JetEngine v2.2.3.Thanks for your report!
