### ISSUE TITLE
Create a new plugin dedicated to Frontend Publishing

### ISSUE THREAD

**Issue by davideassis** [Crocoblock/suggestions#93]
With **JetEngine** we can create and manage Custom Post Types, Custom Taxonomies and Custom Fields and it work perfectly with Elementor, allowing us to work on trully advanced projects.

The only missing piece is the ability to Create and Edit said custom content easily, so I suggest the creation of a new plugin dedicated to **Frontend Publishing**.

Such plugin could offer features like:

- Custom Forms to Post new content and/or Edit existing content.
- Integration with WordPress and WooCommerce Post Types, Taxonomies and Metaboxes.
- Integration with JetEngine Custom Post Types, Custom Taxonomies and Custom Metaboxes.
- The use of Elementor to easily display, position and customize such forms.
- Rules and Conditions to limit the access to Forms and Fields based on status or role.
- Additional Widget to display all the posts generated by the user in a private archive.
- Additional Widget to display all the controls to Edit and/or Delete the current post.

**And why we need a plugin like this?**

The solutions already available to Post and Edit content depend on additional plugins in order to work as expected. Some even make the use of JetEngine completely unnecessary, since they already offer similar features — but they aren't fully integrated with Elementor or other Crocoblock plugins.

A new solution, fully integrated with Elementor and JetEngine, not only increase even more the value of the Crocoblock Suite but keep things at the minimum necessary and easy to use, both for the developer and for the clients.

Everything will be fully functional, fully compatible and way less expensive for everybody.

**How it can be expanded in the future?**

This plugin could also offer support to **Create and Edit Users**, with custom forms to Registration and Login and custom fields synced with the User Meta. It could lead JetEngine to be updated as well, with support for extend existent Post Types and Taxonomies (similar to Pods).

This would allow us to create a basic "restricted to members" site (what's enough in most cases) and we can do it with Elementor and Crocoblock only, without unnecessary extra plugins or manual coding.

**Comment by altechzilla** [comment]
I think at that point they'd have to focus on an all-in forms plugin, such as Gravity Forms, WPForms or Forminator - all of these allow you to hook in a post submission feed. WordPress is missing the ability to manage things on the front-end efficiently.

**Comment by dantetesta** [comment]
This function is very useful .... the Piotnet PAFE plugin have this feature and much more ....

I Need make insertions into taxonomy through front forms.

Please add this feature
