### ISSUE TITLE
Bug in Animated Text

### ISSUE THREAD

**Issue by Akavantseva** [Crocoblock/suggestions#930]
Issue:
After loading the page, if I go down, after passing the animated text generated by the widget, the page starts to move in a strange way and to go up and down on its own. If I keep going down then everything seems to be normal, but then every time I update or arrive on the page the same problem reappears.
I have run several tests and the problem seems to occur only if I use google chrome, both from windows and from mac.
If, for example, I surf with Safari, the page is perfect.
Furthermore, the bug seems to disappear if I only alternate 2 words or phrases in the animated text, from the third onwards the bug appears.
In addition, the only animation that works is the "typing" animation, if I choose other animation modes the widget will delete all the spaces between the words of the animated text.

[Screen 2020-02-09 at 16.10.zip](https://github.com/Crocoblock/suggestions/files/4218670/Screen.2020-02-09.at.16.10.zip)

**Comment by Floydtm** [comment]
[Screen 2020-02-09 at 16.10.zip](https://github.com/Crocoblock/suggestions/files/4218668/Screen.2020-02-09.at.16.10.zip)

**Comment by kaskad88** [comment]
We tried to reproduce your issue based on the information you provided, but without success.
