### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by toby12222** [Crocoblock/suggestions#937]
Jetwoobuilder: could you please add total_sales of product, custom badges, total stock, brand, show only 1 category, brand image in Loop page and single page.

thanks

**Comment by UraraReika** [comment]
Hello and sorry for delay reply.

You can do everything of this with the help of default widgets and dynamic tags functionality. But in this case you although need to use JetEngine plugin.

Thank you for understanding !
