### ISSUE TITLE
Simple "Like" Button

### ISSUE THREAD

**Issue by keremnymn** [Crocoblock/suggestions#939]
Hello!
I'd like a simple "like posts" button with Crocoblock products. For instance, people like the posts, so I can show people most liked posts etc.

I'd really like this and I guess it's not that difficult to implement (I think :) ). It's also very elegant. It'd contribute to Crocoblock products in my opinion.

**Comment by mcj777** [comment]
I support! Need similar functionality https://liker.merkulov.design/ Simple, convenient and understandable.

-------

Поддерживаю! Нужен подобный функционал https://liker.merkulov.design/ Простой, удобный и понятный.

**Comment by MjHead** [comment]
Can be done with Data Stores module
