### ISSUE TITLE
JetEngine Listing Grid to displayed products marked as "Featured"

### ISSUE THREAD

**Issue by deanloh** [Crocoblock/suggestions#941]
Woocommerce lets us mark products as "Featured". It would be nice if Listing Grid recognizes this and lets us set the widget to display featured products only.

**Comment by trofimartya** [comment]
+1

**Comment by robleigh1991** [comment]
bit late but you could do it this way with a query in the query builder

![image](https://user-images.githubusercontent.com/27848999/160881777-bb4a2e06-b8ac-4338-88d9-2ea735cd273a.png)

**Comment by inigo104** [comment]
A bit late  too, you could do it this way in posts query

![Captura de pantalla 2022-06-01 212655](https://user-images.githubusercontent.com/2894924/171486047-5d552d0d-815d-4ba6-a9e5-46b44a92b276.jpg)

**Comment by ashkankhalili** [comment]
> A bit late too, you could do it this way in posts query
> 
> ![Captura de pantalla 2022-06-01 212655](https://user-images.githubusercontent.com/2894924/171486047-5d552d0d-815d-4ba6-a9e5-46b44a92b276.jpg)

what if we want to show just the product which are on sale?! i didnt find any setting !!!! 
why is it so hard in jetengine!!?!

**Comment by robleigh1991** [comment]
Use a meta query and check if _sale_price < _regular_price

**Comment by ashkankhalili** [comment]
> Use a meta query and check if _sale_price < _regular_price

Good one :) Thanks !

**Comment by ashkankhalili** [comment]
> Use a meta query and check if _sale_price < _regular_price

can you help me to find the percentage of the discount to show in dynamic field ?! for example regular price is 10$ and sale price is 5$ then in a dynamic field is shows 50% Off ?! thanks in advance !

**Comment by ashkankhalili** [comment]
> Use a meta query and check if _sale_price < _regular_price

hey there , 
i have used the query as you mentioned, there is only one problem, it does not show the variable products. when i have a product with variations , it does not show those products as onsale products . 
do you have any solution for this case?!

**Comment by chitiore** [comment]
@ashkankhalili  did you have any luck finding a solution? I am having the same need. Greetings.

**Comment by ashkankhalili** [comment]
> @ashkankhalili did you have any luck finding a solution? I am having the same need. Greetings.

hi there :) 
if you are asking for "showing the product with variation", 
no body provide me with anything, but i used my own way to solve the problem, 
first i have created a meta box for products as other settings,
then i created a meta filed with below settings : 
name : product on sale 
name/id : _product_on_sale
object type : field
field type : select
then on field option i created two options as YES and NO,
when i create or edit any product on my website, there is a option to set for the product as "is it on sale" which i can set it to yes or no.
then to show products which are on sale, i used grid listings and in the setting, i have set post query to meta query, and set the key as "_product_on_sale", operator ="regex"  and the value= yes.

this is actually worked for me with no issues, all i had to do is to edit the products  which are on sale and set the meta filed to yes.
![1](https://github.com/Crocoblock/suggestions/assets/14147491/dace6f87-f24c-4651-9b6e-f25c75c88793)
![2](https://github.com/Crocoblock/suggestions/assets/14147491/647a38ab-b232-4295-aafe-2281f21a12b3)
![3](https://github.com/Crocoblock/suggestions/assets/14147491/7d4aee7d-88b1-484f-83c9-8a62bee50377)

if you need more details, please let me know :)
