### ISSUE TITLE
Catalog Mode please!

### ISSUE THREAD

**Issue by toby12222** [Crocoblock/suggestions#944]
jetwoobuilder: Please add YITH WooCommerce Catalog Mode button pls pls!!
https://yithemes.com/themes/plugins/yith-woocommerce-catalog-mode/

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.
