### ISSUE TITLE
Implement dynamic data QR code for contacts (vCard)

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [Crocoblock/suggestions#945]
Hi!
It will be nice feature for generating QR code for vCard contacts data.

**Comment by Floydtm** [comment]
@Morgunov-Vitaly, hi! In the jetengine plugin, this has been [implemented](https://crocoblock.com/knowledge-base/articles/jetengine-how-to-enable-extra-modules-to-work-with-a-dynamic-calendar-qr-codes-and-galleries/) since version 1.2.0

**Comment by Morgunov-Vitaly** [comment]
> @Morgunov-Vitaly, hi! In the jetengine plugin, this has been [implemented](https://crocoblock.com/knowledge-base/articles/jetengine-how-to-enable-extra-modules-to-work-with-a-dynamic-calendar-qr-codes-and-galleries/) since version 1.2.0

Hi! You mean Dynamic Field QR code callback feature, but I talk about separate QR code widget with ability to make QR code with consists of several dynamic fields and for different formats includes vCard. I think it need a settings block with Add field feature when you can add several dynamic metafields and bindthem with standart vCard fields like a name, phone, address, job etc.
See the picture bellow:
![Add vCard QR code feature](https://user-images.githubusercontent.com/19765202/75434142-2cb5cb00-5962-11ea-8935-be2fc494ed6c.jpg)

**Comment by Morgunov-Vitaly** [comment]
Also - it very strange, that at the moment there is no ability to specify current post URL in QR code!
