### ISSUE TITLE
Jet Engine Listing Grid Vertical Slider

### ISSUE THREAD

**Issue by johnnyboland** [Crocoblock/suggestions#947]
The slider for the listing grid only slides horizontally with a multi-column single row layout.  Although this covers the majority of slider use cases perfectly fine, it'd be nice to have the option to cycle through slider vertically in a multi-row single column layout.  

Please see [Happy Addons Logo Carousel Design 8](https://demo.happyaddons.com/elementor-logo-carousel%E2%80%8B-widget-demo/)

**Comment by Crocoblock** [comment]
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/418)
