### ISSUE TITLE
JetWooCommerce Related/Best Sellers

### ISSUE THREAD

**Issue by maikldan** [Crocoblock/suggestions#951]
Hi devs, it is possible to add customization to widgets Related Products and Best Sellers?
Or to adding this Query fields to products grid widget.

**Comment by UraraReika** [comment]
Hello @maikldan!

If we are talking about Best Sellers option than it`s already exist. https://prnt.sc/vfyl3q here it is. If - about Related products than you can use Products Grid/List widgets in single product template by JetWooBuilder in this template some additional options appear https://prnt.sc/vfylzk.
