### ISSUE TITLE
Custom Media Query Breakpoints​

### ISSUE THREAD

**Issue by mcj777** [Crocoblock/suggestions#957]
Разработчики Элементора упорно не хотят расширять функционал по работе с медиа-запросами, чтобы помимо десктопа, планшета и смартфона (только портретные режимы) можно было настраивать шаблоны и под другие типы экранов.

Обсуждение можно посмотреть здесь: https://github.com/elementor/elementor/issues/2043

В связи с этим прошу рассмотреть возможность добавления пользовательских медиа-запросов к виджетам Jet. К примеру, такие запросы очень нужны для работы с виджетом Listing Grid.

На практике мне надо показывать разное кол-во листингов в строке:

- на десктопе - 4
- на ноутбуке - 3
- планшете - 2
- смартфоне -1

Возможно, данный функционал получится внедрить в сами виджеты, через Jet Advanced или каким-либо другим способом.

У PAFE есть небольшое решение на эту тему, но на практике оно малополезное: https://pafe.piotnet.com/docs/custom-media-query-breakpoints%e2%80%8b/

Есть пример внедрения глобальных изменений в коде Элементора: https://kodestat.gitbook.io/elementor/

**Comment by Floydtm** [comment]
@mcj777, please, note, that the feature requests can be accepted and processed only if they’re written in English. I understand you, but other participants may have problems with the translation. Regarding the request itself, our team will not do this. Once this [request](https://github.com/elementor/elementor/issues/2043) is resolved it will be available in Jet plugins
