### ISSUE TITLE
JetEngine: "Load More" Bugs

### ISSUE THREAD

**Issue by vollgasrock** [Crocoblock/suggestions#958]
1. The "Load More" function in listing grids does not work if an intro animation is activated in the listing grid.

2. I have a section with two columns. In the left column is a sticky element with the option "stay in the column".
On the right side a listing grid with the Load More function. If you then scroll to the end of the section and click on "Load More", you scroll directly back to the "Load More" button.
If you scroll down the section and click on "Load More" before the section ends, it works as it should.

Difficult to explain. You can test it [here](http://www.vollgasrock.alfahosting.org/loadmore/)

**Comment by Floydtm** [comment]
@vollgasrock, hi! We looked at your example and found that you are not using our sticky column solution. We also checked this case again using the jettricks plugin and everything works fine. I can suggest you use jettricks - [Sticky Column](https://crocoblock.com/widgets/sticky-column/)
