### ISSUE TITLE
Add ability to display one post for several dates at once in Listing Calendar (JetEngine)

### ISSUE THREAD

**Issue by Crocoblock** [Crocoblock/suggestions#96]
In Listing Calendar widget we have an ability to display one post only for one date.
But if it's an Event post type, some events might be held for several days, and in order to avoid duplicating the posts (cloning them, which is not convenient when there are multiple posts) - we need an ability to display one post for several days (it should appear in several cells in Dynamic calendar).

**Comment by yescreative** [comment]
+1

**Comment by KingGrizzly** [comment]
+1 This is true for many types of events such as workshops, conferences, and camps. Thanks!

**Comment by KingGrizzly** [comment]
Excellent, thank you!

**Comment by petercostellocreative** [comment]
Thankyou!
