### ISSUE TITLE
(jet engine) Enter the meta field "number" for fields that only require numbers

### ISSUE THREAD

**Issue by antonio86itna** [Crocoblock/suggestions#963]
This is something I didn't find in jet engine and it seemed strange to me.

I wanted to insert a "number" meta field to allow the user with a role other than mine to insert car ads and in some places he had to put only numbers and not letters.

I like to be precise with the fields and allow to insert only the type of text that I decide.

It would also be useful to allow me to customize the number and text fields in order to decide whether it is possible or not to insert symbols in addition to the text.

Also lastly it would be useful to be able to set an automatic dropdown field of fiano to a custom field.

For example, if I create a "car kilometers" field (only with numbers) and a dropdown field must be next to it with the choice of inserting the symbol "Mph" or "Km" according to preference. And then on the frontend automatically show the field in full, the user only has to enter the number, for example 100,000 and on the frontend it will automatically be written 100,000km if that has been selected.

Finally to conclude it would also be nice if it is possible to limit the formatting, punctuation, that is I have to decide in every field if punctuation is possible or not and in addition I could insert punctuation, or the division of decimals automatically while the user can only enter numbers.

The latter will make a separate request because they must be well understood.

If I have time I will make some demonstration videos for everything I am requesting.

I believe that everything I write to you will be very useful because I am really very prepared on the subject, especially regarding online ads and therefore their formatting.

**Comment by kaskad88** [comment]
I merged this issue with #1009, which is on the same subject so we could deal with it more efficiently.
