### ISSUE TITLE
JetSmartFilters: Where to add query ID in Woo Product Archive widget 

### ISSUE THREAD

**Issue by sigersmit** [Crocoblock/suggestions#965]
For the sorting widget it is neccessary to add the Query-id to the widget (jet-smart-filters) but in the Elementor Pro Archive Products there is no Query-id field... Al least, I can't find it.

**Comment by bimitya** [comment]
Did you find the answer for this?

**Comment by Floydtm** [comment]
This option is not needed for Elementor Pro Archive Products
