### ISSUE TITLE
Carousel in Product Grid

### ISSUE THREAD

**Issue by woofworkshop** [Crocoblock/suggestions#967]
In a product grid (carousel mode), you can show the user that these are not static pictures, but they can be scrolled, in 2 ways: navigation arrows and pangination. However, in the mobile version, these methods are not convenient! I would like to propose a more modern solution. Its essence lies in the fact that, for example, 2 whole miniatures of goods and part of the third are displayed on the screen. And the user intuitively understands that you can scroll with your finger. It seems to me that this is a brilliant and simple solution, thanks to which the already limited space of the smartphone screen is saved. Here's how they implemented it on etsy.com and lamoda.ru

![IMG_5120](https://user-images.githubusercontent.com/58448161/75610537-21f66400-5b23-11ea-8030-96945384c98c.PNG)

![IMG_4972](https://user-images.githubusercontent.com/58448161/75610533-1c008300-5b23-11ea-9447-78718b7a979e.PNG)

**Comment by marcofrasson** [comment]
Any update for this? @UraraReika

**Comment by marcofrasson** [comment]
Hello, where version its change?

**Comment by UraraReika** [comment]
@marcofrasson Center Mode was added in version 1.6.2.
