### ISSUE TITLE
Provide a guide how to add custom macros

### ISSUE THREAD

**Issue by codemotion** [Crocoblock/suggestions#969]
**Please, describe the feature request, making it clear to understand.**

I've an existing project with strong ACF relations between posts. I cannot move all of them to JetEngine relations system and ACF UI for relations looks more handy for me.

I need to make a custom macros to pool the data from ACF field.

What do I need to do?

**Add an example of where this feature is already implemented. **

I've researched that list of macros is located here:
**/wp-content/plugins/jet-engine/includes/components/listings/macros.php**

```php
public function get_all() {
                        return apply_filters( 'jet-engine/listings/macros-list', array(
                                'title'                    => array( $this, 'get_title' ),
                                'field_value'              => array( $this, 'get_field_value' ),
                                'current_id'               => array( $this, 'get_current_id' ),
                                'current_tags'             => array( $this, 'get_current_tags' ),
                                'current_terms'            => array( $this, 'get_current_terms' ),
                                'current_categories'       => array( $this, 'get_current_categories' ),
                                'current_meta'             => array( $this, 'get_current_meta' ),
                                'current_meta_string'      => array( $this, 'get_current_meta_string' ),
                                'related_parents_from'     => array( $this, 'get_related_parents' ),
                                'related_children_from'    => array( $this, 'get_related_children' ),
                                'related_children_between' => array( $this, 'get_related_children_between' ),
                                'queried_term'             => array( $this, 'get_queried_term' ),
                                'author_id'                => array( $this, 'get_post_author_id' ),
                        ) );
                }
```
As I can understand in case I need to expand macros list I have to use **add_filter** method for  'jet-engine/listings/macros-list' filter.

For example, in **functions.php** of current theme I can add:
```php
add_filter( 'jet-engine/listings/macros-list',function($macros){

        $macros['acf_related'] = 'get_acf_related_posts';
        return $macros;
});

function get_acf_related_posts($field_name){
        return implode(',',array_map(get_field($field_name),function($post){
                 return $post->ID;
}))
}
```

But I cannot debug it due to the admin-ajax.php requests.

I ask for crocoblocks developers to make a guide how to extend macros list and how to write your own.

**Comment by MjHead** [comment]
Hi @codemotion Here is a different examples of custom macros:
- https://gist.github.com/MjHead/c9a77e0101746920055c0a8071445529
- https://gist.github.com/MjHead/37c0c8c317d8fd76eb60b30935e0c494
- https://gist.github.com/MjHead/a68c030b1210bb72325860d30e63a600

As you correctly mentioned, you need to register custom macros function on `jet-engine/listings/macros-list`. Macros list contain array of 'macros name' => 'macros callback' values. Callback has one required parameter - $field_value, this parameter depends from field where this macros used. For example for meta_query parameters $field_value will be queried meta key name. But also you can pass any custom parameter into macros by separating it from macros name with "|" sign. For example %my_macros|my-parameter%. In this case your custom parameter will be passed as second argument into callback function. Callback function totally depends on your needs, so we can't provide any detailed tutorial about writing callback function.
