### ISSUE TITLE
Smart Posts List, featured image breaks accessibility

### ISSUE THREAD

**Issue by greggh** [Crocoblock/suggestions#970]
Support asked me to come over here and make this a feature request. I am still not sure that's the right move, as this is an accessibility bug.

The Smart Posts List widget adds a title and alt text to the featured image, it sets them both to the same text (post title). This is against accessibility rules. If it has the alt set then it doesn't need the title. This means a website can't pass any web accessibility tests if it uses that widget.

Can you please only use the alt attribute on the featured image for the Smart Posts List widget?

I use https://wave.webaim.org/ to test the sites I develop for accessibility. Here it is showing the error:

<img width="449" alt="Screen Shot 2020-03-01 at 9 01 25 AM" src="https://user-images.githubusercontent.com/90286/75627090-4aba4000-5b9b-11ea-881f-963e13bae5d9.png">

**Comment by kaskad88** [comment]
Fix for the next version.
Thanks for your report!
