### ISSUE TITLE
Categories page

### ISSUE THREAD

**Issue by guyzamir** [Crocoblock/suggestions#972]
Can you make a category page where the Categories can be listed and show the subcategories that reside under them?

Example:

Category name
Sub1 (10), Sub2 (5), Sub3 (5)
------------------------------------------------------
Category name
Sub1 (10), Sub2 (5), Sub3 (5)
------------------------------------------------------
Category name
Sub1 (10), Sub2 (5), Sub3 (5)

**Comment by UraraReika** [comment]
Hello @guyzamir! You can achieve this with a help of JetEngine and JetThemeCore or Elementor Pro.
