### ISSUE TITLE
Font Awesome 5 in Jet Tabs

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#978]
Hello, I look forward to implementing FA 5 in Jet Tabs -https: //prnt.sc/rbbxre
Please consider this possibility.

Здравствуйте, очень жду внедрения FA 5 в Jet Tabs -https://prnt.sc/rbbxre
Рассмотрите пожалуйста такую возможность.

**Comment by kaskad88** [comment]
I merged this issue with #785, which is on the same subject so we could deal with it more efficiently.
