### ISSUE TITLE
Item added to cart pop up

### ISSUE THREAD

**Issue by Sayeed1440** [Crocoblock/suggestions#980]
I don't whether it's the right feature to ask for or not. have a look at it, if you don't like it remove it.

If I am not using any added to cart pop up plugin then woo-commerce default added to cart notification doesn't catch the user's attention.

In order to catch the user's attention, we need to create an added to cart pop up & encourage the user to checkout.

I saw you guys doing product quick view using jet pop up. Can you do the same for added to cart notification?

If you do, it would be a great feature & help us in reducing one more plugin in the backend.

**Comment by Floydtm** [comment]
@Sayeed1440, hi! https://crocoblock.com/knowledge-base/articles/jetwoobuilder-how-to-display-a-products-cart-in-a-popup-based-on-jetpopup/

**Comment by xC4M** [comment]
@Floydtm  Is there any way that we can add the product's image, title, and so on in the Cart Popup and show them in there?
Something like this: http://i.prntscr.com/56Yqd45JSS299-2i1ND3rA.png

**Comment by WP-Webdeveloper** [comment]
> [@Floydtm](https://github.com/Floydtm) Is there any way that we can add the product's image, title, and so on in the Cart Popup and show them in there? Something like this: http://i.prntscr.com/56Yqd45JSS299-2i1ND3rA.png

4 years later, but I want to do the same, show the added to cart product with cross sells in the added to cart pop-up. Did you manage to do this?
