### ISSUE TITLE
Portfolio Widget Dynamic Repeater fields set to default

### ISSUE THREAD

**Issue by Sayeed1440** [Crocoblock/suggestions#981]
I have used your Portfolio widget to showcase my Portfolio. The widget has got two options for the image. We can either link it to another page or we can use a lightbox.

However, when we are dynamically adding the content to the widget using repeater fields, the link option is set to default i.e. URL no option to choose the lightbox.

You can see the demo of this issue here:
https://wilsonwings.com/portfolio/the-research-gate/

I opened a ticket to resolve this but they asked me to report it on GitHub.

**Comment by kaskad88** [comment]
Please update the JetElements Dynamic Data Addon plugin from https://github.com/ZemezLab/jet-elements-dynamic-data
