### ISSUE TITLE
Dynamic Link in widget Image Accordion

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#982]
Hello, note that dynamic links are still not supported in the Image Accordion widget. Please implement this functionality - https://prnt.sc/rbv2rm

Здравствуйте, обратите внимание что в виджете Image Accordion всё еще не поддерживаются динамические ссылки. Просьба внедрить этот функционал - https://prnt.sc/rbv2rm

**Comment by kaskad88** [comment]
Added to the next version. Thanks for your report.
