### ISSUE TITLE
Widget Image Accordion mobile responsive

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#984]
Hello, this widget is not suitable for use on mobile devices due to the inability to select here - https://prnt.sc/rbyhtn vertical or horizontal position depending on the device.

Please introduce this feature in the future.

Здравствуйте, данный виджет не пригоден для использования на мобильных устройствах из-за отсутствия возможности выбрать тут - https://prnt.sc/rbyhtn вертикальное или горизонтальное положение в зависимости от устройства.

Просьба внедрить такую возможность в дальнейшем.

**Comment by kaskad88** [comment]
Added for the next version.
