### ISSUE TITLE
Jet Smart Filters | Add unique ID to the Jet listing

### ISSUE THREAD

**Issue by Gugutete** [Crocoblock/suggestions#994]
Hi there and thanks for your attention. I love to use Jet listing everywhere, menu included. Anyway,
• I set up a listing of custom post A in my top menu
• I set up a listing of custom post B in a page X
• I create a smart filter for the B in a normal single page
When I insert and use the filter in the page such as for the search bar, it goes in conflict with the listing A in the top menu. I normally search and it doesnt work, if I get out the A listing from the menu everything works. My idea is to assign to the search tool a unique ID to set in the listing. so that is impossible to get in this trouble. Let me know if it's clear.
Thanks

**Comment by Floydtm** [comment]
@Gugutete, hi! You must associate the filter and listing with a unique id http://prntscr.com/re3vru http://prntscr.com/re3w19 then the filter will work with the desired listing
