### ISSUE TITLE
Dynamic Email for Elementor forms from options page

### ISSUE THREAD

**Issue by stasonua0** [Crocoblock/suggestions#997]
Hello, consider dynamically setting Email forms from Options Page from Jet Engine.
For example, your competitors were able to do this - https://www.dynamic.ooo/widget/dynamic-email-for-elementor-pro-form/

Здравствуйте, рассмотрите возможность динамически задавать формам Email из Options Page от Jet Engine. 
Например ваши конкуренты смогли это сделать - https://www.dynamic.ooo/widget/dynamic-email-for-elementor-pro-form/

**Comment by MjHead** [comment]
Done
