### ISSUE TITLE
Checkbox list filter | Possibility to collapse the main menu item

### ISSUE THREAD

**Issue by Gugutete** [Crocoblock/suggestions#998]
Hi there and thanks for your attention, we have several ecommerce with a sidebar and filters such as for everyone. We have a lot of product category and subcategories. The problem is that having so much categories we need a collapsable menu with the main categories that can expand and count the subcategories. At the moment seems not possible and we really urge of this! Thanks

**Comment by adrianratajczak** [comment]
Hi, any updates about that?

**Comment by MjHead** [comment]
Done
